### ISSUE TITLE
Make logging thread-safe

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#1002]
I just came here to report this little bug that happened to me to the first time, when starting the server:
https://hastebin.com/efehareqer.md

After rebooting, I saw this message:
```
[18:59:30 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1488)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
```
The errors magically 'fixed' in the second start.

* It happens quite often now, here are the new errors: https://hastebin.com/ayumiqirec.md

Well, the message said to report this, so I did.
Thanks again.

**Comment by bensku** [comment]
Do you use addons?

**Comment by TheBentoBox** [comment]
Can anyone else reproduce this? I've never seen this before and skript-yaml is appearing in some of the stack traces, so I'd be inclined to agree with bensku. If it was just a one-off error and nobody else is encountering it then this should be closed.

**Comment by Sashie** [comment]
ive seen this
`[18:59:30 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1488)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]`
but only on version dev25

**Comment by Sashie** [comment]
I have to head to work now but what i've found so far leads me to believe that its the AsyncEffect class, whether i use the one from my addon or the one from skript
tracing the error all the way back to 
`https://github.com/bensku/Skript/blob/83330d720a43a0139c4599804721ed989cf61235/src/main/java/ch/njol/skript/log/HandlerList.java#L32`
the issue thats happening is that the `LinkedList` is not syncronized so when using an AsyncEffect it can sometimes cause this issue.
