### ISSUE TITLE
Anvils in certain locations ignore click events

### ISSUE THREAD

**Issue by UltraFaceguy** [SkriptLang/Skript#1017]
I don't even know a better way to phrase it.

on right click:
    event-block is anvil:

on leftclick on anvil:

Both of the above simply... don't work in certain locations. It seems to be random? I can't seem to get it to react to freshly placed anvils at all, but about 80% of anvils that have been there for awhile work normally. I don't have issues with any other click events, just click events on anvils as far as I can tell.

No addons, no errors, using current version, etc etc. For users like myself this is an annoyingly large issue, as some people like myself make custom XP systems and block vanilla anvil usage completely :x

**Comment by Snow-Pyon** [comment]
I have seen this before and if I recall correctly, this  is an alias issue. The specific issue was that the `anvil` alias covers the data values `0` (North/South) and `1` (East/West) and not `2` (South/North) nor `3` (West/East), in addition to that, there is no specific alias for the anvil item nor an `any anvil` alias.

**Comment by Blueyescat** [comment]
Fixed on my pull request to tim740's aliases: https://github.com/tim740/skAliases/pull/9

You can use: [Blueyescat/.../aliases-english.sk](https://raw.githubusercontent.com/Blueyescat/skAliases/b9b8f80b8af2ec5099d4816e4dfefa21930b2252/aliases-english.sk) (replace everything in `/Skript/aliases-english.sk` with this)

Then make it **``on leftlick on anvil block``**

**Comment by Syst3ms** [comment]
Should this change in aliases be PR'd ? If not, then close.

**Comment by UltraFaceguy** [comment]
This fixes my issue, looks like some anvil combos were indeed left out. It should probably be PR'd.

**Comment by TheBentoBox** [comment]
Guess 'bug' is the correct label for this since it's a problem with the default aliases. @tim740 could you open a PR to fix this (or fix it on your repo then coordinate with Bensku)?

**Comment by bensku** [comment]
Gotta make sure this does not occur with new aliases when they're ready. Short-lived fix to old ones wouldn't hurt either.

**Comment by Blueyescat** [comment]
is it already fixed just update the default file
