### ISSUE TITLE
Selected hotbar slot expression

### ISSUE THREAD

**Issue by Luonline** [SkriptLang/Skript#1044]
# Feature request

Ability to check if the item in player's hand is in a specific item slot.

Ex:
- player is holding {_item} in slot 6

**Comment by TheBentoBox** [comment]
[Already implemented](http://bensku.github.io/Skript/expressions#ExprInventorySlot). Use `slot 6 of player's inventory`.

**Comment by TheBentoBox** [comment]
Closed cause I thought you were talking about something else #oops

What exactly are you asking to be able to do (since IMO that syntax doesn't make much sense)? Are you asking to be able to check which hotbar slot they have selected, or to be able to check what item is in a particular inventory slot?

**Comment by Luonline** [comment]
We have a plugin that sells the item you are currently holding. If the item a player is holding is in slot 6, we want to cancel the event. As slot 6 can be a gadget (something they shouldn't be able to sell). 
Re-reading my example it's terrible. I'll try to add a better one.

**Comment by TheBentoBox** [comment]
Alright, so you basically want a `selected hotbar slot` expression that you can check, correct? Something like `if player's selected hotbar slot is 6`?

**Comment by Luonline** [comment]
Yes that is correct

**Comment by TheBentoBox** [comment]
Sounds good, updated title to reflect that a bit better as well. I agree that this would make sense to have in vanilla Skript. For now if you're in dire need you could use SkQuery since it has this exact expression.

**Comment by Snow-Pyon** [comment]
> Sounds good, updated title to reflect that a bit better as well. I agree that this would make sense to have in vanilla Skript. For now if you're in dire need you could use SkQuery since it has this exact expression.

Give me 10 minutes.

**Comment by Blueyescat** [comment]
@Snow-Pyon Can be closed, but can you add **[s]** to the syntaxes? so "hotbar slot**s** of players"

**Comment by TheBentoBox** [comment]
Will close since it's fixed, Snow-Pyon should have your request via tag so if he agrees with the syntax change I'm sure he'll make the update. Thanks for the reminder!

**Comment by savoryninja1** [comment]
> # Feature request
> Ability to check if the item in player's hand is in a specific item slot.
> 
> Ex:
> 
> * player is holding {_item} in slot 6

index of player's selected hotbar slot
