### ISSUE TITLE
On npc attacking to erorr

### ISSUE THREAD

**Issue by Obliviated** [SkriptLang/Skript#1097]
ım coding a this skript but,when a zombie attacked me, error.

**This is the error:**
https://hastebin.com/madafuruwu.md

**This is my skript code:**
```
on damage:
	make citizen {soldiers.%victim%} look at location of attacker
	make citizen {soldiers.%victim%} attack attacker
	
command /soldier [<text>]:
	trigger:
		if {soldiers.%player%} is set:
			send "&7aa &8&n<command:/npc tphere>Tıkla<reset>"
		else:
			execute player command "npc sel"
			create a citizen named "%colored arg 1%" at player
			change citizen skin to "marcel01"
			set {soldiers.%player%} to last created citizen id
```

**My plugin versions:**
 Skript: Skript version 2.2-dev29
 Skrayfall: skRayFall version 1.9.10
 Citizens: Citizens version 2.0.22-SNAPSHOT (build 1487)
 SkQuery: SkQuery version 3.5.9a-Lime

**Comment by TheBentoBox** [comment]
This is very old, seemed to be add-on related, and the hastebin has expired, so I'm closing it.
