### ISSUE TITLE
loadStructures fail to load script - Simple bug fix

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#1099]
https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/ScriptLoader.java#L727

After looking at the source code for `loadStructure` and `loadStructures` I have found a potential loading issue that restricts scripts from loading due to a NullPointerException in the `Arrays.sort(files)` since the `files` contains 1 or less File objects, it throws a NullPointerException. Or it's caused because it's expecting an Array of File objects, but it gets a single File.

Suggestion Fix:

```java
public final static List<Config> loadStructures(final File directory) {
	if (!directory.isDirectory()) 
		return loadStructures(new File[]{directory});
	final File[] files = directory.listFiles(scriptFilter);
	Arrays.sort(files);
	
	List<Config> loadedFiles = new ArrayList<>(files.length);
	for (final File f : files) {
		if (f.isDirectory()) {
			loadedFiles.addAll(loadStructures(f));
		} else {
			loadedFiles.add(loadStructure(f));
		}
	}
	return loadedFiles;
}
```
This will prevent the null pointer error from happening and instruct a proper method to be called. Helps potential script loading fails.

Was also getting this error, not sure what produces it, but this stupid toString code is the main source, Spaghetti https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/ScriptLoader.java#L753
```
[04:14:57] [Thread-26/WARN]: java.lang.IllegalArgumentException: 'other' is different type of Path
[04:14:57] [Thread-26/WARN]: 	at sun.nio.fs.WindowsPath.relativize(Unknown Source)
[04:14:57] [Thread-26/WARN]: 	at sun.nio.fs.WindowsPath.relativize(Unknown Source)
[04:14:57] [Thread-26/WARN]: 	at ch.njol.skript.ScriptLoader.loadStructure(ScriptLoader.java:753)
```

Haven't tested since I can't compile Bensku's Skript fork without internal errors. So can someone test this fix out?

**Comment by bensku** [comment]
Directory parameter must actually be a directory. But I'll check what happens when an empty directory is passed - NPE is certainly possible.

**Comment by Snow-Pyon** [comment]
Marking this as enhancement since it is more of an user error rather than a bug.

**Comment by Nicofisi** [comment]
A NPE in `Arrays.sort(files)` can only occur when `files` is null which happens only when there is an IOException or when `directory` is not a directory, which is a developer error. But yeah, it's a bit confusing imo that to load the structure of one file you need to use the method which accepts an array of `File`s, so I guess what @TheLimeGlass suggests:
```java
	if (!directory.isDirectory()) 
		return loadStructures(new File[]{directory});
```
would be a good change indeed
