### ISSUE TITLE
StackOverflowError when the parser has to parse long lines (particularly ones with special characters)

### ISSUE THREAD

**Issue by Olyno** [SkriptLang/Skript#1117]
__Error:__

https://hastebin.com/iselokuron.bash

__Code:__

https://hastebin.com/witixexene.vbs

I was asked to report the error, so I'm reporting the error :)

**Comment by Snow-Pyon** [comment]
This is Skript's fault but it's just because in one of your scripts, there is a way long line. Once you reload again it *may* disappear, but the best solution is splitting it up or storing the value somewhere else

**Comment by Syst3ms** [comment]
(NB : I suggested reporting the error)

**Comment by xXAndrew28Xx** [comment]
You could try increasing the stack size via the `-Xss` flag (e.g `-Xss250M`).

**Comment by Nicofisi** [comment]
Could we possibly catch it somewhere and point the user to a specific line or is the place where the StackOverflowError is thrown too unpredictable?

**Comment by Syst3ms** [comment]
The place where this happens is very predictible, it's the parser. :^)

**Comment by TPGamesNL** [comment]
If anyone has this problem, they can try adding `-XX:MaxJavaStackTraceDepth=0` to their startup arguments, and send the stacktrace with that
