### ISSUE TITLE
A Bug about the Type Expression

### ISSUE THREAD

**Issue by Blueyescat** [SkriptLang/Skript#1123]
Looks like the object must be set at the parse time.

```vb

send "%type of stone%"
send "%type of ""stone"" parsed as item%"
send "%type of ""stone"" parsed as item type%"
#Returns: stone

set {_item} to stone
send "%type of {_item}%"
set {_text} to "stone"
send "%type of {_text} parsed as item type%"
#Returns: <none>
```

Happened on dev33, it was working on dev29. Didn't try dev30-dev32.

PaperSpigot 1.12.2-R0.1-SNAPSHOT

**Comment by xXAndrew28Xx** [comment]
Can't reproduce on Spigot 1.12.2-R0.1-SNAPSHOT with latest source (last commit: d74cb68).

**Comment by Snow-Pyon** [comment]
Can reproduce, probably not so easy to fix though.

**Comment by Blueyescat** [comment]
Works fine with Skript 2.3-beta1 on Paper 1.12.2 and 1.13.2, all return "stone block".
