### ISSUE TITLE
Skript Bug with metaid all doors

### ISSUE THREAD

**Issue by EncryptSL** [SkriptLang/Skript#1124]
Hello i found bug in script. Sometimes when i open menu in script. Script not visible door.

Example
`format slot 45 of player with spruce_door named "<- &9Back to MainMenu" to close then run [execute player command "/menu"]`

Bug in my vid.
https://youtu.be/6ur9mP7stp8

**Comment by HYPExMon5ter** [comment]
It’s not a bug, use `spruce door item`

**Comment by Pikachu920** [comment]
Maybe this issue should stay open, but not under this title. Skript should be smarter about whether an item or block should be given based on what the effect/expression expects/returns.  @bensku is something like this feasible for the new aliases system?

**Comment by Syst3ms** [comment]
That would touch the parser and you know how parser changes like that. They usually don't.
