### ISSUE TITLE
World reload causes worlds in location variables to not work correctly until restart

### ISSUE THREAD

**Issue by ghost** [SkriptLang/Skript#1144]
this has been a bug in Skript for a while, it would be nice if it would get fixed.
example:
you go to a world which isn't the main world, but an additional world created by world management plugins like Multiverse-Core or some other
you use !set {spawn} to location of player
then you unload and load back that world and do !teleport player to {spawn}, it will teleport to that location, but in the main server's world, not the one in which you set it
it can be fixed if you use !set world of {spawn} to "%world of {spawn}%" parsed as a world or if you restart the server it also gets fixed
it would be nice if it wouldn't break with world reloads, because I reload worlds for world resetting

**Comment by TheLimeGlass** [comment]
Putting this here for reference. I talked about this in https://github.com/bensku/Skript/issues/1020 but this is not a duplicate.

**Comment by TheBentoBox** [comment]
Thanks for the detailed info @TheLimeGlass. I agree it would be nice to fix this, but I imagine it only affects most users pretty rarely.

**Comment by Wealthyturtle** [comment]
From #341: Worlds that are not loaded before Skript is initialized cannot be accessed properly

**Comment by TheLimeGlass** [comment]
Yup

**Comment by TPGamesNL** [comment]
When #4408 is merged, this issue will be fixed with https://github.com/SkriptLang/Skript/issues/3971#issuecomment-836403090
