### ISSUE TITLE
Event "on tame" recongnizes wolves and ocelots, but doesn't the newer mobs (horses, donkeys, llamas, parrots)

### ISSUE THREAD

**Issue by Eryk1983S** [SkriptLang/Skript#1152]
**Engine:** Spigot 1.12.2.-R.0.1-SNAPSHOT
**Skript-Version:** 2.2. dev34

**Problem:**
Tamer's target is only recognized, if it's a wolf or a ocelot, but in case of a horse, a donkey, a llama or a parrot it doesn't return the target. Maybe it's so, because the event wasn't updated since v1.0. ?

**Description:**
Skript 1:
_on tame:
    cancel event
    send "Some message" to the tamer_

On each entity the taming is cancelled and I get the message. So far correct.

Skript 2:
_on tame:
    tamer's target is a wolf or a ocelot
    cancel event
    send "Some message" to the tamer_

The same results with wolves and ocelots. So far correct.

Skript 3:
_on tame:
    tamer's target is a horse
    cancel event
    send "Some message" to the tamer_

Here is the taming of a horse neighter cancelled nor I'll get any message. The same is with donkeys, llamas and parrots

**Comment by Blueyescat** [comment]
Your targeted entity doesn't mean the tamed entity, it is ``event-entity``.

**Comment by TheBentoBox** [comment]
Agree with @Blueyescat, you shouldn't be using` tamer's target` here since that will retrieve the entity you're looking at which won't necessarily be the tamed animal, especially in the case of a horse, donkey, or llama. Try replacing `tamer's target` with `event-entity` in all of those events and see if you still have the issue.

**Comment by Eryk1983S** [comment]
Thank you for your help. I didn't think about it, that after the taming an another entity can be spawned to replace the earlier (untamed) entity, especially that my formel works with the older mobs. I'll try your solution out and then will confirm in this thread, if it works, so that all others know it. But give me time to the evening before you close the thread, please.

**Comment by TheBentoBox** [comment]
Will do, no rush

**Comment by Snow-Pyon** [comment]
I've tested it with parrots and it did work correctly, could someone else verify it to be sure?
