### ISSUE TITLE
Improve loading speed of skripts using the custom resource pack sound effect?

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1171]
A skript with this effect takes very long time to reload:

play (resource|[custom ]sound) [sound] pack %string% to %player% [at %location%] [(and|with) volume %number%] [(and|with) pitch %number%]

This is from skrayfall addon. is there any way to improve the (re)loading time of a skript using this effect?

**Comment by Blueyescat** [comment]
Use [Skript's own Play Sound effect](https://skripthub.net/docs/?search=id:1121), i'm not sure about if it has parse issues too but should be better.
