### ISSUE TITLE
Skript timings commands should be removed now that timings run through Paper

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1175]
Hello
Im running the current Bensku 2.2 Dev34 skript plugin on a spigot 1.12.2 server, on a windows machine.
Everything works, except the /sk timings commands.
When I run them, absolutely nothing happens, no messages, nothing happens in the console, absolutely nothing.

**Comment by ShaneBolenback** [comment]
edit, I have also tried this on a mac computer as well.
Also... I tried it with paper spigot (as someone told me it does not work on spigot)
and same thing, the command returns absolutely nothing

**Comment by Blueyescat** [comment]
Skript's Timings support is moved to Paper timings directly. Enable [**this**](https://github.com/bensku/Skript/blob/master/src/main/resources/config.sk#L172) config option and run `/sk reload config`.

But i don't know why @bensku didn't remove the timings command.

**Comment by TheBentoBox** [comment]
Hijacking this issue to address the real problem here, which is the one @Blueyescat pointed out of the commands still existing even though Skript now uses Paper for timings. Not a huge deal but they should be removed at some point.

**Comment by Snow-Pyon** [comment]
Well, bensku did remove them, just that he forgot to remove them from the command help. I'll do it later.

**Comment by TheBentoBox** [comment]
This was listed as removed in the latest release (dev36).
