### ISSUE TITLE
new expression "colors"

### ISSUE THREAD

**Issue by FUZIK** [SkriptLang/Skript#1177]
```
hello, add "[all] colors" expression --> return all colors from lang file.
```
thanks

**Comment by TheLimeGlass** [comment]
There are only a few colours. You could make a custom aliases in your english-aliases.sk and then use `all colours` if you were to add it.

**Comment by TheBentoBox** [comment]
The aliases file is for items so I don't know if you could create an alias for colors. Regardless, I can see the benefit of this assuming you're correct in there not being a way to do so already, but as Lime said it would be very easy to solve yourself (such as by creating a list variable containing all colors) and it's also an issue that is rarely relevant, so it will be low prio.

**Comment by Snow-Pyon** [comment]
this could be expanded a bit and we could get something like `(all|every) %*classinfo%` which would be useful for this and other classinfos (types) that are enum values or could be get from the language files.

**Comment by TheLimeGlass** [comment]
https://github.com/TheLimeGlass/skquery/blob/master/SkQuery/src/com/w00tmast3r/skquery/elements/expressions/ExprValues.java

**Comment by Snow-Pyon** [comment]
@TheLimeGlass yeah, pretty much what I was talking about but this being "broader" since it could also try to parse values from the language files, something I'm pretty sure skQuery's expression does not.
