### ISSUE TITLE
SQLite is not working well?

### ISSUE THREAD

**Issue by peccator085** [SkriptLang/Skript#1193]
Log: https://pastebin.com/aiB8MgJY
Config: https://pastebin.com/UYDaRV0a
SQLibrary(7.1): https://dev.bukkit.org/projects/sqlibrary
SKQuery(3.6.0-Lime): https://www.spigotmc.org/resources/unofficial-skquery-fork-1-6-1-12.36631/

**Comment by peccator085** [comment]
Does it fail if UUID is used as a variable name?
Variable name used: 貢献値_A_.%player's uuid

**Comment by bensku** [comment]
Is the database file writable?

In any case, I would advise against using SQLite variable Storage. Because of #306 if nothing else.

**Comment by Snow-Pyon** [comment]
Try updating to SQLibrary 7.2 (an unofficial fork that works in 1.12.2). You can get it [here](https://skripttools.net/?q=SQlibrary).

**Comment by Nicofisi** [comment]
I think this could be closed? Specific to one user, and other issues mention that the whole sql backend requires a rewrite
