### ISSUE TITLE
NPE when clicking outside of an inventory

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#1207]
Error: https://hastebin.com/qepicalunu.md
If the hastebin expires here's a backup (https://pastebin.com/9JuGdnrX)
Code:
```
on inventory click:
    broadcast "%event-slot%"
```

**Comment by Snow-Pyon** [comment]
After testing for a while not being able to reproduce this bug, I happened to click outside of the inventory and there we go. Changed the title to reference the actual issue better.

**Comment by TheLimeGlass** [comment]
@HYPExMon5ter Which minecraft version are you using?

**Comment by HYPExMon5ter** [comment]
1.12.2

**Comment by TheLimeGlass** [comment]
Also the hastebin is dead, it may be hastebin having problems with their database again and will come back soon, or the link is dead.

**Comment by HYPExMon5ter** [comment]
i can try to find the error in my logs and upload it to pastebin instead

**Comment by bensku** [comment]
It is likely that I just fixed this, but you'll have to try with next release.
