### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#1210]
Sorry, didn't know what to call this, but bensku told me to create an issue for it, so that's what I'm doing.

Server Version: Spigot 1.12.2
Addons: None
Skript Version: dev33 and dev35

```
aliases:
	custom helmets = iron block, gold block, diamond block # Change this to anything you'd like

on inventory click:
	inventory action is place all or nothing
	cursor slot of player is custom helmets # Check if item is allowed as helmet
	event-slot is helmet slot of event-player # Check that player clicked the helmet
	cancel the event
	set {_old helmet} to helmet of player # Store old helmet
	set helmet of player to cursor slot of player # Set new helmet to item in player's cursor
	set cursor slot of player to {_old helmet} # Set player's cursor to old helmet, possibly air
```
this code doesn't work when it should.

**Comment by Nicofisi** [comment]
The thing is,
```
on inventory click:
    send "hello"
```
does literally nothing when you try to click with an **iron block** on the **helmet slot** for example, probably simply a Minecraft limitation since you can't *wear* a block in vanilla

**Comment by Pikachu920** [comment]
this is what we determined when i was dming hype about it, no click packets were sent

**Comment by bensku** [comment]
I'm pretty sure this used to work, but haven't checked if Minecraft changed.

**Comment by Nicofisi** [comment]
What do we do about this?

**Comment by bensku** [comment]
This appears to be working now on 1.13.
