### ISSUE TITLE
[Suggestion] Vault Economy Hook

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1217]
Hello

I feel like this has been talked about a few times in other places but I wanted to post this here. 
Would it be possible to add a hook into vault so someone could create their own Vault compatible economy?
I know that Skript would have to communicate with vault letting it knows its the "available economy plugin" - Maybe have an option in the config where it would tell vault its the default economy plugin?

I have seen multiple "Economy Skripts" out there, but the only problem is, they would only work with Skripts YOU write and not other plugins, such as JobsReborn and sever shop plugins.

Thank you for reading :)

**Comment by Pikachu920** [comment]
it's a bit hard conceptually but i could see it

**Comment by ShaneBeee** [comment]
Ill admit I dont know how you guys code all these great addons and this amazing .... but I believe in your guys ;) YOU HAVE THE POWER haha.... I have seen a few threads spread across the inter web and figured a lot of people would love this. I have seen sever "Economy Skripts" but the sad thing is, they won't work with Plugins, .... and anyone developing a Skript themselves would have to write it to MATCH the exact variable set by said eco plugin... and down the road if they wanted to change their eco skript.... they would not be able to, without re-writing all of their variables

**Comment by HYPExMon5ter** [comment]
Would be a great feature to add, would be pretty difficult though. Idk if bensku would be up for this being in Skript, and even so, it’d be low priority and wouldn’t be added for quite some time.

**Comment by Pikachu920** [comment]
its not really difficult coding wise, it is hard to find a nice way to implement it into skript (from a scripter's perspective). perhaps something like:
```
vault:
  money: {money::%player's uuid%}
```

**Comment by HYPExMon5ter** [comment]
True, maybe @bensku has an idea.

**Comment by ShaneBeee** [comment]
Couldn't it just be simple events? Like vault giving money and vault asking for money?
ie:
on vault send:  #sending money to the economy skript
    add event-value to {money::%player%} 
on vault request:
    remove event-value from {money::%player%} 

Something along those lines?

**Comment by Blueyescat** [comment]
As far as i know bensku doesn't accept that, if editing player permissions isn't accepted, this shouldn't be too.

**Comment by Pikachu920** [comment]
@ShaneBee a system like that would cause more issues than it fixes

**Comment by TheLimeGlass** [comment]
Users create script variable based economic because Skript doesn't hook with the latest Vault, and some users need the latest Vault due to other plugins. So users resort to a working alternative. I haven't tested if what Pikachu changed with the vault hook like 1-2 versions ago fixes this or if the whole thing is broken.

**Comment by Snow-Pyon** [comment]
@TheLimeGlass Skript has always worked with latest Vault, I don't know why it didn't work for you but I tested it recently and it worked perfectly fine.
