### ISSUE TITLE
bug comparing variables when variables have spaces in their name

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#1243]
Version: PaperSpigot 1.12.2
Skript: dev35b

So upon further testing, I figured out that, well I had the on death where it resets the kills for that life as the attacker, not the victim, so that's fixed now, but the check to see if the kills for that life is greater than the kill streak doesn't work when there's spaces in the variable names.

Working code: https://pastebin.com/cG36kg4R
![image](https://user-images.githubusercontent.com/12315186/39675558-ca5dd0c4-512a-11e8-96d6-2a232482a2f4.png)

Semi-Working code: https://pastebin.com/94hZgpfV
![image](https://user-images.githubusercontent.com/12315186/39675573-feca17f0-512a-11e8-8e89-b599cb4dbd8f.png)

**Comment by HYPExMon5ter** [comment]
has anyone else tried replicating this?

**Comment by HYPExMon5ter** [comment]
@bensku have you tried replicating this?

**Comment by HYPExMon5ter** [comment]
I was told to use the variables system by bensku https://github.com/SkriptLang/Skript/pull/1205/files/13199a48c12267c6a823f12a5bca8f3c668faefc#r183301939 so idk

**Comment by TheLimeGlass** [comment]
Actual cause is default variables https://github.com/SkriptLang/Skript/issues/2174
