### ISSUE TITLE
[suggestion] search on doc site

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1253]
Hi @bensku 

I would just like to suggest adding a search function on your [doc site](http://bensku.github.io/Skript/) if you can. I find a few times I dont know where to look exactly, and i feel like im a semi-smart skripter, but this may be SUPER helpful for all the skripters who have no clue whether to look for an event/expression/effect/etc

Thanks for reading :)

**Comment by TheBentoBox** [comment]
Not a bad idea. Just in case you don't know, you can do CTRL + F on a web page to open up a search bar which lets you type to find instances of the text you enter on the page. Could help you in the future!

**Comment by ShaneBeee** [comment]
Oh yeah, I already do that, but i just meant for the odd times when you are looking for something and dont know which section to look in.

**Comment by bensku** [comment]
Docs site needs some polishing in general. Search across all pages could be implemented client-side usinh Javascript, perhaps.

**Comment by APickledWalrus** [comment]
Completed in https://github.com/SkriptLang/Skript/pull/3935
