### ISSUE TITLE
'::*} split at "||"' is not a valid item data

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1254]
Error when loading/reloading the script:

`'::*} split at "||"' is not a valid item data (mytest.sk, line 138: set {_verynewlore::*} to {_newlore::*} split at "||"')`

```
set {_newlore::*} to "&0Rüstung: %{_rpname}%||%{_lore::*}%"
set {_verynewlore::*} to {_newlore::*} split at "||"

```

Latest release of skript

**Comment by KingAlterIV** [comment]
``set {_verynewlore::*} to split {_newlore::*} at "||"``

**Comment by bloggy** [comment]
Did the syntax change?

**Comment by bensku** [comment]
Does this happen without addons?

**Comment by bloggy** [comment]
The syntax is actually working for me. I use it in all of my scripts. But yeah you are right. I should not split a list variable as it seems not to be working this way.

**Comment by Snow-Pyon** [comment]
@bensku it doesn't come from an addon, Skript has issues with patterns that start with a string like this one, the same happens for the parse expression.

**Comment by TheBentoBox** [comment]
The `%string% split by %string%` expression doesn't seem to work well with string literals. I'm pretty sure I remember reading somewhere that using the alternate syntax `split %string% by %string%` _does_ work with literals, for some reason. I've used that as a "workaround" on my server before but I'm not sure if that's still the case.

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/719

And adding support for lists is stupid, if this error is still kept as open, then make a better error message.
