### ISSUE TITLE
How to convert variables stored in a CSV file to SQLite

### ISSUE THREAD

**Issue by Baw-Appie** [SkriptLang/Skript#1256]
My server was experiencing a server hangup every 5 minutes, and I found that this was a problem with Skript.
However, there was no .sk file with a run every 5 minutes, and I thought this was a problem with the script's variable storage.

So I want to convert a CSV type variable to a SQLite type variable.
But I can not find a way to do it.
Can you help me?

(I'm sorry I did not speak English)

**Comment by Baw-Appie** [comment]
Then, do you know why the variable.csv.temp file is created every five minutes?

**Comment by xXAndrew28Xx** [comment]
@bensku https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/variables/FlatFileStorage.java#L229-L244
Here is how it converts it to a string when saving as CSV. Maybe run `decode` on the strings, then insert them into SQL.

**Comment by TheLimeGlass** [comment]
If you create a new database and define the pattern to be the same as the CSV/default all new variables will be on both databases and any existing ones that are used will be transferred over to both databases. The only problem will be getting all the variables that aren't always used such as player variables and world variables.

Skript might actually transfer all the values over to the SQLite database, I have never really wanted to transfer all the same values over, but I have used multiple databases before.
