### ISSUE TITLE
Feature request: suppress specific warns for specific skript

### ISSUE THREAD

**Issue by JustDylan23** [SkriptLang/Skript#1260]
Target Minecraft versions: any
Requirements: none
Related issues: none

Proposed syntax:
`Suppress warns:`
`   variable.conflict`
`   variable.save`
(the text editor wouldn't indent it for some reason)

Description:
It would be nice if it was possibility to supress warns in the skript where this suppress warns event is used in. Although warnings are usefull most of the times, sometimes they can get in the way of people. for example when they post their skript and it gives a bunch of variable conflict warns to the person who downloaded it while the variables aren't causing any probems. some people might not now how to disable the thing in the config. it isn't useful anymore due to how addons implemented the variable pattern for their types.

**Comment by TheBentoBox** [comment]
There's a newly opened PR which adds this, though not with the exact proposed syntax. If it gets merged 
 soon it should be in before the next release.
