### ISSUE TITLE
Bug with list variables

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#1262]
This does not work cause i use the same name for list and normal variable
```
command /why:
    trigger:
        set {_i::*} to "1", "2" and "3"
        broadcast "a) %{_i::*}%"
        set {_i} to a random element out of {_i::*}
        remove {_i} from {_i::*}
        broadcast "b) %{_i::*}%"
```

But if you replace "{_i}" by another name, it's working !
So we can see a conflict between variable's names

**Comment by Blueyescat** [comment]
✅ I confirmed with Skript 2.2-dev35b and PaperSpigot 1.12.2.

**Comment by TheBentoBox** [comment]
Is this a new bug? I'm putting it as low priority for now since it's probably a pretty rare bug and one that's easy to fix but it could also be difficult to track down and if it's a new issue it could break old scripts in which case it should be higher prio.

**Comment by Pikachu920** [comment]
yeah, it is
![image](https://user-images.githubusercontent.com/28607612/40256647-c3430aae-5ab0-11e8-8f1f-017d464a53ca.png)

**Comment by TheBentoBox** [comment]
Thank you, gonna up the prio then since this could break old scripts which worked on previous versions (though it's still a pretty rare edge case). One of the main devs can lower again if they don't see it as being as big of an issue.

**Comment by bensku** [comment]
Very interesting bug... With assertations enabled, it seems even more troubling. Null variable name could break stuff.

**Comment by Blueyescat** [comment]
@Pikachu920 You didn't understand the bug ^^
