### ISSUE TITLE
Nao esta funfando o skript na verçao 1.12.2 já tentei varias verçoes

### ISSUE THREAD

**Issue by SroMeliodas** [SkriptLang/Skript#1266]
20.05 16:39:28  [Servidor]  ERROR #! #! em net.minecraft.server.v1_12_R1.PlayerConnectionUtils $ 1.run (SourceFile: 13)
 20.05 16:39:28  [Servidor]  ERROR #! #! em net.minecraft.server.v1_12_R1.PacketPlayInChat.a (SourceFile: 9)
 20.05 16:39:28  [Servidor]  ERROR #! #! em net.minecraft.server.v1_12_R1.PacketPlayInChat.a (SourceFile: 37)
 20.05 16:39:28  [Servidor]  ERRO #! #! em net.minecraft.server.v1_12_R1.PlayerConnection.a (PlayerConnection.java:1198)
 20.05 16:39:28  [Servidor]  ERROR #! #! em net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand (PlayerConnection.java:1338)
 20.05 16:39:28 [Servidor]  ERRO #! #! em org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand (CraftServer.java:629)
 20.05 16:39:28  [Servidor]  ERROR #! #! em org.bukkit.command.SimpleCommandMap.dispatch (SimpleCommandMap.java:140)
 20.05 16:39:28  [Servidor]  ERROR #! #! em org.bukkit.command.PluginCommand.execute (PluginCommand.java:44)
 20.05 16:39:28  [Servidor]  ERROR #! #! em ch.njol.skript.SkriptCommand.onCommand (SkriptCommand.java:187)
 20.05 16:39:28  [Servidor]  ERROR #! #! em ch.njol.skript.ScriptLoader.loadScripts (ScriptLoader.java:267)
 20.05 16:39:28  [Servidor]  ERRO#! #! em ch.njol.skript.ScriptLoader.loadScripts (ScriptLoader.java:243)
 20.05 16:39:28  [Servidor]  ERROR #! #! em ch.njol.skript.ScriptLoader.loadScript (ScriptLoader.java:409)
 20.05 16:39:28  [Servidor]  ERROR #! #! em ch.njol.skript.command.Commands.loadCommand (Commands.java:370)
 20.05 16:39:28  [Servidor]  ERROR #! #! em ch.njol.skript.registrations.Classes.getClassInfoFromUserInput (Classes.java:335)
 20.05 16:39:28  [Servidor]  ERROR #! #! em ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction (Classes.java:240)
 20.05 16:39:28  [Servidor]  ERRO#! #! java.lang.IllegalStateException: Não é possível usar classinfos até o registro terminar em
 20.05 16:39:28  [Servidor]  ERROR #! #! Rastreamento de pilha:
 20.05 16:39:28  [Servidor]  ERROR #! #! 
20.05 16:39:28  [Servidor]  ERROR #! #! Seguindo este guia, a correção do erro deve ser fácil e rápida.
20.05 16:39:28  [Servidor]  ERROR #! #! Se você acha que é um gatilho que está causando o erro, poste também o gatilho.
20.05 16:39:28  [Servidor]  ERROR #! #! e descreva o que você fez antes de acontecer e / ou o que você acha que causou o erro.
20.05 16:39:28  [Servidor]  ERRO#! #! Se não, por favor crie um novo ticket com um título significativo, copie e cole todo este erro nele (ou use o serviço de colar),
 20.05 16:39:28  [Server]  ERROR #! #! e verifique se esse erro já foi relatado.
20.05 16:39:28  [Servidor]  ERROR #! #! Se você é um administrador de servidores, por favor vá para https://github.com/bensku/Skript/issues/
 20.05 16:39:28  [Servidor]  ERROR #! #! Se você está desenvolvendo um add-on para o Skript, isso provavelmente significa que você fez algo errado.
20.05 16:39:28  [Servidor]  ERROR #! #! 
20.05 16:39:28  [Servidor]  ERROR #! #! Não foi possível carregar o GrimmAnunciar.sk
20.05 16:39:28  [Servidor]  ERROR #! #! [Skript] grave erro:
 20.05 16:39:28  [servidor]  ERROR #! #!

**Comment by Pikachu920** [comment]
can you post the stacktrace in english?

**Comment by Snow-Pyon** [comment]
Don't use `/reload`. And try to translate the report next time.

**Comment by Snow-Pyon** [comment]
No response, closing.
