### ISSUE TITLE
MySqll problem

### ISSUE THREAD

**Issue by wohahobg** [SkriptLang/Skript#1267]
Hello there! I am using Skript from long time but always have a problem with MySqll
so here is my config: [redacted]
and here is error which didnt stop spam all console is like that.

`21.05 03:05:20 [Server] INFO Loaded 0 variables so far...
21.05 03:05:21 [Server] INFO Loaded 0 variables so far...
21.05 03:05:22 [Server] INFO Loaded 0 variables so far...
21.05 03:05:23 [Server] INFO Loaded 0 variables so far...
21.05 03:05:24 [Server] INFO Loaded 0 variables so far...
21.05 03:05:25 [Server] INFO Loaded 0 variables so far...
21.05 03:05:26 [Server] INFO Loaded 0 variables so far...
21.05 03:05:27 [Server] INFO Loaded 0 variables so far...
21.05 03:05:28 [Server] INFO Loaded 0 variables so far...
21.05 03:05:29 [Server] INFO Loaded 0 variables so far...
21.05 03:05:30 [Server] INFO Loaded 0 variables so far...
21.05 03:05:31 [Server] INFO Loaded 0 variables so far...
21.05 03:05:32 [Server] INFO Loaded 0 variables so far...
21.05 03:05:33 [Server] INFO Loaded 0 variables so far...
21.05 03:05:34 [Server] INFO Loaded 0 variables so far...
21.05 03:05:35 [Server] INFO Loaded 0 variables so far...
21.05 03:05:36 [Server] INFO Loaded 0 variables so far...
21.05 03:05:37 [Server] INFO Loaded 0 variables so far...
21.05 03:05:38 [Server] INFO Loaded 0 variables so far...
21.05 03:05:39 [Server] INFO Loaded 0 variables so far...
21.05 03:05:40 [Server] INFO Loaded 0 variables so far...
21.05 03:05:41 [Server] INFO Loaded 0 variables so far...
21.05 03:05:42 [Server] INFO Loaded 0 variables so far...
21.05 03:05:43 [Server] INFO Loaded 0 variables so far...
21.05 03:05:44 [Server] INFO Loaded 0 variables so far...
21.05 03:05:45 [Server] INFO Loaded 0 variables so far...

> 
> 21.05 03:05:46 [Server] INFO Loaded 0 variables so far...
> 21.05 03:05:47 [Server] INFO Loaded 0 variables so far...`

**Comment by wohahobg** [comment]
someone will help me :(

**Comment by bensku** [comment]
You have enabled two MySQL variable storages on one database. That might be causing some issues.

That being said... Posting database passwords publicly is a really stupid idea. I have removed the link to config from your post. If you wish to post the config *without* sensitive information, feel free to do so.

I also recommend that you get rid of the original paste and change database password immediately.

**Comment by wohahobg** [comment]
Hello there! What's that mean!?  Which one is the real MySqll? 
Down from this:
		# == MySQL configuration ==

or 2nd one? which one i should to stop.

And yes i really didnt think abaout mysqll info xDD I have change my password already yest.

**Comment by wohahobg** [comment]
I have change Its like that:
https://gist.github.com/wohahobg/c6bec309f03b110340556cf9bd24b732
its right way ?

**Comment by wohahobg** [comment]
bump+

**Comment by Pikachu920** [comment]
Github issues aren't like forums... you just make the issue and it will be looked at eventually, if ever.

**Comment by TheLimeGlass** [comment]
Directing to https://github.com/SkriptLang/Skript/issues/3948
