### ISSUE TITLE
Bug: color coding bug

### ISSUE THREAD

**Issue by JustDylan23** [SkriptLang/Skript#1269]
there are some color coding issues that occured when I did the following things.
> /sk reload test

the file named test did not exist in my scripts folder, it was actually named -test so skript tried to tell me that. but the message contained some color coding issues. I expect this will be fixed in the next update, here is what I saw in the chat.
> `[19:41:26 ERROR]: Invalid format string at 'skript command.reload.script disabled' in the english language file: <gold>%s<reset> is currently disabled. Use <gray>/<gold>skript <cyan>enable <red>%s<reset> to enable it.`

**Comment by Snow-Pyon** [comment]
I thought this bug was fixed already, looks like it isn't the case.

Also, you don't expect something to be fixed/added for the next release  no matter how complex the issue is. We'll fix it as soon as possible.

**Comment by Dylan123111** [comment]
Sorry for that, I did sound kind of dickish. What I meant to say is that I hope you will fix it in the next update because for as far as I am aware it won't take to much effort.

**Comment by HYPExMon5ter** [comment]
Well, it’s not a breaking change, it’s just a visual bug you barely see, so it’s not really a priority as there are much bigger problems that need to be fixed right now

**Comment by TheBentoBox** [comment]
To be closed when a release containing this fix is published.

**Comment by Matocolotoe** [comment]
Whoops, will change the PR name next time xd
