### ISSUE TITLE
Suggestion: Event is cancelled condition

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#1271]
Title says it all, Skellett has this condition, but I don't see why it's not in vanilla Skript.

**Comment by Pikachu920** [comment]
It does exist in skriptas an expression: https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprEventCancelled.java

but yeah it should be made into a condition

**Comment by bensku** [comment]
It doesn't have docs, that's why. Interesting...

**Comment by HYPExMon5ter** [comment]
Oh that’d explain why I couldn’t find it lol
