### ISSUE TITLE
set slot 0 of player's current inventory to {_item}

### ISSUE THREAD

**Issue by PheonBest** [SkriptLang/Skript#1272]
Hi !
I guess "set slot" effect is a skript's effect (and not an addon's effect) because of I don't find it on SkUnity.
I can't use a variable when using "set slot" effect:
`set {_item} to yellow stained glass pane
#set {_item} to {_item} parsed as item
set slot 0 of player's current inventory to {_item} named " "`

error exemple: `[Skript]`` a slot can't be set to {_item} named " " because the latter is neither an item type nor an item stack (Cake GUIV3.sk, line 594: set slot {_list::%{_start}%} of player's current inventory to {_item} named " "')`

Thanks for your work :)

**Comment by Snow-Pyon** [comment]
Duplicate of #1138.
