### ISSUE TITLE
Name of local variable parsed as global variable

### ISSUE THREAD

**Issue by 4rnoP** [SkriptLang/Skript#1275]
if the underscore (specific to local variables) is brought by an expression or another variable, then the variable will be global, not local.
Example:
```
command /test <text>:
	trigger:
		set {_test} to "_localvariable"

		send "Before: %{%{_test}%}%"
		set {%{_test}%} to arg-1
		send "After: %{%{_test}%}%"
```
Just run this command twice, and the second message "Before: ..." will have an value (I also checked in variable.csv, the variable "_localvariable" is set).

**Comment by Pikachu920** [comment]
It is intended that expressions cannot change the "type" of a var, e.g.
```
set {_l} to "::*"
broadcast "%{var%{_l}%}%" # this isn't going to make {var::*}
```
so I guess it should be ignored and do nothing in this case, too

**Comment by Snow-Pyon** [comment]
A note though, you shouldn't use variables in such way, Skript even warns you about starting variable names with a expression and it is for a good reason.

**Comment by Vrganj** [comment]
If you must to use something like this, you could use eval.

**Comment by TheLimeGlass** [comment]
A value should not be able to modify the properties of a variable. This can be a security issue. Skript already warns about it, it should really be erroring.

**Comment by TheLimeGlass** [comment]
Waiting on my fix default variables pull request before I start on this.

**Comment by Moderocky** [comment]
I think there's an inherent security risk to treating this as a bug (where the intended behaviour is for the expression to modify the type of variable it is)

If a script ever has a variable where user-input is included in part of the variable name (e.g. something like `set {var::%arg-1%} to true` then the user could get almost unlimited access to the variable sub-tree in a way that is unexpected and shouldn't really be the script-maker's responsibility to have to worry about.

**Comment by Moderocky** [comment]
I'm going to close this since the part of this that was considered a bug seems to be intended behaviour and by general consensus what's being asked for shouldn't be added.

If there is an issue with the resolution order of expressions inside a variable name string then that probably needs its own specific issue ticket (and a discussion of what the correct order should actually be?)
