### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by SiriuSKR** [SkriptLang/Skript#1276]
- null expression ( if variable set to null, that variable will be delete )
 - yaml features ( node keys, list, value, etc... )
 - global variable ( variables that are automatically deleted when the server is turned off, like this: {!var} )

thank you for reading.

**Comment by HYPExMon5ter** [comment]
2 prob won’t be added and 3 has already been suggested, and 1 you can make yourself, so prob won’t be added either.

**Comment by SiriuSKR** [comment]
Why does not 2 added? How can I make 1 myself? @HYPExMon5ter

**Comment by HYPExMon5ter** [comment]
Cause you can just use skript-yaml, and this isn’t the place to ask for help. Use one of the various Skript discords or the forums for help.

**Comment by Snow-Pyon** [comment]
1. Just delete the variable.
2. No, Skript won't have any I/O feature, for many reasons.
3. This is already possible. See #1049 for more info.

**Comment by SiriuSKR** [comment]
Thank you for answer. @Snow-Pyon , @HYPExMon5ter 
However, I think you need a null expression to use various ExprTernary functions added at this time.

**Comment by Snow-Pyon** [comment]
You can treat an unset variable as null, not pretty but I'd prefer that over a null reference in Skript.

**Comment by HYPExMon5ter** [comment]
^

**Comment by SiriuSKR** [comment]
global variable is not cleared even after the server is turned off @Snow-Pyon
