### ISSUE TITLE
Feature request: Post/pre incrementation expression

### ISSUE THREAD

**Issue by Dylan123111** [SkriptLang/Skript#1277]
Targeted version: latest
Related issues: none
proposed syntax:
`[++|--]%number%[++|--]`

I am going to show how you can do this in the current version of skript and how you should be able to do it using my syntax.
```
#current way to pre increment
loop 10 times:
	set {_int} to {_int} + 1
	broadcast "%{_int}%"
#current way to post increment
set {_int} to 0
loop 10 times:
	broadcast "%{_int}%"
	set {_int} to {_int} + 1

#the way to increment I that proposed
#pre incrementing
loop 10 times:
	broadcast %++{_int}%
#post increment'
#pre incrementing
loop 10 times:
	broadcast %{_int}++%
```

**Comment by Pikachu920** [comment]
I see no issue with the current:
```vb
loop 10 times:
  broadcast "%loop-number%"
```

**Comment by Dylan123111** [comment]
I messed up the syntax here is an improved version:
`<[++|--]%number%|%number%[++|--]>`
This should be more flawless.
The point of this is not only to work for loops such as loop 10 times but also for while loops.

**Comment by Snow-Pyon** [comment]
Skript is supposed to be an English like language, what you proposed there is literally Java within a script. I don't really ser how this would actually be better than just adding 1 to the variable in the following way:
``vb
add 1 to {_int}
```
It doesn't provide any actual advantage, just syntax sugar that doesn't really fit into Skript. 

I'm just closing the issue since I don't support the idea at all, thanks for the suggestion though.
