### ISSUE TITLE
Add proper support for entity name visibility

### ISSUE THREAD

**Issue by melinstagibson** [SkriptLang/Skript#1279]
It appears i can't name a armor stand without naming it with a nametag first.

So i have a command that does

```
set name of target entity to "string"
```
but if i use this command on an armor stand the nametag wont pop up above it. it works with animals etc just fine.
when used on an armor stand i first have to name it with a nametag item and after that is done (text appears above it) i can change its name with my /name command, otherwise the name will be invisible to the players but still corerrectly set when called by something like ``` send "%name of clicked entity%"```

im not even sure if this is a skript issue but it would be nice to see a fix

**Comment by Blueyescat** [comment]
You should change this issue to suggestion to add custom name visible stuff ^^

```vb
send "%custom name visibility of target entity%"
set name visibility of target entity to off

show custom name of target entity
hide name of target entity
```

**Comment by bensku** [comment]
That would be ideal to have as part of Skript, indeed.

**Comment by Snow-Pyon** [comment]
I would rather have a different behaviour when setting the name and the display name (custom name visible when setting the display name only)

**Comment by Pikachu920** [comment]
renaming this issue to reflect more what is really needed in this case, a quick list for things skript needs

- Custom name enable/disable support and conditions

- AI enable/disable support and conditions

- Gravity enable/disable support and conditions

- Marker enable/disable support and conditions

if possible, these would not be implemented as expressions because expressions for these types of things are usually pretty ugly

**Comment by bensku** [comment]
Adding new conditions is to be avoided. In future, they might be removed or their functionality might be substantially changed.

**Comment by Blueyescat** [comment]
using `display name` runs `setCustomNameVisible(true)`

**Comment by AyhamAl-Ali** [comment]
> using display name runs setCustomNameVisible(true)

I guess this fixes the issue

**Comment by TheLimeGlass** [comment]
Closing in favour of https://github.com/SkriptLang/Skript/issues/4185
