### ISSUE TITLE
1.7.10 Skript issue. 

### ISSUE THREAD

**Issue by XinesMC** [SkriptLang/Skript#1281]
I switched my game to 1.8 and changed all the libraries to UUID, meaning now whenever I open Skript [1.7.10] along with my 1.7.10 Server, it does not complete the start.

Any way to fix this?
There is no error message or anything

**Comment by TheBentoBox** [comment]
This isn't the place to report errors with old versions of Skript and we do not support 1.7.

**Comment by bensku** [comment]
Note that recent Skript versions intentionally refuse to load on 1.7.10. I know they wouldn't work properly even if they loaded.
