### ISSUE TITLE
Documentation for new update?

### ISSUE THREAD

**Issue by UzumakiYT** [SkriptLang/Skript#1282]
there is no documentation on skunity for the new update and i cannot find bensku documentation site anymore(is deleted?) is there any docs for the new update?

**Comment by Snow-Pyon** [comment]
https://skriptlang.github.com/Skript

**Comment by UzumakiYT** [comment]
404
There isn't a GitHub Pages site here.

**Comment by TheBentoBox** [comment]
@Snow-Pyon gave a slightly incorrect link, it's here: http://skriptlang.github.io/Skript/

In the future, you should simply check the release logs or the readme. The updated documentation link is in the readme already so you wouldn't have had to make this issue if you had checked there.
