### ISSUE TITLE
Ternary only works with a single string

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#1283]
I've been using the new ternary feature (it's amazing), but I'm having this problem:

`set {_a} to "abc" if {_a} is set else "cba"`
```
Can't understand this expression: '"abc" if {_a} is set else "cba"' (^API.sk, line 18: set {_a} to "abc" if {_a} is set else "cba"'))
```

The ternary seems to only work when using a single `""` string. It works fine using loop-value or variables, though.

Hope this can be fixed soon.
Thanks!

**Comment by Blueyescat** [comment]
This issue isn't about the ternary expression, explained here: https://github.com/SkriptLang/Skript/issues/719
