### ISSUE TITLE
Bug: using where statement in loop and remove effect from loop entity

### ISSUE THREAD

**Issue by JustDylan23** [SkriptLang/Skript#1284]
I just updated my skript to the latest release and I got tons of errors, they all were about one specific thing,
trying to remove a potion effect from a looped entity, where the loop contained a where statement.
I will show the error and the code:
```vb
on right click:
    remove slowness from all entities in radius 5 of player where [input isn't player]
```
this cause the following error:
`
all entities of types entity in radius 5 around the player where [entity isn't player] can't have anything removed from it (test.sk, line 2: remove slowness from all entities in radius 5 of player that match [entity isn't player]')`
the moment I remove the where statement the error will no longer occure, although this shouldn't happend, maybe this can break more stuff than only this. I hope you have an understanding of the issue and will be able to fix it.
- Dylan

**Comment by Pikachu920** [comment]
My initial guess is that this has to do with the generic stuff that goes on for object return types causing issues when Skript tries to determine the changer. Fix is probably making the return type the return type of the object expr?
