### ISSUE TITLE
Backup is not normally performed when setting up a Variable Store with SQLite

### ISSUE THREAD

**Issue by Baw-Appie** [SkriptLang/Skript#1286]
When you set up a Variable Store as SQLite, the newly added Variable is not backed up at the time of backup, and only the last saved Variable is copied.

![kakaotalk_20180602_162056037](https://user-images.githubusercontent.com/15670271/40873562-7f2947c2-669d-11e8-8b60-c51d83864b72.png)

**Comment by TheLimeGlass** [comment]
@Baw-Appie Just out of curiosity have you tested other databases? Like MySQL or Flatfile?

**Comment by Baw-Appie** [comment]
Fixed by using SQLite with MySQL.

Running the server for a long time did not save the variable, and the /stop command did not stop the server and the variable was not saved.
