### ISSUE TITLE
Parse variables in strings

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#1288]
Hi.
I'm suggesting this because Skript seems to have no easy way to parse variables inside strings.

I made this function for that:
```
function replacewith(t: text, r: text) :: text:
	set {_r::*} to (split {_r} at "|") ? {_r}
	loop {_r::*}:
		set {_s::*} to split loop-value at ";"
		replace all {_s::1} with {_s::2} in {_t}
	return colored {_t}
```
Example:
`replacewith({variable}, "<stringone>;%var/text%|<stringtwo>;%var/text%"`
However, it's incredibly slow, as it takes about 10 extra milliseconds when compared to `options:`.

It'd be nice to have either an expression like mine, but with high performance, or a variable* parser.
Example:
```
parse (variables|vars) (from|for) %text%
or
replace args (from|for) %text% (with pattern|using) %text%=%othertext%|%text2%=%othertext2%
```

Hope this can be implemented.
Thanks!

**Comment by Pikachu920** [comment]
if anything would be added, it would be an expression parsing expression, and even then I don't think it should be in vanilla for the same reason evaluate isn't in vanilla - people are going to use it in dumb ways that end up causing vulnerabilities.

**Comment by Blueyescat** [comment]
Doesn't need that advanced things lol, this is wat i gave to someone before:
```vb
loop groups 1 of {_text} matched to "{(.*)}":
    replace all "{%loop-value%}" with "%{%loop-value%}%" in {_text}
```
Uses skQuery.

**Comment by TrademarkTM** [comment]
The problem is not that it's hard to do, but rather slow.
You can't use it when replacing many variables, because it takes almost 0.5ms each.

Instead of taking the usual 6ms (using normal variables), it takes 20ms or more to do the same thing.
For me it's totally unreliable, as it would completely destroy my timings.

**Comment by Blueyescat** [comment]
@TrademarkTM 
![image](https://user-images.githubusercontent.com/19474570/40932592-83d11836-6837-11e8-8441-f14b7e13cbab.png)
