### ISSUE TITLE
Enchantments of item expression returning a single value

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#1289]
**Info:**
Skript Version: dev36
Server Version: 1.12.2 PaperSpigot

**Issue:** The enchantments of an item expression returns a single value which means you can't loop it and you can't get the size of it.

**Comment by bensku** [comment]
@Snow-Pyon Time for hotfix.

**Comment by Pikachu920** [comment]
workaround: `loop enchantments of player's tool and {_empty}:`

**Comment by TheLimeGlass** [comment]
We should add a tag signifying that issues have been dealt with and that it will be added/fixed in the next update.

Or this should be closed. Either or.

**Comment by Snow-Pyon** [comment]
@TheLimeGlass I'd say referencing the issue in the commit is good enough. But a label could be good too.
