### ISSUE TITLE
Script names aren't case-sensitive anymore

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#1292]
Skript version: dev33
OS: Linux
Console log:
```
05.06 00:27:18 [Server] INFO [Skript] Successfully reloaded new_update_stuff.sk. 
05.06 00:27:18 [Server] INFO loaded 1 trigger and 0 commands from 'new_update_stuff.sk' 
05.06 00:27:17 [Server] INFO [Skript] Reloading new_update_stuff.sk... 
05.06 00:27:08 [Server] INFO [Skript] Can't find the script 'NEW_update_stuff' in the scripts folder!
```
Scripts folder: 
![image](https://user-images.githubusercontent.com/12315186/40955438-0b54c04e-6858-11e8-80a9-6ef908d664d9.png)

------------------------------------------------------------------

Skript version: dev36
OS: Windows
Console log:
```
> skript reload Test
[00:22:05 INFO]: [Skript] Reloading Test.sk...
[00:22:05 INFO]: [Skript] Successfully reloaded Test.sk.
> skript reload test
[00:22:14 INFO]: [Skript] Reloading test.sk...
[00:22:14 INFO]: [Skript] Successfully reloaded test.sk.
```
Scripts folder: 
![image](https://user-images.githubusercontent.com/12315186/40955410-dee9b4ce-6857-11e8-84bf-865d7233ab9b.png)

**Comment by Pikachu920** [comment]
what

**Comment by HYPExMon5ter** [comment]
updated, accidentally hit enter lol

**Comment by Pikachu920** [comment]
is this a bad thing?

**Comment by HYPExMon5ter** [comment]
idk, for some people it might be, it doesn't affect me though.. just didn't know if this was intended or what, cause that's not how it used to be.

**Comment by TheBentoBox** [comment]
I don't see this as an issue personally but I think that's more of a decision for the devs

**Comment by HYPExMon5ter** [comment]
Yeah, I think non case sensitive is actually better, makes it easier to type in lol, but just was surprised and thought I'd make an issue if it wasn't intentional

**Comment by TheBentoBox** [comment]
I agree, definitely worth reporting just to make sure.

**Comment by bensku** [comment]
What OS do you use?

**Comment by HYPExMon5ter** [comment]
I added the os to the first message

**Comment by Blueyescat** [comment]
It should be case insensetive because file names aren't case sensetive ¯\\_(ツ)\_/¯

**Comment by HYPExMon5ter** [comment]
Windows is OS it worked for me on so..

**Comment by Blueyescat** [comment]
You say doesn't work on Linux + dev33, works on Windows + dev36 so no info about Linux + dev36.

**Comment by TheBentoBox** [comment]
This is almost certainly due to you using Windows for dev36. Linux's file structure is case-sensitive while the one in Windows.

**Comment by HYPExMon5ter** [comment]
Yeah I’ll check when I get home

**Comment by HYPExMon5ter** [comment]
Alright just checked, just seems to be a windows thing.

**Comment by Blueyescat** [comment]
@HYPExMon5ter LOL why did you close the issue. It should be fixed for Linux.

**Comment by HYPExMon5ter** [comment]
Well idk, if someone thinks it should be case-insensitive of linux too then they can re-open this issue.

**Comment by TheBentoBox** [comment]
I'd say this is working as intended, whether or not the file name you enter exists should be dependent on how that operating system treats file names.

**Comment by Blueyescat** [comment]
I mean, Skript should be user friendly. As it does on Skript codes.

**Comment by bensku** [comment]
I migrared Skript to NIO a few releases back. It seems to use case sensitivety of host file system.

Could also be a bug in OpenJDK, but somehow I find that unlikely...
