### ISSUE TITLE
Feature request: allow damage effect to ignore damage reducing factors

### ISSUE THREAD

**Issue by JustDylan23** [SkriptLang/Skript#1293]
```vb
damage %living entities% by %number% [heart[s]][ with fake cause %damage cause%]
```
this is the current syntax for doing the damage effect on entities, I propose a new syntax that will also allow the damage effect to ignore armor.
```vb
damage %living entities% by %number% [heart[s]][ with fake cause %damage cause%][ [and ignore damage reducing factors]
```
the syntax could still be improbed, if you are able to come up with something better, feel free to comment.

The best way to currently do this is to set an entities health, though you also have to play the hurt effect. the issue with that is that it keeps warning you when you play hurt on a variable with an entity stored in it, wich it should not do. it would be better if you can just ignore damage reducing factors.

**Comment by TheBentoBox** [comment]
I'm not sure how possible this is, but if it is it could be nice.

**Comment by Blueyescat** [comment]
*Already* it ignores armor. The damage effect works by reducing the player's health (afaik there is no any other way). But it doesn't ignore resistance effect, should be a Minecraft thing.

**Comment by Blueyescat** [comment]
setting the health does the same thing with damage effect, but no sound effect
damaging by 0 doesn't do anything

**Comment by Dylan123111** [comment]
the damage effect doesn't ignore protection on armor
