### ISSUE TITLE
Double Else

### ISSUE THREAD

**Issue by sgort87** [SkriptLang/Skript#1294]
Placing two consecutive Else sections causes the script to fail entirely, and prints no errors.

**Comment by HYPExMon5ter** [comment]
I had this issue at one point too

**Comment by Pikachu920** [comment]
as i:
```vb
on script load:
  if true is true:

  else:
  else:
```
?
if not, can you post example code? also please give the errors you get

**Comment by sgort87** [comment]
So I guess it only happens if there's an Else If in there. In game it shows no error, but the console reports a load fail. It would be nice if it could give the same or similar error that it gives if the Else If is not used.

command /doubleelse:
	trigger:
		if true is false:
			stop
		else if false is true:
			stop
		else:
			send "Message 1"
		else:
			send "Message 2"

06.06 21:24:21 [Server] INFO Reloading all scripts...
06.06 21:24:25 [Server] ERROR #!#! 
06.06 21:24:25 [Server] ERROR #!#! [Skript] Severe Error:
06.06 21:24:25 [Server] ERROR #!#! Could not load Test/DoubleElse.sk

**Comment by Blueyescat** [comment]
Ok, this issue hapens if there is an **else if**, if you do **if + else + else** it will say "'else' has to be placed just after an 'if' or 'else if' section"

**Comment by TheBentoBox** [comment]
Pretty bad for noobs IMO since it can somewhat silently break their whole script. Should be fixed.

**Comment by sgort87** [comment]
Especially for new people, but even in my case, it happened because of an indentation error that happened when I was revising my structure. I got lucky and spotted why pretty quickly, but it could have been horrible if it was a bigger script.
