### ISSUE TITLE
Parse expression error when using "\" to escape "[ ]" in dev 35 and 36

### ISSUE THREAD

**Issue by JarrenJ** [SkriptLang/Skript#1295]
`add uncolored loop-value parsed as "\[⟴\] DAMAGE: %number% - %number%" to {_damage::*}`

This worked in dev34, however when I call: {_damage::1} and {_damage::2} now it is shown as  "none".

No errors in console, it just no longer works.

EDIT: Found error.... I no longer need the **\\** to escape the brackets, didn't see that was fixed.

**Comment by Pikachu920** [comment]
You're definitely supposed to escape them, still (it isn't a bug). Maybe this is related to the other parse expression issue with optional types?

**Comment by TPGamesNL** [comment]
Can't replicate:
`("[abc] test 4") parsed as "[abc] test %number%"` doesn't parse.
`("[abc] test 4") parsed as "\[abc\] test %number%"` does parse.
