### ISSUE TITLE
Cancelled drop event returns tool as air

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#1296]
Basically, if you cancel the drop event and you're holding exactly one of an item, `player's tool` returns `air` even if the event is cancelled. It works fine if you're holding 2 or more items.

Hope this can be fixed soon.
Thanks.

**Comment by Blueyescat** [comment]
May need `wait a tick` or uncancel then, but use event-item

**Comment by Snow-Pyon** [comment]
As @Blueyescat said, use event-item.
