### ISSUE TITLE
Displayname return none

### ISSUE THREAD

**Issue by DjTurky** [SkriptLang/Skript#1301]
When i check name of player's tool it return none even item has displayname. If i use anvil it returns name of tool but it returns null when i give item with name with skript.

**Comment by github-usrname** [comment]
# try using 
on load:
  Execute console command "/give %player% minecraft:item 1 0 {display:{Name:"Custom Bow"},ench:[{id:34,lvl:10}]} "

**Comment by TheBentoBox** [comment]
We need more info: server version, Skript version, and the code you're trying to use.

**Comment by DjTurky** [comment]
Server Version: 1.12.2
Skript Version: 2.36 and 2.34 and 2.35 tried
Code: %name of player's tool% and %displayname of player's tool%
No error when using these.
on load:
Execute console command "/give %player% minecraft:item 1 0 {display:{Name:"Custom Name"},ench:[{id:34,lvl:10}]} "
Will try this. When i try i'll write here.

**Comment by github-usrname** [comment]
i just quickly googled everything to be sure and what i want to say its Huge 120 Lines +
but on Short.
i should Recommend Every Newbie to Stop by the FORUMS to Ask for Help and
Step 1 
 Research AND test , then
 if test Failed Repeat Step 1 

P.S.:
Remmember Try's are Unlimited but Patient is not!

Definitions of patient
adjective
able to accept or tolerate delays, problems, or suffering without becoming annoyed or anxious.
"be patient, your time will come"


TheBentoBox, Anyhow to Fix this Without Overriding Names and Paths ?
!   D:\DEV\eclipse-epsilon-1.4-win32-x86_64.zip: Cannot create eclipse-epsilon-1.4-win32-x86_64\features\org.eclipse.emf.ecp.emfforms.idetooling.feature.source_1.10.0.20160912-1709\META-INF\maven\org.eclipse.emf.ecp\org.eclipse.emf.ecp.emfforms.idetooling.feature\pom.properties
    Total path and file name length must not exceed 260 characters

**Comment by TheBentoBox** [comment]
I can't speak for IDE or environment issues, I'm not a developer on the project, just an issue manager (and I'm working on the updated aliases).

Can anyone else confirm this issue? I kind of doubt this is an issue since nobody else has reported it.

**Comment by Blueyescat** [comment]
Of course it works fine. 1.12.2 PaperSpigot - Skript 2.2-dev36

**Comment by TheBentoBox** [comment]
Thought so, thanks @Blueyescat . You're likely just doing something wrong @DjTurky; are you sure you know what that expression is for? You can't just use it on any random item to get the name it shows in-game or something, it has to be an item that has a custom display name, such as one renamed in an anvil or given a name via commands. If you're aware of that and are still having issues, it must be due to your add-ons.

**Comment by github-usrname** [comment]
i havent tested , but im sure if Every1 Else is Aproving < NONE ISSUE> i cant agree more !
