### ISSUE TITLE
Permission messages

### ISSUE THREAD

**Issue by JanTheDeveloper** [SkriptLang/Skript#1303]
Hi,
I've installed the newest Skript release and noticed that permissions messages didn't work as usual. The colors didn't show up (as shown in the images below); They worked just fine in the previous release. You can see the list of plugins installed on my server below. All of them are the newest available releases.

![zrzut ekranu 2018-06-11 o 21 53 48](https://user-images.githubusercontent.com/40182570/41253898-057b1492-6dc2-11e8-96d2-25307ac31bb5.png)
![zrzut ekranu 2018-06-11 o 21 48 08](https://user-images.githubusercontent.com/40182570/41253777-b28c0426-6dc1-11e8-9b97-473a05ea1fc2.png)
![zrzut ekranu 2018-06-11 o 21 47 46](https://user-images.githubusercontent.com/40182570/41253786-b5c39c44-6dc1-11e8-93ae-02b6b6262d04.png)

**Comment by Blueyescat** [comment]
@Pikachu920 probably this https://github.com/SkriptLang/Skript/pull/1225 broke it.

**Comment by Pikachu920** [comment]
yeah probably

**Comment by bensku** [comment]
Might want to use JSON chat parsing here when you fix this.

**Comment by Blueyescat** [comment]
Then JSON chat on permission message would work? It should work for cooldown message too.

**Comment by Sitieno14** [comment]
same problem here
