### ISSUE TITLE
SQL Queries

### ISSUE THREAD

**Issue by github-usrname** [SkriptLang/Skript#1305]
Hey guys , i want to apologize before saying anything , that it may be posted in the Wrong Section or Such but my Errors is Most-Likely this one

when i try to make MySQL Query trough Latest Versions of 
Skript-db / SkQuery / SQLibrary / [SKELLET]
All these addons Are Tested Separately on CLEAN Paper [server.jar] 1.12.2
and when i try to do 
set {_var} to ..... mysql query"SELECT `integer` FROM `Table`"
exec "/tell admin %{_var}% == Var"
{_var} prints >"  None == Var " 
and  {_var::*} aswell 
only ' Skript-db'  returns  Only Names of Columns 
there Values from Database return NONE

So if you please let me Ask For Help , All the Developers out there to give me Direction or Tell me , Where to open " Topic " for Help Also if Some Dev or Anyone Who Tested and Worked to point me to the right Sections,

================================================================

!!!!!!!!!!!!
skript-db-0.1.1-all.jar
!!!!!!!!!!!!
on script load:
  set {sql} to the database "mysql://127.0.0.1:3306/dbase?user=root&password=root&useSSL=false"

command /dbt:
  trigger:
    execute "SELECT * FROM `Table` WHERE `ID`='1'" in {sql} and store the result in {var::*}
    send "%{var::*}% << Value should be 1" to player
{var::*} prints " ID " instead >" 1 "

================================================================

!!!!!!!!!!
SkQuery-3.6.0-Lime
!!!!!!!!!!
script options:
    $ init com.mysql.jdbc.Driver
    $ db url jdbc:mysql://127.0.0.1:3306/dbase
    $ db username root
    $ db password root

command /db:
    trigger:
        set {_result::*} to "§3!broken!§f"
        set {_result::*} to objects in column "ID" from result of query "SELECT * FROM `Table` WHERE `Name`='admin';"

{_result::*} prints " None " expected " 1 "

================================================================

!!!!!!!!!!
SQLibrary-7.1
!!!!!!!!!!
Same Effect

{result::*} prints None EXPECTED 1

================================================================

!!!!!!!!!!
Skellet 1.9.6b /* now the funny part */
!!!!!!!!!!

on load:
    set mysql host to "localhost"
    set mysql username to "root"
    set mysql password to "root"
    set mysql database to "dbase"

< / BREAK >

[Skript] can't understand this event: '    set mysql password to "root"' (sql.sk, line 4:     set mysql password to "root":')

isnt that Great 

================================================================

DB is Up n Runing

APACHE 2.4.7	
MYSQL 5.6.15
PHP 5.5.8

Paper-1-12-2

Windows 10 x64

Java 8.0.1510.12
Due to 
INTEL GRAPHICS 3000 Java Environment Misbehave

i will upload All Logs and i will share a link here

[logs.zip](https://github.com/SkriptLang/Skript/files/2091850/logs.zip)

logs.zip >> https://github.com/SkriptLang/Skript/files/2091850/logs.zip

**Comment by Snow-Pyon** [comment]
This issue tracker is only for Skript issues, if you have issues with an addon contact the addon author.
