### ISSUE TITLE
On inventory click inconsistent

### ISSUE THREAD

**Issue by Zedify** [SkriptLang/Skript#1307]
On inventory click:

Seems to be very inconsistent. Clicking once will call it twice while the next click won't get detected.

**Comment by TheLimeGlass** [comment]
Already a known issue. This is due to the client being of a different version than the server. Nfell made a fix for this a long time ago, did it break again? Please provide your Skript version, Minecraft server version and Skript code that caused the issue.

**Comment by Zedify** [comment]
PaperSpigot 1.8.8, Skript 2.2dev36
`on inventory click:
	broadcast "clicked"
	cancel event`
Very very inconsistent, some times it works, most times it doesnt.

**Comment by Snow-Pyon** [comment]
Can someone else confirm if this happens on 1.9+? Closing otherwise.

**Comment by xbxymax** [comment]
Dev36 actually has a lot of bugs, I tested it for two days and eventually opted to use dev31

**Comment by HYPExMon5ter** [comment]
Not really, it’s pretty stable

**Comment by xbxymax** [comment]
I also believe it is stable, but now it does encounter problems, perhaps after I will collect these issues and submit

**Comment by Pikachu920** [comment]
someone on discord verified this doesn't happen on 1.9 and without via version
