### ISSUE TITLE
 problem with a condition that checks the item in the inventory

### ISSUE THREAD

**Issue by Pixwok** [SkriptLang/Skript#1308]
Hello, I post this topic because it's been several days that I research how to test if the player has a cave_spider egg in his inventory (version of minecraft 1.12.2, version of skript dev36). so I made this code below.

command /deposit:
    permission: wailcast.deposit
    trigger:
        while player's inventory contains spawner_egg:59:
            remove 1 spawner_egg:59 from player
            add 1 to player's money

I think the problem comes spawner_egg:59 because when I put the id of the stone in place of spawner_egg:59 on the first line, it works I think it is from to: between spawner_egg and 59. The problem I do not know how to solve it.
If you have an idea of ​​how to make me part of your solution.

**Comment by TheBentoBox** [comment]
Spawn eggs don't use data values to determine their type anymore, it's stored in the NBT. This should be fixed when the new aliases are released, so you'll just have to wait until then. Further discussion of this should go to #587.
