### ISSUE TITLE
EventValues for on mine/break:

### ISSUE THREAD

**Issue by weberlepecheur** [SkriptLang/Skript#1315]
Hi

Skript dev36
Spigot 1.12.2

I have a problem with the event `on mine:`, when I send `%event-block%` in a message it tells me the correct block, but if I put it in a variable it sends me the name of the script as well as the location of the block as `skript-name:location`

```
on mine:
	{coalindus_stats::%uuid of player%::%event-block%} isn't set:
		send "1 - %event-block%"
		set {coalindus_stats::%uuid of player%::%event-block%} to 0
		send "2 - %block%"

command /cid:
	trigger:
		loop {coalindus_stats::%uuid of player%::*}:
			send "§9Index: %loop-index%  §2➣  §6Value: %loop-value%"
```

This code refers me this :

![image](https://user-images.githubusercontent.com/18701493/41501348-11e869d4-71a3-11e8-846c-e902d9d18c2e.png)

**Comment by Pikachu920** [comment]
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/classes/data/BukkitClasses.java#L190
This is intended functionality implemented by Njol in 2012
