### ISSUE TITLE
on break: not saving event-block properly

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1317]
So i just noticed this today when trying to save an event block during a break event

I did this test code to try it out 
on mine:
        set {_block} to event-block
	send "%{_block}%"
	wait 1 tick
	send "%{_block}%"

now the issue is when i do this, lets say i break grass, first it shows on my screen 
grass_block, then one second later i see
air

so why is it changing??

Skript: dev36
spigot 1.12.2

**Comment by TheBentoBox** [comment]
This is related to past/future event-value changes which are in #671 .

**Comment by Blueyescat** [comment]
@TheBentoBox hmm are you sure? event-block links to the block doesn't copy it. (idk why)

**Comment by Pikachu920** [comment]
it's not related to #671, but it is not an issue

**Comment by TheBentoBox** [comment]
Actually this exact issue (event-block value live updating) was reported ages ago in #72 which was closed by bensku with conversation directed to #671.

**Comment by Pikachu920** [comment]
the value of event-block is not actually changing, it's still pointing to the same block. It only seems different because the string form of a block is it's type. #72 details a different issue
