### ISSUE TITLE
Java 8 end-of-life

### ISSUE THREAD

**Issue by bensku** [SkriptLang/Skript#1321]
I do not like removing or deprecating major features (*cough* Minecraft 1.9 *cough*) without some warning time. So, here it goes:

Java 8 is end-of-life in January 2019. After that, most users will not get bug fixes, security patches or any other updates from Oracle. They should migrate to either Java 10 or (preferably) 11.

For Skript, this means that releases made after January may not support Java 8. After all, running a *server* on top of unsupported, insecure, Java version would be a *bad* idea.

Edit: Corrected a few dates. Note that these apply only to Oracle JRE; most Linux distros ship OpenJDK which *might* have different support lifecycle.

**Comment by Matsjee** [comment]
Yeah uhm... that's a joke right? I hope it is..

**Comment by xXAndrew28Xx** [comment]
Seems like Java 8 is getting LTS updates until 2019. I'm down for migrating Skript to Java 10 or 11. Hopefully Mojang makes Minecraft Java Edition use Java 10+ by then so server hosting providers are forced to update.

**Comment by bensku** [comment]
Seems that I looked at outdated roadmap. Java 8 is getting a few more months of updates than I thought. I'll update the original post.

Note that it seems unclear if some random OpenJDK builds you have will get security fixes on Java 8 after Java 11 is released. Be sure to check it if you're not running Oracle's build.

**Comment by Nicofisi** [comment]
Does Spigot work fine on Java 10 right now? Just curious

**Comment by bensku** [comment]
I have not noticed any issues. It is possible that some plugins do not work well. Also, Minecraft client doesn't really work with Java 9+ as far as I know. However, Mojang usually ships Java for players, so that is *their* problem.

**Comment by AyhamAl-Ali** [comment]
End of life of this issue maybe?

**Comment by TPGamesNL** [comment]
Skript only requires Java 16 for compilation, runtime still allows Java 8 therefore we cannot use any features from Java 9+

**Comment by TheLimeGlass** [comment]
@TPGamesNL I don't think we need to have this as an active issue? What is it representing, we recommend Java 12+ more or so Java 17+ but we still compile to Java 8 as Skript still supports 1.13-1.16 which can run on Java 8.

**Comment by TPGamesNL** [comment]
The issue is about dropping support for Java 8 (or switching to a higher target Java version), which is still a possibility even if we keep supporting 1.13 - 1.16, because 1.13 - 1.16 runs on Java 11 as well.

**Comment by Moderocky** [comment]
Java 8 support will be dropped in favour of Java 11 as of Skript 2.9.
As Java 11 is _also_ past its end-of-life, we will be dropping that in favour of Java 17 in future.
