### ISSUE TITLE
Looping inventory bug

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#1324]
Minecraft Version: 1.12.2 PaperSpigot
Skript Version: dev36

Description: When looping a variable of players `loop all items in inventory of loop-value` doesn't work but `loop all items in loop-value's inventory` does, it doesn't cause an error, just doesn't work.

Code:
```
command /bug:
	trigger:
		add player to {_var::*}
		loop {_var::*}:
			loop all items in inventory of loop-value:
				send "%loop-value-2%"

command /working:
	trigger:
		add player to {_var::*}
		loop {_var::*}:
			loop all items in loop-value's inventory:
				send "%loop-value-2%"
```

**Comment by Pikachu920** [comment]
possibly related to the issue described in #1287?

**Comment by Wealthyturtle** [comment]
Running this on Spigot 1.14.4 / Skript 2.4-beta8 seems to work? /bug and /working both yield the same outputs, can anyone else replicate?

**Comment by TPGamesNL** [comment]
I can not replicate this issue
