### ISSUE TITLE
Command Already Defined Error Message

### ISSUE THREAD

**Issue by sgort87** [SkriptLang/Skript#1329]
The error message for when a duplicate command exists only shows one location where the command exists, and not the script in which it decided to fail. Showing both locations in the error will help identify where to look in these cases.

Also, this made me think to test functions for this duplication error, and it turns out that no error is generated at all. Showing an error and both file names for this would also be helpful.

**Comment by Blueyescat** [comment]
That is a bug, somehow these can't get the script file:
https://github.com/SkriptLang/Skript/blob/1ec68a767c5e35abc487b25df3e47a7af4e58324/src/main/java/ch/njol/skript/command/Commands.java#L344-L345
https://github.com/SkriptLang/Skript/blob/1ec68a767c5e35abc487b25df3e47a7af4e58324/src/main/java/ch/njol/skript/command/Commands.java#L523L-L524

**Comment by sgort87** [comment]
Sure, I'll know the script that the new command is in, but I'll have no idea where the other one is if the "already defined" error points to the script being added. It's a toss-up.

**Comment by TheBentoBox** [comment]
It's fairly simple in any decent text editor to just open all of your scripts and search all of them for the other instance(s) of the function's declaration, but it would still be nice for it to list the locations all of the other declarations if possible.
