### ISSUE TITLE
Can't Fix Errors

### ISSUE THREAD

**Issue by Techno3600** [SkriptLang/Skript#1330]
Here's the errors I'm trying to fix (everything already works, but Skript still yells at me)
https://gist.github.com/Techno3600/d26e9ce863820063385b59d2c89e2823

Here's after I take all of the "" marks off because it told me to do so.
https://gist.github.com/Techno3600/0e866aab422a90562bbd1aeccfc6f7ef

Why does this happen, I just wasted 30 minutes and fixed no errors.

Thanks
Techno

**Comment by Pikachu920** [comment]
You have to also remove the %

**Comment by Techno3600** [comment]
Remove the % and "?
