### ISSUE TITLE
Kotlin Lang Support

### ISSUE THREAD

**Issue by kahverengi001** [SkriptLang/Skript#1333]
Kotlin language support for project. Without Stdlib it'll work. No changes to .jar size. If someone need Stdlib, they can add needed methods to `util` package.

The mixing project with Java is ok. Don't saying remove Java from project (or convert to Kotlin all project).

With Kotlin we can do better stuff. Like easily handle threads, bugs, more readable codes, easy writing and etc...
Just one more thing is maybe we should talk where Kotlin files be need to. I mean on src/kotlin side or src/java.

I'll send a PR for adding Kotlin language support. But if it will accepted, the documentary (README.md) need to be changed for Kotlin too.

**Comment by bensku** [comment]
A couple of points:

* Bukkit is mostly not thread-safe at all. Kotlin or not, it is dangerous to treat it like that.
* Nullness annotations are *likely* incompatible with Kotlin's nullness system. If so, using Kotlin to interact with Skript directly may be quite painful.
* Kotlin IDE support appears to be pretty bad at the moment (mainly concerned about Eclipse, but also Netbeans). Unless situation has improved recently, we *cannot* use Kotlin for anything that provides functionality to scripters. Kotlin API for addons would be ok, most other things wouldn't.

Do you still think there would be many uses for Kotlin in Skript?

**Comment by crzyBrown** [comment]
Mm,

First thread safe is not about Kotlin, so it can't be dangerous unless if you don't use coroutines, threads in codes.

Second isn't project's nullness anotations  Java's? (i mean if you don't use a library or something for this but if it, it will %100 interoperable with Kotlin like as said in kotlinlang.org)

Thirth yeah you are right about this. But i don't think it is really a problem unless if you don't use notpad for editing Kotlin files.

Kotlin is just awesome, i love it too much. I wish the project would be totally written in Kotlin. But Kotlin's mixing project feature is beautiful.

**Comment by bensku** [comment]
We *do* use Eclipse's nullness annotations at the moment. IDEs tend to support them, if they support nullness analysis, but can't say what Kotlin does.

**Comment by crzyBrown** [comment]
Idk what Eclipse's nullness annotations does. Can you explain in short?

Just i can say is Kotlin can great interact with null stuff.

**Comment by Pikachu920** [comment]
It's really strict null analysis enforced by ECJ.  Read about it [here](https://wiki.eclipse.org/JDT_Core/Null_Analysis], if you are interested.

**Comment by crzyBrown** [comment]
Yeah, i searched and it's okay with Eclipse's nullness annotations. It writes in here: 
https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations

**Comment by Syst3ms** [comment]
Kotlin can be configured IDE-wise to take nullability annotations in account. But i don't know if it'd work well with ECJ.

**Comment by Wealthyturtle** [comment]
Closing this issue as I don't think Skript has any current plans for Kotlin support
