### ISSUE TITLE
Variables in Block Break effect

### ISSUE THREAD

**Issue by UzumakiYT** [SkriptLang/Skript#1335]
play redstone block breaking at player <- work
play {_block} breaking at player <- not work

**Comment by Snow-Pyon** [comment]
You can't use variables in type placeholders, the [parse](https://skripthub.net/docs/?id=901) expression is there to solve that.

**Comment by UzumakiYT** [comment]
I cannot get it to work
play {_test} parsed as particle at player

**Comment by Blueyescat** [comment]
"%{_block}% breaking" parsed as visual effect

**Comment by UzumakiYT** [comment]
thank you 🖤
