### ISSUE TITLE
Issues with event values of vehicle events

### ISSUE THREAD

**Issue by Blueyescat** [SkriptLang/Skript#1337]
Skript registers vehicle (Vehicle) and passenger (Entity) for vehicle events, but Vehicle is registered as `event-entity` as there is no vehicle type in Skript.

https://github.com/SkriptLang/Skript/blob/b457dfb16e4014d930ae72194ca8a50f27dd920f/src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java#L691-L720

So it registers double `event-entity`, probably uses the last registered one.

As a simple solution Vehicle can be removed, then you must use `vehicle of event-entity`.

1337

**Comment by Pikachu920** [comment]
i wouldn't even mind registering a vehicle classinfo and having event-vehicle tbh

**Comment by Blueyescat** [comment]
Yeah as i said just removing it would be better. Already it is not possible to use it right now.

**Comment by TheBentoBox** [comment]
This doesn't really cause any forward-facing bugs but I agree it would be nice to be able to use `event-vehicle` in these events.

**Comment by AyhamAl-Ali** [comment]
`PR Available` label missing :hand:
