### ISSUE TITLE
Expression "inventory viewers" always returns the owner as viewing

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1338]
Reproduce:

```
on drop:
    broadcast "%event-player's inventory's viewers%"
```

The expression will always return the event-player as currently viewing their own inventory, wether or not it's actually open to them.

Version: 2.2-dev36

shucks, one too late for getting ticket 1337 :dancer:

**Comment by TheBentoBox** [comment]
I'm not sure how easy it is to handle this properly for player inventories specifically. I don't believe the server has any way to know if the client has their inventory open so it would be incorrect one way or the other: either it'll always say they're viewing it or if we intentionally exclude them it'll say they're not viewing it even when they are.

**Comment by bensku** [comment]
A documentation change wouldn't hurt, though.
