### ISSUE TITLE
Problem with functions(/variables) and inventory has condition

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#1342]
So I was trying to make a shop when I came across this bug. So whenever I run /buy (see code below), it tells me this:
![image](https://user-images.githubusercontent.com/29547183/42097071-66120e16-7bb7-11e8-8566-de28c8c2a6dd.png)
Code:
https://hastebin.com/asuniyoqut.vbs
EDIT: I'm using dev36

**Comment by Blueyescat** [comment]
https://github.com/SkriptLang/Skript/issues/1287

But i said it works when i use **`{_p}'s inventory`** there 🤔

**Comment by TPGamesNL** [comment]
If I use {_p} instead of {_p}'s inventory, even the one which isn't in a function doesn't work:
https://hastebin.com/zuqobicose.vbs
![image](https://user-images.githubusercontent.com/29547183/42097948-c8f8e728-7bb9-11e8-9ac1-5008222b1816.png)

**Comment by Blueyescat** [comment]
function buyItem(p: player, i: item):
    if {_p}'s inventory has {_i}:
```
Doesn't work, but works when you make the parameter "item type".

**Comment by TPGamesNL** [comment]
Okay thanks!
