### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xGlenor** [SkriptLang/Skript#1343]
Hello, I have a bug. It is that since version 1.11.2 by typing something like this ....... I can put items into the frame and rotate them. On 1.8 or 1.8.8 and 1.9.4 it works correctly. I care that it also works on version 1.11.2. So if it's possible, please fix the bug. I've tried to upload other SkQuery and uploaded all versions from dev20 up and it does not work. Thank you in advance for the repair if it is possible

Skript

> On rightclick on item frame:
	player is in world "world_galeria"
	if player is not sneaking:
		cancel event
	if player is holding item frame:
		cancel event

**Comment by Blueyescat** [comment]
Your full code works just fine for me using PaperSpigot 1.12.2 and Skript 2.2-dev36. I can't edit the item frame if i'm not sneaking.

**Comment by TheBentoBox** [comment]
Anyone else able to confirm or not then? If not I'll be closing per @Blueyescat 's observation.

**Comment by TheBentoBox** [comment]
No response, likely an add-on or version issue. If you can provide more reproduction details feel free, I'd be happy to reopen this if it's proven valid.
