### ISSUE TITLE
Bug: can't set an entity's target to a random element out of list-var

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1347]
This will not work:
```
on spawn of zombie:
    loop all entities in event-entity's world:
        distance between loop-entity and event-entity < 32
        add loop-entity to {_targets::*}
    set event-entity's target to a random element out of {_targets::*}
```

This will work though:
```
on spawn of zombie:
    loop all entities in event-entity's world:
        distance between loop-entity and event-entity < 32
        add loop-entity to {_targets::*}
    set {_target} to a random element ouf of {_targets::*}
    set event-entity's target to {_target}
```

Using dev36.
Noteworthy: the spawned zombie in this event has it's AI target selectors cleared by another plugin (MythicMobs), so it spawns with no natural target-intentions. I do wait a sensible amount of time after the spawn event before setting a new target in my script.

**Comment by Snow-Pyon** [comment]
It doesn't  throw any errors? Can you try without any plugin that could possibly modify this behaviour?

**Comment by jaylawl** [comment]
No errors were thrown. I made sure that nothing else could affect the behaviour. Altho i didn't test without add-ons, if you're referring to that

**Comment by Pikachu920** [comment]
he means to try without mythicmobs which seems like something that changes the AI of mobs

**Comment by Pikachu920** [comment]
I couldn't reproduce this with just Skript
