### ISSUE TITLE
Bug: identical locations are exclaimed different when comparing

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1348]
```
command /loctest:
    trigger:
        set {_loc} to location(0, 64, 0, command sender's world)
        # or:
        # set {_loc} to command sender's location
        teleport command sender to {_loc}
        command sender's location != {_loc}
        send "You moved away from {_loc}!"
```
including pitch and yaw in the comparsion didn't seem to make any difference

dev36 skript
a viable workaround is to instead compare the distance between the two locations in question, which will return 0 unless the player moved

**Comment by xXAndrew28Xx** [comment]
Can not reproduce in dev37c (compiled now from master) with this code:
```
command /test:
    trigger:
        set {_loc} to player's location
        teleport player to {_loc}
        if player's location is {_loc}:
            send "same"
```
![image](https://user-images.githubusercontent.com/9660418/43222425-b358d110-9015-11e8-8f21-e824301187e6.png)

**Comment by Pikachu920** [comment]
how about when using the location function?

**Comment by TheBentoBox** [comment]
Never responded and the one test did not lead to a reproduction so I'll close this.
