### ISSUE TITLE
Bug: extreme parsing times in cases where "x/y/z of vector" are used

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1349]
Code to reproduce:
```
command /test:
    trigger:
        set {_v} to vector between command sender's location and command sender's world's spawn
        set {_loc} to location(command sender's x-coord + x of {_vector}, command sender's y-coord, command sender's z-coord + z of {_vector}, command sender's world)
        broadcast "%{_loc}%"
```

Takes between 9-12 seconds to reload this script on my server: https://snag.gy/QinqeR.jpg
Skript-dev36

Note: in more simple context, like `broadcast "%x of {_v}%"`, this issue does not occur

/edit:
Using this:
`set {_loc} to location((command sender's x-coord) + (x of {_vector}), (command sender's y-coord), (command sender's z-coord) + (z of {_vector}), command sender's world)`
helps, but the reload time of the script is still about 0.2-0.3 seconds.

**Comment by Snow-Pyon** [comment]
Closing since this is rather a parser performance issue and there are already many issues about this topic.
