### ISSUE TITLE
Suggestion: "parsed as uuid" or "text parsed as entity"

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1352]
We have the awesome ability to work with UUIDs of any entity, be it player, mob or ... an item frame. Those UUIDs can be saved as text, however, can afterwards only be re-linked to the entity with troubles. Currently, this is the only way i know of:
```
loop all entities:
    loop-entity's uuid = {stored-uuid}
    set {_entity} to loop-entity
    exit loop
```

What i was hoping would be more efficient (and maybe less resource intensive(?)) would hopefully be something along these lines:
```
set {_entity} to {stored-uuid} parsed as entity
set {_entity} to {stored-uuid} parsed as entity-uuid
set {_entity} to {stored-uuid} parsed as uuid

{_entity} is not set
delete {stored-uuid}
```

Thank you for reading, cheers.

**Comment by TheBentoBox** [comment]
Pretty sure that if Skript added a way to parse a UUID as an entity it would just be doing the exact same thing as you'd be doing there (looping all entities and comparing their UUIDs), meaning it wouldn't be any more efficient. Looking to get more dev opinions though in case there's more to that which I'm not aware of.

**Comment by TheLimeGlass** [comment]
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/classes/data/DefaultConverters.java#L295-L310

**Comment by TheLimeGlass** [comment]
Pop

**Comment by TheBentoBox** [comment]
Gonna put priority low on this one since it already has a PR to be addressed and it sounds more valuable than the standard feature request.
