### ISSUE TITLE
Suggestion: more tablist editing capabilities

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1353]
Before you say "there are plugins that can handle this" i gotta say that i'm with you. However none of these plugins have the advanced capabilities of putting variables in the tablist the way Skript does and are usually limited to a few variables like player name, player ping, vault money etc. You can use PlaceholderAPI to expand the range a bit more, but ultimately only Skript could provide ultimate freedom here.

My suggestion:
```
Set line 1 of tablist header to "My awesome server"
Set line 2 of tablist header to "- welcome -"
Set tablist header's line 3 to "{skriptcoins::%player%} SC"
Set tablist footer's line 1 to "yes"
```
Footer and header are neccessary, as in between the server's player list is shown.

**Comment by TheLimeGlass** [comment]
Tablist header and footers require NMS to access. Skript doesn't use NMS (Net Minecraft Server) which means reflection.

**Comment by Snow-Pyon** [comment]
As said above, this isn't possible without touching NMS and that isn't an option for Skript. You'll have to ask the Spigot/Paper guys to add an API for it.

**Comment by Snow-Pyon** [comment]
Looks like I closed this issue too fast, Paper has an API for it actually and it was added in 1.9 so it could be added as a Paper-only feature (we have some already so I don't see why not).

**Comment by jaylawl** [comment]
Paper is the best, great news! Thanks for taking time to investigate this.

**Comment by TheBentoBox** [comment]
Also just to make it clear to you again since it seemed to bother you earlier, priority lowest is pretty standard for most enhancements (feature requests/QoL fixes) and does not mean "we don't care about this" :) Bugs, refactors, and support for new updates of course must always come first.

**Comment by jaylawl** [comment]
Hey @TheBentoBox thanks for taking your time to explain this to me. I saw the priority tags a bit with the wrong eyes to be honest, makes perfect sense to me now. I really appreciate your effort to make this clear, have a good one!

**Comment by CrazyWords1** [comment]
UP
@TheBentoBox I know about " "we don't care about this" ", but many people need this )

**Comment by CrazyWords1** [comment]
Add this feature please

**Comment by TheLimeGlass** [comment]
Spigot has tablist header and footer now by the way for future reference.

**Comment by TheBentoBox** [comment]
This _was_ started at one point by @ShaneBeee but [the pull request was closed](https://github.com/SkriptLang/Skript/pull/1723) and another attempt hasn't been made. If you want to have another go at it Shane it'd be greatly appreciated as always!

**Comment by ShaneBeee** [comment]
> This _was_ started at one point by @ShaneBeee but [the pull request was closed](https://github.com/SkriptLang/Skript/pull/1723) and another attempt hasn't been made. If you want to have another go at it Shane it'd be greatly appreciated as always!

I definitely should try that again, but I need to wait til my current PR for EffBreakNaturally is merged. My fork is all kinds of messed up right now, and I wanted to delete my fork and start fresh once that PR is merged.

**Comment by TheLimeGlass** [comment]
That's what branches are for.

**Comment by ShaneBeee** [comment]
> That's what branches are for.

yes yes i know. But at some point along the way I messed up the main branch, and I have been trying to update it from this repo, and I just couldn't make it happen.

**Comment by AyhamAl-Ali** [comment]
Probably left opened while it's completed [see this](https://docs.skriptlang.org/expressions.html#ExprPlayerlistHeaderFooter)
Can be closed unless it's considered as an enchantment for using `line x of header/footer`

**Comment by jaylawl** [comment]
Oh wow, what a throwback :-) Haven't used skript in ages (because i do java now (which skript was a gateway for me to learn!))

Closing this as it seems it was added as mentioned by above comment

Cheers!

**Comment by AyhamAl-Ali** [comment]
Skript was (and still) a gate to learn programming fundamentals and concepts for many, including me. Happy to hear that :clap:
