### ISSUE TITLE
Colored Bed is glitchy

### ISSUE THREAD

**Issue by 7GrandDadMC** [SkriptLang/Skript#1355]
First of all, Skript doesn't think colored bed is an item (like `red bed`)
And if I set the color of the bed by setting data value (like `bed:14` or `set {_item} to bed` `set data value of {_item} to 14`), it sometimes work but it sometimes does not do anything

Maybe Skript should be supported for colored beds.

**Comment by Snow-Pyon** [comment]
Proper support for colored beds will be added once aliases rework is done. That said, with the amount of issues opened about this topic (perhaps not colored beds in specific but about item ids in general), I'm closing this one.
