### ISSUE TITLE
loop 0 times will loop 2 times.

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#1356]
Skript: dev36

```
on script load:
	loop 0 times:
		broadcast "loop!"
```
It loops twice regardless of event, that's all you need to know.

I'm going to work on fixing this, just putting it here in case I forget.

**Comment by Blueyescat** [comment]
Because it returns `1 and 0` if you didn't check ^^

**Comment by TheLimeGlass** [comment]
This isn't the numbers between syntax...

**Comment by Blueyescat** [comment]
Don't you know `X times` returns numbers between 1 and X? So 0 times means numbers between 1 and 0 so it is `1 and 0`.

**Comment by jaylawl** [comment]
Speaking as a less coding-language savvy person, i agree that `0 times` should not loop at all, because that's what i'd expect skript to do without losing another thought to it. Trying to speak for people of my lesser skill level here.

**Comment by Snow-Pyon** [comment]
@TheLimeGlass it is actually the numbers between syntax, or at least pretty much the same logic if you look at the class of this syntax.

Either way, I do agree that this is a pretty strange behaviour that should be fixed.

**Comment by Pikachu920** [comment]
what happens with negative numbers?

**Comment by Nicofisi** [comment]
> what happens with negative numbers

seems to be what @Blueyescat and @Snow-Pyon said
```vb
command /test:
        trigger:
                loop -5 times:
                        broadcast "%loop-number%"
```
```
> test
[00:11:20 INFO]: 1
[00:11:20 INFO]: 0
[00:11:20 INFO]: -1
[00:11:20 INFO]: -2
[00:11:20 INFO]: -3
[00:11:20 INFO]: -4
[00:11:20 INFO]: -5
```

**Comment by TheLimeGlass** [comment]
Anything less than or equal to 0 just adds 2.

**Comment by Nicofisi** [comment]
> Anything less than or equal to 0 just adds 2.
can you elaborate?

**Comment by Blueyescat** [comment]
It is really simple... **`-5 times`** is equal to **`integers between 1 and -5`**.

**Comment by Nicofisi** [comment]
@blueyescat I know but I don't get what LimeGlass said lol

**Comment by Blueyescat** [comment]
You know but not Lime

**Comment by TheLimeGlass** [comment]
Any number that is less than or equal to 0 will add two numbers, that's hard to understand?

If it's loop -5 times it doesn't stop after looping -5 times it keeps going *two* more numbers.

**Comment by jaylawl** [comment]
I see potential here.
If somebody uses `loop 0 times`, make the plugin delete all of the server's .sk files. 
And if somebody uses `loop -1 times` or any lower number, make all the actions in the loop reverse logically. And delete their files anyway.

**Comment by Nicofisi** [comment]
@LimeGlass hmm now I get what you meant but that's a rather less intuitive way to explain it I have to say lol

**Comment by Blueyescat** [comment]
You mean `-5 times` should be `-1, -2, -3, -4 and -5`, without `1, 0`?
That is how it works currently as **`-5 times`** is equal to **`numbers between 1 and -5`**.

You can make the `times` expression return null if the number is smaller than 1.

**Comment by TheLimeGlass** [comment]
No -5 to -1 is how it should operate, and I fixed the between numbers syntax to work any way you input it, so `numbers between -5 and 8` should work.

**Comment by Nicofisi** [comment]
> You can just make the `times` expression returns null if the number is smaller than 1.

Yes, that would be *the* solution

**Comment by Blueyescat** [comment]
`loop -5 times` is not english, the `times` expression is made to provide more readable codes. If you want negative numbers, use the numbers expression.

**Comment by TheBentoBox** [comment]
I completely agree with @Blueyescat, I feel like parsing should straight up fail if you try to do `%number% times` with a number less than one. It simply doesn't make sense and defeats the point of the expression (to make code more readable since it's essentially a `numbers between` alias).

**Comment by Pikachu920** [comment]
it may make the most sense to split the two up to prevent issues like this

**Comment by TheLimeGlass** [comment]
If a variable is used in the contex, then a condition statement will be needed...

```
if {_x-coordinate} is less than or equal to 0:
    loop numbers between {_x-coordinate} and 0:
        forcedFunction(loop-number)
else:
    loop {_x-coordinate} times:
        forcedFunction(loop-number)
```

This is ugly... Why wouldn't you just add this simple fix...

```
loop {_x-coordinate} times:
    #code that doesn't need to be split
```

It makes everything simpler and easier...

**Comment by Nicofisi** [comment]
@TheLimeGlass I have no idea what you're proposing at the moment. You want `loop -5 times` to loop 5 times? Or do what? 

`loop <negative number> times:` should error at parse time if the expression is a negative number literal, and in case of non-literals simply do nothing when executed

**Comment by TheLimeGlass** [comment]
No, you don't understand. It will loop -5 times with the loop-number being a negative which is what is needed.

**Comment by Blueyescat** [comment]
@TheLimeGlass read this 
![image](https://user-images.githubusercontent.com/19474570/42524272-af9a74b4-8478-11e8-97e5-c8bdca095827.png)
use `loop numbers between 1 and {_x-coordinate}` if you want.

**Comment by bensku** [comment]
Ok, this whole thing is a bug. Looping 0 times should do nothing. Also, looping negative amount of times should not be allowed at all. It should error if hardcoded, and do nothing otherwise.
