### ISSUE TITLE
loop players withing 2 vars (location)

### ISSUE THREAD

**Issue by Efnilite** [SkriptLang/Skript#1358]
Hey there,

so, i want to loop players between two location variables, as marked as the red area.

![2018-07-08_21 54 24](https://user-images.githubusercontent.com/35348263/42424049-15dcbebe-8305-11e8-8fc2-c5afbc740133.png)

but, if a player (in this case my alt) is in that area, he doesnt get teleported.
the player inside the yellow area will not get teleported (blue = player)

![untitled](https://user-images.githubusercontent.com/35348263/42424076-c0b3da2a-8305-11e8-8097-0af3219935e4.png)

i tried multiple things, like `loop all players where [input is in {_m1} and {_m2}]:`
`[input is between {_m1} and {_m2}]`
`[location input is between {_m1} and {_m2}]`
 and `loop all players:
if loop-player is within {_m1} to {_m2}:`
but it didnt work :/

i'm using the latest skript version (36dev 2.2, 1.12 minecraft and bensku's fork) and my addons are:
SkUtilities, SkRayfall, Skellett and SkQuery-Lime

please help, thanks

**Comment by Pikachu920** [comment]
The issue tracker is for reporting bugs, not asking for help. You can use the various forums and discord servers for help with your scripts.

**Comment by Blueyescat** [comment]
@Efnilite Also check `input's head`
