### ISSUE TITLE
Adding lang as a new file

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#136]
Can we please get the lang files as a new configurable file in the Skript folder?

https://github.com/bensku/Skript/blob/master/src/main/resources/lang/english.lang

**Comment by JKGamerxD** [comment]
It's already configurable, but it's not in the Skript folder.

**Comment by JKGamerxD** [comment]
Also @bensku, you forget to add the "mending" enchantment in the lang.

**Comment by ServerCrashes** [comment]
@JKGamerxD He knows, he wants it to actually be in the folder lol

**Comment by bensku** [comment]
This is clearly intended feature, though I do not know why so. Most likely, by providing invalid English language file, you can cause serious trouble. Other language files will default to english, so they're not so critical...

Currently you can create your own language "customenglish.lang" and copy-paste english lang file. It would be better to have Skript treat jar's English language as different than user-specified language. That would be not so easy to code, and I'm not going to do it very soon.

**Comment by Blueyescat** [comment]
You can copy ``lang`` folder to ``plugins/Skript/`` folder currently :thinking: not there by default. Still needs restart to reload.

**Comment by Blueyescat** [comment]
No i didn't and it works fine.

**Comment by thonkinator** [comment]
Sorry for being picky about tagging but this is an intended feature that isn't implemented, as stated by https://github.com/SkriptLang/Skript/blob/master/src/main/resources/lang/readme.txt, not an enhancement.

**Comment by TPGamesNL** [comment]
From that file:
> You can either put language files into the lang folder in the jar or into the plugins/Skript/lang/ folder, but files in the latter folder take precedence
(If there are two files for the same language both will be loaded but the file in the folder will overwrite values from the file in the jar)
**The exception to this rule is the default english file which is only loaded from the jar.**
