### ISSUE TITLE
Bug: client sided weather gets stuck on "clear"

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1368]
Reproduction using Skript dev36 paper1.12.2
```
command /test <text>:
    trigger:
        
        if arg 1 = "rainy" or "rain":
            set command sender's weather to rainy
            send "&7Set your personal weather to rainy"
        else if arg 1 = "clear" or "sunny":
            set command sender's weather to clear
            send "&7Set your personal weather to clear"
        else if arg 1 = "thunder" or "storm":
            set command sender's weather to clear
            send "&7Set your personal weather to storm"
        else if arg 1 = "reset":
            reset command sender's weather
            send "&7Reset your personal weather"

command /test2:
    trigger:
        
        send "Weather in your world: %command sender's world's weather%"
        send "Your personal weather: %command sender's weather%"
```

Regardless of combination, my personal weather is continuously stuck at "clear".

/edit:
I managed to sync my player-weather back with the server weather by deleting my player data on the server.
After further testing it seems like whatever i set my player weather to using the /test command, it immediatly gets stuck on "clear" and cannot be reset.

/edit2:
If i reset my player-data on the server (fixing the issue) and then go for /test2, `%command sender's weather%` will output `clear`, despite the weather in the world being set to rain (and raining in my client correctly)

**Comment by TheLimeGlass** [comment]
@Nicofisi

**Comment by TheBentoBox** [comment]
Fixed by Nico for next release
