### ISSUE TITLE
List contains text is rather slow

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#1369]
I've been messing around with variables, and ended up with this:
```
command /random:
	trigger:
		loop 2500 times:
			add 1 to {_n}
			set {_company::%{_n}%} to random 8 char string from `A-Z0-9`
		add "Jesus" to {_company::*}
		set {_u} to System.nanoTime()
		if {_company::*} where [input = "Jesus"] is set:
			send "WHERE took %System.nanoTime() - {_u}% nanoseconds!"
		set {_u} to System.nanoTime()
		loop {_company::*}:
			loop-value = "Jesus"
			send "LOOP %System.nanoTime() - {_u}% nanoseconds!"
			stop loop
		set {_u} to System.nanoTime()
		if "%{_company::*}%" contains "Jesus":
			send "CONTAINS TEXT took %System.nanoTime() - {_u}% nanoseconds!"
		set {_u} to System.nanoTime()
		if {_company::*} contains "Jesus":
			send "CONTAINS took %System.nanoTime() - {_u}% nanoseconds!"
```

Turns out that contains (using list) takes 3 seconds instead of the average of 5*ms of the others.
The tricky way (using list as text) takes less time than looping the variable.

```
[11:23:35 INFO]: WHERE took 3672692 nanoseconds!
[11:23:35 INFO]: LOOP 5975881 nanoseconds!
[11:23:35 INFO]: CONTAINS TEXT took 4384739 nanoseconds!
[11:23:38 INFO]: CONTAINS took 2925752001 nanoseconds!
```

I know that variables do need a rewrite (since 2011), but I'm pretty sure that 3 seconds for contains is something that needs to be fixed.

Thanks.

**Comment by Nicofisi** [comment]
Can confirm that contains is significantly slower
```
[15:32:12 INFO]: WHERE took 2302180 nanoseconds!
[15:32:12 INFO]: LOOP 3113577 nanoseconds!
[15:32:12 INFO]: CONTAINS TEXT took 2282487 nanoseconds!
[15:32:13 INFO]: CONTAINS took 907576588 nanoseconds!
```

**Comment by Nicofisi** [comment]
In the 4th case all of this code is called every time:
https://github.com/SkriptLang/Skript/blob/b11c6e8a59f9546f217d0268599842a06c65b6f1/src/main/java/ch/njol/skript/conditions/CondContains.java#L98-L115
where the `Comparators.compare(o, item))` line internally needs to get the proper comparator from some list every single time..
https://github.com/SkriptLang/Skript/blob/01ef3f48f0b7501f7ff1ef3cd8acf07511833885/src/main/java/ch/njol/skript/registrations/Comparators.java#L85-L94
I have no idea how this could be fixed to be honest

**Comment by bensku** [comment]
Oh yeah. That is quite a serious issue if you do list comparisons often.
