### ISSUE TITLE
Better Grief Preventation support

### ISSUE THREAD

**Issue by FUZIK** [SkriptLang/Skript#137]
@bensku edit: Help wanted, see below for translation. I edited the title.

Привет, вы добавите совместимость с плагином Grief Prevention?

```
 # к примеру:
    owner claim
    claim name/number
    size claim
    #[событие claim с помощью сундука.](https://youtu.be/RWekSeMi1OE)
    #[поддержку деления на отсеки.](https://www.youtube.com/watch?v=I3FLCFam5LI)
```

Буду рад вашему отчёту по поводу моего вопроса.
Заранее благодарю.

**Comment by ServerCrashes** [comment]
Translation from Google Translate:
Hello, you add a plug-in compatibility with Grief Prevention?

  # for example:
     owner claim
     claim name / number
     size claim
     # [Claim event with the help of the chest.] (Https://youtu.be/RWekSeMi1OE)
     # [Support the subdivision.] (Https://www.youtube.com/watch?v=I3FLCFam5LI)
I will be glad to your report on the occasion of my question.
Thank you in advance.

**Comment by JKGamerxD** [comment]
sKeeland(https://forums.skunity.com/t/addon-skeeland-0-5-11-towny-skyblock-1-8/2589) support it:
```Java
claim delete[d] [event] #event-string for claim & event-player for claim owner.

[remaining] accrued [claim] block[[']s] of %player% #settable
claim at %location%
claim at %player%
owner of %claim%
remaining [claim] block[[']s] of [player] %player%
bonus [claim] block[[']s] of [player] %player%
```

**Comment by bensku** [comment]
Wait a second... Doesn't Skript already support Grief Preventation?

It does. It might be outdated, though. And naturally, it is only standard Skript region support, which doesn't allow checking claim blocks etc.

I would like if addon developers would contribute to Skript in case no NMS code is needed. Creating another new addon seems... pointless.

**Comment by FranKusmiruk** [comment]
Hooks are planned to be moved off Skript sooner or later, closing this issue.
