### ISSUE TITLE
Not able to use text formatting tags in variables.

### ISSUE THREAD

**Issue by TheRealExus** [SkriptLang/Skript#1370]
![image](https://user-images.githubusercontent.com/16813676/42714029-6eca3c46-86a6-11e8-9660-ff1737aa37b0.png)

```
command /test:
	trigger:
		set {_o} to "<tooltip:test>&eWelcome to the Lands<reset>"
		message {_o} to sender
		message {_o} to player
```

I am not able to use tooltips inside variables.

**Comment by Pikachu920** [comment]
this isn't a bug, but maybe an optional "json" could be added to make it work on non variable strings, e.g. `send json {_o} to player`

**Comment by TheBentoBox** [comment]
I think the word we’re looking for is “oversight” 😂 Should work (either directly or via syntax like Pika suggested), but it’s not exactly like it’s an error or something being broken. 

It’d make the most sense if it didn’t require an alternative syntax but would it be much slower to parse every variable within text for chat components?

**Comment by Pikachu920** [comment]
it's not an oversight or bug, when json was implemented @bensku purposefully made it work with only variablestrings
https://github.com/SkriptLang/Skript/blob/01cc5c1ed1449b4996d84a0113dcd269e776d505/src/main/java/ch/njol/skript/effects/EffMessage.java#L75
it's not that it's slow to parse every string, bensku was probably just worried about people "injecting" json into messages which is why a seperate syntax would make sense.

**Comment by OverBrave** [comment]
Problem continues in 2.4.1.
`send "&c▣ &5<ttp:&aTıkla><run command:/sccevap %{_A}%>&eA) &a%{_A}%<reset>" to player`
![image](https://user-images.githubusercontent.com/47111280/73500713-7d262100-43d4-11ea-89a7-7b67b1af96f7.png)

**Comment by Wealthyturtle** [comment]
@OverBrave That's a separate issue. Use ``send formatted``.

**Comment by OverBrave** [comment]
How? Can you give me example? Because it doesn't happen what I did.

**Comment by Alpho320** [comment]
> A similar problem persists continues in 2.4.1.
> `send "&c▣ &5<ttp:&aTıkla><run command:/sccevap %{_A}%>&eA) &a%{_A}%<reset>" to player`
> ![image](https://user-images.githubusercontent.com/47111280/73500713-7d262100-43d4-11ea-89a7-7b67b1af96f7.png)

Yes, I have this problem.

`send "   <ttp:&7Satın alımı onaylıyorsan tıkla.><command:/silah al %{_gun}% %{_price}%>&8[&a&lEVET&8]<reset> &7ya da <ttp: &7Satın alımı onaylamıyorsan tıkla.><cmd:/silah iptal>&8[&c&lHAYIR&8]<reset> " to {_p}`

![sk hata 1](https://user-images.githubusercontent.com/54181545/73533261-711b7d00-442f-11ea-8afd-93cdd4922dc7.png)

**Comment by AyhamAl-Ali** [comment]
Right now you do `send formatted {_o}`
This should be closed.
