### ISSUE TITLE
Request: continue in loops

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#1372]
I want to request something like ```continue loop``` for loops, because sometimes I had to do some stuff with temporary variables for each check in the loop and check for that variable after all the checks are done, so I think it would be easier if Skript would have something like ```continue [in loop]``` or something, which just skips the loop-object which the loop is currently at and continues with the next one.
I hope it gets added.
Cheers.

**Comment by Nicofisi** [comment]
To you and/or anyone who reads this:
* what types of loops would be handled? only `loop <stuff>:` or `while <condition>:` too?
* what if there is more than one loop? how would you specify which one you want to continue?
* considering the above, what would exactly the syntax be?

**Comment by Pikachu920** [comment]
Added for next release, but it only supports normal loops as trying to support while loops opened a whole can of worms that is not so easy to fix.

**Comment by Pikachu920** [comment]
continue loop 1 is less confusing, i could implement it if you agree that syntax is okay

**Comment by Nicofisi** [comment]
the only confusing part is whether it starts counting from loops with the most indentation or with the least indentation:
```
loop A:
    loop B: 
        loop C:
```
would `continue loop 1` continue A or C? continuing C would make it kind of consistent with how `stop \d+ loops` works, but `continue loop 1` to me also sounds like "continue the first/main loop".. this issue is full of hard decisions lol

**Comment by TPGamesNL** [comment]
I think it should work like `loop-value-%integer%`, so just like @TheBentoBox said: loop 1 is the first defined loop, loop 2 the second and so on. Also it might be handy to have something to continue all loops, so maybe a syntax like this: (if someone is going to implement both, the second one is for a specific loop, in @Nicofisi example: `continue loop 2` will only continue loop B, while `continue 2 loops` should continue loop A and B)
```
continue [(1¦all|%integer%)] loop[s]
continue loop [%integer%]
```

**Comment by Pikachu920** [comment]
another question would be, does continuing an outer loop stop all inner loops or does the outer loop run and then the code in the inner loop (after the continue effect) continue to run? For example:
```
loop 1 and 2:
  loop 3 and 4:
    loop 5 and 6:
      if loop-value-1 is 1:
        continue loop 1
      broadcast "%loop-value-1%"
```
should the result be
```
2
2
2
2
1 # the code after continue loop 1 continued after the next loop-value in loop 1 finished
1
1
1
```
or
```
2
2
2
2
```

**Comment by TheBentoBox** [comment]
I'd personally assume it would work like the second example where it stops all inner loops as well, you're continuing to the next iteration of that upper loop which means anything inside of it in the current iteration should be stopped/skipped.

**Comment by Snow-Pyon** [comment]
The This wasn't fully completed, it doesn't support skipping multiple loops yet.

**Comment by bensku** [comment]
Oops, sorry.

**Comment by Pikachu920** [comment]
alright, i fixed the can of worms with while loops above so starting with the next release after #1402 gets merged, the continue effect will support while loops and continuing a specific loop (`continue loop %number%`)

**Comment by TheBentoBox** [comment]
@Pikachu920 As per your above comment, is this now complete?

**Comment by Pikachu920** [comment]
it's complete in the incomplete and unmerged #1402

**Comment by Kastor07** [comment]
This was marked as completed, but was left in an unused merge, which never got implemented. Shouldn't this be open?

**Comment by sovdeeth** [comment]
It was added literally years ago
https://docs.skriptlang.org/docs.html?search=#EffContinue

**Comment by Kastor07** [comment]
> It was added literally years ago https://docs.skriptlang.org/docs.html?search=#EffContinue

I just tried using it on the newest version of skript and it didn't work...

**Comment by sovdeeth** [comment]
> > It was added literally years ago https://docs.skriptlang.org/docs.html?search=#EffContinue
> 
> I just tried using it on the newest version of skript and it didn't work...

What did you try?
