### ISSUE TITLE
Version consistency

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#1377]
Skript 2.2-dev37 is known internally as
```
>version Skript
[10:51:49 INFO]: Skript version 2.2-dev36
```

**Comment by ShaneBeee** [comment]
Yeah, i got the same thing.
Any when I log into my server it says 
"[Skript] A new version of Skript is available: dev37 (you're currently running 2.2-dev36)"
But I definitely downloaded dev 37

**Comment by bensku** [comment]
Fixed.
