### ISSUE TITLE
"<tooltip:click><insertion:/dedem>shift + click" doesn't work

### ISSUE THREAD

**Issue by Mrtol** [SkriptLang/Skript#1378]
nothing happens when i do shift+left click

![image](https://user-images.githubusercontent.com/41306224/42779365-e43267ac-8948-11e8-949a-1e72d1245e53.png)

![image](https://user-images.githubusercontent.com/41306224/42779371-e768d690-8948-11e8-9398-9528a45d2fb4.png)

![image](https://user-images.githubusercontent.com/41306224/42782552-f6bde398-8951-11e8-8f48-6104e885902c.png)

![image](https://user-images.githubusercontent.com/41306224/42782562-fc433bce-8951-11e8-80ea-fcc564f13b25.png)

 ```vb
command /test:
    trigger:
        send "<tooltip:click><insertion:/dedem>shift + click" to player
 ```

**Comment by Nicofisi** [comment]
Why do you press shift?

**Comment by Blueyescat** [comment]
@Nicofisi because insertion means shift+left click.

**Comment by Blueyescat** [comment]
I tried this and it didn't work by the way.

**Comment by aeonlamb** [comment]
Came to report the same issue, still in skript 2.3 beta1.
Also, insertions still aren't mentioned in the docs.
