### ISSUE TITLE
Exit Effect glitches loops

### ISSUE THREAD

**Issue by JeepSmash** [SkriptLang/Skript#1380]
I have encountered this issue several times and it took a long time to finally find where the code was going wrong.  The issue arises when the effect exit integer sections is used inside of a nested loop. When the loop comes around to get executed again it will start from where it was exited rather than from the beginning and will completely ignore its new parameters (if they have changed).  This can provide for very hard to debug issues as it will be extremely inconsistent depending on the conditions and data.
Example:
Setup by having one player with inventory full of stone and all other players with inventory completely empty.
```
loop all players:
 loop items in loop-player's inventory:
  if loop-item is stone:
   message "Stone found for %loop-player%"
   exit 2 sections
  else:
   message "NO Stone found for %loop-player%"
```
If the first player it looped simply had an inventory full of stone it would continue looping that first players inventory and find stone each time and message that stone was found in every players inventory.  The only way around this glitch is to allow the loop to complete which requires setting up a way to ignore all iterations after you want to exit or find away to escape sections without using the exit effect.

**Comment by JeepSmash** [comment]
It started a long time ago but just now finally narrowed it down to what the issue was.  I had avoided the issue by looping things differently in past.  But I would say I first ran into the issue at least a year ago but it may be older than that

**Comment by fl-y** [comment]
I came across this error ever since I began to use skript extensively, which would be about 3 months ago.

**Comment by Pikachu920** [comment]
this happens because currentIter doesn't get cleared when getActualNext is called. I'll fix it in my section PR so if that gets merged this will also be fixed

**Comment by TPGamesNL** [comment]
> this happens because currentIter doesn't get cleared when getActualNext is called. I'll fix it in my section PR so if that gets merged this will also be fixed

Not sure if you fixed it in your PR, but this bug still seems to exist, and it's been a while so I was wondering if it'll be fixed anytime soon (sorry for asking)

**Comment by Pikachu920** [comment]
it is/was fixed in the pr but that pr hasn't been merged since I haven't had the proper environment to work on it. It should be easy enough to fix without that pr though
