### ISSUE TITLE
Can't add text to lore!

### ISSUE THREAD

**Issue by iTzAyhamHD** [SkriptLang/Skript#1382]
So basically I used to use `add "new lore" to lore of player's tool` but after I updated to dev36 it said that you can't add anything to lore!

Is this is a problem or a new feature? Currently I'm using `set lore of player's tool to "%lore of player's tool%||new lore"`

**Comment by Snow-Pyon** [comment]
Probably a syntax conflict with skQuery's lore expression, not something we can't fix. The lore expression is going to be reworked anyways.
