### ISSUE TITLE
Weird behaviour with flight mode and ground state

### ISSUE THREAD

**Issue by JustDylan23** [SkriptLang/Skript#1388]
```vb
on "org.bukkit.event.player.PlayerStatisticIncrementEvent":
	if "%event.getStatistic()%" is "JUMP":
		wait 1 tick
		set {wands::doublejump::%event.getPlayer()%} to true
		while event.getPlayer().isOnGround() is false:
			wait 1 tick
		clear {wands::doublejump::%event.getPlayer()%}
		broadcast "1"
				
on flight toggle:
	if {wands::doublejump::%player%} is set:
		force player to stop flying
		delete velocity of player
		push the player upwards at speed 1.2
		push the player horizontally forwards at speed 1
```
this is basicly a double jump skript, the odd thing is that the force player to stop flying also sets the flight mode and even more odd is that when you land the ground state of the player is still false untill you give yourselve acces to fly again. This is verry odd behaviour, what is going wrong here? this uses skript-mirror

**Comment by Snow-Pyon** [comment]
This is an intended change, the documentation hasn't been updated yet but once it is, you'll see that it was pointed out there.
