### ISSUE TITLE
Zombie horse is not coded into Script

### ISSUE THREAD

**Issue by KIF4440** [SkriptLang/Skript#1389]
on death of zombie horse:
	attacker is a player:
		add 1 to {achivement.fredelig.zombiehorse.drab.count.%attacker%}
		stop
[https://gyazo.com/fc9da5809f4376257ff76831950ac2eb](url)

**Comment by TheBentoBox** [comment]
Try `undead horse`?

**Comment by Nicofisi** [comment]
Yeah, undead should work. But since the horse is called `Zombie horse` on the wiki, it'd be nice to add this alias too in the rework

**Comment by TheBentoBox** [comment]
Gonna put low, not lowest here, since this is pretty misleading (they're referred to as zombie horses in-game). Not sure if I should put aliases label on since the new aliases are for items, not entities (this would be defined in the lang file).
