### ISSUE TITLE
Sound Error

### ISSUE THREAD

**Issue by Techno3600** [SkriptLang/Skript#1390]
Here's the error.
It is not Skillet because I disabled the sound effect in its config.

17.07 21:39:28 [Server] INFO THE SERVER IS RESTARTING IN 10 SECONDS
17.07 21:39:28 [Server] ERROR #!#!
17.07 21:39:28 [Server] ERROR #!#! [Skript] Severe Error:
17.07 21:39:28 [Server] ERROR #!#!
17.07 21:39:28 [Server] ERROR #!#! Something went horribly wrong with Skript.
17.07 21:39:28 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
17.07 21:39:28 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
17.07 21:39:28 [Server] ERROR #!#! Here is full list of them:
17.07 21:39:28 [Server] ERROR #!#! Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/)
17.07 21:39:28 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
17.07 21:39:28 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
17.07 21:39:28 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
17.07 21:39:28 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
17.07 21:39:28 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
17.07 21:39:28 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
17.07 21:39:28 [Server] ERROR #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
17.07 21:39:28 [Server] ERROR #!#!
17.07 21:39:28 [Server] ERROR #!#! Stack trace:
17.07 21:39:28 [Server] ERROR #!#! ch.njol.skript.SkriptAPIException: Call to getSingle() on a non-single expression
17.07 21:39:28 [Server] ERROR #!#! at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:64)
17.07 21:39:28 [Server] ERROR #!#! at ch.njol.skript.lang.util.ConvertedExpression.getSingle(ConvertedExpression.java:150)
17.07 21:39:28 [Server] ERROR #!#! at ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:81)
17.07 21:39:28 [Server] ERROR #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
17.07 21:39:28 [Server] ERROR #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
17.07 21:39:28 [Server] ERROR #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
17.07 21:39:28 [Server] ERROR #!#! at ch.njol.skript.effects.Delay$1.run(Delay.java:101)
17.07 21:39:28 [Server] ERROR #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
17.07 21:39:28 [Server] ERROR #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
17.07 21:39:28 [Server] ERROR #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
17.07 21:39:28 [Server] ERROR #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
17.07 21:39:28 [Server] ERROR #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
17.07 21:39:28 [Server] ERROR #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
17.07 21:39:28 [Server] ERROR #!#! at java.lang.Thread.run(Thread.java:748)
17.07 21:39:28 [Server] ERROR #!#!
17.07 21:39:28 [Server] ERROR #!#! Version Information:
17.07 21:39:28 [Server] ERROR #!#! Skript: 2.2-dev36 (latest)
17.07 21:39:28 [Server] ERROR #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
17.07 21:39:28 [Server] ERROR #!#! Minecraft: 1.12.2
17.07 21:39:28 [Server] ERROR #!#! Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
17.07 21:39:28 [Server] ERROR #!#! OS: Linux amd64 4.9.103-xxxx-std-ipv6-64
17.07 21:39:28 [Server] ERROR #!#!
17.07 21:39:28 [Server] ERROR #!#! Server platform: Spigot
17.07 21:39:28 [Server] ERROR #!#!
17.07 21:39:28 [Server] ERROR #!#! Current node: null
17.07 21:39:28 [Server] ERROR #!#! Current item: play sound
17.07 21:39:28 [Server] ERROR #!#! Current trigger: command /restart (simple event) (restart.sk, line -1)
17.07 21:39:28 [Server] ERROR #!#!
17.07 21:39:28 [Server] ERROR #!#! Thread: Server thread
17.07 21:39:28 [Server] ERROR #!#!
17.07 21:39:28 [Server] ERROR #!#! Language: english
17.07 21:39:28 [Server] ERROR #!#! Link parse mode: LENIENT
17.07 21:39:28 [Server] ERROR #!#!
17.07 21:39:28 [Server] ERROR #!#! End of Error.
17.07 21:39:28 [Server] ERROR #!#!

Thanks
Techno

**Comment by TheBentoBox** [comment]
You must be on the latest version of Skript for us to accept your issue reports.
