### ISSUE TITLE
Accounting problem with some addons

### ISSUE THREAD

**Issue by AlexLew95** [SkriptLang/Skript#1391]
Heya,
I noticed a **big** problem with this new version of skript. Indeed, most of the errors that were still present in __dev36__ such as ``Can't understand this effect`` are no longer present in this dev.
Currently I found just the ``loop-index-2`` problem for example when this loop did not exist or when we put a random variable in our script file where no error targets this variable alone in our code.
We lose a lot of accuracy when we code because of this concern. I hope it will be patched soon...

__More informations about my stuff:__
```
This server is running CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```
**Server:** 1.12.2 spigot and tacospigot
**Skript:** dev37c

**Comment by Pikachu920** [comment]
i don't understand the issue

**Comment by AlexLew95** [comment]
```vb
command test:
	trigger:
		{myvar::test}
``` 
This code should generate an error and yet no error is present
Same problem with ``discord command ...`` etc...

**Comment by Pikachu920** [comment]
it seems like you have addons, if you have mundosk or skquery the posted code is valid. are you sure this happens without addons?

**Comment by AlexLew95** [comment]
It seems SkQuery-Lime is the cause.

**Comment by TheBentoBox** [comment]
Then this isn't a problem, this is just due to how some add-ons handle some of their custom features. Either way, most issues related to add-ons don't belong here. This is where we resolve issues with Skript itself, not its add-ons (we have no control over those).
