### ISSUE TITLE
Bug: loop-value not behaving right when it is an entity

### ISSUE THREAD

**Issue by JustDylan23** [SkriptLang/Skript#1393]
```vb
on left click holding a stick:
	cancel event
	message "1"
	set {_e::*} to living entities in radius 10 around player where [input isn't player]
	loop {_e::*}:
		damage loop-value by 2
	broadcast "2"
```
this skript should damage all entities in radius 10 around player by 2, "should", it doesn't though. this also applies for the apply %effect% effect and probbably more, you also can't remove effects from it, it will give you the error loop-value can't have anything removed from it.

**Comment by JustDylan23** [comment]
sorry, it turned out that I had something disableing all the damage in a world

**Comment by JustDylan23** [comment]
but you can still not remove effects from loop-entity if I am right

**Comment by TheBentoBox** [comment]
I'm pretty sure this is related to the issue you reported in #1287. There seems to be some issues currently with using some effects on entities stored in variables. This is expected cross-restart (entities aren't saved) but not in a situation like this. Let's take discussion there, though.
