### ISSUE TITLE
Waiting a local variable amount of time waits indefinitely

### ISSUE THREAD

**Issue by fl-y** [SkriptLang/Skript#1394]
Version: Hotfix 2.2-dev37c

I apologize for not being specific about the errors before
I shall be as specific as possible this time.

1. parsed timespan just waits indefinitely

```vb
command /testTimer:
	trigger:
		set {_time} to "2 seconds" parsed as timespan
		broadcast "waiting"
		wait {_time}
		broadcast "waited"
```
-> this command will never broadcast waited

2. Erroneous errors in functions - [code](https://imgur.com/a/zqm84wx), [error message](https://imgur.com/a/LVtnapg)

**Comment by fl-y** [comment]
![p1_code](https://user-images.githubusercontent.com/31615341/42954516-ea883b1a-8bb7-11e8-996a-1df6b38eb540.PNG)
![p1_message](https://user-images.githubusercontent.com/31615341/42954521-ec86f938-8bb7-11e8-885e-28a9abf92d7e.PNG)

The images since I just realized that github supports uploading images

**Comment by TheBentoBox** [comment]
What version are you on? Bensku has already released multiple hotfix updates that should hopefully fix all of the erroneous type errors. Make sure you're on dev37c. 

As for the parsed timespan waiting, that should definitely be investigated.

**Comment by TPGamesNL** [comment]
About the timespan waiting, you have a random ` add the end (could be a typing mistake, but just want to be sure the script doesn't have that)

**Comment by fl-y** [comment]
Sorry about not specifying the version. Just updated the comment
The random ` at the end is a mistake after using markdown

**Comment by TheBentoBox** [comment]
Weird. Are those the only type errors you're getting for that function? If so, it seems like they start after the first `wait`, which is interesting.

**Comment by fl-y** [comment]
Yes those are the only errors I get for that function
Also I tried removing the wait and got the same result

**Comment by fl-y** [comment]
Edit: did some testing and found the exact reason for the erroneous warnings.
```javascript
command /removePotion:
	trigger:
		set {_p} to player
		send "test" to {_p}
		remove JUMP from {_p}
		send "test" to {_p}
```
adding this to your skript will induce the "local variable '_p' is <none>" warning on the second send "test"
the remove potion expression for some reason makes skript think that _p's type is empty.

**Comment by Nicofisi** [comment]
About the waiting bug, the fix is super simple
https://github.com/SkriptLang/Skript/blob/01ef3f48f0b7501f7ff1ef3cd8acf07511833885/src/main/java/ch/njol/skript/effects/Delay.java#L84-L88
The duration is gotten after local variables are removed - the lines need to be reordered :)

**Comment by Nicofisi** [comment]
Let me split this into two separate issues, this one tracking the already-fixed waiting bug, and the other one tracking the local variables bug
