### ISSUE TITLE
player's groups returns displayname and not rankname

### ISSUE THREAD

**Issue by CGDoctor8** [SkriptLang/Skript#1397]
### Issue
When Calling %player's group% it will return the primary rank of player
When Calling %player's groups% it should return all ranks of the player but it returns the display name of all ranks
![image](https://user-images.githubusercontent.com/39572468/42983122-2b4511ac-8ba2-11e8-977b-55d5d9664f64.png)

In the screen shot the rank admin has a display name of Admin
For vip3 is has a display name of Phi
### Note
Extend %Display Name% to groups?

**Comment by Pikachu920** [comment]
this is an issue with vault and/or your permissions plugin
