### ISSUE TITLE
Error that is just wrong.

### ISSUE THREAD

**Issue by Fiiily** [SkriptLang/Skript#1401]
upon running the following skript:

```on drop:
    set {_item} to event-item
    set name of {_item} to "test"
    set event-item to {_item}
```

i receive the following error:
```
event-item stack can't be set to anything (drop.sk, line 4: set event-item to {_item}')
```
however, the item actually is renamed upon picking it back up.

Skript version 2.2-dev37c

**Comment by Nicofisi** [comment]
What's the event?

**Comment by Fiiily** [comment]
the entire skript is posted in the original issue

`on drop:`

**Comment by Pikachu920** [comment]
that's because the last line isn't doing it. the second line mutates the item stack which is why the name changed.

**Comment by Snow-Pyon** [comment]
Closing since this is an user error.

**Comment by Fiiily** [comment]
but that's not true, first line sets a variable to the item stack, and then the second like edits that variable, and then the third line actually sets the item stack to the variable. the last line IS doing it.

**Comment by Pikachu920** [comment]
no, it isn't. you can test yourself: remove the last line and the same result will happen. The reason it happens is because the variable holds a reference to the itemstack that is event-item, and mutating that variable mutates that itemstack which in turn mutates the event-item.
