### ISSUE TITLE
Timespan parsing

### ISSUE THREAD

**Issue by CGDoctor8** [SkriptLang/Skript#1403]
I didn't look before posting this, a issue has been opened already Super Sorry 
See #1394 

### Issue
When Trying to parse a time span as a string with a variable it fails silently

### Example
```
command /test:
    trigger:
        set {_ticks} to 1
        wait "%{_ticks}% ticks" parsed as timespan
        broadcast "We will never reach this line on dev37c"```
```
This was produced on 

1. Spigot 1.12.2 git-Spigot-eb3d921-2b93d83 (latest)
2. Skript version 2.2-dev37c

**Comment by TheBentoBox** [comment]
Next time you see you've reported something that's already been reported, close your issue
