### ISSUE TITLE
 Suggestion: Allow vector's when spawning particles

### ISSUE THREAD

**Issue by CGDoctor8** [SkriptLang/Skript#1405]
I [was told by Lime Glass](https://discordapp.com/channels/135877399391764480/138027100593455104/470896891463204874) To make a issue regarding this topic

When trying to spawn a particle with the following syntax it will tell you that vector is not a direction
```
show 1 firework's spark with offset of 0, 0, 0 speed 0 %directions% player's location
show 1 firework's spark with offset of 0, 0, 0 speed 0 vector(1,0,1) player's location
```
According to a quote from Snow-Pyon "everything that takes direction also takes vectors" if true
this would keep the code-base more consistent and would be particularly useful when dealing with particles so you don't have to split it up.

**Comment by TheLimeGlass** [comment]
![image](https://user-images.githubusercontent.com/16087552/43079631-dc29d21e-8e4a-11e8-8332-7d2e0c5bcdd1.png)

**Comment by CGDoctor8** [comment]
This wont give an error on reload but will spawn the particle with a random direction
```
command /test:
    trigger:
        set {_v} to new vector from 1,1,1
        loop 20 times:
            show 1 firework's spark with offset of 0, 0, 0 speed 1 {_v} player's location```
![image](https://user-images.githubusercontent.com/39572468/43089229-5c315a2a-8e61-11e8-9552-405a58753b7a.png)

**Comment by jaylawl** [comment]
I think it has to be taken in consideration that minecraft's particles mostly have their own will when it comes to their behaviour. Just wanted to throw that in here.

**Comment by TheBentoBox** [comment]
This should work, intuitively.

**Comment by TheLimeGlass** [comment]
`(play|show) %visualeffects% (on|%directions%) %entities/locations% [(to %-players%|in (radius|range) of %-number%)]` you can now place the vector as the %direction%
