### ISSUE TITLE
The custom weather of player expression returns clear when it should return null

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1408]
As of dev37c, the new player weather expressions have been fixed and are working just right as far a i was able to test them. Big thanks to everybody involved in adding this feature from me, as i was the one who requested this :dancing_men: 

There's one minor little issue left with this:
The player weather can be reset to match the server's weather. When this is the case, the expression `player's weather` will always return `clear`, no matter what the world's actual weather is. But this is *only* about what the expression returns, the actual weather of the player is synced to the world.

I'm only reporting this because i imagine changing the output to something like `<none>` or `world's weather` could prevent future confusion/reports on this.

Cheers!

@Nicofisi

**Comment by TheBentoBox** [comment]
I feel like I saw a bug for this already or saw it mentioned somewhere but I searched for weather bugs and didn't find anything so I'm probably wrong 😂

**Comment by jaylawl** [comment]
There: https://github.com/SkriptLang/Skript/issues/1368 :)
