### ISSUE TITLE
Error with dev-37 in 1.8 and 1.12

### ISSUE THREAD

**Issue by Spartan9802** [SkriptLang/Skript#1410]
Here I made several tests with several effects and expression and many does not work and returns me an error, here is an example with its error

```javascript
command /test:
	trigger:
		send "%player%"
```

> [21:27:23] [Server thread/ERROR]: #!#! Stack trace:
> [21:27:23] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:264)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1799)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1766)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1514)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:323)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:625)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:241)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:145)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:491)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:812)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1530)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1460)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1487)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:496)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:623)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:391)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:403)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:436)
> [21:27:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
> [21:27:23] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [21:27:23] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
> [21:27:23] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
> [21:27:23] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> [21:27:23] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
> [21:27:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
> [21:27:23] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
> [21:27:23] [Server thread/ERROR]: #!#! 
> [21:27:23] [Server thread/ERROR]: #!#! Version Information:
> [21:27:23] [Server thread/ERROR]: #!#!   Skript: 2.2-dev37c (latest)
> [21:27:23] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
> [21:27:23] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
> [21:27:23] [Server thread/ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
> [21:27:23] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
> [21:27:23] [Server thread/ERROR]: #!#! 
> [21:27:23] [Server thread/ERROR]: #!#! Server platform: Spigot
> [21:27:23] [Server thread/ERROR]: #!#! 
> [21:27:23] [Server thread/ERROR]: #!#! Current node: send "%player%" (test.sk, line 3)
> [21:27:23] [Server thread/ERROR]: #!#! Current item: null
> [21:27:23] [Server thread/ERROR]: #!#! 
> [21:27:23] [Server thread/ERROR]: #!#! Thread: Server thread
> [21:27:23] [Server thread/ERROR]: #!#! 
> [21:27:23] [Server thread/ERROR]: #!#! Language: english
> [21:27:23] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
> [21:27:23] [Server thread/ERROR]: #!#! 
> [21:27:23] [Server thread/ERROR]: #!#! End of Error.

**Comment by Pikachu920** [comment]
this is an issue with the original skquery breaking. either use limes fork or uninstall it but we don't deal with addon issues here, especially since skquery hasn't been maintained by it's creator in 4 years.
