### ISSUE TITLE
Missing documentation for "AsyncEffect"

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1414]
I have been researching how to do stuff with Skript async/threaded for a bit, and apart from the obvious usage of SkQuery's `$ thread`, i randomly went with searching for "Skript AsyncEffect" in google. And behold, there were some actual results: https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/util/AsyncEffect.java

My question now being: why isn't this in any way documented? Is it actually something internal that Skript users don't have access to?

Cheers

**Comment by bensku** [comment]
It is provided for Skript addons written in Java. Using it from scripts is not possible.

**Comment by Pikachu920** [comment]
It's not intended for scripters to use, it's something skript/addon devs can extend to make an effect that runs on another thread. Skript doesn't have any type of tool to run things sync or async - scripters shouldn't have to determine that.

**Comment by Pikachu920** [comment]
It's not intended for scripters to use, it's something skript/addon devs can extend to make an effect that runs on another thread. Skript doesn't have any type of tool to run things sync or async - scripters shouldn't have to determine that.
