### ISSUE TITLE
Newline support in item's lore

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#1424]
I don't know if this is a bug or a removed feature but after I updated from dev35 to dev37c I notinced that I can't add text/String to item's lore while I was able to do that before!

Can someone tell me if this is a bug or a removed feature?

Thanks.

**Comment by jaylawl** [comment]
setting item's lore is still a thing - are you getting any errors? you're being quite non-descriptive

**Comment by iTzAyhamHD** [comment]
Sorry I didn't give an example.

This code will give error: "Lore can't anything added to it":
`add "new lore" to lore of player's tool`

But setting it is working I'm currently using 
`set lore of player's tool to "%lore of player's tool%||new lore"`

**Comment by jaylawl** [comment]
`lore` is a single string object and thus you can't simply add something to it. however you can just set the entire thing like you're doing there, or just set specific lines of the like `set line 1 of player's tool's lore to "asd"`

i recommend you close this issue and request help on skunity.com

**Comment by iTzAyhamHD** [comment]
Thank you for suggestions, my issue here is why it wast working and now it's not? that's all what I wanted to ask and get answer, you're it's a single value and you can't add String to it but then why it was working before dev35?

**Comment by jaylawl** [comment]
Have you downloaded a version before dev35 and tested this yourself?

**Comment by TheLimeGlass** [comment]
There are like 6+ issues about lores, did you check that this isn't a duplicate?

**Comment by iTzAyhamHD** [comment]
@jaylawl Yes I did and it was working perfectly.
@TheLimeGlass No to be honest I didn't check if this issue happened with others, I'm sorry if it's duplicated.

**Comment by Nicofisi** [comment]
I'm 95% sure it's a conflict with skQuery, it has its own lore expression that supports only [setting and resetting](https://github.com/SkriptLegacy/skquery/blob/master/src/main/java/com/w00tmast3r/skquery/elements/expressions/ExprLore.java). Have you recently installed skQuery @iTzAyhamHD?

**Comment by iTzAyhamHD** [comment]
@Nicofisi I had SkQurey from long time ago, but I will try to remove it and see what I get.

**Comment by jaylawl** [comment]
@Nicofisi i removed skquery and it still didnt work

**Comment by Nicofisi** [comment]
@jaylawl well your code technically works okay, except from the fact that `||` means nothing to Skript, there's still no `<nl>` nor `%new line%` in Skript at the moment

**Comment by iTzAyhamHD** [comment]
@Nicofisi I'm sorry for taking so long to answer, but I haven't opened Minecraft since then because of my irl work, I will try to test it soon as possible.

**Comment by PLSINEEDHELP213** [comment]
awea
