### ISSUE TITLE
Suggest: Adding PlaceholderAPI placeholders suuport to Skript

### ISSUE THREAD

**Issue by iTzAyhamHD** [SkriptLang/Skript#1425]
Some people can't use Skellett in shared hosting so it would be great to add support to PlaceholderAPI placeholders in Skript it self.

Thanks.

**Comment by supertassu** [comment]
Duplicate of #644

**Comment by Snow-Pyon** [comment]
@TheLimeGlass there is no need to be rude about it. The issue is closed and the fact that someone uses whatever host they want doesn't mean they can't ask for a feature to be in Skript.

**Comment by TheLimeGlass** [comment]
Free hosts limit what plugins are allowed on their server. Don't use a free host.

**Comment by Blueyescat** [comment]
@TheLimeGlass serveromat doesn't limit plugins or something
