### ISSUE TITLE
Suggestion: Add a disable ability (This is already a text)

### ISSUE THREAD

**Issue by iTzAyhamHD** [SkriptLang/Skript#1430]
Hey, this kind of warning (This is already a text, so you should not put it in one.) is a bit annoying because now I can't find where are the errors of the code while there is a lot of this warnings, maybe some of you would say just fix those warnings and don't put texts in quotes but I'm a bit lazy with this because I got many of it.

It would be great to add a disable ability for this warning.

Best regards.

**Comment by Pikachu920** [comment]
Not happening at this time, refer to the conversation in #1278.

**Comment by Nicofisi** [comment]
Duplicates #1212 , also see #1259 for more information
