### ISSUE TITLE
Bug: cursor slot item detection

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1431]
Skript dev37c
Reproduce using:
```
on inventory click:
    
    broadcast "%event-player's cursor slot%"
```
Please follow this step by step:
1. Open your inventory
2. Get any itemstack on cursor slot (size doesnt matter)
3. Click with the item on an empty slot in the inventory and then _immediatly_:
4. Move your mouse away from any inventory slots

The broadcast only triggers if your mouse is hovering above an inventory slot

/edit:
This is actually true for lots of expressions

**Comment by Snow-Pyon** [comment]
This is probably something we can't fix though, gotta test whether this is a Spigot bug or even a Minecraft bug.

**Comment by TheBentoBox** [comment]
Is this still an issue?

**Comment by jaylawl** [comment]
in skript 2.3 and paper 1.13.2 i dont experience this anymore
