### ISSUE TITLE
Issues with type hints in certain situations

### ISSUE THREAD

**Issue by Nicofisi** [SkriptLang/Skript#1432]
From another issue (#1394) by @fl-y, split because it addressed two different things

---

* Skript version: 2.2-dev37c
* The code
![image](https://user-images.githubusercontent.com/12614053/43489592-ccb28720-951d-11e8-8ff9-c9d54b80776b.png)
* The error
![image](https://user-images.githubusercontent.com/12614053/43489629-ea6a807e-951d-11e8-9417-3b067a580af0.png)

> Weird. Are those the only type errors you're getting for that function? If so, it seems like they start after the first wait, which is interesting.
~ @TheBentoBox

**Comment by jaylawl** [comment]
I guess this belongs here? I'm not sure, excuse me:
```
command /test:
    trigger:
        set {_inv} to chest inventory with 1 row named "test"
        add 1 of dirt to {_inv}
        open {_inv} to command sender
```
https://pasteboard.co/HxE7o2y.png

**Comment by TeAm6AZLIK** [comment]
<img width="582" alt="schermafbeelding 2018-08-09 om 23 46 23" src="https://user-images.githubusercontent.com/30750375/43927625-782564a8-9c2e-11e8-8205-3e0e55cec791.png">

**Comment by Nicofisi** [comment]
@TeAm6AZLIK could you edit that message to contain actual copyable code please? thanks <3

**Comment by TeAm6AZLIK** [comment]
function bartendershop(item: item, name: text, buy: number, chance: number, p: player):
    if balance of {_p} >= {_buy}/2:
        if {_p} has enough space for 1 of water_bottle:
            give {_item} without nbt to {_p}
            remove {_buy}/2 from {_p}'s balance
            send "&e&lBARTENDER &8⎜ &fYou bought a &e%{_name}% &ffor &6$%regex({_buy}/2)%&f!" to {_p}
        else:
            send "&e&lBARTENDER &8⎜ &fYour inventory is full!" to {_p}
    else:
        send "&e&lBARTENDER &8⎜ &fYou don't have enough money!" to {_p}``

**Comment by TeAm6AZLIK** [comment]
> `function bartendershop(item: item, name: text, buy: number, chance: number, p: player):
    if balance of {_p} >= {_buy}/2:
        if {_p} has enough space for 1 of water_bottle:
            give {_item} without nbt to {_p}
            remove {_buy}/2 from {_p}'s balance
            send "&e&lBARTENDER &8⎜ &fYou bought a &e%{_name}% &ffor &6$%regex({_buy}/2)%&f!" to {_p}
        else:
            send "&e&lBARTENDER &8⎜ &fYour inventory is full!" to {_p}
    else:
        send "&e&lBARTENDER &8⎜ &fYou don't have enough money!" to {_p}`

**Comment by TeAm6AZLIK** [comment]
https://pastebin.com/raw/t0v2NbzV

**Comment by bensku** [comment]
Can anyone reproduce these issues with alpha builds? I think they've been fixed for a few months now.

**Comment by TheBentoBox** [comment]
I've been loading some of my scripts in the alpha builds in prep for a 1.13 update and I haven't experienced a single type hint issue yet.
