### ISSUE TITLE
Skript 1.13

### ISSUE THREAD

**Issue by xGlenor** [SkriptLang/Skript#1434]
When will the stable version be on 1.13?

**Comment by Nicofisi** [comment]
After everything mentioned in #1395 is finished (and probably some stuff from #1385)  - no date is known at the moment, but I'd say a preview version is going to be available rather sooner than later. A stable version though? No one knows

**Comment by xGlenor** [comment]
I forgot, I'm sorry

**Comment by xGlenor** [comment]
@Nicofisi 
you are Polish ?

**Comment by Nicofisi** [comment]
@xGlenor yeah, why? 

PS This isn't really the best place for random discussions, feel free to hit me up at https://discord.gg/V4qFVnh ;)
