### ISSUE TITLE
Docs missing hooks

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1436]
So I noticed that certain things are missing from the docs.
Such as prefix/suffix, regions, GriefPrevention, etc
I found these because of the skunity docs, but didn't see them anywhere on the bensku docs.
For fun, I looked and they are on the Njol docs. 
I then looked at the code on this site, and noticed things such as "prefix/suffix" are in a different section called hooks, rather than effects/events/expressions. and Im starting to think everything in the hooks category is missing from the Bensku docs?!?!?
Im not sure if this was done on purpose or mistake, but is it possible to add this stuff back into the docs?

**Comment by bensku** [comment]
Hooks cannot have documentation generated for them if they rely on plugins that are not present on server which generates the documentation. I'm honestly not sure how hard changing that would be.

**Comment by ShaneBeee** [comment]
Ah dur... that makes sense! I will make sure to add those plugins for when i create my own docs. As nico said its probably a good idea to do that, since the bensku docs website is missing those few things. I mean IM smart enough to find them, but some others may not know where to look for those syntaxes.

**Comment by Blueyescat** [comment]
_By the way don't use skUnity especially for Skript docs, https://skripthub.net/docs/?addon=Skript_

**Comment by ShaneBeee** [comment]
I was just stating that because I saw them on there.  I use skunity docs vs skript hub because they have more addons. 
I’ve already regenerated my new skript docs and put them on my website for reference and as suggested I made sure to add the hook plugins to ensure I get a full doc (including vault, pex, economy, GriefPrevention)

**Comment by ShaneBeee** [comment]
Also @bensku  I read your reply a few times and I think I may have worded my post wrong. I meant to say your website with the docs is missing the hook items. I myself realize what you mean about making my own docs and requiring those plugins, which I have done for my docs, so thank you for that info. But I wasn't meaning there was a problem with the doc gen, but specially referring to your website that those parts of the docs were missing.

**Comment by bensku** [comment]
I understood that you meant the website. Currently, however, we don't have any special environment for generating docs: it is my development server. Running plugins other is *always* a bit risky when you're trying to find bugs in Skript.

But in future I'll try to remember to grab the hooked plugins when generating docs. That should do as a temporary solution.

**Comment by ShaneBeee** [comment]
Awesome thank you
I made a copy of the docs for my website as a temp one and got them all working, so personally I'm not terribly concerned ... was more for other people who use the docs website, and potentially dont know where else to look for those syntaxes.

Thanks again

**Comment by Pikachu920** [comment]
another solution might be registering the syntax regardless of plugins if skript is in debug mode. They won't work, but that doesn't matter to the doc gen.

**Comment by AyhamAl-Ali** [comment]
This can have `PR Available` label as it's been added in #4319

**Comment by APickledWalrus** [comment]
Closing as this has been added in the new live docs (pretty sure it existed before that too)
