### ISSUE TITLE
Suggestion: add warning for ":" instead of "::" in variables

### ISSUE THREAD

**Issue by fl-y** [SkriptLang/Skript#1440]
I frequently waste time with type-os when using lists
because I forget to add two colons instead of one.
ex1) loop {myList:*}:
ex2) set {myList:1} to "asdf"
etc.

A warning that tells me which variables have one colon instead of two will be really informative and possibly save me a lot of time.

Thank you always.

**Comment by Blueyescat** [comment]
Some people can use that intentionally, so a config option to toggle that should be added too.

**Comment by Nicofisi** [comment]
Why would you use that intentionally? I've never seen such a thing in a public script

**Comment by Blueyescat** [comment]
✨
