### ISSUE TITLE
Suggestion: "spawn-reason" expression (extension of "on spawn" event)

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1444]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html

"CreatureSpawnReason" is the cause of a mob-spawn. For example, mobs/entities spawned by a plugin like MythicMobs, will be spawned with the reason `custom` or `unknown`. Mobs that are spawned when a chunk is generated (this applies to animals like sheep etc) spawn with the reason `chunk_gen`.

This would allow for things like:
```
on spawn:
    event-entity is in region "spawn"
    spawn reason != custom
    cancel event
```

```
on spawn:
    event-entity is in region "peaceful"
    spawn reason != custom, chunk_gen or spawner
    cancel event
```

Any thoughts on this?
Thank you for reading

**Comment by Snow-Pyon** [comment]
Should be there for the next release.
