### ISSUE TITLE
Skript only recognizes only 2 of 3 arguments

### ISSUE THREAD

**Issue by Duetro** [SkriptLang/Skript#1452]
**Code:**
Not working: `PayDayAddRevenue(uuid of {_player}, {_ontimebonus}, "OnTime-Bonus")`
Working: `PayDayAddRevenue((uuid of {_player}), {_ontimebonus}, "OnTime-Bonus")`

**Error:**
`[23:18:50] [Server thread/ERROR]: [Skript] The function 'PayDayAddRevenue' requires at least 3 arguments, but only 2 are given. (10-F-PayDay.sk, line 244: PayDayAddRevenue(uuid of {_player}, {_ontimebonus}, "OnTime-Bonus")')`

**Info:**
Skript: dev37c
Server: Spigot 1.12.2

**Comment by Snow-Pyon** [comment]
It is because Skript can't parse expressions properly there due to argument parsing being too lenient. The fix is the actual working code or set a variable and using that 

And well, since there are already issues opened about this, I'm closing this one.
