### ISSUE TITLE
Variable and lists for randomly generated item names

### ISSUE THREAD

**Issue by Saelman** [SkriptLang/Skript#1453]
so im having a hard time with something, im trying to make a skript thatll randomly generate a item. currently im at a point where i need to have the item randomly select a name. so itll be say a diamond sword, now when the item is spawned itll randomly be given a name from a list, im using Variables to do this, but i cant seem to figure out how to format a list of Variables for it to grab from, it its kinda set up like this.

give a diamond_sword to player named {name}
set {name} to random element out of {item_name::*}

but how do i set a list of what itll change {name} to from {item_name}
so itll change {name} to a random name from the variable list {item_name}

id like to be able to have a list of like 50 names and itll pick one at random.

anyone have a clue?

**Comment by jaylawl** [comment]
Hey sael, this github is not for support requests, but for bug reports and suggestions regarding the plugin. Please use skunity's forum or discord to seek support in the future.

The solution to your issue is:
```
add "name1", "name2", and "name3" to {_names::*}
set {_item} to diamond sword named random element out of {_names::*}
```
