### ISSUE TITLE
Feature request: all arguments expression for commands

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1455]
Skript dev37c, paper spigot 1.12.1
Reproduce:
```
command /test [<texts>]:
    trigger:
    
        set {_args::*} to arguments split at " "
        loop {_args::*}:
            send loop-value
```
"can't do that because the latter is not an object"

i have also attempted `loop arguments:`, but that returns a single value only, no matter the amount of arguments

**Comment by TheBentoBox** [comment]
If you want to take in text and split it at " ", you can just make the argument `text` (not plural) and then `set {_args::*} to text-argument split at " "`. I'm not sure if I'm misunderstanding but I don't think there is a bug here, there just isn't an `arguments` expression within command events so you're not going about it properly.

**Comment by jaylawl** [comment]
That worked, thank you!
I'm unsure wether i'm doing it wrong or this is unintentional behaviour, hence why i posted this

**Comment by TheLimeGlass** [comment]
Completed https://github.com/SkriptLang/Skript/pull/4087
