### ISSUE TITLE
List variable loops doesnt work

### ISSUE THREAD

**Issue by AhmetDS** [SkriptLang/Skript#1466]
im using list variable like this and it doesnt loops" loop {arkadaslistesi%player%::*}:" sorry for my bad english

**Comment by AhmetDS** [comment]
my plugins 
![image](https://user-images.githubusercontent.com/42338147/44021477-94da5d44-9eed-11e8-91ab-a83a7517c372.png)

**Comment by Nicofisi** [comment]
You need to provide an example snippet of not-working code

**Comment by AhmetDS** [comment]
> options:
    tag: &4[&6Guild&4]
command /guild [<text>] [<player>]:
    trigger:
        if arg-1 is "ekle":
            message "test5"
            arg 2 is set:
                message "test6"
                arg 2 isn't player:
                    message "test7"
                    arg 2 is offline:
                        send "{@tag} &7Eklemeye Çalıştığınız &c%arg 2% &7Şuanda Çevrimdışıdır."
                        stop trigger
                    else:
                        message "test8"
                        if size of {teamliste.%player%::*} is greater than or equal to 15:
                            send "{@tag} &7Guild Listeniz Doludur. Guild Listenizin Kişi Sayısı: %size of {teamliste.%player%::*}%"
                            stop trigger
                        else:
                            message "test9"
                            wait 5 tick
                            loop {teamliste.%player%::*}:
                                message "test"
                                loop all players:
                                    message "test"
                                    if arg-2 is {teamliste.%loop-player%::*}: 
                                        message "Eklemeye Çalıştığınız Kişinin Guildi Bulunmaktadır" to player
                                    else:
                                        message "test2"
                                        if {kisi.%{listofguild.%player%}%} is set:
                                            message "test3"
                                            set {kisi.%{listofguild.%player%}%} to loop-value-1 +1
                                            add arg-2 to {teamliste.%{listofguild.%player%}%::*}
                                            set {listofguild.%arg-2%} to "%{listofguild.%player%}%"
                                            send "{@tag} &8Oyuncu &a%arg 2% &8%{listofguild.%player%}%'nin Guild Listesine Eklenmiştir." < dont working after test 9

**Comment by AhmetDS** [comment]
options:
    tag: &4[&6Guild&4]
command /guild [<text>] [<player>]:
    trigger:
        if arg-1 is "ekle":
            message "test5"
            arg 2 is set:
                message "test6"
                arg 2 isn't player:
                    message "test7"
                    arg 2 is offline:
                        send "{@tag} &7Eklemeye Çalıştığınız &c%arg 2% &7Şuanda Çevrimdışıdır."
                        stop trigger
                    else:
                        message "test8"
                        if size of {teamliste.%player%::*} is greater than or equal to 15:
                            send "{@tag} &7Guild Listeniz Doludur. Guild Listenizin Kişi Sayısı: %size of {teamliste.%player%::*}%"
                            stop trigger
                        else:
                            message "test9"
                            wait 5 tick
                            loop {teamliste.%player%::*}:
                                message "test"
                                loop all players:
                                    message "test"
                                    if arg-2 is {teamliste.%loop-player%::*}: 
                                        message "Eklemeye Çalıştığınız Kişinin Guildi Bulunmaktadır" to player
                                    else:
                                        message "test2"
                                        if {kisi.%{listofguild.%player%}%} is set:
                                            message "test3"
                                            set {kisi.%{listofguild.%player%}%} to loop-value-1 +1
                                            add arg-2 to {teamliste.%{listofguild.%player%}%::*}
                                            set {listofguild.%arg-2%} to "%{listofguild.%player%}%"
                                            send "{@tag} &8Oyuncu &a%arg 2% &8%{listofguild.%player%}%'nin Guild Listesine Eklenmiştir."

**Comment by AhmetDS** [comment]
`options:
    tag: &4[&6Guild&4]
command /guild [<text>] [<player>]:
    trigger:
        if arg-1 is "ekle":
            message "test5"
            arg 2 is set:
                message "test6"
                arg 2 isn't player:
                    message "test7"
                    arg 2 is offline:
                        send "{@tag} &7Eklemeye Çalıştığınız &c%arg 2% &7Şuanda Çevrimdışıdır."
                        stop trigger
                    else:
                        message "test8"
                        if size of {teamliste.%player%::*} is greater than or equal to 15:
                            send "{@tag} &7Guild Listeniz Doludur. Guild Listenizin Kişi Sayısı: %size of {teamliste.%player%::*}%"
                            stop trigger
                        else:
                            message "test9"
                            wait 5 tick
                            loop {teamliste.%player%::*}:
                                message "test"
                                loop all players:
                                    message "test"
                                    if arg-2 is {teamliste.%loop-player%::*}: 
                                        message "Eklemeye Çalıştığınız Kişinin Guildi Bulunmaktadır" to player
                                    else:
                                        message "test2"
                                        if {kisi.%{listofguild.%player%}%} is set:
                                            message "test3"
                                            set {kisi.%{listofguild.%player%}%} to loop-value-1 +1
                                            add arg-2 to {teamliste.%{listofguild.%player%}%::*}
                                            set {listofguild.%arg-2%} to "%{listofguild.%player%}%"
                                            send "{@tag} &8Oyuncu &a%arg 2% &8%{listofguild.%player%}%'nin Guild Listesine Eklenmiştir."`dont working after test 9

**Comment by AhmetDS** [comment]
https://hastebin.com/surupiniku.cpp

**Comment by TheBentoBox** [comment]
Looking at your code, I believe this to be user error and there are a ton of code quality issues, so this isn't the place for it. If you need help writing scripts, use the [skUnity forums](https://forums.skunity.com/). This is the place to either report bugs or suggest features for Skript itself -- the plugin, not your own code.

Just for some tips:
* If you're enforcing that the arguments should be set, there's no reason to make them optional. Remove the []'s from around them.
* To check if a player is in the list you'd do `if {teamlist.%loop-player%::*} contains arg-2`. You're directly comparing a list to a single object which rarely makes sense.
* At least try to avoid going nine indentation levels deep in your command trigger.

**Comment by Snow-Pyon** [comment]
Accidentally opened it somehow. Sorry for the inconvenience.
