### ISSUE TITLE
Suggestion : read the result of a condition

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#1468]
Hi, It's a bit hard to explain so this is some exemples that does not work, but they should be :

```
set {_test} to boolean target block is not water
set {_test} to boolean 1 = 1
set {_test} to boolean player is alive
```
 
This will allow to store the boolean result of a condition, and will permit to create cool stuffs like :

```
function AND(conditions: booleans):
function OR(conditions: booleans):
```

ex : `if AND(boolean {_target} is set, boolean player is op, boolean distance between {_target} and player < 3) is true:`

I propose the syntax : [the|return|evaluate] boolean [of] %condition%

**Comment by TheBentoBox** [comment]
Basically, you want all conditions to be useable as expressions. I believe this is a desire the devs have going forward, so it's not a bad idea. For now, you can use the [ternary expression](http://skriptlang.github.io/Skript/expressions#ExprTernary) added recently, e.g. `set {_test} to true if target block is not water else false`.

**Comment by Nicofisi** [comment]
I couldn't agree more that this is needed - a long term solution for skript 3.0 would be to replace conditions with boolean expressions, and a solution for now would be exactly what's proposed here. Although in my opinion `whether %condition%` would be a nicer syntax, for example `set {_x} to whether player is banned`

**Comment by Nicofisi** [comment]
How about just an expression with a pattern of `.*` and a return type of boolean, trying to parse the given text as a condition in the init method?

**Comment by bensku** [comment]
Performance hit might be quite significant, but if it isn't, I suppose we could do that.

**Comment by Nicofisi** [comment]
Skript would try to parse it after all the other expressions so it would only slow down scripts with broken syntax (or of course scripts that use this intentionally, so yeah, the performance aspect would need to be tested indeed).

**Comment by Anarchick** [comment]
Hey, I have found this : 
`set {_test} to check [player is alive #return a boolean's type]`
Wich works ! it's a sQuerry stuff, but it's maybe more interesting to have this in SkriptLang

**Comment by TheBentoBox** [comment]
Like I said above, you could do that in vanilla Skript already with the ternaries that were added recently, it'd be `set {_test} to true if player is alive else false`. This conversation is more about a shorthand way to do that specific ternary (such as `set {_test} to whether player is alive`)

**Comment by Wealthyturtle** [comment]
Closing in favor of #2207
