### ISSUE TITLE
event-slot can't be compared with integers.

### ISSUE THREAD

**Issue by KingAlterIV** [SkriptLang/Skript#1469]
A error/bug that somewhat popped up after the inventory update (atleast for me).

**Code**
```
on inventory click:
	broadcast "%event-slot% %index of event-slot%"
	if event-slot is 1:
		broadcast "slot 1!"
	if index of event-slot is 2:
		broadcast "slot 2!"
```

**Explanation**
`event-slot` can't be compared because its returning the inventory of someone (`inventory slot <number> of <inventory holder>`). `index of event-slot` returns the slot number, (slot `<number>`).

**Other information**
Software: Using a PaperSpigot fork (not TacoSpigot)
Software version: 1.12.2
Skript version: (dev)36

**Comment by TheLimeGlass** [comment]
`index of event-slot`

**Comment by TheLimeGlass** [comment]
There already are converters.
