### ISSUE TITLE
Bug: incorrect %raw name%s (for 1.12)

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1474]
Skript dev37c
Spigot 1.12.1

The `raw name of %item%` expression returns `minecraft:stained_clay`, the correct return would be `minecraft:stained_hardened_clay`

I will look for some more off raw names and post them here if i can find any

/edit:
More:
Correct: `minecraft:stone_slab`, Actual return: `minecraft:step`
Correct: `minecraft:cobblestone_wall`, Actual return: `minecraft:cobble_wall`
Correct: `minecraft:tallgrass`, Actual return: `minecraft:long_grass`

**Comment by Blueyescat** [comment]
https://github.com/SkriptLang/Skript/issues/520
