### ISSUE TITLE
Putting Skript Releases on Spigot?

### ISSUE THREAD

**Issue by RoboBlawck** [SkriptLang/Skript#1475]
As quoted from a thread on [skUnity](https://forums.skunity.com/threads/putting-skript-releases-on-spigot.7923/#post-34292)

> First of all I would like to apologize in advance if I had posted this request in the wrong section. I'm really new to Skript and skUnity in general and would like to implement it in my server.
> 
> However,
> 
> The server hosting that I use (Aternos) does not allow any plugins that are not officially on bukkit or spigot. This presents a problem as any server owner using Aternos cannot install Skript past 2.1.2(since while the official bukkit website does have Skript, the version is extremely outdated). 
> 
> That being said, is it possible then to place Skript into Spigot as a resource? I know that the Skript we know today is merely a forked version since the official author discontinued it, which may cause some legal problems, but can that issue be remedied simply by asking Njol for permission to put the forked releases on Spigot?
> 
> If we can somehow manage to put Skript onto Spigot, every server owner on behalf of Aternos would thank you. Thanks for reading.

Edit: Specifically, Aternos will not allow any plugins that are not "directly available there", which basically means that even if a Spigot resource were to be added into the resource, the plugin will not be available unless it is directly uploaded to Spigot's servers.

**Comment by ShaneBeee** [comment]
I forgot to mention on SkUnity when i replied to you but 
```
I know that the Skript we know today is merely a forked version since the official author discontinued it, which may cause some legal problems, but can that issue be remedied simply by asking Njol for permission to put the forked releases on Spigot?
```
There is no legal issue here since Skript is using the GNU license, and its an open source project, that anyone can freely fork and post.

**Comment by RoboBlawck** [comment]
I see. That's a relief since there won't be any legal ramifications.

**Comment by Blueyescat** [comment]
Skript will be released on Spigot when Skript 2.3 comes out.

But you shouldn't use Aternos since it is just bad ¯\\\_(ツ\)_/¯ Serveromat is better.

**Comment by TheLimeGlass** [comment]
Close

**Comment by SirAquapyr0** [comment]
So nobody knows ?
