### ISSUE TITLE
Variable not recognized in a function

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#1480]
Spigot : 1.8.8
Skript : 2.2-dev25

When running this code
(where {prefix.%player's world%} is the prefix of the world of the player, for my chat)
`function test(p: player):
	send "%{prefix.%{_p}'s world%}%"`

If it's not in a function, like this :
`send "%{prefix.%player's world%}%"`
The expression works.

But in a function this error appears :
![2018-08-19_23 49 55](https://user-images.githubusercontent.com/42092549/44313549-dbdb2300-a40a-11e8-806d-23d0d1b58991.png)

**Comment by Pikachu920** [comment]
we don't accept issue reports from old versions of skript or 1.8

**Comment by Matocolotoe** [comment]
the latest versions doesn't work and prints a lot of errors regarding variables and i won't update my server to 1.12 just to have an issue fixed '-'

**Comment by TheBentoBox** [comment]
Then you won't receive help. You can't expect people to fix issues for you when you're on a really old version of both the plugin and the game. This fork doesn't officially support 1.8; it was originally made specifically to support 1.9+.

**Comment by Matocolotoe** [comment]
Several servers are still in 1.8 so considering that it is an old version regarding multiplayer is not very true since Skript is not made for solo mode

**Comment by Blueyescat** [comment]
I don't think Spigot supports 1.8

**Comment by TheBentoBox** [comment]
[The large majority of servers are not on 1.8](https://bstats.org/global/bukkit). There are other versions of Skript available for 1.8, use those if you a stable version of Skript that works on 1.8. We're not here to support a 4 year old version.

**Comment by Matocolotoe** [comment]
"I don't think Spigot supports 1.8"
Spigot exists for versions since 1.4.6 haha

**Comment by TheBentoBox** [comment]
You're entitled to run a server on whatever version you want but this is the final word, we make no effort to make this fork run on 1.8 and that plan is not changing. If you have issues using 1.8 with newer releases, either open a pull request to fix those issues yourself or use an older version of Skript.
