### ISSUE TITLE
Duplicate Inventory Bug

### ISSUE THREAD

**Issue by RoboBlawck** [SkriptLang/Skript#1483]
Spigot version: git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Release: dev37c

When attempting to duplicate an inventory directly through set function, any commands applied to the original inventory will apply to the duplicate as well. Completely new and seperated inventories with the same parameters are not affected.

Code used:
```
function testInv():
	set {_inv} to chest inventory with 5 rows named "testInv" #Orginial inventory
	set {_copy} to {_inv} #Creating a duplicate inventory directly through set
	set {_new} to chest inventory with 5 rows named "testInv" #Duplicate inventory through chest inventory
	set slot 0 of {_inv} to dirt #Command
	set {_item} to slot 0 of {_inv} 
	set {_copyItem} to slot 0 of {_copy} 
	set {_newItem} to slot 0 of {_new}
	broadcast "Slot 0 of {_inv}: %{_item}%"
	broadcast "Slot 0 of {_copy}: %{_copyItem}%" 
	broadcast "Slot 0 of {_newItem}: %{_newItem}%" #Nothing happens

command /testInv:
	trigger:
		testInv()
```
Theoretical result of /testInv:
```
[02:11:03 INFO]: Slot 0 of {_inv}: dirt
[02:11:03 INFO]: Slot 0 of {_copy}: air
[02:11:03 INFO]: Slot 0 of {_newItem}: air
```

Experimental result of /testInv:
```
[02:11:03 INFO]: Slot 0 of {_inv}: dirt
[02:11:03 INFO]: Slot 0 of {_copy}: dirt
[02:11:03 INFO]: Slot 0 of {_newItem}: air
```

I'm guessing that  setting {_copy} to {_inv} also duplicates some sort of identifier metadata which the program used, where the completely separate inventory does not. Thoughts? Anyone know what's happening?

Edit: Fixed some formatting

**Comment by jaylawl** [comment]
That's not how that works. Imagine it like this:
```
set {_inv} to some player's inventory
set {_copy} to {_inv}
```
Both variables will just link to the player's inventory, same principle goes for virtual inventories

**Comment by Nicofisi** [comment]
@jaylawl is correct, setting a variable to something doesn't clone the value, and it isn't supposed to do it. Would break a ton of things

**Comment by Pikachu920** [comment]
with a few exceptions that is. Some things are cloned.

**Comment by Nicofisi** [comment]
*How does it happen that I miss something/am wrong 95% of the time when I reply from the phone.. lol*
