### ISSUE TITLE
Bug(?): Issues with setting ItemMeta to ItemStacks residing inside variables

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1484]
Skript dev37c
PaperSpigot 1.12

I'm unsure whether i'm doing something wrong or this could be some valuable info regarding current issues with skript's item handling.

This below code works perfectly fine if applied to items residing inside any inventory. But if it's used on items that reside inside any (local/normal) variable, it simply doesnt. I also tried to add some none-NMS related stuff, like setting unbreakable to true/false in the item meta, but that wouldn't be applied either.

I've done a lot of testing printing out the stages of the code. Everything is applied just fine, speaking of the NBT and the item meta. It just isn't applied to the skript variable.

Some test code:
```
command /test:
    trigger:
    
        set {_i} to stone sword named "well?"
        add "{Count:1b,tag:{fuck:true}}" to {_i}'s item-nbt #####this is not applied, but works as effect command
        add 1 of {_i} to command sender's inventory
```

Here's the jar i'm using this in: https://www.file-upload.net/download-13287563/jNBT.jar.html
Below code as hastebin: https://hastebin.com/uyepuqurel.java
```
package de.jaylawl.jnbt.elements.expressions;

import ch.njol.skript.Skript;
import ch.njol.skript.expressions.base.SimplePropertyExpression;
import ch.njol.skript.classes.Changer.ChangeMode;
import ch.njol.util.coll.CollectionUtils;
import org.bukkit.event.Event;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack;
import net.minecraft.server.v1_12_R1.NBTTagCompound;
import net.minecraft.server.v1_12_R1.MojangsonParseException;
import net.minecraft.server.v1_12_R1.MojangsonParser;

import javax.annotation.Nullable;

public class ExprItemNBT extends SimplePropertyExpression<ItemStack, String> {

    static {
        register(ExprItemNBT.class, String.class, "[item[stack]( |-)]nbt", "itemstack");
    }

    @Override
    @Nullable
    public String convert(ItemStack i) {
        if (i == null || i.getType() == Material.AIR) {return null;}
        NBTTagCompound nbt = new NBTTagCompound();
        CraftItemStack.asNMSCopy(i).save(nbt);
        if (nbt == null) {return null;}
        return nbt.toString();
    }

    @Override
    public Class<?>[] acceptChange(final ChangeMode mode) {
        if (mode == ChangeMode.ADD) {return CollectionUtils.array(String.class);}
        return null;
    }

    @Override
    public void change(Event e, Object[] delta, ChangeMode mode){
        if (delta != null) {
            ItemStack i = getExpr().getSingle(e);
            if (i != null || i.getType() != Material.AIR) {
                net.minecraft.server.v1_12_R1.ItemStack nms = CraftItemStack.asNMSCopy(i);
                switch (mode) {
                    case ADD:
                        NBTTagCompound nbt = new NBTTagCompound();
                        nms.save(nbt);
                        try {
                            NBTTagCompound nbtv = MojangsonParser.parse(((String) delta[0]));
                            nbt.a(nbtv);
                            nms.load(nbt);
                        } catch (MojangsonParseException excep) {
                            Skript.warning("NBT parse error: " + excep.getMessage());
                        }
                        break;
                    default:
                        assert false;
                }
                i.setItemMeta(CraftItemStack.asBukkitCopy(nms).getItemMeta());
            }
        }
    }

    @Override
    protected String getPropertyName() {
        return "itemstack nbt";
    }

    @Override
    public Class<? extends String> getReturnType() {
        return String.class;
    }
}
```

**Comment by Pikachu920** [comment]
http://github.com/Pikachu920/NBTAddon for examples

**Comment by jaylawl** [comment]
I think you either pasted the wrong link or you didn't spend any more than 2 seconds to read over my post.

**Comment by bensku** [comment]
Skript serializes ItemMeta to variables, and apparently that causes loss of some data. I'm unsure how this could be fixed without using NMS code.

**Comment by Pikachu920** [comment]
I closed it because I couldn't reproduce the unbreakable issue, sorry I didn't mention that.
![image](https://user-images.githubusercontent.com/28607612/44596606-65378000-a792-11e8-96a3-bacfad4c4686.png)
are you sure you are dealing with itemmeta correctly in regards to the unbreakable thing? It should look something like this:
```
ItemMeta meta = item.getItemMeta();
// manipulate meta
item.setItemMeta(meta);
```
because the meta from ItemStack#getItemMeta is actually a clone. As for the NMS related stuff, there's not much we can do about it... using NMS typically comes with potentially unexpected behavior everywhere. I'm pretty sure NBT isn't stored in ItemMeta btw.

**Comment by jaylawl** [comment]
Yeah, funny enough, the itemmeta contains the NBT: https://snag.gy/l60qZV.jpg

I realize Skript doesn't touch NMS, and sorry if i made it sound that way, but im not asking to do otherwise. My original post was solely about the thing not working on itemstacks saved in variables.

**Comment by jaylawl** [comment]
@bensku i just "fixed" this...
This is related to some other issue, my code actually works fine.

```
command /test:
    trigger:
        set {_i} to "stone sword" parsed as item
        add "{test:true,kek:false,somevalue:213,yes:false,string:ssssss}" to {_i}'s item-nbt
        add 1 of {_i} to command sender's inventory```
```

The emphasis is on "parsed as item". Whereas `set {_i} to stone sword` from earlier would not work. This is the same issue where setting an item's name would not work.

**Comment by bensku** [comment]
Oh. I thought it only contained some *specific* NBT whitelisted in CraftBukkit source code. Might be that I'm mistaken. Glad to hear you got it working anyway.

Some of bugs you linked should be (partially) fixed for next release. Will take a while to get that on 1.12, at the moment it is buggy even on 1.13.

**Comment by Goetheus** [comment]
Hi everybody!
I think it's the same problem (2.2-dev37c):
```
set {_object} to paper #or to ("paper" parsed as item)
set {_var} to {_object}
set {_object} to {_var} #the object is lost
```
```
add {_object} to {_var::*}
loop {_var::*}:
    broadcast "%loop-value%" #the vanilla name of object appears (not display name)
    set {_object} to loop-value #the object is lost
```
In all cases, the all nbt is lost when we arrive to get the object with a brunch of parses everywhere.

I hope it will be fixed!
Thank you for all! <3

**Comment by Pikachu920** [comment]
@Goetheus after i looked into this further it seems to be caused mostly by how jNBT is written and a dumb parser

**Comment by jaylawl** [comment]
Nbt is stored as itemmeta, this should have nothing to do with my shitty addon

**Comment by Pikachu920** [comment]
it is because of how you have 3 separate expressions and not one multi-type expr
 The parser just takes the first matching expr because a variable's return type is unknown and thus it ends up matching thr wrong one and so it is null. That's my guess anyway.

**Comment by bensku** [comment]
It is quite pointless to try to figure out what is wrong without new aliases, because almost everything relevant got rewritten for them. I recommend you test with 2.3 development releases when they're starting to get a bit more stable.

**Comment by Goetheus** [comment]
@Pikachu920 In my last post, I do not use jNBT. It was only with skript.
jNBT is the first Addon from @jaylawl and it's the only functional nbt addon for skript too! Help him to levelup :P
@bensku Ok! I'll wait for stable dev in 1.13 ;) Good luck! I send you good waves 💌
