### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by titustitus98** [SkriptLang/Skript#1491]
help how can i fix this?
28.08 13:01:30 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1514)
28.08 13:01:30 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1766)
28.08 13:01:30 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1799)
28.08 13:01:30 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:264)
28.08 13:01:30 [Server] ERROR #!#! ch.njol.skript.SkriptAPIException: No class info found for player'
28.08 13:01:30 [Server] ERROR #!#! Stack trace:
28.08 13:01:30 [Server] ERROR #!#! 
28.08 13:01:30 [Server] ERROR #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
28.08 13:01:30 [Server] ERROR #!#! nor it will work, unless you switch to supported platform.
28.08 13:01:30 [Server] ERROR #!#! Other versions might work, but since you're getting this error message something is NOT working,
28.08 13:01:30 [Server] ERROR #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
28.08 13:01:30 [Server] ERROR #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
28.08 13:01:30 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
28.08 13:01:30 [Server] ERROR #!#! Something went horribly wrong with Skript.
28.08 13:01:30 [Server] ERROR #!#! 
28.08 13:01:30 [Server] ERROR #!#! Could not load commands.sk
28.08 13:01:30 [Server] ERROR #!#! [Skript] Severe Error:
28.08 13:01:30 [Server] ERROR #!#!

**Comment by jaylawl** [comment]
You only posted half of your error message, please post the full one. Also helpful would be to know what script you were using when this error happened, please also post the full related script(s).

**Comment by Pikachu920** [comment]
Issue with skRayFall, also unsupported game version

**Comment by titustitus98** [comment]
idk what the issue is with skRayFall is and my server currently is in 1.8.8 should i update it in 1.8.9?

**Comment by jaylawl** [comment]
```28.08 13:01:30 [Server] ERROR #!#! Other versions might work, but since you're getting this error message something is NOT working,
28.08 13:01:30 [Server] ERROR #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
28.08 13:01:30 [Server] ERROR #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).```

This is from your error message. You need Spigot 1.9 or newer.

About issues with SkRayFall you must address the author of that add-on here: https://github.com/eyesniper2/skRayFall/issues
But not if you're using 1.8, because that's simply not supported

**Comment by titustitus98** [comment]
so which skript version should i use?

**Comment by jaylawl** [comment]
You can browse for compatible versions here: https://github.com/SkriptLang/Skript/releases
