### ISSUE TITLE
Blocks with states are missing names

### ISSUE THREAD

**Issue by bensku** [SkriptLang/Skript#1503]
Blocks with states that are missing from aliases do not take name of closest corresponding alias, as they should. As result, raw MATERIAL_NAMES may be returned.

**Comment by Pikachu920** [comment]
why not extend the default state functionally to the aliases file itself

**Comment by bensku** [comment]
I did exactly that; aliases which specify no block states do not have them. However, even when some block states are not specified, we want to match the closest aliases possible. Partial equality checks for Bukkit BlockData are *not* supported; it needs code specific for all types of block data that need them.
