### ISSUE TITLE
Multiple lines of lore not working

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1506]
So referring to my last Issue not being able name items, I had to use my little parsing cheat to make a new item.
(Skript version 2.3-alpha1)
Basically multiple lines of lore won't work.

When doing so I can give it 1 line of lore
```
command /test:
	trigger:
		set {_test} to "diamond sword" parsed as item
		enchant {_test} with sharpness 5
		set lore of {_test} to "test"
		give player 1 of {_test}
```
Works like a charm, but If I set certain lines
```
command /test:
	trigger:
		set {_test} to "diamond sword" parsed as item
		enchant {_test} with sharpness 5
		set 1st line of lore of {_test} to "TEST TEST"
		give player 1 of {_test}
```
It throws this console error, and doesn't give the player said item
https://pastebin.com/QW8G24CQ
(Sorry I was going to use hastebin but it doesn't seem to want to save for me)

**Comment by Nicofisi** [comment]
Hmm, I was sure I tested this throughout, apparently not really. Gonna investigate tomorrow if I find time. Does the enchant effect change anything?

**Comment by ShaneBeee** [comment]
Yes, the enchant effect works (I probably should have removed that for this issue, I just had it on my test skript)

**Comment by TheMemeGqd** [comment]
ddd
