### ISSUE TITLE
"on rightclick on chest" -error 

### ISSUE THREAD

**Issue by nikkedoy98** [SkriptLang/Skript#1507]
`on rightclick on chest:
    message "Hay ma boi"`

Problem is. When chest isn't looking towards north, it does not register right clicks
but if chest looking towards north, then it will register clicks!

**Comment by Nicofisi** [comment]
@nikkedoy98 skript version? server version?

**Comment by nikkedoy98** [comment]
Skript version: 2.3-alpha1
Server version: Spigot-2440e18-60d7982 (or as i say: Spigot 1.13.1 BETA)

**Comment by TheBentoBox** [comment]
Sounds like an alias issue with how Skript is currently handling default values (it doesn't like to freely match them to any state of the block).
