### ISSUE TITLE
SkRayFall error

### ISSUE THREAD

**Issue by itaquito** [SkriptLang/Skript#1510]
Hey! I updated skript and now I get an error of SkRayFall, I dont know if its skript fault or SkRayFall fault.

https://pastebin.com/hbFx1sfe

Also when I try to reload Skript it shows me another error.

https://pastebin.com/TbjS1ds9

**Comment by TheBentoBox** [comment]
The alpha builds don't support versions before 1.13 yet. Wait until one is available that support 1.12 and read the release notes in full from now on:
![image](https://user-images.githubusercontent.com/6902229/45130450-b8c4a900-b156-11e8-9b3c-b6da73ecc6c0.png)
