### ISSUE TITLE
Cannot load variables before config

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1513]
Skript 2.3-alpha2
Paper 1.13.1 snapshot

<img width="499" alt="Untitled" src="https://user-images.githubusercontent.com/16087552/213839986-44ecfd40-d279-4496-9b29-f0cf12a5413b.png">

i deleted everything but the `Skript/scripts` folder when upgrading to alpha2. No matter how often i reboot the localhost, it will always print this complain and not generate a new config.sk

**Comment by TheBentoBox** [comment]
Coulda sworn we had an issue for this but I don't see it. It's probably more of an enhancement than a bug since this technically is not meant to be supported as far as I know, but it should definitely be changed at some point.

**Comment by Blueyescat** [comment]
Also change the title ^^

**Comment by TheLimeGlass** [comment]
This is a bug, it shouldn't be happening. Simple fix aswell.

**Comment by UnderscoreTud** [comment]
I'm not sure if this is fixed or not, but I cannot replicate this on my end

**Comment by TheLimeGlass** [comment]
![canvas](https://user-images.githubusercontent.com/16087552/213839932-80f17486-a4cd-431c-8153-0408f5e4b9bb.png)

**Comment by TheLimeGlass** [comment]
<img width="499" alt="Untitled" src="https://user-images.githubusercontent.com/16087552/213839972-d4b8228b-4785-4682-8967-e0ec923e4953.png">

**Comment by TheLimeGlass** [comment]
config.sk was not generating properly. This has since been fixed.
