### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#1517]
Spigot 1.13.1
Skript 2.3-alpha2

Which file(s) determine the aliases?
```
aliases-english.sk
```
or
```
plugins/Skript-releases/2.3-alpha2/aliases-english:
brewing.sk   combat.sk	    foodstuffs.sk	   misc.sk   README.md	  test.sk   transportation.sk	  z-click-events.sk
building.sk  decoration.sk  +global-variations.sk  other.sk  redstone.sk  tools.sk  z-block-placement.sk
```

Do they need to exist in plugins/Skript/ or are they read from the JAR if they don't exist?

**Comment by TheBentoBox** [comment]
This isn't really an issue report, this probably should have been asked in one of the Discord servers or something.

The default aliases are loaded from the `aliases-english` folder within the JAR itself, not the Skript plugin folder.

**Comment by SlimeDog** [comment]
Sorry. I stay away from Discord.
