### ISSUE TITLE
Summary of some issues with the current aliases

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#1518]
There are a few notable issues I'm currently aware of with the current way the aliases work. I've described most of these issues already in Discord but they're not documented in the issues. I'm testing on 2.3-alpha2 with no add-ons.

1. If a block has a state that is NOT defined in the aliases AND the unsupported state is not currently set to its default value for that block, it will return the material name when running something like `send "%target block%"`. This goes for ANY block with an unsupported state. Examples of such unsupported blocks or states include:
  - Multiple blocks with an `age` state that help control growth (cactuses and kelp, crops are supported)
  - Any block with a directional boolean state (such as `north` or `down`) to imply connectivity (all fences, large mushroom blocks, chorus plant, cobble walls, glass panes, iron bars, vines...)
  - Droppers (`triggered` state)
  - Fence gates (`in wall`)
  - Probably more

Bensku and I agreed in Discord that for now the best way to handle this is probably manually setting the state in Java. If that solves the issue appropriately it's probably better than having an alias for everything since it would introduce thousands of aliases that would likely never be used.

2. An issue with the above solution, though -- blocks where we're manually changing block states to support those that aren't in the aliases OR blocks who match the above criteria (that have an unsupported state set to a non-default value, and thus are returning a material) are failing any comparison:
![image](https://user-images.githubusercontent.com/6902229/45137401-79a65000-b176-11e8-81fa-a13f8e5ac932.png)
Here, you can see the oak leaves are failing a comparison which should obviously pass. This is perhaps because we're explicitly modifying their state in Java. We've also discussed this in Discord and came to the conclusion that the target block and alias input comparison could be updated to be done using [the `matches()` method of the BlockData class](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/BlockData.html#matches-org.bukkit.block.data.BlockData-). The basic process would be:
- Get the block state string for the alias they specify
- Create a `BlockState` object from the alias's state string using [`Server.createBlockData(string)`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Server.html#createBlockData-java.lang.String-)
- Compare it with the block data of the compared block with `compared.getState().getBlockData().matches(aliasData)` (where `compared` is the block you're comparing against and `aliasData` is the `BlockData` object created from the matched alias's block state string)

Again, another option for all of this is to just support EVERYTHING (all states on all blocks) in the aliases. This is a memory and parse-time concern, but it does, I believe, fix both of these issues. I'm totally fine with doing this if it's what we want.

Will add more issues if I come across them, cheers.

**Comment by bensku** [comment]
Using the new method introduced in 1.13.1 fixed everything.
