### ISSUE TITLE
function ExprRawName returns <none> for some specific items

### ISSUE THREAD

**Issue by RoboBlawck** [SkriptLang/Skript#1519]
Spigot: CraftBukkit version git-Spigot-0ede7d0-632449b (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
Version: 2.3-alpha2

Function ExprRawName returns none for some specific items.

Code Used:
```
command /getRawName:
	trigger:
		broadcast "%player's tool%"
		broadcast "%raw name of player's tool%"
			
command /rawTest:
	trigger:
		loop all items:
			if raw name of loop-item is a text:
				add raw name of loop-item to {_raw::*}
			else:
				add loop-item to {_none::*} 
		loop {_raw::*}:
			broadcast "%loop-value%"
		loop {_none::*}:
			broadcast "%loop-value%"
```
Holding one of the items that are without correct raw names (YELLOW_STAINED_GLASS) and getting the raw name using /getRawName results in <none>:

```
[18:43:48 INFO]: YELLOW_STAINED_GLASS_PANE
[18:43:48 INFO]: <none>
```
Using the /rawTest command to retrieve a list of all supported and non supported items of ExprRawName yielded these results:

https://pastebin.com/sM12mtiM

**Comment by RoboBlawck** [comment]
Ah, nevermind. According to the changelog for 2.3-alpha2, "some blocks do not have user-friendly names available". I guess this was what he meant.

**Comment by TheBentoBox** [comment]
This IS still a bug of sorts, and I've explained the cause to bensku but never wrote up a proper report. Cheers!
