### ISSUE TITLE
Latest 1.12 version of Skript wants you to update to the version of Skript that doesnt support 1.12

### ISSUE THREAD

**Issue by LeotomasMC** [SkriptLang/Skript#1523]
Possible Fix: Make builds have a version list, that contains all versions that are known to work, or will probably work, then make the plugin find the latest version that supports the version of the server

**Comment by bensku** [comment]
It is a bit too late to do anything now, but we should improve the updater soon so this does not happen again.

**Comment by bensku** [comment]
1.12 should be *somewhat* functional in next alpha build.

**Comment by Snow-Pyon** [comment]
It does support 1.12 now so, closing.
