### ISSUE TITLE
Skript is not working on MC 1.13.1 Spigot

### ISSUE THREAD

**Issue by RichVillage** [SkriptLang/Skript#1525]
Skript is not working on Minecraft 1.13.1 version.
Skript commands is not working, and when I try to perform Skript plugin command (ex. /skript reload) - It shows just "/skript help"
Even I enter "/skript help", it shows just "/skript help"

Please fix it.. My server want Skript a lot.

**Comment by Pikachu920** [comment]
what Skript version are you using? (you can check with /ver skript)

**Comment by RichVillage** [comment]
@Pikachu920 It is 2.3-alpha2. I download it from Skript Github release page...

**Comment by Pikachu920** [comment]
are there any errors in console? do you use add-ons?

**Comment by RichVillage** [comment]
@Pikachu920 There are no errors in console. I use add-ons: skUtilities SkMorkaz Skellett Umbaska

**Comment by Pikachu920** [comment]
try without add-ons

**Comment by RichVillage** [comment]
@Pikachu920 I see, please let me try..

**Comment by RichVillage** [comment]
@Pikachu920 I try without add-ons, but still not working.. What should I do?

**Comment by TPGamesNL** [comment]
Look at console, did Skript start correctly when starting the server or did you get any errors when executing the command?

**Comment by ShaneBeee** [comment]
"Please fix it.. My server want Skript a lot." Based on this message Im going to make a few assumptions
1) You did not read the release notes. Skript for 1.13 is not meant for production servers ... it is STRICTLY a release they put out for testing purposes, for us to help the dev time find bugs. 
2) Im going to guess you are using files from a 1.12.2 server? As the release notes say ... variables won't be upgraded properly. We have been told to use this on a fresh server and not for the purpose of upgrading a 1.12.2 server.

That being said, I would recommend going back to the Releases page and reading all the release notes.

**Comment by RichVillage** [comment]
@TPGamesNL I checked the console, nothing appeared to console. No errors when starting, and executing the commands.

@ShaneBeee I am sorry for that.. I readed the release note but I don't realize properly what "production servers" means. I am operating server with my few friends and acquaintances, not operating big server.
It is because all my poor English ability. I am really sorry..

**Comment by RichVillage** [comment]
@ShaneBeee I see.. Thank you very much to let me know that fact. Have a nice day!

**Comment by Pikachu920** [comment]
post your entire log file

**Comment by TheBentoBox** [comment]
How's it working now with the new alpha3?

**Comment by Nicofisi** [comment]
Also what's your exact server platform and version? PaperSpigot possibly? That's what we usually recommend :)

**Comment by RichVillage** [comment]
@TheBentoBox It is not working at all. I should wait for the official release..
@Nicofisi Server Version is Spigot 1.13.1-R0.1-SNAPSHOT build 1905...

**Comment by ShaneBeee** [comment]
@RichVillage  Where are you getting your spigot build from? The last spigot build is 1862
https://hub.spigotmc.org/versions/
So build 1905 has yet to exists. Maybe thats why its not loading for you.
The only OFFICIAL way to get spigot is using BuildTools.... I would suggest doing that.

**Comment by RichVillage** [comment]
@ShaneBeee I used Yive's Mirror to get spigot build...
@ALL And Thank you very much. The problem was solved when I cleared Skript plugin config folder.
Thank you very much for answering my silly question..

**Comment by ShaneBeee** [comment]
Yeah I wouldn't trust Yives... technically it is illegal for them to distribute spigot. Im surprised Mojang hasn't taken them down yet.
Also, I have heard nothing but problems from people downloading from them. The fact that they say build 1905 when that hasn't existed yet, is a red flag right there!

**Comment by RichVillage** [comment]
@ShaneBeee Oh... I didn't know about that. Thank you for letting me know.. I should replace my bukkit to officially released Spigot

**Comment by ThisIsACoolBoy** [comment]
I have the same problem.

**Comment by ThisIsACoolBoy** [comment]
i get /skript help

**Comment by ThisIsACoolBoy** [comment]
i cant understand wdym also

**Comment by ShaneBeee** [comment]
@ThisIsACoolBoy Rather than 3 separate replies to this thread, please keep it to one message. If you have more to add you can edit your message. No need to spam this topic as everyone here most likely gets emails for every reply, and I for one dont want to hear my phone ding every 10 seconds when you decide to add another 3 word reply.

**Comment by ThisIsACoolBoy** [comment]
oh ok

**Comment by ShaneBeee** [comment]
> oh ok
> but uh how do i fix this i have the same problem

We still yet to actually know what the problem is. All that's been said is "no work" and the fact that all they see is the Skript help command.

When asked for errors, the reply was "no error", which is 100% not true. When this happens, there is ALWAYS an error. But we still haven't gotten any errors.

We can't fix anything when all you guys tell us is "no work"
