### ISSUE TITLE
EffMakeSay.java does not exist 

### ISSUE THREAD

**Issue by RoboBlawck** [SkriptLang/Skript#1526]
According to the [documentation](http://skriptlang.github.io/Skript/effects.html#EffMakeSay), there should be a function called EffMakeSay that makes a player say a message. 

However, upon searching through the effects folder, it turns out that there that the file EffMakeSay.java does not exist, rendering the make say function literally impossible to use.

In fact, EffMakeSay.java does not exist anywhere at all in the source code when trying to find the file by name.

![what](https://user-images.githubusercontent.com/8304620/45271982-638edd00-b45f-11e8-9d18-2f6f5376aae8.PNG)

What is going on here?  I'm so confused as to how something like this would suddenly disappear. Any thoughts as to what may have happened?

**Comment by TheBentoBox** [comment]
It's not that weird, likely just a merge issue when bensku was merging in the 1.13 branch. It'll be an easy fix.
