### ISSUE TITLE
The Enderdragon doesnt have AI when spawned

### ISSUE THREAD

**Issue by LeotomasMC** [SkriptLang/Skript#1531]
Note: This is NOT a bug with the Script plugin. This is Vanilla behavior.

This effects whenever the enderdragon is spawned, unless you are respawning it in the end using the proper vanilla thing. the specific example of using !spawn 10 enderdragons in the Configuration for the effect command should be removed, as the dragon doesn't damage blocks when its AI is disabled.

**Comment by Nicofisi** [comment]
True, when you /summon it, it doesn't do anything either in "recent" MC versions

**Comment by TheBentoBox** [comment]
To clarify: the suggestion is to update this line from the effect commands section of the main config: 
```
#	!spawn 20 ender dragons - will destroy a large part of the world in a short time if no protection is present
```
