### ISSUE TITLE
Odd behavior of ternary using two of the same functions for both parameters of %objects%

### ISSUE THREAD

**Issue by RoboBlawck** [SkriptLang/Skript#1532]
Skript: 2.3-alpha2
Version: CraftBukkit version git-Spigot-0ede7d0-632449b (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

Ternary fails when using a function twice in both parameters of %objects%.

Consider function return:
```
function return(n: number) :: number: #Returns itself 
	return {_n} 
```

Code used:

```
command /ternary:
	trigger:
		set {_n} to return(5) if 5 = 5 else return(5)
		set {_n} to 5 if 5 = 5 else return(5)
		set {_n} to return(5) if 5 = 5 else 5
		set {_n} to tan(return(5)) if 5 = 5 else return(5)+9
		set {_n} to 5 if 5 = 5 else 5	
```
An error returns when reloading via /sk reload scripts:

> [19:47:21 ERROR]: Functions cannot be used here (or there is a problem with your arguments). (main\test.sk, line 23: set {_n} to return(5) if 5 = 5 else return(5)')

When two identical functions are placed at the same time, it returns an error. However, no errors arise from the console when only one of them are used at the time. Interestingly, when both return functions are transformed, no errors occur. When the set values are identical but are not encapsulated in a function, no errors occur either.

**Comment by TheBentoBox** [comment]
Would like someone else to verify this but setting to lowest since it's a very edge-case situation which is easy to work around. You may also be able to fix it by putting parentheses around the `5 = 5`.
