### ISSUE TITLE
while not work

### ISSUE THREAD

**Issue by UzumakiYT** [SkriptLang/Skript#1535]
```
function whiletest(p: player):
	while {_p} is online:
		broadcast "work"
		wait a second

command test:
	trigger:
		whiletest(player)


```
it will send "work" one time then it stops

```
command test:
	trigger:
		while player is online:
			broadcast "work"
			wait a second
```

works

Skript v2.3-alpha3

**Comment by ShaneBeee** [comment]
If im not mistaken this is a problem from previous version. I remember running into this when i was writing flyCard and having to make a work around... I just didnt think to report it :) GLAD YOU DID!

**Comment by Blueyescat** [comment]
https://github.com/SkriptLang/Skript/issues/1287

**Comment by bensku** [comment]
Could someone test with upcoming build (alpha5) when it is out?

**Comment by UzumakiYT** [comment]
seems to be fixed in Skript v2.3-alpha4, I will test it on alpha5 when is out.

**Comment by Nicofisi** [comment]
@UzumakiYT hey, it's out

**Comment by UzumakiYT** [comment]
seems to work fine.
