### ISSUE TITLE
Inventory click not recognized in bed

### ISSUE THREAD

**Issue by GermanMinerDE** [SkriptLang/Skript#1538]
Hey guys,

I just recognized a little problem, that might be a bug.
When a player sleeps in a bed and opens an inventory of Skript (e.g. with "open chest with x rows...") and wants to take some parts of the GUI, the "on inventory click" event does not call (and I am not able to cancel it to prevents him from taking things).

We are using Skript dev37c on 1.12.2 (it is possible, that the bug occurs with older or the newest versions too, I am not able to test, because Skript 2.3 is not available for 1.12.2. - probably you can fix it there for the future!)

**Comment by GermanMinerDE** [comment]
"on store" and "on unstore" aren't recognized too.

**Comment by ShaneBeee** [comment]
"on store" and "on unswore" aren't Skript events

As for the GUI thing when  player is in bed, I dont think that's a skript problem, thats just an unfortunate situation. I dont think spigot was meant to have a player use a GUI whilst they are in bed.
But I could be wrong!

**Comment by GermanMinerDE** [comment]
Yeah you're right. But with Skript that situation is made possible in the bed.
A packet is being called (window click), when you click in the inventory in the bed (tested).

It would be great, if Skript recognize that.

**Comment by TheBentoBox** [comment]
I need someone to confirm this on 1.13 with alpha3 before I label it. We traditionally don't accept issues for older versions at all (which dev37c technically is now) but I'll leave this for now since the 2.3 builds are super alpha.

Skript doesn't work with packets directly at all. Just because you're seeing a packet doesn't mean Spigot is firing the event, so this very well may be a Spigot-side issue, in which case it's not on us to fix it or recognize it.

**Comment by Blueyescat** [comment]
Totally Spigot-side issue and happens with Paper 1.12.2 dev37c or Paper 1.13.1 alpha-3.

Wow, it is a dangerous bug. What would be the best way to prevent that?
```vb
on packet event play_client_window_click: #MundoSK
	if player is sleeping:
		close player's inventory
```
Cancelling the event didn't do anything even if the player isn't sleeping, but looks like this does the job.

**Comment by bensku** [comment]
Likely a Spigot bug/feature, but this needs to be tested. Does Skript get any event from server?

**Comment by Blueyescat** [comment]
Hmm i noticed that when you cancel inventory clicking still you can get the item like normal but when you leave the game or try to use the item it disappears.

**Comment by TheBentoBox** [comment]
Sounds like this is a Bukkit/Minecraft issue and not something we can fix on our side.
