### ISSUE TITLE
Click on sign event doesn't work

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1540]
```
on rightclick on sign:
	send "&ceee"
	broadcast "&eeee"
on leftclick on sign:
	send "&ceee"
	broadcast "&eeee"
```

no errors, reloaded successfully, not working.
tested with skript 2.3-alpha3 on spigot 1.13.1 server

**Comment by ShaneBeee** [comment]
I just built Skript for the latest commits Bensku did.... and this problem seems to have been fixed :)

**Comment by TheBentoBox** [comment]
This is *basically* a duplicate of the block comparison issues described in #1533 and while I haven't been able to personally test a fresh build yet if Shane says it's fixed and Bensku believe it to be as well then I'm going to close this to divert conversation over to that issue.
