### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by xGlenor** [SkriptLang/Skript#1542]
I have bugs
 - player cannot build at block below: # not working
 
```
on fuel burn:
   block contains coal named "&4&lXXX"
   set the block's fuel slot to coal named "&4&lXXX"

variables:
	{cobble.%player%} = false

command /YYY:
	permission: cobbel.player
	trigger:
		if {cobble.%player%} is false:
			set {cobble.%player%} to true
			send "&e[&a&LXXX&e]&f: &a&lOFF." to player
		else:
			set {cobble.%player%} to false
			send "&e[&a&lXX&e]&f: &a&lON." to player
on mine of stone:
	player has permission "cobbel.player":
		player can build at the targeted block:
			if {cobble.%player%} is true:
				delete block
				cancel event
			else:
				stop
```

**Comment by xGlenor** [comment]
I mean, the event  player cannot build at block below does not work

**Comment by ShaneBeee** [comment]
that expression is linked into a region plugin, ie: GriefPrevention or WorldGuard
http://skriptlang.github.io/Skript/conditions.html#CondCanBuild

""Tests whether a player is allowed to build at a certain location. This condition requires a supported regions plugin to be installed.""

**Comment by xGlenor** [comment]
I have the newest WorldGuard

**Comment by ShaneBeee** [comment]
That condition is checking if a player can build in a region.

Do you have a region set for where this event is taking place?

**Comment by xGlenor** [comment]
We checked it well, in fact, if we test the condition on the plugin PreciousStones works, however, when we test it on the latest WorldGuarantine it stops working

**Comment by xGlenor** [comment]
I use Google translate

**Comment by ShaneBeee** [comment]
Which version of Skript are you running? Along with server version?

**Comment by iOshawott** [comment]
I think that the problem can be same as here https://github.com/SkriptLang/Skript/issues/1537

**Comment by xGlenor** [comment]
Skript - 2.3-alpha3
spigot-1.13.1-R0.1-SNAPSHOT-b1916.jar

**Comment by TheBentoBox** [comment]
If you are using the newest WorldGuard dev builds then they're not fully supported yet as @iOshawott said. Can you send your WorldGuard version?

**Comment by xGlenor** [comment]
WorldGuard 7.0.0-SNAPSHOT;1744-8e819f7

**Comment by TheBentoBox** [comment]
The beta versions aren't supported yet. See #1537
