### ISSUE TITLE
Can add something like goto function?

### ISSUE THREAD

**Issue by AlphaWai** [SkriptLang/Skript#1545]
Hello, I'm currently writing some scripts and I'm being annoyed with the problem that skript doesn't included some function like "goto" in C#. I don't want to copy & paste the whole code to avoid documentation error in the editing for the future. Are there some similar functions to achieve this or can you please add it? Thx a lot for your help

**Comment by Pikachu920** [comment]
you should use a function

**Comment by AlphaWai** [comment]
So I tried to make a function before, but I want to execute something in the function in a click event, and my objective is not to give a output of variable. However, a function do not allow me to use expression like "clicked block" or even "event-block", how could I fix this problem? Or how can I make this done? Thx a lot for your help.

**Comment by Pikachu920** [comment]
you pass them as arguments

**Comment by AlphaWai** [comment]
How can I do so? XD
I'm not really familiar with functions haha
