### ISSUE TITLE
'has enough space for' alias issues

### ISSUE THREAD

**Issue by GiraffeCubed** [SkriptLang/Skript#1546]
**PaperSpigot**: 1.13.1, build 271
**Skript**: 2.3-alpha3

The 'can hold' / 'has enough space for' condition expects "every" or "all" before an item alias.
Checking for "has enough space for 1 iron helmet" results in error, whilst "has enough space for every iron helmet" works as the former should.

**Error**: The condition 'can hold' can currently only be used with aliases that start with 'every' or 'all', or only represent one item. (test.sk, line 3: if player has enough space for 1 iron helmet:')

**Code**: 
command /test:

	trigger:
		if player has enough space for 1 iron helmet:
			give 1 iron helmet to player

**Comment by TheBentoBox** [comment]
Not sure if this should be low or medium priority, there seems to be a valid workaround but this is definitely not super intuitive. The provided syntax looks like it should work IMO.

**Comment by ShaneBeee** [comment]
I tested this one as well in my build of the latest commits and appears to be working just fine.
For proof I sent a video and code on the Skript-Chat discord #skript-help @ 9:31 am PST

**Comment by GiraffeCubed** [comment]
@ShaneBeee You're completely right, my bad. Thanks for the video. I built from latest commits and this is no longer an issue.

**Comment by ShaneBeee** [comment]
Hey your welcome!
I noticed a few bug reports are things that already got fixed but just not released yet. 
Im always an eager beaver and building from the latest commits!

**Comment by GiraffeCubed** [comment]
@ShaneBeee Looks like this is an issue again in Beta1. Same for you?

**Comment by ShaneBeee** [comment]
I just did a test with Beta1, no issues on my side
