### ISSUE TITLE
proposal loop-iteration / loop-increment[ation] on loop %objects% and while %condition%

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#1549]
Hi, i suggest a very small things,
the loop-iteration (also called loop increment[ation]) wich is an integer from 1 to infinite

exemple :
```
loop integers from 3 to 6:
    broadcast "%loop-number% > %loop-iteration%"
```
return "3 > 1", "4 > 2", "5 > 3" and "6 > 4"

this can work for loop %objects% and while %condition%

It's a simple shortcut for :
```
set {_n} to 1
loop integers from 3 to 6:
    broadcast "%loop-number% > %{_n}%"
    add 1 to {_n}
```

**Comment by TheBentoBox** [comment]
I feel like I saw this suggested before as `loop-count` but a quick search didn't turn up an issue. Regardless it's a good idea for sure.

**Comment by TheBentoBox** [comment]
(note I'm putting lowest because it's very easy to do a shortcut yourself as you posted, just two more lines of code, so this is pure lazy QoL).

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/862
