### ISSUE TITLE
Crash on teleport

### ISSUE THREAD

**Issue by Plutoren** [SkriptLang/Skript#1551]
Crash log seen here https://hastebin.com/owedereles.pl
Repeats the bottom part like 300 times before server crashes

Cause: A teleport during the move event. Seen here:
https://hastebin.com/ipamumasut.cpp

Issue: an "on teleport"event in another skript can't receive the event causing a crash.
https://hastebin.com/uvudubevey.cs

Temporary fix proving the issue is related to the teleport event: 
Removing the on teleport event prevents the crash 

I've been using both of these skripts for a while but recently they cause a crash 100% of the time.

Basic concept of the on-move skript, basically it is an elytra free fall game where the player flies through a tunnel and gets teleported up so they feel like they never stop, the player's velocity has to be reset after the teleport hence the on move event as opposed to every 2-3 seconds as it makes things much smoother thanks to the event.getFrom() and getTo() functions from skript mirror. If you still don't understand the elytra free fall just google it, lots of youtube videos of it.

I need the on teleport event to cancel for spectators so I can't just leave this on teleport event out of my server, any thoughts?

**Comment by ShaneBeee** [comment]
"Skript v2.2-dev36" 
Issues for skript are only accepted from the current release of Skript.... there have been 3 releases since dev36, I would recommend updating your skript version to the latest ""stable"" dev37c

**Comment by Nicofisi** [comment]
`skin` is not a type from Skript, it's from some addon - look for addon startup errors or something, and ask the dev to update their addon to the latest Skript if there are any

**Comment by Plutoren** [comment]
Well it seems my original issue was not actually fixed https://hastebin.com/muwudovoda.sql same issue as above but on the updated skript :( Let me know if you need any more info about this.

**Comment by ShaneBeee** [comment]
Its really hard to say, you are using a non Skript event "on any move" and also mixing in skript mirror.
I have used the teleport effect MANY MANY times, and never once had an issues. Currently using dev37c and the effect works.

The issue itself does not appear to be a problem with the Skript plugin or the teleport syntax. 
It just appears to be an issue with your script itself. 

IF you need assistance with your scripts you can join either the SkUnity discord or the Skript-Chat discord
Skript-Chat - https://discord.gg/V4qFVnh
Skunity - https://discord.gg/0l3WlzBPKX7WNjkf
