### ISSUE TITLE
Crash on teleport (reopened)

### ISSUE THREAD

**Issue by Plutoren** [SkriptLang/Skript#1553]
Reposting this because my previous issue was closed because I thought it was fixed after updating Skript but it was not actually.

(Updated) Crash log seen here https://hastebin.com/muwudovoda.sql
Repeats the bottom part like 300 times before server crashes

Cause: A teleport during the move event. Seen here:
https://hastebin.com/ipamumasut.cpp

Issue: an "on teleport"event in another skript can't receive the event causing a crash.
https://hastebin.com/uvudubevey.cs

Temporary fix proving the issue is related to the teleport event:
Removing the on teleport event prevents the crash

Let me know if there is any more information I can provide to help resolve this issue.

**Comment by ShaneBeee** [comment]
Check my reply in #1551

**Comment by Pikachu920** [comment]
In the future, you should just wait for someone with issue permissions to reopen the old issue
