### ISSUE TITLE
Function with return have a limitation

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#1555]
Hi, I have notice that :
```
function test() :: text:
```

can only return a text and not null, if we try to return null or something that is not a text, it will return the last correct output.

So the following code will not work, cause it will always output "test":
```
function test() :: text:
    chance of 50%:
        return "test"
    return {_null}
```

**The return should accept the output type AND the null**
**Why the last output is save on memory ?**

exemple of real interest of this change :
```
function singleYML(path: string, name: string) :: text:
    if yml path "%{_path}%" in file "plugins/PlayerStats/%{_name}%.yml" exists:
        set {_value} to yml value "%{_path}%" from file "plugins/PlayerStats/%{_name}%.yml"
    if {_value} is set:
        return "%{_value}%"
    else:
        return "<none>"

command /test:
    trigger:
        set {_test} to singleYML("uuid", "%player%")
        if  {_test} is set:
            broadcast "{_test} will always be set"
```

**Comment by Blueyescat** [comment]
You are using an outdated Skript

**Comment by Anarchick** [comment]
you right, work on newer version of skript, my bad sorry. I close this issue
