### ISSUE TITLE
No new (1.13) mobs/enchantments

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1556]
Yes I know I have created a pull request for these 2 items, but I just wanted to put an issue here in the event anyone else who is using the alpha versions notices this.

It would be nice to have them added into the alpha version so alpha-testers could test things out with the new mobs and enchantments to make sure everything works as it should.

**Comment by TheBentoBox** [comment]
Missing 1.13 features are being tracked [here](https://github.com/SkriptLang/Skript/issues/1385).

**Comment by ShaneBeee** [comment]
DUR and I knew that too... crap! SORry!
