### ISSUE TITLE
on break issue with item frame

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1561]
I just created a code
```
on break:
	if {verify::%player%} is not set:
		cancel event
		send "&cTo enable block breaking use /bb"
command /bb:
	trigger:
		if {verify::%player%} is not set:
			set {verify::%player%} to true
			send "&aBlock Breaking is now ON"
		else:
			delete {verify::%player%}
			send "&cBlock Breaking turned OFF"
```
issue is that enabling/disabling block works good, but when you have this script loaded - you can't break itemframe even if block break is turned ON

tested in alphav3 since v4 is crashing my server

**Comment by ShaneBeee** [comment]
Breaking item frames aren't considered breaking a block if im not mistaken, but they are considered killing an entity so I dont actually see any bug here

**Comment by iOshawott** [comment]
@ShaneBeee but skript causes that item frames aren't working properly... so it is a bug

**Comment by ShaneBeee** [comment]
Just tested this in 1.12.2 on dev37c and 1.13.1 on alpha 4, and I can confirm that this is a weird issue.
On or Off... i can't break the frame and it won't send a message

**Comment by TheBentoBox** [comment]
Something to note is when you're breaking an item frame, if you just use `send "message"`, it's probably sending it to the item frame instead of to you; I've noticed that before that in some events you need to specify for it to send to the player. That being said, item frames probably shouldn't even be firing break events.

**Comment by Snow-Pyon** [comment]
Can someone confirm this on beta1? I haven't tested yet but from what I've seen in the code, there's no way this could be happening, looks like an user error for me.

**Comment by Efnilite** [comment]
@Snow-Pyon Confirmed, on item frames (on or off) it doesn't break, and it cancels the event with code 
```on break:
	broadcast "1"
	if {verify::%player%} is not set:
		broadcast "2"
		cancel event
		send "&cTo enable block breaking use /bb"

command /bb:
	trigger:
		if {verify::%player%} is not set:
			set {verify::%player%} to true
			send "&aBlock Breaking is now ON"
		else:
			delete {verify::%player%}
			send "&cBlock Breaking turned OFF"```
![2018-10-30_09 49 51](https://user-images.githubusercontent.com/35348263/47706357-44bff200-dc29-11e8-8984-426f8e3c0af3.png)
(on 1.12.2 with beta-1 at least)

**Comment by Snow-Pyon** [comment]
What was happening here was that we have registered an event value for the HangingEvent (a super class) but not the HangingBreakByEntityEvent, which returns the item frame for the HangingEvent#getEntity method, Skript thought that entity was the player (which wasn't the case) and then it result in the condition not being able to get the actual value of the variable.

I don't know if I explained that properly but the important thing is that it should be good to go for the next release.
