### ISSUE TITLE
something.sk<reset> BUG Glitch

### ISSUE THREAD

**Issue by AhmetDS** [SkriptLang/Skript#1571]
![2018-09-30_15 22 03](https://user-images.githubusercontent.com/42338147/46257558-a115e180-c4c4-11e8-82bf-0712e4aae3f5.png)
on inventory click event is not working ;-;

**Comment by AhmetDS** [comment]
here is skript 
``
 on inventory click:	
	if event-item is not minecart named "&6Trash Bin":
		set {1item.%player%} to event-item
	else:
		if {1item.%player%} is set:
			cancel event
			remove {1item.%player%} from player's inventory
			delete {1item.%player%}``

**Comment by AhmetDS** [comment]
sorry for my bad english

**Comment by ShaneBeee** [comment]
Which version of Skript are you using? As well as which version of spigot?

**Comment by AhmetDS** [comment]
dev36 skript version and 1.12.2 spigot

**Comment by AhmetDS** [comment]
git-Spigot-2cf50f0-2b93d83

**Comment by ShaneBeee** [comment]
Update to dev37c... the Skript team do not take issues from past versions as the bugs may have been updated... and theres been 3 updates since 36

**Comment by AhmetDS** [comment]
if i download dev37 version its have a bug/glitch player heads doesnt show on guis

**Comment by ShaneBeee** [comment]
that's not a glitch with skript, thats tuske/skQuery and you need to update those also

**Comment by AhmetDS** [comment]
last version tuske

**Comment by AhmetDS** [comment]
and using tuske

**Comment by ShaneBeee** [comment]
Tuske pikachu patch 3?

**Comment by AhmetDS** [comment]
yes

**Comment by ShaneBeee** [comment]
Check for errors in your console on startup
I currently use tuske pikachu patch 3 and dev37c and have no issues with player heads in guis

**Comment by AhmetDS** [comment]
can you test this skript 
[cioguild .txt](https://github.com/SkriptLang/Skript/files/2431826/cioguild.txt)

**Comment by AhmetDS** [comment]
its bad skript i know but we have hologui plugin

**Comment by ShaneBeee** [comment]
Im sorry but this isn't the place for help with scripts... this is used to report bugs with the latest version of the Skript plugin itself.
If you would like help with a specific script of yours please feel free to join one of the Skript help discords
Skript-Chat: https://discord.gg/V4qFVnh
SkUnity: https://discord.gg/0l3WlzBPKX7WNjkf

**Comment by AhmetDS** [comment]
but every "make gui slot {_guildplayerlist2} - 1 of player with skull of loop-value named "&6%loop-value%" to close then run player command "/guild kick %loop-value%"" make gui slot thing is dont work if it have named "." and skull of loop-value or loop-player

**Comment by bensku** [comment]
Unfortunately we do not provide support for addons here.
