### ISSUE TITLE
error log issue

### ISSUE THREAD

**Issue by titustitus98** [SkriptLang/Skript#1575]
`
02.10 19:56:30 [Server] ERROR indentation error: expected 2 tabs, but found 8 spaces (Rebirth.sk, line 104: loop {cook::*}:')
02.10 19:56:30 [Server] ERROR indentation error: expected 2 tabs, but found 12 spaces (Rebirth.sk, line 105: add 1 to {_result}')
02.10 19:56:30 [Server] ERROR indentation error: expected 2 tabs, but found 12 spaces (Rebirth.sk, line 106: set {_loop-value} to "%loop-value%" parsed as offlineplayer')
02.10 19:56:30 [Server] ERROR indentation error: expected 2 tabs, but found 12 spaces (Rebirth.sk, line 107: send "&8%loop-index%. &f&l%{_loop-value}% &8- &7Amount &e%{cookies::%loop-value%}%"')
02.10 19:56:30 [Server] WARN 'broadcast.sk' is empty
02.10 19:56:31 [Server] ERROR CLICK is not a valid sound type (Rebirth.sk, line 10: play "CLICK" to player at volume 10')
02.10 19:56:31 [Server] ERROR CLICK is not a valid sound type (Rebirth.sk, line 26: play "CLICK" to player at volume 10')
02.10 19:56:31 [Server] INFO You're currently running the latest stable version of Skript.
02.10 19:56:31 [Server] INFO 123 placeholder expansions are available on the cloud.
02.10 19:56:31 [Server] INFO 1 installed expansions have updates available.
02.10 19:56:31 [Server] ERROR There's no loop that matches 'loop-index' (Rebirth.sk, line 109: format gui slot 5 of player with diamond block named "%loop-index%. &f&l%{_loop-value}% &8- &7Amount &e%{cookies::%loop-value%}%" to do nothing')
02.10 19:56:32 [Server] ERROR Use 'attacker' and/or 'victim' in damage events (bangui.sk, line 28: if player's item is diamond sword:')
02.10 19:56:32 [Server] ERROR #!#! 
02.10 19:56:32 [Server] ERROR #!#! [Skript] Severe Error:
02.10 19:56:32 [Server] ERROR #!#! Could not load bangui.sk
02.10 19:56:32 [Server] ERROR #!#! 
02.10 19:56:32 [Server] ERROR #!#! Something went horribly wrong with Skript.
02.10 19:56:32 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
02.10 19:56:32 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
02.10 19:56:32 [Server] ERROR #!#! Here is full list of them:
02.10 19:56:32 [Server] ERROR #!#! skRayFall (https://sk.rayfall.net/) Vixio (http://vixio.space) TuSKe (github.com/Tuke-Nuke/TuSKe) SkAction Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) Reqn SharpSK skript-mirror (https://github.com/btk5h/skript-mirror) SkriptJSON skUtilities (https://tim740.github.io/) ExtrasSK WildSkript (http://www.dzikoysk.net/) SkQuery Ersatz Umbaska SkExtras 
02.10 19:56:32 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
02.10 19:56:32 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
02.10 19:56:32 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
02.10 19:56:32 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
02.10 19:56:32 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
02.10 19:56:32 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
02.10 19:56:32 [Server] ERROR #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
02.10 19:56:32 [Server] ERROR #!#! 
02.10 19:56:32 [Server] ERROR #!#! Stack trace:
02.10 19:56:32 [Server] ERROR #!#! ch.njol.skript.SkriptAPIException: No class info found for player'
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1809)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1776)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1524)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:222)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:976)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:622)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:390)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:402)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:332)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:362)
02.10 19:56:32 [Server] ERROR #!#!     at ch.njol.skript.Skript$2.run(Skript.java:508)
02.10 19:56:32 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
02.10 19:56:32 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
02.10 19:56:32 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
02.10 19:56:32 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
02.10 19:56:32 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
02.10 19:56:32 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
02.10 19:56:32 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
02.10 19:56:32 [Server] ERROR #!#! 
02.10 19:56:32 [Server] ERROR #!#! Version Information:
02.10 19:56:32 [Server] ERROR #!#!   Skript: 2.3-alpha4 (latest)
02.10 19:56:32 [Server] ERROR #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
02.10 19:56:32 [Server] ERROR #!#!   Minecraft: 1.12.2
02.10 19:56:32 [Server] ERROR #!#!   Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11)
02.10 19:56:32 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-042stab127.2
02.10 19:56:32 [Server] ERROR #!#! 
02.10 19:56:34 [Multicraft] Skipped 12 lines due to rate limit (50/s)
02.10 19:56:34 [Server] ERROR #!#! 
02.10 19:56:34 [Server] ERROR #!#! [Skript] Severe Error:
02.10 19:56:34 [Server] ERROR #!#! Could not load customenchants.sk
02.10 19:56:34 [Server] ERROR #!#! 
02.10 19:56:34 [Server] ERROR #!#! Something went horribly wrong with Skript.
02.10 19:56:34 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
02.10 19:56:34 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
02.10 19:56:34 [Server] ERROR #!#! Here is full list of them:
02.10 19:56:34 [Server] ERROR #!#! skRayFall (https://sk.rayfall.net/) Vixio (http://vixio.space) TuSKe (github.com/Tuke-Nuke/TuSKe) SkAction Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) Reqn SharpSK skript-mirror (https://github.com/btk5h/skript-mirror) SkriptJSON skUtilities (https://tim740.github.io/) ExtrasSK WildSkript (http://www.dzikoysk.net/) SkQuery Ersatz Umbaska SkExtras 
02.10 19:56:34 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
02.10 19:56:34 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
02.10 19:56:34 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
02.10 19:56:34 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
02.10 19:56:34 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
02.10 19:56:34 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
02.10 19:56:34 [Server] ERROR #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
02.10 19:56:34 [Server] ERROR #!#! 
02.10 19:56:34 [Server] ERROR #!#! Stack trace:
02.10 19:56:34 [Server] ERROR #!#! ch.njol.skript.SkriptAPIException: No class info found for player'
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1809)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1776)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1524)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:222)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:976)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:622)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:390)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:402)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:332)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:362)
02.10 19:56:34 [Server] ERROR #!#!     at ch.njol.skript.Skript$2.run(Skript.java:508)
02.10 19:56:34 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
02.10 19:56:34 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
02.10 19:56:34 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
02.10 19:56:34 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
02.10 19:56:34 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
02.10 19:56:34 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
02.10 19:56:34 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
02.10 19:56:34 [Server] ERROR #!#! 
02.10 19:56:34 [Server] ERROR #!#! Version Information:
02.10 19:56:34 [Server] ERROR #!#!   Skript: 2.3-alpha4 (latest)
02.10 19:56:34 [Server] ERROR #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
02.10 19:56:34 [Server] ERROR #!#!   Minecraft: 1.12.2
02.10 19:56:34 [Server] ERROR #!#!   Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11)
02.10 19:56:34 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-042stab127.2
02.10 19:56:34 [Server] ERROR #!#! 
02.10 19:56:34 [Server] ERROR #!#! Server platform: Spigot
`
so i keep getting this error log yet i have updated all my addons to the latest version and did the same with skript, what do  i do?

**Comment by titustitus98** [comment]
and some of my skript are working correctly yet when i reload them i get no error

**Comment by Pikachu920** [comment]
it's an issue with skrayfall or some other add-on, but definitely not vanilla

**Comment by titustitus98** [comment]
but i have updated it already why is it causing an  issue?

**Comment by bensku** [comment]
Hard to say. Might be that some of your addons are not really maintained anymore. You need to figure out which one causes this and contact its developer. Or stop using it if they cannot be contacted.

**Comment by titustitus98** [comment]
> @titustitus98 could you please link me to your Umbaska jar here, I'd like to verity the theory that it's caused by Umbaska and I'm interested about which version you use specifically

Umbaska-3.3

**Comment by Nicofisi** [comment]
> > @titustitus98 could you please link me to your Umbaska jar here, I'd like to verity the theory that it's caused by Umbaska and I'm interested about which version you use specifically
> 
> Umbaska-3.3



> could you please link me to your Umbaska jar

**Comment by titustitus98** [comment]
well i have removed umbaska from my server
