### ISSUE TITLE
error log problem

### ISSUE THREAD

**Issue by titustitus98** [SkriptLang/Skript#1580]
Hi i keep getting this log in console (https://pastebin.com/zAx8FCkf) and it says i have an outdated version of skript but the version i am using is the latest stable one after that it's alpha versions and those are only experimental how can i fix this?

**Comment by Pikachu920** [comment]
Same error as #1575, you can just ignore the update message

**Comment by titustitus98** [comment]
the thing is i keep getting that a error when i reload two skripts that depends on each other so idk how to fix that.

**Comment by ShaneBeee** [comment]
did you by any chance load one of the alpha versions and then try to downgrade back to dev37c?

**Comment by ShaneBeee** [comment]
I just noticed your other issue and me suggesting you downgraded.
Try delete your variable file, because If im not mistaken, once variables are upgrade to the new version they cant be downgraded, and in a sense your variable file is corrupt!

**Comment by titustitus98** [comment]
by variable file do you mean variables.csv ?

**Comment by ShaneBeee** [comment]
correct

**Comment by titustitus98** [comment]
hi have have done what you told me but i am still getting this error log: https://pastebin.com/xzakCtjM

**Comment by ShaneBeee** [comment]
Read thru your errors.
Most of the problems are stated in there
Like:
```
06.10 06:23:04 [Server] ERROR CLICK is not a valid sound type (Rebirth.sk, line 10: play "CLICK" to player at volume 10')
06.10 06:23:04 [Server] ERROR CLICK is not a valid sound type (Rebirth.sk, line 26: play "CLICK" to player at volume 10')
```
and
```
ERROR '::%loop-value%}%" to do nothing' is not a valid item data (Rebirth.sk, line 109: format gui slot 5 of player with diamond block named "%loop-index%. &f&l%{_loop-value}% &8- &7Amount &e%{cookies::%loop-value%}%" to do nothing')
```
that one looks like you are either missing tuske or using the wrong version
You need Tuske-Pikachu Patch 3 for Skript dev37c

```
ERROR Use 'attacker' and/or 'victim' in damage events (bangui.sk, line 28: if player's item is diamond sword:')
```
This ones obvious

```
06.10 06:23:10 [Server] ERROR #!#! Current node: set slot 1 of player's current inventory with diamond block named "&bTelepathy" (customenchants.sk, line 18)
```
this one i think needs to be
```
set slot 1 of current inventory of player to diamond... #"to" rather than "with"
```

I could go on... but Im sure you can read the errors and fix them.
This isnt a problem with skript, this is just problems with your code

**Comment by titustitus98** [comment]
and i keep getting this error when reloading these two skripts that depend on each other (https://pastebin.com/zAx8FCkf)

**Comment by ShaneBeee** [comment]
Im not entirely sure what that is from.
Are you using TuSke? And if yes, which version? (please don't say latest)

**Comment by titustitus98** [comment]
i have the latest version of it (1.8.2)

**Comment by ShaneBeee** [comment]
you will need to update as that version doesn't work on dev37c
Use pikachu's patch 
https://skripttools.net/dl/TuSKe+1.8.3-PikachuPatch-v3.jar

**Comment by titustitus98** [comment]
still sends me the same message

**Comment by ShaneBeee** [comment]
Hm... I really have no idea then. It might be one of your other addons. Check to make sure they are all up to date. 
And if you are using SkQuery... update it to SkQuery-Lime
