### ISSUE TITLE
Setting enchantment level of item.

### ISSUE THREAD

**Issue by Androv0215** [SkriptLang/Skript#1584]
Version: 2.2-dev37c
Addons:
- SkDragon
- Skellet
- SkExtras
- SkMorkaz
- SkQuery
- skript-mirror
- skript-yaml
- SkStuff

Issue:

Enchanting an item (like below) works just fine.
`enchant player's held item with sharpness 3`

But using an integer variable in its place does not (like below).
`set {_v} to 3`
`enchant player's held item with sharpness {_v}`

Skript cannot understand the syntax when the variable is used.

**Comment by ShaneBeee** [comment]
this isn't an issue with skript, you need to parse it as an enchantment

**Comment by Androv0215** [comment]
> this isn't an issue with skript, you need to parse it as an enchantment

Thank you! This post is now closed.
