### ISSUE TITLE
Rightclick holding a head

### ISSUE THREAD

**Issue by Florenthz** [SkriptLang/Skript#1586]
Hi friend, Im using alpha5 and this code doesnt works...

on leftclick holding a head:
    if name of player's held item contains "&6Obsequio":
        send the player title "&6+50 Monedas!" with subtitle "&aSaludos!" for 3 seconds
        execute console command "eco give %player% 50"
        remove 1 of player's tool from inventory of player

Also I have this problem
07.10 19:23:47 [Server] INFO Florenthz issued server command: /sk reload all
07.10 19:23:47 [Server] WARN java.lang.IllegalArgumentException: Could not parse data: minecraft:brain_coral[waterlogged=true]
07.10 19:23:47 [Server] WARN at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.newData(CraftBlockData.java:486)
07.10 19:23:47 [Server] WARN at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1809)
07.10 19:23:47 [Server] WARN at org.bukkit.Bukkit.createBlockData(Bukkit.java:1224)
07.10 19:23:47 [Server] WARN at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:320)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:246)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:646)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:603)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:118)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.Aliases.load(Aliases.java:516)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.Aliases.load(Aliases.java:502)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:485)
07.10 19:23:47 [Server] WARN at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
07.10 19:23:47 [Server] WARN at java.util.ArrayList.forEach(ArrayList.java:1249)
07.10 19:23:47 [Server] WARN at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390)
07.10 19:23:47 [Server] WARN at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
07.10 19:23:47 [Server] WARN at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
07.10 19:23:47 [Server] WARN at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
07.10 19:23:47 [Server] WARN at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
07.10 19:23:47 [Server] WARN at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
07.10 19:23:47 [Server] WARN at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:478)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:444)
07.10 19:23:47 [Server] WARN at ch.njol.skript.aliases.Aliases.load(Aliases.java:416)
07.10 19:23:47 [Server] WARN at ch.njol.skript.Skript.reloadAliases(Skript.java:889)
07.10 19:23:47 [Server] WARN at ch.njol.skript.Skript.reload(Skript.java:864)
07.10 19:23:47 [Server] WARN at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:154)
07.10 19:23:47 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
07.10 19:23:47 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)

Greetings friend

**Comment by ShaneBeee** [comment]
"head" isnt an item, use "player head" instead

```
directionals after flattening:
	minecraft version = 1.13 or newer
	skeleton (skull|head) item¦s = minecraft:skeleton_skull
	wither skeleton (skull|head) item¦s = minecraft:wither_skeleton_skull
	zombie (head|skull) item¦s = minecraft:zombie_head
	player (head|skull) item¦s = minecraft:player_head
	creeper (head|skull) item¦s = minecraft:creeper_head
	[ender[ ]]dragon (head|skull) item¦s = minecraft:dragon_head
```
