### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1598]
@bensku before you go and release this, is it too late to give some feedback on the docs?
I just generated them.... the text seems a bit large (on the left sidebar, just a TINY bit too big), plus there's some issues with scrolling where things at the bottom appear to be cut off

#### Some other things:
- That brown color, are you sure thats the color you want?
- I noticed that when you click on anything in the left-sidebar... the top bar disappears 
- The "text" page, is missing all the boxes, so all the text is just looks scattered around the bottom half there

#### Images:
This image is showing how the bottom few lines, i can not scroll down that far.
It's also showing how the formatted boxes are all missing
![](https://i.imgur.com/jamjaa2.png)

These 2 images show, if I click on something in the left-sidebar, the title bar from the top is removed and I cant get it back (unless I go "back" a page)
![](https://i.imgur.com/VZmsxUM.png)
![](https://i.imgur.com/N6JKp2t.png)

**Comment by bensku** [comment]
What browser are you using? The text tutorial formatting is a known issue which I'm probably going to in some future release instead of right now. However, I cannot seem to make the top bar disappear on either Firefox or Chrome. Do note that old versions of browsers and Interner Explorer are not supported.

**Comment by bensku** [comment]
While investigating this, I found out about one other, rather serious bug. I managed to mostly fix it, though the CSS looks horrible as result. Both Chrome and Firefox display pages in same way, so it should be ok for now.

**Comment by ShaneBeee** [comment]
I use Safari (on a mac). I tested with Chrome and it works fine on Chrome, I guess these problems are only on Safari.

I just downloaded the official beta1, and updated my doc templates and regenerated the docs. The top bar is no longer disappearing. So thats good. 
There appears to be a blank gap at the bottom. Not sure if that was on purpose or not.
And I'm still experiencing an issue with the not being able to scroll up to the top properly. Its like the top bar is covering up whatever words are at the top of the screen.

**Comment by ShaneBeee** [comment]
> I'm unfortunately unable to test with Safari, so unless someone else fixes issues with it, they're unlikely to be fixed.
> 
> That being said, the positioning of top level elements (side bar, top bar, content) is a bit unreliable at the moment. Hard to say if I'm doing something wrong or if I just hit browser bugs, but in any case they'll need some work in future.

Thanks for letting me know. It's not the end of the world, that's for sure. And I'm probably one of very very few people using mac (safari).

**Comment by ShaneBeee** [comment]
@bensku 
Okay I found a fix for this. I test it on both a windows computer (using Chrome) and my mac (using safari and chrome)
It fixes the issue on my mac, and seems to have no affect on windows (meaning it doesn't break anything on windows)
I created a test set of docs so you can see it in action [HERE](https://shanebee.tk/test/)

See lines 89 and 120 [style.css](https://cdn.discordapp.com/attachments/358658268341731329/517839277158039552/styles.css)

#### Before (on my mac)
![](https://i.imgur.com/Rq3ZJtj.png)

#### After (on my mac)
![](https://i.imgur.com/ICa2kVB.png)
