### ISSUE TITLE
Improve tab completion

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1600]
Now when you have command /something [player] you can't tab-complete player's nicknames: 
in /something i<tab> you can't get iOshawott. It would be nice if this kind of enhancement will be possible :)

**Comment by TheBentoBox** [comment]
Not sure how possible it is with Skript's dynamic commands but it's definitely desirable.

**Comment by iOshawott** [comment]
weird, after some restarts of server I see that this enhancement is included (?) lol, weird

**Comment by bensku** [comment]
Player names should be tab-completable, anything else isn't at the moment. Changing this might be a good idea, though.

**Comment by iOshawott** [comment]
well, it's possible to add any autocompletion with offlineplayer argument ?

**Comment by bensku** [comment]
@Vulqa wanted text command parameters to be tab-completable as players, too. I'm not so sure this is a good idea, but it is something that should be discussed. You can use this issue to give feedback on what changes to tab completion are wanted.

**Comment by mckite** [comment]
Tab-Auto-Complete just don't work made by Skript.

Other all of  plugin's command supports Tab-Auto_complete

**Comment by JRoy** [comment]
This issue now has a ~$10 bounty:
https://www.bountysource.com/issues/64691943-improve-tab-completion

**Comment by TheLimeGlass** [comment]
Player names is currently possible. Potential closing?
