### ISSUE TITLE
Doing math on some numbers in Skript should return numbers of the same type

### ISSUE THREAD

**Issue by Nicofisi** [SkriptLang/Skript#1602]
Quote of @bensku in #1573: 
>  Integer multiplication should return an integer.

**Comment by Blueyescat** [comment]
What if you do `integer + number`?

**Comment by Snow-Pyon** [comment]
@Nicofisi it would return number.

**Comment by Blueyescat** [comment]
Yes doing math always returns a number 
![image](https://user-images.githubusercontent.com/19474570/47362170-7a6e5380-d6dc-11e8-8510-182b7b19dd59.png)

But then why this gives the "function is declared to return an integer" error?
```vb
function test() :: integer:
	return size of players
```
We can enter integer to a number expression, shouldn't this be also valid for function return types? And you can't get integer in Skript even with using **`"1" parsed as int`**, only other expressions etc. can do this. Actually what can you do with integers?

**Comment by Matocolotoe** [comment]
@Blueyescat "Integers" are actually longs and "Numbers" are doubles
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprArithmetic.java#L59-60

**Comment by Blueyescat** [comment]
everyone knows that

**Comment by Matocolotoe** [comment]
Yeah but the question is why does this class returns a Long if `integer` is true ?

**Comment by bensku** [comment]
This is just a guess, but an integer plus one might overflow if the result is kept as integer. This is much less likely if the result is stored as a long.

**Comment by Matocolotoe** [comment]
Perhaps a _real_ "integer" type could be added
