### ISSUE TITLE
[Suggestion] bStats

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1605]
So I just recently starting looking into, and adding bStats to my plugins. 
I figured it's a pretty cool system.

Anyways, I noticed Skript uses bStats, and I was wondering if there's a possibility to create a syntax, where someone could add a simple syntax to their skript which would in turn be able to register their skript as a plugin in bStats?

I realize this would involve a decent re-write to the bStats class, but maybe its easier than I think, I really don't know, but figured I would throw it out there as a suggestion.

**Comment by Nicofisi** [comment]
Actually I think implementing this should be rather easy and I agree with ShaneBeee that, if at all, then this should be in Skript, not in an addon, because who is gonna download a separate addon just to let you track how many times your script is used, hmmm...

Anyway, you caught my interest, gonna take a look at this today :)

**Comment by bensku** [comment]
Skript's existing usage of bStats will likely not help much when building syntaxes for scripts.

**Comment by Nicofisi** [comment]
@JRoy well how I imagined this was just
```
on skript load:
    register this script to bstats as "Whatever" with version "1.1"
```
not sure what can go wrong here, and it's legally okay too since the bStats class is [GNU](https://github.com/Bastian/bStats-Metrics/blob/master/LICENSE), meaning we can freely modify this. So unless someone from the bStats team explicitly tells us not to add this feature I don't really see a problem, it's the same purpose after all

**Comment by JRoy** [comment]
Yeah but I'm also sure bStats doesn't want their service spammed artificially. Have you checked their terms?

**Comment by Nicofisi** [comment]
@JRoy they have no terms so only the things obvious from law apply, like that they shouldn't be DDOSed or spammed on purpose etc ¯\\\_(ツ)\_/¯

Their motto (which is not a term of service of any sort obviously) is just "Plugin Metrics made with ❤️", and according to Wikipedia
>In computing, a plug-in (<other names>) is a software component that adds a specific feature to an existing computer program.

They don't specify that the plugins need to be written in Java, directly in Java or anything else, and please let's not start this sort of argument here again lol, "PEOPLE WHO WRITE CODE IN SKRIPT ARE NOT DEVELOPERS"

The point of bStats is to count how much different modifications to Minecraft are used - they count server with PaperSpigot, servers with Bungeecord, servers with specific Spigot, Bungee or Sponge plugins, I don't really see how scripts would "spam their service artifically". Scripts are equally valid modifications to Minecraft from my perspective.

**Comment by JRoy** [comment]
I just don't think skript developers who may be younger, un-experienced, and have no sense of morals shall have access to this type of thing. Now, if you don't care about anything I just said, we should most definitely ask the bStats team beforehand as I think it's the right thing to do. I get we can legally do it but I think that if we did this, we'd want to be on their good side.

**Comment by ShaneBeee** [comment]
> I just don't think skript developers who may be younger, un-experienced, and have no sense of morals shall have access to this type of thing. Now, if you don't care about anything I just said, we should most definitely ask the bStats team beforehand as I think it's the right thing to do. I get we can legally do it but I think that if we did this, we'd want to be on their good side.

Asking them might not be a bad idea. Right now they have 3 categories for plugins (can't remember them all) but it includes bukkit plugins, and Bungee plugins, maybe they will be so kind as to add a skript one??! That might be rather cool!

**Comment by Nicofisi** [comment]
We discussed this a bit more on Discord and yeah, I'll try to contact them first 👍

**Comment by bensku** [comment]
I'm not sure how I feel about this. Skript, without addons, does not have any networking capabilities for a very good reason: can't leak any (personally identifiable) information if you can't use network. I'd like to keep it this way. Even if custom charts were disabled, script version (arbitrary string) could be used to expose things like IP addresses.

**Comment by Nicofisi** [comment]
@bensku good point, but hey, we could just make sure that the version is a hardcoded string in the init method of the effect

**Comment by bensku** [comment]
Forcing them to be literals would indeed fix this issue. No fancy custom charts, but still probably useful *enough* stats for scripters.

**Comment by TheLimeGlass** [comment]
This is a horrible idea. Just made your own website with an addon that does this themselves. bStats was designed for Spigot plugins not to be abused by Skript developers. bStats will definitely not be on board with this unless contacting about making a script section but that is still pushing what they have been designed for. Again setting up your own platform for this wouldn't be hard.

**Comment by ShaneBeee** [comment]
Closing this due to the fact of, as stated its a horrible idea, and I agree.
