### ISSUE TITLE
EffHealth needs to be updated not to use deprecated methods

### ISSUE THREAD

**Issue by Nicofisi** [SkriptLang/Skript#1608]
https://github.com/SkriptLang/Skript/blob/7ecafe5fdc34d71263576ddd009f9addf5ee5947/src/main/java/ch/njol/skript/effects/EffHealth.java#L98

**Comment by Nicofisi** [comment]
I wonder if 
```java
i.setDurability((short) 0);
```
is the same thing as
```java
ItemMeta meta = i.getItemMeta();
if (meta instanceof Damageable) {
    ((Damageable) meta).setDamage(0)
}
```
after all durability is how many uses the thing has left (right?), and 'damage' kinda sounds like *how damaged it was*, aka much durability was removed from it, so I have no idea personally, someone would need to investigate this a bit or just know this already lol. 

Also, are all items for which i.setDurability() would have any effect instances or Damageable (now?)? Has the Damageable interface always existed?

**Comment by TheBentoBox** [comment]
Just from a purely English perspective, I'd expect "durability" to be "how many uses there are left" and "damage" to be "how many times it's been used". So something's durability is always its max durability minus its damage.

**Comment by bensku** [comment]
Remember to not break 1.12 and older while changing this.
