### ISSUE TITLE
[Suggestion] Docs "New Stuff" tab

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1610]
Hello
So I wanted to suggest a tab (or maybe another way) for the docs where a user could see all the stuff added per version. 

Example - I would click the new stuff tab, and it would show all the new triggers/conditions/effects/etc added in the latest version. Or possibly grouped by each new release.

I know that a person can see all this stuff in the release notes, but sometimes it can be hard to find the new stuff, if they dont know the exact name of the new trigger/cond/etc.

This would also be a REALLLYYYY good way, to push people using older versions of Skript into using a newer version. Let's say Bob is using Dev27, he clicks on the "New Stuff" tab and sees all the cool new stuff that's been added in all the new versions since Dev27, Bob thinks "Hey, maybe I should update, theres some cool new stuff here".... look at the good we did for Bob :) You're welcome Bob!

**Comment by AyhamAl-Ali** [comment]
This is a cool Idea I might be working on. Something with like `NEW` tag above in `RED` color in `New` tab showing latest version's new additions and the version before it possibly.

**Comment by APickledWalrus** [comment]
Closing as new live docs has this
