### ISSUE TITLE
[Suggestion] Scoreboard tags with values.

### ISSUE THREAD

**Issue by KingAlterIV** [SkriptLang/Skript#1612]
A scoreboard tag with value, like metadata & variables, but different.
I feel like this can become more useful with scoreboard tags since its like another storage type that can have 1024 tags and can persist through restarts along with death.

Syntax (feel free to change):
```
set scoreboard tag[s] %string% of %entity% to [value] %string%
add scoreboard tag[s] %string% with value %value% to %entity%
remove scoreboard tag[s] %string% from %entity%
delete scoreboard tag[s] of %entity%

%entity%'[s] scoreboard tag[s]
scoreboard tag[s] of %entity%
scoreboard tag[s] %string% of %entity%
```

Syntax examples (feel free to change)
```
command /tag:
  trigger:
    set scoreboard tag "tag" of player to "value"

command /has:
  trigger:
    if scoreboard tag "tag" of player is true:
      broadcast "%player% has scoreboard tag ""tag"" of value %scoreboard tag ""tag"" of player ? ""<none>""%!"
```

Scoreboard tag + value example (feel free to change)
```
tag:value
dead:true
bounty:5000
```

Example picture (came from jaylawl's TagAPI)
![](https://i.imgur.com/oI60pY7.png)

**Comment by UzumakiYT** [comment]
http://skriptlang.github.io/Skript/expressions.html#ExprScoreboardTags

**Comment by Blueyescat** [comment]
This is not something should be managed by Skript. I hope you know Skript already has support for scoreboard tags, so you can make that system with vanilla Skript.

**Comment by TheBentoBox** [comment]
I agree with Blue. This would basically just be a wrapper for scoreboard tag functionality and could also lead to confusion if people don't know how it works internally. It's something you can do already in vanilla Skript so if you want it just write functions that use our tag expression, e.g. (maybe not perfect):
```
function setTagValue(e: entity, tag: text, value: text):
    loop scoreboard tags of {_e}:
        if loop-value starts with "%{_tag}%:":
            remove loop-value from scoreboard tags of {_e}
            stop loop
    add "%{_tag}%:%{_value}%" to scoreboard tags of {_e}
function getTagValue(e: entity, tag: text):
    loop scoreboard tags of {_e}:
        if loop-value starts with "%{_tag}%:":
            return last (length of loop-value - length of "%{_tag}%:") characters of loop-value
function hasTagValue(e: entity, tag: text):
    loop scoreboard tags of {_e}:
        if loop-value starts with "%{_tag}%:":
            return true
    return false
--



            stop loop
```
