### ISSUE TITLE
Feature request: bottle manipulation

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#1613]
Please consider extending
> on bucket empty
> on bucket fill

to apply to bottles as well.

**Comment by ShaneBeee** [comment]
for the bottle fill, you can just use a right click event
for the empty, you can use `on consume`

**Comment by SlimeDog** [comment]
Right you are. I was confused by the explicit bucket triggers.

**Comment by SlimeDog** [comment]
Yes, that worked. Thanks.
