### ISSUE TITLE
On place water: trigger is not processed correctly

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#1614]
Spigot 1.13.1 latest
Skript 2.3-beta1

This trigger works, when a player dumps lava from a bucket:
```
on place lava:
       if world is "world_yellowdog":
               cancel the event
               send message "Lava cannot be placed here" to the player
```
This trigger does not work, when player dumps water from a bucket:
```
on place water:
       if world is "world_yellowdog":
               cancel the event
               send message "Water cannot be placed here" to the player
```

Secondarily, in both cases the bucket displays as empty in the hotbar, until some inventory manipulation is made, after which the bucket displays correctly as full.

**Comment by bensku** [comment]
Is this a new issue with 2.3 builds?

**Comment by SlimeDog** [comment]
Quick test: Both triggers work correctly with
Spigot 1.12.2 latest
Skript 2.2-dev37c
