### ISSUE TITLE
New version of skript doesnt like 1.12.2 ft. Lime

### ISSUE THREAD

**Issue by Juc70** [SkriptLang/Skript#1617]
https://pastebin.com/k3xNLLBS

https://i.imgur.com/PVAGMkc.png

Good enough

**Comment by TheLimeGlass** [comment]
Skript code:
```
set {test} to player's tool named "hi"
broadcast "%{test}%"
```
Issue: `java.lang.NoClassDefFoundError: org/bukkit/inventory/meta/Damageable`

Link: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/inventory/meta/Damageable.java

Source where error is: https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/aliases/ItemData.java#L381-L397

Cause: `org/bukkit/inventory/meta/Damageable` only 1.13, server where issue happened is 1.12.2

**Comment by TheBentoBox** [comment]
Good find/info, I'd consider this high prio considering it's a basic part of the item system that isn't compatible with even 1.12 (let alone older versions).

**Comment by Nicofisi** [comment]
:eyes: `// TODO MC<1.13 support`
https://github.com/SkriptLang/Skript/blob/24f075166a03b2a83bdd85d2607c3fde02e36dd1/src/main/java/ch/njol/skript/aliases/ItemData.java#L388

**Comment by ham1255** [comment]
rewrite skript then
