### ISSUE TITLE
Getting display name from player variable does not work

### ISSUE THREAD

**Issue by aeonlamb** [SkriptLang/Skript#1619]
Too preoccupied to test other circumstances this bug might affect right now, but the expression "display name of <player>" is broken. The following works:

```
set {_nick} to display name of player
send "%{_nick}%"
```

but the following will return < none >:

```
set {_p} to player
set {_nick} to display name of {_p}
send "%{_nick}%"
```

Trying to work around this would require saving a variable anytime someone changes their nickname just to get the latest nickname. 
Version: skript 2.3-beta1

**Comment by bensku** [comment]
Is this a new issue?

**Comment by Blueyescat** [comment]
The same code works fine for me with Skript 2.3-beta1 and Paper 1.13.1 or Skript 2.2-dev37c Paper 1.12.2.

**Comment by aeonlamb** [comment]
Sorry, I should've done more testing before sending this in. I set up a fresh server and it worked. after trying every addon I have individually, it appears this is caused by the vixio addon for some reason.
