### ISSUE TITLE
Item with lore expression removing previous meta from items

### ISSUE THREAD

**Issue by weberlepecheur** [SkriptLang/Skript#1620]
Hi

Paper 1.13.1 (or Spigot 1.13.1, i tested both of them)
Skript-2.3-beta1
SkQuery 3.6.1Lime
TuSke-1.8.2-pikachu-v3

I have an issue with lore expression (First code because is in conflict with SkQuery):
```
command /test:
	trigger:
		open virtual chest inventory with size 1 named "MENU" to player
		make a gui slot 1 of player with oak wood door named "name" with lore "lore1||lore2||lore3" to nothing
```
https://pastebin.com/kcmKuVXh

Or so I test Lore expression from Skript:
```
command /test:
	trigger:
		open virtual chest inventory with size 1 named "MENU" to player
		make a gui slot 1 of player with oak wood door named "name" with lore "lore1" and "lore2" to nothing
```
Without error I get this (the name didnt displayed):
![image](https://user-images.githubusercontent.com/18701493/47305203-03c44e00-d629-11e8-9a6c-ef5284199263.png)

**Comment by Blueyescat** [comment]
I'm pretty sure there was another issue that reports this but i can't find it.

**Comment by UzumakiYT** [comment]
https://github.com/SkriptLang/Skript/issues/1505
