### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#1623]
<img width="859" alt="untitled" src="https://user-images.githubusercontent.com/16087552/47442074-e4373d80-d76e-11e8-917a-224e6f362a31.png">
Issue is caused by the latest commit https://github.com/SkriptLang/Skript/commit/f77ed1bf94e2a2a209fcc7b6ba5f02daf9ec3413

Deleting the settings.gradle fixes the issue

Current Gradle version: 4.4

There was no settings.gradle in the git before this commit and now there is which causes this whole issue, potential mistake?

**Comment by Nicofisi** [comment]
My local branch is equal to master (last commit being f77ed1bf94e2a2a209fcc7b6ba5f02daf9ec3413) and it builds fine - it also bulids fine for @Snow-Pyon and Travis built it with no issues either.

Are you sure you used `./gradlew jar` (not `gradle jar`) and that `./gradlew --version` says `4.10` for you?

**Comment by TheLimeGlass** [comment]
Do a git clone fresh of Skript.

**Comment by Nicofisi** [comment]
Skip to 0:50 because my internet connection sucks lol 

https://nicofi.si/file/2018-10-24_17-35-14.mp4

**Comment by TheLimeGlass** [comment]
I was using `gradle build`

**Comment by Nicofisi** [comment]
Oh, then we know your issue - `gradle` runs the Gradle that you installed on your OS, not the wrapper script bound to project which uses the Gradle version specified by the project, and apparently you must have an old version of Gradle installed - please use the wrapper next time :)

**Comment by TheLimeGlass** [comment]
But It always worked until now...

@bensku

**Comment by bensku** [comment]
Gradle versions other than 4.10 are not supported. Use the wrapper; your IDE will also likely do that.

**Comment by TheLimeGlass** [comment]
Ok, that should be specified in the readme. This commit just forces thst.

**Comment by Nicofisi** [comment]
It already is specified in the readme

**Comment by bensku** [comment]
Readme instructs usage of Gradle wrapper. I suppose it could be clarified that using it is actually rather important, not just for convenience.

**Comment by TheLimeGlass** [comment]
No it doesn't

**Comment by Nicofisi** [comment]
@TheLimeGlass the code block with build instructions uses `gradlew`
![image](https://user-images.githubusercontent.com/12614053/47445242-c5f62f80-d7b8-11e8-8f23-ef03e371d24c.png)

**Comment by TheLimeGlass** [comment]
It doesn't specify that you have to use Gradle 4.10+ as I was stating, or that you have to use the wrapper as Bensku was stating. The wrapper is good because you don't need to have gradle installed for it to work, but building should still work for those who actually have and use Gradle.

Bensku answered the issue.
