### ISSUE TITLE
[Missing] Send Block Change

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1626]
Hey, just curious what happened to "Send Block Change" in 2.3 + ??
Im not sure if some effects, etc were accidentally removed/overwritten with the merge of 2.3 to 2.2 but I noticed that effect isnt in the 2.3 docs
[Dev 37c docs](https://shanebee.tk/docs/skript/2.2-dev37c/effects.html#EffSendBlockChange)

This appears to not be in the docs for 2.3

**Comment by bensku** [comment]
I'll dig it up from Git history ASAP.

**Comment by ShaneBeee** [comment]
Awesome thanks. I hadn't tested it to see if its actually missing from Skript or just from the docs. I also think there may be more missing. Might need further investigation
