### ISSUE TITLE
We should be able to parse text to a location

### ISSUE THREAD

**Issue by UzumakiYT** [SkriptLang/Skript#1632]
I know that this is not really a skript issue but now we cannot do things like 

```
command test:
	trigger:	
		teleport player to "x: 10, y: 20, z: 10 (world?)" parsed as location
```

also for some reason, skript-yaml locations are also broken.

**Comment by ShaneBeee** [comment]
you can already do this with a built in location function
http://skriptlang.github.io/Skript/functions.html#location
```
teleport player to location(10, 20, 10, world of player)
```
