### ISSUE TITLE
[Suggestion] adding event priorities to events(like skript-mirror)

### ISSUE THREAD

**Issue by fl-y** [SkriptLang/Skript#1634]
The title says all.
When creating moderately complicated damage-related RPG systems
It can get quite frustrating that every event sent to skript have to be set to a fixed priority.
Skript mirror handles it very nicely([link](https://skript-mirror.gitbook.io/docs/basics/handling-events))
But then again, the syntax gets quite confusing when trying to mix skript syntax and skript-mirror together(also the addon is still in beta and has breaking changes quite frequently).

I'm pretty sure that adding event priorities for skript events shouldn't be too hard, and also quite welcomed by heavy-skript users.

Example
`on Damage of a player with priority highest:
`

Thanks always.

**Comment by Matocolotoe** [comment]
What about that option in the main config ?

**Comment by Blueyescat** [comment]
#197
