### ISSUE TITLE
Dragon Fireball not added

### ISSUE THREAD

**Issue by Moderocky** [SkriptLang/Skript#1635]
Hi,
@TheLimeGlass told me to make an issue here, as "dragon fireball" doesn't seem to be an entity in skript currently.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/DragonFireball.html

That is the entity thing from spigot.

**Comment by ShaneBeee** [comment]
I cant label anything, but Ill start working on this. Going thru the java docs there's a few missing entities, probably not likely to be used, but its worth adding them anyways :)
