### ISSUE TITLE
Failure comparing items with alias groups

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#1642]
When comparing an item (*not* a placed block, which *does* work) against an alias group, it always fails. Example cases:
```
# While holding a diamond chestplate, sends false
send "%true if player's tool is any chestplate else false%"

# While looking at a dropped diamond chestplate
send "%true if (item of target is any chestplate) else false%"
```

I'll note that in these scenarios sending the item (e.g. `send "%player's tool%"` ) is also returning a material string instead of the actual alias name, i.e. "DIAMOND_CHESTPLATE" instead of "diamond chestplate". This may be entirely unrelated (in which case it should be a separate issue) but I figured I'd point it out here.

**Comment by Snow-Pyon** [comment]
Should be fixed for next release.
