### ISSUE TITLE
Local list "refresh" issue

### ISSUE THREAD

**Issue by Olyno** [SkriptLang/Skript#1649]
**Description:**

When a list is "refresh", the data inside is not well taken into account, and some values remain. 

**Code to reproduce:**

The code below will not work, because when you broadcast ``"&aYEP! (%{_addons::*}%)"`` SkUtilities will remain:
```vb
on load:
	set {_addons::*} to "skUtilities", "skript-yaml" and "skript-mirror"
	loop addons list:
		loop {_addons::*}:
			loop-value-1 is loop-value-2
			remove loop-value-2 from {_addons::*}
			broadcast "&aYEP! (%{_addons::*}%)"
			exit loop
```
But in this code, I "refresh" the var at the beginning, and it will tell me correctly "none" at the end (and "SkUtilities" will not remain):
```vb
on load:
	set {_addons::*} and {_addonscheck::*} to "skUtilities", "skript-yaml" and "skript-mirror"
	loop addons list:
		loop {_addons::*}:
			loop-value-1 is loop-value-2
			remove loop-value-2 from {_addons::*}
			broadcast "&aYEP! (%{_addons::*}%)"
			exit loop
```

**Skript:** tested with dev37c and 2.3-beta1
**Addons:** skript-yaml, skUtilities and skript-mirror (latest of each)
**Server:** git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) and git-Spigot-2440e18-4228a56 (MC: 1.13.1)

**Comment by Snow-Pyon** [comment]
Marked as high since it could potentially crash the server, even if setting multiple values at once isn't used as much as for worrying about it.

**Comment by Blueyescat** [comment]
@Snow-Pyon sorry, I tried without addons and it appears to be addon issue with skript-mirror and MundoSK, but only on Skript 2.3-beta1.

Note to addon devs: @TlatoaniHJ @btk5h tried with MundoSK 1.8.6-BETA.55 - skript-mirror 0.19.1 

---
But still the setting multiple list variables to a list doesn't work as excepted ^^

**Comment by Snow-Pyon** [comment]
If that's the case, I'm lowering the priority, gotta find out what could addons make for this to happen.

**Comment by bensku** [comment]
Would be nice to know what causes this, indeed.
