### ISSUE TITLE
Skript's json not working with broadcast

### ISSUE THREAD

**Issue by noftaly** [SkriptLang/Skript#1650]
As the title say, skript's Json doesn't work with broadcast...

```vb
command /testjson:
	trigger:
		broadcast "<command:/test>&b&nClick!<reset>"
```
will send `<command:/test>Click!<reset>`...

Not really intuitive and quite weird...

I'm using 2.2-dev37c, with spigot 1.12.2.
I didn't test with 1.13 and beta1...

Thank you

**Comment by JKGamerxD** [comment]
This could be implemented since all what the broadcast effect does is sending a message to all players and console. Though, it may be obvious but you'd need to update once the feature is added to get it, old versions are not supported after all.

**Comment by TPGamesNL** [comment]
Use what @Andalmere said, it's because broadcast will also send it to console which doesn't support JSON.

**Comment by noftaly** [comment]
> Use what @Andalmere said, it's because broadcast will also send it to console which doesn't support JSON.

Good point, I didn't think about that x)
Thank you ;)

**Comment by bensku** [comment]
Need to fix docs to tell about this.
