### ISSUE TITLE
Sponge support

### ISSUE THREAD

**Issue by CrazyWords1** [SkriptLang/Skript#1651]
Hello, answer on 1 question please
Do you plan to add sponge support?

**Comment by Snow-Pyon** [comment]
It is planned, but it isn't going to be anytime soon. We didn't even get a stable spigot version so releasing one for Sponge would be more problems than anything.

Seeing how slow our progress are, it could easily take two years to get a completely stable version of Skript for Spigot, and then start one for Sponge.

There's still a hope though, if https://github.com/SkriptLang/skript-parser is finished, a Sponge version could be released by us or any other developer interested on implementing it.

That said, I am closing the issue.

**Comment by bensku** [comment]
Current Skript *could* probably be ported to Sponge. It would be extremely hacky and still quite time-consuming, though. It *could* happen if someone had enough time to dedicate to porting.

New Skript built on top of the new parser will support Sponge, but as said, I have no idea when it will be ready. Definitely not this year.
