### ISSUE TITLE
Tabcomplet in command

### ISSUE THREAD

**Issue by Vulqa** [SkriptLang/Skript#1659]
Hello,

I do not know if I have to post that as a report of bug or a question, but I preferred to make a report of bug in case it would turn out to be one.

When I to create a command with an argument, I cannot more tabcomplete a player in my command, has you he a new option there to be activated or something to be made ? Or is it a bug ? It worked in the last version.

Exemple of code: 
```
command /test [<Text>]:
	trigger:
		send "%arg-1%"
```

Version of skript: 2.3-beta1 
Server's version: 1.12.2

**Comment by iOshawott** [comment]
There's something to do with autocomplete I writed about it #1600 I proposed to autocomplete offlineplayer-arguments

**Comment by Snow-Pyon** [comment]
Auto-completing offline player arguments is likely not possible without killing the server's performance, so that's a no for that suggestion. The issue is open since we could enhance tab completion in Skript but not exactly due to what's being proposed.

**Comment by iOshawott** [comment]
@snow-pyon but what's about autocompleting online players with offlineplayer-argument?

**Comment by Vulqa** [comment]
@iOshawott the problem, it is because I cannot put player argument, or of offlines-player argument in my command (the command at the top is just an example) it obliges me to use a player necessarily, but I prefer to have the choice, because we can make more things for my taste with a text argument. :/ I always made like that up to the last version, and it was perfect. @Snow-Pyon it is not possible to put the former system on the new ?

**Comment by Snow-Pyon** [comment]
@Vulqa it might be possible, just that there are more important things to be handled right now. This is due to the massive changes to the commands made in 1.13. Though, we could completely disable the auto-complete workaround for lower versions.

**Comment by bensku** [comment]
It is definitely possible, and relatively easy to do. Just need to add OfflinePlayer in relevant if statement.
