### ISSUE TITLE
On region enter is broken in new release

### ISSUE THREAD

**Issue by Gerlif** [SkriptLang/Skript#1661]
"On region enter" gives the following in console:
`ERROR Could not pass event PlayerMoveEvent to Skript v2.3-beta2`

It works fine when downgrading back to 2.3-beta1

**Comment by TheBentoBox** [comment]
What's your WorldGuard version? The version dependency was updated in beta2 so you may need a more recent release.

**Comment by iOshawott** [comment]
I just got 500 MB spam about ERROR Could not pass event PlayerMoveEvent to Skript v2.3-beta2 without on region enter skript : ( Sure, I have WG 7

back to skript beta1!

**Comment by Nicofisi** [comment]
You need to send the whole error, the whole stacktrace please

**Comment by iOshawott** [comment]
Sorry I wanted to but I cant. It broken my server and I needed to delete logs...

**Comment by Nicofisi** [comment]
Can't fix it without the whole error since it seems to work for us, huh lol

**Comment by Gerlif** [comment]
I'll try to get the logs from the crash later today, thanks for addressing the issue!

**Comment by Zzheyd** [comment]
I have same error with latest version :/

https://pastebin.com/uxHhmR5e

With only this file https://pastebin.com/py631NWJ

Hope fix soon ^^

**Comment by bensku** [comment]
WorldGuard/WorldEdit has had even more unstable API than Skript does. That is kinda bad, because unlike Skript, they do have public (outdated) API documentation available.

**Comment by Zzheyd** [comment]
Error FIXED with latest version of worlguard#1754/wordedit found here (http://builds.enginehub.org)

:)
