### ISSUE TITLE
Some errors with sandstone aliases

### ISSUE THREAD

**Issue by nikkedoy98** [SkriptLang/Skript#1663]
When you set event-block to sandstone, it changes either to sandstone, cut sandstone or chiseled sandstone.

Same happens with red sandstone.

Server info:
- PaperSpigot 1.13.2 build 425
- Skript 2.3-Beta2

Here is the demonstration skript:

```
on block break:
    tool isn't end portal frame
    give event-block to player
    chance of 15%:
        set event-block to sandstone
    else:
        set event-block to red sandstone
    cancel event

**Comment by TheBentoBox** [comment]
Good find, I found a mistake in the aliases for sandstone for 1.13. I'll make the fix now. For now, to work around it, you should be able to use `normal sandstone` instead of just `sandstone` and it will correctly place the plain sandstone.

**Comment by TheBentoBox** [comment]
beta3's alias update should fix this
