### ISSUE TITLE
compare 2 conditions

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#1665]
### Description
The console gives an error when I use `while X  is X or X is X`

### Steps to Reproduce
`while loop-entity isn't on ground or loop-entity isn't swimming:`

### Expected Behavior
Can you fix that please?

### Errors / Screenshots
`[20:05:07 ERROR]: There's no loop that matches 'loop-entity isn't on ground or loop-entity' (test.sk, line 54: while loop-entity isn't on ground or loop-entity isn't swimming:')`

### Server Information
* **Server version/platform:**       Spigot 1.13.2
* **Skript version:**                Skript 2.3 beta2 (it happens also with version 2.3 beta1)

### Additional Context
-

**Comment by Pikachu920** [comment]
unfortunately, chaining conditions is not supported
