### ISSUE TITLE
【beta 2 1.13】blockl data | Can't compare

### ISSUE THREAD

**Issue by zeibo** [SkriptLang/Skript#1666]
it's my code

`on walking on MAGENTA GLAZED TERRACOTTA:`
`    if the block below player is MAGENTA GLAZED TERRACOTTA:0:`
 `       push the player north with force 0.65`
 `       play sound "block.snow.step" with volume 0.5 and pitch 0.3 at location of player`
 `   if the block below player is MAGENTA GLAZED TERRACOTTA:1:`
 `       push the player east with force 0.65`
 `       play sound "block.snow.step" with volume 0.5 and pitch 0.3 at location of player`
 `   if the block below player is MAGENTA GLAZED TERRACOTTA:2:`
 `       push the player south with force 0.65`
 `       play sound "block.snow.step" with volume 0.5 and pitch 0.3 at location of player`
 `   if the block below player is MAGENTA GLAZED TERRACOTTA:3:`
 `       push the player west with force 0.65`
 `       play sound "block.snow.step" with volume 0.5 and pitch 0.3 at location of player`

**Comment by TheBentoBox** [comment]
Data values no longer exist in 1.13 so you can't use `:0` or anything like that. If you want to specify a direction you need to use (for example) `northward magenta glazed terracotta`.

**Comment by zeibo** [comment]
thx  it's helpful
