### ISSUE TITLE
Right click issue with boat

### ISSUE THREAD

**Issue by weberlepecheur** [SkriptLang/Skript#1668]
Hi,

Skript 2.3beta2
Paper 1.13.2-b428

 I discover an issue with the boat (all types of boat). When I right click on them with that code :
```
on right click on a boat:
	broadcast "%clicked entity%"
```
Only the spruce boat broadcast his type. And for a unknow reason, when a right click on a spruce boat skript detect that like if he was a sign (dry wall sign) and runs a skript that works with multiple signs.

![image](https://user-images.githubusercontent.com/18701493/48091754-e5ef0f80-e20a-11e8-8a47-a7274ff2c8ba.png)

I hope I have been clear in my explanations to help you for fixing this issue.

**Comment by TheBentoBox** [comment]
This is quite possibly because beta2 didn't have the updated aliases which are meant to handle the entity relation for items (which I did include for boats). I'll mark this as an aliases issue but we should test again when a fixed release with the updated aliases is posted.

**Comment by ShaneBeee** [comment]
@TheBentoBox Yesterday Snow updated the resource to include the new binary (Which includes the new/correct aliases).
I just loaded it up to test, and this issue seems to be fixed :)

**Comment by weberlepecheur** [comment]
Bug still here in beta4, when right clicking on a boat, skript detect a sign rather than a boat.

```
on right click on a sign:
	cancel event
	broadcast "Sign"

on right click on a boat:
	cancel event
	broadcast "Boat"
```

![boat](https://user-images.githubusercontent.com/18701493/49453546-a3a5f780-f7e3-11e8-984f-9842bafaa85a.jpg)

**Comment by ShaneBeee** [comment]
So i did some testing, and it appears it only happens with the spruce boat, the other 5 boats don't register as a sign. So weird.

**Comment by weberlepecheur** [comment]
So, the issue on my previous post (up there /|\ ) is fixed in beta5 BUT I found that skript doesn't recognize the other boat when clicking on them with that code :

```
on right click on a boat:
	cancel event
	broadcast "Boat"
```
It's trigger only for the **spruce boat** for the other there nothing, cancel event and broadcast dont trigger.

**Comment by Blueyescat** [comment]
```vb
on right click on a boat:
	cancel event
	broadcast "Boat"
```
Works fine with Skript 2.4-alpha3, tested on 1.12.2, 1.13.2 and 1.14.2
