### ISSUE TITLE
Problem with lore

### ISSUE THREAD

**Issue by Vulqa** [SkriptLang/Skript#1670]
### Question

Hello,

I would for example like to make a menu which will serve me to get all the hubs on my network. Once this one made I wanted to show the players connected to the hub in the description of the item which represents this one, everything works, set apart when a player disconnects or joins, thus when it is necessary to update the description of the item the item keeps its former description besides the piece of news, but once the script reload everything returns to the normal. Have you an idea of why ?

Code:
```
function menuHubs(player: player, uuid: String):
	open virtual chest inventory with 5 rows named "Changer de hub" to {_player}
	format gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 37, 38, 39, 40, 41, 42, 43 and 44 of {_player} with brown glass pane named ""
	
	set {_servers::*} to all of the bungeecord servers
	loop {_servers::*}:
		if loop-value contains "hub":
			add loop-value to {_hubs::*}
	set {_slot} to 10
	loop {_hubs::*}:
		set {_players::*} to all bungeecord players on server "%loop-value-1%"
		set {_line} to 3
		set {_hub} to green clay named "&7Serveur: &e%loop-value-1%"
		loop {_players::*}:
			set {_uuid} to network variable {api::users::%loop-value-2%::uuid}
			set line 1 of lore of {_hub} to "&7Joueur(s): &e%size of {_players::*}%"
			set line {_line} of lore of {_hub} to "&8- &a%loop-value-2% &7(%{api::users::%{_uuid}%::displayRank}%&7)"
			add 1 to {_line}
		add 1 to {_line}
		set line {_line} of lore of {_hub} to "&d» &eClique pour te connecter"
		format gui slot {_slot} of {_player} with {_hub}
```

Exemples:
- http://prntscr.com/lfaess #When i'm alone
- http://prntscr.com/lfaewo #When my second account is here (no script reload)
- http://prntscr.com/lfaf4h #When my 2 accounts are here (with script reload)

My skript's version: 2.3-beta2
My server's version: 1.12.2

**Comment by Snow-Pyon** [comment]
The problem is that you're adding a line twice

**Comment by Snow-Pyon** [comment]
The problem is that you're adding a lin

**Comment by Snow-Pyon** [comment]
The problem is that you're adding a new line twice:
```vb
loop {_players::*}:
...
  set line {_line} of lore of {_hub} to "&8- &a%loop-value-2% &7(%{api::users::%{_uuid}%::displayRank}%&7)"
  add 1 to {_line}
add 1 to {_line}
```
Here, t
