### ISSUE TITLE
2.3+ getEnchantmentTypes() returning null on prominent enchanted ItemTypes

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#1673]
### Description
The new 2.3-beta2 caused this to not return properly
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprEnchantmentLevel.java#L75

In Skript you should always handle the return and input as a Number, or else the syntax ultimately doesn't work.

### Steps to Reproduce
Just using the expression.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/16087552/48175811-cb7c6b00-e2ca-11e8-99aa-58f1692afb1c.png)

### Server Information
* **Server version/platform:** Any
* **Skript version:** 2.3-beta2

### Additional Context
The usage of Streams in Java 8 on Arrays is a pitfall aswell. They're way slower than actually just using a for loop which this should be doing.

In addition the return should not be an Integer, Double or Long, the return always has to be a Number. It's a known bug and this issue just shows an example of it.

**Comment by Snow-Pyon** [comment]
The expression works, the above error is more of a problem with the parser than anything (and I doubt changing the return type will solve anything).

And about using streams, I find them cleaner. Though, it has been proven that Streams are usually slower depending on the action, but how slow is it compared to a for loop in this specific case would be something that needs a benchmark to see whether it is actually worth it.

**Comment by TheLimeGlass** [comment]
Ok I did further testing. Here is what my test code was:
```java
@SuppressWarnings("null")
@Override
protected Number[] get(final Event e) {
	Enchantment[] enchantments = enchants.getArray(e);
	List<Number> numbers = new ArrayList<>();
	for (ItemType item : items.getArray(e)) {
		if (item == null || item.getEnchantmentTypes() == null)
			continue;
		for (EnchantmentType enchantment : item.getEnchantmentTypes()) {
			if (enchantment == null)
				continue;
			if (CollectionUtils.contains(enchantments, enchantment.getType())) {
				numbers.add(enchantment.getLevel());
			}
		}
	}
	return numbers.toArray(new Number[numbers.size()]);
}
```
For some reason it's not the syntax but the ItemType, potential issue with new aliases?

I always got null from the enchantment types, which is why you see the null checks.

I think this is an enchantment issue on ItemTypes.

**Comment by KingAlterIV** [comment]
uh... ignore that, didn't read the issue correctly. ^

**Comment by bensku** [comment]
Enchantment methods handled global item meta wrong. I fixed that, and changed how global item meta works to make future mistakes like this less likely.
