### ISSUE TITLE
Should it be like this?

### ISSUE THREAD

**Issue by wohahobg** [SkriptLang/Skript#1674]
Hello there, I am not sure if this must be for here but, I have 2 questions.

1st last night I have install whole new skript new version `[Skript] Enabling Skript v2.3-beta2`
`[08:38:14] [Craft Scheduler Thread - 2/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m You're currently running the latest stable version of Skript.[m
`

So I have two errors 1st one is from beging from when I have install the new version + new folder, note that I did not have any skript before install it. I just wanted start my own basic command, but before that I would like to know why it show this: https://gist.github.com/wohahobg/e7b78daa1f905624da53e0f7d366c4c7
and 2nd is I just start my basic commands for my server and when I reloaded the skrpt it happen this:
https://gist.github.com/wohahobg/cdb7c5bd159aafc87c49a65f6cffb75b

Here is my basic skript I just start it. https://gist.github.com/wohahobg/894130b2c795b902e581c12f513edf7f

Thanks to everyone!

**Comment by TheLimeGlass** [comment]
You don't need to call both of these, one is called when the skript loads and other is when Skript starts.
```
on skript load:
	send "&8&l[&6Basic&8&l] &eCommands is Enabled &a✔" to console
	set {basic.prefix} to "&6&lBasic &7» "
	send "&8&l[&6Basic&8&l] &eCommands prefix is set to %{basic.prefix}%" to console
	
on load:
	send "&8&l[&6Basic&8&l] &eCommands is Enabled &a✔" to console
	set {basic.prefix} to "&6&lBasic &7» "
send "&8&l[&6Basic&8&l] &eCommands prefix is set to %{basic.prefix}%" to console
```

I tested this Skript on 2.3-beta2 with all the yaml and particles disabled. Please only report errors without any addons installed.

Everything worked fine for me with modifications, and removal of addon syntax.

**Comment by TheBentoBox** [comment]
The banner issue should already be fixed in the latest aliases. Could use someone else verifying it on 1.12 but I also did so myself.

**Comment by TheBentoBox** [comment]
No response, no verification, and I believe this was fixed.
