### ISSUE TITLE
Vanilla Sound Effect doesn't produce sound when a volume isn't specified

### ISSUE THREAD

**Issue by ItsMinity** [SkriptLang/Skript#1677]
### Description
Vanilla skript sound effect no longer works. No errors. 

### Steps to Reproduce
`play sound "BLOCK_NOTE_BLOCK_BASS" at player for player`
That doesn't produce a sound. No errors. 

### Expected Behavior
Expected a sound to get produced.

### Errors / Screenshots
None

### Server Information
* **Server version/platform:**       Spigot 1.13.2 (Latest)
* **Skript version:**                2.3-beta2

**Comment by Nicofisi** [comment]
Can be edited directly on GitHub if you're or someone is sure that 1 is the right value - https://github.com/SkriptLang/Skript/blob/37cc1a3ad978aaba18496b1ae441b0908424f70b/src/main/java/ch/njol/skript/effects/EffPlaySound.java#L86-L87

**Comment by TheBentoBox** [comment]
1 is definitely the correct "default" value for both as far as vanilla is concerned. Whether Bukkit's implementation is different is another story but it would seem clear from this issue at least that volume is meant to be 1.

**Comment by TheBentoBox** [comment]
I've opened a PR with the change on the linked lines @Nicofisi . #1678
