### ISSUE TITLE
options not working with command messages

### ISSUE THREAD

**Issue by melinstagibson** [SkriptLang/Skript#1679]
```
options:
    i: "&b[&dINFO&b] &e"

command /cd:
    cooldown: 10 seconds
    cooldown message: %{@i}% test %remaining time%
    trigger:
        feed the player
```

if i use an option it uses the default permission message, it works when i replace it by a variable tho.
latest skript, paper 1.13.2

**Comment by UzumakiYT** [comment]
try 
`cooldown message: {@i} test %remaining time%`

**Comment by melinstagibson** [comment]
> try
> `cooldown message: {@i} test %remaining time%`
same issue

**Comment by ShaneBeee** [comment]
> > try
> > `cooldown message: {@i} test %remaining time%`
> 
> same issue

remove the quotes from the option, I tested this and it works:
```
options:
    i: &b[&dINFO&b] &e

command /cd:
    cooldown: 10 seconds
    cooldown message: test {@i} %remaining time%
    trigger:
        feed the player
```

**Comment by Pikachu920** [comment]
for now double the quotes and it will work
