### ISSUE TITLE
[Docs] Messed up Item Enchantments/Items of Entity section

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1680]
### Description
The area in expressions for Item Enchantments and Item of Entity is a bit messed up

### Steps to Reproduce
go here in [DOCS](http://skriptlang.github.io/Skript/expressions.html#ExprEnchantments)

### Expected Behavior
For it to be there?!?!

### Errors / Screenshots
As you can see in the picture, the Item of entity is missing its "Pattern" and "Since" (well, the since is there its just missing the pretty brown box)
![](https://i.imgur.com/SGPC1hW.png)
I think due to the fact is has no Pattern set up in the code
![](https://i.imgur.com/rhvtN9B.png)

### Server Information
None required

**Comment by TheBentoBox** [comment]
This is fixed.
