### ISSUE TITLE
Give Items with damage

### ISSUE THREAD

**Issue by RiverThrough** [SkriptLang/Skript#1682]
### Question
Hello, wanted to ask if it was still possible to give a player a damaged item in the same syntax, for example prior to 1.13 I would do:
`give shears:18 named "Custom Item" with lore "This item has 18 damage"`
that would give a player the shears with the name and lore and it would have 18 damage added to it, the reason I use this is because I have custom items through my resource pack using the damage value trick

after the 1.13 update this no longer works due to the aliases rework I'm pretty sure, I know there are ways to still accomplish this, I have already completed a solution using skript-mirror but overall it was much more simple the way it was so I thought I'd ask if this was still possible to achieve in the same line or if it will possibly be readded as an enhancement?  Thanks for reading

Edit: I should mention a big reason I loved it when it was integrated prior to 1.13 was also because it worked well across skript, it would also work as conditions, for example I could do:
`if player is holding shears:19`
so while I have found ways to give the damaged items now its still a pain in the ass having to add many lines to my scripts for condition checks and whatnot

**Comment by ShaneBeee** [comment]
Set the damage/data value of the item. 
http://skriptlang.github.io/Skript/expressions.html#ExprDurability

This is due to the change in Minecraft and the Flattening. They dropped item IDs which ended up changing how everything worked.

**Comment by bensku** [comment]
Some items still have durability. Might be useful to make an expression for setting that and returning the item, so it can be used in conditions.

**Comment by Matocolotoe** [comment]
Already possible with data values

**Comment by Snow-Pyon** [comment]
@Matocolotoe we know, the intent of this issue is to request a more direct way to use them since the `<item type>:<data value>` format doesn't work anymore, which is understandable for 1.13 but isn't that conventient for lower versions.

**Comment by Matocolotoe** [comment]
Understood +1

**Comment by PatoFrango** [comment]
I can say that it broke my whole server. it runs on 1.12 and not only it was heavily affected by this but also by calling functions with multiple parameters and having to write "and", and many other aliase "bugs". as a result, I can no longer update skript and i'll be stuck on 2.2-dev36 forever. this really, really sucks as the whole server runs on skript and heavily depends on it.

**Comment by FranKusmiruk** [comment]
@PatoFrango there's the [Damaged Item](https://skriptlang.github.io/Skript/expressions.html#ExprDamagedItem) expression that was implemented at some point, you may use that now.
