### ISSUE TITLE
Can't give item with more line of lores

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1683]
`add 2 gold nugget named "&2Szczęśliwa Moneta" with lore "&eSpełnia życzenie||&bNapraw przedmiot" to player's inventory`
it gives item with 1 line of lore &eSpełnia życzenie||&bNapraw przedmiot intead of two lines: &eSpełnia życzenie and &bNapraw przedmiot

### Server Information
* **Server version/platform:**       1.13.2 - paper
* **Skript version:**                latest

**Comment by Blueyescat** [comment]
Skript's with lore expression doesn't work with || like skQuery's expression. You use a list: `with lore "&eSpełnia życzenie" and "&bNapraw przedmiot"`

**Comment by Blueyescat** [comment]
@iOshawott can you close the issue pls
