### ISSUE TITLE
Small suggestions :P

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#1686]
Hello, I have some small suggestions...
1. If crafting/enchant/kill mob may/ succesfull summon/open give, something may... If possible a if Enderdragon killed open world2 hmm 🤔.
2. On specific coords: like summon spawn entity
3. If Player entry into selected coords summon a mob or something. I want to do a scary ^^ walk and when walking forward In some enter i want do Guardians potion the from sea on Player for 1sec like a jumpscare he he :+1: 😂

**Comment by ShaneBeee** [comment]
1) Sorry but I have no clue what you mean
2) If you are meaning spawn an entity at certain coords, that is already possible
3) This is also possible if you use a world guard region or a cuboid (i believe supported by SkQuery)

**Comment by Misio12320** [comment]
1. I want to do a enchanting table may by Skript and this enchanting table shall summon lightningbolt on specific coords with some chance. If the enchant will succesfull of course... And want to do like a hm... When I with friends kill Ender dragon it Will open 1 world which we can teleport or something... 2. Hm yeah I was meaning the lightning Bolt when the Enchant is succesfull summon it on specific coords like 20 blocks up the Player which enchanted or something :P
3. Good idea maybe...

**Comment by ShaneBeee** [comment]
Why are you posting this here?
This GitHub is for posting issues and suggestions with the Skript plugin itself.
Its not the place to post questions and to get help for your specific scripts. 
If you are looking for help, join the discords I sent you in #1684

**Comment by Misio12320** [comment]
So im suggesting here and I translate what I mean about these suggestions

**Comment by bensku** [comment]
Issue tracker is wrong place for that kind of questions.
