### ISSUE TITLE
Characters expression

### ISSUE THREAD

**Issue by JavierKasunic** [SkriptLang/Skript#169]
The first suggestion is this expression:

```
char[acter]s from "a" to "o" #Or like SkQuery `a-z`, and if I'm not wrong, it's the regex (I think).
```

With support for `random` too.

**Comment by TheLimeGlass** [comment]
Skript already has support for this. It's just a matter of an addon developer using them.

https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/registrations/EventValues.java#L68-L76

**Comment by bensku** [comment]
Event values are buggy. Very buggy.

And I'm afraid that I have no idea how that could be fixed. Skript could really use complete rewrite.

**Comment by TheBentoBox** [comment]
Not sure if this is still something you'd like to tackle in the foreseeable future Bensku.

**Comment by TheLimeGlass** [comment]
This feature is suppose to work. Like say the time of a expression is -1 meaning the past state of an event.

So a developer can make an event value for event-location using the past location in an event. Then in skript you should be able to use `past event-location` and vice versa for future event-location `future event-location`

Example https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/vehicle/VehicleMoveEvent.html the getFrom() would be the past location and the getTo() would be the future location.

I thought this feature that Skript has was the coolest feature I ever read in Skript when I found it. Then I played with it for awhile and found it didn't even work. I was really sad.

Would love to see a fix for this if you can. I have no clue where the syntax testing for the past and future part of the syntax is. If you know can you direct me to that class. Thanks

**Comment by bensku** [comment]
Fixing is not priority. Maybe at some point (new parser?).

**Comment by FranKusmiruk** [comment]
Edited the issue to only have the suggestion that is feasible to add, the rest are either impossible due to bugs or behavior of Skript itself.

**Comment by JavierKasunic** [comment]
it took 7 years and I don't use this anymore but the feature was done, glad to see this project is still going strong!
