### ISSUE TITLE
Skript changes variable if it's named in GUI (TuSKe/SkQuery)

### ISSUE THREAD

**Issue by nikkedoy98** [SkriptLang/Skript#1690]
### Description
if i create and variable which is now a diamond.
I use it (variable) in a TuSKe/SkQuery GUI naming it to "Swag item". Then it suddenly changes to diamond named "Swag item" also in the variable!

I've tested this with both versions of Skript (1.13.2-Beta2 and 1.12.2-Dev37c) and
in 1.13.2 it does change variable, but in 1.12.2 it doesn't!
(PaperSpigot) 

### Steps to Reproduce

1. add Skript
2. add TuSKe 1.8.2 (or SkQuery - Lime fork. Remember to change given skript to corresponding conditions)
3. Paste skript below and be amazed.

!!! 4. Remember to switch between minecraft versions (1.13.2 paper and 1.12.2 paper)

### Errors / Screenshots

This one works perfectly (1.12.2)
![1 12 2 - this works](https://user-images.githubusercontent.com/42248504/48570827-ee7fce00-e90d-11e8-938b-64a4dfddf846.PNG)

But this one doesnt (1.13.2)
![1 13 2 - this doesn t work](https://user-images.githubusercontent.com/42248504/48570833-f7709f80-e90d-11e8-8198-a04b57bd163a.PNG)

### Server Information
To make it work: PaperSpigot 1.12.2, Skript-Dev37c, TuSKe (Pikatchu920 Fork) or (SkQuery 3.6.1-Lime)
To make it workn't: PaperSpigot 1.13.2, Skript-1.13.2-Beta2, TuSKe (orginal) or (SkQuery 3.6.1-Lime)

### Additional Context
Here is the Skript:

```
command /reloaditem:
    trigger:
        set {esine} to diamond
        message "%{esine}%"

command /test:
    trigger:
        message "%{esine}%" #Says it correctly. But here comes the fun part
        open virtual chest inventory with 1 rows named "&cNot mine problem" to player #(Tested with TuSKe and SkQuery)
        make gui slot 0 of player with {esine} named "&6Swag item" to close
        message "%{esine}%" #See. It changes that
        wait 2 ticks
        execute console command "/reloaditem" #Lets reload that item
        message "%{esine}%"
        wait 2 seconds
        execute console command "/reloaditem" #And after few seconds
        message "%{esine}%" #Mindblow

**Comment by bensku** [comment]
We need an example that does not use addons, or TuSKe developer to help with debugging.

**Comment by Blueyescat** [comment]
It is not related to GUIs, looks like the `named` expression changes name of the actual item.
```vb
command /test:
	trigger:
		set {_x} to diamond
		message "%{_x}%"
		set {_y} to {_x} named "&cTest"
		message "%{_x}%"```
