### ISSUE TITLE
Bug: Setting variable to slot of inventory not working. (Can't understand)

### ISSUE THREAD

**Issue by LogaaanCZ** [SkriptLang/Skript#1692]
### Description

Skript can't understand:
set {_slots.1} to slot 1 of player
set {_slots,1} to slot 1 of current inventory of player
### Expected Behavior

Setting variable to slot.
### Server Information
* **Server version/platform:**        1.13.2 / Linux
* **Skript version:**                 Latest

**Comment by bensku** [comment]
If you have addons, please test without them.

**Comment by Nicofisi** [comment]
@bensku is this fixed?

**Comment by bensku** [comment]
No, I tagged wrong issues in commit. Noticed when I wrote patch notes.

**Comment by Blueyescat** [comment]
Should be an user issue, works on beta4 too. :no_entry_sign:
