### ISSUE TITLE
Error when trying to add lore to player's pickaxe

### ISSUE THREAD

**Issue by Matt4499** [SkriptLang/Skript#1695]
### Description
Trying to add a lore to a player's tool.

### Steps to Reproduce
https://pastebin.com/LMmbLN4j
shift right click with a diamond pick and click the tnt

### Expected Behavior
A lore of "Explosive" to be added onto the pickaxe

### Errors / Screenshots
https://pastebin.com/LMmbLN4j the errors are in the paste

### Server Information
* **Server version/platform:**       PaperSpigot 1.12.2 update 1589
* **Skript version:**                v2.3-beta2

### Additional Context
Newest Version of skQuery installed, Newest version of Skript installed.

**Comment by TheBentoBox** [comment]
Duplicates #1691, see there for cause/solution.
