### ISSUE TITLE
Aliases still doesn't works as it need to work

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1696]
Aliases with wheat, potato, carrots, beetroots are broken!
(with cocoa everything is "medium cocoa"!)
nether warts are "items" with this
```
on break:
	send "%event-block%"
```
1) When I break fully grown beetroots it says that it's "freshly planted"

2) full grown potatoes are "stage three" but potatoes have more stages!

3) full grown carrots are "freshly planted too"

4) on break wheat we'll get information that's "wheat item" XD

mc: 1.13.2 paper
skript: latest (beta-2)
Because of this all of my scripts that are based on this aliases are broken.

**Comment by bensku** [comment]
What Minecraft version are you using?

**Comment by iOshawott** [comment]
@bensku  1.13.2-paper and beta-2 skript

**Comment by bensku** [comment]
Was a regression, relevant commit has been reverted.
