### ISSUE TITLE
Event Issues

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#1699]
### Description
I've been wondering if this is a bug or not. There's on block form event and on grow of oak event
Are they the same function? It triggers on block form event even though I grow a tree.

### Steps to Reproduce
`on grow of oak:
	broadcast "test"`

### Expected Behavior
It works perfectly but it also can be trigger with other events such as on block form.

### Errors / Screenshots
They both event execute the same thing. 
On block form and On grow of oak
I hope this is fixable so I can work on with my skript! Thanks!

No error

### Server Information
1.12.2
2.2-dev36

**Comment by Efnilite** [comment]
`on block form` is the equivalent of a grow event (no specific block types like trees, etc), so it'd make that they trigger at the same time

**Comment by Sodies** [comment]
> `on block form` is the equivalent of a grow event (no specific block types like trees, etc), so it'd make sense that they trigger at the same time

So I can fix it by using on block form of cobblestone?

**Comment by Sodies** [comment]
> `on block form` is the equivalent of a grow event (no specific block types like trees, etc), so it'd make sense that they trigger at the same time

I used on block form of cobble_stone.
No issues but still it triggers the effects from on grow of oak event.

**Comment by TheBentoBox** [comment]
So you're saying that `on block form` triggers `on grow` regardless of what block was formed?

**Comment by Sodies** [comment]
> So you're saying that `on block form` triggers `on grow` regardless of what block was formed?
Yup.
Like i put
`on grow of oak:
	broadcast "test"`
and
`on block form of cobble_stone:"`

it triggers the on grow of oak effects when cobblestone is form

**Comment by bensku** [comment]
I wonder if #865 might've been this all along...
