### ISSUE TITLE
"On break of spawner" also triggers for breaking Soul Sand

### ISSUE THREAD

**Issue by brjedi** [SkriptLang/Skript#1706]
### Description
I have a plugin that is supposed to drop an item whenever a Mob Spawner is mined. However, it also runs whenever Soul Sand is broken.

### Steps to Reproduce

> on break of spawner:
> 	player's gamemode is survival:
> 		make console execute "/essentials:give %player% prismarineshard 1 name:&3&lMob_Spawner_Shard lore:&eCombine_10_at_/warp_Spawner_to_get_a_mob_spawner!"
> 		message "&8&l<&6&lVK&f&lSpawner&8&l> &eYou have received a Mob Spawner Shard! Redeem it at &3/warp Spawner&e!"
(Formatted correctly at https://pastebin.com/0DDyWgCU )
### Expected Behavior
When you mine a spawner, it should drop a "Spawner Shard"
When you mine Soul Sand, it should drop Soul Sand, as usual, never touching this Skript.

### Server Information
* **Server version/platform:**      1.13.2  _git-Spigot-e4d0c66-f3f2fe5_
* **Skript version:**                2.3-beta2

### Additional Context
- Also running SkQuery 3.6.0-Lime
- This is not just a problem with the most recent Skript version, as it was also this wat in previous versions.
- Still happens with SkQuery disabled
- Still happens with the aliases file empty

**Comment by brjedi** [comment]
Edit: The same thing happens with glass. Whenever you break glass, it runs the commands for break of a spawner

**Comment by Snow-Pyon** [comment]
Probably a duplicate of #1567, but since spawner and soul sand don't seem to have a common supertype, this might be an unrelated bug.

**Comment by bensku** [comment]
Was probably related, since it got fixed by reworking supertypes.

**Comment by TheBentoBox** [comment]
They actually DO have a common supertype, in `z-block-placement.sk` there's `special torch sides = soul sand, monster spawner`, so this was definitely a supertype issue.
