### ISSUE TITLE
%uuid of entity target% in far

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#1707]
I have created own skript and Im learning the Skript in some time... I founded a bug or I wrote wrong. Im here cause I asked on discord server to get help with that and anyone couldnt help me with that...
Theres the code: https://code.skript.pl/1xv8vf0z 
And the error is: When I click a mob it opens the GUI near. And when I click option to edit the entity to Invulnerable:1 works and the Invulnerable:0 too. But when I have opened the GUI and the entity run away it doesnt works BUT THE Invulnerable:1 works and other "yes" options... The Invulnerable:0 doesnt work, it says in console <none>. Sorry for my English :P.

**Comment by Snow-Pyon** [comment]
The issue tracker is only used to report bugs or suggest a feature; your issue is neither and should be handled outside the issue tracker.
