### ISSUE TITLE
block under player (?)

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1709]
```
on sneak toggle:
	if {tp::%player%} is not set:
		if block under player is gold block:
			set {tp::%player%} to true
			set {_x} to block under player
			loop 70 times:
				if block above {_x} is gold block:
					set {_x} to block above {_x}
					set {_x} to block above {_x}
					teleport player to {_x}
					stop
				else:
					set {_x} to block above {_x}
```
since beta3 "if block under player is gold block" doesn't works
but "if "%block under player% is "gold block"" works
It worked in beta2
paperspigot 1.13.2

`on step on gold block:`

doesn't works too

===
but
```
on sneak toggle:
	if {tp::%player%} is not set:
		if "%block below player%" is "gold block":
			set {tp::%player%} to true
			set {_x} to block below player
			loop 70 times:
				if "%block above {_x}%" is "gold block":
					set {_x} to block above {_x}
					set {_x} to block above {_x}
					teleport player to {_x}
					stop
				else:
					set {_x} to block above {_x}
```
works good

and "diamond block" doesn't works "block of diamond" works

**Comment by bensku** [comment]
What does sending block under player give?

**Comment by iOshawott** [comment]
if I'm standing on gold block it says it's "gold block"
if I'm standing on diamond block it says it's "block of diamond"
```
command /naczymstoje:
	trigger:
		send "%block under player%"
```

**Comment by iOshawott** [comment]
> Ah, I think I figured it out. Don't do string comparisons; just compare block with alias directly. Not sure about on step event, though.

uh... you don't understand me 
when I compare block with alias directly "if block under player is gold block:" <- it isn't working!
When I do "if "%block under player%" is "gold block":" <- it works!

**Comment by iOshawott** [comment]
```
every 1 seconds:
	loop all players:
		if block under loop-player is gold block:
			broadcast "TEST1"
		if "%block under loop-player%" is "gold block":
			broadcast "TEST2"
```

Okay, sooo 
<img src="http://oshawott.pl/ss/c0ce.png">

**Comment by bensku** [comment]
Sorry, my misunderstanding.

**Comment by bensku** [comment]
Please try again with the new release.

**Comment by iOshawott** [comment]
Looks works good now :)
