### ISSUE TITLE
[issue] log handler error

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1712]
### Description
100+ errors on load

### Steps to Reproduce
When loading my skript [SkEco](https://forums.skunity.com/resources/skeco.599/) on beta2, I have no issues, but when loading it on beta3 I get these [ERRORS](https://paste.md-5.net/temefeline.py)

### Expected Behavior
Expected no errors.

### Errors / Screenshots
https://paste.md-5.net/temefeline.py

### Server Information
```
[19:18:30 INFO]: This server is running Paper version git-Paper-463 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[19:18:30 INFO]: Previous version: git-Paper-453 (MC: 1.13.2)
[19:18:30 INFO]: Checking version, please wait...
[19:18:31 INFO]: You are 4 version(s) behind
```
* **Skript version:** Skript version 2.3-beta2

**Comment by bensku** [comment]
The script uses addons. It would be ideal to have a test case that doesn't.

**Comment by ShaneBeee** [comment]
You're right.
And well crap... when i first loaded Skript beta3, before I had addons I got that error, and sure enough now, I cant get it to happen again. 

Im wondering if its something to do with a weird variable. I will keep testing.

**Comment by ShaneBeee** [comment]
I'm going to close this for now, and I will re-open it later IF I can get it to show that error again with no addons. #BlameTheAddons
