### ISSUE TITLE
Why is some effects/conditions doesn't work in latest skript?

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#1717]
### Description
Using the latest skript beta4 alot of conditions and other stuff become "Can't understand" error. Not sure why. Is it because it no longer support 1.12.2?

### Errors / Screenshots
Error like:
can't understand this event: 'on break of wood logs'
can't understand this condition: 'player has 5 flint and 4 stick and 2 cobble_stone'
Can't understand this condition/effect: format slot 4 of player with 1 of wheat named "&f&lFarming"

### Server Information
* 1.12.2
* beta4

**Comment by TheBentoBox** [comment]
Aliases have changed, so the name you used previously to refer to some item types may not work anymore. For example, `cobble_stone` is not a valid alias anymore, you must use `cobble`, `cobblestone`, or `cobblestone block`. To refer to any type of log, you'd use `any log`.

Aliases can be found [here](https://github.com/SkriptLang/skript-aliases/).
