### ISSUE TITLE
Rightclick with second hand BUG

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1731]
```
on rightclick with dried kelp:
	if player has space for 1 bedrock:
		set {_var} to name of event-item
		if {_var} contains "Czekoladka Adwentowa":
			if {_var} contains "<cyan>":
				replace all "<cyan>" in {_var} with ""
				replace all ".12.2018r - Czekoladka Adwentowa" in {_var} with ""
				remove 1 dried kelp named "<cyan>%{_var}%.12.2018r - Czekoladka adwentowa" from player's inventory
				if {_var} is "2":
					add 3 diamonds to player's inventory
```
It just doesn't remove dried kelp when you're rightclicking with second hand ; d

**Comment by Efnilite** [comment]
Does the player have a space for bedrock, and does the name of the right clicked item contain `Czekoladka Adwentowa`? Also im pretty sure the problem lies with it containing <cyan>, but idk if you can even do that

**Comment by iOshawott** [comment]
> Does the player have a space for bedrock, and does the name of the right clicked item contain `Czekoladka Adwentowa`? Also im pretty sure the problem lies with it containing , but idk if you can even do that

space for bedrock - just checking "can player hold anything else?" 
What do you have to "Czekoladka Adwentowa"? XD


Everything is okay if you're holding it in main hand =)

After added additional checks I just disabled rightclicking with second hand:
```
on rightclick with dried kelp:
	if player has space for 1 bedrock:
		set {_var} to name of event-item
		if {_var} contains "Czekoladka Adwentowa":
			if {_var} contains "<cyan>":
				replace all "<cyan>" in {_var} with ""
				replace all ".12.2018r - Czekoladka Adwentowa" in {_var} with ""
				player's tool is 1 dried kelp named "<cyan>%{_var}%.12.2018r - Czekoladka adwentowa"
				remove 1 dried kelp named "<cyan>%{_var}%.12.2018r - Czekoladka adwentowa" from player's inventory
```

**Comment by bensku** [comment]
Can't reproduce. Please give a self-contained sample with usage instructions.

**Comment by iOshawott** [comment]
I'm kinda trying now but it's weird because it's hard to reproduce. On a lot of re-loading and right-clicks, I got this bug only 1 time.
Only one what I'm sure is that on right-click event doesn't work with second hand if you have specific items in first hand (example: planks) ... [ https://www.youtube.com/watch?v=vOqErEtFWGc ]
So maybe this bug I said earlier works only when you have something specific in hand...

```
command /gimmechocolate:
	trigger:
		add 1 dried kelp named "<cyan>4.12.2018r - Czekoladka adwentowa" to player's inventory
on rightclick with dried kelp:
	if player has space for 1 bedrock:
		set {_var} to name of event-item
		if {_var} contains "Czekoladka Adwentowa":
			if {_var} contains "<cyan>":
				replace all "<cyan>" in {_var} with ""
				replace all ".12.2018r - Czekoladka Adwentowa" in {_var} with ""
				remove 1 dried kelp named "<cyan>%{_var}%.12.2018r - Czekoladka adwentowa" from player's inventory
				else if {_var} is "4":
					add anvil to player's inventory
```

Welp, but I'm sure that bug somewhere is because I saw that one player got 100 anvils from clicking it : (

**Comment by TheBentoBox** [comment]
Still can't reproduce, haven't seen anyone else report this old issue, closing.
