### ISSUE TITLE
NullPointerException when checking enchantment type of air

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#1732]
### Description
When checking enchantments (such as enchantment level) of air, a null pointer exception is thrown.

### Steps to Reproduce
1. Have an empty hand.
2. Run the effect command `send "%level of <any enchantment> of player's tool%"`.

### Expected Behavior
I would expect this to return 0 for air just like it would on any other item if the enchantment didn't exist.

### Errors / Screenshots
[Here is a paste of the error](https://pastebin.com/pyzWr4FF).

### Server Information
* **Server version/platform:** 1.13.2
* **Skript version:** 2.3-beta4

**Comment by TheBentoBox** [comment]
Setting to medium because this causes huge error spamming on code which previously worked fine because you now need to sanity check any code which, for example, checks the player's tool's enchantment level to see if it's air first.

**Comment by TheLimeGlass** [comment]
@bensku recently edited this chunk of code. Probably a really simple fix.
