### ISSUE TITLE
1.13.2

### ISSUE THREAD

**Issue by imflitch** [SkriptLang/Skript#1734]
When will there be a update for 1.13.2?
It doesnt work for 1.13.2 only 1.13(flat), and that version is really unsecure and buggy, will there be a update anytime soon?

**Comment by TheBentoBox** [comment]
2.3-beta4 works fine on 1.13.2. What issues are you seeing and what versions are you using?

**Comment by imflitch** [comment]
It just gives "skript /help" when using any skript command

**Comment by TheBentoBox** [comment]
But what versions of everything are you using? What's your server platform/version and what's your Skript version?

**Comment by HYPExMon5ter** [comment]
Then there must be errors, check console/logs

**Comment by imflitch** [comment]
Oh damn guys, it was a skript addons which wasnt updated, didnt even check for that, my bad!
