### ISSUE TITLE
"if event-block's location is" not working

### ISSUE THREAD

**Issue by zeibo** [SkriptLang/Skript#1737]
ver. 1.13  | 2.3 beta 2

my script

> on right click on SMOOTH STONE:
> 　if name of player's held item is "123":
> 　　if event-block's location is location(7001.5, 69, 3966.5, player's world):
> 　　　send "test" to player

no error and no effect
Or what did i miss?

**Comment by TrademarkTM** [comment]
The Y of a block also has `.5`.

**Comment by zeibo** [comment]
thx  ><
