### ISSUE TITLE
Add list variable sorting

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#1743]
### Variable sorting expression
My idea is basically to have a sort expression in Skript. Instead of changing the variable itself, it would return a list of texts with the values.

Here's how I made it (in skript-mirror)
```
expression (multi[ple] replace|replacer) [(elements|values)] %texts% with %objects% in %text%:
	return type: text
	get:
		set {_text} to expr-3
		loop exprs-1:
			add 1 to {_n}
			replace all "%loop-value%" with "%{_n}th element of exprs-2%" in {_text}
		return {_text}

local expression variable %objects% in %event%:
	return type: object
	get:
		set {_name} to expr-1.getName().toString(expr-2)
		return Variables.getVariable({_name}, expr-2, expr-1.isLocal())

plural expression (1¦(top|first)|2¦(last)) %integer% (values|elements) of %objects% [formatted] as %text%:
	return type: texts
	get:
		set {_map} to variable raw exprs-2 in event
			
		set {_list} to new ArrayList({_map}.entrySet())
		{_list}.sort(Entry.comparingByValue())
		
		if parse mark = 1:
			Collections.reverse({_list})
		
		loop ...{_list}:
			add 1 to {_n}
			set {_r::%{_n}%} to replacer "<pos>", "<key>" and "<value>" with "%{_n}%", "%loop-value.getValue()%" and "%loop-value.getKey()%" in expr-3
			{_n} = expr-1
			stop loop

		return {_r::*}
```

Usage:
```
set {_a::*} to top 10 elements of of {kills::*} formatted as "&a<pos>. &f<key> &7has &f<value> kills"
loop {_a::*}:
    send loop-value
```

It could use some other placeholder instead of `<something>`, but in general I think this expression could be really useful.

Thanks again.

**Comment by TheLimeGlass** [comment]
`sorted %objects%` is already an expression.

**Comment by TrademarkTM** [comment]
It sorts the variable itself and deletes the indices.
If you use %player% as index it would be removed, so it can't display %player% for example (which is one best uses of sorting).

**Comment by TheLimeGlass** [comment]
You can grab the indices of the variable list and sort them, then match against.

What I do is I set a variable with the following variable naming: `{name::player::%player%::highscore}`

Then in order to grab the highest player you loop all offline players
```
set {_highest} to player
loop all offline players:
    if {name::player::%loop-offlineplayer%::highscore} > {name::player::%{_highest}%::highscore}:
        set {_highest} to loop-offlineplayer
broadcast "The highest player on the server is %{_highest}% with %{name::player::%{_highest}%::highscore}%"
```
It's all about how you structure your variable naming that allows you to take advantage of getting these values.

**Comment by TrademarkTM** [comment]
I'm not sure if that method is efficient.
My expression, doing it in the simplest way possible, returns the top 10 of 100k values in 50ms.

The issue about the indices is actually mine.. I was trying to do something like that but it wasn't useful that way.
I think this should be implemented because it's easy to use. You don't need to loop anything or compare values, just add a formatting and how many values you want and it's done.

**Comment by TheBentoBox** [comment]
Gonna let the devs decide if this is something they want. It's definitely mostly in the realm of "already possible but requires more work" but there are definite issues that have pained me as well (like it losing indices)

**Comment by Snow-Pyon** [comment]
I'll assign it to myself since I am personally interested in this, but anyone is able to add it if they wish (I've found myself with less time than what I had before holidays lately...)

**Comment by Wealthyturtle** [comment]
Closing in favor of #371
