### ISSUE TITLE
Paper Spigot 1.7.10 [MCP]

### ISSUE THREAD

**Issue by droopi29** [SkriptLang/Skript#1744]
hi,

hi have a litlle question do you have a version of your plugin for PaPer spigot 1.7.10 or a link ? 

thanks,

**Comment by TheBentoBox** [comment]
Sorry, no, this fork was made specifically to support Minecraft versions 1.9 and above. I'd try using the old version of the plugin from bukkitdev, found [here](https://dev.bukkit.org/projects/skript).

**Comment by droopi29** [comment]
this version don't work for my skript any version 1.8 ?

**Comment by bensku** [comment]
That is correct.
