### ISSUE TITLE
2 default command don't work (see more)

### ISSUE THREAD

**Issue by AlexLew95** [SkriptLang/Skript#1746]
### Description
2 commands in the latest skript version don't work: ``/skript update download`` and ``/skript update changes``. Maybe more commands don't work.

### Steps to Reproduce
Use ``/skript update changes`` in the console. See ? Nothing happened.

### Expected Behavior
See description

### Errors / Screenshots
![Image available here: https://i.imgur.com/22n2ag0.png](https://i.imgur.com/22n2ag0.png)

### Server Information
* **Server version/platform:**       1.12.2
* **Skript version:**                       2.3-beta4

**Comment by Nicofisi** [comment]
This simply wasn't implemented yet - #241
