### ISSUE TITLE
Lagging with lore in 1.13.2 Version

### ISSUE THREAD

**Issue by wohahobg** [SkriptLang/Skript#1757]
Hello there all! I have a problem with the [with lore] so I have made script with 412 lines + -, because some lines are empty or got extra text with #Extra text here.
So the problem is I have got 8 lores in my script and when I reload it, it took around 8,000 ms but when I reload same script but without [with lore "test" and "test 1" and etc..] it took me 364 ms ? I have ask somebody to try it and `well, sry I'm still on 1.12 and can't update now as it will break many things in my server.. however I converted all the lores to skQuery with || and it took 600ms and without lores it took 300ms`
The skript version of person who try it is 2.2dev37c
Version 1.12.x [http://prntscr.com/lw88jb](http://prntscr.com/lw88jb)
With lore in 1.13.3 [http://prntscr.com/lw89cb](http://prntscr.com/lw89cb)
Without lore in 1.13.3 [http://prntscr.com/lw89lb](http://prntscr.com/lw89lb)

There is 0 errors in my script
Server version: 1.13.3 / Platform: Paper
Skript version: I am using last version of Skript [http://prntscr.com/lw894p](http://prntscr.com/lw894p)

I am so sorry if this should not be here ! Just I feel it should be here so if not please move it !

Edit: Here is the script one with lore and one without lore

[CODE WITH LORE : https://pastebin.com/KsMRkvhe](https://pastebin.com/KsMRkvhe)

[CODE WITHOUT LORE : https://pastebin.com/q7PRnyHq](https://pastebin.com/q7PRnyHq)

**Comment by wohahobg** [comment]
Yes ofc I have update the SkQuery to last version of Lime Glasses...

**Comment by wohahobg** [comment]
I am sorry for bump it, but can somebody help me :(

**Comment by Snow-Pyon** [comment]
The version where you are experiencing this is now unsupported, if you are able to reproduce it in the latest version, I'll reopen the issue.

**Comment by wohahobg** [comment]
What this mean ? You mean version 1.13.3 is not supported by Skript ? but it happen even on 1.13 ? and I am using the last version of Skript for it.

**Comment by Snow-Pyon** [comment]
The latest version of Skript is 2.3-beta4, and the issue report says the person who reproduced it did it in dev37c.

**Comment by wohahobg** [comment]
Yes I am using last version of skript. The person who try it was using the dev37c.
http://prntscr.com/lx6qg3 and it working great.. On the last version does not.

**Comment by Snow-Pyon** [comment]
Oh, I am so sorry for the confusion. I'll reopen it then. Did you try with addons? if so, try removing them.

**Comment by wohahobg** [comment]
Yes I have try it without adons, just vanilia gui even is more slower. After I remove whole lores everything become quicker.

**Comment by wohahobg** [comment]
[https://wohahobg.tinytake.com/sf/MzE3NzkzNl85NTE3MjU4](https://wohahobg.tinytake.com/sf/MzE3NzkzNl85NTE3MjU4)

So hello again, I have made that videio becosuse today by I have usign lores It become all of those errors in my console with lores, but if there is 0 lores it working perfect. I have reload 1 teme skript with Lore and one without lore ! Check out above.
Here is the full code of error in console.
[https://pastebin.com/R2Gp3jQW](https://pastebin.com/R2Gp3jQW)

**Comment by DevilishDante** [comment]
Hello now in lastest 1.13.2 and lastest skript 2.3.1 i have same problem too with ancient lore system skript reload in 2-3 second, with new system, server disconnect me for reloading , and took a very long time

**Comment by TheBentoBox** [comment]
This is now 5+ months old and is misleadingly not related to lore directly but rather to Skript being very slow at parsing long explicit lists in general. It's the same reason almost any complex syntax takes very long to parse.
