### ISSUE TITLE
Command /clear, remove the item which I have add to {list::*}

### ISSUE THREAD

**Issue by wohahobg** [SkriptLang/Skript#1761]
So the problem is, when I add my item to list and then I am doing  /clear the item which I have added is removed from {list::*}. I am not using any plugins for /clear I am using vanilia one from minecraft 1.13.2.  I don't geting any errors in console. 
Videio what I mean here [https://wohahobg.tinytake.com/sf/MzE3NzEwN185NTE1MDA3](https://wohahobg.tinytake.com/sf/MzE3NzEwN185NTE1MDA3) please look it.

The code with which I am testing

```
command /addtest [<text>]:
	trigger:
		if arg is not set:
			send "&c&m-------------------------------"	
			send "&bIndex    &8&l|| &eValue"
			send ""
			loop {list::*}:
				send "&e%loop-index%  &8&l|| &d&l%loop-value%"
			send ""
			send "&c&m-------------------------------"
		if arg is "add":
			add tool to {list::*}
			send "%tool% added to list"
		if arg is "dell":
			delete {list::*}
			send "done"

```

### Server Information
* **Server version/platform:**      I am using server version: Paper Spigot 1.13.2
* **Skript version:**   I am usign skript version:  [2.3-beta4](http://prntscr.com/lxdgsm)

**Comment by Tinkot** [comment]
probably a better description of the issue: using '_**delete {list::*}**_' deletes all values but keeps indexes.

**Comment by ShaneBeee** [comment]
I just tried this, using your EXACT code, adding a few tools to the list, running /clear, and all the items are still in the list, so, unfortunately, I can not replicate this issue.

**Comment by wohahobg** [comment]
> I just tried this, using your EXACT code, adding a few tools to the list, running /clear, and all the items are still in the list, so, unfortunately, I can not replicate this issue.
> 
> **EDIT:**
> I lied. The clear command I was using was from essentials.
> When I use /minecraft:clear then yes, I can confirm it erases the item from the variable.

That is exactly what I tried to say.. That's why I made that video, I was thinking 3 weeks why my {list::*} items is 0 air before get that after Minecraft /clear command in 1.13.3 clear my last item which I have added to {list::*} I hope they will fix it, plus my issues with lores 👍 :( :)
