### ISSUE TITLE
Item id error

### ISSUE THREAD

**Issue by ghost** [SkriptLang/Skript#1765]
In 2.3beta version, the id of item is strange.
I wrote the following syntax and threw grass several times, and all other IDs were printed.

On item spawn:
	broadcast "%id of entity%"

**Comment by bensku** [comment]
Items were removed in Minecraft 1.13. What version are you running?

**Comment by chokechoke1** [comment]
> Item IDs were removed in Minecraft 1.13. What version are you running?

1.13.2, How can i get name of item?

**Comment by chokechoke1** [comment]
> `name of item`, obviously. Or `raw name of item`, if you need it for Vanilla commands.

Thank you so much!

**Comment by chokechoke1** [comment]
> `name of item`, obviously. Or `raw name of item`, if you need it for Vanilla commands.


Can not output the raw name of the dropped item?

**Comment by TheBentoBox** [comment]
Dropped items aren't items themselves, they're an entity. To get the item within the dropped item, you need to use `item of %dropped item entity%`.
