### ISSUE TITLE
Lores check error in 1.13.2

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#1766]
### Description
So I'm making a keep inventory item when die. So in the previous 1.12.2 it works fine with 
`if player contains 1 disc 11 named "&d&lTest" with lore "Hello||Test":`
but now in 1.13.2 it doesn't work but I tested something to know what's the issues.
Now in 1.13.2
`if player contains 1 disc 11 named "&d&lTest" with lore "Hello||Test":` doesn't check
but
`if player contains 1 disc 11 named "&d&lTest" with lore "Hello":`
works

### Errors / Screenshots
no error in console 
lores spilt problem

### Server Information
* **Server version/platform:**       1.13.2
* **Skript version:**               beta4

**Comment by weberlepecheur** [comment]
Because the format was changed in 2.3, now :
`named "NAME" with lore "LORE1", "LORE2" and "LORE3"`

**Comment by Sodies** [comment]
> Because the format was changed in 2.3, now :
> `named "NAME" with lore "LORE1", "LORE2" and "LORE3"`

AHH THATS WHY
Nice i think they should let people know it changed

**Comment by bensku** [comment]
I don't think we changed anything. The old syntax was from an addon, wasn't it?

**Comment by weberlepecheur** [comment]
Yeah, from SkQuery who was faster than skript for parsing multiple ligne of lore

Télécharger Outlook for Android

________________________________

**Comment by Sodies** [comment]
> I don't think we changed anything. The old syntax was from an addon, wasn't it?

Not sure what is causing it but it looks like even spilt lore " ||  " doesn't work in 1.13 now

**Comment by Nicofisi** [comment]
Yep || *was* from skQuery, if has never been a part of Skript. Also, LimeGlass removed it from his fork when it got added to Skript
