### ISSUE TITLE
function "location" ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Olyno** [SkriptLang/Skript#1767]
### Description
When you use the function ``location`` included in skript, a ArrayIndexOutOfBoundsException will be generate if we don't precise the world in parameter.

### Steps to Reproduce
 - Use a syntax with the function ``location`` like:
```vb
set block at location(50, 50, 50) to stone
```
and you will get a java ArrayIndexOutOfBoundsException:
https://pastebin.com/raw/07by8m4H

### Errors / Screenshots
https://pastebin.com/raw/07by8m4H

### Server Information
* **Server version/platform:**       1.13.2 (spigot)
* **Skript version:**                       2.3-beta5

**Comment by bensku** [comment]
This one is tricky. EventValueExpression is used to default to event-world, but it isn't properly initialized and will always return null. Unfortunately, initializing it would require a current even in Skript loader, which isn't available for default functions.

**Comment by Wealthyturtle** [comment]
Closing this in favor of #1465 since it has more information
