### ISSUE TITLE
Condition on death event trigger a types.barflag problem ?!

### ISSUE THREAD

**Issue by weberlepecheur** [SkriptLang/Skript#1769]
### Description
A weird error is occured when reloading the code below, it's says that chainmail cap named "{@item.casque}" is not a types.barflag.
I don't even know what a types.barflag

### Steps to Reproduce
```
on death of player:
	drops of player contain chainmail helmet named "{@item.casque}"
	remove chainmail helmet named "{@item.casque}" from the drops
```

### Expected Behavior
To see if the items in question is in the dropped items, if yes then remove it.

The condition to see the dropped item doesn't work (exist?).
The effect to remove it works fine.

### Errors / Screenshots

> [21:02:46] [Server thread/INFO]: death of player (death/spawn of player):
> [21:02:46] [Server thread/ERROR]: chainmail cap named "Casque de Tolbar" is not a types.barflag (from ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:552)) (tellus_EffItem.sk, line 63: drops of player contain chainmail helmet named "{@item.casque}"')
> [21:02:46] [Server thread/INFO]:     remove [[itemtype:chainmail cap]] named "Casque de Tolbar" from the drops
> [21:02:46] [Server thread/INFO]: loaded 4 triggers and 0 commands from 'tellus_EffItem.sk'
> [21:02:46] [Server thread/INFO]: [Skript] Encountered 1 error while reloading tellus_EffItem.sk!

### Server Information
Paper 1.13.2
Skript 2.3-beta5

**Comment by Snow-Pyon** [comment]
1. Barflag isn't a type from Skript, it's either from skRayFall or Skellett. Try removing those addons and if the issue persists reopen the issue.

**Comment by weberlepecheur** [comment]
Ok, my bad, this condition simply doesn't exist.
