### ISSUE TITLE
Variable errors

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#1771]
### Description
When I started up my server, this error came up
Edit: After deleting my variables file, it no longer showed this error (or atleast not yet, idk my console kept getting spammed so I just stopped the server), but was getting spammed with these errors: https://pastebin.com/9Bx7hsMh

### Steps to Reproduce
Not sure.

### Errors / Screenshots
https://pastebin.com/Pe38iG3U

### Server Information
* **Server version/platform:**       PaperSpigot 1.13.2
* **Skript version:**                2.3-beta6

**Comment by bensku** [comment]
I screwed up variable updating. Possibly by committing wrong mappings file to Git.

**Comment by thejimmyj57** [comment]
Issue still persists after redownloading beta6

**Comment by bensku** [comment]
I meant the first error, not the one you're getting with clean variable db. Is that exact error still occurring?

**Comment by thejimmyj57** [comment]
The log handler error is the one I am referring to. Every time the server starts it’s continuously throws those errors for the first 10 minutes.

**Comment by Snow-Pyon** [comment]
If you're using skript-mirror, it causes those errors with log handlers. The bug is fixed now but there is no release for it yet.

**Comment by TheBentoBox** [comment]
No further response and as Snow said this is likely an add-on issue.
