### ISSUE TITLE
Emoji not support in GUI

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#1773]
### Description
In the latest bensku skript it seems like emoticon doesn't support now.
I tried adding emoticon in GUI item name. And then check it with on inv click
but it seems like it doesn't recognize anymore

### Steps to Reproduce
`command /setting:
	trigger:
		open "CHEST" with 2 rows named "Test" to player
		set slot 6 of player's current inventory to 1 of clock named "&f&l◉ &a&l&nTest&f&l ◉"`
It don't recognize this ◉
which in the past it works [1.12.2]

### Errors / Screenshots
no errors

### Server Information
* **Server version/platform:**      1.13.2
* **Skript version:**                beta6

### Additional Context
I have a question with the prefix and suffix function. Is it broken?
I used beta5 and it works but in beta6 it became "Can't understand this condition/effect: set the player's suffix to "&7&l[&c&lTest&7&l]""

**Comment by HYPExMon5ter** [comment]
Prob didn’t save the script file as UTF-8, as for prefix/suffix, I don’t believe it’s broken, but I haven’t tried it on the beta releases yet so couldn’t tell you for sure.

**Comment by Sodies** [comment]
> Prob didn’t save the script file as UTF-8, as for prefix/suffix, I don’t believe it’s broken, but I haven’t tried it on the beta releases yet so couldn’t tell you for sure.

what about prefix and suffix

**Comment by Snow-Pyon** [comment]
Pretty sure this isn't a Skript issue, there have been no changes to how strings are saved.

It's probably just what Hype said.

**Comment by Sodies** [comment]
> Pretty sure this isn't a Skript issue, there have been no changes to how strings are saved.
> 
> It's probably just what Hype said.

Okay. What about the changing prefix and suffix? Is that an addons or skript itself?
It can't understand the effects
`set the player's prefix to "&7&l[&f&lEnd&7&l]"`

**Comment by Snow-Pyon** [comment]
You need Vault and a permission manager that supports Vault. That said, I am closing the issue.
