### ISSUE TITLE
Error with color codes GUI

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#1775]
### Description
Setting any slot with an item with name that has color &f&l&n. Skript doesn't recognize this I think.
I was making a gui and test it with inventory click event.
`on inventory click:
	if name of clicked item contains "&f&l&nTest":`
This doesn't work BUT
`on inventory click:
	if name of clicked item contains "&a&l&nTest":`
This works. What I change was the color only

### Steps to Reproduce
Test it yourself. 
Step 1 - `set slot 0 of player's current inventory to 1 of diamond sword named "&f&l&nAdvanced Ability" with lore "&8&m----&3&m----&8&m----&3&m----&8&m----", "&7Open Advanced Ability Menu" and "&8&m----&3&m----&8&m----&3&m----&8&m----"`
Step 2 - 
`on inventory click:
	if name of clicked item contains "&f&l&nAdvancedAbility":`
This code doesn't work. But if you change to other color like &a&l&n
It works!

### Errors / Screenshots
No errors

### Server Information
* **Server version/platform:**       1.13.2
* **Skript version:**                beta6

**Comment by bensku** [comment]
Spigot or Minecraft loses the first &f somewhere. Not a Skript bug, but maybe we should report this to Spigot team.

**Comment by TheBentoBox** [comment]
This is very old and as bensku said is likely not an issue on our end or anything we can fix. I wouldn't be surprised if Bukkit or Minecraft itself ignores white color codes at the start of the name since they're redundant for most items.
