### ISSUE TITLE
Error of TuSke

### ISSUE THREAD

**Issue by KAMIL0024** [SkriptLang/Skript#1776]
### Description
`with lore`  causes a bug
 
### Steps to Reproduce
```
on rightclick:
  location of clicked block is {lootchest::%player's world%}
  cancel event
  open chest with 6 rows named "&7Loot chest" to player
  format gui slot 53 of player with chest named "&aDostepne nagrody" with lore "||&7Kliknij, aby zobaczyc"
```
### Errors / Screenshots
https://hastebin.com/roselesoni.md

### Server Information
* **Server version/platform:**       spigot 1.12.2
* **Skript version:**                2.3-beta6

**Comment by HYPExMon5ter** [comment]
`with lore` has nothing to do with this error and this error has been in Tuske for quite a while, download pika’s fork for a fix. This isn’t the place for addon errors
