### ISSUE TITLE
Optimize Parsing of location()

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#1783]
### Description

Using the location(x, y, z, w) function can cause a simple Skript to take upwards of 10 seconds to reload, while the syntax location x, y, z, w does not

### Steps to Reproduce

Code that does not hang the parser
```
command /test [<number>] [<number>]:
    trigger:
        set {_loc} to location (x coord of player + arg-1), (y coord of player), (z coord of player + arg-2) in (world of player)
```

Code that does hang the parser
```
command /test [<number>] [<number>]:
    trigger:
        set {_loc} to location(x coord of player + arg-1, y coord of player, z coord of player + arg-2, player's world)
```
### Expected Behavior

For the second code snippet to not cause the parser to hang since it's just 3 lines of code...

### Errors / Screenshots

https://pastebin.com/raw/mzcahgcj (Server thread dump)

### Server Information
* **Server version/platform:** Paper 1.12      
* **Skript version:** 2.2-dev37c (Although I was able to replicate this laggy behavior on skUnity's parser)

**Comment by TheLimeGlass** [comment]
https://github.com/SkriptLang/Skript/pull/5133
