### ISSUE TITLE
10 - 1 + 5 = 10 - 1 - 5

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#1784]
### Description
Skript returns the wrong result when using expressions like `10 - 1 - 5`.
In that example, it returns 14 instead of the expected 4.

Likewise, `10 - 1 - 5 - 4` = `10` in Skript, where the expected result is 0.

The logic is correct when parentheses are assumed `10 - (1 - 5)`.

### Server Information
* **Server version/platform:** Spigot 1.12.2
* **Skript version:** Skript 2.3 beta6

**Comment by bensku** [comment]
See #535 for more math issues.

**Comment by Wealthyturtle** [comment]
Closing this in favor of #535
