### ISSUE TITLE
Owch my server! Noticed lag in latest build and did a timings report things don't seem right plz help

### ISSUE THREAD

**Issue by axemwa** [SkriptLang/Skript#1785]
Did a timings report things don't seem right is this something that needs fixing should I be concerned?
![image](https://user-images.githubusercontent.com/37608633/50570599-3fc21f00-0de1-11e9-877e-2d87cc376354.png)

https://timings.aikar.co/?id=1ce23f58b75243ddb5a2f9bc2551b02a

Minecraft 1.13.2
Paper Spigot 488

No errors

**Comment by bensku** [comment]
TPS looks good, probably shouldn't worry too much.
