### ISSUE TITLE
Problem with store chestplate, leggings, boots and offhand in variable

### ISSUE THREAD

**Issue by DevilishDante** [SkriptLang/Skript#1786]
### Description
Hello, since lastest update i have this error when i want some some stuff in variable 

### Expected Behavior
https://pastebin.com/kF3xGPMt there here a code here who reproduce this, for none reason error doesn't appear in console but always "error occured in game"
### Errors / Screenshots
https://pastebin.com/9jYsqg92
in game i have :
"An internal error occured while attempting to perform this command."

### Server Information
* **Server version/platform:**       git-Spigot-fe3ab0d-162bda9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
* **Skript version:**               2.3-beta7

### Additional Context
Thanks for all update and and all it's great !  (i dont how say this in english u.u)

**Comment by TheBentoBox** [comment]
Can anyone confirm this for me?
