### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by CrazyWords1** [SkriptLang/Skript#1788]
Maybe you would like to add an opportunity for people to thank you with money?

**Comment by TheBentoBox** [comment]
A nice thing to ask; we'll see if bensku wants to add this. I believe it's been discussed in the past and there are some technicalities surrounding it.

**Comment by bensku** [comment]
There are some legal issues with having an open donation link. If you want to donate now, you can contact the developer you want to donate to (using Discord, for example).

**Comment by ShaneBeee** [comment]
In my opinion, as much as this is lovely, donators often think they deserve something more. 
Plugins, for example, they want priority access to something.
On discord/websites/servers, donators want perks.

It's extremely hard to do with an open source plugin with MANY MANY contributors. 
Who would the donation go to? What would it be used for? What would said donator expect from said donation?

Legalities aside, it gets difficult in many other ways. 
As Bensku said, the best option is to donate directly to the dev you want to donate to.

**Comment by Blueyescat** [comment]
Discord accounts of [Developers](https://github.com/SkriptLang/Skript#developers) should be included in the README file.

**Comment by TheLimeGlass** [comment]
All Skript developers agreed on a sponsor like Open Collective. Kenzie owns the hosting and I think the domain for skriptlang.org so it makes sense for Kenzie to setup the sponsor for the organization.

**Comment by Moderocky** [comment]
Just following up on this: @APickledWalrus is investigating setting up some kind of collective donation system.
