### ISSUE TITLE
Impossible to rename a mob

### ISSUE THREAD

**Issue by AlexLew95** [SkriptLang/Skript#1790]
### Description
Impossible to rename a mob with the last version of skript (2.3-beta7)

### Steps to Reproduce
Just test a simple code like that to see:
```vb
on spawn of villager:
    kill event-entity
    spawn a zombie at location of event-entity
    set name of spawned zombie to "Nah"
```

### Expected Behavior
I expected to rename the zombie.

### Server Information
* **Server version/platform:**       1.12.2
* **Skript version:**                       2.3-beta7

### Screenshot

![](https://i.imgur.com/8hxcTaL.gif)

**Comment by ShaneBeee** [comment]
I can not replicate this.
I used your exact code on a 1.12.2 as well as 1.13.2 and both times the zombie was named "Nah" as long as my pointer was pointing at the zombie

**Comment by AlexLew95** [comment]
Conflict with an addon, no relation with skript, I close the issue
