### ISSUE TITLE
On Region Enter / Exit missing?

### ISSUE THREAD

**Issue by bolleboor** [SkriptLang/Skript#1793]
### Description

If I try to use the events "on region enter:" or "on region exit:" skript says they are invalid and can't understand.
![image](https://user-images.githubusercontent.com/22412324/50687595-3bd10f80-1022-11e9-909c-370d43cbe2dd.png)

Here is the code that I used in my skript (DUTCH)

![image](https://user-images.githubusercontent.com/22412324/50687608-4be8ef00-1022-11e9-8577-f60adf369838.png)

### Steps to Reproduce

Just use it as an event.

### Expected Behavior

I just thought it should work, it has worked before, before I used the beta versions.

### Errors / Screenshots

This is the only error I could find, no errors are displayed in the console:
![image](https://user-images.githubusercontent.com/22412324/50687651-72a72580-1022-11e9-95c4-5693f820eeac.png)

No Console error showed up.

### Server Information
* **Server version/platform:** Spigot 1.12.2       
* **Skript version:** Skript2.3 beta 6 & 7 (I tried beta 6 and 7)

**Comment by bensku** [comment]
Are you using WorldGuard 6?

**Comment by bensku** [comment]
Support for WorldGuard 6 is coming back in next release.
