### ISSUE TITLE
Reseting enchantments doesn't work

### ISSUE THREAD

**Issue by bensku** [SkriptLang/Skript#1794]
### Description
Resetting enchantments of an item does not work.

### Steps to Reproduce
1. Enchant an item.
2. Try to reset enchantments in it.

### Expected Behavior
Enchantments are removed, because default states of all items are without enchantments.

### Errors / Screenshots
No errors.

### Server Information
* **Server version/platform:** Paper 1.13.2
* **Skript version:** 2.3

### Additional Context
Known issue for 2.3. Minor enough that I decided not to delay the release.

**Comment by Snow-Pyon** [comment]
Likely related to #1795.
