### ISSUE TITLE
Skript claims WorldGuard 6 is not supported, but it is supported

### ISSUE THREAD

**Issue by CrazyWords1** [SkriptLang/Skript#1796]
### Description
WorldGuard 6 is not Support

### Server Information
* **Server version/platform:**       PaperSpigot 1.12.2
* **Skript version:**                2.3

**Comment by Snow-Pyon** [comment]
Please specify what errors you're getting and your version of WG exactly.

**Comment by CrazyWords1** [comment]
worldguard-bukkit-6.2.2
Not a error, a message about a not compatible version of WG

**Comment by CrazyWords1** [comment]
![default](https://user-images.githubusercontent.com/32343185/50720244-df75fa80-10ca-11e9-8c5d-c40f55294d2e.png)

**Comment by ham1255** [comment]
@CrazyWords1  skript 2.3 does not support world guard 6 anymore

**Comment by ham1255** [comment]
even if you update to worldgaurd 7 it wont work its only supported for 1.13

**Comment by CrazyWords1** [comment]
@ham1255 For people updating from the previous beta release, a few things were changed:

    Added back WorldGuard 6 support

**Comment by bensku** [comment]
WorldGuard 6 should work just fine. However, Skript's hook system doesn't know how to disable hooks without spitting errors yet... Didn't want to rewrite large parts of it so close to release.

**Comment by TPGamesNL** [comment]
I cannot replicate this, it's probably been fixed at some point
