### ISSUE TITLE
The expression player's tool doesn't fully work 

### ISSUE THREAD

**Issue by Eole7** [SkriptLang/Skript#1799]
### Description

Datas values in the expression `player's tool` don't work

### Steps to Reproduce

```
on right click:
    broadcast "%player's tool%"
```

For example, with this code if we click with any colored glass, "purple stained glass" will be sent, even if the glass is red.

[screenshot](http://www.noelshack.com/2019-01-6-1546694762-bug.gif)

### Server Information
* **Server version/platform:**  Spigot 1.12.2     
* **Skript version:**   2.3.1

**Comment by bensku** [comment]
See #1850.
