### ISSUE TITLE
Problem with getting a yaml list using skript-yaml

### ISSUE THREAD

**Issue by bilektugrul** [SkriptLang/Skript#1801]
### Description
When the "/skgui reload config" command dispatched, Skript is sending this stacktrace.

### Errors / Screenshots
https://paste.ubuntu.com/p/YmdGczsXF9/

### Server Information
* **Server version/platform:**       PaperSpigot 1.13.2
* **Skript version:**               2.3.1 (latest release)

**Comment by bensku** [comment]
Redownload 2.3.1 to fix this.
