### ISSUE TITLE
Item Name

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1807]
### Description
%name of item% in variables is not working. Im guessing because an item stored in a variable, is stored as an item type not an item stack, therefor the naming expression doesnt work for it

### Steps to Reproduce
```
command /test:
	trigger:
		set {_item} to diamond sword
		set name of {_item} to "Test"
		send "&6Item: &b%{_item}% &6Name: &b%name of {_item}%"

		set {_item2} to diamond sword named "&aTest"
		set name of {_item2} to "New Name"
		send "&6Item: &b%{_item2}% &6Name: &b%name of {_item2}%"

		set {_item3} to "diamond sword" parsed as item
		set name of {_item3} to "Test"
		send "&6Item: &b%{_item3}% &6Name: &b%name of {_item3}%"
```
output:
```
[02:21:05 INFO]: Item: diamond sword Name: <none>
[02:21:05 INFO]: Item: diamond sword named Test Name: <none>
[02:21:05 INFO]: Item: diamond sword named Test Name: Test
> 
```
as you can see in the first example, it should be setting the name but it is not
in the second example, the item is named, but cant be renamed, and you can also see that it will not show the name in %name of {_item2}% (shows <none> even though its named)
example three, where I have paresed it as an item i can then set the name and %name of {_item3}% is correctly shown
 
### Expected Behavior
For names of items in variables to be able to be changed as well as shown when using %name of {variable}%

### Errors / Screenshots
no errors
No need for screenshots, I just tested this in console, output has been shown!

### Server Information
* **Server version/platform:** Paper-492
* **Skript version:**  Skript version 2.3.1

### Additional Context
I can't think of anything else to add.
I know this has been reported a couple times in other contexts in the past, I just wanted to create a new issue that specifically relates to the variable stored items and their names.

**Comment by ShaneBeee** [comment]
> #1802

thats a different issue.

**Comment by ham1255** [comment]
@ShaneBeee  read that code
blue cat commenited to that issue  with this code
```
executing 'set {a} to 5'
executing 'set {item} to stone'
executing 'set {name} to "test"'
executing 'send "%{a} of {item} named {name}%"'
```

**Comment by Snow-Pyon** [comment]
@ham1255 they are different issues. One is about passing ItemStack to the expression and it failing to be converted and the other about it being unable to get the name of items in a variable.
