### ISSUE TITLE
Permission Colors stopped working

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1809]
### Description
Permission colors in commands stopped working

### Steps to Reproduce
use this code:
```
command /test:
	permission: perm.perm
	permission message: &cYou do not have perm for this
	trigger:
		send "test"
```
it outputs:
"&cYou do not have perm for this" (not colored)
### Expected Behavior
It should send "You do not have perm for this" in red
### Errors / Screenshots
no errors
![](https://i.imgur.com/imoXyvf.png)

### Server Information
* **Server version/platform:** PaperMC (git-Paper-474 (MC: 1.13.2))
* **Skript version:** Skript version 2.3.1

**Comment by ham1255** [comment]
try use this §c

@ShaneBeee

**Comment by ShaneBeee** [comment]
well that is odd that works,

but still &c should work

**Comment by Nicofisi** [comment]
Do you have any clue what version this used to work in?

**Comment by Pikachu920** [comment]
The commit that fixed this was likely lost in the 1.13 merge, it should still be in commit history

**Comment by Blueyescat** [comment]
It works with cooldown messages but not permission messages

https://github.com/SkriptLang/Skript/pull/1047/files#diff-96afdca7bb9db518e3faac3e25164e9fR449

https://github.com/SkriptLang/Skript/commit/b26cf61002986784d5bc6801aad9811bd0741644#diff-96afdca7bb9db518e3faac3e25164e9fR426

@Pikachu920 you should have used the same code in any way

**Comment by ShaneBeee** [comment]
here is when pikachu pixed it
https://github.com/SkriptLang/Skript/commit/de0351cfe5b9704ae12fd8d02890561bedb19133

**Comment by bensku** [comment]
That commit should be back now.
