### ISSUE TITLE
AsyncEffect problems

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#1817]
### Description
The commit https://github.com/SkriptLang/Skript/commit/048ce296c2c3427bbbb5f9d128d150b802de0df3 broke many addons because temporary variables cannot be used anymore in async effects.
- MundoSK's async scope.
- await from skript-mirror.
- skript-db's execute.
- Many Vixio's syntaxes.

### Steps to Reproduce
Some examples:
```
set {_p} to player's name
set {_uuid} to uuid of player

execute "INSERT INTO test (player, uuid) VALUES (%{_p}%, %{_uuid}%)" in {sql}
```

```
await {_number}.toString()
```

### Expected Behavior
Temporary variables should work in async effects.

### Server Information
* **Server version/platform:** Paper 1.12.2
* **Skript version:** 2.3.1

### Additional Context
The current workaround is to use an useless async effect before setting the temp variables, which for some reason keeps them:
```
await 0.toString()
set {_p} to player's name
set {_uuid} to uuid of player

execute "INSERT INTO test (player, uuid) VALUES (%{_p}%, %{_uuid}%)" in {sql}
```
The code above works just fine.

Thanks.

**Comment by bensku** [comment]
Unfortunately, there is no easy solution. Originally, Skript used WeakHashMap for local variables, but it made them local per event, not trigger. Currently it is just a HashMap, and available local variables depend on currently executed trigger. This relies on the fact that triggers are not executee concurrently.

Access to local variables could, however, be provided - maybe as an argument to execute() or a field that is set by AsyncEffect.

**Comment by GermanMinerDE** [comment]
We have problems with this too, in Skript 2.3.3 & 2.3.2
Paper 1.12.2

We are using MundoSK's "async:"
Previous defined Temp-Variables aren't available in async (as described)

**Comment by AigleDev** [comment]
Solved or not
because all sql addons are not working !

**Comment by Syst3ms** [comment]
> Unfortunately, there is no easy solution. Originally, Skript used WeakHashMap for local variables, but it made them local per event, not trigger. Currently it is just a HashMap, and available local variables depend on currently executed trigger. This relies on the fact that triggers are not executee concurrently.
> 
> Access to local variables could, however, be provided - maybe as an argument to execute() or a field that is set by AsyncEffect.

Multiple things are to be taken from this : 

1. Skript is designed horribly, but that's nothing new. It uses too much static for async to function somewhat nicely
2. A clean solution would break tons of other things ; changing Skript's structure (even for the best) is a bad idea because of addons.
3. A hacky workaround seems necessary here.

**Comment by Blueyescat** [comment]
The current AsyncEffect has some big problems:
- [ ] It is not possible to use local variables **in** the async effect
- [ ] It doesn't run the async effect if there is no any other effect after the async effect

---
This will not run anything:
```vb
async effect "here"
```

This will run the async effect, but the input variable will be null:
```vb
set {_x} to "test"
async effect "%{_x}%"
set {_y} to {_y}
```

**Comment by antoinech2** [comment]
Hello, are there any new solutions to this problem?

The syntax `await 0.toString()` before the effect works well, but in function with parameters it clear all locals variables, so the parameters are cleared.

Exemple:
```
function RefreshClaimPermission(player:player):
	set {TEMP.local_variables} to {_player} 
	await 0.toString() #BDD FIX
	set {_player} to {TEMP.local_variables}
	execute unsafe "SELECT world_chunk,x_coord_chunk,z_coord_chunk FROM %{TEMP.config.database_table_storage}% WHERE owner = '%{_player}%'" in {mysql_db} and store the result in {_mysql_result::*}
```
I have to set the parameter in global variable. Then, i set it again into a local variable.

Is there another way to do that? This is really important because the addon skript-db is totally unusable.
