### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by titustitus98** [SkriptLang/Skript#1819]
hi there I am having an issue where my server keeps randomly crashing I have read through the error log and noticed it is due to skript

error log:
`12.01 11:44:16 [Server] ERROR The server has stopped responding!
12.01 11:44:16 [Server] ERROR Please report this to http://www.spigotmc.org/
12.01 11:44:16 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
12.01 11:44:16 [Server] ERROR Spigot version: git-Spigot-e8ded36-acbc348 (MC: 1.12.2)
12.01 11:44:16 [Server] ERROR ------------------------------
12.01 11:44:16 [Server] ERROR Server thread dump (Look for plugins here before reporting to Spigot!):
12.01 11:44:16 [Server] ERROR ------------------------------
12.01 11:44:16 [Server] ERROR Current Thread: Server thread
12.01 11:44:16 [Server] ERROR PID: 16 | Suspended: false | Native: true | State: RUNNABLE
12.01 11:44:16 [Server] ERROR Stack:
12.01 11:44:16 [Server] ERROR java.net.SocketInputStream.socketRead0(Native Method)
12.01 11:44:16 [Server] ERROR java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
12.01 11:44:16 [Server] ERROR java.net.SocketInputStream.read(SocketInputStream.java:171)
12.01 11:44:16 [Server] ERROR java.net.SocketInputStream.read(SocketInputStream.java:141)
12.01 11:44:16 [Server] ERROR sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
12.01 11:44:16 [Server] ERROR sun.security.ssl.InputRecord.read(InputRecord.java:503)
12.01 11:44:16 [Server] ERROR sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
12.01 11:44:16 [Server] ERROR sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
12.01 11:44:16 [Server] ERROR sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
12.01 11:44:16 [Server] ERROR sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
12.01 11:44:16 [Server] ERROR sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
12.01 11:44:16 [Server] ERROR sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
12.01 11:44:16 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
12.01 11:44:16 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
12.01 11:44:16 [Server] ERROR sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
12.01 11:44:16 [Server] ERROR java.net.URL.openStream(URL.java:1045)
12.01 11:44:16 [Server] ERROR uk.tim740.skUtilities.url.ExprUrlReadLine.get(ExprUrlReadLine.java:28)
12.01 11:44:16 [Server] ERROR uk.tim740.skUtilities.url.ExprUrlReadLine.get(ExprUrlReadLine.java:1)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
12.01 11:44:16 [Server] ERROR ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.Effect.run(Effect.java:52)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:93)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.function.Function.execute(Function.java:119)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.Effect.run(Effect.java:52)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
12.01 11:44:16 [Server] ERROR ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
12.01 11:44:16 [Server] ERROR ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:96)
12.01 11:44:16 [Server] ERROR ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:110)
12.01 11:44:16 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
12.01 11:44:16 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
12.01 11:44:16 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
12.01 11:44:16 [Server] ERROR net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
12.01 11:44:16 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
12.01 11:44:16 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)`

**Comment by titustitus98** [comment]
so if anyone could point me out on how to fix this it would be appreceated

**Comment by Pikachu920** [comment]
Use Reqn for your web requests and this crash will go away 👍

**Comment by titustitus98** [comment]
um sorry but what is Reqn?

**Comment by Pikachu920** [comment]
https://github.com/btk5h/reqn
