### ISSUE TITLE
Save chest contens in variable

### ISSUE THREAD

**Issue by CrazyWords1** [SkriptLang/Skript#1827]
### Description
I want to save chest contens in a variable , and i'm saved it, but after server restarting, variable is empty, how i can fix that or you fix that?

**Comment by Pikachu920** [comment]
the suggestion is adding a serializer to the inventory classinfo but that's easier said than done

**Comment by CrazyWords1** [comment]
suggestion

**Comment by CrazyWords1** [comment]
suggestion
