### ISSUE TITLE
Teleport Cause not working

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1832]
### Description
Teleport Cause is causing issues (hehe, see what I did there)
It is not registering the teleport causes

### Steps to Reproduce
Code I tried
```vb
on teleport:
	if teleport cause is ender pearl:
		send "PEARL"
	if teleport cause is gateway:
		send "GATEWAY"
	if teleport cause is plugin:
		send "PLUGIN"
```
here is the console output when I reload
```
> sk reload test
[20:33:07 INFO]: [Skript] Reloading test.sk...
[20:33:07 ERROR]: Can't compare a teleport cause with an item type (test.sk, line 5: if teleport cause is ender pearl:')
[20:33:07 ERROR]: Can't compare a teleport cause with 'gateway' (test.sk, line 7: if teleport cause is gateway:')
[20:33:07 ERROR]: Can't compare a teleport cause with a damage cause (test.sk, line 9: if teleport cause is plugin:')
[20:33:07 INFO]: [Skript] Encountered 3 errors while reloading test.sk!
```
### Expected Behavior
I expect it to load and recognize the teleport causes

### Errors / Screenshots
See steps to reproduce

### Server Information
* **Server version/platform:**  Paper version git-Paper-492 (MC: 1.13.2)
* **Skript version:**  Skript version 2.3.1

### Additional Context
None

**Comment by Pikachu920** [comment]
m

**Comment by ham1255** [comment]
@ShaneBeee 
try this 
```
if "%teleport cause%" is "%ender pearl%":
```

**Comment by Snow-Pyon** [comment]
@ham1255 yeah, that's going to work but the issue here is that the provided code should work. We could add some comparators to fix it, it'll only solve comparison issues though

**Comment by ham1255** [comment]
@snow-pyon well same thing on if damage cause is "void": it does give same error

**Comment by Snow-Pyon** [comment]
Yeah, we can add comparators to fix that. The best solution would be a context-sensitive parser but that's easier said than done.

**Comment by ShaneBeee** [comment]
Closing this in favour of #2637 
There are many issues on the tracker all stemming from this one big issue, so I wanted to condense this into one larger issue.
