### ISSUE TITLE
Grow state isn't working

### ISSUE THREAD

**Issue by Eole7** [SkriptLang/Skript#1837]
### Description
The growing state of plantations isn't working

### Steps to Reproduce
```
on break:
    broadcast "%event-block%"
```

### Expected Behavior
If we break a newly planted carrot, "stage three carrot plant" will be sent instead of "freshly planted carrot plant". Same for beetroot, "fully grown beetroot plant" is always sent even if the plant is in its first stage.

### Server Information
* **Server version/platform:**  Paper 1.12.2
* **Skript version:** 2.3.2

### Additional Context
This applies to all plantations

**Comment by bensku** [comment]
Please try again with latest Skript.

**Comment by bensku** [comment]
Closing due to no response. Hopefully this was fixed!
