### ISSUE TITLE
Could not pass event PlayerDeathEvent, drop skull

### ISSUE THREAD

**Issue by mogge42** [SkriptLang/Skript#1839]
### Description
Head drop skript broke when i updated to newest version of skript.

### Steps to Reproduce
on death of player:
	if attacker is a player:
		drop skull of victim with lore "Slain by %attacker%, At %now%" at victim
### Expected Behavior
Expected head to drop at death event location

### Errors / Screenshots
[Error](https://gist.github.com/mogge42/384e73bbb4fc2dba2baf42164235fd5d)

### Server Information
Skript v2.3.2 - Server version 1.12.2-R0.1-SNAPSHOT
[19:11:50 INFO]: [Skript] You're currently running the latest stable version of Skript.

**Comment by bensku** [comment]
You're running outdated SkQuery.
