### ISSUE TITLE
item name

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#1841]
### Description

if I didn't set any custom name for an item, 

I try to get a name of bone meal, but it say ink sac

### Steps to Reproduce

if name of player's tool is not set:
@set {_in} to name of player's tool
@send "%{_in}%"

### Server Information
* **Server version/platform:**      1.12.2  
* **Skript version:**              2.3.2

**Comment by bensku** [comment]
That expression only works with custom names of items. Also, cannot reproduce this on 1.12.2.
