### ISSUE TITLE
[Suggestion] Command default messages

### ISSUE THREAD

**Issue by HAHAYOUDEAD** [SkriptLang/Skript#1844]
### Description
There is unavoidable default message for "usage" entry, thus it's never been used by me. "cooldown message" is completely replaced by custom message, while "usage" still has "Correct usage: " in front of the text you put there.

### Suggestion
Replace wrong usage message completely with custom message, if set.

### How it would look
```
command /testing <text>:
    usage: <cyan>Usage: blabla
    trigger:
        send "hi"
```
![sk](https://user-images.githubusercontent.com/46863862/51550283-1e52d100-1e7d-11e9-8112-cc71a9d8de0f.png)

**Comment by Blueyescat** [comment]
It is possible to change it from the `lang` folder in the Skript jar file and you can move the `lang` folder to `plugins/Skript/`. 

But yes i agree that it is unnecessary and wouldn't break anything if Skript removes it.

**Comment by HAHAYOUDEAD** [comment]
@Blueyescat Yes, but you can't actually set it to nothing in lang files, at least I didn't find a way. It even sends "<reset>" in chat as is :c

**Comment by ham1255** [comment]
just put &c
