### ISSUE TITLE
on break of skull item

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#1847]
### Description

on break of skull item event does not work
### Steps to Reproduce

on break of skull item:
@send "good"

### Server Information
* **Server version/platform:**      1.12.2  
* **Skript version:**              2.3.2

**Comment by ShaneBeee** [comment]
1) Please stop tagging random people here. When you use `@` you are actually tagging a person named `send` ... that poor random person is probably confused

2) you dont break a skull `item` .... and Item is something in your hand, a block is something you break.

I do believe Bensku is well aware of this issue with the skulls and is still working on it.

**Comment by noy98** [comment]
oh, sorry for tagging someone

I didn't mean to it.

I just used to tab for skript 
-----Original Message-----

**Comment by bensku** [comment]
Don't use block break event for items.
