### ISSUE TITLE
On damage don't work

### ISSUE THREAD

**Issue by xGlenor** [SkriptLang/Skript#1849]
on damage:
	victim is fish or dolphins:
		attacker cannot build at block below:
			cancel the event

Help me, skript does't work

**Comment by ShaneBeee** [comment]
Are you reporting a bug or trying to get help with a script?

If you are reporting a bug, please use the proper issue template. 
`skript does't work` is very VERY vague, as Skript DOES work. You are going to need to put more information here.

If you are just looking for help with writing your script this is not the place.

**Comment by xGlenor** [comment]
Sorry, I didn't know
Please, delete or closed the
