### ISSUE TITLE
Sometimes when I start my server this appears

### ISSUE THREAD

**Issue by Padlick01** [SkriptLang/Skript#1852]
### Description
Sometimes when I start my server, Skript is spamming with error's

### Steps to Reproduce
I don't know how to do it, it's there on startup

### Errors / Screenshots
http://prntscr.com/mczv3s

### Server Information
* **Server version/platform:**       1.13.2 Paperspigot
* **Skript version:**                2.3.2

### Additional Context
When this error appears, none of my scripts are working at all. When I type in a command which is defined in a script, there is no reply.

**Comment by ShaneBeee** [comment]
That is caused by Skript Mirror
