### ISSUE TITLE
check item of player in function

### ISSUE THREAD

**Issue by ruddeTR** [SkriptLang/Skript#1855]
When I want to check item of player's inventory in function, there's no error but it doesn't work. I tested it on 2.3.2 version and Paper 1.3.2 build 509.

```
function Test(p: player):
	if {_p} doesn't have 16 iron ingot:
		send "true" to {_p}
	else:
		send "false" to {_p}
```

**Comment by bensku** [comment]
Try again with latest Skript. I remember fixing something like this.
