### ISSUE TITLE
Issues with bed block

### ISSUE THREAD

**Issue by LenjoyOfficial** [SkriptLang/Skript#1856]
### Description:
*My main language is not English, sorry for typos or grammatical mistakes!*
1. I can't find an alias for the bed block. If I get its type with a code, it says "BED_BLOCK" but it isn't working in the skript. I can only test it with the ID of bed (which is 26).
2. If I break a bed's foot part, and a code cancels the event, only the breaked part of bed appears back.
EDIT: This only works in creative mode!

### Steps to Reproduce:
1. If you test it normally:
`on break:`
`    if event-block is bed block:` <- also "bed block" is the name of bed item
I can only test it with it's id:
`on break:`
`    if id of event-block is 26:`
2. Write a code that cancels the break of bed:
`on break:`
`    if id of event-block is 26:`
`        cancel event`
Then break a bed's foot part
Note: If you break the bed's head part, it will work properly.

### Expected Behavior:
1. Bed should has an alias, like "bed block", and for item "bed item".
2. The head part of bed will also appear back.

### Errors / Screenshots:
![2019-01-28_17 44 46](https://user-images.githubusercontent.com/47115878/51851721-bf7dd380-2324-11e9-8d1c-b9678846ecc3.png)
![2019-01-28_17 44 48](https://user-images.githubusercontent.com/47115878/51851719-bee53d00-2324-11e9-9ec0-34419704b10d.png)

### Server Information:
* **Server version/platform:** CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)
* **Skript version:** 2.3.2

**Comment by TheBentoBox** [comment]
Weird, we do have the bed alias defined for 1.12 [here](https://github.com/SkriptLang/skript-aliases/blob/master/decoration.sk#L157). I can try to look more into this later but I'm not sure why that's happening off the top of my head.

**Comment by bensku** [comment]
On 1.12 and below, minecraft:bed is both bed block and item... For Spigot, though, there are two separate materials; BED and BED_BLOCK. I've managed to hack around this particular issue, but there are probably more.
