### ISSUE TITLE
color of glass pane

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#1859]
### Question

```vb
if arg 1 is "목록":
	open "chest" with 6 rows named "&8채널목록" to player
	set {_slot} to 0
	loop {채팅채널.정렬::*}:
		if {_slot} is 55:
			stop
		set {_amount} to size of {채팅채널.%loop-value%::*}
		if {_amount} is 0:
			set {_amount} to 1
		if {_amount} > 64:
			set {_amount} to 64
		if size of {채팅채널.%loop-value%::*} < 40:
			set slot {_slot} of current inventory of player to {_amount} of light_green_stained_glass_pane named "&f&l채널&7: &6%loop-value%" with lore "&f◈ &e채널인원&7: &a%size of {채팅채널.%loop-value%::*}%&f명&f&l / &7%{채팅채널.%loop-value%.최대인원수}%명", "&f◈ &e개설자&7: &6%{채팅채널.%loop-value%.개설자}%" and "&f"
		else:
			set slot {_slot} of current inventory of player to {_amount} of red_stained_glass_pane named "&f&l채널&7: &6%loop-value%" with lore "&d◈ &e채널인원&7: &a%size of {채팅채널.%loop-value%::*}%&f명&f&l / &7%{채팅채널.%loop-value%.최대인원수}%명", "&d◈ &e개설자&7: &6%{채팅채널.%loop-value%.개설자}%", "&f", "&d◈ &f해당 채널은 &c핫 플레이스 &f입니다." and "&f"	
		add 1 to {_slot}
```

color of glass pane does not work

**Comment by TheBentoBox** [comment]
What versions are your server and Skript? There are known bugs with data values in aliases not seeming to work well in versions prior to 1.13.

**Comment by noy98** [comment]
>           What versions are your server and Skript? There are known bugs with data values in aliases not seeming to work well in versions prior to 1.13.

server is 1.12.2 skript is 2.3.2

**Comment by Nicofisi** [comment]
Just to confirm, the issue is that the `set slot ...` line does nothing when you try to set `light_green_stained_glass_pane`, but it works with for example `stone`?

If so, does for instance `give light_green_stained_glass_pane to player` work?

Does it parse correctly but do nothing when run, or is there an error on reload?

**Comment by Snow-Pyon** [comment]
Support for underscores in item aliases have been removed in 2.3, use spaces instead.
