### ISSUE TITLE
Bring back "||" for lore splitting

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1861]
I noticed that you removed the option to split lore text into several lines with "||".
But this was a great feature and now it is much more complicated to work with variable lore text that has variable amount of lines.

**Example (this is no longer possible):**
set {_var} to 10
set {_test} to "Hello this my lore line 1||And here is a variable %{_var}%"
....
make a gui slot 1 of player with EMERALD with name "Test" with lore "%{_test}%"

There is no workaround, or did I miss something?

**Comment by TheBentoBox** [comment]
A couple of things:
1. We didn't remove anything, the usage of "||" as a line split was from skQuery. Lime removed it when Skript added its own full lore expressions.
2. Our lore expressions use lists of strings:

```
set {_test::*} to "Hello this is my lore line 1" and "And here is a variable %{_var}%"
make a GUI slot 1 of player with emerald with name "Test" with lore {_test::*}
```

If you have a text containing || that you want to use as lore, you can just do something like `... with lore ({_test} split at "||")`. The fact that lore operates as a list of strings also means you can do stuff like `loop player's tool's lore`.
