### ISSUE TITLE
JSON Text Doesn't Work Well With Variables

### ISSUE THREAD

**Issue by Bartuzen** [SkriptLang/Skript#1863]
### Description

If you send a text variable text contains JSON without putting it between "%%", then JSON doesn't work. It only works if I put the variable in "%%". (Its a bad explanation but you can understand it if you check the photo.)
### Steps to Reproduce

![-rojy9mosaaczsnpee3gyq](https://user-images.githubusercontent.com/15032958/52056067-4378cb00-2572-11e9-87ed-31142a6feec8.png)

### Expected Behavior

Both usages should result with a working JSON text.

### Server Information
* **Server version/platform:** 1.13.2 Paper      
* **Skript version:** 2.3.2

**Comment by ShaneBeee** [comment]
that's probably because `ttp` is nothing

As per the docs
```
tooltip | show text | Shows a tooltip when player hovers over text with their mouse
```
it's tooltip not ttp

**Comment by Bartuzen** [comment]
> that's probably because `ttp` is nothing
> 
> As per the docs
> 
> ```
> tooltip | show text | Shows a tooltip when player hovers over text with their mouse
> ```
> it's tooltip not ttp

No, `ttp` is alias of `tooltip`. And even if it wasn't, both result had to be like `<ttp:test>test`. And it also doesn't work with `tooltip`.

**Comment by TheBentoBox** [comment]
Not sure if this is quite a bug or an enhancement under the hood since I'm not sure what the implementation differences are between explicitly wrapping it as a string, but either way it appears as a bug from a user's perspective. Low prio though because as you've shown there's a very simple fix that users can do for now.

**Comment by Bartuzen** [comment]
> Not sure if this is quite a bug or an enhancement under the hood since I'm not sure what the implementation differences are between explicitly wrapping it as a string, but either way it appears as a bug from a user's perspective. Low prio though because as you've shown there's a very simple fix that users can do for now.

Yeah, its more of an enchantment. There is a workaround but `is already text` warning are making it bad.

**Comment by ShaneBeee** [comment]
1) my bad i didn't know that was an alias
2) it works (in game) because it was never meant to work in console, since console does not support hoverable or clickable messages.
![](https://i.imgur.com/4HSrRmT.png)

**Comment by Bartuzen** [comment]
> 1. my bad i didn't know that was an alias
> 2. it works (in game) because it was never meant to work in console, since console does not support hoverable or clickable messages.
>    ![](https://camo.githubusercontent.com/e988fefc64a953edfa5d9d73f181b3238153d2a8/68747470733a2f2f692e696d6775722e636f6d2f34485372526d542e706e67)

But photo is in game .-.

**Comment by ShaneBeee** [comment]
I'm aware, i just said that, it was never intended to work in console, its not supposed to work in console

**Comment by Pikachu920** [comment]
It purposefully only works with strings, see #1370 for info on why that is and how it could be changed
