### ISSUE TITLE
Both "Starts With" and "Ends With" Check End of the String

### ISSUE THREAD

**Issue by Bartuzen** [SkriptLang/Skript#1864]
### Description

So lets say I have a string named "test". If I say `if "test" ends with "st"` it says true, which is correct. And if i say `if "test" starts with "st"` it says true which is not correct. Both `starts with` and `ends with` check only end of the string.

### Steps to Reproduce

![download](https://user-images.githubusercontent.com/15032958/52111952-3c0afd80-2616-11e9-8a8d-839e790b6efe.png)
### Expected Behavior

`starts with` should check `starts with` instead of `ends with`.

### Server Information
* **Server version/platform:** Paper 1.13.2      
* **Skript version:** 2.3.2

**Comment by Snow-Pyon** [comment]
I believe this was fixed not so long ago, did it get lost in merge?

**Comment by bensku** [comment]
I think it was lost in conditions rework.
