### ISSUE TITLE
Make permissions work for offline players

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1865]
```
command /checkperm <offlineplayer>:
	trigger:
		if arg-1 has permission "mytestpermission":
			message "true"
```

# Does not work, when arg-1 is offline while executing this command

**Comment by Snow-Pyon** [comment]
Offline players don't have permissions, the way permission managers such as PEX or LuckPerms work is saving the permission a player has when it's online and then apply them when they join.

So, the only way to achieve this would be hooking into Vault (and thus hooking into a permission plugin that supports Vault), the problem with this is that this would make the condition dependent of two extra plugins, which is not ideal.

That said, I believe there's already another issue regarding this so I am closing this.
