### ISSUE TITLE
I want to set my list size to 10.

### ISSUE THREAD

**Issue by DetegiCE** [SkriptLang/Skript#1867]
`on command:`
`If sender is a player:`
`		set {_time} to now`
`		add "&f/%full command% &c(%{_time}%)" to {colog.%player%::*}`
`		If size of {colog.%player%::*} is bigger than 10:`

how can i do?

**Comment by Efnilite** [comment]
Is there something wrong in this code? Because the issues section is for solving bugs and stuff, not for asking help.

Also the syntax you're looking for is
`if size of {list::*} is greater than 10:` or `if size of {list::*} > 10:`
