### ISSUE TITLE
The right-click event is never called with "on door" specified

### ISSUE THREAD

**Issue by bolleboor** [SkriptLang/Skript#1868]
### Description
"on right click on door" / "on right click on wood door" is not working.
(I tried testing "on right click on glass" and that worked)

### Steps to Reproduce
Try to use "on right click on door:" and it is not responding.
I even tried with a simple message, but no answer.

I even tried:

on right click:
[TAB] if event-block is door:

### Expected Behavior
I expected it to be working fine.

### Errors / Screenshots
There is no error appearing in console.

### Server Information
* **Server version/platform:** 1.12.2      
* **Skript version:** 2.3.2

**Comment by bolleboor** [comment]
Still an issue.

**Comment by bolleboor** [comment]
This is still an issue and isn't fixed in 2.3.4

**Comment by GermanMinerDE** [comment]
Still in 2.3.5

**Comment by Nicofisi** [comment]
As a bad and temporary workaround you could probably do something like:
```
on right click:
    "%event-block%" contains "door"
    do blah blah blah
```

**Comment by FranKusmiruk** [comment]
I cannot seem to reproduce on 1.13.2, can someone confirm this is only a 1.12 issue?

**Comment by bensku** [comment]
It is 1.12 specific. On 1.13 we can properly ignore unspecified block states, but on 1.12 it is a bit harder.

**Comment by TheBentoBox** [comment]
2.4 alphas have fixed most item comparison bugs. Iron doors do have proper aliases so this should be resolved.
