### ISSUE TITLE
Getting spammed with (debug?)-messages in console

### ISSUE THREAD

**Issue by Duetro** [SkriptLang/Skript#1870]
### Description
Since Skript 2.3.3 (latest) the console is getting spammed by debug-messages maybe? At the Server start there were about 10/sec, after the complete start there is about 1/sec. I tried setting verbosity to low but it didn't help.

### Steps to Reproduce
We are using latest Paper 1.12.2 and Skript 2.3.3. We just updated and this happened.

### Expected Behavior
These Messages shouldn't be there

### Errors / Screenshots
Screenshot: https://s.duetro.de/i/mstsc_2019-02-03_14-16-49.png
Pastebin: https://pastebin.com/raw/PnCiK0yg

### Server Information
* **Server version/platform:**  git-Paper-1596 (1.12.2-R0.1-SNAPSHOT)
* **Skript version:** Skript 2.3.3

**Comment by Duetro** [comment]
I guess that's the commit that's causing this problem:
https://github.com/SkriptLang/Skript/commit/56b16b1b9452d93049ee2737701c765f3aeefdc2#diff-f799f5087e8eb137b53ba101b2de77cf

**Comment by bensku** [comment]
Oops
