### ISSUE TITLE
Player's tool is not detected as item

### ISSUE THREAD

**Issue by YellowZaki** [SkriptLang/Skript#1871]
```
set {_item} to player's tool
if {_item} is fishing rod:
	broadcast "DEBUG3"
```
Doesn't work, but

```
set {_item} to fishing rod
if {_item} is fishing rod:
	broadcast "DEBUG3"
```
It does work

Server Information
Server version/platform: Spigot 1.13.2
Skript version: 2.3.3

**Comment by bensku** [comment]
Note that tool is always the item in main hand. Use event-item if you want the used item.

**Comment by Blueyescat** [comment]
@bensku i knew that but it doesn't do that
![image](https://user-images.githubusercontent.com/19474570/52217833-55c47300-28aa-11e9-8c7f-4e3c92592fc7.png)

**Comment by bloggy** [comment]
For me this works. I have just tested it:

```
command /tooltest [<text>]:
	trigger:
		set {_item} to player's tool
		if {_item} is fishing rod:
			broadcast "DEBUG3"
```

[https://i.imgur.com/Hmq1TVG.png](url)

**Comment by YellowZaki** [comment]
Well, it seems it doesn't work because my fishing rod was damaged, but that was what I was trying to do, repair my item in hand if it is a fishing rod.

**Comment by bloggy** [comment]
> 
> 
> Well, it seems it doesn't work because my fishing rod was damaged, but that was what I was trying to do, repair my item in hand if it is a fishing rod.
> 
> EDIT: I have just discovered a lot of my skripts are not working when trying to detect if player's tool is x and x is damaged. It used to work.

**He is right.**
I just tested it. There seem to be a **bug with damaged items/tools.**

My script:
```
command /tooltest [<text>]:
	trigger:
		set {_item} to player's tool
		broadcast "Item: %{_item}%"
		if {_item} is a fishing rod:
			broadcast "FISHING ROD"
		if {_item} is iron axe:
			broadcast "IRON AXE"
		if {_item} is bow:
			broadcast "BOW"
```

Using a damaged bow, I get these results:
`Item: bow`

Using a non-damaged bow, I get these results:
```
Item: bow
BOW
```

It only returns BOW when the bow is not damaged at all. Same for all the other tools I have tested.

**Comment by YellowZaki** [comment]
@TheBentoBox I've discovered the issue is more serious. It doesn't detect the item if has a name/has lore/is damaged...
Basically, if the item is modified, it is not detected.

**Comment by TheBentoBox** [comment]
Can anyone else verify this? Might be worth pushing to critical prio since it sounds like it would break a ton of stuff.

For now, if you're experiencing these issues, I'd recommend downgrading.

**Comment by YellowZaki** [comment]
Note: I have downgraded to 2.3.2 and the issue is resolved. Items are detected even if they are damaged/has lore.

**Comment by bensku** [comment]
@TheBentoBox You were right about the cause of this issue :)
