### ISSUE TITLE
Update.

### ISSUE THREAD

**Issue by wohahobg** [SkriptLang/Skript#1872]
### Question

Hey there, my question is simple.. So I try to update from 2.3.2 to 2.3.3 but really I cannot ? it always send me in console:
> 04.02 10:03:07 [Server] INFO [Skript] Enabling Skript v2.3.2
04.02 10:03:08 [Server] INFO [Skript] A new version of Skript is available: 2.3.3 (you're currently running 2.3.2)
04.02 10:03:08 [Server] INFO Download it at: <aqua><u><link:https://github.com/SkriptLang/Skript/releases/download/2.3.3/Skript.jar>https://github.com/SkriptLang/Skript/releases/download/2.3.3/Skript.jar
04.02 10:03:09 [Server] INFO [Skript] Loaded 71394 aliases in 2117ms
04.02 10:03:09 [Server] INFO [Skript]  ~ created by & © Peter Güttinger aka Njol ~

So I try few things:
- try to remove whole folder.
- try it on my localhost
- try it on totally different server
I have download it more then 5 times..
and always its say I am on 2.3.2 :( ?

so why it always it say have to be update ? is this any mistake or it is any kind of bug by my self? 

I am putting my issue here because its is a question not sure if it's bug.

**Comment by Blueyescat** [comment]
You are actually using 2.3.3 but the versions in the Skript jar is not updated by a mistake. You can ignore the  message.

**Comment by BlightedBlue** [comment]
bensku forgot to update the version when he released 2.3.3, like Blueyes said, just ignore it. It should be fine in the next update.

**Comment by wohahobg** [comment]
Lovly thanks!

**Comment by wohahobg** [comment]
Great thanks.
