### ISSUE TITLE
Giving a multiplied amount of something has no effect

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1874]
I am using version: Loading Skript v2.3.2
I am on: 1.13.2 PaperSpigot

The code:
```
set {_menge} to 10
set {_samount} to 10
set {_testitem} to apple
give {_menge}*{_samount} of {_testitem} to player
```
**This does not work! No errors but does not give any item to the player.**

The code:
```
set {_menge} to 10
set {_samount} to 10
set {_testitem} to apple
set {_anzahl} to {_menge}*{_samount}
give {_anzahl} of {_testitem} to player
```
**This works!**

**Comment by bensku** [comment]
When did this issue start occurring?

**Comment by bloggy** [comment]
> 
> 
> When did this issue start occurring?

I don't know exactly. But it does NOT HAPPEN on my old 1.12 server with this version of skript:
Enabling Skript v2.2-dev36

**Comment by bensku** [comment]
Surprisingly enough, your code seems to work. Maybe this bug was caused by some deeper issue that has been fixed.
