### ISSUE TITLE
WorldGuard hook doesn't work correctly on 1.12.2

### ISSUE THREAD

**Issue by wohahobg** [SkriptLang/Skript#1875]
Hello today I just try to do something with world guard but without effect.
I try to execute player command with the code below on [**Server Version 1.12.2**](http://prntscr.com/mgikjk)
```
on region enter:
	wait 1 tick
	if "%region at player%" contains "test":
		execute player command "test"
command /test:
	trigger:
		broadcast "&c&lTEST TEST TEST TEST"
```
The code working well on **Server Version 1.13.2** but does not working on ***Server Version 1.12.2***
 [https://dev.bukkit.org/projects/worldguard/files/2610618](https://dev.bukkit.org/projects/worldguard/files/2610618)

### Server Information
* **Server version/platform:**  1.12.2
* **Skript version:**   2.3.3

**Comment by GermanMinerDE** [comment]
We are currently using WorldGuard 6.2.2-SNAPSHOT 8eeab68 on latest Paper 1.12.2
Skript 2.3.3

Linking into WorldGuard does not work, error while loading Skripts with "%region at player%" (unknown effect / condition)

**Comment by Plutoren** [comment]
I would like to vouch for this issue.

Take this example code:
```
command /regionat:
	permission: is.op
	trigger:
		message "%regions at player%"
```
It displays `<none>` despite being in a region.

I am also running paper 1.12.2 with latest fawe/skript/wg

Reverting skript to 2.3.2 resolves the issue but I really want to update to fix all the alias bugs so I would appreciate a fix on this issue, cheers.

**Comment by bensku** [comment]
Adding FAWE support for 1.13 broke it for 1.12. Normal WorldGuard still worked.
