### ISSUE TITLE
Remove all from - not working

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1878]
Spigot: Paper 1.13.2
Skript: Skript v2.3.3
Errors in console: no errors

My script
```
command /remall [<text>]:
	trigger:
		set {_text} to "This is a test!!!"
		remove all "!" from {_text}
		broadcast {_text}
```

**Result:**
This is a test!!!

**Expected result:**
This is a test

**Comment by Efnilite** [comment]
You can try using `replace all "!" with "" in {_text}` since I don't know if `remove all "!" from {_text}` works in Skript

**Comment by Snow-Pyon** [comment]
This is intended behaviour and there are reasons why this shouldn't work either way. Use what Efnilite suggested above.
