### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#1879]
### Description

I don't know but the skript doesn't work.
### Expected Behavior

it is not working
### Server Information
* **Server version/platform:**       1.12.2 
* **Skript version:**               2.3.3

**Comment by TheBentoBox** [comment]
Try writing it like this?: `drop loop-value of ({_a} parsed as item type) at player's location`. The parentheses may help because currently it's not clear what you're parsing.

**Comment by noy98** [comment]
thank you
