### ISSUE TITLE
"event-entity" is not set in the trigger "on death of x"

### ISSUE THREAD

**Issue by YellowZaki** [SkriptLang/Skript#1881]
I used to do:

**on death of slime:
     event-entity's name is "x"**

Now, event-entity is not set (and it doesn't show as an error in the log) and I have to do

**on death of slime:
     slime's name is "x"**

Skript version: 2.3.2

**Comment by Pikachu920** [comment]
if this did work at some point it shouldn't have - skript is meant to force you to use attacker or victim like @Efnilite said
