### ISSUE TITLE
Skript deletes MySQL table on startup

### ISSUE THREAD

**Issue by diamondpumpkin** [SkriptLang/Skript#1882]
Spigot: 1.13.2 Build (I don't actually know, it's difficult to tell with the BuildTools thing. I update it frequently.)
Skript: 2.3.3
SQLibrary: 7.1
MySQL: 14.14 Distrib 5.5.59

Issue:
Configuring the config.yml as shown below successfully connects to the database and I'm able to read and write data to it. When I restart the server it mistakenly thinks I've changed something in the pattern, from what I've gathered at least and deletes the entire table. Resulting in complete loss of all variables stored in the MySQL database.

config.yml
```
databases:
	MySQL:
		type: MySQL
		pattern: db_.*
		host: 0.0.0.0
		port: 3306
		user: skript
		password: youreallythinkiwouldgiveyouthis
		database: skript
		table: variables
		monitor changes: true
		monitor interval: 20 seconds
	default:
		type: CSV
		pattern: .*
		file: ./plugins/Skript/variables.csv
		backup interval: 2 hours
```

Console output on startup

```
07.02 17:23:17 [Server] INFO [Skript] Loading variables...
07.02 17:23:17 [Server] INFO [Skript] Successfully deleted the old variables table from the database 'MySQL'.
07.02 17:23:17 [Server] INFO [Skript] Loaded 10 variables in 0.2 seconds
07.02 17:23:18 [Server] INFO [Skript] All scripts loaded without errors.
07.02 17:23:18 [Server] INFO [Skript] Loaded 2 scripts with a total of 8 triggers and 4 commands in 0.72 seconds
07.02 17:23:18 [Server] INFO [Skript] Finished loading.
```
Very high verbosity shows the samething.
shortly after
```
07.02 17:23:37 [Server] ERROR [Skript] database error: No operations allowed after statement closed.
07.02 17:23:57 [Server] ERROR [Skript] database error: Table 'minecraft.variables' doesn't exist
```
It does like to alternate, so once it's delete the database, and I start it again it works fine until I restart it again, repeating the cycle.

**Comment by DaviPatrick** [comment]
Using latest version and is not deleting.

**Comment by diamondpumpkin** [comment]
> Using latest version and is not deleting.

Just tried again with 2.3.3. Getting the same error, if I remove permissions to drop tables for the user I get this.

```
08.02 14:53:56 [Server] INFO [Skript] Loading variables...
08.02 14:53:56 [Server] ERROR #!#! 
08.02 14:53:56 [Server] ERROR #!#! ===!!!=== Skript variable load error ===!!!===
08.02 14:53:56 [Server] ERROR #!#! Unable to load (all) variables:
08.02 14:53:56 [Server] ERROR #!#! There was an error deleting the old variables table from the database 'MySQL', please delete it yourself: DROP command denied to user 'minecraft'@'s114323.wholesaleinternet.net' for table 'variables'
08.02 14:53:56 [Server] ERROR #!#! 
08.02 14:53:56 [Server] ERROR #!#! Skript will work properly, but old variables might not be available at all and new ones may or may not be saved until Skript is able to create a backup of the old file and/or is able to connect to the database (which requires a restart of Skript)!
08.02 14:53:56 [Server] ERROR #!#! 
08.02 14:53:56 [Server] INFO [Skript] Loaded 10 variables in 0.2 seconds
08.02 14:53:56 [Server] INFO [Skript] All scripts loaded without errors.
08.02 14:53:56 [Server] INFO [Skript] Loaded 1 script with a total of 0 triggers and 1 command in 0.24 seconds
08.02 14:53:56 [Server] INFO [Skript] Finished loading.
```

**Comment by diamondpumpkin** [comment]
Tried 2.3.4 as well, samething. It really thinks the database contains 'old variables'.

**Comment by Nicofisi** [comment]
From a quick glance at the code: `variables` seems to be a table name reserved for old Skript versions(??). If your table is called this way, Skript tries to port it to a new format. The default name of the variable table in Skript versions released in the past few years is `variables21`. Try using it, or just anything other than `variables`. Still, it's a very confusing behavior and I don't think the easiest fix in general would be to just consider removing this code, now that it's 2019

**Comment by diamondpumpkin** [comment]
> From a quick glance at the code: `variables` seems to be a table name reserved for old Skript versions(??). If your table is called this way, Skript tries to port it to a new format. The default name of the variable table in Skript versions released in the past few years is `variables21`. Try using it, or just anything other than `variables`.
> 
> Still, it's a very confusing behavior and I think the easiest fix to prevent such confusion in the future would be to just consider removing this code, now that it's 2019

This seems to have worked, kind of annoying that this is a thing. OCD doesn't like extra numbers at the end of the table name.

**Comment by Snow-Pyon** [comment]
You can change the table name by adding the `table` entry to your db config, there should also be an example of it in the default configuration.

**Comment by Nicofisi** [comment]
@Snow-Pyon yeah, he knows it and did change it, from `variables21` to `variables`. So in my opinion this issue is quite severe since `variables` is probably the first name everyone comes up with 💭 

I think we should either
- delete the code for porting variables from Skript <2.1 altogether
- make it somehow detect whether the table `variables` already contains variables in the "new format", whatever it is, and then not try to do anything with it in such case
- at least mention the fact that `variables` is a reserved name that causes data loss in the config... listen how bad this idea sounds though
