### ISSUE TITLE
Suggestion: Ability to use entity as argument and parse text as entity

### ISSUE THREAD

**Issue by diamondpumpkin** [SkriptLang/Skript#1883]
Skript: 2.3.3

I'm trying to create a small script that'll allow me to spawn a mob of my choosing and how many in a command.

```
command /mob <entity> <number>:
    trigger:
        spawn arg number of arg entity at target block
```
This doesn't work with error `Can't use entity as argument of a command`
Also tried
```
command /mob <text> <number>:
    trigger:
        set {_mob} to arg text parsed as entity
        spawn arg number of {_mob} at target block
```
which tells me `Text cannot be parsed as an entity`. I know in previous versions of Skript you were able to do this.

**Comment by Pikachu920** [comment]
You couldn't do this previously - are you thinking of entity type?

**Comment by Snow-Pyon** [comment]
The `entity` type refers to actual existing entities in the world, whereas `entity type` refers to well, an entity type such as skeleton or zombie, that's what you're looking for.
