### ISSUE TITLE
random lore add

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#1884]
### Question
 skript 2.3.3 they changed lore like with lore "", "" and ""
I just want to make a skript like shop, so I had to make a lore split by "||" in version 2.2.
but for skript 2.3.3 how to get lores of custom items and add random line of lore?

ex) the item is namd "custom" and lores are "-happy", "-sad" and "bad"
but I want to add lores "- Right click to buy", "- Left click to sell" on random  like of the items

**Comment by Nicofisi** [comment]
There you go - https://github.com/SkriptLang/Skript/issues/1861#issuecomment-458987029

Also, I highly recommend reading the release notes for Skript 2.3(.1) - https://github.com/SkriptLang/Skript/releases/tag/2.3.1
