### ISSUE TITLE
Right click holding ___ event

### ISSUE THREAD

**Issue by BearoTooth** [SkriptLang/Skript#1885]
Broken in latested update, used latest update posted and right click holding compass actions broken, same as holding clock. Used version before it, works fine. - Using version 1.13.2 spigot file. <- please look into.

**Comment by bensku** [comment]
Please provide your Skript version and a sample script that works without addons and demonstrates the issue.

**Comment by BearoTooth** [comment]
it's been solved in one of the current updates.
