### ISSUE TITLE
Error in lore of item

### ISSUE THREAD

**Issue by varthex** [SkriptLang/Skript#1886]
Skript version:  2.3.4
Spigot version: 1.13.2

Code: https://pastebin.com/raw/b0cwRe3q
Error: https://youtu.be/992lMKIF2QQ

**Comment by Efnilite** [comment]
What's the error and what is wrong, that's very unclear lol

**Comment by TheBentoBox** [comment]
This line is incorrect: `set {_loreItem::*} to the lore of {_item} split at "||"`. If you're not getting errors from it then you probably have an outdated version of skQuery. If you want to set a list variable to the lines of an item's lore, just do `set {_loreItem::*} to lore of {_item}`, Skript's lore expression already returns the lore as a list of strings with each one being a line.

**Comment by varthex** [comment]
I updated Skquery

Why lore duplicates? Restart the script fixes the error for a while

https://youtu.be/DsLza0hrio0
Code: https://pastebin.com/raw/3biKBZ1q

**Comment by bloggy** [comment]
I guess this is the same bug as https://github.com/SkriptLang/Skript/issues/1813

**Comment by TheBentoBox** [comment]
If this is the same as #1813 we'll track there
