### ISSUE TITLE
Checking item's name is broken!

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1888]
### Description
On chat you'll get test1 test2 test test 3 only having 3 unnamed diamonds!! And all 3 diamonds dissapears!

### Steps to Reproduce
code:
```
command /wtf2:
	trigger:
		if player have 1 diamond:
			remove 1 diamond from player's inventory
			send "&aTest1"
		if player have 1 diamond named "&4Test":
			remove 1 diamond named "&4Test" from player's inventory
			send "&aTest2"
		if player have 1 diamond named "&4Test" with lore "&cTest":
			remove 1 diamond named "&4Test" with lore "&cTest" from player's inventory
			send "&aTest test 3"
```
get 3 diamonds (normal, unnamed) and type /wtf2
### Expected Behavior
When you have only 3 normal diamonds, you should get only one message! (test 1) And it shouldn't remove diamonds xd

### Server Information
* **Server version/platform:**       paper-487
* **Skript version:**                latest! (on 2.3.2 works perfectly!)

### Additional Context
I'm back to 2.3.2 :( Why new versions are so buggy

**Comment by bensku** [comment]
> Why new versions are so buggy
See #1195 for an explanation.
