### ISSUE TITLE
"%player%'s name" Expression Doesn't Work With Variables

### ISSUE THREAD

**Issue by Bartuzen** [SkriptLang/Skript#1889]
### Description

"%player%'s name" expression doesn't work with variables. Just check the code below to see what I mean.
### Steps to Reproduce

```vb
command /s:
	trigger:
		set {_p} to player
		send "%player's name%"
		send "%{_p}'s name%"
```
Prints:
```vb
Bartuzen
<none>
```

### Server Information
* **Server version/platform:** Paper 1.13.2      
* **Skript version:** 2.3.4

**Comment by Efnilite** [comment]
You set `{_s}`  to the player's name and you use `{_p}'s name` lol

**Comment by Bartuzen** [comment]
Yeah? What is the problem?

**Comment by Bartuzen** [comment]
Yeah thats very stupid. But it results same with correct variables.

**Comment by Efnilite** [comment]
Can't confirm this on 1.13.2 with 2.3.4,
```command /d:
	trigger:
		set {_p} to player
		send "%player's name%"
		send "%{_p}'s name%"```
prints out
```Efnilite
Efnilite```

**Comment by Bartuzen** [comment]
Addon issue I guess.
