### ISSUE TITLE
item "types" comparison no longer working, same for options

### ISSUE THREAD

**Issue by melinstagibson** [SkriptLang/Skript#1892]
So at least those 2 scripts broke with the last update. i dont even know how many others are affected....

```
on block break:
        "%lore of player's tool%" contains "Smelting"
        if player's tool is a pickaxe:
                send "test"
```
```
on consume of cookie:
        player has permission "donor"
        if event-item is {@redpill}:
            send "test"
```
i should probably user more of skript-mirror stuff for the critical scripts, thats the second time my eco went to shit due to an update :(

**Comment by iOshawott** [comment]
checking name/lore is broken on latest #1888 checking event-items is broken too. It's not your fault. It's duplication of my issue
