### ISSUE TITLE
Some problems with Skulls

### ISSUE THREAD

**Issue by Duetro** [SkriptLang/Skript#1893]
### Description
The only way i know to detect a click on a head is this code:
```
on click:
    "%event-block%" is "SKULL"
```
-> it's not possible to use `on click on skull:`

also: It's not possible to set a block to an player head (tested with default skin - no custom nbt)

### Steps to Reproduce
Just try the code above

### Expected Behavior
`on click on skull:` (error at load)
`on click on player head:` (loads, but doesn't work)
`set block at player to skull` (error at load)
`set block at player to player head` (no error, but doesn't work)

### Server Information
* **Server version/platform:**       git-Paper-1596 (MC: 1.12.2)
* **Skript version:**                Skript 2.3.5 (latest) [tested with 2.3.4, 2.3.3, 2.3.2]

**Comment by Nicofisi** [comment]
Related to #1877

**Comment by GermanMinerDE** [comment]
Same here, not only with skulls.

**Here with:**
`on rightclick:
    clicked block is iron door` (not working, no errors)

`on rightclick on iron door:` (not working, no errors)

`on rightclick on IRON_DOOR_BLOCK:` (error on load, but "IRON_DOOR_BLOCK" is, what comes out when doing "%target block%" while looking on the block.)

**Only thing that works (and parsing every item-type to string is definitely not that, what you should do every time):**
`on rightclick:
    "%clicked block%" is "IRON_DOOR_BLOCK"`


Skript 2.3.5
Paper 1596 (MC 1.12.2)

**Comment by TheBentoBox** [comment]
There have been numerous item comparison bugs resolved recently, especially on 1.12 and below. This should hopefully be resolved now.
