### ISSUE TITLE
How to get the code of a specific version ?

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#1895]
### Question
Hi, I would like to know if it was possible to get the source code of a certain version, for example I'm looking for Skript2.2-dev36, is there any way to find the code for that verison, or if not, the latest commit that has been done for this version ?

**Comment by Efnilite** [comment]
You can find it by browsing to the releases > your version tag > the random number under the title > view files, current link for dev36 is https://github.com/SkriptLang/Skript/tree/cf46b68d8614af5792ba014f6b592ffd7c470fbf

**Comment by TheBentoBox** [comment]
The zipped source code is also available under each release on the releases page:

![image](https://user-images.githubusercontent.com/6902229/52717910-3398b800-2f70-11e9-9fd5-223ad23a31ce.png)

**Comment by Blueyescat** [comment]
![image](https://user-images.githubusercontent.com/19474570/52718064-a11a0800-2fb3-11e9-92a1-2209b562587f.png)

**Comment by Matocolotoe** [comment]
Thank you very much @Efnilite @TheBentoBox @Blueyescat !
