### ISSUE TITLE
Bedrock and End Crystal bug

### ISSUE THREAD

**Issue by MisterPawlak** [SkriptLang/Skript#1896]
Hi, write down the code below.

on place:
	if event-block is bedrock:
		cancel event
		send "Example"

And try to resurrect the dragon using this method: https://i.imgur.com/5yh1wU3.png

After the resurrection of the dragon, this message will appear for no apparent reason.

**Comment by APickledWalrus** [comment]
This may be because the crystals on the tower are reset/replaced during the resurrection of the dragon. (Or because you’re placing crystals on bedrock for the resurrection to start?)

**Comment by Matocolotoe** [comment]
is Minecraft that broken to make the player manually place the crystals on the bedrock lol

**Comment by APickledWalrus** [comment]
Is the message being sent to you or the console or?

**Comment by Matocolotoe** [comment]
I believe he must be online to resurrect the dragon

**Comment by bensku** [comment]
Sounds like a Minecraft bug to me. Can you find any other cases where this happens?

**Comment by Dad3** [comment]
I would also like to prevent end crystals being placed on obsidian/bedrock if anyone can help with that.

**Comment by TheBentoBox** [comment]
Likely a Minecraft issue and we never received more info.
