### ISSUE TITLE
Doors aren't close

### ISSUE THREAD

**Issue by bbobbo6742** [SkriptLang/Skript#1897]
On Spitgot 1.13.2 and Skript 2.3.5,

Command /a:
  trigger:
    close target block

The door does not close but only toggles.

**Comment by Efnilite** [comment]
All of these 3 syntax
```
(close|turn off|de[-]activate) %blocks%
(toggle|switch) [[the] state of] %blocks%
(open|turn on|activate) %blocks%
``` do the exact same thing, so I think this is intended and just a confusing pattern 🤔

**Comment by Nicofisi** [comment]
Maybe whoever wrote the effect considered it unimportant or forgot, it should be an easy fix though
