### ISSUE TITLE
Using Skript variables in Java code

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#1898]
### Question
Is it possible to get Skript variables from a string in Java code ?
For instance : `Skript.getVariable.fromString("kills.matocolotoe")`

**Comment by Efnilite** [comment]
If you knew Java, yes, but this is not the place for questions. It's for bug reports.. lol
Also the syntax for it is `Skript.getVariable(String name, Event event, boolean isLocal)` or something like that, you can take a look at Skript's main class for that

**Comment by Blueyescat** [comment]
There is a `question` label and a `Question` issue template (added because the label), but probably the issue template should get removed assuming the owners wouldn't want every simple question here.

**Comment by Matocolotoe** [comment]
Thanks and sorry @Blueyescat :/

**Comment by Blueyescat** [comment]
There's nothing wrong with you

**Comment by Matocolotoe** [comment]
Thought I was doing something wrong by posting a question on the issue tracker xd
