### ISSUE TITLE
on break of ripe wheat

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#1899]
### Description

on break of ripe wheat
### Steps to Reproduce

on break of ripe wheatv
### Expected Behavior

on break of ripe wheat

it doesn't understand
### Server Information
* **Server version/platform:**       1.12.2 
* **Skript version:**               2.3.4

**Comment by Efnilite** [comment]
Can confirm this with 1.12.2 and running 2.3.5, it appears there's something with this alias: 
```
{crop growth stage} wheat plant¦s = minecraft:wheat
```
and the crop growth stage? (
```
{crop growth stage}:
	{default} = - {Damage:7}
	freshly planted = - {Damage:0}
	stage (2|two) = - {Damage:1}
	stage (3|three) = - {Damage:2}
	stage (4|four) = - {Damage:3}
	stage (5|five) = - {Damage:4}
	stage (6|six) = - {Damage:5}
	stage (7|seven) = - {Damage:6}
	(ripe|fully grown|stage (8|eight)) = - {Damage:7}
```
As you can see, `ripe` should be working

**Comment by noy98** [comment]
> ripe wheat doesn't exist, use ripe wheat plant, that's the correct alias:
> {crop growth stage} wheat plant¦s = minecraft:wheat

still does not work

**Comment by TheBentoBox** [comment]
Try upgrading to 2.3.5, it fixed some major item comparison bugs. And show your updated code.

**Comment by Efnilite** [comment]
I tested in 2.3.5 and it worked, so you should upgrade 👍

**Comment by noy98** [comment]
> Try upgrading to 2.3.5, it fixed some major item comparison bugs. And show your updated code.

I upgraded to 2.3.5, but still doesn't work

**Comment by noy98** [comment]
> Try upgrading to 2.3.5, it fixed some major item comparison bugs. And show your updated code.


on break:
	if event-block is fully grown wheat plant:
		cancel event

does not work

**Comment by Efnilite** [comment]
What does not work? It errors?

**Comment by noy98** [comment]
@Efnilite

Cancel event does not work

**Comment by Hexivoid** [comment]
@noy98 No more errors though?

**Comment by TheBentoBox** [comment]
@Efnilite Would you mind testing and seeing if `cancel event` works for you in this scenario? And are you testing in 1.12.2 like the reporter or are you in 1.13?

**Comment by bensku** [comment]
Please respond to requests for more information if you want your issues solved.

**Comment by SiebeDW** [comment]
I tested using the code
`
on break of ripe wheat plant:
	cancel event
`
Like @Efnilite scenario
It does cancel the event so there is no issue here anymore.
