### ISSUE TITLE
Materials aren't working...

### ISSUE THREAD

**Issue by RepublicanSensei** [SkriptLang/Skript#1900]
### Description
Skript cannot read the items.

### Steps to Reproduce
if block under player isn't LAVA or WATER or AIR:

### Errors / Screenshots
[00:23:29 ERROR]: Can't compare a block with ('LAVA', 'WATER' or 'AIR') 

### Server Information
* **Server version/platform:**       lastest 1.13.2 (i tried 1.13 and 1.13.1 none worked)
* **Skript version:**               lastest

### Additional Context
please help me

**Comment by Efnilite** [comment]
What is latest? /ver Skript please

Also this *does* work on 1.13.2 with Skript 2.3.5, current code 
```
on command:
	if block under player isn't LAVA or WATER or AIR:
		send "yep, it works"
```
prints `yep, it works` just fine, with no errors on reload

**Comment by bensku** [comment]
Cannot reproduce even on 1.12.
