### ISSUE TITLE
Colored note particles

### ISSUE THREAD

**Issue by ITCHI14** [SkriptLang/Skript#1901]
The note particle spawn only one color is this a cyan color only
Please add the ability to make colored notes
This is my code:
```
loop 1200 times:
    wait 5 ticks
    if {disc::%player%::*} is set:
        show note on location above the clicked block
    else:
        stop
```

**Comment by TheBentoBox** [comment]
I'm pretty sure we have some support for colored visual effects already... but not sure if it applies to notes and it's not documented in the docs very well.

**Comment by Blueyescat** [comment]
Yeah colored notes isn't supported: [english.lang#L1164](https://github.com/SkriptLang/Skript/blob/master/src/main/resources/lang/english.lang#L1164)
