### ISSUE TITLE
Any way to disable auto-completion ?

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#1903]
### Question
I was wondering if there was any setting or value to change to disable auto-completion, that is to say you would have to enter the exact name of a player on a command to run successfully.

For example, if I create a /test command with a player or an offline player as a first argument, and I execute /s Mato, it will do /s Matocolotoe.

It's frustrating if you have players with very similar names online.

**Comment by BlightedBlue** [comment]
This is not a bug report or an enhancement request, to my knowledge. For help with coding scripts / Skript help, use the respective discord servers. ([skUnity Discord](https://discord.gg/Daa2jTC))

**Comment by bensku** [comment]
It is not possible at the moment. Would be good to have, though.

**Comment by Matocolotoe** [comment]
@bensku where do you think I can work out code to remove it ?

**Comment by Dad3** [comment]
It is possible with my handy script you should save somewhere. I use it for almost every command.
`#To avoid skript hardcoded messages, use [<text>].
#This script tests if arg-1 is a player with allowing name shortcuts.
command /command [<text>]:
    trigger:
        if arg-1 is set:
            set {_arg1} to arg-1 parsed as offlineplayer
            if {_arg1} has played before:
                #Player in arg-1 is online or offline and his full username was typed.
                send "full username %{_arg1}%"
            else if arg-1 parsed as player is online:
                #Player in arg-1 is online without his full username typed.
                send "full username: %arg-1 parsed as player%"
            else:
                send "Player not found."
        else:
            send "Usage: /command <player>"`

**Comment by Dad3** [comment]
To achieve what you want, just remove the "else if" section of my code and you're good to go.

**Comment by Dad3** [comment]
Even better: `if arg-1 parsed as offlineplayer is online:` checks if player is online ONLY if full username was typed. There we go close issue

**Comment by Matocolotoe** [comment]
no @Dad3 it makes the same thing, I tried :)

**Comment by Dad3** [comment]
> no @Dad3 it makes the same thing, I tried :)
> Edit : there is an error in your script you parse the argument as an online player lmaooo

There are no errors in my script it seems like you don't know how to use it properly. I went way out of my way to give you all the methods to achieve what you need, and everything works flawlessly.

**Comment by Matocolotoe** [comment]
lol I tried to parse as offline player and it does the same thing

**Comment by Dad3** [comment]
how come it works for me then.

```python
command /text [<text>]:
    trigger:
        if arg-1 parsed as offlineplayer is online:
            send "yes"
```
works only if u type the full username of the player.

**Comment by Matocolotoe** [comment]
wait i'll try again and if it somehow works then thanks xd

**Comment by Matocolotoe** [comment]
It works, thanks a lot @Dad3
