### ISSUE TITLE
Unable to sort list variables

### ISSUE THREAD

**Issue by Hexivoid** [SkriptLang/Skript#1904]
Description: Attempting to sort any list variables results in a `List of type class java.lang.Object does not support sorting` error when loading. (I guess trying different sort methods for six hours yesterday wasn't very beneficial...)

Steps to reproduce: Please view this thread: https://forums.skunity.com/threads/unable-to-sort-list-variable.8775/

Here's another example not working as confirmed by @TheLimeGlass:
`on script load:
    set {_list::lime} to "1" parsed as number
    set {_list::lime2} to "2" parsed as number
    set {_list::lime3} to "3" parsed as number
    broadcast "%sorted {_list::*}%"` 

Expected behavior: List to be sorted numerically (or alphabetically)

Errors and screenshots: Check thread above. Same error for LimeGlass's code: 
![hmmlime](https://user-images.githubusercontent.com/20330597/52964757-2107ef80-3371-11e9-8dbc-c7665ff22610.PNG)

Server Information (tried with multiple versions)
Server core: Spigot 1.12.2 and Paper 525
Skript: 2.3.1 and 2.3.5 _(latest stable and latest dev builds at the time)_

**Comment by TPGamesNL** [comment]
Simply 
`set {_list2::*} to sorted {_list::*}` 
results in an error

**Comment by Hexivoid** [comment]
Thank you for narrowing it down. Other sort syntaxes also don't work, such as `message "%sorted {_list}%` too.

**Comment by MorkaZ** [comment]
Here is manual:
[https://github.com/MorkaZ/MorkazSk/wiki/Mox-Data-tutorial](https://github.com/MorkaZ/MorkazSk/wiki/Mox-Data-tutorial)

**Comment by Snow-Pyon** [comment]
@MorkaZ may I ask what does that have to do with the issue?

**Comment by Efnilite** [comment]
Because in this (https://github.com/MorkaZ/MorkazSk/issues/5) issue he was asking about morkazsk's sorting, probably

**Comment by Hexivoid** [comment]
Correct. I tried MorkasSk's sorting after Skript's wasn't working only to find out both weren't working at the time...

**Comment by MorkaZ** [comment]
Ohh, I posted link on wrong issue ;|. Sorry about that, just ignore it.

**Comment by Hexivoid** [comment]
Now we just have to wait for @Snow-Pyon to mark/tag this as a bug,

**Comment by TheBentoBox** [comment]
Putting as medium since this seems to basically break the sorting expression

**Comment by Hexivoid** [comment]
Guess that works too. Thank you @TheBentoBox :)

**Comment by Nicofisi** [comment]
I thought I found the fix but apparently not - #1433 - since it's been applied a long time ago and you still have issues, hmm... maybe we should delete the parse time check altogether?
