### ISSUE TITLE
set {test::*} to all items of player 

### ISSUE THREAD

**Issue by TeAm6AZLIK** [SkriptLang/Skript#1906]
### Description

`Slot 1: grass
Slot 2: dirt:
Slot 3: stone`

`!set {test::*} to all items of player`
`!broadcast "Broadcast: %{test::*}%"`

`Broadcast: grass`

Its only storing one item in the variable
### Expected Behavior

`Broadcast: grass, dirt, stone`

### Server Information
* **Server version/platform:**        git-Paper-493 (MC: 1.13.2)
* **Skript version:**                 2.3.5

**Comment by Hexivoid** [comment]
Why the exclamation marks?

**Comment by Pikachu920** [comment]
they are using effect commands
