### ISSUE TITLE
Boats cannot be pushed while a player is riding them.

### ISSUE THREAD

**Issue by xCustomWorld** [SkriptLang/Skript#1908]
### Description
The boat is not launched upwards (also tested with any other direction). Following code works only for minecarts, but not boats.

### Steps to Reproduce:
```skript
on right click:
    push player's vehicle upwards with speed 1
```

### Expected Behavior:
A boat the player is riding should be launched upwards with the speed 1. 

### Errors / Screenshots:
No errors shown.

### Server Information:
* **Server version/platform:** Spigot 1.13.2
* **Skript version:** 2.3.5

### Additional Context
I'm trying to create an ice boat-race karting minigame. The problem is launching a boat up when it meets a hill or higher terrain. I don't want to be able just to create a flat terrain "ice road". The problem is, that the code above works for minecarts (I haven't tested it with other vehicles than boats and minecarts). I heard that boats are complex and "exotic" entities when it comes into moving them. I don't know if this is a bug in Skript or in Minecraft and I'm confused, so I created this bug report.

Thank you for your attention and patience while solving my problem.

**Edit:**
This doesn't work only when player is riding the boat.

**Comment by bensku** [comment]
Sounds like a Minecraft limitation to me.

**Comment by TheBentoBox** [comment]
I also believe this is a Minecraft limitation. We're certainly not making any specific checks to not push boats.

**Comment by xCustomWorld** [comment]
Oh, okay, thanks. Guess I will need to use another vehicle then.
