### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Carvane** [SkriptLang/Skript#1910]
Console spam:
https://pastebin.com/EkpeT1YB

Server version: PaperSpigot #1598
Skript version: 2.3.5 (latest)

**Comment by ShaneBeee** [comment]
You will get better support if you fill out the [BUG REPORT](
https://github.com/SkriptLang/Skript/issues/new?template=bug-report.md) you clearly deleted

**Comment by bensku** [comment]
Duplicate of #1902.
