### ISSUE TITLE
player's prefix and player's suffix does not work

### ISSUE THREAD

**Issue by sOxTw** [SkriptLang/Skript#1912]
### Description

Well the problem is in:
`%player's prefix%` and `%player's suffix%` mark me that they do not recognize each other.
### Steps to Reproduce

`set {_tag} to "%player's prefix%&c%player%"`
### Expected Behavior

By using this line, a return of the following is expected:
`**{GROUP}{NAME OF PLAYER}**`
Using PermissionEX I hope you return your Prefix and the Player's Name.
### Errors / Screenshots

![](https://image.prntscr.com/image/aBpsnpzwQHuG9IUR02W13w.png)

### Server Information
* **Server version/platform:**  1.8.8     
* **Skript version:**    2.2-dev37c            

### Additional Context

In previous versions of Skript 2.2 I never set an error. As in the version: 2.2-dev25, thank you for reading!

**Comment by ShaneBeee** [comment]
2.2Dev37c is no longer support, nor is Spigot 1.8.8

**Comment by TheBentoBox** [comment]
Please report again in a supported Skript and server version otherwise I will close this

**Comment by sOxTw** [comment]
And what version of skript can I use for Spigot 1.8.8?

**Comment by ShaneBeee** [comment]
Dev37c is the latest version that will work for Spigot 1.8.8 but Dev36 is the recommend version as there have been know memory leaks in dev37c

**Comment by bensku** [comment]
We can't help you here with 1.8.
