### ISSUE TITLE
Argument tab completions not working

### ISSUE THREAD

**Issue by mckite** [SkriptLang/Skript#1915]
### Description

Tab auto completion just works complete command and 
is not working for arguments. 

command /broadcast[< text>]:
	aliases: loudspeak

### Steps to Reproduce

type the any command which made by Skript and put some letters on the argument and
press the tab to auto complete player names.

### Expected Behavior

It supposed to be auto-completed name to that argument,  

It should be work like this (This screenshot is on Skript 2.2)
https://cdn.discordapp.com/attachments/540325717401927681/548679406315503623/ex_temp.jpg

### Errors / Screenshots

Tab-auto-completing is not working Since Skript 2.3 (It's working correctly on Skript 2.2)

Just work when
Script like this : 
"command /info <player > "

But, Some times tab auto - completion need to like 

"command /broadcast [< text>] "

For example, such as Broadcast command, 
they may need auto-completion of player's name and combine with other texts like "/broadcast KitePro is testing the Skirpt"

https://cdn.discordapp.com/attachments/540325717401927681/548678595363471360/tab.jpg
[](https://cdn.discordapp.com/attachments/540325717401927681/548678595363471360/tab.jpg
)

It should be work like this (This screenshot is on Skript 2.2)
https://cdn.discordapp.com/attachments/540325717401927681/548679406315503623/ex_temp.jpg

### Server Information
* **Server version/platform:**      This server is running CraftBukkit version git-Spigot-2cf50f0-8166d17 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

* **Skript version:**                2.3.5

### Additional Context

IF that is not a bug and new function, it need to support multi type of argument for need tab-autocomplete in < text >.

command /broadcast [< text>]:
	permission: skript.essentials.me
	usage: /broadcast <text >
	trigger:
		if arg 1 is not set:
			message "&6/broadcast<text > "
		else if player's money is greater than 2500:
			broadcast "%player%: %args%"
		else:
			message "&cnot enough moeny."

# It need to tab auto completion for user's Convenience

**Comment by mckite** [comment]
[https://github.com/SkriptLang/Skript/issues/1915](url)

**Comment by bensku** [comment]
Your command argument is text, and Skript has no idea how to auto-complete it. If you want pressing tab to give a list of players, use player or offlineplayer as type of the argument.

Skript used not to handle tab completions at all, leaving it for Bukkit to do. I think that was changed when fixing 1.13 bugs. See #1600 for details.

**Comment by mckite** [comment]
So, if I need both <player> to auto-complete and <text> to broadcast,
HOW CAN I DO?

Back to Skript 2.2?

**Comment by mckite** [comment]
I find how to it.

I can use like below. (Please don't change this auto-completion fuction in future, keep this thing can be as <text >

command warn [<offlineplayer>]  [<offlineplayer>]:
      if "%arg 1%" parsed as player is set:

**Comment by mckite** [comment]
> Your command argument is text, and Skript has no idea how to auto-complete it. If you want pressing tab to give a list of players, use player or offlineplayer as type of the argument.
> 
> Skript used not to handle tab completions at all, leaving it for Bukkit to do. I think that was changed when fixing 1.13 bugs. See #1600 for details.

But, Other Commands not made by Skript argument auto-completion is working.

**Comment by mckite** [comment]
> Your command argument is text, and Skript has no idea how to auto-complete it. If you want pressing tab to give a list of players, use player or offlineplayer as type of the argument.
> 
> Skript used not to handle tab completions at all, leaving it for Bukkit to do. I think that was changed when fixing 1.13 bugs. See #1600 for details.

But That Problem just on Skript.
Tab-Auto-Complete just don't work made by Skript.

Other all of  plugin's command supports Tab-Auto_complete
