### ISSUE TITLE
on click / rightclick not canceling + Player ported below world

### ISSUE THREAD

**Issue by GermanMinerDE** [SkriptLang/Skript#1916]
### Description
When holding something in the off hand and not holding an item in the main hand, the canceling of the "on click" or "on rightclick"-event does not have any effect -> The block is being placed.

You could say, please use "on place", but there is a second issue then.
I need to have the itemStack of the item that is being placed to check, if it is the item, that should not be placeable. I only get the event-block.

### Steps to Reproduce
Tested with holding a player skull in off hand, main hand air.
It is placeable.

Skript:
`on rightclick:
    cancel event
    
on click:
    DebugMax("click")
    cancel event`

### Expected Behavior
It should not be placeable.

### Server Information
* **Server version/platform:**      Paper 1.12.2 1598 + 1596
* **Skript version:**               2.3.5

**Comment by Soufreur78** [comment]
I confirm to meet the same problem. The right click event does not work at all when you have an item in the second hand and none in the first hand.

* **Server version/platform:**      Spigot 1.9.4
* **Skript version:**               2.3.5

**Comment by GermanMinerDE** [comment]
For me it is only with some blocks / items.
For example with skull in off hand it does not cancel (but my test message is being sent, so the event itself works!!!)

**Some Examples**
Canceled with X in off hand:

- quartz block
- dirt
- oak log
- saplings

NOT canceled with X in off hand:
- sign
- player head / skull
- doors

(There can be more than this)

**Comment by Hexivoid** [comment]
Did I read that right? You're being teleported when placing a block?

**Comment by GermanMinerDE** [comment]
I'll be testing on a clean server now - can't believe that for myself haha

**Comment by bensku** [comment]
Cannot reproduce teleportation on 1.12. It is probably not caused by Skript. Cancellation issues do exist, but only on MC 1.12 and older.
