### ISSUE TITLE
Drop a list doesn't work

### ISSUE THREAD

**Issue by uiytt** [SkriptLang/Skript#1917]
### Description
Drop a list of item return an error when reload 

### Steps to Reproduce
Just put this code and reload:
```
on right click on stone:
	set {_l::*} to stone, dirt, glass and diamond
	drop {_l::*} to player's location
```
### Expected Behavior
Well... I expect the items to drop.
### Errors / Screenshots
Error :` Can't understand this condition/ effect : drop {_l::*} to player's location`

### Server Information
* **Server version/platform:**       Spigot 1.12.2
* **Skript version:**               2.3.5

**Comment by TheBentoBox** [comment]
Using `to` there is incorrect grammar; it should be `at player's location`, not `to player's location`.

Please verify that changing to `at` fixes your issue.

**Comment by uiytt** [comment]
Yes it's at idk why i wrote "to"....
But it still doesn't work (same error)

**Comment by uiytt** [comment]
So any idea ?

**Comment by Nicofisi** [comment]
Looks like it should work, hmm, maybe try one of these?
```
drop {_l::*} (at player's location)
drop ({_l::*}) (at player's location)
drop {_l::*} (at) (player's location)
drop {_l::*} ((at) (player's location))
drop ({_l::*}) ((at) (player's location))
```

**Comment by uiytt** [comment]
None of them work
I always have "Can't understand this condition/ effect : drop {_l::*}" (without  to player's location) or "Can't understand this condition/ effect : drop".

This works fine : 
```
on right click on stone:
	set {_l} to stone
	drop {_l} at player's location
```

**Comment by uiytt** [comment]
So still no idea ?

**Comment by bensku** [comment]
This bug is an interesting one. Haven't seen syntaxes fail to accept variables but accept other lists just fine before.

If you're just trying to avoid copy-pasting lists of items, you can still put the lists in options and refer to them. It should work, because options are replaced in scripts before any other parsing is done.

**Comment by uiytt** [comment]
I used it for storing player's drop and drop it later so i can't use your method , i will wait for a patch
