### ISSUE TITLE
Official or semi-official IRC? 

### ISSUE THREAD

**Issue by abcarroll** [SkriptLang/Skript#1919]
### Description

Is there an official, or even un-official IRC channel?

Years ago I believe there used to be one on the spigot IRC server, but I don't see it any longer.  It looks like it's moved to Discord?  I don't understand this change, but just wondering if there exists a place without needing to sign up for Discord.

**Comment by Nicofisi** [comment]
You're right, every active English community uses forums or Discord. What's wrong with it? Signing up to Discord is the matter of entering your nick, email, password, and clicking Google's reCAPTCHA. Actually I'm pretty sure it supports anonymous accounts too, where you only enter a nick to register, also you don't need to download anything, it works well in the browser

**Comment by bensku** [comment]
I don't think Skript ever had an IRC channel. Still, @Nicofisi is missing quite an important point: Discord's has terms of service you need to agree on, even if you use it anonymously. This might be why OP doesn't want to use Discord.

**Comment by Pikachu920** [comment]
it doesn't fix the root of the issue, but have you tried a discord -> irc bridge. part of the issue is there never has been an "official" Skript chat - the one on spigot was just made by them and the discord servers are made by lots of different people.
