### ISSUE TITLE
Skript Parser error

### ISSUE THREAD

**Issue by KaylorSwift** [SkriptLang/Skript#1923]
When I was using the Skript Parser over 1000 lines, it didn't show any parse result.
Can anyone help to fix it? Thanks so much~

**Comment by Nicofisi** [comment]
You don't perhaps mean the skUnity parser at https://parser.skunity.com, do you?

**Comment by KaylorSwift** [comment]
Yes.

**Comment by SiebeDW** [comment]
Skunity parser is not related to this repo.

**Comment by Nicofisi** [comment]
> Skunity parser is not related to this repo.

^

Please use report any issues with the skUnity Parser at https://discord.gg/2cPjgTB because we can't do anything about it here, it's not a part of Skript.
