### ISSUE TITLE
Weird parsing bug

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#1924]
### Description
When parsing an empty string as a player, it will return the only online player (if there is only one player online: if there are more or less than 1 it'll return none)

### Steps to Reproduce
```
command /test:
	trigger:
		set {_p} to "" parsed as a player
		message "p: %{_p}%"
```

### Expected Behavior
Parsing an empty string as a player should return none in all cases.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/29547183/53683342-097d1f00-3d00-11e9-85bc-04cce3dbba5f.png)
![image](https://user-images.githubusercontent.com/29547183/53683344-139f1d80-3d00-11e9-98f4-3e49c70c5c5e.png)

### Server Information
* **Server version/platform:** Spigot 1.13.2
* **Skript version:** 2.3.5

**Comment by AlexLew95** [comment]
You parse nothing as player, of course it will return you "null"

**Comment by TPGamesNL** [comment]
This is caused by https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/classes/data/BukkitClasses.java#L785-L792
because it uses `Bukkit.matchPlayer`, which returns the list of players with a name matching it (the player's name must contain the given input). 
This is also why running a command with a player argument, using a player's name that isn't on the server, you may still get valid player (if a player whose name contains the input is online).
