### ISSUE TITLE
List function arguments doesn't keep indices

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#1926]
### Description
When you have a list argument in a function, the indices of that list aren't passed on to the function.
I've also seen #811, but that is about the return values of functions, not that arguments. I also wanted to make this report because of the alternate suggestion (see Additional Context)

### Steps to Reproduce
```
function listTest(list: objects):
	loop {_list::*}:
		broadcast "%loop-index%: %loop-value%"
		
command /listtest:
	trigger:
		set {_list::a} to "value a"
		set {_list::b} to "value b"
		set {_list::c} to "value c"
		listTest({_list::*})
```
![image](https://user-images.githubusercontent.com/29547183/53683875-7bf0fd80-3d06-11e9-9b9a-bd8781d9d915.png)

### Expected Behavior
The list should keep its indices

### Server Information
* **Server version/platform:** Spigot 1.13.2
* **Skript version:** 2.3.5

### Additional Context
This could also be resolved by adding a 'indices of' expression, which returns all of the indices of that list. (this expression could be added as another function argument in some functions, since not every function requires the indices of a list)

**Comment by TheBentoBox** [comment]
This duplicates #811, but that's very old and was written before we had the templates in place so this one looks nicer, so I'll make this the primary one for tracking this bug.

**Comment by TheBentoBox** [comment]
I'm labelling with the same priority as #811 since I imagine they'd have about the same level of importance.

**Comment by Pikachu920** [comment]
an indices of expression already exists

**Comment by TPGamesNL** [comment]
@Pikachu920 I'm not seeing it on the docs, only slot index but that is a different thing. Is it missing from the docs perhaps?

**Comment by Pikachu920** [comment]
hmm... looks like it may have been lost in 1.13 merge. need to fix

**Comment by Wealthyturtle** [comment]
Closing in favor of #3127
