### ISSUE TITLE
Click event doesn't work with off-hand for villagers

### ISSUE THREAD

**Issue by ruddeTR** [SkriptLang/Skript#1927]
Skript doesn't detect my right click when I have an item in my off hand (but it works with baby villagers).

https://imgur.com/a/2CQpHyX

Skript version: 2.3.5
Server version: paper-551 (1.13.2)

Code:
```
on click on villager:
	{x} isn't "test"
	send "trigger" to player
	cancel event
```

**Comment by Bartuzen** [comment]
It's fixed in 2.3.6.

**Comment by ruddeTR** [comment]
No, it still exists.

**Comment by FranKusmiruk** [comment]
The issue is weird, it won't trigger when you have an usable item in your off-hand and a non-usable one in your main hand, it does trigger when both are usable items though.
