### ISSUE TITLE
Delayed effects in functions

### ISSUE THREAD

**Issue by HAHAYOUDEAD** [SkriptLang/Skript#1930]
### Description
When using delayed effects in function, it doesn't return the correct value.

#### Initially tried with delayed effect from Tablisknu, so here is an example using this plugin:
```skript
function testhead(name: text) :: item:
    set {_p} to Bukkit.getOfflinePlayer({_name})
    retrieve skin of {_p} with timeout 2 seconds into {_skin}
    if {_skin} is not set:
        broadcast "error"
    else:
        set {_head} to skull from {_skin} with owner "%{_p}%"
        return {_head}

command /test5 [<text>]:
    trigger:
        give testhead(arg) to player
```
#### Results:
1. /test5 Waltz - nothing happens
2. /test5 Waltz - I get a head of Waltz
3. /test5 Steve - I get a head of Waltz
4. /test5 Steve - I get a head of Steve

#### Vanilla interpretation (thanks to Tlatoani):
```skript
function dfun(res: int) :: int:
  set {_pie} to false
  while 1 + 1 is 2:
    if {_pie} is true:
      return {_res}
    wait 1 tick
    set {_pie} to true

command /test6 [<int>]:
    trigger:
        broadcast "%dfun(arg)%"
```
#### Results:
1. /test6 1 - `<none>`
2. /test6 2 - `1`
3. /test6 3 - `2`
4. /test6 4 - `3`

### Expected Behavior
I expect it to either not work at all, which would be sad, or return correct values

### Server Information
* **Server version/platform: Paper 540**      
* **Skript version: 2.3.6**             

### Also
I don't quite understand what delayed means and how it affects functions, i.e. https://skriptlang.github.io/Skript/expressions.html#ExprSkull this is also delayed, because it retrieves data from mojang, right? But it works fine with functions (not really, sometimes it hangs the server, but there is not problems with returning values)

**Comment by Pikachu920** [comment]
unfortunately expressions can't be delayed due to how Skript is currently written
