### ISSUE TITLE
"is not online" comparison issues

### ISSUE THREAD

**Issue by APickledWalrus** [SkriptLang/Skript#1939]
### Description
If you use `is not online:` the condition will pass, even if the player is online.
If you use `is offline` the condition will not pass if the player is online.
I am not sure if it will work properly if the player is offline as well.
I recently updated from dev36, 1.12.2).

### Steps to Reproduce
```
command /onlinetest:
	trigger:
		set {_online} to player
		set {_offline} to {_online} parsed as an offlineplayer
		if {_offline} is offline:
			send "OFFLINE A"
		if {_offline} is not online:
			send "OFFLINE B"
		if {_online} is offline:
			send "ONLINE A"
		if {_online} is not online:
			send "ONLINE B"
```

### Expected Behavior
Both conditions should NOT be triggered.

### Errors / Screenshots
http://prntscr.com/mvancg

### Server Information
* **Server version/platform:**       1.13.2 Paper git-Paper-562 (1 behind latest)
* **Skript version:**                2.3.6

**Comment by Pikachu920** [comment]
The first condition functions as expected as you can't parse a player and so the expression's value is null which is not online

**Comment by APickledWalrus** [comment]
> The first condition functions as expected as you can't parse a player and so the expression's value is null which is not online

Yeah, it is actually null. My bad.
I used this in a function, in which both values are set (apparently)
Maybe I'm still missing something here? Returns same as before.
```
function onlinetest(online: player, offline: offlineplayer):
	if {_offline} is offline:
		broadcast "OFFLINE A"
	if {_offline} is not online:
		broadcast "OFFLINE B"
	if {_online} is offline:
		broadcast "ONLINE A"
	if {_online} is not online:
		broadcast "ONLINE B"
	broadcast "%{_online}% %{_offline}%"

command /onlinetest:
	trigger:
		onlinetest(player, player)
```

**Comment by APickledWalrus** [comment]
Any update on this?

**Comment by bensku** [comment]
Can't reproduce this. The latter test case only prints player name twice.

**Comment by APickledWalrus** [comment]
I will test this again when I get the chance, and see if the issue persists.

**Comment by TheBentoBox** [comment]
@APickledWalrus are you able to reproduce this anymore on the latest release?

**Comment by APickledWalrus** [comment]
Totally forgot about this. I will test it again in the next few hours.
