### ISSUE TITLE
Convert string variables to worlds

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#1940]
Spigot 1.13.2 latest
Skript 2.3.6

Is this meant to evaluate, or have I borked the syntax?

Test script:
```
command /test-load:
        permission: blackdog.op
        trigger:
                if "world" is loaded:
                        send "world is loaded" to console
                else:
                        send "world is not loaded" to console

                set {_TARGET_WORLD} to "world"
                if {_TARGET_WORLD} is loaded:
                        send "world is loaded" to console
                else:
                        send "world is not loaded" to console
```
Result:
```
>sk reload test
[23:22:00 INFO]: [Skript] Reloading test.sk...
[23:22:00 INFO]: [Skript] Successfully reloaded test.sk.
>test-load
[23:22:02 INFO]: world is loaded
[23:22:02 INFO]: world is not loaded
```

**Comment by ShaneBeee** [comment]
I tried it and you are right.
I changed this line
```
set {_TARGET_WORLD} to "world"
```
to 
```
set {_TARGET_WORLD} to world "world"
```
and it works fine.

My guess is because you are saving your variable as the text "world", not the actually WORLD "world", and then checking if the text "world" is loaded. So Skript is probably confused.

**Comment by SiebeDW** [comment]
Maybe as suggestion when you use is loaded it automatic parses the string variable to world?

**Comment by SlimeDog** [comment]
Thanks. Much obliged. As you might guess, the code segment above is part of a larger script. _TARGET_WORLD appears to be correctly cast/evaluated (tested by debug statements) in the following cases
```
       if event-world is {_TARGET_WORLD}:
        set {_TARGET_WEATHER} to weather in {_TARGET_WORLD}
```

**Comment by FranKusmiruk** [comment]
We could possibly add a String <-> World converter, the problem with those is that they often mess up error handling though, would need more input on it.

**Comment by Matocolotoe** [comment]
We can already use the default function world(String) @FranKusmiruk
