### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1942]
### Description
I would like to suggest an option to run functions via the json chat system.
I do understand you can basically do this exact thing with commands, but the issue I am having is once the player clicks the option and the command runs, they can keep clicking it, spamming the console with:
```
[20:00:39 INFO]: ShaneBee issued server command: /test confirm
[20:00:40 INFO]: ShaneBee issued server command: /test confirm
```

Ex:
```vb
function test(p: player):
    send "CONFIRM" to {_p}

some event:
    send "Click to confirm <func:test(player)>CONFIRM<reset>"

**Comment by FranKusmiruk** [comment]
This is something that is sadly something not very feasible to add, it's a thing way too insecure for Skript to add it, an addon is free to try it though.

**Comment by ShaneBeee** [comment]
Fair enough. Pikachu already told me on Discord it wouldn't be pretty/clean enough to add it. 
Thanks for the response, I appreciate it!
