### ISSUE TITLE
Please help me fix this

### ISSUE THREAD

**Issue by GTSkill** [SkriptLang/Skript#1947]
### Question
command /shopfinalsellgrind <string> <string>:
	trigger:
		wait 1 tick
		#set {name} to yml value "%arg 1%.name" of file "plugins/Skript/finalbuygrind.yml"
		#set {price} to yml value "%arg 1%.price" of file "plugins/Skript/finalbuygrind.yml"
		set {name} to skutil yaml string "%arg 1%.name" from file "{@file}"
		if Player's inventory contains 1 of {name}:
			remove 1 of {name} from player
			give player cobblestone named "OooF"
			send "Ooofed"

I dont get what the issue is here

YML file

'344':
  name: leather
  price: 8
'115':
  name: nether_wart
  price: 6
'81':
  name: cactus
  price: 3
83::
  name: reeds
  price: 5
'296':
  name: wheat
  price: 7
'391':
  name: carrot
  price: 7
'392':
  name: potato
  price: 7
'434':
  name: beetroot
  price: 7
'435':
  name: beetroot_seeds
  price: 3
'295':
  name: wheat_seeds
  price: 3
'362':
  name: melon_seeds
  price: 3
'361':
  name: pumpkin_seeds
  price: 3
'265':
  name: iron_ingot
  price: 11
'352':
  name: bone
  price: 6
'262':
  name: arrow
  price: 8
'369':
  name: blaze_rod
  price: 5
'289':
  name: gunpowder
  price: 6
'367':
  name: rotten_flesh
  price: 5
'287':
  name: string
  price: 6
'375':
  name: spider_eye
  price: 9
'368':
  name: ender_pearl
  price: 8

**Comment by bensku** [comment]
We can't help you with addons here.
