### ISSUE TITLE
Skript issue (v2.3.5)

### ISSUE THREAD

**Issue by N1kotus** [SkriptLang/Skript#1948]
This happened when i'm trying to start my server.
Console:
https://pastebin.com/gnnkEhVr

Server Information
* **Server version/platform:**       Spigot 1.13.2
* **Skript version:**                2.3.5

**Comment by bensku** [comment]
Try without addons. It might help.

**Comment by Blueyescat** [comment]
What causes the errors are the scripts that uses the addons 😜

**Comment by TheBentoBox** [comment]
No response.
