### ISSUE TITLE
[Suggestion] Stop Sound

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1949]
### Description
I would like to suggest adding a stop sound effect. Either as a new effect or a new pattern to the already available play sound effect.
Spigot added a stopSound method to the player class in 1.10 (I don't see it in 1.9.4 but I do see it in 1.10.2)

**Comment by FranKusmiruk** [comment]
This was added by Blueyescat on his PR to improve the sound stuff (#1928), so, when that PR gets merged, this should be there as well.

**Comment by ShaneBeee** [comment]
Oh, how the heck did i miss that!?!
Thanks

**Comment by Misio12320** [comment]
+1. Yes add this...

**Comment by Matocolotoe** [comment]
@ShaneBeee it has been added
