### ISSUE TITLE
On Block Place Issue

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1950]
Unable to get the lore of a block when placing a player head item with lore.

Version (Skript): 2.3.6

My script:
```
on block place:
	if event-block is player head item:
		broadcast "%lore of event-block%"

```

Result:` <none> `
But the lore is set.

**Comment by FranKusmiruk** [comment]
Blocks don't have lore.

**Comment by bloggy** [comment]
Wait. This event is triggered before the block is placed and if am not wrong it can have a lore as long as it is not a placed block.

**Comment by TheBentoBox** [comment]
You'd need to check the lore of the item, not the placed block; `event-block` will return the actual block instance which would be placed and a block doesn't have lore even if the item did.

**Comment by Blueyescat** [comment]
player's tool
player's off tool
