### ISSUE TITLE
Another issue with v2.3.5....

### ISSUE THREAD

**Issue by N1kotus** [SkriptLang/Skript#1951]
* **This happens, when server starts:**
> [14:06:39 INFO]: [Skript] Loading variables...
> [14:06:58 ERROR]: [Skript] 1817 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:264)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
> [14:07:00 ERROR]: [Skript] 2 log handlers were not stopped properly! (at me.iblitzkriegi.vixio.util.scope.EffectSection.stopLog(EffectSection.java:87)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
> [14:08:59 ERROR]: [Skript] 3649 log handlers were not stopped properly! (at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:353)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

### Server Information
* **Server version/platform:**       Spigot newest 1.13.2
* **Skript version:**                2.3.5

**Comment by ShaneBeee** [comment]
That is caused by Skript Mirror 1.0.0
Try the snapshot builds of Skript Mirror [**2.0.0**](https://circleci.com/gh/btk5h/skript-mirror)
