### ISSUE TITLE
Placing a bed breaks the with cancel event takes away 2 beds

### ISSUE THREAD

**Issue by hihihoholalalolo1227** [SkriptLang/Skript#1956]
so, basically, I made this script for skript where you can get one more home.
Version: 1.11.2 (with ViaVersion, ViaRewind, ViaBackward)
The script:
```
on right click holding a bed:
    broadcast "&aon bed worked"
    if player's tool is bed named "&a&l+1 Home" with lore "&7(Click to redeem this item)":
        broadcast "&aif statement worked"
        execute console command "/addhome %player% 1"
        remove 1 of player's tool from player

on place of bed:
    if player's tool is bed named "&a&l+1 Home" with lore "&7(Click to redeem this item)":
        cancel event
        if event is canceled:
            broadcast "&acancelled"
```
Look below for what it does:
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/19301522/54407766-7c4da900-46b5-11e9-821f-88d568bcb693.gif)
The problem is:
When I am placing it (right-clicking it on a block), it takes away 2 of the player. 
I'm not sure the problem, but I get NO ERRORS when loading this skript.
**EDIT**:I know Why is this happening, It is because of Beds are 2 blocks.
But can you please fix this.
**EDIT 2**: It doesn't remove the extra bed when in survival, when you place it.

**Comment by bensku** [comment]
What Skript version are you using? Do you have addons? Given script doesn't load without errors for me.

**Comment by hihihoholalalolo1227** [comment]
ok, I resolved this. Please close this thread
