### ISSUE TITLE
Skript GUI not working on 1.8.8

### ISSUE THREAD

**Issue by DiamondDaniel** [SkriptLang/Skript#1958]
`16.03 15:57:56 [Server] ERROR #!#! 
16.03 15:57:56 [Server] ERROR #!#! [Skript] Severe Error:
16.03 15:57:56 [Server] ERROR #!#! 
16.03 15:57:56 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
16.03 15:57:56 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
16.03 15:57:56 [Server] ERROR #!#! and check whether this error has already been reported.
16.03 15:57:56 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
16.03 15:57:56 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
16.03 15:57:56 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
16.03 15:57:56 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
16.03 15:57:56 [Server] ERROR #!#! 
16.03 15:57:56 [Server] ERROR #!#! Stack trace:
16.03 15:57:56 [Server] ERROR #!#! java.lang.IllegalArgumentException: Title cannot be longer than 32 characters
16.03 15:57:56 [Server] ERROR #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
16.03 15:57:56 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom$MinecraftInventory.<init>(CraftInventoryCustom.java:59)
16.03 15:57:56 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom.<init>(CraftInventoryCustom.java:32)
16.03 15:57:56 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createInventory(CraftServer.java:1525)
16.03 15:57:56 [Server] ERROR #!#!     at org.bukkit.Bukkit.createInventory(Bukkit.java:938)
16.03 15:57:56 [Server] ERROR #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:36)
16.03 15:57:56 [Server] ERROR #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:14)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:63)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:98)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
16.03 15:57:56 [Server] ERROR #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
16.03 15:57:56 [Server] ERROR #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16.03 15:57:56 [Server] ERROR #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16.03 15:57:56 [Server] ERROR #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16.03 15:57:56 [Server] ERROR #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
16.03 15:57:56 [Server] ERROR #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
16.03 15:57:56 [Server] ERROR #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
16.03 15:57:56 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
16.03 15:57:56 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
16.03 15:57:56 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16.03 15:57:56 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
16.03 15:57:56 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
16.03 15:57:56 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
16.03 15:57:56 [Server] ERROR #!#! 
16.03 15:57:56 [Server] ERROR #!#! Version Information:
16.03 15:57:56 [Server] ERROR #!#!   Skript: 2.2-dev22f
16.03 15:57:56 [Server] ERROR #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
16.03 15:57:56 [Server] ERROR #!#!   Minecraft: 1.8.8
16.03 15:57:56 [Server] ERROR #!#!   Java: 1.8.0_191 (OpenJDK 64-Bit Server VM 25.191-b12)
16.03 15:57:56 [Server] ERROR #!#!   OS: Linux amd64 4.19.6-1.el7.elrepo.x86_64
16.03 15:57:56 [Server] ERROR #!#! 
16.03 15:57:56 [Server] ERROR #!#! Running CraftBukkit: false
16.03 15:57:56 [Server] ERROR #!#! 
16.03 15:57:56 [Server] ERROR #!#! Current node: null
16.03 15:57:56 [Server] ERROR #!#! Current item: open inventory to the player
16.03 15:57:56 [Server] ERROR #!#! 
16.03 15:57:56 [Server] ERROR #!#! Thread: Server thread
16.03 15:57:56 [Server] ERROR #!#! 
16.03 15:57:56 [Server] ERROR #!#! End of Error.
16.03 15:57:56 [Server] ERROR #!#! `

Is what i get when i try to open a GUI

**Comment by FranKusmiruk** [comment]
Skript doesn't support 1.8.8.
