### ISSUE TITLE
Lore

### ISSUE THREAD

**Issue by DDuart** [SkriptLang/Skript#1961]
Hello, can you add lore like in the old SkQuery?
```java
if (lore.length == 1) {
    meta.setLore(Arrays.asList(lore[0].split("\\|\\|")));
} else {
    meta.setLore(Arrays.asList(lore));
}
```
it would be easier to update from version dev37c

**Comment by Blueyescat** [comment]
no

**Comment by TheBentoBox** [comment]
There aren't plans to add support for old lore and it's pretty easy to do updates to old syntaxes in many scenarios by replacing `||` with `", "`.
