### ISSUE TITLE
Skull block

### ISSUE THREAD

**Issue by DDuart** [SkriptLang/Skript#1965]
```vbs
on rightclick:
  if clicked block is skull:
    broadcast "ok"
```

Can't compare a block with 'skull'
newest skript / newest paper 1.12.2

**Comment by ShaneBeee** [comment]
You need to fill out the issue template, you have next to zero helpful info here!
`skull` isnt a block
see the aliases https://github.com/SkriptLang/skript-aliases/blob/master/decoration.sk

**Comment by DDuart** [comment]
just test yourself, it's hard to explain.

**Comment by ShaneBeee** [comment]
> just test yourself, it's hard to explain.
yes, as i said


> `skull` isnt a block
> see the aliases https://github.com/SkriptLang/skript-aliases/blob/master/decoration.sk

**Comment by DDuart** [comment]
after place skull on floor and type `!send "%targeted block%"` it returns `SKULL`.

**Comment by ShaneBeee** [comment]
use this for now, its a workaround that was used in a previous issue the exact same as this
`if "%clicked block%" = "SKULL":`

**Comment by DDuart** [comment]
i need to set targeted block to floor skull, how can i do this?

**Comment by TheBentoBox** [comment]
We need to know your server and Skript version as that drastically affects where the issue could be coming from. Don't assume the information you've provided is enough.

**Comment by DDuart** [comment]
newest skript / newest paper 1.12.2

**Comment by FranKusmiruk** [comment]
I am directly closing this since you totally skipped the issue template. Not going to ask further questions on the matter.

Either edit this issue with the proper template or create a new one.
