### ISSUE TITLE
apply potion effect to player problem

### ISSUE THREAD

**Issue by titustitus98** [SkriptLang/Skript#1969]
### Description
Ok so I made a skript to add a potion effect linked to the player's tool but when I have the tool equipped the potion effect shows up but does not change my speed only the particles appeare

### Steps to Reproduce
add this piece of code then reload it and try it.
`command testspeed [<number>]:
	permission: test.speed%
	trigger:
		set {_num} to 1
		loop lore of player's tool:
			if loop-value contains "Speed":
				set line {_num} of lore of player's tool to "&7Speed %arg-1%"
				stop
			add 1 to {_num}
		add "&7Speed %arg-1%" to lore of player's tool
		send "set speed %arg-1% to tool"
		set {speed::%player's tool%} to arg-1
		
		
		
		
		
		
on any movement:
	if {speed::%player's tool%} is set:
		if player does not have swiftness:
			apply potion of swiftness of tier {speed::%player's tool%} to player for 10 seconds`
### Expected Behavior
Should apply me the speed to which the var is set in the first part of the code

### Errors / Screenshots
No errors are sent in mc and in console
--->

### Server Information
Server Version: paper-1.12.2 Skript 2.3.6

### Additional Context
None

**Comment by Syst3ms** [comment]
Please use proper Markdown formatting in your issues.

**Comment by titustitus98** [comment]
> Please use proper Markdown formatting in your issues.

Hi I do not understand what you mean by that as I have done what it told me to do when creating a new issue.

**Comment by TPGamesNL** [comment]
Use this: https://guides.github.com/features/mastering-markdown/ (click 'Code' button below examples)

**Comment by titustitus98** [comment]
sorry I fixed my issue
