### ISSUE TITLE
Event-specific priority feature

### ISSUE THREAD

**Issue by UltraFaceguy** [SkriptLang/Skript#197]
Long story short, this is a simple one. If you use skript's entity spawn, and another plugin cancels the event, the skript stuff still goes through. I don't know if it fails to see if the event is cancelled, or if it executes skripts on a low EntitySpawnEvent event priority, but the issue is there.

This can be tested pretty easily. Make zombie spawns broadcast "Dank Memes" if they spawn in worldguard region "meme-zone". Now set meme-zone to deny zombie spawns, and none will spawn, but it will still spam "Dank Memes". And really, nobody wants that.

**Comment by Pilvinen** [comment]
Have you tried adjusting the "plugin priority" from config.sk?

**Comment by UltraFaceguy** [comment]
I have, unfortunately, and the current priority is perfect for other plugins I have. Altering it will break 3 other cases that are worse.

Perhaps the solution is to have a few more priority options, per event?

**Comment by Pilvinen** [comment]
No. The solution is to check for WG region "meme-zone" at the location of the last spawned entity in the spawn event and to stop the execution of the code based on this information.

Doing it like I explained above makes it irrelevant whether and when the event gets cancelled at one point or another.

Also you can do it in couple of minutes and don't have to wait for 6-12 months to see if someone has time to consider possible ways to implement the really difficult per event priority options which, imo, sounds like an impossible task.

**Comment by Pilvinen** [comment]
If that is not your actual use case that you gave in the example then off the top  of my head you can also wait for a short period and check with Skript whether or not the entity actually spawned.

Also there's nothing preventing you from doing the actual spawn denial yourself with Skript instead of leaving it to your plugin.

And if your situation is harder than this then it doesn't even really matter if you cancel the event twice. Once from the plugin and then once from Skript with your own custom spawn handling. 

These are just the most obvious options that  came to mind. There are numerous different approaches you can take based on your situation even when you can't adjust the plugin priority option from config.sk.

**Comment by UltraFaceguy** [comment]
Yeah, I'll get right to cancelling it that way in every one of the dozens of regions that require this. Because checking for 20+ regions on every entity spawn is totally a practical and efficient way to detect that! The spawn denials are happening as a conflict with worldguard itself, because changing the event priority from where it is breaks things one way or another.

I made that suggested solution because it can fix a problem, and be a possible enhancement for others.

Right here https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/SkriptEventHandler.java we see where the events are loaded. It doesn't seem too implausible to be able to check a few new config values against many of the event types as they're loaded.

`final static void registerBukkitEvents() {
		for (final Class<? extends Event> e : triggers.keySet()) {
			assert e != null;
			if (!containsSuperclass((Set) registeredEvents, e)) { // I just love Java's generics
				Bukkit.getPluginManager().registerEvent(e, listener, SkriptConfig.defaultEventPriority.value(), ee, Skript.getInstance());
				registeredEvents.add(e);
			}
		}
	}`

**Comment by Pilvinen** [comment]
Unless you are running your server on a 486 then yes, it is totally practical and will not put ANY strain on your MC server nor will it create ANY kind of lag. You are totally over reacting.

Also entity spawns are not even time critical so if it does take 0,01 ms longer to spawn an entity than usual you really don't have to worry about it.

My advice to you is that you just fix it now the way I suggested. It should only take a couple of minutes and it will work.

You're not reporting a bug, you're suggesting a new feature and I'm telling you that Bensku is super busy with our game project (Rituals of the old) and he has a big backlog with Skript, so unless you're willing to code this yourself and make a pull request I wouldn't hold my breath.

I hope you find a solution that works for you.

**Comment by bensku** [comment]
It would be possible to implement event-specific priority, but as said, I don't have time very soon.
