### ISSUE TITLE
[Suggestion] Don't parse skript on server start (configurable)

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1970]
Loading a lot of scripts takes ages getting parsed on server start or server restart. My suggestion is to make a config option to enable / disable skript parsing on server start.
This would improve server startup time a lot.

**Comment by FranKusmiruk** [comment]
When would you load them if we were to add that configuration option? Manually? Scripts are best loaded on server start so it doesn't hurt gameplay for the players, there's also an experimental option to make it asynchronous if it is that slow for you. 

That aside, you may consider checking your scripts and see what's delaying the parsing, and use an alternate syntax if available, splitting up your scripts into small parts is also good. It shouldn't take more than a few seconds if you happen to have a lot of scripts.

That being said, I am rather against this feature since it doesn't seem like a solution to anything but rather, a workaround to something. If you could explain a valid use-case, which isn't the one explained in the main issue, I may consider it.

**Comment by Govindass** [comment]
> When would you load them if we were to add that configuration option? Manually? Scripts are best loaded on server start so it doesn't hurt gameplay for the players, there's also an experimental option to make it asynchronous if it is that slow for you.
> 
> That aside, you may consider checking your scripts and see what's delaying the parsing, and use an alternate syntax if available, splitting up your scripts into small parts is also good. It shouldn't take more than a few seconds if you happen to have a lot of scripts.
> 
> That being said, I am rather against this feature since it doesn't seem like a solution to anything but rather, a workaround to something. If you could explain a valid use-case, which isn't the one explained in the main issue, I may consider it.

"more than a few seconds"? xD more like minutes, takes me like 5 minutes to parse my 90 scripts.

**Comment by Blueyescat** [comment]
so you want to freeze the server while the players are playing

**Comment by FranKusmiruk** [comment]
> "more than a few seconds"? xD more like minutes, takes me like 5 minutes to parse my 90 scripts.
That means you've got something delaying it or that they're rather long scripts as explained above. I've had myself a server with ~100 scripts which didn't really take longer than 15 seconds to parse everything.

**Comment by ham1255** [comment]
@Govindass  lol you have about +90 plugins aswell

**Comment by bloggy** [comment]
Loading scripts should not automatically mean that they are parsed the same time. And some times there are no other effects / methods to achieve something, so improving scripts load time does not always work.
We have huge scripts with thousands of line of code, already split into several scripts. But still, they take forever to load.

So loading the scripts without parsing them on server start could be very nice to have.

**Comment by Nicofisi** [comment]
So when would you like them to be parsed?

**Comment by Pikachu920** [comment]
Can you explain how loading isn't synonymous with parsing?

**Comment by bloggy** [comment]
Let me try to clarify this.
I don't know how skript handles loading / parsing. 
My idea was to have the scripts enabled (loaded) without being parsed (=> not checking for errors / correct syntax) on server start. 
This should be configurable (in skript's config file).  **Parse on server start: true/false**
With this option set to TRUE you'd have to use `/skript reload MYSCRIPT` to actually parse a specific script.

**Comment by Govindass** [comment]
> Let me try to clarify this.
> I don't know how skript handles loading / parsing.
> My idea was to have the scripts enabled (loaded) without being parsed (=> not checking for errors or correct syntax) on server start.
> This should be configurable (in skript's config file). **Parse on server start: true/false**
> With this option set to TRUE you'd have to use `/skript reload MYSCRIPT` to actually parse a specific script.
> From my understanding this feature would increase server load time extremely.

I think for it to work, the syntax has to be checked if is correct, other way Skript won't know what code to execute.

**Comment by FranKusmiruk** [comment]
I am closing the issue since what you're asking for isn't recommendable and even then, it wouldn't work as you expect since Skript has to parse the syntax for them to work, there isn't such thing as "loading" in-between.

**Comment by bloggy** [comment]
This is a little bit offtopic, but Fran, your skript-db fork seems to work fine. Why don't you build a .jar for download?
