### ISSUE TITLE
spawn egg item not working

### ISSUE THREAD

**Issue by MadPanCake** [SkriptLang/Skript#1971]
### Description
Skript doesn't recognise spawn eggs as item stacks. It used to do it in **version 2.2-dev37c** when I was using "spawn_egg" instead of "spawn egg", but now neither "spawn_egg" nor "spawn egg" works and both display same error message 

> Can't compare an item stack with 'spawn egg' (looting.sk, line 50: if event-item is spawn egg:')
or
> Can't compare an item stack with 'spawn egg' (looting.sk, line 50: if event-item is spawn_egg:')

### Steps to Reproduce
```
on pickup:
	if event-item is spawn egg:
		if name of event-item is "&aCat Grenade":
			if player's gamemode is survival:
				if player has spawn egg:
```

### Expected Behavior
It should just work and do the code after `'if event-item is spawn egg:'` thing.

### Errors / Screenshots
> Can't compare an item stack with 'spawn egg' (looting.sk, line 50: if event-item is spawn egg:')

### Server Information
* **Server version/platform: spigot-1.12**
* **Skript version: 2.3.6 (latest)**

**Comment by FranKusmiruk** [comment]
It is just that the aliases changed a bit, you can try using `any spawn egg` instead.

**Comment by MadPanCake** [comment]
It still doesn't work at least partially, it doesn't give any errors, but putting `any spawn egg` instead of `spawn egg` doesn't make the code work. And there are cases when I have to check the amount of spawn eggs player has and then I can't use `if player has 2 any spawn eggs:` as it gives me the same error as before.

**Comment by Blueyescat** [comment]
It should, but aliases of 1.12.2- don't support the plural form (any spawn egg**s**). Also the `any` should be optional.

Anyways this works fine on 1.13.2:
```vb
on pickup:
	if event-item is slime spawn egg:
		broadcast "ok"
```
Note that if you are using **`send`**, you need to specify the player using `to player` because it tries to send the message to event-entity which is the dropped item.

**Comment by TheBentoBox** [comment]
I've updated the spawn egg alias groups to all be formatted as `[any] spawn egg¦s`

**Comment by TheBentoBox** [comment]
This should be fixed in the latest release.
