### ISSUE TITLE
Dyes and water bottles doesn't work in on pickup event

### ISSUE THREAD

**Issue by MadPanCake** [SkriptLang/Skript#1973]
### Description
Dyes doesn't work in on pickup event.

**EDIT: It seems that this code doesn't work neither if its any dye, or water bottle.**

### Steps to Reproduce
```
on pickup:
	if event-item is red dye:
		send "1" to player
        if event-item is water bottle:
		send "1" to player
```

Additionally, full code:
```
on pickup:
	if event-item is stone sword or bow or leather cap or elytra or leather pants or leather boots or glass bottle:
		if name of event-item contains "Starter" or "Training" or "Novice" or "Wings":
			wait 1 tick
			remove event-item from player
	if event-item is red dye:
		send "1" to player
	if event-item is water bottle:
		send "1" to player
```
Removing stone sword, armors, elytra, glass bottles and arrows works fine, removing dirt too.

### Expected Behavior
As stated above.

### Errors / Screenshots
No errors occured.

### Server Information
* **Server version/platform: spigot-1.12**       
* **Skript version: latest**

**Comment by TheBentoBox** [comment]
Likely fixed by the numerous item comparison fixes made in the recent months.
