### ISSUE TITLE
Lit redstone ore is missing an alias

### ISSUE THREAD

**Issue by Vrganj** [SkriptLang/Skript#1974]
### Description

There isn't an alias for lit redstone ore.

### Steps to Reproduce

```
mine:
    block = any ore:
        send "%block%"
```

### Expected Behavior

I thought it was going to return something, but didn't.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/43708436/54883339-3dfa7b80-4e65-11e9-9a30-95691583a2be.png)
This is what I get when I send "%block%" without checking if it's an ore

### Server Information
* **Server version/platform:** Paper 1.12.2      
* **Skript version:** 2.3.6

**Comment by TheBentoBox** [comment]
This should be addressed in the latest release.
