### ISSUE TITLE
Where filter issue

### ISSUE THREAD

**Issue by APickledWalrus** [SkriptLang/Skript#1975]
### Description
The where filter doesn't not work in some instances where it *probably* should. I don't think this is user error, but it could be. I assume this is because of the way of how it's coded to accept things. See below for an example.

### Steps to Reproduce
```
set {_pot} to arg-3 where [arg-3 parsed as an integer < 0]
replace all "-" in {_pot} with "" where [arg-3 parsed as an integer < 0] WORKS FINE
replace all "-" with "" in {_pot} where [arg-3 parsed as an integer < 0] ERRORS
```

### Expected Behavior
Both lines of code should work, as they are the same thing, no?

### Errors / Screenshots
Error Message: http://prntscr.com/n2ejkx
arg-3 is defined as a text in the command.

### Server Information
* **Server version/platform:**       Paper git-Paper-562 (15 behind) 1.13.2 
* **Skript version:**                2.3.6

**Comment by FranKusmiruk** [comment]
1. You're using it incorrectly, it is to filter stuff, not to use it as a condition.
2. Return type of variables is unknown at parse-time, hence why it errors since the replace all effect expects a string, so, this is expected behaviour.
3. You can use the `do if` effect there instead:
```vb
replace all "-" with "" in {_pot} if arg-3 parsed as integer is less than 0
```

**Comment by Pikachu920** [comment]
@FrankMusmiruk I guess we should probably make it fail init on a single expression
