### ISSUE TITLE
Return player in "on vehicle ..." events (only "on vehicle exit" works)

### ISSUE THREAD

**Issue by l-Aeden-l** [SkriptLang/Skript#1976]
All is in the title, but simply it would be great to get the player for:
on vehicle create
on vehicle damage
on vehicle destroy
on vehicle enter

**Comment by Syst3ms** [comment]
Please use the issue format for your request.

**Comment by ShaneBeee** [comment]
For the time being, try `event-entity` as players are not the only ones who interact with vehicles

**Comment by FranKusmiruk** [comment]
I've checked myself and those events don't have the proper event values (except the vehicle exit event), it returns the passengers of the entity instead of the entity who entered in the vehicle enter event or the entity who attacked in the vehicle damage event.

**Comment by l-Aeden-l** [comment]
Do you think you can add the proper event values for each one?

**Comment by TheBentoBox** [comment]
This should be resolved in the latest releases.
