### ISSUE TITLE
[Bug] Weird Block Thing

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1977]
### Description
Im not sure if this has been reported, but If it has, this really should have been fixed by now. I totally forgot about this, but when you set a block to something like oak stairs, it sets the stairs at the location, and then a mirrored version above it

### Steps to Reproduce
in game run `!set block at player to oak stairs`
and you get this (see pic below)

### Expected Behavior
To place 1 stair not 2

### Errors / Screenshots
![](https://i.imgur.com/tsEfg9Y.png)

### Server Information
* **Server version/platform:**  Paper version git-Paper-564 (MC: 1.13.2)
* **Skript version:** 2.3.6

### Additional Context
none

**Comment by Govindass** [comment]
maybe try !set block at player to oak stair

**Comment by ShaneBeee** [comment]
> maybe try !set block at player to oak stair

same outcome

**Comment by Vrganj** [comment]
Works on Paper 1.12.2, skript 2.3.6

**Comment by ShaneBeee** [comment]
> Works on Paper 1.12.2, skript 2.3.6

Yeah Im aware... this is a 1.13.2 bug with Skript, since 1.13.x handles blocks/items very different than previous versions.

**Comment by TheBentoBox** [comment]
This has to do with how Skript handles placing bisected blocks (such as double height flowers). Blocks that have a top and bottom half extend the [`Bisected`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/Bisected.html block data) but things that can be flipped upside-down (like stairs) also extend this subclass. This may be an issue with trapdoors too for that same reason.

**Comment by Syst3ms** [comment]
You mention double height flowers, but those don't extend Bisected according to the Javadoc.

**Comment by TheBentoBox** [comment]
I'm not sure where you're looking but because they look like they all are `Bisected` BlockData instances to me:

![image](https://user-images.githubusercontent.com/6902229/55007104-38ac4680-4fb5-11e9-96f0-bd14c8c4c156.png)
![image](https://user-images.githubusercontent.com/6902229/55007013-14506a00-4fb5-11e9-95f5-b7e827eee056.png)
![image](https://user-images.githubusercontent.com/6902229/55007035-1ca8a500-4fb5-11e9-9d99-6eeb4151cf50.png)
![image](https://user-images.githubusercontent.com/6902229/55007055-26caa380-4fb5-11e9-8a3a-80dca0cafd3c.png)

**Comment by Syst3ms** [comment]
Weird : 
![image](https://user-images.githubusercontent.com/21205986/55007475-c56bfa00-4fdf-11e9-88ab-09c8abb3f117.png)

**Comment by TheBentoBox** [comment]
They're not subinterfaces, they return a straight up instance of the Bisected interface itself. The classes which extend Bisected are those which either are a combination of many interfaces (such as trapdoor) and/or those that which have more data specific to that block type (stair shape, door hinge side). The only block state on double height plants is which half they are, top or bottom, so their data is just a simple Bisected instance.

**Comment by Syst3ms** [comment]
Well I would agree with you, but you can't instantiate an interface as far as I know ; you need an implementing class. I don't know how Spigot manages it.

**Comment by TheBentoBox** [comment]
Yeah, I wouldn't really know, don't work in plugin dev or Java that much. There are languages where you can type things as an interface even if it's not instantiated in the traditional sense but I don't know how the implementation works in this case.
