### ISSUE TITLE
Player head issues

### ISSUE THREAD

**Issue by Vrganj** [SkriptLang/Skript#1978]
### Description

When I  try `on right click on player head` it parses without any errors, but when I try triggering the event, nothing happens.

### Steps to Reproduce

```vb
on right click:
  send "%tool%"
```

### Expected Behavior

I thought it'd trigger the event.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/43708436/54991259-d7887100-4fbc-11e9-93ea-9b3cae3c2fb9.png)
![image](https://user-images.githubusercontent.com/43708436/54991349-0acb0000-4fbd-11e9-8782-67f91fc76c35.png)

### Server Information
* **Server version/platform:** Paper 1.12.2      
* **Skript version:** 2.3.6

**Comment by FranKusmiruk** [comment]
The string representation says you clicked a dragon head meanwhile you used `on right click on player head`.

**Comment by Vrganj** [comment]
> The string representation says you clicked a dragon head meanwhile you used `on right click on player head`.

Yeah

**Comment by TheBentoBox** [comment]
> Yeah

?

An ender dragon head isn't a player head. You can't detect a player clicking on an ender dragon head with `on right click on player head` because it's an ender dragon head, not a player head. If you want to detect them clicking on an ender dragon head, it would be `on right click on ender dragon head`.

**Comment by Vrganj** [comment]
What I'm trying to say is that I'm clicking on a player head but when I try using `on roght click on player head` it won't work. When I try using the `on right click` event and send "%tool%" it returns south facing ender dragon head...

**Comment by Vrganj** [comment]
> The string representation says you clicked a dragon head meanwhile you used `on right click on player head`.

`on right click on player head` doesn't work, that's the problem, when I use `on right click` and send "%tool%" it tells me I clicked on a dragon head, so I tried using `if tool = south facing dragon head named "..."` and that also didn't work

**Comment by TheBentoBox** [comment]
Any potential real issues here will likely have been fixed with the updates to item comparisons and this also seems to have been in part due to misunderstanding.
