### ISSUE TITLE
Skript is unable to name item in var "IF Vixio is installed" IS IT skript releated or not

### ISSUE THREAD

**Issue by ham1255** [SkriptLang/Skript#1982]
### Description
i know this isn't related to skript to fix but Problem that skript is Unable to name item in  Var

### Steps to Reproduce

```
command /server:
	trigger:
		wait 10 ticks
		set {_item} to "Ender pearl" parsed as item
		set name of {_item} to "&dSkyblock"
		set lore of {_item} to "&f&l%{Skyblock}%/200||%{Skyblock_Status}%"
		send "%{_item}%"

	
```
it should output "ender pearl named "&dSkyblock"" right?
But. if vixio is installed it just output "Ender pearl" like no naming happend but lore worked

and there is no error on console Because i reported the error on vixio bug tracker
and dev said he fixed it https://github.com/iBlitzkriegi/Vixio/issues/152

### Server Information
* **Server version/platform:**       1.12.2 paper 
 **Skript version:**                2.3.6 skript

**Comment by Blueyescat** [comment]
As you said it is related to Vixio, because it registers the same syntax with Skript. In the issue you mentioned, they made the syntax **`discord name`** instead of **`[discord] name`** but a new version with this change is not released yet.

❌

**Comment by ham1255** [comment]
@Blueyescat  i forgot to till that i downloaded the vixio project from the github and i complied it and error is gone but still not able to name the item in the var here https://github.com/iBlitzkriegi/Vixio/commit/ae5c7d819ac762523000418ec075a10ddfa2b451

**Comment by Blueyescat** [comment]
Then why would removing/installing Vixio would affect it

**Comment by ham1255** [comment]
i am not sure

**Comment by SiebeDW** [comment]
This is a jar that i got from vixio. This didnt broke my skripts after update so i hope this helps you @ham1255 
https://ufile.io/ca1rn

**Comment by FranKusmiruk** [comment]
Closing since it's an issue with Vixio.
