### ISSUE TITLE
Error with the condition "can build"

### ISSUE THREAD

**Issue by Eryk1983S** [SkriptLang/Skript#1985]
Server: Spigot 1.12.2.-R.0.1-SNAPSHOT
Skript-Version: 2.3.6.

### Description
Trigger:
on break:
	player can build
	send "You can build" to the player

[15:00:02 ERROR]: Can't understand this condition/effect: player can build (Script.sk, line 13: player can build')

### Expected behaviour:
It should normally work as it was described in the docs:
https://docs.skunity.com/syntax/conditions

**Comment by TheBentoBox** [comment]
The condition requires you to specify the location you're checking. It says that [right in the docs you linked to](https://docs.skunity.com/syntax/search/id:2274).

**Comment by Eryk1983S** [comment]
Hi,
I don't want to spam, so I write here.

In the docs there was an example:
if player can build:
  send "You can build"
else if player is not allowed to build:
  send "You can't build"

There wasn't any location...

*But it's not so important as the thing, that the negative condition "can
not build" doesn't work.*

Greetings
Eryk

czw., 28 mar 2019 o 15:31 Jake Ben-Tovim <notifications@github.com>
napisał(a):

**Comment by FranKusmiruk** [comment]
That's on skUnity, you may contact them about it. Since our docs has a (http://skriptlang.github.io/Skript/conditions.html#CondCanBuild)[working example].

**Comment by Eryk1983S** [comment]
Sorry, I thought, that I write a private mail. But if the thread isn't closed yet, I'll try to precise the issue.

@FranKusmiruk Thanks for the link to the docs of 2.3. It will be useful in the future...

...But now it doesn't help. My current trigger is:

on break:
	player cannot build at the targeted block
	send "Control message" to the player
	kill player
	message "Control message 2"

I only get the message from WorldGuard or from Towny, that I'm not allowed to destroy the block. Skript doesn't send neighter "Control message" nor "Control message 2" and I'm not killed.

Earlier I tried something like that:

on break:
	player can build at the targeted block:
	       send "Control message" to the player
	else:
	       send "Control message 2" to the player

In this case only Control message was displayed, but not Control message 2.
