### ISSUE TITLE
Play effect problems

### ISSUE THREAD

**Issue by Ilkkadius** [SkriptLang/Skript#1986]
### Description

"Play effect" effect isn't working as intended with coloured dust and potion break -effects.

### Steps to Reproduce

**First and more important problem:**
Example code:

on right click with diamond sword:
    play green dust in event-location

The code above doesn't give error to console, but the green dust doesn't appear in the clicked block.

But if you add any number before the green dust, error is printed to the console and nothing happens in the block that was clicked.

on right click with diamond sword:
    play 2 green dust in event-location

**Second, less important problem:**
Console error is obtained also, if potion breaking -effects are put to green dust's place, for example this code gives error when clicked a block with diamond sword:

on right click with diamond sword:
    play 2 speed potion break in event-location

If the integer before "speed potion break" is removed, visual effect occurs and no error is printed. However, potion break -effects work if they are put inside parentheses, like this:

on right click with diamond sword:
    play 2 (speed potion break) in event-location

Changing the number before potion break -effect doesn't however alter the seen visual effect in any way.
### Errors / Screenshots

Console error from coloured dust: https://gist.github.com/Ilkkadius/96293ffc04c5f9bc98120f2df4b9866c

Console error from speed potion break -effect: https://gist.github.com/Ilkkadius/003a9a51b6b813ba658ba838781f85b5

**Comment by ShaneBeee** [comment]
I didn't realize there were 2 of the same issue. Anyways this has been fixed.
