### ISSUE TITLE
No manifest file when trying to open .jar

### ISSUE THREAD

**Issue by BxPanxi** [SkriptLang/Skript#1988]
Hi! I just tried to download the Skript.jar file, the latest one, and when I tried double-clicking it, nothing happened. So when I tried it in cmd, I got; No main manifest attribute, in Skript.jar. I was wondering why? I tried previous version too.

**Comment by FranKusmiruk** [comment]
Skript isn't an standalone program, it's a minecraft plugin for Bukkit/Spigot servers.

**Comment by SiebeDW** [comment]
#1748 would be usefull
