### ISSUE TITLE
Error executing a command with the console

### ISSUE THREAD

**Issue by Valentyn72** [SkriptLang/Skript#1989]
Hello, since 1.13, the skripts blocking the commands for some players
(like this one : `on command "/mvtp":
	if player is not "Pseudo" or "Pseudo" or "Pseudo":
		send "&4Message"
		cancel event`)
also block the commands executed by the console whereas normally they are blocked only for the players. Before that was not the case. How to do ?
Thanks.

**Comment by ShaneBeee** [comment]
just try adding a condition like:
`if sender is a player:`

**Comment by Valentyn72** [comment]
It's good.
Thanks :)
