### ISSUE TITLE
"set block above to wheat plant" doesn't work

### ISSUE THREAD

**Issue by SoraNoIseki** [SkriptLang/Skript#1990]
I have tried this script for test:
```
on rightclick on grass, dirt or soil with any hoe:
    block above is air
    player has seeds
    set block to soil
    set block above to wheat plant
    remove seeds from player
    damage tool by 1
```

But **"set block above to wheat plant"** doesn't work.  It works by using "carrot plant" instead.

Server Information:
* **Server version/platform:  Spigot 1.12.2**
* **Skript version: 2.3.6**

**Comment by TheBentoBox** [comment]
This alias [does exist](https://github.com/SkriptLang/skript-aliases/blob/master/other.sk#L65) for 1.12.2 so I can't say from an aliases side why this is an issue.

**Comment by TheBentoBox** [comment]
Closing in favor of #2394 as it is the same bug and that one better describes the problem.
