### ISSUE TITLE
Ability to use multiple parts of alias variations

### ISSUE THREAD

**Issue by APickledWalrus** [SkriptLang/Skript#1992]
### Description
Hopefully this makes sense. Essentially the ability to use multiple parts of an alias variation (if that's what you call it?) would be nice. It would allow for enchanting books and different block states to be able to be put into the alias. Not sure how difficult this is though.
Example to better explain:

```
{block states}:
    multiple variations usable = true <--- Could be used to enable this; false by default
    east = -[east=true]
    west = -[west=true]

{waterloggable} {block states} cobblestone wall
waterlogged east west cobblestone wall <--- allows for both [east] and [west] to be true
```
Instead of having to create a tag like "east-west = -[east=true,west=true]," you could allow the usage of both as making tags like that doesn't work for large numbers of combinations.

**Comment by bensku** [comment]
I'm not sure if I agree about the syntax, but this might be useful. In some cases, this already works; not specifying a block state matches all values of it.

**Comment by APickledWalrus** [comment]
Yeah, wasn’t sure what to put for the syntax  so I just put that.

**Comment by Moderocky** [comment]
It might be nicer to hyphenate between the multiple states, such as `north-south cobblestone wall`, seems a bit more natural than separate words to me

**Comment by APickledWalrus** [comment]
I am going to close this because BlockData is likely the best solution here.
