### ISSUE TITLE
Multiple conditions in one if statement

### ISSUE THREAD

**Issue by Vrganj** [SkriptLang/Skript#1993]
### Description

It'd be really useful if we could put multiple conditions in an if statement. Would work something like this
```vb
if arg is true and {_hi} is set:
else if {_hi} and arg are false:
else:
```

**Comment by FranKusmiruk** [comment]
This is a duplicate, I don't remember the exact issue but I do know there was an issue about this. Regardless, this is possible but kind of problematic due to how Skript works.
