### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by DDuart** [SkriptLang/Skript#1996]
there is way to create something like this?
```vbs
function test(w: world, p: player):
function test(p: player):
```
two functions named in the same way with different arguments

**Comment by DDuart** [comment]
```vbs
function test(w: world, p: player):
  ...
  
function test(p: player):
  test({_p}.getWorld(), {_p})
```

**Comment by DDuart** [comment]
is the chance that you will add it? the code would be much clearer.

**Comment by FranKusmiruk** [comment]
What you're asking for is function overloading and due to how functions are implemented right now, this isn't really feasible. I could keep this as enhancement but there's an issue about it wandering around already. 

Also, **use the issue templates**.
