### ISSUE TITLE
Can not delete item in "on pickup" event

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1999]
Can not delete item in on pickup event. Latest Skript version on Paper Spigot 1.13.2.

```
on pickup:
	if event-item is a gold nugget:
		delete item
```

Error:
https://hastebin.com/ziyakekemi.cs

Also tried:
"delete event-entity" -> does nothing  
"delete event-item" -> nothing

**Comment by TheBentoBox** [comment]
Have you tried any other expressions? `event-entity` or `the dropped item`?

**Comment by FranKusmiruk** [comment]
Solved in Discord, it was an user error.

**Comment by Fusseldieb** [comment]
> Solved in Discord, it was an user error.

**What did you see?**

Tell us. 
 
How did you solve it?
