### ISSUE TITLE
Potion expression not being usable in event parameters

### ISSUE THREAD

**Issue by itismejoey** [SkriptLang/Skript#20]
Error: can't understand this even 'on dispense of potion'. 

All other on dispense of work fine.

**Comment by bensku** [comment]
Interesting... It would be that direct targeters "on X of Y" don't support expressions, which potion system now uses. Will have to look at this.

**Comment by Pilvinen** [comment]
I can confirm.

On the other hand this works:

```
on dispense:
  event-item is potion
  broadcast " DEBUG: 1"
```

You can use it as a workaround.

**Comment by bensku** [comment]
Needs alias system which supports more than just legacy ids, or parser hacks. I think the latter is bad idea, so no fix right now.

**Comment by itismejoey** [comment]
@Pilvinen Your example does not work for me, returns:

```Can't compare an item stack with a types.material```
