### ISSUE TITLE
Display name expression don't work in functions

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#2000]
Skript 2.3.6
Paper build 616

Code:
```
function TestDisplay(p: player):
	set the display name of {_p} to "&cAdmin %{_p}%"
	broadcast "Display %{_p}%: %{_p}'s display name%"
```
Behaviour: http://prntscr.com/naxii8

**Comment by Govindass** [comment]
this is the 2000th issue

**Comment by TheBentoBox** [comment]
I'd appreciate a confirmation from someone else + confirmation that it works fine outside of functions

**Comment by ShaneBeee** [comment]
I can confirm this works outside of a function

I ran these two:
```
!set display name of player to "test"
!send "Display: %display name of player%"
```
Which showed an output of "Display: test"
And when I chat it shows my display name as test.

I can also confirm it is not working in the function as ruddeTR stated

**Comment by Blueyescat** [comment]
@Govindass i thought you meant 2000th issue of the same bug

**Comment by FranKusmiruk** [comment]
I can't reproduce this isssue using Skript 2.3.6 on Paper 1.13.2 (build 600 currently)

**Comment by ShaneBeee** [comment]
I also cant reproduce this error, using Skript 2.5-beta4 and Paper version git-Paper-202
Closing.
If anyone still has issues with this, please let us know so we can re-open
