### ISSUE TITLE
Can't join the server + plugin doesn't load !

### ISSUE THREAD

**Issue by Nosiows** [SkriptLang/Skript#2001]
### Description
When the server start , i get an error and i can't join !

### Steps to Reproduce
Create an atom 1.12.2 server and install the plugin !

### Errors
https://hastebin.com/oruyevokav.rb

### Server Information
Atom 1.12.2
Skript 2.3.6

**Comment by FranKusmiruk** [comment]
Atom isn't a supported platform at moment.

**Comment by Blueyescat** [comment]
enhancement
