### ISSUE TITLE
loop - only a single value

### ISSUE THREAD

**Issue by DDuart** [SkriptLang/Skript#2002]
hi!
loops doesn't work if you use `any`.

for example:
```
      loop any flower:
        broadcast loop-value
```

error:
```
Can't loop dandelion, poppy, blue orchid, allium, azure bluet, red tulip, orange tulip, white tulip, pink tulip, oxeye daisy, sunflower, lilac, rose bush or peonies because it's only a single value
```

u need to use `loop any flower and air` for example to make it works

**Comment by Pikachu920** [comment]
that shouldn't work, you need to use all flowers

**Comment by imnotcap** [comment]
Hi, i got this skript, and it wont let me use the "loop event-block:" because it's a single value.
Do you have some suggestions?

`on break:
    loop event-block:
        set {_e::%location of loop-value%} to true
        set {_e::%location of loop-value%::*} to location of loop-value and type of loop-value
    wait 10 seconds
    loop {_e::*}:
        set block at {_e::%loop-index%::1} to {_e::%loop-index%::2}`

`#The function that brings everything together:

function chain(b: block, n: number, p: player):
    wait 1 tick
    if {_n} is less than 50:
        add 1 to {_n}
        loop blocks in radius 3 around {_b}:
            if loop-block is any log:
                set block below loop-block to air
                chain(loop-block,{_n}, {_p})
                break loop-block naturally
                play sound "entity.player.levelup" with volume 0.05 at location of loop-block
                wait 10 tick
                wait 2 seconds
                stop
                wait 2 seconds

# The tool itself in action:

on break:
    if player is in world "new":
    if player is holding gold axe named "&e&lTreecapitator" with lore "&7", "&7Fell a tree with style,", "&7make it dissapear in a few seconds.", "&7", "&f⅄⅃", "&f⅌":
        if gamemode of player is survival:
            if event-block is any log:
                set {_tree} to false
                loop blocks above event-block:
                    if loop-block is any leaves:
                        set {_tree} to true
                if {_tree} is true:
                    chain(event-block, 0, player)

# Regenerate the logs that have been broken function:

on break:
    loop event-block:
        set {_e::%location of loop-value%} to true
        set {_e::%location of loop-value%::*} to location of loop-value and type of loop-value
    wait 10 seconds
    loop {_e::*}:
        set block at {_e::%loop-index%::1} to {_e::%loop-index%::2}`

**Comment by TheLimeGlass** [comment]
> Hi, i got this skript, and it wont let me use the "loop event-block:" because it's a single value. Do you have some suggestions?
> 
> `on break: loop event-block: set {_e::%location of loop-value%} to true set {_e::%location of loop-value%::*} to location of loop-value and type of loop-value wait 10 seconds loop {_e::*}: set block at {_e::%loop-index%::1} to {_e::%loop-index%::2}`
> 
> `#The function that brings everything together:
> 
> function chain(b: block, n: number, p: player): wait 1 tick if {_n} is less than 50: add 1 to {_n} loop blocks in radius 3 around {_b}: if loop-block is any log: set block below loop-block to air chain(loop-block,{_n}, {_p}) break loop-block naturally play sound "entity.player.levelup" with volume 0.05 at location of loop-block wait 10 tick wait 2 seconds stop wait 2 seconds
> # The tool itself in action:
> 
> on break: if player is in world "new": if player is holding gold axe named "&e&lTreecapitator" with lore "&7", "&7Fell a tree with style,", "&7make it dissapear in a few seconds.", "&7", "&f⅄⅃", "&f⅌": if gamemode of player is survival: if event-block is any log: set {_tree} to false loop blocks above event-block: if loop-block is any leaves: set {_tree} to true if {_tree} is true: chain(event-block, 0, player)
> # Regenerate the logs that have been broken function:
> 
> on break: loop event-block: set {_e::%location of loop-value%} to true set {_e::%location of loop-value%::_} to location of loop-value and type of loop-value wait 10 seconds loop {_e::_}: set block at {_e::%loop-index%::1} to {_e::%loop-index%::2}`

This isn't for help regarding Skript, there are forums and Discord servers for this. You can't loop a single block, if I don't understand what you're trying to do, there is no way Skript will.
