### ISSUE TITLE
Issue with "%newline%" and "||"

### ISSUE THREAD

**Issue by Tyloonie** [SkriptLang/Skript#2005]
### Description

Whenever adding "||" or "%newline%" to the lore of an item in a GUI using skQuery, it doesn't add a new line. Instead, it simply prints the expression as raw text. I'm unsure whether this is an error within skQuery or Skript itself.

### Steps to Reproduce

https://hastebin.com/ohilavubiw.pl

### Expected Behavior

I expect the expression to function as intended by adding a new line to the lore of the GUI item.

### Errors / Screenshots

This is how the code from above looks ingame.
https://gyazo.com/ec938bc194205f89350c33895b1ce2de

### Server Information
* **Server version/platform: Paper 1.13.2 (newest)**       
* **Skript version: 2.3.6 (newest)**                
* **skQuery version: 3.6.4 (newest)**

**Comment by TrademarkTM** [comment]
`%newline%` is from skQuery, and it isn't supposed to work on lores anyways.
`||` is also from skQuery, it does exactly that on lores.

In 2.3 the lore expression was introduced in Skript (and removed in skQuery 3.6.3). It uses lists, not characters: `diamond sword with lore "Multiple", "line" and "lore"`.

**Comment by Tyloonie** [comment]
So if I for example had an option containing various lines of lore using `||` to split them, I would then have to create 5 different options, each containing their own line of lore?

`gui-lore: Lore||Lore||Lore`

would then become

`gui-lore-1: Lore`
`gui-lore-2: Lore`
`gui-lore-3: Lore`

Doesn't seem very productive. Perhaps there is a smarter way to do this that I don't know of? Thanks for your quick reply.

**Comment by TrademarkTM** [comment]
I suppose you can use `split %string% at %string%` if you don't want to use multiple options (personally I don't like them anyways).

`...with lore (split {@lore} at "||")`
* () are not required

**Comment by Tyloonie** [comment]
Works brilliantly - you forgot adding the `""` around `{@lore}` (`...with lore (split "{@lore}" at "||")`) but doing so did the trick.
Thank you for your help. Have a lovely evening - sorry for the trouble.
