### ISSUE TITLE
Stair Name

### ISSUE THREAD

**Issue by Plutoren** [SkriptLang/Skript#2006]
### Description
Stair names are a bit broken on 1.13

### Steps to Reproduce
I put 4 stairs down like so:
![stairs](https://i.gyazo.com/1a1408e4ecd38867056686b49a665537.png)
Then I used the right click on quartz stairs event and message myself the clicked block
```
on right click on quartz stair:
	message "%clicked block%"
```
Then I right click each of the 4 stairs and get this output
![output](https://i.gyazo.com/b7e72ddecc69e155a835f4c29044e4a0.png)

### Expected Behavior
The stairs would all have the same name besides the direction but there are several changes such as dry/bottom not appearing, and even the "nether" part of "nether quartz"

This issue exists for other stairs but some have different behavior

### Server Information
* **Server version/platform:**       Paper 1.13.2
* **Skript version:**               Skript 2.3.6

**Comment by TheBentoBox** [comment]
I've asked for this to be fixed for but as I understand it it's not super easy. It's an issue with Skript itself so it's not something I can fix in the aliases unfortunately. It's also not that important but I agree it should be fixed at some point if possible because it's at the very least confusing and potentially misleading.

**Comment by TrademarkTM** [comment]
I don't understand why the aliases work like that. Wouldn't it be easier to use expressions/conditions instead?
```
facing of %block%
%block% is (1¦dry|2¦wet)

set block at event-location to *wet/dry* *bottom/top* quartz stair *facing north/south/east/west*
```

**Comment by TheBentoBox** [comment]
Many versions of Minecraft don't have a consistent way to represent that, e.g. `facing` is represented entirely different pre-1.13, so defining that in the aliases lets the code itself be version-agnostic when it comes to how to create or identify specific blocks being in specific states.

Also the latter ("or even") idea is fairly anti-Skript as far as the whole "it looks like English" part goes.

**Comment by TheLimeGlass** [comment]
Don't know when this was solved but it's as expected now.
