### ISSUE TITLE
Wheat plant - Jobs skript / Don't work - help plz

### ISSUE THREAD

**Issue by gethertv** [SkriptLang/Skript#2009]
Hello, i want create skript on JOBS and if i want get 10 diamond for **"ripe wheat plant" - dont work**, but if i want get 10 diamond for **"potato plant" - works**

on break of ripe wheat plant:
	give 10 diamond to player
on break of potato plant:
	give 10 diamond to player

Help me plz. i dont have error

**Comment by TheBentoBox** [comment]
Please re-open this and this time actually use one of the issue templates that are suggested to you when you create a new issue. We need more information like your versions which you haven't provided.

**Comment by gethertv** [comment]
maybe help, give link?

**Comment by ShaneBeee** [comment]
> maybe help, give link?

When you create an issue you are given an option of 3 templates. Click bug report, but this time, don't delete the template, fill out all the things it is asking you to fill out.
