### ISSUE TITLE
sorting lists breaks loop-index

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2014]
### Description
when sorting lists, loop-index doesn't function properly

### Steps to Reproduce
```vbs
command /baltop [<text>]:
	trigger:
		send ""
		send "                  &6&lBaltop"
		send ""
		set {_top::*} to sorted {balance::*}
		loop {_top::*}:
			add 1 to {_n}
			send " &e(##%{_n}%) &7%loop-index% &e$%loop-value%"
```

### Expected Behavior
loop-index should return what it usually does (the player), and not the position in the list

### Server Information
* **Server version/platform:**  https://i.imgur.com/6d5nCFP.png
* **Skript version:**  2.3.6

**Comment by TheBentoBox** [comment]
Duplicates #202

**Comment by MrScopes** [comment]
> Duplicates #202

why hasn't it been fixed then? It's been 2 and a half years

**Comment by Pikachu920** [comment]
because it isn't that simple, and issues aren't prioritized based on how old they are
