### ISSUE TITLE
Dyes not matching item 

### ISSUE THREAD

**Issue by Moderocky** [SkriptLang/Skript#2016]
### Description
When using a dye such as `ink sac` in the `on rightclick with ...` event, or with `event-item` in that, the condition will fail if it is not an exact match.
What this means is that `on rightclick with ink sac:` will work only if you have a normal item, and not one with any NBT tags, or different lore.

This can be bypassed by using `type of event-item is ink sac` as a condition, though obviously that might not be appropriate for every case.

This is limited to all dyes. Other items work as expected.

### Steps to Reproduce
```on rightclick with ink sac:
  broadcast "hi"
```
Try right-clicking with a default item straight from the creative inventory, and also with one with custom lore+NBT tags.

The same can be reproduced with below:
```on rightclick:
  event-item is ink sac
  broadcast "hi"
```

This works for all dyes.

### Expected Behavior

The condition should pass, as it would with other item types such as `stone pickaxe` or `sugar`

### Errors / Screenshots

There was no console error or information produced.

### Server Information
* **Server version/platform:** Paper Spigot 1.12.2      
* **Skript version:**  2.3.6 (latest)              

### Additional Context

My server seems to be ground zero for any and all bugs, so others may not be able to reproduce this. I was, however, advised to make an issue.

**Comment by TheBentoBox** [comment]
Is this still an issue on the 2.4 alpha releases?

**Comment by TheBentoBox** [comment]
This should be resolved with the merge of #2030.
