### ISSUE TITLE
Bow spanning reset when giving an item

### ISSUE THREAD

**Issue by MinisBett** [SkriptLang/Skript#2017]
### Description

If your bow is spanned and the skript gives you an item the bow spann will reset.
### Steps to Reproduce

every second:
    loop all players:
        give sandstone to player

Then hold rightclick on the bow
### Expected Behavior

It shouldn't reset.
### Errors / Screenshots

Attached zip file with a video by "steyes" on skunity discord.

### Server Information
* **Server version/platform: *PaperSpigot 1.13.2*       
* **Skript version: *2.3.6*                

### Additional Context

[2019-04-21_15-09-57.zip](https://github.com/SkriptLang/Skript/files/3101260/2019-04-21_15-09-57.zip)

**Comment by FranKusmiruk** [comment]
This is Minecraft's default behaviour, nothing we can do about it.
