### ISSUE TITLE
Drop cancel Glitch

### ISSUE THREAD

**Issue by Obliviated** [SkriptLang/Skript#2019]
i tried first cancel, condition and uncancel thats worked i can't drop and click. But when i open my inventory and drop with press q glitching and cloning the item.
```
on load:
	loop all players:
		set slot 8 of loop-player to orange dye named "&6&lThats your skill"
on drop:
	cancel event
	event-item isn't orange dye named "&6&lThats your skill":
		uncancel event
on inventory click:
	cancel event
	item isn't orange dye named "&6&lThats your skill":
		uncancel event

**Comment by Wealthyturtle** [comment]
I am only able to replicate this issue in creative mode, survival mode doesn't have this issue.
