### ISSUE TITLE
Skript & Mods

### ISSUE THREAD

**Issue by CrazyWords1** [SkriptLang/Skript#2020]
### Question
Hello, i'm using new experimental core 'Tablecloth'
This core support BukkitApi and Forge on version 1.12.2
When i'm using newest skript 2.3.6 i get this error

![изображение](https://user-images.githubusercontent.com/32343185/56594001-aaec6700-6605-11e9-8840-131dcbe91c08.png)

But When i'm using 2.2 dev-36 , all work without bugs/errors

I know that you do not officially support fashion and are not going to change anything, for the sake of some kind of experimental core, but if you can help at least something, I beg you, help (

Sorry for distribute

**Comment by bensku** [comment]
Skript cannot initialize aliases, because Bukkit's Material enum is not in consistent state. To me it looks like someone used reflection to modify it, but the fields for new materials are (naturally) missing.

Skript didn't use Bukkit's material system before 2.3, so old versions are not affected.

**Comment by CrazyWords1** [comment]
@bensku big thk , Is there any way to fix this?
P.S (I certainly understand, there is nothing bug, but maybe somehow you(or me) did something to make it work? )

**Comment by Cronosus** [comment]
have same problem with varius items (in this case BoP, but also other mods do this)
https://paste.ee/p/ejbt8
