### ISSUE TITLE
Skellet variable id for npc issue

### ISSUE THREAD

**Issue by hitbuns** [SkriptLang/Skript#2024]
### Description

The problem is that i can't use "%name of citizen {_count}%" to check for the contain. I can still use %name of citizen 2% but not %name of citizen {_count}%. This means that either im blind and stupid or the skellett addon can't read variables in the citizen id section

### Steps to Reproduce

1. The problem is the variable {_count} used in name calling of citizen id expression

### Expected Behavior

I expected the expression to supply me a string name of the npc's display name and compare it to a contain condition

### Errors / Screenshots

errors are in logs.

https://gist.github.com/hitbuns/1b23aa2000a6817448d5e629d2a337e2 //Contains Logs and the skript used

### Server Information
* **Server version/platform:**        spigot 1.8.8
* **Skript version:**                 Bensku 2.3.6

**Comment by FranKusmiruk** [comment]
Addon issues must be reported to their own issue trackers, we are generally not responsible for them. Also, 1.8.8 is unsupported, please consider updating to receive support.
