### ISSUE TITLE
Mute sound at region/somewhere?

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2025]
Hey. I have a suggestion. Is there a option to add "mute all sounds at player (for 4 sec) "? In mean like when player enter a region: mute all sounds like zombie hurt, villagers etc. E.g loop-player "set player's volume to 0 (for 5 real seconds) " and let it don't hear anything. 
(in the margin)  I have a thing if it's not possible cause playsound is faster than code so... rip. :P. Something more I have to say :thinking: ?

**Comment by TheBentoBox** [comment]
This is not possible to control server-side.
