### ISSUE TITLE
Weird bug using on break event

### ISSUE THREAD

**Issue by leonidesu** [SkriptLang/Skript#2026]
### Description
Trouble with some event / conditions.

### Steps to Reproduce
```
on break:
	player is in "world"
	if name of player's tool is "&6&lThor's Pickaxe":
		stop
	"%event-block%" contains "ore"
	set event-block to air
	cancel event
	message "&c[Curse Of Build] &aSilahkan mining di &6/warp resource &aatau gunakan &6&lThor's Pickaxe &ayang dapat dibeli di &6/warp tokenshop"
```
When I start the server, this script works perfectly and it have 0 errors. But after several hours. The `stop` stopped working without any error produced. I think this is some kind of weird bug because I tried to find problem with the script but I didn't get any.

### Expected Behavior
When someone break any block that contains ore without Thor's Pickaxe, it will be replaced as an air and no drops coming out.

### Errors / Screenshots
Using the Thor's Pickaxe, the block disappeared and giving me no drops. Also there is no error in console.

### Server Information
* **Server version/platform:**      Paper 1.13.2
* **Skript version:** Latest version (2.3.6)

**Comment by bensku** [comment]
Did you reload any scripts during those few hours? Also, do you use addons?

**Comment by AsDsDD** [comment]
I have also observed some very strange behaviour about the conditions on _on break_ trigger. Console filling with errors when mining blocks.
Here's few of the errors:
https://pastebin.com/HNbzaeiz
https://pastebin.com/Hv96Y3ps

**Comment by Blueyescat** [comment]
@AsDsDD that is an issue with the Skellett addon, you need to disable hanging event from its config.

**Comment by bensku** [comment]
Just remembered that world comparisons might have some issues if you reload worlds with other plugins. Not sure if applicable here, but it *could* cause this.

**Comment by leonidesu** [comment]
Sorry for the late reply.
I managed to disable this script since it is not working properly. You could make this as a reference but I don't want to try it any further. And I'm sure this is an error because sometimes it does work but then somehow its not working properly.

I use many addons, here is the list:
```
reqn
sharksk
skellett
skemail
skore
skquery
skrayfall
skutilities
tuske
```

**Comment by leonidesu** [comment]
Update: Similar problem here. A certain permission required for a player to break the block. I give the player a temporary permission. At first it was working properly. But when the permission unset the player still could break the block. I restarted the server then the player cannot break the block anymore. There must be some error out there.
