### ISSUE TITLE
Set color of wool

### ISSUE THREAD

**Issue by Remixful** [SkriptLang/Skript#2033]
```
set {_b} to wool
set the color of {_b} to {_color}
```

```
set {_b} to wool
set the color of {_b} to red
```

Neither of these codes work. The block stays green.

```
	set {_b} to wool

	set the color of {_b} to red

	broadcast "%color of {_b}%"
```
Prints red

**Comment by ShaneBeee** [comment]
In 1.13+ wool is no longer 1 item, its 16 separate items, 1 for each color, and Im almost 100% sure cant be dyed.

**Comment by Remixful** [comment]
`set {_b} to "%{_color}% wool" parsed as item`

Thanks to someone at SkUnity for telling me how to achieve this 😄
