### ISSUE TITLE
String color bug

### ISSUE THREAD

**Issue by Remixful** [SkriptLang/Skript#2035]
```
	set {colors::*} to "red", "blue", "green", "yellow" and "purple"
	
	loop {colors::*}:
		broadcast "<%loop-value%>Hello world"
		
	loop {colors::*}:
		broadcast "<light %loop-value%>Hello world"
		
	broadcast "<light red>Hello world"
	broadcast "<light blue>Hello world"
	broadcast "<light green>Hello world"
	broadcast "<light yellow>Hello world"
	broadcast "<light purple>Hello world"
```
I've encounted a bug with color tags in strings.
![image](https://user-images.githubusercontent.com/8620268/57029653-5bfb8e80-6c10-11e9-9791-57156a1cfc45.png)

### Server Information
* **Server version/platform:**      Paper-624 (MC 1.13.2)
* **Skript version:**                2.3.6

**Comment by TheBentoBox** [comment]
I'm not sure how feasible this is to fix, it's likely due to the order in which things are done with string parsing (i.e. color tags are being parsed before variables). Will defer to devs.

**Comment by TPGamesNL** [comment]
Having formatting like this now requires [the coloured expression](https://skriptlang.github.io/Skript/expressions.html#ExprColoured), which parses all of the colours here, so this is fixed
