### ISSUE TITLE
[Licensing] Skript violates the GPL

### ISSUE THREAD

**Issue by A-n-o-n** [SkriptLang/Skript#2038]
### Description
When @Njol created Skript, he licensed under GPLv3. GPLv3 doesn't permit linking to non-GPL complient code. Minecraft is closed source and is therefore not GPL complient, yet Skript links to it anyway.

This would allow an unscrupulous contributor to submit a DMCA takedown the github and the whole project could be removed. This happened to bukkit in 2014.

The only way to resolve this would be to make every past contributor agree to license the code they contributed under a new license (I'd recommend LGPLv3), and if they don't agree, remove/rewrite their code.

Of course, you [could just ignore this like bukkit did](https://bukkit.org/threads/bukkit-is-gpl-all-non-gpl-plugins-are-breaking-copyright-law-or-worse.38412/) in 2011, but the threat would always be there...

**Comment by ShaneBeee** [comment]
""When @Njol created Skript, he licensed under GPLv3. GPLv3 doesn't permit linking to non-GPL complient code. Minecraft is closed source and is therefore not GPL complient, yet Skript links to it anyway.""
Skript doesn't like to NMS (Minecraft's code), its all linked to the Bukkit/Spigot API, which is completely open source

**Comment by bensku** [comment]
I have explicitly disallowed use of any Minecraft server code in Skript. This includes dynamically calling NMS code with reflection. Provided that an application (probably Glowstone) implements all features of Paper API, full functionality of Skript will be available. As far as I know, Skript satiesfies requirements of GPLv3; it definitely does not, dynamically or not, "link" against any proprietary code.

It is true that while APIs Skript relies on are open, closed implementations of them exist and are widely used. For example, Spigot and Oracle JDK are not fully open source. Provided that users do no redistribute anything they do not have source code for, I don't think this is against GPLv3.
