### ISSUE TITLE
Can't show colored concrete blocks (as ghost blocks) to players

### ISSUE THREAD

**Issue by kevin777787** [SkriptLang/Skript#2039]
### Description
You can't make a player see a colored concrete block.

### Steps to Reproduce
In this case the block should be a yellow concrete block, but it's a white concrete block.
`command concretetest:
    trigger:
        make player see block at player as yellow concrete`

### Expected Behavior
The block should turn yellow.

### Errors / Screenshots
There are no errors.

### Server Information
* **Server version/platform:**       git-Spigot-f09662d-51d62de MC: 1.13.2
* **Skript version:**                2.3.6

### Additional Context
Nope.

**Comment by TheBentoBox** [comment]
Can confirm.
