### ISSUE TITLE
calcExperience default function is broken

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2040]
### Description
calcExperience function is broken
It returns very weird values and even sometimes negative numbers

https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java

### Steps to Reproduce
I just used this code.
```
load:
	loop integers from 1 to 50:
		broadcast "%calcExperience(loop-number)%"
```

And I got these values.
```
7 // This is calcExperience(1)
16
27
40
55
72
91
112
135
160
187
216
247
280
315
-368 // This is calcExperience(16)
-326
-279
-227
-170
-108
-41
31 // This is calcExperience(23)
108
190
277
369
466
568
675
-2933 // This is calcExperience(31)
-2812
-2682
-2543
-2395
-2238
-2072
-1897
-1713
-1520
-1318
-1107
-887
-658
-420
-173
83 // This is calcExperience(47)
348
622
905
```

### Expected Behavior
Needed experience for a level shouldn't return negative numbers

### Server Information
* Server version/platform : Spigot 1.13.2
* Skript version : 2.3.6 (latest)

**Comment by Moderocky** [comment]
The equations in that function have BIDMAS errors.

These are what they are supposed to be:
```
level^2 + 6 × level (at levels 0–16)
2.5 × level^2 – 40.5 × level + 360 (at levels 17-31)
4.5 × level^2 – 162.5 × level + 2220 (at levels 32+)
```
(From Wiki)

Looks like a simple BIDMAS error, from what I can tell.

**Comment by Matocolotoe** [comment]
Comes from a + somehow turned into a - by the person who did the function some time ago
Just opened a pull request which should fix it

**Comment by Moderocky** [comment]
Aha, awesome :)

**Comment by Matocolotoe** [comment]
Pull request merged, closing
