### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by Joeripoes** [SkriptLang/Skript#2042]
I tried the latest version of skript but when I did /sk reload all it loaded with 140 errors and my skripts are broken for 99%. Does this plugin work on 1.14 or am I doing something wrong.

**Comment by noftaly** [comment]
1.14 is not supported yet. That's why :)

**Comment by FranKusmiruk** [comment]
1.14 was recently released, Spigot is on dev builds and Paper 1.14 isn't even out yet. We're going to support it, but you gotta wait for it.
