### ISSUE TITLE
'spawn a fish' doesn't spawn anything

### ISSUE THREAD

**Issue by Blueyescat** [SkriptLang/Skript#2046]
### Description
'spawn a fish' doesn't spawn anything, it should spawn a random fish.

### Errors
None

### Server Information
* **Server version/platform:** Paper 1.13.2
* **Skript version:** 2.3.6

**Comment by TheBentoBox** [comment]
This is somewhat an enhancement too, but yeah, we should be able to spawn supertypes to spawn a random sub-type.
