### ISSUE TITLE
skript can't check enchantment level

### ISSUE THREAD

**Issue by Command1264** [SkriptLang/Skript#2049]
### Description
skript can't checkenchantment level
### Steps to Reproduce
<!--- Steps to reproduce the problem. If applicable, add a script or code on block damage:
	if event-block is bedrock:
		if player's tool is golden pickaxe:
			if tool of the player is enchanted with efficiency 32767:
				execute console command "execute at %player% run playsound minecraft:block.stone.break ambient %player% ~ ~ ~ 1 0.8"
				damage tool by 1
				set event-block to air
				drop 1 bedrock at the event-block

### Expected Behavior
I hope it can use golden_pickaxe withefficiency 32767 to break bedrock ,but it only check had efficiency or didn't have efficiency. It didn't check level 
### Errors / Screenshots
no

### Server Information
* **Server version/platform:Spiogt 1.13.2-1a3504a-dfa7583
* **Skript version:2.3.6

**Comment by FranKusmiruk** [comment]
Please use the issue template properly.
