### ISSUE TITLE
Command Argument NPE

### ISSUE THREAD

**Issue by OfficialDonut** [SkriptLang/Skript#2050]
### Description

If the syntax `[the] <(\d*1)st|(\d*2)nd|(\d*3)rd|(\d*[4-90])th> arg[ument][s]` is used with any arg number but `1st` it will throw a NullPointerException when the script is reloaded (it throws the NPE regardless of the amount of args that the command actually has except if it has none in which case it gives the correct error `This command doesn't have any arguments`).

### Steps to Reproduce

This results in a NPE when the script is reloaded
```
command /test <text> <text>:
    trigger:
        broadcast "%2nd argument%"
```

### Errors / Screenshots

https://hastebin.com/erudeyuhan.md

**Comment by OfficialDonut** [comment]
Actually it doesn't just throw a NPE when you try to use a number greater than the amount of args but rather any arg but the first. e.g. this will also throw an NPE: 
```
command /bug <text> <text> <text>:
	trigger:
		broadcast "%2nd argument%"
```
I will edit the issue

**Comment by TheBentoBox** [comment]
Does this actually interrupt the loading of the script or is it just a "harmless" error?

**Comment by OfficialDonut** [comment]
it interrupts loading

**Comment by TheBentoBox** [comment]
oh dear
