### ISSUE TITLE
Minecart can't be compared to loop-entity

### ISSUE THREAD

**Issue by weberlepecheur** [SkriptLang/Skript#2051]
Hi,

Skript 2.3.6
Paper-588

I have an issue with minecart/boat.
When I try to compare a loop-entity with a minecart it won't work.
But for whatever reason when he compare with a spruce boat (only the spruce boat) it's works ? (Since when a boat is a minecart ? but a minecart isn't ?)
```
on vehicle exit:
	event-entity is a player
	loop all entities in radius 1 around player:
		send "%loop-entity%" to player
		# When loop-entity is a spruce boat, he pass, but not the minecart ?
		loop-entity is a minecart
		kill loop-entity
		drop minecart at player's location
		stop
```

**Comment by Matocolotoe** [comment]
(just a comment on your code) you could just kill player's vehicle as a temporary solution ?

**Comment by weberlepecheur** [comment]
I didnt know that was an expression for this, I will try when I have some time.

**Comment by Matocolotoe** [comment]
very weird

**Comment by TheBentoBox** [comment]
A temporary workaround could be using a string comparison against `"%player's vehicle%"`

**Comment by weberlepecheur** [comment]
Okay, the string comparison works, thanks for that !

Also I happen to see that skript try to compare the player vehicle with **the item type** minecart, not **the entity type**

**Comment by Wealthyturtle** [comment]
Closing this issue in favor of #2637
