### ISSUE TITLE
issue showing particles

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2052]
### Description
So I'm setting a variable to text for a user's set particle. Example, {particle::%player's uuid%} is "Smoke". When parsing this as a visual effect, it won't display at the targeted, or event-block unless done in an effect command.

### Steps to Reproduce
The main part of the script
```vbs
on break:
	if {particle::%player%} is set:
		show ({particle::%player's uuid%} parsed as visual effect) at event-block
```
I also tried replacing event-block with targeted block, no different.
However, when I run `show ({particle::%player's uuid%} parsed as visual effect) at targeted block` as an effect command, it runs fine and shows the particle.

### Expected Behavior
Shows the particle at the event-block based on the user's particle variable.

### Server Information
* **Server version/platform:** git-Spigot-f09662d-51d62de (API 1.13.2-R0.1-SNAPSHOT)
* **Skript version:**   latest

**Comment by bolleboor** [comment]
Do you have particle animations enabled in your client?

**Comment by ShaneBeee** [comment]
```vb
on break:
	if {particle::%player%} is set:   <-----
		show ({particle::%player's uuid%} <------
```
your two variables are different. 
is `{particle::%player%}` even set?
`{particle::%player%}` and `{particle::%player's uuid%}` are two VERY different variables. 
Add a debug message to see if that is even set.

**Comment by MrScopes** [comment]
> ```vbnet
> on break:
> 	if {particle::%player%} is set:   <-----
> 		show ({particle::%player's uuid%} <------
> ```
> 
> your two variables are different.
> is `{particle::%player%}` even set?
> `{particle::%player%}` and `{particle::%player's uuid%}` are two VERY different variables.
> Add a debug message to see if that is even set.

haha oops, I changed the variable without noticing. I'll check it out later on

**Comment by TheBentoBox** [comment]
No response and looks like a bug in your code. Closing.
