### ISSUE TITLE
GUI Error

### ISSUE THREAD

**Issue by bolleboor** [SkriptLang/Skript#2053]
### Description

I made a menu using Tuske and tried to open it, but when I opened the menu, it doesn't display the emerald block but it still opens the menu.

### Steps to Reproduce

Create a GUI with Tuske (Use the pikachupatch version in order to make it work in 1.12.2)
And that's it.

PikachuPatch link if needed: https://cdn.discordapp.com/attachments/399406334526750723/440604232874197002/TuSKe-PikachuPatch-v2.jar
### Expected Behavior

Opening the menu correctly and showing the emerald block.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/22412324/57568864-53177380-73ed-11e9-92e1-d159124b62fd.png)

> [13:01:27 ERROR]: #!#!
> [13:01:27 ERROR]: #!#! [Skript] Severe Error:
> [13:01:27 ERROR]: #!#!
> [13:01:27 ERROR]: #!#! Something went horribly wrong with Skript.
> [13:01:27 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [13:01:27 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
> [13:01:27 ERROR]: #!#! Here is full list of them:
> [13:01:27 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) skUtilities (https://tim740.github.io/) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SharpSK
> [13:01:27 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
> [13:01:27 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
> [13:01:27 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
> [13:01:27 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
> [13:01:27 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
> [13:01:27 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
> [13:01:27 ERROR]: #!#!
> [13:01:27 ERROR]: #!#! Stack trace:
> [13:01:27 ERROR]: #!#! java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.WeakHashMap
> [13:01:27 ERROR]: #!#! at com.github.tukenuke.tuske.util.VariableUtil.<init>(VariableUtil.java:24)
> [13:01:27 ERROR]: #!#! at com.github.tukenuke.tuske.util.VariableUtil.getInstance(VariableUtil.java:17)
> [13:01:27 ERROR]: #!#! at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:141)
> [13:01:27 ERROR]: #!#! at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54)
> [13:01:27 ERROR]: #!#! at ch.njol.skript.lang.Condition.run(Condition.java:56)
> [13:01:27 ERROR]: #!#! at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
> [13:01:27 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
> [13:01:27 ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
> [13:01:27 ERROR]: #!#! at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
> [13:01:27 ERROR]: #!#! at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
> [13:01:27 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [13:01:27 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
> [13:01:27 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
> [13:01:27 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:953)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
> [13:01:27 ERROR]: #!#! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [13:01:27 ERROR]: #!#! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
> [13:01:27 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
> [13:01:27 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
> [13:01:27 ERROR]: #!#!
> [13:01:27 ERROR]: #!#! Version Information:
> [13:01:27 ERROR]: #!#! Skript: 2.3.6 (latest)
> [13:01:27 ERROR]: #!#! Flavor: skriptlang-github
> [13:01:27 ERROR]: #!#! Date: 2019-03-03
> [13:01:27 ERROR]: #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
> [13:01:27 ERROR]: #!#! Minecraft: 1.12.2
> [13:01:27 ERROR]: #!#! Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
> [13:01:27 ERROR]: #!#! OS: Linux amd64 4.15.0-48-generic
> [13:01:27 ERROR]: #!#!
> [13:01:27 ERROR]: #!#! Server platform: Spigot
> [13:01:27 ERROR]: #!#!
> [13:01:27 ERROR]: #!#! Current node: null
> [13:01:27 ERROR]: #!#! Current item: format a gui slot [[long:12]] of the player with ([[itemtype:emerald block]] named "§7Richtrekening" with lore "Bekijk je zichtrekening / haal geld af of stort" >> ch.njol.skript.classes.data.DefaultConverters$13@3ad58312: ch.njol.skript.aliases.ItemType->org.bukkit.inventory.ItemStack)
> [13:01:27 ERROR]: #!#! Current trigger: rightclick on dirt (rightclick on [[itemtype:dirt block]]) (economie.sk, line 5)
> [13:01:27 ERROR]: #!#!
> [13:01:27 ERROR]: #!#! Thread: Server thread
> [13:01:27 ERROR]: #!#!
> [13:01:27 ERROR]: #!#! Language: english
> [13:01:27 ERROR]: #!#! Link parse mode: DISABLED
> [13:01:27 ERROR]: #!#!
> [13:01:27 ERROR]: #!#! End of Error.
> [13:01:27 ERROR]: #!#!

### Server Information
* **Server version/platform:** Spigot 1.12.2      
* **Skript version:** 2.3.6 (Latest)

**Comment by TPGamesNL** [comment]
TuSKe issues should be reported to TuSKe, you shouldn't report them here.

**Comment by TheBentoBox** [comment]
^
