### ISSUE TITLE
Cannot Load Skript

### ISSUE THREAD

**Issue by MinecraftLunitic** [SkriptLang/Skript#2054]
### Description
It is unable to load skripts.

### Steps to Reproduce
1.Write a skript
2.Do what you need to do to activate the skript
Then an error will occur in console.

### Expected Behavior
I expected it to do what my skript was supposed to do

### Errors / Screenshots
https://gist.github.com/MinecraftLunitic/57652d17eb3275bc6c35650aa1c6470e

### Server Information
Java:       1.14
 Skript Version:    2.3.6

**Comment by TheBentoBox** [comment]
Yep, the current version doesn't work on 1.14. Wait until you see a release that says it's compatible with 1.14 before reporting bugs on 1.14.
