### ISSUE TITLE
NPE when adding items as variable into database

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2056]
I get this null pointer when giving me items that have been stored (as variable) in database:
https://hastebin.com/ovabohifim.rb

Example Item:
https://i.imgur.com/tsV5BbU.png
(It has protection 3 enchantment)

Part of code that I use in the script to STORE the items:

```
						loop all items in inventory of targeted block:
							message "Added: &e%loop-item%"
							add loop-item to {kits::%{_kitname}%::items::*}

```

Part of code that I use in the script to GIVE the items:

```
loop {kits::%{_kitname}%::items::*}:
  give {_playerobject} {_item}
```

It happens as soon as the item is enchanted

**Comment by TheBentoBox** [comment]
Is this still happening on the latest release? I don't see any reason it would've been fixed but want to verify before tagging as a proper bug.

**Comment by bensku** [comment]
2.4 alpha release broke enchantment data compatibility. @FranKusmiruk may know more. This is generally not acceptable, and we need to do *something* about it before final 2.4 release.

**Comment by FranKusmiruk** [comment]
Could you publish the staktrace in another paste service such as Pastebin? Hastebin links tend to expire in a certain span of time, like this one did.

**Comment by bloggy** [comment]
https://textsaver.flap.tv/lists/2qak
https://gist.github.com/bloggy/06e34636206d375a34795cca9d285695
https://www.pastefs.com/pid/124032

**Comment by TPGamesNL** [comment]
Fixed in https://github.com/SkriptLang/Skript/commit/9a65d97985cace6a01621d3f3bddfc7a79c50435
