### ISSUE TITLE
Cannot trigger a creature click event

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#2058]
on rightclick on a pig:
	send "s"
After successfully loading the above code
I click on a pig without any hint

skript 2.3.6
This server is running Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by APickledWalrus** [comment]
I believe it is sending the message to the event-entity by default, so you need to specify for it to send to the player.

send “s” to player

**Comment by xbxymax** [comment]
> I believe it is sending the message to the event-entity by default, so you need to specify for it to send to the player.
> 
> send “s” to player

on rightclick with an clock:
	send "s" to player
	broadcast "s"
I tested it and it still doesn't work.
I started using skript2.3.6 in recent days
It's very variable and there are some problems with the asynchronous code that USES skquey in functions

**Comment by APickledWalrus** [comment]
What all addons do you have installed, are you sure the scripts are reloading properly? Make sure to check console

**Comment by xbxymax** [comment]
> What all addons do you have installed, are you sure the scripts are reloading properly? Make sure to check console

I installed a lot of add-ons, but there was no error at startup. Currently clicking on a creature does not trigger an effect, but clicking on an item does

**Comment by TheBentoBox** [comment]
Try again in the latest release, some bugs were fixed regarding entity click events.

**Comment by TheBentoBox** [comment]
No response, probably fixed, closing.
