### ISSUE TITLE
 I have a problem putting potions in the hotbar

### ISSUE THREAD

**Issue by Spygain** [SkriptLang/Skript#2060]
### Question
Hello, it's been several days that I go back on the Internet to know how to put potions in the hotbar, if you can help me I will thank you, I hope it is possible.

Thank you in advance

_____________________________________________________________________________
on rightclick on a sign:
    if targeted block is a sign:
        if line 2 is "&4&l[Barbare]":
            equip player with iron helmet
            equip player with iron chestplate of thorns 2
            equip player with iron leggings
            equip player with iron boots of feather falling 1
            set slot 0 of player to iron axe of sharpness 3
            set slot 1 of player to iron sword of fire aspect 1
	   set slot 2 of player 1 splash potion[s] of {swiftness}
*

_____________________________________________________________________________
[Auto-equip.zip](https://github.com/SkriptLang/Skript/files/3187595/Auto-equip.zip)
_____________________________________________________________________________
My server is under:
Spigot 1.13.2
Skript 2.3.6
SkQuery 3.6.5
SKRayFall 1.9.15
QuarSk 1.3.1
Skellett 1.9.6b
Skript-mirror-0.19.1
skUtilities.v0.9.2
TuSKe 1.8.2
_____________________________________________________________________________

**Comment by Matocolotoe** [comment]
> set slot 2 of player 1 splash potion[s] of {swiftness}

set slot 2 of player to splash potion of speed

**Comment by Spygain** [comment]
The "set slot 2 player to splash potion of speed", does not work, and yet I spend hours to find how to do.

I really do not understand, I'm blocking and I can not move forward, it's very embarrassing

**Comment by Matocolotoe** [comment]
That's because you use tabs **and** spaces, if you want to use one type of character, you will have to do it for the whole code (e.g. using exclusively tabs or exclusively spaces)

**Comment by Spygain** [comment]
Nevertheless, I use tabs however, bizzare, would you be able to contact you via discord or other programe to discuss it ?

**Comment by Matocolotoe** [comment]
Discord : Gio'#7098
