### ISSUE TITLE
[1.14] Leveled enchantments not working properly

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#2063]
### Description
When using effectively any expression to reference an enchant with a specific level, it doesn't work. This is most important when either spawning in an enchanted item or applying a specifically leveled enchant to an item.

### Steps to Reproduce
1. Run `give player stick of sharpness 3` or `enchant player's tool with sharpness 3`. This problem is not specific to Sharpness or level 3 enchants.

### Expected Behavior
The enchant item should be spawned in and the player's tool should be enchanted appropriately. Instead, an error is given as detailed in the screenshot below.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/6902229/57975112-9778b580-7991-11e9-8680-bd08e82d47a3.png)

### Server Information
![image](https://user-images.githubusercontent.com/6902229/57975121-afe8d000-7991-11e9-97a9-e6db6819bf51.png)

### Additional Context

I have not tested without add-ons yet so there's the off chance that it's caused by an add-on incompatibility.

**Comment by KingAlterIV** [comment]
The bug also happens to me without any addon on Paper 1.14.1

![](https://i.imgur.com/4ny581H.png)
![](https://i.imgur.com/kJOVjI7.png)

**Comment by Moderocky** [comment]
For me as well.
