### ISSUE TITLE
[1.14] New entities, visual effects, and potion effects are not registered

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#2064]
### Description
None of the entities, visual effects (particles), or status effects added in 1.14 are available. #2023 was the pull which added these but they were reverted in #2029 until Paper 1.14 was out and it was never added back in before the alpha release.

### Steps to Reproduce
1. Try to spawn in any new entities, play and new visual effects, or apply the new potion effects. An error will appear.

### Expected Behavior
The new features would be recognized.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/6902229/57975242-3d78ef80-7993-11e9-887e-6800a0add300.png)
![image](https://user-images.githubusercontent.com/6902229/57975247-47025780-7993-11e9-962c-c376fb955751.png)
![image](https://user-images.githubusercontent.com/6902229/57975249-4ec1fc00-7993-11e9-9c00-707558478342.png)

### Server Information
![image](https://user-images.githubusercontent.com/6902229/57975252-57b2cd80-7993-11e9-9a3d-d1b40ed2eb73.png)

### Additional Context
None.

**Comment by SlimeDog** [comment]
Spigot 1.13.2 final
Skript 2.4-beta1

On server start-up or skript reload
```
[05:53:54] [Server thread/ERROR]: [Skript] Can't compare an entity with 'a cat' (save-my-pets.sk, line 11: if shooter's target is a cat:')
[05:53:54] [Server thread/ERROR]: [Skript] can't understand this event: 'on damage of a cat' (save-my-pets.sk, line 26: on damage of a cat:')
```

No issue reported on Spigot 1.14.4 with Skript 2.4-beta1.
No issue reported on Spigot 1.13.3 final with Skript 2.4-alpha4.
