### ISSUE TITLE
RightClick on Smithing Table triggered by Spruce Boat

### ISSUE THREAD

**Issue by Moderocky** [SkriptLang/Skript#2066]
### Description

If you use the following event in your code:
`on rightclick on smithing table:`
It will also be triggered when right-clicking on a Spruce Boat.
Par example:
```
on rightclick on smithing table:
  player is not sneaking
  cancel event
  open smithing menu to player
```
`open smithing menu to player` is a custom skript-mirror syntax, but this should not have any bearing on events.
This code is also triggered when right-clicking a spruce boat.

### Steps to Reproduce

Make a smithing table event.
```
on rightclick on smithing table:
  cancel event
  #do something
```
Right-click on a spruce boat.

### Expected Behavior

I did not expect the spruce boat to trigger it.

### Errors / Screenshots

For your consumption, I have prepared a short movie!
https://cdn.moderocky.com/mov/smi.mp4

As you can see, my menu is also opened by the boat.
I have tested this issue after disabling my skript-mirror utils and my addon (Misk) neither of which affect events at all, and it still happens.
If you want a copy of either of these to test with, just ask.

No console errors have appeared.

### Server Information
* **Server version/platform:**       
Paper version git-Paper-28 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
[Latest, I can also reproduce on -27]
* **Skript version:**                
2.4-alpha1
[Latest, as of now]

### Additional Context

This was also an issue when I built Skript before the 2.4 alpha release, though obviously I couldn't make a bug ticket then since it wasn't a supported version.

**Comment by Blueyescat** [comment]
Works as expected with Skript 2.4-alpha3
