### ISSUE TITLE
Velocity of a vehicle in a string always returns 0.

### ISSUE THREAD

**Issue by Moderocky** [SkriptLang/Skript#2067]
### Description

If you use `"%velocity of player's vehicle%"`, it will always return `x: 0, y: 0, z: 0` even if the entity is moving at significant speed, such as a horse.
It works fine for just `"%velocity of player%"` though, from what I can tell.

I have not tested if the actual velocity returns correctly.

### Steps to Reproduce

I used this:
```
command /vc:
  trigger:
    player's vehicle exists
    message "%velocity of player's vehicle%"
    wait 2 second
    player's vehicle exists
    message "%velocity of player's vehicle%"
# allow for delay so you can move a bit after running command.
```
to test it.
Player's velocity usually returns `x: 0, y: -0.08, z: 0`, the vehicle's velocity is always 0, 0, 0.

### Expected Behavior

I expected the actual velocity of the entity to be displayed in an XYZ format.

### Errors / Screenshots

N/A
No console errors

### Server Information
* **Server version/platform:** Paper -28 1.14.1, also replicated on 1.13.2       
* **Skript version:** 2.4 ALPHA, also replicated on 2.3.6              

### Additional Context

N/A?

**Comment by Wealthyturtle** [comment]
Unfortunately this cannot really be fixed since this is handled by Spigot, and they do not wish to fix this - see https://hub.spigotmc.org/jira/browse/SPIGOT-3330 and https://hub.spigotmc.org/jira/browse/SPIGOT-3510
