### ISSUE TITLE
[1.14.1] Title and action bar problem

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#2073]
Title and action bar can't running.

![image](https://user-images.githubusercontent.com/47111280/57985228-974de800-7a6d-11e9-8796-62a102521ad4.png)
![image](https://user-images.githubusercontent.com/47111280/57985234-aaf94e80-7a6d-11e9-8267-7b72c78e1a48.png)

Paper 1.14.1#28
Skript 1.14.1 Alpha

**Comment by KingAlterIV** [comment]
Should use the template

**Comment by TheBentoBox** [comment]
These are not our [title](http://skriptlang.github.io/Skript/effects#EffSendTitle) and [action bar](http://skriptlang.github.io/Skript/effects#EffActionBar) syntaxes and you did not follow the issue template.
