### ISSUE TITLE
if lore of player's tool contains "" not working

### ISSUE THREAD

**Issue by Coolfire02** [SkriptLang/Skript#2076]
After doing some extensive testing, for some weird reason that expression isn't working at all. I've tried another form of checking and it does prove that the condition dosen't work at all

I first tried [if lore of player's tool contains "Level":]
with message "true" below to check whether it worked or not, and an else that messages "false"
and it broadcasted "False" after checking

Then I tried
set {_lore::*} to lore of player's tool
if {_lore::*} contains "Level":

also returns false.

![2019-05-20_10 40 25](https://user-images.githubusercontent.com/39693704/57995028-91e6b100-7af2-11e9-8551-9bd5e7dfa876.png)

^ That was what had happened when I tried doing
on mine:
	if player's tool is a diamond pickaxe:
		if lore of player's tool does not contain "&7 &3&l&m=-&b&l Level":
			broadcast "1"
			set {_colon} to ":"
			set {_lore::*} to lore of player's tool
			add "{basefortune:%level of fortune of player's tool%}" to the player's tool's nbt
			Add "{Unbreakable:1}" to the player's tool's nbt
			add "{BurstFortune:0.0}" to the player's tool's nbt
			set lore of player's tool to "&8&m-------------------" and "&7 &3&l&m=-&b&l Level &7&l- &3&l1 &3&l&m-=" and "&7 " and "&7 &7Energy%{_colon}% &8(&b0 &7/ &37100&8)" and "&7 &7Blocks Mined%{_colon}% &71" and "&8&m-------------------" and "&e&l> &7Fortune Boost%{_colon}% 0%%" and "&e&l> &7Token Boost%{_colon}% 0%%" and "&e&l> &7Energy Boost%{_colon}% 0%%" and "&8&m-------------------" and {_lore::*}
			set line {@BarLine} of player's tool's lore to "&7 &7&l||||||||||||||||||||||||||| &8(&70%%&8)"

and since the (if lore of player's tool does not contain "&7 &3&l&m=-&b&l Level":) condition isn't working, the lore lines keep adding those few lines over and over again.

Then I also thought it was just an issue with this particular skript and turns out, every other item that uses if lore of player's tool contains "" also does not work.

Skript addons & versions + Skript ver -
Tuske 1.8.2
SkQuery 3.6.5
skRayFall+v1.9.15
Skellet 1.9.6b
Sk-NBeeT (One of the latest versions)
SharpSK (Latest ver)
PirateSk (Unknown ver)
ExtrasSK (Unknown ver)
Skript 2.3.6

I'm running Spigot 1.12.2

**Comment by Coolfire02** [comment]
Also, that expression if lore of player's tool does not contain "&7 &3&l&m=-&b&l Level": worked fine before upgrading to 2.3.6 

I upgraded from dev36 and kappa there are aloootttt of issues xD

**Comment by TheBentoBox** [comment]
The Skript lore expression returns a list of strings with each one being a line, so writing it in this way means you're checking if any of the lines of lore are equal to that exact string. You can either instead `loop lore of player's tool` and check if each loop-value contains your string or you can parse the entire string as a list (`if "%lore of player's tool%" contains "x"`)
