### ISSUE TITLE
Event "on damge" and "on block break" doesn't work

### ISSUE THREAD

**Issue by xGlenor** [SkriptLang/Skript#2077]
Hi, i have a problem, event "on damge of item frame" doesn't work, Skript Version 2.3.6, Minecraft Version: Paper 1.13.2 My script is 

> On damage of item frame:
>     send "test" to attacker

and event "on block break:" recognizes item fram as block so with skript 

> on block break:
>     cancel event

  i cant destroy item frames

**Comment by TheBentoBox** [comment]
Duplicates #892 .
