### ISSUE TITLE
1.14 - Name of player's tool

### ISSUE THREAD

**Issue by Ydda** [SkriptLang/Skript#2078]
```
on tool change:
	if name of player's tool is "&fTest":
		broadcast "Test"
```
Skript does not understand difference between coloured and uncoloured item names, therefore the code above returns nothing.

**Comment by TheBentoBox** [comment]
> Skript does not understand difference between coloured and uncoloured item names

This is untrue. To be clear, an uncolored tool's name does not start with the `&f` formatting code, so you should just check if its name is "Test".

Also, you didn't follow the issue template, so I'll close this. If you believe this is a legitimate issue and not a misunderstanding on your part then feel free to reopen and follow the template this time. They exist for a reason.
