### ISSUE TITLE
1.14 - Location of event-block

### ISSUE THREAD

**Issue by Ydda** [SkriptLang/Skript#2079]
```
on place of inner-right east facing prismarine stairs:
	if block east of event-block is not air or water or glass:
		set event-block to inner-right east facing spruce stairs
```
Skript messes up the coordinates of the event-block causing sometimes the wrong block or two blocks to be affected when the event-block is only supposed to be one block.

**Comment by FranKusmiruk** [comment]
Please use the proper issue template when reporting to the issue tracker.
