### ISSUE TITLE
Remove (item) from player bugs out in creative

### ISSUE THREAD

**Issue by Coolfire02** [SkriptLang/Skript#2081]
Skript Version: 2.3.6

When I was bug testing my server, I noticed a bug where "Items" made in skript wouldn't get removed even after using them when in creative. When I went back into GMS, it acted fine. The server most likely isn't the issue considering we are under maintenance atm and there is almost close to zero lag involved. 

Heres the piece of code that was used in the GIF shown below

on rightclick:
	player's tool is a book named "&f&lEnchanter Script" with lore "&7Redeem this &fEnchanter Script &7and" and "&7receive an abundance of enchant books!"
	remove a book named "&f&lEnchanter Script" with lore "&7Redeem this &fEnchanter Script &7and" and "&7receive an abundance of enchant books!" from player
	play sound "mob.zombie.woodbreak" with volume 1 at player
	play sound "mob.wither.spawn" with volume 1 at player
	set {_randomsimple} to a random integer between 2 and 6
	set {_randomunique} to a random integer between 1 and 5
	set {_randomelite} to a random integer between 1 and 3
	set {_randomultimate} to a random integer between 0 and 2
	set {_randomlegendary} to a random integer between 0 and 1
	set {_randomheroic} to a random integer between 0 and 0
	play sound "mob.zombie.woodbreak" with volume 1 at player
	execute console command "/ae givercbook simple %player% %{_randomsimple}%"
	wait 1 ticks
	play sound "mob.zombie.woodbreak" with volume 1 at player
	execute console command "/ae givercbook unique %player% %{_randomunique}%"
	wait 1 ticks
	play sound "mob.zombie.woodbreak" with volume 1 at player
	execute console command "/ae givercbook elite %player% %{_randomelite}%"
	wait 1 ticks
	play sound "mob.zombie.woodbreak" with volume 1 at player
	execute console command "/ae givercbook ultimate %player% %{_randomultimate}%"
	wait 1 ticks
	play sound "mob.zombie.woodbreak" with volume 1 at player
	execute console command "/ae givercbook legendary %player% %{_randomlegendary}%"
	wait 1 ticks
	play sound "mob.zombie.woodbreak" with volume 1 at player
	execute console command "/ae givercbook heroic %player% %{_randomheroic}%"
	stop

[https://i.gyazo.com/b92d9279d37994037537951b7fffe9a5.gif](url)

**Comment by Coolfire02** [comment]
*Note after on rightclick: everythign else is tabbed once, don't know why the tabbing is removed when i posted the bug report. The code is 100% correct, no errors

**Comment by Wealthyturtle** [comment]
Closing this issue as it's not technically a bug - intended Spigot behavior (see https://hub.spigotmc.org/jira/browse/SPIGOT-1239 for more info)
