### ISSUE TITLE
RedstoneOre Unrecognizable 

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#2083]
### Description
Redstone Ore unrecognize in the latest version of skript

### Steps to Reproduce
```
on break:
  if event-block is redstone ore:
    send "hi"
```
no error but doesn't work

### Expected Behavior
it'

### Server Information
1.12.2            1.12.2
2.3.6 Skript

**Comment by TheBentoBox** [comment]
Duplicate of #1974 which should already be fixed in the 2.4 alpha releases.
