### ISSUE TITLE
1.14 - Item type does not matter when clicking an entity

### ISSUE THREAD

**Issue by Ydda** [SkriptLang/Skript#2084]
When right clicking an entity, item type does not matter.

```
on right click holding a clock:
	make console execute command "/title %player% actionbar ""&fThe clock is %time%."""
```

When clicking air or a block with say a diamond axe the above event does not fire, as expected. However, when clicking an entity, the above event does fire.
No errors show up on console.

### Server Information
* **Server version/platform:**       Spigot 1.14.1-R0.1-SNAPSHOT
* **Skript version:**                2.4-alpha1

**Comment by xbxymax** [comment]
I have the same problem today.
On the server side of 1.12.2, use 2.4
The script code has not been changed, waiting for repair

**Comment by Patbox** [comment]
I can also confirm this on Paper 1.14.2
