### ISSUE TITLE
enchant problem

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#2089]
enchant tool with sharpness 5
[14:04:22 ERROR]: Error in: enchant tool with sharpness 999
[14:04:22 ERROR]: (No specific information is available)
but,
disenchant tool
It works

This server is running Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Skript v2.4-alpha1

**Comment by ShaneBeee** [comment]
This has already been reported and fixed.
#2063
