### ISSUE TITLE
Bed occupied

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2090]
Hey. I have a suggestion. Could you please add "if bed is occupied:" condition? e.g on bed enter: if bed is occupied: cancel event send something? Bed can be occupied by player/villager. if bed is occupied by player or villager: etc.

**Comment by Blueyescat** [comment]
The item alias should work:
```vb
on bed enter:
    if event-block is an occupied bed:
```
There is no a Spigot API to get the sleeping entity, but you can do something with `entities in radius` (check whether the found entity is sleeping)

**Comment by Misio12320** [comment]
`right click:
    if event-block is an occupied red bed:
        cancel event
        message "this bed is occupied"` < this works
`right click:
    if event-block is an occupied any bed:
        cancel event
        message "this bed is occupied"` < this does not work. "any bed" does not mean all colored beds and white?


> The item alias should work:
> 
> ```vbnet
> # is this even triggered if it is occupied
> 
> on bed enter:
>     if event-block is an occupied bed:
> ```
> 
> There is no a Spigot API to get the sleeping entity, but you can do something with `entities in radius` (check whether the found entity is sleeping)

Your code does not work. I mean does not work with "if event-block is an occupied RED bed:".  It does send "this bed is occupied" and only this... Isn't better add a easier alias for this? Like suggested here and in other thread...

**Comment by Blueyescat** [comment]
is an occupied bed
is any occupied bed

**Comment by Misio12320** [comment]
Yes but v

> Isn't better add a easier alias for this? Like suggested here and in other thread...
Where I have to learn the event-block. **Also for a better look add this alias.**

**Comment by ShaneBeee** [comment]
`is an occupied any bed`
Grammatically speaking, that makes no sense.
The correct grammar would be `is any occupied bed`

the object we are comparing here is an `occupied bed` so when we are referring to any of the occupied beds, we would say `any occupied bed`

If we talk about a single occupied bed, its `occupied bed` but we also have to add a descriptor for color, ergo `occupied red bed` ... thats why its different with `any`. Its just how grammar works.

**Comment by Misio12320** [comment]
Yes but I would like to see in skript easier language by suggesting this: if bed is occupied <-- all in 1 I mean all colors are here. + 
If color of bed is red:
# do something

**Comment by Wealthyturtle** [comment]
@Misio12320 If you're requesting for nicer aliases then rename this issue, since it was initially about having a conditional to check if beds are occupied, but as Blueyescat mentioned, you can already technically do that via the alias of ``is any occupied bed``

**Comment by Blueyescat** [comment]
"is occupied" needs a separate condition which is not really important but okay

**Comment by Wealthyturtle** [comment]
@TheBentoBox In your opinion, would you rather let bed occupancy be an alias or conditional?

**Comment by ShaneBeee** [comment]
I know you asked bento, but im going to give my option.
Personally I dont think a condition should be required for something like a block state.
That would be like creating a condition for direction of blocks (if thats not already a thing), whether or not a furnace/campfire is lit, if a slab is top or bottom, if farmland is moist or not, if a fence is attached or not, snow levels, water logged, etc. You get my point.

I think theres a reason for block states, and all of the aliases take care of this, I personally see no need to create conditions for all these things.

**Comment by Wealthyturtle** [comment]
Yeah, that's my line of thought too, but I mean, it might be slightly useful if people don't know the aliases that they want exist? I don't know

**Comment by ShaneBeee** [comment]
> Yeah, that's my line of thought too, but I mean, it might be slightly useful if people don't know the aliases that they want exist? I don't know

I agree, but with that said, does that mean there should be conditions for every block state? 

> might be slightly useful if people don't know the aliases that they want exist

People already dont know 50% of the aliases exist. 
People dont know 50% of the Skript syntaxes exist. 
This is because they dont care to read the docs or look at the aliases file/repo. 
Adding more conditions won't solve this.

**Comment by TPGamesNL** [comment]
@Misio12320 Why did you reopen this?

**Comment by Misio12320** [comment]
Well, because its an enhancement and I suggested `if bed is occupied by player|villager: ` condition

**Comment by TPGamesNL** [comment]
I don't think this is possible, Bukkit only provides whether the bed is occupied: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/type/Bed.html#isOccupied()
