### ISSUE TITLE
Removing item from player crashes the server

### ISSUE THREAD

**Issue by Minityy** [SkriptLang/Skript#2092]
I have an item for when I right click it, it should be removed from the player. But it crashes the server instead.

### Steps to Reproduce

```
 command /give [<text>] [<text>]:
 	trigger:
 		if argument 1 is "item":
 			if argument 2 is "TPShard":
 				give player 1 prismarine shard of curse of vanishing named "&b&lTeleportation Shard"
                                stop

 on right click:
 	if player is holding prismarine shard of curse of vanishing named "&b&lTeleportation Shard":
		remove 1 prismarine shard of curse of vanishing named "&b&lTeleportation Shard" from the player
 		stop
```

Console error:
[crash-2019-05-22_20.40.05-server.txt](https://github.com/SkriptLang/Skript/files/3209979/crash-2019-05-22_20.40.05-server.txt)

Server Information
* **Server version/platform:** paper-37 1.14.1
* **Skript version:** 2.4-alpha1

**Comment by Ydda** [comment]
Happens when removing offhand tool as well.

**Comment by Ydda** [comment]
Crash no longer occurs in latest Spigot release. Removing offhand tool removes main hand tool though.

**Comment by Minityy** [comment]
> Crash no longer occurs in latest Spigot release. Removing offhand tool removes main hand tool though.

Still is crashing on latest version of Paper, we'll see if there is an update for that today.

**Comment by Blueyescat** [comment]
Probably related to Spigot because that way always worked before, also you should use
```vb
remove 1 from item amount of event-item
```
and no unnecessary `stop`s

**Comment by Minityy** [comment]
> Probably related to Spigot because that way always worked before, also you should use
> 
> ```vbnet
> remove 1 from item amount of event-item
> ```
> 
> and no unnecessary `stop`s

Looks like that worked! Removed the item and didn't crash the server.
