### ISSUE TITLE
inventory clicking problem

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#2093]
### Description
it works on the previous version but not in 2.4 skript bensku. Inventory click event seems broken
it doesn't work and trigger anything

### Steps to Reproduce
```
on inventory click:
	if name of clicked item contains "&a&lExchange Items":
		close player's inventory
		make player execute command "say hi"
```

### Expected Behavior
To execute the third line but doesnt.

### Errors / Screenshots
No errors. Nothing

### Server Information
* **Server version/platform:**       1.12
* **Skript version:**                2.4

**Comment by Wealthyturtle** [comment]
Cleaned up your code for you

**Comment by Wealthyturtle** [comment]
I'm unable to replicate this with Spigot 1.14.4 / Skript 2.4-beta8, can anyone else confirm this issue?

**Comment by Blueyescat** [comment]
2.4 is not a Skript version.

`clicked item` is not from Skript *because who knows*, use event-slot or clicked slot. Though this shouldn't be a problem.

Are you really sure about the issue? Looks weird, debug it like:
```vb
on inventory click:
	send "%event-slot% -- %clicked item%"
	send "%name of event-slot% -- %name of clicked item%"
	if name of clicked item contains "&a&lExchange Items":
		send "ok"
		close player's inventory
		make player execute command "say hi"
```

**Comment by Wealthyturtle** [comment]
Closing this issue as no one is able to replicate.
