### ISSUE TITLE
Several issues with Wither Skull Entities

### ISSUE THREAD

**Issue by Moderocky** [SkriptLang/Skript#2097]
### Description

Probably related to [#332](https://github.com/SkriptLang/Skript/issues/332), though the problem is more extensive than described.

I think Skript just has no idea what a Wither Skull entity is.

You can: `make player shoot a wither skull`. This works!
However, `last shot entity` is nothing.

On top of this, in the `on shoot` event triggered by this,
`shooter` is nothing.
`projectile` returns "fireball" as a string and is not the entity.

### Steps to Reproduce

```
make player shoot a wither skull
set {_s} to last shot entity
wait 1 second
kill {_s}
# won't work
```

```
on shoot:
    broadcast "%projectile%" # returns fireball
    broadcast "%shooter%" # returns <none>
```
### Expected Behavior

I expected the projectile to be a wither skull. I expected last shot entity to be a wither skull. I expected the shooter to be me, as it is in any other `on shoot` event triggered by me.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/14147477/58343209-5594b700-7e4a-11e9-9726-b8e165b19914.png)

No errors.

### Server Information
* **Server version/platform:** Paper -33, 1.14.1      
* **Skript version:** 2.4 alpha 1               

### Additional Context

I've already checked that no custom types from my addon are interfering here.

**Comment by Moderocky** [comment]
On top of this:
`make player shoot wither skull` shoots nothing, but there is no error.
`make player shoot a wither skull` works.

**Comment by TheBentoBox** [comment]
At first I thought that this was due to an aliases conflict but it looks like the aliases for the wither skull item all including "skeleton" in the middle, e.g. `wither skeleton skull`, so this is likely an internal issue.

**Comment by Wealthyturtle** [comment]
Related: #332

**Comment by ShaneBeee** [comment]
I did some testing, this issue seems to have been resolved.

As for the shooter issue, I did some testing in another plugin, this appears to be a CB/Spigot issue.
