### ISSUE TITLE
Server freeze when shutting down cause of Skript

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2100]
Paper Spigot 1.13.2
Latest Skript:  Skript v2.3.6

Planned server shut down was interrupted by Skript (error saving variables):

First we did a "kickall" from console to kick all players
then this appeared in the server log:
https://hastebin.com/vegerowoga.cs

Then the server was trying to stop the server and shutting down all plugins and it froze when it reached Skript:
[05:00:18] [Server thread/INFO]: [SkQuery] Disabling SkQuery v3.6.3
[05:00:18] [Server thread/INFO]: [skript-db] Disabling skript-db v0.1.1
[05:00:18] [Server thread/INFO]: [skDragon] Disabling skDragon v0.14.999
[05:00:18] [Server thread/INFO]: [Skript] Disabling Skript v2.3.6

After these lines nothing happend for hours. I had to kill the server and restart.

**Comment by TheBentoBox** [comment]
Is this a consistent issue? And are you still experiencing this in the 2.4 alphas?

**Comment by bloggy** [comment]
This happend once so far

**Comment by Wealthyturtle** [comment]
@bloggy In future, please use a more persistent pasting service like pastebin - your hastebin link no longer provides the crash log. Do you still encounter this issue in the past 5 months?

**Comment by Wealthyturtle** [comment]
Closing this issue as there is no real way to replicate this issue. Could be an I/O issue or something similar that caused this to happen.

**Comment by MorkaZ** [comment]
This issue still exist on 1.20.1. Console output stay like this forever:
![image](https://github.com/SkriptLang/Skript/assets/4214815/8d059276-0627-427f-9439-f6ca2fdc038f)
May be caused by MySQL database type in config (started to happen after enabling it)

**Comment by Fusezion** [comment]
I suggest creating a new issue over commenting on one from 4 years ago
