### ISSUE TITLE
Item with Lore

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#2102]
Is it possible to improve this effect?
When I use
Ice is named "xx" with the lore "xx", "xx", "xx", "xx", "xx", "xx", "xx", "xx", "xx", "xx", "xx", "xx", "xx"
Found that the script's load time was greatly extended
A single one might extend it by more than 20 seconds

**Comment by xbxymax** [comment]
The first code increases the load time by 18 seconds.
The second code USES NBT and takes less than 1 second to complete

[code]
make a gui slot 21 of arg 1 with grass block named "§b地皮命令" with lore "","§e随机领取一块地皮: §a/p a","§e领取您脚下的地皮: §a/p c","§e传送到您的地皮: §a/p h","§e传送到其他人的地皮: §a/p h 玩家名","§e设置地皮传送点: §a/p hs","§5-§f设置后使用传送命令将会来到该位置.","§e查看当前地皮信息: §a/p i","§e添加帮手: §a/p add 玩家名"," §5-§f帮手能在您的地皮内进行建筑,"," §5-§f但您离线时他们将不能建筑.","§e添加可信玩家: §a/p t 玩家名","§5-§f无论您是否在线还是离线,","§5-§f可信玩家都能在您的地皮内建筑.","§e添加黑名单: §a/p d 玩家名","§5-§f黑名单内的玩家将不能进入您的地皮","§e将玩家从您的地皮信息中移除: §a/p r 玩家名","§5-§f如果目标玩家是您地皮内的帮手或是可信玩家,","§5-§f亦或者是黑名单内的玩家,都将被移除.",""," §e使用符号&c*&e表示所有玩家"[/code]

[code]
make a gui slot 21 of arg 1 with grass block with nbt "{display:{Lore:["""",""§e随机领取一块地皮: §a/p a"",""§e领取您脚下的地皮: §a/p c"",""§e传送到您的地皮: §a/p h"",""§e传送到其他人的地皮: §a/p h 玩家名"",""§e设置地皮传送点: §a/p hs"",""§5-§f设置后使用传送命令将会来到该位置."",""§e查看当前地皮信息: §a/p i"",""§e添加帮手: §a/p add 玩家名"","" §5-§f帮手能在您的地皮内进行建筑,"","" §5-§f但您离线时他们将不能建筑."",""§e添加可信玩家: §a/p t 玩家名"",""§5-§f无论您是否在线还是离线,"",""§5-§f可信玩家都能在您的地皮内建筑."",""§e添加黑名单: §a/p d 玩家名"",""§5-§f黑名单内的玩家将不能进入您的地皮"",""§e将玩家从您的地皮信息中移除: §a/p r 玩家名"",""§5-§f如果目标玩家是您地皮内的帮手或是可信玩家,"",""§5-§f亦或者是黑名单内的玩家,都将被移除."","""","" §e使用符号§c*§e表示所有玩家""],Name:""§b地皮命令""}}"
[/code]

**Comment by TheBentoBox** [comment]
As said in #1757, this is part of a much larger issue with Skript's parser in general and should be addressed in an issue dedicated to that.
