### ISSUE TITLE
Reload files that aren't scripts

### ISSUE THREAD

**Issue by Vrganj** [SkriptLang/Skript#2103]
### Description
You can reload files that aren't scripts.

### Steps to Reproduce
```vb
/sk reload ../../../spigot.yml//
```

### Expected Behavior
Returns an error

### Errors / Screenshots
Don't have any right now.

### Server Information
* **Server version/platform:**       Spigot 1.14.1
* **Skript version:**                Skript 2.4-alpha1

**Comment by TheBentoBox** [comment]
I guess this is technically a bug? Or maybe more of an enhancement to add a sanity check?

Regardless, very low priority.
