### ISSUE TITLE
[1.14] Can't get type of block

### ISSUE THREAD

**Issue by HAHAYOUDEAD** [SkriptLang/Skript#2105]
### Description
When trying to get type of a block, the return is `<none>`

### Steps to Reproduce
```
on walk on grass:
    broadcast "%type of event-block%"
```

### Expected Behavior
I expect it to return item type of a block, like `grass block` for that example ^

### Errors / Screenshots
![mcblocktype](https://user-images.githubusercontent.com/46863862/58384527-47ca6780-7feb-11e9-8fe0-9960f3944aaf.jpg)

no errors

### Server Information
* **Server version/platform:**       1.14.1 Paper-43
* **Skript version:**                2.4-alpha1

**Comment by Nicofisi** [comment]
Does it only not work with grass or with anything?

**Comment by HAHAYOUDEAD** [comment]
Doesn't work with anything

**Comment by TheBentoBox** [comment]
This is fixed in 2.4-alpha2.
