### ISSUE TITLE
there is no slot in an on inventory click event

### ISSUE THREAD

**Issue by MorgrotSK** [SkriptLang/Skript#2108]
I have problem
I ma using skript 2.2 on minecraft 1.7.10 and i keep getting that error in title.
Here is problematic part of my code: 
`on inventory click:
	set yaml value "%{actualinv:%{_playeru}%}%slot%{pocetslotov:%{_playeru}%}-{invstranytemp:%{_playeru}%}%" from file "inventare\%{_playeru}%.yaml" to event-slot`

**Comment by SiebeDW** [comment]
1.7.10 is not supported. You could try go to Skunity or another place.

**Comment by TheBentoBox** [comment]
Only report issues here if you're using the latest version from [our releases page](https://github.com/SkriptLang/Skript/releases). We do not support versions below 1.9.
