### ISSUE TITLE
On right click on ArmorStand

### ISSUE THREAD

**Issue by krentel** [SkriptLang/Skript#2117]
### Description
I try to open a GUI by clicking on an armor stand

### Steps to Reproduce
`on rightclick on armor stand:
broadcast "click"`

### Expected Behavior
I can right-click it does not work and I have no error

### Errors / Screenshots
![téléchargement](https://user-images.githubusercontent.com/30783299/58611570-dff87300-82af-11e9-923a-e94f9b2ce5ad.png)

### Server Information
* **Server version/platform:**       Spigot-1.8.8
* **Skript version:**                Skript 2.2-dev37c

**Comment by ShaneBeee** [comment]
Skript 2.2 dev series is no longer supported on this repo.
Spigot versions below 1.9 are not supported either.

**Comment by TheBentoBox** [comment]
Not only what Shane said, but this specific issue is meant to be fixed in the 2.4 alpha releases.

All of your versions are out of date so we cannot help you. Please only report issues if using a supported server version (1.9+) with the latest Skript release.
