### ISSUE TITLE
Expansion of the cooldown feature within skript

### ISSUE THREAD

**Issue by tyhh00** [SkriptLang/Skript#2120]
Like currently, you can only do

```
command /coinflip:
	cooldown: 2 seconds
	cooldown message: &cYou can only use this command every 2 seconds
```

but it would be great if something like
```
command /coinflip [<string>] [<string>]:
	aliases: cf
	trigger:
		if arg-1 is not set:
			openCF(player)
		if arg-1 is set:
			if arg-1 is "update":
				cooldown: 2 seconds
				cooldown message: &cYou can only use it in %cooldown duration% seconds later
				openCF(player)
```

was added

**Comment by APickledWalrus** [comment]
that could be cool. Maybe keep the current settings where they’re at, and instead add an expression like,

set command cooldown to %timespan%

**Comment by TheBentoBox** [comment]
Do the [command cooldown expressions](http://skriptlang.github.io/Skript/expressions#ExprCmdCooldownInfo) not satisfy this for you? You should be able to add/set/delete the remaining time, elapsed time, and last usage time of the player's cooldown for that command within the command event. You could try to set the cooldown of the command to the highest value you want and for all cases where it should have no cooldown `set remaining cooldown to 0 seconds`.

**Comment by Vrganj** [comment]
> Do the [command cooldown expressions](http://skriptlang.github.io/Skript/expressions#ExprCmdCooldownInfo) not satisfy this for you? You should be able to add/set/delete the remaining time, elapsed time, and last usage time of the player's cooldown for that command within the command event. You could try to set the cooldown of the command to the highest value you want and for all cases where it should have no cooldown `set remaining cooldown to 0 seconds`.

Ehm.. Forgot about the `cancel cooldown`, didn't you?

**Comment by Moderocky** [comment]
Since the existing expressions already seem to support all of the requested behaviour I'm closing this.
