### ISSUE TITLE
Chest options

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2121]
### Description
Can you add an option to set an amount of rows of a chest when you open it? Or and option to rename the chest?
I mean:
`open chest with 4 rows named "Random Chest" to the player`

**Comment by TPGamesNL** [comment]
That already exists: https://skriptlang.github.io/Skript/expressions.html#ExprChestInventory (you forgot `inventory`)
You can also set them afterwards: [rows](https://skriptlang.github.io/Skript/expressions.html#ExprInventoryInfo) and [name](https://skriptlang.github.io/Skript/expressions.html#ExprName) (the 3rd `Name / Display Name` item)

**Comment by TheBentoBox** [comment]
This is already possible as has been pointed out. Please check the docs next time!
