### ISSUE TITLE
Warning for ExprItemsIn on variables doesn't get called

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#2122]
### Description
Variables of inventories can't be used in the ExprItemsIn expression. This should be implemented. Currently it's not and the warning message stating that variables aren't accepted doesn't work. The error i'm getting is a cannot understand condition. Some priority issues.
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprItemsIn.java#L72

### Steps to Reproduce
`if items in inventory {_inventory} doesn't contain air:`
`if items in {_inventory} doesn't contain air:`

### Errors / Screenshots
`[Server thread/ERROR]: can't understand this condition: '(items in inventory {_inventory}) doesn't contain air' (test.sk, line 59: if (items in inventory {_inventory}) doesn't contain air:')`

### Server Information
* **Server version/platform:** 1.14.2 Paper
* **Skript version:** 2.4-Alpha1

Known Alternative: `if {_inventory} doesn't contain air:`

**Comment by TheBentoBox** [comment]
This would be useful and as it stands is potentially confusing and limiting (if someone doesn't know about the other workaround syntax which does work, there is no alternative).

**Comment by Blueyescat** [comment]
When you actually look at the ExprItemsIn code and the warning, it is not related at all.
It is a problem with CondContains.
