### ISSUE TITLE
Date function not working/ difference between dates 

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#2123]
using the date function does not work. An internal error occurs. May as well be the difference of dates
 Skript: 2.4alpha1 Mc 1.14.2

`
command lol:
    trigger:
        set {_} to "%now%"
        set {_c::*} to split {_} at " "
        set {_d::*} to split {_c::1} at "."
        replace all "," with "" in {_d::*}
        set {_1} to date(({_d::3} parsed as integer), ({_d::1} parsed as integer), ({_d::2} parsed as integer), 19, 0)
        send "c1 %{_c::1}%"
        send "c2 %{_c::2}%"
        send "d1 %{_d::1}%"
        send "d2 %{_d::2}%"
        send "d3 %{_d::3}%"
        set {_g} to difference between {_1} and {_}
        send "%{_g}%"`

https://pastebin.com/Xx5qmBT6

Im sorry for my stupidity and not existing capability of posting a code.

**Comment by SiebeDW** [comment]
This is actually "invalid"
Since you didnt used the format. You need click on bug reportand then use the format you get.

**Comment by ShaneBeee** [comment]
> ` command lol: trigger: set {_} to "%now%" set {_c::*} to split {_} at " " set {_d::*} to split {_c::1} at "." replace all "," with "" in {_d::*} set {_1} to date(({_d::3} parsed as integer), ({_d::1} parsed as integer), ({_d::2} parsed as integer), 19, 0) send "c1 %{_c::1}%" send "c2 %{_c::2}%" send "d1 %{_d::1}%" send "d2 %{_d::2}%" send "d3 %{_d::3}%" set {_g} to difference between {_1} and {_} send "%{_g}%"`
> 

This is such a mess to read, I can't tell where one line ends and another begins.
Please use code blocks ex:
```vb
command /test:
    trigger:
        # do stuff
```

**Comment by Vrganj** [comment]
Spent like 5 minutes trying to convert this

```vb
command lol:
    trigger:
        set {_} to "%now%"
        set {_c::*} to split {_} at " "
        set {_d::*} to split {_c::1} at "."
        replace all "," with "" in {_d::*}
        set {_1} to date(({_d::3} parsed as integer), ({_d::1} parsed as integer), ({_d::2} parsed as integer), 19, 0)
        send "c1 %{_c::1}%"
        send "c2 %{_c::2}%"
        send "d1 %{_d::1}%"
        send "d2 %{_d::2}%"
        send "d3 %{_d::3}%"
        set {_g} to difference between {_1} and {_}
        send "%{_g}%"
```
