### ISSUE TITLE
SkQuery EffOptionThread

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#2124]
command /test:
	trigger:
		set {_w} to now
		send "%{_w}%" = a date var
		$ thread
		.... code
		send "%{_w}%" = <none>

function a(s:string,i:integer=0):
	send {_s} = a text var
	$ thread
	.... code
	send {_s} = <none>

skript 2.4
1.12.2

**Comment by ShaneBeee** [comment]
This issue tracker is for the plugin Skript itself, not for addons.
Please direct your issue to the addon you are having issues with.
