### ISSUE TITLE
Clicking on entities ignores itemtype

### ISSUE THREAD

**Issue by LoToRTv** [SkriptLang/Skript#2135]
Hello i have skript

on rightclick holding a player head:
	make player execute command "/profilmenu"

the command is start when it clicks on entine like villager or cow a more 
pls fix my problem ? 
* **Server version/platform:**       1.14.2 paper 65
* **Skript version:**                 2.4-alpha1

**Comment by jaylawl** [comment]
```
on rightclick holding a player head:
    clicked entity is not set
    player command "/profilmenu"
```

**Comment by TheBentoBox** [comment]
This has already been fixed via [this commit](https://github.com/SkriptLang/Skript/commit/c66673c80ef1d172832936ad2f791d3fbba39263) but it's not in a release yet and I don't think there's an issue tracking it.

**Comment by TheBentoBox** [comment]
Resolved in alpha2.
