### ISSUE TITLE
[1.14] Cat entity type is not defined/supported in 1.14

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#2136]
### Description
[OcelotData](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/entity/OcelotData.java) was updated to support 1.14 in that it no longer treats ocelots as tameable when on 1.14+, but a CatData class for 1.14 was never created at all.

### Steps to Reproduce
1. Try to `spawn a cat`.

### Expected Behavior
A cat will be spawned.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/6902229/58846016-8c897a80-864b-11e9-83d4-3a925a74c242.png)

### Server Information
* **Server version/platform:** Paper 1.14.2 (version git-Paper-58)
* **Skript version:** 2.4-alpha2

**Comment by Misio12320** [comment]
Congrats.
