### ISSUE TITLE
Can't set name of entity. Intended?

### ISSUE THREAD

**Issue by HAHAYOUDEAD** [SkriptLang/Skript#2139]
If type of object (mob) is `entity`, not `living entity`, you can't change it's name via Skript effects. Is this intended? 

```sh
import:
    org.bukkit.Bukkit
    java.util.UUID

function efromUUID(uuid: text) :: entity:
    set {_uuid} to UUID.fromString({_uuid})
    return Bukkit.getEntity({_uuid})

on rightclick with stick:
    set {_c} to clicked entity
    {_c}.setCustomName("shmek") #works
    set name of efromUUID(uuid of clicked entity) to "kek" #error #1
    set name of {_c} to "pek" #no errors, does not work


    apply swiftness 1 to {_c} #works
    apply swiftness 1 to efromUUID(uuid of clicked entity) #error #2
```

![изображение](https://user-images.githubusercontent.com/46863862/58914349-e8750180-8726-11e9-86ba-701c7ac2bc6a.png)

If it is intended, why can I apply potion effects to this entity (while it's in a variable) but cannot change it's name?

I expected Skript to take in any entity and then decide whether effect can be applied to it, it seemed logical to me.

**Comment by TheLimeGlass** [comment]
Because Entities aren't allowed to be stored in variables.
```
on rightclick with stick:
	set name of clicked entity to "Works"
```
Use it's reference for getting the clicked entity, also next time only use Skript syntax when reporting a bug, and only have Skript installed with no addons as intended in the readme.

**Comment by HAHAYOUDEAD** [comment]
I was creating a question, not a bug report, but I guess there is no difference when it's posted. 

Thank you for response, but my issue is not with the variables, but with that you can't change name of `entity`, but can of `living entity`. I understand, that you can't actually change name of any but living entity, but what if I have a function that returns entity which is not always living, but sometimes is, and I need to change it's name? (I hope it makes sense) Here is another example without using skript-mirror or variables (unless it's the same way with fuctions):

```
function efromTarget(p: player) :: entity:
    return target of {_p}

function efromTarget_living(p: player) :: living entity:
    return target of {_p}

on rightclick with stick:
    set name of efromTarget_living(player) to "test_l" #works
    set name of efromTarget(player) to "test" #the same error as #1 in original post
```

**Comment by Pikachu920** [comment]
@TheLimeGlass they absolutely are allowed to be - any object can be. They just aren't serializable and can't persist restarts.

**Comment by TheBentoBox** [comment]
This definitely doesn't make sense because non-living entities do support custom names. I actually do so regularly on my server with names on item stacks for displays and stuff.

**Comment by jaylawl** [comment]
I can confirm this issue happening, but only when an entity is residing within a local variable (didnt test with normal variables)
