### ISSUE TITLE
[1.14] Barrel inventory

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#2140]
### Description
```
		if block at loop-value is barrel:
			loop all items in inventory of block at loop-value:
```
Skript can't identify the stuff in the barrel.

### Server Information
* **Server version/platform:**       Paper #65 1.14.2
* **Skript version:**                2.4-alpha3

**Comment by ShaneBeee** [comment]
Based on your code I cant replicate this since you are only showing 2 small lines of what appears to be a much larger code.

I tested with my own code
```
!give player all items in inventory of target block
```
I tried this with both a barrel and a chest, same outcome.

I recommend if you are going to post an issue, rather than deleting the template, keep the template and fill it in with proper steps to replicate, since the code you provided, theres no way to replicate it with that code.

**Comment by OverBrave** [comment]
function scsat(p: player):
	set {_loc::*} to skutil yaml list "location.%{_p}%" from file "plugins/SCSat/data.yml"
	loop {_loc::*}:
		if block at loop-value is barrel:
			loop all items in inventory of block at loop-value:
				set {_locofbarrel} to inventory of block at loop-value-1
				set {_adet} to amount of type of loop-item in {_locofbarrel}
				set {_item} to type of loop-item
				add skutil yaml value "ayarlar.%type of type of loop-item%" from file "plugins/SCSat/ayarlar.yml" to {_fiyat}
				remove {_adet} of {_item} from {_locofbarrel}
				add ({_adet}*{_fiyat}) to {_p}'s balance``

**Comment by ShaneBeee** [comment]
Probably an issue with SkUtilities,
Its been stated in the past to report errors after testing without addons

**Comment by OverBrave** [comment]
Files and locations are already being processed. This system was working at 1.13. (Updated skript)

> ```
> on place of barrel:
> 	add location of block to skutil yaml list "location.%player%" from file "plugins/SCSat/data.yml"
> ```
> 
> ```
> every 90 seconds:
> 	loop all players:
> 		scsat(loop-player)
> function scsat(p: player):
> 	set {_loc::*} to skutil yaml list "location.%{_p}%" from file "plugins/SCSat/data.yml"
> 	loop {_loc::*}:
> 		if block at loop-value is barrel:
> 			loop all items in inventory of block at loop-value:
> 				set {_locofbarrel} to inventory of block at loop-value-1
> 				set {_adet} to amount of type of loop-item in {_locofbarrel}
> 				set {_item} to type of loop-item
> 				add skutil yaml value "ayarlar.%type of type of loop-item%" from file "plugins/SCSat/ayarlar.yml" to {_fiyat}
> 				remove {_adet} of {_item} from {_locofbarrel}
> 				add ({_adet}*{_fiyat}) to {_p}'s balance
> ```
> 
> Here skript says that things have not been detected.
