### ISSUE TITLE
error enable scripts

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#2141]
After starting the server, when I use /sk enable xx
An error pops up when you open a script.
The details are here
http://haste.athion.net/kagutadoxu.md

2.4-alpha3
1.12.2

**Comment by xbxymax** [comment]
This error appears to occur only once after the server has been restarted

**Comment by Laukage** [comment]
if you would send your code, we might be able to help you but without its kinda hard.

**Comment by xbxymax** [comment]
The content of the - var_server. Sk
There are some custom aliases for items
Such as xred bed
http://haste.athion.net/ugesapelel.sql

**Comment by TheBentoBox** [comment]
This is due to skript-mirror. You'll need to update to a 2.0 alpha release of skript-mirror which no longer causes this log handler bug.
