### ISSUE TITLE
Villager, raid suggestion.

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2145]
Hey. I have a suggestion. Could you please might add this:
1. On villager panic: (When villager get scared by raid, by zombie or entity, trigger something like kick all players or kill entity)
2. If panic is caused by (When villager get into panic by someone, trigger something. The panic mean when villager will run.)
3. Loop all entities near villager: (e.g when zombie is near to villager in e.g 50 blocks, kill the zombie.)
4. If player is in village:
5. on entry real village: ( created by Minecraft not player)
6. On raid start: (e.g send location of the attacked village)
I'm not favors the villagers just a think about them.

Edit: 
7. Isn't easier coding with "Freeze player/entity"? freeze entity ( ---->infinite time) (for 5 real seconds)

**Comment by TheBentoBox** [comment]
We cannot add any of this as none of it is supported by the Bukkit API.

**Comment by Misio12320** [comment]
can they add this? Where to request something like this?

**Comment by TheBentoBox** [comment]
I believe feature requests are to be made at the [Spigot Jira](https://hub.spigotmc.org/jira/secure/Dashboard.jspa).
