### ISSUE TITLE
1.14 - loop-value in "loop x times" effect is not recognized as an integer

### ISSUE THREAD

**Issue by antoinech2** [SkriptLang/Skript#2146]
### Description
When you use a loop x times 

> loop 3 times:

the loop-number, ou loop-value is not recognized as an integer, but as a simple number

### Steps to Reproduce
```
command /test:
	trigger:
		loop 3 times:
			send "%loop-value%" to player
			if loop-value is integer:
				send "INT"
			else if loop-value is number:
				send "NUM"
```
Result:
![image](https://user-images.githubusercontent.com/42295406/59109604-9e199d80-893d-11e9-88f2-461ad5eb0c91.png)

### Expected Behavior
Before (1.12), loop-number was an integer.

### Errors / Screenshots
I can't use the "loop-number" expression in function with integer argument.
![image](https://user-images.githubusercontent.com/42295406/59109768-f05abe80-893d-11e9-94c2-14281e505841.png)

### Server Information
* **Server version/platform:**      PaperSpigot 1.14.2 build # 55
* **Skript version:**                Skript 2.4-alpha3

**Comment by Moderocky** [comment]
This is because Skript's numbers are longs, not integers.

You can check if the number's rounded value is equal to the number itself in order to make sure it's an integer.

**Comment by Matocolotoe** [comment]
> This is because Skript's numbers are longs, not integers.
> 
> You can check if the number's rounded value is equal to the number itself in order to make sure it's an integer.

The function he used is made with Skript, so if the parameter is specified to be an integer it _is_ a long, Skript's "numbers" are doubles

**Comment by Wealthyturtle** [comment]
Closing this issue in favor of #2326.
