### ISSUE TITLE
Entity click events firing twice

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#2148]
```vb
on rightclick with an flint:
	send "hi %player%" to player```
```

^ click on a player using flint to test

Result for me:
```
hi xbxymax
hi xbxymax
```

Skript version: `2.4-alpha3`
Server version: `Paper version git-Paper-1613 (MC: 1.12.2)`

**Comment by xbxymax** [comment]
If right click item event
The player is facing an NPC or creature
It triggers two events

**Comment by TheBentoBox** [comment]
Can anyone else confirm this? A check on 1.14 would be good too.

**Comment by HAHAYOUDEAD** [comment]
Happens on 1.14. It's very inconsistent though, I tried to find some logic but no luck. All I figured is that it somehow depends on angle at which you look at entity.

**Comment by xbxymax** [comment]
There are still many problems with 1.12.2.
I added a test for the time being
Right-click when using an item
'the tagrget entity is set'
And then terminate

**Comment by Wealthyturtle** [comment]
Closing this issue in favor of #2259 since it's got more information.

**Comment by Wealthyturtle** [comment]
Re-opening this issue as this issue is better

**Comment by TPGamesNL** [comment]
Closing as I cannot replicate this issue (1.16.5, 2.6-alpha1)
(if you can, comment so)

**Comment by colton-boi** [comment]
Can replicate this issue (1.17.1, 2.6.2)

Right clicking on a player with this code:
`on right click:

    broadcast event-itemtype`
broadcasts:

With no held items:
  Single broadcast of "0 air"

With item in tool slot:
  Double broadcast of item

With item in offhand and NOT in tool slot:
  Single broadcast of "0 air"
  Single broadcast of item

With item in offhand AND tool slot:
  Double broadcast of item

Issue seems to be something to do with offhand triggering second event, unknown fix

**Comment by AyhamAl-Ali** [comment]
@colton-boi 
Share your `/sk info` please and try all that without any addons and no other scripts
I have tested your scenarios accordingly and all worked as expected
![image](https://user-images.githubusercontent.com/20037329/177221368-649df57d-0547-4f51-b33d-5ab2ef6b3404.png)
![image](https://user-images.githubusercontent.com/20037329/177221401-8ba34a51-3113-468f-8ed2-32e69dc8e2e3.png)

**Comment by colton-boi** [comment]
were you right clicking on a player?

**Comment by AyhamAl-Ali** [comment]
> were you right clicking on a player?

No I was clicking on ground

**Comment by colton-boi** [comment]
That's the problem then, this whole bug is to do with right clicking on another PLAYER/NPC

**Comment by AyhamAl-Ali** [comment]
Still can't replicate
![image](https://user-images.githubusercontent.com/20037329/177358120-8e28592f-c9d4-4560-9255-d9633c49eb13.png)
Each test was only broadcasted once
Have you tried the suggestions I mentioned above?
