### ISSUE TITLE
On right click on a skull?

### ISSUE THREAD

**Issue by Spoorloos** [SkriptLang/Skript#2149]
Hey, i want to make a security camera skript for my reallife server. But on right click doesn't work for some reason. This is the error:
![2019-06-09_09 23 23](https://user-images.githubusercontent.com/50328378/59156279-ab976a80-8a98-11e9-8185-7ff86ac3b09c.png)
i get this error to with, on right click, and on left click im using spigot 1.11.2 and this happends with any skript i download from bensku. here is my code:

[SecurityCamera.txt](https://github.com/SkriptLang/Skript/files/3269323/SecurityCamera.txt)
PS, Im dutch :D

**Comment by TheBentoBox** [comment]
You need to specify the type of head, e.g. `player head`.

In the future if you're not sure how to do something ask on the forums. This issue tracker is for reporting bugs in the plugin.

**Comment by Spoorloos** [comment]
TheBentoBox This is a bug! The whole right click and left click doesn't work!!!!!!

**Comment by Spoorloos** [comment]
on right click holding a ... doesn't work and on right click not and on left click and allllll that things

**Comment by Spoorloos** [comment]
![2019-06-09_11 28 28](https://user-images.githubusercontent.com/50328378/59157359-bdcdd480-8aa9-11e9-8603-75117480420a.png)

**Comment by Spoorloos** [comment]
see

**Comment by SiebeDW** [comment]
Its `on right click on player head:`
PS, Ik ben ook Nederlands

**Comment by Spoorloos** [comment]
ja maar heel right click en left click werkt niet

**Comment by Spoorloos** [comment]
YESSS ik heb wat gevonden! maar hoe kan ik kijken wie zijn skull

YAYY i found something on that but how can i check who's skull im clicking on?

**Comment by SiebeDW** [comment]
Not sure but maybe if you use the player's tool expression the name is in it?

**Comment by TheBentoBox** [comment]
Once again, this isn’t the place to ask for help with scripts when you don’t know how to do something. If you need help, ask on the skUnity forums or in one of the Discords. If you find a bug in the plugin, then you can report it here. If you don’t know the difference, you should ideally still ask others for help first before reporting it here. We get enough issue reports already.
