### ISSUE TITLE
Colors no longer work when they are written in upper case

### ISSUE THREAD

**Issue by andrei923** [SkriptLang/Skript#2152]
### Description
Not sure if is a bug but the colors no longer work when they are written in upper case (in 2.3.6 & older they work)

### Steps to Reproduce
```
command color:
    trigger:
        broadcast "<red>test"
        broadcast "<RED>test"
```

### Expected Behavior
to work in upper case too

### Server Information
* **Server version/platform:**       spigot 1.13.2
* **Skript version:**   2.4-alpha3

**Comment by TheBentoBox** [comment]
Gonna put this as medium since it's a breaking change assuming you're correct that it used to work.
