### ISSUE TITLE
Remove item doesn't work in function

### ISSUE THREAD

**Issue by leonidesu** [SkriptLang/Skript#2153]
### Description
Just try something simple like this
```
command /testinv:
	permission: skript.admin
	trigger:
		anjing(player)
		
function anjing(p: player):
	remove 8 of end crystal named "&bShard" from inventory of {_p}
```
and its not working as its used to be.
I've tried 
```
command /testinv:
	permission: skript.admin
	trigger:
		remove 8 of end crystal named "&bShard" from inventory of player
```
and its working. so the function must be the problem.

### Steps to Reproduce
```
command /testinv:
	permission: skript.admin
	trigger:
		anjing(player)
		
function anjing(p: player):
	remove 8 of end crystal named "&bShard" from inventory of {_p}
```

### Expected Behavior
The command is intended to work properly by removing 8 end crystals named "&bShard" from player's inventory

### Errors / Screenshots
There was no error in console while executing the command

### Server Information
* **Server version/platform: 1.13.2 Paperspigot 628**       
* **Skript version: 2.3.6**

**Comment by TheBentoBox** [comment]
We only accept bug reports for the latest version of Skript.
