### ISSUE TITLE
Cancel first attack suggestion

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2154]
Hello. I have a suggestion. What do you think about "cancel first damage" its about when player hit player the first hit going to be canceled, the next one going to damage.
Like e.g on first join player must hit something 10 times to damage players. After the 10 0 damage hits the hit will damage. if player haven't hit (entity) 10 times: cancel damage

**Comment by ShaneBeee** [comment]
This doesn't really sound like a Skript "feature" as much as it sounds like something you can just code with what Skript already has to offer.

Skript generally tries to integrate things from the BukkitAPI, rather than creating features which can be done within your scripts.

**Comment by Blueyescat** [comment]
> Skript doesn't store data itself
It does, like last spawned entity and command cooldowns and much more

**Comment by TheBentoBox** [comment]
This isn't something Skript should implement. Skript mostly just acts as a utility interface with the Bukkit API. This would be very easy to implement yourself and that is what you should do if you need it.
