### ISSUE TITLE
[SUGGESTION] Code Section Registration (Similar to Class Register with Java)

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#2159]
### Description

I always wanted to make some special codes for special cases but in all times some events would be called for nothing because the special case is not met which might also cause some lag if the event is being called too many times for nothing. So to avoid this thing and to reduce the amount of lag that might be caused due to the un-needed codes in some cases this feature comes in place.

With Java you can put some codes in a class and choose to register it if it meets some conditions so for example you can register a class if the user is running MC 1.12.2 or lower.

**How would it be used with Skript?**

```
options:
	enable-damage-events: false

on load:
	if {@enable-damage-events} = true:
		#register [code] section[s] %code sections% to skript
		register code sections damage events and pvp events to skript


code section damage events:
	on damage:
		# some codes
		# This is just a code that will only be used if it is registered with "on load" event

code section pvp events:
	on damage of a player:
		# some codes
		# This is just a code that will only be used if it is registered with "on load" event
```

so with this you don't have to do this that might also cause some lag due to calling events [too many times] for nothing.
```
on damage:
	{@enable-damage-events} = true
	# some codes
	# this will be called for nothing
```

Some others might have more ideas to use this feature for better purposes but this was just a simple example.

Thanks.

**Comment by FranKusmiruk** [comment]
What you're asking for is partly possible with functions, the registering functionality would be feasible if #1149 is implemented.

Either way, stuff like this is kind of problematic to implement right now, and the fact that it is a feature addons such as MundoSK offers leads me to think it's not something worth implementing on vanilla.

That said, I am closing the issue.
