### ISSUE TITLE
Request: switch statements

### ISSUE THREAD

**Issue by yyeerai** [SkriptLang/Skript#216]
You can add Switches and for statement?

**Comment by bensku** [comment]
For statement... Can't you just use loops?

Switch statement might be useful, but definitely not high priority. Even some general purpose languages (Lua) do not have switches, and even Java didn't have String switch until version 7.

**Comment by JKGamerxD** [comment]
And if you want the Switches there are addons like MundoSK that has it.

**Comment by TheBentoBox** [comment]
Not sure if you still want support for this Bensku; for loops clearly don't need to be added as normal loops are essentially the same in many situations. If you'd like I could try to speak to the MundoSK developer to see if he'd be interested in making a PR to get his switch statements integrated into vanilla Skript. They work very well.

**Comment by Pikachu920** [comment]
@Snow-Pyon I would be willing to add this, I just wonder how. Include TuSKe's scope tools in skript and remove its need for reflection? What about the logging issues that come with parsing a trigger? that's something I do not want to make an actual proper fix for.

**Comment by Snow-Pyon** [comment]
@Pikachu920 I wouldn't want another trigger section in Skript right now seeing how harcoded the current ones are, if you were to add this you would have to do it in the same way Skript does with the loop statements. Hence why this is lowest priority, as it needs of a proper API for it before we even think about implementing it.

That's just what I think about it though, if @bensku differs on my opinion then go ahead.

**Comment by bensku** [comment]
You can certainly try, but I would recommend proposing how exactly you'd do it *before* you start coding. Otherwise, time might be wasted if it cannot be merged for some reason.

**Comment by FranKusmiruk** [comment]
Closing in favor of #4000
