### ISSUE TITLE
Command Block Command Sender

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2160]
### Description

Currently, when you make a command like

```
command /example:
    trigger:
         broadcast "%command sender's location%"
```

and execute the command `/example` in a command block, the location broadcasted will return with a `<none>`

My suggestion is to add a test for whether or not command blocks are executing the command, and to return the location of the executing command block should the command sender's location be used

**Comment by Blueyescat** [comment]
Possible to implement, just a CommandSender -> Block converter.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/command/BlockCommandSender.html

It would be also nice to make event-block work for command blocks, not sure if it will work with the converter.

Already works for command block minecarts.

**Comment by Wealthyturtle** [comment]
@Blueyescat I was trying to implement this via registering a new converter in DefaultConverters.java, with the following code
```
		// CommandSender - Block
		Converters.registerConverter(CommandSender.class, Block.class, new Converter<CommandSender, Block>() {
			@Override
			@Nullable
			public Block convert(final CommandSender s) {
				System.out.println("Request: CommandSender -> Block");
				if (s instanceof BlockCommandSender) {
					System.out.println("Successful Conv");
					return ((BlockCommandSender) s).getBlock();
				}
				System.out.println("Failed Conv");
				return null;
			}
		});
```
But after running the above Script, this converter is not called at all... any idea?
