### ISSUE TITLE
on book sign event-itemstack unavailable

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2162]
### Description

When using the `on book sign` event, supposedly there should be an event value for getting the book, via `event-itemstack`, but the event value does not exist

### Steps to Reproduce

```
on book sign:
    set {_book} to event-itemstack
```

### Expected Behavior

For `event-itemstack` to return the book that is being signed

### Errors / Screenshots

```
Can't understand this expression: 'event-itemstack' (test.sk, line 2: set {_book} to event-itemstack')
```

### Server Information
* **Server version/platform:**       Spigot 1.14.2
* **Skript version:**                2.4.1-alpha3

### Additional Context

Similar to #2151 ?

**Comment by TheBentoBox** [comment]
Technically the [PlayerEditBookEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerEditBookEvent.html) doesn't support getting the item as far as I can tell, just the meta. It has a `getSlot()` but it returns the slot index and is deprecated so we shouldn't use it.

You could kinda get around this limitation by getting the event's player and checking which item they're holding (main hand or off hand) is a book and quill and return that, though you could also do that yourself as a user. I'm not really sure Skript itself should be handling that sort of stuff but I'll leave it up to the devs.

**Comment by Wealthyturtle** [comment]
But according to skUnity's documentations, there should be an event value for the itemstack available. In this case, Skript flat out doesn't recognize its existence?

**Comment by TheBentoBox** [comment]
The skUnity docs are incorrect.

**Comment by TheBentoBox** [comment]
Also not sure what you mean by this:

> Regardless of what data type it's returning, it should still be able to fit into a variable

What is the "it's" that is returning a data type? The literal Bukkit event itself doesn't have this data available. We cannot implement it directly without a bit of a goofy hack.

**Comment by Wealthyturtle** [comment]
I meant to say that event-itemstack truly didn't exist as mentioned in the docs, but since the docs are incorrect then that would make sense... lol

**Comment by Pikachu920** [comment]
shouldn't player's tool work?

**Comment by TheBentoBox** [comment]
You can be editing a book from your offhand tool.

**Comment by Runakai1** [comment]
But it’s True, event-itemstack is listed in lots of events as a value tho it isn’t implemented, event-item only does work. It was(or still is) in the inventory click event

**Comment by Wealthyturtle** [comment]
Perhaps someone should make a list of broken event-itemstack syntaxes from the docs? Seems quite common

**Comment by Blueyescat** [comment]
`ìtemstack` magically stopped working.

**Comment by FranKusmiruk** [comment]
We could change how that's done internally and it should work again.

**Comment by Wealthyturtle** [comment]
Just re-visited this issue and it seems that it's not entirely wrong, you can use ``event-item`` instead of ``event-itemstack`` and everything will work fine
