### ISSUE TITLE
do something 20 times.

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2164]
Hey. I have a suggestion. Could you might add please something like "20 times" e.g play sound"" with volume 10 at player 20 times. this 20 times in this same second or like send "" to player 20 times. Isn't it easier than loop or something what doing this?

**Comment by ShaneBeee** [comment]
I vote no on this, since:
```
send "blah" to player 20 times
```
is exactly the same as
```vb
loop 20 times:
    send "blah" to player
```
All you are really saving is **a** line and "loop"
In my opinion this would not make things any easier really!

**Comment by Runakai1** [comment]
I agree with Shane. Also you can add multihull effects under the loop without having to write `20 times` at the end all the time.

**Comment by Misio12320** [comment]
Well. Good idea next time I will use something like this... Thanks

**Comment by Blueyescat** [comment]
No, see the Ternary and Default Value expressions and the Do If effect? They are and this is for easier and shorter codes. This can also have an 'interval' feature. But yeah, you wouldn't have ability to run multiple effects because long parse time.
