### ISSUE TITLE
Errors with "leashes"

### ISSUE THREAD

**Issue by JaydenJinx** [SkriptLang/Skript#2166]
ERROR: https://hastebin.com/vanavenaja.cs
CODE: https://hastebin.com/ulopufijem.coffeescript

Spigot 1.14.2
Skript 2.4-alpha3

**Comment by Blueyescat** [comment]
Please don't use hastebin in issues next time, it doesn't work really well.

**Comment by JaydenJinx** [comment]
Noted. Will do. Sorry about that.
