### ISSUE TITLE
Item data not clearing in loop

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2167]
### Description

When re-creating an `{_item}` variable in each iteration of a loop, the `{_item}`'s previous data (lore, name, etc.) are not cleared and still remain

### Steps to Reproduce

```
command /test:
    trigger:
        set {_test::1} to "abc"
        set {_test::2} to "123"
        set {_test::3} to "xyz"
        loop {_test::*}:
            set {_item} to paper
            send "Previous lore = %{_item}'s lore%, Previous name = %{_item}'s name%"
            set line 1 of {_item}'s lore to loop-value
            set {_item}'s name to loop-value
```
### Expected Behavior

When `{_item}` is re-declared, all its prior data should be cleared

### Errors / Screenshots

Output of `/test`:
```
Previous lore = <none>, Previous name = <none>
Previous lore = abc, Previous name = abc
Previous lore = 123, Previous name = 123
```
Previous lore/name still persists

### Server Information
* **Server version/platform:**       Spigot 1.14.2
* **Skript version:**                2.4.1-alpha3

**Comment by TheBentoBox** [comment]
I'm not sure if this is a new issue but regardless this seems really confusing and could cause bugs which are silent and very hard to track down.
