### ISSUE TITLE
pitch and yaw error in 1.14.2 minecraft version (Skript 2.4 alpha 3)

### ISSUE THREAD

**Issue by OPEN900** [SkriptLang/Skript#2170]
set {_a} to player's location
set {_a}'s yaw to 1
set {_a}'s pitch to 1
teleport player to {_a}

pitch and yaw are doesn't change

**Comment by Blueyescat** [comment]
It works fine. Make sure you don't use dead addons, try without any addon and try exactly the same code...

**Comment by FranKusmiruk** [comment]
Please use the issue template when reporting to the issue tracker.

**Comment by Blueyescat** [comment]
They provided enough info.
