### ISSUE TITLE
Skript randomly broke

### ISSUE THREAD

**Issue by trent304** [SkriptLang/Skript#2172]
### Description

Whenever I do any commands that I have made with skript none of them work for some reason. I even reuploaded a backup that works perfectly with the old Jar's aswell still nothing. 
### Steps to Reproduce

Do litterly any command that is setup in skript 
### Expected Behavior

No command found, when reloading a unexpected error report 
### Errors / Screenshots

https://gyazo.com/22ced9e9c6f1267214796a8be87a8303
 https://pastebin.com/cmHiYvss https://pastebin.com/K6XtWJV1

### Server Information
* **Server version/platform:**        1.8.8
* **Skript version:**                 Skript-oldparser

### Additional Context
 Those two pastebins are seprate problems but both started right around the same time

**Comment by ShaneBeee** [comment]
"Skript version: Skript-oldparser" <-- Im not even sure which Skript version that is.

Anyways, Skript 2.3+ does not work on 1.8.8, therefor you are using an old, outdated version of Skript that is not supported here.

**Comment by Pikachu920** [comment]
@ShaneBeee it's a really, really old version from back in the day when bensku was making a new parser... new releases were released in two forms, one with the original parser and one with his

@trent304 we only accept issues on supported Minecraft versions and the latest Skript version

**Comment by trent304** [comment]
What is the download for build 2.2 can't really find it

**Comment by ShaneBeee** [comment]
https://github.com/SkriptLang/Skript/releases/tag/dev36
