### ISSUE TITLE
Multi-line comments

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2180]
### Description

At the moment, you can only use single-line comments (declared with #) that will make any text after it part of a comment. My suggestion is to be able to "terminate" a comment, e.g.
```
set {_i} to dirt named "&6Dirt" #TODO# enchanted with unbreaking 1
```
Which would allow for comments to be inserted within lines of Skript, rather than on a separate line or to the end of the line

Similarly, multi-line comments would also solve this issue, and also allow people to comment out large chunks of Skript.

Although the parsing for this may be problematic, I think it'll certainly help out Skript users working on large projects :)

**Comment by FranKusmiruk** [comment]
>Although the parsing for this may be problematic
It might not be the case but still, do we really need this? There's a ton of languages that handle comments just like Skript does and I've never seen it as a big deal.

What I am saying is just that I am unable to see the advantages of this, if anything, multi-line comments would be a more viable option.

**Comment by Wealthyturtle** [comment]
Yeah, multiline comments would work great too lol

**Comment by Moderocky** [comment]
Personally, I do see having an end-comment-tag as being a useful feature but would much prefer multi-line support for comments as well.
It's a pain to have to comment every line with a `#` when you want to comment out a section.

**Comment by TheBentoBox** [comment]
Will mark as an enhancement for the sake of multiline comments.

**Comment by Forcinq** [comment]
can we still do this :)
