### ISSUE TITLE
Banner aliases don't work

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2183]
### Description
Can't check for banner blocks using aliases
The same error occurs when using `any wall banner` or `any standing banner`

### Steps to Reproduce
```
on right click:
    clicked block is set
    clicked block = any banner
    send "that's a banner"
```

### Errors / Screenshots
Returns: `Can't understand this condition: [...]`
Functional workaround:
```
"%clicked block%" contains "banner":
```
No console errors

### Server Information
* **Server version/platform:**       Paper 1.13.2
* **Skript version:**                2.3.6

**Comment by TheBentoBox** [comment]
Already fixed [here](https://github.com/SkriptLang/skript-aliases/commit/06b32df839f3a9358371343f95ea7d4638da6999) and cannot reproduce on 2.4-alpha3. Update your aliases.

**Comment by jaylawl** [comment]
Hey thanks for the info!
As far as i knew, it wasn't possible to update the aliases anymore - is there something i'm missing or did you mean to tell me to update skript completely instead?

**Comment by ShaneBeee** [comment]
Someone correct me if im wrong, but all you have to do is download the aliases repo, unzip it, throw it in your Skript folder and rename it `aliases-english` and TAADAA you have new aliases :) (restart your server of course - or I think you can run `/sk reload aliases`)

**Comment by jaylawl** [comment]
That worked! :) Had to rename to just `aliases`, but anyway thank you!

**Comment by ShaneBeee** [comment]
> That worked! :) Had to rename to just `aliases`, but anyway thank you!

You're welcome. I knew it was something along those lines, I just always for it it. Glad you figured it out!

**Comment by bensku** [comment]
I'm terribly late, but downloading and renaming to aliases.zip should also do the trick.
