### ISSUE TITLE
Teleport causes don't work

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2185]
### Description
Teleport causes seemingly can't be understood by the parser, all of them fail

### Steps to Reproduce
Simply put this in a skript and reload it
```
on teleport:
    teleport cause = ender pearl
    teleport cause = command
    teleport cause = plugin
    teleport cause = nether portal
    teleport cause = end portal
    teleport cause = spectate
    teleport cause = gateway
    teleport cause = chorus
    teleport cause = unknown
```

### Errors / Screenshots
https://snag.gy/7voauh.jpg

### Server Information
* **Server version/platform:**      paper 1.13.2
* **Skript version:**                2.3.6

**Comment by TheBentoBox** [comment]
Can confirm on 1.14 with 2.4-dev3.

**Comment by ShaneBeee** [comment]
This is a duplicate of #1832

**Comment by TheBentoBox** [comment]
Oops, thanks.
