### ISSUE TITLE
Spawn reasons comparisons

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2186]
### Description
none of the spawn reasons can be parsed correctly

### Steps to Reproduce
Simply put this in a skript and reload it
```
on spawn:
    spawn reason = natural
    spawn reason = jockey
    spawn reason = chunk generation
    spawn reason = mob spawner
    spawn reason = egg
    spawn reason = spawn egg
    spawn reason = lightning
    spawn reason = built snowman
    spawn reason = built iron golem
    spawn reason = built wither
    spawn reason = village defense
    spawn reason = village invasion
    spawn reason = breed
    spawn reason = slime split
    spawn reason = reinforcements
    spawn reason = nether portal
    spawn reason = dispense egg
    spawn reason = infection
    spawn reason = cured
    spawn reason = ocelot baby
    spawn reason = silverfish reveal
    spawn reason = mount
    spawn reason = trap
    spawn reason = ender pearl
    spawn reason = perching
    spawn reason = drowned
    spawn reason = shear
    spawn reason = customized
    spawn reason = default
```

### Errors / Screenshots
(i made a typo in the test skript here but you get the idea)
https://snag.gy/jEPAMp.jpg

### Server Information
* **Server version/platform:**       paper 1.13.2
* **Skript version:**               2.3.6

**Comment by TheBentoBox** [comment]
Can confirm I've run into this and it still occurs on 2.4-alpha3.

**Comment by ShaneBeee** [comment]
Closing this in favour of #2637 
There are many issues on the tracker all stemming from this one big issue, so I wanted to condense this into one larger issue.
