### ISSUE TITLE
Function return & contains-condition issue

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2187]
### Description
When returning several objects via a function and directly checking if the function contains a certain object, the result will always be false.
However when setting the function returns to a list variable, the contains-condition works correctly.

### Steps to Reproduce
```
function testy() :: texts:
    return ("a", "b", "c")

command /test:
    trigger:
        
        if testy() contains "a":
            send "##1: yes"
        else:
            send "##1: nope"
            
        set {_list::*} to testy()
        if {_list::*} contains "a":
            send "##2: yes"
        else:
            send "##2: nope"
```

### Server Information
* **Server version/platform:**      paper 1.13.2
* **Skript version:**               2.3.6

Additional stuff:
When setting the function to return integers, the line `if testy() contains (1, 2, 3):` will refuse to parse. Using objects as a return parses correctly, but still doesn't let the condition function properly.

**Comment by TheBentoBox** [comment]
Can confirm on 1.14 with 2.4-dev3. Gonna put as medium since this is both a pain in the ass and can cause annoying bugs since it throws no errors at all.

**Comment by HYPExMon5ter** [comment]
Was fixed in beta6
