### ISSUE TITLE
[SUGGESTION] Private Functions

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#2188]
### Description

Sometimes I use the same function name in different scripts, this causes functions to get messed up with 2 diff codes. 

We should be able to do `private function test():` that only registers for the current script.

Thanks.

**Comment by andrei923** [comment]
mayve `local function test():`

**Comment by TheBentoBox** [comment]
Sounds super useful!

**Comment by bensku** [comment]
I think even making functions local by default and adding 'global' functions might work. Or just namespaces for everything.

**Comment by AyhamAl-Ali** [comment]
> 
> 
> I think even making functions local by default and adding 'global' functions might work. Or just namespaces for everything.

That would be even better and more useful.

**Comment by jaylawl** [comment]
@bensku please, absolutely do not make functions local by default. That's just shit-tons of unneccessary busy work to change for people that have lots of functions

**Comment by AyhamAl-Ali** [comment]
> @bensku please, absolutely do not make functions local by default. That's just shit-tons of unneccessary busy work to change for people that have lots of functions

True, if functions will become local by default everyone will have to recode, I think global by default is better.

**Comment by Wealthyturtle** [comment]
Yes, that would be a breaking change so that probably won't be happening.

**Comment by AyhamAl-Ali** [comment]
Any progress on this?

**Comment by FranKusmiruk** [comment]
> Any progress on this?
It isn't a priority, PRs are welcome though.

**Comment by LowScarlet** [comment]
and don't forget how to use local function to other file.sk
```vb
import:
  from file.sk import local function test
  *Optional
  from file.sk import all local function
  import all local function from file.sk as hello

on load:
  file.test()
  hello.test()
```

**Comment by Moderocky** [comment]
> and don't forget how to use local function to other file.sk

No. The point of local functions is to be local to a file. There would not be some extra syntax to use them in other files, since this defeats the purpose.

**Comment by LowScarlet** [comment]
> > and don't forget how to use local function to other file.sk
> 
> No. The point of local functions is to be local to a file. There would not be some extra syntax to use them in other files, since this defeats the purpose.

That kind of thinking is what keeps the script from developing later

**Comment by LowScarlet** [comment]
> > and don't forget how to use local function to other file.sk
> 
> No. The point of local functions is to be local to a file. There would not be some extra syntax to use them in other files, since this defeats the purpose.

That kind of thinking is what keeps this project from developing in the future
