### ISSUE TITLE
Scripts wont run/load

### ISSUE THREAD

**Issue by redstonermoves** [SkriptLang/Skript#2191]
Console --> https://pastebin.com/raw/WvWFHiXf
Script(s) --> https://pastebin.com/raw/bfcDBZws
Link to script(s) --> https://www.spigotmc.org/resources/ban-gui.68567/
Server Version --> 1.14.2
Full server download --> https://cdn.discordapp.com/attachments/592365694109089841/592366258792562717/Whats_going_on.zip

**Comment by TheBentoBox** [comment]
We only accept bug reports for the latest Skript version.
