### ISSUE TITLE
Timespan not parsing when using variables

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2193]
### Description

Skript can parse timestamps when the values are given directly, e.g. ```5 seconds```, but is unable to do so when the direct value is replaced with a variable, e.g. ```{_x} seconds``` or ```arg-1 seconds```

### Steps to Reproduce

```
command /test <number>:
    trigger:
        set {_t} to arg-1 seconds
        set {_n} to arg-1
        set {_t} to {_n} seconds
```

### Expected Behavior

For the timespan to be properly parsed

### Errors / Screenshots

```
Line 3: Can't understand this expression: 'arg-1 seconds' (script.sk, line 3: set {_t} to (arg-1) seconds')
Line 5: Can't understand this expression: '{_n} seconds' (script.sk, line 5: set {_t} to {_n} seconds')
```

### Server Information
* **Server version/platform:**       Spigot 1.14.2
* **Skript version:**                2.4.1-alpha3

**Comment by TPGamesNL** [comment]
Alternatively you can use "%arg-1% seconds" parsed as a timespan, but an expression like `%number% (seconds|minutes|etc)` would be nice

**Comment by Wealthyturtle** [comment]
Didn't know you could do that... oops

**Comment by FranKusmiruk** [comment]
@TPGamesNL that would probably end up breaking more than what it solves, parsing it is the proper solution to the issue.
