### ISSUE TITLE
Pattern Regexes

### ISSUE THREAD

**Issue by Vrganj** [SkriptLang/Skript#2195]
### Question

I've been wondering do Skript patterns get converted to regex when parsing? If so, could you tell me how?

**Comment by TPGamesNL** [comment]
I don't think this is the case, this seems to be the method used to analyze patterns: https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/lang/SkriptParser.java#L1478 and https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/lang/SkriptParser.java#L1478 to compare them to syntax (I could be wrong, don't take my word)

**Comment by Pikachu920** [comment]
they don't get converted to regex

**Comment by Vrganj** [comment]
Okay, but does anyone have any good-ish ways of converting patterns to regex?

**Comment by Pikachu920** [comment]
skript patterns are more complex than regex allows for in any sane form

**Comment by Vrganj** [comment]
The parser seems to work fine by converting patterns into regex, but it isn't too great at it

**Comment by Pikachu920** [comment]
the skUnity parser? it doesn't convert them to regex, it uses the actual parser

**Comment by Vrganj** [comment]
I'm talking about the highlighting, if you look at the code you'll see

**Comment by Pikachu920** [comment]
highlighting is a totally different beast that is easier to tackle. actually parsing scripts with regex is much harder and not very practical

**Comment by Vrganj** [comment]
Well I'm trying to use it for highlighting anyway, but haven't found a good way to convert it yet
