### ISSUE TITLE
UUID in default variables

### ISSUE THREAD

**Issue by Vrganj** [SkriptLang/Skript#2196]
### Description

You can't use UUID's in variables

### Steps to Reproduce

```vb
variables:
    {test::%player%} = 5 # works
    {test::%uuid of player%} = 5 # doesn't work
```
### Expected Behavior

It's supposed to work the same.

### Errors / Screenshots

```
Line 3: Can't understand the type 'uuid of player' (script.sk, line 3: {test::%uuid of player%}: 5# doesn't work')
```

### Server Information
* **Server version/platform:** Paper 1.14.2      
* **Skript version:** Skript 2.4-alpha3

**Comment by Wealthyturtle** [comment]
Can confirm that ```%player's uuid%``` also doesn't work

**Comment by Pikachu920** [comment]
The variables section doesn't support expressions - it's meant for setting simple variables.

**Comment by Vrganj** [comment]
It's kind of weird that it supports players, but not UUID's

**Comment by Pikachu920** [comment]
It doesn't support players, if you look at what variable actually gets set there it's something like {test::<player>}

**Comment by Vrganj** [comment]
Explain this
https://github.com/SkriptLang/Skript/blob/master/src/main/resources/scripts/kill%20counter.sk

**Comment by Pikachu920** [comment]
[Look at where it's implemented](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/ScriptLoader.java#L572). There's nothing special for dealing with player variables or expressions in specific, only classinfos.
