### ISSUE TITLE
Where is the skript plugin project? Helpme0.0

### ISSUE THREAD

**Issue by Leo9487** [SkriptLang/Skript#2199]

**Comment by FranKusmiruk** [comment]
https://github.com/SkriptLang/Skript/releases

Also, please use the [forums](https://forums.skunity.com) or one of the various Discord servers for this kind of questions. The issue tracker is only to report bug or feature requests.

**Comment by ShaneBeee** [comment]
"Where is the skript plugin project? " ??? Um, its right here?!?! You are on the page for the project.
