### ISSUE TITLE
Spectator target doesn't work in 2.3.1 of skript

### ISSUE THREAD

**Issue by Apex142** [SkriptLang/Skript#2201]
**DESCRIPTION**

I use 2.3.1 of skript, and  spectator target doesn't work 

**STEPS TO REPRODUCE**
set **spectator target of player to (arg-1 parsed as player)** 
or 
**set player's spectator target to arg-1 parsed as player**

**ERROR**

>sk reload mutation
[23:00:32 INFO]: [Skript] Reloading mutation.sk...
[23:00:33 WARN]: a types.citizen cannot be saved, i.e. the contents of the variable {mutation::%the player%.npc} will be lost when the server stops. (mutation.sk, line 5: set {mutation::%player%.npc} to the last created citizen')
[23:00:33 ERROR]: Can't understand this condition/effect: set spectator target (mutation.sk, line 8: set spectator target')
[23:00:33 INFO]: [Skript] Encountered 1 error while reloading mutation.sk!

### SERVER INFORMATION
* **Server version/platform: Minecraft 1.12.2**       
* **Skript version: 2.3.1**

**Comment by Blueyescat** [comment]
set spectator target

is not equal to 

set spectator target of player to (arg-1 parsed as player)

**Comment by Apex142** [comment]
So i use what please ?

**Comment by ShaneBeee** [comment]
To add to what Blue said, I recommend updating to a supported version of Skript, such as at least 2.3.6.
Issues are not accepted for outdated versions (if something here was actually broken, it may have been fixed in the many versions that have come out since 2.3.1)

**Comment by Apex142** [comment]
I just put the new version, but it still does not work

**Comment by Blueyescat** [comment]
Use the correct code (you already know it) instead of "set spectator target"

**Comment by Apex142** [comment]
Doesn't work,
set player's spectator target to arg-1 parsed as player

**Comment by ShaneBeee** [comment]
thats probably because that isn't even Skript code

**Comment by Blueyescat** [comment]
Nice, the expression is lost somehow

**Comment by Apex142** [comment]
@Blueyescat Yes but i'm new in skript, and this class doesn't help me

**Comment by Blueyescat** [comment]
Nothing you can't do

**Comment by ShaneBeee** [comment]
Long story short, in one of the previous updates, a bunch of commits were lost. 
Blue is pointing out that this is one of them, it was accidentally removed. 

It will need to be re-added back in. Until then, there nothing you can do.

**Comment by Apex142** [comment]
Can anyone redo the plugin please ?

**Comment by ShaneBeee** [comment]
It will most likely appear in the next update. probably 2.4-alpha4

**Comment by Apex142** [comment]
an idea when she is going out?

**Comment by ShaneBeee** [comment]
Bensku said probably tomorrow

**Comment by Apex142** [comment]
ok thank you, I keep this topic open, for maybe help people who have the same problem as me

**Comment by Blueyescat** [comment]
Here is a custom build with this issue fixed: http://www.mediafire.com/file/flur3vrr6fp3prk/Skript.jar/file
