### ISSUE TITLE
 Skript 2.3.7 colored arg problem (Same as #2208)

### ISSUE THREAD

**Issue by mckite** [SkriptLang/Skript#2209]
Description
After the recent Skript 2.3.7 update, colored arguments are now unable to parse and show up as color (this worked in Skript 2.3.6)

Steps to Reproduce
command /test <text>:
    trigger:
        send "%colored arg-1%"
Expected Behavior
For colored arguments to correctly parse.
Currently, when entering "&6Test" or "<aqua>Test" for example, the text returned by the command will still be white

Errors / Screenshots
Server Information
Server version/platform: Spigot 1.12.2
Skript version: Skript 2.3.7
Additional Context

**Comment by ShaneBeee** [comment]
If the issue is the same, why are you posting a duplicate issue?

**Comment by mckite** [comment]
Because Skript version is different

**Comment by Wealthyturtle** [comment]
@mckite they are not going to do a backwards update unless it's a critical security bug. Use the latest version.
