### ISSUE TITLE
2.3.7 skript color and special code arg bug on 1.13.2 (same as #2209 and #2208)

### ISSUE THREAD

**Issue by Command1264** [SkriptLang/Skript#2210]
### Description
* **color: <green> &a &k**
* **special code: <url:https://www.youtube.com> <show text:test> <run command:/suicide> <suggest command:/spawn>**
* **on .sk file is no problem, but on minecraft arg has bug**

### Steps to Reproduce
command /test [< text >]: (because of < text > Will not see so I add 2 spaces)
    trigger: (4 spaces)
        send "%arg-1%" to all player (8 spaces)

### Expected Behavior
* **Expected Behavior--> &a&k<url:https://www.youtube.com>OuO**
* **Actual behavior--> OuO**

### Errors / Screenshots
* **https://youtu.be/zIh65YX7fig**

### Server Information
* **Server version/platform:1.13.2**
* **Skript version:2.3.7**

**Comment by Command1264** [comment]
same with #2209 and #2208

**Comment by ShaneBeee** [comment]
If the issue is the same, why are you posting a duplicate issue?
