### ISSUE TITLE
Teleportation problem (PlayerTeleportEvent)

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#2211]
### Description

The problem is when I fall into the void (below 110), an error appears in the console and I get kicked for sending too many packets.
### Steps to Reproduce

https://gist.github.com/Romitou/29461611c154403b2230b8fda8ac584e

### Expected Behavior

This code had to teleport players to {s.lobby} if they passed below layer 110. It worked very well in 2.4-alpha3.
### Errors / Screenshots

https://gist.github.com/Romitou/e70185390546fb0ede066d7d457b8c30
https://youtu.be/3yvM9xf4RYk

### Server Information
* **Server version/platform:**  git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)     
* **Skript version:** 2.4-alpha4               

### Additional Context

I'm going back to Skript 2.4-alpha3 to stop having this problem, but I just wanted to post it here to help you. Sorry if my english is bad, I'm french. Sorry if there are no phrases in some places, my post was reset when I posted it ...

**Comment by TPGamesNL** [comment]
What world and xyz coords is the variable `{s.lobby}` set to?

**Comment by Romitou** [comment]
> What world and xyz coords is the variable `{s.lobby}` set to?

Hello, thank you very much for your answer, here is the content of the variable:
x: 0.5, y: 124.5, z: 0.5

**Comment by ShaneBeee** [comment]
This is not a Skript issue, since `on any move` is a SkQuery syntax.

**Comment by Romitou** [comment]
Very sorry @ShaneBeee I don't think this is a SkQuery syntax. I will try to choose a another syntax or Skript for my skript.
Very sorry for my bad english and thanks you very much for your response and sorry.

**Comment by ShaneBeee** [comment]
> Very sorry @ShaneBeee I don't think this is a SkQuery syntax. I will try to choose a another syntax or Skript for my skript.
> Very sorry for my bad english and thanks you very much for your response and sorry.

1) Never apologize for your English skills, you don't need to. You're doing better than some native English speakers ;)
2) Also no need to apologize for the issue. Im just pointing out that its an SkQuery issue and nothing the Skript devs can do about it.
