### ISSUE TITLE
Spawning mobs problems

### ISSUE THREAD

**Issue by andrei923** [SkriptLang/Skript#2212]
### Description
when you try to spawn some mobs through a function it doesn't work for some reason.

### Steps to Reproduce

```
function spawnmob(loc: location, entity: entity type):
	spawn {_entity} at {_loc}

#This does not work.
command golem:
    trigger:
        spawnmob(location of player, iron golem)

#This does not work.
command silverfish:
    trigger:
        spawnmob(location of player, silverfish)

#This does not work.
command zombie:
    trigger:
        spawnmob(location of player, zombie)		

#This works
command chicken:
    trigger:
        spawnmob(location of player, chicken)		

#This works
command golem2:
	trigger:
		spawn an iron golem at player
```

### Expected Behavior
to spawn the mobs

### Errors / Screenshots
no errors

### Server Information
* **Server version/platform:**       spigot 1.13.2
* **Skript version:**               2.4-alpha4
no addons or plugins

**Comment by bensku** [comment]
This is a regression introduced in 2.2-dev15, aka commit d921185. I'll try fixing this and hope nothing else breaks.
