### ISSUE TITLE
I get this error and had to report it

### ISSUE THREAD

**Issue by Joeripoes** [SkriptLang/Skript#2214]
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:19 [Server] ERROR #!#! [Skript] Severe Error:
30.06 10:26:19 [Server] ERROR #!#! Version supports setTamed but MethodHandle lookup failed
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:19 [Server] ERROR #!#! Something went horribly wrong with Skript.
30.06 10:26:19 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
30.06 10:26:19 [Server] ERROR #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
30.06 10:26:19 [Server] ERROR #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:19 [Server] ERROR #!#! Stack trace:
30.06 10:26:19 [Server] ERROR #!#! java.lang.IllegalAccessException: no private access for invokespecial: interface org.bukkit.entity.Ocelot, from java.lang.Object/public
30.06 10:26:19 [Server] ERROR #!#!     at java.lang.invoke.MemberName.makeAccessException(MemberName.java:850)
30.06 10:26:19 [Server] ERROR #!#!     at java.lang.invoke.MethodHandles$Lookup.checkSpecialCaller(MethodHandles.java:1572)
30.06 10:26:19 [Server] ERROR #!#!     at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:1002)
30.06 10:26:19 [Server] ERROR #!#!     at ch.njol.skript.entity.OcelotData.<clinit>(OcelotData.java:46)
30.06 10:26:19 [Server] ERROR #!#!     at java.lang.Class.forName0(Native Method)
30.06 10:26:19 [Server] ERROR #!#!     at java.lang.Class.forName(Class.java:348)
30.06 10:26:19 [Server] ERROR #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
30.06 10:26:19 [Server] ERROR #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
30.06 10:26:19 [Server] ERROR #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
30.06 10:26:19 [Server] ERROR #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
30.06 10:26:19 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
30.06 10:26:19 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
30.06 10:26:19 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
30.06 10:26:19 [Server] ERROR #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
30.06 10:26:19 [Server] ERROR #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
30.06 10:26:19 [Server] ERROR #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859)
30.06 10:26:19 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:19 [Server] ERROR #!#! Version Information:
30.06 10:26:19 [Server] ERROR #!#!   Skript: 2.4-alpha4
30.06 10:26:19 [Server] ERROR #!#!     Flavor: skriptlang-github
30.06 10:26:19 [Server] ERROR #!#!     Date: 2019-06-27
30.06 10:26:19 [Server] ERROR #!#!   Bukkit: 1.14.3-R0.1-SNAPSHOT
30.06 10:26:19 [Server] ERROR #!#!   Minecraft: 1.14.3
30.06 10:26:19 [Server] ERROR #!#!   Java: 1.8.0_212 (Java HotSpot(TM) 64-Bit Server VM 25.212-b10)
30.06 10:26:19 [Server] ERROR #!#!   OS: Linux amd64 4.15.0-43-generic
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:19 [Server] ERROR #!#! Server platform: Paper
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:19 [Server] ERROR #!#! Current node: null
30.06 10:26:19 [Server] ERROR #!#! Current item: null
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:19 [Server] ERROR #!#! Thread: Server thread
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:19 [Server] ERROR #!#! Language: english
30.06 10:26:19 [Server] ERROR #!#! Link parse mode: DISABLED
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:19 [Server] ERROR #!#! End of Error.
30.06 10:26:19 [Server] ERROR #!#! 
30.06 10:26:20 [Server] INFO [Skript]  ~ created by & © Peter Güttinger aka Njol ~
30.06 10:26:20 [Server] INFO [GetSpawners] Enabling GetSpawners v1.20

**Comment by ShaneBeee** [comment]
Re-download alpha 4, Snow fixed this and changed the download file.

**Comment by bensku** [comment]
Yeah, that should solve the issue. I'm curious, though - did you download your release from Github or some other place? The broken build was up for a short time, two days ago.

**Comment by Joeripoes** [comment]
I regularly check jithub and jenkins websites for latest versions of my plugins
