### ISSUE TITLE
Upon closing server, server hangs at skript randomly.

### ISSUE THREAD

**Issue by Coolfire02** [SkriptLang/Skript#2216]
I've not idea why this happens however, skript seems to not disable properly occasionally. It isn't a big issue as it has only happened once in like 3 weeks however it's still an issue that I'm really puzzled about considering the fact that it dosent normally hang at skript. 

I have no idea how to produce this however about 50minutes after 'closing' the server when one of my admins reported, the last log of console was 

[03:04:31] [Server thread/INFO]: [Skript] Disabling Skript v2.3.6
[03:04:31] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: skript
[03:04:34] [User Authenticator #523/INFO]: UUID of player YungPedro is d9b086d9-febf-3ba1-a4b3-2ce4085d1df3

everything past that line is basically attempts from players trying to connect to the server

I'm running skript 2.3.6
1.12.2

**Comment by TheBentoBox** [comment]
Between the following issues:

1. 2.3.6 isn't the latest version of Skript.
2. This sounds like it's very rare and fairly unique to your server (e.g. I've never had this issue on my live server and I've had 2.3.6 running on it for months with automated restarts twice per day).
3. There are external things happening upon Skript disabling (I see a PlaceholderAPI hook disabling).

I don't think this is something we can realistically address without any information on reproduction steps or an actual indication of what may be happening.
