### ISSUE TITLE
Unable to set inventory slot of offlineplayer

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2217]
### Description

You are unable to set the inventory slot of players who are offline. Although this strictly may not be a bug (since I'm not sure if Skript intends for this to be a function) but I believe that it is in practice a bug due to the fact that if a function is trying to return an item to a player, and they have a crash, get disconnected, kicked, etc. the items are not able to write to the items to their inventory, causing loss of player data.

### Steps to Reproduce

```
every 1 second:
    set {_p} to "[insert your account name here]" parsed as offlineplayer
    if {_p} is not online:
        set slot 1 of {_p} to emerald
```

### Expected Behavior

For items to be added to offlineplayers' inventories too

### Server Information
* **Server version/platform:**       Spigot 1.14.3
* **Skript version:**                Skript 2.4-beta4

**Comment by Matocolotoe** [comment]
You just cannot manipulate offline players' inventories in Minecraft

**Comment by Wealthyturtle** [comment]
Don't plugins like OpenInv exist? They allow you to see and edit offline player's inventories...

**Comment by LeotomasMC** [comment]
plugins like openinv either directly look at the player .dat files for inventory, or save them into its own system of storing inventories, and load the changes to their inventory when they next join.

**Comment by FranKusmiruk** [comment]
@Wealthyturtle what you can do is exactly what @LeotomasMC said but in Skript, you'd just have to save the inventory in a variable and modify the player's inventory when they join.

Closing since this is just not possible using Bukkit's API.
