### ISSUE TITLE
Can't compare the opened inventory with a variable

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#2218]
### Description
If you create an inventory and open it to a player, comparing it to the original variable does not pass the condition.

### Steps to Reproduce
You shouldn't be able to click on this inventory:
```
on load:
	set {-gui} to chest inventory with 3 rows named "Test"
	set slot 1 of {-gui} to stone
	
command /gui [<text>]:
	trigger:
		open {-gui} to player
		
on inventory click:
	event-inventory is set
	event-inventory = {-gui}
	cancel event
```

### Expected Behavior
The condition should pass?
When using `.equals() = true` from skript-mirror, it works fine.

### Server Information
* **Server version/platform:** Paper 1.14.3
* **Skript version:** 2.4 alpha4

**Comment by TheBentoBox** [comment]
It would be very useful for custom GUIs if this worked properly. You'd think Skript could default to a `.equals()` check for any types which don't have an explicit comparator defined.
