### ISSUE TITLE
Skript does not build.

### ISSUE THREAD

**Issue by gp-Airee** [SkriptLang/Skript#2223]
### Description
Skript does not build.

### Steps to Reproduce
Build Skript.

### Expected Behavior
Skript should build using `./buildbot-compile.sh`

### Errors / Screenshots
https://gist.github.com/gp-Airee/1f1d58924bea95b9ca47b1827a3264bc

### Server Information
```
javac 1.8.0_212
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

**Comment by FranKusmiruk** [comment]
You have to clone Skript using the recurse-submodules flag this way: `git clone --recurse-submodules <git repo>`

**Comment by bensku** [comment]
Don't use buildbot compilation script unless you are actually hosting Buildbot yourself.

**Comment by TPGamesNL** [comment]
It might be a good idea to include all source (so also from the aliases) in the source files that are added as an asset with every release (I'm not sure if this is possible on Github but it would me useful)

**Comment by bensku** [comment]
Unfortunately I don't think that is possible. A shame, but nothing we can do about it.
