### ISSUE TITLE
Put the line break "||"

### ISSUE THREAD

**Issue by Soufreur78** [SkriptLang/Skript#2227]
Hi, I use Google traduction because I'm french.

In update 2.3.1 you removed the ability to use "||" (from SkQuery) to skip lines in a lore with your new system.
The problem is that my skripts lose in optimization.

Here is a simple example of using the expression "||". Very useful in large menu with several objects, conditions, action ...

```set {_object::} to diamond and coal
set {_name::} to "Diamond" and "Coal"
set {_lore::*} to "1er line of diamond||2nd line of diamond" and "1er line of coal||2nd line of coal"
set {_n} to 1

loop {_lore::*}:
      format gui slot {_n} of player with {_object::%{_n}%} named "%{_name::%{_n}%}%" with "%{_lore::%{_n}%}%" to do nothing
      add 1 to {_n}```


Please simply allowed the possibility to use "||" to skip lines :). Because since the update with your system (", "" and ""...) we can no longer use "||"

**Comment by ShaneBeee** [comment]
>In update 2.3.1 you removed the ability to use "||" (from SkQuery) to skip lines in a lore with your new system.

This is an issue tracker for Skript, not SkQuery. You will have to take that up with SkQuery as it has absolutely nothing to do with the Skript plugin itself.

**Comment by Blueyescat** [comment]
You can use
```vb
set {_object::*} to diamond and coal
set {_name::*} to "Diamond" and "Coal"
set {_lore::1::*} to "1er line of diamond" and "2nd line of diamond"
set {_lore::2::*} to "1er line of coal" and "2nd line of coal"

loop {_lore::*}:
	format gui slot {_n} of player with {_object::%{_n}%} named {_name::%{_n}%} with lore {_lore::%{_n}%::*}
	add 1 to {_n}
```
instead, but that code looks bad to me, i mean relying on variable indexes. I would recommend you to use
```vb
set {_items::1} to diamond
set {_names::1} to "Diamond"
set {_lores::1::*} to "1er line of diamond" and "2nd line of diamond"

set {_items::1} to coal
set {_names::1} to "Coal"
set {_lores::2::*} to "1er line of coal" and "2nd line of coal"

loop {_items::*}:
	set {_n} to loop-index parsed as number
	format gui slot {_n} of player with {_items::%{_n}%} named {_names::%{_n}%} with lore {_lores::%{_n}%::*}
```

Multi line code blocks are made with ```

**Comment by Soufreur78** [comment]
> This is an issue tracker for Skript, not SkQuery. You will have to take that up with SkQuery as it was removed from SkQuery and has absolutely nothing to do with the Skript plugin itself, since that line break was never in Skript

Hello, yes the "||" belongs to SkQuery but it is with the update of Skript that it is no longer possible to use it. It is therefore up to the creator of Skript not to block the use of "||". The system ("," ") is interesting but you should not block the use of" || "if possible.

(Google traduction suck i know)

**Comment by ShaneBeee** [comment]
> > This is an issue tracker for Skript, not SkQuery. You will have to take that up with SkQuery as it was removed from SkQuery and has absolutely nothing to do with the Skript plugin itself, since that line break was never in Skript
> 
> Hello, yes the "||" belongs to SkQuery but it is with the update of Skript that it is no longer possible to use it. It is therefore up to the creator of Skript not to block the use of "||". The system ("," ") is interesting but you should not block the use of" || "if possible.
> 
> (Google traduction suck i know)

Incorrect. Skript is not blocking it, Limeglass (the maintainer of SkQuery) removed the lore expression from SkQuery 3.6.2+

**Comment by TheBentoBox** [comment]
As Shane has said, we did not block or remove support for "||", it was removed from SkQuery itself after Skript added its own expression for multiline lore. You must update your scripts to use lists of strings (", ") for multiline lores.
