### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Alperenn** [SkriptLang/Skript#2232]
### Description
i need help

### Steps to Reproduce
http://pasted.co/6dc8f453

### Expected Behavior
http://pasted.co/6dc8f453
### Errors / Screenshots
http://pasted.co/6dc8f453

http://pasted.co/6dc8f453
### Server Information
* **Server version/platform:**       1.8.9
* **Skript version:**                2.0

### Additional Context

**Comment by TPGamesNL** [comment]
Your Skript version is actually 2.2-dev36, which isn't supported. Use the latest version if you want to report bugs.
It also seems that this isn't caused by Skript itself, but rather by RandomSK

**Comment by Alperenn** [comment]
All plugins fail when I update the plugin how can i solve ?

**Comment by TPGamesNL** [comment]
1.8.x isn't supported by Skript, update your server version or contact the developer of RandomSK (by making an issue on github for example) to fix RandomSK for 2.2-dev36.

**Comment by TheBentoBox** [comment]
Not the latest Skript version, not a supported Minecraft version, AND using outdated add-ons!
