### ISSUE TITLE
Firing crossbow doesn't trigger projectile shoot event

### ISSUE THREAD

**Issue by bluelhf** [SkriptLang/Skript#2233]
### Description
Firing a crossbow doesn't trigger the `on projectile shoot:` event

### Steps to Reproduce
Use this snippet:
``` 
on shoot:
  send "hi"
```
Then fire a crossbow.

### Expected Behavior
The player is sent the "hi" message when they fire the crossbow

### Server Information
* **Server version/platform:** git-Paper-111 (MC: 1.14.3)
* **Skript version:** 2.3-alpha4

### Additional Context
Using `org.bukkit.event.entity.EntityShootBowEvent` instead of Skript's native event solves the issue (see snippet below)
``` 
import:
  org.bukkit.event.entity.EntityShootBowEvent

on EntityShootBowEvent:
  broadcast "hi"
``` 
(using skript-mirror v2.0.0-SNAPSHOT)

**Comment by TPGamesNL** [comment]
Does `org.bukkit.event.entity.ProjectileLaunchEvent` get triggered?

**Comment by bluelhf** [comment]
It does.
```vb
import:
  org.bukkit.event.entity.ProjectileLaunchEvent

on ProjectileLaunchEvent:
  broadcast "just testing"```
works as expectded.

**Comment by TPGamesNL** [comment]
Maybe it's because of the player expression. Try broadcasting `"hi"` instead of sending it in the normal shoot event.

**Comment by bluelhf** [comment]
i'm dumb
