### ISSUE TITLE
Removing player's tool will crash the server.

### ISSUE THREAD

**Issue by seph976** [SkriptLang/Skript#2237]
Tested on Spigot 1.14.3 and PaperMC 1.14.3
Using latest Skript version (Alpha 2.4)

**Description**
Removing players tool crashes the server.
(remove 1 of player's tool from player)

If the player has a stack of items, it wont remove any and simply not work, but if there is only one left, the item will be taken and the server closes.

Tested on a clean server with no other mods or addons.

**Crash Report**
[crash-2019-07-08_13.29.21-server.txt](https://github.com/SkriptLang/Skript/files/3368593/crash-2019-07-08_13.29.21-server.txt)

**Comment by seph976** [comment]
Sorry, didnt realize there was a format to be followed, tried to clean it up for you guys and also tested on a completely clean server.

**Comment by Wealthyturtle** [comment]
Spigot Bug. #2143

**Comment by bensku** [comment]
Unfortunately @Wealthyturtle is correct. Skript doesn't use NMS, so an error like this shouldn't be possible. Try updating your server software. If that doesn't help, we'll have to report this upstream.

**Comment by seph976** [comment]
Sorry for the late reply, the workaround does work, thank you @Wealthyturtle 

As for the error, i tried it on a completely fresh install of the latest dev build of Spigot with no other plugins than Skript, also tried it on PaperMC so its definitely a Spigot problem then.

Anyway, thanks again.
