### ISSUE TITLE
My custom commands wont work

### ISSUE THREAD

**Issue by puppimaniax13** [SkriptLang/Skript#2238]
### Description
 When I try to use my script it wont give an out put and just says its right but in the console it says its wrong

### Steps to Reproduce
 command /cc:
	description: Clears Chat!
	permission: clear.chat
	executable by: players
	trigger:
		loop 300 times:
			broadcast ""

#{===========================================================}
#{===========================================================}

### Expected Behavior
 Nothing will work 

### Errors / Screenshots
 08.07 04:43:02 [Server] Server thread/INFO All scripts loaded without errors.
08.07 04:43:02 [Server] Server thread/ERROR #!#! 
08.07 04:43:02 [Server] Server thread/ERROR #!#! End of Error.
08.07 04:43:02 [Server] Server thread/ERROR #!#! 
08.07 04:43:02 [Server] Server thread/ERROR #!#! Link parse mode: DISABLED
08.07 04:43:02 [Server] Server thread/ERROR #!#! Language: english
08.07 04:43:02 [Server] Server thread/ERROR #!#! 
08.07 04:43:02 [Server] Server thread/ERROR #!#! Thread: Server thread
08.07 04:43:02 [Server] Server thread/ERROR #!#! 
08.07 04:43:02 [Server] Server thread/ERROR #!#! Current item: null
08.07 04:43:02 [Server] Server thread/ERROR #!#! Current node: loop 300 times: (start.sk, line 6)
08.07 04:43:02 [Server] Server thread/ERROR #!#! 
08.07 04:43:02 [Server] Server thread/ERROR #!#! Server platform: Spigot
08.07 04:43:02 [Server] Server thread/ERROR #!#! 
08.07 04:43:02 [Server] Server thread/ERROR #!#!   OS: Linux amd64 3.10.0-957.21.2.el7.x86_64
08.07 04:43:02 [Server] Server thread/ERROR #!#!   Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b04)
08.07 04:43:02 [Server] Server thread/ERROR #!#!   Minecraft: 1.14.3
08.07 04:43:02 [Server] Server thread/ERROR #!#!   Bukkit: 1.14.3-R0.1-SNAPSHOT
08.07 04:43:02 [Server] Server thread/ERROR #!#!     Date: 2019-06-27
08.07 04:43:02 [Server] Server thread/ERROR #!#!     Flavor: skriptlang-github
08.07 04:43:02 [Server] Server thread/ERROR #!#!   Skript: 2.3.7 (latest)
08.07 04:43:02 [Server] Server thread/ERROR #!#! Version Information:
08.07 04:43:02 [Server] Server thread/ERROR #!#! 
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:692)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:155)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.Skript.reload(Skript.java:910)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:377)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:425)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:406)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:648)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:493)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1022)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:628)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:638)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:365)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:450)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:415)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:246)
08.07 04:43:02 [Server] Server thread/ERROR #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:241)
08.07 04:43:02 [Server] Server thread/ERROR #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
08.07 04:43:02 [Server] Server thread/ERROR #!#! Stack trace: 

### Server Information
* **Server version/platform:**       
* **Skript version:**

**Comment by APickledWalrus** [comment]
Skript 2.3.7 does not support 1.14. Use the 2.4 alpha series.
