### ISSUE TITLE
Ability to directly delete entities from existence

### ISSUE THREAD

**Issue by TheAberto** [SkriptLang/Skript#2240]
an example code:
```
command  /LiveForThreeSecond:
    trigger:
        spawn cow
        set {_theCow} to last spawned cow
        wait 3 seconds
        delete {_theCow}
```
The ` delete {_theCow}` effect just deleting a variable. But we can not delete the spawned cow with using a variable.

Maybe you can use this effect: `delete random element of {_theCow}` or `delete random element of {_theCows::*}` (save the cow in a list variable.)

So, i think developers should add an effect like this: `delete entity of {_theCow}`

**Comment by TPGamesNL** [comment]
`kill {_theCow}`

**Comment by TheAberto** [comment]
> `kill {_theCow}`
Dropping loots thats not same thing you know.

**Comment by TPGamesNL** [comment]
> > `kill {_theCow}`
> You know thats not same thing. its dropping items.

You can cancel that in on death...

**Comment by TheAberto** [comment]
> > > `kill {_theCow}`
> > 
> > 
> > You know thats not same thing. its dropping items.
> 
> You can cancel that in on death...

Thats not same thing still. Your method has 2 part.
-kill entity
-cancel drops
#Triggered on death event.

also, there are death particles when an entity death. 
![300px-Particle_cloud](https://user-images.githubusercontent.com/52698522/60905998-e00c6b00-a27e-11e9-90f1-c7737315285f.png)

also, the entities will looks red. So,why we should deal for it? please do not say anything until you don't know.

**Comment by TPGamesNL** [comment]
Sorry, I didn't really understand what you were saying, but I think I get it now.

**Comment by Wealthyturtle** [comment]
Deleting entities could be a useful enhancement, so that users don't have to listen to additional events and the like thereof.

**Comment by sovdeeth** [comment]
#5198 fixes this:
```
delete entity within {var}
```
