### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by Alperenn** [SkriptLang/Skript#2241]
Can you please help me?
http://pasted.co/6ad2455a

**Comment by TPGamesNL** [comment]
This has nothing to do with Skript, it's about RandomSK. I recommend you to ask on [the SkUnity forums](https://forums.skunity.com/forums/skript/) or another place to get Skript help before opening an issue here, since the github page is for reporting bugs.

**Comment by Alperenn** [comment]
> This has nothing to do with Skript, it's about RandomSK. I recommend you to ask on [the SkUnity forums](https://forums.skunity.com/forums/skript/) or another place to get Skript help before opening an issue here, since the github page is for reporting bugs.

okay, ı am so sorry
