### ISSUE TITLE
Inventory Action warn

### ISSUE THREAD

**Issue by Alperenn** [SkriptLang/Skript#2243]
`[23:26:22] [Server thread/WARN]: [Skript] Ignored an exception due to user configuration: Can't register org.bukkit.event.inventory.InventoryType with the code name inventorytype because that name is already used by inventory type
[23:26:22] [Server thread/WARN]: [Skript] Ignored an exception due to user configuration: Can't register org.bukkit.event.inventory.ClickType with the code name clicktype because that name is already used by click type
[23:26:22] [Server thread/WARN]: [Skript] Ignored an exception due to user configuration: Can't register org.bukkit.event.inventory.InventoryAction with the code name inventoryaction because that name is already used by inventory action
`

**Comment by ShaneBeee** [comment]
Rather than deleting the issue template, could you please fill it in.
The template provides everyone here with the information needed to help resolve an issue.

Here is what the template looks like

```
<!--- This is just a recommended template, but you should follow it --->

### Description
<!--- A clear and concise description of what the problem is --->

### Steps to Reproduce
<!--- Steps to reproduce the problem. If applicable, add a script or code snippet here --->

### Expected Behavior
<!--- A clear and concise description of what you expected to happen --->

### Errors / Screenshots
<!--- If applicable, add errors and screenshots to help explain your problem --->

<!---
 If you get a console error, you should send the full error. Also if the error contains a stack trace; you can remove the Server Information section below.
 Also you should send long errors using a permanent and reliable paste service like Gist, not hastebin.
--->

### Server Information
* **Server version/platform:**       <!-- /version -->
* **Skript version:**                <!-- /version Skript -->

### Additional Context
<!--- Add any other context about the problem here --->

```

**Comment by bensku** [comment]
This is an addon issue. You've enabled a workaround in Skript, but it is not exactly stable one. Consider updating your addons.
