### ISSUE TITLE
Iron Doors bug

### ISSUE THREAD

**Issue by MedroYT** [SkriptLang/Skript#2244]
When you right click on iron door, nothing happens even if you call a on right click event.

`on right click on iron door:
    send "This works" to player`

I expected to get a message when I right clicked on the iron door.

No errors at all, just nothing happens on right click.

* **Server version/platform:** 1.12.2
* **Skript version:** Skript bensku-2.4-alpha4

**Comment by PobabZ** [comment]
```
on right click:
 if event-block is iron door:
  send "hi" to player
```

**Comment by MedroYT** [comment]
tried to do this twenty times before this post, doesn't work :)

**Comment by ShaneBeee** [comment]
This is due to some material mappings that are messed up for 1.12.2 and below.
I don't mean to sound rude but I have told Bensku this a few times now, and each time he tells me I'm wrong.

As a temp solution you can do the following and it will work
```vb
on right click:
	if "%type of event-block%" = "IRON_DOOR_BLOCK":
```

**Comment by bensku** [comment]
The material mappings are not wrong, it is just that some Minecraft 1.12.2 ids map to multiple Bukkit materials. There is a workaround, but it doesn't currently apply to doors: https://github.com/SkriptLang/Skript/blob/9fad99138e36c61aece0faa3b53c1812d013d8e8/src/main/java/ch/njol/skript/bukkitutil/ItemUtils.java#L99

**Comment by TheBentoBox** [comment]
Closing in favor of #2394 as it is the same bug and that one better describes the problem.
