### ISSUE TITLE
Variable Duplication

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2246]
### Description

_Disclaimer: If this is an invalid Skript bug, please close this issue. I'm not 100% sure if this is an issue with Skript, or if it's fixable at all_

Recently, my server has had the issue of having data loss (happened twice already within three days).

The data loss arises when duplicate variables are created, due to the server suddenly terminating. Although upon server startup Skript claims that it has kept one of the two duplicate variables, in reality, both of them were deleted and the Skript data is only retrievable via the backups folder. As such, when the server is started again, the Skript data is lost (i.e. Skripts can't access the variables that would normally be there) and I have to manually retrieve and extract the data from the backups folder, before restarting to re-initialize the variables.

The second issue is the data loss itself, I believe that the server must have abruptly stopped while Skript was trying to save variables. I do not know how Skript currently handles variables, but if it doesn't already do this, would it be possible for Skript to write the data that it's trying to save first to a temporary data file (while keeping the original data file), before deleting the old data file and renaming the new data file? This would ensure that at any given point, a copy of the data will be saved in a database-specific file, since at the moment, duplicate variables were saved all over the place when the server went down. For instance, I had a leaderboard list, and for whatever reason it got saved in both the gang database and the leaderboard database (shown in server logs upon server startup).

### Steps to Reproduce

Not entirely sure how to replicate this issue, but if it helps I'm using the CSV database storage option.

### Expected Behavior

For Skript data to be properly saved, and for duplicate variables to be properly saved and not completely removed.

### Errors / Screenshots

Log Excerpts:
- Server Freeze on 9th July: https://gist.githubusercontent.com/Wealthyturtle/200e040dc1d63cdc48c13143853b47e6/raw/194bceacdc30b06ce60b9ce293138c67b3d7a72f/gistfile1.txt
- Variable Loading Errors on 9th July: https://gist.githubusercontent.com/Wealthyturtle/ea6d06a46573e60fc543794d2743fef5/raw/5e662f4e696e206410a4c04142ab1df0881a92f8/gistfile1.txt
- Crash on 11th July: No logs available
- Variable Loading Errors on 11th July: https://gist.githubusercontent.com/Wealthyturtle/520f2e9be9ae9658c18c5d91d557ce5a/raw/b7a1ed1e975265b244d0d1e2425958ecb7e3acf6/gistfile1.txt

### Server Information
* **Server version/platform:**       Spigot 1.14.3
* **Skript version:**                Skript 2.4-alpha4

**Comment by Wealthyturtle** [comment]
Anyone have any idea on this issue? :/

**Comment by TheLimeGlass** [comment]
Please provide your config.sk you may have two databases saving the same values and thus only one can be chosen.

**Comment by Wealthyturtle** [comment]
@TheLimeGlass https://pastebin.com/6YwqEJwC
