### ISSUE TITLE
"the" + variable => "the"

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2248]
### Description

A string with "the" before displaying a variable always removes "the"

### Steps to Reproduce

```
command /test:
	trigger:
		set {_biome} to "Ice Plains"
		broadcast "We are in the %{_biome}% biome"
```
For example, this broadcasts `We are in Ice Plains biome`

### Expected Behavior

Should have broadcasted "We are in **the** Ice Plains biome"
The following workaround can be used to get what you wanted, but if you make advanced code it can become really annoying
```
command /test:
	trigger:
		set {_biome} to "the Ice Plains"
		broadcast "We are in %{_biome}% biome"
```

### Errors / Screenshots

No error.

### Server Information
* **Server version/platform:** Paper 1.14.3 (build 129)
* **Skript version:** 2.4-alpha4

**Comment by TPGamesNL** [comment]
Duplicate of #367

**Comment by Matocolotoe** [comment]
Whoops, sorry.
