### ISSUE TITLE
State of example scripts

### ISSUE THREAD

**Issue by bensku** [SkriptLang/Skript#2252]
Current example scripts are outdated. They're also often not terribly good *examples*, which is probably quite confusing for newbies. And, finally, they not all of them work. This needs to change.

I have three potential fixes which I would like feedback on.

## Just remove them
Remove example scripts from Skript. Point users to online resources for usable scripts and tutorials.

## Fix current examples
Fix current example scripts that do not work. Check all of them for style issues and do changes as needed. Possibly introduce a few new examples for new Skript features.

## Rework example scripts
Throw most, if not all, of current examples to rubbish bin. Create new ones, and this time, actually design them to teach new users. Add both very simple (/hat) and somewhat more complex (a simple chat system) examples.

Don't dump example scripts in scripts directory on first load, but instead allow doing that with commands. Possibly allow running unmodified example scripts from Skript jar directly.

I'm honestly not sure which option is the best. First one would require the least amount of effort, while the third option would definitely require a lot of outside contributions.

**Comment by APickledWalrus** [comment]
I’d say that reworking and fixing them is probably the best idea. I remember looking at the scripts when I first started, so they can come in handy for beginners.

**Comment by Blueyescat** [comment]
What about a GitHub repository for official example scripts (not for dumping into the scripts folder)? It would be easier to manage the scripts and its README would contain a "how to load" info, this would also teach the users how to load a ready to use script. But all PRs should be reviewed properly in that repository, **it should not be a place to share *big* scripts**, scripts shouldn't contain author/contributors info.

Thus a new Skript release wouldn't be need to update the scripts, the scripts folder wouldn't be ugly on first load. But there should be a file that leads the user to the examples repository.

I don't really think it is worth to work on a command system right now.

**Comment by jaylawl** [comment]
I remember when i first downloaded Skript, that i was very grateful for the provided example scripts and they instantly taught me how stuff works on a basic level. I think they should stay in

**Comment by bensku** [comment]
@Blueyescat Separate git repository would be good in any case. It can be included in jar if needed by using git submodules.

**Comment by Matocolotoe** [comment]
I think they should work the same as the new aliases, on a seperate repository and able not to load by default.

**Comment by gmalone** [comment]
Who are the key players in the world of Skript that are available, willing and can get a cleanup reorganization underway resulting in an authoritative Sk-code reference repository?

**Comment by bensku** [comment]
I agree with @gmalone; both Skript and the documentation really need improvements. Unfortunately, I don't think we *can* address all major issues anytime soon. To put it simply, I (and, as far as I know, other Skript developers) don't have enough time.

Skript, unfortunately, has a huge learning cliff for people who want to dive into its Java code. This is mostly due to missing documentation, and in my opinion, is slowly improving.
