### ISSUE TITLE
Could not load skript

### ISSUE THREAD

**Issue by Silxene** [SkriptLang/Skript#2253]
### Description
I am using spigot 1.14.3, I downloaded the SkUnity 2.3.7 version. I put it in plugins folder like always. I put my skript that I made in the scripts folder. I reload the server and the skripts and It says loaded 0 triggers, 0 commands. I check console and it also has errors. I used the SkUnity and my skript has no parse errors. I also doubt it would do this even if my skript had errors.

### Steps to Reproduce
Download spigot 1.14.3, download SkUnity 2.3.7 and put in plugins folder. Join the server with 1.14.3 client and make a skript called "Commands.sk", inside the file put this: https://pastebin.com/L7yV63nX.

### Expected Behavior
I expected the skript to load successfully. I use the latest version of SkUnity and Minecraft, I thought there wouldn't be issues. Or I am just really dumb and I didn't do something that I should've. Sorry if that's the case.

### Errors / Screenshots
Image of it in-game: https://ibb.co/8DTKBsW
Console Error: https://pastebin.com/WbGFeuWT

### Server Information
Server version/platform: Spigot 1.14.3
Skript version: 2.3.7

### Additional Information
Discord: Silxene#3555
Please get back to me asap. I really was looking forward to testing my skripts.

**Comment by TPGamesNL** [comment]
You need to use the alpha version for 1.14.3

**Comment by TheBentoBox** [comment]
Our latest releases can always be found [here](https://github.com/SkriptLang/Skript/releases). As @TPGamesNL stated, you need the latest alpha releases to use Skript on 1.14.
