### ISSUE TITLE
Reversed list expression

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#2260]
### Description
There isn't much to say really, it'd just reverse the order of the elements.
`reverse[d] %objects%`

It'd be useful when you need to loop numbers backwards, for example:
`loop reversed (integers between 1 and 100):`

**Comment by TheLimeGlass** [comment]
You can do `loop numbers between 100 and 1` and it works in reverse by the way. I added that I think somewhere near 2.2dev-25ish
