### ISSUE TITLE
Issues with inline comparison of functions

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2261]
### Description

When comparing 2 objects returned by functions without `:` an error appears

### Steps to Reproduce

```
function a() :: boolean:
	return true

function b() :: boolean:
	return false
```

Does work :
```
a() = b():
a() is b():
a() != b():
a() is not b():
```

Does not :
```
a() = b()             # Invalid brackets/variables/text in ') = b('
a() != b()            # Invalid brackets/variables/text in ') != b('
a() is b()            # Invalid brackets/variables/text in ') is b('
a() is not b()        # Invalid brackets/variables/text in ') is not b('

```
Storing the results into variables and then comparing them _does_ actually work, with or without `:`

### Expected Behavior

The condition should pass.

### Errors / Screenshots

The following error appears : `Invalid brackets/variables/text in ...` (more info in the piece of code)

### Server Information
* **Server version/platform:** 2.4-alpha4
* **Skript version:** Spigot 1.14.3

**Comment by Blueyescat** [comment]
I tried, that error happens when you use "inline conditions", not normal conditions (with `:`)
and doesn't happen if one of the expressions is not a function
