### ISSUE TITLE
ID of closed lower parts of wood doors are messed up

### ISSUE THREAD

**Issue by Lemrigue** [SkriptLang/Skript#2264]
### Description
The ids of closed lower parts of wood doors seem messed up

### Steps to Reproduce / Screenshot
Place a oak door, don't open it, make a little script to check the id of the event-block :
```
on right click:
    send "%event-block%"
```
right click on the closed lower part of the door, the chat send : "top" or "upper" while it should send "lower" or "bottom" :
[https://puu.sh/DURIX/ba985126e7.png](url)
Edit : The handle needs to be on the right

### Server Information
* **Server version/platform:** paper 1.14.3 build 134
* **Skript version:** 2.4-alpha4

I tried on another server with skript 2.3.7, on a 1.13.2 server, there is no problem

**Comment by bensku** [comment]
Cannot reproduce this.

**Comment by Lemrigue** [comment]
Ok I regenerated my materials.json file and the bug is gone, seems like it was my bad, sorry !
But now I noticed that some lower and upper ID are the same, I don't know if it's still a problem on my side though
![doors](https://user-images.githubusercontent.com/11993172/61581301-d9061800-ab1c-11e9-9b75-c6714d351388.png)

**Comment by bensku** [comment]
There have been recent changes that affect naming of aliases. In any case, what you're seeing is not really a bug.
