### ISSUE TITLE
Problem with setting a variable to armor stand item

### ISSUE THREAD

**Issue by Padlick01** [SkriptLang/Skript#2268]
### Description
When you set a variable to an armor stand, example for an gui, Skript throws an huge error.
### Steps to Reproduce
set {Playermods::existing::dummy} to armor stand with name "&8Delegator"

### Expected Behavior
That the variable is set to an item that is an armor stand 

### Errors / Screenshots
https://pastebin.com/CQDVqJLK

### Server Information
* **Server version/platform:**       git-Spigot-9a643a6-eb2e657 (MC: 1.14.3)
* **Skript version:**                2.4-beta2

**Comment by bensku** [comment]
Possible Spigot bug. Needs more investigation.

**Comment by Padlick01** [comment]
Today, I saw there's are new Error related to this issue. But different thing, it's an Java Error, not Skript.
And yes, I know, it's from Skript alpha4. But that doesn't make any difference because this issue is also on beta3 present.
https://pastebin.com/JrQXbAsc

**Comment by Padlick01** [comment]
Seems to be fixed.
