### ISSUE TITLE
2.4-beta2 cat entity not recognized on 1.13.2

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#2271]
Spigot 1.13.2 final
Skript 2.4-beta1

On server start-up or skript reload
```
[05:53:54] [Server thread/ERROR]: [Skript] Can't compare an entity with 'a cat' (save-my-pets.sk, line 11: if shooter's target is a cat:')
[05:53:54] [Server thread/ERROR]: [Skript] can't understand this event: 'on damage of a cat' (save-my-pets.sk, line 26: on damage of a cat:')
```

Similar to #2064 and #2074, but...
No issue reported on Spigot 1.14.4 with Skript 2.4-beta1.
No issue reported on Spigot 1.13.3 final with Skript 2.4-alpha4.

**Comment by JRoy** [comment]
Yeah, @bensku removed cat registration for some reason in https://github.com/SkriptLang/Skript/commit/a8c2c3d6de141a61f18562b8ea46624f39f2aca1. Possibly a tempfix?

**Comment by Padlick01** [comment]
That's because a cat is an 1.14 entity. In lower versions they are named "ozelot". 
The cat is an completly new entity from 1.14.

**Comment by BurntValentine** [comment]
To confirm - ozelot is also not valid:

20.07 15:37:03 [Server] ERROR can't understand this event: 'on death of an ozelot' (mobHeads.sk, line 24: on death of an ozelot:')

"Ocelot" worked in the 2.4beta4 build on a Spigot 1.13.2 setup, and does not in the 2.4alpha1/2 builds

**Comment by Padlick01** [comment]
> To confirm - ozelot is also not valid:
> 
> 20.07 15:37:03 [Server] ERROR can't understand this event: 'on death of an ozelot' (mobHeads.sk, line 24: on death of an ozelot:')
> 
> "Ocelot" worked in the 2.4beta4 build on a Spigot 1.13.2 setup, and does not in the 2.4alpha1/2 builds
> 
> 20.07 15:38:31 [Server] ERROR can't understand this event: 'on death of an ocelot' (mobHeads.sk, line 24: on death of an ocelot:')

Yep, can confirm on 1.14.3 with 2.4beta2

**Comment by BurntValentine** [comment]
Further evidence, though if cats being registered at all was removed that would be the problem, if I just stick a script with this in:

on death of a mob:
	send "You just killed a %victim%" to attacker

And then kill an ocelot it says I just killed a damageable mob

**Comment by Padlick01** [comment]
To bring this to an end; @SlimeDog I would close this issue because your report isn't an issue. It's normal. Cats are 1.14 stuff and aren't existing in 1.13 at all.

And to @BurntValentine I would say that you create a new issue for the ocelot problem.

**Comment by SlimeDog** [comment]
True re: cat=1.14 entity, but "cat" was recognized (even though technically a tamed ocelot) previously.

**Comment by Padlick01** [comment]
> True re: cat=1.14 entity, but "cat" was recognized (even though technically a tamed ocelot) previously.

That's true. But, as I said, your "issue" isn't a real issue, that's normal behaviour in my thinking. I didn't want to say more.
Also, I don't think that it wasn't intended that the cat was registered as an entity in skript in 1.13.x and lower.

**Comment by BurntValentine** [comment]
"Cat" wasn't a registered entity in 1.13.2 and lower it was an alias for Ocelot as the two were the same thing until 1.14+. It should still register as an alias for ocelot in 1.13.2 and older, but ocelot itself doesn't work either so I'd still say this report is fine

**Comment by Padlick01** [comment]
> "Cat" wasn't a registered entity in 1.13.2 and lower it was an alias for Ocelot as the two were the same thing until 1.14+. It should still register as an alias for ocelot in 1.13.2 and older, but ocelot itself doesn't work either so I'd still say this report is fine

Even then; I don't think, it's an good idea to put "cat" as an alias for ocelot. Because of that 1.14 stuff it could be confusing for some people.

**Comment by SlimeDog** [comment]
> Also, I don't think that it was intended that the cat was registered as an entity in skript 1.13.x and lower.

Since "cat" was recognized since 2014, I think intent probably isn't the issue.

**Comment by Padlick01** [comment]
Yes, I know that "cat" was recognized since some years. But as I said above, since 1.14 I really think, it shouldn't be an alias anymore. It can really confuse somebody.

**Comment by SlimeDog** [comment]
It seems quite reasonable that "cat" = "tamed ocelot". But I opened this only to point it out. I have no dog in this fight (so to speak), since I'm running a single 1.13.2 only as a plugin test server; the rest are 1.14.x test servers.

**Comment by BurntValentine** [comment]
It shouldn't be an alias in 1.14+ where "cat" is an actual thing in MineCraft, but this is about 1.13.2 and lower where it should still be an alias and was until the 2.4beta1 release.

I can open a separate report for the ocelot issue, but it's the same issue so that just seems unnecessary

**Comment by SlimeDog** [comment]
That's like saying "dog" shouldn't be recognized for tamed wolf (which it is).

**Comment by Padlick01** [comment]
> That's like saying "dog" shouldn't be recognized for tamed wolf (which it is). Does that confuse anyone?

No, because dogs aren't existing in any Minecraft version. You can't compare that each other.

**Comment by SlimeDog** [comment]
I can and do. But I'm done here. Whatever the Skript team decides works for me.

**Comment by SlimeDog** [comment]
Confirmed "ocelot" (but not "cat") recognized in Skript 2.4-beta3, on 1.13.2 final.
