### ISSUE TITLE
2.4-beta2 anything %player% related doesn't work

### ISSUE THREAD

**Issue by Cla6** [SkriptLang/Skript#2273]
### Description
Commands and events that include %player% or anything player related give out an error
Current version: PaperSpigot 135 and Skript 2.4-beta2

### Steps to Reproduce
Basically here's a bit of my skript/script

command /stats [<text>] [<player>] [<text>] [<integer>]:
	trigger:
		if arg-1 is "view":
			if arg-2 is set:
				send "&7Stats for: &c%arg-2%"

### Expected Behavior
It's meant to show you the stats for the player you want (arg-2) but it gives you an error instead. This is also reproduced when arg-2  is not set and you're viewing your own stats, but instead of saying that the error is at %arg-2% it says %player%

Before you say "It's probably your script, you did something wrong" let me tell you that no, it is not. I downgraded from 2.4-beta2 to 2.4-alpha2 and the script works flawlessly.

The addons aren't the problem either.

### Errors / Screenshots
https://pastebin.com/PpvACs1P

### Server Information
Server version: PaperSpigot,  version 135, 1.14.4
Skript version: Skript 2.4-beta2

**Comment by Patbox** [comment]
The same

**Comment by Moderocky** [comment]
Could you paste the segment of your skript inside backticks (```) please? That will keep the formatting and make it readable.
