### ISSUE TITLE
Error when looping items on quit event - 2.4beta2, Spigot 1.13.2

### ISSUE THREAD

**Issue by BurntValentine** [SkriptLang/Skript#2274]
### Description
Error given during the on quit event when trying to loop items, stops the action from working

### Steps to Reproduce
Run this script, which loads fine, and then log in/out of the server which should trigger it saving a copy of your inventory on quit but it fails and spits an error out:
(Ignore the #'d lines, normally it's set up with skQuery to make an actual inventory when you check the backup rather than drop the items, but the issue is present without skQuery)

### Expected Behavior
On log out your inventory in any world other than "Creative" should be saved as a backup which can then be checked/retrieved via the commands.

### Errors / Screenshots
Console error when quitting the server: https://gist.github.com/BurntValentine/485a815dfe155ea78547d137b61d00a7

### Server Information
Server version/platform: Spigot 1.13.2
Skript version: 2.4beta2

### Additional Context
No addons present, script edited a little to remove the feature used from skQuery for testing to confirm it happens with just Skript. Worked fine in 2.4beta2.

**Comment by BurntValentine** [comment]
Forgot the script link: https://gist.github.com/BurntValentine/94efb752e4af3b7db0780b89573df9e6

**Comment by bensku** [comment]
I couldn't reproduce this with your test case, but still found the issue and fixed it. Hopefully it works for you, too.
