### ISSUE TITLE
Repeated variable in colored messages

### ISSUE THREAD

**Issue by PanGargamel** [SkriptLang/Skript#2279]
### Description
I found a bug when sending user colored chat messages containing variables.

### Steps to Reproduce
1. Install this script:
```
command /test:
	trigger:
		set {_str} to "a"
		send "&a%{_str}%"
```
2. Run "/test" a couple of times

### Expected Behavior
The output should be lightgreen colored "a" letter every time you run "/test" command. Instead of this, I get "aa" after second run, "aaa" after third, "aaaa" after fourth, etc.

### Server Information
* **Server version/platform:**       git-Paper-134 (MC: 1.14.3)
* **Skript version:**                2.4-beta3

### Additional Context
I also found out that using `send colored` instead of `send` solves the problem. The problem doesn't also occur if you remove colors from your message.

**Comment by sjoerdtim** [comment]
Can confirm, I'm having this problem as well.

**Comment by bensku** [comment]
Sounds like a case of literal pollution.

**Comment by bolleboor** [comment]
Yes, I have the problem aswell and it's annoying.
Reloading the skript itself will fix the issue until you repeat it again for 2 times.
