### ISSUE TITLE
Issue with colored text/arguments as variables - 2.4beta3

### ISSUE THREAD

**Issue by BurntValentine** [SkriptLang/Skript#2280]
### Description
Running a command with a colored argument, and then sending a message with that argument as a variable, outputs "null"

### Steps to Reproduce
Script: https://gist.github.com/BurntValentine/7fb8b75a7fe41b0e7bde529297a3e1b9
Run the command `/lmjoin set <player name> &5Test` and the message returned is that it was set to "null" (tried with a direct %arg 3%, %colored arg 3% and doing set {_test} to arg 3 or colored arg 3 and using that - same result)

The message given in chat if you log out and back in is correctly `Test` in purple however.

Every time you re-run the command, whether it be the same command or a different message/player, it also adds another "null" on the end, so second commands output is "nullnull" etc...

### Expected Behavior
The message output when using the command should be colored as per the color codes used.

### Server Information
Server version/platform: Spigot 1.13.2
Skript version: 2.4beta3

**Comment by bensku** [comment]
Fixed in 2.4-beta4.
