### ISSUE TITLE
Crashes and errors when using variables in messages

### ISSUE THREAD

**Issue by sjoerdtim** [SkriptLang/Skript#2281]
### Description
Whenever you try to send or broadcast a message with color and an expression, this causes an error or a client crash. I've tested this with numerous functions and it keeps happening.
It seems to behave differently when done through a command as opposed to through an event on sign click.

### Steps to reproduce
Code: https://pastebin.com/VkDJmDdq
The command shows that it does not crash without colours or without variables, but as soon as you have both colours and variables, it crashes or gives the error. For me, the error appeared when I used the command (for the last send effect) and the crash appeared when I clicked a Team sign. When the command's last send effect gets called, it did not display the sent message in game.

### Expected Behavior
What I'd expect to happen is that the code runs fine without crashes or errors.

### Errors / Screenshots
Client crash on sign click: https://i.imgur.com/GToXe5o.png
Error at the end of the command (from console): https://pastebin.com/ykd6FNw6

### Server Information
* **Server version/platform:**  Paper version git-Paper-639 (MC 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* **Skript version:** Skript version 2.4-beta2

### Additional Context
In my opinion, should be a very high priority issue, as it completely breaks a lot of functionalities used by almost every single skript.

Edit: Also, I was running many addons when I first encountered this, but even after removing every single plugin apart from Skript, I was still getting this issue.

**Comment by bensku** [comment]
Latest version has fix for this.
