### ISSUE TITLE
Lenient parsing mode doesn't parse links starting with http[s]:// and all links in colored messages

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2283]
### Description

When `parse links in chat messages` is set to `lenient` (everything that contains a dot will be interpreted as a link), if the message is colored the link isn't a link anymore.

### Steps to Reproduce

```
command /test:
    trigger:
        send "google.com"     # Works
        send "&bgoogle.com"   # Does nothing when clicking on it
```

### Expected Behavior

The link should parse

### Errors / Screenshots

No error in console.

### Server Information
* **Server version/platform:** any      
* **Skript version:** latest

**Comment by TheBentoBox** [comment]
Is this still an issue on the latest beta release?

**Comment by Matocolotoe** [comment]
Yes, and the issue also happens when [un]colouring the text containing the link

**Comment by bensku** [comment]
Lenient link parsing has few users, so priority for this is very low.

**Comment by Matocolotoe** [comment]
Would `send colored` fix the problem ?

**Comment by Matocolotoe** [comment]
Found something else (see issue title)
