### ISSUE TITLE
Set Respawn Location not working

### ISSUE THREAD

**Issue by sjoerdtim** [SkriptLang/Skript#2284]
### Description
Using set respawn location on an on respawn event doesn't work.

### Steps to reproduce
Set a variable for this and then die. When you respawn you will just go to the default spawn instead of the one you set in the script.
```
on respawn:
	set respawn location to {any.variable.location}
```

### Expected Behavior
What I'd expect to happen is that the player respawns at the new variable location.

### Server Information
* **Server version/platform:**  Paper version git-Paper-639 (MC 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* **Skript version:** Skript version 2.4-beta3

**Comment by FranKusmiruk** [comment]
I guess it should work but either way, the recommended method is teleporting the player (it sets the respawn location internally).

**Comment by sjoerdtim** [comment]
@FranKusmiruk I would agree, except that teleporting on respawn only works if you first add a 1 tick delay. This extra delay makes the respawn look significantly less smooth, so I would definitely prefer this expression to work.

**Comment by Blueyescat** [comment]
Tested with Skript 2.4-alpha4, without any delay in code (probably some other plugins overrides it in your case):

1.13.2
`set respawn location to {spawn}` doesn't do anything (doesn't set the location)
`teleport player to {spawn}` works fine

1.14.4
`set respawn location to {spawn}` works fine
`teleport player to {spawn}` works fine

But both use the same spigot method, what

**Comment by APickledWalrus** [comment]
Can't reproduce this running:
- Skript 2.5
- Paper 1.16.3 (git-Paper-214)

**Comment by Romitou** [comment]
I can't reproduce either.
- Skript 2.5
- Paper 1.16.2 (git-Paper-182)

**Comment by APickledWalrus** [comment]
I am going to say this is safe to close then.
