### ISSUE TITLE
Projectile comparison not functioning correctly

### ISSUE THREAD

**Issue by sjoerdtim** [SkriptLang/Skript#2286]
### Description
When you try to compare a projectile in a on projectile hit event, it doesn't work unless you parse both as string.

### Steps to Reproduce
```
on projectile hit:
	projectile is snowball:
		broadcast "Doesn't work!"
	projectile is a snowball:
		broadcast "Doesn't work!"
	"%projectile%" is "snowball":
		broadcast "Works!"
```

### Expected Behavior
Expected behavior would be that all three of these conditions result in true.

### Server Information
* **Server version/platform:** Paper version git-Paper-639 (MC 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* **Skript version:** Skript version 2.4-beta3

### Additional Context
I have only tested this with snowballs.

**Comment by HAHAYOUDEAD** [comment]
same issue with (all?) other projectiles on 1.14.4 paper

tried with arrow, egg and ender pearl

**Comment by ShaneBeee** [comment]
Closing this in favour of #2637 
There are many issues on the tracker all stemming from this one big issue, so I wanted to condense this into one larger issue.
