### ISSUE TITLE
Freeze suggestion

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2287]
Hello. I have a suggestion. Could you please add "freeze entity"? Right click on entity:
Freeze entity for 4 seconds?

**Comment by Blueyescat** [comment]
Does anyone know an appropriate way for this? Potion effects aren't, disabling AI isn't too and shouldn't be added as a freeze effect.

**Comment by Misio12320** [comment]
1. Execute command "data merge %uuid of clicked entity% {NoAI:1}" too long.
2. Potion what? Hard to understand and for look.
And freeze would look easier to understand and in code would look friendly

**Comment by bensku** [comment]
Do you just want to stop the entity for a while? That is possible, Skript has expression for movement speed.

**Comment by Misio12320** [comment]
Yep. I don't see this in docs. Freeze option is not possible or what? Easier as said.

**Comment by Blueyescat** [comment]
Speed expression is only for players, doesn't prevent jumping (+ moving)
you will need jump boost -100 potion to prevent jumping, doesn't prevent sprinting + jumping
you will need blindness to prevent sprinting

Teleporting the entity every ticks is not equal to freezing

NoAI doesn't work for players and should be implemented as a "toggle AI" effect

This is why there is no a proper way for it, it would be ridiculous to implement a "freeze" effect using ways like that.

**Comment by Misio12320** [comment]
Excelent. Clever. Rip them pfff.
