### ISSUE TITLE
Placeholder appending issue

### ISSUE THREAD

**Issue by ArtelGG** [SkriptLang/Skript#2290]
### Description

The variables "%tps%" and "%tps from last 1m%" (and more, most likely.) are being infinitely appended to a command running "send". My guess is a StringBuilder got messed up somewhere.

### Steps to Reproduce

Add one or both of the placeholders to a command response, run the command 2+ times and see infinite appended numbers.

You can find the Skript's code [here](https://pastebin.com/fLhS9mLK).

### Expected Behavior

The placeholder should only be replaced one time, not appended infinitely.

### Errors / Screenshots

Running the command repeatedly produces this output: https://i.imgur.com/YMeVdWg.png

### Server Information
* **Server version/platform:**       
* **Skript version:**                
PaperSpigot 1.14.4-b135
Skript 2.4-b3

### Additional Context

N/A

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/2279
