### ISSUE TITLE
No block updates when setting blocks

### ISSUE THREAD

**Issue by sjoerdtim** [SkriptLang/Skript#2292]
### Description
When a block is set using Skript, there is no block update. This causes blocks like fences and iron bars to not connect to eachother and/or other surrounding blocks.

### Steps to Reproduce
Set a couple blocks to fence blocks using Skript and watch how they get connected.

### Expected Behavior
Block updates are called, causing these fences to connect to eachother properly.

### Errors / Screenshots
![Proof](https://i.imgur.com/ufCTklg.png?1)

### Server Information
* **Server version/platform:** Paper version git-Paper-639 (MC 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* **Skript version:** Skript version 2.4-beta3

**Comment by bensku** [comment]
Is this something new, or has Skript always done this? In any case, Skript causing block updates would make setting many blocks significantly slower.

**Comment by sjoerdtim** [comment]
Might just be Minecraft changing how they handle the fence block states. 

Still, I think setting a block to fence using Skript should have it connect properly. Not sure what other way you could use to resolve this.
