### ISSUE TITLE
About player head issue. > Item Type Issue

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#2293]
After i use

set yaml value "Head" from file "plugins/Heads.yml" to skull of player

Head data can't be recorded properly.

Head: !!ch.njol.skript.aliases.ItemType
  all: false
  amount: 1
  itemMeta:
    ==: ItemMeta
    meta-type: SKULL
    internal: H4sIAAAAAAAAAONiYOBi4AnOLs3JCSjKT8vMSeVgYPJMYVBJSTY2TTI3NNM1MrI00zVJNbHQtTQzSdJNMzIxTTQzMTZKSgQqZfFLzE1l4AwJdXb0dw1zDWJgAAA34U4EUQAAAA==
    skull-owner: TUCAOEVER

And i tried to use type of skull of player,it shows that skull of player is

south facing ender dragon head

I can't figure out what is the real problem?
Anything except skull of player can be recorded properly.
Is it wrong with sk-yaml or wrong with skript itself?

**Comment by TUCAOEVER** [comment]
I am using skript v2.3.7 on 1.12.2 Paperspigot.

**Comment by ShaneBeee** [comment]
First of all, thats not a bug, that is how yaml saves Items, I'm not exactly sure what you are trying to save it as though, but that looks right to me.

Second, this is a bug tracker for the Skript plugin, your issue has nothing to do with Skript, it has to do with skript-yaml

**Comment by TUCAOEVER** [comment]
Why? Everything but skull item can't be recorded.
I think it's wrong with item type of 'skull of player'
it's not an item which i can't use yaml to record.

**Comment by TUCAOEVER** [comment]
When i have skull in my hand and everything is okey.
But i can't record directly via using skull of player

**Comment by TUCAOEVER** [comment]
> First of all, thats not a bug, that is how yaml saves Items, I'm not exactly sure what you are trying to save it as though, but that looks right to me.
> 
> Second, this is a bug tracker for the Skript plugin, your issue has nothing to do with Skript, it has to do with skript-yaml

Why? Everything but skull item can't be recorded.
I think it's wrong with item type of 'skull of player'
it's not an item which i could use yaml to record.
