### ISSUE TITLE
Clay ball

### ISSUE THREAD

**Issue by Pitircinky** [SkriptLang/Skript#2295]
Skript 2.3.7
Spigot 1.12.2
`format slot 11 of player with clay ball named "&7" to be unstealable`

[17:57:56 ERROR]: Can't understand this condition/effect: format slot 11 of player with clay ball named "&7" to be unstealable (test.sk, line 12: format slot 11 of player with clay ball named "&7" to be unstealable')
So I need item ID's for skript.

**Comment by Blueyescat** [comment]
It exists in the aliases for 1.12.2, so should work: https://github.com/SkriptLang/skript-aliases/blob/master/misc.sk

You are *trying to use* gui codes of the skQuery addon, but **no** using skQuery for guis is insecure, broken, not supported at all. You should use TuSKe for GUIs: https://github.com/Tuke-Nuke/TuSKe/wiki/GUI-Manager

**Comment by Pitircinky** [comment]
`old items:
	minecraft version = 1.12.2 or older
	charcoal = minecraft:coal {Damage:1}
	sugar cane¦s = minecraft:reeds
	**clay [ball¦s] = minecraft:clay**
	popped chorus fruit¦s = minecraft:chorus_fruit_popped
	nether brick item¦s = minecraft:netherbrick
`
give player 1 clay balls
give player 1 clay ball
give player 1 clay_ball

clay still won't work and I will use TuSKe thanks.

**Comment by Blueyescat** [comment]
What does it say when you hold a clay ball and run `send "%tool%"`? 

This may fix it as a workaround:
```vb
aliases:
    clay [ball¦s] = minecraft:clay
```
add to top of your script

**Comment by Pitircinky** [comment]
this code fixed my error.
`clay [ball¦s] = minecraft:clay_ball `
%tool% = CLAY_BALL
But now skript send me everything twice times.

**Comment by bensku** [comment]
Consider using Skript 2.4.

**Comment by TheBentoBox** [comment]
I believe this actually is an issue in the aliases; it appears I mistakenly used just `clay` for pre-1.13 when the ID for balls was actually always `clay_ball` and the block was always `clay`. An annoying point of confusion.

Just fixed this [here](https://github.com/SkriptLang/skript-aliases/commit/5ac409d03dcef8760fdeaf047e9748dbdc5e5401) for next release.

**Comment by HYPExMon5ter** [comment]
This should be closed, it was fixed in beta6
