### ISSUE TITLE
IllegalAccessException on Skript enable

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2297]
### Description

On Skript enable, the following error gets thrown up by the server in the logs
https://pastebin.com/7bkwY6EC

### Steps to Reproduce

Just load up a server with Skript 2.4-alpha4

### Expected Behavior

No error to be thrown by the server

### Errors / Screenshots

Error listed above

### Server Information
* **Server version/platform:**       Spigot-1.14.3
* **Skript version:**                Skript 2.4-alpha4

**Comment by ShaneBeee** [comment]
`Skript version: Skript 2.4-beta4` <-- ???
There is not beta4, maybe that is your issue?!?!

**Comment by APickledWalrus** [comment]
Definitely looks like they made it their self or got it from someone.

Version is "2.4 alpha4" according to the log.

**Comment by Wealthyturtle** [comment]
Uhhhh might be the host side... I’ll get back to this issue

**Comment by ShaneBeee** [comment]
Test this with an actual, supported version of Skript, self-built versions are not supported in the issue tracker.

**Comment by Wealthyturtle** [comment]
Unable to replicate on a fresh build, sorry
