### ISSUE TITLE
Co-ordinates Not Working

### ISSUE THREAD

**Issue by BurntValentine** [SkriptLang/Skript#2300]
### Description
Co-ordinates of a location/event not correct  (may be a death event issue)

### Steps to Reproduce
Script: https://gist.github.com/BurntValentine/2898ba7cdf49a72e2322621ca411d8a6
Check your co-ordinates and kill yourself. The X co-ord given is correct but the Y is null and the Z is way off

### Expected Behavior
Correct co-ordinates given for where the event took place

### Errors / Screenshots
Co-ords where I was before I killed myself: https://i.gyazo.com/416179233c07d220182c91b8b4110235.png
Message given in chat that has the incorrect co-ordinates: https://i.gyazo.com/df1fe626a41cec07614a3f2f63bcdad6.png

### Server Information
Server version/platform: Spigot 1.13.2
Skript version: 2.4beta3

**Comment by Wealthyturtle** [comment]
Any logs? Unable to replicate using Spigot 1.14.4 / Skript 2.4-beta5

![image](https://user-images.githubusercontent.com/19924575/63207157-b81cec80-c0f3-11e9-93dc-3275fce64da9.png)

**Comment by BurntValentine** [comment]
Whatever changes were made in beta4/5 seem to have fixed this, so this issue is resolved
