### ISSUE TITLE
NPE when using loop-value in a date list

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2302]
### Description

When having a date list, and looping through the date list and getting the difference between now and loop-value, an NPE will occur upon skript parse.

### Steps to Reproduce

```
command /test:
    trigger:
        loop {list::*}:
            send "%difference between now and loop-value%"
```

### Expected Behavior

For an NPE to not be thrown on skript parse

### Errors / Screenshots

https://pastebin.com/HqprGYjk

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta3

**Comment by TPGamesNL** [comment]
AFAIK this occurs when one of the 2 expressions has `Object` as their return type (not as a variable), such as:
`set {_x} to difference between (metadata "test" of player) and (metadata "test" of player)`
or 
`set {_x} to difference between 1 and loop-value`
