### ISSUE TITLE
null error

### ISSUE THREAD

**Issue by JJJJYO** [SkriptLang/Skript#2303]
### Description

I don't know what is wrong
It doesn't have any errors on console
### Errors / Screenshots

![image](https://user-images.githubusercontent.com/49342156/61930956-4650f780-afba-11e9-9802-9fdbb191ff69.png)

```send "%player% %player% %player% %player% %player%"```
### Server Information
* **Server version/platform:**        1.13.2/spigot
* **Skript version:**                2.4-beta3

### Additional Context

I think it is big error.

**Comment by antoinech2** [comment]
Same problem in Minecraft 1.14.4 with Skript 2.4-beta3. This is very strange, look:
![image](https://user-images.githubusercontent.com/42295406/61943084-03335c00-af9b-11e9-8e50-374d1141ef7d.png)

**Comment by TrademarkTM** [comment]
I can confirm it for beta3 and 1.14.4.

**Comment by antoinech2** [comment]
hope that it will be quickly fixed! 
I cannot do anything until this bug is fixed ;(
