### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by ham1255** [SkriptLang/Skript#2305]
### Description

It would be nice since it have good performance and stuff getting saved in json-like document

**Comment by Matocolotoe** [comment]
Duplicate of #1787

**Comment by ham1255** [comment]
this as reminder? cause that post was created in Jan 2

**Comment by Wealthyturtle** [comment]
Still a duplicate, you could make a comment in the original

**Comment by bensku** [comment]
Some issues sit waiting for years, usually because they depend on very large reworks of Skript.
