### ISSUE TITLE
NPE when clicking outside of an inventory

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#2306]
This bug was fixed in 2.3.6 but occurs with the latest version of Skript (beta3)
( I didn't test earlier version )

Error:
https://pastebin.com/cdb73MHb

Skript version: 2.4beta3
Mc version: 1.14.4 paperspigot

Code: (It's only this part as air doesn't return null or whatever the mistake on 2.3.6 was)

```
on inventory click:
	event-inventory != player' inventory
	event-slot != air
```

**Comment by TheBentoBox** [comment]
I can confirm this and while it's pretty harmless it's really annoying and spams console.

**Comment by Wealthyturtle** [comment]
Did some quick testing and it seems like the index parsed to getItem() from the ch.njol.skript.util.slot.InventorySlot class is -999 for some reason

**Comment by FranKusmiruk** [comment]
This was fixed at some point.

@Wealthyturtle that's the "slot" Minecraft states as nothing.

**Comment by Blueyescat** [comment]
@FranKusmiruk 
> This bug was fixed in 2.3.6 but occurs with the latest version of Skript (beta3)

**Comment by Wealthyturtle** [comment]
Yeah... I got -999 on the latest version of Skript

**Comment by FranKusmiruk** [comment]
Whoops, missed that, sorry.
