### ISSUE TITLE
After last update broken reloading script and error on start

### ISSUE THREAD

**Issue by Mr-Vuda** [SkriptLang/Skript#2307]
https://pastebin.com/JRM6PrsN
http://prntscr.com/ol24pn

When o do /sk reload any script, it just sends this errors and stops the server. And at start i have that error from prtscr

**Comment by awaffle1** [comment]
Which version are you talking about? The latest stable (2.3.7) or the latest beta release?

**Comment by Matocolotoe** [comment]
About the log handler error, try using skript-mirror 2.0.0 : https://circleci.com/gh/btk5h/skript-mirror/3#artifacts/containers/0 (Perhaps it can fix the other one too ?)

**Comment by TheBentoBox** [comment]
Did not follow the template, no idea what Skript version or add-ons you are using. Please ensure you're using skript-mirror 2.0 as mentioned above and if you have this issue again you can report it while actually following the bug report template. It's there for a reason.
