### ISSUE TITLE
Duplicate Aliases Stored

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2308]
### Description

When running a Memory Analysis on my server, I found that Skript Aliases were taking up 49.6MB in 1.2M objects
![image](https://user-images.githubusercontent.com/19924575/62006649-1bab9e00-b176-11e9-8c91-ce7ebf2fc095.png)
![image](https://user-images.githubusercontent.com/19924575/62006651-25350600-b176-11e9-8371-6cf4f8e39536.png)

Odd thing is that some aliases are duplicated many times
![image](https://user-images.githubusercontent.com/19924575/62006655-32ea8b80-b176-11e9-9bb3-b0e1f59a2605.png)
![image](https://user-images.githubusercontent.com/19924575/62006657-3b42c680-b176-11e9-8784-a70a9f5c3f2a.png)
![image](https://user-images.githubusercontent.com/19924575/62006658-43026b00-b176-11e9-988a-83c4d28fff0d.png)

May not be a large bug, but seems inefficient to have 1.4k copies of trapdoors stored

### Steps to Reproduce

Just run a server with Skript, and then dump the heap after it's done with loading

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta3

### Additional Context

Used Eclipse Memory Analyser

**Comment by TheBentoBox** [comment]
Really strange that some of the trapdoors are storing more dupes than others too.

The aliases should be guarding against storing duplicate entries like this.

**Comment by bensku** [comment]
I investigated this, and found no obvious memory leaks. Still, I managed to optimize a bit.

Let's look at those duplicate Minecraft id strings first. JVM string deduplication should take care of most of the overhead, but not all of it. I've applied String.intern() on them, which might help a bit.

I've implemented deduplication, which removes most of unnecessary memory usage. Still, there are many aliases; they do consume quite a lot of memory.

**Comment by bensku** [comment]
New release with my changes is out. Does it help with memory usage, @Wealthyturtle?

**Comment by Wealthyturtle** [comment]
@benksu will get back to you in 24 hours :)

**Comment by Wealthyturtle** [comment]
![image](https://user-images.githubusercontent.com/19924575/62435121-a8092280-b76d-11e9-9fc8-af40f692d60e.png)
![image](https://user-images.githubusercontent.com/19924575/62435139-b5bea800-b76d-11e9-87dd-cf6dbc7721ca.png)
Can confirm that it's been optimized! @bensku 

By the way, please check out #2246 :/

**Comment by bensku** [comment]
Accidentally tagged this instead of #2396
