### ISSUE TITLE
Play sound not working

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2310]
Version:
[Skript] Enabling Skript v2.4-beta4

This gives an error:
play "BLOCK_ANVIL_PLACE" to {_p} at volume 1 with pitch 1.7

Error:
https://i.imgur.com/adsiRzM.png

**Comment by Blueyescat** [comment]
The syntax is
```autohotkey
play sound[s] %strings% [(in|from) %soundcategory%] [(at|with) volume %number%] [(and|at|with) pitch %number%] [(to|for) %players%] [(at|from) %locations%] 
```

You should check whether the code is actually correct before sending a bug report. Probably you used an add-on before.
