### ISSUE TITLE
Loop enchantments no longer working

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2311]
Version: Enabling Skript v2.4-beta4

My skript:

```
loop all enchantments of {_item1}:
			add "%loop-value% %enchantment level of loop-value of {_item1}%" to {_enchants1::*} 

```
Error:
https://i.imgur.com/zhi2jJM.png

Worked in 1.13.2 just fine.

**Comment by Blueyescat** [comment]
The syntaxes are
```autohotkey
[the] enchantments of %itemtypes% 
%itemtypes%'[s] enchantments 
```

You should check whether the code is actually correct before sending a bug report. Probably you used an add-on before.
