### ISSUE TITLE
A config option doesn't seem to work properly

### ISSUE THREAD

**Issue by Maoman1** [SkriptLang/Skript#2312]
EDIT: I don't know how but it suddenly started working again. I didn't change the bit in the options nor did I change how I use {@Prefix}

### Description
At the start of my script I have
```
options:
  Prefix: &b[MaoChat]&r
```
and later I have
```
send "{@Prefix} <some message>" to player
```
but in chat it just says "{@Prefix}" rather than replacing it with [MaoChat]

There is no error in console

Screenshot:
https://i.imgur.com/U0In1qG.png

### Server Information
* **Server version/platform:**       PaperSpigot 1.14.4
* **Skript version:**                2.4 beta4

Other Notes:
I'm new to skript and thought I was simply doing it wrong but Blueyescat in the skripthub discord server said this should be reported as a bug

**Comment by TheBentoBox** [comment]
This could be a huge problem if it is happening inconsistently.

**Comment by bensku** [comment]
Can't think why this might happen. Options are replaced before any parsing is done, so can't be new chat system changes.

**Comment by Wealthyturtle** [comment]
Closing this issue as I can't replicate this either, tried weird cases too.
