### ISSUE TITLE
remove item from player problem

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#2313]
### Description
`remove 64 salmon from player` but this delete only one salmon.

### Server Information
* **Server version/platform:**       Paper 1.14.4
* **Skript version:**               2.4-beta4

**Comment by bolleboor** [comment]
Strange.
I'm unable to confirm this in 1.12.2 but haven't checked for 1.14.4.
Maybe try 

`remove 64 salmon from player's inventory`

**Comment by OverBrave** [comment]
It works when I get the syntax of `player's inventory` but it doesn't work as I mentioned above.

**Comment by OverBrave** [comment]
Not working on 1.14.4

**Comment by Wealthyturtle** [comment]
@overbrave Try

remove 64 from item amount of salmon

**Comment by OverBrave** [comment]
Not working.

**Comment by ilsubyeega** [comment]
Ok, i have similar problem.

### Steps to Reproduce

```
command r1:
	trigger:
		remove 1 of diamond from player's inventory
command r64:
	trigger:
		remove 64 of diamond from player's inventory
```

### Expected Behavior

r1 command should remove 1 of diamond, r64 command should 64 of diamond

### Errors / Screenshots
There is no errors in console
https://youtu.be/D-hvSbVQ7o8 (Recorded)

### Server Information
* **Server version/platform:**  git-Paper-1618 (MC: 1.12.2)     
* **Skript version:** 2.4-beta4

**Comment by OverBrave** [comment]
Exactly!

**Comment by Matocolotoe** [comment]
Can confirm, doesn't remove any item.

**Comment by Matocolotoe** [comment]
Also, `remove all salmons from player` doesn't remove anything

**Comment by iOshawott** [comment]
It's with all items... This version of skript should be removed from download section or smth ;-; or add a note it's not usable :| 
alpha-4 for ever! beta is bugged a lot

**Comment by bensku** [comment]
It is not a stable release for a very good reason.
