### ISSUE TITLE
incompatible with Skellett ?

### ISSUE THREAD

**Issue by Zzheyd** [SkriptLang/Skript#2314]
Hi here,

i'm runing on paper 1.14.4, i cant use Skellett with Skript, is normal ?

When i put Skellett on my server, after rester anybody cant log on server, same on local test with ONLY Paper/Skript/Skellett

https://cdn.discordapp.com/attachments/598042593447641088/605441577430679562/sklt.JPG

I need Skellett for many reason .... for "if "%fishing state%" is "CAUGHT_FISH"" for example ......

Or maybe did you have Skellett like to use with 1.14.4 and new sript version :/

Thank you

**Comment by Blueyescat** [comment]
This issue tracker is only for Skript, not any addon.

fyi Skellett is dead, its author works on a new version but it is also inactive.

**Comment by TheBentoBox** [comment]
As Blue said, issues with add-ons should be reported to their authors. We're not responsible for upkeeping them.
