### ISSUE TITLE
(Suggestion) make skript (run) on 1.8

### ISSUE THREAD

**Issue by andrei923** [SkriptLang/Skript#2318]
I'm aware that skript does not support 1.8 and is not going to.
But I think we should be a able to use the lastest(or a newer one, the last stable version that works on 1.8 is dev36 and lots of things have been added/fixed in the new versions), will be great to use an official version on 1.8 .
Features that does not work on 1.8 should be disabled, ex.particles.

**Comment by Blueyescat** [comment]
https://github.com/SkriptLang/Skript/issues/847 close
