### ISSUE TITLE
Color reset after a variable

### ISSUE THREAD

**Issue by ilsubyeega** [SkriptLang/Skript#2319]
### Description

The color of the text after the variable is getting reset.

### Steps to Reproduce

```
command vvv:
	trigger:
		set {_method} to "CB"
		message "&aABC %{_method}% AAA"
		message "&aABC %{_method}% &aAAA"
```

run command /vvv and you will get messaged with
"&aABC CB&r AAA"
"&aABC CB &aAAA"

### Expected Behavior

First line should be "&aABC CB AAA" not "&aABC CB&r AAA"

### Errors / Screenshots

Video: https://youtu.be/TVC1BoIa63U
Screenshot:
https://imgur.com/a/DXkjOz7

### Server Information
* **Server version/platform:** git-Paper-1618 (MC: 1.12.2)       
* **Skript version:** 2.4-beta4

**Comment by bensku** [comment]
Some more fallout from chat security updates. Implementing this is unfortunately not trivial.

**Comment by aescraftbr** [comment]
Looks like it's a two way issue:

The color, if set by a coloured variable, won't be reseted after the variable, EVEN if you use &r or §r to reset it.

`command /testcolorerror:
  trigger:
    set {_X} to colored "&1XXX"
    set {_Y} to colored "&2XXX"
    set {_Z} to colored "&3XXX"
    message "| %{_X}% §r| %{_Y}% §r| %{_Z}%"`

The first "|" will not be coloured
But the second "|" will have the {_X}'s colour, and the third "|" will have the {_Y}'s colour, even with the &r (reset) code.

Others confirm:
![error](https://user-images.githubusercontent.com/25469900/62495003-27691700-b7ab-11e9-8c32-05e30f75aa36.png)

**Comment by iOshawott** [comment]
Oh my god, all my skripts needs to be redone because of this ;-;

**Comment by FranKusmiruk** [comment]
@aescraftbr just to be sure, can this be tested using Skript's chat codes (i.e.: `<reset>`) instead of raw format?

**Comment by Govindass** [comment]
this is pretty much the last bug in Skript which is truly disturbing to me, I hope it gets fixed soon!

**Comment by Matocolotoe** [comment]
Please fix this...

**Comment by Govindass** [comment]
> Please fix this...

you can use workaround:
send formatted "message"
instead of normal send, or send colored if you don't need format.

**Comment by Matocolotoe** [comment]
oh thank you so much <3
