### ISSUE TITLE
Reload percent of script 

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2320]
Welcome. I have a suggestion.
on script reload:
    reload 50 percent of script
    wait 2 ticks
    reload 50 percent of script
It should reload script with wait to do not lag the server if code is long.

**Comment by HYPExMon5ter** [comment]
That’s a terrible idea, recoding the parser to be faster and more reliable would be better but that’s already planned and won’t happen for a long time because of how long it’ll take
