### ISSUE TITLE
Setting n lists to a given one will set the n-th list to the n-th object

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2321]
### Description

When setting two list variables to the same list variable, something really weird happens.

### Steps to Reproduce

Using the following, `{_a::*}` becomes `One` and `{_b::*}` becomes `Two`
```
function test(t: texts):
	set {_a::*} and {_b::*} to {_t::*}
	broadcast "%{_a::*}%"
	broadcast "%{_b::*}%"

command /test:
	trigger:
		set {_u::*} to "One", "Two" and "Three"
		test({_u::*})
```

Using the following, both `{_a::*}` and `{_b::*}` will both be `One, Two and Three`
```
function test(t: texts):
	set {_a::*} to {_t::*}
	set {_b::*} to {_t::*}
	broadcast "%{_a::*}%"
	broadcast "%{_b::*}%"

command /test:
	trigger:
		set {_t::*} to "One", "Two" and "Three"
		test({_t::*})
```

### Expected Behavior

When using the first code example, the lists `{_a::*}` and `{_b::*}` should both be equal to `{_t::*}`

### Errors / Screenshots

No errors

### Server Information
* **Server version/platform:** Spigot 1.14.4      
* **Skript version:** beta4               

### Additional Context
It seems like Skript doesn't create two copies of the given list (here `{_t::*}`) but puts the value of the n-th object in the given list into the n-th new list.
If we add another list (according to the following code):
- `{_a::*}` becomes `One`
- `{_b::*}` becomes `Two`
- `{_c::*}` becomes `Three` which is the 3rd object of the list.
```
function test(t: texts):
	set {_a::*}, {_b::*} and {_c::*} to {_t::*}
	broadcast "%{_a::*}%"
	broadcast "%{_b::*}%"
	broadcast "%{_c::*}%"

command /test:
	trigger:
		set {_t::*} to "One", "Two" and "Three"
		test({_t::*})
```

Also happens with 4 objects and 4 lists.

**Comment by TPGamesNL** [comment]
Fixed in #3823
