### ISSUE TITLE
Setting a list to another doesn't keep indices

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2322]
```
command /test:
    trigger:
        set {_list::a} to 1
        set {_list::b} to 2
        set {_list::c} to 3
        set {_newlist::*} to {_list::*}
```
Now the list indices are just 1, 2, 3, etc. so for example `newlist::1` instead of `newlist::a`
The following workaround can be used, but it's still annoying.
```
loop {_list::*}:
    set {_newlist::%loop-index%} to loop-value
```

**Comment by bensku** [comment]
Unfortunately, accessing a list variable with '::*' only produces values. This needs a new variable system to fix.

**Comment by Wealthyturtle** [comment]
Closing in favor of #3127
