### ISSUE TITLE
Feature Request: Is alphanumeric

### ISSUE THREAD

**Issue by Farwl** [SkriptLang/Skript#2324]
I think there should be a condition to check if a string is alphanumeric. (Containing only letters and numbers)

```
chat:
    message is alphanumeric:
        send "Message is alphanumeric"
```

**Comment by Vrganj** [comment]
You can use regex for now, I guess...

**Comment by Farwl** [comment]
Yeah I do, but it would be better to have a condition for it.

**Comment by Vrganj** [comment]
Skript-mirror ¯\_(ツ)_/¯

**Comment by Farwl** [comment]
I'm on Minehut :P

**Comment by Vrganj** [comment]
Well, then use regex. I don't know why I even commented in here.

**Comment by TrademarkTM** [comment]
TuSKe has some RegEx expressions you can use.

**Comment by FranKusmiruk** [comment]
Regex is something that I wouldn't want in Skript for a variety of reasons, it's better for it to be in an addon rather than Skript itself.

We could implement this condition though.

**Comment by Blueyescat** [comment]
@FranKusmiruk some example reasons?

**Comment by Wealthyturtle** [comment]
@bensku please close this enhancement, was added in beta6 :)
