### ISSUE TITLE
Send to specific player

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2325]
Hello. A suggestion. Send "" to specific player. e.g
command /send:
    trigger:
        send "" to Sebastian_Z_GTA
I'm doing a survival and I don't want to let friend get the message which need to be send to me. We do not use permission plugin. And I don't have idea what to write to let send to me specific message.

**Comment by Vrganj** [comment]
Don't post that in issues. This isn't an issue, it's just a question.
```vb
command send:
    trigger:
        send "" to "Sabastian_Z_GTA" parsed as player
```

**Comment by Misio12320** [comment]
does not send wow congrats.

**Comment by TPGamesNL** [comment]
You should check the name in the code, it's different from your message.
If that doesn't work, use parentheses: `send "" to ("Sebastian_Z_GTA" parsed as a player)`

**Comment by Misio12320** [comment]
Why this is soo hard?... Ok thanks
