### ISSUE TITLE
loop-number/integer not an actual Skript integer

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2326]
### Description

The expressions `loop-number` and `loop-integer` (as well as `loop-value` if the value is an integer) are not usable as integers in function parameters

### Steps to Reproduce

```
function test(i: integer):
	# Some code

command /test:
	trigger:
		loop 10 times:
			test(loop-integer)
			test(loop-number)
			test(loop-value)
```

### Expected Behavior

No error should appear

### Errors / Screenshots

The 1st argument given to the function 'test' is not of the required type integer. Check the correct order of the arguments and put lists into parentheses if appropriate (e.g. 'give(player, (iron ore and gold ore))'). Please note that storing the value in a variable and then using that variable as parameter will suppress this error, but it still won't work. (test.sk, line 8: test(loop-number)')

### Server Information
* **Server version/platform:** Spigot 1.14.4      
* **Skript version:** 2.4-beta4              

### Additional Context

Skript's "integers" being longs, `loop-number` is an actual integer and thus is not of type long. Also, this error didn't occur in 2.2.

**Comment by Vrganj** [comment]
You shouldn't use integers in skript

**Comment by Matocolotoe** [comment]
> Also, this error didn't occur in 2.2.

**Comment by Vrganj** [comment]
It doesn't matter if it occured before. You shouldn't use integers

**Comment by Matocolotoe** [comment]
This is still a valid issue.

**Comment by FranKusmiruk** [comment]
>It doesn't matter if it occured before. You shouldn't use integers

Doesn't change the fact that this error shouldn't appear when the input is expected to be an integer.

Also, try to be a bit more polite in the issue tracker, there's no need to say it like this.
