### ISSUE TITLE
Fishing Rod attacker and tool

### ISSUE THREAD

**Issue by korhox** [SkriptLang/Skript#2327]
### Description
Using skript:

```
on damage:
	send "%attacker% attacks %victim% with %attacker's tool%" to victim
```

will result message:
<none> attacks korho with <none>

when attack item is fishing rod or damage is generally fall damage.

When mob or player attacks, message is displayed riht, eg.
spider attacks korho with air
or
zombie attacks korho with iron sword

### Steps to Reproduce

1. Install skript:
```
on damage:
	send "%attacker% attacks %victim% with %attacker's tool%" to victim
```

2. Get someone to trow fish hooks to you
### Expected Behavior

I expected that I would get message:
Blebq attacks korho with fishing rod

(When attacker is player Blebq)
(or fishing rod is fishing rod hook, etc)
### Errors / Screenshots

No errors

### Server Information
* **Server version/platform:** Paper version git-Paper-156 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)       
* **Skript version:** Skript version 2.4-beta4

**Comment by Wealthyturtle** [comment]
I don't think fishing rod reeling does any damage? All it does is pull your victim closer to you, which may result in fall damage if done at a distance. Unless you mean by actually using a fishing rod as a weapon by left-clicking, in which case still works.

![image](https://user-images.githubusercontent.com/19924575/66570471-3b146d80-eba0-11e9-9e0c-b9b88daf6862.png)

**Comment by TheBentoBox** [comment]
Hooking an entity with a fishing rod is not an attack or damage event and thus should not fire the damage event.
