### ISSUE TITLE
arg color and special code doesn't have use on 2.4-BETA4

### ISSUE THREAD

**Issue by Command1264** [SkriptLang/Skript#2329]
### Description
when i use arg color or special, it doesn't have use.

### Steps to Reproduce
command /autobroadcast [< text >] [< text >]:
	permission: {@權限}
	permission message: {@開頭}&c你沒有權限使用此指令
	executable by: players and console
		trigger:
		if command sender is not the console :
			if arg-1 is "say" or "s":
				send "{@公告}%arg-2%" to all players
				send "{@公告}%arg-2%" to console
				stop

### Expected Behavior
Originally, the color and special code is to be used.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/50344708/62406461-ddcbd100-b5de-11e9-87d5-767e39fc061a.png)

### Server Information
* **Server version/platform:** 1.13.2
* **Skript version:**  2.4-beta4

**Comment by TPGamesNL** [comment]
Use https://skriptlang.github.io/Skript/expressions.html#ExprColoured

**Comment by Wealthyturtle** [comment]
Use ```send formatted``` instead of ```send```, it's a security fix :)

**Comment by Vrganj** [comment]
Why did you set command senders to players and console if you're checking if it's the console..?

**Comment by bensku** [comment]
This is intentional.
