### ISSUE TITLE
removing items from inventory not working properly

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#2330]
### Description
Can't remove more than 1 item from inventory

### Steps to Reproduce
command /cobble2:
	trigger:
		remove 10 cobblestone from player's inventory

### Expected Behavior
Should remove 10 cobble, but it's removing 1!

### Errors / Screenshots
none

### Server Information
* **Server version/platform:**      Paper-156 
* **Skript version:**    latest

**Comment by DavidVioMC** [comment]
This is a duplicate of #2313

**Comment by iOshawott** [comment]
I haven't seen it. okay closing
