### ISSUE TITLE
Right-click with block toggles door and places block

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#2331]
### Description

With this skript:
```
on rightclick on iron door:
	toggle the block

on rightclick on iron trapdoor:
	toggle the block
```
door is toggled and block in hand is placed.

### Steps to Reproduce

Rightclick on lower half of door. The door is toggled, but the block in hand is also placed.

### Expected Behavior

Door should toggle, but block should remain in hand.

### Errors / Screenshots

pre rightclick:
![2019-08-04_16 38 48](https://user-images.githubusercontent.com/17748923/62430914-7fcee480-b6d7-11e9-90de-88d7661f1aa8.png)
post right click:
![2019-08-04_16 39 06](https://user-images.githubusercontent.com/17748923/62430918-89f0e300-b6d7-11e9-912e-ee08c348f665.png)

### Server Information
* **Server version/platform:**       Spigot 1.3.2 final or 1.14.4 latest
* **Skript version:**                Skript 2.4-beta5

**Comment by TheBentoBox** [comment]
Why should the block remain in your hand? You're not cancelling the event. In vanilla Minecraft clicking an iron door like this will place the block as you can't open them with your hands. If you want to prevent that default behavior you need to cancel it.

**Comment by SlimeDog** [comment]
Of course. Thanks.
