### ISSUE TITLE
Reloading a Disabled Skript

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2332]
### Description

Reloading a Disabled Skript will throw a language error

### Steps to Reproduce

Create a disabled skript in the scripts folder, e.g. ```-test.sk```
Afterwards, run the command in console ```sk reload test```

### Errors / Screenshots

```
[Server thread/ERROR]: Invalid format string at 'skript command.reload.script disabled' in the english language file: <gold>%s<reset> is currently disabled. Use <gray>/<gold>skript <cyan>enable <red>%s<reset> to enable it.
[Server thread/INFO]: [Skript] Skript command.reload.script disabled
```

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta5

### Additional Context

```/sk enable test``` properly works

**Comment by ham1255** [comment]
message is even weird

**Comment by Matocolotoe** [comment]
Duplicate of #1269

**Comment by Wealthyturtle** [comment]
Oops duplicate of #1269
