### ISSUE TITLE
Skript Path Finding

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2334]
I want to suggest a feature: path finding.
Adding pathfinding abilities would allow many options and possibilities like Pets and stuff.

**Comment by Runakai1** [comment]
Some add-ons already have this feature

**Comment by Moderocky** [comment]
Paper has (recently) included some utilities for pathfinding and I think even multiple waypoint support.
I suppose that this functionality could be added to Skript in the future, but I'm not sure how they feel about paper-only features.

**Comment by TheBentoBox** [comment]
Could be useful one day. We have some paper-only features already.
