### ISSUE TITLE
All items in inventory expression doesn't return the correct value in loops

### ISSUE THREAD

**Issue by LenjoyOfficial** [SkriptLang/Skript#2340]
### Description
When I want to loop all the items in a chest inventory, and printing the values for debug,
it says the slot instead of the items.

### Steps to Reproduce
Type the command /test:
```
command test:
	trigger:
		open a chest inventory named "" with 2 rows to player
		set slot 0 of player's current inventory to dirt named "&aDirt"
		loop all items in player's current inventory:
			send "%loop-value%"
```
See the chat

### Expected Behavior
Prints out this in the chat: "dirt named "&aDirt""

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/47115878/62474218-b160b200-b7a2-11e9-88b3-6f168277d739.png)

### Server Information
* **Server version/platform:** CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)
* **Skript version:** v2.4-beta5

**Comment by TUCAOEVER** [comment]
loop-item instead of loop-value?

**Comment by LenjoyOfficial** [comment]
it prints the same

**Comment by bensku** [comment]
They can be compared againt items. Still, this is not intentional.

**Comment by LenjoyOfficial** [comment]
huh thanks i thought i did a mistake

**Comment by Runakai1** [comment]
The title is a bit misleading since %all items in player's [current] inventory% still works

**Comment by LenjoyOfficial** [comment]
ok but nobody will read only a title and test it as it is in the title

**Comment by Lakingsun** [comment]
1 of loop-value
