### ISSUE TITLE
Warn using date()

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2345]
### Description

When using the skript date() function, a warn for ```List is missing 'and' or 'or', defaulting to 'and'``` is thrown in the console

### Steps to Reproduce

```
command /test:
    trigger:
        set {_d} to date(1970, 1, 1)
        broadcast "Date: %{_d}%"
```

### Expected Behavior

For the data inside the date() function call to not be treated as a list

### Errors / Screenshots

```
[Server thread/INFO]: [Skript] Reloading test.sk...
[Server thread/WARN]: List is missing 'and' or 'or', defaulting to 'and': 1970, 1, 1 (test.sk, line 3: set {_d} to date(1970, 1, 1)')
[Server thread/INFO]: [Skript] Successfully reloaded test.sk.
>test
[Server thread/INFO]: Date: 1/1/70 12:00 AM
```
Date works properly, just that it throws an un-necessary warn

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta5

**Comment by HYPExMon5ter** [comment]
Did you even read the warning? Just use date(1970, 1 and 1)

**Comment by Matocolotoe** [comment]
The issue also happens when using any function (from Skript or Java with skript-mirror).
The problem is that function parameters were not behaving as a raw list of objects before...

**Comment by Wealthyturtle** [comment]
@HYPExMon5ter For the record, I'm following the **given example format**. https://github.com/SkriptLang/Skript/blame/19a2fa2a1ba1ea07c5382cd158cfb9ac0d5a1810/src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java#L369
```date(2014, 10, 1)```

**Comment by HYPExMon5ter** [comment]
Yeah that needs to be updated, but, the code I sent *should* eliminate that warning while still having the same outcome, I haven’t tested it though

**Comment by bensku** [comment]
Using 'and' for function parameters is not intentional.
