### ISSUE TITLE
Clickable message not working anymore

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2346]
Skript:
[Skript] Loading Skript v2.4-beta5

Code:
message "{@pre} &e<command:/guma edit %{_id}%>>> GUI %{_id}% BEARBEITEN <<"

Result:
https://i.imgur.com/XEdKldu.png

This worked in 1.13.2

**Comment by Laukage** [comment]
try <suggest command:/guma edit %{_id}%>

**Comment by bloggy** [comment]
> 
> 
> try <suggest command:/guma edit %{_id}%>

does not work

**Comment by Laukage** [comment]
you should be using "message formatted" for all json stuff.

**Comment by bloggy** [comment]
I don't know what you mean but my original script works just fine in 1.13.2 so I would like to know why it stopped working in 1.14.4. Either it's a bug or a feature but it's not stated anywhere so I better wait for a dev.

**Comment by Laukage** [comment]
use this:

message formatted "{@pre} &e<command:/guma edit %{_id}%>>> GUI %{_id}% BEARBEITEN <<"

**Comment by bloggy** [comment]
thank you. that works. Is it new? Or why the old syntax not working anymore?

**Comment by bensku** [comment]
Caused by #2198, a security issue.
