### ISSUE TITLE
Item with lore expression thows CCE when used with variables

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2347]
Another issue:

Code:

```
command /testi [<text>]:
	trigger:
		open virtual chest inventory with 3 rows named "test" to player
		set {_i} to 0
		set {_p} to player
		set {_item} to APPLE
		set {_name} to {_item}'s name
		add "test1" to {_lore::*}
		add "test2" to {_lore::*}
		loop 3 times:
			make a gui slot {_i} of {_p} with {_item} with name {_itemname} with lore {_lore::*} to run function Guma_BuySlot({_id},loop-number - 1,{_p})
			add 1 to {_i}
```

Error:
https://pastebin.com/XhaKSsPR

**Comment by bloggy** [comment]
replacing the {_item} in the make a gui slot effect with APPLE makes the code work.

**Comment by Runakai1** [comment]
This is not a skript issue. It's tuske

**Comment by bloggy** [comment]
Sure? How can I make the same with Skript?

**Comment by Wealthyturtle** [comment]
@bloggy GUIs are currently not within the realm of Skript, if it’s a Tuske bug report it to their author, not here.

**Comment by bloggy** [comment]
I don't know if it is a Tuske bug. And there is no active developer of Tuske I think. So no more GUIs in skript?

**Comment by Runakai1** [comment]
There are guis in vanilla skript. The Inventory name expression is just broken. Use skript mirror for that and everything should work fine. (Event.getView().getTitle() is "inventory name")
There is a tutorial about vanilla guis on the forum tutorial page (skunity)

**Comment by bloggy** [comment]
> 
> 
> There are guis in vanilla skript. The Inventory name expression is just broken. Use skript mirror for that and everything should work fine. (Event.getView().getTitle() is "inventory name")
> There is a tutorial about vanilla guis on the forum tutorial page (skunity)

I should wait for the devs to answer here because changing all my scripts would take me days ...

**Comment by Runakai1** [comment]
Imo you should just spend your time learning vanilla guis. Depending on an add-on that's most likely going to be abandoned or already is is not good

**Comment by Blueyescat** [comment]
You didn't actually show the error of the first code.
The second error is related to Skript.

**Comment by bloggy** [comment]
> 
> 
> You didn't actually show the error of the first code.
> The second error is related to Skript.
> 
> also why use skellett to open the inventory

Oh yeah I noticed it. I think the first error was fixed and not a Skript bug. I removed it for now. But the second issue still persists. I will no longer use skellett to open inventory (I use skript's feature now)

**Comment by bloggy** [comment]
Do you think you can fix this asap? I can not do anything because of GUIs not working ...

**Comment by Wealthyturtle** [comment]
Did a quick test:

- Name and Lore are set: No CCE
- Name is set, Lore isn't set: No CCE
- Name isn't set, Lore is set: CCE thrown
- Name and Lore aren't set: CCE thrown

Then, without the name and lore variables being set,

- Lore removed: No CCE
- Name removed: No CCE
- Lore and Name are removed: No CCE
- Lore and Name remain: CCE thrown

**Comment by ShaneBeee** [comment]
Just wanted to check in on this issue.
The last comment was back in September, 6 months ago, we've had several releases since then, just wanted to check in and see if this issue is still present.

**Comment by TPGamesNL** [comment]
Can confirm with 
```
set {_item} to apple
add "test" to {_lore::*}
set {_x} to {_item} with name {_NONE} with lore {_lore::*}
```
or `set {_x} to {_item} with name {_NONE} with lore {_NONE::*}` for the last line
error: https://pastebin.com/BVVhD5Ed
