### ISSUE TITLE
 Skript Bug - delete {var}

### ISSUE THREAD

**Issue by Zunoo** [SkriptLang/Skript#2352]
### Description
Hello i have little problem. If i set variables to save in database,  and after this i want to delete the variable with delete {var} . So it doesn't work , variable is still in the database.

### Steps to Reproduce
command /example:
	trigger:
		set {example} to true
		wait 5 seconds
		delete {example}

### Server Information
* **Server version/platform:**       git-Paper-1616 (MC: 1.12.2)
* **Skript version:**                 2.4-beta5

**Comment by Wealthyturtle** [comment]
@Zunoo If you mean by looking at the database file, the change is not instant... It'll take time to clear it from the database due to performance. If you do 
```
command /example:
trigger:
set {example} to true
wait 5 seconds
delete {example}
broadcast {example}
```
You should see in chat that it's ```<none>``` and not ```true``` if the value truly wasn't deleted.

**Comment by FranKusmiruk** [comment]
As the above user said, it isn't done at time since that would probably kill the server if you're doing it consequently. If I recall properly, variables are updated on a 5 minute interval and after server stops.
