### ISSUE TITLE
Object function parameter with a text default value causes severe error

### ISSUE THREAD

**Issue by ItzAtomikHD** [SkriptLang/Skript#2353]
### Description
If you create a function with a parameter of type `object` and you want to give it a default value of a string, it causes an error.

### Steps to Reproduce
Create a function with a parameter type object and a default value of a string.
```
function blah(s: object = "") :: text:
	return "%{_s}%"
	
command /test:
	trigger:
		set {_default} to blah()
		set {_custom} to blah("hey")
		broadcast {_default}
		broadcast {_custom}
```

### Expected Behavior
The default value to be applied when no parameter is passed.

### Errors / Screenshots
An error is thrown from Skript, but only when no parameter is passed.
https://gist.github.com/ItzAtomikHD/53307190bb80120bcc4316827892b0d8

### Server Information
* **Server version/platform:** Spigot 1.14.4-R0.1-SNAPSHOT
* **Skript version:** 2.4-beta5

**Comment by Matocolotoe** [comment]
This is because the object specified as a default value must be serialized to an actual string before. They fixed it for function parameters but not for default values like this.
