### ISSUE TITLE
Removing item from inventory ignores extra data on the item

### ISSUE THREAD

**Issue by PanGargamel** [SkriptLang/Skript#2354]
### Description
I found it impossible to remove only not enchanted items from the inventory.

### Steps to Reproduce
1. Install this script:
```
command /test:
	trigger:
		clear player's inventory
		give player diamond pickaxe
		give player diamond pickaxe of efficiency 1
		give player diamond pickaxe of efficiency 2
		
		set {_item} to "diamond pickaxe" parsed as item
		
		remove 3 of {_item} from player's inventory
```
2. Run `/test` as a player

### Expected Behavior
Only one pickaxe should be removed from inventory, as the {_item} variable contains the exact item, not itemtype. Instead, all 3 pickaxes are removed.

### Server Information
* **Server version/platform:**       git-Paper-134
* **Skript version:**                2.4-beta5

### Additional Context
In this issue I am assuming that `diamond pickaxe` and `diamond pickaxe of efficiency 1` are not the same things when parsed as `item` - at least that's what I found in the documentation:

> Unlike item type an item can only represent exactly one item

**Comment by PanGargamel** [comment]
I just also found out that this issue appeared in 2.4-beta5 version. In 2.4-beta4 the code above works properly and the issue is not present.

**Comment by Wealthyturtle** [comment]
Seems like it's removing an ```item type``` rather than an ```item```

**Comment by bensku** [comment]
I hope my quick fix doesn't break anything else.

**Comment by bluelhf** [comment]
@bensku How reassuring! :sweat_smile:
I'm sure it's fine.

**Comment by ruddeTR** [comment]
It was fixed in beta6 but appeared again in beta7. #2404
