### ISSUE TITLE
X of loop-value-1

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2357]
### Description

Using the ```X of item``` expression with the ```loop-value-1``` expression seems to cause some wierd glitch.

### Steps to Reproduce

```
command /test:
    trigger:
        set {_data::*} to dirt, stone, bone, rotten flesh and egg
        loop {_data::*}:
            set {_comp} to 1 of loop-value-1 #Using loop-value will work, removing X of expression works, but when both X of and loop-value-1 expressions are used, it breaks
            broadcast "%{_comp}%"
```
### Expected Behavior

```X of``` and ```loop-value-1``` should work together?

### Errors / Screenshots

```
[Server thread/INFO]: -1
[Server thread/INFO]: -1
[Server thread/INFO]: -1
[Server thread/INFO]: -1
[Server thread/INFO]: -1
```

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta5

**Comment by TUCAOEVER** [comment]
"%loop-value%" parsed as material

**Comment by Matocolotoe** [comment]
Why would you use loop-value-1 here ? No need to, so it is parsed as `(loop-value) - 1`

**Comment by Wealthyturtle** [comment]
Well, when I work with nested loops, I tend to call all the first loop's values as ```loop-value-1``` regardless of whether or not it's within the nested loop for the sake of clarity

**Comment by Matocolotoe** [comment]
That sounds really weird...

**Comment by Wealthyturtle** [comment]
Closing this issue since it's a mistake on my part.
