### ISSUE TITLE
skript2.4 within, between not work

### ISSUE THREAD

**Issue by Lakingsun** [SkriptLang/Skript#2358]
```
command /test:
    trigger:
        set {_loc1} to location 3 west 3 north 3 up player
        set {_loc2} to location -3 west -3 north -3 up player
        if player is between {_loc1} and {_loc2}:
            message "123"

command /test2:
    trigger:
        set {_loc1} to location 3 west 3 north 3 up player
        set {_loc2} to location -3 west -3 north -3 up player
        if player is within {_loc1} and {_loc2}:
            message "123"

command /test3:
    trigger:
        set {_loc1} to location 3 west 3 north 3 up player
        set {_loc2} to location -3 west -3 north -3 up player
        if player's location is within {_loc1} and {_loc2}:
            message "123"

command /test4:
    trigger:
        set {_loc1} to location 3 west 3 north 3 up player
        set {_loc2} to location -3 west -3 north -3 up player
        if player's location is between {_loc1} and {_loc2}:
            message "123"
```
It doesn't output "123"

**Spigot 1.14.4
Skript 2.4-beta5**

**Comment by LenjoyOfficial** [comment]
there isnt a space between "within" and {_loc1} try that

**Comment by JaydenJinx** [comment]
Try "location of player".

**Comment by Lakingsun** [comment]
> there isnt a space between "within" and {_loc1} try that

my typo

**Comment by Lakingsun** [comment]
> Try "location of player".

I tried but it doesn't print "213".

**Comment by JaydenJinx** [comment]
"3 meters" instead of "3"

**Comment by JaydenJinx** [comment]
"above" instead of "up"

**Comment by JaydenJinx** [comment]
Also, try "add 3 to x-coord of {_loc1}".

**Comment by Lakingsun** [comment]
> Also, try "add 3 to x-coord of {_loc1}".

I changed it, but result is same

**Comment by JaydenJinx** [comment]
Test it with 'broadcast "%{_loc1}% %{_loc2}%"'

**Comment by JaydenJinx** [comment]
throw the player's location in there to prove that it actually is within those bounds

**Comment by Lakingsun** [comment]
> Test it with 'broadcast "%{_loc1}% %{_loc2}%"'

Output the coordinates I want

I do not speak English well, sry

**Comment by Lakingsun** [comment]
> throw the player's location in there to prove that it actually is within those bounds

```
command /test4:
	trigger:
		set {_loc1} to location 3 meters west 3 meters north 3 meters up player
		set {_loc2} to location -3 meters west -3 meters north -3 meters up player
		set block at {_loc1} to diamond block
		set block at {_loc2} to gold block
		if player's location is between {_loc1} and {_loc2}:
			message "123"
		else:
			message "2"
```
https://ifh.cc/g/eSAdw.jpg

**Comment by JaydenJinx** [comment]
It is okay. Try:

command /test:
    trigger:
        set {_loc1} to player's location
        set {_loc2} to player's location
        add 3 to x-coord of {_loc1}
        add 3 to y-coord of {_loc1}
        add 3 to z-coord of {_loc1}
        subtract 3 from x-coord of {_loc2}
        subtract 3 from y-coord of {_loc2}
        subtract 3 from z-coord of {_loc2}
        player's location is within {_loc1} and {_loc2}
        message "123"

**Comment by JaydenJinx** [comment]
I'm on my phone. Don't know how to format. Sorry.

**Comment by Lakingsun** [comment]
> I'm on my phone. Don't know how to format. Sorry.

if i use "within", i get an error. If i use "between", there is no error, but it does not work.

**Comment by Lakingsun** [comment]
> It is okay. Try:
> 
> '''
> command /test:
> trigger:
> set {_loc1} to player's location
> set {_loc2} to player's location
> add 3 to x-coord of {_loc1}
> add 3 to y-coord of {_loc1}
> add 3 to z-coord of {_loc1}
> subtract 3 from x-coord of {_loc2}
> subtract 3 from y-coord of {_loc2}
> subtract 3 from z-coord of {_loc2}
> player's location is within {_loc1} and {_loc2}
> message "123"
> '''

do not print "123"

**Comment by ham1255** [comment]
hmmm try this code
```
on script load:
 set {_loc1} to 5
 if {_loc1} is between 1 or 10:
  broadcast "yep {_loc1} is between 1 or 10"
```

**Comment by Lakingsun** [comment]
> on script load:
>  set {_loc1} to 5
>  if {_loc1} is between 1 and 10:
>   broadcast "yep {_loc1} is between 1 or 10"

it does work, but it is number
