### ISSUE TITLE
name of %inventory%

### ISSUE THREAD

**Issue by Lakingsun** [SkriptLang/Skript#2359]
### Description

When i print name of inventory, it print <none>
### Steps to Reproduce

```
on inventory click:
    message "%name of player's top inventory%"
```
### Expected Behavior

prints out name of top inventory
### Server Information
* **Server version/platform:**        1.14.4 Spigot
* **Skript version:**                 2.4beta5

**Comment by TPGamesNL** [comment]
Duplicate or #2069
