### ISSUE TITLE
"drop" effect doesn't work in "on death" event

### ISSUE THREAD

**Issue by PanGargamel** [SkriptLang/Skript#2365]
### Description
`drop` effect is not working when used in `on death` event.

### Steps to Reproduce
1. Install this script:
```
on death:
	drop 1 diamond
```
2. Kill any living entity

### Expected Behavior
One diamond should be dropped at location of killed entity, but it doesn't work.

### Server Information
* **Server version/platform:**       git-Paper-134
* **Skript version:**                2.4-beta5

### Additional Context
I tested this script also on 2.4-beta4 Skript version, it also doesn't work. The `drop` effect works well when used in `on mine` event.

**Comment by ShaneBeee** [comment]
I dont really think this is a bug, I think its always been like this, you need to specify where you are dropping the diamond (I think this is due to the fact that this event has multiple locations, ie: location of victim and attacker)
ex:
```vb
on death:
	drop 1 diamond at victim
```
this works fine

**Comment by PanGargamel** [comment]
Okay, that's right. I've been following an example at docs.skunity.com, which is apparently invalid.
Anyway, your code works. Thanks for your help!

**Comment by Blueyescat** [comment]
This is a bug. It should drop the item at the victim, because it is death event.
