### ISSUE TITLE
skript 2.4 within, between error

### ISSUE THREAD

**Issue by Lakingsun** [SkriptLang/Skript#2368]
### Description

"witihn" and "between" don't work
### Steps to Reproduce

```
command /test:
    trigger:
        set {_loc1} to location 3 west 3 north 3 up player
        set {_loc2} to location -3 west -3 north -3 up player
        if player is between {_loc1} and {_loc2}:
            message "123"

command /test2:
    trigger:
        set {_loc1} to location 3 west 3 north 3 up player
        set {_loc2} to location -3 west -3 north -3 up player
        if player is within {_loc1} and {_loc2}:
            message "123"

command /test3:
    trigger:
        set {_loc1} to location 3 west 3 north 3 up player
        set {_loc2} to location -3 west -3 north -3 up player
        if player's location is within {_loc1} and {_loc2}:
            message "123"

command /test4:
    trigger:
        set {_loc1} to location 3 west 3 north 3 up player
        set {_loc2} to location -3 west -3 north -3 up player
        if player's location is between {_loc1} and {_loc2}:
            message "123"
```
It doesn't outprint "123"
within = error  + not work
beteen = not work
### Expected Behavior

outprint "123"
### Errors / Screenshots

Can't compare a player with within {_loc1} and {_loc2}
Can't compare a location with within {_loc1} and {_loc2}

### Server Information
* **Server version/platform:**        1.14.4  spigot
* **Skript version:**                 2.4 beta5

**Comment by Lakingsun** [comment]
I tried printing the position variable and the value I want is displayed

**Comment by ShaneBeee** [comment]
isn't this the same as #2358 ?

**Comment by Lakingsun** [comment]
> isn't this the same as #2358 ?

I didn't report it as a bug.

**Comment by ShaneBeee** [comment]
> within = error + not work

the only `within` expression is as follows:
```vb
[(all [[of] the]|the)] blocks (within|between) %block% and %block%
```
this returns a list of all blocks, within a straight line between 2 blocks (not locations)
see [**here**](http://skriptlang.github.io/Skript/expressions.html#ExprBlocks)

> between = not work

```vb
%objects% (is|are) between %objects% and %objects%
```
this is checking if an object (the player) is between 2 other objects (your locations) but in this case its a straight line not a cuboid. 

Long story short, this isn't a bug, Skript just doesn't have the feature you are trying to use here.


Long story short, this isn't a bug, Skript just doesn't have a feature for checking between
