### ISSUE TITLE
Log Handler

### ISSUE THREAD

**Issue by DDuart** [SkriptLang/Skript#2369]
### Description
I'm trying to update server from 1.12.2 to 1.14.4

### Errors / Screenshots
https://pastebin.com/raw/R5D6AUfV

### Server Information
* **Server version/platform:**       1.14.4, paper
* **Skript version:**                2.4-beta5

**Comment by TPGamesNL** [comment]
This is caused by skript-mirror, not Skript: https://github.com/btk5h/skript-mirror/issues/110 (update to skript-mirror 2.x)
