### ISSUE TITLE
[1.12.2] Skript 2.4-beta5 not loading on 1.12.2

### ISSUE THREAD

**Issue by awaffle1** [SkriptLang/Skript#2372]
On 2.4-beta5, Skript will not load. It looks like it's a problem with 1.13 (and above) item names and 1.12 (and below) item names. Here's the error: https://pastebin.com/yDBMbSUN

**Comment by awaffle1** [comment]
Same error in 2.4-alpha3 ( #2137 ) where a issue where skript not loading in versions 1.12 and below should be fixed.

**Comment by awaffle1** [comment]
Latest stable 2.3.7, throws same error

**Comment by awaffle1** [comment]
Tested 2.4-beta5 on a 1.14.4 server, works fine

**Comment by APickledWalrus** [comment]
try deleting the materials.json or something like that when changing versions

**Comment by Blueyescat** [comment]
^ that happens when you downgrade your server version

**Comment by awaffle1** [comment]
> ^ that happens when you downgrade your server/mc version

Ok. I actually upgraded to 1.14.4, downloaded a new version of skript, and then downgraded to 1.12.2. Thanks.
