### ISSUE TITLE
on tab complete event

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#2374]
Add a `on tab complete` event, like the one in MundoSk. Mundo is splitting into different addons and none of them currently have this, and I feel this would fit good in vanilla skript.

**Comment by PanGargamel** [comment]
As far as I remember, SkQuery supports implementing tab completers (but there's still no `on tab complete` event).

**Comment by bensku** [comment]
Duplicate of #1600.

**Comment by HYPExMon5ter** [comment]
This isn’t really a duplicate, both are valid. Other issue is specifically for having it add player’s names as tab completions automatically, this is adding an event for cancelling, removing, and adding your own completions.
