### ISSUE TITLE
Player prefix/suffix support not working

### ISSUE THREAD

**Issue by midoublelo** [SkriptLang/Skript#2375]
### Description
Player prefixes and suffixes are not working. Skript doesn't understand the "set prefix" effect or the "player's prefix" expression. Skript also falsely identifies players as worlds in this scenario.

### Steps to Reproduce
command /testprefix [player]:
	trigger:
		set prefix of arg-1 to "test"

### Expected Behavior
The player's prefix would be set to 'test'.

### Errors / Screenshots
[Server thread/ERROR]: the 1st argument is not a world (testprefix.sk, line 3: set prefix of arg-1 to "test"')

### Server Information
* **Server version/platform:**      1.14 Spigot
* **Skript version:**                2.4-beta4

**Comment by Laukage** [comment]
Works on beta5, try updating :)

**Comment by bensku** [comment]
I would recommend the same.
