### ISSUE TITLE
Skript supported world gaurd in 1.14.4?

### ISSUE THREAD

**Issue by ham1255** [SkriptLang/Skript#2377]
problem is that tried every world guard 7 and skript keep complaining it's not compatible 
```
>.... [03:43:01 ERROR]: [Skript] An error occurred while trying to enable support for FAWE WorldGuard 7. WorldGuard region support has been disabled!
>.... [03:43:01 ERROR]: [Skript] Could not hook into WorldGuard. This can happen if Skript doesn't support the installed version of WorldGuard
```

**Comment by Matocolotoe** [comment]
Duplicate of #1796

**Comment by ham1255** [comment]
@Matocolotoe i am talking about world guard 7 here ._.

**Comment by Matocolotoe** [comment]
Well it is the same problem

**Comment by bensku** [comment]
It is not a same problem. Skript wouldn't explicitly tell you that region support has been disabled if it worked.

**Comment by ham1255** [comment]
> It is not a same problem. Skript wouldn't explicitly tell you that region support has been disabled if it worked.
didn't you fix the while ago?

**Comment by bensku** [comment]
Yes, I've updated Skript a few times due to WG API changes. I'm not sure when I have time to investigate that again.

**Comment by Wealthyturtle** [comment]
Closing in favor of #2674
