### ISSUE TITLE
Functions stick around after reload and disable

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2378]
### Description

Whenever you have a Skript that has a function, for instance ```a()```, and then subsequently **replace** ```a()``` with ```b()``` entirely with a Skript reload, calling ```a()``` would not result in any parse error

### Steps to Reproduce

Load this Skript first:
```
function a():
    a()
```

Afterwards, **replace** the previous Skript with:
```
function b():
    a()
```

No parse error will occur

### Expected Behavior

When using the Skript:
```
function b():
    c()
```
An error will be properly shown to the user
![image](https://user-images.githubusercontent.com/19924575/63169312-0afd9200-c069-11e9-8c85-36fcb471b308.png)

But in the above scenario, no such error is given

### Errors / Screenshots

Detailed above.

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta5

### Additional Context

@bensku since you have planned to redo Skript's function system, might want to fix this issue as well. Thanks! :)

**Comment by Matocolotoe** [comment]
Seems like some functions aren't cleared 🤔

**Comment by Wealthyturtle** [comment]
Yep, can confirm that also...

1. /sk reload test1
```
function a():
    a()
```

2. /sk disable test1

3. /sk reload test2
```
function b():
    a()
```

Will not throw any parse error

**Comment by bensku** [comment]
I'll try to make sure this is fixed in functions rework.
