### ISSUE TITLE
Tooltip with variables/expressions broken since 2.4-beta

### ISSUE THREAD

**Issue by TomYaMee** [SkriptLang/Skript#2379]
### Description
Tool tip does not work with variables/expressions in 2.4 beta
Tested with from beta-3 to beta-5. Reverting back to alpha-4 works fine.

### Steps to Reproduce
```
set {_test} to "test variable"
message "<tooltip:%{_test}%>Sda" to all players
```

```
message "<tooltip:%player%>Sda" to all players
```

### Expected Behavior
Expressions and variables to work in tooltip
Attached below is from alpha-4
![ExpressionAlpha](https://user-images.githubusercontent.com/1576097/63762156-ec16bf80-c8f4-11e9-9925-5505ef91d8ad.png)
![VariableAlpha](https://user-images.githubusercontent.com/1576097/63762204-051f7080-c8f5-11e9-9725-5e856ed0b9f8.png)

### Errors / Screenshots
Attached below is from beta-3 to beta-5
![Expression](https://user-images.githubusercontent.com/1576097/63762023-b4a81300-c8f4-11e9-9251-552d69562b04.png)
![Variable](https://user-images.githubusercontent.com/1576097/63761914-7dd1fd00-c8f4-11e9-8371-5efa7e47a2b1.png)

### Server Information
* **Server version/platform:**        git-Paper-167 (MC: 1.14.4)
* **Skript version:**                2.4-beta (All version)

**Comment by ham1255** [comment]
yep i confirm this too

**Comment by ham1255** [comment]
i think its related to this problem #2198

**Comment by ham1255** [comment]
@bensku

**Comment by FranKusmiruk** [comment]
@ham1255 there's no need to mention him, we all receive notifications for each issue in the tracker, he might just not have enough time to look into it.

**Comment by Malfrador** [comment]
Same problem with <tooltip:> 2.4-alpha4 is the latest version this works fine.

**Comment by TomYaMee** [comment]
@TheBentoBox This is from native Skript as its documented on the official documentation https://skriptlang.github.io/Skript/text.html

**Comment by TPGamesNL** [comment]
> @TheBentoBox This is from native Skript as its documented on the official documentation https://skriptlang.github.io/Skript/text.html

He was talking about the new line expression. 
Does the json work without it?

**Comment by TomYaMee** [comment]
> He was talking about the new line expression.
> Does the json work without it?

Ah, my bad misunderstood. Yeah the tooltip works without newline.
![image](https://user-images.githubusercontent.com/1576097/63704736-3a2cb400-c85e-11e9-945a-f7abb3720e65.png)

**Comment by iWanheda** [comment]
Also variables ^

**Comment by TomYaMee** [comment]
> Also variables ^

Can confirm variables are broken as well
![image](https://user-images.githubusercontent.com/1576097/63761056-0e0f4280-c8f3-11e9-9d06-8a5ee663785d.png) 
`message "<tooltip:%player%>Sda" to all players`

**Comment by TomYaMee** [comment]
Updated description to better reflect the issue. @TheBentoBox so after some more testing this seems to affect variables/expressions in general.

**Comment by TPGamesNL** [comment]
Sounds like that security fix is blocking too much. You can use the formatted expression, but I think this shouldn't be blocked.

**Comment by TomYaMee** [comment]
@TPGamesNL That worked, thanks! Seems like an intended feature made by #2215. Whoever has the same issue should refer to https://skriptlang.github.io/Skript/effects.html#EffMessage. Closing the issue now.

**Comment by StakeoutPunch** [comment]
I hate to dredge things up, but while I see that this is closed, what was the resolution? Tough luck to anyone that wants to use variables in json?

**Comment by TomYaMee** [comment]
> I hate to dredge things up, but while I see that this is closed, what was the resolution? Tough luck to anyone that wants to use variables in json?

Hey, you can refer to the link I have shared previously, you'll need to use the formatted expression for it to parse variables.

`message **formatted** 'Your message here'`
