### ISSUE TITLE
Please add Skript to craftbukkit

### ISSUE THREAD

**Issue by RajehTXD** [SkriptLang/Skript#2380]
Just please, add the skript into craftbukkit.

**Comment by Runakai1** [comment]
Just use spigot.

**Comment by RajehTXD** [comment]
do they work the same?

**Comment by RajehTXD** [comment]
i heard spigot is different

**Comment by RajehTXD** [comment]
does paper work too/
i heard of paper on the fourms and plugin sites.

**Comment by Wealthyturtle** [comment]
Bukkit/CraftBukkit is not supported by Skript
Spigot/Paper is supported by Skript

Simple as that

**Comment by JRoy** [comment]
Bukkit is not server software. It's the API that Craftbukkit, Spigot, and Paper implement. Bukkit is supported.

Craftbukkit, the server software, is not supported.
