### ISSUE TITLE
loop-value-X Detection

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2382]
### Description

When trying to subtract from a nested loop-value, the parsing of the minus symbol becomes glitchy

### Steps to Reproduce

```
command /test:
    trigger:
        loop 3 times:
            loop 3 times:
                broadcast "%loop-value-1-1%"
```
Will yield the following parse error:
![image](https://user-images.githubusercontent.com/19924575/63223623-2e504a80-c1eb-11e9-878c-6b1dccf9c3a8.png)

```
command /test:
    trigger:
        loop 3 times:
            loop 3 times:
                broadcast "%loop-value-1 - 1%"
```
Will yield the following parse error:
![image](https://user-images.githubusercontent.com/19924575/63223627-3e682a00-c1eb-11e9-9468-41882a9549d2.png)
This shows that Skript is trying to parse ```loop-value-X``` where ```X``` is the nested loop order in this case as ```X``` being ```1 - 1``` for some reason

### Expected Behavior

```
command /test:
    trigger:
        loop 3 times:
            loop 3 times:
                broadcast "%(loop-value-1)-1%"
```
Yields no parsing errors (intended behavior)

```
command /test:
    trigger:
        loop 3 times:
            loop 3 times:
                broadcast "%loop-value-1+1%"
```
Yields no parsing errors when performing addition instead of subtraction (no bracketing required at all for addition for some reason)
### Errors / Screenshots

Listed above.

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta5

### Additional Context

Skript should stop detecting the nested ```loop-value```'s order after it has hit a non-numeral character, like space characters or another minus symbol. Since at present it seems to break with these 2 characters, but work perfecting fine with the plus symbol.

**Comment by iWanheda** [comment]
You can fix that with ((loop-value-1) - 1)
