### ISSUE TITLE
Use one .csv file on multiple different servers

### ISSUE THREAD

**Issue by GlobooX** [SkriptLang/Skript#2386]
### Question
I try to set one .csv file for my 4 servers connected to BungeeCord.
When i set {test} variable to "true" on server 1 then on the others server variable {test} is still "none"

Please tell me how i can modify databases: (in config.sk) to connect all server to one variables file.
I try to use SQLite but when seccond server is started then i have this error "[Skript] database error: [SQLITE_BUSY]  The database file is locked (database is locked)"

**Comment by APickledWalrus** [comment]
You will have to use SQL if you want to use variables across multiple servers. Perhaps you are writing too many variables at once?

**Comment by GlobooX** [comment]
Heah, You have right but i need to have rly fast variable messaging cross 4 servers. MySQL with 1 seconds monitor-changes is not good idea with ~100k variables

**Comment by Pikachu920** [comment]
you can't point all your servers to a single csv

**Comment by GlobooX** [comment]
Ok, i cant use one csv file.. Is any solution to connect all variables cross server?

**Comment by APickledWalrus** [comment]
why do you have/need 100k variables?

**Comment by GlobooX** [comment]
~20 variables per player and almost 5k players from start to end edition of server.
5000 * 20

A lot of player variables i have stored in yml but some variables i need to have in csv or sqllite file. (Becouse i need use it rly fast between servers)

**Comment by bensku** [comment]
There is no good solution for this at the moment.
