### ISSUE TITLE
Rightclick event doesn't work with named items in 1.12

### ISSUE THREAD

**Issue by nurdism** [SkriptLang/Skript#2387]
### Description
"on rightclick with [item]" not working on 1.12.2

### Steps to Reproduce
```
on rightclick with dye:
	send "&cTEST"
```

### Expected Behavior
Should print "TEST" in chat but  does not

### Server Information
* **Server version/platform:**  1.12.2 (Spigot & Paper)
* **Skript version:**  Skript-2.4-beta5

[EDIT: Correct Issue](https://github.com/SkriptLang/Skript/issues/2387#issuecomment-523449138)

**Comment by TheAberto** [comment]
1.12.2 aliases are not good. Are you sure dye is right?
do send "%tool%"

or first, test with a simple item.

on rightclick with stone:

**Comment by nurdism** [comment]
did some more testing, seem named items aren't working

![image](https://i.imgur.com/VoMxfHJ.png)

```
on pickup:
	cancel event

on drop:
	cancel event

on join:
	wait 5 ticks
	clear player's inventory
	set slot 1 of player to gray dye named "Test"
	set slot 2 of player to gray dye

on rightclick:
	send "%tool%"

on rightclick with gray dye:
	send "&cTEST 1"

on rightclick with any dye:
	send "&cTEST 2"
```

**Comment by ham1255** [comment]
hmm try 
```
on join:
  broadcast "player's held item"
```

**Comment by TheAberto** [comment]
```
on click:
    type of tool is gray dye:```
