### ISSUE TITLE
Chat Bug with variables & color codes

### ISSUE THREAD

**Issue by Farwl** [SkriptLang/Skript#2388]
### Description
Using variables in text effects (ex. the send effect), will act as the reset color code. 

**Example;** 

**Code**
```send "&aYou found a chest! &e(%size of {chest.%player's uuid%::*}%/16)"```

**Outcome**
![image](https://user-images.githubusercontent.com/44182379/63455621-1e1eb200-c41b-11e9-937f-4274189c238f.png)

As mentioned above, everything after the variable gets reset. 

### Steps to Reproduce
Described above

### Expected Behavior
Text shouldn't be reset unless you use &r. The color code should make all the following text, that color.

### Errors / Screenshots
Shown above

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                2.4-beta5

### Additional Information
Now you could just add another color code, but in a different case (my case), this still needs to be fixed because I can't do some things with skript.

**Example;**

On my server, I have a skripted leveling system. 

I have a stats command to show your level.

Your level is also shown in the sidebar.

I use variable to represent different level "colors"

**Code**
```send "%{levelcolor::%arg-1's uuid%}%%{level::%arg-1's uuid%}%✫"```
Sends your level

The levelcolor variable is a color code. (It is set, I checked) But, since this bug exists, it doesn't matter what its set to, because the text following the variable, gets reset anyways.

![image](https://user-images.githubusercontent.com/44182379/63455930-c765a800-c41b-11e9-9525-68cac85b0d54.png)

So there's not really any simple in-game fix.

Would appreciate it if this could be fixed soon ;)

**Comment by Matocolotoe** [comment]
Duplicate of #2319

**Comment by Farwl** [comment]
Didn't see that.
