### ISSUE TITLE
on command is not working right

### ISSUE THREAD

**Issue by ham1255** [SkriptLang/Skript#2390]
### Description

on command is not working right. 
### Steps to Reproduce

first load this code to your server
```
on command "test1255" or "test1256":
	broadcast "&c&ltest Command was executed &a%command% "
```
then type command test1255 it should output 
![image](https://user-images.githubusercontent.com/34905970/63491091-65627c80-c4c7-11e9-801c-cd60064840a0.png)
but when doing test1256 ITS DOESN'T output anything!!!!
![image](https://user-images.githubusercontent.com/34905970/63491146-84610e80-c4c7-11e9-8440-2c4936b2345e.png)

### Expected Behavior

it should work like test1255
### Errors / Screenshots

No errors

### Server Information
* **Server version/platform:**      paper spigot 1.14.4[edited]
* **Skript version:**               Skript 2.4 beta5

**Comment by FranKusmiruk** [comment]
That's because you're using an `or` list, which means Skript will choose one of the elements in the list. If you want it to work for both of the commands, you must use an `and` list.

**Comment by ham1255** [comment]
shouldn't skript tell me that i use something wrong?
