### ISSUE TITLE
Why skript makes fun of me

### ISSUE THREAD

**Issue by ItzArty** [SkriptLang/Skript#2392]
Why...
I have this:
on damage:
    if victim is a player:
        if {godmode.%victim%} is set:
            if {godmode.%player%} is "yes":
                cancel event
skript suggests me to edit it to this:
on damage:
    if victim is a player:
        if {godmode.%victim%} is set:
            if {godmode.%victim%} is "yes":
                cancel event
skript suggests me to enter a valid entity

**Comment by DavidVioMC** [comment]
Your indentation is non existent.

**Comment by HYPExMon5ter** [comment]
Because there’s a victim and a attacker in a damage event, meaning there can be multiple players, so `player` shouldn’t be used in a damage event

**Comment by TheBentoBox** [comment]
The issue has been described to you. It's telling you what you've done wrong, not "making fun of you". 

In the future the skUnity forums/Discord or the Skript Chat Discord would be better places to ask questions you don't understand.
