### ISSUE TITLE
Using 'Contains' for List Variables

### ISSUE THREAD

**Issue by AsuDev2** [SkriptLang/Skript#2393]
Tried on Version 1.13.2/1.14 using Skript 2.4-beta5

Recently I ran a stress test comparing looping list variables to find an object and also using contains to find an object. It seems that looping is actually WAY faster. I don't know why its the case but I was wondering if there could be an enhancement for using 'Contains' with list variables so that its as fast as looping.

The Stress Test:
3000 random strings with 12 random chars each in a list variable
set var to random string out of the list variable

Looping to find the random string:
Looping Speed: Took 3ms on average (2ms-4ms) to find the random object.

Using contains to find the random string:
Contains Speed: Took 600ms on average (500ms-700ms) to find the random object.

**Comment by Blueyescat** [comment]
simple code to test
```vb
function listContains(list: objects, o: object) :: boolean:
    loop {_list::*}:
        if loop-value is {_o}:
            return true
    return false

on load:
    set {x::*} to integers between 1 and 1000
    
    set {_s} to (unix timestamp of now * 1000)
    if {x::*} contains 500:
        output "contains1 - %(unix timestamp of now * 1000) - {_s}%ms"

    set {_s} to (unix timestamp of now * 1000)
    if listContains({x::*}, 500) is true:
        output "contains2 - %(unix timestamp of now * 1000) - {_s}%ms"
```

**Comment by FranKusmiruk** [comment]
@Blueyescat May I ask, what's the `output` effect you're using there? If it is a custom syntax, you may as well provide it or just change that to a broadcast.

**Comment by TheBentoBox** [comment]
The contains effect has long been problematic. It's slow and historically has simple not even always worked properly.

In this specific scenario (checking contains on a list of objects) the operation the condition is doing has no reason to be 200x slower than the same condition being rewritten as a Skript function. There is clearly some large for optimization and fixes here and given how often this condition is used it should be addressed sooner rather than later IMO.

**Comment by Malfrador** [comment]
Also, location for variables (specifically locations) does not seem to work using "contains"
'''
command /capture:
	trigger:
		set {_loc} to location of block below player
		set {_rg} to "test3"
		set {_p} to player
		broadcast "Loop:"
		loop {CPs.%{_rg}%::*}:
			broadcast "%loop-value%"
		broadcast "Loc: %{_loc}%"
		# This does not work. Broadcast loop-value prints {_loc} in the list, but "contains" does not find it. 
		if {CPs.%{_rg}%)::*} contains {_loc}:
			broadcast "test"
'''
{_loc} is even in there twice, still does not find it and never shows "test"
Chat:
 
![javaw_2019-08-26_18-01-44](https://user-images.githubusercontent.com/6106558/63704663-c7a2e080-c82b-11e9-8722-55f0c8d6ad39.png)

**Comment by bluelhf** [comment]
> 
> 
> Also, looking for variables (specifically locations) does not seem to work using "contains"
> 
> ```
> command /capture:
> 	trigger:
> 		set {_loc} to location of block below player
> 		set {_rg} to "test3"
> 		set {_p} to player
> 		broadcast "Loop:"
> 		loop {CPs.%{_rg}%::*}:
> 			broadcast "%loop-value%"
> 		broadcast "Loc: %{_loc}%"
> 		# This does not work. Broadcast loop-value prints {_loc} in the list, but "contains" does not find it. 
> 		if {CPs.%{_rg}%)::*} contains {_loc}:
> 			broadcast "test"
> ```
> 
> {_loc} is even in there twice, still does not find it and never shows "test"
> Chat:
> 
> ![javaw_2019-08-26_18-01-44](https://user-images.githubusercontent.com/6106558/63704663-c7a2e080-c82b-11e9-8722-55f0c8d6ad39.png)
> 
> Looping works fine:
> 
> ```
> 	loop {CPs.%{_rg}%::*}:
> 		if loop-value is {_loc}:
> 			broadcast "Yeah!"
> ```

#### Cannot replicate with following code:
```vb
function lookup(l: locations, p: player):
  log "looking for %{_p}%'s location (%{_p}'s location%) in this list:"
  loop {_l::*}:
    if loop-value isn't {_p}'s location:
      log "  %loop-value%"
    else:
      log "  %loop-value% <--- FOUND"
  if {_l::*} contains {_p}'s location:
    log "found"
  else:
    log "not found"
```
Output for `!lookup((spawn of me's world, (location(0,0,0,world of me))), me)`:
```
looking for blce's location (x: 10008.18, y: 85, z: 10001.32) in this list:
x: -1, y: 63, z: 0
x: 0, y: 0, z: 0
not found
```
Output for `!lookup((spawn of me's world, (location(0,0,0,world of me)), location of me), me)`:
```
looking for blce's location (x: 10008.18, y: 85, z: 10001.32) in this list:
x: -1, y: 63, z: 0
x: 0, y: 0, z: 0
x: 10008.18, y: 85, z: 10001.32 <--- FOUND
found
```
