### ISSUE TITLE
Everything with beacons does not work

### ISSUE THREAD

**Issue by Malfrador** [SkriptLang/Skript#2395]
### Description

All events, conditions or effects that involve the beacon block are not working. The beacon block is showing up in expressions like %target block%, but you can not place it, check for it in events or loops or do anything else with it.
Example:
```
# This works
on place:
	set {_workaroundstring} to event-block
	"%{_workaroundstring}%" is "beacon"
	cancel event
# This does not
on place of beacon:
	cancel event
```

### Steps to Reproduce
Try the skript above with the newest Skript version and without any addons. 

### Expected Behavior
The beacon block to work like all other blocks do fine.

### Errors / Screenshots
No error in log or while parsing.

### Server Information
* **Server version/platform:** PaperSpigot 1.13.2        
* **Skript version:**   2.4-beta5. Tried older versions as well

**Comment by TheBentoBox** [comment]
I'll check this out later.

**Comment by Wealthyturtle** [comment]
Closing this issue in favor of #2459.
