### ISSUE TITLE
/sk errors

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2400]
### Description
command to show all errors and warnings from all scripts

**Comment by FranKusmiruk** [comment]
As ShaneBee said above, you can use `/sk reload all` to reload all scripts and see all of the error/warnings.

**Comment by MrScopes** [comment]
> As ShaneBee said above, you can use `/sk reload all` to reload all scripts and see all of the error/warnings.

this breaks certain addons like tuske

**Comment by Matocolotoe** [comment]
lmao it doesn't break anything, if scripts take too much time to reload you will be timed out but Skript is not responsible for major addon errors

**Comment by MrScopes** [comment]
> lmao it doesn't break anything, if scripts take too much time to reload you will be timed out but Skript is not responsible for major addon errors

na it breaks some addons

**Comment by Matocolotoe** [comment]
if you can't accept the truth in any kind of problem then i don't know what to do for you

**Comment by bluelhf** [comment]
@MrScopes how the fuck does reloading scripts break addons

**Comment by TPGamesNL** [comment]
This is an issue with TuSKe: https://github.com/Tuke-Nuke/TuSKe/issues/63#issuecomment-407522019.
That being said, it isn't something Skript should fix, this will have to fixed within TuSKe (which isn't really maintained anymore, so I suggest using vanilla Skript for GUI's)
