### ISSUE TITLE
problem with setting names of entities

### ISSUE THREAD

**Issue by Padlick01** [SkriptLang/Skript#2402]
### Description
When you use this event, the spawn rate increases extremly (like 20 animals/monster inside one chunk).

### Steps to Reproduce
Some code, that produces that problem for me:
https://pastebin.com/qdM7q1kE

### Expected Behavior
The spawn rate should stay normal and not going crazy.

### Errors / Screenshots
https://cdn.discordapp.com/attachments/516617094926827520/616227299867623434/unknown.png

### Server Information
* **Server version/platform:**       git-Paper-176 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
* **Skript version:**                2.4-beta5

EDIT: Have an fail inside my script. Just replace event.getEntity() with event-entity in line 7. Had tested that code also with skript-mirror and Java code. Java code works for me just normal. With Skript the spawn rate gets crazy.

EDIT 2: With that script I posted the spawn rate only for zombies gets crazy. If you do same with skeleton, creeper or something else same thing.

**Comment by Blueyescat** [comment]
Maybe the limits doesn't count named/special entities etc.. not related to Skript after all.

**Comment by Padlick01** [comment]
Then I have to create a workaround to fix that. Like loop all entities around event-entity. If that distance between them is to small then cancel the spawn event? Should work I think.

**Comment by TheBentoBox** [comment]
If I understand your first edit correctly, are you saying that using `event.getEntity()` is what caused the issue?

Normally I'd close something like this immediately as not our issue but just want to verify as there have been strange issues like this with events before (like when people were falling through the ground because Skript wasn't cloning player locations before modifying to check for offsets).

**Comment by Padlick01** [comment]
Nope. In my script I've posted I made an mistake. Copied my script that was builded with skript-mirror code. Forgot to replace event.getEntity() in my paste with event-entity.

**Comment by Padlick01** [comment]
But as I saw, doesn't seem to be an problem of the event. Spawn rate gets crazy when I set the (display-)name of them. 
Also I found out that you can't loop zombies or other animals/monster that have an name.

**Comment by TheBentoBox** [comment]
If this is only when they're named, then as Blue said this isn't a Skript issue. The mob cap mechanics most likely ignore named entities.
