### ISSUE TITLE
Advanced entity spawning effect [Suggestion]

### ISSUE THREAD

**Issue by Moderocky** [SkriptLang/Skript#2403]
### Description

Currently, if you spawn an armour stand (and possibly other entities) in Skript and then modify it using the `last spawned X` expression, even if there is no delay between the spawning and the modification it will show up on (some?) clients as though there is.

What I mean by this is that if you spawn an armour stand and then make it invisible (or modify its NBT via an addon) it will still show up for a tiny moment when it is spawned on the client. This also happens when using Bukkit's spawn method, so it's not actually a limitation of Skript.

However, if you spawn an entity in java (bukkit API) and modify it using a lambda in the spawn effect, it does not have this momentary flicker and will spawn invisible/modified in the way that you chose.

What I am suggesting is something based on this, with a block syntax such as:
```
on (some event):
    spawn an armor stand at player's location:
        set the entity's helmet to stone
        add "{Invisible:1b}" to the entity's nbt # or some other invisibility syntax
        # I suppose 'the entity' could be replaced with 'the armor stand' or something more suitable?
        # more stuff relating to the to-be-spawned stand here
    # back to the code
```
(This is a rough example.)

It would have to be a block syntax, as is used in Tuske's GUIs and would probably be unable to include any delays(?) but it would allow somebody to sort of pre-prepare the about-to-be-spawned entity, so it would spawn with the chosen properties rather than them being added after the effect.

This is just a suggestion I thought might be beneficial to some users. :)

**Comment by Blueyescat** [comment]
hope @Pikachu920 finishes his Section API

**Comment by Misio12320** [comment]
Might be better when the "more effects" release add:
'''vb
On spawn
    set the entity's helmet to stone and equip with (type) chestplate and set event-entity's walk speed to x""
