### ISSUE TITLE
How long until next release?

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2407]
It's been almost a month since the last release and I wonder when there will be a new release ready for download? There are some serious bugs that prevent people from using Skript on 1.14 servers (like the item variable in GUIs issue etc.). Can you provide an ETA for the next update?

**Comment by TPGamesNL** [comment]
Well you could always build it yourself if you want to, but there will still be some things that aren't fixed. 

Also, if the item variables in GUI thing from Skript (not an addon), can you link me the issue? I can't seem to find it

**Comment by bensku** [comment]
Issues you're probably refering to are not fixed yet.

**Comment by Matocolotoe** [comment]
@Misio12320 Would you mind stopping disliking every single message on the repo ?

**Comment by Misio12320** [comment]
@matocolotoe where every message where? Disliking random useless topics like #2398 which I does not disliked so wheres every single message? The topic should be closed. 4 days and no response so why he wrote this. 48 hours/7 days for answer and close issue. Sorry? My fault guy wrote an issue without skript version and following steps which is required to report a bug. Gave my opinion in emote without commenting and this is all. 2.And in this topic hes true but they work hard so just have to wait some time. May its better to fix more bugs and release a better stable with more bug fixes and wait some time than release a version every fix a bug...

**Comment by TPGamesNL** [comment]
I've even seen you dislike and like comments/threads at the same time. How does that help anyone?

**Comment by bloggy** [comment]
> 
> 
> Issues you're probably refering to are not fixed yet.

@bensku thx for the reply. I am refering to this issue: https://github.com/SkriptLang/Skript/issues/2347

@TPGamesNL see link above

Appreciate you guys working hard on fixing all that stuff. I am checking here for a new release daily and it just gets a little bit frustrating to see the message "bensku released this 27 days ago"

**Comment by TPGamesNL** [comment]
> > Issues you're probably refering to are not fixed yet.
> 
> @bensku thx for the reply. I am refering to this issue: #2347
> 
> @TPGamesNL see link above
> 
> Appreciate you guys working hard on fixing all that stuff. I am checking here for a new release daily and it just gets a little bit frustrating to see the message "bensku released this 27 days ago"

As stated [here](https://github.com/SkriptLang/Skript/blob/master/.github/CONTRIBUTING.md#code-bounties), you can put bounties on issues, it might speed up the process. Since there are many bugs in Skript, it takes time for one specific issue to be resolved. Also, you can just use vanilla GUI's in the meanwhile, or use more variables instead of doing everything in 1 line as a temporary fix.
