### ISSUE TITLE
Expressions reset text formatting

### ISSUE THREAD

**Issue by bluelhf** [SkriptLang/Skript#2409]
### Description
Using an expression after formatting a piece of text (eg. `&a%player's name%`) resets the formatting of the text.

### Steps to Reproduce
Use following code:
```vb
command /test:
  trigger:
    set {_hi} to "hello"
    send "&c%player's name% more text"
    send "&c%{_hi}% more text"
```

Then run /test.

### Expected Behavior
The expression should be sent in red, and so should the rest of the text

### Observed Behavior
The expression is sent in red, but the text after it is sent in white

### Server Information
* **Server version/platform:** Paper version git-Paper-152 (MC: 1.14.4)
* **Skript version:** 2.4-beta5

### Additional Information
I believe this issue is related to [this commit](https://github.com/SkriptLang/Skript/commit/c5a9cdac4507010304bd21e345c2f938a04f7ce2)

**Comment by HYPExMon5ter** [comment]
Pretty sure there is already an issue for this.

**Comment by bluelhf** [comment]
> 
> 
> Pretty sure there is already an issue for this.
> EDIT: yeah there is, issue #2319

Yep, sorry, didn't see it.
