### ISSUE TITLE
Held item or Player's tool removal is not working as intended.

### ISSUE THREAD

**Issue by aescraftbr** [SkriptLang/Skript#2411]
### Description
When you remove a held item or player's tool, it's not selecting the held item slot, but the first slot from the toolbar that has the same item (even if named, with custom nbt, etc.)

**Example:**
slot 1: music disc cat named "test"
slot 2: music disc cat named "woops"

Holding disc named "woops", so, slot 2 is selected / in hand
Use this:
`remove held item from player`

Slot 1 is removed.
Slot 2 that should be removed, stays.

### Expected Behavior
Slot 2 should be the one removed.

### Server Information
* **Server version/platform:**       1.14.4
* **Skript version:**                skript 2.4-beta5

**Comment by TheBentoBox** [comment]
Duplicates #2354
