### ISSUE TITLE
Weird behavior of functions in do if effects

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2416]
### Description

Boolean functions don't work in some cases in do if effects

### Steps to Reproduce

```
function b() :: boolean:
	return {bool} ? true : false

function c():
	delete {somevariable}

command /test:
	trigger:
		c() if b()
```

However if you write `c() if b() is true`, no error appears.
However n°2, `c() if {bool}` works without the `is true` after it.

### Expected Behavior

`if %boolean%` should work even with functions

### Errors / Screenshots

`Invalid brackets/variables/text in ') if b(' (test.sk, line 9: c() if b()')`

### Server Information
* **Server version/platform:** Spigot 1.14.4      
* **Skript version:** 2.4-beta5 (latest)

**Comment by Blueyescat** [comment]
It is not supposed to be working, functions that return a boolean don't behave like a condition.

**Comment by Matocolotoe** [comment]
Then maybe this could be added into Skript and include these functions ?

**Comment by Blueyescat** [comment]
Actually.. a function should work with SkQuery's condition, that should be the general issue with function parsing. For example this will cause it too: `a() + b()`

these should work in this case: `(c()) if b()` -- `delete {x} if b()`

**Comment by Matocolotoe** [comment]
🤔

**Comment by iWanheda** [comment]
> function b() :: boolean:
	return {bool} ? true : false

What?? Just return {bool}

**Comment by Matocolotoe** [comment]
It was just an example, and {bool} is a boolean (as you just told me to return it lol)

**Comment by iWanheda** [comment]
I mean what was it defined as, anyways great it was an example

**Comment by FranKusmiruk** [comment]
Can we get a case where this occurs **without addons**? It's quite difficult for us to trace down these kind of parsing bugs and addons don't make it easier.
