### ISSUE TITLE
Can't join server (1.14.4 / 2.4-beta6)

### ISSUE THREAD

**Issue by AsuDev2** [SkriptLang/Skript#2420]
I am on paper#186 for 1.14.4 and using skript 2.4-beta6.

My issue is that I cannot join my server. I believe this error is caused by Skript because when I remove it, I can join fine. Here is the error and the plugin list:
![Capture](https://user-images.githubusercontent.com/42305658/64206495-57114a80-ce4f-11e9-89a3-5204d1168875.PNG)
All of these plugins are their most recent versions and most of them support 1.14.4. I am not sure what causes this error but when I googled it on the spigot forums, it said it had to do with Skript not working for 1.14...

**Comment by Blueyescat** [comment]
Caused by Skellett. Delete it or disable Packet event from its configs.

**Comment by AsuDev2** [comment]
Thanks it worked! If anyone else has issues with this, go to the SyntaxToggles.yml file and set the Packets option under Main node to false.
