### ISSUE TITLE
PlayerCommandPreprocessEvent error 

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#2422]
### Description

https://hastebin.com/ifujofojik.php

### Server Information
* **Server version/platform:**       1.14.4
* **Skript version:**                2-4-beta-6

### Additional Context
The menus created with Tuske do not work.

**Comment by Matocolotoe** [comment]
Seems like TuSKe needs another patch for functions

**Comment by Blueyescat** [comment]
Use this for now, instead of `make gui .. to run function x()`
```vb
make gui .... to run:
    x()
```

**Comment by TheBentoBox** [comment]
This should be fixed because as far as I can tell the change that broke this API was unnecessary.
