### ISSUE TITLE
Grow events not properly firing for certain crops

### ISSUE THREAD

**Issue by JeroenoBoy** [SkriptLang/Skript#2424]
### Description
So i was fooling around with 0 tick stuff and wondered what happend with crops and when i canceled the on grow stuff, Sugarcane worked, but bamboo didnt. so i thought it was on me. so i tried more and it wouldnt cancel. so i tried more stuff, Chorus flowers also didnt work, sapplings also grow, 

### Steps to Reproduce

Just make a farm and place trees etc

Code:
```
on plant grow:
	cancel event

on block grow:
	cancel event

on crop grow:
	cancel event
```

### Expected Behavior

I expected nothing to grow

### Server Information
* **Server version/platform:**       1.14.4 paper build 176
* **Skript version:**                2.4-beta5

### Additional Context

i could also just do /gamerule randomtickspeed 0 but that wont fix 0 tick stuff

**Comment by Wealthyturtle** [comment]
Just tested this, seems like newer crops don't properly cancel, e.g. chorus fruit and bamboo. Skript can detect that they're being grown but for some reason can't properly cancel them?

Code:
```
on plant grow:
	broadcast "Cancelling %past event-block%"
	cancel event
```
![image](https://user-images.githubusercontent.com/19924575/66193709-c46e0080-e6c5-11e9-8a76-897260a4c903.png)
(But doesn't actually cancel the chorus fruit's growth)

**Comment by TPGamesNL** [comment]
Closing because this is a Spigot issue, as said above
