### ISSUE TITLE
Required command arguments disappear in the doc examples

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2425]
### Description

Required arguments in Skript commands don't show in the documentation examples.

### Expected Behavior

The required arguments, like `<player>` should show.
The problem is probably due to some HTML stuff.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/42092549/64253020-a5d8e600-cf1c-11e9-96fb-3d192bdc5156.png)

![image](https://user-images.githubusercontent.com/42092549/64252793-20553600-cf1c-11e9-82f2-264070123367.png)

**Comment by Wealthyturtle** [comment]
Seems to be treating brackets in examples as HTML, and brackets outside examples as text...
![image](https://user-images.githubusercontent.com/19924575/65824242-56c26e80-e298-11e9-8024-7e4666bd8242.png)
