### ISSUE TITLE
Make the aliases section like the new aliases in skript

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#2426]
With the new aliases system you can specify which aliases are for what version and some other stuff while the `aliases` section you can put in scripts to make aliases for that script is lacking. You should be able to specify the version without having to edit the main aliases.

**Comment by TheBentoBox** [comment]
I'll put as medium as these are good ideas which seem really useful.

**Comment by bensku** [comment]
Using aliases from Skript should work now. It was broken for a long time, though.

**Comment by HYPExMon5ter** [comment]
Oh, good to know, I just tried it and it works fine lol. I'll remove that part from the message since it's already been fixed
