### ISSUE TITLE
issue with armor condition

### ISSUE THREAD

**Issue by taelover** [SkriptLang/Skript#2428]
Hello, I'm a pretty new skript user, and I am using the most recent version of skript released only 20 hours ago, of this bug thread being made. And I am using skript to make classes related to armor, but whenever my armor gets damaged, skript can't confirm that i'm still wearing diamond armor

anyways here is my code, if anymore information is nessecary feel free to ask me, correct me if my code is wrong, but I'm pretty shure this is a bug.

```
every tick:
	loop all players:
		if {LastBreath.%loop-player%} is not set:
			set {LastBreath.%loop-player%} to 0
		if loop-player is wearing all diamond armor:
			execute console command "/effect give %loop-player% resistance 10 0 true"
			execute console command "/effect give %loop-player% slowness 10 0 true"
			if {Class.%loop-player%} is not "Tank":
				set {Class.%loop-player%} to "Tank"
				message "&c&l(!) &4&l%{Class.%loop-player%}% &4&lSuit Equipped!" to loop-player
				set loop-player's max health to 15
				set loop-player's health to loop-player's health*1.5
				stop
		else:
			if {Class.%loop-player%} is "Tank":
				execute console command "/effect clear %loop-player%"
				clear {Class.%loop-player%}
				message "&c&l(!) &4&lSuit Unequipped!" to loop-player
				set loop-player's health to loop-player's health/1.5 
				set loop-player's max health to 10
```

						 
						 
anyways, it might just be an issue with my skript, but i'm pretty shure its an issue with this version of skript. anyways correct me if i'm wrong and thanks for reading

I'm going to use the older version of skript for now, as this bug essentially in this version is pretty critical for my server.

**Comment by Niggarboi** [comment]
Pls fix this issue has occured in my skript aswell thanks for sharing Teelover

**Comment by TheBentoBox** [comment]
Should be fixed in the new release.
