### ISSUE TITLE
Click events not working

### ISSUE THREAD

**Issue by Padlick01** [SkriptLang/Skript#2429]
### Description
Click events are not working

### Steps to Reproduce
use an click event (doesnt matter which one, click, left click, right click... doesnt matter.) with an item and put an message into it. I don't get any message back.
ex:
on click with nether star:
message "test"

### Expected Behavior
The event should be thrown and the message should be printed.

### Errors / Screenshots
no error

### Server Information
* **Server version/platform:**       git-Paper-175 (MC: 1.14.4)
* **Skript version:**                2.4-beta6

### Additional Context
In beta5 the click events are fully working. In beta6 they doesn't.

EDIT 1: I don't know, if this only occurs when using items in the event. Havn't tested that because rolled back to beta5 already.

**Comment by iWanheda** [comment]
I confirm this, was going to post the same thing, after the latest update it hasn't been working. My ex:
```
on left click:
	if event-item is a diamond hoe:
```

**Comment by bensku** [comment]
Cannot reproduce on Paper 1.14.4.

**Comment by Padlick01** [comment]
I cannot test it atm, but would be nice to know which version of paper you have. Maybe it was only a paper bug, but that can't be the problem because I only have that issue on beta6 oO

**Comment by bensku** [comment]
Happens only on items with meta. This is a regression caused by fix of #2354.
