### ISSUE TITLE
Aliases issue

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#2430]
When editing the skripts default aliases you can't use aliases in files loaded after the one you're using the alias in, not sure if that should be fixed but just thought it should be brought to attention.

**Comment by ShaneBeee** [comment]
I wouldn't call this an aliases issue, nor would I call this a bug at all.

Skript lands scripts in alphabetical order (starting with directories first)... your best bet is to create a file that starts with a, something like `a-custom-aliases.sk` and put your custom stuff in there that will be used in other scripts.

Also for future notice, please don't be scared to use the issue template that is provided to you when you create a new issue. Deleting the template is just removing the stops and proper info needed to report a bug.

**Comment by HYPExMon5ter** [comment]
Yes but this wasn’t a bug about skript nor really a bug, more of an enhancement so didn’t need to give version numbers and stuff so wasn’t gonna use the template. But yeah you’re right, it’d just be better to do that
