### ISSUE TITLE
CCE ScriptFunction -> JavaFunction

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2434]
### Description

When TuSKe tries to generate the documentation files, a CCE appears.

### Expected Behavior

The doc should be generated without any exception like with previous Skript versions.

### Errors / Screenshots

```
java.lang.ClassCastException: ch.njol.skript.lang.function.ScriptFunction cannot be cast to ch.njol.skript.lang.function.JavaFunction
```

### Server Information
* **Server version/platform:** Spigot 1.14.4      
* **Skript version:** 2.4-beta7 (latest)               

### Additional Context

This happens with TuSKe but it's probably related to Skript's function API since it didn't happen before beta7.

**Comment by TheBentoBox** [comment]
I recommended that this be logged as it appears to be due to a breaking change to the function API but if it's a necessary, breaking change then handle this issue as you see fit.

**Comment by bensku** [comment]
Full stack trace would be helpful.

**Comment by Padlick01** [comment]
I use beta7 and TuSKe. I don't have this issue.
Probably you installed a new addon that isn't great coded. Had this problem with Skungee long time ago.

**Comment by Matocolotoe** [comment]
I have the latest version from @Pikachu920 🤷‍♂

**Comment by Padlick01** [comment]
me too.^^

**Comment by Blueyescat** [comment]
> Full stack trace would be helpful.

**Comment by Matocolotoe** [comment]
> Can't run a test server immediately all the time in my life.

**Comment by Matocolotoe** [comment]
Okay, the issue doesn't occur anymore, don't know what went on lmao
