### ISSUE TITLE
Java functions names now override Skript functions'

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2435]
### Description

Since beta7, you can't create a Skript function that has the same name as a Java function that is used at least once in the Skript plugin

### Steps to Reproduce

```function log(t: text, u: text)```

### Expected Behavior

Skript function names should be independent from Java ones.

### Errors / Screenshots

```
[15:34:27] [Server thread/ERROR]: [Skript] Function name 'log' is reserved by Skript (api.sk, line 887: function log(t: text, u: text):')
```

### Server Information
* **Server version/platform:** Spigot 1.14.4      
* **Skript version:** 2.4-beta7               

### Additional Context

The issue occurs with any Java function (from Java itself like in the `log` example or Skript's internal stuff)

**Comment by bensku** [comment]
This is intentional. Functions are global, and overwriting built-in functions may break other scripts.
