### ISSUE TITLE
Still issues with function parameters API

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2436]
### Description

Since beta7, skript-mirror can't access Skript's parameter fields anymore

### Steps to Reproduce

```
import:
    org.bukkit.Bukkit
```

### Errors / Screenshots

```
[15:34:28] [Server thread/WARN]: [Skript] Skript's parameters field could not be resolved. Class proxies will not work. (api.sk, line 2: org.bukkit.Bukkit')
```

### Server Information
* **Server version/platform:** Spigot 1.14.4      
* **Skript version:** 2.4-beta7

**Comment by Blueyescat** [comment]
Not a Skript problem, because the addon was accessing Skript's private `Function.parameters` instead of using the public method `Function#getParameters`.

**Comment by bensku** [comment]
Indeed. It would be interesting to hear why it does that.
