### ISSUE TITLE
Ignoring text after variables

### ISSUE THREAD

**Issue by HardstylesDev** [SkriptLang/Skript#2437]
### Description
It completely replaces the character after a variable if it's a singular char.

### Steps to Reproduce
```
command oktest:
	trigger:
		set {_s} to 5
		send "%{_s}%s"
```
### Expected Behavior
It should obviously just print the S after the variable in this case.
### Errors / Screenshots
No errors.

### Server Information
* **Server version/platform:** Paper MC 1.8.8 R0.1
* **Skript version:** 2.2-dev36

**Comment by bensku** [comment]
Sorry, the relevant system has received significant rewrites after your version. We can't suåport that old versions.
