### ISSUE TITLE
Remove from player's inventory works wrong on latest 

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#2442]
### Description
When using skript https://pastebin.com/2pfWM5hc <- code is here
On rightclick it's removing wrong items (first in toolbar) not 1 of everything (it's not looking at name of item)

### Steps to Reproduce
1. type /zdrapki daj 100
2. rightclick on them - you'll randomly get some cards
3. rightclick on card - if you have different 9 it should remove 1 of every card, but it's removing first on toolbar

Example
you have 64 cards of number 1, 1 card of number 2, 1 card of number 3 etc. - you should only get reward 1 time and you should lost cards 1,2,3,4,5,6,7,8,9 (1 of them) but on latest, you'll lose 9 cards number 1 and none others. On beta-5 it worked!

### Expected Behavior
^^^

### Errors / Screenshots
No errors

### Server Information
* **Server version/platform:**     Paper-186  
* **Skript version:**       latest (beta-7)         

### Additional Context
On beta-5 there's no bug like this and it worked great

**Comment by TheBentoBox** [comment]
Going to track this in #2446.
