### ISSUE TITLE
Remove effect don't work properly (beta7)

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#2446]
I've opened a ticket which related with this issue like 2 weeks ago. It was in Skript beta-5 and has been fixed in Skript beta-6 but the same issue appeared again Skript beta-7.

### Description
I've set my hotbar 0, 1 and 2 with two papers with nbt CustomItems:Summon_Skeleton_1/2/3 and I tried to remove them with function below. I attached two result belongs to Skript 2.3.7 and Skript 2.4-beta-5

### Expected Behavior
Remove just one in each hotbar. So Skript 2.3.7 works properly in that case.

### Errors / Screenshots
No errors in console.
Remove effect in Skript 2.4-beta-5: https://i.imgur.com/P0s2DD2.png
Remove effect in Skript 2.3.7: https://i.imgur.com/9qGhq9c.png

### Server Information
* **Server version/platform:** Paper 1.13.2 Build 643 (+ Paper 1.14.4 Build 186)
* **Skript version:** Skript 2.4-beta-5(still exists in beta7) in first screenshot, Skript 2.3.7 in second screenshot

```
command /nbttest:
	trigger:
		removeNBTItem(player, 1, "CustomItems:""Summon_Skeleton_1""")
		removeNBTItem(player, 1, "CustomItems:""Summon_Skeleton_2""")
		removeNBTItem(player, 1, "CustomItems:""Summon_Skeleton_3""")
function removeNBTItem(p: player, a: number, nbt: text):
	broadcast " ", " "
	broadcast "&bSearching: %{_nbt}%"
	loop all items in {_p}'s inventory:
		broadcast " "
		nbt of loop-item contains {_nbt}
		broadcast "&cRemoved: %loop-item%(%{_a}%)"
		remove {_a} of loop-item from {_p}
		stop loop
```

**Comment by TheBentoBox** [comment]
I'll use this as the new main issue for tracking this problem as it seems to describe it best. Though ideally the example wouldn't rely on an add-on.

This is a really bad bug that needs fixing. It's as bad as the other critical bugs that have been fixed recently.

**Comment by bensku** [comment]
Regression was introduced in 062a72. Unfortunately, that commit fixes another high-priority bug. Changing ItemData equals() MatchQuality to EXACT might help, but is dangerous in other ways.

**Comment by ruddeTR** [comment]
Thanks for the information. What should I do for temporary solution?

**Comment by iOshawott** [comment]
You are talking about some bugs in beta-5 which is in beta-7... I don't understand, bug I saw is only in beta-7, not in beta-5. Hope it will be fixed too
