### ISSUE TITLE
Make between condition work with unsorted numbers

### ISSUE THREAD

**Issue by bluelhf** [SkriptLang/Skript#2448]
### Description
Currently, the between condition doesn't work unless the two numbers being tested against are sorted in smallest-to-highest order.
![image](https://i.imgur.com/NQ74w3p.png)
The logical approach would be to have it working regardless of how the numbers are sorted.

I suggest adjusting the condition so it either
1. Automatically sorts the numbers given to it
or
2. Works with unsorted lists

**Comment by ShaneBeee** [comment]
this has already been reported, a while back, #1481
