### ISSUE TITLE
Whitelisting commands if variable is set

### ISSUE THREAD

**Issue by ItzArty** [SkriptLang/Skript#2449]
Hi, im making an Auth system but i want to prevent players to execute any commands if not logged in but only allow them to execute /login and /register
my current skript is like that:
`on command:
    if {loginmode.%player%} is set:
        if command is "/login":
            cancel event`
can you please edit it and send it? thx

**Comment by KingAlterIV** [comment]
This github is not for Skript (not the plugin) help. Its for reporting Skript (plugin) bugs and such.

**Comment by DavidVioMC** [comment]
Ask for help here instead: https://discord.gg/79RFqxg

**Comment by KingAlterIV** [comment]
This github is not for general Skript help, it's for bug reports and such.

**Comment by ItzArty** [comment]
KingAlterIV then why there is a question button ?

**Comment by KingAlterIV** [comment]
The question is for the Skript (plugin), not for general Skript help.
