### ISSUE TITLE
Tooltip newline won't work

### ISSUE THREAD

**Issue by aescraftbr** [SkriptLang/Skript#2451]
### Description
When trying to set a new line inside tooltip, it breaks the tooltip.

### Steps to Reproduce
Use this in a command:
```
command /testing:
  trigger:
    send "<tooltip:&aLINE 1%nl%&bLINE 2%nl%&cLINE 3>Hover<reset>"
```

### Expected Behavior
New lines should work in tooltip.

I've tested this with SkQuery and with skript mirror. Same result (tooltip breaks in both cases).

Snippet for the skript mirror new line expression used to test:
```
import:
  java.lang.System

expression (nline):
  return type: text
  get:
    return last character of System.lineSeparator()
```

### Errors / Screenshots
https://i.imgur.com/eVNsqX4.png

### Server Information
* **Server version/platform:** Paper version 187 (mc.1.14.4)
* **Skript version:**  Skript ver 2.4-beta7

### Additional Context
This seems to be working before, as shanebee's post in skunity says that it was possible:

https://forums.skunity.com/threads/chat-tooltip-help.8251/#post-36006

**Comment by IamFULL1** [comment]
> Ok, I just found the solution, and you need to use
> 
> send formatted
> 
> instead of just "send".

Thanks!!
