### ISSUE TITLE
Other plugins cannot cancel PlayerInteractEvent

### ISSUE THREAD

**Issue by RockinChaos** [SkriptLang/Skript#2452]
Not quite sure if this is a bug or intended operation,

I have my own plugin which cancels the PlayerInteractEvent, where I would assume Skript listens to for the following Skript;
```
on rightclick on iron door:
	toggle the block
	cancel the event
```

However, despite my plugin canceling the event before Skript has a chance to handle it, the door is still toggled. **I was wanting to know if Skript is simply ignoring canceled events?**

What is suppose to happen which this does with other plugins is the event is canceled as first priority by my plugin and the other plugins do not perform any operations --- simply the above Skript shouldn't be executed. It is likely that I may have overlooked something but any insight on this would be great.

**Comment by bensku** [comment]
Skript passes only first event to scripts, and if its cancellation status is modified, copies cancellation status to second event. In the rare cases where Skript cannot link the first and second event together, scripts will receive both. Unfortunately, this causes minor issues like what you described.
