### ISSUE TITLE
"Crash Error"

### ISSUE THREAD

**Issue by MaPaJe** [SkriptLang/Skript#2453]
### Description
I'm not able to join my server due to timing out
https://hastebin.com/upajodivez.css
### Server Information
* **Server version/platform:**     Paper 1.12.2 1618
* **Skript version:**                 2.4 Beta 5

### Additional Context
I have addons;
Skellet, MonduSK, SkRayFall, SkQuery 3, Skript Mirror, Skript Paper, TuSke Pikachu Patch 3,

**Comment by Matocolotoe** [comment]
try using skript-mirror 2.0.0 if you don't already https://skripttools.net/dl/skript-mirror+2.0.0-SNAPSHOT.jar

**Comment by FranKusmiruk** [comment]
This is an issue caused by skript-mirror.
