### ISSUE TITLE
plant grow stage changing

### ISSUE THREAD

**Issue by NebuSensei** [SkriptLang/Skript#2456]
### Description

I can't change the stage of wheat (or others) plant (it's always stay stage 1)
### Steps to Reproduce

```
on break:
	event-block is stage eight wheat plant:
		cancel event
		set {_a} to random integer between 0 to 3
		set {_a} to "%{_a}% seeds" parsed as item
		give {_a} to player
		give wheat to player
		set event-block to freshly planted wheat plant
		wait 1 seconds
		set event-block to stage 3 wheat plant
		wait 1 seconds
		set event-block to stage 6 wheat plant
		wait 1 seconds
		set event-block to fully grown wheat plant
```
### Expected Behavior

Wheat plant should change stages
### Errors / Screenshots

No error

### Server Information
* **Server version/platform:**       1.14.4 paper
* **Skript version:**               2.4-beta7

**Comment by bluelhf** [comment]
We don't provide help with scripts here. Try the SkUnity or Skript-Chat discord servers instead.

**Comment by NebuSensei** [comment]
I didnt ask for script help stages are not working on set block

**Comment by KingAlterIV** [comment]
It works fine, it's not a bug at all. It's a player error.
https://i.imgur.com/Xmexi85.gifv

**Comment by bluelhf** [comment]
Was able to reproduce with given code, but found the following solution:
```vb
on break:
  event-block is stage eight wheat plant:
    cancel event
    set {_a} to random integer between 0 to 3
    set {_a} to "%{_a}% seeds" parsed as item
    give {_a} to player
    give wheat to player
    set block at event-block to freshly planted wheat plant
    wait 1 seconds
    set block at event-block to stage 3 wheat plant
    wait 1 seconds
    set block at event-block to stage 6 wheat plant
    wait 1 seconds
    set block at event-block to fully grown wheat plant```
Paper-152, 2.4-beta6.
