### ISSUE TITLE
past/future event-values not registering

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#2457]
### Description
It appears that past/future event values are not registering.

### Steps to Reproduce
Using this code:
```vb
on break:
    send "Past: %past event-block%" to console
    send "Current: %event-block%" to console
```
To different values should output to console, but this is the outcome when breaking a sand block:
```
[23:08:44 INFO]: Past: sand block
[23:08:44 INFO]: Current: sand block
```

I first noticed then working with my addon Skript-Paper and realizing the armor change event was not showing the past value:
```java
Skript.registerEvent("Player Change Armor", SimpleEvent.class, PlayerArmorChangeEvent.class, "player change armor")
        .description("Called when the player themselves change their armor items")
        .examples("on player change armor:",
                "\tcancel event",
                "\tset helmet of player to pumpkin")
        .requiredPlugins("Paper 1.12.2+")
        .since("1.0.0");
EventValues.registerEventValue(PlayerArmorChangeEvent.class, ItemType.class, new Getter<ItemType, PlayerArmorChangeEvent>() {
    @Override
    @Nullable
    public ItemType get(PlayerArmorChangeEvent e) {
        ItemStack item = e.getOldItem();
        Bukkit.getConsoleSender().sendMessage("Past: " + item.getType()); // DEBUG
        if (item != null) return new ItemType(item);
        return null;
    }
}, -1);
EventValues.registerEventValue(PlayerArmorChangeEvent.class, ItemType.class, new Getter<ItemType, PlayerArmorChangeEvent>() {
    @Override
    public ItemType get(PlayerArmorChangeEvent e) {
        ItemStack item = e.getNewItem();
        Bukkit.getConsoleSender().sendMessage("Current: " + item.getType()); // DEBUG
        if (item != null) return new ItemType(item);
        return null;
    }
}, 0);
```

using this code:
```vb
on player change armor:
    send "Past: %past event-item%" to console
    send "Current: %event-item%" to console
```
When changing from diamond leggings to gold leggings, the values should be different, but they output the same, also if you look at my Java code, I added two debug messages in, one for each event value, and the past value is not firing to console, this is the output when changing from diamond to gold leggings:

```
[23:12:55 INFO]: Current: LEGACY_GOLD_LEGGINGS <-- plugin debug message
[23:12:55 INFO]: Past: gold leggings
[23:12:55 INFO]: Current: LEGACY_GOLD_LEGGINGS <-- plugin debug message
[23:12:55 INFO]: Current: gold leggings
```
as you can see, it sends "CURRENT" event value for both past event-item and event-item

### Expected Behavior
The past/future event values should properly register and work.

### Errors / Screenshots
none -> see code above

### Server Information
* **Server version/platform:**       
* **Skript version:** Paper = git-Paper-187 (MC: 1.14.4)

**Comment by OfficialDonut** [comment]
https://github.com/SkriptLang/Skript/issues/671

**Comment by ShaneBeee** [comment]
Oh damn ... how did I miss that.  Oops.
