### ISSUE TITLE
Offlineplayer that has not joined the server returns null in variable

### ISSUE THREAD

**Issue by BladeMC1** [SkriptLang/Skript#2458]
```vb
command /fpa [<Text>] [<offlineplayer>]:
    permission: sa.as
    trigger:
        if arg 1 is "isim":
            add arg-2 to {fa::*}
            send "Başarı ile %arg-2% &feklendi" to player
```
I add people with this command and when I add: http://prntscr.com/p6a5sh
When you restart the server: http://prntscr.com/p6a5xa

Server and skript relase: http://prntscr.com/p6cdca

**Comment by ShaneBeee** [comment]
1) Any version other than the newest version of Skript is no longer supported
2) 1.8.8 and below has never been supported by this fork
3) When creating a new issue, please don't delete the template, actually fill it in.

**Comment by Blueyescat** [comment]
I can confirm this on a Paper 1.13.2 server with Skript 2.4-beta7, happens if the offline player saved in a variable has never played on the server.

**Comment by FranKusmiruk** [comment]
Be aware that even if this bug is fixed, neither your minecraft version nor your Skript version is supported anymore so you won't be able to solve this without updating.
