### ISSUE TITLE
Beacon item in Skript is different than in vanilla Minecraft.

### ISSUE THREAD

**Issue by CHarcoalToast** [SkriptLang/Skript#2459]
### Description
The beacon item has different data than the vanilla Minecraft.

### Steps to Reproduce
Since I can't make GIFs, I am going to describe the steps.

1. Go in creative inventory and take a beacon
2. Then type '!give "beacon" parsed as itemtype to player (or just beacon, you need a Skript option for this.)
3. Normally, you should have 2 beacons stacked on eachother, but instead of that, they split. When you hover the beacons in your inventory, you'll see that the vanilla one has no tags, but the skript one has "1 NBT tag". I don't know why, but I think because of that, it splits instead of stacking.

### Server Information
* **Server version/platform:**       Spigot 1.13.2
* **Skript version:**                       2.3.7

### Additional Context
This may seem a small problem, but it actually infects one of my Skripts heavily, because I really need a beacon.

**Comment by Wealthyturtle** [comment]
Possibly related to #2395

**Comment by Wealthyturtle** [comment]
Using Sk-NBeeT, found that Skript's beacon item has an NBT tag of ``{Levels:0.0d}``, while vanilla beacons do not have any NBT tags

**Comment by CHarcoalToast** [comment]
> Using Sk-NBeeT, found that Skript's beacon item has an NBT tag of `{Levels:0.0d}`, while vanilla beacons do not have any NBT tags

Thank you for testing this. This would be a tiny improvement and (I think) really easy to fix. Not a high priority tho.

**Comment by TheBentoBox** [comment]
Yeah, I'll definitely put in a fix for this soon, mostly just been falling to the wayside due to being a pretty low prio issue. I figured it was this exact issue since I remember adding support for beacon levels a while back.

**Comment by CHarcoalToast** [comment]
I think this can be closed as the PR is already merged?

**Comment by TheBentoBox** [comment]
As far as I can tell there hasn't been a release posted which actually contains this fix. The aliases submodule wasn't updated for beta8. This shouldn't be closed until there's a release containing it but it does need labels.
