### ISSUE TITLE
skRayFall scoreboard broken

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2463]
### Steps to Reproduce
every second:
   loop all players:
      wipe loop-player's sidebar
      set name of sidebar of loop-player to "&e&l<SERVER NAME REMOVED>"
      set score "&r" in sidebar of loop-player to 6
      set score "&bRank: &f%loop-player's prefix%" in sidebar of loop-player to 5
      set score "&bSell Booster: %{sb.%player%}%" in sidebar of loop-player to 4
      set score "&bMoney&8: &f%loop-player's balance%" in sidebar of loop-player to 3
      set score "" in sidebar of loop-player to 2
      set score "&e<IP REMOVED>" in sidebar of loop-player to 1    

### Expected Behavior

put the variable in the sidebar
### Errors / Screenshots
There's no loop that matches 'loop-player to 4'
### Server Information
* **Server version/platform:** 1.14 spigot
* **Skript version:**   2.4-beta5-MH
SkRayFall latest

**Comment by Jayderp** [comment]
My code is indented, it's just that github is really stupid.

**Comment by Jayderp** [comment]
fuck...
set score "&bSell Booster: **_%{sb.%player%}%_**" in sidebar of loop-player to 4

closed

**Comment by ShaneBeee** [comment]
A couple things to keep in mind, for future bug reports:
1) This issue tracker is for the Skript plugin itself, not for Skript addons. Each addon is handled by its own dev, you should report bugs to them
2) `Skript version: 2.4-beta5-MH` <-- Skript only supports its own version. Minehut uses an outdated fork of Skript, so any issues should be reported to them.
