### ISSUE TITLE
Getting item's name in functions returns nothing

### ISSUE THREAD

**Issue by SpinKnight** [SkriptLang/Skript#2468]
**Description**
When passing an item through a function, then getting it's name with `name of %item%` will return nothing (\<none\>).

**Steps to Reproduce**
Make a function that takes in an item as a parameter, then output the name of the passed-in item by broadcasting it with `name of %item%`. Make sure the item is named and does not have it's default name.
Make an event or command that explicitly outputs the name of an item within the command/event. After that pass in the exact same item into the function described above.

**Expected Behavior**
Being able to get an item's name through a function.

**Errors / Screenshots**
![image](https://user-images.githubusercontent.com/50058385/65245422-e162db00-daec-11e9-9207-85b17dcdf4ca.png)

**Code:**
```
on rightclick on chest:
    broadcast "in event:"
    broadcast "%name of player's tool%"
    getItemName(player's tool)

function getItemName(i:item):
    broadcast "in function:"
    broadcast "%name of {_i}%"
```

**Server Information**
* **Server version/platform:** Paper 1.14.4 (git-Paper-187)
* **Skript version:** 2.4-beta7

**Comment by FranKusmiruk** [comment]
Try using `itemtype` instead of just `item`.

**Comment by SpinKnight** [comment]
I already tested that, it doesn't fix the issue. I get the same output (\<none\>).

**Comment by Govindass** [comment]
it's a bug of variables to be exact and not functions, "%name of {_anyvaritem}%" will cause <none>

**Comment by SpinKnight** [comment]
It's still quite a bug since you'd otherwise have to split it to get the name.

**Comment by Blueyescat** [comment]
addons?

**Comment by Blueyescat** [comment]
Can't confirm with Paper 1.14.4 - Skript 2.4-beta8, it is probably related to addons like Vixio v2.0.0, it has a `name of` expression which is changed to `discord name of` in v2.0.1.

**Comment by FranKusmiruk** [comment]
@SpinKnight did you test this without addons? If not, please do so.

**Comment by Wealthyturtle** [comment]
Unable to replicate with vanilla Skript, closing this issue.
