### ISSUE TITLE
Detecting right click on an armor stand

### ISSUE THREAD

**Issue by ItzArty** [SkriptLang/Skript#2469]
Hi girls,
is there any way to detect right click on armor stands, since I have tested a lot of different ways, but nothing did work, hm?

**Comment by Wealthyturtle** [comment]
Think you can do it via this script
```
on right click:
	if "%entity%" is "armor stand":
		broadcast "Armor Stand"
```

**Comment by FranKusmiruk** [comment]
The issue tracker is reserved for bugs, feature requests and questions about Skript's API/implementation. If you're seeking for support please use the forums or enter the discord guild.
