### ISSUE TITLE
The style "command" doesn't work properly

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2472]
### Description
When you use the style "command" in a text message, and you want to use an argument of your command, it won't work. I get the style in the message. (The screenshot will explain everything.)

### Steps to Reproduce
Put this script in a document:
![Schermopname (442)](https://user-images.githubusercontent.com/38358953/65353077-857f7b80-dbec-11e9-9509-91c61c83bd4e.png)

### Expected Behavior
I expext the text "This is text." in the chat and if I click on it, I expext to get the message "It works!"

### Errors / Screenshots
No console errors; here a screenshot:
![2019-09-20_21 14 19](https://user-images.githubusercontent.com/38358953/65352866-0427e900-dbec-11e9-9a96-06042885e721.png)

### Server Information
* **Server version/platform:**       Paper 1.14.4
* **Skript version:**                Skript 2.4-beta7

**Comment by Wealthyturtle** [comment]
This is due to a security update. For formatted messages you now have to use ``message formatted``
