### ISSUE TITLE
Placing a bed using "set block" at a certain position places either the foot or the head of the bed (not consistent!) 

### ISSUE THREAD

**Issue by Zulfen** [SkriptLang/Skript#2473]
Placing a bed using "set block" at a certain position places either the foot or the head of the bed at the location. 
**Code:**
```
command /trybedplace:
   trigger:
      set {_location} to location (-79, 68, 34) in world of player
      set block at {_location} to west facing red bed head
```
What I expected my code to do is place, for example, the head of the bed (and thus the rest of the bed) consistently at the location.
**Screenshots:**
Command try 1:
https://ibb.co/C5kQxMT
Command try 2:
https://ibb.co/TPw955S

**Server info:**
* **Server version/platform:** ```2.4-beta7```
* **Skript version:** ```This server is running Paper version git-Paper-175 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)```

If you need any extra info, please ask :)

**Comment by Zulfen** [comment]
Here are the images here if you dont want to use the links:
![2019-09-20_21 19 48](https://user-images.githubusercontent.com/38318382/65357364-c7112600-dbee-11e9-9dee-75f6497949d5.png)
![2019-09-20_21 19 41](https://user-images.githubusercontent.com/38318382/65357366-c7112600-dbee-11e9-8d4d-768de70a91f6.png)

**Comment by Zulfen** [comment]
Update: I am using the latest versions of skRayFall and skUnity. Sorry for not specifying earlier.

**Comment by Wealthyturtle** [comment]
Can confirm this with vanilla Skript. Thanks for reporting!

**Comment by Ofus-Will** [comment]
bump
