### ISSUE TITLE
Multiple lines in kick-reason?

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2474]
### Question
Is it possbile to do something like
`
command /test:
	trigger:
		kick the player due to "Test %new line% test"`

So you can see the message on different lines?

**Comment by Blueyescat** [comment]
Yes that code would work fine but Skript itself doesn't have line breaks yet. The SkQuery addon provides the `(nl|new line)` expression.

**Comment by Anoniempje1234** [comment]
Maybe something to add to Skript? I think more people would like this :)

**Comment by Wealthyturtle** [comment]
It's been discussed before but not yet implemented because it'd need some overhauling on other expressions, e.g. new lines may work on messages but cause issues in item lore

**Comment by Anoniempje1234** [comment]
Oh, I understand;
Maybe you can do something like:
`command /test:
	trigger:
		kick the player due to "line 1", "line 2" and "line 3"`
I think you can use it in an item lore as well.
It's just idea :)

**Comment by Wealthyturtle** [comment]
Good idea, might do a PR on it
