### ISSUE TITLE
Compatible Error with CatServer

### ISSUE THREAD

**Issue by MaPaJe** [SkriptLang/Skript#2480]
Im running catserver which is a spigot/forge "fork" but for some reason i get skript errors upon load

My Skript Version is: Beta 5 2.4
CatServer Version: Latest
 Ver:  This server is running CatServer version git-CatServer-1.12.2-3c5e7d0 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2848)

Steps to reproduce: 
Use CatServer and skript

https://hastebin.com/akawaquvij.rb

**Comment by Wealthyturtle** [comment]
Duplicate of #2339
