### ISSUE TITLE
Online/Offline comparison issues

### ISSUE THREAD

**Issue by APickledWalrus** [SkriptLang/Skript#2483]
### Description
A few months ago, I reported #1939. That issue was closed for being user error / no longer reproducible, but on 2.4-beta7 I have encountered what I think is an actual issue with the condition.

### Steps to Reproduce
https://gist.github.com/APickledWalrus/0b0be38865f9276631aa25052bc367e5

### Expected Behavior
"ONLINE A" should be displayed for all 3
"OFFLINE B" should not be displayed at all

I included the skript-mirror part as it may be useful for reference.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/29044720/65819935-c715b500-e1f0-11e9-9be6-71adac2791d2.png)

### Server Information
* **Server version/platform:**       git-paper-191 (MC: 1.14.4) 8 version behind
* **Skript version:**                2.4-beta7

**Comment by Wealthyturtle** [comment]
![image](https://user-images.githubusercontent.com/19924575/66209566-36f0d780-e6ea-11e9-93ae-00db5fea12e0.png)
Unable to replicate? Using Spigot 1.14.4 w/ Skript 2.4-beta8

**Comment by APickledWalrus** [comment]
I am still encountering this issue, but I will try updating Paper.

**Other Information**
![image](https://user-images.githubusercontent.com/29044720/66355503-8c6cf480-e935-11e9-8005-d6f29cd668e2.png)

**Comment by Wealthyturtle** [comment]
Have you tried to see if this can be replicated on a localhost server with Skript?

**Comment by Wealthyturtle** [comment]
Anything?

**Comment by APickledWalrus** [comment]
Really sorry for the lack of updates here. I will finish gathering the info for this and let you know ASAP!

**Comment by APickledWalrus** [comment]
After the long delay, I finally got the chance to test this (my apologies).
I was not able to replicate this on a localhost using:

2.4-beta9
git-Paper-223 1.14.4 (latest)
Windows 10 Home Version 10.0.18362 Build 18362
OpenJDK jre-12.0.2.10 OpenJ9

I am still able to replicate this on the original server using beta9 but still using the original version of paper.

**Comment by Wealthyturtle** [comment]
What about on localhost with the version of paper used on your main server?

**Comment by APickledWalrus** [comment]
Will test tonight/tomorrow

**Comment by APickledWalrus** [comment]
Oops... forgot about this.

Using the latest version of paper (225) I am no longer able to reproduce this on the original server, so I am going to close this issue. I did remove a bunch of plugins, so it was either one of them or paper causing the issue.
