### ISSUE TITLE
Remove effect don't work properly (beta8) :(

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#2489]
I've opened a ticket which related with this issue like 2 weeks ago. It was in Skript beta-5 and has been fixed in Skript beta-6 but the same issue appeared again Skript beta-7 and beta-8.

### Description
I've set my hotbar 0, 1 and 2 with two papers with nbt CustomItems:Summon_Skeleton_1/2/3 and I tried to remove them with function below. I attached two result belongs to Skript 2.3.7, Skript 2.4 beta-5 and Skript 2.4 beta-8.

### Expected Behavior
Remove just one in each hotbar. So Skript 2.3.7 works properly in that case.

### Errors / Screenshots
No errors in console.
Remove effect in Skript 2.4-beta-5: https://i.imgur.com/P0s2DD2.png
Remove effect in Skript 2.3.7: https://i.imgur.com/9qGhq9c.png
Remove effect in Skript 2.4 beta-8 (same result with beta-5): https://i.imgur.com/4WVktLC.png

### Server Information
* **Server version/platform:** Paper 1.13.2 Build 643(when beta-5) (+ Paper 1.14.4 Build 187 when beta-8)
* **Skript version:** Skript 2.4-beta-5(still exists in beta-7 and beta-8) in first screenshot, Skript 2.3.7 in second screenshot

```
command /nbttest:
	trigger:
		removeNBTItem(player, 1, "CustomItems:""Summon_Skeleton_1""")
		removeNBTItem(player, 1, "CustomItems:""Summon_Skeleton_2""")
		removeNBTItem(player, 1, "CustomItems:""Summon_Skeleton_3""")
function removeNBTItem(p: player, a: number, nbt: text):
	broadcast " ", " "
	broadcast "&bSearching: %{_nbt}%"
	loop all items in {_p}'s inventory:
		broadcast " "
		nbt of loop-item contains {_nbt}
		broadcast "&cRemoved: %loop-item%(%{_a}%)"
		remove {_a} of loop-item from {_p}
		stop loop
```

**Comment by Wealthyturtle** [comment]
From what you're saying, it looks like https://github.com/SkriptLang/Skript/commit/062a7236d4b988a2fc79d8cfe9707f247d507cfa broke something...

Cleaning up your script for others to take a crack at this issue
```
command /giveitem <string>:
	trigger:
		set {_i} to dirt
		set nbt of {_i} to arg-1

command /nbttest <string>:
	trigger:
		removeNBTItem(player, 1, arg-1)

function removeNBTItem(p: player, a: number, nbt: text):
	broadcast " ", " "
	broadcast "&bSearching: %{_nbt}%"
	loop all items in {_p}'s inventory:
		broadcast " "
		nbt of loop-item contains {_nbt}
		broadcast "&cRemoved: %loop-item%(%{_a}%)"
		remove {_a} of loop-item from {_p}
		stop loop
```

**Comment by bensku** [comment]
Can someone provide a test case without NBT?

**Comment by Alderheart** [comment]
I can. ```
on death:
	remove all nether quartz from drops
```

**Comment by legofreak1999** [comment]
The whole remove effect with items seems to be broken. Still with beta9.

```
command /remove:
	trigger:
		remove all paper from player
```

**Comment by TPGamesNL** [comment]
Cannot reproduce, this has probably been fixed
