### ISSUE TITLE
offlineplayer does not work

### ISSUE THREAD

**Issue by Malfrador** [SkriptLang/Skript#2494]
### Description

The "offlineplayer"-Expression does not work as intented. Neither does it work as a command argument (<offlineplayer> nor as an if/else statement.
`command /example <offlineplayer>` allows every text as an argument. 
`if arg 1 is a offlineplayer` always returns false.
%size of all offline players% works fine.
### Steps to Reproduce

Try a simple command with `command /example <offlineplayer>:` Use /command (Playername that does not exist) inGame. The command will work, but it should not because the offline player does not exist. 
### Expected Behavior

The command not to work and the if/else statement to return "true" for  "is a offlineplayer".

### Server Information
* **Server version/platform:**  1.13.2, Paper     
* **Skript version:**  2.4-beta5

**Comment by Blueyescat** [comment]
An OfflinePlayer may or may not be a player that has played on the server. You can use the `has played before` condition to check it.

> `if arg 1 is a offlineplayer` always returns false.

It is meant to check whether the type of `arg 1` is offlineplayer, yes should return true.

**Comment by FranKusmiruk** [comment]
Closing as this is a misunderstandment from the user.
