### ISSUE TITLE
bug with on inventory click -> skript infinitely repeated itself

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2496]
Latest Skript: Skript v2.4-beta8

**skript:**
```
on inventory click:
	if "%clicked inventory%" is "inventory of %player%":
		message "test"
```
or
```
on inventory click:
	message "%clicked inventory%"
```
or
```
on inventory click:
	message "%event-inventory%"
```

same error with

```
on inventory open:
	message "%event-inventory%"
```

**error:**
https://i.imgur.com/kjoLVZC.png

**how to reproduce:**
open a chest and click in its inventory

**Comment by bloggy** [comment]
And another issue with adding items from chest inventory to a list var:

```
command /testi [<text>]:
	trigger:
		if targeted block is any chest:
			message "&eUsing Targeted Chest..."
			loop all items in inventory of targeted block:
				message "Added: &e%loop-item%"
				add loop-item to {_test::*}
```

error:
https://i.imgur.com/pzzt3tq.png
(there is no error in the console)

**Comment by FranKusmiruk** [comment]
Can someone confirm this?

Also, next time, do not delete the issue template, there's info we may need there.

**Comment by Blueyescat** [comment]
Can you show the console error for the `another issue`

**Comment by bloggy** [comment]
yes but there is no error in the console except of:
[18:42:17] [Server thread/INFO]: [Skript] The script 'gui_creator.sk' infinitely (or excessively) repeated itself!

**Comment by bloggy** [comment]
I have this bug with only a few plugins installed on my server, see startup log:
https://pastebin.com/tfvbiSQZ

I tested this script:
```
command /testi [<text>]:
	trigger:
		if targeted block is any chest:
			message "&eUsing Targeted Chest..."
			loop all items in inventory of targeted block:
				message "Added: &e%loop-item%"
				add loop-item to {_test::*}

```

error:
https://i.imgur.com/i65WsGc.png

console log - after error message:
[18:51:02] [Server thread/INFO]: screamfine issued server command: /testi
[18:51:02] [Server thread/INFO]: [Skript] The script 'test.sk' infinitely (or excessively) repeated itself!

**Comment by FranKusmiruk** [comment]
Closing as @Blueyescat couldn't confirm it and there's a lack of information on the issue overall which leads me to believe this is an user-error.

**Comment by bloggy** [comment]
What spigot version & plugins do you have so I can test it with these exact versions?
Thank you
