### ISSUE TITLE
I can't use my skript

### ISSUE THREAD

**Issue by preadz19** [SkriptLang/Skript#2497]
Description
When i reload my plugin or my skript , thats write 1 skript load , 0 triggers , 0 command :|

Commande on the skript:

 Scommand /enchante [<text>] [<number>] [<text>]:
	trigger:
		if arg 1 is set:
			if arg 2 is set:
				if arg 3 is set:
					set {_enchantlvl} to "%arg 1% %arg 2%" parsed as enchantement type
					set {_nom} to "%arg 3%"
					enchant the player's tool with {_enchantlvl}
					set name of player's toll to colored "%{_nom}%"
					send "{@Valider}" to player
				else:
					send "@ErreurArg3" to player
					send "@ExempleEnchant3" to player
			else:
				send "@ErreurArg2" to player
				send "@ExempleEnchant2" to player
		else:
			send "@ErreurArg1" to player
			send "@ExempleEnchant" to player
			send " " to player
			send "ExempleCmd" to player

https://www.noelshack.com/2019-40-2-1569941578-sans-titre.png

/version 1.9
version Skript : lateast

**Comment by Matocolotoe** [comment]
c'est juste qu'un alias s'est mal chargé / an alias just loaded wrongly
(d'ailleurs pro anglais mdr)

**Comment by preadz19** [comment]
> c'est juste qu'un alias s'est mal chargé / an alias just loaded wrongly
> (d'ailleurs pro anglais mdr)

a ok et je fais comment ?

**Comment by Matocolotoe** [comment]
> > c'est juste qu'un alias s'est mal chargé / an alias just loaded wrongly
> > (d'ailleurs pro anglais mdr)
> 
> a ok et je fais comment ?

le chargement des alias n'affecte en rien tes fichiers...

**Comment by preadz19** [comment]
> > > c'est juste qu'un alias s'est mal chargé / an alias just loaded wrongly
> > > (d'ailleurs pro anglais mdr)
> > 
> > 
> > a ok et je fais comment ?
> 
> le chargement des alias n'affecte en rien tes fichiers...

euh ouai ok mais pk il marche pas ducoup

**Comment by Matocolotoe** [comment]
Skript ne supporte que les derniers patchs de chaque version, si tu as la 1.9 passe ton serveur en 1.9.4

**Comment by preadz19** [comment]
> Skript ne supporte que les derniers patchs de chaque version, si tu as la 1.9 passe ton serveur en 1.9.4

ducoup ta un moyen de le passer vite en 1.9.4

**Comment by FranKusmiruk** [comment]
Please use the issue template when reporting to the issue tracker. Also, we'd rather have the comments in English since it's what Skript is based off after all and the fact that it's the only language the current developers have in common.

That said, I am closing the issue.
