### ISSUE TITLE
Skript Enhancements

### ISSUE THREAD

**Issue by Olyno** [SkriptLang/Skript#2506]
Here is a todo list of changes I will do about skript:

 - [x] Update the [current skript website](https://skriptlang.github.io/Skript/index.html):
    - - [x] #611
    - - [x] #1253
    - - [x] #1429
    - - [x] #2425 
    - - [x] #1825
 - [x] Update default scripts examples:
    - - [x] #2252 

I just wanted to warn you what I was going to do, hence my issue. 
If you have any suggestion, question or other about one of these issues, please say it here. It will be more easily for me (and anyone who want help me) to follow.

**Comment by Wealthyturtle** [comment]
What about #1825?

**Comment by Olyno** [comment]
> What about #1825?

Added 👍
