### ISSUE TITLE
llama and trader llama are interchanged

### ISSUE THREAD

**Issue by Padlick01** [SkriptLang/Skript#2507]
### Description
As the title says, normal llamas and trader llamas are reversed.

### Steps to Reproduce
EFFECT COMMANDS:
spawn a llama at player                |  spawns a trader llama
spawn a trader llama at player     |  spawns a normal llama

### Expected Behavior
spawn a llama should spawn a normal llama and spawn a trader llama should spawn a trader llama.

### Errors / Screenshots
There isnt any error.

### Server Information
* **Server version/platform:**       git-Paper-209 (MC: 1.14.4)
* **Skript version:**                2.4-beta8

**Comment by TheBentoBox** [comment]
Can confirm
