### ISSUE TITLE
Loop exploded blocks giving error

### ISSUE THREAD

**Issue by ghost** [SkriptLang/Skript#2509]
In previous versions you could loops blocks that were apart of an `on explode:` event. This seems to no longer be the case. Now it returns `Can't under this loop: 'loop exploded blocks'`.

```
on explode:
	loop exploded blocks:
		set location of loop-value to tnt
```
This returns the error listed [here](https://i.imgur.com/TDBiS9D.png), in earlier versions this would've set the blocks looped to tnt, with the code above. I looked in the docs and github issues/changelog I didn't see any mention of a change to how loops work so I'm unsure why this no longer works.

### Server Information
* **Server version/platform:** 1.14.4-Spigot built from BuildTools 10/3/19
* **Skript version:** 2.4-beta8

**Comment by ShaneBeee** [comment]
If I'm not mistaken `exploded blocks` is part of SkQuery not Skript

**Comment by Wealthyturtle** [comment]
Yes, Skript does not support the looping of exploded blocks, that’s SkQuery

**Comment by TheBentoBox** [comment]
While the others are correct I guess we could take this in as an `exploded blocks` feature request. Would be a good addition!

**Comment by diamondpumpkin** [comment]
I'm sorry, didn't realize SkQuery was the one that added it. I suppose I'm just too stupid, I really don't deserve life.
