### ISSUE TITLE
Severe Error [1.14]

### ISSUE THREAD

**Issue by Mehehehehe82** [SkriptLang/Skript#2517]
The console threw out [this mess](https://hastebin.com/ezivoqopiq.md). (Yes, twice.)
I am using the following plugins:

- CommandHook.jar
- InteractiveBooks.jar
- ItemBind.jar  MobStacks.jar
- Multiverse-Core-4.1.0.jar
- Multiverse-Portals-4.1.0.jar
- Nicknamer.jar
- PlugMan.jar
- Skript.jar (of course)
- StackSize.jar  worldedit-bukkit-7.0.1.jar

**Comment by TheBentoBox** [comment]
Duplicates #2487.
