### ISSUE TITLE
Docs Glow Example

### ISSUE THREAD

**Issue by APickledWalrus** [SkriptLang/Skript#2518]
### Description
The example code for the glow expression errors.

### Steps to Reproduce
Try and run the example code. It will error.

### Expected Behavior
The example should be updated or it should be made possible to write the expression in the shown way.

``set glowing of player on`` doesn't work
``set glowing of player to on`` works

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/29044720/66242484-bb822c80-e6cf-11e9-80c3-6c2de6e06b35.png)
![image](https://user-images.githubusercontent.com/29044720/66242427-92fa3280-e6cf-11e9-97b6-edf624189841.png)
![image](https://user-images.githubusercontent.com/29044720/66242437-98577d00-e6cf-11e9-9188-e39de7d0aac0.png)

### Server Information
* **Server version/platform:**       git-paper-191 (MC: 1.14.4) (18 versions behind)
* **Skript version:**                2.4-beta7 (I know it's not the latest but the I do not think the bug would be fixed)

**Comment by APickledWalrus** [comment]
This issue is good to be closed now.

**Comment by Wealthyturtle** [comment]
This is in the 2.4-beta10 release but for some reason is not in the 2.4 branch... will close when it is added there.
