### ISSUE TITLE
Dye RGB Numeric ids are not supported anymore

### ISSUE THREAD

**Issue by larsjarred9** [SkriptLang/Skript#2528]
### Description
There is an issue with RGB when using dye. It thinks that the RGB is a Numeric ID

### Steps to Reproduce
**After giving the player an item:**
dye {_armour) (189, 148, 0)

And then giving the player that item with give player 1 {_armour}

**When using in a menu:**
format slot 31 of player with leather leggings dyed (189, 148, 0) named "&cLion Outfit Pants" to close

### Expected Behavior
There should be no error and RGB should work perfectly fine

### Errors / Screenshots

"Numeric ids are not supported anymore"
https://prnt.sc/pfhn7t

### Server Information
* **Server version/platform:**      git-Paper-1613 MC: 1.12.2
* **Skript version:**                2.4-Beta-8

**Comment by bluelhf** [comment]
`%itemtypes% dyed %color%` isn't a valid expression.

**Comment by larsjarred9** [comment]
![image](https://user-images.githubusercontent.com/31996561/66267145-fc905300-e82d-11e9-9121-24b37509487a.png)

**Comment by ShaneBeee** [comment]
> ![image](https://user-images.githubusercontent.com/31996561/66267145-fc905300-e82d-11e9-9121-24b37509487a.png)
> 
> Example that doesn't use an addon

the dyed syntax you are using is an effect, not an expression, so it won't work that way.

**Comment by larsjarred9** [comment]
Issue fixed
