### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2529]
Suggestion. Add expression add 50 hearts to %livingentities%, remove 50 hearts from %livingentities%. It should add/remove hearts to entity. Just like "set the last spawned entity's max health to 1000" but in my suggestion is add.

2.Duplicate entity? I would like to edit NBT to entity and after duplicate him.

**Comment by bluelhf** [comment]
NBT is unsupported by Spigot and thus is unlikely to get added to Skript, health addition/subtraction seems unnecessary since you can just use `set health of last spawned entity to (health of last spawned entity - 2)`, but I think it could be a nice small addition

**Comment by Misio12320** [comment]
+ if talking about add health to entity there should be option to "add 2 point|s to  %livingentities% movement speed" in mean potion of speed should be increased to entity if you know (reader) what I mean.

**Comment by TheBentoBox** [comment]
You can already add or subtract from an entity's max health with `add %number% to %entity%'s max health` and `subtract %number% from %entity%'s max health`.

Cloning an entity isn't properly supported by the Bukkit API as far as I'm aware and we don't deal in NBT or NMS.

**Comment by Matocolotoe** [comment]
@Misio12320 you really are a weird person I mean you dislike every message on the repo when you realize you're wrong or when you wanna have fun disliking idk

**Comment by Misio12320** [comment]
Where I have disliked? My last disliked post was 10 days ago. So where is this every message. Dude.

**Comment by ShaneBeee** [comment]
> Where I have disliked? My last disliked post was 10 days ago. So where is this every message. Dude.

Just incase you forgot:
![Screen Shot 2019-10-07 at 1 47 44 AM](https://user-images.githubusercontent.com/20008482/66297434-87ac3000-e8a4-11e9-959f-59bc3c3c70c2.png)

**Comment by Wealthyturtle** [comment]
![image](https://user-images.githubusercontent.com/19924575/66298132-aef61200-e923-11e9-8f50-af280c267d91.png)
This too.
