### ISSUE TITLE
Replace First Effect

### ISSUE THREAD

**Issue by APickledWalrus** [SkriptLang/Skript#2531]
### Description 
It could be useful if there was an effect to replace the first occurrence of a text in an object. I don’t think this already exists, but I may be wrong.

Example Syntax:
``replace first %texts% in %texts% with %text%``

**Comment by Wealthyturtle** [comment]
Correct me if I'm wrong, but shouldn't it be ``replace first %texts% in %texts% with %text%``? Don't understand how ``replace first "example" in player's inventory with "example2"`` would work

**Comment by APickledWalrus** [comment]
> 
> 
> Correct me if I'm wrong, but shouldn't it be `replace first %texts% in %texts% with %text%`? Don't understand how `replace first "example" in player's inventory with "example2"` would work

My bad, I meant %texts%. I have changed the description to fit.
