### ISSUE TITLE
did not work (HELP)

### ISSUE THREAD

**Issue by ReQiuYTPL** [SkriptLang/Skript#2533]
good morning i am going to make a minecraft server with my friend on version 1.14.4 Bukkit. but when I put the Script plugin it doesn't work and I have this error:

https://imgur.com/a/0Wv4pBh

**Comment by APickledWalrus** [comment]
Instead of using CraftBukkit, use PaperSpigot. Also, please use the issue template in the future as it makes it easier to determine the issue :)
