### ISSUE TITLE
Missing mooshroom variations in 1.14+

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#2537]
### Description
Skript currently does not have a way to spawn a brown mooshroom

### Steps to Reproduce
try:
```vb
spawn brown mooshroom
```

### Expected Behavior
Be able to spawn a brown mooshroom

### Errors / Screenshots
![Screen Shot 2019-10-08 at 1 46 12 AM](https://user-images.githubusercontent.com/20008482/66381055-72e79f00-e96d-11e9-8464-f0e5780fe5ca.png)

### Server Information
* **Server version/platform:**  git-Paper-209 (MC: 1.14.4)
* **Skript version:** Skript 2.4-Beta8

### Additional Context
I'm creating a PR for this.

**Comment by FranKusmiruk** [comment]
I actually didn't know 1.14 added those or I would have done it earlier, my bad on that one.

**Comment by ShaneBeee** [comment]
> I actually didn't know 1.14 added those or I would have done it earlier, my bad on that one.

No worries, gave me a chance to try out adding a new entity data :) so it's a win win.
