### ISSUE TITLE
i don`t know skunity`s click type

### ISSUE THREAD

**Issue by tegy1117** [SkriptLang/Skript#2539]
What is wrong in this project? It`s say click type is wrong
How many click types in skunity? and what is that?and please steele...
this is my skunty construction.
   if click type is "RIGHT":
   if click type is "SHIFT_RIGHT":
   if click type is "LEFT":
   if click type is "SHIFT_LEFT":

waht is wrong?

**Comment by TheBentoBox** [comment]
1. The list of click types can be found [here](http://skriptlang.github.io/Skript/classes.html#clicktype). Please use the documentation when you have issues in the future.
2. Please use the issue template for all issues. You didn't provide us with any information about your server or Skript version so it is effectively impossible for you to receive help.
3. This plugin is called Skript, not skUnity.
