### ISSUE TITLE
Variables being set to any type - (maybe) a bug

### ISSUE THREAD

**Issue by aescraftbr** [SkriptLang/Skript#2544]
### Question
I got a question regarding the variables.
When you set a variable to be "any disc", for example, it would be set to all the list, instead of just one.
```
command /testdisc:
  trigger:
    set {_disc} to a disc
    loop 2 times:
      send "%{_disc}%"
    set {_disc} to a random element out of a disc
    loop 2 times:
      send "%{_disc}%"
```

{_disc} is being set to "record 11, record 13, record blocks, record cat" and so on
even "random element out of a disc" won't set it to a single value.

This is a intended feature, or a bug?
Thanks!

**Comment by MrScopes** [comment]
try using list variables

**Comment by CHarcoalToast** [comment]
Since 'a disc' is basically 'any disc', Skript will at a sort of 'or' list. When taking something from that list, it will always be random. It looks complicated, but when you need one sort of disc from a list, just try to add every disc you want to a list.

**Comment by APickledWalrus** [comment]
Related to #2194?

**Comment by Wealthyturtle** [comment]
Definitely related, but since this isn't a direct duplicate it should be left open

**Comment by Wealthyturtle** [comment]
Closing this issue in favor of #2194 for tidiness
