### ISSUE TITLE
Setting/Resetting player weather broken

### ISSUE THREAD

**Issue by VacantFiend** [SkriptLang/Skript#2551]
Setting/resetting player weather seems to be broken unless i'm doing something wrong?

```
on player's held item change:
  if player's held item is dirt:
    set weather to rain
```

Successfully changes the world's weather to rain.

```
on player's held item change:
  if player's held item is stone:
    set player's weather to rain
```

Instantly changes the player's weather to clear.

```
on player's held item change:
  if player's held item is cobblestone:
    reset player's weather
```

Also changes player's weather to clear.

**Comment by ShaneBeee** [comment]
I can confirm this. Setting the player's weather to anything just sets it to sun
