### ISSUE TITLE
Serialization of items changed from 1.13.2 to 1.14.4+

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2554]
Skript: v2.4-beta8

Error (look at the lore):
https://i.imgur.com/kEtKH7E.png

This happened to many items stored in the database in 1.13.2. When I give me such an item, the lore is bugged.

**Comment by ShaneBeee** [comment]
I could be wrong, but I think this is a Spigot issue. 
When 1.14 came out, lores changed, and plenty of people had issues with lores on Spigot.
I can't remember how exactly they changed, but it was a formatting change of some kind.

**Comment by TheBentoBox** [comment]
> I can't remember how exactly they changed, but it was a formatting change of some kind.

Lore used to be a list of raw strings and it was changed to an array of JSON elements.

As for whether or not this is actually a Spigot issue, no idea. I'd like to hear more opinions.

**Comment by bensku** [comment]
If your items are stored in variables, I can see how this could happen. Skript serializes ItemMeta on 1.13, and deserializes on 1.14 using Spigot-provided serializer. It might not work well with lore.

**Comment by Wealthyturtle** [comment]
This could potentially 'corrupt' items that are being stored by Skript, needs a workaround or fix of some sort

**Comment by bloggy** [comment]
Yes these items are stored in the default skript database.

**Comment by bensku** [comment]
I'm not sure if it is possible to fix this. We could adopt our own item serialization format, but we *can't* easily change parsing of ItemMeta serialized with Java serialization.

**Comment by bensku** [comment]
Chances are that not too many people are updating from 1.13 to 1.14 anymore.

**Comment by bloggy** [comment]
We are still on 1.13.2. We are planning to upgrade to 1.15 because 1.14 is a pain in the *** for busy production servers regarding its poor performance. I hope there will be no issues on 1.15?

**Comment by bensku** [comment]
This is likely to accept people updating from 1.13.2, unfortunately.

**Comment by bloggy** [comment]
This still is not fixed?

**Comment by bensku** [comment]
@bloggy This is correct. Only few things have been fixed since I last commented here.

**Comment by bloggy** [comment]
I noticed it :-( Many of the items we stored in database are showing incorrect lores now (especially line 1 of the lore of an item seems to get its color tags removed).
