### ISSUE TITLE
Ambiguity between on step and on stepping events

### ISSUE THREAD

**Issue by MaPaJe** [SkriptLang/Skript#2555]
### Description
The on stop on pressureplate event is only triggered upon jumping on it.
Skript version 2.4 beta-7
Paper 1.12.2 

This for some reason wasn't a problem in 2.4Beta-5

Tested Versions:
2.4 Beta-8: Problematic
2.4 Beta-7: Problematic
2.4 Beta-6: Problematic
2.4 Beta-5: Working as expected
2.4 Alpha-4: Problematic
2.3.7: Problematic
2.3.6: Problematic
2.3.5: Working as expected
2.3.3: Problematic
2.3.2: Working as expected
2.3.1: Working as expected
2.2 Dev36 Working as expected

### Steps to Reproduce
on step on pressure plate:
	broadcast "%event-block%"
	broadcast "&6Congratz you stepped on me"

stepping on it / jumping on it

### Expected Behavior
Triggers upon any move on a pressureplate like in 2.4 Beta 5

### Errors / Screenshots
https://gyazo.com/1dbffaea66d521bec10abbc85f4f9a7f

**Comment by ShaneBeee** [comment]
> Skript version 2.4 beta-7

Since we only accept bug reports for the latest version available, could you please test this on version [**2.4-beta8**](https://github.com/SkriptLang/Skript/releases/tag/2.4-beta8) and report back your findings.

**Comment by MaPaJe** [comment]
I've tested on multiple versions now.

**Comment by TPGamesNL** [comment]
You shouldn't use this event, it's not meant for pressure plates. Use [this](https://skriptlang.github.io/Skript/events.html#pressure_plate_trip) instead.

**Comment by MaPaJe** [comment]
It's the event Im using, Look at the syntax @TPGamesNL

**Comment by TPGamesNL** [comment]
> It's the event Im using, Look at the syntax @TPGamesNL

Sorry, I didn't notice since they have like the exact same syntax, which might be the issue. Can you check if `on plate:` works?

**Comment by ShaneBeee** [comment]
I've tried this on both Paper 1.12.2 and Paper 1.14.4, both using Skript 2.4-beta8, and I could not replicate the issue.
Every time I walk onto a pressure plate, it fires the event.

Are you possibly using any addons which may be causing conflicts?
Try replicate this issue without any addons on your server.

**Comment by MaPaJe** [comment]
No addons just a regular stone pressure plate

**Comment by bluelhf** [comment]
I remember there being an issue where you wouldn't trigger the step event for the plate, but for thd block below it, since you aren't really stepping on the plate itself.

**Comment by MaPaJe** [comment]
If you go from a carpet onto the pressure plate, the event will always be fired

**Comment by MaPaJe** [comment]
Using On Plate: yields a consistant outcome
Why the event is triggered differntly between versions, still bothers me

**Comment by MaPaJe** [comment]
I think on step on pressure plate: should trigger on plate,
its because its conflicting with the on step event

**Comment by ShaneBeee** [comment]
so what I noticed is as follows:
```vb
on step on pressure plate:
```
this triggers the "step on" event, the reason this doesnt fire is because you arent stepping on the pressure plate block, since you are already technically on it.

```vb
on stepping on pressure plate:
```
this fires the pressure plate event, which fires consistently when you walk/jump on it.

**Comment by bensku** [comment]
That seems confusing. We need to update syntaxes.

**Comment by TheLimeGlass** [comment]
This has been broken since around 1.10. I don't know if it still does this but; if you cancelled the event without waiting a tick it would send you through the block. Here is a video I posted about it back in 2016 https://www.youtube.com/watch?v=V_rUiqICfvA
