### ISSUE TITLE
When using color codes, only the first line of the chat will be coloured

### ISSUE THREAD

**Issue by CHarcoalToast** [SkriptLang/Skript#2556]
### Description
When using color codes in a text/string that uses more characters than the width of the player's chat, the second line and the lines after the first won't be coloured anymore.

### Steps to Reproduce
I just tried this:
```
command /test:
    trigger:
        send "&aTestttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt"
```

### Expected Behavior
It will print the message over multiple lines in the same color, but it doesn't.

Even with the 'colored %text%' expression.

### Server Information
* **Server version/platform:**       Spigot 1.13.2
* **Skript version:**                2.4-beta8

**Comment by TPGamesNL** [comment]
I remember this being a bug in the Minecraft client in ~1.8, but I think it's been fixed long ago. Anyway, this is probably not an issue with Skript since the client is responsible for splitting the text into multiple lines, not the server.

**Comment by Wealthyturtle** [comment]
This is technically not Skript's fault because it's an issue with the client resetting colors each line, including text overflows. See https://www.spigotmc.org/threads/json-message-losing-color-on-new-line.31949/ for more info

**Comment by JRoy** [comment]
@CHarcoalToast what client (or mod) are you using?

**Comment by Wealthyturtle** [comment]
Edit: After some discussion, since this issue arises from the client's side, and there are many different client GUI resolutions, scales, etc. it is not possible for Skript to help handle this type of issue (you could try and force players to use Minecraft 1.8 and above to fix this)

**Comment by CHarcoalToast** [comment]
I am using 1.13.2 on my private test server. If Skript can’t fix this, can you leave a way I can do it myself (for example getting the color of a letter or some other way)

**Comment by Wealthyturtle** [comment]
Just spam color codes wherever you think they’ll lose color, there’s no way other than that. Getting the color of a particular character is not helpful.
