### ISSUE TITLE
Log Handlers

### ISSUE THREAD

**Issue by Creeper1841** [SkriptLang/Skript#2563]
Description
When starting the server, over 22k "log handlers" weren't stopped properly and it's impossible to start the server again.

Steps to Reproduce
I'm not sure how it happened, we just restarted the server, when using some functions and we got these errors.

Errors / Screenshots

>.... [14:10:17 ERROR]: [Skript] 2234 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:264)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

>.... [14:10:17 ERROR]: [Skript] 4399 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:264)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

>.... [14:10:17 ERROR]: [Skript] 6 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1602)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

>.... [14:10:32 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:580)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

>.... [14:10:36 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:580)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

>.... [14:12:59 ERROR]: [Skript] 1737 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:264)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

>.... [14:12:59 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:354)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

>.... [14:13:26 ERROR]: [Skript] 21397 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:771)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

Server Information
Server version/platform: PaperSpigot 1.14.4
Skript version:              It happened from Skript 2.4Beta4 to Beta8

**Comment by TPGamesNL** [comment]
This is caused by skript-mirror 1.0.0, update it to 2.0.0

**Comment by Blueyescat** [comment]
Update skript-mirror to 2.0.0-snapshot: https://circleci.com/gh/btk5h/skript-mirror/5#artifacts/containers/0

Also the **!** requirement at the end of field names is removed in that version. So you will need to convert things like `Class.FIELD!` -> `Class.FIELD`,  `blabla.field!` -> `blabla.field` if you have any.
