### ISSUE TITLE
Problem with "On right click"

### ISSUE THREAD

**Issue by falsinq** [SkriptLang/Skript#2567]
I'm trying to make a skript that when you right click on a clock, it does a command.

    give player 1 clock named "&9&l>> &b&lServer Selector &9&l<<"
    if player right click:
    execute player command "/srvs"

I need help for this. Thanks!

**Comment by michaelmuzzarelli** [comment]
I believe the issue lies with the space in the "right click" event.  I might also consider including a check to ensure that the player is holding the correct item, as such:

```
give player 1 clock named "&9&l>> &b&lServer Selector &9&l<<"

on rightclick holding a clock named "&9&l>> &b&lServer Selector &9&l<<":
    execute player command "/srvs"
```

Please let me know if it gives you any more trouble!

**Comment by Wealthyturtle** [comment]
``on right click`` is a valid syntax same as ``on rightclick``. 

As I don't see any problem with the event from this issue, I'll be closing this. In future, if you have any script-related queries, post it on the Skript Discord @ https://discordapp.com/invite/0lx4QhQvwelCZbEX instead.

**Comment by Blueyescat** [comment]
Skript Chat Discord
