### ISSUE TITLE
Slow aliases loading

### ISSUE THREAD

**Issue by leonardo-dgs** [SkriptLang/Skript#2568]
### Description
Skript aliases loading takes almost 10 seconds, I hope it can be implemented a faster way to load.

### Steps to Reproduce
1. Install Skript
2. Start the server

### Errors / Screenshots
`[Skript] Loaded 114225 aliases in 8694ms`

### Server Information
* **Server version/platform:** `Paper version git-Paper-210 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)`
* **Skript version:** `2.4-beta9`

**Comment by bensku** [comment]
That sounds about right on a slow computer; on fast one, it takes a few seconds. The loading takes a while, because there are a lot of aliases (over 100k, as you can see). Further optimizing aliases loading is not easy. Some sort of aliases cache could potentially be implemented.

**Comment by sovdeeth** [comment]
Sidestepped with the minimized aliases available from the skript-aliases repo. Closing as aliases are being phased out.
