### ISSUE TITLE
mobile docs

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2570]
### Description
Docs on mobile are pretty bad. The global nav overlaps and it's hard to click on the section you want to go to. You also need to scroll a lot on mobile and it's generally just a bad user experience.

### Steps to Reproduce
Load the docs on chrome (latest version on android)

### Expected Behavior
<!--- The global nav bar could be a dropdown menu, and the side nav could be like how https://discord.js.org/#/'s side nav on mobile is.

**Comment by FranKusmiruk** [comment]
I do not remember the exact issue, but I am sure this is a duplicate.

**Comment by TPGamesNL** [comment]
I am not able to find any open issues for this, since the only issue about the docs on mobile is this one, which was just closed

**Comment by FranKusmiruk** [comment]
https://github.com/SkriptLang/Skript/issues/1184 this issue, even if not detailed, takes care of that issue as well (responsiveness of the documentation is part of an issue with the current stylesheet, which is hopefully being rewritten anyways).
