### ISSUE TITLE
llama and trader llama; it isnt fixed in beta9

### ISSUE THREAD

**Issue by Padlick01** [SkriptLang/Skript#2573]
### Description
I posted that issue for beta8 already; should be fixed in beta9 but it isnt.

### Steps to Reproduce
Use effect commands:
spawn a llama at player > spawns a trader llama
spawn a trader llama at player > spawns a normal llama

### Expected Behavior
see Steps to Reproduce

### Errors / Screenshots
video: https://youtu.be/w8N8oe9LjYY

### Server Information
* **Server version/platform:**       paper-214 (MC 1.14.4)
* **Skript version:**                2.4beta9

**Comment by ShaneBeee** [comment]
Can confirm!
