### ISSUE TITLE
Types of trees

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#2580]
### Description
Hello! I know someone reported a bug with type trees 2 years ago but it still didn't get added.
Can you add new types of trees:
- Small jungle tree
- Huge jungle tree
- Acacia tree
- Dark oak tree
- Swamp tree

I tried to grow jungle tree but Skript said it can't understand this condition/effect.

**Comment by ShaneBeee** [comment]
Those are all currently in the plugin:
https://github.com/SkriptLang/Skript/blob/a185e752e278a00e51e1b2d212b3f1e95b6ca786/src/main/resources/lang/english.lang#L375

**Comment by 3meraldK** [comment]
> Those are all currently in the plugin:
> ://github.com/SkriptLang/Skript/blob/a185e752e278a00e51e1b2d212b3f1e95b6ca786/src/main/resources/lang/english.lang#L375-L439

Didn't work for me

**Comment by ShaneBeee** [comment]
Theres a small comparison issue with some trees, where you need to type like:
`dark oak tree tree` but other than that, they all work fine
![Screen Shot 2019-10-19 at 11 39 19 AM](https://user-images.githubusercontent.com/20008482/67149845-2487a980-f265-11e9-8f72-a1849aeafc06.png)
