### ISSUE TITLE
All potions are water

### ISSUE THREAD

**Issue by bluelhf** [SkriptLang/Skript#2581]
### Description
All potions default to either water bottles or mundane potions since beta9

### Steps to Reproduce
Use Skript 2.4-beta9
Try giving yourself any potion
See result

### Expected Behavior
You should be given the right potion without any issue.

### Errors / Screenshots
![img](https://i.imgur.com/jkuGm3T.png)

### Server Information
* **Server version/platform:** git-Paper-219 (MC 1.14.4)
* **Skript version:** 2.4-beta9

**Comment by ShaneBeee** [comment]
I can confirm this.
