### ISSUE TITLE
Some nouns don't parse correctly

### ISSUE THREAD

**Issue by NickAcPT** [SkriptLang/Skript#2585]
### Description

Basically, the noun `bottle¦ of enchanting¦s of enchanting` isn't parsing correctly.
When requesting the singular value with `Noun#getSingular`, I'm getting `bottleof enchanting`.

### Steps to Reproduce

```java
new Noun("entities.bottle of enchanting.name").getSingular() //returns bottleof enchanting
```
### Expected Behavior

Expected to receive the correct singular version: 
```java
"bottle of enchanting"
```

### Server Information
* **Server version/platform:** Paper version git-Paper-221 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)      
* **Skript version:** 2.4-beta8

**Comment by bensku** [comment]
Noun doesn't support use of ¦ like that. Where did you get the idea that this would work? Is it documented somewhere, or does Skript do this?

**Comment by NickAcPT** [comment]
This is from the data that's on Skript's english language file.

You can even check it here: https://github.com/SkriptLang/Skript/blob/9d185678d171e88616a39bc781f8ce0550bfb350/src/main/resources/lang/english.lang#L804-L805
