### ISSUE TITLE
set block at location to Flower Pot don't work

### ISSUE THREAD

**Issue by Emrolehero** [SkriptLang/Skript#2594]
I run the latest version of Skript.
I tried this the expression with just Skript without addons and with new versions of Skript, the
expression "set block at event-block to flower pot" don't work but "set block at event-block to stone" works.
So the problem is with flower pots, we can't place flower pots with newest versions, they don't tell me an error, just it not place the flower pot.

**Comment by Wealthyturtle** [comment]
More information please. Exact version of Skript and server jar? (Spigot? Paper? 1.14.4? 1.12.2? 1.9?)

**Comment by ShaneBeee** [comment]
Closing this due to 1 month and no reply. 
If anyone else is having this issue please reply and we can re-open it.
