### ISSUE TITLE
on equip

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#2595]
### Description
add **on equip** event. it's triggered when player equips some armor.

**Comment by Wealthyturtle** [comment]
Unfortunately this it not really feasible - neither Spigot nor Paper has an equip event, you could however listen onto the current click events for it

**Comment by ShaneBeee** [comment]
> Unfortunately this it not really feasible - neither Spigot nor Paper has an equip event, you could however listen onto the current click events for it

Paper has an armor change event (I actually use it in Skript-Paper), we could potentially add something like that to Skript.

**Comment by Wealthyturtle** [comment]
It does? Oops I was searching for "equip" in the paper docs... Yeah in that case it could be added.

**Comment by Wealthyturtle** [comment]
Marked as completed since it's manually merged.
