### ISSUE TITLE
register new shaped recipe

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#2596]
### Description
**register new shaped recipe** is bugged, because it really makes a recipe, but doesn't count amount of items in workbench.

### Steps to Reproduce
**1.** write a script with register new shaped recipe
**2.** include amount of items needed in recipe fe. 64 of cobblestone in each slot
**3.** don't working

### Expected Behavior
it should take every item but it doesn't.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/48335651/67583894-ce2ad700-f74c-11e9-9f07-e087f4bd4aac.png)

### Server Information
* **Server version/platform:** 1.14.4
* **Skript version:** 2.4

### Note
i know i can make a condition 'if player's inventory contains ...' but I want to inform you there's a bug

**Comment by TPGamesNL** [comment]
1) This effect is part of SkQuery, not Skript.
2) Normal crafting, the way it is implemented in Bukkit, doesn't take the amount of a recipe item in account (I think), you will need to make your own crafting system for that.
