### ISSUE TITLE
Returning something else

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#2597]
Using 
`slot 9 of player's current inventory`
returns:
![unknown](https://user-images.githubusercontent.com/48415331/67590243-cd00a680-f75a-11e9-9eab-570b033a4358.png)

Setting a variable to it however returns the item. I'd suggest returning the item without having to set a variable to it.

**Comment by ShaneBeee** [comment]
Can you please fill out the template you deleted, there is more information we need to help triage this issue, including server and Skript version.

**Comment by Runakai1** [comment]
Usually I included such things but the template it deleted doesn't involve such things.

**Comment by Matocolotoe** [comment]
there is already a converter allowing you to use the following
`if slot 9 of player's current inventory is an apple`

**Comment by Wealthyturtle** [comment]
I believe for some reasons it returns the slot object itself, and not the item contained inside the slot. However, as pointed out already, converters exist internally to convert the slot to an item when you store it in a variable, use it in comparisons with other items, etc.
