### ISSUE TITLE
apply effect fix

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#2598]
### Description
fix an apply effect because it adds additional time for effect but it should set time

**Comment by bluelhf** [comment]
Do you mean that apply effect should be instant? AFAIK that's a spigot limitation, will look into it.

**Comment by TPGamesNL** [comment]
> Do you mean that apply effect should be instant? AFAIK that's a spigot limitation, will look into it.
> 
> E: Looked into it. Doesn't look like you can make it instant.

I think they mean that currently, when using the apply effect potion, it adds your chosen timespan to the duration of the effect (e.g. I already have 2 minutes of resistance, I use Skript to apply 1 minute, then I have 3 minutes of resistance). They probably don't want it to be added to the duration.

**Comment by bluelhf** [comment]
@TPGamesNL There's a method with a boolean parameter to either add or replace potion effects, could probably add a `replacing existing effects` part to the apply effect and utilise that.

**Comment by TPGamesNL** [comment]
> @TPGamesNL Isn't there a method with a boolean parameter to either add or replace potion effects, could we not add a `replacing existing effects` part to the apply effect and utilise that.
> 
> E: [This one](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#addPotionEffect-org.bukkit.potion.PotionEffect-boolean-)

Yes that would probably be a good idea.
I just looked at the code for the effect, and apparently Skript does the adding of the duration manually: [L35](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffPotion.java#L135). But then they still make use of the `force` boolean...

**Comment by ShaneBeee** [comment]
Fixed in 2.5-alpha2
