### ISSUE TITLE
floats in functions

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#2599]
### Description
floats in functions seems to be bugged or I was typing those floats wrong.
```
Launch(player, 0.5)

function Launch(p: player, n: integer):
# code
```

n: floats didn't work

**Comment by Matocolotoe** [comment]
`integer` in Skript represents a long (therefore a mathematical integer, 0.5 isn't one)

**Comment by 3meraldK** [comment]
> integer in Skript represents a long (therefore a mathematical integer, 0.5 isn't one)

so what can I do then?

**Comment by Teetady** [comment]
use "number"?

**Comment by Wealthyturtle** [comment]
As Matocolotoe said, use number as the equivalent of float, and not integer.
