### ISSUE TITLE
Size of {::*} working incorrect

### ISSUE THREAD

**Issue by legofreak1999** [SkriptLang/Skript#2600]
# Description
Wenn a list has a list inside a list and the values are deleted. the "size of" expression still thinks there values inside of the variable

### Steps to Reproduce
```
command /variablesizebug:
	trigger:
		set {test::test} to "test"
		set {test::test::test} to "test"
		set {_s} to size of {test::*}
		send "%{_s}%"
		delete {test::test::test}
		delete {test::test}
		set {_s} to size of {test::*}
		send "%{_s}%"
		delete {test::*}
		set {_s} to size of {test::*}
		send "%{_s}%"
```

### Expected Behavior
send values should be 1 0 0 instead of 1 1 0

### Server Information
* **Server version/platform:**   Paper version git-Paper-642 (MC: 1.13.2)
* **Skript version:**                skript version 2.3.7 & skript version 2.4-beta9

**Comment by APickledWalrus** [comment]
What happens if you delete the variable you’re sending each time before you send it again? Are the results the same? Also reports are only accepted from the latest skript version, so if possible please test it there :)

**Comment by legofreak1999** [comment]
I also tested it with 3 commands like this:
same results

```
command /variablesizebug:
	trigger:
		set {test::test} to "test"
		set {test::test::test} to "test"
		set {_s} to size of {test::*}
		send "%{_s}%"

command /variablesizebug2:
	trigger:
		delete {test::test::test}
		delete {test::test}
		set {_s} to size of {test::*}
		send "%{_s}%"

command /variablesizebug3:
	trigger:
		delete {test::*}
		set {_s} to size of {test::*}
		send "%{_s}%"
```

Gonna temperarly update skript bc i dont like to use the beta's. will give a update to this issue wenn tested.

**Comment by legofreak1999** [comment]
> 
> 
> What happens if you delete the variable you’re sending each time before you send it again? Are the results the same? Also reports are only accepted from the latest skript version, so if possible please test it there :)

Just tested on 
skript version 2.4-beta9
Paper version git-Paper-642 (MC: 1.13.2)
same results

**Comment by legofreak1999** [comment]
Temporarly workaround requires skript mirror

```
expression proper size of %objects%:
	get:
		set {_list::*} to expression-1
		set {_i} to size of {_list::*}
		return {_i}
```
Because the object is inside the new variable {list::*} size will work properly
