### ISSUE TITLE
Suggestion: Alter Numbers expression

### ISSUE THREAD

**Issue by bluelhf** [SkriptLang/Skript#2601]
### Description
Currently, Numbers is kind of dumb. Here's part of its description:
> Use 'numbers' if your start is not an integer and you want to keep the fractional part of the start number constant, or use 'integers' if you only want to loop integers.

This means that
`all numbers from 1.1 to 5` -> `1.1, 2.1, 3.1, 4.1`

**I don't see an use for this. This is why I propose a different approach:**

If 'integers' is used, Numbers should work as it is now, that's all good.
If 'numbers' is used, it should get the decimal precision of the starting number and use that as a step.

For example,
`all numbers from 1 to 5` -> `1, 2, 3, 4, 5`
`all numbers from 1.1 to 2` -> `1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0`
`all numbers from 2.95 to 3` -> `2.95, 2.96, 2.97, 2.98, 2.99, 3`
`all integers from 1 to 6` -> `1, 2, 3, 4, 5, 6`
`all integers from 1.2 to 6` -> `2, 3, 4, 5, 6`

**Comment by Wealthyturtle** [comment]
I agree, those changes sound nice.

**Comment by bluelhf** [comment]
Implemented
