### ISSUE TITLE
"Play effect" syntax's range part doesn't work

### ISSUE THREAD

**Issue by LenjoyOfficial** [SkriptLang/Skript#2603]
### Description
This is the syntax of "play effect":
```(play\|show) %visual effects% (on\|%directions%) %entities/locations% [(to %players%\|in (radius\|range) of %number%)](play\|show) %number% %visual effects% (on\|%directions%) %locations% [(to %players%\|in (radius\|range) of %number%)]```
I used the "in range of %number%" part with different values, but I couldn't spot any difference between the displays. The screenshots describe this better.

### Steps to Reproduce
Execute this: `play 10 heart at player's location in range of 0.5`, and watch the output.
Then execute this: `play 10 heart at player's location in range of 100`, and watch the output.
You can see that the actual range hasn't changed at all.

### Expected Behavior
The first effect would display 10 heart particles in a 0.5 block radius, and the second in a 100 block radius.

### Errors / Screenshots
![2019-10-29_09 08 38](https://user-images.githubusercontent.com/47115878/67749282-1ee04f80-fa2d-11e9-9a87-403a457abea5.png)
![2019-10-29_08 59 55](https://user-images.githubusercontent.com/47115878/67749308-2dc70200-fa2d-11e9-8d54-55871481a36e.png)

There aren't any console errors.

### Server Information
* **Server version/platform:** CraftBukkit version git-Spigot-56f8471-7554e08 (MC: 1.14.4)
* **Skript version:** 2.4-beta9

### Additional Context
Please fix it :D

**Comment by ShaneBeee** [comment]
I believe range is referring to "players in range", meaning it will player for all players within the specified range

**Comment by LenjoyOfficial** [comment]
really? ok i will create a suggestion for what i meant

**Comment by LenjoyOfficial** [comment]
is there any way to specify my version of range?
