### ISSUE TITLE
"last spawned entity" doesn't work properly

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2607]
### Description

When you use "last spawned entity" after a shoot-effect, it doesn't work?

### Steps to Reproduce

**1. Put this scripts in a file:**
```
command /test:
	trigger:
		shoot a fireball from the player with speed 3
		if last spawned entity is a fireball:
			broadcast "yes"
		else:
			broadcast "%last spawned entity%"
		stop
```
**2. Load the script.**
**3. Execute the command /test.**
**4. You shall see the message "none" in the chat.**

### Expected Behavior

I expected to see "yes" in the chat :(

### Errors / Screenshots

/

### Server Information
* **Server version/platform:**       Paper 1.14.4
* **Skript version:**                Skript v2.4-beta9

### Additional Context

/

**Comment by CHarcoalToast** [comment]
Skript is probably not recognising fireball as an entity. Try to get the fireball as a projectile and see if it works

**Comment by Wealthyturtle** [comment]
Did some investigation, and the issue is because the comparison actually doesn't work, see issue #2286
