### ISSUE TITLE
WTF error with dragon egg and spruce boat IDs

### ISSUE THREAD

**Issue by Leonardo-Fiori** [SkriptLang/Skript#2609]
### Description
https://www.youtube.com/watch?v=SUmSAwWhs8g&feature=youtu.be

I have a skript that logs interaction with dragon eggs, and does some cool stuff with them.

`on rightclick on a dragon egg:
	message "&6Dragon egg interaction happened" to console
	set {eggClicked::%now%} to "%player% clicked egg at: %event-location%"
	play sound "entity.enderman.teleport" with volume 1 and pitch 1 at location at targeted block
	play sound "entity.evoker.cast_spell" with volume 1 and pitch 0.8 at location at targeted block
	show portal at location at event-block
	show portal at location at event-block
	show mob spawner flames at event-block`

This is the part of the code involved in it.

Look at the video and see what is happening. Spruce boats act as dragon eggs!

They actually trigger that part of the code... and all the other ones that use "dragon egg" block or item. Why?

Full code:
https://pastebin.com/fEjxMf1h

### Server Information
* **Server version/platform:** git-Paper-223 (MC: 1.14.4)
* **Skript version:** 2.4 beta 9 (latest here on github)

**Comment by Wealthyturtle** [comment]
Can confirm this odd issue using
```
on rightclick on a dragon egg:
    broadcast "Detected %event-block%"
```
That will produce an output of ``Detected <none>`` but nonetheless still oddly triggers for spruce boats. I can't seem to get this bug triggering with other boat variants or with other blocks, needs more investigation.
