### ISSUE TITLE
Exception when reloading script on scripts folder

### ISSUE THREAD

**Issue by NickAcPT** [SkriptLang/Skript#2612]
### Description

Reloading a script file on the scripts folder causes Skript to throw an exception.

### Steps to Reproduce

Have a file on the scripts folder, not inside any sub.folders, and try to reload it.

### Expected Behavior

Normal file load

### Errors / Screenshots

```
#!#!
#!#! [Skript] Severe Error:
#!#! Exception occurred in Skript's main command
#!#! Used command: /sk reload basic
#!#!
#!#! Something went horribly wrong with Skript.
#!#! This issue is NOT your fault! You probably can't fix it yourself, either.
#!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
#!#! This ensures that your issue is noticed and will be fixed as soon as possible.
#!#!
#!#! Stack trace:
#!#! java.lang.IllegalArgumentException: 'other' is different type of Path
#!#!     at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:388)
#!#!     at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:44)
#!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:952)
#!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:190)
#!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
#!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
#!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
#!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701)
#!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456)
#!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
#!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
#!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
#!#!     at java.lang.Thread.run(Thread.java:748)
#!#!
#!#! Version Information:
#!#!   Skript: 2.4-beta9
#!#!     Flavor: selfbuilt-unknown
#!#!     Date: unknown
#!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
#!#!   Minecraft: 1.14.4
#!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
#!#!   OS: Windows 10 amd64 10.0
#!#!
#!#! Server platform: Paper
#!#!
#!#! Current node: null
#!#! Current item: null
#!#!
#!#! Thread: Server thread
#!#!
#!#! Language: english
#!#! Link parse mode: DISABLED
#!#!
#!#! End of Error.
#!#!
```

### Server Information
* **Server version/platform:** Paper 1.14.4      
* **Skript version:** 2.4-beta9 (Up to commit 7ddb4cf74696b8b17b73a30c388b2491c3ff5b8f)

**Comment by ShaneBeee** [comment]
You're building from Master branch, master branch is not a released version. 

I recommend either downloading one of the actual released builds, or building from the 2.4 branch

**Comment by NickAcPT** [comment]
This is not used on a production environment. **I know this is not a released version.**

Building from master allows me to actually find bugs. I haven't seen anyone mention this bug recently. Imagine if no one tested it to the point of this problem being present over on a release..

Using this code instead of the one in https://github.com/SkriptLang/Skript/blob/b95c298d9069a531091bf7140bbd05bce195536c/src/main/java/ch/njol/skript/ScriptLoader.java#L951-L952 seems to alleviate the problem temporarily.
```java
		String name = Skript.getInstance().getDataFolder().toPath().toAbsolutePath()
			.resolve(Skript.SCRIPTSFOLDER).relativize(script.toPath().toAbsolutePath()).toString();
```

**Comment by bluelhf** [comment]
Can reproduce with Paper-219, custom-built Skript (with [this PR's changes](https://github.com/SkriptLang/Skript/pull/2602)).
Suggest making a pull request that changes this? @NickAcPT

**Comment by NickAcPT** [comment]
It appears to me that b95c298d9069a531091bf7140bbd05bce195536c is the commit at fault here.

**Comment by bensku** [comment]
Reducing priority, as this does not affect many people right now. Need to fix this before 2.5, though.

**Comment by NickAcPT** [comment]
One of my suggestions for the future, is to actually add loading/unloading to the tests on Skript. It wouldn't hurt to have it and it might help to catch breaking problems to critical components like this in the future.

**Comment by Wealthyturtle** [comment]
It would be more tricky to add tests for that, and this sort of issue doesn't really occur very often.

**Comment by NickAcPT** [comment]
Well, I feel like loading/unloading are great smoke tests for Skript. Even if it doesn't happen often, it would be easier to catch them in the future even before breaking code is committed.

**Comment by bensku** [comment]
@NickAcPT Test script system assumes loading works, but adding more tests for script loading is possible.

This issue should be fixed now, and has not appeared in any release, so closing.
