### ISSUE TITLE
Mass spam and errors with region exit event (worldguard).

### ISSUE THREAD

**Issue by APickledWalrus** [SkriptLang/Skript#2613]
### Description
I have a piece of code, that when a player exits a region, it teleports them to a different location. For some reason, this calls the event again many times (enough that my chat was essentially cleared by it) and spams the console repeatedly. I have attached the code and error below.

### Steps to Reproduce
The location I am teleporting the player to is outside of the region.
```
options:
    world: world
on region exit:
    send "yo"
    teleport player to location at x-coordinate of player, 100.0, z-coordinate of player of the world world("{@world}")
```

### Expected Behavior
The player should be teleported out of the region with no errors.

### Errors / Screenshots
I know it is long & repetitive, but I was only able to ctrl+a to get it, as the console was sending to many messages at once for me to easily select a section.
https://gist.github.com/APickledWalrus/0ffc015981e5e62ee7f35189a3ff156b

### Server Information
* **Server version/platform:**       git-Paper-225 MC 1.14.4 (latest paper build)
* **Skript version:**                2.4-beta9
* **WorldGuard version:**       7.0.0;02b731f

**Comment by bensku** [comment]
It looks like Spigot fires the move event again when you teleport the player. This could happen because the player has not yet exited the region until the event has passed. I'm not sure if we can do anything about this on Skript side.

**Comment by APickledWalrus** [comment]
I added in a 10 tick delay which was long enough to fix this issue, and solve the problem in my case. We can probably close this unless you'd like to keep it open.
