### ISSUE TITLE
Suggestion: Add tab support

### ISSUE THREAD

**Issue by awaffle1** [SkriptLang/Skript#2614]
### Description

Just add tab support.
Whenever I'm making my skripts, in say, Notepad++, when I start a new line it automatically adds tabs.
Now, if I forget to remove those tabs and replace them, when I move my skript over to the actual server, Skript starts throwing out errors.
It's really annoying and I have to go through all the errors to find out where to replace tabs with spaces.

**Comment by Wealthyturtle** [comment]
Skript already has tab support in scripts... you just have to be consistent - there can’t be a mixing of spaces or tabs, only fully spaces or fully tabs for indentation.

**Comment by awaffle1** [comment]
Ah. Okay. That makes sense
