### ISSUE TITLE
ExprPlayerlistHeaderFooter improvements

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2627]
### Description
able to set multiple lines in tab header and footer, example:
```
		set loop-player's tab list header to "hello", "cool dude" and "yo"
		set loop-player's tab list footer to "yes" and "%loop-player%"
```
currently this returns an error saying it can only be set to one text

**Comment by ShaneBeee** [comment]
I agree that should definitely be done.

**Comment by APickledWalrus** [comment]
Adding could be useful as well.

add “Hello %player%” to the player’s tab list footer

Maybe a way to edit a specific line from the tab header/footer?

set line 2 of player’s tab list header to “Hello!”
delete line 2 of player’s tab list footer

**Comment by MrScopes** [comment]
> Adding could be useful as well.
> 
> add “Hello %player%” to the player’s tab list footer
> 
> Maybe a way to edit a specific line from the tab header/footer?
> 
> set line 2 of player’s tab list header to “Hello!”
> delete line 2 of player’s tab list footer

line x of tab list header would definitely be a nice expression

**Comment by JRoy** [comment]
Whereas lores actually are stored as multiple strings, the tablist header and footer use one string and are separated by newlines. My pull request, #2505, adds a newline literal which will allow for multiple lines on the tablist.

**Comment by ShaneBeee** [comment]
The line separator will definitely be helpful.
I think we can easily add something for setting multiple lines using a list, and I think it would be helpful, but as JRoy pointed out, the header/footers are actually a single line, so replacing/setting/adding each line separately from the effect might get a little tricky, and in my opinion isn't something we should be handling.

**Comment by Blueyescat** [comment]
Yeah, this shouldn't work with text lists but line breaks. (no need to keep this issue open)

**Comment by MrScopes** [comment]
i guess when newline will be out this will be useless
