### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by SmellyEggplant** [SkriptLang/Skript#2629]
### Description
I'm fairly new to skript, and I've created a command that tells the player how much more of an item they need out of 64

### Steps to Reproduce
Once the command is run, it'll say "An internal error occurred while attempting to perform this command." to my player, here's the code:

options:
    amount: 64

command /antimatter:
    trigger:
        set {_am} to amount of sweet berries named "    &4&ki &cAnti-matter berries &4&ki" with lore "&3Trade for anti-matter gens" and "       &9&l&kii &6/antimatter &9&l&kii" in player's inventory
        if player has 64 sweet berries named "    &4&ki &cAnti-matter berries &4&ki" with lore "&3Trade for anti-matter gens" and "       &9&l&kii &6/antimatter &9&l&kii":
            remove 64 of sweet berries named "    &4&ki &cAnti-matter berries &4&ki" with lore "&3Trade for anti-matter gens" and "       &9&l&kii &6/antimatter &9&l&kii" from player
            give player 1 light gray glazed terracotta named "&b&ki &f&lAnti-Matter Generator &b&ki" with lore "&4Resets every 10 seconds!"
            send "&b&lOculis &8&l» &f&lAnti-Matter &3generator received!"
        else:
            set {_needed} to {@amount} - {_am}
            send "&b&lOculis &8&l» &3You need %{_needed}% more"

### Expected Behavior
It should send a message to the player that reads "&b&lOculis &8&l» &3You need (64 - however many more you need) more" but, as stated before it says An internal error occurred while attempting to perform this command." instead. 

### Errors / Screenshots
Here's the gist link to the error:
https://gist.github.com/SmellyEggplant/e4382b0a8b3894f3c3138dbc7713570c

### Server Information
* **Server version/platform:**       Minehut
* **Skript version:**                2.4-beta5-MH (custom version)

Thanks in advance! :)

**Comment by SmellyEggplant** [comment]
> ### Description
> I'm fairly new to skript, and I've created a command that tells the player how much more of an item they need out of 64
> 
> ### Steps to Reproduce
> Once the command is run, it'll say "An internal error occurred while attempting to perform this command." to my player, here's the code:
> 
> command /antimatter:
> trigger:
> set {_am} to amount of sweet berries named " &4&ki &cAnti-matter berries &4&ki" with lore "&3Trade for anti-matter gens" and " &9&l&kii &6/antimatter &9&l&kii" in player's inventory
> if player has 64 sweet berries named " &4&ki &cAnti-matter berries &4&ki" with lore "&3Trade for anti-matter gens" and " &9&l&kii &6/antimatter &9&l&kii":
> remove 64 of sweet berries named " &4&ki &cAnti-matter berries &4&ki" with lore "&3Trade for anti-matter gens" and " &9&l&kii &6/antimatter &9&l&kii" from player
> give player 1 light gray glazed terracotta named "&b&ki &f&lAnti-Matter Generator &b&ki" with lore "&4Resets every 10 seconds!"
> send "&b&lOculis &8&l» &f&lAnti-Matter &3generator received!"
> else:
> set {_needed} to {@amount} - {_am}
> send "&b&lOculis &8&l» &3You need %{_needed}% more"
> 
> ### Expected Behavior
> It should send a message to the player that reads "&b&lOculis &8&l» &3You need (64 - however many more you need) more" but, as stated before it says An internal error occurred while attempting to perform this command." instead.
> 
> ### Errors / Screenshots
> Here's the gist link to the error:
> https://gist.github.com/SmellyEggplant/e4382b0a8b3894f3c3138dbc7713570c
> 
> ### Server Information
> * **Server version/platform:**       Minehut
> * **Skript version:**                2.4-beta5-MH (custom version)
> 
> Thanks in advance! :)

**Comment by Wealthyturtle** [comment]
See if this issue can be replicated on 2.4-beta9 first.

**Comment by bensku** [comment]
Unfortunately, we do not support custom versions here.

**Comment by bensku** [comment]
Oops, looks like we were both replying at same time. I'll let @Wealthyturtle handle this

**Comment by bluelhf** [comment]
We'd appreciate if you could replicate this on a localhost server running 2.4-beta9 and the latest release of Paper. Please also provide the full code (including the options, we don't know what {@amount} is.)

**Comment by ShaneBeee** [comment]
I can confirm this behaviour, it appears its something to do with lore trying to parse at the time time as checking, I wrote some simple test code:
```vb
command /antimatter:
	trigger:
		# throws error
		set {_test1} to amount of diamonds named "Blah" with lore "blah" and "blah" in player's inventory

		# works fine
		set {_test2} to amount of diamonds named "Blah" in player's inventory

		# works fine
		set {_i} to diamonds named "Blah" with lore "blah" and "blah"
		set {_test3} to amount of {_i} in player's inventory
```

1) Checking for a named item with lore throws an error
2) Checking for a named item works fine
3) Setting the item (With name/lore) to a var then checking if the inventory contains the var works fine.

**Comment by SmellyEggplant** [comment]
> See if this issue can be replicated on 2.4-beta9 first.



> We'd appreciate if you could replicate this on a localhost server running 2.4-beta9 and the latest release of Paper. Please also provide the full code (including the options, we don't know what {@amount} is.)

Sorry for late reply, but I've decided to ditch this and use another way to do it. If I have any other problems I'll make sure to do this too



> I can confirm this behaviour, it appears its something to do with lore trying to parse at the same time as checking if the inventory contains said item, I wrote some simple test code:
> 
> ```vbnet
> command /antimatter:
>     trigger:
>         # throws error
>         set {_test1} to amount of diamonds named "Blah" with lore "blah" and "blah" in player's inventory
> 
>         # works fine
>         set {_test2} to amount of diamonds named "Blah" in player's inventory
> 
>         # works fine
>         set {_i} to diamonds named "Blah" with lore "blah" and "blah"
>         set {_test3} to amount of {_i} in player's inventory
> ```
> 
> 1. Checking for a named item with lore throws an error
> 2. Checking for a named item works fine
> 3. Setting the item (With name/lore) to a var then checking if the inventory contains the var works fine.
> 
> _**Note:**_
> Tested on Skript 2.4-beta10
> 
> **Edit:**
> Further testing:
> 
> ```
> set {_test1} to amount of (diamonds named "Blah" with lore "blah" and "blah") in player's inventory
> ```
> 
> throwing the item with name/more into parenthesis stops the error.

Thanks for the help. If I'm using anything like this, I'll be sure to use this method
:)
