### ISSUE TITLE
My code isn't working

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#2630]
### Question
As the title says - my code isn't working
`on inventory click:
	if inventory name of player's current inventory is "Recipe":
		cancel event`
No errors, but If i "steal" some item in this inventory it won't cancel the event.
I tried to ask many players, they answered me but anyway it didn't work, help me

**Comment by bluelhf** [comment]
@3meraldK This isn't the place to ask questions regarding scripts written in Skript - This issue tracker is for actual issues with the plugin itself.

**Comment by 3meraldK** [comment]
> @3meraldK This isn't the place to ask questions regarding scripts written in Skript - This issue tracker is for actual issues with the plugin itself.

so where can I ask about that problems, and if you can please answer (and sorry if I put this issue into wrong place)

**Comment by ShaneBeee** [comment]
Hey, on the main page of this repo, at the bottom you will find some links for discords and forums.
https://github.com/SkriptLang/Skript#relevant-links

This issue tracker is for issues with the plugin itself.

Also note in 1.14+ inventories no longer have titles, the dev team is aware of this issue and will hopefully be able to get a fix out in the future.
