### ISSUE TITLE
Function parameter (Function)

### ISSUE THREAD

**Issue by LeoStoch** [SkriptLang/Skript#2631]
My suggestion is for functions in general. It would be nice if you are able to five a function another function as parameter instead of only text/numbers... that can be then executed within the function.

**Comment by Wealthyturtle** [comment]
What do you mean? Do you want something like
```
function f(func: function):
    func()
```

**Comment by LeoStoch** [comment]
Yes, exactly.

**Comment by Wealthyturtle** [comment]
Duplicate of #1265
