### ISSUE TITLE
loop-player

### ISSUE THREAD

**Issue by AggerTV** [SkriptLang/Skript#2635]
### Description

https://www.youtube.com/watch?v=rO1Rg51ppxA&feature=youtu.be

All of the other required information can be found in the video

pastebin link of the script (it gives no errors upon reloading)
https://pastebin.com/GDLLK401

### Server Information
* **Server version/platform:**       
* **Skript version:**

**Comment by ShaneBeee** [comment]
This is not an issue with Skript, this is a common issue with skRayFall scoreboards.
You need to set a variable to the loop player, and use that within the variables of your code for the scoreboard.

Closing this as its not a Skript issue.

If you require further assistance, please use the forums and/or one of the discords which are there to provide support for writing scripts.
You can find these links here:
https://github.com/SkriptLang/Skript#relevant-links
