### ISSUE TITLE
Is there a parsing api?

### ISSUE THREAD

**Issue by DeepRobin** [SkriptLang/Skript#2636]
### Question

Is there a api for parsing skript?
I want to check a skript if it is a force op skript, because i'll work on a security plugin.

**Comment by Wealthyturtle** [comment]
You can try and check out https://github.com/SkriptLang/skript-parser, although I'm not too sure if it's useful in your specific case. In future, you can direct questions like this to the Skript Chat Discord, link is https://discordapp.com/invite/0lx4QhQvwelCZbEX

**Comment by bensku** [comment]
That is probably not useful, unless you're writing a clone of Skript. Checking if scripts contain forbidden syntaxes is something I would not attempt to do now, because Skript doesn't really provide good support for it at the moment.
