### ISSUE TITLE
Comparison Issues

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#2637]
### Description
There are some fairly big comparison issues in Skript. Looking thru the latest issues there are a few issues regarding this already, I just wanted to condense the issues into one big issue to help visualize how big this bug actually is. 

Some notable issues with comparison are with Spawn Reasons as seen in #2186 
It appears the comparison is attempting to compare a type (a spawn reason) but it won't allow this comparison.

Another notable instance is entity comparisons. One example I have encountered:
```vb
if event-entity is a tropical fish
```
no matter what, this returns false. In this case Skript is seeing `tropical fish` as an item, and this comparison will always return false.

In some cases you can do things like:
```vb
if "%spawn reason%" = "egg":
```
and it will work. This clearly is not an ideal way to compare things.
In certain instances this will not work. ex:
```vb
if "%event-entity%" = "tropical fish"
```
this won't work, as this will return the type of tropical fish, ie: `Betty`

Another notable comparison issue is damage causes, as seen in #2184) When comparing some damage causes, Skript seems to think the second object is an item, enchantment, potion, etc, as seen in this image from jaylawl:
![](https://i.snipboard.io/O6Cr8n.jpg)

It seems comparing 2 objects, the 2nd object is not parsing correctly, in many cases it parses as an item type before attempting to match the 1st object. 

I've been digging around in the comparison classes trying to figure out a way to fix this, but it all seems very complicated. I think the comparison classes need to somehow attempt to match the type of the 2nd object to the type of the 1st object, before attempting to compare across other types.

### Steps to Reproduce
some example codes that will not parse correctly:
```vb
on spawn:
    if event-entity is a tropical fish: #always returns null
```
```vb
on spawn:
    spawn reason = natural
    spawn reason = jockey
```
these will return this error: (as provided by jaylawl)
![](https://i.snipboard.io/jEPAMp.jpg)

### Expected Behavior
I would expect comparisons to correctly compare the 2 objects, in a fashion where the types of the 2 of objects are the same. 

### Server Information
* **Server version/platform:**  I have tested on Paper 1.14.4 (224)
* **Skript version:** 2.4-beta9

### Additional Context
See previous issues for additional context. (I closed these in favour of this issue)
#2286 
#2186 
#2213 
#2184 
#1832

**Comment by bensku** [comment]
All related issues should be fixed in 2.5.
