### ISSUE TITLE
Chunk Unloading Can't Be Cancelled

### ISSUE THREAD

**Issue by Parrothead** [SkriptLang/Skript#2638]
### Description
Cancelling the unload chunk event no longer works ("cannot be cancelled"). All of the docs websites I've visited, SkUnity, Skript Hub, etc, all have "....Cancel the event to force the server to keep the chunk loaded..." in the event description. It also worked on previous (1.12) builds of Skript.

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/6238537/68542149-4ca38d80-0377-11ea-82b3-e360f4a5dd2d.png)

### Errors / Screenshots
![unloadchunk](https://user-images.githubusercontent.com/6238537/68542117-d6069000-0376-11ea-8a0b-3041f6a2b5e4.png)

### Server Information
* **Server version/platform:**      1.14.4
* **Skript version:**                2.4-beta9
### Additional Context
Did not see any comment anywhere referencing intended removal.

**Comment by Wealthyturtle** [comment]
Skript is merely following the Spigot code, and in this case it looks like around 1.12 something the ChunkUnloadEvent stopped being a cancellable event.

Spigot 1.9: https://jd.andross.fr/spigot-1.9-R0.1-SNAPSHOT/javadoc/
Spigot 1.14.4: https://jd.andross.fr/spigot-1.14.4-R0.1-SNAPSHOT/javadoc/org/bukkit/event/world/ChunkUnloadEvent.html (no longer implements Cancellable)
