### ISSUE TITLE
All scripts expression

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#2640]
an expression that returns all scripts with an option to return their file location or maybe a whole new expression for a scripts file location. 

Example syntaxes: 
[all] scripts [including sub[( |-)]dir[ectorie]s]

Or

[all] scripts
%strings% file location

This could be used for a variety of different scripts

**Comment by ShaneBeee** [comment]
I'm just curious, could you please provide a use case for this?

I'm just wondering how/when something like this would be used.

**Comment by legofreak1999** [comment]
Well i run a update detector would be usefull for that.

But if u wanna do this skriptmirror:

```
import:
	java.io.File

set {_dir} to new File("plugins/Skript/scripts").listFiles()
set {_dir::*} to split "%{_dir}%" at ", "
```

![afbeelding](https://user-images.githubusercontent.com/6773171/68631698-03287f00-04ec-11ea-88e5-a02f25d6c0a8.png)

**Comment by HYPExMon5ter** [comment]
Updaters, as stated above, tab completers, auto reloaders, etc. and yes, I know you can do it with skript-mirror, and your code above doesn’t work with scripts in sub directories @legofreak1999

**Comment by APickledWalrus** [comment]
could also be useful to get the loaded and unloaded scripts

**Comment by HYPExMon5ter** [comment]
^ true

**Comment by legofreak1999** [comment]
@HYPExMon5ter why wouldnt it be u can check for directorys inside the directory and loop trough those?

**Comment by legofreak1999** [comment]
Oh wait but indeed u cant check if those are valid files seen by skript

**Comment by HYPExMon5ter** [comment]
Yes I know, but I was saying the code you provided doesn’t do that.
