### ISSUE TITLE
Inconsistent villager naming

### ISSUE THREAD

**Issue by bensku** [SkriptLang/Skript#2641]
### Description
On MC 1.9-1.13, Skript has 'priest' villager, while on 1.14 it is 'cleric. This hurts compatibility of scripts.

### Steps to Reproduce
Change regression test for #2625 to run on all supported versions.

### Expected Behavior
Same name for same villager type is used on all versions. Ideally, both names would work on all versions.

### Errors / Screenshots
Parsing fails with wrong name.

### Server Information
* **Server version/platform:** 1.14
* **Skript version:** 2.4, master (2.5)

### Additional Context
@ShaneBeee might know why this is the case.

**Comment by ShaneBeee** [comment]
I'll take a look at this. It should be a relatively simple fix. (Let's hope)
