### ISSUE TITLE
Add event-key which returns the pressed hotbar key on inventory click event

### ISSUE THREAD

**Issue by nopeless** [SkriptLang/Skript#2643]
The current on inventory click event doesn't have any values for the key in which the user pressed.
I think it would be a good enhancement to put some sort of event-key.
I'm currently using skript-mirror getHotbarButton() for this value.

**Comment by NickAcPT** [comment]
This was implemented on PR #2648. Please close this.

**Comment by TheBentoBox** [comment]
No, we don't close issues until a release has been published with the resolution applied. I'll mark as completed but it will remain open until that time.
