### ISSUE TITLE
Picking up lava or water with a bucket sends a huge error to console and acts as an "on break" event.

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2645]
Description
This error occurs when a script is listening for an "on break" event and a player picks up water or lava.

**Steps to Reproduce**
Skript Version: 2.4-beta9
1. Set an on break event to "send "hello" to player
2. Pick up water or lava with a bucket
3. It will send "hello" to you even though water can't be broken.

Expected Behavior
Nothing should be sent to the player, however since Skript thinks that picking up lava of water is a "block break" event, it does.

Errors / Screenshots
![image](https://user-images.githubusercontent.com/49515406/68616828-b4e6a080-052a-11ea-96ed-c226e3e86275.png)
![image](https://user-images.githubusercontent.com/49515406/68616961-00994a00-052b-11ea-999d-b0407159cad7.png)

![image](https://user-images.githubusercontent.com/49515406/68616923-e6f80280-052a-11ea-98cc-9caca2053bda.png)

Console Error: https://gist.github.com/Jayderp/4ec7cd917a89aa567371498ec5c09067

Server Information
* **Server version/platform:** Spigot 1.14.4 (BuildTools Build #103 --rev latest)
* **Skript version:** 2.4-beta9

Additional Context
`on break:
	if event-block is not dirt, lava, or water:
		send "&c&lYOU ARE BLIND! &6Unfortunately, this is not dirt." to player
		cancel the drops
		drop dirt at location of event-block
	else:
		set {_c} to random integer between 1 and 3
		add all items to {_i::*}
		set {_item} to {_c} of random element out of {_i::*}
		wait 1 tick
		if {_item} contains "floor", "ender portal block", "attached", "powered", "air", "command", "structure block", "structure void", or "barrier":
			send "&c&lYOU GOT UNLUCKY! &6Unfortunately, this block would've dropped an illegal item. Sorry." to player
			stop
		else:
			wait 1 tick 
			send "&a&lITEM FOUND! &a%{_item}%"
			drop {_item} at location of event-block`

**Comment by Jayderp** [comment]
It seems that github has completely messed up my skript code, but trust me, every thing is indented correctly and there are no errors on reload.

>sk reload test
[09:11:50] [Server thread/INFO]: [Skript] Reloading test.sk...
[09:11:51] [Server thread/INFO]: [Skript] Successfully reloaded test.sk.

**Comment by ShaneBeee** [comment]
Can confirm.

**Comment by Jayderp** [comment]
Breaking a painting:
java.lang.ClassCastException: org.bukkit.event.hanging.HangingBreakByEntityEvent cannot be cast to org.bukkit.event.block.BlockBreakEvent

**Comment by FranKusmiruk** [comment]
Sorry, accidentally reopened it.

**Comment by Jayderp** [comment]
Fixed in 2.4.
