### ISSUE TITLE
Parsing issue with the split expression

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2647]
### Description
There is a parsing issue with the split expression, that seems to only occur when a string literal is used in place of a variable.

### Steps to Reproduce
```
function a():
    set {_s} to "" #Fix parse problem
    set {_r::*} to "test" split at {_s}
```
The above code will not throw any errors during parsing, while
```
function a():
    set {_r::*} to "test" split at ""
```
will cause a parse error.

### Expected Behavior

For no parse error to be thrown

### Errors / Screenshots

`` {_r::*} can't be set to '"test" split at ""' because the latter is not an object``

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta10

### Additional Context

N/A

**Comment by Matocolotoe** [comment]
Can confirm

**Comment by FranKusmiruk** [comment]
Duplicate of #709

**Comment by Wealthyturtle** [comment]
Oops my bad
