### ISSUE TITLE
bug with 2.4Beta10, skript-mirror and kosmos

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#2650]
### Description
The version 2.4Beta10 stop the code at `Bukkit.clearRecipes()` BUT ONLY IF you have the addon Kosmos , the code work with 2.4Beta9

### Steps to Reproduce
```
import:
    org.bukkit.Bukkit

command /test:
    trigger:
        Bukkit.clearRecipes()
        broadcast "1" #Not send with 2.4Beta10
```
### Errors / Screenshots
They are no error, the broadcast is not sent

### Server Information
paper/spigot 1.14.4
Skript2.4Beta10
skript-mirror2.0.0SNAPSHOT
Kosmos-1.0-BETA.4

### Additional Context
MundoSk was good, but Kosmos and ThatPacketAddon are really full of bugs

**Comment by ShaneBeee** [comment]
This issue tracker is for the Skript software itself, not for addons.
Please report any issues with addons to the respective developers of said addon.
