### ISSUE TITLE
Json format - variable

### ISSUE THREAD

**Issue by Soufreur78** [SkriptLang/Skript#2655]
Hello I'm french. Here is a bug that I have since I updated in 1.14

When I use the json chat format of Skript, I can not put any variable. I did not have problems in 1.8.

Variable : %player%, %now%, %{_t}% etc... doesn't work and break the tooltip. It's the same for suggest command and command. 

Screen show the problem : https://imgur.com/3Qbmhq0

Code `command /test:
	trigger:
		message "<tooltip:&aHey>Test 1 withou variable"

command /test2:
	trigger:
		message "<tooltip:&aHey %player%>Test 1 with variable`

Server version : CraftBukkit version git-spigot-56f8471-56118c6 (MC: 1.14.4-R0.1 SNAPSHOT)

Skript version: 2.4-beta9

I don't found any subject about this issue, i'm sorry if there is one

**Comment by ShaneBeee** [comment]
for you code, try this `send formatted "...`

**Comment by Soufreur78** [comment]
> for you code, try this `send formatted "...`


It works ! Thank you I delete my post

**Comment by ShaneBeee** [comment]
Perfect, glad it worked 👍
