### ISSUE TITLE
Parsing Stripped Wood

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2657]
### Description
For some reason, Skript cannot parse stripped wood from a string.

### Steps to Reproduce
```
command /test <string>:
    trigger:
        set {_i} to arg-1 parsed as itemtype
        broadcast "%{_i}%"
```

If you do something like ``/test diamond``, it will properly broadcast ``diamond`` indicating a successful parse.

However, ``/test stripped oak wood`` and other wood variants will not, instead broadcasting ``<none>`` indicating a failed parse.

### Expected Behavior

For ``/test stripped oak wood`` to properly return a broadcast of ``stripped oak wood`` (plus other variants, too)

### Errors / Screenshots

N/A

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta10

### Additional Context

N/A

**Comment by ShaneBeee** [comment]
Thats probably because the alias is `stripped oak bark`
https://github.com/SkriptLang/skript-aliases/blob/0640711844b08f053dda6da941e732533763fa0a/building.sk#L462

**Comment by Wealthyturtle** [comment]
That's odd... the Minecraft ID is ``minecraft:stripped_oak_wood``

**Comment by ShaneBeee** [comment]
Yeah I'm not sure why it was done that way, 
could be updated to something like
`{axis-aligned} stripped oak (bark|wood) [block¦s] = minecraft:stripped_oak_wood`
