### ISSUE TITLE
minecraft:grass Alias

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2658]
### Description

At the moment, Skript does not have an alias for the ``minecraft:grass`` block on 1.13 or newer - only ``minecraft:grass_block``.

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Errors / Screenshots

N/A

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta10

### Additional Context

N/A

**Comment by ShaneBeee** [comment]
https://github.com/SkriptLang/skript-aliases/blob/0640711844b08f053dda6da941e732533763fa0a/decoration.sk#L184

**Comment by Wealthyturtle** [comment]
Github lied to me :(
