### ISSUE TITLE
Skript error

### ISSUE THREAD

**Issue by ssaa1122** [SkriptLang/Skript#2662]
Half of my scripts not working cuz of this errpr
![image](https://user-images.githubusercontent.com/48889497/69730728-71b92f80-10dd-11ea-863a-99cce80d0eff.png)

**Comment by Anarchick** [comment]
code ?

**Comment by TPGamesNL** [comment]
Looks like SkQuery's fault

**Comment by ShaneBeee** [comment]
We do not support custom builds of Skript. Please report it to the author of the version you are using (ie: Minehut) or please reproduce the error using a version of Skript from this repo.

As you can see in the error stack trace, the error is caused by SkQuery.

**Comment by ssaa1122** [comment]
Fixed it were a error at this code
variables:
 {spawn} =
