### ISSUE TITLE
firework's spark with colors

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2663]
### Description

Should it be nice to have firework's sparks with colors?
For example:
```
on click on iron door:
   show 10 red firework's spark at clicked block
```
I know it's not a big enhancement, but it's worth to mention it.... I think

**Comment by Anarchick** [comment]
from [https://www.spigotmc.org/threads/comprehensive-particle-spawning-guide-1-13.343001/](url)
"Note: Unfortunately, FIREWORKS_SPARK particles cannot be colored. The colors they get from fireworks are completely client-side, so we have no control over them."
