### ISSUE TITLE
Low Priority: New flowers aren't included in 'any flowers'

### ISSUE THREAD

**Issue by ThePumpkin5822** [SkriptLang/Skript#2665]
Recently in 1.14 they added 3 new flowers. Lily of the Valley, Cornflower and Wither Rose. These three flowers aren't included in the any alias 'any flowers'.

```
on break of any flower:
    cancel event
```
The 3 new flowers will not be called on this event. I know there's been some changes on how aliases work, could they possibly be reintroduced in some way so I don't have to bug you guys about it?

**Comment by ShaneBeee** [comment]
> Recently in 1.14 they added 3 new flowers. Lily of the Valley, Cornflower and Wither Rose. These three flowers aren't included in the any alias 'any flowers'.
> 
> ```
> on break of any flower:
>     cancel event
> ```
> 
> The 3 new flowers will not be called on this event. I know there's been some changes on how aliases work, could they possibly be reintroduced in some way so I don't have to bug you guys about it?

Yes.  Thanks for pointing this out.   I’ll fix it when I get home.
