### ISSUE TITLE
function Error

### ISSUE THREAD

**Issue by qtt509** [SkriptLang/Skript#2669]
This function works fine. However, when reloading, an error is displayed.
so, All functions work. However, only reloads show errors. Why is this?

**"" A function named "Add_SkillDamage" already exitst in scripts ""**

Minecraft Version : 1.12.2
Skript Version : 2.4

![1](https://user-images.githubusercontent.com/58448722/70002756-5f8b3580-15a4-11ea-8deb-b0847b5e7726.PNG)

**Comment by ShaneBeee** [comment]
Its because the file is named SkillDamage and you are reloading skilldamage, which initiates another instance of the same script file, thus trying to load the same function again

**Comment by qtt509** [comment]
No, there is only one SkillDamage function.
And it works fine.

**Comment by qtt509** [comment]
> Its because the file is named SkillDamage and you are reloading skilldamage, which initiates another instance of the same script file, thus trying to load the same function again


No, there is only one SkillDamage function.
And it works fine.

**Comment by ShaneBeee** [comment]
Thats not what im saying.
You have a file named `SkillDamage.sk` and you are reloading `skilldamage`, when this happens, Skript tries to load another version of the same file, thus loading the same function again.
Skript is case sensitive when it comes to the reload command.

**Comment by qtt509** [comment]
Thank you so much !!! There is no error when I distinguished capital letters.

![캡처](https://user-images.githubusercontent.com/58448722/70003134-9746ad00-15a5-11ea-95b7-9bc46bc00d0a.PNG)
