### ISSUE TITLE
Reload Error

### ISSUE THREAD

**Issue by qtt509** [SkriptLang/Skript#2670]
If you reload the sk files one by one, there is no error.

But when I typed / sk reload scripts, I get an error in the bukkit.

why is this?

Minecraft version: 1.12.2 (Paper)
Skript : 2.4

![1](https://user-images.githubusercontent.com/58448722/70004402-797b4700-15a9-11ea-8842-986d43c7d46c.PNG)

![2](https://user-images.githubusercontent.com/58448722/70004407-7bdda100-15a9-11ea-81e5-bda46d891867.PNG)

![3](https://user-images.githubusercontent.com/58448722/70004408-7d0ece00-15a9-11ea-84f1-604e72da1293.PNG)

**Comment by Wealthyturtle** [comment]
This just means you likely have scripts that took too long to parse. Try and use brackets as much as possible in long lines in your scripts to make it easier on the parser.
