### ISSUE TITLE
Unable to clear item display name

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2673]
### Description

At the moment, the clear effect does not seem to work on the ``display name`` expression (for items).

### Steps to Reproduce

```
command /t:
    trigger:
        broadcast "Before %player's tool's display name%"
        clear player's tool's display name
        broadcast "After %player's tool's display name%"
```

Run the command ``/t`` while holding a renamed item, and the before and after broadcasts are the same.

### Expected Behavior

The item's display name should be cleared.

### Errors / Screenshots

No parsing or console errors occur.

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4

### Additional Context

N/A

**Comment by ShaneBeee** [comment]
Just tested this using 1.12.2 and 1.16.1 with Skript 2.5-beta1.

When parsing I get this error:
```
[14:54:28 ERROR]: the display name of the tool of the player can't be deleted/cleared. It can however be reset which might result in the desired effect. (test.sk, line 39: clear player's tool's display name')
```

As the error stated, I changed clear -> reset and it works as intended. 
I'm guessing this got fixed somewhere along the way .... so yay 👍

**Comment by FranKusmiruk** [comment]
> [14:54:28 ERROR]: the display name of the tool of the player can't be deleted/cleared. It can however be reset which might result in the desired effect. (test.sk, line 39: clear player's tool's display name')

So Skript actually gives some useful errors huh
