### ISSUE TITLE
FAWE Worldguard 1.14 not supported

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#2674]
### Errors / Screenshots
![image](https://user-images.githubusercontent.com/47111280/70230923-66fc3b80-176a-11ea-8261-9d0ce1ac6872.png)

### Server Information
* **Server version/platform:** 1.14.4 Paper
* **Skript version:**  2.4

**Comment by KnuffelBeestje** [comment]
Any update on this for 2.4.1?
Still waiting for the support.

WorldGuard 7.0.1
Skript version 2.4.1

**Comment by bensku** [comment]
No changes in 2.4.1. If upstream WorldGuard 7 works with FAWE now, we could switch to that hook. Support for anything FAWE-specific is not going to happen anytime soon.

**Comment by KnuffelBeestje** [comment]
> No changes in 2.4.1. If upstream WorldGuard 7 works with FAWE now, we could switch to that hook. Support for anything FAWE-specific is not going to happen anytime soon.

Yes, WorldGuard 7 support would be great :)

**Comment by Zzheyd** [comment]
Maybe one day... FAWE > WE :/ But skript dont hook with
