### ISSUE TITLE
Team support 

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2676]
Add a team support which was added in: 1.13*? E.g
Force|make plater join team ""
Create team ""
On damage:
If player is in team "":
Edit from 1.13 not 14

**Comment by FranKusmiruk** [comment]
Are you talking about scoreboard teams? If so, this is a duplicate since there are some issues open about scoreboard support in general, teams being a part of it.

**Comment by Misio12320** [comment]
I mean https://minecraft.gamepedia.com/Commands/team

**Comment by FranKusmiruk** [comment]
That's just scoreboard teams, it has its own command now but they're still part of the scoreboard system. That being said, there's a ton of issues requesting general scoreboard support, it's sadly not the easiest of the tasks and hence why we haven't added it yet.

So, I am closing the issue as it's pretty much a duplicate.
