### ISSUE TITLE
on inventory click

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#2681]
### Description
Every time some player changes every inventory/clicks on it etc. then console sends this message:

[Skript] In 1.13+ you cannot get the title name of an inventory outside of an InventoryClickEvent, Only if this inventory has an InventoryHolder may it be used in this state.

### Server Information
* **Server version/platform:**      1.14.4, Paper 226
* **Skript version:**                2.4-beta10

**Comment by Wealthyturtle** [comment]
Does this error occur if you do not have any scripts loaded?

**Comment by 3meraldK** [comment]
> Does this error occur if you do not have any scripts loaded?

I use script to preventing stealing items from GUI, made for statistics.

**Comment by 3meraldK** [comment]
Anyway, I solved that spam message by uploading Sk-NBeeT add-on. It's okay, but I want to know how to solve te problem without uploading that addon or/and removing on inventory click event.

**Comment by Wealthyturtle** [comment]
Are you sure that is from Skript itself? Could be an addon. I am unable to find that string in the Skript repo.

**Comment by FranKusmiruk** [comment]
This error comes from skQuery:
https://github.com/SkQuery/SkQuery/blob/master/src/main/java/com/w00tmast3r/skquery/elements/expressions/ExprInventoryName.java#L31

**Comment by koukuko** [comment]
This log does come from SkQuery, and this happened because the player clicked on the UI of the inventory (not the slot) while picking up the item.

You can check `on inventory click` event like this to avoid this error.
```
on inventory click:
	type of event-inventory is set
        # your code
```
