### ISSUE TITLE
Custom commands not showing in tab completer

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#2685]
### Description
So in 1.15 commands seem to register, as in they work, but they do not show up in the command suggestions.

### Steps to Reproduce
Simple command test:
```vb
command /test:
    trigger:
        send "&aSoooo.... the command works!"
```

### Expected Behavior
The command should show up in the command suggestions as previous versions did.

### Errors / Screenshots
As you can see in the image, I have the command in my code, when I run the command, the output works (message is sent to player), but when I type the command `/test` I get the message that the command does not exist.
![Screen Shot 2019-12-11 at 1 51 57 AM](https://user-images.githubusercontent.com/20008482/70610802-0da46a00-1bb9-11ea-863d-c57ae9e23653.png)

### Server Information
* **Server version/platform:** version git-Spigot-f39a89e-db0dafb (MC: 1.15)
* **Skript version:** Skript 2.4

### Additional Context
n/a

**Comment by bensku** [comment]
Reloading commands completions to clients is the one place where Skript calls OBC code. It is version specific and will need an update for 1.15.
