### ISSUE TITLE
(json formatting) Tooltip bugs

### ISSUE THREAD

**Issue by soulstriker23** [SkriptLang/Skript#2686]
### Description
When using skript version **2.4**. Having any type of (arg-player) included into the tooltip, weblink, or cmd will not make the json message work properly. This issue was **not** in 2.4-alpha4 version. So I'm not sure why it changed when it got updated. 

### Steps to Reproduce
Code formatted
![image](https://user-images.githubusercontent.com/25358676/70645500-fd60af00-1bf9-11ea-8cdf-27db55618a65.png)

command /test [< player >]:
	trigger:
		send "&aTesting here <tooltip:&eTeleport to &a%arg-player%><cmd:tp %arg-player%>&e%arg-player%" to player

![image](https://user-images.githubusercontent.com/25358676/70645204-58de6d00-1bf9-11ea-98d2-5d0c71e5c952.png)

### Additional Context
No errors at all, if you just remove the %arg-player% it sends as normal.

![image](https://user-images.githubusercontent.com/25358676/70645751-6811ea80-1bfa-11ea-903d-b6d0ba4e2eba.png)

### Server Information
Server version/platform: 1.14.4; PaperSpigot 226
Skript version: 2.4

**Comment by bensku** [comment]
This was caused by the fix for #2198. You now need to tell Skript that you *really* want to use dynamic content in formatting tags, because it can be dangerous. This can be done with <code>formatted</code> expression. In this case, it is probably safe.
