### ISSUE TITLE
GUI problem

### ISSUE THREAD

**Issue by AggerTV** [SkriptLang/Skript#2689]
https://www.spigotmc.org/threads/cancel-event.406674/#post-3620205

Skript version:
2.4-beta9

Server version:
Paper 1.12.2

**Comment by FranKusmiruk** [comment]
Please fill the issue request with clear information of what's the issue next time.

**Comment by TPGamesNL** [comment]
> https://www.spigotmc.org/threads/cancel-event.406674/#post-3620205
> 
> Skript version:
> 2.4-beta9
> 
> Server version:
> Paper 1.12.2

I'm gonna assume you reported is because the post stated that is was a Skript limitation, but it's not a Skript limitation. Spigot doesn't allow it, so Skript gives you a warning.
