### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#2690]
### Description
While starting a server, I got spam of these messages:
`[21:15:26 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]`

### Server Information
* **Server version/platform:**       1.14.4, Paper 236
* **Skript version:**                2.4-beta10

**Comment by ShaneBeee** [comment]
This error is caused by skript-mirror, please update to skript-mirror 2.0.0
