### ISSUE TITLE
Can't set a players gamemode to spectator.

### ISSUE THREAD

**Issue by skptical** [SkriptLang/Skript#2693]
The problem i'm having is that im re-creating essentials and i was doing all find. Until i got to the gamemode commands i tried to create a command to set the player gamemode to spectator but all it does is spit out the error: 

'spectator' is not an entity type (basics.sk line 199: set player's gamemode to spectator') 

I am currently using paper spigot 1.8.8 SNAPSHOT and skript 2.2 for 1.8

**Comment by bensku** [comment]
Unfortunately we can't provide help for any issues you may have with Minecraft 1.8 here, see #847 for details. With a bit searching, you might be able to find a fork that mostly works, though.
