### ISSUE TITLE
Can't delete target entity

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#2695]
### Description
When attempting to delete a target entity, nothing happens

### Steps to Reproduce
example code:
```vb
delete target entity of player
```
When running this code, the entity is still there.

### Expected Behavior
The entity should delete

### Errors / Screenshots
no errors

### Server Information
* **Server version/platform:** 2.4
* **Skript version:** git-Paper-5 (MC: 1.15)

### Additional Context
I found the issue, will be doing a PR shortly.

**Comment by Anoniempje1234** [comment]
You can always try to kill the target entity :)

**Comment by ShaneBeee** [comment]
> You can always try to kill the target entity :)

Yes, I am aware of what I can do, but Im not trying to kill an entity, I'm trying to delete them.

**Comment by Wealthyturtle** [comment]
@Anoniempje1234 Killing the target entity will result in particles, and mob drops, which adds further complexity.
