### ISSUE TITLE
drops not being removed.

### ISSUE THREAD

**Issue by FallingCactus** [SkriptLang/Skript#2700]
### Description
I have found after updating to 1.15 that anything to do with drops "to drops" "clear drops" ect is not working, loads fine but does not clear the drops.

### Steps to Reproduce
any basic script to clear dropped items in 1.15

### Expected Behavior
as 99% of my skripts work perfectly in 1.15 i just assumed they would too but thought I would let you know in case its not been picked up yet.  

### Errors / Screenshots
no errors on reload.

### Server Information
* ** Paper 1.15 release #19
* ** Skript 2.4

**Comment by FranKusmiruk** [comment]
Can you try changing `clear` by `cancel` in any of the scripts you were deleting drops and see if that makes any difference?

**Comment by FallingCactus** [comment]
> Can you try changing `clear` by `cancel` in any of the scripts you were deleting drops and see if that makes any difference?

Using cancel in place of clear has the same effect, no errors but drops to not despawn.

**Comment by ShaneBeee** [comment]
Do you have any code to reproduce this issue?
In the Steps to Reproduce you put:
> any basic script to clear dropped items in 1.15

That doesn't really help us triage this issue.

I just tested this:
```vb
on death of sheep:
    clear drops
```
and it works fine, when I kill the sheep, they drop nothing! I can not reproduce this issue.

**Comment by FallingCactus** [comment]
`on death of a player:
	loop drops:
		set {chargeback.%uuid of victim%::*} to drops
		if player has permission "{@Permission}":
			clear drops
			set {chargeback.enabled.%uuid of victim%} to true
			stop`

this is something i had working before but does not seem to work since the 1.15 update.

**Comment by ShaneBeee** [comment]
My guess is something wrong with your code, I tried this to test:
```vb
on death of a player:
    clear drops
```
and it worked as it should, I can not replicate this issue.

**Comment by Wealthyturtle** [comment]
@FallingCactus Have you tried with just Skript alone and no Skript addon plugins?

**Comment by FallingCactus** [comment]
```on death of a player:
	clear drops```


just tried this and it doesnt seem to work either.

**Comment by ShaneBeee** [comment]
100% a conflicting plugin then. I just Skript running on a test server and it works as intended. Thus can not replicate this issue in Skript.

**Comment by FallingCactus** [comment]
I have removed the 2 addons i had "skquery, skellett" Skript priority set on highest and using just the simple:
 on death of a player:
    clear drops

does not seem to work. added and broadcast after the "clear drops" and it showed fine in chat.

honesty lost on what this could be, thanks anyway guys.

**Comment by bensku** [comment]
Check that you're running latest Spigot/Paper, new MC releases are usually a bit buggy.
