### ISSUE TITLE
name of Inventory not set variable

### ISSUE THREAD

**Issue by qtt509** [SkriptLang/Skript#2701]
name of Inventory not set {_name}
MC: 1.15
Skript : 2.4

command test:
	trigger:
		set {_inv} to chest with 3 row named "Test"
		open {_inv} to player
		
on inventory click:
	set {_name} to name of current inventory of player
	message "%{_name}%" to player

![1](https://user-images.githubusercontent.com/58448722/70943547-7a75a380-2094-11ea-9ba2-c1c5dc6cf71c.PNG)

**Comment by ShaneBeee** [comment]
Duplicate of #2069
