### ISSUE TITLE
why loop serveral many times?  (  on inventory click )

### ISSUE THREAD

**Issue by zidlsl** [SkriptLang/Skript#2702]
### Description

On inventory click Event
i using Loop

but several times like 2 or 3

### Errors / Screenshots

![제목 없음](https://user-images.githubusercontent.com/35989737/70991680-51442a00-210b-11ea-9084-a1f68148b1c4.png)

### Server Information
* **Server version/platform:**        1.12.2
* **Skript version:**                 2.4

**Comment by zidlsl** [comment]
i think problem is cancel event

**Comment by Wealthyturtle** [comment]
Is there a parse error with this script? If so, please attach it here.

**Comment by zidlsl** [comment]
> Is there a parse error with this script? If so, please attach it here.

No Error

**Comment by Wealthyturtle** [comment]
Uhh what's the problem then with the script? What are you reporting exactly?

**Comment by nopeless** [comment]
@zidlsl you don’t need to clear {_stack::*}, there are redundant code everywhere.
this place is where you submit issues about skript not issues about your script.
how do you even reproduce the error

i suggest closing

**Comment by Wealthyturtle** [comment]
Closing this issue since it is unclear what OP is reporting.
