### ISSUE TITLE
1.15 support

### ISSUE THREAD

**Issue by bensku** [SkriptLang/Skript#2703]
Since Bukkit API was not changed much, Skript 2.4 works fine on 1.14. However, there are a few rough edges.

* Aliases for new things are missing (updates at skript-aliases repo are out, next release will bundle them)
* Tab completions require update due to OBC code (#2685, PR #2688 with other code)
* Bees are not supported (PR #2688, might *exceptionally* merge this feature to stable branch)
* Skript is compiled against 1.14 (can't use 1.15 APIs, old removed APIs are not compile errors)
* Test scripts are not run on 1.15 (2.4 not affected, it doesn't have them at all)
  * Add runner for Paper 1.15
  * To reduce time spent on tests, move 1.13 or 1.14 to extra platforms

I'll try to get this done by end of this week.

**Comment by iCodeDreamsMC** [comment]
Will this fix the command auto completer in 1.15 Paper MC?

**Comment by ShaneBeee** [comment]
> Will this fix the command auto completer in 1.15 Paper MC?

It literally says that in his message
> Tab completions require update due to OBC code (#2685, PR #2688 with other code)

**Comment by iCodeDreamsMC** [comment]
I'm blind! Sorry. LOL
