### ISSUE TITLE
Unable to Modify Item Amount of loop-item

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2707]
### Description
Currently, you are not able to modify the item amount of loop-item when looping through a player's inventory. I'm not entirely sure if this is a bug, but it definitely seems strange considering that you can clear loop-item and do all other manner of changes to it, just not the item amount for some reason.

### Steps to Reproduce

```
command /t:
    trigger:
        loop all items in player's inventory:
            broadcast "Before - %item amount of loop-item%"
            set item amount of loop-item to 10
            broadcast "After - %item amount of loop-item%"
```
And fill your inventory with random items

### Expected Behavior

All items in the player's inventory should have an item amount of 10 after running the command.

### Errors / Screenshots

Command Output (with 3 random items inside the inventory):
```
Before - 1
After - 1
Before - 1
After - 1
Before - 1
After - 1
```

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4

### Additional Context

N/A

**Comment by nopeless** [comment]
I had this problem as well
you can work around by looping the slots and setting the slot
but i still think loop-item should be set like that as well(the code you provided above)
