### ISSUE TITLE
Yaw/Pitch of location does not work if the location is in a variable

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#2708]
### Description

Yaw/Pitch of location does not work if the location is in a variable
### Steps to Reproduce
set {_loc} to location of player
send "%pitch of {_loc}% %yaw of {_loc}%"
all none ^

### Expected Behavior
Expected to give same result as %yaw of player% does

### Errors / Screenshots
no errors

### Server Information
* **Server version/platform:** 1.12.2 Paper 
* **Skript version:**  2.4

**Comment by Wealthyturtle** [comment]
That's not your problem, your problem is that the ``location of player`` does not come with yaw/pitch. If you do...
```
set {_loc} to location of player
set {_loc}'s yaw to player's yaw
set {_loc}'s pitch to player's pitch
send "%pitch of {_loc}% %yaw of {_loc}%"
```

Then it should not return <none>. I believe this is done for optimization purposes (?) since not many people use yaw/pitch anyways.

**Comment by Govindass** [comment]
> That's not your problem, your problem is that the `location of player` does not come with yaw/pitch. If you do...
> 
> ```
> set {_loc} to location of player
> set {_loc}'s yaw to player's yaw
> set {_loc}'s pitch to player's pitch
> send "%pitch of {_loc}% %yaw of {_loc}%"
> ```
> 
> Then it should not return `<none>`. I believe this is done for optimization purposes (?) since not many people use yaw/pitch anyways.

it still returns none and in older version of Skript it worked right

**Comment by Wealthyturtle** [comment]
Can replicate, my bad. Setting a location's yaw/pitch does not work

**Comment by nopeless** [comment]
can we increase priority @Wealthyturtle ?
set {a} to location(0, 100 ,0, ("world" parsed as world), 0, 0)
this does not save the pitch as well

**Comment by jaylawl** [comment]
encountered  this exact issue on paper 1.14.4 / spigot 2.4 just last night

**Comment by jaylawl** [comment]
```
command /loc:
    trigger:
    
        command sender != console
        
        set {_l} to location(0, 0, 0, (command sender's world))
        set {_l}'s yaw to 180
        set {_l}'s pitch to -45
        
        send "yaw: %{_l}'s yaw%, pitch: %{_l}'s pitch%"
        
        {_l}.setYaw(180)
        {_l}.setPitch(-45)
        
        send "yaw: %{_l}'s yaw%, pitch: %{_l}'s pitch%"
        
        send "yaw: %{_l}.getYaw()%, pitch: %{_l}.getPitch()%"
```
Extracting the yaw & pitch via skript-mirror works correctly (send #3)

**Comment by Govindass** [comment]
to avoid the need of changing your scripts to use skript-mirror code, I have made a replacement for broken vanilla Skript syntaxes:
```
#Yaw, is broken in Skript 2.4
expression:
	patterns:
		[the] yaw of %location%
		%location%'s yaw
	return type: number
	get:
		return expression 1.getYaw()
	set:
		expression 1.setYaw(change value)
	remove:
		expression 1.setYaw(expression 1.getYaw() - change value)
	add:
		expression 1.setYaw(expression 1.getYaw() + change value)

#Pitch, is broken in Skript 2.4
expression:
	patterns:
		[the] pitch of %location%
		%location%'s pitch
	return type: number
	get:
		return expression 1.getPitch()
	set:
		expression 1.setPitch(change value)
	remove:
		expression 1.setPitch(expression 1.getPitch() - change value)
	add:
		expression 1.setPitch(expression 1.getPitch() + change value)
```

**Comment by ShaneBeee** [comment]
Can this be rechecked?

I just did some testing and it seems to work.

example code:
```vb
command /test:
    trigger:
        set {_l} to location(1, 1, 1, world "world", 11, 12)
        send "Y: %yaw of {_l}%"
        send "P: %pitch of {_l}%"
        set yaw of {_l} to 10
        set pitch of {_l} to -45
        send "Y: %yaw of {_l}%"
        send "P: %pitch of {_l}%"
```
output:
```
> test
[14:54:36 INFO]: Y: 11
[14:54:36 INFO]: P: 12
[14:54:36 INFO]: Y: 10
[14:54:36 INFO]: P: -45
```

**Comment by Wealthyturtle** [comment]
> Can this be rechecked?
> 
> I just did some testing and it seems to work.
> 
> example code:
> 
> ```vbnet
> command /test:
>     trigger:
>         set {_l} to location(1, 1, 1, world "world", 11, 12)
>         send "Y: %yaw of {_l}%"
>         send "P: %pitch of {_l}%"
>         set yaw of {_l} to 10
>         set pitch of {_l} to -45
>         send "Y: %yaw of {_l}%"
>         send "P: %pitch of {_l}%"
> ```
> 
> output:
> 
> ```
> > test
> [14:54:36 INFO]: Y: 11
> [14:54:36 INFO]: P: 12
> [14:54:36 INFO]: Y: 10
> [14:54:36 INFO]: P: -45
> ```

Try  
```
set {_loc} to location of player
set {_loc}'s yaw to player's yaw
set {_loc}'s pitch to player's pitch
send "%pitch of {_loc}% %yaw of {_loc}%"
```

**Comment by Govindass** [comment]
I just tested, I cannot reproduce this bug anymore, so it's fixed, yay! closing
