### ISSUE TITLE
set world of location does nothing

### ISSUE THREAD

**Issue by GovindasOM** [SkriptLang/Skript#2709]
### Description
using:
set {w} to location of player
set world of {w} to "spawn" parsed as a world
send "%world of {w}%"

sends the same world as {w} originally had, not new "spawn" one, but "spawn" world definitely exists 

### Server Information
* **Server version/platform:**  1.12.2 Paper & 1.16.3 Paper
* **Skript version:** 2.5.1

**Comment by nopeless** [comment]
The same issue occurs to me
tested by
`set {w} to location of player`
`send "%world of {w}%" # sends "world"`
`set world of {w} to ("world_nether" parsed as world)`
`send "%world of {w}%" # sends "world"`

**Comment by Govindass** [comment]
skript-mirror fix:
```
#Set world of location, is broken in Skript 2.4
expression:
	patterns:
		[the] world of %location%
		%location%'s world
	return type: world
	get:
		return expression 1.getWorld()
	set:
		expression 1.setWorld(change value)
```

**Comment by Govindass** [comment]
the skript-mirror fix above doesn't always work seems like, so I've did some testing to actually get when this thing broke

this thing has been broken for a very long time, I found that it has been broken in 2.2 dev30d already, in 2.2 dev30d it throws an error, while in newer versions it doesn't throw any error
``` the world of {_loc} can't be set to anything (worldexpr.sk, line 8: set world of {_loc} to world("test")')```

**Comment by Govindass** [comment]
got skript-mirror workaround fixed:
```
expression:
	patterns:
		[the] [custom] world [of %locations/entities%]
		%locations/entities%'[s] [custom] world
	return type: world
	get:
		return (expression 1).getWorld()
	set:
		expression 1.setWorld(change value)
```

may require to unregister Skript's world syntax to work, which is:
```
[the] world [of %locations/entities%], %locations/entities%'[s] world
```

you can unregister it using my skript-mirror code snippet that can be found here:
https://pastebin.com/raw/xyhCSr2d

**Comment by Govindass** [comment]
I just tested and this problem still persists on 2.5beta4

**Comment by Romitou** [comment]
I can reproduce.
- Skript 2.5
- Paper 1.16.2 (git-Paper-182)

**Comment by Govindass** [comment]
just tested, still present in 2.5.1

**Comment by Sonlein** [comment]
very annoying bug, still on 2.5.1

**Comment by Sonlein** [comment]
> got skript-mirror workaround fixed:
> 
> ```
> expression:
> 	patterns:
> 		[the] [custom] world [of %locations/entities%]
> 		%locations/entities%'[s] [custom] world
> 	return type: world
> 	get:
> 		return (expression 1).getWorld()
> 	set:
> 		expression 1.setWorld(change value)
> ```
> 
> may require to unregister Skript's world syntax to work, which is:
> 
> ```
> [the] world [of %locations/entities%], %locations/entities%'[s] world
> ```
> 
> you can unregister it using my skript-mirror code snippet that can be found here:
> https://pastebin.com/raw/xyhCSr2d

that's doesn't work, can you help please?
Can't understand this loop: 'loop ...Skript.effects'
Can't understand this expression: {_r}.patterns
Can't understand this expression: amount of ...Skript.effects

**Comment by Govindass** [comment]
> > got skript-mirror workaround fixed:
> > ```
> > expression:
> > 	patterns:
> > 		[the] [custom] world [of %locations/entities%]
> > 		%locations/entities%'[s] [custom] world
> > 	return type: world
> > 	get:
> > 		return (expression 1).getWorld()
> > 	set:
> > 		expression 1.setWorld(change value)
> > ```
> > 
> > 
> > may require to unregister Skript's world syntax to work, which is:
> > ```
> > [the] world [of %locations/entities%], %locations/entities%'[s] world
> > ```
> > 
> > 
> > you can unregister it using my skript-mirror code snippet that can be found here:
> > https://pastebin.com/raw/xyhCSr2d
> 
> that's doesn't work, can you help please?
> Can't understand this loop: 'loop ...Skript.effects'
> Can't understand this expression: {_r}.patterns
> Can't understand this expression: amount of ...Skript.effects

you need skript-reflect

**Comment by Sonlein** [comment]
> > > got skript-mirror workaround fixed:
> > > ```
> > > expression:
> > > 	patterns:
> > > 		[the] [custom] world [of %locations/entities%]
> > > 		%locations/entities%'[s] [custom] world
> > > 	return type: world
> > > 	get:
> > > 		return (expression 1).getWorld()
> > > 	set:
> > > 		expression 1.setWorld(change value)
> > > ```
> > > 
> > > 
> > > may require to unregister Skript's world syntax to work, which is:
> > > ```
> > > [the] world [of %locations/entities%], %locations/entities%'[s] world
> > > ```
> > > 
> > > 
> > > you can unregister it using my skript-mirror code snippet that can be found here:
> > > https://pastebin.com/raw/xyhCSr2d
> > 
> > 
> > that's doesn't work, can you help please?
> > Can't understand this loop: 'loop ...Skript.effects'
> > Can't understand this expression: {_r}.patterns
> > Can't understand this expression: amount of ...Skript.effects
> 
> you need skript-reflect

okay, but if i disable the on load expression: "/ disable-expression [the] world [of% locations / entities%],% locations / entities% '[s] world" then it gives me "Can't understand this condition / effect: set world of% location%...", as can I use the new expression from the script mirror?

**Comment by Govindass** [comment]
> > > > got skript-mirror workaround fixed:
> > > > ```
> > > > expression:
> > > > 	patterns:
> > > > 		[the] [custom] world [of %locations/entities%]
> > > > 		%locations/entities%'[s] [custom] world
> > > > 	return type: world
> > > > 	get:
> > > > 		return (expression 1).getWorld()
> > > > 	set:
> > > > 		expression 1.setWorld(change value)
> > > > ```
> > > > 
> > > > 
> > > > may require to unregister Skript's world syntax to work, which is:
> > > > ```
> > > > [the] world [of %locations/entities%], %locations/entities%'[s] world
> > > > ```
> > > > 
> > > > 
> > > > you can unregister it using my skript-mirror code snippet that can be found here:
> > > > https://pastebin.com/raw/xyhCSr2d
> > > 
> > > 
> > > that's doesn't work, can you help please?
> > > Can't understand this loop: 'loop ...Skript.effects'
> > > Can't understand this expression: {_r}.patterns
> > > Can't understand this expression: amount of ...Skript.effects
> > 
> > 
> > you need skript-reflect
> 
> okay, but if i disable the on load expression: "/ disable-expression [the] world [of% locations / entities%],% locations / entities% '[s] world" then it gives me "Can't understand this condition / effect: set world of% location%...", as can I use the new expression from the script mirror?

please contact me at Discord Govindas#8889 for help as we shouldn't spam bug report with irrelevant information

**Comment by Nioxed** [comment]
this still seems to be an issue in 2.5.3.

Shouldn't this deserve more attention as its been broken for over a year, and it's pretty important?

**Comment by Govindass** [comment]
> 
> 
> this still seems to be an issue in 2.5.3.
> 
> Shouldn't this deserve more attention as its been broken for over a year, and it's pretty important?

it has been broken for multiple years - if not the entire Skript's lifespan

I agree on higher priority, using skript-reflect to do this, slows down the server as reflection isn't as optimized as base Skript syntaxes
