### ISSUE TITLE
Directional block comparison is broken on 1.12

### ISSUE THREAD

**Issue by antoinech2** [SkriptLang/Skript#2711]
### Description

A lot of item name do not seem to work and comparison is very hard to do.

### Steps to Reproduce
Player head in hand:
`send "%tool of player%"`
Output: "south facing ender dragon head"

dirch door in hand:
`send "%tool of player%"`
Output: "right-hinged closed top birch wood door"

Moreover, comparaison are destroyed. You have to compare with the EXACT item name
Ex: `if tool of player is head or player head` doesn't work
Also, it's impossible to compare a type of door, or all types of door
`if targeted block of player is door, any door, any wood door, birch door, closed birch door` None of them works!

### Server Information
* **Server version/platform:**  PaperSpigot 1.12     
* **Skript version:**   2.4 (last version)             

### Additional Context
It very complicated to compare items, and it destroys a lot of my skripts. Please help ;)

**Comment by ShaneBeee** [comment]
1) I recommend if you are going to post an issue and you require help, don't insult the team by saying their work is "ridiculous or stupid"... that is just blatantly rude. TheBentoBox (mostly) and other people spent a LOT of time writing the aliases, trying their best to make sure they were suitable for all users and properly expressed their types. Insulting them by saying they're stupid is just unneeded on this issue tracker, and get's you no where. 
(I have edited your message to remove the rude comments)

2)
> Ex: if tool of player is head or player head doesn't work

I tried this exact line of code, and it works with no issues. I gave myself a head of myself, and that condition returns true.

3) As for the door comparison issue. We will look into this. I will mark it as a bug.

**Comment by antoinech2** [comment]
I may have expressed myself poorly but I was not talking about the work of the developers (which I respect a lot), but the name of the items which seems very strange and bizarre to me. Sorry for the misunderstanding.

I'll make some more tests to verify the comparaison of the player head.

**Comment by bensku** [comment]
FYI, the comparison issues are mostly specific to 1.12 and older Minecraft versions. While Minecraft 1.12 does use block states, Spigot API got good support for them only in 1.13.

@antoinech2 If you can update to Minecraft 1.14 or 1.15, I would recommend that. Comparison issues might not ever be fully solved on 1.12.

**Comment by legofreak1999** [comment]
[Issue Regarding Head](https://github.com/SkriptLang/skript-aliases/commit/7efad1a0b2a2b6a08660062ccaa618d20b356753#commitcomment-37821004)

**Comment by APickledWalrus** [comment]
This might work better now with #3419 
I'll do some testing.
