### ISSUE TITLE
Playing sound with distance

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2715]
Hey. Help please with my sound. When I try to play sound at target block named {X} with volume, pitch (without for/at player) it plays the sound but when I go away it does not go stealth. Can you help?

every 1 real seconds:
    if now formatted as "HH:mm:ss" is "23:38:58":
        play sound "custom." with volume 2 with pitch 1 at {X}
        wait 1 real second
        play sound "custom." with volume 2 with pitch 1 at {X}
        stop

**Comment by Wealthyturtle** [comment]
Cleaned up code:
```
on script load:
    set {x} to location (x), (y), (z) in (world "world") #Replace with some other location in your world

every 1 second:
    play sound "ENTITY_VILLAGER_NO" with volume 2 with pitch 1 at {x}
    wait 1 second
    play sound "ENTITY_VILLAGER_NO" with volume 2 with pitch 1 at {x}
```

Unable to replicate. The villager noise I used does not travel has a radius but does not permeate forever.

**Comment by Misio12320** [comment]
The custom sounds is locked to player. how to fix it?

**Comment by Misio12320** [comment]
@Wealthyturtle

**Comment by Wealthyturtle** [comment]
I don't see why the custom sound would be "locked" to a player, unless:

1) Your custom sound is extremely long
2) Your area is too small and so the sound will always be playing

**Comment by Kartosowski** [comment]
If you're using a custom sounds and is playing globally just convert it to mono

https://onlineaudioconverter.com/
