### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#2718]
### Description
Is there a possibility to add 'except'? For example:
`kill all monsters except zombie villager`

**Comment by ShaneBeee** [comment]
Yes there is, there is a filter system.

ex:
`kill all monsters where [input is not a zombie villager]`

For the future, please use the forums/discord or check the docs first, if you require assistance with general Skript syntaxes.

This issue tracker is for, well, issues.
