### ISSUE TITLE
Wont even launch

### ISSUE THREAD

**Issue by emil302s** [SkriptLang/Skript#2720]
When i try and launch it it loads somthing but after that nothing happens

**Comment by ShaneBeee** [comment]
We're going to need a lot more info than this. 
This is why we provide a template for you to fill in, the one which you deleted.

I'm closing this as there is absolutely no info here to help triage an issue.

**Comment by emil302s** [comment]
The is not information i can give nothing happens when i try and launch it

**Comment by Wealthyturtle** [comment]
You're not providing us a lot of information, @emil302s.

Server Version? Skript Version? Skript Addons? Plugins? Scripts? Server Logs? etc.

**Comment by Wealthyturtle** [comment]
Wait. Why are you trying to run the Skript Jar?!
