### ISSUE TITLE
Bug: spawn reason expression issues

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2722]
### Description
I want to cancel any wandering trader spawns except the ones that come via plugin. Skript outputs, that the spawn reason for that would be "customized".

However, it will complain saying "Cant compare a spawn reason with 'customized'".

Aditionally, when trying to use `CreatureSpawnEvent` via skript-mirror instead, it refuses to output `event.getSpawnReason()` correctly and instead outputs the skript aliases for that spawn reason.

### Steps to Reproduce
```
on spawn of wandering trader:
    broadcast "%spawn reason%"
    spawn reason != customized
    cancel event
```

### Errors / Screenshots 
```
Can't compare a spawn reason with 'customize' 
```

### Server Information
* **Server version/platform:**       paper1.14
* **Skript version:**                2.4

**Comment by ShaneBeee** [comment]
This issue falls under #2637 

Bensku has actually fixed this in his PR #2721 (just tested It to make sure that actually was fixed before I said it).


For the time being (until the PR is merged and released), use string comparison, 
ie: `if "%spawn reason%" != "customized":`
