### ISSUE TITLE
Bug: "armor stands" not reconigzed as plural(?)

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2723]
### Description
The code below worked in the previous skript version (i think 2.3.6). After updating to 2.4, it will not.

### Steps to Reproduce
Does not work:
```
command /as:
    trigger:
        loop all armor stands:
            broadcast "%loop-entity%"
```

This code however *does work*:
```
command /as:
    trigger:
        loop (armor stands in world "survival"):
            broadcast "%loop-entity%"
```

### Expected Behavior
Loop all armor stands.

### Errors / Screenshots
```
Can't loop armor stand because it's only a single value
```

### Server Information
* **Server version/platform:**       1.14 papr
* **Skript version:**                2.4

**Comment by nopeless** [comment]
armor stands is recognized as plural.
but specifically for armor stands, the world does not default to the world of executer
more like a very low priority bug

**Comment by Runakai1** [comment]
Also there is no armor stand entity alias. Setting a variable to an Armor stand only makes it an item
