### ISSUE TITLE
Bug: skript is not creating integers, but longs

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2728]
### Description
Im trying to pass integers to some skript-mirror stuff where integers are a required input

### Steps to Reproduce
```
command /testy:
    trigger:
        set {_n} to 1
        broadcast "%{_n}'s class%"
        set {_n} to ("1" parsed as integer)
        broadcast "%{_n}'s class%"
```
Returns `java.long.Long` in both broadcasts

(if you're having this issue, use {_n}.intValue() to get the integer you need)

### Expected Behavior
To be what skript calls an integer actually be an integer.
I'll find a way to work around, but it's misleading and might throw people off.

### Server Information
* **Server version/platform:**       paper 1.14.4
* **Skript version:**               2.4 (along with skript-mirror 1.0.0)

**Comment by bensku** [comment]
Skript does not really have an integer data type, just number. Moreover, "integer" in general is a very different thing from Java's <code>int</code> or <code>java.lang.Integer</code>. A <code>long</code> does not contain fractionals, so it is an integer too.

Currently, the number type Skript uses is implemented with <code>java.lang.Number</code>, which allows you to get <code>int</code> from it like you did. This is the best you can do, although even that is may change at some point in future.

**Comment by jaylawl** [comment]
Why not just call the thing a long then and call it a day? No reason to be misleading in that way. I can see why this wouldn't be an easy fix, moreover anything one would want to touch without the whole card house falling down

**Comment by bensku** [comment]
<code>long</code> is a very confusing name for people without programming experience. However, my main point was that Skript doesn't have an integer type. There is just a number that could be integer, a floating point number or something else. Do not assume it is anything by <code>java.lang.Number</code>.

**Comment by jaylawl** [comment]
Fair, thanks

**Comment by Pikachu920** [comment]
also, skript-mirror handles number conversion for you... it requires no extra code on your part

**Comment by jaylawl** [comment]
@Pikachu920 maybe im using an outdated version then (im running 1.0.0). i was messing about with the new custommodeldata stuff from 1.14, using the methods provided by spigot `item.setCustomModelData(int)` - however it would straight up always tell me that  i was inputting longs instead of integers.
