### ISSUE TITLE
The server delays and spam in the console. (on inventory click)

### ISSUE THREAD

**Issue by Carvane** [SkriptLang/Skript#2732]
### Description
The server delays and spam in the console.

### Errors / Screenshots
https://pastebin.com/ufB3tuMq

### Server Information
Server version: git-Paper-237 (MC: 1.14.4)"
Skript version: 2.4

**Comment by nopeless** [comment]
code? @Carvane

**Comment by jaylawl** [comment]
```
 java.lang.IllegalArgumentException: Slot 64 greater than inventory slot count
```
You defined a slot that is "impossible". No inventory has a slot number that is this big (not counting glitched chest inventories)
Your slot number must be at most 53 (for a chest inventory for 6 rows)

**Comment by Carvane** [comment]
Maybe someone breaks it. Here you have the code script https://pastebin.com/jhg9p0Y2

**Comment by Jayderp** [comment]
> Maybe someone breaks it. Here you have the code script https://pastebin.com/jhg9p0Y2

Use this and close your bug report.
https://pastebin.com/sZYSFqi1

**Comment by Jayderp** [comment]
> Maybe someone breaks it. Here you have the code script https://pastebin.com/jhg9p0Y2

Until you send us your full code, we can't help you.

**Comment by TPGamesNL** [comment]
Closing because OP didn't repond and I can't replicate this
