### ISSUE TITLE
Chat Format messes with replacement in future lines.

### ISSUE THREAD

**Issue by Mastriel** [SkriptLang/Skript#2734]
Description: Placing a `replace all %text% in message with %text%` in an `on chat:` event after a `on chat:` event which contains a `set chat format` effect, the replacement will not work.

1. Have a skript with 2 chat events, one above the other, containing a `set chat format to "%text%"`
2. Have the lower chat event replace all of any word in the message with anything
3. Watch

The text should be replaced, but it isn't. The message stays the same as if the second chat event never executed (although using debugging methods, you can see it has).

No errors are produced.

* **Server version/platform:**       PaperSpigot 1.14.4, ver 237
* **Skript version:**               Skript 2.4

**Comment by APickledWalrus** [comment]
Unless I’m misunderstanding what you’re saying, changing the message only changes it for that instance of the event as far as I’m aware, so it makes sense that it wouldn’t be changed in the other event.

**Comment by nopeless** [comment]
@APickledWalrus but its counter intuitive :/
I suggest to change this behavior so it stores the message and puts it into chat format properly.
I understand that the concept of 2 events is not practical tho

**Comment by ShaneBeee** [comment]
I vote no on this, because, as you said:
> I understand that the concept of 2 events is not practical tho

You are right, it is impractical, you should just use 1 event.

**Comment by bensku** [comment]
Sounds like issue with how Spigot (or Minecraft) treats chat format, but it wouldn't be first time we emulate broken functionality in Skript.

**Comment by Pikachu920** [comment]
this is definitely an issue with your code. you should be using `[message]` not `%message%` if you want the message after all events and not during the current event. that's in the docs i believe
