### ISSUE TITLE
on break part data of event-block

### ISSUE THREAD

**Issue by zidlsl** [SkriptLang/Skript#2736]
```vb
on right click:
    broadcast "%data of event-block%" -> 0
```

 wheat's data is 7 but send 0

### Server Information
* **Server version/platform:**        1.12.2
* **Skript version:**                 2.4

**Comment by ShaneBeee** [comment]
As per the docs for [**Data Value**](http://skriptlang.github.io/Skript/expressions.html#ExprDurability) as seen here:
```
[the] ((data|damage)[s] [value[s]]|durabilit(y|ies)) of %item stacks/slots%
%item stacks/slots%'[s] ((data|damage)[s] [value[s]]|durabilit(y|ies))
```
This expression is for item stacks and slots, not blocks. I'll be honest, I'm not even sure why its sending 0, it should be sending an error.

**Comment by Wealthyturtle** [comment]
Will try fixing this issue in #2510.

**Comment by Wealthyturtle** [comment]
Edit: Too complex, will solve in another PR.

**Comment by TheLimeGlass** [comment]
The issue is event-block and event-item not returning.
