### ISSUE TITLE
Colored dust error, but parses successfully

### ISSUE THREAD

**Issue by JaydenJinx** [SkriptLang/Skript#2740]
Minecraft Version: 1.15.1 (Spigot)
Skript Version:  2.4.1

On a fresh server, Skript only (no addons), this simple code **parses correctly**, but does not function. It produces **one error on load**, but no error when "/test" is run. When "/test" is run, nothing happens.

Error: https://pastebin.com/sLZcuG3t
Code: https://pastebin.com/gKsyiCaD

**Comment by Wealthyturtle** [comment]
https://github.com/SkriptLang/Skript/blob/cccd71c2f69bcc11d2350944db303f9b98c18478/src/main/java/ch/njol/skript/util/VisualEffect.java#L420

The error is coming from Line 420 *lol*.

**Comment by JaydenJinx** [comment]
;) ;)

Doesn't work with other colors by the way. "red", "blue", and "green" all raise the same issue.

**Comment by nopeless** [comment]
so, its a bug right?
I don’t understand why the label is needs testing

**Comment by Wealthyturtle** [comment]
It needs testing to ascertain the scope of the issue.

**Comment by Govindass** [comment]
I am having the same problem

**Comment by BurntValentine** [comment]
I have this issue also - this seems to apply to other colour-able particles like potion swirl as well

For example `play red potion swirl at projectile` and without colour `play potion swirl at projectile` fails, but a non-colour-able particle (for example `play flame at projectile`) works fine
