### ISSUE TITLE
Sign more colors than limit text

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2742]
I have a suggestion. Add "set 1st letter of clicked sign to colored red in line 4". It should set the color of 1 letter. As I saw in Minecraft is limit of text so "&xT&xe&xx&xt" contains 2x more letters than this word and the suggestion should replace color of letter when player write max text and cannot add colors.

**Comment by Wealthyturtle** [comment]
You do know that color or other format codes used in Minecraft occupy additional characters, right?

If you set a text to "test", the length will be 4 characters visually and 4 characters internally
If you set a text to "&etest", the length will be 4 characters visually **but it will still be 6 characters internally** - 4 characters from "test" + 2 characters from "§" and "e" internally.

This is standard Minecraft behavior and Skript can't do anything to change that - Skript can neither shrink the internal length of colored text, nor can Skript increase the max character length of each line on a sign.

**Comment by Misio12320** [comment]
Excuse me what? 

> If you set a text to "&etest", the length will be 4 characters visually **but it will still be 6 characters internally** - 4 characters from "test" + 2 characters from "§" and "e" internally.

This is true but I suggested to Skript replace clear "T" with "&eT" without adding to the line by just replacing it and coloring only this one because normal its "text"

**Comment by Misio12320** [comment]
@Wealthyturtle can you answer or @ShaneBeee explain me?
