### ISSUE TITLE
Deleting variables are not registered instantly.

### ISSUE THREAD

**Issue by madebygood** [SkriptLang/Skript#2743]
Deleting variables are not registered instantly. I have a chat games Skript that asks players simple questions like what's 5+5, and if their message matches the answer variable it deletes the answer variable so that no one else can answer it. In theory it should not allow more than 1 person to answer because the variable is deleted as soon as someone answers it correctly, and I had been running this code for months before the update without issue. However after the update I constantly saw 2-3 players getting a prize from the chat games meaning that the answer variable was not being deleted fast enough. I am sure this is related to the variable storage issue so I thought I would add it here instead of opening a brand new issue. I patched my chat games by adding a time variable when something is answered but clearly there is a minor issue here related to the updates.

The problem also occurs in command events, death, and world change events.

**Comment by ShaneBeee** [comment]
We're going to need more info here. This is why we have an issues template.
So rather than deleting it, could you please fill in the template so we can properly triage the issue.

**Comment by Wealthyturtle** [comment]
Isn't the chat event possibly asynchronous?
