### ISSUE TITLE
Deleting variables are not registered instantly.

### ISSUE THREAD

**Issue by madebygood** [SkriptLang/Skript#2744]
### Description
Deleting variables are not registered instantly. I have a chat games Skript that asks players simple questions like what's 5+5, and if their message matches the answer variable it deletes the answer variable so that no one else can answer it. In theory it should not allow more than 1 person to answer because the variable is deleted as soon as someone answers it correctly, and I had been running this code for months before the update without issue. However after the update I constantly saw many players getting a prize from the chat games meaning that the answer variable was not being deleted fast enough. I am sure this is related to the variable storage issue so I thought I would add it here instead of opening a brand new issue. I patched my chat games by adding a time variable when something is answered but clearly there is a minor issue here related to the updates.

The problem also occurs in command events, death, and world change events.

This error does not always occur.
But it happens very often.

### Steps to Reproduce
1) A simple quiz is broadcast.
2) Save the correct answer to {quiz.answer}
2) Receive user input with '/answer [arg]' command.
3) If arg matches {quiz.answer}, delete the variable and pay the prize to the correct user.
4) if {quiz.answer} is not set, users should not be able to enter the correct answer.
5) However, many users can enter additional correct answers here.

This issue does not only occur in the above skript. Many other skripts are also experiencing problems that do not immediately delete the variable.

### Expected Behavior
delete {variable} must run immediately.

### Errors / Screenshots
![cap](https://user-images.githubusercontent.com/43653581/71761237-f7fe3800-2f0b-11ea-8116-ed55dc27af61.JPG)

### Server Information
1.12.2
Skript 2.4.1
Paper Bukkit

**Comment by ShaneBeee** [comment]
Can you send the code that is causing issue?

I tried to replicate with a tester and I can not replicate this issue.

**Comment by madebygood** [comment]
`command /contest [<int>] [<text>]:
	trigger:
		if arg 1 or arg 2 is not set:
			message "&3  ★  /contest [prize money] [sentence] &7:: &fA typing contest will be held with the sentence."
			message "   └  The winner will be awarded a prize."
			exit
		else:
			if {type.contest} is set:
				message "&c  ★  &7The battering contest is currently underway."
				exit
			if arg 1 < 25000:
				message "&c  ★  &7Minimum Prize Money : &e&o25,000B"
				exit
			if arg 1 > 500000:
				message "&c  ★  &7Maximum Prize Money : &e&o500,000B"
				exit
			if arg 1 >= player's money:
				message "&c  ★  &7Money is scarce."
				exit
			if arg 2's length >= 50:
				message "&c  ★  &7Maximum character: 50"
				exit
				
			if {t.cool} is not set:
				set {t.cool} to now
			set {_tnow} to difference between {t.cool} and now
			if {_tnow} < 60 seconds:
				set {_ttext} to "%difference between 60 seconds and {_tnow}%"
				replace all " seconds" with "" in {_ttext}
				replace all " second" with "" in {_ttext}
				message "&c  ★  &rHost cooldown : &3%{_ttext}%sec"
				exit
						
			set {tajabar} to skellett new bossbar
			add arg 1 to {typecontest.hos.%player%}
			remove arg 1 from player's money
			set {type.contest} to now
			add 2 second to {type.contest}
			set {type.host} to player
			set {type.prize} to arg 1
			set {typesentence.now} to arg 2
			broadcast "&a  ★  &f&oLet's start the battering contest! Enter the sentence at the top of the screen."
			broadcast "&a  ★  &3Host&f : %{type.host}% &f |  &3Prize&f : %{type.prize}%B"
			
			wait 2 seconds
			while {type.contest} is set:
				add 1 to {type.record}
				set skellett title of bossbar {tajabar} to "&f/answer %{typesentence.now}%"
				set skellett color of bossbar {tajabar} to white
				loop all players:
					skellett add loop-player to bossbar {tajabar}
				set progress of bossbar {tajabar} to {type.record}/160
				show actionbar "&d/type %{typesentence.now}%" to all players
				if {type.record} == 60 or 120:
					broadcast "&a  ★  &f&oThe typing contest is in progress."
					broadcast "&a  ★  &3Host&f : %{type.host}% &f |  &3Prize&f : %{type.prize}%B"
				if {type.record} == 160:
					skellett remove all player bossbar {tajabar}
					add {type.prize} to {math.type}
					set {type.contest} to 0
					set {type.record} to 0
					set {type.prize} to 0
					delete {tajabar}
					delete {type.host}
					delete {typesentence.now}
					delete {type.contest}
					set {t.cool} to now
				wait 1 seconds
			
command /typecontestcancel:
	trigger:
		if {type.contest} is set:
			if player has permission "staff.staff":
				broadcast "&a  ★  &3staff %player% stop contest."
				skellett remove all player bossbar {tajabar}
				add {type.prize} to {math.type}
				set {type.contest} to 0
				set {type.record} to 0
				set {type.prize} to 0
				delete {type.host}
				delete {tajabar}
				delete {typesentence.now}
				delete {type.contest}
				set {t.cool} to now
						
			
command /answer [<text>]:
	trigger:
		if {type.contest} is set:
			if {type.host} is player:
				message "&c  ★  &7You are not allowed to participate in your contest."
				exit
			if arg 1 is {typesentence.now}:
				add 1 to {typecontestwin.%player's uuid%}
				set {_text} to "&a  ★  &f%player%&7(%{typecontestwin.%player's uuid%}% win)&f was the fastest. &aTime taken: %difference between {type.contest} and now%"
				delete {type.host}
				delete {typesentence.now}
				delete {type.contest}
				set {t.cool} to now
				broadcast "%{_text}%"
				execute console command "tm message %player% &r\n&aCongratulations! %{type.prize}%B+"
				skellett remove all player bossbar {tajabar}
				add {type.prize}-{type.prize}/8 to player's money
				add {type.prize}/8 to {math.type}
				set {type.record} to 0
				set {type.prize} to 0
			else:
				message "&c  ★  &7wrong!"
		else:
			message "&c  ★  &7I'm a step behind..."
		`

**Comment by madebygood** [comment]
[typecontest.zip](https://github.com/SkriptLang/Skript/files/4021645/typecontest.zip)

**Comment by madebygood** [comment]
> Can you send the code that is causing issue?
> 
> I tried to replicate with a tester and I can not replicate this issue.
> 
> This is my tester code (use a fake way to run the same command, 20 times, all within the same tick)
> 
> ```vbnet
> command /test:
>     trigger:
>         set {var} to 1
>         wait 5 ticks
>         loop 20 times:
>             execute sender command "/a 1"
> 
> command /a <number>:
>     trigger:
>         if {var} is set:
>             if arg-1 = {var}:
>                 send "&aYOU WON - TIME: &7%now%"
>                 delete {var}
>             else:
>                 send "&cNOPE TRY AGAIN - TIME: &7%now%"
>         else:
>             send "&5NO QUIZ!! - TIME: &7%now%"
> ```
> 
> Outcome:
> <img alt="Screen Shot 2020-01-03 at 11 15 53 PM" width="590" src="https://user-images.githubusercontent.com/20008482/71761377-03575200-2e7f-11ea-9c17-6c6b6119ca07.png">

**Comment by ShaneBeee** [comment]
I did a slight modification to allow myself to run the code, using this code:
```vb
command /test1:
    trigger:
        loop 20 times:
            execute player command "/answer test"
            wait 2 tick
```
I set the answer to "test" btw. Anyways, I rank that, and this was the outcome:
<img width="966" alt="Screen Shot 2020-01-03 at 11 47 49 PM" src="https://user-images.githubusercontent.com/20008482/71762390-79f64e80-2e83-11ea-860d-c7a1ee57f18e.png">
as you can see, it allowed me to answer once, and then the competition was over.

Needless to say, I can not replicate this issue. My guess is you have a conflicting plugin/addon of some sorts that is delaying the variables. Either that or your variable file is exceptionally large and Skript is having issues loading/modifying the variables.

**Comment by madebygood** [comment]
> I did a slight modification to allow myself to run the code, using this code:
> 
> ```vbnet
> command /test1:
>     trigger:
>         loop 20 times:
>             execute player command "/answer test"
> ```
> 
> I set the answer to "test" btw. Anyways, I rank that, and this was the outcome:
> <img alt="Screen Shot 2020-01-03 at 11 47 49 PM" width="966" src="https://user-images.githubusercontent.com/20008482/71762390-79f64e80-2e83-11ea-860d-c7a1ee57f18e.png">
> as you can see, it allowed me to answer once, and then the competition was over.
> 
> Needless to say, I can not replicate this issue. My guess is you have a conflicting plugin/addon of some sorts that is delaying the variables. Either that or your variable file is exceptionally large and Skript is having issues loading/modifying the variables.

It is true that the variable file is very large.
The variables.csv file on my server is 300mb.
Is this causing problems?

**Comment by ShaneBeee** [comment]
Most definitely yes. I believe SnowPyon told me at one point it shouldn't be any larger than 20MB

**Comment by madebygood** [comment]
> 가장 그렇습니다. SnowPyon이 한 시점에서 20MB보다 크면 안된다고 말했습니다.

Thank you very much for telling me the cause.

Is there a revolutionary way to reduce the size of a variable?

**Comment by ShaneBeee** [comment]
Yes, write more efficient code. 
Its evident you are saving way WAY too many variables.

Im closing this issue and marking it as invalid since this is not a Skript issue, but a server performance, user issue.

**Comment by madebygood** [comment]
> 보다 효율적인 코드를 작성하십시오.
> 너무 많은 변수를 저장하는 것이 분명합니다.
> 
> Skript 문제가 아니라 서버 성능, 사용자 문제이므로이 문제를 종료하고 유효하지 않은 것으로 표시했습니다.

All right, I want the skript to be updated to work normally even with large variables.

**Comment by Govindass** [comment]
> > 보다 효율적인 코드를 작성하십시오.
> > 너무 많은 변수를 저장하는 것이 분명합니다.
> > Skript 문제가 아니라 서버 성능, 사용자 문제이므로이 문제를 종료하고 유효하지 않은 것으로 표시했습니다.
> 
> All right, I hope the skript to be updated to work normally even with large variables.

you could make multiple .csv databases for different kind of things, but I have heard that it works right even with multiple gigabytes, but haven't had the chance to test that myself, my variables.csv is 12mb.
