### ISSUE TITLE
Startup Problem

### ISSUE THREAD

**Issue by Max0fficial** [SkriptLang/Skript#2746]
### Description
Skript plugin won't start, even though everything has been updated to the latest version

### Errors / Screenshots
Error code -> https://pastebin.com/G3cuiVTv

### Server Information
* **Server version/platform:**       Paper Spigot version git-Paper-33 (MC: 1.15.1)
* **Skript version:**                Skript v2.4.1

**Comment by APickledWalrus** [comment]
It looks like one of your scripts has a line that is too long for the parser to read. Try shortening some of your lines or increasing your stack size.

**Comment by Wealthyturtle** [comment]
Duplicate of #1117, as APickledWalrus stated, try shortening extremely long lines in scripts (or use brackets)

**Comment by Max0fficial** [comment]
> Duplicate of #1117, as APickledWalrus stated, try shortening extremely long lines in scripts (or use brackets)

currently I don't have any scripts uploaded (skripts folder is empty)

**Comment by ShaneBeee** [comment]
Do you have any Skript addons installed?
I have seen a couple people with this error now, I believe its addon related, but I don't know which addon.

**Comment by Max0fficial** [comment]
I don't have any addons installed
it's weird :|
