### ISSUE TITLE
Ability to loop files in folder

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2749]
Good morning gamers. Can you add "Loop files in folder "":"? And add expression %all files in ""%.

**Comment by Moderocky** [comment]
Skript does not contain any file-handling syntax. There are file-based addons that contain this expression and similar things. If you need file syntax then you should download one of those. If you'd like this expression to be added to one of those add-ons, then you should suggest it to the addon developer, not on the Skript GitHub.
