### ISSUE TITLE
Alias conflict with the potion expression

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#275]
If file is missing, it should be regenerated. Instead:
`[07:44:05] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev22e
[07:44:06] [Server thread/ERROR]: [Skript] Could not find the english aliases file aliases-english.sk
[07:44:06] [Server thread/ERROR]: [Skript] Could not load the english aliases config: plugins/Skript/aliases-english.sk (No such file or directory)`

**Comment by SlimeDog** [comment]
and:
`[07:45:55] [Server thread/WARN]: [Skript] There are no aliases defined for the following ids: 438, 441`
although they are defined in aliases-english.sk
`...
        dragon breath = 437
        splash potion = 438
        spectral arrow = 439
        tipped arrow = 440
        lingering potion = 441
        shield = 442
...`
but perhaps incorrectly?

**Comment by bensku** [comment]
Hmm, first one is troubling. Second one seems to be something @tim740 might want to take look. Might be Skript bug, though...

**Comment by SlimeDog** [comment]
Since the aliases-*.sk isn't regenerated if missing, is the default content documented somewhere?

**Comment by TheBentoBox** [comment]
It's open source, you're commenting on the repository right now. Just [find the aliases file in the repository](https://github.com/bensku/Skript/blob/master/src/main/resources/aliases-english.sk), it will always be the most up to date default aliases file.

**Comment by SlimeDog** [comment]
I know how to find it. That wasn't the issue I raised. It's pretty standard to replace a missing configuration file. But no worries.

**Comment by TheBentoBox** [comment]
@bensku , I'm still experiencing this issue with the very latest aliases, I believe it's a Skript bug which is possibly due to the way potions are parsed now as of 1.9. The two aliases that never seem to register even when they're properly defined are for 438 and 441, which are splash potion and lingering potion, respectively.

**Comment by SlimeDog** [comment]
Skript 2.2-dev22g:
[09:21:48] [Server thread/WARN]: [Skript] There are no aliases defined for the following ids: 438, 441, 452

**Comment by SlimeDog** [comment]
Skript 2.2-dev25

452 is parsed correctly now
>         iron(_| )nugget¦s = 452

438 and 441 are still not parsed
> [08:49:59] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev25
[08:50:00] [Server thread/INFO]: [Skript] Loaded a total of 20487 english aliases
[08:50:00] [Server thread/WARN]: [Skript] There are no aliases defined for the following ids: 438, 441

even though they exist in the aliases file
>         splash(_| )potion¦s = 438
>         lingering(_| )potion¦s = 441

**Comment by Snow-Pyon** [comment]
This was fixed on one of the latest update of Tim's aliases as far I can tell.

**Comment by SlimeDog** [comment]
Indeed. Thanks Tim.

**Comment by bensku** [comment]
... by removing said aliases entirely, which is NOT a good fix.

**Comment by SlimeDog** [comment]
Yikes!

**Comment by TheBentoBox** [comment]
I can definitely confirm that it seems to be a conflict with the potion expressions. I added aliases for 438 and 441 by renaming them from the default `splash(_| )potion¦s` and `lingering(_| )potion¦s` to `splash(_| )pot¦s` and `lingering(_| )pot¦s`. Works fine now. A possible solution is reworking the syntax of the potion expression or of `%potioneffecttype%` to not allow for potions without types, or to just change the default aliases to include `item` (such as `splash(_| )potion(_| )item¦s`).
