### ISSUE TITLE
on experience spawn event

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#2751]
### Description

Each time you reload skript with the reload command, the on experience spawn event is stacked.

### Steps to Reproduce

`on experience spawn:`

`> broadcast "Spawn~"`

I reloaded five times and the message is printed five times when the event occurs. The more you reload, the more messages you get at once.

### Errors / Screenshots

https://drive.google.com/file/d/1nFUO576lBWkoYDIbjH6-DyZPcJlE9mG6/view?usp=sharing
### Server Information
* **Server version/platform:**        paper 1.15.1 build 31
* **Skript version:**                 v2.4.1

**Comment by Wealthyturtle** [comment]
I can confirm this issue. Seems very weird... and potentially dangerous.
