### ISSUE TITLE
'On chunk unload' (documentation)

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2753]
### Description

`Called when a chunk is unloaded due to not being near any player. Cancel the event to force the server to keep the chunk loaded and thus keep simulating the chunk (e.g. physics, plant growth, minecarts, etc. will keep working and won't freeze).`
 
This is the description of the event, the last sentence should be removed: the event is not cancellable.

### Errors / Screenshots

`[19:19:51 ERROR]: [Skript] An on chunk unload event cannot be cancelled (servertje.sk, line 92: cancel event')`

### Server Information
* **Server version/platform:**       Paper 1.15.1 (43)
* **Skript version:**                Skript 2.4.1 & Skript 2.5

**Comment by Wealthyturtle** [comment]
Oddly enough the ChunkUnloadEvent used to be cancellable in the past (see https://jd.andross.fr/spigot-1.9-R0.1-SNAPSHOT/javadoc/org/bukkit/event/world/ChunkUnloadEvent.html vs https://jd.andross.fr/spigot-1.14.4-R0.1-SNAPSHOT/javadoc/org/bukkit/event/world/ChunkUnloadEvent.html for an example)

**Comment by andrei923** [comment]
https://jd.andross.fr/spigot-1.14.4-R0.1-SNAPSHOT/javadoc/org/bukkit/World.html#setChunkForceLoaded-int-int-boolean- is used instead.
