### ISSUE TITLE
Remove from player's inventory bug

### ISSUE THREAD

**Issue by 0zelot** [SkriptLang/Skript#2756]
`remove 1 light gray dye of unbreaking 10 named "name" with lore "lore" and "lore2" from player's inventory`
When player has 1 plain light gray dye and light gray dye as I wrote above, it remove plain item.

Skript's version: 2.4

**Comment by ShaneBeee** [comment]
1) Can you please try update your Skript version (latest stable is 2.4.1, you can also test out alpha and see if this bug persists, 2.5-Alpha1)
2) Please fill in the template when creating issues rather than deleting it. We need more info than this.

**Comment by 0zelot** [comment]
This bug is also in 2.4.1
Server version: Paper 1.14.4
There were no errors in the console.

**Comment by iOshawott** [comment]
On 2.5-Alpha 1 I tried

if player have 3 sponge:
    remove 3 sponge from player's inventory

when sponge have any name - it will not be removed, but it triggers this if :|

**Comment by ShaneBeee** [comment]
Duplicate of #2714
