### ISSUE TITLE
damage-effect doesn't show damage

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2760]
### Description

When you use "damage entity by x hearts", you can't see the entity taking damage.

### Steps to Reproduce

1. Load this script:
```
on rightclick:
	damage event-entity by 2 hearts
```
2. Click on a mob; you'll see nothing. If you repeat clicking, the mob will die.

### Expected Behavior

In 2.4.1, you saw the mob was taking damage. So there's a little bug. :)
### Errors / Screenshots

N/A

### Server Information
* **Server version/platform:**      Paper 1.15.1 build 43
* **Skript version:**                2.5; it does work on 2.4.1

### Additional Context

I already opened an issue 'removing x from health', which is closed, and I understand why... and I've been told I should open another if this doesn't work either. So, here it is

**Comment by ShaneBeee** [comment]
This is do to WealthyTurtle changing the damage method in HealthUtils.
The change he applied was setting the health of the entity rather than damaging the entity. Due to that, the entity no longer takes damage.
This change will need to be reverted.

**Comment by ShaneBeee** [comment]
Fixed in 2.5-alpha2
