### ISSUE TITLE
EffReplace ClassCastException

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2763]
### Description
An internal error happen when something happens.

### Steps to Reproduce
executing command says internal error.
command xeze:
    trigger:
        replace all stone and dirt in player's inventory and player's top inventory with diamond

### Expected Behavior
Like the docs say the items should be replaced.

### Errors / Screenshots
https://pastebin.com/fFCnNKES + When player have more than 1 of stone and dirt the error does not occur and nothing happens.

### Server Information
* **Server version/platform:**      This server is running Paper version git-Paper-47 (MC: 1.15.1) 
* **Skript version:**                Skript version 2.5-alpha1

### Additional Context
Plugins (9): Citizens, Multiverse-Core, Skellett, Skent*, SkQuery, Skript, WorldBorder, WorldEdit, WorldGuard
Link to example: https://docs.skunity.com/syntax/search/replace

**Comment by Misio12320** [comment]
Tested without Skript addons: This same. Plugins (7): Multiverse-Core, PluginConstructorAPI, ServerRestorer, Skript, WorldBorder, WorldEdit, WorldGuard


[20:19:57 ERROR]: #!#!
>.... [20:19:57 ERROR]: #!#! [Skript] Severe Error:
>.... [20:19:57 ERROR]: #!#!
>.... [20:19:57 ERROR]: #!#! Something went horribly wrong with Skript.
>.... [20:19:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
>.... [20:19:57 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
>.... [20:19:57 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
>.... [20:19:57 ERROR]: #!#!
>.... [20:19:57 ERROR]: #!#! Stack trace:
>.... [20:19:57 ERROR]: #!#! java.lang.ClassCastException: ch.njol.skript.aliases.ItemType cannot be cast to org.bukkit.inventory.ItemStack
>.... [20:19:57 ERROR]: #!#! at ch.njol.skript.effects.EffReplace.execute(EffReplace.java:123)
>.... [20:19:57 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
>.... [20:19:57 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
>.... [20:19:57 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
>.... [20:19:57 ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
>.... [20:19:57 ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
>.... [20:19:57 ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
>.... [20:19:57 ERROR]: #!#! at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
>.... [20:19:57 ERROR]: #!#! at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
>.... [20:19:57 ERROR]: #!#! at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
>.... [20:19:57 ERROR]: #!#! at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [20:19:57 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [20:19:57 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1812)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014)
>.... [20:19:57 ERROR]: #!#! at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937)
>.... [20:19:57 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
>.... [20:19:57 ERROR]: #!#!
>.... [20:19:57 ERROR]: #!#! Version Information:
>.... [20:19:57 ERROR]: #!#! Skript: 2.5-alpha1 (latest)
>.... [20:19:57 ERROR]: #!#! Flavor: skriptlang-github
>.... [20:19:57 ERROR]: #!#! Date: 2020-01-11
>.... [20:19:57 ERROR]: #!#! Bukkit: 1.15.1-R0.1-SNAPSHOT
>.... [20:19:57 ERROR]: #!#! Minecraft: 1.15.1
>.... [20:19:57 ERROR]: #!#! Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
>.... [20:19:57 ERROR]: #!#! OS: Linux amd64 4.15.0-46-generic
>.... [20:19:57 ERROR]: #!#!
>.... [20:19:57 ERROR]: #!#! Server platform: Paper
>.... [20:19:57 ERROR]: #!#!
>.... [20:19:57 ERROR]: #!#! Current node: null
>.... [20:19:57 ERROR]: #!#! Current item: replace ([[itemtype:stone block]] and [[itemtype:dirt block]])[class ch.njol.skript.aliases.ItemType] in (inventory of the player and current inventory of the player)[interface org.bukkit.inventory.Inventory] with [[itemtype:diamond]](case sensitive: false)
>.... [20:19:57 ERROR]: #!#! Current trigger: command /xze (simple event) (test.sk, line -1)
>.... [20:19:57 ERROR]: #!#!
>.... [20:19:57 ERROR]: #!#! Thread: Server thread
>.... [20:19:57 ERROR]: #!#!
>.... [20:19:57 ERROR]: #!#! Language: english
>.... [20:19:57 ERROR]: #!#! Link parse mode: DISABLED
>.... [20:19:57 ERROR]: #!#!
>.... [20:19:57 ERROR]: #!#! End of Error.
>.... [20:19:57 ERROR]: #!#!

**Comment by ShaneBeee** [comment]
I think the issue here is that you are replacing items in the player's top inventory, but you haven't opened an inventory to the player, therefor there is no top inventory to replace items in.

**Comment by bensku** [comment]
Judging from the stack trace, this is probably fallout from #2510. I kind of expected that something like this might happen.

**Comment by Misio12320** [comment]
15 minutes lost for write. Fix the docs 

> Link to example: https://docs.skunity.com/syntax/search/replace

**Comment by ShaneBeee** [comment]
Fixed in 2.5-alpha2
