### ISSUE TITLE
What's up with "features.sk"?

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2769]
### Question
I've been playing around with features.sk just now, couldn't get it to deactivate anything nor to get some output out of it (as setting debug=true promises) to.

I took a random event, in this case the EvtFirework, and tried to disable. Nothing happens upon either reloading all of skript nor rebooting the server. Played around with the text in there quite a bit. Nothing.

Does it straight up not work?
And why are the comments in that file really no help at all? They sound like someone tried to explain what to do to somebody who already has a deep understanding of how Skript works internally - but in a rush.

Whatever the case, updating the file or removing it should be considered - because that was just time wasted.

**Comment by TheDGOfficial** [comment]
It's not used anymore, but maybe used in future. #2086

**Comment by jaylawl** [comment]
> 
> 
> It's not used currently, but maybe implemented in the future. #2086

Thank you. In that case the file is just non-functional garbage and should be deleted

**Comment by APickledWalrus** [comment]
I would say just to disable the creation of the file for now, as to not confuse people.

**Comment by Wealthyturtle** [comment]
Closing in favor of #2252

**Comment by TPGamesNL** [comment]
@Wealthyturtle Why was this closed? This issue is about the `features.sk` file, which is not related to the example script files.
