### ISSUE TITLE
Variable issue

### ISSUE THREAD

**Issue by babayoga101** [SkriptLang/Skript#2774]
### Description
When you set a location variable in a different world than the default one(in this case the default world is named "World"), and you go to the second world(in this case the default world is named "Spawn") and set a location variable per-say {spawn}, in the second world, then you restart the server the variable doesn't load, but if you do the exact same thing in the main world it does load on boot. The variable is also in variables.csv as 
```
core.server.loc.spawn, location, 8605776F726C6480FF0000000181046E616D65208005737061776E017809404FC000000000000179094052000000000000017A0940596000000000000570697463680800000000037961770800000000
``` 

### Steps to Reproduce
Here's an example script using Skellet for world management
```
on load:
	load world "Spawn" with generator "normal" with fawe async

command /gotoworld:
    trigger:
        teleport player to world "Spawn"

command /setspawn:
    trigger:
        set {core.server.loc.spawn} to player's location

command /spawn:
    trigger:
        teleport player to {core.server.loc.spawn}
```
do /gotoworld
then /setspawn
then /spawn
then restart the server
log back in and do /spawn
poof it doesn't work
### Expected Behavior
The variable will not load but is still in variables.csv

### Server Information
* **Server version/platform:** Spigot 1.12.2-R0.1-SNAPSHOT
* **Skript version:** 2.4.1

**Comment by ShaneBeee** [comment]
As discussed on discord, the issue here is Skript loads, variables load, then your script loads. At this point your world is loading, after your variables have already loaded. Skript won't load world variables if the world doesn't exist.
This seems more of an issue with the addon you are using to load the world.
