### ISSUE TITLE
regex thing error

### ISSUE THREAD

**Issue by Mr-Vuda** [SkriptLang/Skript#2780]
### Description
When I start/restart server, there is chance to show this error and skript dont load at all.

### Steps to Reproduce
-

### Expected Behavior
-

### Errors / Screenshots
https://paste.md-5.net/nadopocode.php and this just go in infinitive like that

### Server Information
* **Server version/platform:**       Paper 1.12.2
* **Skript version:**                2.4

### Additional Context
-

**Comment by Wealthyturtle** [comment]
Duplicate #2777, read my explanation there.

**Comment by Mr-Vuda** [comment]
What do you mean by " shortening lines in your scripts."?

**Comment by Wealthyturtle** [comment]
I mean, the StackOverflowError basically means the Skript parser was unable to fully parse your script because it was too complex. Typically that means you have chained too many expressions/whatever in a single line.

**Comment by Mr-Vuda** [comment]
But it load normaly sometimes :/ weird
