### ISSUE TITLE
Replace not working correctly.

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2790]
### Description
I wan't to let me the Skript replace something in code and broadcast text. Issue is this it does not work.

### Steps to Reproduce
write code:
```
command allFiles:
	trigger:
		set {_name::*} to all files from directory "Gods"
		if "%{_name::*}%" contains "a":
			replace all "A" in {_name::*} with "se"
			broadcast "%{_name::*}%"
```

### Expected Behavior
Should send replaced name of files. But it does not replace
code:
```
command allFiles:
	trigger:
		set {_name::*} to all files from directory "Gods"
		if "%{_name::*}%" contains "a":
			replace all "A" in {_name::*} with "se"
			broadcast "%{_name::*}%"
```

### Errors / Screenshots
![2020-01-23_21 34 18](https://user-images.githubusercontent.com/42146429/73021802-98b78780-3e28-11ea-9c83-052865a0f7dd.png)

Empty. Only brodcast so this is good.
### Server Information
* **Server version/platform:** This server is running Paper version git-Paper-70 (MC: 1.15.2)
* **Skript version:** Skript version 2.4.1  2.5pre1 too does not work.

### Additional Context
I think this issue is released to owner of Skent. But the owner says me its issue of Skript so I came here.

**Comment by Misio12320** [comment]
Affects Skript version 2.5-alpha1. Confirmed one more time with tests now because before tests I forgot.

**Comment by APickledWalrus** [comment]
Did this work before 2.5? If so, it could be an issue with the relave effect updates.

**Comment by Misio12320** [comment]
1. In 2.4.1 does not too.
2. I have wrote "%{_files::1}%" cannot be changed and can thus not have parts replaced. (worldrobert.sk, line 90: replace all "A" and "n" in "%{_files::1}%" with "S"')

**Comment by Wealthyturtle** [comment]
Duplicate #367

**Comment by Misio12320** [comment]
How duplicate? It does not contain send "THE %{}%"?? And the old one is from 3 years 😂😂

**Comment by Wealthyturtle** [comment]
My mistake, is not the elision issue. In any case, your code is wrong.

``set {_name::*} to all files from directory "Gods"``

Your name list contains the file type, and not the string type... Replace needs a string.

**Comment by Misio12320** [comment]
Still not working
```
command allFiles:
	trigger:
		set {_name::*} to all files from directory "Gods/"
		if "%{_name::*}%" contains "A":
			replace all "A" and "a" and "b" and "c" in {_name::*} with ""
			message "%{_name::*}%" to console
```
I'm confused.

**Comment by Wealthyturtle** [comment]
You did not solve the problem. The problem is that **your name list is not a string list**.

**Comment by Misio12320** [comment]
Why you don't send me the answer? It's skript not rl

**Comment by Misio12320** [comment]
How to fix it? I still does not know where is the issue. Why you don't write these 5 words fixing the issue?

**Comment by Wealthyturtle** [comment]
You need to calm down and listen to yourself. I have already told you the answer. The replace effect works on **strings** and your {_name::*} list is **not a string list**, it is a file list. I do not think that I need to give you any further “solution”, as:

1) This is your own implementation issue, irrelevant to Skript.
2) You are clearly using an addon outside of Skript - which this definitely not supported by us.
