### ISSUE TITLE
Max-function (bug/question)

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2796]
### Description

I'm not sure if I do it correctly (because that can be the problem), but I've some issues with the max-functions.
### Steps to Reproduce

Script:
```
command /test42:
	trigger:
		delete {test42::*}
		delete {test42i::*}
		add "Test1" to {test42::*}
		add "Test2" to {test42::*}
		add "Test3" to {test42::*}
		message "%{test42::*}%"
		message "%all indexes of {test42::*}%"
		loop {test42::*}:
			add loop-index to {test42i::*}
		message "%{test42i::*}%"
		message "%max({test42i::*})%"
```
Result:
```
[14:52:27 INFO]: Test1, Test2 and Test3
[14:52:27 INFO]: 1, 2 and 3
[14:52:27 INFO]: 1, 2 and 3
[14:52:27 INFO]: <none>
```
So I presume that loop-indexes aren't 'real' numbers??

### Expected Behavior

Instead of 'none', the result of the max-function should be 3, I guess?
### Errors / Screenshots

Afterwards, I got this error when I tried `message "%max(all indexes of {test42::*})%"`:

`[14:46:06 ERROR]: The 2nd argument given to the function 'max' is not of the required type number. Check the correct order of the arguments and put lists into parentheses if appropriate (e.g. 'give(player, (iron ore and gold ore))'). Please note that storing the value in a variable and then using that variable as parameter will suppress this error, but it still won't work. (test.sk, line 414: message "%max(all indexes of {test42::*})%"')`

### Server Information
* **Server version/platform:**       Paper 1.15.2
* **Skript version:**                Skript 2.5-alpha1

### Additional Context

I don't know much about functions, so it's possible that I made a mistake and all the text above is nonsense. :)

**Comment by Wealthyturtle** [comment]
Indexes are strings in Skript, that's why you can do stuff like {var::test} - not numbers.
