### ISSUE TITLE
The skriptTest Gradle task does not work on Windows

### ISSUE THREAD

**Issue by Olyno** [SkriptLang/Skript#2797]
### Description

``gradlew skriptTest`` command doesn't work on windows.

### Steps to Reproduce

Simply execute the command.

### Expected Behavior

Execute tests

### Informations
* **OS:**               Windows 10
* **StackTrace:**       https://hasteb.in/nefofuyu.kotlin
* **Java version:**     11.0.3
* **Gradle version:**   5.4

**Comment by bensku** [comment]
Could you post Gradle log with --info, would be interesting to see what the classpath for test platform is.

**Comment by Olyno** [comment]
Here is logs: https://hasteb.in/qopalaxi.sql

**Comment by bensku** [comment]
Java didn't like forward slashes in name of Skript jar. Please let me know if there are more issues running tests on Windows.

**Comment by Olyno** [comment]
Sorry for the really late answer, I still have the same issue, here are new logs: https://hasteb.in/ojusulog.gradle

**Comment by Nicofisi** [comment]
I have the same error as @Olyno on Windows 10 on 4563dcd5ba0ae2c84dbec3f0277c37a3082709ee

```
> Task :skriptTest FAILED
Error: Could not find or load main class ch.njol.skript.tests.platform.PlatformMain
Caused by: java.lang.ClassNotFoundException: ch.njol.skript.tests.platform.PlatformMain
```
