### ISSUE TITLE
block under player..?

### ISSUE THREAD

**Issue by Jware0704** [SkriptLang/Skript#2798]
on sneak toggle:
    if block under player is lime terracotta:
        execute player command "/mw goto Info"

i don't know how to fix..
Can you help me execute command when player is standing on lime terracotta?

**Comment by Wealthyturtle** [comment]
The GitHub Skript repository isn't the place to ask for help with individual scripts. Unless you have found a bug with the above script or something, you should ask for help on the Skript Chat Discord server and not here.
