### ISSUE TITLE
Function is deleted while it isn't

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#2802]
### Description

While reloading my skript it randomly appears something like this
https://oshawott.pl/ss/205b.png ( "The function 'money' was deleted or renamed (...)" )
but I haven't changed anything and the function is on it's place all the time. My friend said that he see it too

### Steps to Reproduce

Can't provide how to reproduce, sorry. I tried to do a code for it, but it failed. Maybe it depends on time (I tried only with short time)

### Expected Behavior

It shouldn't appear that a function is removed or renamed : d

### Errors / Screenshots

^like I said + no more errors

### Server Information
* **Server version/platform:**    Paper-84 1.15.2   
* **Skript version:**       2.5-alpha1

**Comment by ShaneBeee** [comment]
This usually happens when reloading scripts, especially if the function was moved.

**Comment by iOshawott** [comment]
> This usually happens when reloading scripts, especially if the function was moved.

It would be understandable, but the function stays at same place all the time (and throws a lot of errors...)
We don't touch it (function), just editing code in skript with function makes this happen o.O

**Comment by Govindass** [comment]
I have the same problem constantly, when reloading bigger scripts the whole chat gets spammed by those, while I haven't edited or moved the functions

**Comment by TPGamesNL** [comment]
I usually get this error when I use a function in an effect command (on 2.4.1)

**Comment by short509** [comment]
me too, please fix function reload error.

**Comment by jaylawl** [comment]
same, occuring very often, especially when re-loading specific script files only

**Comment by ShaneBeee** [comment]
Fixed in 2.5-alpha2
