### ISSUE TITLE
RootVehicle

### ISSUE THREAD

**Issue by Foxstone1** [SkriptLang/Skript#2804]
### Description

Requesting a feature that allows for Vehicles themselves to be targeted directly. 

In some regard this should be possible if its possible to recognize the "RootVehicle" data on rideable entities since this only appears while a player/entity is riding that vehicle. 

Adding this feature allows for the modification and manipulation of Horses, Mules, boats, etc. while the Rider is still riding.

**Comment by Wealthyturtle** [comment]
Doable - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#getPassenger--

**Comment by ShaneBeee** [comment]
Im very confused by this request

Skript has expressions for [**Vehicle of Entity**](http://skriptlang.github.io/Skript/expressions.html#ExprVehicle) as well as [**Passenger of Vehicle**](http://skriptlang.github.io/Skript/expressions.html#ExprPassenger)

**Comment by Wealthyturtle** [comment]
Looking at ExprPassenger and PassengerUtils, it seems that Skript is calling the ``getPassengers()`` function that pulls out all the passenger(s) that an entity has. Although, I'm not sure if the order is preserved, will need to test that.

**Comment by ShaneBeee** [comment]
that's how it works, the method you sent is deprecated:
`Deprecated. entities may have multiple passengers, use getPassengers()`

**Comment by Wealthyturtle** [comment]
Oops, my bad. It looks like the passenger expression only returns the entity directly above it, so chained passengers are not reported.
