### ISSUE TITLE
local variables cannot be declared to none

### ISSUE THREAD

**Issue by yhdev7935** [SkriptLang/Skript#2805]
### Description
`local variables` cannot be declared to none

### Steps to Reproduce

see the message below.

### Expected Behavior
see the message below.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/55119171/73661210-08592c80-46dd-11ea-80cf-bb43f466e178.png)

### Server Information
* **Server version/platform:**       1.10.2/PaperSpigot
* **Skript version:**                2.4.1

**Comment by bensku** [comment]
Seems to be working as intended, passing nothing will cause most expressions to do nothing.

**Comment by TheBentoBox** [comment]
This is working as intended. Local variables are local to the trigger, so once it gets set in the 2nd iteration of the loop it will hold that value within the trigger unless you set it to a new one or delete it. The bottom image is the correct course of action -- if you want a variable to have its value cleared, delete it.
