### ISSUE TITLE
Fix send name of vehicle and push

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2807]
### Description
I want to create when player enter a region with minecart: it should push him up with it but does not work..

### Steps to Reproduce
Write code
on enter region "wow":
    send name of player's vehicle
    push player's vehicle upwards with speed 5.0

### Expected Behavior
Should send name of player's vehicle but nothing happens.

### Errors / Screenshots
Nah

### Server Information
* **Server version/platform:**        This server is running Paper version git-Paper-90 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
* **Skript version:**                Skript version 2.5-alpha1

### Additional Context
Nah..

**Comment by Misio12320** [comment]
Okay this does not work too:
on rightclick:
    cancel event
    send name of clicked entity

**Comment by ShaneBeee** [comment]
Are you sure that event is even firing?

your code:
`on enter region "wow":`

event:
`(enter[ing]|leav(e|ing)|exit[ing]) [of] ([a] region|[[the] region] %regions%)`

this event calls for a region not a string. I'm almost certain your event is not firing the way you have written it.

**Comment by Misio12320** [comment]
> Okay this does not work too:
> on rightclick:
> cancel event
> send name of clicked entity

Why it does not send name, huh?



> Are you sure that event is even firing?
> 
> your code:
> `on enter region "wow":`
> 
> event:
> `(enter[ing]|leav(e|ing)|exit[ing]) [of] ([a] region|[[the] region] %regions%)`
> 
> this event calls for a region not a string. I'm almost certain your event is not firing the way you have written it.

I always write event on enter region "": and works fine. can't understand this event: 'on enter region wow' (Bum.sk, line 36: on enter region wow:')

**Comment by ShaneBeee** [comment]
> Why it does not send name, huh?

I believe you need to use `on right click on entity`

> I always write event on enter region "": and works fine. can't understand this event: 'on enter region wow' (Bum.sk, line 36: on enter region wow:')

I'm not sure then. Region support isn't the best within Skript. Debug your code and see if that event is even firing.

**Comment by Misio12320** [comment]
"Unfortonetly" works...
2.How to debug

**Comment by Misio12320** [comment]
Oh sh*me. The rightclick does not works
on right click on entity:
    send "%name of clicked entity%" to player
sends <none>. + send name of clicked entity to player : sends nothing :clap:

**Comment by iOshawott** [comment]
event-entity is not working, seems related to #2771
