### ISSUE TITLE
Can't change item amount in some cases

### ISSUE THREAD

**Issue by HAHAYOUDEAD** [SkriptLang/Skript#2816]
### Description
Can't modify item amount of tool of player (didn't test much else)

### Steps to Reproduce
```
on rightclick with coal:
    add 1 to item amount of tool of player
```
\> nothing happens

```
on rightclick with coal:
    set {_i} to coal
    add 5 to item amount of {_i}
    give {_i} to player
```
\> gives 6 coal
### Server Information
* **Server version/platform:**       Paper<i>#</i>98 1.15.2 
* **Skript version:**                2.5

### Additional Context
Can't remove from or set either
Worked with Skript 2.4.1 and was very useful

**Comment by Wealthyturtle** [comment]
Duplicate #2707
