### ISSUE TITLE
On Player World Change vs. On Join

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#2822]
### Question
I have code that needs to be triggered whenever a player enters a world, either when connecting to the server (and therefore entering a world) or when explicitly changing worlds. It appears that
- **on player world change**

is not fired on connection to the server (and therefore entry into a world). I appreciate that 
- **on join**

is fired when the player connects to the server (and enters a world, ie, after **on connect**), but if my test results are true, then I need to duplicate the code in both events. Please advise.

**Comment by ShaneBeee** [comment]
Those are true. 
You could use a function, so fire said function in both events, ex:
```vb
function something(p: player):
    do stuff for {_p}

on join:
    something(player)

on world change:
    something(player)
```

**Comment by SlimeDog** [comment]
That's exactly what I do. Thanks.
