### ISSUE TITLE
Clear inventory of player while the player is in a variable does not work.

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#2823]
### Server Information
* **Server version/platform:**  Paper 1.12.2
* **Skript version:** 2.4

using:

set {p} to player
clear inventory of {p}

does nothing, does not clear inventory, but using:
clear inventory of "%{p}%" parsed as a player

clears it.

**Comment by Govindass** [comment]
seems to be related to https://github.com/SkriptLang/Skript/issues/2708 btw

**Comment by ShaneBeee** [comment]
I just tested this on 2.5-alpha2 .... appears to be fixed :)
