### ISSUE TITLE
Removing item from player's inventory only removes vanilla items.

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2825]
### Description

The syntax `remove all %itemstack% from %players%'s inventory` is a little broken. It will only work on vanilla item stacks, unless there is a syntax I am missing, which is stupid.
### Steps to Reproduce

![image](https://user-images.githubusercontent.com/49515406/75012886-f0104c80-54e7-11ea-8a8c-44a944135afb.png)
Write the above code into a script, reload it, and rejoin the server. Normal bows will be removed from your inventory, however, custom bows won't.
### Expected Behavior

The script should take away any bow in your inventory, however it only takes Vanilla bows.### Errors / Screenshots
![image](https://user-images.githubusercontent.com/49515406/75013065-4f6e5c80-54e8-11ea-9b52-5a92685ea5c9.png)

No errors, however, I did mark the events in chat.

### Server Information
* **Server version/platform:**  paper something     
* **Skript version:**          2.4

**Comment by ShaneBeee** [comment]
> Skript version: 2.4

seems you're a couple versions behind. Please at least try on an updated version, such as 2.5-alpha1

**Comment by Jayderp** [comment]
ok

**Comment by Jayderp** [comment]
![image](https://user-images.githubusercontent.com/49515406/75013269-c4419680-54e8-11ea-813b-1691fa966443.png)
holy crap outdated

**Comment by Jayderp** [comment]
@ShaneBeee 
![image](https://user-images.githubusercontent.com/49515406/75013358-f8b55280-54e8-11ea-97bc-ff5aa823011e.png)

**Comment by Jayderp** [comment]
![image](https://user-images.githubusercontent.com/49515406/75013377-066ad800-54e9-11ea-94d7-02dece570f34.png)

**Comment by Jayderp** [comment]
shanea[s'
h
seahs
SHANEBEEEEEEEEEEe
sahen
shane hsane shane

ok so there's nothing between 2.5-alpha420 and 2.4 that fixes itemstack syntaxes so yeah

**Comment by ShaneBeee** [comment]
I'm locking and closing this issue as you can't seem to be mature enough to properly report an issue!
