### ISSUE TITLE
SHAAAAAANEBEEEEEEEEEE HEEEEEEEEEEELLLLLLLLLP

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2826]
PLS FIX THE `REMOVE ALL %ITEMSTACK% FROM %PLAYERS% INVENTORY` SYNTAX IT ONLY WORKS ON VANILLA ITEMS PLS SHANE!!!!!!!!
PLS FIX THE `REMOVE ALL %ITEMSTACK% FROM %PLAYERS% INVENTORY` SYNTAX IT ONLY WORKS ON VANILLA ITEMS PLS SHANE!!!!!!!!
PLS FIX THE `REMOVE ALL %ITEMSTACK% FROM %PLAYERS% INVENTORY` SYNTAX IT ONLY WORKS ON VANILLA ITEMS PLS SHANE!!!!!!!!
PLS FIX THE `REMOVE ALL %ITEMSTACK% FROM %PLAYERS% INVENTORY` SYNTAX IT ONLY WORKS ON VANILLA ITEMS PLS SHANE!!!!!!!!

**Comment by Jayderp** [comment]
I LIKE MTN DEW

**Comment by ShaneBeee** [comment]
Please stop. This is an official last warning!
