### ISSUE TITLE
Skript v2.1.2 java.lang.StackOverflowError

### ISSUE THREAD

**Issue by Hite29** [SkriptLang/Skript#2831]
### Description
Error when server are loading and in /sk reload all

### Errors / Screenshots
https://hastebin.com/sonilusala.bash

https://gist.github.com/Hite29/e3bb20202574b281104d05a3de01ae83

### Server Information
Paperspigot 1.8.8
Skript v2.1.2

**Comment by ShaneBeee** [comment]
That version is not from us.
It was also abandoned 5 years ago.
