### ISSUE TITLE
Make look

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2833]
Hello. Can you add option like "make %entities% look at %entity/player%" for x seconds?

**Comment by Vrganj** [comment]
That's a pretty simple script to make. There's no need for that.

**Comment by Misio12320** [comment]
Suggestion = better Skript <3

**Comment by Vrganj** [comment]
It's the job of an addon to add things like these. Skript only does what it needs to do.

**Comment by TheLimeGlass** [comment]
Requires reflection, and Skript doesn't handle reflection, you will have to calculate vectors yourself.
