### ISSUE TITLE
Skript 2.5: Skript throws error when attempting to repair item

### ISSUE THREAD

**Issue by staridiot** [SkriptLang/Skript#2839]
### Description
Repairing an item of any type in any slot of a player will throw an error.

### Steps to Reproduce
```
command /rep:
	trigger:
		repair held item of player
```
### Error
https://pastebin.com/u7F4iJX7

### Server Information
* **Server version/platform:**  1.15.2 / Paper 112
* **Skript version:** 2.5-alpha1 (not present on 2.4.1)

**Comment by bensku** [comment]
Probably #2755 duplicate, but needs to be tested.

**Comment by ShaneBeee** [comment]
This issue has been fixed in bensku's PR
Fix damaging items #2836
