### ISSUE TITLE
loop players/entities does not work in command blocks

### ISSUE THREAD

**Issue by AlphaWai** [SkriptLang/Skript#2847]
### Description

Expressions like "loop players" or "loop entities" under a skript command does not work in command blocks.
The action under the loop did not work as expected, while it works if executed as a player.
### Steps to Reproduce

```
command /test:
   trigger:
       broadcast "1"
       loop all entities in radius 5 around command sender:
           broadcast "%loop-entity%"
           if "%loop-entity%" is "minecart":
               set {_nbt} to nbt of loop-entity
               broadcast "Minecart's NBT is %{_nbt}%."
```
### Expected Behavior

When a command block with "/test" in it is activated, it should broadcast "1" then look for entities around the command block, then broadcast the name of the loop-entity. If the entity is a minecart, then broadcasts its NBT.

### Errors / Screenshots

When the command is executed by a player, it works as expected, which broadcast everything.
When the command is executed by cmd block with a minecart nearby, only "1" is broadcasted and didn't enter the loop.

### Server Information
* **Server version/platform:**  1.12.2    
* **Skript version:**    2.4.1            

### Additional Context

```
command /track:
	trigger:
		loop players in radius 5 around command sender:
			if loop-player's vehicle is minecart:
				make loop-player execute command "/test"
				if {express.%loop-player%} is true:
					delete {express.%loop-player%}
					broadcast "Express Train is found"
 command /test:
	trigger:
		loop all entities in radius 5 around player:
			broadcast "%loop-entity%"
			if "%loop-entity%" is "minecart":
				set {_nbt} to nbt of loop-entity
				if {_nbt} contains "Express":
					set {express.%player%} to true
```
I retried with the code above, with "/track" command in a command block, and nothing happens after the cmd block is activated.  So "loop players" is also not working for cmd block.

**Comment by Nicofisi** [comment]
Does `broadcast "%chunk at command sender%"` work?

**Comment by Wealthyturtle** [comment]
If the command sender is a command block, its location can be retrieved by using %block's location%.

**Comment by AlphaWai** [comment]
> If the command sender is a command block, its location can be retrieved by using %block's location%. This is done so that skripters can differentiate between a player versus a command block executing the command, and add special handling for command blocks.

Okay I just retried with the code below:
```
command /test:
	trigger:
		set {_loc} to location of command sender
		broadcast "%{_loc}%"
		loop all entities in radius 5 around {_loc}:
			broadcast "%loop-entity%"
			if "%loop-entity%" is "minecart":
				set {_nbt} to nbt of loop-entity
				if {_nbt} contains "Express":
					broadcast "Express Train Found"
```
When the command is run by a player, the message of "broadcast '%{_loc}%'" is the coordinates of my location.
When the command is run by a command block, the message is "<none>", which means the skript didn't get the location of the command block in the first sentence.
So what's wrong with it?

**Comment by AlphaWai** [comment]
> Does `broadcast "%chunk at command sender%"` work?
It works for a player, but it display "<none>" in a command block.

> By the way is there an `event-location` in this event (=in commands)? If so, does this work if used instead?
I'm not sure if commands can use this expression.

**Comment by Wealthyturtle** [comment]
Use Skript 2.5-beta1 minimum for this feature.

> > If the command sender is a command block, its location can be retrieved by using %block's location%. This is done so that skripters can differentiate between a player versus a command block executing the command, and add special handling for command blocks.
> 
> Okay I just retried with the code below:
> 
> ```
> command /test:
> 	trigger:
> 		set {_loc} to location of command sender
> 		broadcast "%{_loc}%"
> 		loop all entities in radius 5 around {_loc}:
> 			broadcast "%loop-entity%"
> 			if "%loop-entity%" is "minecart":
> 				set {_nbt} to nbt of loop-entity
> 				if {_nbt} contains "Express":
> 					broadcast "Express Train Found"
> ```
> 
> When the command is run by a player, the message of `broadcast "%{_loc}%"` is the coordinates of my location.
> When the command is run by a command block, the message is `<none>` , which means the skript didn't get the location of the command block in the first sentence.
> So what's wrong with it?

**Comment by AlphaWai** [comment]
> Use Skript 2.5-alpha1 minimum for this feature.

I just retried with 2.5-alpha2, the result is the same.

**Comment by Nicofisi** [comment]
> > If the command sender is a command block, its location can be retrieved by using %block's location%. This is done so that skripters can differentiate between a player versus a command block executing the command, and add special handling for command blocks.
> 
> Okay I just retried with the code below:
> 
> ```
> command /test:
> 	trigger:
> 		set {_loc} to location of command sender
> 		broadcast "%{_loc}%"
> 		loop all entities in radius 5 around {_loc}:
> 			broadcast "%loop-entity%"
> 			if "%loop-entity%" is "minecart":
> 				set {_nbt} to nbt of loop-entity
> 				if {_nbt} contains "Express":
> 					broadcast "Express Train Found"
> ```
> 
> When the command is run by a player, the message of `broadcast "%{_loc}%"` is the coordinates of my location.
> When the command is run by a command block, the message is `<none>` , which means the skript didn't get the location of the command block in the first sentence.
> So what's wrong with it?

@Wealthyturtle said `block's location`, not `location of command sender` though.

**Comment by AlphaWai** [comment]
> @Wealthyturtle said `block's location`, not `location of command sender` though.

Thanks, problem solved.
