### ISSUE TITLE
Command not recognised.

### ISSUE THREAD

**Issue by Saalty** [SkriptLang/Skript#2854]
I know it said not to do scripting problems but it happens with every script: my own, other peoples etc. My server is outdated but I really dont know why this problem is happening but when I used the original skript from spigot the commands worked fine but there was errors with code so I had to upgrade to an older version of skript-lang that supported 1.7. All the errors went away but now all commands just say unknown command so I upgraded my server to 1.8 and upgraded skriptlang to a later version (2.1.2) and it still does it. Please help I know it doesn't support 1.8 but I really need help on why this isn't working. Also why isn't 1.8 supported it is the most popular version out there hypixel on it mineplex on it please help please please It recognises the scripts but it says there aer 0 triggers and 0 commands when there is please HELP

**Comment by bensku** [comment]
1.8 and earlier versions are not supported by us. We do not currently have anyone who is interested enough to work on adding 1.8 support to this Skript version.
