### ISSUE TITLE
Servercrash when using on join in loop [CRITICAL!]

### ISSUE THREAD

**Issue by Paitorocxon** [SkriptLang/Skript#2855]
### Description
The server crashes when using on join together with a while player is online loop (wait 50 ticks).
Works when you're online and reload but the whole server crashes critically on rejoin.
Used version: 2.4 Stable (Latest release)

### Steps to Reproduce

on join:
    stopEffect id "ring.%uuid of {_from}%"
    stopEffect id "ring2.%uuid of {_from}%"
    while player is online:
        inventory name of player's current inventory contains "none"
        {tp.%player%.is} is 1:
            set {_from} to {tp.%player%.from}
            open chest with 1 rows named "&6Teleport" to player
            set slot 3 of player's current inventory to green wool with name "&2Accept" with lore "&eTeleport from %{_from}% &eaccept"
            set slot 5 of player's current inventory to red wool with name "&4Deny" with lore "&eTeleport from %{_from}% &edeny"
        wait 50 ticks

**Comment by Wealthyturtle** [comment]
Don’t delete the issue template provided... what’s the crash? Where’s the crash log?

**Comment by ShaneBeee** [comment]
The reason this happens is as follows:

Your code:
```vb
while player is online:
inventory name of player's current inventory contains "none"
```
so you are saying, while player is online, if their inventory's name is "none" ... do this stuff, then wait 50 ticks.
But you have no wait if the inventory is named anything else, therefor your loop is looping excessively 

I suggest not using inline conditions here, actually create new sections and make sure you have a wait in your loop regardless.
