### ISSUE TITLE
skRayfall invisible bug

### ISSUE THREAD

**Issue by Gaebalja626** [SkriptLang/Skript#2856]
Before read this bug report you should know that i'm Korean so i'm not good at English.

### Description

/team add test "testname"
/team join test
/team modify test seeFriendlyInvisibles true <<<<< this do not works
when we have invisibility we can see team translucently visible
but When server have skRayFall plugin
we cant see team 

### Steps to Reproduce

/team add test "testname"
/team join test 
/team modify test seeFriendlyInvisibles true

Command /giveeffect:
@trigger:
@@apply potion of invisibility of tier 2 without particles to player for 5 second

### Expected Behavior

show oneself in translucent light
But it's not. It's not visible at all

### Errors / Screenshots

![2020-03-09_19 00 31](https://user-images.githubusercontent.com/60886648/76202618-780c8b00-6238-11ea-8610-cc5f237b3eab.png)

### Server Information
* **Server version/platform:**       1.15.2
* **Skript version:**                 2.5 alpa 2

**Comment by ShaneBeee** [comment]
This issue tracker is for the Skript plugin itself.
All issues with addons need to be reported to the developer of the respective addon, in this case SkRayFall, as there is nothing we can do to resolve the issues from other plugins.

**Comment by Gaebalja626** [comment]
okey
