### ISSUE TITLE
Please change the numbers with a variable name

### ISSUE THREAD

**Issue by karingijs2727** [SkriptLang/Skript#2857]
apply speed 1 without particles to last spawned entity for 999 days
set the last spawned entity's max health to 375
spawn zombie at location of {SPAWN} 
give 1 diamond sword of sharpness 5 to player
-----------------------------------------------------------------------
Can change the numbers with a variable ?
please add this in the new version of skript
-----------------------------------------------------------------------
apply speed {SPEED} without particles to last spawned entity for {DAYS} days
set the last spawned entity's max health to {HP}
spawn {ZOMBIE} at location of {SPAWN} 
give {NUMBER} diamond sword of sharpness {NUMBER} to player

**Comment by Wealthyturtle** [comment]
You can already do this...?

set {SPEED} to 1

etc.

**Comment by Pikachu920** [comment]
you actually gotta parse it as a potioneffecttype for this to work as the effect isn't an expression but rather a class info literal parser
