### ISSUE TITLE
on rightclick Bug...?

### ISSUE THREAD

**Issue by yhdev7935** [SkriptLang/Skript#2862]
## Expected Behavior

Just one message to me(GameMaster_)

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/55119171/76759756-ad345280-67cf-11ea-8ebf-6ac88503626d.png)

```
on rightclick holding paper:
	if name of player's tool is "&aTEST":
		cancel event
		message "%sender% &a1234 TEST" to "GameMaster_" parsed as player
```

But When I clicked empty space, there is no error.
--->

### Server Information
* **Server version/platform:**       1.12.2
* **Skript version:**                2.4.1

**Comment by bluelhf** [comment]
What?

**Comment by Gumbraise** [comment]
You must say, that a player is selected. Like, if rightclick on a player :)
