### ISSUE TITLE
exact time until cooldown

### ISSUE THREAD

**Issue by AggerTV** [SkriptLang/Skript#2868]
### Description

Hello there, it would be nice, if you had the option to show the exact time until a cooldown (on a command) runs out. Maybe in /dd/hh/mm//ss format

Ex. I'm using command cooldowns on daily player rewards, but at the moment I can only show the date and time the player last made the command, and not when the player again can use the command.

I hope I formulated myself in somewhat of an understandable way :)

**Comment by noftaly** [comment]
You can already with the `remaining time` expression. e.g:
```
command /cake:
    cooldown: a day
    cooldown storage: {cake::%player's uuid%}
    cooldown message: One cake is enough for you today! Try again %remaining time% later.
    cooldown bypass: cake.eater
    trigger:
        if the player has space for a cake:
            give a cake to the player
        else:
            send "You do not have enough space in your inventory to hold the cake!"
            cancel the cooldown
```

**Comment by AggerTV** [comment]
Oups, didn't know that 😄 
Thanks

**Comment by noftaly** [comment]
no problem!
