### ISSUE TITLE
Misleading/Spammy warning with on inventory click

### ISSUE THREAD

**Issue by staridiot** [SkriptLang/Skript#2870]
### Description
Using `inventory name of %inventory%` causes a misleading & spammy warning to pop up in console

### Steps to Reproduce
Named a chest `&7Chest` and placed it, the error was not called no matter where I clicked. It does call if I open an inventory via SkQuery and click outside the opened inventory. This warning is also called when you pick block (middle click) in creative.
```
on inventory click:
	set {_inv} to inventory name of player's current inventory
	if {_inv} is "&7Chest":
		message "%{_inv}%"
```
### Expected Behavior
This warning is called when a player uses pick block (middle click) in creative and when clicking outside a plugin opened inventory. It's a bit misleading since it clearly does work and it's quite spammy. It would be nice to not see it again.

### Errors / Screenshots
```
[Server] Server thread/ERROR [Skript] In 1.13+ you cannot get the title name of an inventory outside of an InventoryClickEvent, Only if this inventory has an InventoryHolder may it be used in this state.
```

### Server Information/Tested on
* **Server version/platform:**       
Spigot git-Spigot-6de3d4b-a6f8093
                                                    Paper 143
* **Skript version:**                      2.5 alpha 2

**Comment by ShaneBeee** [comment]
`inventory name of %inventory%` <-- this is not a Skript expression. 
Sounds like an issue with SkQuery (I believe that expression is from SkQuery)

**Comment by Pikachu920** [comment]
yep, skquery: https://github.com/Minehut/SkQuery/blob/master/src/main/java/com/w00tmast3r/skquery/elements/expressions/ExprInventoryNameContainer.java#L79

**Comment by staridiot** [comment]
How am I expected to know this when it says **Skript** in the prefix of the error?

**Comment by TheBentoBox** [comment]
> How am I expected to know this when it says Skript in the prefix of the error?

By checking the docs to see where the effect/expression you're using originates. It takes just a minute and you'll waste less of everyone's time, including your own.

**Comment by Pikachu920** [comment]
@staridiot i was able to figure it out by just googling the error, but really it's not big deal either way. I'm just confirming it is from skquery.

side note: the fact it says Skript as the prefix is also the fault of the addon dev
