### ISSUE TITLE
Skript 2.2 dev36 not working

### ISSUE THREAD

**Issue by Congraz8961** [SkriptLang/Skript#2871]
Hi, so I have a bad problem. Have no idea how to fix the problem. I got an error message and was referred to here. Hope you guys can fix the problem, because I don't know what to do without script.

This is what it says over the console:
![image](https://user-images.githubusercontent.com/56209437/77219614-dcccbd00-6b37-11ea-87f8-d663f65862fb.png)

![image](https://user-images.githubusercontent.com/56209437/77219632-fa9a2200-6b37-11ea-866e-f0024392ba05.png)

Sry for my bad english

**Comment by ShaneBeee** [comment]
Sorry but this issue tracker is for updated versions of the Skript software.

The version you are using (2.2dev36) has been outdated for quite some time now, and is no longer supported. Not to mention are using a custom build (not supported by us) as well as using it on a 1.8.8 server (not supported by us)
