### ISSUE TITLE
Restoring inventory from variable

### ISSUE THREAD

**Issue by Laukage** [SkriptLang/Skript#2872]
### Description
```set {staffinv::%uuid of player%::inventory} to the player's serialized inventory``` works just fine, but when you restore the inventory using ```restore inventory of player from {staffinv::%uuid of player%::inventory}``` it doesn't do anything and prints out the error below.
### Steps to Reproduce
```
command /sm:
	trigger:
		if {staffmode::%uuid of player%} is not set:
			set {staffmode::%uuid of player%} to true
			set {staffinv::%uuid of player%::inventory} to the player's serialized inventory
			wait 1 tick
			clear player's inventory
			message "Turned on"
		else:
			delete {staffmode::%uuid of player%}
			message "Turned off"
			restore inventory of player from {staffinv::%uuid of player%::inventory}
```

### Expected Behavior
I expected it to actually restore the inventory.

### Errors / Screenshots
https://paste.gg/p/anonymous/eafb559482d540ffb6990b4e633b6a89

### Server Information
* **Server version/platform:** Paper-143
* **Skript version:** Skript 2.4.1

**Comment by ShaneBeee** [comment]
This is not a Skript syntax, this is from SkQuery, as seen in the stack trace here:
```

[16:38:59] [Server thread/ERROR]: #!#! Stack trace:
--
  | [16:38:59] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 41)
  | [16:38:59] [Server thread/ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
  | [16:38:59] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.createInventory(CraftServer.java:1661)
  | [16:38:59] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.util.serialization.InventorySerialUtils.fromBase64(InventorySerialUtils.java:35)
  | [16:38:59] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.EffDeserializeInventory.execute(EffDeserializeInventory.java:35)
```

**Comment by Jayderp** [comment]
@Laukage report this bug on the skquery discord or github

**Comment by Laukage** [comment]
> @Laukage report this bug on the skquery discord or github

I already did.
https://github.com/SkQuery/SkQuery/issues/35
