### ISSUE TITLE
PlayerToggleSneakEvent not cancelling

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2873]
### Description

The "on sneak toggle" event doesn't cancel when using a "cancel event".
### Steps to Reproduce

Type something like 

`on sneak toggle:`
`   cancel event`

and reload. In-game, if you sneak you won't be put back into standing mode

### Expected Behavior

When you crouch you should be put back into walking mode.
The event is cancellable, as seen here.
![image](https://user-images.githubusercontent.com/49515406/77240745-34f5e300-6c4e-11ea-94d8-f3ddcf32a08d.png)

### Errors / Screenshots
I've tried this a few times and every time it doesn't work:

![image](https://user-images.githubusercontent.com/49515406/77240720-e3e5ef00-6c4d-11ea-8ea7-60c1519b12fb.png)
Snippet I used (doesn't work, i tried like 10 others):
![image](https://user-images.githubusercontent.com/49515406/77240724-ed6f5700-6c4d-11ea-925f-970afc4976ed.png)

### Server Information
* **Server version/platform:**  
![image](https://user-images.githubusercontent.com/49515406/77240763-75edf780-6c4e-11ea-8ea2-3bd46a4dbe2f.png)
     
* **Skript version:**        
![image](https://user-images.githubusercontent.com/49515406/77240760-69699f00-6c4e-11ea-8f59-4346266cfa94.png)
        

### Additional Context

Shane I'm actually trying to help this time please don't ddos my wifi

**Comment by Pikachu920** [comment]
unfortunately it's a minecraft thing. it does cancel - other players will see you as if you were standing normally, but the player's own client will think it's sneaking

**Comment by Jayderp** [comment]
thanks pika. also your tuske fork is very nice

**Comment by Misio12320** [comment]
may better report to bugs.mojang to get sure they can fix or something?
