### ISSUE TITLE
Using the teleport effect with pitch or yaw conditions returns error.

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2882]
### Description

The effect "with yaw" and "with pitch" seem to not work or have been removed.
### Steps to Reproduce
Create a basic command and trigger to run "teleport player to location at (%location% in world "%world%" with pitch 0 and yaw 0"
It should work (according to this thread from 2018):
![image](https://user-images.githubusercontent.com/49515406/77637168-1c712a00-6fba-11ea-8c43-b2285c2fbfef.png)
![image](https://user-images.githubusercontent.com/49515406/77637186-24c96500-6fba-11ea-80cb-2b1403be66a3.png)

However, when I implement it I get this:
![image](https://user-images.githubusercontent.com/49515406/77637229-37439e80-6fba-11ea-9932-d2ebc66ebcda.png)
(ignore /setbox and south)

### Expected Behavior

The script should reload fine, with no syntax error and running the /ee er command should teleport you to the location of the box and set your pitch and yaw to 0.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/49515406/77637419-8558a200-6fba-11ea-95df-f7804979168d.png)

![image](https://user-images.githubusercontent.com/49515406/77637782-116ac980-6fbb-11ea-9bea-1db0cbf49841.png)

### Server Information
* **Server version/platform:**    
![image](https://user-images.githubusercontent.com/49515406/77637458-986b7200-6fba-11ea-89a6-2ee574b4f02a.png)
also since minehut has ligma it's 16 versions behind
   
* **Skript version:**      
![image](https://user-images.githubusercontent.com/49515406/77637440-90133700-6fba-11ea-946a-0689f2b5287f.png)
          

### Additional Context

Pretty sure this used to work, however, support must've either been dropped, or the syntax has changed.
Here's my list of Skript plugins:
![image](https://user-images.githubusercontent.com/49515406/77637882-33fce280-6fbb-11ea-9b62-422835d042c8.png)
And all plugins:
![image](https://user-images.githubusercontent.com/49515406/77637918-424afe80-6fbb-11ea-9531-27fd5934a5fc.png)

**Comment by ShaneBeee** [comment]
`Skript version: 2.4.1-MH` <--- this is a fork of Skript made by the Minehut team.

Please test with our software when reporting issues to us regarding our software.
