### ISSUE TITLE
[SUGGESTION] Add "pitch" and "yaw" expressions to teleport effect

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2883]
### Description
A "pitch" and "yaw" expression helps to get REALLY precise data for a teleport condition.
Say I want an `/ee er` command to teleport a player to the center of a box with lyrics to a roddy ricch song. The player faces directly south with their camera angle at 0.
You'd think to use `teleport player to location at %location% in world %world% with yaw 0 and pitch 0` BUT YOU'D BE WRONG
According to ShaneWasp, there are no pitch and yaw expressions.
![image](https://user-images.githubusercontent.com/49515406/77644238-95c24a00-6fc5-11ea-91de-3b709c7cfece.png)

This made me hubble bubble and cry for 6.5 seconds.

Please add :)

**Comment by ShaneBeee** [comment]
Jayderp I have locked this message, removed the inappropriate contented and reported it.
