### ISSUE TITLE
[For future] Add options to 1.16

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2884]
Hello gamers.
1. Add when 1.16 release a support to cancel enchant on compass right clicked on the new block. 
2. Add support to change drop item from Piglin.

**Comment by JRoy** [comment]
This is way too early to make an issue ticket about. 1.16 isn't even at the pre-release stage yet, let alone do we have a 1.16 bukkit api yet and therefore don't even know if theses things are possible to accomplish.

Once 1.16 is released for bukkit, work will begin by the skript developers/contributors to update skript to it but now is too early to be requesting features.

**Comment by Misio12320** [comment]
Eh sure ok.
