### ISSUE TITLE
SkriptParser.parse errors

### ISSUE THREAD

**Issue by kikimessy** [SkriptLang/Skript#2885]
### Description

I've been receiving these errors (found at https://gist.github.com/kikimessy/f6c625794b1443d6b097ffd90af2a1f9) on my server whenever I try to load this script (also found at https://gist.github.com/kikimessy/f6c625794b1443d6b097ffd90af2a1f9) I'm unsure of why this is happening. Sometimes this can completely crash the server if the error causes the server to be unresponsive long enough.
### Steps to Reproduce
1. Add the script
2. Reload the script
3. View the logs, something similar to mine should pop up
### Expected Behavior
I'm expecting for the script to be able to parse normally without any errors, and without crashing the server
### Errors / Screenshots
https://gist.github.com/kikimessy/f6c625794b1443d6b097ffd90af2a1f9

### Server Information
* **Server version/platform:**  git-paper-129 (MC: 1.15.2)
* **Skript version:**               2.4.1-MH

**Comment by bensku** [comment]
We do not support patched versions of Skript or addons your script uses.
