### ISSUE TITLE
Furnace fuel burn event not working with future time state

### ISSUE THREAD

**Issue by mapokapo** [SkriptLang/Skript#2889]
~~**EDIT:** After trying to fix the error, the following error log occurs when running the code below in version 2.5-alpha2 of Skript [log3.txt](https://gist.github.com/mapokapo/d51e661dcf87f38ae99ad049cc6d6a62)~~

~~on fuel burn:~~
	~~clear the result slot of the block~~
The error was fixed by restarting the server. `/skript reload scripts` didn't properly reload all scripts.

### Description
After a furnace `on fuel burn` event gets triggered, the future time state (`will be` or `after the event`) of the `fuel slot` in the `event-block` isn't fulfilled, and doesn't work as expected.

### Steps to Reproduce
1. Insert smeltable items and fuel into a furnace
2. Wait until all but one fuel item burn out
3. Then, the last fuel item burning out should be the only one to satisfy the future time condition (`the block's fuel slot will be air`), but it doesn't

The following code is in question:
```
on fuel burn:
	the block's fuel slot will be air  # or "the fuel slot of the block will be air / after the event is air"
	broadcast "aaa"  # doesn't ever run
```

### Expected Behavior
The expected outcome is the future time condition being fulfilled after the last fuel item burns out, leaving the furnace fuel slot empty/air, and the code proceeding successfully

### Errors / Screenshots
There are no errors in version 2.5-alpha2, but see more below

### Server Information
* **Server version/platform:** git-Paper-145 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
* **Skript version:** 2.5-alpha2

### Additional Context
Although the issue persists and is identical on Skript version 2.4.1 stable, it produces the following 2 console errors:
[log1.txt](https://gist.github.com/mapokapo/ebb335ed0d7f20d2a2390383123fb53b)
[log2.txt](https://gist.github.com/mapokapo/22d5c71a91af122237c24a9d238950a5)

**Comment by ShaneBeee** [comment]
I'm not 100% sure but I think this may be related to #671

**Comment by mapokapo** [comment]
This issue technically includes 2 bugs, one of which was mentioned in the edit at the top. The first one was the inconsistency with time states, and the second one with Skript failing to recieve the FurnaceBurnEvent. I will change the title back to the original since that's what this issue was originally about. Should I make a new issue for the FurnaceBurnEvent error?

**Comment by ShaneBeee** [comment]
> I will change the title back to the original since that's what this issue was originally about. Should I make a new issue for the FurnaceBurnEvent error?

no, because that issue seems to be only present on 2.4.1 and not 2.5, so its really no issue.

**Comment by mapokapo** [comment]
This is indeed related to #671 as you said, as the future and past time states of the fuel slot item are the same

**Comment by ShaneBeee** [comment]
> This is indeed related to #671 as you said, as the future and past time states of the fuel slot item are the same

sadly this is something that we're not 100% sure how to fix. 
for me personally, I just wait a tick, and then do checks. I know its not a "fix" per se, but it does seem to work in most cases

**Comment by mapokapo** [comment]
That certainly seems like a solution.

> > I will change the title back to the original since that's what this issue was originally about. Should I make a new issue for the FurnaceBurnEvent error?
> 
> no, because that issue seems to be only present on 2.4.1 and not 2.5, so its really no issue.

Regarding the FurnaceBurnEvent, it occurs in 2.5-alpha2, _along_ with the time states not working consistently. AFAIK it doesn't happen in 2.4.1

**Comment by ShaneBeee** [comment]
> Regarding the FurnaceBurnEvent, it occurs in 2.5-alpha2, _along_ with the time states not working consistently. AFAIK it doesn't happen in 2.4.1

in my testing, I only got the stack trace error if I used `fuel slot` but if I used `fuel slot of event-block` it worked fine.

**Comment by mapokapo** [comment]
It turns out the `/skript reload scripts `command didn't completely reload the scripts, and it required a server restart. However, `clear the result slot of the block` is not understood by the parser, but `clear the block's result slot` is, and works as intended. I will update the part of the post regarding this issue.

**Comment by TheLimeGlass** [comment]
Issue is expressions don't get converted into event-values which can then be used in the time states https://github.com/SkriptLang/Skript/issues/3150

I also go into information about it here https://github.com/SkriptLang/Skript/pull/3149
