### ISSUE TITLE
Language.get seems to ignore the .lang file

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2890]
### Description

The `get` method from the `ch.njol.skript.localization.Language` class seems to ignore what's written in the .lang file

### Steps to Reproduce

The "none" setting is set to 0 in my .lang file
However, `!broadcast (class "ch.njol.skript.localization.Language").get("none")` broadcasts `<none>`

### Expected Behavior

The "none" setting shouldn't be ignored

### Errors / Screenshots

N/A

### Server Information
* **Server version/platform:** Spigot 1.14.4      
* **Skript version:** 2.4.1

**Comment by Pikachu920** [comment]
in what lang file? did you edit the default one or did you make a new one?

**Comment by Matocolotoe** [comment]
I edited the default one

**Comment by ShaneBeee** [comment]
I marked this as needs-testing, we'll have to test this.
