### ISSUE TITLE
Expression "no damage ticks" can't work properly

### ISSUE THREAD

**Issue by lnelg10** [SkriptLang/Skript#2893]
### Description
Expression "no damage ticks" can't work properly.

### Steps to Reproduce
```
 on damage:
    set victim's invulnerability ticks to 1
    send "%victim's invulnerability ticks%" to the attacker
```

### Expected Behavior
It successfully sends the victim's invulnerability ticks “1” to the attacker , but actually the interval doesn't get changed . (I can't do damage to it in about 0.2 seconds.)

### Errors / Screenshots
 No errors , it doesn't warn anything , but it can't work.

### Server Information
Server version/platform:       1.13.2 paper spigot
Skript version:           Second 2.5 unstable alpha release

**Comment by ShaneBeee** [comment]
Im confused, what exactly is the issue here?

**Comment by lnelg10** [comment]
> Im confused, what exactly is the issue here?

I used the expression "No Damage Ticks" . In fact I copied the code in the document . I just changed "20" to "1" or "20" "40" etc. But actually the entity's invulnerable time didn't change. 
I did an experiment by using a weapon that can shoot 10 arrow in one second . But the number which the entity took damage is seems not changes although I changed the no damage ticks.
P.S. English is not my mother tongue, maybe my description is not clear ,I'm sorry.
```
on damage:
    set victim's invulnerability ticks to 1
```

**Comment by bluelhf** [comment]
The damage event is called before damage is applied, which might be why setting the invulnerability ticks does nothing. Can you try waiting one tick before setting them, and report back results?

**Comment by lnelg10** [comment]
> The damage event is called before damage is applied, which might be why setting the invulnerability ticks does nothing. Can you try waiting one tick before setting them, and report back results?

I modified my code and now it works properly ,thanks for your help!
```
on damage:
	wait 1 tick
	set victim's invulnerability ticks to 1
```
