### ISSUE TITLE
All skulls/player heads report as ender dragon

### ISSUE THREAD

**Issue by DavidVioMC** [SkriptLang/Skript#2897]
### Description

All skulls and playerheads report as ender dragon helmet.

### Steps to Reproduce

`on right click:
	broadcast "%event-item%"`

### Expected Behavior

It should report it as the correct item

### Errors / Screenshots

![Screenshot_5](https://user-images.githubusercontent.com/40337710/77910452-0a77db80-7287-11ea-8a7e-41c95780c84e.png)

### Server Information
* **Server version/platform:**       1.12.2 Paper (git-Paper-1618)
* **Skript version:**                2.4.1

**Comment by ShaneBeee** [comment]
Yes, this is a know issue, give me a min to find the duplicate that this duplicates

**Comment by DavidVioMC** [comment]
Oh, I didn't know that. I can close it then.

**Comment by Wealthyturtle** [comment]
Duplicate #2711
