### ISSUE TITLE
[Skript] Unable to make a final save of the database

### ISSUE THREAD

**Issue by MrGametop1** [SkriptLang/Skript#2899]
### Description

In the skript folder, the variables.csv becomes a variables.csv.temp

### Steps to Reproduce

Its like a fity fity, i cant really pin point what is going on when it happens, but it only happens on server restart.

### Expected Behavior

It shoudlnt make a variables.csv.temp file, but save everything to the variables.csv instead of variables.csv.temp

### Errors / Screenshots

[Skript] Unable to make a final save of the database 'default' (no variables are lost): plugins/Skript/variables.csv.temp -› /data/service20974/data/service_item_1243986/./plugins/Skript/variables.csv: Invalid cross-device link
Link to the error:
https://hastebin.com/fukemojali.coffeescript

It has happend like over 50 times, but once it pasted this error, but this error is not linked to the problem i have:
https://hastebin.com/butivexupa.md

config for this exact database (its default config btw):
	default:
		type: CSV
		pattern: .*
		file: ./plugins/Skript/variables.csv
		backup interval: 2 hours

### Server Information
* **Server version/platform:**       
This server is running Paper version git-Paper-145 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
* **Skript version:**                
2.4.1 "cccd71c"

### Additional Context

One time it happend like every single time with 
delete {variable::*}
Then it happend after nearly restart

**Comment by ShaneBeee** [comment]
I have never seen an error like this. Almost looks to be a file issue with your server machine.

**Comment by MrGametop1** [comment]
With an other machine, and a other minecraft version
It does nearly the same thing but, makes the temp file, but still saves and uses the right .csv file, which is super wierd

**Comment by TPGamesNL** [comment]
@MrGametop1 Are you able to provide the stack trace again? The hastebin link has expired

**Comment by TPGamesNL** [comment]
Closing due to lack of response for a month
