### ISSUE TITLE
Rightclick event not being called for villagers

### ISSUE THREAD

**Issue by ArVdC** [SkriptLang/Skript#290]
Thanks for the [#273](https://github.com/bensku/Skript/issues/273) fix.
But I just noticed that some rightclik events can't be cancelled anymore by the "cancel event" command.
Actually, it fails for villagers (I need to hide their shops GUI) and item frames (I need to avoid the items rotation)

**Comment by bensku** [comment]
It is known that right click events are very occasionally not working correctly. Click events are handled by hand-written lookup table (what was clicked? what player had in both hands?), and that is far from perfect solution.

**Comment by ArVdC** [comment]
I didn't kow that. Thank you for clarification.
But my following lines of code still work fine, so it's look like the rightclick events are correctly detected.
Only the event cancelling doesn't work ... however it was working fine with the dev20b, just before I update to the dev22f.

```
on rightclick on a villager:
    cancel the event
    send "Here is a few dirt" to event-player
    give 5 of dirt to event-player
```
In this example, the player always receives the message and the five dirts.
However the cancelling doesn't fail occasionally but on each try ...

**Comment by bensku** [comment]
Oh, then it is something new. If you can catch the event, you should be able to cancel it... I hope Spigot 1.11 didn't change anything significant here.

**Comment by ArVdC** [comment]
I hope so too. Thank you for your concern.
I'm trying to check if the issue can be due to an addon incompatibility.
I'll keep you informed.

**Comment by JeepSmash** [comment]
code:
```
on right click on item frame:
    player's tool is map
    send "Maps in item frames are not allowed here." to event-player
    cancel event
```
This code stopped working properly when i updated to dev22f however now the event is no longer canceled and the map is placed in the item frame after the player gets sent the message.

**Comment by JeepSmash** [comment]
I have found another situation when right click events will not cancel properly.  I am having an issue where the right click event cannot be canceled if the player has an item in their offhand that can be placed upon right click.

```
on place:
 cancel event
 message "You cannot place blocks here"
```

if the player right clicks holding an item that cannot be placed vanilla trys to place the offhand item for the click.  Canceling the event does not stop the action to place the offhand item where the click occurred.  So with this code if the player had a sapling in their tool slot and stone in his offhand it would still place the stone block if they right clicked on anything a sapling cannot be placed on with the code executing to cancel the event.

**Comment by nshun1896** [comment]
I also confirm it.
```
on rightclick on item frame:
	cancel the event
	message "hey" to player

```
When I have an item and right click on an empty item frame, the item will be put in the item frame and the message will be given to player.
I assume this event is detected correctly, but cancel doesn't work.
I hope it will be fixed. Thanks.

**Comment by YellowZaki** [comment]
Bump?

**Comment by zmolahah** [comment]
@JeepSmash Just so you guys know I encountered this problem a bit ago as well but I just used Skellet as a hacky workaround to fix the problem

```
rightclick on item frame:
	set {_rotation} to clicked entity's item frame rotation
	wait 2 ticks
	set clicked entity's item frame rotation to {_rotation}
```

This will put the rotation back to it's previous state when someone attempts to rotate the only problem is you can see people attempting to rotate but I don't find that to be a major issue

**Comment by melinstagibson** [comment]
Just tried cancelling "on right click on villager", sadly isnt working either. dev25. Any chance to fix this? anything else works i just cant cancel it

so bump i guess

**Comment by bensku** [comment]
Literally calling event.setCancelled(true) doesn't work, so I have no more ideas...

**Comment by ChimpGamer** [comment]
"on left click on villager" doesn't work for me :(

**Comment by TheBentoBox** [comment]
@ChimpGamer You shouldn't use "left click" on entities since that's a damage event, use `on damage of villager`.

**Comment by ChimpGamer** [comment]
Ow, sorry. But I have to use "left click". Because a Shop is on that Villager (plugin) and it uses left click to open the shop. (Can't change button). And with Skript I'm trying to set a permission on that.

**Comment by TheBentoBox** [comment]
Left clicking a villager IS a damage event, that's what I'm saying. If you want to detect players left clicking a villager, use the damage event. If canceling that doesn't work, then that's the fault of your shop plugin, and not something Skript can do anything about.

And again, this isn't the place to talk about this, as it's not relevant to this issue. If you want more help trying to figure out a way around that, go ask on the skUnity forums, not here.

**Comment by Snow-Pyon** [comment]
Can someone confirm this is still an issue?

**Comment by HYPExMon5ter** [comment]
It's still in issue in dev35
