### ISSUE TITLE
Names and lores of books are being ignored

### ISSUE THREAD

**Issue by DavidVioMC** [SkriptLang/Skript#2900]
### Description

Named books are being ignored when checking for names/lores.

### Steps to Reproduce

```
command /testbook:
	trigger:
		give player book named "Test" with lore "Testing book"
		give player book
		
command /removebook:
	trigger:
		set {_book} to amount of book named "Test" with lore "Testing book" in player's inventory
		broadcast "%{_book}%"
		remove 1 book named "Test" with lore "Testing book" from player
```

### Expected Behavior
After doing /testbook, player will contain one vanilla book and one named "Test with lore "Testing book", when /removebook is executed, the vanilla book should stay in player's inventory and one "testing" book should be removed, but instead, the vanilla book will be removed and the testing one will stay.

### Errors / Screenshots

No errors

### Server Information
* **Server version/platform:**   1.12.2 Paper (git-Paper-1618)    
* **Skript version:**    2.4.1

**Comment by ShaneBeee** [comment]
can you try 2.5-alpha3.... I believe this issue has already been resolved.

**Comment by Romitou** [comment]
Yes, solved in 2.5-alpha2. (#2714)

**Comment by DavidVioMC** [comment]
Seems to be fixed but when checking for an item with multiple lores, it seems to cause internal error. For example when you add this:
`command /removebook:
	trigger:
		set {_book} to amount of book named "Test" with lore "Testing book" and "t" in player's inventory`

This worked fine in 2.4.1, not sure if this is a problem related to #2714 or I should open another issue.

**Comment by Romitou** [comment]
Hello, I can confirm this en 2.5-alpha3.
Until this issue is resolved, you can go through this working method.

```python
command /givetest:
    trigger:
        give a book named "This is a test." with lore "Hello!" and "Wow!" to player

command /test:
    trigger:
        set {_lore::*} to "Hello!" and "Wow!"
        set {_book} to amount of book named "This is a test." with lore {_lore::*} in player's inventory
        send "%{_book}%"
```

**Comment by ShaneBeee** [comment]
I just tested this using 1.12.2 and 1.16.1 with Skript 2.5-beta1 and the issue seems to have been resolved somewhere along the way.
