### ISSUE TITLE
1.15.2 Spigot | Skript version 2.4.1 | Commands Not Working

### ISSUE THREAD

**Issue by BatDev0** [SkriptLang/Skript#2901]
### Question

When I try to do /skript help it just says /skript help in the chat. This is a fresh server. Is there any way I can fix this. I read the release notes and it said 1.15 is officially supported with the one I installed. 

Version: Skript version 2.4.1
Server Version: 1.15.2 Spigot Latest Release
Plugins: EssentialsX, Shopkeepers, Group Manager, Multiverse, Protocol Support, Vault, Rank Grant

Thanks!

**Comment by ShaneBeee** [comment]
any console errors?

**Comment by BatDev0** [comment]
No console errors. It just says the `/skript help` in the console and chat. I am also using bungeecord if that helps?

**Comment by BatDev0** [comment]
@ShaneBeee 

Okay, Thanks for the help.
