### ISSUE TITLE
Priority for event

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2904]
May add a priority event? E.g
on rightclick:
    priority is 1:
        spawn zombie

on rightclick:
    priority is 2:
        spawn ender dragon

Ender dragon should spawn not zombie because priority is higher.

**Comment by ShaneBeee** [comment]
Even if we had even priorities, both events would still fire, therefor both entities would still spawn.

**Comment by Wealthyturtle** [comment]
> Even if we had add event priorities, both events would still fire, therefor both entities would still spawn. I don't think you understand how event priorities work.

^
Also, duplicate of #197

**Comment by Misio12320** [comment]
Why its "invalid" not duplicate??
