### ISSUE TITLE
<none> 

### ISSUE THREAD

**Issue by bonjourkemal** [SkriptLang/Skript#2908]
```
command /scmarket:
    trigger:
        SCMarket(player)
function SCMarket(p : player):
    #...
    make gui slot 4 of {_p} with sunflower named "&fCoin &8» &7%{coin::%{_p}%} ? 0%" to nothing
```
When I use / scmarket, there is no problem with the data, but when I go through the menu, the data appears as none? Why is that?

**Comment by bonjourkemal** [comment]
Skript ver: 2-5 alpha3
Server ver: 1.15.2 paperspigot

**Comment by bonjourkemal** [comment]
when set {coin::%player%} to 125 and it's working but when this variable is not set, as i mentioned above, the problem arises

**Comment by bonjourkemal** [comment]
That is not problem in Skript 2.4. So I using Skript 2.4 now..

**Comment by ShaneBeee** [comment]
Can you try replicate this without using addons?
The code you have here is from Tuske, and Tuske is known for having issues with player stuff in functions.

**Comment by bonjourkemal** [comment]
I think there is no need to try because it works without using tuske. Logically, I can't try this skript if I remove tuske.

**Comment by ShaneBeee** [comment]
> I think there is no need to try because it works without using tuske. 

Sounds to me like an issue with Tuske then.

**Comment by bonjourkemal** [comment]
It works with Skript 2.4 but not with Skript 2.5.  Will they help if I notify the tuske producer?  at least I think the new addon should be made.
