### ISSUE TITLE
Problem with "HttpURLConnection"

### ISSUE THREAD

**Issue by Carvane** [SkriptLang/Skript#2909]
Description: sometimes the server does not respond and crashes by the script

Steps to Reproduce: when the player connects to the server and the script checks the page
Skript: https://pastebin.com/n2YNwkbX

Errors / Screenshots: https://pastebin.com/bdDEu6wn

Server Information:
* **Server version/platform: Tuinity 1.15.2 Build #33
* **Skript version: 2.5-alpha3

**Comment by Wealthyturtle** [comment]
That would be an issue with skQuery, the plugin you're using for this expression, not Skript itself. Please report the issue to skQuery.
