### ISSUE TITLE
on redstone change

### ISSUE THREAD

**Issue by Carvane** [SkriptLang/Skript#2912]
Description: script does not work

Skript v1:
```vb
on redstone change:
    delete event-block
```

Skript v2:
```vb
on redstone change:
    set block at location of event-block to air
```

Errors / Screenshots: lack

Server Information:

**Server version/platform**: Tuinity 1.15.2 Build #33
**Skript version**: 2.5-alpha3

**Comment by ShaneBeee** [comment]
Can you please add a detailed description of the issue.
"does not work" does not tell us anything.

**Comment by ShaneBeee** [comment]
Closing due to lack of response. 
I'm not sure what the actual issue is here.
