### ISSUE TITLE
invalid lines & formatting

### ISSUE THREAD

**Issue by melmito** [SkriptLang/Skript#2919]
- Description
&n / &m, seems to invalidly duplicate lines and show them on each other, this is able to be reproduced on a scoreboard and in chat.

- Steps to Reproduce
Simply use &n or &m in-chat you'll see it stacks up eachother.

- Expected Behavior
like older versions to simply output it right and not so fk'd up.

- Errors / Screenshots
https://postimg.cc/Th7c9xrY

- version
2.5-alpha3/older - this can be reproduced on 1.13+

**Comment by TheBentoBox** [comment]
We have no control over how these outputs are rendered at all. This is entirely based on how Minecraft decides to render these formatting effects and based on the active font.
