### ISSUE TITLE
Vanished players / online players

### ISSUE THREAD

**Issue by AggerTV** [SkriptLang/Skript#2920]
### Description

This expression includes vanished players, maybe do so it doesn't include vanished players
%number of all players%

**Comment by ShaneBeee** [comment]
Im sorry but no. 
Number of all players is the number of player objects currently on the server.
Whether another plugin vanishes the players from being visually seen does not change this number and should not change this number.

**Comment by Pikachu920** [comment]
you can probably do `amount of all players where [input is visible to player]`
