### ISSUE TITLE
Former world doesn't work

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2922]
### Description

'Former world' doesn't work properly, it gives the future world.
### Steps to Reproduce

Script:
```
on teleport:
	broadcast "%former world%"
	broadcast "%future world%"
```
Build a nether portal and go through.
### Expected Behavior

I expected to see:
`world`
`world_nether`
but I see:
`world_nether`
`world_nether`
### Errors / Screenshots

No errors.

### Server Information
* **Server version/platform:**       Paper 1.15.2
* **Skript version:**                Skript v2.5-alpha3

**Comment by ShaneBeee** [comment]
Duplicate of #671
