### ISSUE TITLE
Internal error when a player types a custom command

### ISSUE THREAD

**Issue by saltyfishhy** [SkriptLang/Skript#2925]
I have a command (/rank offlineplayer) which opens a gui showing some basic things and options like promote, set rank, skull, etc. The command works great for me, however when one of my admins who has the permission executes it she gets a message in chat saying "An internal error has occurred" I looked in console, and found an error.

https://pastebin.com/E4vY8RR0

Not sure what's going on here...

**Comment by nfell2009** [comment]
The error is related to the addon TuSKe. You'd need to report it to the author. However, the author of that addon, Tuke_Nuke, is inactive.

**Comment by ShaneBeee** [comment]
As nfell stated, this is not a Skript error.
