### ISSUE TITLE
Suggestion: simplify ternary expression

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#2928]
### Description
Hello, I recently wondered if there was a way to reproduce the behavior of the separator `||` coming from JavaScript in Skript.

I know this is a tertiary expression, which I will use, but I was wondering if it is possible to reduce this expression like this, ie check the previous variable if none is specified: `send "%{_test} if set, else {_test2}%"` instead of checking if the variable is defined after, normally like this: `send "%{_test} if {_test} is set, else {_test2}%"`.

I do not know if my explanations are clear, I apologize otherwise and thank you for letting me know. 
Here is an another example:

```py
command test:
	trigger:
		set {_welcome} to "Welcome!"

		# This is my suggestion:
		send "%{_hello} if set, else {_welcome}%"
		# Output: "Welcome!"

		set {_hello} to "Hello!"
		
		# Or like this:
		send "%{_hello} || {_welcome}%"
		# Output: "Hello!"

		# Instead of the current syntax:
		send "%{_hello} if {_hello} is set, else {_welcome}%"
		# Output: "Hello!"
```
Related to https://github.com/SkriptLang/Skript/blob/6524d69f1e8583f917ea18c9fe526ec6df66dbfc/src/main/java/ch/njol/skript/expressions/ExprTernary.java

Thank you very much for your work around Skript, do not hesitate to comment on my suggestion!

**Comment by Pikachu920** [comment]
You can use the default value expression: `{_nothing} otherwise {_something else}`

As a side note you should know this is not how the || operator works in JS, that operator is actually checks if the value is truthy so
```
const value = 0;
const anotherValue = "I shouldn't be seen";
console.log(value || anotherValue);
```
will actually print "I shouldn't be seen" rather than 0.
