### ISSUE TITLE
Setting the colour of a bed causes an error.

### ISSUE THREAD

**Issue by Zulfen** [SkriptLang/Skript#2931]
### Description
Trying to set the colour of a bed at a certain location causes a Skript error in console and does not change the colour.

### Steps to Reproduce
```
on break of red bed:
   broadcast "%colour of event-block%"
   cancel event
   set block at event-location to white bed
   set the colour of the block at event-block to blue
```
### Expected Behavior
For the bed to change to the desired colour (i know it would place at a different location, just wanted to test.)

### Errors / Screenshots
https://gist.github.com/Zulfen/a0d745be5174518c16fd3992ef20210b

### Server Information
* **Server version/platform:** Paper version git-Paper-221 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

* **Skript version:** 2.4.1

Please reply if you would like any further info!

**Comment by ShaneBeee** [comment]
The error comes from Spigot:
```
java.lang.UnsupportedOperationException: Must set block type to appropriate bed colour
```
It tells you there exactly what to do.

We can suppress this error, but we aren't going to "fix" it, due to its not being broken. in 1.13+ each color bed is a different block.

**Comment by Pikachu920** [comment]
@ShaneBeee any reason we couldn't just replace the bed with a blue bed? I believe that is the intended behavior here

**Comment by ShaneBeee** [comment]
> @ShaneBeee any reason we couldn't just replace the bed with a blue bed? I believe that is the intended behavior here

We totally could do that. Now in my opinion we are giving the user the wrong impression. 
At the end of the day, the user could just set the block to the block they want. 

If someone wants to do it that way I guess they could, and I won't be opposed to it. Its just not something I personally would do.

**Comment by Zulfen** [comment]
Alright, thank you :)
