### ISSUE TITLE
Players' inventories keep swapping without any sensible reason.

### ISSUE THREAD

**Issue by workonfire** [SkriptLang/Skript#2932]
### Description
I'm experiencing a stupid problem. I have a script, basically what it does is just to give every online player a "mysterious egg" (screenshot below) according to the user rank by permissions (e.g. VIP -> permission.vip etc.) and broadcast a message to the chat every 10 minutes. The problem is this piece of code:
```every 10 real minutes:
    loop all players:
        if loop-player has permission "niespodzianka.2":
            give 2 of glowing heart of the sea {@jajko} to the loop-player
        if loop-player has permission "niespodzianka.3":
            give 1 of glowing heart of the sea {@jajko} to the loop-player
        else:
            give 1 of glowing heart of the sea {@jajko} to the loop-player
```
When every player receives the egg, **_sometimes_** everyone on the servers' inventories swap with other players inventories. Sometimes the inventories revert back to the original ones, but sometimes not. I have no idea what is causing the problem here. I don't know whether it's a Skript issue, or one of my installed addons, which are listed below. I can't check it, so I'm posting the issue here.

### Steps to Reproduce
Load the script, wait 10 minutes and pray. The biggest problem there is that I just can't reproduce this bug in any way, unless it will happen randomly, so it's unbelievably hard to documentate it.

### Expected Behavior
The _mysterious egg_ should be given to every player without swapping any inventories.

### Screenshots
![image](https://user-images.githubusercontent.com/34654573/79777028-f3348700-8336-11ea-8d37-25effee511bc.png)

### Server Information
* **Server version/platform:** 
![image](https://user-images.githubusercontent.com/34654573/79777114-0fd0bf00-8337-11ea-8694-e5398c44a04e.png)

* **Skript version:** 2.4.1
* **Skript addons:** `Ersatz`, `SK-NBeeT`, `Skellett`, `SkQuery`, `skript-mirror` and `skUtilities`

### Additional Context
I have found a similar issue down here: https://forums.skunity.com/threads/inventories-keep-swapping.10149/
But unfortunately - no replies.

# FULL SCRIPT: https://pastebin.com/T7HRcaRY

**Comment by ShaneBeee** [comment]
> I don't know whether it's a Skript issue, or one of my installed addons, which are listed below. I can't check it, so I'm posting the issue here.

Well, you're going to have to check yourself. It is not our job to test the addons you have listed here.
Try remove your addons and replicate this issue without addons. 
skUtilities for example is an abandoned add-on that has been very well known to cause a lot of issues.

While I do appreciate the very thorough report you have here, there appears to be nothing substantial to say this is a Skript issue.

**Comment by workonfire** [comment]
> Well, you're going to have to check yourself.

I wish I could:

> The biggest problem there is that I just can't reproduce this bug in any way, unless it will happen randomly, so it's unbelievably hard to documentate it.

Yes, I know - I do have installed some Skript add-ons, that might be causing the issue.

But I think the fact that they're installed is completely irrelevant, since the guy from the [thread](https://forums.skunity.com/threads/inventories-keep-swapping.10149/) I mentioned earlier has only one common addon with me, and the problem **STILL** occurs. This excludes every add-on from the list above (except `SkQuery`) from causing the issue.

And I do not think `SkQuery` causes this bug, because this add-on is not used in my script in any way.
I might be wrong, but for me, everything indicates that it is indeed a Skript issue..

**Comment by ShaneBeee** [comment]
> I wish I could:

I'm not really sure why you're saying you can't. Its your job to test without addons. 

If you can replicate this without any addons then we can investigate further.

**Comment by Pikachu920** [comment]
@workonfire not necessarily, just because the same issue is described doesn't mean it's the same cause however can you clarify what you mean when you say they swap inventories? Do you mean that every item in one players inventory swaps with every item in another players inventory?

**Comment by workonfire** [comment]
@Pikachu920 
> Do you mean that every item in one players inventory swaps with every item in another players inventory? or is it just the egg that swaps?

Every item in one player's inventory swaps with every item in another player's inventory. Sometimes it'll just "copy" someone's inventory, clear mine and "paste" the contents of this person's inventory to my or someone else's inventory. Sometimes it'll stay forever like that and the previous inventory won't return, even after logout.

Here is my plugin list:
![image](https://user-images.githubusercontent.com/34654573/79809046-d1a3c180-836f-11ea-9101-8238017a1b76.png)


@ShaneBeee 
I was wrong - most of the code rely on those add-ons.
I'll try to replicate the issue without any add-on anyway, because the issue may still be caused by Skript itself.

**Comment by workonfire** [comment]
Unfortunately, I was not able to reproduce the issue without add-ons.
Sorry for the inconvenience.
