### ISSUE TITLE
Problem with "Skript"

### ISSUE THREAD

**Issue by Oxsi44** [SkriptLang/Skript#2936]
I need help with my skript.

When i try to write /sk reload or anything with skript, it says "an internal error occurred while attempting to perform this command minecraft". 

**My server is 1.14.4!**

Anyone that can help. Or were out for the same problem?

Thanks in advance! :)

**- Oxsi44**

**Comment by Govindass** [comment]
Skript version? startup errors?

**Comment by Oxsi44** [comment]
> Skript version? startup errors?

The latest version. Have also tried to 1.14.4.

**Comment by ShaneBeee** [comment]
When posting an issue, we provide templates to follow. These templates ask you to enter certain information that help us triage the issue.
You have deleted the template and given us absolutely no important information other than your server version.

Please follow the template in the future!
