### ISSUE TITLE
Mushroom Stem Sides Cannot be placed or detected.

### ISSUE THREAD

**Issue by Baezor1** [SkriptLang/Skript#2937]
### Description
Mushroom Stem block have sides (ex: North, East, Up, Down). Skript does not have any way I can find to actually detect these sides or place a block with the correct sides you want. The reason this is important is because for certain texture packs and plugins, you can reskin these mushroom stem blocks to have different textures. (I'm using a plugin call Oraxen to create items and block currently if that is important.)

### Steps to Reproduce
If you spawn in a block with one side west (_/setblock (coords) minecraft:mushroom_stem[up=false, down=false, north=false
, south=false, west=true, east=false]_), and run a skript to save the block, it wont save the side. You can check in F3 on the right side to see the sides.
### Expected Behavior
If you save with a variable,

### Errors / Screenshots

Skript Im using.
`on break of mushroom stem:`
`	set block to bedrock`
`	wait 2 seconds`
`	set block to {coolblock}`
`command /coolblock:`
`	trigger:`
`		set {coolblock} to player's targeted block`

Before Breaking the block.
![Screen Shot 2020-04-21 at 12 59 10 PM](https://user-images.githubusercontent.com/64096464/79898852-8a4e1d00-83d1-11ea-9c91-4269fb15e7c5.png)
After Breaking the block.
![Screen Shot 2020-04-21 at 1 10 25 PM](https://user-images.githubusercontent.com/64096464/79898907-9cc85680-83d1-11ea-89a2-f5f77042a8d4.png)

_There are no console errors._

### Server Information
* **Server version/platform:**       Paper 1.15.2
* **Skript version:**                2.5 Third Unstable Alpha

### Additional Context
This is my kinda dumb work around right now.
`on break of mushroom stem:`
`	cancel event`
`	set {x.%event-block%} to event-block's x-coordinate`
`	set {y.%event-block%} to event-block's y-coordinate`
`	set {z.%event-block%} to event-block's z-coordinate`
`	set {x.%event-block%} to round {x.%event-block%}`
`	set {y.%event-block%} to round {y.%event-block%}`
`	set {z.%event-block%} to round {z.%event-block%}`
`	set {x.%event-block%} to {x.%event-block%}-1`
`	set {y.%event-block%} to {y.%event-block%}-1`
`	set {z.%event-block%} to {z.%event-block%}-1`
`	#send "%{x.%event-block%}% %{y.%event-block%}% %{z.%event-block%}%" to player`
`	set block to bedrock`
`	wait 10 seconds`
`	execute console command "/setblock %{x.%event-block%}% %{y.%event-block%}% `%{z.%event-block%}% minecraft:mushroom_stem[up=false, down=false, north=false, `south=false, west=true, east=false]"`

**Comment by ShaneBeee** [comment]
I do agree this needs to be handled in Skript. Not just for the mushroom blocks but for all blocks.

Until Skript has something built in I recommend using SkBee's [**Block Data**](https://skripthub.net/docs/?id=4058) expression.

**Comment by Baezor1** [comment]
Okay, ill mess around with it. Thanks!

**Comment by ShaneBeee** [comment]
> Okay, ill mess around with it. Thanks!

You're welcome. In the future I'll look into adding something like this directly into Skript.

**Comment by Baezor1** [comment]
Okay, but should I close the issue or keep it open?

**Comment by ShaneBeee** [comment]
> Okay, but should I close the issue or keep it open?

Leave it open. Its a good reminder for us or anyone who wants to work on implementing this as a feature in Skript

**Comment by Baezor1** [comment]
Okay, thanks for the help!

**Comment by ShaneBeee** [comment]
Im going to close this issue as it was somewhat completed.

I think we (the team) can agree we'd never do an alias for this.
Skript 2.5 now offers block data for settings blocks, so this is totally possible to do.
