### ISSUE TITLE
Contains check not working

### ISSUE THREAD

**Issue by Reals7eel** [SkriptLang/Skript#2938]
### Description
I'm trying to check if a Beacon I'm placing has the name "Soul Generator" prior to placing it (the name of the item in the player's inventory), but doing a single contains check doesn't work at all.

### Steps to Reproduce
This doesn't work:
```
on place of beacon:
    if name of player's tool contains "Soul Generator":
        send "doesn't work"
```
but, this, annoying bulky way of doing it, does:
```
on place of beacon:
    if name of player's tool contains "Soul":
        if name of player's tool contains "Generator":
            send "works"
```

### Expected Behavior
Being able to just do `if name of player's tool contains "Soul Generator"` without doing multiple contains checks.

### Errors / Screenshots
None.

### Server Information
* **Server version/platform:**       1.15.2 (paper, 176)
* **Skript version:**                2.5 alpha 3

**Comment by ShaneBeee** [comment]
Works fine for me:

<img width="954" alt="Screen Shot 2020-04-21 at 7 11 11 PM" src="https://user-images.githubusercontent.com/20008482/79933113-e6319980-8403-11ea-86e0-22a8572de870.png">

BUT.... if I give myself a beacon with a name that has two different colours it doesn't work as you stated:
<img width="954" alt="Screen Shot 2020-04-21 at 7 12 48 PM" src="https://user-images.githubusercontent.com/20008482/79933192-298c0800-8404-11ea-9b43-9edaa8b2ebb4.png">


This isn't a bug... you are probably giving yourself an item with a name that has a color code in between SOUL and GENERATOR ... therefor no, the name ISNT "Soul Generator"

**Comment by Reals7eel** [comment]
yeah it was me being an idiot, my bad, I'll close this
It fixed after updating my servers paper version
using the same exact code
