### ISSUE TITLE
aliases-english.sk and aliases-german.sk don't create on first load

### ISSUE THREAD

**Issue by TheBrainOfThePanda** [SkriptLang/Skript#2939]
### Description

aliases-english.sk and aliases-german.sk are missing on some releases of Skript when downloading from the Github releases.
### Steps to Reproduce

Install Skript 2.4.1
Go to Plugins/Skript and see that aliases-english.sk and aliases-german.sk are missing.
### Expected Behavior

Plugins/Skript/aliases-english.sk and Plugins/Skript/aliases-german.sk exist.
### Server Information
* **Server version/platform:** Spigot 1.15.2      
* **Skript version:** Skript 2.4.1

**Comment by HYPExMon5ter** [comment]
Newer versions of skript do not generate these files; they’re stored within
the jar themselves

**Comment by ShaneBeee** [comment]
As Hype said, those files no longer generate in Skript 2.3+
