### ISSUE TITLE
remove all doesn't remove enchanted items

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2941]
### Description
when you use the `remove all` effect, if the item is enchanted it doesn't get removed

### Steps to Reproduce
`remove all diamonds from player's inventory`

### Expected Behavior
all diamonds including enchanted ones should be removed

### Errors / Screenshots
https://youtu.be/Dcir3kzlSmU

### Server Information
* **Server version/platform:** git-paper-155 (1.15.2)
* **Skript version:** 2.4.1-mh

**Comment by ShaneBeee** [comment]
Can you please try with the latest alpha release 2.5-alpha3?

I believe that was already fixed.

**Comment by MrScopes** [comment]
> Can you please try with the latest alpha release 2.5-alpha3?
are there any workarounds? I use minehut

**Comment by ShaneBeee** [comment]
oh I didn't see even see that.
Then no, Minehut uses a fork, you'll need to report them.

**Comment by MrScopes** [comment]
found a workaround
`remove all items from player's inventory where [input contains diamond]`
