### ISSUE TITLE
Skript Loading Error

### ISSUE THREAD

**Issue by annemettean** [SkriptLang/Skript#2942]
### Description

If there is a long time between each time I reload my skripts, then my server crashes. But if I reload the same skripts shortly, my server does not crash. 

### Errors / Screenshots

https://pastebin.com/PN64uN8Q

### Server Information
* **Server version/platform: git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2)       
* **Skript version: 2.4.1

**Comment by Romitou** [comment]
Seems to be related to #2355.
Please test only with the Skript plugin.

**Comment by Govindass** [comment]
you need to increase your server's timeout, it is not Skript issue
