### ISSUE TITLE
Smoke in campfire

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2947]
Can you add "increase campfire's smoke by 2". It should increase the smoke. And just add an event where place under campfire 2x of hay bale should increase the smoke by 2x.

**Comment by ShaneBeee** [comment]
> Can you add "increase campfire's smoke by 2". It should increase the smoke. 

Theres already aliases for a campfire and a signal campfire
```yaml
{waterloggable} {lightable} campfire¦s = minecraft:campfire
{waterloggable} {lightable} signal[ing] campfire = minecraft:campfire[signal_fire=true]
```
There is no way to increase it by 2. Its either a normal campfire or a signal campfire. Its a block state.

> And just add an event where place under campfire 2x of hay bale should increase the smoke by 2x.

Thats not how campfires work, nor are we going to make up an event for something so specific as that.
