### ISSUE TITLE
loop-entities will not get killed

### ISSUE THREAD

**Issue by marcellmit2l** [SkriptLang/Skript#2948]
If I try to kill an sheep or something, It is not working if it wants to specify exactly
only if i say is not a player or its a animal then the get killed

The Sheep will **not** be killed:
```
on place of stone:
    loop all entities in radius 10 of event-location:
        loop-entities is sheep:
            kill the entity
```
but the player does:
```
on place of stone:
    loop all entities in radius 10 of event-location:
        loop-entities is player:
            kill the entity
```
This works (verything is killed except the player):
```
on place of stone:
    loop all entities in radius 10 of event-location:
        loop-entities is not a player:
            kill loop-entity
```
works also;
```
on place of stone:
    loop all entities in radius 10 of event-location:
        loop-entities is a animal:
            kill loop-entity
```

**Get no Errors**

**Server version:** Spigot 1.14.4-R0.1-SNAPSHOT)

**Skript version:** 2.4.1

**Comment by ShaneBeee** [comment]
I don't see any issue here.
When you use the syntax correctly it seems like it works.
When you use the syntax incorrectly it doesn't work.

Not sure what else to tell ya here.

**Comment by ShaneBeee** [comment]
Closing this due to no response.
As stated previously this isn't a Skript issue, this is user error.
Correct code would be:
```vb
on place of stone:
    loop all entities in radius 10 of event-location:
        loop-entity is a sheep:
            kill loop-entity
```
Above code works as intended.
