### ISSUE TITLE
death bug

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2949]
### Description
when users die, they die but just stand there. they can still move around like nothing happened, and they get healed.

### Steps to Reproduce
```
on death of player:
	attacker is a player
	attacker is not victim
	if attacker's tool isn't air:
		cancel event
		set {_l} to join lore of attacker's tool with nl
		set {_item} to "<tooltip:&c%name of attacker's tool ? type of attacker's tool%%nl%&7%enchantments of attacker's tool ? ""&7No Enchants""%%nl%&7%{_l} ? """"%>&c%name of attacker's tool ? type of attacker's tool%&r"
	send formatted "&c%attacker% &7killed &c%victim% &7with &c%{_item} ? type of attacker's tool%&7." to all players
```

### Expected Behavior
users should die and get teleported to spawn

### Server Information
* **Server version/platform:**  git-paper-155 (1.15.2)
* **Skript version:** 2.4.1

**Comment by ShaneBeee** [comment]
This isn't an issue with Skript, its an issue with Paper.
Try update your paper version, you're 65 versions behind.

**Comment by MrScopes** [comment]
> This isn't an issue with Skript, its an issue with Paper.
> Try update your paper version, you're 65 versions behind.

why is it only when I add this script?

**Comment by ShaneBeee** [comment]
because you are cancelling a death event, and apparently that doesn't work well in paper.

**Comment by MrScopes** [comment]
> because you are cancelling a death event, and apparently that doesn't work well in paper.

holy shit I just noticed that lmaoo
