### ISSUE TITLE
MySQL variable problem

### ISSUE THREAD

**Issue by PuchiGFX** [SkriptLang/Skript#2952]
I have a bungeecord with 2 servers connected with the same MySQL database for variables.
Currently im using it for a ban system which can punish players that never joined the server.
And i got one problem with that.
For example, when i ban a player who never joined before in server 1 it shows this:
https://prnt.sc/s72aoz (Test is the player i banned)
But when i check the same variable in server 2:
https://prnt.sc/s72bbo
Using PaperSpigot 1.15.2-R01 and Skript 2.4.1

**Comment by Pikachu920** [comment]
using the same variable file for different servers isn't supported
