### ISSUE TITLE
Delete variable not working in MySQL

### ISSUE THREAD

**Issue by PuchiGFX** [SkriptLang/Skript#2953]
I have a MySQL system for a bungeecord server.
When i set a variable in survival server everything is okey:
https://prnt.sc/s7hdct
When i go to lobby server and i delete the variable stills okey:
https://prnt.sc/s7hdsh
But when i go back to survival server it stills there:
https://prnt.sc/s7heag
Its that a bug?
Using PaperSpigot 1.15.2-R01 and Skript 2.4.1

**Comment by Pikachu920** [comment]
using the same variable file for different servers isn't supported
