### ISSUE TITLE
"On inventory click" event does not work properly.

### ISSUE THREAD

**Issue by Blacksoul16** [SkriptLang/Skript#2955]
### Description
When the "on inventory click" event is used, it does not detect the item being clicked.
This doesn't happen in creative mode (and the output seems to be "inverted", because when I click on, for example, a stone, when I see the output of the event-item it says "air", and it should be "stone", but when I leave the item in a slot it says "stone". Or maybe I don't understand how it works), but it does in survival and adventure.

### Steps to Reproduce
Simply use the "on inventory click" event and test the output of the event-item.

Here's the code I used:

```
on inventory click:
    send "%event-item%"
    if event-item = {customitem::HotbarItem}:
        if gamemode of player != creative:
            cancel event
```

### Expected Behavior
It should detect the item I clicked, which is inside a variable (emerald named Abrir menú principal). And if it's the one I specified, it should cancel the movement of the item.

### Errors / Screenshots
Creative test 1 (click on the item):
![Creative test 1](https://user-images.githubusercontent.com/31175013/80561831-c5dd7e00-89b3-11ea-8c9c-e82288b7f05d.png)
Creative test 2 (leaving the item where it was):
![Creative test 2](https://user-images.githubusercontent.com/31175013/80561836-c8d86e80-89b3-11ea-8d78-c09302ed542c.png)
Survival test 1 (same as creative test 1)
![Survival test 1](https://user-images.githubusercontent.com/31175013/80561838-caa23200-89b3-11ea-8525-c131afdb2779.png)
Survival test 2 (same as creative test 2)
![Survival test 2](https://user-images.githubusercontent.com/31175013/80561842-cc6bf580-89b3-11ea-9a96-d57ddaa4ca33.png)
Also one of the times I reloaded the script, this appeared:
![Error](https://user-images.githubusercontent.com/31175013/80562033-6d5ab080-89b4-11ea-859f-d9768324d2d8.png)

### Server Information
* **Server version/platform:**       Paper version git-Paper-243 (MC: 1.14.4)
* **Skript version:**                2.5-alpha3

**Comment by TheLimeGlass** [comment]
Potentially related https://github.com/SkriptLang/Skript/issues/1488

**Comment by TPGamesNL** [comment]
Cannot reproduce, has possibly been fixed already
