### ISSUE TITLE
Parsing "hay bale" as item returns "<none>"

### ISSUE THREAD

**Issue by Hervus7** [SkriptLang/Skript#2957]
### Description
Parsing string "hay bale" or "hay block" or "redstone lamp" as item returns "\<none\>" instead of item.

### Steps to Reproduce
> command /lol:
	trigger:
		set {_a} to "hay block" parsed as item
		set {_a2} to hay block
		set {_b} to "dirt" parsed as item
		set {_c} to 30
		give {_c} of {_a} to player
		give {_c} of {_a2} to player
		give {_c} of {_b} to player

### Expected Behavior
As you see in my code I should get 30 dirt and 60 hay block. But I'm getting only 30 dirt and 30 hay block. Only item from {_a2} is given to me. Dirt in {_b} is to show that this method works as it have.

### Errors / Screenshots
No error on reloading, no additional error in console.

### Server Information
No addons only Skript
* **Server version/platform:**       Paper version git-Paper-227 (MC: 1.15.2) 1.15.2-R0.1-SNAPSHOT
* **Skript version:**                both 2.4.1 and 2.5-alpha3

**Comment by ShaneBeee** [comment]
It's because Hay Bale isn't an item its an item type.
Item = a physical item stack a player/inventory has
Item Type = an alias

Therefor you should be doing 
```vb
set {_a} to "hay block" parsed as item type
# instead of
set {_a} to "hay block" parsed as item
```
