### ISSUE TITLE
data value of clicked block

### ISSUE THREAD

**Issue by jrbq** [SkriptLang/Skript#2960]
`on leftclick on a cauldron:`
`    broadcast "%data value of clicked block%"`

Always returns 0 and seems to be doing the same with other blocks as well. Minecraft 1.15.2 with the latest Paper, Skript 2.4 (newest stable)

**Comment by TheBentoBox** [comment]
Data values no longer exist as of 1.13. You'll need to check the explicit block, e.g. `if clicked block is a filled cauldron`.
