### ISSUE TITLE
Check for potion effect types

### ISSUE THREAD

**Issue by legofreak1999** [SkriptLang/Skript#2962]
### Description

Can't seem to find a way to check for potions/effects.

### Steps to Reproduce

`If player has speed:`
`if player contains speed:`

### Expected Behavior

No reload errors and a proper way to check for effects. (Not getting just checking the property).

### Errors / Screenshots

Don't have these available rn.

### Server Information
* **Server version/platform:** 
Paper spigot 1.15.2 R0.1
* **Skript version:**                
2.4.1
### Additional Context

I looked a bit around seems to relate to:

`	@Override
	@Nullable
	protected PotionEffect[] get(final Event e) {
		return null;
	}
	`
https://github.com/SkriptLang/Skript/blob/a35311ce12d156883a5688c43650ce3a229e7518/src/main/java/ch/njol/skript/expressions/ExprPotionEffect.java

**Comment by ShaneBeee** [comment]
Im marking this as a low priority enhancement. I wouldn't necessarily call this as a bug, but rather a feature we should probably implement.

Im currently working on a new system for potion effects. Its in early stages but Im going to continue working on it before proposing it publicly.

**Comment by Wealthyturtle** [comment]
Closing in favor of #1458
