### ISSUE TITLE
1.13.2 -> 1.15.2 Stored skript variables no longer working / loading 

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2963]
Skript: Enabling Skript v2.5-alpha3
Spigot/Paper: 1.15.2

Hi there,
how to fix not loading variables when upgrading from 1.13.2 to 1.15.2?

I get hundreds of errors like this:
>.... [09:53:17 ERROR]: #!#! Cannot load the variable {guma::gui::test::slot::19} from the database 'default', because it cannot be loaded as an item type

Variables are stored in SQLite Database.

I tested how the "BLOB" looks like in sqlite database in 1.13.2:

`value €Hvalue:
  ==: org.bukkit.inventory.ItemStack
  v: 1631
  type: STONE_AXE
`

and in 1.15.2:

`value €Hvalue:
  ==: org.bukkit.inventory.ItemStack
  v: 2230
  type: STONE_AXE
`

Is there any skript command to update stored variables to get them working in newer versions of spigot?
Do I need to update to 1.14.4 first in order to get them working?
What does that "v: 2230" mean?

**Comment by bloggy** [comment]
I managed to access the guis with the items ingame. But the errors in the console are still spamming on server start, event after saving the items in 1.15.2 again. This needs to be fixed somehow.

**Comment by Wealthyturtle** [comment]
Duplicate #2554
