### ISSUE TITLE
Infinite fireworks?

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2964]
Hi all,
is there any syntax or way to make infinite fireworks like it was possible in 1.13.2. with this syntax:

launch "BALL" firework at player timed 1 coloured "light blue", "white", "cyan", "light blue", "cyan", "light cyan", "light blue" and "white"

Thanks for your help!

**Comment by legofreak1999** [comment]
https://forums.skunity.com/threads/infinite-fireworks-in-1-15-2.11456/

**Comment by ShaneBeee** [comment]
Appears this was answered 👍

**Comment by legofreak1999** [comment]
But i needed to look in source to get it. Documentation still should be added.
