### ISSUE TITLE
Can't set variable to loop entity

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2965]
Skript: Skript v2.5-alpha3
Spigot: 1.15.2

```
command /test:
	trigger:
		loop all entities in radius 2 of player's location:
			set {_s} to loop-entity
```

Result:
https://i.imgur.com/FkAF1hI.png

**Comment by bloggy** [comment]
The above skript works but only if you change it to this:

```
command /test:
	trigger:
		set {_loc} to player's location
		loop all entities in radius 2 of {_loc}:
			set {_s} to loop-entity
```

**Comment by TheBentoBox** [comment]
Duplicates #946.  For some reason doing `%value%'s location` ends up converting the entities into their respective locations when iterating. Your workaround is what's needed for now.
