### ISSUE TITLE
Help With Errors (I'm very new to skript)

### ISSUE THREAD

**Issue by gabecorrcode** [SkriptLang/Skript#2968]
Hello, I have been trying to make a GUI menu to do some basic commands, but I am very new to this plugin and can not seem to solve some of the errors I'm having. here is my code at this point:
`command /steak:
     trigger:
          open chest inventory with size 3 named "&e&lSteak Menu" to player
          format steak slot 0 of player with white bed named "&b&lIsland" to run:
              is home
          format steak slot 4 of player with cooked beef named "&b&lHub" to run:
              warp hub
          format steak slot 8 of player with iron ingot named "&b&lResource World" to run:
              warp resource`

**Comment by ShaneBeee** [comment]
The issue tracker is for .... issues, not for asking for help using the plugin. 
Please use the forums or discords that can be found on my main page in the readme.
