### ISSUE TITLE
addons

### ISSUE THREAD

**Issue by AggerTV** [SkriptLang/Skript#2970]
### Description

It would be nice with a "/skript addons" command, that would give you how many, and what addons is installed on your server

**Comment by jaylawl** [comment]
dont add this...
just make yourself a script that does this

**Comment by AggerTV** [comment]
> dont add this...
> just make yourself a script that does this

Well that is not of very much help. 
Do you know about anywhere I can learn more about this topic?

**Comment by ShaneBeee** [comment]
I actually think have an addons command is a good idea.
I Also like the idea of just using the `/skript info` command, have it print its current messages (links to the docs and aliases) as well as the version and a list of aliases and their versions.

**Comment by jaylawl** [comment]
> 
> 
> > dont add this...
> > just make yourself a script that does this
> 
> Well that is not of very much help.
> Do you know about anywhere I can learn more about this topic?

intital thought on this would be to use skript-mirror to loop through the installed plugins on the server when using said command that youre proposing.
then you just check if they have named skript as a dependency and if so, add them to your addons list.

**Comment by jaylawl** [comment]
```

        for (Plugin plugin : Bukkit.getPluginManager().getPlugins()) {
            for (String dependency : plugin.getDescription().getDepend()) {
                if (dependency.equals("Skript")) {
                    //plugin is a skript addon
                }
            }
        }
```

just convert this to skript language

**Comment by AggerTV** [comment]
> ```
> 
>         for (Plugin plugin : Bukkit.getPluginManager().getPlugins()) {
>             for (String dependency : plugin.getDescription().getDepend()) {
>                 if (dependency.equals("Skript")) {
>                     //plugin is a skript addon
>                 }
>             }
>         }
> ```
> 
> just convert this to skript(-mirror) language

Thank you.

But you (@ShaneBeee sorry for ping), that this will maybe be added to some future update?

**Comment by ShaneBeee** [comment]
Yeah, ill start working on it.
Ps... you can just do `Skript.getAddons()` which will return a list of addons currently installed, instead of looping all plugins

**Comment by jaylawl** [comment]
> 
> 
> I actually think have an addons command is a good idea.
> I Also like the idea of just using the `/skript info` command, have it print its current messages (links to the docs and aliases) as well as the version and a list of aliases and their versions.

I don't neccessarily think it's a bad idea either - however the main skript version for minecraft 1.15 is still in alpha releases, while minecraft 1.16 is about to be released soon

also rip my code Skript.getAddons() sounds a lot better :-D

**Comment by ShaneBeee** [comment]
> however the main skript version for minecraft 1.15 is still in alpha releases

the latest stable release, 2.4.1, works on 1.15.2.
The alpha release is not targeted at any specific version.
So that doesn't really factor into the equation of this request.

**Comment by Pikachu920** [comment]
@jaylawl it's a little more complex than that. adding new features is a lot easier than fixing existing bugs, especially without introducing more bugs. due to that, there's not many people familiar enough with Skript's codebase to solve them and from that group most of us are pretty busy. if we put a hold on new features in favor of bug fixing, you could easily just end up getting neither.
