### ISSUE TITLE
Skript starts loading chunks stops server from responding.

### ISSUE THREAD

**Issue by lucasboss45** [SkriptLang/Skript#2976]
### Description
Skript starts loading chunks at random times which stops the server from responding.

### Steps to Reproduce
Issue happens at random

### Errors / Screenshots
https://pastebin.com/ukaTkqTa

### Server Information
* **Server version/platform:Paper-243 (1.14.4)**       
* **Skript version: 2.4.1**

**Comment by ShaneBeee** [comment]
My guess is you are attempting to set too many blocks in a large area over a very short period of time, which in turn crashes your server.

Hard to say though, you have no reproduction steps nor any code. 

Look over your scripts and try to pinpoint when this issue occurs. 

The lack of information here really makes this difficult to triage.

**Comment by lucasboss45** [comment]
None of my skripts contains any block setting.

**Comment by ShaneBeee** [comment]
Well Im not really sure what to tell ya here. With the lack of info theres really no way for us to figure this one out. 
Skript itself won't perform any tasks without you telling it to. Therefor it won't just randomly start loading chunks.

According to the error, you have some code which has a wait, along with checking a block type.

As I stated, without seeing code its quite difficult to figure out the issue. Im thinking maybe you're checking blocks in a large area, I really have no clue.

**Comment by lucasboss45** [comment]
It kinda is difficult to check all 20 skripts, but I'll focus on some that contains block type checking.

Also what's weird is that on the first "not responding" prompt the chunks around [-100, 50] get loaded. By 450 seconds the server is waiting for chunks at around [-1500, 500] which is what is really confusing.
