### ISSUE TITLE
Teleport error

### ISSUE THREAD

**Issue by mkko120** [SkriptLang/Skript#2977]
When I try to run my script (code below) it giving me some error.

code here:

https://pastebin.com/Sqqzyqeu

### Expected Behavior
I want to teleport across worlds without multiverse because multiverse spawn point is far away from my teleport destination

console log:
https://pastebin.com/6G5Q1YGk

regards,
mkko120

**Comment by ShaneBeee** [comment]
This is due to a user error, you are setting a local variable in one event, but attempting to use said local variable in another event (which is not possible)
