### ISSUE TITLE
Skript is red on /pl or /plugins

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [SkriptLang/Skript#2978]
### Description
I found out a bug that when I check /pl it always says Skript in red, I try /skript and /sk and it says Internal Error Occurred.  This is driving me crazy rn.

### Steps to Reproduce
To reproduce this bug or remake it. Install the latest version (2.4.1) and it says "Skript in light red, and so on the other plugins."

### Expected Behavior
I was expecting it to be running properly without it saying any error and should work. But that was not the case.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/48828036/81696874-8adc4f80-9475-11ea-9dbd-babe7da56679.png)

### Server Information
* **Server version/platform:**       I do not have access as I'm just only a moderator.
* **Skript version:**                <21.4>

**Comment by ThisIsACoolBoy** [comment]
After a while of checking the owner said "I will tell you the server type only. He said it is CraftBukkit / Bukkit"

**Comment by ThisIsACoolBoy** [comment]
Wait a sec in owners discord console it says because im using craftbukkit Its disabled for the reason to prevent damage and unknown behaviour.

**Comment by Romitou** [comment]
Skript doesn't support Bukkit.

**Comment by AhmedFathey2008** [comment]
anytype is skript support?
paper?

**Comment by Romitou** [comment]
Skript support Spigot (so, PaperSpigot).
