### ISSUE TITLE
Tooltips on Replace effect

### ISSUE THREAD

**Issue by Fhalinkz** [SkriptLang/Skript#2979]
Tooltips does not work on "replace" effect

![image](https://user-images.githubusercontent.com/48141623/81784430-85c6e100-9505-11ea-87d6-997d773f35cc.png)

`replace "Zeus" in message with formatted "<ttp:&aZeus>Zeus<reset>"`

**Server version/platform:** Paper 1.15.2
**Skript version:** 2.4.1

**Comment by Romitou** [comment]
I believe that you cannot modify the message in this way, not being formatted basic, since it is also sent to the console.

**Comment by Fhalinkz** [comment]
But i want prefix in the message

(prefix)
![image](https://user-images.githubusercontent.com/48141623/81786560-8614ab80-9508-11ea-8b48-7c855c3fa278.png)

**Comment by ShaneBeee** [comment]
Formatting will no work in the message format, it needs to be done in a send message.
