### ISSUE TITLE
It said to me send to this site

### ISSUE THREAD

**Issue by ssaa1122** [SkriptLang/Skript#2982]
Description
Once server starts skript spams the console with this error

Steps to Reproduce
Restarted 
Deleted variables and backups
Updated skript to 2.5 alpha 3 and error is still there

Errors / Screenshots
https://pastebin.com/RrNYRFtT

Server Information
Server version/platform: 1.14.4-R0.1-SNAPSHOT
Skript version: 2.4

**Comment by ShaneBeee** [comment]
This is not a Skript issue, this is an issue with using an outdated version of Skript-mirror
Update your Skript-mirror to 2.0.0 and you should be good to go.
