### ISSUE TITLE
Skript command bug

### ISSUE THREAD

**Issue by Lennord** [SkriptLang/Skript#2985]
Hello, I have a bug in the Skript plugin, because when I do a reload or turn on the server, and its tells me on the console "/skript help" when I execute all the commands of the Skript plugin! Please correct this problem...

Version Minecraft; 1.15.2
Version Skript: 2.5-alpha3
Plugin: skBee, skQuery,skRayfall and Skript

Console error : https://pastebin.com/9sTX1HZK

**Comment by ShaneBeee** [comment]
Duplicate of #2752
