### ISSUE TITLE
uuids by default

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2987]
### Description
`use player UUIDs in variable names:` should be true by default

**Comment by ShaneBeee** [comment]
Why?

If you are going to suggestion something, you should explain why it should be done.

Me personally, I see no need to mess with defaults. If users want to change it, they can open up the config and change it. It's not hard to do.

**Comment by Govindass** [comment]
in my opinion it's far better to have it separated, so you can use %player% and %uuid of player% when you wish to

**Comment by MrScopes** [comment]
> Why?
> 
> If you are going to suggestion something, you should explain why it should be done.
> 
> Me personally, I see no need to mess with defaults. If users want to change it, they can open up the config and change it. It's not hard to do.

> in my opinion it's far better to have it separated, so you can use %player% and %uuid of player% when you wish to. having it default would just be attempt to account for stupidity of users who forget about uuid support, which would have potential to cause issues for some people as not everyone want to use uuids, temporary variables usually don't need them

you can always just use %player's name% if you want their name, it's definitely nice not having to set an additional variable just to get the uuid in functions. default %player% for uuids is just a lot better to have, and most people don't even touch the config so they don't even know what you can edit

**Comment by FranKusmiruk** [comment]
I agree that this should be on by default. In reality, this should have never been a config option, but instead, a conversion from old variable name serialization to the new one. 

The serialization of expressions in variable names should always be unique to the instance, names are not unique.

**Comment by Pikachu920** [comment]
another thing is that this would be a super breaking change. My 2 cents is that this is best implemented by moving the option to the config to something individually set in each script, so it works regardless of the configuration (really all script options should function like that)

**Comment by Wealthyturtle** [comment]
This would be a rather breaking change, considering that it would break all scripts that currently store data via player names, unless there's some automatic updating going on.

**Comment by jaylawl** [comment]
Don't fix what ain't broken

**Comment by FranKusmiruk** [comment]
> it's just a default config setting. if it involves forcing players rewriting their stuff because of this, it's not worth it

The setting would need a system which converts existing variables that use player as index to UUIDs, this would not be something users should notice.

Now, if you depend on the index being the player's name, your logic is flawed, since you could have used `player's name` to clearly state that you want so. Even if this is the case, I honestly doubt anyone depends on the variable being the player's name, people didn't have a way to get the index before dev30 so they couldn't have taken advantage of it.

I am in favour of changing this as long as we can manage to convert existing variables.

**Comment by jaylawl** [comment]
im positive you can do it - my point being that it's wasted energy for something unneccessary

**Comment by Wealthyturtle** [comment]
> > it's just a default config setting. if it involves forcing players rewriting their stuff because of this, it's not worth it
> 
> The setting would need a system which converts existing variables that use player as index to UUIDs, this would not be something users should notice.
> 
> Now, if you depend on the index being the player's name, your logic is flawed, since you could have used `player's name` to clearly state that you want so. Even if this is the case, I honestly doubt anyone depends on the variable being the player's name, people didn't have a way to get the index before dev30 so they couldn't have taken advantage of it.
> 
> I am in favour of changing this as long as we can manage to convert existing variables.

Correct me if I'm wrong, but don't player -> uuid conversions take some time? Assuming this is done under the hood without caching, lag can add up.

**Comment by Govindass** [comment]
I personally depend very much on player names as indexes, so this change would be very hurtful if not configurable

**Comment by Runakai1** [comment]
Also why should others change `player` to `player's name` when you can change `player` to `player's uuid`

**Comment by Pikachu920** [comment]
@Wealthyturtle you are thinking of uuid -> offline player.

**Comment by FranKusmiruk** [comment]
> Also why should others change player to player's name when you can change player to player's uuid

Because variables should be unique by default unless specified otherwise, player's name isn't unique and thus it should be the other way around.

> I personally depend very much on player names as indexes, so this change would be very hurtful if not configurable as I use just %player% and not %player's name%
>
> (I use this in variables that have lifetime of like up to 20 minutes, so UUID support isn't needed)

Again, if someone depends on this logic, they should be fully aware they are depending on a logic that is flawed and that they're a minority, it doesn't reflect what most part of people's expectations on the variable name. Besides, it wouldn't take more than a regex replace to make all those variables use the player's name expression, which most editors support.

**Comment by TheBentoBox** [comment]
> player's name isn't unique

I do lean towards agreeing with you @FranKusmiruk but want to note that this isn't really true, Mojang still requires that usernames be unique despite the transition over to UUIDs years ago.

The same might not be true in the future but that would require more changes on their part, e.g. how would commands handle the transition? Right now you can only target based on username so it'd be a very breaking change for vanilla servers and command block/data pack systems if usernames were no longer unique. Due to issues like that I honestly don't really see them ever making user names not unique.

**Comment by FranKusmiruk** [comment]
> The same might not be true in the future but that would require more changes on their part, e.g. how would commands handle the transition? Right now you can only target based on username so it'd be a very breaking change for vanilla servers and command block/data pack systems if usernames were no longer unique. Due to issues like that I honestly don't really see them ever making user names not unique.
I don't see that as an issue since making them not unique doesn't make resolving the player/offlineplayer instance impossible for users that have joined the server, they would just have to keep track of their UUIDs and they already do. My opinion on this is irrelevant to the issue though.

As for not unique, I meant that players can change it and have data loss without anyone noticing it. Let's say you have a backpack script and you saved the inventory items in a variable like `{backpack::%player%::items::*}`, but after a while they change of name and they lose all their items, the owner of the script doesn't know why. I must not be the only one thinking that logic is flawed.

**Comment by jaylawl** [comment]
i just realized that just setting this to use UUID by default would only concern newly generated configs and not touch those that already exist (and thus not interfere with people's already created content).

if that's the case i take my posts from earlier back and say: go for it.

but for the love of god do not touch people's existing databases. that'd just be arrogant and intrusive

**Comment by Govindass** [comment]
> 
> 
> > Also why should others change player to player's name when you can change player to player's uuid
> 
> Because variables should be unique by default unless specified otherwise, player's name isn't unique and thus it should be the other way around.
> 
> > I personally depend very much on player names as indexes, so this change would be very hurtful if not configurable as I use just %player% and not %player's name%
> > (I use this in variables that have lifetime of like up to 20 minutes, so UUID support isn't needed)
> 
> Again, if someone depends on this logic, they should be fully aware they are depending on a logic that is flawed and that they're a minority, it doesn't reflect what most part of people's expectations on the variable name is. Besides, it wouldn't take more than a regex replace to make all those variables use the player's name expression, which most editors support.

how is it flawed if the variable is only needed while the player is online? it is not flawed as UUID support isn't required in most cases of single session variable.

**Comment by FranKusmiruk** [comment]
> how is it flawed if the variable is only needed while the player is online? it is not flawed as UUID support isn't required in most cases of single session variable. I think backwards compatibility is far more important than such minor thing this is. I remember one of Skript's goals being good cross-version compatibility, with always-changing rules of Skript it is becoming harder and harder to update a script from example 1.8 times to now. I'd understand if it was something critical, but %player% does not need to be unique, it never has been. I am aware that %entity% defaults to entity's uuid and I've been negatively affected by such behavior when trying to just include entity type on the variable index, which I think is what would be more worth changing than making everything follow the same broken behavior.

What are you doing with variables that using entity UUIDs is affecting your workflow? It just sounds like a pretty edge case to me.

And you said it yourself, for single-session variables, that isn't what most variables are used for and even then, it shouldn't affect anyone unless you're depending on the variable name. As for updating, I think this is an exaggeration, how many times have you depended on the variable name for it to be hard to update? It is as trivial as regex replace as I said earlier, and also taking into account you can just set the option back to false to keep the same behaviour on your server.

**Comment by Govindass** [comment]
> 
> 
> > how is it flawed if the variable is only needed while the player is online? it is not flawed as UUID support isn't required in most cases of single session variable. I think backwards compatibility is far more important than such minor thing this is. I remember one of Skript's goals being good cross-version compatibility, with always-changing rules of Skript it is becoming harder and harder to update a script from example 1.8 times to now. I'd understand if it was something critical, but %player% does not need to be unique, it never has been. I am aware that %entity% defaults to entity's uuid and I've been negatively affected by such behavior when trying to just include entity type on the variable index, which I think is what would be more worth changing than making everything follow the same broken behavior.
> 
> What are you doing with variables that using entity UUIDs is affecting your workflow? It just sounds like a pretty edge case to me.
> 
> And you said it yourself, for single-session variables, that isn't what most variables are used for and even then, it shouldn't affect anyone unless you're depending on the variable name. As for updating, I think this is an exaggeration, how many times have you depended on the variable name for it to be hard to update? It is as trivial as regex replace as I said earlier, and also taking into account you can just set the option back to false to keep the same behaviour on your server.

to answer entity UUIDs question, it is because I needed non-unique variable list indexed by entity type, like "zombie", I used this to cache some custom AI calculations so they don't need to be re-calculated for every one, but can be re-used for entities of same type that are in 3x3 range within
