### ISSUE TITLE
Problem with expression "repair"

### ISSUE THREAD

**Issue by ghost** [SkriptLang/Skript#2989]
Description:
Hey! When I use an expression supposed to repair objects in my inventory, it turns the arrows (whether normal or so with a potion effect) into a bow or the opposite effect takes place. My bows become arrows.

Steps to Reproduce:
Put a few bows in your inventory, then 64 arrows. Type this command:
`command /repairall:
	trigger:
		repair all items of player's inventory`

Expected Behavior:
This should only repair tools that have durability.

Screenshots:
Before entering the command: https://prnt.sc/si51nv
After entering the command: https://prnt.sc/si51xp

Server Information:
Server version/platform: Paper-284 / 1.15.2
Skript version: 2.5-alpha3

**Comment by ShaneBeee** [comment]
I can confirm this.
For the time being I recommend looping the items and repairing the loop item.
