### ISSUE TITLE
Clear all potion effects

### ISSUE THREAD

**Issue by Zulfen** [SkriptLang/Skript#2990]
Thought this would be a good addition to Skript. :)

```(clear|remove) [all] [potion] effects (from|of) %players%```
...or have ```all potion effects``` as an expression.

There is currently no way to do this with modern Skript. Skellett supposedly has it, but actually appears not to have it at all. 

Not sure what else to add, so please reply to ask for extra info !

**Comment by ShaneBeee** [comment]
Closing in favour of a more in-depth issue report #1458
