### ISSUE TITLE
Particles 1.15.2

### ISSUE THREAD

**Issue by Zeldaboy1111** [SkriptLang/Skript#2991]
A issue I am having with particles in 1.15.2 Skript is that they go flying. This issue is not occurring to all particles.

i.e. a code snippet of the particles that fly off:
on left click:
    show 10 firework spark at the player

As you can see if you tested it yourself, particles go flying. This is the issue I am having with some particles, I recommend going through all of them and testing which do and which don't work.

[Here](https://gyazo.com/c33fedf0b668b149d86dd536294fca7c) is a short film of the issue.

Server version: 1.15.2
Skript version:  2.4.1

**Comment by ShaneBeee** [comment]
I could be wrong, but I think this may be an issue with Bukkit and not Skript.
I have done some particle stuff in plugins as well, with the same outcome.

**Comment by jaylawl** [comment]
Looking at the syntax skript provides for playing particle effects, there is currently no way to change this:

```
(play|show) %visual effects% (on|%directions%) %entities/locations% [(to %players%|in (radius|range) of %number%)]
```

There are lots of possible parameters for particles missing which would address the particles velocity etc.

For now, until this is enhanced in vanilla skript, you'll have to use an add-on. i'd recommend skript-mirror. here's a particle script using skript-mirror i used for particles:

```
import:
    org.bukkit.Particle

function spawnParticle(l: location, p: text, a: number, s: number, xo: number, yo: number, zo: number):
    ({_l}'s world).spawnParticle(Particle.valueOf(capitalized {_p}), ({_l}'s x-coord), ({_l}'s y-coord), ({_l}'s z-coord), round({_a}), {_xo}, {_yo}, {_zo}, {_s}, null, true)
```

**Comment by bluelhf** [comment]
@jaylawl Although fairly undocumented, it's possible to change the offset and speed of particles with Skript. `show redstone dust with offset of 1, 1, 1 and speed 0 at player` (Funnily enough, this also addresses OP's issue, but I think a speed of 0 should be default behaviour, anyways.)

**Comment by FranKusmiruk** [comment]
@bluelhf If my memory serves me right, we just use whatever speed Spigot has as the default value.

**Comment by Zeldaboy1111** [comment]
The fact that other syntaxes do work (but give a long reloading time) means that there has to be a bug with the code in Skript.
If you put another value than "0" at this syntax "show redstone dust with offset of 1, 1, 1 and speed 0 at player", it could do weird too. The speed of the particles has to be incorrect in Skript if other addons can make it work?
