### ISSUE TITLE
Problem with the function on rightclick

### ISSUE THREAD

**Issue by THEzombiePL** [SkriptLang/Skript#2995]
### Description

My script stopped working after changing from 2.4.1 to 2.5-alpha3. When I right click on the paper, nothing happens, the lower version worked fine. 

### Steps to Reproduce

Just use the "right-click" event and test to see if the message will be sent. 

***Here is the code I used:***
```
on rightclick with paper:
 if name of player's tool is "&3Test":
  broadcast "&cTest1"
  broadcast "&cTest2"
command /test:
 trigger:
  give paper named "&3Test" to player
```

### Expected Behavior

After right clicking, it should send the message "Test1" and "Test2".

### Errors / Screenshots
No errors are displayed. 

### Server Information
* **Server version/platform:** *1.15.2/PaperSpigot*    
* **Skript version:** *2.5-alpha3*

**Comment by ShaneBeee** [comment]
Appears to work as intended:
<img width="966" alt="Screen Shot 2020-05-19 at 2 35 21 AM" src="https://user-images.githubusercontent.com/20008482/82310588-73233080-9979-11ea-8df4-c1b3374d58e4.png">

Needless to say, I can not reproduce said issue.

**Comment by THEzombiePL** [comment]
Then I don't know why it doesn't work for me :(

**Comment by TheBentoBox** [comment]
I also can't reproduce this. I'm using paper.

**Comment by THEzombiePL** [comment]
It suddenly started working, I don't know why, but it works. Thank you for your help and sorry for the problem.
