### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by justxqh** [SkriptLang/Skript#2998]
### Description
When a player joins the skript plugin gets an error

### Steps to Reproduce
I dont know actually

### Expected Behavior
That theres no error

### Errors / Screenshots
https://pastebin.com/hkFLADpN
--->

### Server Information
* **Server version/platform:**      MC Version: 1.8
* **Skript version:**                2.1.2

**Comment by Romitou** [comment]
The stack trace indicates that it is SkRayFall.
In addition, you are using an unsupported version of Skript.

**Comment by TheBentoBox** [comment]
Insanely outdated Minecraft and Skript version. We do not support either of these.
