### ISSUE TITLE
Closed down again. for the last time:

### ISSUE THREAD

**Issue by MangoTangoMan12** [SkriptLang/Skript#2999]
The link:
https://pastebin.com/raw/t8FDQhkW

Question: Do you know what it means, and how do you fix it?

**Comment by TheBentoBox** [comment]
Stop reposting this or we'll need to discuss your posting privileges.

We closed this for a reason every time. Take the time to actually read and understand the comments left for you on the prior bug reports. You yourself said you're new here so it's astounding you're so sure of yourself in the validity of reposting this multiple times.

Do not post this again and without discussing on #2945.
