### ISSUE TITLE
GUI clicking twice

### ISSUE THREAD

**Issue by AggerTV** [SkriptLang/Skript#3000]
### Description

When you click in a gui menu, and use the "on inventory click" event to open another GUI, it clicks twice, 1 time for the actual click, and then it for some reason clicks again.

### Expected Behavior

When I click, it should only click 1 time, not 2 times.

### Errors / Screenshots

https://gyazo.com/c4ffaf979873e1bd1309c0ba2cce2466
here you see how it clicks twice (I added some delay, so it is easier to see)
I click the "previous page" button, and since I have set the "previous page" button in slot 40 of all my GUI's for consistency, it goes back 2 pages.
Also notice how I move my curser, and yet it still clicks slot 40 bringing me 1 more page backwards

### Server Information
* **Server version/platform:**      Paper version git-Paper-1618 (MC: 1.12.2)
* **Skript version:**                Skript version 2.5-alpha2

### Additional Context
I hope I formulated myself in somewhat of an understandable way, if not please tell me, and I will try and formulate it in another way

**Comment by AggerTV** [comment]
ohh yeah, this is the full code
https://pastebin.com/P9PwyRdP

**Comment by ShaneBeee** [comment]
When posting an issue, please send some reproducible code. We're not going to sift thru your 981 line script trying to reproduce the error.

That said, I wrote some simple test code:
```vb
on inventory click:
    send "Clicked: %clicked slot%"
```
I could not reproduce the error. As you can see in the picture each time I click its only fired once:
<img width="1306" alt="Screen Shot 2020-05-19 at 12 55 32 PM" src="https://user-images.githubusercontent.com/20008482/82372095-35052b80-99d0-11ea-8747-f9b8078efbb5.png">

**Comment by AggerTV** [comment]
here you can see what I mean.
Instead of going to "&a&lPAGE 2", it goes to "&4&lPAGE 3"
`command /gui:
	trigger:
		open chest with 5 rows named "&d&lPAGE 1" to player
		set slot 22 of player's current inventory to iron block named "&d&lPAGE 1"
		
on inventory click:
	if name of player's current inventory is "&d&lPAGE 1":
		cancel event
		if clicked slot is 22:
			open chest with 5 rows named "&a&lPAGE 2" to player
			set slot 22 of player's current inventory to gold block named "&a&lPAGE 2"
			
	if name of player's current inventory is "&a&lPAGE 2":
		cancel event
		if clicked slot is 22:
			open chest with 5 rows named "&4&lPAGE 3" to player
			set slot 22 of player's current inventory to diamond block named "&4&lPAGE 3"`

**Comment by ShaneBeee** [comment]
When trying to use your code:
```vb
> sk reload test
[13:18:52 INFO]: [Skript] Reloading test.sk...
[13:18:52 ERROR]: Can't understand this condition/effect: open chest with 5 rows named "&d&lPAGE 1" to player (test.sk, line 9: open chest with 5 rows named "&d&lPAGE 1" to player')
[13:18:52 ERROR]: Can't understand this condition/effect: open chest with 5 rows named "&a&lPAGE 2" to player (test.sk, line 16: open chest with 5 rows named "&a&lPAGE 2" to player')
[13:18:52 ERROR]: Can't understand this condition/effect: open chest with 5 rows named "&4&lPAGE 3" to player (test.sk, line 22: open chest with 5 rows named "&4&lPAGE 3" to player')
[13:18:52 INFO]: [Skript] Encountered 3 errors while reloading test.sk!
```
My guess is this code is from an addon. Please try replicate the error without addons

**Comment by ShaneBeee** [comment]
After further examining the code, and refactoring it to use Skript syntax and not syntax from an addon, I came to the conclusion this is user error.
The event isn't firing twice, its the fact you're using conditions incorrectly, one condition passes, you open a new gui, then it moves on to the next condition, which matches, because you didn't use an else if, therefor it executes that code as well.

**Comment by AggerTV** [comment]
ohh yeah, how stupid of me.
Thanks a lot, it works now :D
