### ISSUE TITLE
On portal issue

### ISSUE THREAD

**Issue by buccimichele5** [SkriptLang/Skript#3006]
### Description
The on portal: event seems to have issues. 1) It says that I can use cancel event to cancel the teleport but doesn't work, you still get teleported. Also as it looks like the on portal doesn't trigger, I tried multiple times and it doesn't get triggered.

### Steps to Reproduce
Just try use on portal event

### Expected Behavior
The on portal: should trigger when a player uses the portal

### Errors / Screenshots
No errors are getting sent
### Server Information
* **1.15.2 / Spigot**
* **Skript version: 2.4.1**

### Additional Context
This is an example of what I was trying to do (I will paste it because it might just me that I'm dumb)
https://pastebin.com/raw/dFMeBfs7

**Comment by FranKusmiruk** [comment]
Can someone else verify this is true? We do not interfere with the event in any way, meaning that any issues that you may encounter with it are most likely from Spigot and not from us.

**Comment by Wealthyturtle** [comment]
The pastebin link is now invalid, so I can't refer to your code.

Are you sure you're using the right portal event? There's like 3 portal events,

``
on portal enter
``
``
on player portal
``
and
``
on portal create
``

**Comment by buccimichele5** [comment]
Hello! I'm using the on portal enter: one. Since it looks like the Pastebin link is broken, here is another one: https://pastebin.com/raw/TxzchXHS
I tried asking on some discord support servers about skript about this code and many people told me it looks right (not sure 100%) I tried again with simpler things and saw that it looks like it's not working at all. (not sure if it's just my server problem or not, can't verify it)

**Comment by Wealthyturtle** [comment]
Sorry for the delay, @buccimichele5 can you try replicating this issue on 2.5-alpha3? Try seeing if 1.15.2 Paper changes anything too.

**Comment by buccimichele5** [comment]
Alright, I will try that.

**Comment by buccimichele5** [comment]
Doesn't seem to be working still

**Comment by Wealthyturtle** [comment]
Unable to replicate the event not firing and the event not being cancelled... could be a plugin issue.
