### ISSUE TITLE
Item Crack Particle not working

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#3012]
Information:
Skript: 2.5-alpha3
Paper: 1.15.2

using `play stone breaking at target block`
works fine. However using
`play tool breaking at {_spawnloc} to the player`
doesn't. (the spawnloc variable is working fine, as other particles spawn)
`play 10 bow item breaking at target block`
throws no ingame error.

Console error:
https://pastebin.com/3UsvftAh

Code:
```
command eating:
	trigger:
		set {_v} to vector from yaw 45 and pitch 45
		set standard length of {_v} to 0.5
		set {_spawnloc} to player's head location ~ {_v}
		send "%{_spawnloc}%"
		play 10 bow item breaking at target block
		play mob spawner flames at {_spawnloc} to the player```

**Comment by Wealthyturtle** [comment]
Could we have a regression test for this? Since this is a version-dependent fix
