### ISSUE TITLE
Escaping when parsing 

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#3013]
I am not entirely sure if this is an user error or something with skript.
Skript version: 2.5 alpha3
Mc: Paper 1.15.2

excaping | and () while parsing works and throws no error. The list is returning none, display name when debugging returns the correct name

Code:

```
command spawnentity:
	trigger:
		spawn a pig at player
		set display name of last spawned entity to "&b(&c&l!&b) &7[&6Level&7] &7| &c999"
	
command parse:
	trigger:
		set {_list::*} to display name of target parsed as "&b\(&c&l!&b\) &7[&6Level&7] &7\| &c%integer%"
		send "%{_list::*}%"

**Comment by Pikachu920** [comment]
you have to escape the `(`, `|`, `[` and `]` as they have special meaning in skript patterns which is what you're making via the parse expr. is that what you are reporting? i'm a little confused

**Comment by Runakai1** [comment]
I am just bad at formatting my code correctly on github.. I am escaping ( and | as the error told me when i wasnt escaping it but the list is returning none

**Comment by TPGamesNL** [comment]
It's probably because the `&` characters aren't converted in syntax strings from the parse expression.

**Comment by Runakai1** [comment]
> It's probably because the `&` characters aren't converted in syntax strings from the parse expression.

I removed the color codes and it is still returning none

```
command spawnentity:
	trigger:
		spawn a pig at player
		set display name of last spawned entity to "(!) [Level] | 999"
	
command parse:
	trigger:
		set {_list::*} to display name of target parsed as "\(!\) [Level] \| %integer%"
		send "%{_list::*}%"```

**Comment by bluelhf** [comment]
Does `(display name of target) parsed as "\(!\) \[Level\] \| %integer%"` work?

**Comment by Runakai1** [comment]
> Does `(display name of target) parsed as "\(!\) \[Level\] \| %integer%"` work?

It does. Maybe adding a warning to escape [ and ] would be handy

**Comment by FranKusmiruk** [comment]
Could you check whether the `parse error` expression shows that information?

**Comment by Runakai1** [comment]
> Could you check whether the `parse error` expression shows that information?

I hope I used it correctly. I Used the code without escaping [ ] and with escaping it. Both didn't return anything however escaping [ and ] resulted in correct parsing as stated previously
```
command parse:
	trigger:
		set {_list::*} to (display name of target) parsed as "\(!\) [Level] \| %integer%"
		send "%{_list::*}%"
		send "%parse error%"

**Comment by Runakai1** [comment]
Is this being worked on?

**Comment by TPGamesNL** [comment]
You wouldn't really be able to add a warning for this, since the syntax `\(!\) [Level] \| %integer%` is valid, `[]` denoting an optional group
