### ISSUE TITLE
looping blocks

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#3014]
I am not entirely sure if that is intended behaviour:

Skript: 2.5 alpha3
paper 1.15.2

the first command works but the second  doesn't

```

command loop:
	trigger:
		if "%all blocks in radius 1 of player%" contains "sand block":
			send "SAND!"
			
command loop2:
	trigger:
		if all blocks in radius 1 of player contains sand block:
			send "SAND!"

**Comment by Wealthyturtle** [comment]
Try testing with loop all blocks? And then using conditionals to test for sand?

**Comment by bluelhf** [comment]
I don't know whether it's intended or not, but it sounds like it'd be expected. Command 2 is checking if a list of blocks contains an item type. For a better solution, I'd use the following:
```
command loop3:
    trigger:
        if size of (all blocks in radius 1 of player) where [type of input is sand block] > 0:
            send "SAND!"
```

**Comment by Runakai1** [comment]
> I don't know whether it's intended or not, but it sounds like it'd be expected. Command 2 is checking if a list of blocks contains an item type. For a better solution, I'd use the following:
> 
> ```
> command loop3:
>     trigger:
>         if size of (all blocks in radius 1 of player) where [type of input is sand block] > 0:
>             send "SAND!"
> ```

That's irritating since placing blocks etc is also used by defining an item type

**Comment by FranKusmiruk** [comment]
This should work as there's a comparator for Block <-> ItemType

**Comment by Runakai1** [comment]
> Try testing with loop all blocks? And then using conditionals to test for sand?

Didn't see that. That works fine

**Comment by TheLimeGlass** [comment]
Probably related to the contains syntax, it's been buggy for a long time. This should have been fixed though recently https://github.com/SkriptLang/Skript/commit/7cb8a903378e64f315f5f1ff754a39847e458e31
