### ISSUE TITLE
Disabling a Feature

### ISSUE THREAD

**Issue by Gagrgan-Minecraft** [SkriptLang/Skript#3016]
**How to disable a feature or change it in file 'plugins/Skript/features.sk'?**
Tried to disable or change `[skutil[ities] ]zip file[s] %strings% to zip[ file] %-string%`, but it seemed to be not working. Tried disabling it like `uk.tim740.skUtilities.files.EffZipFiles: [skutil[ities] ]zip file[s] %strings% to zip[ file] %-string%` or `EffZipFiles: [skutil[ities] ]zip file[s] %strings% to zip[ file] %-string%` but nothing happened.

**Comment by ShaneBeee** [comment]
This features.sk file currently does nothing, you can see more regarding the issue in #2769

**Comment by Gagrgan-Minecraft** [comment]
> This features.sk file currently does nothing, you can see more regarding the issue in #2769 

Thank you for the information!
