### ISSUE TITLE
Changing from Gamemode Spectator

### ISSUE THREAD

**Issue by farwl** [SkriptLang/Skript#3018]
### Description
I try to change my gamemode from Spectator, to Creative in this specific scenario, and it remains spectator. I've tried every work-around, and I've found it is an issue with Skript.

### Steps to Reproduce
Try the code below.
https://pastebin.com/raw/DnVexZFh

### Expected Behavior
Your gamemode should change to creative from spectator, instead, your gamemode remains spectator.

### Server Information
* **Server version/platform:**       Paper 1.15.2
* **Skript version:**                2.4.1

### Additional Context
This problem only occurs with spectator. I tried using the other gamemodes, and it worked fine.

**Comment by FranKusmiruk** [comment]
Please try without addons.

**Comment by farwl** [comment]
Just attempted it without any addons, just vanilla Skript, and the same thing still happens.

**Comment by Zulfen** [comment]
You are referring to the player as {_p} (a local variable, is it the player argument from a function?), which is not set in the command trigger. Use arg-1 (you only have one argument, which is a player, so that should work).

**Comment by farwl** [comment]
That makes no sense. There aren't any functions being used. I'm simply using a local variable 
![image](https://user-images.githubusercontent.com/44182379/83984952-5db07f00-a905-11ea-9e57-7717ea7b66d8.png)
That also doesn't really have anything to do with the actual bug with Skript.

**Comment by Wealthyturtle** [comment]
Tested with
```
command /t:
	trigger:
		set {_x} to creative
		set player's gamemode to {_x}
		wait 1 second
		set {_y} to spectator
		set player's gamemode to {_y}
		wait 1 second
		set {_z} to creative
		set player's gamemode to {_z}
```
Starting in creative and spectator gamemodes, it cycled through them correctly.

I also tried replacing ``{_x}``, ``{_y}`` and ``{_z}`` with the literal "creative" and "spectator", but still unable to replicate.
