### ISSUE TITLE
split by "||" not working... - High Priority 

### ISSUE THREAD

**Issue by emergenitro** [SkriptLang/Skript#3019]
Look, I know this may seem like #719 but, it's not because my version is dev25 and hence, is not working... I tried ("") and even [split "%{_lore::*}%" by "||"] 

I need help ASAP. Thanks in advance!!!

**Comment by emergenitro** [comment]
![image](https://user-images.githubusercontent.com/49610482/83222601-478b1c00-a1ab-11ea-8535-be4fff31a582.png)

**Comment by Vrganj** [comment]
Yeah, but have you tried ("string") split at "||"

**Comment by emergenitro** [comment]
hmm lemme try that!

**Comment by emergenitro** [comment]
No, but, I am using a complex method... Because the skript I'm making is a custom enchants skript!

**Comment by Vrganj** [comment]
Split by is working, whatever you're doing is wrong

**Comment by emergenitro** [comment]
set lore of player's tool to "%{_lore::*}%" split at "||"

How do I make it work with that?

**Comment by Vrganj** [comment]
I literally just told you to use () around the first string

**Comment by emergenitro** [comment]
okay okay one sec

**Comment by emergenitro** [comment]
![image](https://user-images.githubusercontent.com/49610482/83236685-7a8ed900-a1c6-11ea-933f-44b2b965845f.png)

There

**Comment by Vrganj** [comment]
Can't your read the error..? Just don't split the string

**Comment by emergenitro** [comment]
Bruh the lore will become

like Efficiency and Fortune and Flying And Explosive

**Comment by Wealthyturtle** [comment]
```
command /ex:
    trigger:
        set {_x} to diamond pickaxe
        set {_x}'s lore to split "1||2||3||4" at "||"
        broadcast "%{_x}'s lore%"
```
Run ``/ex``.
