### ISSUE TITLE
Found a bug today, not that important, but I still need this asap

### ISSUE THREAD

**Issue by SaltyPotata** [SkriptLang/Skript#3025]
Grass is functioning as grass block

```
on break of grass:
	if {blockregen} is true:
		if world is "world":
			wait 0.1 second
			add location of event-block to {grass::*}
			set event-block to air
			wait 20 seconds
			set event-block to grass
			remove location of event-block from {grass::*}
```

**Comment by ShaneBeee** [comment]
What exactly is the issue?

Also rather than deleting the template please fill it out see what have proper information regarding the issue at hand.

**Comment by SaltyPotata** [comment]
When I type grass it works for grass block but not for grass

**Comment by ShaneBeee** [comment]
> When I type grass it works for grass block but not for grass

Ahh, well that's because in Skript:
```
grass = minecraft:grass_block
short grass = minecraft:grass
```
