### ISSUE TITLE
Pls I Need Help With Variables!

### ISSUE THREAD

**Issue by PLSINEEDHELP213** [SkriptLang/Skript#3027]
Hi I Would Like to learn how to detect like if a variable has been cleared? please i need this!

**Comment by PLSINEEDHELP213** [comment]
like

Command /test:
 trigger:
  if {batman::*} is cleared:
   broadcast "Hi"

**Comment by TheBentoBox** [comment]
This is not the place to ask questions like this. In the future, if you need help, I'd recommend the [skUnity forums](https://forums.skunity.com/) or one of the many Skript Discord servers.

You can check if a list variable is empty by checking if its size is 0, and for a non-list variable you can just check if it `is set`.
