### ISSUE TITLE
Spigot server doesn't work due to skript

### ISSUE THREAD

**Issue by iamral** [SkriptLang/Skript#3030]
My spigot server doesn't work. It writes 
`[Skript] 3 log handlers were not stopped properly! (at ch.njol.skript.registrations.Classes.parse(Classes.java:470)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]`

I use this script https://www.spigotmc.org/resources/speedrunner-vs-assassin-dream.75578/

What can I do to solve this problem?

**Comment by iamral** [comment]
I have to add that sometimes my server starts, but it takes about 3-4 attempts to do it

**Comment by Govindass** [comment]
the script you've linked is made by a person who doesn't know much of what he's doing, he's using booleans as strings and similar, I'd recommend to find a better alternative.

**Comment by Wealthyturtle** [comment]
Duplicate #2992
