### ISSUE TITLE
On the newest version of skript (2.5 alpha 3), crash caused by reload skript

### ISSUE THREAD

**Issue by Ghostfish123** [SkriptLang/Skript#3031]
### Description
Involved method:
function findDistanceP(loc1: location, loc2: location) :: number:
    set {_result} to findDistance(x-position of {_loc1}, y-position of {_loc1}, z-position of {_loc1}, x-position of {_loc2}, y-position of {_loc2}, z-position of {_loc2})
    return {_result}
function findDistance(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number) :: number:
    set {_result} to ( ({_x1}-{_x2})^2 + ({_y1}-{_y2})^2 + ({_z1}-{_z2})^2 )^(1/2)
    return {_result}

### Errors / Screenshots

The server crashed by reloading the functions

**Comment by Wealthyturtle** [comment]
It's not a crash, it's a timeout. There's too many arguments in your function causing the parser to be lag.

**Comment by Wealthyturtle** [comment]
I can't find the issue that describes this, but I'm pretty sure this is a duplicate. You can try and mitigate this issue by reducing the number of arguments (consider having a list as the parameter instead?) Or you could try bracketing the parameters, e.g:
```
set {_result} to findDistance((x-position of {_loc1}), (y-position of {_loc1}), (z-position of {_loc1}), (x-position of {_loc2}), (y-position of {_loc2}), (z-position of {_loc2}))
```
