### ISSUE TITLE
Gui Item Saving Problem

### ISSUE THREAD

**Issue by nTrok** [SkriptLang/Skript#3032]
**Description:**
I was trying to make a custom storage chest gui and I encountered a problem when trying to save the amount of each item put into the gui to where only 1 of the item would be saved.

**Code:**
https://pastebin.com/p99NtBNx

**What it's supposed to do**:
It is supposed to save over the exact amount of items placed into the gui slot.

**Error Screenshot:**
![image](https://user-images.githubusercontent.com/66415857/83743341-d23ea180-a617-11ea-8f79-dd5c1b7f7204.png)

**Additional Info:**
I honestly don't know if this is a bug or if there is a way to fix this, LimeGlass said it seemed like glitch so i'm gonna assume his knowledge is correct and it is. Please respond if you have any knowledge that could help me out. Thanks!

**Comment by Runakai1** [comment]
You're saving the type which is in fact only one of an item. This was already stated in the discord channels

**Comment by Wealthyturtle** [comment]
... Use ``add 1 of loop-value to {storage::row1::%player's uuid%::*}``?
