### ISSUE TITLE
Anvil Inventory support

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#3035]
As the title already says I'd like Skript to have porper anvil inventory support. You can open anvil guis but they're not configurable. Neither setting slots nor getting them works. Using ThatPacketAddon can do that, however using the on packet event play_client_item_name event alters the bahaviour of setting slots of an inventory-variable and you have to click on the slot so the inventory updates. Updating with mirror doesn't work, setting slots directly works. If you need more information i'll be glad to give it. This is not a bug, it's a suggestion.

**Comment by ShaneBeee** [comment]
From my understanding, this is not something the Bukkit API allows.
You need to use either Packets or NMS, neither of which Skript supports.
