### ISSUE TITLE
Graphic glitch when potion effect apply

### ISSUE THREAD

**Issue by Katalijst** [SkriptLang/Skript#3038]
### Description
When the potion effect is applied, the item in hand is gone for a second and back in hand.
(Tested only on potion effect with particles hidden, may apply to regular potion effect too)

### Steps to Reproduce
Apply a potion effect every X time with an item in hand.

### Expected Behavior
It should not make the item disapear for a second.

### Errors / Screenshots
[https://youtu.be/Ohr-PWF4fdU](https://youtu.be/Ohr-PWF4fdU)
Check the sword in hand when the potion timing reset

### Server Information
* **Server version/platform:** git-Paper-283 (MC: 1.15.2)
* **Skript version:** 2.4.1 and 2.5 Alpha 3

**Comment by ShaneBeee** [comment]
From my understanding, this has nothing to do with Skript, this has to do with Bukkit and/or Minecraft itself.

**Comment by Wealthyturtle** [comment]
That's a Minecraft visual glitch.
