### ISSUE TITLE
Hotbar Slot broken in docs

### ISSUE THREAD

**Issue by OfficialDonut** [SkriptLang/Skript#3040]
### Description

Hotbar slot is broken in the docs.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/26726670/83979858-668e5a00-a8df-11ea-8fb9-f37214787983.png)

![image](https://user-images.githubusercontent.com/26726670/83979861-7148ef00-a8df-11ea-82c1-f0894a920da2.png)

**Comment by Wealthyturtle** [comment]
Yep, documentation bug.

**Comment by ShaneBeee** [comment]
Marking this as completed and closing.
This was fixed sometime after the 2.5-alpha2 (the current docs on the website)
You can see here in the latest docs: [**ShaneBee's Temp Docs**](https://shanebeestudios.com/docs/skript/2.5-beta1/expressions.html#ExprHotbarButton)
