### ISSUE TITLE
"on vehicle exit" event is triggered on vehicle enter!

### ISSUE THREAD

**Issue by Leonardo-Fiori** [SkriptLang/Skript#3043]
https://hastebin.com/ibavuwivuc.py

This code gets triggered whenever i enter a boat...

### Server Information
* **Server version/platform:** Paper build 334 1.15.2       
* **Skript version:** 2.4.1

**Comment by Wealthyturtle** [comment]
Just tested with boats and minecarts, cannot replicate the issue. Likely to be a user error.
