### ISSUE TITLE
Inventory comparison

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#3048]
Paper: 1.15.2
Skript: 2.5 alpha3

I think skript's metadata implementation needs to be redone as the following code resulted into a stackoverflow (I don't know if the NPE is still part of the metadata thing)

```
set metadata tag "firstJoinGUI" of player to chest inventory with 3 rows named "&cWelcome/Willkommen!"
on inventory close:
	if metadata tag "firstJoinGUI" of player is set:
		open metadata tag "firstJoinGUI" of player to player
```

Error:
https://pastebin.com/1CTAuPFh

**Comment by Pikachu920** [comment]
it's got nothing to do with metadata - the inventory is just closing as soon as you open it causing an infinite loop and eventually a stackoverflow

**Comment by Runakai1** [comment]
> it's got nothing to do with metadata - the inventory is just closing as soon as you open it causing an infinite loop and eventually a stackoverflow
> 
> i believe you have to wait a tick before opening the inventory

Adding a delay helped. Thanks. I've just heard that Skript's metadata implementation is not very well(?) therefore I added it and assumed it was because of that. But also comparing an inventory with multiple metadata tags to (X, Y or Z) takes so long to execute anything after the condition

**Comment by Pikachu920** [comment]
i wrote the metadata implementaiton, what types of things aren't working for you? maybe we can get another issue open to fix them

**Comment by Runakai1** [comment]
> i wrote the metadata implementaiton, what types of things aren't working for you? maybe we can get another issue open to fix them

The only thing I have found yet is what I stated with the inventory comparison. 

```
if event-inventory is metadata tag "", "" or "" of player 
```
Skript kinda struggles with it

**Comment by FranKusmiruk** [comment]
That's actually an issue aside from metadata, comparing inventory instances doesn't work. The same things happen when comparing a virtual inventory from a variable and the one open to the client when they're the same. Don't remember the exact details but I believe it has to do with serialization.

**Comment by Runakai1** [comment]
> That's actually an issue aside from metadata, comparing inventory instances doesn't work. The same things happen when comparing a virtual inventory from a variable and the one open to the client when they're the same. Don't remember the exact details but I believe it has to do with serialization.

You guys can rename the title or close this issue then. I don't really know if it's still qualified as a bug or if the title is misleading.

**Comment by FranKusmiruk** [comment]
> You guys can rename the title or close this issue then. I don't really know if it's still qualified as a bug or if the title is misleading.
Renamed it for a better understanding of the issue.

**Comment by TheLimeGlass** [comment]
Wait what? This code works fine for inventory comparison in 2.5-Alpha-5
```vb
command /test:
	trigger:
		set {_inventory} to chest inventory with 3 rows named "&6Test"
		add 1 diamond to {_inventory}
		set metadata "inventory" of player to {_inventory}
		open metadata "inventory" of player to player
		set {inventory} to {_inventory}

on inventory click:
	cancel event
	if metadata "inventory" of player is event-inventory:
		broadcast "yup1"
	if {inventory} is event-inventory:
		broadcast "yup2"
	if current inventory of player is event-inventory:
		broadcast "yup3"
	if metadata "inventory" of player is {inventory}:
		broadcast "yup4"
```

**Comment by Wealthyturtle** [comment]
Closing in favor of #2218
