### ISSUE TITLE
194 log handlers were not stopped properly!

### ISSUE THREAD

**Issue by detraismc** [SkriptLang/Skript#3058]
i dont know what error is this, but it says i need to report this

>.... [11:24:34 WARN]: [Skript] Loaded class lib.PatPeter.SQLibrary.SQLibrary from SQLibrary v7.1 which is not a depend, softdepend or loadbefore of this plugin.
>.... [11:24:36 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.registrations.Classes.parse(Classes.java:470)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
>.... [11:24:36 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
>.... [11:24:36 ERROR]: [Skript] 11 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:878)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
>.... [11:24:36 ERROR]: [Skript] 6 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1593)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
>.... [11:24:36 ERROR]: [Skript] 194 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:253)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

**Comment by FranKusmiruk** [comment]
Please follow the template when reporting to the issue tracker. Also, this error often comes from skript-mirror, make sure to update it if you're using it. If the error persists, try without addons and report again.
