### ISSUE TITLE
Deleted/cleared variables do not get removed from the database

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#306]
Hello Bensku.
I'm creating a backpack Skript for my server. My saving system works perfectly, but the variables don't get removed from the variables.csv file. They appear as null, and as you should know, everytime someone opens the backpack it saves and deletes everything again. So the file gets so friggin' huge.

It would be a way better to completely and instantly delete them. The file will get huge if I use my script, and the lag will be real.

Also, another thing. I saw in a forum that the variables are saved using the main thread. Is it real? Shouldn't it be an async task?

**Comment by bensku** [comment]
Variable handling does indeed need some improvements.

**Comment by karingijs272** [comment]
thats true when you use delete {VARIABLE} some thimes he will not be deleted from the file and some times he will get Null in the file but you can easy fix it

```
command /test:
	trigger:
		set {VARIABLE} to "LOL"
command /remove:
	trigger:
		if {VARIABLE} is set:
			set {_delete} to {VARIABLE}
			remove "%{_delete}%" from {VARIABLE}
```
When you use this code the variable will be easy deleted :)

**Comment by FUZIK** [comment]
bensku, i reformulate the question.
when a> remove {example.variable}
it is removed from server RAM?

это может быть отличным временным решением:
https://forums.skunity.com/topic/2092/skutilities-v0-8-7-conversions-files-more-java-8-sk-2-2/218
https://forums.skunity.com/topic/400/skquery-reading-and-writing-yaml
http://umbaska.co.uk/

**Comment by Moderocky** [comment]
Closing in favour of #1020 with more details.
