### ISSUE TITLE
last spawned entity does not always return

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#3063]
### Description
last spawned entity does not always return, it'll return none in some cases

### Steps to Reproduce
simple code:

spawn a villager at location of {_p}
set {_villager} to last spawned entity

sometimes, with about 30% chance, {_villager} will be none while the villager did get spawned

### Expected Behavior

I expect it to return villager entity at ALL times
### Errors / Screenshots
None

### Server Information
* **Server version/platform:**        1.12.2 paper
* **Skript version:**                2.5 alpha3

**Comment by ShaneBeee** [comment]
I can not replicate this issue:

```vb
command /test:
    trigger:
        loop 20 times:
            spawn a villager at spawn of world "world"
            set {_v} to last spawned villager
            send "Villlager: &a%{_v}% &7UUID: &b%uuid of {_v}%" to console
        kill all villagers
```
<img width="932" alt="Screen Shot 2020-06-21 at 4 35 00 AM" src="https://user-images.githubusercontent.com/20008482/85223514-a8f07600-b378-11ea-9e3b-3da86e4bf9f3.png">

**Comment by Govindass** [comment]
> 
> 
> I can not replicate this issue:
> 
> ```vbnet
> command /test:
>     trigger:
>         loop 20 times:
>             spawn a villager at spawn of world "world"
>             set {_v} to last spawned villager
>             send "Villlager: &a%{_v}% &7UUID: &b%uuid of {_v}%" to console
>         kill all villagers
> ```
> 
> <img alt="Screen Shot 2020-06-21 at 4 35 00 AM" width="932" src="https://user-images.githubusercontent.com/20008482/85223514-a8f07600-b378-11ea-9e3b-3da86e4bf9f3.png">

oh you can, check the output more, some UUIDS are the same, you aren't deleting {_v}

**Comment by ShaneBeee** [comment]
Hmm, not sure then, Ill mark it as a bug.

**Comment by Govindass** [comment]
I think it should be of higher priority than just low, because many people in their scripts that work with entities use "last spawned entity" and with it being unpredictable, it can really destroy their logic (like it did in mine)

**Comment by ShaneBeee** [comment]
changed

**Comment by Govindass** [comment]
if anyone runs into the same issue before it is fixed, here's a temporary skript-mirror workaround:
```
import:
	org.bukkit.entity.EntityType
function entityType(type: string) :: string:
	switch {_type}:
		case "ender dragon":
			return "ENDER_DRAGON"
		case "TNT":
			return "PRIMED_TNT"
		case "ender crystal":
			return "ENDER_CRYSTAL"
		case "armor stand":
			return "ARMOR_STAND"
		case "dropped item":
			return "DROPPED_ITEM"
	return {_type}
expression (spawn|summon) [custom] %entitytypes% at %location%:
	get:
		return (expression 2).getWorld().spawnEntity((expression 2), EntityType.valueOf((entityType("%expression-1%")).toUpperCase()))
```

**Comment by Moderocky** [comment]
This issue does not appear to affect newer versions at all, from what I can see.
While it might still be happening, it has not appeared in over a dozen tests on either my local or remote servers. It seems to be limited to outdated MC versions from what I can tell (I'm going to test 1.13 through 1.15 today)

1.12.2 (issue present - there are duplicate indices):
![image](https://user-images.githubusercontent.com/14147477/86512686-2b0e7f00-bdfc-11ea-9976-66eaed407633.png)

1.16.1 (issue presumably absent - no duplicate indices):
![image](https://user-images.githubusercontent.com/14147477/86512534-036ae700-bdfb-11ea-8a42-7160a202bbb3.png)

**Comment by ShaneBeee** [comment]
So turns out this was just a silly little typo in VillagerData. 
Its always those teeny tiny things right!
