### ISSUE TITLE
Skript not saving variables

### ISSUE THREAD

**Issue by lidanthedev** [SkriptLang/Skript#3064]
### Description
Skript Doesn't save variables after a little while the server was online 

### Steps to Reproduce
I added my config.sk and variables
[Skript.zip](https://github.com/SkriptLang/Skript/files/4809798/Skript.zip)

### Expected Behavior
It should save variables

### Errors / Screenshots
https://pastebin.com/QiZ02Qyj

### Additional Context
This problem happens to me for a long time and no one knows how to fix it

**Comment by Wealthyturtle** [comment]
Everything looks good to me... not sure why this exception is being thrown.

**Comment by lidanthedev** [comment]
is there any way to fix it?

**Comment by lidanthedev** [comment]
did it god fixed cuz it's still happening to me

**Comment by TPGamesNL** [comment]
Duplicate of https://github.com/SkriptLang/Skript/issues/3453.
In this case the second thread that's using log handlers is the variable saving thread.

**Comment by startree236** [comment]
Did you solve the problem?
I am also having the same error..

**Comment by TPGamesNL** [comment]
> Did you solve the problem?
> I am also having the same error..

This issue has been fixed in 2.6-alpha1

**Comment by startree236** [comment]
> > Did you solve the problem?
> > I am also having the same error..
> 
> This issue has been fixed in 2.6-alpha1

Thank you for answer!
World Guard did not work in version 1.12.2, is there any solution?

**Comment by TPGamesNL** [comment]
> > > Did you solve the problem?
> > > I am also having the same error..
> > 
> > 
> > This issue has been fixed in 2.6-alpha1
> 
> Thank you for answer!
> World Guard did not work in version 1.12.2, is there any solution?

That is not related to this issue
