### ISSUE TITLE
Timespan issue

### ISSUE THREAD

**Issue by titustitus98** [SkriptLang/Skript#3069]
hey I am currently developing a prison server and I have encountered an issue when attempting to make a global multiplier timer:
Every time I run the command /setglobalmulti 2 10 seconds it generates an eternal error when trying to set a variable or something to the difference between now and the second argument which is parsed as a timespan and I can't figure out how to fix it, can anyone help me with this please?

here is the code:

`command setglobalmulti <number> <text>:
    permission: set.global.multiplier
    trigger:
        loop all players:
            set {global.multi::%loop-player's uuid%} to arg-1
        set {multi.active} to true
        set {global.multi.start} to now
        set {time} to arg-2 parsed as timespan
        set {_time} to difference between {global.multi.start} and {time} parsed as timespan
        broadcast "&8[&3&lMultiplier&8] &7A global multiplier of &fx%arg-1% &7has been set for &f%{_time}%"`

Error Message:
https://pastebin.com/KtBcn7VY

**Comment by APickledWalrus** [comment]
You’re comparing a date and a timespan, which is leading to an issue. I’m assuming {_time} is supposed to be how long the multiplier lasts? If I were you, I would take in a timespan as an argument. Based on the code you gave, you should just be able to send the user that timespan in place of {_time} variable.

**Comment by Wealthyturtle** [comment]
Duplicate #1001
