### ISSUE TITLE
Erreur...

### ISSUE THREAD

**Issue by redbourd** [SkriptLang/Skript#3073]
>.... [15:57:45 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.Statement.parse(Statement.java:54)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

Bonjour... j'ai cette erreur avec skript, pouvez vous m'aider ? Surement a cause de skript mirror...

**Comment by Pikachu920** [comment]
You are right, this is a skript-mirror issue

**Comment by redbourd** [comment]
> You are right, this is a skript-mirror issue

Ok but will it be corrected? Because we really need it ...

**Comment by TomYaMee** [comment]
This has already been fixed in skript-mirror 2.0.
