### ISSUE TITLE
java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by PanIntegralus** [SkriptLang/Skript#3075]
### Description
After loading the plugin, the error is spammed in the console, but appears loaded correctly using the command /plugins.

### Steps to Reproduce
- Use Skript 2.5-alpha3
- Use CraftBukkit version git-Spigot-a99063f-8ea9b13 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
- Start the server

### Expected Behavior
The plugin loads.

### Errors / Screenshots
Screenshot: https://i.imgur.com/RMIMxcg.png
Console: https://ghostbin.co/paste/c2de5

### Server Information
* **Server version/platform:** CraftBukkit version git-Spigot-a99063f-8ea9b13 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
* **Skript version:** Skript 2.5-alpha3

**Comment by Wealthyturtle** [comment]
Dupe #2903
