### ISSUE TITLE
Skript GUI

### ISSUE THREAD

**Issue by Woutdvv** [SkriptLang/Skript#3080]
https://pastebin.com/ZqMSpZQN

Hi! Check my ATM code, When I press a item in the gui, Nothing happened, I know their is a 1.12 bug, But i fixed it with de code i thing

Can someone help me?

**Comment by ShaneBeee** [comment]
This is an issue tracker for Skript, not a place to get help on how to write scripts.
Please use the skUnity/Spigot forums or one of the many Skript related discords for general code support.
