### ISSUE TITLE
{_p}'s uuid in functions

### ISSUE THREAD

**Issue by EcoMoney-Empire** [SkriptLang/Skript#3082]
### Description
Whenever I use a function and define player, I try to do: *set {_test.%{_p}'s uuid%} to "test"* it doesnt work, and there are errors.

### Steps to Reproduce
```vb
function test(p: player):
  set {name.%{_p}'s uuid%} to "Hello"
```

### Expected Behavior
I expect it to be able to use {_p}'s uuid, because it is a player.

### Errors / Screenshots

![Annotation 2020-06-26 142757](https://user-images.githubusercontent.com/64294865/85894234-f8400780-b7b9-11ea-9603-66821878c494.png)

### Server Information
* **Server version/platform:**       1.15.2
* **Skript version:**                2.5-alpha3

### Additional Context
None

**Comment by Pikachu920** [comment]
can you try `uuid of {_p}`?

**Comment by Runakai1** [comment]
This has been a bug for ages

**Comment by EcoMoney-Empire** [comment]
I know but it should be fixed because it would make things easier, thanks though.

**Comment by Wealthyturtle** [comment]
Duplicate #837, as people mentioned, use ``uuid of {_p}``
