### ISSUE TITLE
Clean up build system

### ISSUE THREAD

**Issue by FranKusmiruk** [SkriptLang/Skript#3084]
### Description
Right now, our build scripts are a bit of a mess, they do work but there's a lot of inconsistencies and repeated code in them. I am creating this issue so I don't forget what needs a change and also to receive input on things we could potentially improve in the overall building system.

As of now, the following changes are needed:
- [x]  Clean up the main build.gradle file:
    - [x] Remove pointless usage of GStrings in some places.
    - [ ] Make the release tasks more object-oriented to avoid repeating code.
    - [x] Remove uneeded repositories/dependencies.
    - [x] Update dependencies (Probably make use of dependabot?)
    - [x] Overall improvement of the code by making use of Groovy features.
    - [x] Remove or update maven publish code. Consider making use of Github Packages as maven repository if we end up doing the latter.
- [x] Update gradle wrapper (could probably automate this).
- [ ] Replace environment variables with configuration files or parametized tasks.
- [x] Replace bash scripts with gradle tasks.
- [x] Properly document or release cycle and any information needed for anyone to compile Skript.

Other things we may consider doing:
- [x] Either update ECJ and configure it properly or completely getting rid of it.
- [x] Target to newer Java versions.

That's basically all the issues I can recall as of now, if I forgot something or you have a suggestion, feel free to comment it here.

**Comment by TPGamesNL** [comment]
@FranKusmiruk this needs updating (or can be closed entirely)

**Comment by FranKusmiruk** [comment]
> @FranKusmiruk this needs updating (or can be closed entirely)

marked off the finished tasks, there's still some stuff to tackle from the list though so not closing yet.

**Comment by TheLimeGlass** [comment]
Completed majority of these
