### ISSUE TITLE
Stone stair alias issues

### ISSUE THREAD

**Issue by Khasar11** [SkriptLang/Skript#3089]
### Description
When giving a item type "stone stair" it gives a random stone stair type instead of the specific stone one. This must've been an oversight after they added regular stone stairs in a previous update

### Steps to Reproduce
give 1 of stone stairs to player
when you check with expression players tool it returns stone stairs for the normal stone stairs, but when you give stone stairs it gives a random one

### Expected Behavior
I expect it to give a minecraft:stone_stairs instead of stuff like polished granite stairs, mossy stone brick stairs etc...

### Errors / Screenshots
No errors but here's some SS'
http://prntscr.com/t92j0e
http://prntscr.com/t92jo5

### Server Information
Paper version git-Paper-27 (MC 1.16.1) Latest as of this
Skript version 2.5-alpha4

**Comment by TheBentoBox** [comment]
Fixed via [this commit](https://github.com/SkriptLang/skript-aliases/commit/935b2e882e5d2dc1f780a691aec37fd287fff2d1), will be in the next release but you can go grab the updated aliases from that repo now if you'd like.
