### ISSUE TITLE
Making a very long list breaks the entire script

### ISSUE THREAD

**Issue by Ikbenmathijs** [SkriptLang/Skript#3092]
### Description

When you set a list that contains a lot of long strings (haven't tested with other data types), it breaks skript and says an internal error occurred when reloading it. It also breaks loading all scripts on startup, and /skript reload all. (reloading individual scripts still work)

### Steps to Reproduce

1. create a really long list with strings in a script. (for example: https://pastebin.com/1MVhh92X breaks it for me (it's a list my script loops through for NPC dialog)
2. reload the script in game

### Expected Behavior

the script reloading successfully and me being able to use the list in my code

### Errors / Screenshots

my server log: https://pastebin.com/QrMjHSQw (it's a test server. It spits out a very big error)

### Server Information
* **Server version/platform:**  paper 1.16.1 #34, ubuntu 20.04 (64 bit), openjdk 11 (64 bit)     
* **Skript version:**  2.5-alpha4

**Comment by Romitou** [comment]
Some of the errors indicate that they came from TuSKe.
For the `Caused by: java.lang.StackOverflowError` error, see #2752

**Comment by Wealthyturtle** [comment]
Long lines will cause Skript to overflow, known issue. Use brackets.
