### ISSUE TITLE
Syntax "show anvil inventory to player" shows a hopper instead

### ISSUE THREAD

**Issue by lucasboss45** [SkriptLang/Skript#3096]
### Description
The syntax `show anvil inventory to player` shows a hopper instead, the syntax `show hopper inventory to player` shows an anvil instead.

### Steps to Reproduce
Use the syntax `show anvil inventory to player`

### Expected Behavior
It should show the written inventory type

### Errors / Screenshots
No errors

### Server Information
* **Server version/platform:** Paper-375 (MC: 1.15.2)
* **Skript version:** 2.4.1

### Additional Context

Plugins:
`
Plugins (29): Biosphere2*, ConsoleSpamFix, CorpseReborn, CustomItems, gProtector*, IllegalStack, NBTAPI, PlaceholderAPI, PluginHiderPlus, PlugMan, ProtocolLib, Scoreboard-revision*, SharpSK*, SkBee, skDragon, Skellett, SkinsRestorer, SkQuery, skRayFall*, Skript, skript-db*, skript-mirror*, SkriptJSON*, skUtilities*, Tablisknu, ThatPacketAddon*, Towny, TuSKe*, WolvSK`

**Comment by lucasboss45** [comment]
Issue only seems to occur when using "show" and not when using "open"

**Comment by buccimichele5** [comment]
Yep I can confirm this
