### ISSUE TITLE
Once again all menus are not working as they should :))))

### ISSUE THREAD

**Issue by Laukage** [SkriptLang/Skript#3100]
### Description

People can shift+click things out of my menus, thats basically it.

### Steps to Reproduce

https://paste.gg/p/anonymous/59a0996e66584ebaba0fd501592497df

### Expected Behavior

not to be able to?

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/46964809/86514514-0ffb3980-be13-11ea-9296-1b7030ac3cff.png)
A mcmmo error appears when this happens, however i think thats a mcmmo bug.

### Server Information
* **Server version/platform:** Paper-47 (1.16.1)      
* **Skript version:** Skript 2.5-alpha5

**Comment by Moderocky** [comment]
As the error states, this is an mcMMO error...
