### ISSUE TITLE
Links - Permission

### ISSUE THREAD

**Issue by AggerTV** [SkriptLang/Skript#3101]
### Description
Hello, I think it would be nice, if there was an permission node that allowed for users with the given permission node, to be allowed to send links in chat when the "parse links in chat messages:" is enabled.
This way, groups like Moderators could send links, but people up to no good, could not.

**Comment by FranKusmiruk** [comment]
Skript doesn't have many features by itself (with a few exceptions), and this can be done through a script. I'm rather skeptical about this but if people really want this feature, PRs are more than welcome.

**Comment by Moderocky** [comment]
I feel this is out of scope for Skript, it's something a script should do rather than being a feature of the plugin itself.
