### ISSUE TITLE
Using any command results in "/skript help" appearing in the chat

### ISSUE THREAD

**Issue by nitroxit** [SkriptLang/Skript#3104]
### Description
Im trying to run a basic skript. I put the .sk file into the skripts folder like normal and did /sk reload in chat only to get "/skript help" in return. I tested to see if the skript would work anyways and it didn't.

### Steps to Reproduce
Use /sk reload

### Expected Behavior
I expected for the skript to be reloaded to I could use it.  I also kind of expected something to go wrong since there isn't a stable release yet I just didn't expect this.

This is the error I get just upon starting the server or reloading all my plugins: https://throwbin.io/4KIyPVL

### Server Information
My server is on paper spigot 1.16.1 and I'm using the newest release of skript.

**Comment by Romitou** [comment]
Please see #2752
