### ISSUE TITLE
'uncoloured message' doesn't remove §x

### ISSUE THREAD

**Issue by GiraffeCubed** [SkriptLang/Skript#3106]
### Description
When trying to uncolour a message in the new hex colour code system, the opening §x is not removed from the result, making it difficult to work with hex coloured messages.

### Steps to Reproduce
```
on chat:
    send "%uncoloured message%"
```
Then send hex coloured message in chat
(See screenshot for resulting behaviour)

### Expected Behavior
§x should be treated as a colour code, and removed from 'uncoloured message'

### Errors / Screenshots
As you can see, the 'x' is left in
http://prntscr.com/tckvt7
(Giraffe was #FF0000, Cubed was &e)

### Server Information
* **Server version/platform:** Paper 1.16.1 (ver 73)
* **Skript version:** 2.5 Alpha 5

**Comment by APickledWalrus** [comment]
This will probably be fixed in #3098

**Comment by APickledWalrus** [comment]
![image](https://user-images.githubusercontent.com/29044720/86672672-e3871f00-bfc4-11ea-8d4c-1222e0842611.png)

patched if #3098 is merged

**Comment by GiraffeCubed** [comment]
I gave my affected code a test with #3098 and it is solved, thanks @APickledWalrus
