### ISSUE TITLE
loop-enchantments no longer working as it previously would

### ISSUE THREAD

**Issue by BurntValentine** [SkriptLang/Skript#3108]
### Description
Unable to pull the data in a similar way for an items enchantments.
Previously if you looped an items enchantments you'd use "loop-enchantment" to get the type of enchantment alone and could use "level of loop-enchantment" to get the level, now it only recognises "loop-value" which gives the name of the enchant and level in one go which doesn't work the same or as well as before

It also won't allow for "level of loop-value" to just pull the level when needed

### Steps to Reproduce
Simple command to test it - this used to reduce the level of all enchantments on the held item by 1 on a server running Skript2.5alpha3 on Paper 1.15.2 (build 376):

`command /test:
    trigger:
        loop enchantments of player's tool:
            remove 1 from level of loop-enchantment of player's tool`

Whereas on a Paper 1.16.1 server (build 74) with Skript 2.5alpha5 (no addons, just this) it won't accept "loop-enchantment" at all, only "loop-value" which outputs the enchant name and level as one variable, unlike "loop-enchantment", and you can't use "remove 1 from level of loop-value of player's tool" either.

### Expected Behavior
Exactly how loop-enchantment worked previously.

### Errors / Screenshots
No errors as such, aside from anything other than "loop-enchantment" giving "there's no loop that matches X" when looping enchantments, and "remove 1 from level of loop-value of player's tool" not working and giving the there's no loop that matches message too.

### Server Information
---When it works fine as expected:
* **Server version/platform:**   git-Paper-376 (MC: 1.15.2)
* **Skript version:**   2.5alpha3

---When it does not:
* **Server version/platform:**   git-Paper-74 (MC: 1.16.1)
* **Skript version:**   2.5alpha5

### Additional Context
Tested with and without addons, tested with the same skript between the two setups

Assuming this is a bug as nothing in the changelogs between these versions mentions any changes to this

**Comment by FranKusmiruk** [comment]
Needs confirmation of whether this is caused by the server upgrade (unlikely, but could happen) or skript upgrade.

**Comment by BurntValentine** [comment]
On further testing it appears it's not base Skript - I was sure it was and was working when I tested it yesterday with no addons... but apparently "loop-enchantment" doesn't work with base Skript, only works with Skellett and it's broken as of their latest update (where a lot of features were apparently removed because they're now in base Skript, but this one is clearly not) so reported it to them.
