### ISSUE TITLE
Unfounded error of an expression inside a variable

### ISSUE THREAD

**Issue by carlodrift** [SkriptLang/Skript#3110]
### Description
Skript doesn't understand the effect, it should.

### To Reproduce
```as
set {_a::%size of {_b::*}%} to true
```

### Server Information
* **Server version/platform:** Paper 1.15.2
* **Skript version:** Tried 2.4.1 and 2.5-alpha5

**Comment by FranKusmiruk** [comment]
I believe this is the same issue as #3082, can someone confirm?

**Comment by APickledWalrus** [comment]
> I believe this is the same issue as #3082, can someone confirm?

Looks like it. Main issue seems to be that putting a an expression that has a variable in it within a variable does not work.

**Comment by TPGamesNL** [comment]
Duplicate of #837
