### ISSUE TITLE
Incoherence of "is between" condition 

### ISSUE THREAD

**Issue by CarloDrift** [SkriptLang/Skript#3111]
### To Reproduce
```as
if 5 is between 10 and 1:
    broadcast "should be broadcast"
else if 5 is between 1 and 10:
    broadcast "should not be"
```

### Expected Behavior
In all literary logic, the first broadcast should be sent but not the second. That's not the case.

### Server Information
* **Server version/platform:** Paper 1.15.2
* **Skript version:** Tried 2.4.1 and 2.5-alpha5

**Comment by FranKusmiruk** [comment]
For sake of clearing things out, are both broadcasts sent or just the second?

**Comment by CarloDrift** [comment]
Only the second one.

**Comment by Matocolotoe** [comment]
For `(a) is between (b) and (c)` it seems like Skript is testing if `a > b` and `a < c` isn't it ?
