### ISSUE TITLE
on inventory close does not work for player's inventory

### ISSUE THREAD

**Issue by Alderheart** [SkriptLang/Skript#3113]
### Description

On inventory close works correctly for all inventories except the player's. This was fine until very recently, however not sure which one specifically changed it.

Example:

```
on inventory close:
	broadcast "closed"
```

Only broadcasts for containers, not the player inventory.

### Server Information
* **Server version/platform:**       1.16.1
* **Skript version:**              2.5 alpha 5

**Comment by FranKusmiruk** [comment]
This is something out of our control, see https://github.com/PaperMC/Paper/issues/3733.
