### ISSUE TITLE
random vector ruturn only positive

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#3135]
### Description
Use the expression random vector on skript 2.5 alpha5 return only positive axies

### Steps to Reproduce
`broadcast "%random vector%"`

**Comment by Anarchick** [comment]
It seems that it's not a bug but a normal utilisation of Vector#getRandom() https://papermc.io/javadocs/paper/1.15/org/bukkit/util/Vector.html#getRandom--
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprVectorRandom.java

So I suggest to add negative value support for the skript expression %random vector%

**Comment by ShaneBeee** [comment]
If that is the intended behaviour of Vector, please explain why Skript should break its intended behaviour and add negative values?

**Comment by Anarchick** [comment]
The question is why bukkit return only positive values ? it's intended or a mistake ? what is the benefit for only positive ?

When someone espect to use a random vector he would like to have  a vector with 360° yaw and 180° pitch.

Yes it's easy to make a vector with random values BUT :
- When you write some code, you try to optimize the performance ?
- Cause of the Skript parsing, the code needed to create the +/- random vector is not optimized as it should be.
- And after creating a random vector, you (maybe) need to set the length of this vector / normalize

What do you think about creating a new expression :
`[a] random vector of length %number%`
