### ISSUE TITLE
Vanilla Gui example

### ISSUE THREAD

**Issue by Zzheyd** [SkriptLang/Skript#3140]
Hello :)

Have Skript AND ONLY skript2.5-alpha5 AND latest paper 1.16.1(89).

Tuske is dead with skript version for 1.16+
So i decide te rework my gui and use vanilla gui, "vanilla gui.sk".

`#
# A vanilla example of a gui creation using Skript only
# Requires Skript 2.3+
#

command /gui:
	trigger:
		set {_gui} to a new chest inventory with 6 row with name "Gui Test"
		set slot 0 of {_gui} to stone
		open {_gui} to player
 
on inventory click:
	if name of event-inventory is "Gui Test":
		if index of event-slot = 0:
			cancel event
			send "You clicked on the slot 0 !"`

Right?
Beacause dont work fine, /gui work and open a menu and ... nothing 

"on inventory click:" do nothing, i can pick up a stone, zero cancel event, zero message : "send "You clicked on the slot 0 !""

Sorry for my bad english, thanks.

**Comment by ShaneBeee** [comment]
`if name of event-inventory is "Gui Test":`
this is already a know issue .... Skript hasn't had inventory names since I believe 1.14, due to a change in Spigot/Bukkit API

Refer to #2069

**Comment by Zzheyd** [comment]
Oh ... ok 

Did you have any idea for replacement "tuske"?

All of my gui is make with tuske ... work fine on 1.15.2, but tuske dont work on 1.16 ^^'

**Comment by ShaneBeee** [comment]
1) This isn't the place to be asking for addon support
2) The inventory name issue (as you can see from the issue I linked you) is completed and will be in the next update
3) Tuske GUIs work completely fine for me.

**Comment by FranKusmiruk** [comment]
> Oh ... ok
> 
> Did you have any idea for replacement "tuske"?
> 
> All of my gui is make with tuske ... work fine on 1.15.2, but tuske dont work on 1.16 ^^'

There's someone who forked TuSKe and removed everything but the GUI stuff, if you're interested on it: https://github.com/APickledWalrus/skript-gui
