### ISSUE TITLE
Skript is causing the server to sync load which crashes the server.

### ISSUE THREAD

**Issue by Laukage** [SkriptLang/Skript#3142]
### Description

Skript is causing the server to sync load which crashes the server, or atleast makes it unjoinable.

### Steps to Reproduce

ehm, i'm actually not sure - it just happens once in a while

### Expected Behavior

That it just works?

### Errors / Screenshots

https://paste.gg/p/anonymous/e70248f7af4f49e8b867e5f223bcb43d

### Server Information
* **Server version/platform:** Paper-90 (1.16.1)      
* **Skript version:** Skript-alpha5             

### Additional Context

The paper guys pointed the finger at skript when they saw the stacktrace, but yeah..

**Comment by Pikachu920** [comment]
can you link your issue on the paper repo? it might have some pertinent information

**Comment by Laukage** [comment]
> can you link your issue on the paper repo? it might have some pertinent information

It was in their paper-help channel on discord.
but Snow-pyon read it i think.

**Comment by Govindass** [comment]
maybe you could show the code? it seems to be related to a command that teleports you've created

**Comment by Laukage** [comment]
> maybe you could show the code? it seems to be related to a command that teleports you've created
i've created many, so that would be hard to send the specific "code" which causes it.

**Comment by Laukage** [comment]
I've investigated it a bit and i think i found the issue.
I have a "Portal" system working with regions.



![image](https://user-images.githubusercontent.com/46964809/88282301-935ccc00-cce9-11ea-89ed-739ed259f987.png)


Timings:
https://timings.aikar.co/?id=b4556f0035df4184856c8baebdaf2c1b

Github is doing something wierd to the code, so heres a picture aswell
![image](https://user-images.githubusercontent.com/46964809/88282428-d7e86780-cce9-11ea-900c-df71520d9d5f.png)

Code:
`
on region enter:
	if "%event-region%" contains "portal":
		if player has permission "Back":
			set {temp_::back::%uuid of player%} to location of player
		wait 1 tick
		set {_region} to "%event-region%"
		replace all " ","in" and "world" with "" in {_region}
		set {_loc} to yml value "Location.%{_region}%" in "Portaler"
		if {_loc} is set:
			teleport player to {_loc}
		else:
			message "&8&l[ &d&lPORTAL &8&l] &7Portalen er ikke opsat, kontakt portal ejeren."
`

**Comment by Moderocky** [comment]
If you put the code in three backticks (```) it'll be indented properly. :)

**Comment by Govindass** [comment]
an workaround for this would be to use skript-reflect and then use player.teleportAsync({_loc})

**Comment by Laukage** [comment]
I'm already doing that though.
