### ISSUE TITLE
Add support of hexadecimal colors for Minecraft 1.16+

### ISSUE THREAD

**Issue by antoinech2** [SkriptLang/Skript#3144]
### Description
Minecraft 1.16 added hexadecimal colors support for messages in JSON format used in /title, /tellraw,...

However, It seems to be impossible to use these colors with Skript's strings...
As we can do ` "<red>This is red" ` in Skript, we should be able to do something like: ` "<#ffab24>Great Orange !" ` or ` "<color:#ffab24> Great Orange !" `

I hope that it will be added soon ;)

**Comment by APickledWalrus** [comment]
This feature has already been added, and will be available in the next release 😁
See #3098

**Comment by antoinech2** [comment]
Thanks !
