### ISSUE TITLE
Error handling test event (Internal Development)

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#3152]
### Additional test feature
An event that makes sure it's contents error. Something for testing that errors are happening.

This came to my attention when I recently fixed a bug with errors not displaying.

For general error test
```vb
failing test "failing local variables":
        set {_incorrect} to "%{_notFound}%"

failing test "failing function not present":
        set {_function} to notFound()

failing test "failing no condition":
        if this condition doesn't exist:
                set {_error} to false

failing test "failing variable list":
        set {_variable} to true
        add "incorrect input and not list variable" to {_variable}
```
For defining the event to read on.
```vb
failing test "define attacker or victim message" on "org.bukkit.event.entity.EntityDamageByEntityEvent":
        message "Dummy message that should error due to victim or attacker not defined"

failing test "skript test error" on "ch.njol.skript.tests.runner.SkriptTestEvent":
        message "invalid event for attacker to be in %attacker%"
```
All possible from my research, except for faking an event, it's constructors need to be visible. Add to TestTracker, and error if the section doesn't error from a logger.

@bensku

**Comment by TPGamesNL** [comment]
Failing assert included in https://github.com/SkriptLang/Skript/pull/3629
