### ISSUE TITLE
java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by Maximillus** [SkriptLang/Skript#3163]
# Description

Nach dem Laden des Plugins wird der Fehler in der Konsole als Spam versendet, aber mit den Befehlen / Plugins korrekt geladen angezeigt.

Verwenden Sie Skript 2.5-alpha3
Verwenden Sie die CraftBukkit-Version git-Spigot-a99063f-8ea9b13 (MC: 1.15.2) (Implementierung der API-Version 1.15.2-R0.1-SNAPSHOT)
Starten Sie den Server

**Comment by Matocolotoe** [comment]
We need the whole stacktrace

**Comment by Wealthyturtle** [comment]
Duplicate #2752
