### ISSUE TITLE
sending without the need of strings 

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#3164]
It would be a very handy feature if you could just insert variables in the send effect. So you don't have to put "%%" around it and would just convert it into a string by itself. That would make debugging a bit less frustrating

**Comment by ShaneBeee** [comment]
This could be fairly simple to add, and I could see this being useful, basically
```
send {_myThing}.toString()
```

**Comment by Runakai1** [comment]
> This could be fairly simple to add, and I could see this being useful, basically
> 
> ```
> send {_myThing}.toString()
> ```

Exactly what I did with my mirror snippet. I'm looking forward seeing it being in skript 🍡

**Comment by Pikachu920** [comment]
@Runakai1 in case you want to the "true" skript string representation you can do it like so:
```
send Classes.toString({_myThing})
```
where `Classes` is `ch.njol.skript.registrations.Classes`

**Comment by Govindass** [comment]
I think same should then be done for function arguments, so you can include number in a string argument

**Comment by FranKusmiruk** [comment]
> I think same should then be done for function arguments, so you can include number in a string argument

I am not sure I am understanding the feature being requested here, how would you implement this in functions?

**Comment by ThatOneTqnk** [comment]
> > I think same should then be done for function arguments, so you can include number in a string argument
> 
> I am not sure I am understanding the feature being requested here, how would you implement this in functions?

I believe they mean that function parameters that accept strings should implicitly convert parameters that are not of the string type to a string
