### ISSUE TITLE
All spawn eggs now returning the bat egg

### ISSUE THREAD

**Issue by Wafffidooe** [SkriptLang/Skript#3167]
### Description
Hello!
I happened to notice that when displaying 1.9+ spawn eggs in GUIs, it will only display the donkey egg. No errors or anything received. 

### Steps to Reproduce
This is my code:
![20200719_024703](https://user-images.githubusercontent.com/47904309/87864608-99118500-c96a-11ea-8b3e-ac13ccbf11ac.jpg)

This is what it looks like:
![20200719_024433](https://user-images.githubusercontent.com/47904309/87864614-a9296480-c96a-11ea-8d98-22ab97486a4f.jpg)

I tried setting variables to the 1.9+ spawn eggs, didn't make a difference either. And as you see on my code, I also tried replacing "spawn shulker" with "shulker spawn egg" - no difference

Anddd I was right...
It happens in all kind of scenarios.
I just tested it with this:

`command /test:`
`    trigger:`
`        give player 1 spawn shulker`
(For some reason I can't add the tabs in here - but you get the point)
IT GIVES ME A DONKEY EGG

I tested it on all spawn eggs. These are the ones that returns the donkey egg:
Zombie Villager, Zombie Horse, Wither Skeleton, Vindicator, Vex, Stray, Skeleton Horse, Shulker,  Polar Bear, Parrot, Mule, Llama, Husk, Evoker and Elder Guardian 

Also, I don't have the opportunity to test this on the spawn eggs in versions higher than 1.12.2. But I bet they might have the same issue.

### Server Information
* **Server version/platform:**       1.12.2 Spigot
* **Skript version:**      latest release (2.5 alpha 5)

**Comment by Wafffidooe** [comment]
Anddd I was right...
It happens in all kind of scenarios.
I just tested it with this:

`command /test:
    trigger:
        give player 1 spawn shulker`

IT GIVES ME A DONKEY EGG

This is a bug/error!

**Comment by Wafffidooe** [comment]
I just upgraded Skript from 2.5-alpha5 to 2.5-beta2, and now all eggs return the bat egg, and I mean ALL eggs. Even the ones that used to work before

**Comment by APickledWalrus** [comment]
Should be fixed!
