### ISSUE TITLE
url no working

### ISSUE THREAD

**Issue by MisterPawlak** [SkriptLang/Skript#3170]
command /warn <player> [<text>]:
	permission: admin.mod
	permission message: &cNie masz do tego uprawnień!
	trigger:
		broadcast "&8&l[&7&l!&8&l] &4Gracz &a%argument 1% &4otrzymał/a ostrzeżenie od &a%player%&4."
		broadcast "&8&l[&7&l!&8&l] &4Powód: &a%argument 2%"
		set {_and} to "&"
		set {_reason} to argument 2
		replace all "ę" in {_reason} with "e"
		replace all "ó" in {_reason} with "o"
		replace all "ł" in {_reason} with "l"
		replace all "ś" in {_reason} with "s"
		replace all "ą" in {_reason} with "a"
		replace all "ż" in {_reason} with "z"
		replace all "ź" in {_reason} with "z"
		replace all "ć" in {_reason} with "c"
		replace all "ń" in {_reason} with "n"
		replace all " " in {_reason} with "_"
		set {_url} to "https://szesciennakraina.pl/indeksikfas.php?nick=%argument 1%%{_and}%source=%player%%{_and}%created=%now%"
		set {_result} to text from url "%{_url}%"

This code doesn't open the page at all.

**Comment by Wealthyturtle** [comment]
Skript doesn't have a URL expression...
