### ISSUE TITLE
Variables in item count do not work anymore

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#3187]
### Description
Variables in item count do not work anymore

### Steps to Reproduce
```
set slot 0 of player to {_count} of {_item}
```
it works if it isn't variables, but if both count and item is variable... nope

### Expected Behavior

I expect it to work, it worked before alpha6.
### Errors / Screenshots

a slot can't be set to entity {_item}'s {_count}attribute because the latter is neither an item type nor an item stack

### Server Information
* **Server version/platform:**        1.12.2 paper
* **Skript version:**                2.5 alpha6(rev1)

### Additional Context

None

**Comment by Govindass** [comment]
just got an error in another code that may be related:
remove {_count} of snowballs from victim's inventory

**Comment by APickledWalrus** [comment]
For the main issue, Skript thinks you are using the expression `%attributetypes% of %entities%`. This can be fixed by just changing the syntax, so we’ll most likely need to do that.

**Comment by TheLimeGlass** [comment]
> 
> 
> just got an error in another code that may be related:
> remove {_count} of snowballs from victim's inventory
> 
> [10:39:24 ERROR]: [Skript] Use 'attacker' and/or 'victim' in damage events (Paintball.sk, line 683: remove {_count} of snowballs from victim's inventory')

Post full code?

**Comment by Wealthyturtle** [comment]
> > just got an error in another code that may be related:
> > remove {_count} of snowballs from victim's inventory
> > [10:39:24 ERROR]: [Skript] Use 'attacker' and/or 'victim' in damage events (Paintball.sk, line 683: remove {_count} of snowballs from victim's inventory')
> 
> Post full code? @Govindass
> 
> Make sure you're only using `victim` in damage events.
> 
> Test this code on current 2.5-alpha-6 avoiding this bug and didn't get the victim error.
> 
> ```vbnet
> on damage:
> 	set {_count} to 5
> 	remove "{_count} of snowballs" parsed as itemtype from victim's inventory
> ```

This happens when you do ``{_x} of {_y}``

**Comment by Govindass** [comment]
> 
> 
> > just got an error in another code that may be related:
> > remove {_count} of snowballs from victim's inventory
> > [10:39:24 ERROR]: [Skript] Use 'attacker' and/or 'victim' in damage events (Paintball.sk, line 683: remove {_count} of snowballs from victim's inventory')
> 
> Post full code? @Govindass
> 
> Make sure you're only using `victim` in damage events.
> 
> Test this code on current 2.5-alpha-6 avoiding this bug and didn't get the victim error.
> 
> ```vbnet
> on damage:
> 	set {_count} to 5
> 	remove "{_count} of snowballs" parsed as itemtype from victim's inventory
> ```

the code on this event is huge, but more context to it would be:
```
		if metadata "burning" of projectile is set:
			{_cancel} is not set
			ignite victim for 3.5 seconds
			set {_count} to rounded (amount of snowballs in victim's inventory/100)*20
			{_count} is not 0
			remove {_count} of snowballs from victim's inventory
			send "&e&l%{_count}% &cof your snowballs burned!" to victim
```
the event is "on damage of player"

**Comment by ShaneBeee** [comment]
Im removing the completed label, as this has not been fixed and still throws an error.

**Comment by ShaneBeee** [comment]
Sorry my mistake, it has been fixed, the error was from a different issue.
