### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Woutdvv** [SkriptLang/Skript#3196]
Watch the error...
http://skungee.com/setekayise.md

https://prnt.sc/tnh9pr

**Comment by oHeckGage** [comment]
Try disabling each addon before reporting here. Also, stick to the format, please. If that doesn't work, reply here. (I'm not very active)

**Comment by ShaneBeee** [comment]
As oHeckGage stated, please try without addons.
It appears you're using a really old version of Skript-mirror which is most likely causing you issue.

**Comment by Woutdvv** [comment]
Where can I find a new version of Skript mirror?

**Comment by Woutdvv** [comment]
I have now downloaded skript-mirror v1.1.0 and I have a new error **http://skungee.com/gogoguwaro.md**

**Comment by ShaneBeee** [comment]
Closing due to this not seeming like a Skript error, but rather an error from Skript-mirror.
