### ISSUE TITLE
Cannot reload a skript!

### ISSUE THREAD

**Issue by Juan16236123** [SkriptLang/Skript#3211]
### Description
When I try to reload a Skript, it says "[Skript] Reloadng {name}.sk..." and then nothing else happens. I check console and it gives me some errors where I show under "Errors / Screenshots". The Skript works completely fine when the server starts up and I join. But when I do /sk reload {name} it doesn't work!

### Steps to Reproduce
I was doing nothing. I just restarted my server and then when I tried to reload a Skript, this just happened

### Expected Behavior
It should of reloaded the Skript and show the errors that occur or it successfully reloaded.

### Errors / Screenshots
"/sk reload hub" - https://imgur.com/JZCHviH (Nothing pops up)

### Server Information
Bukkit: 1.8.8-R0.1-SNAPSHOT
Java: 1.8.0_252 (OpenJDK 64-Bit Server VM 25.252-b09)
Minecraft: 1.8.8

Skript Version: 2.2-dev25

### Additional Context
This never happened for the 8 months I have been skripting. This started about 8 - 9 days (talking with SkUnity) but I decided to make a report here since they said they didn't know my issue. (I need to stay on 1.8.8)

**Comment by ShaneBeee** [comment]
Skript 2.2-dev25 is severely outdated and no longer supported. We're currently supporting 2.4.1 and 2.5(alphas)

Also, 1.8.8 is not supported by us.

**Comment by Juan16236123** [comment]
So what version should I change my server to?

**Comment by ShaneBeee** [comment]
> So what version should I change my server to?

We support 1.9.4+

**Comment by Juan16236123** [comment]
Is that going to change anytime soon? So I don't need to switch versions after?

**Comment by ShaneBeee** [comment]
> Is that going to change anytime soon? So I don't need to switch versions after?

Most likely not. According to bStats roughly 55% of servers run on 1.15.2+
We have no plans to support a severely outdated version of Minecraft.

This fork never has, and probably never will support 1.8.8

**Comment by Juan16236123** [comment]
Alright, I'll change my server from 1.8.8 to 1.9.4. Thank you!

**Comment by Juan16236123** [comment]
Wait, I have a question. My other KitPvP server has it working fine. But not working here.

**Comment by Juan16236123** [comment]
Working fine with 2.2 skript

**Comment by ShaneBeee** [comment]
I dunno.... and I will repeat, we have not and do not support Minecraft versions below 1.9.4

**Comment by Juan16236123** [comment]
Hello, I changed my server from 1.8.8 to 1.9.4. The error continues. My current Skript version is 2.4.1.

Code - https://pastebin.com/2QeQF8cz

**Comment by ShaneBeee** [comment]
IM not sure where the rest of the error is, but the stack trace is missing, anyways:
```
set slot 0 of player to compass with no nbt named "&aGame Selector" (hub.sk, line 2)
```
`with no nbt`<-- that is not Skript code, that is from an addon, so please report it to said addon.
