### ISSUE TITLE
Wrong showned color when using quotes with Hex colors

### ISSUE THREAD

**Issue by antoinech2** [SkriptLang/Skript#3213]
### Description
When you try to send message with hexadecimal color, the color showned is not the same if you use quotes around variable or not. The good color is when there is no quotes

### Steps to Reproduce
`set {test} to "<#171f96>Test"`
`send "%{test}%"`
Output: Wrong color
`send {test}`
Output: Correct color

### Expected Behavior
The colors should be the same with or without quotes

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/42295406/88461786-e760df80-cea6-11ea-998e-577e1ca88e11.png)

### Server Information
* **Server version/platform:** Minecraft 1.16.1 running Paper 1.16.1-R0.1-SNAPSHOT
* **Skript version:** 2.5-alpha6(rev1)

**Comment by APickledWalrus** [comment]
What if you do:

"%colored {test}%"

**Comment by Pikachu920** [comment]
actually, the first example should not work at all. skript isn't meant to do parse the colors (or any chat formatting) from variables.

**Comment by Pikachu920** [comment]
i take that back, it looks like colors work but nothing else

**Comment by antoinech2** [comment]
> What if you do:
> 
> "%colored {test}%"

Well, it's exactly the same, wrong color
