### ISSUE TITLE
Error when loading Skript

### ISSUE THREAD

**Issue by wooden-utensil** [SkriptLang/Skript#3215]
### Description
When I load Skript it doesn't load anything, spams errors in the console, then the server hangs

### Steps to Reproduce
I'm not sure

### Expected Behavior
Skript loads normally

### Errors / Screenshots

https://pastebin.com/raw/uFqE42um

### Server Information
* **Server version/platform:** 
* **Skript version:**

**Comment by ShaneBeee** [comment]
this is an error with outdated versions of Skript-mirror, not Skript.

**Comment by wooden-utensil** [comment]
thanks
