### ISSUE TITLE
PAPI change, expansion out-of-date

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#3229]
### Description
Spigot 1.16.1
PlaceholderAPI 2.10.7-DEV-25 and later

This expansion's PlaceholderAPI registration is out-of-date. See reference issue.
```
[12:41:40] [Server thread/WARN]: [PlaceholderAPI] Loaded class ch.njol.skript.Skript from Skript v2.5-alpha6 which is not a depend, softdepend or loadbefore of this plugin.
[12:41:40] [Server thread/ERROR]: [PlaceholderAPI] expansion class SkriptExpansion is outdated:
Failed to load due to a [NoSuchMethodError], attempted to use me.clip.placeholderapi.PlaceholderAPI.registerPlaceholderHook(Ljava/lang/String;Lme/clip/placeholderapi/PlaceholderHook;)Z
```

### Steps to Reproduce
Update PlaceholderAPI to latest dev builds.

### Server Information
* **Server version/platform:** `1.16.1`
* **Skript version:**  `2.5-alpha6`

**Comment by ShaneBeee** [comment]
Skript does not hook into PAPI. 
The expansion you are referring to is made separately from Skript.
https://www.spigotmc.org/resources/papi-skript-expansion.42205/
