### ISSUE TITLE
Can no longer modify the data/damage value of an item that is saved in a variable.

### ISSUE THREAD

**Issue by Adondriel** [SkriptLang/Skript#3237]
### Description
When saving player's tool in a variable, modifying the data value of that variable no longer modifies the data value of the item in the player's inventory.

### Steps to Reproduce
1. Save player's tool in a variable.
2. Modify the data/damage values of said variable.

### Expected Behavior
Modifying the data value of the item saved in the variable should update the data value of the item in the inventory it belongs to.
(This is the behavior that happens in Alpha-5 release)
Video of alpha-5 behavior:
![2020-07-27_278](https://user-images.githubusercontent.com/1113496/88599687-5d498000-d03a-11ea-889f-7402323e96ce.gif)

### Errors / Screenshots

Example of how I use this feature:
```
options:
	grapple: {shop.gen.misc.grapple.fullItem}
	hook: {shop.gen.misc.hook.fullItem}
	fishrod: fishing rod named "&eGrapple &cUnloaded" with lore "&eRight click to reload"
 
on right click with fishing rod:
	cancel event
	if {grapple.%player%.reloading} is false:
		damage tool of player by 64
		reloadAnimation(player, tool of player)
 
function reloadAnimation(p: player, i: item):
	set {grapple.%{_p}%.reloading} to true
	set data of {_i} to data of {_i} - 1
	wait 1 tick
	if data of {_i} is greater than 0:
		reloadAnimation({_p}, {_i})
	else:
		replace all {@fishrod} in {_p}'s inventory with {@grapple}
		set {grapple.%{_p}%.reloading} to false
```

### Server Information
* **Server version/platform:** 1.15.2 & 1.16.1
* **Skript version:** 2.5-alpha6(rev1)

**Comment by bluelhf** [comment]
I believe this is expected behaviour - when an item is saved in a variable, all that's stored is the item data (that is, it is pass-by-value) - you'd have to reapply the changes if you want the player's item to be synced with the variable.

![See this gif](https://blog.penjee.com/wp-content/uploads/2015/02/pass-by-reference-vs-pass-by-value-animation.gif)
The right side is what Skript is expected to do (and does.)

**Comment by Adondriel** [comment]
The behavior in previous releases was passing by reference, and that makes things a lot more efficient & manageable. Otherwise I have to track user behavior of item movement.

**Comment by FranKusmiruk** [comment]
Adondriel, I think you're actually looking for `slot` in the function instead of `item`.

**Comment by Adondriel** [comment]
> Adondriel, I think you're actually looking for `slot` in the function instead of `item`.

I think you're right, can you give me the syntax for that?

**Comment by FranKusmiruk** [comment]
```ruby
options:
	grapple: {shop.gen.misc.grapple.fullItem}
	hook: {shop.gen.misc.hook.fullItem}
	fishrod: fishing rod named "&eGrapple &cUnloaded" with lore "&eRight click to reload"
 
on right click with fishing rod:
	cancel event
	if {grapple::%player's uuid%::reloading} is not set:
		damage tool of player by 64
		reloadAnimation(player, tool of player)
 
function reloadAnimation(p: player, i: slot):
	set {grapple::%{_p}%::reloading} to true
	damage {_i} by 1
	wait 1 tick
	if damage of {_i} is greater than 0:
		reloadAnimation({_p}, {_i})
	else:
		replace all {@fishrod} in {_p}'s inventory with {@grapple}
		delete {grapple::%{_p}%::reloading}
```
with some marginal improvements to the code, but this should be what you're expecting. Items are and have been always passed by value, Skript was probably doing some sort of conversion ItemType -> Slot there which shouldn't have happened.

Anyways, I will close this as user-error, for more assistance, you can mention me in any of the Skript discord servers and I'll check it out.

**Comment by Adondriel** [comment]
@FranKusmiruk I have been doing a lot of testing, and I could not get your suggestion to work.
When I set the type to "slot" "damage of {_tool}" is not able to be retrieved. Here is my example code:
```
on right click with wooden hoe:
	set damage of player's tool to 40
	set {_tool} to tool of player
	# 40
	send "%damage of player's tool%"
	# <none>
	send "%damage of {_tool}%"
	repair(player, {_tool}, 0)

function repair(p: player, tool: slot, loopCount: number):
	#prevent inf loops, since this code doesn't actually work.
	if {_loopCount} is less than 100:
		send "1" to {_p}
		set {_dmg} to the damage value of {_tool}
		# <none>
		send "%{_dmg}%" to {_p}
		if {_dmg} is greater than 0:
			send "2" to {_p}
			repair {_tool} by 1
			send "%damage of {_tool}%" to {_p}
			wait 1 tick
			repair({_p}, {_tool}, {_loopCount} + 1)
```

If I set the type to "item" it functions as you would imagine, BUT does not replace the item (as it did in previous versions), and only modifies the item in memory.

The reason I need this behavior is so that I can use the damage meter as a way to show the cooldown on an ability, and this change breaks that behavior.
The only alternative risks deleting/replacing the wrong item from a player's inventory, and I don't want the player to have to stay hovered over the item while they are "reloading" the ability.

This description also lends credit to how I previously used the "tool" 
![image](https://user-images.githubusercontent.com/1113496/97770371-09eb4000-1b09-11eb-9c92-02d8fb66ec38.png)
