### ISSUE TITLE
Blocks From %block% to %block% doesn't work

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#3243]
### Steps to Reproduce

```
command /tx:
	trigger:
		set {_c} to chunk at player's location
		set {_pos1} to bottom northwest corner of {_c}
		set {_pos2} to top southeast corner of {_c}
		loop blocks from {_pos2} to {_pos1}:
			add 1 to {_x}
		send "%{_x}%" to player
```
{_x} always return 286. I used codes below to test wheather "corner of {_c}" functions correctly
```
command /tx:
	trigger:
		set {_c} to chunk at player's location
		set {_pos1} to bottom northwest corner of {_c}
                set {_pos2} to top southeast corner of {_c}
                teleport player to location of {_pos1}
                send "%location of {_pos1}%" to player
                wait 2 seconds
                teleport player to {_pos2}
                send "%location of {_pos2}%" to player
```

And as my expect,it works in a proper way

### Expected Behavior
{_x} should be "16x16x256=65536" instead of "286"

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/43756134/88810017-5f047680-d1e7-11ea-98ed-03263902cef3.png)

### Server Information
* **Server version/platform:** 1.15.2 Paper
* **Skript version:** 2.5 alpha3

**Comment by Anarchick** [comment]
https://skripthub.net/docs/?id=2054
It's normal

set (all blocks from block at player to target block) to stone
![2020-07-29_16 14 23](https://user-images.githubusercontent.com/34984003/88811258-a0306280-d1b6-11ea-960b-50f19a3de076.png)


set (all blocks within block at player and target block) to stone
![Uploading 2020-07-29_16.14.13.png…]()

**Comment by TUCAOEVER** [comment]
> https://skripthub.net/docs/?id=2054
> It's not a bug
> 
> set (all blocks from block at player to target block) to stone
> ![2020-07-29_16 14 23](https://user-images.githubusercontent.com/34984003/88811258-a0306280-d1b6-11ea-960b-50f19a3de076.png)
> 
> You should use this syntax :
> set (all blocks within block at player and target block) to stone
> ![2020-07-29_16 14 13](https://user-images.githubusercontent.com/34984003/88811428-d1109780-d1b6-11ea-8bdf-05932e49a6ca.png)

So i must install skquery for this feature? I was thinking "from block to block" aliases get all blocks in cuboid region

**Comment by DeltaRays** [comment]
Hey, I have asked in the skript development channel as to whether or not I can do it, but once I get the approval I'll modify the blocks within expression to support getting them as a line and as a cuboid

**Comment by Anarchick** [comment]
> Hey, I have asked in the skript development channel as to whether or not I can do it, but once I get the approval I'll modify the blocks within expression to support getting them as a line and as a cuboid

I have seen a class util AABB which return all blocks in cuboid region. You should maybe use this ;)

**Comment by DeltaRays** [comment]
👀 I'll look into it

**Comment by ShaneBeee** [comment]
This isn't a bug, but as intended. Skript does not currently have a "within" or "cuboid" expression but is definitely something that has been requested, see #1291
