### ISSUE TITLE
None of my script works, and it produces an error.

### ISSUE THREAD

**Issue by deathsou** [SkriptLang/Skript#3245]
### Description
As i was working on my script, i realized that none of it was working at all, so i tested something really basic (on command "e": broadcast "hi") and when even that didn't work, i checked console for errors. Sure enough, there was a large error, saying that it might be one of a few addns i had on. So, i deleted them, and restarted, same issue, this time saying it was an error with skript. I removed and re-downloaded skript, but kept having the same error.

### Steps to Reproduce
I have Skript version 2.4.1. I had a couple outdated addons (Skquery and Skellett) but I removed them and downloaded the newer versions. The error occurs every time i do a skript-related command.

### Expected Behavior

Normal skript behavior, I guess.

### Errors / Screenshots
Console error:
https://pastebin.com/embed_js/6FLE2L77

### Server Information
Spigot 
2.4.1
### Additional Context
Could this be due to the fact that I added and removed addons in a short period of time?

**Comment by Wealthyturtle** [comment]
Uh, this is definitely an addon problem. Skript does not have any citizen hooks...
