### ISSUE TITLE
Teleportation in skript sets yaw and pitch to 0

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#3246]
### Description

Teleportation in skript ignores yaw and pitch (sets it to 0)

### Steps to Reproduce

```
on jump:
	if block under player is diamond block:
		set {_z} to location of block under player
		add 5 to y-coordinate of {_z}
		teleport player to block at location of {_z}
```

### Expected Behavior

It shouldn't change yaw and pitch to 0

### Errors / Screenshots

No errors

### Server Information
* **Server version/platform:** Paper-127 
* **Skript version:** 2.5-alpha6

**Comment by APickledWalrus** [comment]
This isn't actually Skript setting the yaw/pitch. It's because the yaw / pitch of the location ({_z}) is 0. You could fix this by doing:

`
set pitch of {_z} to player's pitch
set yaw of {_z} to player's yaw
`

However, maybe an improvement to EffTeleport could be made? Something like:
`
using %livingentity%'[s] (1¦pitch|2¦yaw|3¦(pitch and yaw|yaw and pitch))
`
(syntax isn't ideal, but it could work)

**Comment by iOshawott** [comment]
Yeah, it would be awesome, cuz it worked with pitch in 2.5-alpha 5...

**Comment by Govindass** [comment]
it's because you're using block location, you should use location 1 meter below player

**Comment by iOshawott** [comment]
@Govindass -.-
I used IT like this and IT worked. I need location od block because it's for elevator skript

**Comment by Govindass** [comment]
> 
> 
> This isn't actually Skript setting the yaw/pitch. It's because the yaw / pitch of the location ({_z}) is 0. You could fix this by doing:
> 
> `set pitch of {_z} to player's pitch set yaw of {_z} to player's yaw`

you can't really fix it that way, because this: https://github.com/SkriptLang/Skript/issues/2708

**Comment by iOshawott** [comment]
I fixed it this way and it's working

**Comment by Govindass** [comment]
> 
> 
> I fixed it this way and it's working

hm, interesting, I guess the bug isn't present on all minecraft versions then

**Comment by TheLimeGlass** [comment]
Blocks don't have a yaw/pitch. We cannot save the values when it'll always be 0. Use the player's location and remove the reference to the block. Like location under the player or as Pickle said, update the yaw and pitch of the location to the player.
