### ISSUE TITLE
"%number% of %item%" broken in 2.5-alpha6

### ISSUE THREAD

**Issue by antoinech2** [SkriptLang/Skript#3255]
### Description
The statement to set a variable to a certain number of item doesn't work in last version 2.5-alpha6

### Steps to Reproduce
```
set {test_item} to stone
set {test_number} to 5
set {test_output} to {test_number} of {test_item}
give {test_output} to player
send "%{test_output}%"
```

### Expected Behavior
Found output: variable `{test_output}` is `<none>`. "give" effect not working
Expected output : variable `{test_output}` should be `5 stones` with "give" effect working

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/42295406/89098821-1cab8700-d3eb-11ea-97ba-f13786d2d32e.png)
(Give doesn't do anything)

### Server Information
* **Server version/platform:** PaperSpigot 1.16.1
* **Skript version:** 2.5-alpha6(rev1)

### Additional Context
It worked fine on the previous alpha version, because my skripts broke just after the update of Skript

**Comment by antoinech2** [comment]
After looking in detail at the list of bug reports, it may be a duplicate of #3187 
I don't know if it is the exact same bug

**Comment by Wealthyturtle** [comment]
Yes, it is a duplicate.

**Comment by antoinech2** [comment]
Okay, sorry about that then.
