### ISSUE TITLE
Add multiple condition check

### ISSUE THREAD

**Issue by AzonFR** [SkriptLang/Skript#3261]
It would be really nice if we can check more than one condition in the same line like:
`sender has permission "test.condition" && arg is set && distance between player and {spawn} > 50:`

or 

`sender has permission "test.condition" || arg is set || distance between player and {spawn} > 50:`

and maybe :

`sender has permission "test.condition" && (arg is set || distance between player and {spawn} > 50):`

**Comment by Runakai1** [comment]
https://github.com/SkriptLang/Skript/issues/2207#issue-461754632

**Comment by ShaneBeee** [comment]
Closing as this is currently being discussed in 2207 as Runakai stated.
