### ISSUE TITLE
Experience classinfo can't be parsed

### ISSUE THREAD

**Issue by FranKusmiruk** [SkriptLang/Skript#3265]
### Description
The experience classinfo can't be parsed, it does not have an `user`.

### Steps to Reproduce
`set {_test} to "5 exp" parsed as experience points`

### Expected Behavior
The classinfo to have an user so it can be used within scripts.

### Server Information
* **Server version/platform:** unrelated
* **Skript version:** unrelated

### Additional Context
The classinfo's user should be `experience ?(points?)?`

**Comment by Runakai1** [comment]
Why does this have good first issue when it's not the first issue from you that has the tag? Or am I just not getting the meaning behind this lol

**Comment by FranKusmiruk** [comment]
@Runakai1 good first issue means that it's a good or relatively easy task for new contributors to handle, not that it's my first good issue though that's quite funny to think about.

**Comment by Runakai1** [comment]
> @Runakai1 good first issue means that it's a good or relatively easy task for new contributors to handle, not that it's my first good issue though that's quite funny to think about.

Oh yeah, that makes sense lol. I think there are a few ways to interpret that
