### ISSUE TITLE
Alias issue with Crimson and Warped stairs

### ISSUE THREAD

**Issue by Lythed** [SkriptLang/Skript#3272]
### Description
There is an issue with "any stairs" aliases

### Steps to Reproduce
Download and Install Paper 1.16.1 and Skript 2.5-beta1
Try this script: https://pastebin.com/raw/gnLMyTKx
Place Crimson and Warped stairs
Rightclick on it

### Expected Behavior
Crimson and Warped stairs should send the two messages but there is only the "Ok!" sended

### Errors / Screenshots
No error
https://i.fiery.me/m1tf4.gif

### Server Information
* **Server version/platform:** git-Paper-111 (MC: 1.16.1)
* **Skript version:** Skript 2.5-beta1

### Additional Context
/

**Comment by ShaneBeee** [comment]
Re-opening as this hasn't been released yet.
