### ISSUE TITLE
strange bug with upper case

### ISSUE THREAD

**Issue by AzonFR** [SkriptLang/Skript#3273]
https://gyazo.com/f94465df05e4cfcf050aef4b5bd37110
https://gyazo.com/58aa210ee337894ece3daa59785a9fab

and another issue, all uppercase are gone with this script for example :
https://gyazo.com/113f9ec0f020733a3c9b446fd7bd1043
https://gyazo.com/cadd09cb77470b840ad71842dccd643e
`send "%{_t::*}%"` result > https://gyazo.com/f43478c3adec511a76e41b90bcf05bdd

### Server Information
* **Server version/platform:** PaperSpigot 1.12
* **Skript version:** 2.5-alpha6

**Comment by FranKusmiruk** [comment]
So, it isn't being lower cased by the command logic (one could think the argument would be lower cased), or the split expression but the loop? Now this is really weird. Can someone please confirm this behaviour?

**Comment by AzonFR** [comment]
Hmm idk why but after restarting, the bug has disappeared, i use the same skript version and spigot version on a other server and never seen this bug. I close, thanks :)

**Comment by AzonFR** [comment]
Edit : i find the bug, it's an issue with the latest version of https://www.spigotmc.org/resources/placeholderapi.6245/ (2.10.9).
