### ISSUE TITLE
reload error

### ISSUE THREAD

**Issue by phoeinxmc** [SkriptLang/Skript#3274]
### Description

I reload a skript
### Steps to Reproduce

/sk relaod (skript)
### Expected Behavior

the skript should have reloadet
### Errors / Screenshots

05.08 21:53:49 [Server] ERROR #!#! 
05.08 21:53:49 [Server] ERROR #!#! [Skript] Severe Error:
05.08 21:53:49 [Server] ERROR #!#! Exception occurred in Skript's main command
05.08 21:53:49 [Server] ERROR #!#! Used command: /sk reload skirpts-sammen
05.08 21:53:49 [Server] ERROR #!#! 
05.08 21:53:49 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
05.08 21:53:49 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
05.08 21:53:49 [Server] ERROR #!#! and check whether this error has already been reported.
05.08 21:53:49 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
05.08 21:53:49 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
05.08 21:53:49 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
05.08 21:53:49 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
05.08 21:53:49 [Server] ERROR #!#! 
05.08 21:53:49 [Server] ERROR #!#! Stack trace:
05.08 21:53:49 [Server] ERROR #!#! java.lang.NullPointerException
05.08 21:53:49 [Server] ERROR #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:264)
05.08 21:53:49 [Server] ERROR #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:255)
05.08 21:53:49 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:713)
05.08 21:53:49 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:706)
05.08 21:53:49 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
05.08 21:53:49 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
05.08 21:53:49 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
05.08 21:53:49 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
05.08 21:53:49 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
05.08 21:53:49 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
05.08 21:53:49 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
05.08 21:53:49 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
05.08 21:53:49 [Server] ERROR #!#! 
05.08 21:53:49 [Server] ERROR #!#! Version Information:
05.08 21:53:49 [Server] ERROR #!#!   Skript: 2.2-dev24b

there is no bugs ingame
### Server Information
* **Server version/platform:** 
* **Skript version:** 
is in the control error

**Comment by ShaneBeee** [comment]
Outdated/unsupported version of Skript
