### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Woutdvv** [SkriptLang/Skript#3278]
I have this weird error, I reinstalled skript, I deleted all my addons, nothing works.

https://pastebin.com/HQi43Y2a

**Comment by ShaneBeee** [comment]
Which version of GriefPrevention are you using?

**Comment by ShaneBeee** [comment]
Closing due to no reply.

I see this in the error:
```
Caused by: java.lang.NoClassDefFoundError: me/ryanhamshire/GriefPrevention/Claim
```
My guess is you are running grief prevention on your server but possibly the wrong version of that plugin.
