### ISSUE TITLE
set {_item}'s name to "XX" BUG

### ISSUE THREAD

**Issue by JeepSmash** [SkriptLang/Skript#329]
I have found an issue regarding setting an items displayname.  I'm not sure if its related to #234 which is an issue regarding displaying an items display name but this is an issue setting an items display name.
Non working code:
```
set {_item} to 1 book
set {_item}'s line 1 of lore to "&9Crush Spell"
set {_item}'s name to "&bSpell Book"
give player {_item}
```
The resulting item will simply be "book" and have no custom display name set but will have the correct lore.

Working code for a work around:
```
set {_item} to "1 book" parsed as item
set {_item}'s line 1 of lore to "&9Crush Spell"
set {_item}'s name to "&bSpell Book"
give player {_item}
```
The resulting item will properly display Spell Book and have the lore set.  It's also worth noting that it does not do this for all items and seems to be selective for some reason.

**Comment by TheBentoBox** [comment]
I believe this definitely related to (the now closed) #234 as you said. The workaround you found will probably be useful to bensku for fixing it.

**Comment by JeepSmash** [comment]
Additional Information:
Another bug with setting an item's name is that it will not set the name of a skull properly without it having other data first.
Non working code: Add Name then Lore
```
	set {_n} to "jeepsmash"
	set {_item} to skull of {_n} parsed as offlineplayer
	set name of {_item} to "&2&l&oDerp King"
	set line 1 of lore of {_item} to "&c&lBow to your King!"
```
will result with a "jeepsmash's head" name on the item with the correct lore.  But if you change the order that the info is added to the item then it will work properly:
Working code: Add Lore then Name
```
	set {_n} to "jeepsmash"
	set {_item} to skull of {_n} parsed as offlineplayer
	set line 1 of lore of {_item} to "&c&lBow to your King!"
	set name of {_item} to "&2&l&oDerp King"
```
will produce the properly named skull with the proper lore

**Comment by Blueyescat** [comment]
^ because setting lore converts the item type to item stack.

Lore expression uses %itemstack/itemtype%, name expression uses only %itemstacks%. I think both should use only item type and should work.

**Comment by bensku** [comment]
Affected by #1506, which I fixed, but other than that, does not seem to exist anymore.
