### ISSUE TITLE
Skript parser error [1.8.8, 2.2-dev36]

### ISSUE THREAD

**Issue by NRCAsk** [SkriptLang/Skript#3292]
### Description
Basically, I added this piece of code to my skript: 
`on right click:`
  `broadcast "1"`
  `type of item is magma cream`
   `name of item contains "&d&lTOKENS"`
   `set {_n::*} to uncoloured name of tool parsed as "\>\> TOKENS \(%int%\) <\<\"`
   `broadcast "%{_n::*}%"`
And when I reload the skript, no errors occur, everything reloads fine. However, when I try to right click a magma cream with the name ">> TOKENS (100) <<" it sends a parser error to console.

### Expected Behavior
In theory, the code should simply broadcast the name of tool parsed as what is stated above; instead, it just sends errors :(

The error can be seen here:
https://pastebin.com/NhaHPZ18

### Server Information
* **Server version/platform: git-PaperSpigot-"4c7641d" (implementing API version 1.8.0-R0.1-SNAPSHOT)
* **Skript version: 2.2dev36

**Comment by ShaneBeee** [comment]
Outdated Skript version
And also 1.8.8 is not supported.
Skript only supports 1.9.4+
