### ISSUE TITLE
Hex color in .yml doesn't convert through variable

### ISSUE THREAD

**Issue by Kamill0s** [SkriptLang/Skript#3293]
### Description

It shows hex color code as a text.

### Steps to Reproduce
I want to save the hex color in .yml file for global text color used in different skripts at once.
In my skript i save the .yml color value into `{_}` and then I show it in: `send "%{_}%test" to player`
.yml code: `color: '<##4F9C44>'`
### Expected Behavior

Should convert string into the hex color.

### Errors / Screenshots

https://imgur.com/a/hq5vNfY

### Server Information
Server version: 1.16.1 / paper
Skript version: 2.5-beta1

**Comment by Pikachu920** [comment]
you would need to use `colored {_}`. Skript doesn't have any yaml support either - so this could be an addon issue

**Comment by Kamill0s** [comment]
It doesn't work. Text is still default white.

**Comment by ShaneBeee** [comment]
Closing as this is most likely an addon issue, as Pikachu said, Skript doesn't have Yaml support.
