### ISSUE TITLE
Server lag When over 30 player

### ISSUE THREAD

**Issue by waiching514** [SkriptLang/Skript#3296]
### Description
Sometimes server will held some enderdragon event, and over 30 player join, and will cause lag
(my server most rpg made by skript)

### Steps to Reproduce
many player using rpg made by skript such as "on rightclick,on damage, event"(cool down using many variable)

### Errors / Screenshots
timings: https://timings.aikar.co/?id=3863d8288e63459e828d28fd2a51d16f#timings
https://i.imgur.com/Lrwjl9U.png

### Server Information
* **Server version/platform:paper-134 1.16.1
* **Skript version: 2.5-beta-1

**Comment by ShaneBeee** [comment]
Not much we can do here.
Seems like you probably have some inefficient scripts.
