### ISSUE TITLE
Change something not really important

### ISSUE THREAD

**Issue by YeaZz** [SkriptLang/Skript#3298]
Hello,

It would be cool if ExprTimePlayed.java could handle Offline Players too :)
(if it's not already, and in that case it's a problem from me 🤔 )

Thank you

**Comment by ShaneBeee** [comment]
Looking at that class, it really should have supported offline player in the first place, not sure why it didn't.

**Comment by ItsMeYeazzz** [comment]
Ok, i'll test it again later, thank you for your fast answer.

**Comment by ShaneBeee** [comment]
No, im saying the class SHOULD have supported it, but it currently does not.

**Comment by ItsMeYeazzz** [comment]
Oooh ok, my bad, thank you x)

**Comment by FranKusmiruk** [comment]
Whoever does this, take into account that the ability to get an offline player's statistic was implemented in 1.15.2 (and exactly in that version, it isn't a thing in 1.15.1 or 1.15), so you may have to add a check for that in registration and also clarify it on the documentation.

**Comment by CarloDrift** [comment]
> Whoever does this, take into account that the ability to get an offline player's statistic was implemented in 1.15.2 (and exactly in that version, it isn't a thing in 1.15.1 or 1.15), so you may have to add a check for that in registration and also clarify it on the documentation.

This was implemented in 1.13 (just tested).

**Comment by ShaneBeee** [comment]
Unless its implemented somewhere else, Im pretty sure its not available for offline player's in 1.13

<img width="1192" alt="Screen Shot 2020-08-15 at 11 56 28 AM" src="https://user-images.githubusercontent.com/20008482/90319610-839e6500-deee-11ea-898b-8f8c96023173.png">
<img width="1192" alt="Screen Shot 2020-08-15 at 11 56 55 AM" src="https://user-images.githubusercontent.com/20008482/90319612-86995580-deee-11ea-80b1-1bb822e91b6a.png">

**Comment by CarloDrift** [comment]
> Unless its implemented somewhere else, Im pretty sure its not available for offline player's in 1.13
> 
> <img alt="Screen Shot 2020-08-15 at 11 56 28 AM" width="1192" src="https://user-images.githubusercontent.com/20008482/90319610-839e6500-deee-11ea-898b-8f8c96023173.png">
> 
> <img alt="Screen Shot 2020-08-15 at 11 56 55 AM" width="1192" src="https://user-images.githubusercontent.com/20008482/90319612-86995580-deee-11ea-80b1-1bb822e91b6a.png">

I thought I tested in 1.13, my bad. That's 1.15.

**Comment by AyhamAl-Ali** [comment]
Completed in #4264
