### ISSUE TITLE
List header and/or footer

### ISSUE THREAD

**Issue by Wafffidooe** [SkriptLang/Skript#3299]
### Description
 Hello! It's the first time I wanted to use this feature from Skript (used an addon before), but when loading the skript, it doesn't understand the condition.

### Steps to Reproduce
I used the exact example (the first one) from the documentation:
![Screenshot_20200811-165837_Discord](https://user-images.githubusercontent.com/47904309/89980194-af60e700-dc71-11ea-9813-263ae70c5b7e.jpg)

### Expected Behavior
Should work... I mean, it's a direct example from the documentation.

### Errors / Screenshots
Can't understand the condition

### Server Information
* **Server version/platform:** 1.12.2 - Spigot
* **Skript version:** 2.5 alpha5

**Comment by ShaneBeee** [comment]
As explained on discord, this is 1.13+ only

<img width="926" alt="Screen Shot 2020-08-11 at 11 05 34 PM" src="https://user-images.githubusercontent.com/20008482/89980678-3c328300-dc27-11ea-8954-47567841a32c.png">
