### ISSUE TITLE
x log handlers were not stopped properly!

### ISSUE THREAD

**Issue by Sitieno14** [SkriptLang/Skript#3300]
### Description
Some weird errors in console, and I had to force restart server to fix them

### Steps to Reproduce
Stop then start your server, just sometimes

### Expected Behavior
Nothing

### Errors / Screenshots
https://pastebin.com/2fQW0R6a

### Server Information
This server is running Paper version git-Paper-385 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Skript version 2.5-beta1

**Comment by Romitou** [comment]
If I remember correctly, this is due to an outdated version of skript-mirror. This is not related to Skript ; you can retry using skript-reflect or skript-mirror 2.0.0.

**Comment by ShaneBeee** [comment]
As stated, this is caused by using an outdated version of skript-mirror
```
[skript-mirror] Enabling skript-mirror v0.19.1*
```
