### ISSUE TITLE
Version issue with tests.

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#3306]
### Description
From my understanding, and looking at the code, testing with a version should test that version and above.
Ex:
```vb
test "blah blah" when minecraft version is "1.12.2":
```
This SHOULD test on versions 1.12.2 and above. 
Unfortunately it is not. 

The main issue here is going to have to change versions of tests each major update. 
ex: If we wrote `when minecraft version is "1.16.1"` we would then therefor have to change it to 1.16.2 when 1.16.2 comes out, same for 1.17

### Expected Behavior
The version in the testing environment should test for that version and above

### Server Information
* **Server version/platform:** Paper 1.16.2
* **Skript version:** Skript 2.5-beta2

### Additional Context
I've looked thru the code and can't figure this one out. 
I even tested using that condition in a regular script, and it works as intended, so it only seems to not work correctly in the testing environment. 

Im marking this as a medium priority bug. Even though this has no affect what-so-ever on the end user, this is definitely something we need to fix on our end.

**Comment by APickledWalrus** [comment]
It turns out, we are using the wrong conditions in tests. We're actually using `CondCompare` with` ExprVersion` when we should be using `CondMinecraftVersion`
Here's the difference:
```vb
CondCompare and ExprVersion (WRONG WAY!):
test "TEST" when minecraft version is "1.12.2"
```
```vb
CondMinecraftVersion (RIGHT WAY!):
test "TEST" when running minecraft "1.12.2"
```

**Comment by ShaneBeee** [comment]
Im going to close this, as Pickle pointed out this was an oversight not a bug.
