### ISSUE TITLE
play sound script  cause tps drop

### ISSUE THREAD

**Issue by waiching514** [SkriptLang/Skript#3309]
### Description
When a script having play sound e.g. 
on rightclick:
	if the name of the tool of the player is "&atest":
		play raw sound "ENTITY_POLAR_BEAR_WARNING" at player with pitch 1 volume 1
### Steps to Reproduce
on rightclick:
	if the name of the tool of the player is "&atest":
		play raw sound "ENTITY_POLAR_BEAR_WARNING" at player with pitch 1 volume 1
on damage:
	if the name of the tool of the attacker is "&atest":
		play raw sound "ENTITY_POLAR_BEAR_WARNING" at player with pitch 1 volume 1

### Server Information
* **Server version/platform:** paper 1.16.1-135
* **Skript version:** 2.5-beta-2

### Additional Context
you can try my script reloading time
[testscript.zip](https://github.com/SkriptLang/Skript/files/5078496/testscript.zip)

**Comment by ShaneBeee** [comment]
`play raw sound` is not a Skript syntax, that is from some addon.
