### ISSUE TITLE
Skript command priority

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#3313]
Add to Skript a command priority for example:
Command essentials:
    Priority: low, medium, high and highest
The priorities should overwrite the existing command.

**Comment by ShaneBeee** [comment]
Commands already override plugin commands.

**Comment by Misio12320** [comment]
So give them priority to make them not bugging with other plugins. Without "priority: e.g high" the command should work like in the config file. The priority is just like a "addon"

**Comment by ShaneBeee** [comment]
I dont understand the need.

From what I know, commands in Skript override plugin commands. 
If you want it to override, it'll override.
If you dont want it to override, dont write the command.
