### ISSUE TITLE
RGB color for chat

### ISSUE THREAD

**Issue by Yoahim** [SkriptLang/Skript#3318]
Hey, I recently tried to write a script to color someone's chat messages with the RGB color of their choice. The effect is as follows:
![Adnotacja 2020-08-17 162440](https://user-images.githubusercontent.com/69805158/90407982-7a0c2d00-e0a7-11ea-9a6b-e7fdd3823834.png)

### Server Information
* **Server version/platform:** PaperSpigot 1.16.1 (Paper-131)
* **Skript version:** 2.5 Beta2

Here is the link to the screenshot of script responsible for that: https://imgur.com/a/ML5KOb5

**Comment by TheBentoBox** [comment]
Hex codes are written by putting the hex code inside of angled brackets, e.g. `<#FFFFFF>`
