### ISSUE TITLE
Bug Setting a variable to a Wither Skull Entity

### ISSUE THREAD

**Issue by JeepSmash** [SkriptLang/Skript#332]
I have made script that will allow players to shoot various objects with special trailing effects behind them and ran into a problem when I got to wither skulls

The following code will shoot a wither skull from the player indicating "wither skull" accurately works for the spawn expression and "the spawned wither skull" accurately works for the thrust expression but the set expression does not properly set the variable to the entity.
```
spawn a wither skull 2 in front of player
thrust the spawned wither skull in direction of player with force .5
set {_ent} to the spawned wither skull
message "%location of {_ent}%"
```
The message will display "<none>" indicating the variable was not properly set to the entity
But running the following code with one change: change "wither skull" to "fireball" when using the set expression WILL accurately set the variable to the "wither skull" that was spawned.

```
spawn a wither skull 2 in front of player
thrust the spawned wither skull in direction of player with force .5
set {_ent} to the spawned fireball
message "%location of {_ent}%"
```
I have tried this with several different entity types snowballs, eggs, arrows, fireballs and wither skull was the only one that didn't work properly but did work once i changed the set expression to reference a fireball.

**Comment by TheBentoBox** [comment]
Interesting. Thank you for the extensive bug report.

**Comment by bensku** [comment]
Hmm, this is very interesting. Technically fireball and wither skull are both quite similar, i.e. projectiles.

**Comment by TheLimeGlass** [comment]
```
shoot wither skull from player at speed 1 in direction of player
```
Does not work either, as I have just ran into this issue.

The issue may be a simple fix by adding a Wither Skill EntityData to define all it's components.

It's clearly being considered a projectile so the shoot effect should be used but it's not working either.

The shoot effect is for projectiles and the last entity expression has support for getting last shot projectiles
```
set {_arrow} to the last shot arrow
```

It's not so much a variable issue, but Skript not being able to read the english input `wither skull` and convert that into a WitherSkull EntityData object.

**Comment by bensku** [comment]
#1631 made me *probably* realize what is wrong. The thing is, Skript has no idea what type variables should contain. Even local variable type hints don't work *backwards*. Thus, just allowing entities to be compared with items is *not* a solution. Creating a item -> entity converter might help more, but I'm not sure what side effects that might have.

**Comment by Wealthyturtle** [comment]
Closing in favor of #2097
