### ISSUE TITLE
"last" in the "replace" syntax

### ISSUE THREAD

**Issue by GallicoAquilae** [SkriptLang/Skript#3326]
The `replace first %strings% in %strings% with %string%` can replace the first string in a text with another string, but there is no good way to replace the last string, only with a split and a loop.

**Comment by Mr-Darth** [comment]
For now, you can either reverse everything and replace first, then reverse again
```vb
function reverseString(o: string) :: string:
	set {_r::*} to reversed (split {_o} by "")
	return join {_r::*}
function replaceLast(o: string, p: string, w: string) :: string:
	set {_o} to reverseString({_o})
	set {_p} to reverseString({_p})
	set {_w} to reverseString({_w})
	replace first {_p} with {_w} in {_o}
	return reverseString({_o})
```
or do
```vb
function replaceLast2(o: string, p: string, w: string) :: string:
	set {_i} to last index of {_p} in {_o}
	set {_n} to {_i} + length of {_p} - 1
	return join (first {_i}-1 characters of {_o}), {_w}, (subtext of {_o} from indices {_n}+1 to (length of {_o}))
```

**Comment by DeltaRays** [comment]
Hey, my pull request https://github.com/SkriptLang/Skript/pull/3156 already has that

**Comment by GallicoAquilae** [comment]
> Hey, my pull request https://github.com/SkriptLang/Skript/pull/3156 already has that

Oh I didn't knew that, sorry
