### ISSUE TITLE
Json messages using <> not working.

### ISSUE THREAD

**Issue by ryanrox333** [SkriptLang/Skript#3328]
### Description
If you try and use anything like `<message:>` or `<cmd:>` it doesn't work.

### Steps to Reproduce
I used a `on chat:` event and canceled the event and put `<message:>`. It should of shown the tooltip message but instead nothing.

### Expected Behavior
[Picture of what its supposed to do.](https://imgur.com/DIELuXd)

### Errors / Screenshots
[Picture of what it now shows](https://imgur.com/73nVz6A)

### Server Information
* **Server version/platform:** **Spigot 1.15.2**
* **Skript version:** **2.4.1**

### Additional Context
Not really.

**Comment by ShaneBeee** [comment]
use `formatted` before using formats
ie: `send formatted "<message>"`

**Comment by ryanrox333** [comment]
![uhh](https://user-images.githubusercontent.com/44746268/90834503-6d424000-e318-11ea-9dd8-d99571ece6f8.png)

**Comment by ShaneBeee** [comment]
formats like tooltips only work in messages, not lore.

**Comment by ryanrox333** [comment]
It isnt a lore, it is a message...
`send formatted "%player's prefix%<tooltip:&a%player%'s &7Stats:%nl%&7%nl%&7Money: &a%player's balance%%nl%&7Level: &a%{level.%player%}%%nl%&7%nl%&eClick to message &6%player%&e!><suggest command:/emsg %player%>%player%<reset>%player's suffix% &r%message%" to all players`

**Comment by ShaneBeee** [comment]
Hmm yes that seems to not be working.

**Comment by DeltaRays** [comment]
I tested with 
```vbs
on chat:
	send formatted "%player%<tooltip:&a%player%'s &7Stats:%nl%&7%nl%&7Money: &a%amount of stone in player's inventory% %nl%&7Level: &a%{level.%player%}%%nl%&7%nl%&eClick to message &6%player%&e!><suggest command:/msg %player%>%player%<reset> &r%message%" to all players
``` and it works fine

**Comment by ryanrox333** [comment]
DeltaRays what version of Skript were you running?

**Comment by DeltaRays** [comment]
I wass running Skript 2.5 beta 3

**Comment by Govindass** [comment]
this problem most likely appears due to the $ symbol
