### ISSUE TITLE
Log handler was not stopped properly

### ISSUE THREAD

**Issue by Lerbiq** [SkriptLang/Skript#3335]
### Description
I updated the server to 1.16.2 and got the errors linked bellow in the console.

### Steps to Reproduce
Update from paper 1.16.1 (I don't know the exact build) to paper 1.16.2 (build 141) and watch console.

### Expected Behavior
No errors in console
### Errors / Screenshots
https://pastebin.com/SHTXuVEe

### Server Information
* **Server version/platform:**  Paper 1.16.2, build 141.
* **Skript version:** 2.5-beta2

**Comment by ShaneBeee** [comment]
This is due to using an outdated version of Skript mirror, update to Skript-mirror 2.0.0 or use Skript-reflect
