### ISSUE TITLE
On respawn event gets triggered, when the player goes through end portal

### ISSUE THREAD

**Issue by Viljami0** [SkriptLang/Skript#3338]
The On respawn event gets triggered, when the player goes through end portal in the **end side, when the player teleports to their bed.** 

The version is:
(Server) git-Paper-135 (MC: 1.16.1)
(Skript version) 2.5-beta2

**Comment by ShaneBeee** [comment]
This is a Spigot issue not a Skript issue. You can see the issue on [**Spigot's Jira**](https://hub.spigotmc.org/jira/browse/SPIGOT-5217?jql=text%20~%20%22respawn%20portal%22)
