### ISSUE TITLE
Player name cannot be compared with owner

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#3344]
### Description
Player name in previously accepted skript is not recognized. The skript ran without error through Skript 2.5-beta2.

### Steps to Reproduce
- Update from Skript 2.5-beta2 to 2.5-beta3.
- Start server.
- Obverse console/log error.

Note that the real player name has been replaced below by "playerName".

### Errors / Screenshots
```
[15:50:10] [Server thread/INFO]: [Skript] Loading Skript v2.5-beta3
[15:50:27] [Server thread/INFO]: [Skript] Enabling Skript v2.5-beta3
...
[15:51:35] [Server thread/INFO]: [Skript] Loading variables...
[15:51:35] [Server thread/INFO]: [Skript] Loaded 7 variables in 0.0 seconds
...
[15:51:40] [Server thread/ERROR]: [Skript] Can't compare an inventory holder with a text (save-my-pets.sk, line 38: owner of the victim is "playerName"')
[15:51:40] [Server thread/ERROR]: [Skript] Can't compare an inventory holder with a text (save-my-pets.sk, line 54: owner of the victim is "playerName"')
```

### Server Information
* **Server version/platform:** Spigot 1.16.2 (Jenkins 2897)
* **Skript version:** 2.5-beta3

### Additional Context
The skript
```
on damage of a cat:
        owner of the victim is "playerName"
        cancel event
        send "Don't hurt that cat!" to the attacker
        attacker is not "playerName"
...
```

**Comment by ShaneBeee** [comment]
Hot diggity, you fix one bug and create another haha.

Anyways the inventory (holder|owner) expression and the (owner|tamer) expression are clashing.
Until I can fix this, use `tamer` instead.

**Comment by SlimeDog** [comment]
`tamer` works fine. Thanks.

**Comment by SlimeDog** [comment]
Per documentation:
```
The tamer of an entity. Can only be used in entity tame events. 
```
Nevertheless, it appears to work fine in the quoted comparison.

**Comment by ShaneBeee** [comment]
2 different expressions:
<img width="576" alt="Screen Shot 2020-08-28 at 5 17 36 PM" src="https://user-images.githubusercontent.com/20008482/91623934-73f13880-e952-11ea-9b07-9660e85cbbe0.png">
<img width="661" alt="Screen Shot 2020-08-28 at 5 17 57 PM" src="https://user-images.githubusercontent.com/20008482/91623936-75bafc00-e952-11ea-8292-faa519b98f51.png">

This was simply a clash with:
<img width="876" alt="Screen Shot 2020-08-28 at 4 52 45 PM" src="https://user-images.githubusercontent.com/20008482/91623945-7e133700-e952-11ea-989e-e1480ba76c3e.png">
