### ISSUE TITLE
Named items not returning as ItemType

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#3347]
### Description

Errors, A LOT. of them.
### Expected Behavior

No errors
### Errors / Screenshots

https://pastebin.com/raw/knSmdyN6 (some may have appeared that aren't caused by the update, but... look at all those item stacks, they definitely worked before!)

### Server Information
* **Server version/platform:** 1.12.2 Paper
* **Skript version:** 2.5 beta3

**Comment by Romitou** [comment]
I can confirm with Paper 1.15.2.

**Comment by ShaneBeee** [comment]
Ok, luckily this was an easy fix. But for future reference, please fill in the issue template and describe the actual issue. 
I happened to know why this broke, but this isn't always the case. Saying "lots of errors" doesn't help us triage the issue in a lot of cases. 

Help us help you!

**Comment by Govindass** [comment]
> 
> 
> Ok, luckily this was an easy fix. But for future reference, please fill in the issue template and describe the actual issue.
> I happened to know why this broke, but this isn't always the case. Saying "lots of errors" doesn't help us triage the issue in a lot of cases.
> 
> Help us help you!

well it was an actual issue.. I restarted server after update, saw errors, that's all xD

**Comment by Leonardo-Fiori** [comment]
Tested both **Beta 2** and last **nightly build**... nope! The issue is still there, i want to check if the item has NO name applied on it:

```
if arg-player has arg-number of diamonds named "":
	remove arg-number of diamonds named "" from arg-player's inventory
	add {_worth} to arg-player's money
	... bla bla do stuff 😄 
```

Small gif where i rename diamond to testname, but the code i wrote above sees it as named ""

https://giphy.com/gifs/ehOBHL0qObLzL5wqs4

**Comment by Govindass** [comment]
> 
> 
> Tested both **Beta 2** and last **nightly build**... nope! The issue is still there, i want to check if the item has NO name applied on it:
> 
> ```
> if arg-player has arg-number of diamonds named "":
> 	remove arg-number of diamonds named "" from arg-player's inventory
> 	add {_worth} to arg-player's money
> 	... bla bla do stuff 😄 
> ```
> 
> Small gif where i rename diamond to testname, but the code i wrote above sees it as named ""
> 
> https://giphy.com/gifs/ehOBHL0qObLzL5wqs4

the issue you're having is different from the issue reported in this issue

**Comment by Leonardo-Fiori** [comment]
@ShaneBeee does not think so 🤷‍♂️ 
look #3364 , he closed it as duplicate of this one

**Comment by Leonardo-Fiori** [comment]
For me this is not fixed yet. I can't check if an item has no name applied

**Comment by ShaneBeee** [comment]
`if name of item is not set`
