### ISSUE TITLE
Server running at 11tps and server is hanging

### ISSUE THREAD

**Issue by Viljami0** [SkriptLang/Skript#3349]
### Description
Hello, 
2 weeks ago I made an SMP server, but today it started to not function properly. 
When you connect to the SMP, no chunks load, the tps is at 11 (normally 20-18.5) and the console is SPAMMED with errors

### Expected Behavior
The chunks should have loaded, the tps should have been 20 and the console should have been mostly clear (apart from the frequent crashes)

Console error: https://pastebin.com/X5573yMV

### Server Information
Latest build of Paper aka build # 160
Skript 2.5beta 2 **AND** 2.5beta 3 
Addons:
SkQuery 4.1.3
Skellett-Legacy

### Additional Context
Please help, I cannot do anything.

**Comment by Wafffidooe** [comment]
Are you saying, that you are using two different versions of Skript at once, or have you tried using one, and switched to the other?

**Comment by ShaneBeee** [comment]
Theres really no details here we can work with.
I see in the crash that you are attempting to teleport a player via a command. 
You should post some code or something, not really sure what you've done that would cause a crash.

Skript itself isn't going to crash your server, but inefficient code definitely can.

**Comment by Viljami0** [comment]
> Are you saying, that you are using two different versions of Skript at once, or have you tried using one, and switched to the other?

I have tried both

**Comment by Viljami0** [comment]
> Theres really no details here we can work with.
> I see in the crash that you are attempting to teleport a player via a command.
> You should post some code or something, not really sure what you've done that would cause a crash.
> 
> Skript itself isn't going to crash your server, but inefficient code definitely can.

Here is my home commands (The ones I used during the issue)

`command /sethome [<player>]:
  trigger:
    if arg-1 is not set:
      set {home.%player%} to player's location
      send "&aSuccess!"
    else:
      if player has permission "op":
        set {home.%arg-1%} to player's location
        send "Success"
      else:
        send "You do not have permission to set someone else's home."

command /home [<offline player = %player%>] [<text>]:
  trigger:
    if arg-2 is "-f":
      if player has permission "op":
        teleport the player to {home.%arg-1%}  
        send "&aSuccess!"
    else:
      if arg-1 is the player:
        if {home.%arg-1%} is set:
          send "&aTeleporting. Please wait %{_temp2}% seconds."
          wait 1 second
          teleport the player to {home.%arg-1%}  
          send "&aSuccess!"
        else:
          send "You have not set a home, yet!"
      else:
        if {home.%arg-1%} is set:
          send "&aTeleporting. Please wait %{_temp2}% seconds."
          wait 10 second
          teleport the player to {home.%arg-1%}  
          send "&aSuccess!"
          send "&a%player% &ateleported to your home." to arg-1
        else:
          send "That person has not set a home"`

**Comment by Viljami0** [comment]
Nevermind, it works now! Thanks.

**Comment by Govindass** [comment]
I think the problem was that you were doing synchronous teleportations, on 1.13+ you should be using player.teleportAsync({_loc}) with skript-reflect
