### ISSUE TITLE
Game rules syntaxes before 1.13?

### ISSUE THREAD

**Issue by carlodrift** [SkriptLang/Skript#3350]
It's a pity that these syntaxes are limited to versions 1.13+.

**Comment by ShaneBeee** [comment]
I cant speak for the rest of the devs on the team, but I personally dont think this should be added for outdated versions of Minecraft.
The Bukkit API change drastically for GameRules in 1.13, and having to support 2 different APIs for this can be a hassle. 

Im pretty sure there is an addon out there that supports game rules on outdated server versions, or you can update your server.

**Comment by CarloDrift** [comment]
Thank you for your reply. Actually, it's not for my server but for a public script. Therefore it only works in 1.13+.

**Comment by TheLimeGlass** [comment]
Attempted to support this in 2.6.4, requires reflection. Also the name of the gamerule is unknown, and it's not the command gamerule either so using a String in 1.12 and lower is confusing.
