### ISSUE TITLE
Sweep attack damage cause isn't understood in 1.9

### ISSUE THREAD

**Issue by CarloDrift** [SkriptLang/Skript#3352]
### Steps to Reproduce
```vb
on damage:
	damage cause is sweep attack
```

### Error
```cmd
Can't compare a damage cause with 'sweep attack'
```

### Server Information
* **Server version/platform:** git-Paper-773 (MC: 1.9.4)
* **Skript version:** 2.5-beta2

**Comment by ShaneBeee** [comment]
Didn't exist in 1.9.4

**Comment by TPGamesNL** [comment]
To clarify, it did exist in Minecraft:
![image](https://user-images.githubusercontent.com/29547183/91636076-27fbcd80-e9fe-11ea-9b6f-a5ffb05d74c8.png)
It just wasn't implemented in Bukkit (as a damage cause)
