### ISSUE TITLE
 error in console on "inventory click" event

### ISSUE THREAD

**Issue by Poweringg** [SkriptLang/Skript#3359]
### Description
getting error in console on "inventory click" event - https://docs.skunity.com/syntax/search/id:3711

### Steps to Reproduce
write this skript... 
```
on inventory click:
	send "%event-slot%" to console
```
when player clicks to any inventory slot, it send "...", but when player clicks outside of inventory, console got error.

### Expected Behavior
no error.

### Errors / Screenshots
https://pastebin.com/pKZF5Dek

### Server Information
SK: 2.5-b3
PaperServer: 1.16.2-r0.1 build 174

**Comment by ShaneBeee** [comment]
I could have sworn this was fixed before.
Will investigate further.

**Comment by Runakai1** [comment]
> I could have sworn this was fixed before.
> Will investigate further.

Twice in fact
