### ISSUE TITLE
Fawe worldedit not supported by skript

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#3361]
[Skript] Loading Skript v2.5-beta3
[FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.16.2

Error:
https://hastebin.com/uposufahuv.shell

I think Skript should support Fawe right out of the box because less people using default worldedit because of not being async.

**Comment by Romitou** [comment]
Related to #2674

**Comment by ShaneBeee** [comment]
Closing as duplicate of #2674
