### ISSUE TITLE
checking named items syntax broken in last beta

### ISSUE THREAD

**Issue by Leonardo-Fiori** [SkriptLang/Skript#3364]
i used this line of code to check if player had X regular diamonds (that had no special name or lore):
`if arg-player has arg-number of diamonds named "":`

now, after updating to beta 3, i get this error on load of the script:
`the 1st argument of diamond named "" is not an item type (atm_diamond.sk, line 233: if arg-player has arg-number of diamonds named "":')`

### Server Information
* **Server version/platform:** git-Paper-184
* **Skript version:** Skript version 2.5-beta3

**Comment by Romitou** [comment]
This problem has already been reported and completed (https://github.com/SkriptLang/Skript/issues/3347).

**Comment by Leonardo-Fiori** [comment]
Where can I find a build for that?

**Comment by Romitou** [comment]
You can find a Nightly Build [here](https://github.com/SkriptLang/Skript/actions/runs/229999658), fixing the problem or go to beta2 while waiting for beta4.

**Comment by ShaneBeee** [comment]
Closing as duplicate of #3347

**Comment by Leonardo-Fiori** [comment]
Tested both nightly and beta 2, neither works.

```
if arg-player has arg-number of diamonds named "":
	remove arg-number of diamonds named "" from arg-player's inventory
	add {_worth} to arg-player's money
	... bla bla do stuff 😄 
```

https://giphy.com/gifs/ehOBHL0qObLzL5wqs4
