### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by apox-lab** [SkriptLang/Skript#3366]
error :

> [16:29:09 ERROR]: #!#!
> [16:29:09 ERROR]: #!#! [Skript] Severe Error:
> [16:29:09 ERROR]: #!#!
> [16:29:09 ERROR]: #!#! Something went horribly wrong with Skript.
> [16:29:09 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [16:29:09 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
> [16:29:09 ERROR]: #!#! Here is full list of them:
> [16:29:09 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) SkQuery Skellett (https://forums.skunity.com/resources/skellett.24/)
> [16:29:09 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
> [16:29:09 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
> [16:29:09 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
> [16:29:09 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
> [16:29:09 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
> [16:29:09 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
> [16:29:09 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
> [16:29:09 ERROR]: #!#!
> [16:29:09 ERROR]: #!#! Stack trace:
> [16:29:09 ERROR]: #!#! java.lang.IndexOutOfBoundsException: Index: 46, Size: 46
> [16:29:09 ERROR]: #!#! at java.util.ArrayList.rangeCheck(ArrayList.java:659)
> [16:29:09 ERROR]: #!#! at java.util.ArrayList.get(ArrayList.java:435)
> [16:29:09 ERROR]: #!#! at net.minecraft.inventory.Container.func_75139_a(Container.java:219)
> [16:29:09 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryView.setItem(CraftInventoryView.java:121)
> [16:29:09 ERROR]: #!#! at com.w00tmast3r.skquery.elements.effects.EffFormatSlot.execute(EffFormatSlot.java:94)
> [16:29:09 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
> [16:29:09 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
> [16:29:09 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
> [16:29:09 ERROR]: #!#! at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
> [16:29:09 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
> [16:29:09 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422)
> [16:29:09 ERROR]: #!#! at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:830)
> [16:29:09 ERROR]: #!#! at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470)
> [16:29:09 ERROR]: #!#! at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
> [16:29:09 ERROR]: #!#! at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
> [16:29:09 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
> [16:29:09 ERROR]: #!#!
> [16:29:09 ERROR]: #!#! Version Information:
> [16:29:09 ERROR]: #!#! Skript: 2.2-dev37c (custom version)
> [16:29:09 ERROR]: #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
> [16:29:09 ERROR]: #!#! Minecraft: 1.12.2
> [16:29:09 ERROR]: #!#! Java: 1.8.0_262 (OpenJDK 64-Bit Server VM 25.262-b10)
> [16:29:09 ERROR]: #!#! OS: Linux amd64 4.9.0-12-amd64
> [16:29:09 ERROR]: #!#!
> [16:29:09 ERROR]: #!#! Server platform: Paper
> [16:29:09 ERROR]: #!#!
> [16:29:09 ERROR]: #!#! Current node: null
> [16:29:09 ERROR]: #!#! Current item: format slot
> [16:29:09 ERROR]: #!#! Current trigger: command /istmetier (simple event) (skins.sk, line -1)
> [16:29:09 ERROR]: #!#!
> [16:29:09 ERROR]: #!#! Thread: Server thread
> [16:29:09 ERROR]: #!#!
> [16:29:09 ERROR]: #!#! Language: english
> [16:29:09 ERROR]: #!#! Link parse mode: DISABLED
> [16:29:09 ERROR]: #!#!
> [16:29:09 ERROR]: #!#! End of Error.
> [16:29:09 ERROR]: #!#!

**Comment by Pikachu920** [comment]
Caused by skQuery
