### ISSUE TITLE
on region enter - Event not work

### ISSUE THREAD

**Issue by Skyfuller1303** [SkriptLang/Skript#3367]
### Description

The event on region enter is not working

### Steps to Reproduce
Create an file with the event and reload it

### Errors / Screenshots
`[16:46:29 INFO]: [Skript] Reloading regions.sk...`
`[16:46:29 ERROR]: can't understand this event: 'on region enter' (regions.sk, line 1: on region enter:')`
`[16:46:29 INFO]: [Skript] Encountered 1 error while reloading regions.sk!`

### Server Information
Paper version git-Paper-387 (MC.1.15.2)
Skript version 2.5 beta3
WorldGuard version 7.0.3:5407315

**Comment by ShaneBeee** [comment]
ok, so I just tested, here was the code:

```vb
on region enter:
    send "E: %event-region%"
```
Here is what it says when I reload:
```
> sk reload test
[12:05:16 INFO]: [Skript] Reloading test.sk...
[12:05:16 INFO]: [Skript] Successfully reloaded test.sk.
```

Here are my versions of Skript, WE and WG:
```
> ver skript
[12:04:59 INFO]: Skript version 2.5-beta3
> ver worldedit
[12:05:03 INFO]: WorldEdit version 7.1.0;8e55131
> ver worldguard
[12:05:05 INFO]: WorldGuard version 7.0.3;5407315
> ver
[12:06:23 INFO]: This server is running Paper version git-Paper-387 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

Needless to say, I can not replicate this issue.

**Comment by TobyMinceraft** [comment]
If I had to guess, the reporter does not have WorldGuard installed, as explicitly stated on the [SkriptLang docs](https://skriptlang.github.io/Skript/events.html#region_enterleave):
`This event requires a supported regions plugin to be installed.`
