### ISSUE TITLE
Skript placeholder for PlaceholderAPI isn't working.

### ISSUE THREAD

**Issue by CharrDino** [SkriptLang/Skript#3369]
### Description
Attempting to download the ecloud skript placeholder for PlaceholderAPI and reloading will not download the expansion, producing an error in console.

### Steps to Reproduce
/papi ecloud download Skript
/papi reload

### Expected Behavior
The skript placeholder expansion would've been registered on PlaceholderAPI reload, be listed in the installed and not have produced an error code in console.

### Errors / Screenshots
https://pastebin.com/rfiWNU8R

The error is line three.

PlaceholderAPI installed list. (no there is no other page except page 1)
https://gyazo.com/c01fb6ea1b163184286f37c5511b331b

### Server Information
Paper 1.16.2-r0.1 build 185
skript 2.5-beta3

### Additional Context
PlaceholderAPI version 2.10.9

**Comment by ShaneBeee** [comment]
The placeholder for Skript is not part of this repo.
