### ISSUE TITLE
send all players title is not working

### ISSUE THREAD

**Issue by hwanhee1102** [SkriptLang/Skript#3371]
hello. i am korean that using skript 2.5 beta, and paper-186 and minecraft ver 1.16.2,
but i want to load skript, but skript get many error.
![image](https://user-images.githubusercontent.com/62053210/92545599-76755b80-f28b-11ea-8b53-f4e817f6f399.png)
plz hlp

**Comment by hwanhee1102** [comment]
oh but on skript plugin load, says "All scripts loaded without errors."
and on sk reload all, it says "Encounter 15 error" how can i do?

**Comment by ShaneBeee** [comment]
1) When using this issue tracker, please fill in the template that is given to you, rather that deleting it.
2) The syntax you are using is not Skript syntax, I believe the one you are using is from skRayFall, so either:
a) report the issue to the respective addon
b) use Skript's syntax http://skriptlang.github.io/Skript/effects.html#EffSendTitle
