### ISSUE TITLE
Can't check if an item has NO NAME with: item named ""

### ISSUE THREAD

**Issue by Leonardo-Fiori** [SkriptLang/Skript#3372]
Sorry, i thought i had to re-open a new ticket on this because you marked the only two existing tickets regarding this issue as completed. I didn't know what to do and this issue is hitting my server really really much because i have coded a bank system based on it! Close this if you think it's useless, but the issue is still here! 😢 

i used this line of code to check if player had X regular diamonds (that had **no** special **name** or lore):
`if arg-player has arg-number of diamonds named "":`

now, after updating to beta 3, beta 2 or also last nightly build, i get this error on load of the script:
`the 1st argument of diamond named "" is not an item type (atm_diamond.sk, line 233: if arg-player has arg-number of diamonds named "":')`

### Server Information
* **Server version/platform:** git-Paper-184
* **Skript version:** **Skript version 2.5-beta3 also beta2 and also last nightly build (built 12 days ago)**

**Comment by Pikachu920** [comment]
the name is probably not an empty string but rather nothing at all (null). have you tried something like this: `if name of player's tool is not set:`?

**Comment by Leonardo-Fiori** [comment]
It used to work, always worked. The problem is that the code is written in a different way, take a look:

command /atm-deposit-dm <number> <player>:
	trigger:
		**if arg-player has arg-number of diamonds named "":**
			remove arg-number of diamonds named "" from arg-player's inventory
			add {_worth} to arg-player's money
			play sound "block.metal.step" with volume 1 and pitch 2 for arg-player

you see, how can i use the `is not set` condition?

**Comment by Leonardo-Fiori** [comment]
@ShaneBeee hey man, sorry if i look annoying but i just tested on beta 4 and nope! issue is not solved 😢 

```
if arg-player has arg-number of diamonds named "":
	remove arg-number of diamonds named "" from arg-player's inventory
```
just accepts renamed diamonds, and diamonds named "Diamond" using /irename from Essentials. I just want to check if it actually has no name! Don't know what to do
