### ISSUE TITLE
Specifying a text directly in the split expression does not work

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#3374]
### Description
When using the `%text% split (at|using|by) [[the] delimiter] %text%` expression, an error is displayed in the console at the time of parse.

### Steps to Reproduce
```py
on script load:
	set {_s} to "Hello"

	set {_a::*} to "Hello" split at "e" # Does not work
	set {_a::*} to {_s} split at "e" # Works

	set {_a::*} to split {_s} at "e" # Works
```

### Expected Behavior
There should be no error, like the `split %text% (at|using|by) [[the] delimiter] %text%` expression wich works properly.

### Errors / Screenshots
```
[18:45:01 ERROR]: {_a::*} can't be set to '"Bonjour" split at "j"' because the latter is not an object (test.sk, line 3: set {_a::*} to "Bonjour" split at "j"')
```

### Server Information
* **Server version/platform:** 2.5-beta3
* **Skript version:** git-Paper-264 (MC: 1.15.2)

**Comment by TPGamesNL** [comment]
Duplicate of https://github.com/SkriptLang/Skript/issues/719

**Comment by Romitou** [comment]
Thank you!
