### ISSUE TITLE
Links in plain chat using variables / expressions does not work

### ISSUE THREAD

**Issue by Viljami0** [SkriptLang/Skript#3377]
### Description

I cannot use links with variables in them. Looked at issue [#501](https://github.com/SkriptLang/Skript/issues/501) and doing that worked, but when I put any variable or expression in it, it failed. 

### Test skript:
`command /uuid <offline player>`
`  permission: op`
`  trigger:`
`    message "<link:http://namemc.com/profile/%arg-1's uuid%>&3Namemc site<reset>`

It sends `<link:http://namemc.com/profile/(your-uuid)>&3Namemc site`

### Steps to Reproduce

1. Make a new file named test.sk
2. Paste the script as mentioned above
3. Run /sk reload test
4. Run /uuid <your-name>
5. Click on the 'Link'

### Expected Behavior

A window should have popped up saying 
Are you sure you want to open this website
http://namemc.com/profile/<your-uuid>
Never open links from people you don't trust
Yes      Copy to clipboard       No

### Server Information
* **Server version/platform:** git-Paper-192 (MC: 1.16.3)
* **Skript version:** Latest aka 2.5-beta3

**Comment by DeltaRays** [comment]
Try using **send formatted** instead of **message**

**Comment by Viljami0** [comment]
> Try using **send formatted** instead of **message**

Works, thank you so much!
