### ISSUE TITLE
Colored particles are still broken

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#3379]
### Description

It simply fails to load the script with a huge stacktrace if used in a script, if used in effect command it throws many stacktraces too.
### Steps to Reproduce

!play purple dust at player
### Expected Behavior

to just work as I remember it was mentioned to be fixed
### Errors / Screenshots

https://pastebin.com/raw/x8g9GpdB

### Server Information
* **Server version/platform:**  1.12.2 Paper
* **Skript version:**  2.5-beta3

**Comment by ShaneBeee** [comment]
When I updated the classes, I couldn't find a way to make coloured particles work for legacy versions.
Im not sure if Spigot/Bukkit API documentation is missing something or maybe it wasn't possible with the Bukkit API back then. Im really not sure.
Im going to mark this as a low priority bug as it doesn't seem to affect 1.13+

**Comment by Govindass** [comment]
they used to work a very long time ago for me
