### ISSUE TITLE
Copy Alert

### ISSUE THREAD

**Issue by Lucas4545ah** [SkriptLang/Skript#3380]
Hello, y'know do you support apexhosting? The only thing I found was this: **https://dev.bukkit.org/projects/skript**

**Comment by Lucas4545ah** [comment]
The logo is suspicious.

**Comment by ShaneBeee** [comment]
Closing as Im not really sure what the question is here.

**Comment by Pikachu920** [comment]
That is the original plugin page for Skript back when the original creator was still working on it so it is legit it's just very outdated. Where does apexhosting come into this?
