### ISSUE TITLE
Scoreboard glitch

### ISSUE THREAD

**Issue by torisetDev** [SkriptLang/Skript#3387]
### Description

Any basic scoreboard skript with %loop-player%  will show the other's scoreboard instead of the actuall loop-player

### Expected Behavior

The scoreboards should have been per player not global.

### Errors / Screenshots

None

Nope

![image](https://user-images.githubusercontent.com/67580316/93658744-057e3280-fa47-11ea-9bd6-8b108dadcaca.png)

### Server Information
* **Server version/platform:** 
* **Skript version:** 
Paper 1.16.3
Latest Alpha (Release 4 Alpha)

**Comment by ShaneBeee** [comment]
Skript doesn't have scoreboards, which means you are using an addon for your scoreboard. 
This issue tracker is for Skript itself, we do not provide support for addons, Please report your issue to said addon.
