### ISSUE TITLE
wrong example for Enchanting Experience Cost skript2.5

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#3397]
https://skripthub.net/docs/?id=4268

wrong example:
```
pattern: [the] [displayed] ([e]xp[erience]|enchanting) cost
on enchant:
	send "Cost: %the displayed cost of enchanting%" to player```

**Comment by APickledWalrus** [comment]
Comes from here for those looking: https://github.com/SkriptLang/Skript/blob/c7f9aa951ab1d5c557263822ddf53e37c5be82a0/src/main/java/ch/njol/skript/expressions/ExprEnchantingExpCost.java#L47
