### ISSUE TITLE
Wrong alias name for zombie piglin

### ISSUE THREAD

**Issue by WrexBG** [SkriptLang/Skript#3398]
### Description
The type of zombie piglins returns "(zombie pigman". Firstly, it has that weird bracket in the beginning, and secondly, maybe it could be changed to "zombie piglin". This can cause inconvenience when checking the type. The issue does not apply for using 
"zombie pigman" as a type. If you try "summon zombie pigman at player" it will work fine.

### Steps to Reproduce
E.g. broadcast the type of an entity that's zombie piglin
broadcast "%target%"
broadcast "%type of target%"

### Expected Behavior
Skript should return "(zombie pigman"

### Errors / Screenshots
There are no errors in the console. 
![image](https://user-images.githubusercontent.com/40688355/94160829-55b12680-fe85-11ea-9bc7-ddb2cf5593a1.png)

### Server Information
Server: Paper version git-Paper-198 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Skript:  Skript version 2.5-beta4

### Additional Context
Other addons and plugins
![image](https://user-images.githubusercontent.com/40688355/94161083-9872fe80-fe85-11ea-9131-e7e347f55b1a.png)

**Comment by ShaneBeee** [comment]
1) The bracket thing, that is weird, Ill try get that fixed soon
2) As for the type, that probably won't get changed, and here is why:
In the lang file:
```
	zombie pigman:
		name: (zombie pig¦man¦men|zombified piglin)
		pattern: <age> (zombie pigm(an|1¦en)|zombified piglin(|1¦s))|(4¦)(zombie pigletboy(|1¦s)|zombified piglin (kid(|1¦s)|child(|1¦ren)))
```
To support multiple versions both names are there. It just happens to be returning the first option, but both are usable for comparison.

**Comment by WrexBG** [comment]
1. Awesome, thanks a lot!
2. Ooh I tried "zombie piglin" and it wasn't a thing. That's why I though it's not updated. My bad that I didn't look at the aliases. But maybe "zombie piglin" might be added as well haha.

**Comment by ShaneBeee** [comment]
> Ooh I tried "zombie piglin" and it wasn't a thing. That's why I though it's not updated. My bad that I didn't look at the aliases. But maybe "zombie piglin" might be added as well haha.

in all fairness, that's not their name.... they might be offended (im joking), but yeah, That might be a good idea and shouldn't be too hard to fix.
