### ISSUE TITLE
Play sound syntax doesn't support custom namespaces.

### ISSUE THREAD

**Issue by Patbox** [SkriptLang/Skript#3404]
### Description
Skript's play sound syntax doesn't work, if you want to use namespaced sounds
### Steps to Reproduce
Just execute this: `play sound "minecraft:block.note_block.pling"`
It will not play anything.

### Expected Behavior
Just to play, like the /playsound command

### Server Information
* **Server version/platform:** Tuinity 1.16.3
* **Skript version:** 2.5

### Additional Context
From what I checked in code, it's problem with a `SOUND_VALID_PATTERN` regex, as it doesn't include `:`
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffPlaySound.java

Also, from my test with spigot's playSound (with skript-reflect), using there `:` works just fine.

**Comment by ShaneBeee** [comment]
Im marking this as an enhancement as im not really sure this would be qualified as a bug.
