### ISSUE TITLE
Teleportation cause comparison is not responding

### ISSUE THREAD

**Issue by LamCarrie** [SkriptLang/Skript#3425]
### Description
The teleportation cause is not working. Whenever I compare it to anything, nothing gets send whatsoever.

### Steps to Reproduce
The code I use

```vb
on teleport:
 	if "%teleport cause%" is "chorus fruit":
 		send "hi" to player
``` 

I also tried
```vb
on teleport:
 	if %teleport cause% is chorus fruit:
 		send "hi" to player
```

### Expected Behavior
the message "hi" should have been sent, however, nothing was sent. In fact, even if I use 
```vb
on teleport:
 	send "hi" to player
```

Nothing gets sent when I get teleported
Was wondering if the
On Teleport event is broken, or the teleportation cause is broken.
Please help 

### Server Information
* **Server version/platform:** 1.16.3 Paper spigot
* **Skript version:** 2.5-beta2-MH

**Comment by LamCarrie** [comment]
I used proper indention but idk why github is not showing tab (This is the first time I posted anything)

**Comment by WeeskyBDW** [comment]
Trying remove %%
`if teleport cause is "chorus fruit"` 

 if it dont work, try `if teleport cause is "CHORUS_FRUIT"`
[see Bukkit javadoc for TeleportCause](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerTeleportEvent.TeleportCause.html)

**Comment by LamCarrie** [comment]
Nope, doesnt work.
Error msg: Can't compare teleport cause with a text 
As I said, the problem still occurs even if the skript is just 
on teleport:
send "hi" to player

**Comment by Pikachu920** [comment]
try these:
`if teleport cause is chorus:`
`if teleport cause is "chorus fruit" parsed as a teleport cause:`

**Comment by APickledWalrus** [comment]
I'm not able to reproduce this issue on 2.5 release:
![image](https://user-images.githubusercontent.com/29044720/94995522-eca86d80-056c-11eb-8331-eabfecbda665.png)

However, it is odd that the event is fired twice when I eat chorus fruit. I suspect that might just be a spigot thing though.

**Comment by LamCarrie** [comment]
> I'm not able to reproduce this issue on 2.5 release:
> ![image](https://user-images.githubusercontent.com/29044720/94995522-eca86d80-056c-11eb-8331-eabfecbda665.png)
> 
> However, it is odd that the event is fired twice when I eat chorus fruit. I suspect that might just be a spigot thing though.

Whats the skript you used, mind posting it?

**Comment by APickledWalrus** [comment]
Latest release https://github.com/SkriptLang/Skript/releases/tag/2.5

**Comment by LamCarrie** [comment]
I mean the script of the skript xd

**Comment by APickledWalrus** [comment]
```vb
on teleport:
  send "&bTELEPORT EVENT FIRED" to player
  if the teleport cause is chorus:
    send "&dTELEPORT CAUSE IS CHORUS FRUIT"
```

**Comment by LamCarrie** [comment]
aight this should be a problem of skript version I'm using, thank you very much
