### ISSUE TITLE
event-slot for helmet,chestplaye,leggings,boots

### ISSUE THREAD

**Issue by ExtraSmartMiner** [SkriptLang/Skript#3430]
when I was using "if event-slot is (player's helmet, player's chestplate, player's leggings or player's boots):" it would also think that it was slots 39,38,37,36 in a double chest

To do just do:
on inventory click:
    if event-slot is (player's helmet, player's chestplate, player's leggings or player's boots):
        broadcast "Armor"

It should only work for slots 39,38,37,36 in the player inv not double chests/guis

![chest](https://user-images.githubusercontent.com/70736085/95016852-44051700-061b-11eb-9bc3-8453763fdf71.PNG)

Server: 1.16.3
Script Version 2.5

**Comment by ShaneBeee** [comment]
Tested and can reproduce.
