### ISSUE TITLE
Strange lore parse bug

### ISSUE THREAD

**Issue by CrazyWords1** [SkriptLang/Skript#3449]
Description
I have a item with some lore (player name and simple number), and i have a variable where i use player name and simple number, but when i'm want to receive this variable, from lore parsing, i'm can't do this.
Steps to reproduce
set {_player} to line 2 of lore of player's tool
set {_card} to line 4 of lore of player's tool
send "{pd::%{_player}%::cards::%{_card}%} = %{pd::%{_player}%::cards::%{_card}%}%"
![изображение](https://user-images.githubusercontent.com/32343185/95277939-7a83a180-0868-11eb-9a47-a719f9a13b17.png)

**Comment by ShaneBeee** [comment]
closing due to lack of info, template deleted.
