### ISSUE TITLE
strange bug with lore 

### ISSUE THREAD

**Issue by CrazyWords1** [SkriptLang/Skript#3450]
### Description
I have a item with some lore (player name and simple number), and i have a variable where i use player name and simple number, but when i'm want to receive this variable, from lore parsing, i'm can't do this.
### Steps to Reproduce
set {_player} to line 2 of lore of player's tool
set {_card} to line 4 of lore of player's tool
send "{pd::%{_player}%::cards::%{_card}%} = %{pd::%{_player}%::cards::%{_card}%}%"

### Expected Behavior
Variable is not <none>, variable = 0

### Errors / Screenshots

![изображение](https://user-images.githubusercontent.com/32343185/95278275-45c41a00-0869-11eb-84f3-5c0bbc668765.png)

### Server Information
![изображение](https://user-images.githubusercontent.com/32343185/95278225-22996a80-0869-11eb-9b08-df3293617458.png)

**Comment by ShaneBeee** [comment]
do you have pictures of this item's lore?

**Comment by CrazyWords1** [comment]
![изображение](https://user-images.githubusercontent.com/32343185/95278369-7b690300-0869-11eb-95c2-7d0a7ad29385.png)

**Comment by ShaneBeee** [comment]
debug your code, this is most likely user error

**Comment by APickledWalrus** [comment]
It looks like you’re using a semi-colon in your list. `cards:;1`

**Comment by CrazyWords1** [comment]
![изображение](https://user-images.githubusercontent.com/32343185/95278529-d3076e80-0869-11eb-9b1c-4c6e95110bcb.png)

**Comment by ShaneBeee** [comment]
closing cause this is just user error

**Comment by CrazyWords1** [comment]
Help me please, i don't understand what error i have?

**Comment by ShaneBeee** [comment]
This is an issue tracker for the Skript plugin. 
We use it for reporting actually issues with the plugin, not for helping with Skript code.
If you need help, you can find some links in the readme
