### ISSUE TITLE
Default permission message

### ISSUE THREAD

**Issue by Leautis** [SkriptLang/Skript#3451]
the default permission message to be an option in the config

**Comment by ShaneBeee** [comment]
default permission is handled by the server, not by Skript

**Comment by APickledWalrus** [comment]
Do you mean this message?

https://github.com/SkriptLang/Skript/blob/7255ce1d280d34dd195d2368a58dbfb4bf9e9b7e/src/main/resources/lang/english.lang#L163

**Comment by ShaneBeee** [comment]
oh wait that's in Skript? .... ooo, ignore me 🤣

**Comment by ShaneBeee** [comment]
Ok closing this because apparently its in the lang file already
