### ISSUE TITLE
Color bug V2.5

### ISSUE THREAD

**Issue by SoMuchWessel** [SkriptLang/Skript#3458]
Hey there,

I found a problem with colors in the latest 2.5 skript.

This is the code:
![image](https://user-images.githubusercontent.com/27766663/95625176-61e9d600-0a78-11eb-8bdd-d3807176d0fe.png)

This is the result:
![image](https://user-images.githubusercontent.com/27766663/95625213-6f06c500-0a78-11eb-86de-383e7e789b21.png)

**Comment by ShaneBeee** [comment]
`send coloured` or `send formatted`

Closing as this is not an issue
