### ISSUE TITLE
1.16 colors bug Skript 2.5

### ISSUE THREAD

**Issue by SoMuchWessel** [SkriptLang/Skript#3459]
Hey there,

I ran into an issue when using the 1.16 skript color support.

Code:
![image](https://user-images.githubusercontent.com/27766663/95626136-facd2100-0a79-11eb-8e0d-5cdbe886b4eb.png)

The result:
![image](https://user-images.githubusercontent.com/27766663/95626153-04568900-0a7a-11eb-85e7-9c8e04ee4357.png)

**Comment by ShaneBeee** [comment]
you literally just reported this, I replied AND closed it
