### ISSUE TITLE
Severe Error: Java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by yawyann** [SkriptLang/Skript#3461]
### Description
I'm regenerating the map, All goes to plan but a error on console shows.

### Steps to Reproduce
Try and set a location to something that needs direction, like a door or torch.

### Expected Behavior
Regen all the blocks in the list.

### Errors / Screenshots
ERROR: https://paste.md-5.net/wulituhoni.md
CODE: https://paste.md-5.net/uqofiqopov.coffeescript

### Server Information
* **Server version/platform:** 1.1.6.3
* **Skript version:** 2.5

**Comment by ShaneBeee** [comment]
Can you try updating to 1.16.3 before reporting issues please.
Skript only supports the latest revision of any Minecraft major release.

from your error:
```
Bukkit: 1.16.2-R0.1-SNAPSHOT
Minecraft: 1.16.2
```
This may very well be an old CB/Spigot issue.

**Comment by yawyann** [comment]
> Can you try updating to 1.16.3 before reporting issues please.
> Skript only supports the latest revision of any Minecraft major release.
> 
> from your error:
> 
> ```
> Bukkit: 1.16.2-R0.1-SNAPSHOT
> Minecraft: 1.16.2
> ```
> 
> This may very well be an old CB/Spigot issue.

It still happens on 1.16.3.
ERROR: https://paste.md-5.net/axakesuxey.md

**Comment by ShaneBeee** [comment]
what exactly are you setting?
The error seems a bit odd, like you're attempting to set a wall torch facing down.

**Comment by yawyann** [comment]
I'm setting torches, stair cases, doors. Pretty much like a village. I'm going to repaste the schematic because it could be something that I messed up pasting the schematic.

**Comment by yawyann** [comment]
Yeah, It still happens with the fresh map. It seems that the variable isn't being saved right? The torch was placed facing east and when my Skript started the regeneration, It would place the torch in a different direction (shown here: https://prnt.sc/uwtgsr). I have absolutely no clue how or why it behaves like that.

**Comment by ShaneBeee** [comment]
Im not sure either. 
The code you sent is missing information, and without that info, I really have no clue what you're saving/doing.

**Comment by yawyann** [comment]
Here's the code.
CODE: https://paste.md-5.net/cemulalone.coffeescript

**Comment by ShaneBeee** [comment]
Ok, well the misdirection of how your torches are being pasted is just user error.
You're saving a string variation of the block into a var, and then parsing it as an item type. This is not a reliable way to do things, and is definitely not something I would recommend.
I suggest using block data.

As for the error, Im confused. The error is a Minecraft error not a Skript error... it seems like its trying to set a wall torch's facing to "down", which I dont even know how that's possible, Skript has nothing for that.
I'm really not sure if this is a Skript, Spigot or Minecraft issue.

**Comment by yawyann** [comment]
Ah, Since it is probably user error, I'll close this issue and keep trying to find the fix with block data. Thank you for your time, Shane.
