### ISSUE TITLE
String multiplication

### ISSUE THREAD

**Issue by Leautis** [SkriptLang/Skript#3464]
allow multiplication of text:
"string" * 3 = "stringstringstring"

**Comment by ShaneBeee** [comment]
This has been discussed a few times.

Internally the code to do this, would be exactly the same as how you would do it in a script. 
Therefor something of this caliber really makes no sense to put in Skript.

Here is a simple function you can use, with an example of usage
```vb
# Function
function stringMultiply(s: string, i: integer) :: string:
	set {_new} to ""
	loop {_i} times:
		set {_new} to "%{_new}%%{_s}%"
	return {_new}

# Usage
on load:
	set {_a} to stringMultiply("test", 5)
	send "T: &b%{_a}%" to console
```
