### ISSUE TITLE
Inventory action bug; Can't compare with 'hotbat move' and 'readd';

### ISSUE THREAD

**Issue by WrexBG** [SkriptLang/Skript#3465]
### Description
Skript throws an error when comparing `inventory action` with `hotbar move and readd` which is when you swap an item from another inventory with an item in your hotbar.

### Steps to Reproduce
Try to parse:
```
on inventory click:
    if inventory action = (hotbar move and readd):
        broadcast "&7[&cBug&7] &7This will give an error!"
```

### Expected Behavior
No error and a message `"&7[&cBug&7] &7This will give an error!"` should have been broadcasted when swapping an item from another inventory with an item in your hotbar.

### Errors / Screenshots
```
[19:58:02 INFO]: [Skript] Reloading test.sk...
[19:58:02 ERROR]: Can't compare a inventory action with ('hotbar move' and 'readd') (test.sk, line 2: if inventory action = (hotbar move and readd):')
[19:58:02 INFO]: [Skript] Encountered 1 error while reloading test.sk!
```
![image](https://user-images.githubusercontent.com/40688355/95777532-a79bde00-0cc6-11eb-8526-398147826dfa.png)

### Server Information
* **Server version/platform:** git-Paper-198 (MC: **1.16.3**) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
* **Skript version:** 2.5

### Additional Context
Other plugins and addons:
![image](https://user-images.githubusercontent.com/40688355/95777761-1a0cbe00-0cc7-11eb-8732-24d4ccf50a96.png)

**Comment by ShaneBeee** [comment]
Based on the error:
`Can't compare a inventory action with ('hotbar move' and 'readd') `
It appears its trying to compare with 2 different things... silly Skript.
