### ISSUE TITLE
Server freeze when reloading script

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#3470]
### Description
Server just freeze when reloading script with this code. When Skript loads scripts the server freeze for over 4 minutes by this script.

### Steps to Reproduce
Use this code:
```vb
command House-Boom:
	trigger:
		set weather to rain
		wait 3 seconds
		loop 10 times:
			set {_loc} to location of (random element out of ((all blocks in region "burza") where [location of input is location of highest solid block at location of input]))
			strike lightning effect at {_loc}
			wait 5 seconds
		wait 10 seconds
		set the weather to default
```

### Expected Behavior
The server should not be freeze for a few minutes.
### Errors / Screenshots
None

 https://pastebin.pl/view/fab7831a

I was not able because the server crash when I reload the script in game.

### Server Information
* **Server version/platform:** This server is running Paper version git-Paper-220 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
* **Skript version:** 2.5

### Additional Context
SK-NBeeT v2.10.0
SkQuery v4.1.3
skUtilities v0.9.2
Skent v1.9
SharpSK v1.6.3

**Comment by DeltaRays** [comment]
I can't replicate this issue with only skript 2.5 and on paper 220 (1.16.3).

**Comment by Misio12320** [comment]
Then weird. Might this code
`command /asert:
    description: wear a block as helmet/head
    permission: skript.hat
    trigger:
        equip player with holding item`
because the server freeze after sending this:
 "Can't understand this condition/effect: equip player with holding item (dominek.sk, line 110: equip player with holding item')" 
after 2 minutes it sends:
"[Skript] [location of input is location of highest solid block at location of input] is not a valid lambda statement. (dominek.sk, line 119: set {_loc} to location of (random element out of ((all blocks in region "burza") where [location of input is location of highest solid block at location of input]))')
[17:27:12 ERROR]: [Skript] the weather in event-world can't be set to the default MOTD because the latter is not a weather type (dominek.sk, line 123: set the weather to default')"

**Comment by DeltaRays** [comment]
I think it's your original code, but skript is not causing it. I'll install the addons you have and will test to see

**Comment by DeltaRays** [comment]
After trying again it seems as if skript is causing it, but I don't know why, sorry.

**Comment by Misio12320** [comment]
Okay them. Thanks, I need a bypass to fix this.

**Comment by Misio12320** [comment]
I've wrote into another sk file and yeah, the crash is caused by this code said in thread. https://pastebin.pl/view/ca726a4e

Plugins (14): Citizens, Denizen, Multiverse-Core, PluginConstructorAPI, ServerRestorer, SharpSK*, SK-NBeeT, Skent*, SkQuery, Skript, skUtilities*, WorldBorder, WorldEdit, WorldGuard
I'm using bungeecord (Waterfall). . I have tested this on another hosting and this same occur. 
With version 2.5-beta1 the delay does not occur.

**Comment by ShaneBeee** [comment]
Lines like this:
```
set {_loc} to location of (random element out of ((all blocks in region "burza") where [location of input is location of highest solid block at location of input]))
```
are doing A LOT of work for the Skript parser. You've got like 4 different expressions here. Break your code up.
You're putting too much stress on your server.

Im closing this, as this is something that has been reported multiple times.
