### ISSUE TITLE
Bug for variables list

### ISSUE THREAD

**Issue by Lennord** [SkriptLang/Skript#3471]
Hello, I have a big problem, when I put a variable at best of a block it gives me an error, in fact what I want is when we have a rental position of 1 and 2, I want that its gives me the blocks of position 1 and 2....

Error: https://pastebin.com/b6gTQ2qq
Code: https://pastebin.com/isQfB0v2
Spigot: 1.16.3
Skript version: 2.5

**Comment by ShaneBeee** [comment]
Skript does not currently have a `blocks within` expression... so that is an issue with another addon.
