### ISSUE TITLE
on commandblock command:

### ISSUE THREAD

**Issue by buccimichele5** [SkriptLang/Skript#3472]
Hello! Today I would like to suggest this new event
`on commandblock command:`
This should be triggered when a commandblock executes a command, also, like `on command:` we should be able to check what command it was with `if command is "blabla":` 
This would be very useful in a lot of cases. for example people could create some sort of commandblocks system for creative servers.

**Comment by WeeskyBDW** [comment]
Hey !
```
on command:
    send command sender
```
doesn't return "command block" when a command is executed by a command block ?

**Comment by ShaneBeee** [comment]
This can all already be done:

<img width="977" alt="Screen Shot 2020-10-15 at 12 49 37 AM" src="https://user-images.githubusercontent.com/20008482/96092936-5cc5c600-0e80-11eb-91b0-2503489da658.png">

**Comment by buccimichele5** [comment]
hi! I didn't know this, and after a bit of searching I tought it was impossible. Thanks!
