### ISSUE TITLE
On jump cancel teleport one block under

### ISSUE THREAD

**Issue by ThePitereq** [SkriptLang/Skript#3473]
My code (very simple):
```
on jump:
	cancel event
```
Server version: git-Paper-1618 (MC: 1.12.2)

When i cancel the jump player is teleported one block under last position. On older version of Script it works fine.

**Comment by ShaneBeee** [comment]
Which version of Skript are you using?

For future reference, please fill in the issue template we provide rather than deleting it.

**Comment by ThePitereq** [comment]
Latest version of Script. Sorry about no template but i am new on github and i've not found any topic about template.

**Comment by ShaneBeee** [comment]
I tested this using Skript 2.5 on both Paper 1.16.3 and Paper 1.12.2.
Both cases worked as expected.

That said, the behaviour of an event cancellation is handled by the server (ie: Paper) not Skript. 

I recommend looking for conflicting plugins, such as addons which may have changed how this event works and/or is handled.
