### ISSUE TITLE
Error with log handlers

### ISSUE THREAD

**Issue by NiniMine** [SkriptLang/Skript#3474]
### Description

After a server restart i sometimes get the error message "1 log handler was not stopped properly! 
### Steps to Reproduce

Sometimes after a server restart

### Errors / Screenshots

<a href="https://ibb.co/6m30f7y"><img src="https://i.ibb.co/6m30f7y/loghandlers.png" alt="loghandlers" border="0"></a>

### Server Information
* **Server version/platform: Paperspigot 1.16.3** 
* **Skript version: 2.5**

**Comment by APickledWalrus** [comment]
These errors usually come from an outdated version of skript-mirror. Please try updating to a newer version.
