### ISSUE TITLE
[Bug] split can't work

### ISSUE THREAD

**Issue by Command1264** [SkriptLang/Skript#3475]
### Description
split can't work

### Steps to Reproduce
1.write
```
command split:
	trigger:
		set {_scripts::*} to all files of dir path "plugins/test"
		loop {_scripts::*}:
			send "%loop-value%" to command sender

			add loop-value split by "\" and "/" to {_splitString::*}

		
		loop {_splitString::*}:
			send "%loop-value%" to command sender
		send "%{_splitString::*}%" to command sender
```
in test.sk
2. reload test.sk
3. run command "/split"
4.See error

### Expected Behavior
```
plugins\test\-test2.sk
plugins\test\test1.sk
plugins\test\test3.sk
plugins\test\test4.sk
plugins
test
-test2.sk
plugins
test
test1.sk
plugins
test
test3.sk
plugins
test
test4.sk
plugins, test, -test2.sk, plugins, test, test1.sk, plugins, test, test3.sk, plugins, test and test4.sk
```
like this

### Errors / Screenshots
![螢幕擷取畫面 2020-10-15 231727](https://user-images.githubusercontent.com/50344708/96150438-ee930900-0f3c-11eb-95ec-089640fff14d.png)
![螢幕擷取畫面 2020-10-15 231425](https://user-images.githubusercontent.com/50344708/96150451-f357bd00-0f3c-11eb-9deb-c05d8d21e330.png)

### Server Information
* **Server version/platform:** Spigot-1.16.3
* **Skript version:** 2.5

**Comment by ShaneBeee** [comment]
The split expression only takes in one delimiter, not two.
