### ISSUE TITLE
1.8 Skript help

### ISSUE THREAD

**Issue by AidanTheBandit** [SkriptLang/Skript#3476]
On 1.8 anytime I try to run a skript command is just says /skipt help . When I try to do /skript help it just says the same thing. Please add 1.8 support or if this is a bug fix the bug.

**Comment by ZorgBtw** [comment]
Hey ! Skript is only 1.9+, but you can also download Skript for 1.8 with this link » https://github.com/Matocolotoe/Skript-1.8/releases (this is a Skript's fork for 1.8)

**Comment by AidanTheBandit** [comment]
thanks it worked
