### ISSUE TITLE
Funny bug with on spawn

### ISSUE THREAD

**Issue by Galajus** [SkriptLang/Skript#3477]
### Description
spawn loop entity

### Steps to Reproduce
```
on spawn:
	if spawn reason is "natural" parsed as spawn reason: #btw "if spawn reason is spawner egg" doesn't work
		if chance of 100%: #for tests
			set name of event-entity to "test"
```

### Errors / Screenshots

no errors

https://prnt.sc/v1h8p7 -> work time 7 minutes
https://prnt.sc/v1h9t1 haha :D

### Server Information
* **Server version/platform:**  Bug is tested on 1.15.2 and 1.16.3 Paper
* **Skript version:**  2.5

**Comment by APickledWalrus** [comment]
Maybe I’m missing something... but what is the bug here?

**Comment by Galajus** [comment]
try this code and you understand :D for example, use my code, walk on map 3 minutes and watch how fast mobs are spawning around you

**Comment by Moderocky** [comment]
> try this code and you understand :D for example, use my code, walk on map 3 minutes and watch how fast mobs are spawning around you

This isn't a bug, you're giving the entities a name, so they become persistent. When they're persistent they don't count to the mob cap, so the game is free to spawn more entities.

**Comment by Runakai1** [comment]
Adding PersistenceRequired:0b to the nbt of the entity adds them to the mob count

**Comment by Galajus** [comment]
> > try this code and you understand :D for example, use my code, walk on map 3 minutes and watch how fast mobs are spawning around you
> 
> This isn't a bug, you're giving the entities a name, so they become persistent. When they're persistent they don't count to the mob cap, so the game is free to spawn more entities.

Oh... i'm stupid xd
