### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by WesleyAustin** [SkriptLang/Skript#3482]
### Description
Console Error

### Steps to Reproduce

Ran my script, that normally functions fine, when the server TPS was low (around 10), with around 23,000 chunks loaded and 8,500 entities.

### Expected Behavior

The console should have outputted the result of the calculation that the script was doing

### Errors / Screenshots

https://pastebin.com/vp01gXfe

### Server Information
* **Server version/platform:** CraftBukkit version git-Spigot-4af49dc-c5e9a16 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
* **Skript version:** 2.5

**Comment by ShaneBeee** [comment]
Steps to reproduce:
> Ran my script, that normally functions fine, when the server TPS was low (around 10), with around 23,000 chunks loaded and 8,500 entities.

But... what is the script?!?!? "Steps to reproduce" is supposed to be steps so WE (the dev team, or anyone really) can reproduce this situation, and help us find the error.

**Comment by WesleyAustin** [comment]
This is the function that is running whilst I received the error.
{poslist::*} is a list of possible samples. (containing 15 strings)
{sample2::%loop-value%::*} is a list of data (containing 7 doubles)
{sample::%loop-value%::*} is another list of data (containing 7 doubles)

Is this enough of the script to reproduce the error?
```
function similarity(p: player):
	loop {poslist::*}:
		set {dp::%loop-value%} to 0
		loop {sample2::%loop-value%::*}:
			loop {sample::%{_p}%::*}:
				if loop-index-2 = loop-index-3:
					add loop-value-2*loop-value-3 to {dp::%loop-value-1%}
		wait 1 tick

	loop {poslist::*}:
		send "%{dp::%loop-value%}%" to console
	set {mag::%{_p}%} to 0
	loop {sample::%{_p}%::*}:
		add loop-value^2 to {mag::%{_p}%}
	set {mag::%{_p}%} to sqrt {mag::%{_p}%}
	delete {closest::%{_p}%}
	wait 1 tick
	loop {poslist::*}:
		wait 1 tick
		send "&6%{dp::%loop-value%}% / %{mag::%{_p}%}%*%{magnitude::%loop-value%}%" to console
		set {similarity1::%loop-value%::%{_p}%} to {dp::%loop-value%}/({mag::%{_p}%}*{magnitude::%loop-value%})
		if {closest::%{_p}%} is not set:
			set {closest::%{_p}%} to {similarity1::%loop-value%::%{_p}%}
		else:
			send "&c%{similarity1::%loop-value%::%{_p}%}% %loop-value%" to console
			if 1-{similarity1::%loop-value%::%{_p}%} <1-{closest::%{_p}%}:
				set {closest::%{_p}%} to {similarity1::%loop-value%::%{_p}%}
				send "&aNew closest: %{closest::%{_p}%}%" to console
	loop {poslist::*}:
		wait 1 tick
		if {dp::%loop-value%}/({mag::%{_p}%}*{magnitude::%loop-value%}) = {closest::%{_p}%}:
			set {ecld::%loop-value%::%{_p}%} to 0
			loop {sample2::%loop-value%::*}:
				loop {sample::%{_p}%::*}:
					if loop-index-2 = loop-index-3:
						add ((loop-value-2)-(loop-value-3))^2 to {ecld::%loop-value-1%::%{_p}%}
						send "&dsample2: %loop-value-2% &esample: %loop-value-3%" to console
			wait 1 tick
			send "%{ecld::%loop-value%::%{_p}%}%" to console
			set {euclideandist::%loop-value%::%{_p}%} to sqrt {ecld::%loop-value%::%{_p}%}
			send "&2--------------------------------------" to console
			send "&aClosest match: %loop-value%" to console
			send "&aMagnitude: %{mag::%{_p}%}%" to console
			send "&aMatch Magnitude: %{magnitude::%loop-value%}%" to console
			send "&cProbability: %({closest::%{_p}%})*100%%%" to console
			send "&2Euclidean Distance: %{euclideandist::%loop-value%::%{_p}%}%" to console

**Comment by ShaneBeee** [comment]
I dont think that code has anything to do with the error.
The error is coming from a sheep, regarding sheep's color.

**Comment by ShaneBeee** [comment]
I found the issue, I will hopefully get this fixed ASAP

**Comment by WesleyAustin** [comment]
Thank you
