### ISSUE TITLE
[Suggestion] On portal

### ISSUE THREAD

**Issue by buccimichele5** [SkriptLang/Skript#3485]
Hello, I see that there is an On Portal event, I think you should add a way to check what type of portal it is (end/nether)

**Comment by ShaneBeee** [comment]
You can already do this with `teleport cause`

ex:
```vb
on portal:
	send "Cause: %teleport cause%"
```
<img width="966" alt="Screen Shot 2020-10-22 at 1 39 02 AM" src="https://user-images.githubusercontent.com/20008482/96846961-737f9600-1407-11eb-82f8-3a6c94dd29ca.png">

**Comment by buccimichele5** [comment]
If players use `cancel event` this is not gonna work doe

**Comment by ShaneBeee** [comment]
The Bukkit API does not have any methods for getting the portal, other than the teleportation cause.
So it will be in your hands to get creative and figure out how to make it work.

**Comment by buccimichele5** [comment]
Alright, thanks for the information
