### ISSUE TITLE
ternary doesn't work with strings

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3490]
### Description
you can use the ternary expression with numbers, but not text

### Steps to Reproduce
```
set {_d} to "hi" if 1 = 1 else "d"
```
doesn't work,
```
set {_d} to 5 if 1 = 1 else 10
```
does work

### Expected Behavior
it should return "hi", but instead errors

### Errors / Screenshots
Can't understand the expression

### Server Information
* **Server version/platform:** Paper 1.16.3 (#240)
* **Skript version:** 2.5

**Comment by Romitou** [comment]
Try surrounding your text with parentheses, like this:
`set {_} to "hi" if 1 = 1, else ("d")`.

**Comment by Pikachu920** [comment]
been around for a while unfortunately: I think it was first reported in #3410 719

**Comment by MrScopes** [comment]
> Try surrounding your text with parentheses, like this:
> `set {_} to "hi" if 1 = 1, else ("d")`.

yeah this works, would still be nice if it's fixed
