### ISSUE TITLE
%variable% parses stuff different than normal variables

### ISSUE THREAD

**Issue by MrEnxo** [SkriptLang/Skript#3491]
### Description
Sometimes %variable% just parses stuff different than a normal variable like if i wanna do confusing ish computations with locations like %location at block below event-block% that does not work at all it just bugs out

### Steps to Reproduce
make a on place right and set a variable like this one {block::%location at block below event-block%} or something bridging off one blocks location and it does not work also some other things like player's uuid If i want to do arg-1's uuid i have to do set {_pu} to arg-1's uuid then put it in a variable as a key

### Expected Behavior
let me do it without bugging out

### Errors / Screenshots
im to lazy.

### Server Information
Skript

### Additional Context
Idk also locations are buggy i think its with %% tho so idk

**Comment by ShaneBeee** [comment]
Closing due to lazy bug report. 

If you wish to report an issue, put some effort into your post.
