### ISSUE TITLE
Incorrect loop-value parsing when using "Reversed List" expression

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#3492]
### Description
The type of the loop-value in a loop of the indexes is incorrect (I'm not sure this is what it is, however).

### Steps to Reproduce
This line `set {_i} to (loop-value) parsed as integer` is not valid when parsing.
```applescript
on script load:
    set {test::1} to "a"
    set {test::2} to "b"
    set {test::4} to "c"

command test <integer>:
    trigger:
        loop reversed indexes of {test::*}:
            broadcast "loop-value is a text." if loop-value is a text
            set {_i} to (loop-value) parsed as integer
```

If I remove parentheses around `loop-value`, that gives me this error:
```
[23:17:32 ERROR]: There's no loop that matches 'loop-value parsed as integer' (test.sk, line 5: set {_i} to loop-value parsed as integer')
```

### Expected Behavior
`loop-value` should indeed be considered as a text.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/35146758/97093652-1590bf80-164e-11eb-9f14-cc94ef53f204.png)
https://gist.github.com/Romitou/d397dbb01cb47921745ad0f0f1a74b90

### Server Information
* **Server version/platform:** 1.16.2 - git-Paper-182
* **Skript version:** 2.5.1

**Comment by ShaneBeee** [comment]
you are looping indexes, which are numbers not texts.

**Comment by Pikachu920** [comment]
i believe this could be fixed by making overriding `isLoopOf` for the reversed expression to call the `isLoopOf` of the original expression. that would at least let you use `loop-text` which should work.
