### ISSUE TITLE
Expression 'decimals between' totally incorrect

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#3494]
### Description
Using the `[(all [[of] the]|the)] (numbers|integers|decimals) (between|from) %number% (and|to) %number%` expression, more precisely `decimals from %number% to %number%`, the returned values are totally incorrect.

### Steps to Reproduce
Here is the code used.
```py
command test:
    trigger:
        loop decimals from 3.0 to 4.0:
            broadcast "%loop-number%"
```
Here is the result in the console.
```
6
6.1
6.2
6.3
6.4
6.5
6.6
6.7
6.8
6.9
```

### Expected Behavior
The expression should have returned correct values.
```
3
3.1
3.2
3.3
3.4
3.5
3.6
3.7
3.8
3.9
```

### Errors / Screenshots
No errors.
![image](https://user-images.githubusercontent.com/35146758/97220804-5c0c2880-17cc-11eb-9c5d-5bc47ed2c01d.png)

### Server Information
* **Server version/platform:** 1.16.2 - git-Paper-182
* **Skript version:** 2.5.1

**Comment by Romitou** [comment]
If I use the example from the documentation, - `loop decimals from 3.94 to 4: # loops 3.94, 3.95, 3.96, 3.97, 3.98, 3.99, 4` -, here is the result:
```
7.88
7.89
7.9
7.91
7.92
7.93
```

**Comment by ShaneBeee** [comment]
@bluelhf Im calling you in on this one, you wrote the decimals thing right?!?!

**Comment by TheBentoBox** [comment]
Seems like it's starting from double the intended value, then past that is counting appropriately from that point.

**Comment by TheBentoBox** [comment]
Seems like [this line](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprNumbers.java#L168) may be the issue? It's adding the start value to the current value in the iterator's `next()` which would cause it to start off at double the value.
