### ISSUE TITLE
Thrown error when check if an event-entity is equal to a type of entity

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#3499]
### Description
If we miss to write the "a" from "**a** spider" , an error is thrown. It's not only for spider but all types of entities.
No skript parsing error.

### Steps to Reproduce
```java
on spawn:
    type of event-entity is a zombie or a skeleton or a creeper or a zombie villager or a drowned or a husk or spider
    # Rest of the code
```
This thrown a console error : 
`type of event-entity is a zombie or a skeleton or a creeper or a zombie villager or a drowned or a husk or spider`
This works : 
`type of event-entity is a zombie or a skeleton or a creeper or a zombie villager or a drowned or a husk or a spider`

### Expected Behavior
With previous Skript version, we do not need to write the "a" or "an"

### Errors / Screenshots
https://hastebin.com/vojexixame.md

### Server Information
* **Server version/platform:** PAPER-249 (1.16.3)
* **Skript version:** 2.5.1

**Comment by Romitou** [comment]
After a lot of research, this is due to the addition of PR #3208.

**Comment by Romitou** [comment]
Oops, I made a mistake in my last comment which I deleted.
In any case, I can reproduce this issue with Skript 2.5.1 and git-Paper-182 (MC: 1.16.2) : https://gist.github.com/Romitou/6895be87f61831dc49ddf28d6d1b7741.

**Comment by ShaneBeee** [comment]
This isn't actually a bug, but rather user error

`spider` refers to an actual entity, ie: the spider.
`a spider` refers to an entity type.

On that note, it shouldn't throw the error it is throwing, it should throw a Skript error stating the syntax is incorrectly being used.

**Comment by TheLimeGlass** [comment]
Are you using an addon? Does your addon list include Umbaska? There is a "bug" that requires you to put the letter **a** before an entity type. It's really weird, can you attempt the same issue with no add-ons please and thank you.
