### ISSUE TITLE
Using variables inside {@%varaible%}

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#3504]
### Description

I have had this issue ever since 2.2dev36,
Options have always been a strict part of Skript I guess, they are not flexible enough.

If you try to use `{@%{variable}%}` or `{@%expression%}` this doesn't work, maybe because optinos are parsed before anything else so Skript reads it as it is like `{@%expression%}` and `%expression%` option doesn't exist so it is considered `undefined`

### Steps to Reproduce

Try the following code:
```
options:
  test1: value1
  test2: value2

on chat:
  loop 1 and 2:
    broadcast "{@test%loop-value%}" # expected to be read as {@test1} {@test2} so it broadcast value1 then value2

    # tuske evaluate extra test
    evaluate: broadcast "{@test%loop-value%}"

```

### Expected Behavior

Expected to be read as {@test1} {@test2} so it broadcast "value1" then "value2"

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/20037329/97717409-6e88a980-1acd-11eb-841b-38413a173519.png)
![image](https://user-images.githubusercontent.com/20037329/97717761-d0e1aa00-1acd-11eb-933c-29c000a0242a.png)

None

### Server Information
* **Server version/platform:** 
* **Skript version:** 
![image](https://user-images.githubusercontent.com/20037329/97717601-a7c11980-1acd-11eb-8015-396096e3448a.png)

**Comment by ShaneBeee** [comment]
1) This isn't a bug, this is intended, as you stated options are parsed at parse time, therefor variables won't work in them
2) if you need to do this, just use variables. In my opinion what you are doing makes absolutely no sense when you can use variables to do the exact same thing.

Im going to leave this open to get feedback from other devs, but in my opinion, there is no reason to change the behaviour of options.

**Comment by AyhamAl-Ali** [comment]
The only reason I'm doing this is to make these values easier to edit for other users and maybe for me later on, I usually use .yml files and make the code lots shorter but the idea of parsing variables inside the options tag can be used with looping lots of options.

This is a quick example that I am currently using (for now I'm using options as I'm coding it for simple users [more specifically using it on minehut so I can't use .yml feeatures])

```
options:
	# default values
	win-xp-percentage: 20
	win-coins-percentage: 5

	lose-xp-percentage: 10
	lose-coins-percentage: 2

	draw-xp-percentage: 15
	draw-coins-percentage: 3.5

	win-coins: 200
	win-xp: 200 * {_nextLevel}
	
	lose-coins: 50 # maybe lower?
	lose-xp: 50 * {_nextLevel}

	draw-coins: 125
	draw-xp: 100 * {_nextLevel}


	# used in a command when creating a game and setting the default values that are used in options
	loop "win", "lose", "draw":
		loop "xp", "coins":
			set {TDM::games::%arg-2%::%loop-value-1%-%loop-value-2%-percentage} to {@%loop-value-1%-%loop-value-2%-percentage}
			

```

with the idea of using loops I can save few lines and even better when I have more similar options that I can just loop some strings and get the option of that loop-value

I hope you understood my point.

After all it is a feature/addition that can be used in a way or another and options should be more flexible for such flexible programming language

**Comment by Pikachu920** [comment]
why not just use variables instead of options?

**Comment by AyhamAl-Ali** [comment]
> why not just use variables instead of options?

As I mentioned above my point, I can for sure, sometimes it is easier for users (not devs) to use options instead of checking the `on load and changing the variables there`

But the point is still why not making options more flexible, it is a feature that could be used in a way

**Comment by Pikachu920** [comment]
the thing is that it's not possible to implement this (without requiring the parsing to happen at runtime and thus cause decent lag). we could implement it so that you could use expressions that can be evaluated at parse time but that would not be very useful for your use case and probably more confusing to users than the existing implementation.
