### ISSUE TITLE
Skript Parsing output format (messy)

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#3505]
I have been using [SkriptEnhanced](https://forums.skunity.com/resources/skriptenhanced.409/) script made by `Duetro` and it was amazing how it formats the script parsing/reloading output in a very clean and readable way, also I can autocomplete script names, and it shows more details about errors and the line that has the error etc.

This script doesn't work anymore because it needs mundoSk for json stuff and mundoSk is deprecated, so I am back to Skript's default parsing output.

I would love to see Skript itself enhance that thing and make it a vanilla thing and  and I'm sure many others would love that too.

**What to enhance?**

- Add empty lines between every line (make it easier to read)
- Make `Error %line%` more visible (use it on its own line and use colors) 
- Optional: Add hover event over every error showing the error line and some other surrounding lines
- Reloading time

Images (from SkriptEnhanced):

![image](https://user-images.githubusercontent.com/20037329/97724914-36399900-1ad6-11eb-9c24-b54d33190a82.png)
![image](https://user-images.githubusercontent.com/20037329/97724927-3a65b680-1ad6-11eb-96f3-3cece054415d.png)
![image](https://user-images.githubusercontent.com/20037329/97725023-58331b80-1ad6-11eb-931f-c902e1fae9a3.png)

![image](https://user-images.githubusercontent.com/20037329/97724946-40f42e00-1ad6-11eb-96e2-61e0c9e935dd.png)

**Comment by ShaneBeee** [comment]
This is definitely a neat idea, and would help out with errors for sure.

**Comment by Misio12320** [comment]
Well, it looks good but what if people like old one? Might add into config file the old and new parser output?

**Comment by Pikachu920** [comment]
what does the old one provide that the new one doesn't? if they both provide the same info. i don't really see a reason keep the legacy one in.

**Comment by Misio12320** [comment]
The old one provide red color errors. Skript = coding. Dev-C++ contains too the red color when error occur. Maybe some older users of Skript like the old one atmosferic and would like to return to it when the new one release, dont they?
