### ISSUE TITLE
log handlers not stopped properly

### ISSUE THREAD

**Issue by KokaineKola** [SkriptLang/Skript#3513]
### Description
I added Skript mirror, and then when I tried starting my server, I got messages in the console saying "[Skript] 4 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:263)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]", I then updated Skript and when I tried starting the server again, I was spammed with hundreds of these messages.

### Steps to Reproduce
Installed the latest version of skript mirror and skript and started my server, not much else I can say.

### Expected Behavior
Should have started, with no errors.

### Server Information
* **Server version/platform:** paper-133 1.16.1
* **Skript version:** 2.5.1

**Comment by Romitou** [comment]
This is a known skript-mirror problem. Try to update with [skript-reflect](https://github.com/TPGamesNL/skript-reflect).
