### ISSUE TITLE
Lore problem

### ISSUE THREAD

**Issue by WithqutMe** [SkriptLang/Skript#3515]
### Description
I can't change the lore of an item

### Steps to Reproduce
`set lore of loop-player's tool to "LORE 1||LORE 2"`
![image](https://user-images.githubusercontent.com/53946492/97988412-38a13900-1ddd-11eb-934b-234864803996.png)

### Expected Behavior
The lore should change but it remains empty.

### Errors / Screenshots
None errors.

### Server Information
* **Server version/platform:** 1.16.4
* **Skript version:** Minehut's Skript

**Comment by ShaneBeee** [comment]
> Skript version: Minehut's Skript

We do not offer support for forks of our resource.
Please try replicate this issue using our version of Skript, or report the issue to Minehut.
