### ISSUE TITLE
Log handlers not stopped properly after loading variables

### ISSUE THREAD

**Issue by DerpoDrago** [SkriptLang/Skript#3516]
Description: I just updated to the latest Skript version to boot my server and discover that nobody can join and get kicked with the "Timed out" message after waiting on the "Encrypting" screen.

How to replicate: Start the server up

Expected behavior: Expected server to boot up normally.

Errors: https://pastebin.com/jeUBN4MH

Server jar: Tuinity 1.16.4
Skript version: Skript 2.5.1

**Comment by ShaneBeee** [comment]
This is caused by running outdated versions of skript-mirror

This has also been reported numerous times:
https://github.com/SkriptLang/Skript/issues?q=is%3Aissue+log+handler+is%3Aclosed
