### ISSUE TITLE
HEX color support to "send" effects

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#3517]
I was working with hex colors and private message channels. And I realised HEX colors couldn't read in send codes, only last letter is reading like #ff7700's &0 or #d3d3d3's & 3. Here is example:
```
command /hex:
	trigger:
		send "display: %player's display name%" to all players
		set player's display name to "<##d3d3d3>%player%"
		send "(displaying ""3"") setted to hex display: %player's display name%" to all players
		broadcast "(displaying ""##d3d3d3"") real display: %player's display name%"
```
Note: "broadcast" effect is working fine.

Skript 2.5.1 and Paper 1.16.3

**Comment by ShaneBeee** [comment]
try `send formatted` or `send coloured`

**Comment by rudde0** [comment]
I can't use them because I'm trying to do private message channels. So, players can abuse that with typing something like "<command:/op ShaneBee>hello!" or "&6H&be&el&9l&8o"

Maybe I can find a way with variables but, can't we add this feature to send effects?

**Comment by rudde0** [comment]
Also, it makes impossible to work hex codes with SkBee's component function.
```
command /hex <text>:
	trigger:
		set player's display name to "<##d3d3d3>%player%"
		set {_m} to "%player's display name%&f: %uncoloured arg 1%"
		set {_t} to text component from {_m}
		set hover event of {_t} to a new hover event showing player's tool
		send component {_t} to player
```
Output: `&3Player&f: Text`

**Comment by APickledWalrus** [comment]
probably looking at something like https://github.com/SkriptLang/Skript/issues/3112 for this

**Comment by ShaneBeee** [comment]
> I can't use them because I'm trying to do private message channels. So, players can abuse that with typing something like "<command:/op ShaneBee>hello!" or "&6H&be&el&9l&8o"

in a case like this, you could just do something like 
```vb
send formatted "<##123456>BLAH BLAH %player% &r>> %uncolored arg-1%"
```

Also, I texted your exact code for the SkBee thing, and it worked fine for me:
<img width="966" alt="Screen Shot 2020-11-30 at 2 22 48 AM" src="https://user-images.githubusercontent.com/20008482/100597955-f3c0d300-32b2-11eb-961b-2cc2ed112551.png">


Either I am missing something here, or just don't understand the issue, since I see no issue at all.
