### ISSUE TITLE
Small error in ColorRGB.class

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#3518]
### Description
https://github.com/SkriptLang/Skript/blob/c06a8c8318d5a2aecb0520b0c827bbb49414e115/src/main/java/ch/njol/skript/util/ColorRGB.java#L58
```java
@Override
	public String getName() {
		return "RED:" + bukkit.getRed() + ", GREEN:" + bukkit.getGreen() + ", BLUE" + bukkit.getBlue();
	}
```

Missing ":" at "BLUE:", cause it return `[21:11:23 INFO]: RED:127, GREEN:178, BLUE56` with skript 2.5.1

**Comment by ShaneBeee** [comment]
This has already been fixed on the dev branch:
https://github.com/SkriptLang/Skript/blob/f24439208a042b7a40339daeae034024a923002f/src/main/java/ch/njol/skript/util/ColorRGB.java#L59
