### ISSUE TITLE
Block 2 blocks below event block

### ISSUE THREAD

**Issue by Mikimoka** [SkriptLang/Skript#3519]
### Description
I am currently in updating skripts from very old skript 2.2-dev25, paperspigot 1.11.2 to latest skript 2.5.1 and and latest paperspigot 1.16.3. There is homeever problem.
block 2 blocks below event-block, is not working its gives errors

### Steps to Reproduce
```
on piston extend:
  below block 2 blocks event-block is air
  #below line works without error its not solution i need check if block 2 blocks below event-block is air
  block below event-block is air 
```
### Expected Behavior
No errors

### Errors / Screenshots
[23:33:55 INFO]: [Skript] Reloading piston.sk...
[23:33:55 ERROR]: event-block is not a direction (piston.sk, line 2: block 2 blocks below event-block is air')
[23:33:55 INFO]: [Skript] Encountered 1 error while reloading piston.sk!

### Server Information
* **Server version/platform:** paperspigot 1.16.3
* **Skript version:** skript 2.5.1

### Additional Context
I got lots of skript that are using this same block 2 blocks below/abovem if i cant get them working then i will stuck forever in old version :(

**Comment by ShaneBeee** [comment]
yes we are aware of this issue. 
Use `block 2 meters below` .... I dont remember where the issue is to tag is as a duplicate, but this has been reported.

**Comment by Mikimoka** [comment]
`block 2 meters below `... confirming it works.  Thanks shanebeee you are lifesaver.
