### ISSUE TITLE
PlaceholderAPI PlaceholderHook Warning 

### ISSUE THREAD

**Issue by ellaira-ash** [SkriptLang/Skript#3523]
### Description
An warning message for Placeholder API comes up when starting the server. In the PAPI Help Discord, they said to warn plugin developers about this error message if it showed up. 

### Steps to Reproduce
1. Start the server.
2. Look for the error message in the console. 

### Errors / Screenshots
`06.11 16:21:26 [Server] WARN [PlaceholderAPI] skript is attempting to register placeholders via a PlaceholderHook class which is no longer supported!`

### Server Information
* **Server version/platform:** Paper 1.16.3 (248)
* **Skript version:** 2.5.1

**Comment by ShaneBeee** [comment]
Skript does not have PAPI support. The PAPI extension you are referring to is external.
