### ISSUE TITLE
Externally Stop Triggers

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3532]
It would be nice if we could externally stop triggers, example:
```
function hello(p: player, trigger: trigger):
    send "Hello %{_p}%!"
    stop trigger {_trigger}

command /hi:
    trigger:
        hello(player, trigger)
        send "HI!" # this won't be sent since the trigger gets stopped
```

**Comment by ShaneBeee** [comment]
What would be the point of this?

Can you provide a use case? Maybe some more details?

you could always have it return a boolean and just do a boolean check.

In my opinion this makes no sense at all

**Comment by MrScopes** [comment]
> What would be the point of this?
> 
> Can you provide a use case? Maybe some more details?
> 
> you could always have it return a boolean and just do a boolean check.
> 
> In my opinion this makes no sense at all

yeah I have a boolean check already, what I use now:
```
function hasPermission(p: player, level: integer) :: boolean:
	permissionLevel({_p}) < {_level}
	send "&cYou don't have permission." to {_p}
	return true

command /chat [<text>] [<text>]:
	trigger:
		hasPermission(player, 1) isn't set
```
but if stopping triggers externally was added, I could remove the `isn't set`. I like to make systems like this and want to make more and it'll make the code more readable (imo) if I could just stop the trigger externally

**Comment by ShaneBeee** [comment]
So .... you want this added so you can write less code?

I still don't understand the reasoning behind this. I see absolutely 0 benefit based on what you've asked for and "detailed" in this request.

**Comment by MrScopes** [comment]
> So .... you want this added so you can write less code?
> 
> I still don't understand the reasoning behind this. I see absolutely 0 benefit based on what you've asked for and "detailed" in this request.

that's fair, it's not really necessary. but still though, it would be nice to have ig

**Comment by TheDGOfficial** [comment]
> > What would be the point of this?
> > Can you provide a use case? Maybe some more details?
> > you could always have it return a boolean and just do a boolean check.
> > In my opinion this makes no sense at all
> 
> yeah I have a boolean check already, what I use now:
> 
> ```
> function hasPermission(p: player, level: integer) :: boolean:
> 	permissionLevel({_p}) < {_level}
> 	send "&cYou don't have permission." to {_p}
> 	return true
> 
> command /chat [<text>] [<text>]:
> 	trigger:
> 		hasPermission(player, 1) isn't set
> ```
> 
> but if stopping triggers externally was added, I could remove the `isn't set`. I like to make systems like this and want to make more and it'll make the code more readable (imo) if I could just stop the trigger externally

hasPermission function that you coded returns a boolean not an object, so therefore the `isn't set` condition will be always false. Also you can already ommit the isn't set section like you didn't use an if or isn't set or is true in where you used permissionLevel function, Skript can handle conditions like that (as far as I remember, maybe if is required, but the spacing/tabbing after conditionals are optional if you are not using else clauses, and writing is true/false is also optional if you have an add-on which implements CondBoolean, like TuSKe or SkQuery).

**Comment by Pikachu920** [comment]
this seems like it would create some really hard to debug scenarios and confusing code in my opinion

**Comment by MrScopes** [comment]
> hasPermission function that you coded returns a boolean not an object, so therefore the `isn't set` condition will be always false. Also you can already ommit the isn't set section like you didn't use an if or isn't set or is true in where you used permissionLevel function, Skript can handle conditions like that (as far as I remember, maybe if is required, but the spacing/tabbing after conditionals are optional if you are not using else clauses, and writing is true/false is also optional if you have an add-on which implements CondBoolean, like TuSKe or SkQuery).

that's the point actually, it won't return a boolean if they have permission, otherwise it passes fine

**Comment by ShaneBeee** [comment]
Looking back on this, it makes less and less sense to me.

Lets play with this for a second, as per your suggestion:
```vb
function permCheck(p: player, s: string, t: trigger):
    if {_p} does not have permission {_s}:
        send "You do not have perm for whatever you are attempting to do" to {_p}
        stop {_t}

command /cookie:
    trigger:
        permCheck(player, "cookie.yummy.yummers", trigger)
        give player a cookie
        send "NOM NOM"
```
Now in this case, I have to put the no perm message in the function, since it can't be done in the stopped trigger.
Which could be fine, but what if I want to customize messages per command?!?! then I have to add a string to the function params.

Current Skript:
```vb
function permCheck(p: player, s: string) :: boolean:
    return true if {_p} has permission {_s} else false

command /cookie:
    trigger:
        if permCheck(player, "cookie.yummy.yummers") = true:
            give player 10 of cookie
            send "NOM NOM"
        else:
            send "no perms... no cookies for you"
```
this just looks more logical to me, and it also looks much easier to read, as it closer resembles a proper programming language, such as Java.

> this seems like it would create some really hard to debug scenarios and confusing code in my opinion

I agree also with Pikachu on this.

**Comment by TPGamesNL** [comment]
Closing, see comment above
