### ISSUE TITLE
Block and entity metadata is not saved

### ISSUE THREAD

**Issue by Sonlein** [SkriptLang/Skript#3535]
### Description
After server reload all block and entity metadata is removed

### Steps to Reproduce
set metadata value <name> of <block>/<entity> to <value>
reload server

### Expected Behavior

Block and entity metadata should persist after server reload

### Server Information
* **Server version/platform:** Spigot 1.16.1
* **Skript version:** 2.5.1

### Additional Context
Idk if this is a bug or not, but this is not the behavior I was expecting. If it was intended, please tell me how you can save the metadata

**Comment by Pikachu920** [comment]
this isn't a bug, metadata is supposed to be used for data that doesn't need to be persistent. If you would like persistent data you can use variables or relational variables.
