### ISSUE TITLE
Error loading scripts

### ISSUE THREAD

**Issue by vDjgamer** [SkriptLang/Skript#3540]
I installed a script in the plugin, restart the server and it took over. This is a bug, but I don't have the Gringotts on Skript

### Steps to Reproduce
Just restart the server for the Scripts to load

### Expected Behavior
The script had to be started

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/74229644/98991207-27e57700-24f1-11eb-8991-80e737d06977.png)
![image](https://user-images.githubusercontent.com/74229644/98991301-48153600-24f1-11eb-8998-b80013441dfa.png)

### Server Information
* **Server version/platform:** 1.15.2 Spigot
* **Skript version:** 2.5.1

**Comment by ShaneBeee** [comment]
Seems to be an issue with Gringots and/or Vault

If you are using `balance of player` or anything to do with money, that can cause an issue.

I don't know what version of anything you are running but I recommend updating whatever you have.
This issue doesn't seem to be related to Skript itself.

**Comment by TPGamesNL** [comment]
Closing due to lack of response
