### ISSUE TITLE
Make newline work in lore and tellraw

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#3544]
I always loved SkQuery's new line feature, it just works everywhere with no problem at all.

I was happy when skript added their own but after trying it I found out that it doesn't work with `/tellraw` command nor item lore.

As for item lore there will be someone that will say use `with lore "" and ""` but that is just not functional nor nice, it is not just about `few more chars` many people just like the simplicity of `||` or `%nl%` when making new lines in lore.

and it is even better to have multiple ways to make new lines in item lore
I hope you got my point.

For `item lore` the second line and all lines below just doesn't appear and for `tellraw` it says `Expected whitespace to end one argument, but found trailing data`

Thank you.

**Comment by ShaneBeee** [comment]
As for the lore, I'm not entirely sure what you are talking about.

I have seen many people use the new line expression in lore and its worked.
I just tested it:
<img width="966" alt="Screen Shot 2020-11-14 at 3 37 32 PM" src="https://user-images.githubusercontent.com/20008482/99159218-6c0e7e00-268f-11eb-8c6a-e1ce339221b9.png">
Appears to work as expected.

As for the tellraw, Im not sure how that would even work, does tell raw support new line?

**Comment by ShaneBeee** [comment]
Did another test, apparently you can just use `\n` in tell raw 

<img width="430" alt="Screen Shot 2020-11-14 at 3 43 55 PM" src="https://user-images.githubusercontent.com/20008482/99159328-42a22200-2690-11eb-93af-55b87ec42389.png">

**Comment by AyhamAl-Ali** [comment]
As for me the lore doesn't work 
![image](https://user-images.githubusercontent.com/20037329/99159479-4f049a00-26e5-11eb-8405-5a40a6dda35d.png)

as for tellraw I'm using the known script `json.sk`, I used to use `%nl%` in `tooltips` and it works but now it doesn't anymore, I had to edit json.sk to use `\n`

**Comment by AyhamAl-Ali** [comment]
Apparently `set lore` works with `nl` but `with lore`  doesn't
![image](https://user-images.githubusercontent.com/20037329/99159521-b0c50400-26e5-11eb-9786-d0a7437e3f52.png)

**Comment by AyhamAl-Ali** [comment]
as for the json this is some more details

Using `json("PLAYER", "test||ttp:Line 1%nl%Line 2")`
This will throw an error in console saying the following
![image](https://user-images.githubusercontent.com/20037329/99159561-039ebb80-26e6-11eb-8aae-5e69137378ef.png)

**Comment by ShaneBeee** [comment]
If thats the case, I recommend just using lore lists.
Im not sure why people say commas and quotes are longer
`", "` is exactly the same amount of characters as `%nl%` ... 4!

That said, I don't see this being "fixed" as it's not broken, and Skript added lore lists for a reason. 
It seems counter productive to move backwards.

Im going to mark this as "dev needed" to see what the rest of the team thinks, because in my opinion, this is a non-issue and something I personally would not spend any time on.

**Comment by AyhamAl-Ali** [comment]
> As for item lore there will be someone that will say use `with lore "" and ""` but that is just not functional nor nice, it is not just about `few more chars` many people just like the simplicity of `||` or `%nl%` when making new lines in lore.

I pointed that out before because this was suggested before long time ago and same answer were given,

Not sure about other users but for me I just don't like to keep adding more quotes for new lines, I like to stay in one double quotes and just use a simple separator like `||` or `%nl%` that is what I meant, I would also like to hear others opinion of course.

as for the bug part, i think there is a bug in `with lore` as it just doesn't support `newline` expression which by default it should because it is related.

**Comment by MrScopes** [comment]
as far as lores go, it's meant for you to use lore as a list, ie:
```
with lore "hi", "hello" and "hi man"
```
instead of 
```
with lore "hi%nl%hello%nl%hi man"
```
