### ISSUE TITLE
Player's balance not working

### ISSUE THREAD

**Issue by Envqu** [SkriptLang/Skript#3545]
Player's balance not working with Skript 2.5.1

Example Skript:

```
on inventory click:
	if clicked inventory is player's inventory:
		stop
	if inventory name of player's current inventory is "Shop":
		cancel event
		if clicked item is baked potato:
			if player's balance >= 8:
				remove 8 from the player's account
				add 1 baked potato to player's inventory
				send "&a+1 Potato"
			else:
				close player's inventory
				send "&cNo money"
```

I just installed Skript 2.5 and now its working.

**Comment by ShaneBeee** [comment]
define "not working"

Also, which version is your server?
Any errors?

Need more info here, this is why we provide an issue template, as it asks you to fill in a bunch of information we are looking for.

Deleting the template is not helpful as we do not have the required information to triage your issue.

**Comment by Envqu** [comment]
Im sorry. Server version is Tuinity 1.15.2 and no errors in console.
`%player's balance%` working, but `if player's balance is 8:` and `set {_balance} to player's balance`  not.

**Comment by ShaneBeee** [comment]
> btw. I noticed bug with 2.5 version.

Bugs in old version are irrelevant to us.

> Yep, I made big mistake in my skript, sorry.

closing as it appears you got this fixed.
