### ISSUE TITLE
Selecting doors in different directions

### ISSUE THREAD

**Issue by Zyphrono** [SkriptLang/Skript#3551]
### Description
Doors cannot be selected with target block when looking in certain directions. This bug appeared several times in earlier versions of skript and also got fixed plenty of times. Sadly, it reappeared in the recent version (2.5.1)

It totally depends on how you place the door.
### Steps to Reproduce
Depending on how you actually place the door, it can only be detected when looking at it in one direction.

1. Place the door
2. Set a variable to the target block (only works if you look at the bottom part of the door for some reason)
3. Check if the variable is a door (`if {variable} is door`)

### Expected Behavior
Should work when facing the door in all directions.

### Errors / Screenshots
No errors are being logged.

### Server Information
* **Server version/platform:** Paperspigot 1.12.2 build 1618
* **Skript version:** 2.5.1 (stable)

**Comment by KnuffelBeestje** [comment]
Still reproducible in **2.5.3**

**Comment by TPGamesNL** [comment]
I cannot reproduce. It might help if you specify exactly which direction and door facing you're using, possibly providing screenshots.

**Comment by KnuffelBeestje** [comment]
Code:
```
command /checkifdoor:
    trigger:
        set {_door} to target block
        if {_door} is door:
            send "Yup, that's a door!"
        else:
            send "Nope, that isn't a door!"
```

Video:
[https://youtu.be/5pwcXpiXn9k](url)

**Comment by TPGamesNL** [comment]
Alright I can confirm this on Spigot 1.12.2, not on Paper 1.16.5

**Comment by TPGamesNL** [comment]
Seems that directional block comparison is broken on 1.12, tested with doors and stairs

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/2711
