### ISSUE TITLE
Setting a mob to a variable

### ISSUE THREAD

**Issue by kill05** [SkriptLang/Skript#3552]
### Description
i've set a zombie as a variable and then spawn it. It works if my variable is set to a, while it doesn't when it's set to b
### Steps to Reproduce

command /test:
	trigger:
		set {a} to zombie
		spawn {a} at player
this one works ^^

command /boss:
	trigger:
		set {b::1.entity} to zombie
		spawn {b::1.entity} at player
this one doesn't ^^

### Expected Behavior
to work in both cases

### Errors / Screenshots

no errors.

### Server Information
* **Server version/platform:**  paper 251, 1.16.3
* **Skript version:**  2.5.1

**Comment by ShaneBeee** [comment]
try `a zombie` and let me know how it goes.

Typically `zombie` would refer to an entity object, ie: an instance of a specific entity, whereas `a zombie` will refer to an entity type.

Think of it like `player` vs `a player` .... `player` would be THE player in said event, whereas `a player` would just be a type

**Comment by MrScopes** [comment]
```v
command /test:
    trigger:
        set {b::1.entity} to zombie
        spawn ("%{b::1.entity}%" parsed as entitytype) at player
```
try this

**Comment by kill05** [comment]
the thing that is a bit strange to me is that when i changed my variable name to {b::1.boss_entity} to both parts it worked just fine. I checked multiple times. Didn't work. My syntax does work but i got these strange inconsistencies.

**Comment by kill05** [comment]
also another odd thing, now they both work.
Idk anymore this thing's driving me crazy, i've been testing with it for 4hrs yesterday and i still don't realize the problem.
