### ISSUE TITLE
creeper entity does not work

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#3554]
### Description
The code does not detect creeper. Other mobs are killed.
Other mobs = this in code
### Steps to Reproduce
Use this code:
```vb
every 5 real seconds:
    loop all entities in world "swiat":
       if loop-entity = a skeleton or a zombie or a spider or a creeper or a husk or a witch::
            set {_l::*} to loop-entities
            if {_l::*} is in region "{@region1}":
                kill {_l::*}
```

### Expected Behavior
The creeper should be killed.

### Errors / Screenshots
null

### Server Information
[20:59:58 INFO]: [Skript] Server Version: git-Paper-282 (MC: 1.16.4)
[20:59:58 INFO]: [Skript] Skript Version: 2.5.1
[20:59:58 INFO]: [Skript] Installed Skript Addons:
[20:59:58 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[20:59:58 INFO]: [Skript]  - SkQuery v4.1.4
[20:59:58 INFO]: [Skript]  - TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe)

**Comment by MrScopes** [comment]
try removing `a` from it for now, I'm not sure if this will work but `a` usually indicates a type and you're comparing an entity to it's type so maybe there's an issue with that for creepers? just a suggestion, idk if this will help

**Comment by Misio12320** [comment]
I have tested this code:
```
every {@czas} real second:
	if {domofon} is true:
		loop all entities in world "swiat":
			if loop-entities = skeleton, zombie, spider, husk, creeper, witch:
				set {_l::*} to location of loop-entities
				if {_l::*} is in region "{@region1}" or "{@region2}":
					kill {_l::*}
```
Weird, because previous some code worked fine now it does not work.
