### ISSUE TITLE
Unit tests fail on Windows

### ISSUE THREAD

**Issue by TheGlitch76** [SkriptLang/Skript#356]
[logs.zip](https://github.com/bensku/Skript/files/722335/logs.zip)
This is the folder with the html file. Run index.html to see the logs.

**Comment by TheGlitch76** [comment]
bump. Still having the same problem.

**Comment by bensku** [comment]
Tests fail on Windows. I think the result jar is still there and working, though.

**Comment by TheGlitch76** [comment]
Oh wow, after a bit of searching for it, the jar file is there. I'll add it to my server and see if it all runs correctly.

**Comment by CDAGaming** [comment]
Bump, still having this issue compiling

**Comment by Nicofisi** [comment]
The tests seem not to run at all for some reason actually? When i run `./gradlew test` after intentionally putting an `assumeTrue(false)` anywhere in the tests it just silently *"works"/skips it*

```
:processTestResources NO-SOURCE
:testClasses
:test

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 5s
```

**Comment by bensku** [comment]
This was fixed a long ago.
