### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by NODUF** [SkriptLang/Skript#3564]
Can somebody help me?

![Snímek obrazovky (300)](https://user-images.githubusercontent.com/47395783/99890349-6cde7b80-2c5e-11eb-8a60-71715ef86dbd.png)

![Snímek obrazovky (308)](https://user-images.githubusercontent.com/47395783/99890371-b75ff800-2c5e-11eb-83eb-30670f81cb2b.png)

**Comment by ShaneBeee** [comment]
This is not a Skript issue.

This issue tracker is for issues related with the Skript plugin itself.
If you need support, please see https://github.com/SkriptLang/Skript/#relevant-links or reach out to the developer of said addon you are using.
