### ISSUE TITLE
on damage with new mobs is broken

### ISSUE THREAD

**Issue by HexicDragon2** [SkriptLang/Skript#3565]
### Description

When I check for a new mob (ravager)'s name and I broadcast it, it broadcasts it correctly, but when I use an if statement for the name, it doesn't.
### Steps to Reproduce

Used an "on damage"
### Expected Behavior

It should've easily gone through with it after, but it seems like the if statement for checking a new mob's name is broken (it works fine for mobs like zombies).
### Errors / Screenshots

 https://pastebin.com/BUTT91kV | Code that also should've worked: https://pastebin.com/8zJQABbu

 N/A

### Server Information
* **Server version/platform:**  1.16.4
* **Skript version:**   2.5

**Comment by ShaneBeee** [comment]
A couple things here:

1) `Skript version: 2.5` <-- this is not the version you are using. You actually using 2.5-MH, which is Minehut's custom fork.
(for anyone else reading this, Im talking to the user on Discord right now, which is how I know)
We only offer support for the latest build of our fork, not outdated builds, nor forks.
If there is an issue with the version you are using please report it to Minehut.

2) I did some light testing:
```vb
on death:
	if victim is ravager:
		if name of victim is "Yeti":
			broadcast "&aA YETI DIED"
```
Outcome:
<img width="580" alt="Screen Shot 2020-11-22 at 2 56 37 PM" src="https://user-images.githubusercontent.com/20008482/99919603-4ad31080-2cd3-11eb-96e8-6fbc289e3cc7.png">

Needless to say, I could not replicate this issue on Skript 2.5.1
