### ISSUE TITLE
Region enter not working properly

### ISSUE THREAD

**Issue by neondeex** [SkriptLang/Skript#3566]
### Description
On region enter: event do not capture when people are walk looking blackguards or when you shif

### Steps to Reproduce
Make a region and do something like this
on region enter:
    if "%event-region%" contains "baraccess":
        message "&a&lBob &8» &fIs good to see you again!"
Then you will not get the message when you join the region looking blackguards or holding shift

### Expected Behavior

Detect that the player joins

**Comment by ShaneBeee** [comment]
Closing due to missing information.

It appears you deleted half of the template. We need the details that the template asks for, to help us triage this issue.

When creating new issues, please fill in the details the template asks for.
