### ISSUE TITLE
Expression "IP"/"IP of player" returns 127.0.0.1

### ISSUE THREAD

**Issue by gamingsim** [SkriptLang/Skript#3569]
### Description
Whenever I use the IP or IP of player Expressions skript returns 127.0.0.1 When it obviusly should have been my IPv4 Adress.

The Server is the hubserver of a bungeecord network, the server.properties had 127.0.0.1 as Server address which I since tried removing but that didn't change anything

Skript v2.5.1
Paper288 (1.16.4)
Bungee1439
Skungee v1.0.15
SKQuery v4.1.4
SQLibrary-7.1

**Comment by WeeskyBDW** [comment]
Hey
This isn't a skript issue, but a bungeecord (unresolvable) issue, see [this bungeecord issue](https://github.com/SpigotMC/BungeeCord/issues/31) .
