### ISSUE TITLE
Log Handler Error

### ISSUE THREAD

**Issue by Rehrocko** [SkriptLang/Skript#3572]
### Description
Console spammed with errors

### Steps to Reproduce
Restarting the server with Skript installed

### Expected Behavior
A normal boot

### Errors / Screenshots
![Console](https://user-images.githubusercontent.com/69391270/100255394-0e88f580-2f09-11eb-9860-40c06a4e0d9c.png)

https://pastebin.com/A4vrefbc

Multiple pages of that

### Server Information
Paperspigot 1.16.3
Skript 2.5.1

**Comment by WeeskyBDW** [comment]
Hey
Please try to reinstall skript and/or server

**Comment by Romitou** [comment]
I think you have skript-mirror installed on your server.
Try to remove it or replace it with skript-reflect and try again.

**Comment by Rehrocko** [comment]
Thanks all, replacing skript-mirror with skript-reflect seemed to do the job.
