### ISSUE TITLE
Bucket fill event bug

### ISSUE THREAD

**Issue by Sonlein** [SkriptLang/Skript#3584]
### Description
skript doesn't return the value of player's offhand tool on bucket fill event if player fills bucket with second hand

### Steps to Reproduce
```
on bucket fill:
  broadcast "%player's offhand tool%"
```
fill bucket with second hand

### Expected Behavior
skript should return player's offhand tool

### Server Information
* **Server version/platform:** Spigot 1.16.1
* **Skript version:** 2.5.1

### Additional Context
Another stupid bug...

**Comment by ShaneBeee** [comment]
Confirmed this bug. Should be an easy fix.
