### ISSUE TITLE
Text argument issues

### ISSUE THREAD

**Issue by Khasar11** [SkriptLang/Skript#3588]
### Description
Text arguments for some reason does not like it if a : is inputted in them

### Steps to Reproduce
Say you have a command like this (except with proper indents of course idk how to do that on github):
`command /rawmsg [<text>]:
	trigger:
		send arg-1 to player`
If you now from in game execute `/rawmsg (anything including a :)` it will not work, it will not return any errors or messages at all not to console and not to the player, it is the same even if you remove the ``to player` bit and a lot of other combinations

### Expected Behavior
: character should work fine in text arguments

### Errors / Screenshots
![bilde](https://user-images.githubusercontent.com/67635910/100552178-be51c080-3285-11eb-98f2-d54c1d5bb785.png)
![bilde](https://user-images.githubusercontent.com/67635910/100552192-d32e5400-3285-11eb-8ef5-bc7ea886eadb.png)

### Server Information
* **Server version/platform:** 1.16.4 298 (latest as of writing)
* **Skript version:** 2.5.2

### Additional Context
Tried with 0 addons installed, same issue occurs, no message is logged to console or to the player

**Comment by ShaneBeee** [comment]
I could not replicate this issue.

Using your exact code and running different commands, this is what I see in game:

<img width="509" alt="Screen Shot 2020-11-29 at 2 00 53 PM" src="https://user-images.githubusercontent.com/20008482/100554708-5bdbce80-324b-11eb-8a53-b70c431b89f5.png">

And this is what I see in console:
```
[14:00:29 INFO]: ShaneBee issued server command: /rawmsg test
[14:00:31 INFO]: ShaneBee issued server command: /rawmsg test:
[14:00:33 INFO]: ShaneBee issued server command: /rawmsg test:::
[14:00:37 INFO]: ShaneBee issued server command: /rawmsg blah
[14:00:39 INFO]: ShaneBee issued server command: /rawmsg blah:
[14:00:40 INFO]: ShaneBee issued server command: /rawmsg blah::
[14:00:42 INFO]: ShaneBee issued server command: /rawmsg blah:::
[14:00:46 INFO]: ShaneBee issued server command: /rawmsg :
[14:00:47 INFO]: ShaneBee issued server command: /rawmsg ::
```

Seems to work as it should.

**Comment by Khasar11** [comment]
Hm i dont know then, must be something weird going on on my end
