### ISSUE TITLE
Spawn item frame in air

### ISSUE THREAD

**Issue by Sonlein** [SkriptLang/Skript#3590]
### Description
You can't spawn item frame in air

### Steps to Reproduce
```
on command "/framespawn":
    spawn item frame at block at player
```

nothing happens
if try it on ground, item frame will spawn

### Expected Behavior
item frame should be spawned in air, because vanilla minecraft "/summon item_frame ~ ~ ~" in air spawns item frame

### Server Information
* **Server version/platform:** Spigot 1.16.1
* **Skript version:** 2.5.1

**Comment by ShaneBeee** [comment]
This is not a Skript issue, this is a Bukkit issue. Bukkit does not allow for spawning an ItemFrame in air.

When using Bukkit code (not Skript) I get the following error:
```
threw a IllegalArgumentException: Cannot spawn hanging entity for org.bukkit.entity.ItemFrame at Location{world=CraftWorld{name=world},x=-108.4520379720062,y=87.7431359597822,z=126.87189415497132,pitch=90.0,yaw=-43.499573} (no free face)
```
This is hard coded in CraftBukkit:
<img width="1038" alt="Screen Shot 2020-11-30 at 4 25 14 AM" src="https://user-images.githubusercontent.com/20008482/100610194-1c04fd80-32c4-11eb-9a2c-a8200c4e3ee7.png">
