### ISSUE TITLE
Thread Dump when reloading Skript

### ISSUE THREAD

**Issue by KokaineKola** [SkriptLang/Skript#3596]
### Description
When I reload my skript, I get a massive thread dump and server runs 24990ms or 499 ticks behind

### Steps to Reproduce
I have managed to figure out the issue is within this one line. When I remove both enchantments protection and frost walker, no issues. When I add one, slight lag, both enchants cause massive lag.

[drop 1 of leather boots of protection 6 and frost walker 2 with nbt "{HideFlags:63, display:{color:13225422}}" named "&fBlizzard Boots" with lore "&7Defense: &a+70" and "&7Strength Bonus: &c+5" and "&7Full Set Bonuses:" and "&bNever Freeze Again" and "&7Undead Damage: &c+12" and "&7All Damage: &c+8" and "&7Protection VI" at location of {_E}]

### Expected Behavior
Should drop coloured leather boots named and with lore at the location of an entity. With protection 6 and frost walker 2.

### Errors / Screenshots
https://hastebin.com/avikawejaq.shell
https://pastebin.com/MkBeF615

### Server Information
Paper version git-Paper-300 (MC: 1.16.4)
Skript 2.5.2
skBee v1.8.4

### Additional Context
This line is inside a function that gives the entity which is {_E}.

**Comment by ShaneBeee** [comment]
You're strictly writing way too much in one line, and overloading the parser.
Try breaking that line up into multiple lines.

**Comment by KokaineKola** [comment]
> You're strictly writing way too much in one line, and overloading the parser.
> Try breaking that line up into multiple lines.

Had no idea that was a thing, thanks for the help

**Comment by ShaneBeee** [comment]
Closing this as a non-issue.
We're aware the parser has issues when overloading lines, I believe there's an issue or two already floating around regarding this.
