### ISSUE TITLE
Issue with BossShopPro

### ISSUE THREAD

**Issue by ThiccPickle** [SkriptLang/Skript#3601]
### Description
Created a Skript that would take an online status of another Bungee server and set it to the value of a placeholder. The placeholder was placed in a BossShopPro menu. At first, it worked, then the placeholder value was no longer set.

### Recreate
1. Bungee Proxy with two servers
2. Install Bungeecord, Skungee, Skript, skript-placeholders, and all their dependencies
3. Create menu item in BSP: https://pastebin.com/tNbceLTu
4. Create Skript: https://pastebin.com/4S6iwwjT
5. Run "/menu" in-game and check console.

### Expected Behavior
I expected it to display the correct value for the placeholder in the menu (&aONLINE or &cOFFLINE)

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/75459439/101110951-f8c1a300-358e-11eb-84d3-8c2828976faf.png)
https://pastebin.com/bbTtgqtu

### Server Information
Version Information:
Skript: 2.5.2 (latest)
Flavor: skriptlang-github
Date: 2020-11-28
Bukkit: 1.16.3-R0.1-SNAPSHOT
Minecraft: 1.16.3
Java: 1.8.0_272 (OpenJDK 64-Bit Server VM 25.272-b10)
OS: Linux amd64 4.15.0-76-generic

**Comment by ShaneBeee** [comment]
1) We do not support outdated revisions of Minecraft (ie: 1.16.3), we only support the latest revision of each major version.

2) This is not an issue with Skript, appears to be an issue with an addon you are using. Please report the issue to the respective addon.
