### ISSUE TITLE
I use a papermc server and java jre 11  i got this error

### ISSUE THREAD

**Issue by d7gross** [SkriptLang/Skript#3603]
[ERROR] .... #!#!

[ERROR] .... #!#! [Skript] Severe Error:

[ERROR] .... #!#!

[ERROR] .... #!#! Something went horribly wrong with Skript.

[ERROR] .... #!#! This issue is NOT your fault! You probably can't fix it yourself, either.

[ERROR] .... #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).

[ERROR] .... #!#! This ensures that your issue is noticed and will be fixed as soon as possible.

[ERROR] .... #!#!

[ERROR] .... #!#! Stack trace:

[ERROR] .... #!#! java.lang.NoSuchMethodError: org/bukkit/Effect.getName()Ljava/lang/String; (loaded from file:/home/gs-41050/cache/patched_1.16.4.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@e680a75f) called from class ch.njol.skript.util.VisualEffect$Type (loaded from file:/home/gs-41050/plugins/Skript.jar by PluginClassLoader{plugin=Skript v2.2-dev36, pluginEnabled=true, url=plugins/Skript.jar}).

[ERROR] .... #!#! at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:196)

[ERROR] .... #!#! at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:63)

[ERROR] .... #!#! at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:269)

[ERROR] .... #!#! at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:891)

[ERROR] .... #!#! at ch.njol.skript.Skript.onEnable(Skript.java:336)

[ERROR] .... #!#! at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)

[ERROR] .... #!#! at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)

[ERROR] .... #!#! at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)

[ERROR] .... #!#! at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)

[ERROR] .... #!#! at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)

[ERROR] .... #!#! at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468)

[ERROR] .... #!#! at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)

[ERROR] .... #!#! at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935)

[ERROR] .... #!#! at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)

[ERROR] .... #!#! at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3194.0000000030BD1A50.run(Unknown Source)

[ERROR] .... #!#! at java.base/java.lang.Thread.run(Unknown Source)

[ERROR] .... #!#!

[ERROR] .... #!#! Version Information:

[ERROR] .... #!#! Skript: 2.2-dev36

[ERROR] .... #!#! Bukkit: 1.16.4-R0.1-SNAPSHOT

[ERROR] .... #!#! Minecraft: 1.16.4

[ERROR] .... #!#! Java: 11 (Eclipse OpenJ9 VM openj9-0.10.0)

[ERROR] .... #!#! OS: Linux amd64 4.15.0-106-generic

[ERROR] .... #!#!

[ERROR] .... #!#! Server platform: Paper

[ERROR] .... #!#!

[ERROR] .... #!#! Current node: null

[ERROR] .... #!#! Current item: null

[ERROR] .... #!#!

[ERROR] .... #!#! Thread: Server thread

[ERROR] .... #!#!

[ERROR] .... #!#! Language: english

[ERROR] .... #!#! Link parse mode: DISABLED

[ERROR] .... #!#!

[ERROR] .... #!#! End of Error.

[ERROR] .... #!#!

**Comment by Govindass** [comment]
you're using Skript 2.2 dev36, which is not supported anymore, use Skript 2.5.1 (or Skript 2.5.2, but that one is unstable right now)

**Comment by ShaneBeee** [comment]
As Govindass stated you're using an outdated version.
