### ISSUE TITLE
[CRITICAL] teleport {_player} to {_loc} DELETES ALL LOCAL VARIABLES!

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#3605]
### Description

using teleport {_player} to {_loc}, when at the target location the chunks aren't loaded (but are generated), will delete all local variables in the code. (It may be 1.12.2 only bug, as it has no async teleportation)
### Steps to Reproduce

1. have 0 chunks loaded in the "testworld"
2. use this code:
```
command /asynctp:
	trigger:
		set {_game} to "no bug"
		set {_loc} to spawn point of world "testworld"
		set {_player} to player
		wait a tick
		teleport {_player} to {_loc}
		send "%{_game}%"
```
3. observe it outputting `<none>`
### Expected Behavior

To not delete local variables, as it was before.
### Errors / Screenshots

None

### Server Information
* **Server version/platform:** 1.12.2 Paper (maybe it is 1.12.2 only bug?)
* **Skript version:** 2.5.2

### Additional Context

This is very likely caused by async teleportation update.

**Comment by TPGamesNL** [comment]
PR: https://github.com/SkriptLang/Skript/pull/3478
I have no clue how this wasn't seen by any reviewers (other reviewers were requested, none responded, but it was still merged). Most of the things you should keep in mind when creating async effects in Skript were not used, mainly variable backup and re-setting those variables. See [`AsyncEffect`](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/util/AsyncEffect.java) for reference.

**Comment by APickledWalrus** [comment]
If you're able to, please let me know if the build from that PR fixes your issue. @Govindass

**Comment by Govindass** [comment]
> 
> 
> If you're able to, please let me know if the build from that PR fixes your issue. @Govindass

I cannot test it, because the nightly build throws very many errors for me, it is likely incompatible with 1.12.2 (WorldGuard and MundoSK syntaxes no longer work)

**Comment by Govindass** [comment]
the bug hasn't been fully fixed - the teleportation still causes a delay which breaks scripts that depended on old logic.

**Comment by TPGamesNL** [comment]
It should probably be documented that EffTeleport is now a delayed effect, as that has a big impact on plenty of scripts (breaking change)

**Comment by JRoy** [comment]
> It should probably be documented that EffTeleport is now a delayed effect, as that has a big impact on plenty of scripts (breaking change)

Line of execution isn't broken, the next TriggerItem still executes after all teleports have occurred and the chunk has been fully loaded (async on paper or sync on spigot) https://github.com/SkriptLang/Skript/blob/da691e2d36b038a20ed14cf1f6ab01f471c11451/src/main/java/ch/njol/skript/effects/EffTeleport.java#L93-L106

**Comment by Govindass** [comment]
> > It should probably be documented that EffTeleport is now a delayed effect, as that has a big impact on plenty of scripts (breaking change)
> 
> Line of execution isn't broken, the next TriggerItem still executes after all teleports have occurred and the chunk has been fully loaded (async on paper or sync on spigot)
> 
> https://github.com/SkriptLang/Skript/blob/da691e2d36b038a20ed14cf1f6ab01f471c11451/src/main/java/ch/njol/skript/effects/EffTeleport.java#L93-L106

does that mean functions can now be delayed? because I teleport inside a function

**Comment by Pikachu920** [comment]
> > > It should probably be documented that EffTeleport is now a delayed effect, as that has a big impact on plenty of scripts (breaking change)
> > 
> > 
> > Line of execution isn't broken, the next TriggerItem still executes after all teleports have occurred and the chunk has been fully loaded (async on paper or sync on spigot)
> > https://github.com/SkriptLang/Skript/blob/da691e2d36b038a20ed14cf1f6ab01f471c11451/src/main/java/ch/njol/skript/effects/EffTeleport.java#L93-L106
> 
> does that mean functions can now be delayed? because I teleport inside a function

They are the same as before - the function can have delayed execution however the calling code will continue before the delayed code finishes + it can't be used as an expression anymore (or at least, the return value will always be none if the return comes after a delay)

**Comment by Govindass** [comment]
> > > > It should probably be documented that EffTeleport is now a delayed effect, as that has a big impact on plenty of scripts (breaking change)
> > > 
> > > 
> > > Line of execution isn't broken, the next TriggerItem still executes after all teleports have occurred and the chunk has been fully loaded (async on paper or sync on spigot)
> > > https://github.com/SkriptLang/Skript/blob/da691e2d36b038a20ed14cf1f6ab01f471c11451/src/main/java/ch/njol/skript/effects/EffTeleport.java#L93-L106
> > 
> > does that mean functions can now be delayed? because I teleport inside a function
> 
> They are the same as before - the function can have delayed execution however the calling code will continue before the delayed code finishes + it can't be used as an expression anymore (or at least, the return value will always be none if the return comes after a delay)

my code depends on world of player to change immediately, else it doesn't execute

**Comment by TPGamesNL** [comment]
Making `EffTeleport` async would break the following (and more):
- line of executions in functions **not** used as expressions, as the calling code does not wait for the function to finish delays.
- functions with return values (used as expressions), since no value would be returned when `EffTeleport` is used before `EffReturn`.
- triggers that influence events (cancel event, change event values, etc) after calling `EffTeleport`.

The least that can be done is for it to be documented.

**Comment by Govindass** [comment]
seriously it shouldn't have been made async in the first place

**Comment by ham1255** [comment]
@Govindass  async teleport player

**Comment by ShaneBeee** [comment]
Unless I am missing something here, I don't see the issue. 

Currently testing this on 1.12.2 (because Govindass I know you use that)
code:
```vb
function moveTo(p: player, w: world) :: world:
	teleport {_p} to spawn of {_w}
	return world of {_p}

command /world <world>:
	trigger:
		send "World before TP: &a%world of player%"
		set {_w} to moveTo(player, arg-1)
		send "World after TP: &b%{_w}%"
```
Result:
<img width="966" alt="Screen Shot 2020-12-14 at 3 19 31 AM" src="https://user-images.githubusercontent.com/20008482/102075564-458d5100-3dbb-11eb-8941-81680d02f610.png">

Needless to say, it works totally fine for me.


Prior to this change, when you used the teleport effect, the chunk was force loaded, if there was any delay in that chunk loading, the code after the teleport would all be delayed also, just like this is. 

So unless there is more info you can give us, I don't see any issue here.
Josh set it up, so all code after the teleport, is executed after the teleport is complete (ie: its kinda put on hold waiting for the TP to finish)

**Comment by TPGamesNL** [comment]
That code shouldn't even parse, but the trigger isn't marked as delayed in the init section (which is also a bug with `AsyncEfect` / `EffLoadServerIcon`, the only `AsyncEffect` currently in Skript), so it won't error. 

My suggestion is making teleportation optionally async, as was suggested by #3355.

**Comment by Govindass** [comment]
> 
> 
> Unless I am missing something here, I don't see the issue.
> 
> Currently testing this on 1.12.2 (because Govindass I know you use that)
> code:
> 
> ```vbnet
> function moveTo(p: player, w: world) :: world:
> 	teleport {_p} to spawn of {_w}
> 	return world of {_p}
> 
> command /world <world>:
> 	trigger:
> 		send "World before TP: &a%world of player%"
> 		set {_w} to moveTo(player, arg-1)
> 		send "World after TP: &b%{_w}%"
> ```
> 
> Result:
> <img alt="Screen Shot 2020-12-14 at 3 19 31 AM" width="966" src="https://user-images.githubusercontent.com/20008482/102075564-458d5100-3dbb-11eb-8941-81680d02f610.png">
> 
> Needless to say, it works totally fine for me.
> 
> Prior to this change, when you used the teleport effect, the chunk was force loaded, if there was any delay in that chunk loading, the code after the teleport would all be delayed also, just like this is.
> 
> So unless there is more info you can give us, I don't see any issue here.
> Josh set it up, so all code after the teleport, is executed after the teleport is complete (ie: its kinda put on hold waiting for the TP to finish)
> 
> **EDIT**
> wait, hold on, I had "keep spawn loaded" set to true, so that sped things up, if I set that to false, I now see the issue.
> when using the same code as above, I now get a return of null.
> 
> On that note, that issue is different than this one, and a new issue should be created so we can properly address it.

well your test environment is very simplistic, I have situation where I have 100s of triggers executing simultaneously and things getting out of order with this change, I sadly cannot give a test script as it is a really complex environment
