### ISSUE TITLE
Divide by 10

### ISSUE THREAD

**Issue by ZorgBtw** [SkriptLang/Skript#3608]
### Description
Division by 10 don't really works

### Steps to Reproduce
I tried this code:
```
command /bug <number>:
	trigger:
		set {_number} to arg-1 / 10
		broadcast "%{_number}%"
```
Execute a command like /bug 10.548

### Expected Behavior
It should be returned 1.0548 or something rounded, but it actually returns 10.45.

### Server Information
* **Server version/platform:** PaperSpigot 1.12.2
* **Skript version:** 2.5.2

**Comment by ShaneBeee** [comment]
Tested this and can verify.

For the time being, set a temp var to the arg, this seems to be a workaround for the issue.
Marking it as a medium bug, since there is a possible work around.

**Comment by ShaneBeee** [comment]
Did a little more digging into this, I found sorta where the bug stems from.
Skript thinks the "-" in arg-1 is part of the math haha! Silly Skript 

So you can work around by doing: `set {_number} to (arg-1) / 10`
This will prevent Skript trying to take the "-" into account as part of the arithmetic

**Comment by TPGamesNL** [comment]
Closing this issue as `(arg) - (1 / 10)` is a valid interpretation, and with expression priority and math operator priority, this will never be fixed, unless the `arg` pattern is removed entirely
