### ISSUE TITLE
on mine: instant break

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3609]
we should be able to
```
on block damage:
    set instant break of event-block to true
```
I can try to make this if you want

**Comment by Katalijst** [comment]
This already exists:
`on mine:
    break event-block using player's tool`

**Comment by MrScopes** [comment]
edit: it would have to be on block damage

**Comment by MrScopes** [comment]
closing since Kataljst showed me (but it would have to be on block damage)
