### ISSUE TITLE
Colored name items problem

### ISSUE THREAD

**Issue by wallxq** [SkriptLang/Skript#3613]
### Description
Don't work 'named "&6Sword of God". All items when has & syntax, color dont work in skript. You can't remove they form player or something else. That problem i have in lastest skript but on old 2.5 alpha5 works all.
### Steps to Reproduce
just use item with colored name and try remove it from player using "named"

**Comment by ShaneBeee** [comment]
Closing due to lack of information.

When opening issues, please do not delete the issue template.
The information requested in that template is vital for us to triage said issue.
