### ISSUE TITLE
"Remove 1 from item amount" not working

### ISSUE THREAD

**Issue by Spennncer** [SkriptLang/Skript#3614]
**Description**
I was getting the same issue as #2143 where the remove 1 of event-item from player's inventory was crashing my 1.14.4 server when using latest skript, so I tried the workaround in #2092 but I can't seem to get the workaround working.

**Steps to Reproduce**
While holding 64 diamonds
```
on right click:
	event-item is diamond:
		remove 1 from item amount of event-item
		broadcast "Test"
```

**Expected Behavior**
Expect to remove 1 diamond from my inventory, but the amount does not decrease. "Test" was broadcast to the server, however. No errors in console.

**Errors / Screenshots**
None yet, can't get the effect to work. 

**Server Information**
* **Server version/platform:** Spigot 1.14.4 (Also tried 1.16.4)
* **Skript version:** Skript 2.5.2

Any help is appreciated. Maybe there's something I'm not seeing that is obvious to someone else.

**Additional Context**

**Comment by Leautis** [comment]
You can easily work around by `remove 1 from item amount of tool`

**Comment by Spennncer** [comment]
Alright I was able to get it working using tool instead of event-item. Thank you.
