### ISSUE TITLE
set blocks within two locations

### ISSUE THREAD

**Issue by Wafffidooe** [SkriptLang/Skript#3615]
Hello

I have a skript where this one line used to be working just fine. It is still loading without errors, but it is not working.

This part of my Skript should explain enough:
```vb
command /event [<text>] [<integer>]:
	permission: Event
	permission message: &cYou don't have the permission to start an event&7!
	trigger:
		if arg-1 is "start":
			if {Event.Occuring} is set:
				stop
			else:
				delete {-EventPlayers::*}
				delete {-vote::*}
				send "&8&l[&5&lB E T&8&l] &bAll event-data has been cleared!"
				set {_countdown} to arg-2
				broadcast "&e&lE&6&lV&2&lE&4&lN&1&lT &estarts in %{_countdown}% second[s]"
				set {Event.Occuring} to true
				set {_pos1} to location(50, 157, 309, world "world")
				set {_pos2} to location(2, 157, 253, world "world")
				set blocks within {_pos1} and {_pos2} to packed ice
```

I did debug it, pos1 and pos2 are being set correctly. Yet, no packed ice-blocks are being set within the two locations..

It's even an example in the docs:
set blocks within %location% and %location% to stone

No errors or anything in console

* **Server version/platform:** 1.12.2    Spigot
* **Skript version:** (I have tested the certain Skript in both Skript version 2.5.1 and 2.5.2 - not working - note, it used to be working in previous versions of Skript)

**Comment by ShaneBeee** [comment]
I just found this issue the other day. I should have popped it on the issue tracker so people were aware I already know.

The issue is the bounding box that is created with this expression is actually 1 block smaller for each x, y an z.
For the time being, try increasing the Y coord in your location function.
