### ISSUE TITLE
Potions are bugged

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/Skript#3617]
### Description
Effects like giving player strong splash potion of healing doesn't work. Even copied an example from docs and still didn't work `strong splash potion of instant damage`

### Expected Behavior
`give strong splash potion of instant damage to player` should work

### Errors / Screenshots
`Can't understand this expression.`

### Server Information
* **Server version/platform:** 1.16.3 Purpur
* **Skript version:** 2.5.1

**Comment by 3meraldK** [comment]
`splash potion of strong health` worked

**Comment by ShaneBeee** [comment]
~~1) `Server version/platform: 1.16.3 Purpur` <-- we only support the latest revision of MC versions (ie: 1.16.4)
2) `Skript version: 2.5.1` <-- we do not support outdated builds
3) `strong splash potion of instant damage` <-- this is not a valid alias~~

Ah, closed as I was typing.
For future reference, check the aliases before creating issues:
https://github.com/SkriptLang/skript-aliases/blob/master/brewing.sk
