### ISSUE TITLE
Database Sync Problem

### ISSUE THREAD

**Issue by wallxq** [SkriptLang/Skript#3620]
### Description
Deadlocks and errors occur when connecting two servers to one mysql database. I noticed this problem after switching to Java 11. Paper makers now recommend using Java 11 so I changed it. Returning to Java 8, the problem is completely absent.

### Steps to Reproduce
It is enough to connect two servers to one database for the variables to synchronize between the servers and use Java 11 and Paper 1.16.4 version 318. I have the Interval set to 5 but changing to 10 and 20 did not fix the problem, only returning to Java 8 fixes the problem.

https://pastebin.com/WqxrBthg

### Server Information
Paper 1.16.4 version 318
Skript 2.5.1

Edit:
Okay.. In Java 8 a have too problem with this. How i can fix this? I clear all variable21 in recent days.When I had over 5,000 variables, this problem was not, and now only 70.
https://pastebin.com/N75aHpKL

**Comment by wallxq** [comment]
https://pastebin.com/bAkJfLZz
On nightly the same problem. 
I tried removing each addon one by one but that didn't help. I tried to delete the database and change utf but it also doesn't help. Maybe someone knows how to deal with it?

**Comment by ShaneBeee** [comment]
Marking this as "investigating"
Personally I have never touched anything regarding SQL systems, so I haven't the slightest clue what could be going on here.
Last time I heard Skript's SQL databased didn't even work, so I have no clue.

**Comment by Pikachu920** [comment]
You are hooking two instances of a skript into a single variable database?

**Comment by wallxq** [comment]
> You are hooking two instances of a skript into a single variable database?

Yes, i want use for example {hp.%player%} for many servers but for 1 player. Just sync.

**Comment by CrazyWords1** [comment]
Create sync with one of this
Skript-db or Skript-Reflect

**Comment by wallxq** [comment]
> Create sync with one of this
> Skript-db or Skript-Reflect

Thanks for your help, I did even a little better using the redis database which is extremely fast.
