### ISSUE TITLE
Hex code Formatting not synced with most plugins

### ISSUE THREAD

**Issue by DiscStrad** [SkriptLang/Skript#3621]
### Description
Hex code formatting with a Permission plugins for prefixes wont work in chat

### Steps to Reproduce
Make a chat skript with pex and luckperms and use a custom hex code for prefix it will not work

### Expected Behavior
It should be colored

### Errors / Screenshots
no errors

### Server Information
* **Server version/platform: 1.16.4**
* **Skript version: 2.5.1**

### Additional Context
Just change Hex code format to #hexcode instead of <#hexcode>

**Comment by APickledWalrus** [comment]
This is not currently possible and probably never will be. Skript uses <> to search for chat formatting. I think you should be able to work around this.
