### ISSUE TITLE
event-location does not work on spawn event of a mob (Last worked for me in skript 2.5 alpha 4)

### ISSUE THREAD

**Issue by Voiddar** [SkriptLang/Skript#3622]
### Description
event-location doesn't work with on spawn event of a mob (Last worked for me in 2.5 alpha 4)

### Steps to Reproduce
Use any code that uses event-location with an on spawn event, this one is enough:

on spawn of a mob:
	message "%event-location%" to all players

### Expected Behavior
event-location returns what it's supposed to return. Instead, it's returning an error message

### Errors / Screenshots
Error in console + no output in-game
https://i.imgur.com/E7qz7H6.png
https://i.imgur.com/PG6wPG9.png

### Server Information
Server Version: Paper 1.15.2 Build 334
Skript: Release 2.5.2

### Additional Context

Tested the bug with no addons, same result

**Comment by APickledWalrus** [comment]
Could you copy and upload the full error to something like GIST? Maybe it's just on my end, but the image is very low quality and I can't discern the error message.

**Comment by Voiddar** [comment]
That's weird... I don't know what GIST is but after googling a bit it seems like it needs commands and stuff. Anyway, the image is not that necessary, it's just a screenshot of the same console error that can be found in the pastebin link I sent.

If you wanna watch the image anyways, I'm using Microsoft Edge the imgur link and the image look fine there. Left click the image to zoom into it

**Comment by APickledWalrus** [comment]
By Gist I just meant GitHub gist, I should've been more specific haha

Also, I don't see any pastebin link. Am I missing something?

**Comment by Voiddar** [comment]
woops, I forgot to paste the link, sorry
https://pastebin.com/LaLSv3Px

**Comment by APickledWalrus** [comment]
I'm thinking this is an issue caused by https://github.com/SkriptLang/Skript/pull/3427
