### ISSUE TITLE
[12:10:31 ERROR]: #!#! Could not load json.sk

### ISSUE THREAD

**Issue by Brok3nmindd** [SkriptLang/Skript#3626]
### Description

Json wont load.
### Steps to Reproduce

I startet my Server only with Skript and SkQuery (both newest version)
### Errors / Screenshots

> [12:10:31 ERROR]: #!#! Could not load json.sk
> [12:10:31 ERROR]: #!#!
> [12:10:31 ERROR]: #!#! Something went horribly wrong with Skript.
> [12:10:31 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [12:10:31 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
> [12:10:31 ERROR]: #!#! Here is full list of them:
> [12:10:31 ERROR]: #!#! SkQuery v4.1.4
> [12:10:31 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
> [12:10:31 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
> [12:10:31 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
> [12:10:31 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
> [12:10:31 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
> [12:10:31 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
> [12:10:31 ERROR]: #!#!
> [12:10:31 ERROR]: #!#! Stack trace:
> [12:10:31 ERROR]: #!#! java.lang.NullPointerException
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSubstring.isSingle(ExprSubstring.java:108)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.init(EffChange.java:249)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:251)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:45)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:146)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:650)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
> [12:10:31 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:231)
> [12:10:31 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [12:10:31 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
> [12:10:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
> [12:10:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:764)
> [12:10:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
> [12:10:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
> [12:10:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
> [12:10:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
> [12:10:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
> [12:10:31 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:832)
> [12:10:31 ERROR]: #!#!
> [12:10:31 ERROR]: #!#! Version Information:
> [12:10:31 ERROR]: #!#!   Skript: 2.5.2 (latest)
> [12:10:31 ERROR]: #!#!     Flavor: skriptlang-github
> [12:10:31 ERROR]: #!#!     Date: 2020-11-28
> [12:10:31 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
> [12:10:31 ERROR]: #!#!   Minecraft: 1.16.4
> [12:10:31 ERROR]: #!#!   Java: 14.0.2 (OpenJDK 64-Bit Server VM 14.0.2+12-Ubuntu-120.04)
> [12:10:31 ERROR]: #!#!   OS: Linux amd64 5.4.0-54-generic
> [12:10:31 ERROR]: #!#!
> [12:10:31 ERROR]: #!#! Server platform: Paper
> [12:10:31 ERROR]: #!#!
> [12:10:31 ERROR]: #!#! Current node: set {_code} to the first character of {_color} (json.sk, line 45)
> [12:10:31 ERROR]: #!#! Current item: null
> [12:10:31 ERROR]: #!#!
> [12:10:31 ERROR]: #!#! Thread: Server thread
> [12:10:31 ERROR]: #!#!
> [12:10:31 ERROR]: #!#! Language: english
> [12:10:31 ERROR]: #!#! Link parse mode: DISABLED
> [12:10:31 ERROR]: #!#!
> [12:10:31 ERROR]: #!#! End of Error.
> [12:10:31 ERROR]: #!#!

### Server Information
* **Server version/platform:**  Paper(322)
* **Skript version:**  latest

**Comment by ShaneBeee** [comment]
This is due to another issue #3585
