### ISSUE TITLE
Trigger stop when checking the player's tool and it's name 

### ISSUE THREAD

**Issue by 4L0N50asd** [SkriptLang/Skript#3630]
### Description

I have an script where it does something only when the player has an item on its hand, and that item's name is a custom name. This worked until Skript version 2.5.1, there it stopped working, also doesn't works in 2.5.2, 2.5.3. No console errors.
### Steps to Reproduce

Code:
```
command /testingasd:
	trigger:
		if player is holding a trident named "&d&lTrident":
			broadcast "It Worked"
```
I used other trigger ways like "on chat → if message is...→ if player is holding...", "on shoot → shooter's tool is a trident named..." and when uploading to 2.5.1 i just got noticed that it just doesn't works, but also it doesn't send errors.

### Expected Behavior

Expected to continue the trigger and do the stuff after checking if player's tool is a <type> item named <name>

### Errors / Screenshots

No console errors and no errors in chat when reloading the script file. Just stops the trigger.

### Server Information
* **Server version/platform:** 
Paper version git-Paper-296
* **Skript version:** 
2.5.1
2.5.2
2.5.3

**Comment by APickledWalrus** [comment]
Same issue as #3618. There is a fix in progress :)
