### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by laivytkill** [SkriptLang/Skript#3638]
cant start the server, i use the latest version of spigot, and paper spigot 1.16.1

https://pastebin.com/QJxJyfZZ

:c

**Comment by MrScopes** [comment]
I'm assuming you meant the latest version of skript? (2.5.3)

**Comment by laivytkill** [comment]
> I'm assuming you meant the latest version of skript? (2.5.3)

yea i downloaded today @MrScopes

**Comment by MrScopes** [comment]
> > I'm assuming you meant the latest version of skript? (2.5.3)
> 
> yea i downloaded today @MrScopes

have you tried 2.5.2

**Comment by ShaneBeee** [comment]
Closing due to lack of information.
When creating a new issue, please fill in the template. You have provided us with very little information.

Based on the crash, my only guess is your code is doing something excessively. 
Try to debug this yourself.
