### ISSUE TITLE
Skript can't load variables on Debian 10

### ISSUE THREAD

**Issue by Kapsulon** [SkriptLang/Skript#3639]
Hello, i am using the latest release of skript on a 1.16.4 spigot server, it is setup on a debian 10 VM, every time i try doing something, i get this error:

[Skript] Loading variables...
[22:36:54] [Server thread/ERROR]: #!#!
[22:36:54] [Server thread/ERROR]: #!#! ===!!!=== Skript variable load error ===!!!===
[22:36:54] [Server thread/ERROR]: #!#! Unable to load (all) variables:
[22:36:54] [Server thread/ERROR]: #!#! Cannot write to the database file 'variables.csv'!
[22:36:54] [Server thread/ERROR]: #!#!
[22:36:54] [Server thread/ERROR]: #!#! Skript will work properly, but old variables might not be available at all and new ones may
 or may not be saved until Skript is able to create a backup of the old file and/or is able to connect to the database (which requ
ires a restart of Skript)!

I already tried doing sudo chmod 777 Skript.jar but it isn't working

**Comment by Romitou** [comment]
You're indeed experiencing file permissions issues. You must chown or chmod the Skript's folder, not the .jar file.

**Comment by Kapsulon** [comment]
I resolved the issue, had to do "sudo chmod 777 variables.csv"

**Comment by Kapsulon** [comment]
Now i have an issue very similar to the one before, when i close my server nothing is saved, i get this message in the console: [Server thread/ERROR]: [Skript] Unable to make a final save of the database 'default' (no variables are 
lost): plugins/Skript/variables.csv.temp (Permission denied)
Since its a temporary file i can't really change its permissions, any idea ?

**Comment by Romitou** [comment]
As already said above, you must chmod or chown the ENTIRE folder recursively in order to allow Skript to write, read...

**Comment by Pikachu920** [comment]
@Romitou is right, this is just a permissions thing and not related to the way Skript is reading/writing. As a side note, why wouldn't you simply give the user running the server read/write access (if not ownership) of the entire server folder and it's contents?
