### ISSUE TITLE
Cancel event passthrough 

### ISSUE THREAD

**Issue by wallxq** [SkriptLang/Skript#3640]
### Description
Cancel event can be passed with a large number of clicks, and sometimes even with the first click.

The item that I have in the "cursor slot of player" will be able to put it there after brutally clicking on the slot. However, if there is an item in slot 40 for example, it cannot be done. Only if slot = air.

### Steps to Reproduce
(editing your code directly into here, cause that website is loading so slowly [edited by ShaneBeee])
```vb
on inventory click:
    if clicked slot is 40:
        cancel event
```

### Expected Behavior
The item shouldn't go in there no matter what.

### Errors / Screenshots
0 errors

![javaw_2020_12_15_15_18_07_921](https://user-images.githubusercontent.com/36922415/102226899-3d333400-3ee9-11eb-9f45-246c7b7a3732.gif)

### Server Information
Paper 1.16.4 version 325
Skript 2.5.3

**Comment by ShaneBeee** [comment]
I tried your exact code on the same version of Skript and paper, and I could not reproduce.
Issues like this are generally not related to Skript, but the server itself possibly a tiny lag issue that is causing it to do that.
More often than not, the item isn't actually moved, just the player (client) hasn't realized that yet.

**Comment by MovesLikeJaeger** [comment]
Pretty sure this is a clientside visual thing isn't it?

**Comment by wallxq** [comment]
I tested it during server maintenance where players are absent.  It's quite strange, I connect to the server via LAN.  Ping is almost equal to 0. Tps constantly 20. Then I will create a test server without plugins, only with skript and see if the problem occurs.  I use a very powerful r9 5950x hardware, so the power per thread is quite high.  I will let you know how it turned out on the server without plugins.

**Comment by wallxq** [comment]
![e](https://user-images.githubusercontent.com/36922415/102356256-45ed3e00-3fad-11eb-8789-27a00d5f30ae.gif)
I use clean server, only skript and defaults skripts with that for block 40 slot.
