### ISSUE TITLE
Cooldown bypass command 

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#3643]
Hey, add a pattern like this:
Cooldown bypass command: test
And trigger:
        Cancel cooldown to all or 10 random or "/test" commands for all players|op's etc.

**Comment by ShaneBeee** [comment]
what exactly are you asking for here?
Can you give at least some sort of details, some more than "like this"

**Comment by Misio12320** [comment]
When player use a command with cooldown.
I want to skip his cooldown via command /bypass %player%
I suggest to add effect ""bypass cooldown of command" test" for %player%""

**Comment by ShaneBeee** [comment]
You can already cancel the Cooldown in a command.
http://skriptlang.github.io/Skript/effects.html#EffCancelCooldown

With a variable and some creativity, this shouldn't be all that hard to accomplish.
