### ISSUE TITLE
Target block player head placed on walls

### ISSUE THREAD

**Issue by Henriiig** [SkriptLang/Skript#3644]
### Description

Player heads are not registered as a target block when placed on walls

### Steps to Reproduce

Place a player head on a wall and try getting the block using the following skript which works when the player head is not placed on a wall.

command /getblock:
	trigger:
		if target block is player head:
			set {_b} to target block
			set {_nbt} to nbt of target block
			give player 1 of {_b} with nbt {_nbt}
		if target block is not player head:
			give player target block

### Expected Behavior

The player should receive the targeted player head with correct nbt using the command

### Server Information
* **Server version/platform:** 
* **Skript version:** 

Server: Paper git-paper-323 MC 1.16.4
Skript: 2.5.3

**Comment by ShaneBeee** [comment]
That is because the aliases are different for wall/floor heads.

```
# Skulls on walls
{directional} player wall[-mounted] (head|skull)¦s = minecraft:player_wall_head

# Skulls on floors
{reversed rotatable} player (head|skull)¦s = minecraft:player_head
```
as seen here:
https://github.com/SkriptLang/skript-aliases/blob/09d308f78833c6ecb5f38b0b0f0dad717caf7ac0/decoration.sk#L556
