### ISSUE TITLE
on inventory open

### ISSUE THREAD

**Issue by wallxq** [SkriptLang/Skript#3645]
### Description
The event is not working properly. The event works just like on inventory close.
### Steps to Reproduce
https://pastebin.pl/view/f5dd38b2

### Expected Behavior
It should say "eee" when opening inventory, not closing it.

### Errors / Screenshots
Without errors.

### Server Information
Paper 1.16.4 version 325
Skript 2.5.3

**Comment by ShaneBeee** [comment]
I can not replicate the issue.

Test code
```vb
on inventory open:
	send "&aOPEN"

on inventory close:
	send "&cCLOSE"
```

output:
<img width="966" alt="Screen Shot 2020-12-16 at 1 45 18 PM" src="https://user-images.githubusercontent.com/20008482/102410168-04f12b80-3fa5-11eb-8d90-2f9fae69a569.png">
<img width="966" alt="Screen Shot 2020-12-16 at 1 45 28 PM" src="https://user-images.githubusercontent.com/20008482/102410174-07538580-3fa5-11eb-98cb-63b474796692.png">

**Comment by Leautis** [comment]
I think he means when player opens their own inventory but that is client side

**Comment by wallxq** [comment]
> I think he means when player opens their own inventory but that is client side
Do you mean a crate created by us is interpreted differently from that created and placed by someone else or a server? I think some in-game package is responsible for this.

**Comment by wallxq** [comment]
Okay, i tested this on clear server and work good. I will look for addons that are responsible for this.

**Comment by wallxq** [comment]
Wolfsk was problem
