### ISSUE TITLE
On click EVENT problem

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#3646]
### Description
In the latest 2.5.3 skript bensku. on left click / right click is not working. no error but it just dont

### Steps to Reproduce
tested multiple ways 
on click:
on right click:

### Expected Behavior
to trigger

### Errors / Screenshots
no errors

### Server Information
paper-1.16.4-335
skript 2.5.3

**Comment by DelayedGaming** [comment]
1. Can you show us the full code you used?
2. Make sure you are holding something before left/right clicking. Server does not recognize you are clicking with empty hand.

**Comment by Sodies** [comment]
im using
`on right click with compass:
    send "s"`

doesn't send anything

**Comment by Sodies** [comment]
> 1. Can you show us the full code you used?
> 2. Make sure you are holding something before left/right clicking. Server does not recognize you are clicking with empty hand.

fixed it. please close this case. THAnks!
