### ISSUE TITLE
Triggers Twice every effects

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#3649]
### Description
In the latest 2.5.3 skript bensku. effects will activate twice

### Steps to Reproduce
at 7:00:
	if size of all players is greater than 0:
		add 1 to {days}
		broadcast "&f&lLife &7➥ &eYou are now living on day &e&l&n%{days}%&r&e&l!"
		stop

### Expected Behavior
suppose to trigger once only

### Errors / Screenshots
no errors just the message send twice

### Server Information
paper-1.16.4-335
skript 2.5.3

**Comment by TPGamesNL** [comment]
Event description: An event that occurs at a given minecraft time **in every world** or only in specific worlds. The trigger is executed once per world.

**Comment by Sodies** [comment]
> Event description: An event that occurs at a given minecraft time **in every world** or only in specific worlds. The trigger is executed once per world.

thanks i forgot i have 2 worlds
