### ISSUE TITLE
Crash when generating new block

### ISSUE THREAD

**Issue by DIABLOxMJ** [SkriptLang/Skript#3650]
### Description
server crash because a product error since I installed Skript 2.5.3 and conflicts with Citizen and WorldGuard something that was not present with Skript 2.5.2 it makes impossible to generate new chunk and none of my Skript interacts with the chunks concerned.

### Steps to Reproduce
By generating new chunk

### Expected Behavior
nothing

### Errors / Screenshots
https://pastebin.com/raw/27SqTXS8

### Server Information
Server version/platform: Paper v191 MC v1.16.3
Skript version: 2.5.3

### Additional Context
Nothing

**Comment by TPGamesNL** [comment]
Can you show your code from the event https://skriptlang.github.io/Skript/events.html#chunk_generate

**Comment by DIABLOxMJ** [comment]
on chunk generate:
	loop blocks within event-chunk:
		if loop-block is end_stone:
			chance of 0.001%:
				set block at location of loop-block to target

It just allows to replace a block within a radius of the end stone with another.

**Comment by TPGamesNL** [comment]
Try waiting a tick before looping

**Comment by DIABLOxMJ** [comment]
Ok thank you for your advice and your responsive response I will try immediately

**Comment by DIABLOxMJ** [comment]
It works better since the "wait 1 second" thank you for the info I should have foreseen it sooner I close the subject.
