### ISSUE TITLE
Looping Ignores If

### ISSUE THREAD

**Issue by Rebel0810** [SkriptLang/Skript#3654]
### Description
When I loop blocks it ignores my if and does it no matter what

### Steps to Reproduce
Code:
```
on right click on a villager:
  if player is holding a stick:
    set {_loc1} to location of villager
    set {_loc2} to block 75 above block at location of villager
    loop all blocks between {_loc1} and {_loc2}:
      set loop-blocks to bedrock
```

### Expected Behavior
Only if I am holding a stick when right clicking the villager should the blocks be looped

### Errors / Screenshots
No errors

### Server Information
* **Server version/platform:** 
* Server version is Spigot 1.16.4
* **Skript version:** 
* I am using Skript 2.5.3

**Comment by ShaneBeee** [comment]
I tested, slightly adjusted your code (to debug):
```vb
on right click on a villager:
  if player is holding a stick:
    set {_loc1} to location of villager
    set {_loc2} to block 75 above block at location of villager
    send "&aClicking" to player
    loop all blocks between {_loc1} and {_loc2}:
      set loop-blocks to bedrock
  else:
    send "&cNOPE" to player
```
outcome:
<img width="966" alt="Screen Shot 2020-12-25 at 4 00 28 AM" src="https://user-images.githubusercontent.com/20008482/103134395-ca068c00-4665-11eb-96c8-7b5da69af30a.png">


Needless to say, I can not replicate this issue.

**Comment by ShaneBeee** [comment]
Closing due to could not replicate, and have had no response in nearly 30 days
