### ISSUE TITLE
Unexpected behavior on Skript reload

### ISSUE THREAD

**Issue by bailletced** [SkriptLang/Skript#3660]
### Description

Let's assume we have two .sk files : one named **test1.sk** and another one named **test2.sk**
The file **test1.sk** is calling a function named _myfunction()_
The file **test2.sk** contains the function named _myfunction()_

That being said, when modifying the content of _myfunction()_ and then reloading the file **test2.sk** by performing a **/sk reload test2.sk**, changes are not taken into account. We also have to reload **test1.sk**.

### Steps to Reproduce

Create a file named **test1.sk** with following content:
```
command /test [<text>]:
    trigger:
        myfunction()
```
Create a file named **test2.sk** with following content:
```
function myfunction():
    broadcast "test 2"
```

Perform the command **/sk reload scripts**
Then, run /test to see the result. "test 2" should be broadcasted.
Afterward, edit the file test2.sk  with following content:
```
function myfunction():
    broadcast "test 2 refreshed"
```
Perform the command  **/sk reload test2.sk**
Then, run /test to see again the result.

### Expected Behavior

At the second output, "test 2 refreshed" should be displayed. 
However, only "test 2" is being displayed.
Because of this bug, to make changes occurs, **test1.sk** also need to be reloaded.

### Server Information
* **Minecraft:** 1.16.4
* **Paper:** 279
* **Skript version:** 2.5.3

### Additional Context

This issue is causing problem when reloading all scripts in a project is time consuming. Such an issue is unfortunately limiting the development of large projects.

**Comment by bailletced** [comment]
Is the issue clear enough? I can add some details if required.

**Comment by Olyno** [comment]
^ I can confirm
