### ISSUE TITLE
Last spawned entity not working well

### ISSUE THREAD

**Issue by Palgia** [SkriptLang/Skript#3662]
### Description
The expression "last spawned entity" works fine except when you use it to set an armor.

### Steps to Reproduce
`command /testspawn:`
` trigger:`
`  spawn 1 zombie at player`
`  set helmet of last spawned entity to diamond helmet`

### Expected Behavior
The spawned zombie should have a diamond helmet, but it doesn't. 

If I try this for example, it works:
`command /testspawn:`
` trigger:`
`  spawn 1 zombie at player`
`  set name of of last spawned entity to "TEST"`

So the issue is only related setting last spawned entity's armor. 

### Errors / Screenshots
There is no errors.

### Server Information
Server: Spigot 1.16.4-R0.1 SNAPSHOT
* **Skript version:** 2.5.3

**Comment by ShaneBeee** [comment]
Update your Spigot, this was a spigot issue.

**Comment by Palgia** [comment]
Thanks for your help, fixed !
