### ISSUE TITLE
"Is Enchanted" condition doesn't check for enchantment level

### ISSUE THREAD

**Issue by oskarkk** [SkriptLang/Skript#3664]
### Description
"Is Enchanted" condition is true for every level of enchantment that is tested. Possibly existing since #2049

### Steps to Reproduce

```
on inventory click:
  if event-item is enchanted with efficiency 3:
    message "efi3"
  if event-item is enchanted with efficiency 4:
    message "efi4"
  if event-item is enchanted with efficiency 5:
    message "efi5"
```

Then if you click on any item enchanted with any level of efficiency you will get:
```
efi3
efi4
efi5
```

### Expected Behavior
[Official docs](https://skriptlang.github.io/Skript/conditions.html#CondIsEnchanted):
`%item types% (is|are) enchanted [with %enchantment type%]`

Official example:
`tool of the player is enchanted with efficiency 2`

[Enchantment type syntax](https://skriptlang.github.io/Skript/classes.html#enchantmenttype) (formatting on the website is broken btw):
`<enchantment> [<level>]`

So, e.g. efi5 should appear only when clicking an item with efficiency 5. 

### Server Information
```
[17:25:10 Server thread/INFO] [Skript] Server Version: git-Spigot-628435a-6917945 (MC: 1.16.4)
[17:25:10 Server thread/INFO] [Skript] Skript Version: 2.5.3
[17:25:10 Server thread/INFO] [Skript] Installed Skript Addons:
[17:25:10 Server thread/INFO] [Skript]  - Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[17:25:10 Server thread/INFO] [Skript]  - SkQuery v4.1.4
[17:25:10 Server thread/INFO] [Skript]  - SkBee v1.9.1 (https://github.com/ShaneBeee/SkBee)
[17:25:10 Server thread/INFO] [Skript]  - Ersatz v1.0
```

**Comment by TPGamesNL** [comment]
This is caused by
https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/conditions/CondIsEnchanted.java#L68
there is simply no check for the level

**Comment by FranKusmiruk** [comment]
> This is caused by
> https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/conditions/CondIsEnchanted.java#L68
> 
> 
> there is simply no check for the level

Do note, the logic should be added to the [ItemType#hasEnchantments(EnchantmentType...)](https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/aliases/ItemType.java#L1154-L1165) check.
