### ISSUE TITLE
Remove named item (1.16) form player's inventory

### ISSUE THREAD

**Issue by Envqu** [SkriptLang/Skript#3665]
### Description

remove crimson nylium named "x" from player's inventory - not working (no errors)
if i replace nylium with dirt its ok.

- remove crimson nylium from player's inventory - its works without "named ..."

### Server Information
* **Server version/platform:** Paper-345 (1.16.4) 
* **Skript version:** 2.5.3

**Comment by APickledWalrus** [comment]
Does https://github.com/SkriptLang/Skript/pull/3633 improve your situation at all?

You can download a jar to test here: https://github.com/SkriptLang/Skript/suites/1657582871/artifacts/30803126
It is experimental though so don't run it in a production environment.

**Comment by TPGamesNL** [comment]
Can't replicate, likely fixed in #3960
