### ISSUE TITLE
correct usage option is missing in english.lang , german.lang, korean.lang

### ISSUE THREAD

**Issue by mckite** [SkriptLang/Skript#3667]
### Description
correct usage option is missing in english.lang , german.lang, korean.lang

When I change the usage:
It does not shown as prefix of correct usage.

I tired to change the usage: 
but it is not showing.
```
# -- Commands --
commands:
	no permission message: You don't have the required permission to use this command
	cooldown message: You are using this command too often, please try again later
	executable by players: This command can only be used by players
	executable by console: This command can only be used by the console
	usage: Usage:
	invalid argument: Invalid argument <gray>'%s<gray>'<reset>. Allowed are:
	too many arguments: This command can only accept a single %2$s.
	internal error: An internal error occurred while attempting to perform this command.
	no player starts with: There is no player online whose name starts with '%s'
	multiple players start with: There are several players online whose names start with '%s'
```

### Steps to Reproduce
Nothing
### Expected Behavior

There should be option for "correct-usage" and able to set prefix of usage.

Or
When type wrong usage for command.
It should show the message "Usage: /command <args>" instead of just "/command <args>"

### Server Information 
* **Server version/platform:**  Paper version git-Paper-1618 (MC: 1.12.2
* **Skript version: 2.5.3

**Comment by ShaneBeee** [comment]
> Steps to Reproduce
>
> Nothing

Why is there no steps to reproduce?

What method are you using to change the lang file?

**Comment by mckite** [comment]
I tried to find correct-usage text in lang file, but not exist.

I changed usage: Usage: to usage: Info
by text editor, but it does not apply in game.

**Comment by ShaneBeee** [comment]
are you changing the lang file in the Skript jar?

We need more info here.

**Comment by mckite** [comment]
> are you changing the lang file in the Skript jar?
> 
> We need more info here.

Yes it is in the skript.jar

**Comment by TPGamesNL** [comment]
This feature was removed in https://github.com/SkriptLang/Skript/pull/2266, so it isn't supposed to be there. The `usage` node is used when incorrectly using the `/skript` command.
