### ISSUE TITLE
coal is not checked as intended

### ISSUE THREAD

**Issue by mckite** [SkriptLang/Skript#3668]
### Description

When write script as just remove coal, it also removes charcoal/.

command /coaltest [<text>]:
	usage: /coaltest 
	trigger:
		if player has 64 of mine_coal:
			remove 64 of mine_coal from the player
			give player charcoal named "&atest"

### Steps to Reproduce

Add the alias.
like below in misc.sk:

old items:
	minecraft version = 1.12.2 or older
	charcoal = minecraft:coal {Damage:1}
	**mine_coal = minecraft:coal {Damage:0}**
	sugar cane item¦s = minecraft:reeds
	sugar cane¦s = minecraft:sugar_cane_block
	popped chorus fruit¦s = minecraft:chorus_fruit_popped
	nether brick item¦s = minecraft:netherbrick

And make an command:

command /coaltest [<text>]:
	usage: /coaltest 
	trigger:
		if player has 64 of mine_coal:
			remove 64 of mine_coal from the player
			give player charcoal named "&atest"

This problem also can be reproduced by as below:

command /stonetest [<text>]:
	usage: /stonetest 
	trigger:
		if player has 64 of polished granite:
			remove 64 of polished granite from the player
			give player raw granite named "&atest"

And, get a 64 of polished granite and get a 64 of raw polished granite,
and type /stonetest 2 times, 
the raw granite is removed while it is not intended,

This problem does not happen in skript 2.3.6

### Expected Behavior

The item should remove just coal  (Not charcoal)
 instead of both charcoal and coal.

### Server Information
* **Server version/platform:* Paper version git-Paper-1618 (MC: 1.12.2) 
* **Skript version:**  2.5.3

**Comment by APickledWalrus** [comment]
Seems to be the same issue as #3669
