### ISSUE TITLE
Wool comparing problem

### ISSUE THREAD

**Issue by mckite** [SkriptLang/Skript#3669]
### Steps to Reproduce

When write the code as below:
```vb
command /wooltest [<text>]:
	usage: /wooltest 
	trigger:
		if player has 64 of orange wool:
			remove 64 of orange wool from the player
			give player yellow wool named "&atest"
```

If player has 64 of orange wool and 64 of yellow wool, and then type "/wooltest" two times,
the yellow wool is removed from inventory.

### Expected Behavior

If the player types "wooltest" 2 times, it should not remove yellow wool as yellow wool is not orange wool.

It seems problem at loading aliases or checking item that has data of such as "{Damage:1}"

**It seems the might be the same problem as https://github.com/SkriptLang/Skript/issues/3668**

This problem does not happen in 2.3.6.

### Server Information
* **Server version/platform:** Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
* **Skript version:**2.5.3
* 

### Additional Context

**It seems related problem as https://github.com/SkriptLang/Skript/issues/3668**

**Comment by EtoNikei** [comment]
Recommend using types of items with many data values. (e.g if player has type of orange wool -> remove orange wool from player's inventory)

**Comment by mckite** [comment]
> Recommend using types of items with many data values. (e.g if player has type of orange wool -> remove orange wool from player's inventory)

I already uses as  orange wool .

**Comment by APickledWalrus** [comment]
Seems to be fixed with https://github.com/SkriptLang/Skript/pull/4162
