### ISSUE TITLE
Installation bug: config and other files not generated

### ISSUE THREAD

**Issue by williamd5** [SkriptLang/Skript#3670]
### Description
Configuration files and other files that would usually be generated by Skript are missing on initial install.

### Steps to Reproduce
1. Put Skript.jar in /plugins
2. Create a folder called "Skript"
3. Restart server

### Expected Behavior
Config files should be generated

### Errors / Screenshots
`/sk reload config`:
![image](https://user-images.githubusercontent.com/66572326/103445660-e024d580-4c7f-11eb-9761-539d527370d9.png)

### Additional Context
This happens if you are importing scripts (hence adding content to the `Skript` folder) before the plugin is initialised.

**Comment by ShaneBeee** [comment]
1) Missing version info
2) You have to let Skript initialize first, so it can create the appropriate files.

**Comment by williamd5** [comment]
I am running release 2.5.3.
What am I suggesting is that Skript checks if the files e.g. config.sk exist and not if the folder exists. It's much more convenient to be able to create a scripts folder before having restarted the server hence load Skript. For instance, if you only do scheduled reboots and one of your scripts uses events such as on join etc., this will cause players joining after the reboot not trigger these events because you need to move the scripts once your server is started, reload them, etc.
