### ISSUE TITLE
Drops from block

### ISSUE THREAD

**Issue by EtoNikei** [SkriptLang/Skript#3676]
### Description
Got failed item-drops with enchantments.

### Steps to Reproduce
I create a simple script, while player mining a block, drop from event-block added to inventory of event-player.
code: https://pastebin.com/8YtbRsFY

### Expected Behavior
On mine a STONE drop from event-block using SILK TOUCH should be a STONE BLOCK, not COBBLESTONE BLOCK

### Errors / Screenshots

no any.

### Server Information
Dedicated server: Paper-1.12.2-b1618.jar
Skript version: tested on 2.4 and 2.5.3

### Additional Context
I hope to solve this problem :(

**Comment by ShaneBeee** [comment]
This is actually an issue with the server not Skript. It was something that was fixed in Spigot within the last year I believe, so those fixes will not reflect on your 1.12.2 server.
