### ISSUE TITLE
Cant open unnamed brewing stand

### ISSUE THREAD

**Issue by DampfWaffel** [SkriptLang/Skript#3677]
### Description
Script won't recognize the Code for opening a brewing stand without any name.

### Steps to Reproduce
`open brewing stand inventory named "&7Hello There" to player` - works as intended
`open brewing stand inventory to player` - dont work

### Expected Behavior
the brewing stand should be opened

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/19693397/103677371-7dcf1c00-4f82-11eb-8018-92ce1e2d44ef.png)

### Server Information
* **Server version/platform:** Paper version git-Paper-337 (MC: 1.16.4)
* **Skript version:** 2.5.3

### Additional Context
i've encountered the Error last year ago.
https://discord.com/channels/135877399391764480/399406319221866507/759807373963034694

**Comment by ShaneBeee** [comment]
Thats because there is no effect for opening a brewing stand. 
There is, as you can see, an expression for named inventory, which includes the brewing stand inventory.

This is not a bug.

**Comment by DampfWaffel** [comment]
ah okey.
so the difference is the open effect does not support inventory types?

oke but confusing. thanks for the answer

**Comment by FranKusmiruk** [comment]
> so the difference is the open effect does not support inventory types?

It does and correct me if I am wrong since I haven't looked at the source code in a while but I remember adding an InventoryType -> Inventory converter so this would be possible. If that hasn't changed then this is indeed a bug.

**Comment by TPGamesNL** [comment]
I can confirm this. 

> > so the difference is the open effect does not support inventory types?
> 
> It does and correct me if I am wrong since I haven't looked at the source code in a while but I remember adding an InventoryType -> Inventory converter so this would be possible. If that hasn't changed then this is indeed a bug.

I cannot find that converter anywhere, maybe you thought of [this](https://github.com/SkriptLang/Skript/commit/3a2b0fccd31af904e9708438fd3106ff95103ae4#diff-0fe51f09a3ff2335a35d2257553edaba977d17955755696e542e7ed804aae892)?
