### ISSUE TITLE
Differentiating between a 3x3 Crafting table inventory and player's actual inventory.

### ISSUE THREAD

**Issue by MovesLikeJaeger** [SkriptLang/Skript#3681]
**#Description**
Attempted to set slots of a 3x3 crafting inventory to air, was not able to proceed due to not being able to differentiate between the player's inventory and the crafting inventory using:
- index of event-slot
- event-inventory
- player's top|current|open inventory

Index of event-slot will return "1" on the top left of the crafting inventory, which is the same as the 2nd slot of the player's inventory. This repeats throughout all crafting slots/first few of the players inventory slots.
gif: https://gyazo.com/5c0da7f9b83710c61703767a9c266450

**# Steps to Reproduce**
Clicking between the 3x3 crafting inventory and player inventory to compare between.

on inventory click:
#was not able to differentiate with these:
  broadcast "p's top|current|open inv: %player's top inventory%, index of e-slot: %index of event-slot%, e-inventory: %event-inventory%, event-slot: %event-slot%"

#was able to with differentiate skript-reflect 2.1.0:
  broadcast "slottype: %event.getSlotType()%, rawslot: %event.getRawSlot()%, hashcode: %event.getClickedInventory().hashCode()%"

**# Expected Behavior**
I assumed there would be a way to differentiate between the two inventories (Apologies if this is the wrong assumption).

**# Errors / Screenshots**
N/A

**#Screenshots of assumed bug**
![image](https://user-images.githubusercontent.com/75779721/104003420-44f3a900-5207-11eb-8edc-de4fae47f947.png)

**# Server Information**
Paper 1.16.4
Skript 2.5.3
*Not required but was present: SkBee
*Tested after with methods from: Skript-Reflect (also present entire time)

**Comment by TPGamesNL** [comment]
Have you tried using https://skriptlang.github.io/Skript/expressions.html#ExprTypeOf?

**Comment by MovesLikeJaeger** [comment]
Thank you very much, works perfectly. You were the one who suggested I make a ticket about this too hahaha!
Awesome, broadcasting type of event-inventory will return different strings when you click in your own inventory and in the crafting bench! I can't believe I didn't see this, cheers

**Comment by TPGamesNL** [comment]
Oh I forgot about that lol
