### ISSUE TITLE
[Skript] Severe Error

### ISSUE THREAD

**Issue by jakkeren** [SkriptLang/Skript#3684]
### Description
Severe Skript error appears out of random - skript variables won't save after server restart.

### Steps to Reproduce
Came out of random, nothing specific was done to make the error appear. When restarting our server, all skript variables not stored in YAML will be reset.

### Expected Behavior
Skript should save the variables inside of variables.csv as expected, not leave it empty.

### Errors / Screenshots

https://pastebin.pl/view/0271e3a6

### Server Information
* **Server version/platform: Latest paper version, 1.16.4.
* **Skript version: Latest skript version, 2.5.2.

**Comment by ShaneBeee** [comment]
Based on what I see in the error:
```
09.01 13:36:25 [Server] ERROR #!#! Stack trace:
09.01 13:36:25 [Server] ERROR #!#! java.lang.ClassCastException: org.bukkit.event.hanging.HangingBreakEvent cannot be cast to org.bukkit.event.hanging.HangingBreakByEntityEvent
09.01 13:36:25 [Server] ERROR #!#!     at com.gmail.thelimeglass.Register$46.get(Register.java:566) <=============
09.01 13:36:25 [Server] ERROR #!#!     at ch.njol.skript.registrations.EventValues$3.get(EventValues.java:322)
09.01 13:36:25 [Server] ERROR #!#!     at ch.njol.skript.registrations.EventValues$3.get(EventValues.java:1)
09.01 13:36:25 [Server] ERROR #!#!     at 
```
it appears this is caused by a LimeGlass addon, my guess would be Skellett.

Please try replicate this issue without addons installed. If the issue persists, then send the new error.
If not, please reach out to the author of the addon with the issue.

**Comment by ShaneBeee** [comment]
Closing due to lack of response, and this appears to not be a Skript issue.
