### ISSUE TITLE
ConcurrentModificationException when reloading script during event execution

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#3685]
### Description
I got a console error

### Steps to Reproduce
a.sk:
```
on join:
	make server execute command "sk reload a"

on join:
	broadcast "Welcome, player!"
```

### Expected Behavior
No console error

### Errors / Screenshots
https://pastebin.com/uMfUeBHQ

### Server Information
* **Server version/platform:** Paper-1.16.4-317
* **Skript version:** 2.5.2

### Additional Context
This occurs because of an iterator in SkriptEventHandler (btw, why is it abstract?). The iterator, provided by `getTriggers`, uses the iterator from the lists in `triggers`. This iterator is started when SkriptEventHandler's `check` method is called, and it checks if there's a value, then gets that trigger and executes it. Because the iterator is still in use when the trigger is executed (and with that, the script reloaded), the list in `triggers` is modified, therefore the iterator will throw an `ConcurrentModificationException`. This issue can be solved by first making a copy of the list, then iterating over them and executing them.

**Comment by Moderocky** [comment]
Using your fix (cloning the list) does the original event trigger continue to run despite the reload?

**Comment by TPGamesNL** [comment]
Yes, executing of the trigger is just a method call, if the list is copied I don't see a way it'll have an impact on the loop running (or trigger running)
![image](https://user-images.githubusercontent.com/29547183/104463785-7dea9f80-55b2-11eb-9fed-9644bad609b9.png)

**Comment by Moderocky** [comment]
Might this then have unintended consequences?
If the original behaviour was to throw a checked exception which would halt the execution, and now it will continue, would it not be better to catch and silence that original exception from the event iterator (because in this instance the exception IS serving a purpose - stopping the event from running while it’s being reloaded)

**Comment by TPGamesNL** [comment]
I guess this is partially just a choice for how devs want it to work. 

```
on join:
	make server execute command "sk reload a"

on join:
	broadcast "Welcome, player!"
```
If they only want this code to execute the first trigger that reloads a script, not executing any triggers after it (including from other files), that's up to them. I just think it'd make more sense to have Skript execute all triggers, independent of whether their scripts have been reloaded or not.

While the exception is technically serving a purpose, since the trigger list has been updated, I do not think that it should affect trigger execution, but I would appreciate some feedback from the devs.

**Comment by Moderocky** [comment]
My only concern would be if the event triggered some long-running execution, like a `while player is online` in this instance - would it not keep running after the reload?

**Comment by TPGamesNL** [comment]
That would keep running after reloading, independent of whether any fix for this is implemented or not.
