### ISSUE TITLE
Functions not working when passing empty list variable

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#3687]
### Description
Functions not working correctly when passing an empty list variable to them.

### Steps to Reproduce
The script:
```
function testfunc(l: objects):
	broadcast "something"

command /testing [<text>] [<text>]:
	trigger:
		testfunc({_temp::*})
```
Result should be:
"something" in the chat.
But nothing happens. (not even a console error)

Now if you add an element to the list variable like this, it will work:

```
function testfunc(l: objects):
	broadcast "something"

command /testing [<text>] [<text>]:
	trigger:
		add "red" to {_temp::*}
		testfunc({_temp::*})
```
result: "something" in chat

### Expected Behavior
The code in the functions should be executed, even when you pass an empty list variable to it.

### Server Information
* **Server version/platform:** Tuinity 1.16.4
* **Skript version:** 2.5.3

**Comment by TPGamesNL** [comment]
Cause:
https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/lang/function/Function.java#L89-L90
