### ISSUE TITLE
Addition of some things in the aliases.

### ISSUE THREAD

**Issue by Blacksoul16** [SkriptLang/Skript#3688]
• Add `crimson slab` and `warped slab` to the [any slab](https://github.com/SkriptLang/skript-aliases/blob/95dcc1eb0b206024576fd37a60283be0cb74734c/building.sk#L668) section.
• Add `crimson stair` and `warped stair` to the [any stair](https://github.com/SkriptLang/skript-aliases/blob/95dcc1eb0b206024576fd37a60283be0cb74734c/building.sk#L669) section.
• Add `any walls`, there is nothing that puts all the walls in the same group.
• Add `any potted plant` or something like that to make it easier to handle the plants in a pot.
• Add `polished blackstone button` to the [any button](https://github.com/SkriptLang/skript-aliases/blob/95dcc1eb0b206024576fd37a60283be0cb74734c/redstone.sk#L256) section.

**Comment by mckite** [comment]
Also add
mine_coal as just coal in mine 
 minecraft:coal {Damage:0} # Not for coal:1
