### ISSUE TITLE
%location {_loc}% return a wrong location

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#3689]
### Description
when you use `location %location%` it always return the location of player, and not %location%

### Steps to Reproduce
```applescript
command /testloc:
    trigger:
        set {_loc} to location at target block of player # or any location
        broadcast "%{_loc}%"
        broadcast "%location {_loc}%" # bug : return location of player
        broadcast "%location of player%"
```

### Expected Behavior
return location at target block

### Server Information
* **Server version/platform:** Paper-1.16.4
* **Skript version:** 2.5.3

**Comment by ShaneBeee** [comment]
I don't even think thats valid syntax, just one of those odd things Skript allows.
There is this:
```vb
(location|position) of %location%
```
http://skriptlang.github.io/Skript/expressions.html#ExprLocationOf

does that work as intended?

**Comment by ShaneBeee** [comment]
Im going to close this, as its been 12 days with no response, and the fact that you aren't using a valid syntax.
