### ISSUE TITLE
Skript Java Stack Trace

### ISSUE THREAD

**Issue by WhatsWifi** [SkriptLang/Skript#3694]
### Description
Java Stack trace when loading skript

### Steps to Reproduce
Honestly I don't remember what happened. I installed Java 15 yesterday, then started it today and it shows this error. Java 15 has been uninstalled and i still get this error.

### Expected Behavior
It's supposed to kick all players from the server with a certain message

### Errors / Screenshots
Console error: [right here](https://pastebin.com/C1vJSix3)
My Skript: [click me!](https://pastebin.com/ZdnUfTxW)
The errors appear to be happening on these 2 lines:
**_on unload:
(tab) loop all players:
(double tab) kick loop-player because "%{wmprefix}% &cPlugin has been unloaded, and you were kicked to allow proper world resetting. Sorry!"_**

### Server Information
* **Server version/platform:** Spigot 1.8.8
* **Skript version:** v2.2

### Additional Context
Yes I know that I'm using an outdated version of Skript but I'm trying to make a minigame server and 1.8 pvp is best for that kind of stuff.

**Comment by ShaneBeee** [comment]
Closing due to unsupported, severely outdated version.

We only offer support for this fork of Skript.
