### ISSUE TITLE
Cursor Slot/Item returns "0, Air" 

### ISSUE THREAD

**Issue by L3v3lup** [SkriptLang/Skript#3696]
### Description
The cursor expression is broken. If an item is clicked on, it returns "0 Air".
For some funny reason, it returns the right item, if the player is in an anvil.

### Steps to Reproduce
```
on inventory click:
	send "%cursor slot of player%"
```

### Server Information
* **Server version/platform:** PaperSpigot 1.16.4 - Build 391
* **Skript version:** 2.5.3

### Additional Context
Unfortunately Skellett & MorkazSK's cursor slot expression is broken too. Currently no way of getting the cursor slot :/
(Already removed those plugins and tried skript only)

**Comment by ShaneBeee** [comment]
Works fine for me:
<img width="966" alt="Screen Shot 2021-01-16 at 3 35 11 AM" src="https://user-images.githubusercontent.com/20008482/104810778-e650a100-57ab-11eb-895a-33998c32347d.png">
<img width="966" alt="Screen Shot 2021-01-16 at 3 35 19 AM" src="https://user-images.githubusercontent.com/20008482/104810779-e8b2fb00-57ab-11eb-8843-acddf4b24edc.png">

Please keep in mind, events are called before they actually happen. ie: when the event has been called the player hasn't clicked yet, so their cursor is not set.

If you are trying to get the item they clicked on, its `clicked item`

**Comment by L3v3lup** [comment]
Oh my god.
I just found out that it only works in survival mode. In creative, it doesnt.
Idk, is that worthy of keeping it open as a bug report? Confusing for skripters, but ultimately works..

Would'nt have found the reason without your screen, Thanks :D

**Comment by ShaneBeee** [comment]
might as well close it. The fact that it doesn't work in creative mode is not a Skript issue.
