### ISSUE TITLE
Block hardness

### ISSUE THREAD

**Issue by darealHeroBrine** [SkriptLang/Skript#3697]
Im useing skellet for block hardness andit does not change anything it keeps the orriginal hardness and when i check for the hardness level of the block it returns the value 0

**Comment by ShaneBeee** [comment]
So report that to skellett

**Comment by darealHeroBrine** [comment]
you guys are faster though

**Comment by ShaneBeee** [comment]
yes, but we can't fix skellett, its not our plugin.
This issue tracker is for OUR plugin.. Skript!

**Comment by darealHeroBrine** [comment]
i am reopening this as skellet has not responded in three days

**Comment by darealHeroBrine** [comment]
i guess i need to open a new one?

**Comment by ShaneBeee** [comment]
just because Skellett hasn't responded, doesn't mean it makes this our issue.

I repeat, this bug is with Skellett **NOT** Skript... there is absolutely nothing we can do about this.

I repeat again **This issue tracker is for OUR plugin.. Skript... NOT for other plugins.**

**Comment by Pikachu920** [comment]
if you would like, you can open a feature request however it will likely not be implemented in the near future
