### ISSUE TITLE
Inventory Move Item Event

### ISSUE THREAD

**Issue by EarthAgar** [SkriptLang/Skript#3698]
The Inventory Move Item Event should be added to vanilla Skript. Not everyone can use Reflect / Mirror or have the knowledge to effectivly use it. Another reason is because TuSke's implementation of this is no longer working and I've tested on 1.16.4.

I'm sure this is unneeded but I'll link the exact event from the SpigotAPI to eliminate and potential miscommunication:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/InventoryMoveItemEvent.html

**Comment by Pikachu920** [comment]
obviously not vanilla, but this may be of interest https://github.com/APickledWalrus/skript-gui

**Comment by EarthAgar** [comment]
> obviously not vanilla, but this may be of interest https://github.com/APickledWalrus/skript-gui

I knew it was a TuSke fork but I didn't think they carried over anything other than just the gui creation portion of the plugin.

**Comment by EarthAgar** [comment]
> > obviously not vanilla, but this may be of interest https://github.com/APickledWalrus/skript-gui
> 
> I knew it was a TuSke fork but I didn't think they carried over anything other than just the gui creation portion of the plugin.

Ok after further testing that event doesn't seem to exist in skript-gui

**Comment by EarthAgar** [comment]
To clear up everything, this event is not achievable with any addons currently.

**Comment by bnjrKemal** [comment]
It's needed.
