### ISSUE TITLE
Minecraft location locations are gone

### ISSUE THREAD

**Issue by Cream1018** [SkriptLang/Skript#3699]
### Description
I reloaded the server, and then many bugs happened. And i found out all locations are gone. I mean the skript can't find/load them.

### Steps to Reproduce
Before i reloaded the server i added a "nolagg" plugin, but i removed it when this error happened.

### Expected Behavior
Some variabels er gone

### Errors / Screenshots
Just error of any cmd if the cmd have have a location variabel

### Server Information
* **Server version/platform:** 
* **Skript version: 2.2-dev37c

**Comment by ham1255** [comment]
reload causes problem...... restart instead

**Comment by ShaneBeee** [comment]
Skript 2.2-dev37c is super outdated. 
We only offer support for the most recent version of Skript, which is 2.5.3
