### ISSUE TITLE
Bug menu

### ISSUE THREAD

**Issue by Lennord** [SkriptLang/Skript#3706]
Hello, I found a problem to correct, when I create a menu and I'm creative and I open the menu and quit the menu quickly, it gives me an error and in addition it gives me the menu items (not everything and some items).

Here I wanted to tell you the problem by hoping that it will not be complicated to correct it...

Version Spigot: 1.16.4
Version Skript: 2.5.3
List of plugins: Skript, SkQuery, Skungee, SkRayfall, SkBee and Skellett

Bug report: https://pastebin.com/UMCuatFf
Code: https://pastebin.com/SrUaGPND

**Comment by ShaneBeee** [comment]
The code you provided is SkQuery GUI code.
The error you provided is SkQuery GUI error.

This issue tracker is for Skript. Please report add-on issues to the respective add-on developer.
