### ISSUE TITLE
Damage event goes off twice

### ISSUE THREAD

**Issue by nemxo0709** [SkriptLang/Skript#3715]
### Description

When executing damage via skript with 'damage entity by x hearts', if you use the 'on damage:' event it listens the event twice. For example if I do 'on damage:' followed by 'broadcast "test"' it would broadcast "test" twice. The damage itself goes off only once.
### Expected Behavior

The message "test" should of gone off only once.
### Server Information
* **Server version/platform:** Paper version git-Paper-318
* **Skript version:** 2.5.3

**Comment by blek-id** [comment]
It is also affecting 3rd party plugin that listen to EntityDamageEvent to manipulate the final damage that skript damage is causing. Having the EntityDamageEvent ran twice means that the damage will be manipulated twice causing inaccuracies.

Some skript to test out damage
```
command /selfdmg [<number>]:
    Trigger:
        damage player by arg-1
```

![debug skript](https://user-images.githubusercontent.com/26654664/106147806-e2108480-61aa-11eb-852e-34f70fdc56f1.gif)

**Comment by TheLimeGlass** [comment]
Skript calls the event twice to check if the living entity can be damaged. This was probably because LivingEntity#damage didn't call the damage event in the past and we have to respect backwards compatibility. I have added a configuration option to disable this check in a pull request at #3719

**Comment by blek-id** [comment]
had a commment on your PR, please check @TheLimeGlass

**Comment by TheDGOfficial** [comment]
> Skript calls the event twice to check if the living entity can be damaged. This was probably because LivingEntity#damage didn't call the damage event in the past and we have to respect backwards compatibility. I have added a configuration option to disable this check in a pull request at #3719

What kind of backwards compatibility? This should be default if it doesn't cause any issues in my opinion (i.e if LivingEntity#damage calls the event and cancels the damage respectively if any plugin cancels it on supported versions of this fork). Having an event fire twice is just confusing and can cause problems easily.
