### ISSUE TITLE
[Bug?] Invulnerability ticks don't seem to be working properly

### ISSUE THREAD

**Issue by MovesLikeJaeger** [SkriptLang/Skript#3729]
# Description
Attempted to set the invulnerability ticks of a living entity to something and noticed that it hardly ever works

# Steps to Reproduce
Literally just use this code and you will notice that it only sometimes actually sets their damage delay
I was testing on a pig, maybe this has something to do with it? It still worked sometimes - although rarely - so I assume it's unrelated.

`on damage:`
` -attacker is a player`
` -set victim's invulnerability ticks to 1000`
` -wait a tick`
` -broadcast "%victim's invulnerability ticks%"`
No, I didn't use `-` in my actual code 👍 

Using the above code, here is an exact example of what happened when attacking a single pig.
No other code was present.

![image](https://user-images.githubusercontent.com/75779721/106406097-1df26500-649d-11eb-9efc-6b15d7e8c9b8.png)

No errors / Console errors.

# Server Information
Skript 2.5.3
Paper 1.16.5
No addons present.

Thanks for reading.

**Comment by ShaneBeee** [comment]
If im not mistaken, this is a Spigot/Minecraft issue. 
Even directly using Bukkit code, it results in the same way.

**Comment by MovesLikeJaeger** [comment]
Okay. I will close this then, but if anybody needs a way for this to work, I believe Skellett has a method that works (or used to -  I haven't tested it since Skript 2.4).
