### ISSUE TITLE
Log handlers

### ISSUE THREAD

**Issue by EtoNikei** [SkriptLang/Skript#3731]
### Description

Errors after reload the server.

### Steps to Reproduce

Reloading the server.

### Expected Behavior

Unknown.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/73131948/106621388-1918d880-65a5-11eb-9785-5d55c0083039.png)

### Server Information
* **Server version/platform:** PaperSpigot 1.12.2 
* **Skript version:** 2.5.3 

### Additional Context

Plugins: 
![image](https://user-images.githubusercontent.com/73131948/106621496-33eb4d00-65a5-11eb-8c1e-42cd88d7bdf8.png)
Core:
![image](https://user-images.githubusercontent.com/73131948/106621555-41083c00-65a5-11eb-8e76-1d46d34b4671.png)

**Comment by Romitou** [comment]
Try updating skript-mirror to skript-reflect. https://github.com/TPGamesNL/skript-reflect

**Comment by ShaneBeee** [comment]
As Romitou stated, please update Skript-mirror or switch to Skript reflect.
The version of Skript-mirror you are running is prone to this issue.
