### ISSUE TITLE
On Inventory Open event-inventory for double chest causes error

### ISSUE THREAD

**Issue by DrakDragon** [SkriptLang/Skript#3732]
For some reason, attempting to get the event-inventory of a double chest causes an error:
![Capture](https://user-images.githubusercontent.com/18022280/106653084-f6ae9d00-655b-11eb-82f3-9a2c10545a30.PNG)

Code to produce this error:
`on inventory open:

	wait 1 tick
	broadcast "%event-inventory%"
`

Code above against a single chest, shulker chest, and barrel all work as intended, but when used on a double chest you get the error produced above.

**Comment by ShaneBeee** [comment]
Closing due to lacking any sort of information as requested in issue template.

When creating a new issue, please do not delete the template, but actually fill it in. The template asks for information that helps us correctly triage your issue.
