### ISSUE TITLE
Querying event-inventory of a double chest results in "skript infinitely repeated itself" error

### ISSUE THREAD

**Issue by DrakDragon** [SkriptLang/Skript#3733]
### Description
Querying a double-chest for the event-inventory caused an error to return saying that the skript infinitely (or excessively) repeated itself.

### Steps to Reproduce
Open a double-chest, with the following event:
```
on inventory open:

	wait 1 tick
	broadcast "%event-inventory%"
```

### Expected Behavior
Output should have read "inventory of [facing] double chest" or similar

### Errors / Screenshots
![Capture](https://user-images.githubusercontent.com/18022280/106654369-afc1a700-655d-11eb-9cd9-a182dd6fb4b9.PNG)

### Server Information
* **Server version/platform:** PaperMC 1.16.5 (Was: PaperMC 1.16.4, updated to confirm it wasn't a version issue.)
* **Skript version:** 2.5.3 (Was: 2.5.2, updated to confirm it wasn't a version issue.)

### Additional Context
Querying the event-inventory of a single chest, barrel, or shulker box works as intended, the issue only seems to happen for double chests.

**Comment by TheDGOfficial** [comment]
Does this happen on 1.16.5 w/ 2.5.3 and when removing the wait 1 ticks
section?

**Comment by DrakDragon** [comment]
> Does this happen on 1.16.5 w/ 2.5.3 and when removing the wait 1 ticks section?
Yes, I have updated to 1.16.5 and the 2.5.3 version of Skript, still got the same error with and without the "Wait 1 Ticks"

**Comment by TPGamesNL** [comment]
Can you set `verbosity` to `debug` in `config.sk`? This'll print an error in console when that message appears, put it in a pastebin and send it.

**Comment by TPGamesNL** [comment]
Can confirm. Part of error: https://pastebin.com/XGUWPZnv

**Comment by TheLimeGlass** [comment]
Has this error with this script for more testing purposes. This one being related to indices and changing loop-item to a variable index name.
```vb
on rightclick:
	clicked block is a chest
	# Chest must contain items
	add all armour to event-inventory
	loop items in event-inventory:
		set {_crash::%loop-item%} to true
```

**Comment by TheLimeGlass** [comment]
Can confirm pull request #3822 also fixes this.
