### ISSUE TITLE
Problem with checking if event-slot is air

### ISSUE THREAD

**Issue by ExtraSmartMiner** [SkriptLang/Skript#3735]
I get an error in the console for checking if the event-slot is air

on inventory click:
	event-slot is not air

        or

on inventory click:
	"%event-slot%" is not "air"

There should not be an error but there is

![errrror](https://user-images.githubusercontent.com/70736085/106909207-aa7f6c00-66c5-11eb-8d3e-c3a94316b4e7.PNG)

 Skript version 2.5.3
Minecraft: 1.16.5

**Comment by TheDGOfficial** [comment]
Please attach the full error including the stacktrace. The bottom lines in
the exception only give information about the envrionment. The real error
should be on the top.

**Comment by TPGamesNL** [comment]
Closing due to lack of response, and me not being able to replicate it.
