### ISSUE TITLE
Feature: Open/close doors

### ISSUE THREAD

**Issue by Wafffidooe** [SkriptLang/Skript#3738]
A feature like this could be cool:

Effect:
<Close | open> all <doors | trapdoors | fencedoors> (in region "regionname" | in world "worldname")

Condition:
If all <doors | trapdoors | fencedoors> (in region "regionname" | in world "worldname") are <closed | opened>

**Comment by bilektugrul** [comment]
You can use toggle effect.
https://skriptlang.github.io/Skript/effects.html#EffToggle
Also, that condition probably can be work with checking block state. There is no require to a new condition.

**Comment by TPGamesNL** [comment]
Closing as the suggestions are just simplifications of what's already doable, and not useful simplifications either.
