### ISSUE TITLE
Right click event sometimes doesn't fire if the player spams right click on the same block

### ISSUE THREAD

**Issue by SlickNicky10** [SkriptLang/Skript#3739]
### Description
Attempting to use Skript to disable right clicking on some types of blocks (barrels, beacons, trapdoors etc), but if the player simply spams right click it will eventually go through. I tried broadcasting "%block%" on any right click event (just "on right click:"), and it appears that the event itself never even gets called in Skript for the one time it goes through. It's not client-side only, as subsequent calls to the event recognize the changed block (example trap door -> open trap door)

## Code:
```vb
on right click:
    if block is barrel or trapdoor:
        cancel event
    broadcast "%block%"
```

## In-Game:
Literally just spam right click until the trapdoor eventually opens, or the barrel GUI opens.

### Expected Behavior
The barrel/trapdoor should stay closed.

### Errors / Screenshots
https://gyazo.com/90f94bfb995eafda2e38abac1233967a

### Server Information
* **Server version/platform:** git-Paper-"b89788a" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* **Skript version:** 2.5.3-MH

### Additional Context
Yes, this is Minehut's fork of Skript, this is a Minehut server. Minehut's fork of Skript doesn't touch this event, it makes changes to things such as the /sk disable command to remove the ability to use "../" in file names.

**Comment by lafayettes** [comment]
Unfortunately due to the fact that it is the Minehut Fork, Addon Developers and the Main Skript developers most likely won't be touching these due to the fact its minehut.

**Comment by Romitou** [comment]
The version of Minehut is a modified version of Skript, so the SkriptLang team does not manage its problems. The best solution is to address your problems directly to Minehut or to try to reproduce the issue on a local server with the version of SkriptLang.

**Comment by SlickNicky10** [comment]
> 
> 
> The version of Minehut is a modified version of Skript, so the SkriptLang team does not manage its problems. The best solution is to address your problems directly to Minehut or to try to reproduce the issue on a local server with the version of SkriptLang.

This issue has nothing to do with Minehut.

**Comment by Romitou** [comment]
Very good. You should then be able to reproduce this problem with the version of this repository.

**Comment by TPGamesNL** [comment]
We don't support forks. Feel free to test on an official version from us, and reopen this issue or create a new one.
