### ISSUE TITLE
Non-Alphanumeric Username causing TPS to drop very badly

### ISSUE THREAD

**Issue by not-3than** [SkriptLang/Skript#3742]
### Description

When Skript tries to get the UUID of an Offline player with a weird symbol, it causes an error, and if a player spams that command, such as `/stats ✴acbsuq14☆`, it makes the TPS drop super badly.

### Steps to Reproduce

It's some kind of hacked client glitch, not sure which one. Whenever I try to spam the command, it doesn't happen. But one particular person keeps using a VPN to join with alts and spam different variations of that command.

### Expected Behavior

It shouldn't cause the TPS to drop exponentially.

### Errors / Screenshots

https://pastebin.com/HQPZzWmN

http://prntscr.com/yolhpw

### Server Information
* **Server version/platform:** git-Paper-"b89788a" MC 1.16.5 (Minehut)
* **Skript version:** 2.5.3-MH (Minehut's custom fork of Skript)

**Comment by TheDGOfficial** [comment]
Custom Skript forks are not supported here as far as I know, so even if it
is an upstream issue, you should either reproduce it on official version or
report to the fork’s maintainer instead.

Don’t know what causes the issue, but you can try adding cooldown to
command, parse the player yourself or as you said prevent VPN/alts.

Also, is this happening just with the stats command or all commands? It can
be code on your trigger, too.

**Comment by WeeskyBDW** [comment]
Minecraft protocol dont block usernames with symbols ? Or non-alphanetic usernames

**Comment by TPGamesNL** [comment]
It only allows [`a-zA-Z0-9_`](https://wiki.vg/Mojang_API#Response_6), but Skript uses the regex `\S+` (and a length check), which allows for way more characters: https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/classes/data/BukkitClasses.java#L853
