### ISSUE TITLE
Missing getHitEntity() in "on projectile hit" event

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#3746]
### Description

`on projectile hit` event should have `event-entity` or `hit entity` to get the hit entity, it is available in spigot but not found/working in Skript.

The issue here is that when using fishing rod on players there is no damage so `on damage` event won't even fire and `on projectile hit` doesn't have `hit entity` so there is no way to check for that.

### Steps to Reproduce

No steps.
### Expected Behavior

None.
### Server Information
* **Server version/platform:**   Paper 1.16.5-R0.1-Snapshot "b89788a"
* **Skript version:**  Skript 2.5.3

**Comment by Pikachu920** [comment]
it would probably make sense to add this to the victim expression
