### ISSUE TITLE
TusKe error

### ISSUE THREAD

**Issue by makk87** [SkriptLang/Skript#3747]
When I start my server, the console shows me this error message: https://dpaste.org/Zqbv
I tried to check skript's website about this, but I don't now how to fix that.

Version Information:
   Skript: 2.5.3 (latest)
   Flavor: skriptlang-github
   Date: 2020-12-11
   Bukkit: 1.16.4-R0.1-SNAPSHOT
   Minecraft: 1.16.4
   Java: 11.0.9.1 (OpenJDK 64-Bit Server VM 11.0.9.1+1)
   OS: Linux amd64 4.15.0-135-generic
   Server platform: Paper

**Comment by Romitou** [comment]
Please report your issue to TuSKe directly.
By the way, I recommend that you use skript-gui instead of TuSKe for the GUIs, as it is no longer maintained.

**Comment by makk87** [comment]
Can you link skript-gui to download?

**Comment by Romitou** [comment]
https://github.com/APickledWalrus/skript-gui

**Comment by makk87** [comment]
Thanks, and now I create GUI menus without TuSKe?

**Comment by Romitou** [comment]
Yes, you can now use skript-gui for your GUIs.

**Comment by makk87** [comment]
Okey, but where do I upload this? Into the skript folder?

**Comment by ShaneBeee** [comment]
Closing as this is not a Skript issue
