### ISSUE TITLE
on can build check event doesn't have player?

### ISSUE THREAD

**Issue by nshun1896** [SkriptLang/Skript#375]
The script below returns <none>.
Is it impossible to detect who is trying to build?

```
on can build check:
   message "%player%"
```

**Comment by TheBentoBox** [comment]
Confirmed, doesn't work for me either. (1.11.2 dev23).

**Comment by bensku** [comment]
The underlying Spigot/Bukkit event does not contain any player information.

**Comment by nshun1896** [comment]
OK.　Thank you for your quick response!

**Comment by ShaneBeee** [comment]
The event now (in 1.13) has a `getPlayer()` method, so I have done a PR for this

**Comment by TheBentoBox** [comment]
This was added in [this PR](https://github.com/SkriptLang/Skript/pull/1935).
