### ISSUE TITLE
Incompatible with Comodore

### ISSUE THREAD

**Issue by networkException** [SkriptLang/Skript#3750]
### Description
I'm using https://github.com/lucko/commodore for one of my plugins, but since using Skript I noticed autocomplete not working anymore. To be precise it falls back to suggesting playernames.

### Steps to Reproduce
- Use comodore to register tab completion using Mojang's Bridagier command builder
- Register a command listener in a script

### Expected Behavior
The autocompletion of the comodore command should work

### Errors / Screenshots
n/a

### Server Information
* **Server version/platform:** Minecraft 1.16.5 (Paper 468)
* **Skript version:** 2.5

### Additional Context
n/a

**Comment by TPGamesNL** [comment]
Do you still have this issue? It's been a while
