### ISSUE TITLE
There's no loop that matches 'loop-player'

### ISSUE THREAD

**Issue by RazerStorm** [SkriptLang/Skript#3751]
Hey, i am trying to make a skript that pushes a player when they toggled the option. My problem is that i get this error:

![image](https://user-images.githubusercontent.com/76501059/107859164-e211b500-6e37-11eb-99ea-12a319491812.png)

```
every 1 seconds in "world":
	loop all players:
		if {spawn.%loop-player%} is true:
			push loop-player south at speed 2

command /pushme:
	trigger:
		if {spawn.%loop-player%} is true:
			set {spawn.%loop-player%} to false

		else if {spawn.%loop-player%} is false:
			set {spawn.%loop-player%} to true

on join:
	set {spawn.%loop-player%} to false

```

**Comment by ShaneBeee** [comment]
Closing due to lack of information, and not filling in the provided template.

**Comment by RazerStorm** [comment]
> Closing due to lack of information, and not filling in the provided template.

I dont saw a template

**Comment by ShaneBeee** [comment]
It's quite hard to miss 

<img width="1533" alt="Screen Shot 2021-02-13 at 11 48 09 AM" src="https://user-images.githubusercontent.com/20008482/107859911-74db3100-6df1-11eb-9ae4-2e372b1e8913.png">
<img width="1533" alt="Screen Shot 2021-02-13 at 11 48 19 AM" src="https://user-images.githubusercontent.com/20008482/107859916-77d62180-6df1-11eb-9593-4138da818095.png">
<img width="1533" alt="Screen Shot 2021-02-13 at 11 48 30 AM" src="https://user-images.githubusercontent.com/20008482/107859918-79074e80-6df1-11eb-8f59-5681da8e4d76.png">

**Comment by RazerStorm** [comment]
> It's quite hard to miss
> (uploading pics)

What pics?

**Comment by RazerStorm** [comment]
> It's quite hard to miss
> 
> <img alt="Screen Shot 2021-02-13 at 11 49 52 AM" width="1533" src="https://user-images.githubusercontent.com/20008482/107859951-aeac3780-6df1-11eb-8d14-63e17a056407.png">
> 
> <img alt="Screen Shot 2021-02-13 at 11 50 03 AM" width="1533" src="https://user-images.githubusercontent.com/20008482/107859953-b1a72800-6df1-11eb-9b3b-d0241bab80e0.png">
> 
> <img alt="Screen Shot 2021-02-13 at 11 50 12 AM" width="1533" src="https://user-images.githubusercontent.com/20008482/107859954-b23fbe80-6df1-11eb-9b6a-22c7e579048f.png">

but it isnt a bugg?

**Comment by ShaneBeee** [comment]
> but it isnt a bugg?

Then why are you posting this on our issue tracker?
This issue tracker is for bug reports and suggestions, not a place for getting help with your scripts.

**Comment by RazerStorm** [comment]
> > but it isnt a bugg?
> 
> Then why are you posting this on our issue tracker?
> This issue tracker is for bug reports and suggestions, not a place for getting help with your scripts.

Because i saw a other dude doing it and this is my first time on this forum and i just needed help
