### ISSUE TITLE
Clear Drops

### ISSUE THREAD

**Issue by ExtraSmartMiner** [SkriptLang/Skript#3754]
If you try to clear drops from block with a gui it will not clear the items from it

fill a chest will items then make
on block break:
    clear drops

And if break the chest it will still drop its items.

It should clear the items but it dose not.

Version: 2.5.3

**Comment by kill05** [comment]
items into a chest don't count as drops of the broken block, you need to empty the chest and then clear drops

**Comment by TPGamesNL** [comment]
I cannot confirm this. Which exact server version are you on?

**Comment by TPGamesNL** [comment]
Closing due to lack of response
