### ISSUE TITLE
"send", "message" etc. not working

### ISSUE THREAD

**Issue by sajmonn1** [SkriptLang/Skript#3756]
### Description
Hi, I added a skript plugin to my minecraft server and added some scripts I found on the internet. After the /sk reload all, everything works as it should, however, It's not displaying messages that should be sent ONLY to the player. I mean - if I use "broadcast", it displays the message without any problem (but as we know, this will show the message to all players so I cannot use it), but when I use "send", "message" etc, nothing happens. Everything that is supposed to happen from the script happens, but no matter how I try to change the code the message won't display to player. 
In the game everything happens from the code (e.g. in the script below It suppose to get a head to the player's inventory and after it's done It should send to the player a message whose head the player got - player gets the head to the inventory, but there is still no message.

### Steps to Reproduce
I added a script with this code:
```command /głowa [<offlineplayer>] [<text>]:
    aliases: /skull, glowa
    executable by: player
    trigger:
        if arg 1 is not set:
            set {_p} to player
        else:
            set {_p} to arg 1
        give {_p}'s head to player
        send "§a§lOtrzymałeś głowę gracza §c%{_p}%§7!" to player
```
So as I said I has tried changing "send "" to player" in the code to just "send", to "send "" to loop-player", "message", "message "" to player" and many more similar, but it didn't change anything....

### Errors / Screenshots
Unfortunately the plugin does not display any error information, it looks like it just doesn't see any problem.
![sk](https://user-images.githubusercontent.com/79197514/108193280-913edc80-7115-11eb-994b-9089623b1aad.PNG)

### Server Information
* **Server version/platform:** [11:50:48 INFO]: This server is running Paper version git-Paper-384 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[11:50:48 INFO]: Checking version, please wait...
[11:50:49 INFO]: You are 7 version(s) behind
* **Skript version:** 2.5.3

**Comment by TPGamesNL** [comment]
Do you have any console errors?

**Comment by sajmonn1** [comment]
> Do you have any console errors?

Yes, now I see that when I use the command, in the console it shows this:
https://pastebin.com/s8ebjVp1

**Comment by DarkryCZ** [comment]
> > Do you have any console errors?
> 
> Yes, now I see that when I use the command, in the console it shows this:
> https://pastebin.com/s8ebjVp1

If what you sent was full code, I don't think it is even supposed to work.
try this:

`command /test:
    permission: test
    trigger:
        message "Test message" to player
        
If it doesn't work for your, then there is somehting weird ith your Skript. If it does, then your code is crappy.

**Comment by sajmonn1** [comment]
> > > Do you have any console errors?
> > 
> > 
> > Yes, now I see that when I use the command, in the console it shows this:
> > https://pastebin.com/s8ebjVp1
> 
> If what you sent was full code, I don't think it is even supposed to work.
> try this:
> 
> [https://pastebin.com/irNCp7P4](url)
> 
> If it doesn't work for your, then there is somehting weird ith your Skript. If it does, then your code is crappy.

Unfortunately still no message, and in the console as far as I can see something very similar (if not the same) to the previous one :/
Console errors: https://pastebin.com/VdvCGu4R

**Comment by TheDGOfficial** [comment]
Does this happen without LuckPerms and ProtocolLib? They are on the stack
traces in the errors you sent. It looks like there is nothing in the error
message about Skript. It is only triggering it.

**Comment by sajmonn1** [comment]
> Does this happen without LuckPerms and ProtocolLib? They are on the stack traces in the errors you sent. It looks like there is nothing in the error message about Skript. It is only triggering it.

I tried to remove first ProtocolLib, then LuckPerms, but after removing both of these plugins the problem still occurs, but from what I noticed the errors in the console have shortened by 10 lines, so this is what popped up for me now: https://pastebin.com/78GDh5LU
By the way, since the problem is not directly in the Skript, I also upload a list of uploaded plugins, maybe this will help in some way: 
Plugins (16): ColoredSigns*, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, GadgetsMenu, LoginSecurity*, MarriageMaster, PlotSquared, SkinsRestorer, SkQuery, Skript, Vault, Vehicles, WorldEdit, WorldEditCrashFix*

**Comment by TPGamesNL** [comment]
> I tried to remove first ProtocolLib, then LuckPerms, but after removing both of these plugins the problem still occurs, but from what I noticed the errors in the console have shortened by 10 lines, so this is what popped up for me now: https://pastebin.com/78GDh5LU

That error still contains traces of LuckPerms:
> [12:10:20 WARN]: at **me.lucko.luckperms**.lib.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:54)
Btw, which version of LuckPerms were you using?
Can you also check if you get the same error when you remove all colour codes and formatting from the message?

**Comment by sajmonn1** [comment]
> > I tried to remove first ProtocolLib, then LuckPerms, but after removing both of these plugins the problem still occurs, but from what I noticed the errors in the console have shortened by 10 lines, so this is what popped up for me now: https://pastebin.com/78GDh5LU
> 
> That error still contains traces of LuckPerms:
> 
> > [12:10:20 WARN]: at **me.lucko.luckperms**.lib.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:54)
> 
> Btw, which version of LuckPerms were you using?
> Can you also check if you get the same error when you remove all colour codes and formatting from the message?

Thanks a lot - my mistake was that after deleting LuckPerms instead of resetting the server I just typed /reload in game, so all the files didn't delete as they should have. After the restart the messages started appearing normally, those without colour and with. So my problem is solved, the problem was LuckPerms. Once again thank you very much for your help! I guess the issue can be closed now 😃

Oh, and just for others who might have a similar problem in the future, I will say that it was version LuckPerms v5.2.107, I will now look for an alternative for this.

**Comment by sajmonn1** [comment]
> > > I tried to remove first ProtocolLib, then LuckPerms, but after removing both of these plugins the problem still occurs, but from what I noticed the errors in the console have shortened by 10 lines, so this is what popped up for me now: https://pastebin.com/78GDh5LU
> > 
> > 
> > That error still contains traces of LuckPerms:
> > > [12:10:20 WARN]: at **me.lucko.luckperms**.lib.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:54)
> > 
> > 
> > Btw, which version of LuckPerms were you using?
> > Can you also check if you get the same error when you remove all colour codes and formatting from the message?
> 
> Thanks a lot - my mistake was that after deleting LuckPerms instead of resetting the server I just typed /reload in game, so all the files didn't delete as they should have. After the restart the messages from scripts started appearing normally, those without colour and with. So my problem is solved, the problem was LuckPerms. Once again thank you very much for your help! I guess the issue can be closed now 😃
> 
> Oh, and just for others who might have a similar problem in the future, I will say that it was version LuckPerms v5.2.107, I will now look for an alternative for this.

**Comment by TheDGOfficial** [comment]
> instead of resetting the server I just typed /reload in game, so all the files didn't delete as they should have.

Reloading is always a bad idea. Do not reload the server, and do not use plugins like PlugMan. You can reload scripts however, that is fine, but I do not recommend that either. Use test servers when writing scripts and on production, you should not need to reload it anyway.

Learning to read Java error stack traces is very helpful in solving these types of errors yourself or getting a quick idea what it is about. Or you can just check the error message trying to find a plugin name.
