### ISSUE TITLE
Unable to install plugin.

### ISSUE THREAD

**Issue by krlyx2** [SkriptLang/Skript#3757]
Hello! I was trying to install Skript to put onto my Minecraft server but the plugin will not register that it is actually there. All of the files that I need to change the code, and other things are there. But when I run /plugins it does not show. I've reinstalled Skript, restarted my server, and other things. Does anyone know how to fix this?

**Comment by kill05** [comment]
in case you are using 1.8, notice skript is not compatible. You can find a fork but it doesn't 100% work

**Comment by krlyx2** [comment]
I am trying to use 1.16.4

**Comment by TheDGOfficial** [comment]
Though 1.16.4 should work, readme clearly states that only the latest
Minecraft revision is supported.

Also, deleting the issue template doesn’t help. You’ve deleted it and
didn’t even provide anything useful like an error message.

Ensure you are using Spigot/Paper 1.16.5 latest build and Skript 2.5.3 from
official sources.
