### ISSUE TITLE
At %time% event problem

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#3758]
Im using this code:
at 7:00 in "world":
broadcast "S"

It only execute once. After I set night and set 7am again it wont broadcast anymore....

There's no error. 
Im using paper 1.16.5
Skript version 2.5.3

**Comment by TPGamesNL** [comment]
I cannot replicate. Have you tried setting the time to something just before 7:00?

**Comment by TPGamesNL** [comment]
Closing due to lack of response
