### ISSUE TITLE
cursor slot

### ISSUE THREAD

**Issue by ExtraSmartMiner** [SkriptLang/Skript#3760]
I can not check what is in the cursor slot

on inventory click:
    message "%cursor slot of player%"
    remove 1 of player's cursor slot from player's cursor slot

It sees the cursor slot as 0 air

There are 0 errors

2.5.3

**Comment by TPGamesNL** [comment]
Try waiting a tick before using the cursor slot

**Comment by Kormic1** [comment]
Instead of removing it, try to set to it, but decreased by 1.

`set player's cursor slot to (item amount of player's cursor slot - 1) of player's cursor slot`

That should do the trick. Make sure that you have any item in cursor slot while clicking on any inventory slot.

**Comment by ExtraSmartMiner** [comment]
I am on 1.16.5 any anything to do with the cursor slot is not working. Do you think it could be a plugin

**Comment by TPGamesNL** [comment]
I cannot confirm this, cursor slot seems to be working as expected for me. Try this code:
```
on inventory click:
	message "&aCursor slot [1]: %cursor slot of player%"
	wait 1 tick
	message "&cCursor slot [2]: %cursor slot of player%"
```

**Comment by kill05** [comment]
Can confirm this is not an issue, i've used it recently and works as expected, ie how TPGamesNL said it does above.

**Comment by TPGamesNL** [comment]
Closing due to lack of response
