### ISSUE TITLE
Add && 

### ISSUE THREAD

**Issue by LukasmanMHdude** [SkriptLang/Skript#3769]
In java, you can do && to combine checks and stuff. I think it would be cool if you could do smth like
```vb
command /help:
	trigger:
		if player's name is "quick_" && {var} is set:
			make player execute command "/quest"
```

**Comment by AyhamAl-Ali** [comment]
That would be great also add `||` as an or operator

**Comment by TPGamesNL** [comment]
I'm closing this in favour of #2207, since that issue also discusses the syntax for boolean operations
