### ISSUE TITLE
Using arguments when trying to clear a node doesn't work.

### ISSUE THREAD

**Issue by HW2955** [SkriptLang/Skript#3775]
### Description

When trying to use anything other than actual node ex. {Cool::Node::%player%::Health} skript doesn't know what to do and throws an error:
**Can't understand this condition/effect: clear %arg 1% (skript.sk line xx: clear %arg 1%)**
### Steps to Reproduce

Use any argument instead of node.
### Expected Behavior

If path is valid/or even not, skript should try to find node from the argument.
### Errors / Screenshots

Explanation should be enough

### Server Information
* **Server version/platform:**  git-paper-1618
* **Skript version:**  2.5.3
in addition to that i use Skellet 1.9.11, SkQuery 4.14, Skript-mirror 0.19.1, but i don't think these have anything to do with that.

**Comment by Romitou** [comment]
I didn't understand where the problem was, because you can't do that. Do you mean `clear arg-1` instead? If  not, can you attach an example script so that we can reproduce it?

**Comment by HW2955** [comment]
[clearnode.txt](https://github.com/SkriptLang/Skript/files/6048449/clearnode.txt)
as i explained in the file, adding "-" doesn't work aswell.

**Comment by Romitou** [comment]
If I understood correctly, you want to delete a variable by its name, right? If so, you will have to do the following: `clear {%arg 1%}`

**Comment by HW2955** [comment]
Well, clearly my fault not understanding skript.
