### ISSUE TITLE
Vectors are passed by references

### ISSUE THREAD

**Issue by LoganLilypad** [SkriptLang/Skript#3779]
### Description
Vectors use referencing instead of making a carbon copy, so if you set A to a vector, then set B to A and then adjust B, A ends up having the same value as B

### Steps to Reproduce
Using this sample code or similar highlights the issue, B being set to A, but when B is changed, A changes too
```
set {_a} to vector(1, 2, 3)

send "A: %{_a}%"

set {_b} to {_a}

send "B: %{_b}%"

set vector length of {_b} to 2

send "B2: %{_b}%"

send "A2: %{_a}%"
```

### Expected Behavior
When B is changed, A should stay the same as it's not the one that's being directly changed

### Errors / Screenshots
No errors

### Server Information
* **Server version/platform:** Paper Spigot 1.16.5
* **Skript version:** 2.5.3

### Additional Context
I'm pretty sure its related to https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/lang/Variable.java#L49 as I heard there was a similar issue with locations

**Comment by FranKusmiruk** [comment]
well, as for vectors it goes, I couldn't think of a case where passing them by reference could benefit its usage nor some of the team members when the question was brought up in a discussion. I think we can safely mark this as unintended behaviour unless someone else can prove otherwise.


 

> I think the most important thing here is whether Skript should use pass by reference or pass by value (either via function arguments or the change effect). The current behaviour is inconsistent:
> 
> * Locations: value
> * Vectors, items, etc: reference
> * List variables: value

Items are not passed by reference, only slots are since that's their sole purpose as a type, or am I missing something?

**Comment by TPGamesNL** [comment]
Example for items:
```
function doStuff(item: object):
	set name of {_item} to "New name"

command /funky:
	trigger:
		set {_item} to stone named "Test"
		broadcast "[1] name: %name of {_item}%"
		doStuff({_item})
		broadcast "[2] name: %name of {_item}%"
```

result:
![image](https://user-images.githubusercontent.com/29547183/110651417-b75b1800-81bb-11eb-847c-28a0eda45694.png)
