### ISSUE TITLE
Server overloads when loading/reloading a skript.

### ISSUE THREAD

**Issue by GiftShower** [SkriptLang/Skript#3780]
### Description

Server overloads while loading a script. Without the script it works fine. Only overload at startup, thread dump on script reload.

### Steps to Reproduce

I don't really know because I made the code as short as possible. no infinite loop, but maybe parsing text 1 as integer might be causig this.

### Expected Behavior
[https://pastebin.com/534xn1mm](url)

### Server Information
* **Server version/platform:** git-purpur-993 (mc 1.16.5)
* **Skript version:** Skript version2.5.3

### Additional Context

Using SkBee and Skellett.
removed SkQuery, SkDragon and SkRayFall because i'm not using it anymore. using sql to save variables.

**Comment by Romitou** [comment]
Can you attach an example script so that we can reproduce your issue?

**Comment by GiftShower** [comment]
here. i just put the full code here
[https://pastebin.com/DfbJ8V7u](url)

**Comment by TPGamesNL** [comment]
I cannot replicate. Issues like these can be solved by:
- not making complex lines in your scripts
- not making too long scripts
- not reloading all scripts at once
- enabling asynchronous loading (which might break things)
