### ISSUE TITLE
Teleporting player sets their yaw & pitch to 0

### ISSUE THREAD

**Issue by SmiesznyCzlowiek** [SkriptLang/Skript#3781]
### Description

When teleporting a player it resets their pitch and yaw
### Steps to Reproduce

for an example doing
**set {Location} to location({@TeleportX}, {@TeleportY}, {@TeleportZ}, player's world, player's yaw, player's pitch)**
**teleport player to {Location}** will work, but when doing
**teleport player to {@TeleportX}, {@TeleportY}, {@TeleportZ}, player's world, player's yaw, player's pitch** or anything of that nature doesn't, not a big issue but still annoying.
### Expected Behavior

we should be able to teleport a player and set their pitch and yaw without declaring a variable.
### Server Information
* **Server version/platform:**  paper 1618
* **Skript version:** 
2.5.3

**Comment by FranKusmiruk** [comment]
can someone confirm this?

**Comment by TPGamesNL** [comment]
I cannot confirm, since the second code doesn't parse. If you make it use a location function (`teleport player to location({@x}, {@y}, {@z}, player's world, player's yaw, player's pitch)`), it works (keeps the same pitch/yaw as player)

**Comment by FranKusmiruk** [comment]
Closing as it is most likely a user error.
