### ISSUE TITLE
EffectDrop will make an exception when it triggered by death event

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/Skript#3782]
### Description

It can't drop a item from variables when triggered by death event

### Steps to Reproduce

on some event:
⁠    set {TestItem} to tool of player  #tool is not air

on death of player:
⁠    drop 1 of {TestItem} at player

### Expected Behavior

Drop a item

### Errors / Screenshots

https://paste.ubuntu.com/p/jMCDtw9fGP/

### Server Information
* **Server version/platform:** 
* Paper 1.12.2
* **Skript version:** 
* Both 2.4.1 and 2.5.3 happened

### Additional Context

No

**Comment by TPGamesNL** [comment]
Will be fixed when https://github.com/SkriptLang/Skript/pull/3774 is merged
