### ISSUE TITLE
Database Error Message contains broken link

### ISSUE THREAD

**Issue by Dancull47** [SkriptLang/Skript#3785]
### Description

Database Error Message contains broken link.
### Steps to Reproduce

Enable MySQL in Config file without having SQLibrary.
### Expected Behavior

It should point to `https://dev.bukkit.org/projects/sqlibrary` instead of `http://dev.bukkit.org/server-mods/sqlibrary/files/`
### Errors / Screenshots

[00:48:06] [Server thread/ERROR]: #!#! You need the plugin SQLibrary in order to use a database with Skript. You can download the latest version from http://dev.bukkit.org/server-mods/sqlibrary/files/

### Server Information
* **Server version/platform:** 1.16.5 
* **Skript version:** 2.5.3

**Comment by TheDGOfficial** [comment]
This fixed by #3714 already and will be in the next release.
