### ISSUE TITLE
uncolored %string% is removing all <>

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#3787]
### Description

Uncoloring messages containing `<` or `>` will remove any and all `<` and `>` which shouldn't remove all/any, it should only remove those who are used for coloring or styling

### Steps to Reproduce

`send uncolored "<< >> > <"` # will print empty message

### Expected Behavior

Print `<< >> > <`

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/20037329/110139601-e64c4500-7ddb-11eb-81c2-b32dbb5d1215.png)

### Server Information
* **Server version/platform:** 
* **Skript version:** 
* Tested with Skript 2.5.3 and 2.5.1 on paper 1.16.3
EDIT: paper 1.16.5 as well

**Comment by TheDGOfficial** [comment]
Does this started after hex color support or it is already like that before
too?

**Comment by APickledWalrus** [comment]
From this line: https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/util/chat/ChatMessages.java#L512

Could be fixed just by checking if the tag is actually valid. Ideally this whole system could be overhauled at some point (see #3112).

As a temporary workaround, you could try manually removing color codes through EffReplace.

**Comment by AyhamAl-Ali** [comment]
> From this line:
> 
> https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/util/chat/ChatMessages.java#L512
> 
> Could be fixed just by checking if the tag is actually valid. Ideally this whole system could be overhauled at some point (see #3112).
> 
> As a temporary workaround, you could try manually removing color codes through EffReplace.

I have already made a workaround by replacing all `<` and `>` with a specific pattern of characters then do the uncoolor effect then replace all the patterns back to `<` and `>`





> Does this started after hex color support or it is already like that before too?

Not sure about that, I jumped from dev36 to Skript 2.5.3 sometime ago, I haven't checked older versions but as APickledWalrus stated above, it should check if tag is valid and not just remove any tag.

**Comment by TheDGOfficial** [comment]
> Not sure about that, I jumped from dev36 to Skript 2.5.3 sometime ago, I haven't checked older versions but as APickledWalrus stated above, it should check if tag is valid and not just remove any tag.

So this was not an issue on dev36? Just checked and can't find a line like that on dev36 tag. Can be fixed like explained above, just removing the tag when it is valid would be enough, not sure about the mentioned "parser bugs" in the comment, though, that code section can probably be removed completely.

https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/util/chat/ChatMessages.java#L509

**Comment by AyhamAl-Ali** [comment]
> > Not sure about that, I jumped from dev36 to Skript 2.5.3 sometime ago, I haven't checked older versions but as APickledWalrus stated above, it should check if tag is valid and not just remove any tag.
> 
> So this was not an issue on dev36? Just checked and can't find a line like that on dev36 tag. Can be fixed like explained above, just removing the tag when it is valid would be enough, not sure about the mentioned "parser bugs" in the comment, though, that code section can probably be removed completely.
> 
> https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/util/chat/ChatMessages.java#L509

Yes I don't remember I had such issue before with `2.2-dev36`.

Also, that line is not supposed to be there in that way, it removes all these characters without checking if that character it doing its thing to avoid it for example here is another issue with it
![image](https://user-images.githubusercontent.com/20037329/110236716-0e54b900-7f40-11eb-8d91-070e83bde764.png)
It just removes any `&` character as well.
