### ISSUE TITLE
add on leave

### ISSUE THREAD

**Issue by quick007** [SkriptLang/Skript#3789]
According to the parser at least, `on leave:` isn't an event. I think it would be nice to add this as another of using `on disconnect:`.

**Comment by TheDGOfficial** [comment]
Simple to add, you can open a PR or I can look when I have time. Might be
the case for region enter/exit too (region leave), can’t check the source
rn, will look.

**Comment by APickledWalrus** [comment]
Wouldn't hurt to have. Here is the registration line for this event: https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/events/SimpleEvents.java#L310

**Comment by LukasmanMHdude** [comment]
> Simple to add, you can open a PR or I can look when I have time. Might be

checked the docs actually, `on leave:` seems to be unused
