### ISSUE TITLE
Calling functions with a player parameter with the effect commands doesnt work

### ISSUE THREAD

**Issue by 5mmx** [SkriptLang/Skript#3790]
### Description
Calling a function that has a player or offline player as any argument with an effect command (for clarity, effect commands are those that start with !. For example !send "test", they work like normal minecraft commands but with ! Instead of /), even if the player is specified it will not work, saying that the player argument has not been given/is incorrect.

### Steps to Reproduce
1) Enable effect commands in skript config
2) Create a skript and type:

`function test(player: player):
    send "Test!" to {_player}`

3) Run the effect command `!test(<your minecraft username>)`

### Expected Behavior
It should send "Test!" to the specified player

### Server Information
* **Server version/platform:** Paper 1.16 Build 524
* **Skript version:** 2.5.3

### Additional Context
Not a big deal, but would be cool if this could be fixed

**Comment by TheDGOfficial** [comment]
Just entering the player name? You have to use special “me” (which is
specific to effect commands) or “playername” parsed as player as far as I
remember.

**Comment by APickledWalrus** [comment]
This seems to just be user error, like pointed out above. You would need to do something like `!test(player)` (for the executor) instead of putting in a raw name.
