### ISSUE TITLE
Event-Value event-item in Pickup Event has some problem

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/Skript#3792]
### Description

Used expression "amount of event-item" in pickup event, Skript will cast event-item to a Skript Array

### Steps to Reproduce

on pick up:
    send "%amount of event-item%" to player

### Expected Behavior

Send amount of the item stack to player

### Errors / Screenshots

https://paste.ubuntu.com/p/kFJWT649vG/
]

### Server Information
* **Server version/platform:** 
* Paper 1.12
* **Skript version:** 
Skript 2.5.3

### Additional Context

I think "amount of event-item" should return event.getItem().getItemStack().getAmount()

**Comment by TPGamesNL** [comment]
That expression is for lists, use this instead: https://skriptlang.github.io/Skript/expressions.html#ExprItemAmount

**Comment by zimzaza4** [comment]
umm...

**Comment by zimzaza4** [comment]
on pick up:
set {_item} to event-item

Can not operate

**Comment by zimzaza4** [comment]
But if you use the on inventory click event, there is no problem
