### ISSUE TITLE
Skript doesn't working as it should

### ISSUE THREAD

**Issue by AndusDEV** [SkriptLang/Skript#3793]
### Description
Skript is loading scripts but not triggers (Loaded 3 scripts with total 0 triggers and 7 commands in 0,56 seconds). One of the scripts was previously (before reset) on server and it was working perfectly. After reset when i added skript back it wasn't working. I removed all plugins and left only skript but it still didn't worked as it should. The commands are working but when they should show some messages they just not showing up. For example: /gmc - changes gamemode to creative but not showing up the message "Changed gamemode to creative".

### Steps to Reproduce
I don't really know i just installed skript and it wasn't working since then

### Expected Behavior
Good question

### Errors / Screenshots

https://imgur.com/a/859R9rg

https://pastebin.pl/view/6b75b55b

### Server Information
* **Server version/platform:** Paper-1.16.4/Linux(4.15.0-76-generic)/Java 11/
* **Skript version:** 2.5.3

**Comment by AyhamAl-Ali** [comment]
Did you recently (after server reset) updated Java or server version or Skript?
Could you share your code of command `/eventy`

**Comment by AndusDEV** [comment]
No i don't. And I will send the code in maybe five minutes.

**Comment by AndusDEV** [comment]
https://pastebin.pl/view/065411bd

**Comment by AndusDEV** [comment]
I don't think it's script fault because I have some scripts that work but they just don't show the text that they should show

**Comment by TheDGOfficial** [comment]
There is LuckPerms in the stacktrace, try without any plugins on a fresh
server and verify all your JARs signatures.

I’ve seen this issue before and it turned out to be a malware plugin
rewriting all plugin JARs and injecting something into them.

Can’t remember the issue number; but like I said this is not a Skript issue.

**Comment by TPGamesNL** [comment]
It was #3756

**Comment by AndusDEV** [comment]
> There is LuckPerms in the stacktrace, try without any plugins on a fresh
> server and verify all your JARs signatures.
> 
> I’ve seen this issue before and it turned out to be a malware plugin
> rewriting all plugin JARs and injecting something into them.
> 
> Can’t remember the issue number; but like I said this is not a Skript issue.
> 

Its working now. I don't really know how it started working but it's working. Oh and i tried before without plugins and it wasn't working.
