### ISSUE TITLE
StackOverFlowError still not fixed

### ISSUE THREAD

**Issue by TheDGOfficial** [SkriptLang/Skript#3797]
### Description
StackOverFlowError on very long lines. Still not fixed after #3195, though that only fixed (well, not a fix but a warning) it on aliases. It still occurs on scripts. Though this an user error (having very long lines), it prints a very long stack-trace and says it to report to here, so giving a more user friendly Skript#error would be better.

Besides, it is not fully a user error. While having long script lines is often bad code, this still a Java exception and our problem. If JDK didn't used a recursive regex implementation that would not be a problem - but it is. Perhaps the regex triggering this error should be optimized. That would can speed up parsing speed, too.

### Steps to Reproduce
Use this script and start the server or reload optionally.

```vb
on command:
 if command is "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "":

```

Might want to increase the line's character count by just repeating it more if you don't get the error (the max stack size JDK option is platform dependent)

Tested on Java version (System: 64-bit Windows 10):
![image](https://user-images.githubusercontent.com/24778409/110331410-23a91080-8030-11eb-85f7-ebcfcc7fb341.png)

Can also test with Java 16 and 17 early access if desired, I don't think results will change however.

### Expected Behavior
Successfully parsing and/or getting a meaningful, friendly error (in case of success, we would get an empty configuration section warning since there is no other code after the if condition)

### Errors / Screenshots
Very long stacktrace repeating like this (ommitted, very very long, can provide full if desired but it doesn't contain anything related to Skript):

```
java.lang.StackOverflowError: null
        at java.util.regex.Pattern$Branch.match(Pattern.java:4800) ~[?:?]
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4855) ~[?:?]
        at java.util.regex.Pattern$Loop.match(Pattern.java:4964) ~[?:?]
        at java.util.regex.Pattern$GroupTail.match(Pattern.java:4886) ~[?:?]
        at java.util.regex.Pattern$BranchConn.match(Pattern.java:4763) ~[?:?]
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3996) ~[?:?]
        at java.util.regex.Pattern$Branch.match(Pattern.java:4800) ~[?:?]
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4855) ~[?:?]
        at java.util.regex.Pattern$Loop.match(Pattern.java:4964) ~[?:?]
        ... ommitted
```

### Server Information
* **Server version/platform:** 1.16.5/Paper
* **Skript version:** 2.5.3

### Additional Context
I've managed out to find the cause on actually where this occurs on Skript side and will provide a PR.

**Comment by Ryan12439** [comment]
I have had this bug as well, and it has caused me a world of trouble. I’ve tried many suggestions from other threads. I’ve made my lines short (my longest line is about 15 words long), I’ve used both OpenJDK and Oracle, versions 8, 11, and 15, to no avail. This issue being fixed would make my life much easier.

**Comment by TheDGOfficial** [comment]
Unfortunately the PR I have will not completely fix this either; it will
only print a more user friendly error and will not stop parsing completely
(because it is treated as a normal error and not a fatal one)

However though, it is open for fixes. Since I found exactly which regexes
cause this; fixing this would be much easier if someone knows regex (I’
dont much; and modifying blindly can break things) than before where we had
only stack traces pointing to JDK.

The error also helps and provides which line the error occurred.

If you can, testing with my PRs GH Actions build and providing feedback
would be useful.

 I’ve only had this error on very long lines but is dependent on thread
stack size so you can try to increase -Xss manually (using 64 Bit Java
already increases it that is why we recommend 64 Bit Java)

If you get that constantly across machines then providing a reproducible
test script like on the issue would help, too.

**Comment by TheDGOfficial** [comment]
You can also try using AdoptOpenJDK with OpenJ9 instead of default HotSpot
(do note that plugins depending on implementation specific VM features will
break like NMS) Since it has tail call optimization; it may help.

Getting a stack trace from both (different Java VMs) and potentially others
like GraalVM too may help knowing if this issue occurs on standard
HotSpot/JDK only or occurs on all Java versions/implementations.

I’ll add different JVM and Xss to the things to try suggestion in the PR
when I have time.

**Comment by Ryan12439** [comment]
The thing I’ve read about Xss is that it increases the likelihood of a memory overflow error. I am running 64 bit Java. I’m not exactly sure how to test the PR but I will try to figure it out and let you know.

**Comment by Ryan12439** [comment]
Ok, I got your pull enabled, and somehow it fixed the regex error instead of just warning me about it...

**Comment by TheDGOfficial** [comment]
Yes the last commit I pushed will fix it entirely for inputs not containing
#. You can try the older build (before “Various optimizations” commit)
