### ISSUE TITLE
Skripts not loading, Errors after running command, Error said to report here

### ISSUE THREAD

**Issue by BritishTI** [SkriptLang/Skript#3804]
### Description
I installed skript on my server it worked fine at first as expected, a few hours later I added a skript I went to reload it and got the message "Could not load timerss.sk: plugins/Skript/scripts/timerss.sk (Permission denied) (config.sk, line 188: databases:')" although I don't believe it was the skript since I've had it before and all it was, was a command that said Hello world!

### Steps to Reproduce
I'm not to sure since it just randomly happened, but the error in the logs told me to report it here.

### Expected Behavior
The skript should've reloaded and been functional in-game and there shouldn't be any errors after running the command.

### Errors / Screenshots
https://file.io/ORZ8Leem9qLm
^ Errors
https://docs.google.com/document/d/1pjWJAY6sNXeFGEJ7XhZKV28xDC-TEUKO1v96pgoRtG8/edit?usp=sharing
^ Images of in-game and errors

### Server Information
* ** Java 8, 1.16.5, Tunity
* 
* **Skript version:** 
2.5.3

**Comment by TheDGOfficial** [comment]
The NPE is from this line:
https://github.com/SkriptLang/Skript/blob/da691e2d36b038a20ed14cf1f6ab01f471c11451/src/main/java/ch/njol/skript/ScriptLoader.java#L404

Though that is possibly unrelated and its root cause is the Permission denied error you've got. Check and ensure your file permissions are correct and Skript has access to it.

**Comment by TPGamesNL** [comment]
The NPE is a result of the Permission denied error:
https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/ScriptLoader.java#L849-L852
This is probably a file permissions issue, but it would be good to add null checks after structure loading
