### ISSUE TITLE
[Error message] sef fuel event create error

### ISSUE THREAD

**Issue by VeteranDrenor** [SkriptLang/Skript#3809]
Bonjour/Hello,

J'ai cette erreur :
I got this error :
https://pastebin.com/VuTWpgRY
En utilisant cette ligne qui marchait bien auparavant :
By using the line thats works well before :
 set fuel of {_blockForge} to 1 of stick 
 
 Thanks you !

**Comment by TPGamesNL** [comment]
This is an issue with Skellett, report it here: https://github.com/TheLimeGlass/Skellett/issues
PS, it's probably caused by `{_blockForge}` not being set
