### ISSUE TITLE
EffTeleport async problems

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#3816]
### Description
Event manipulation won't always work with teleport effects.

### Steps to Reproduce
```
on break of stone:
	teleport player to {loc}
	cancel event
```
set `{loc}` to a location in an unloaded chunk, and trigger the event. The event will not be cancelled.

### Expected Behavior
Because EffTeleport is an async effect, **the code shouldn't parse**.

### Errors / Screenshots
None

### Server Information
* **Server version/platform:** git-Paper-529 (MC: 1.16.5)
* **Skript version:** 2.5.3

### Additional Context
Related: https://github.com/SkriptLang/Skript/issues/3605, https://github.com/SkriptLang/Skript/pull/3478
In my opinion, that PR shouldn't have been merged, teleporting should be optionally done async, not always.

**Comment by Mehmetturker50** [comment]
`on break:
    if event-block is stone:
        cancel event
        set {loc} to location 0, 0, 0 in world "world"
        teleport the player to {loc}`

**Comment by Mehmetturker50** [comment]
``on break:
    if event-block is stone:
        cancel event
        set {loc} to location 0, 0, 0 in world "world"
        teleport the player to {loc}``

**Comment by Mehmetturker50** [comment]
on break:
    if event-block is stone:
        cancel event
        set {loc} to location 0, 0, 0 in world "world"
        teleport the player to {loc}
        
i didn't check it but it should work.

**Comment by Mehmetturker50** [comment]
``on break:
    if event-block is stone:
        cancel event
        set {loc} to location 0, 0, 0 in world "world"
        teleport the player to {loc}``

**Comment by TheDGOfficial** [comment]
The issue says it should give an error instead of silently not working. The
script is wrong in purpose.

**Comment by TPGamesNL** [comment]
@TheDGOfficial The comments were deleted by the commenter :)
