### ISSUE TITLE
on craft is called even if slot is full

### ISSUE THREAD

**Issue by HW2955** [SkriptLang/Skript#3826]
### Description

when slot is full/has an item on craft event is still called, even though we're not crafting anything
### Steps to Reproduce

here's simple skript to show the behaviour, and that it is infact called.
`on craft:
    if "%event-clicktype%" is "number key":
        send "on craft event was called!" to player`
### Expected Behavior

either shouldn't be called, or we should have something along lines on inventory click's "clicked slot"
### Errors / Screenshots

-

-

-
### Server Information
* **Server version/platform:** 
* **Skript version:** 
paper-1618
skript 2.5.3

**Comment by TPGamesNL** [comment]
Cause: https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/events/EvtItem.java#L67-L71

**Comment by TPGamesNL** [comment]
Not much we can do here, since the event is called with a normal `InventoryAction`, so I presume the check whether the item can be put into the inventory is made after the event call.
