### ISSUE TITLE
Can't get the player's uuid with a player stocked in a variable

### ISSUE THREAD

**Issue by Vulqa** [SkriptLang/Skript#3829]
### Description
I cannot retrieve the player's uuid via the player stocked in a variable, the {_uuid} variable give me "none"

### Steps to Reproduce

Code :
```
command /test:
  trigger:
    test(player)

function test(player: player):
  set {_uuid} to uuid of {_player}
  message "%{_uuid}%" to {_player}
```
or
```
command /test:
  trigger:
    set {_player} to player
    set {_uuid} to uuid of {_player}
    message "%{_uuid}%"
```

### Server Information
Server version/platform: Paper 1.16.5
Skript version: 2.5.3

**Comment by TPGamesNL** [comment]
I cannot reproduce. Are you sure `player` is set?

**Comment by Vulqa** [comment]
I tested them all by removing my plugins one by one and it is actually a conflict with the skScraft addon (this expression I think https://skripthub.net/docs/?id=4621 )

Sorry for the useless issue!
