### ISSUE TITLE
Issue on load

### ISSUE THREAD

**Issue by kill05** [SkriptLang/Skript#3835]
### Description
Sometimes when my server starts, a skript of mine gives an error to the console, but if I /sk reload it works fine

### Steps to Reproduce
1) Load in my server with the skript
2) Read 50% of the time an error in the console

### Expected Behavior
My skript loading fine

### Errors / Screenshots

https://pastebin.com/S5AFU13B

(the first part is a Tuske error i have attached just in case, while in the second part there is the main error. Also i'd like to point out that i am NOT using any final damage or heal amount expressions in my skript and I don't cancel events after they have passed.)

### Server Information

![image](https://user-images.githubusercontent.com/50295718/111851693-8c3b9b80-8914-11eb-97c5-525c41369c49.png)

### Additional Context

I don't feel like attaching publicly the skript here. If it is needed, please dm kill05#3840 on discord. I'm both in skunity and skript chat discords.

**Comment by WeeskyBDW** [comment]
Hello
Can you give an another script code that have this error ? If you dont want to send your script code.

**Comment by kill05** [comment]
I didnt have any problems similart to this one ever, so I cant really tell what causes it specifically, my on load event just sets some lists

**Comment by TPGamesNL** [comment]
This is probably caused by an old version of skript-mirror. I recommend you upgrade to [skript-reflect](https://github.com/TPGamesNL/skript-reflect), an updated fork of skript-mirror.

**Comment by kill05** [comment]
Seems to have solved the issue thanks
