### ISSUE TITLE
Mohist 1.16.5-425 + Skript 2.5.3 are not functional and when I send /sk reload all command, Skript responds /skript help.

### ISSUE THREAD

**Issue by Egregoros** [SkriptLang/Skript#3845]
Mohist 1.16.5-425 + Skript 2.5.3 are not functional and when I send /sk reload all command, Skript responds /skript help.

**Comment by TPGamesNL** [comment]
Skript does not support your server software. Also fill in the template next time, instead of deleting it. Related: #2020
