### ISSUE TITLE
[Suggestion] on enderman enrage

### ISSUE THREAD

**Issue by 5mmx** [SkriptLang/Skript#3847]
Hello! I have noticed that there isn't any event in skript that triggers when an enderman gets enraged. I figured out that some add-on had this, but said add-on got discontinued and no longer works. I think this should be built-in skript.

This event should probably have some event values:

1) The entity, aka the enderman that got triggered. (So we can check for its name etc.)

2) The player that enraged the enderman.

This would be really helpful when working to make "custom" endermans and in many situations. Additionally, there should also be a way to cancel the event.

**Comment by TPGamesNL** [comment]
Would be Paper only, see https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/event/entity/EndermanAttackPlayerEvent.html

**Comment by 5mmx** [comment]
I guess that would be ok, some other stuff in skript only works for paper. Good to know
