### ISSUE TITLE
suggestion worldborder

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#3848]
Add a effect:
Create|set world|border|world border of world "" with radius 2000 of %location% with square|circle| etc. I guess would be a cool thing...

**Comment by Wafffidooe** [comment]
Would be a nice feature! In addtion it'd be good to be able to name the border, like:
create square|circle worldborder named "test" in world "world" with radius 2000 of %location%

Then you do something like this:
every 100 seconds in world "world":
    reduce size of worldborder "test" (in world "world") by 2

**Comment by TheLimeGlass** [comment]
closing in favour of more detailed https://github.com/SkriptLang/Skript/issues/5178
