### ISSUE TITLE
Creeper in damage event is parsed as... firework?

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#3849]
### Description

Well, skript thinks that in damage event creeper is a firework

### Steps to Reproduce

```
on damage:
	if victim is zombie:
		send "this is zombie" to attacker
	if victim is creeper:
		send "this is creeper" to attacker
```

### Expected Behavior

It should parse creeper as a mob like with zombie

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/36040466/112217480-fa3cd700-8c22-11eb-97f5-5cbe89929598.png)

Similar error you get when you call a slime
![image](https://user-images.githubusercontent.com/36040466/112219663-99fb6480-8c25-11eb-970f-bbf8a100e22c.png)

### Server Information
* **Server version/platform:** git-Tuinity-9bdcb9b (latest at this moment)
* **Skript version:** 2.5.3 (latest at this moment)

**Comment by TPGamesNL** [comment]
You need to use `if victim is a zombie`, keyword **`a`**, otherwise Skript will try comparing it with other types, such as the firework type 'creeper'.
