### ISSUE TITLE
Detect the domain is a player joining

### ISSUE THREAD

**Issue by Aeris1One** [SkriptLang/Skript#3854]
It would be great, after a `on join` event, to be able to test which domain is a player joining. 
Like for example I've `minigames.domain.tld` and `plots.domain.tld` and I want them to do specific actions on player on join. So maybe an expression like `domain of player` to be able to test `if domain of player is ...` and then do specific actions.

That's possible at least in Java, here is a open source plugin implementing such a check : https://www.spigotmc.org/resources/domainteleport.12723/

**Comment by TPGamesNL** [comment]
This would be present in the connect event, not join: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerLoginEvent.html#getHostname()
