### ISSUE TITLE
Error when sending a message to a player and console with same effect

### ISSUE THREAD

**Issue by AzonFR** [SkriptLang/Skript#3863]
### Description
The send effect doesn't work when we send a message to player[s] and console
But it work when `player` is replaced by `sender` and the sender is a player. It send the message to the sender (player) and console.

### Steps to Reproduce
```
command /test:
  trigger:
    send "hey! it is a test :)" to player and console
```

### Errors / Screenshots
https://pastebin.com/hBULXqcf

### Server Information
* **Server version/platform:** Spigot 1.8.8
* **Skript version:** 2.5.3 fork for 1.8

**Comment by Matocolotoe** [comment]
> * 2.5.3 fork for 1.8

Well then report it to that fork

**Comment by TPGamesNL** [comment]
Can confirm.

Caused by `Utils#getSuperType(Class...)` not returning the right supertype (returns `java.lang.Object`, should be `org.bukkit.command.CommandSender`) for the input: 
> class `org.bukkit.entity.Player`
> > extends `org.bukkit.entity.HumanEntity`
> > > extends `org.bukkit.entity.LivingEntity`
> > > > extends `org.bukkit.entity.Damageable`
> > > > > extends `org.bukkit.entity.Entity`
> > > > > > extends `org.bukkit.command.CommandSender`

and
> class `com.destroystokyo.paper.console.TerminalConsoleCommandSender`:
> > extends `org.bukkit.craftbukkit.v1_16_R3.command.CraftConsoleCommandSender`
> > >  implements `org.bukkit.command.ConsoleCommandSender`
> > > >  extends `org.bukkit.command.CommandSender`
