### ISSUE TITLE
on place player head <- Bug/error

### ISSUE THREAD

**Issue by danielzinh** [SkriptLang/Skript#3870]
### Description
when I put a player head in a "broken" way the event does not run.

### Steps to Reproduce
make the code:
"
on place player head:
    broadcast "a"
"
and try to place a head clicking in another head or non-whole blocks such as slabs, lamps, torches, among others

like this print: https://prnt.sc/111s9iw
or this: https://prnt.sc/111sa5n

the heads placed in that case, doesn't runned the place event

### Expected Behavior
execute the code "on place" and said "a" in the chat. (broadcast)

### Errors / Screenshots
"Correct" way: https://prnt.sc/111sb52
"Doesn't execute event" way: https://prnt.sc/111sbqy (placing head clicking in another head or like)

### Server Information
* **Server version/platform:** 
* **Skript version: 2.5.2**
![image](https://user-images.githubusercontent.com/50877639/113341358-727e5900-9303-11eb-9fda-2777978a7f8b.png)

### Additional Context
i like potatoes

**Comment by TPGamesNL** [comment]
You need to use `player wall head` for those
