### ISSUE TITLE
Add more support for event-direction

### ISSUE THREAD

**Issue by ExtraSmartMiner** [SkriptLang/Skript#3879]
It was wondering if event-direction could also be used for player's block such as:

on right click:
    set block at location 1 event-direction of player's target block to dirt

Or if the player has not clicked a block it changes to the target block and if that is not set then <none>

**Comment by Ankoki-Dev** [comment]
iirc anything that isn't `above` or `below` needs to be `northward`, `eastward`, `westward`, or `southward`, but event-direction returns `north`, `east`, `south` and `west`. Its not really hard to make a little function to change them or so but i do agree its annoying, however if it was to be changed there would probably be issues in the same way there is now, just the other way round if that makes sense

**Comment by TPGamesNL** [comment]
> It was wondering if event-direction could also be used for player's block such as:
> 
> on right click:
> set block at location 1 event-direction of player's target block to dirt
> 
> Or if the player has not clicked a block it changes to the target block and if that is not set then

What direction would event-direction refer to here?

**Comment by ExtraSmartMiner** [comment]
It would be the same as

on right click:
set block at location 1 event-direction to dirt

but you don't have to click on a block for it to place the dirt u can just be looking at it: Above/Below/North/East/South/West

**Comment by TheLimeGlass** [comment]
You can do
```vb
on block place:
	set block in the direction of event-block from player to dirt
```

But this error is currently present https://github.com/SkriptLang/Skript/issues/3876

**Comment by TPGamesNL** [comment]
As said above, you can already get this direction with an expression
