### ISSUE TITLE
Allow On left Click in adventure mode

### ISSUE THREAD

**Issue by ExtraSmartMiner** [SkriptLang/Skript#3880]
Right now if you left-click this event will not run if you are in adventure mode

**Comment by TheLimeGlass** [comment]
Cannot reproduce on 2.5.3 and a 1.16.5 server. Please provide us with more information like what your server version is. If you run PaperSpigot, what version your client is and what version of Skript you have.

My test script:
```vb
on left click:
	player's gamemode is adventure
	broadcast "test"
```

**Comment by ExtraSmartMiner** [comment]
I mean on left click dose not run in adventure

**Comment by ExtraSmartMiner** [comment]
I am using the same server u said

**Comment by ExtraSmartMiner** [comment]
paper

**Comment by TheLimeGlass** [comment]
What version is the server? Type /version and /version Skript. We need those two versions.

**Comment by Romitou** [comment]
Cannot reproduce with TheLimeGlass' script :
- `Yatopia version git-Yatopia-"04855bf" (MC: 1.16.4)`
- `Skript version 2.5.3`

**Comment by ExtraSmartMiner** [comment]
2.5.3

**Comment by ExtraSmartMiner** [comment]
1.16.5

**Comment by TPGamesNL** [comment]
Please type whatever you want to say in one message, and edit that message instead of sending another

**Comment by TheLimeGlass** [comment]
Send your script coding.

**Comment by ExtraSmartMiner** [comment]
on left click:
    broadcast "hi"

**Comment by ExtraSmartMiner** [comment]
that works in survival and creative
but not adventure

**Comment by TPGamesNL** [comment]
@ExtraSmartMiner As I just said, please edit your messages instead of sending multiple in a row

**Comment by ShaneBeee** [comment]
If I'm not mistaken, when the player clicks in adventure mode, if they are not able to break the targeted block, it is not sent to the server. The client itself handles whether the player can break/place based on the NBT of said item in hand.

**Comment by TPGamesNL** [comment]
Tested, this is indeed the case. If the tool can interact with the block, `event-block` will be set
