### ISSUE TITLE
[SUGGESTION] Check if an alias is already registered

### ISSUE THREAD

**Issue by UeberallGebannt** [SkriptLang/Skript#3881]
It would be nice to have a way to check if an alias is already registered, this comes in handy if there are custom materials that are dynamically generated.

Is it possible (or maybe already implemented?) to do something like this:

`isAliasRegistered("dirt")`

**Comment by TPGamesNL** [comment]
You can already check this with `if "dirt" parsed as a material is set`. Is this good enough?

**Comment by UeberallGebannt** [comment]
Basically, but i would need to do that in Java, not in a skript

**Comment by TPGamesNL** [comment]
Have you tried using https://github.com/SkriptLang/Skript/blob/d09320866fa15bd6f2fc77b13f3e0cfd2c46ef36/src/main/java/ch/njol/skript/aliases/Aliases.java#L245

**Comment by UeberallGebannt** [comment]
I saw this, yet I wasn't sure what exactly I get because the plugin is a bit complicated '^^

**Comment by UeberallGebannt** [comment]
Can I just do `parseItemType("dirt") != null` ?

**Comment by TPGamesNL** [comment]
Use `Aliases.parseItemType("dirt") != null`. You might want to use a log handler to, because the javadoc comment says it prints errors.

**Comment by UeberallGebannt** [comment]
Thank you ^^
