### ISSUE TITLE
Variable doesn't deserialize ItemStacks correctly

### ISSUE THREAD

**Issue by yhdev7935** [SkriptLang/Skript#3885]
### Description
Variable doesn't deserialize ItemStacks correctly

### Steps to Reproduce
1)
```
command test:
  trigger:
    set {var} to orange wool block named "foo"
    broadcast "%{var}%" # outputs: orange wool block named "foo", normal.
```
2) Restart server
3)
```
command test2:
  trigger:
    broadcast "%{var}%" # ouputs: you will see... white wool block named "foo"
```

### Server Information
* **Server version/platform:** Spigot 1.12.2
* **Skript version:** Skript 2.5.3

**Comment by TPGamesNL** [comment]
Can confirm (on 1.12, not 1.16)

**Comment by Romitou** [comment]
Looking at the BukkitClasses : 
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/classes/data/BukkitClasses.java#L1111
I see that the ItemStack is serialized with ConfigurationSerializer, via the Bukkit Yaml serializer:
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/classes/ConfigurationSerializer.java#L69-L73
Tell me if I'm wrong, but this would be more of an issue with Bukkit?

**Comment by yhdev7935** [comment]
Is this hard to fix? The item is not properly stored, so I think it needs to be corrected quickly. Or is there a problem?

**Comment by yhdev7935** [comment]
@TPGamesNL

**Comment by TPGamesNL** [comment]
> Is this hard to fix? 

I don't know, I haven't looked into what causes this
> The item is not properly stored, so I think it needs to be corrected quickly. Or is there a problem?

The reason the priority on this isn't higher is because it only happens on 1.12, but not on 1.16.

**Comment by TPGamesNL** [comment]
Duplicate of #2111
