### ISSUE TITLE
[21:27:19 ERROR]: [Skript] 6 log handlers were not stopped properly! 

### ISSUE THREAD

**Issue by Ruubgaming** [SkriptLang/Skript#3886]
### Description
When I start my server I get a lot of those messages. The message told me to file a report here.

### Steps to Reproduce
I did just what others would do. I have some extra's installed and just a few scripts. I have skript-yalm, skquery and skript mirror

### Expected Behavior
Everything I coded works, it just gives me this error.

### Errors / Screenshots
![Leads _ Console - Mozilla Firefox 8-4-2021 08_13_07](https://user-images.githubusercontent.com/82137277/113977086-5702d900-9842-11eb-829c-1fb3542d70de.png)

https://p.sc2.nl/E5agj

### Server Information
* **server version:** Paper 1.16.5
* **Skript version:** v2.5.3

**Comment by TheDGOfficial** [comment]
Use skript-reflect instead of skript-mirror

**Comment by Ruubgaming** [comment]
It looks like that worked :) Thanks.
