### ISSUE TITLE
The uncolored message in an on chat event is buggy

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#3887]
### Description
The "uncolored message" result is buggy (not showing as it should). It displays very strange numbers and strings.

### Steps to Reproduce
```
on chat:
	set {_msg} to uncolored message
	broadcast "DEBUG: %{_msg}%"
```
Then just write "&5test" in the chat. 

### Expected Behavior
Should show the correct value (an unformatted text)

### Errors / Screenshots
https://i.imgur.com/Gs4S9ki.png

### Server Information
* **Server version/platform:** This server is running Tuinity version git-Tuinity-"94f025a" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* **Skript version:** Skript] Loading Skript v2.5.3

**Comment by TPGamesNL** [comment]
I cannot confirm. Can you try `broadcast "DEBUG: %message% ; %uncolored message%"`

**Comment by bloggy** [comment]
This is the result @TPGamesNL 

https://i.imgur.com/l6e1U9V.png

**Comment by bloggy** [comment]
Found the issue: plugin called InteractiveChat.jar -> maybe somebody else may find this useful. Thanks for your help!
