### ISSUE TITLE
Gliding State Errors When Using Variables

### ISSUE THREAD

**Issue by RedstoneGamer54** [SkriptLang/Skript#3891]
### Description
Nothing happens.

### Steps to Reproduce
```
set {_p} to player
set {_p}'s gliding state to true
```

### Expected Behavior
The player should be gliding.

### Errors / Screenshots
[https://pastebin.com/SrbV29rJ](url)

### Server Information
* **Server version/platform:** Paper 1.16.5
* **Skript version:** 2.5.3

**Comment by TPGamesNL** [comment]
Caused by https://github.com/SkriptLang/Skript/blob/d09320866fa15bd6f2fc77b13f3e0cfd2c46ef36/src/main/java/ch/njol/skript/expressions/ExprGlidingState.java#L41
using `entity` instead of `livingentity`
