### ISSUE TITLE
When trying to set a new line inside tooltip, it breaks the tooltip.

### ISSUE THREAD

**Issue by Damiano-221** [SkriptLang/Skript#3895]
I want to do a tooltip with newline %nl% but i doesn't work.

I have Skript 2.5.3 and SkQuery
Minecraft Version: 1.16.5
Server: Spigot-1.16.5

command /testing:
  trigger:
    send "<tooltip:&aLINE 1%nl%&bLINE 2%nl%&cLINE 3>Hover<reset>"

This is the code
This is the bug/error screen:
https://i.imgur.com/eVNsqX4.png

**Comment by AyhamAl-Ali** [comment]
Newlines works in tootips, you just need to use `send formatted %string%` like `send formatted "<ttp:line1%nl%line2>test" to player`
