### ISSUE TITLE
invisible passenger bug minehut

### ISSUE THREAD

**Issue by DerpyFood** [SkriptLang/Skript#3898]
### Description
when u spawn a spider theres a chance for it to be a spider jockey and the skeleton on the spider jockey is invisible and shoots arrows until the spider is dead in minehut 

Same for any mob that can spawn with a passenger

### Steps to Reproduce
spawn a spider at %location%

### Expected Behavior
it should just spawn the mob and not with invisible passengers
### Errors / Screenshots
none

### Server Information
* **Server version/platform:** 2.5.3-MH
* **Skript version:**

**Comment by FranKusmiruk** [comment]
Skript doesn't do anything on its own as it just calls the World#spawn(Location, EntityType) method, if this happens then it might just be Paper/Spigot doing such thing. Also, forks are not supported so please avoid reporting the issue without confirming with vanilla Skript first.
