### ISSUE TITLE
on break of oak_log does work.

### ISSUE THREAD

**Issue by HelParadox** [SkriptLang/Skript#3900]
I was just trying to write a simple skript with this expression and it was give me an error.

I put in the code "on break of oak_log:"

It should have detected if the oak log was broken and run some other code

![2021-04-12_17 37 54](https://user-images.githubusercontent.com/74212566/114479693-e1866800-9bb5-11eb-8031-620f00a6724d.png)

Server version: git-Paper-"b89788a" (MC: 1.16.5)
Skript Version: 2.5.3-MH

**Comment by MinecollYT** [comment]
Use `on break of oak log:`

**Comment by iamthewallrus** [comment]
> Skript Version: 2.5.3-MH
minehut has a dodgy version of skript ngl, I use it myself on the reg and it's inconsistent

also use _oak log_ instead of _oak_log_

**Comment by AyhamAl-Ali** [comment]
Can confirm on vanilla Skript 2.5.3 and MC 1.16.5

`oak_log` = Error
`oak log` = Working

**Comment by TPGamesNL** [comment]
`oak log` is a normal item type, but `oak_log` is a block data, which cannot be used everywhere (e.g. `oak_log with lore "abc"` errors too).
You should stick to using the aliases instead of namespaced IDs for now, although having more support for block data is a suggestion.

**Comment by APickledWalrus** [comment]
I believed this was added in https://github.com/SkriptLang/Skript/pull/4033 which has been merged (and is in beta builds). I am going to close this issue since it should have been resolved.
