### ISSUE TITLE
Issue with custom items from itemsadder

### ISSUE THREAD

**Issue by MinecollYT** [SkriptLang/Skript#3901]
### Description
It seems like Skript changes the lore of an itemsadder item

### Steps to Reproduce
|> Install Skript, TuSKe and Itemsadder
|> Create a gui 
|> Add a custom item with a lore to that gui
|> Give yourself the itemsadder item that has been used in the GUI

### Expected Behavior
Keeping the lore and not changing it

### Errors / Screenshots
https://github.com/PluginBugs/Issues-ItemsAdder/issues/821

### Server Information
* **Server version/platform:** Paper 1.16.5
* **Skript version:** 2.5.3

### Additional Context
I'm not sure if this belongs into the Skript bug reports or into the TuSKe bug reports - sry If I got it wrong

**Comment by TPGamesNL** [comment]
Show your code

**Comment by MinecollYT** [comment]
Everything should be in the mentioned itemsadder issue, but the important parts of the gui are:
```
		open virtual chest inventory with size 5 named "&4&lW&caffen&4&ls&cchmied" to player
		format gui slot (integers from 10 to 16) of player with barrier named "&c&lLEER"
		format gui slot (integers from 19 to 25) of player with barrier named "&c&lLEER"
		format gui slot (integers from 28 to 34) of player with barrier named "&c&lLEER"
		# dragon_sword
		format gui slot 10 of player with customitem "emerald_sword_1" with lore " &8● &7Kosten&8: &e%format(2800)% Coins" and "" and "&a&l[!] &fKlicke um das Item zu kaufen&8." and "&c&l[!] &7&nKeine Rückerstattung&r &7möglich&8!" to close then run function buyCI(player, 2800, "emerald_sword_1")```

**Comment by TPGamesNL** [comment]
It seems that ItemType isn't immutable, for example:
```
on death:
	set {_x} to (first element of drops) with lore "abc"
```
will change the lore of the drops. Related: https://github.com/SkriptLang/Skript/issues/3779

**Comment by FranKusmiruk** [comment]
This is actually inteded behaviour, the `with lore` expression specifically implies it's going to change the given item's lore within its pattern after all. If anything a notice should be added to the documentation.

**Comment by MinecollYT** [comment]
> This is actually inteded behaviour, the `with lore` expression specifically implies it's going to change the given item's lore within its pattern after all. If anything a notice should be added to the documentation.

But shouldn't it only change the lore of the item in the current gui?

**Comment by AyhamAl-Ali** [comment]
> But shouldn't it only change the lore of the item in the current gui?

Back in the days when `with lore` expression from `SkQuery` was the only expression available it used to clone the item and apply the new lore on it and return the cloned item instead of changing the original item.

Sometime ago when I updated to 2.3 probably I don't remember exactly (and `with lore` is now a Skript expression), my script broke because my GUI had a lot of `with lore` and it kept duplicating lores, I have no idea why Skript wouldn't clone the item and return the cloned one instead of changing the original one.

After long time I thought this is fixed but it seems not, with Skript 2.5.3 I have tested a code and my GUI items keep changing when any player open the GUI and the lore applies on the original item.

> This is actually inteded behaviour, the `with lore` expression specifically implies it's going to change the given item's lore within its pattern after all. If anything a notice should be added to the documentation.

Why is it intended? there must be a reason ofc

**Comment by AyhamAl-Ali** [comment]
Also, before I forgot, if this is intended and won't be changed would you add a new expression that allows cloning the item instead of editing the original one? like `clone item with lore %string%`

**Comment by FranKusmiruk** [comment]
> Also, before I forget, if this is intended and won't be changed would you add a new expression that allows cloning the item instead of editing the original one? like `clone item with lore %string%`

We have discussed about it and decided to change the behaviour of the ExprWithLore, so this should be fixed whenever a new release comes out.

**Comment by danielzinh** [comment]
i recommend use SkQuery's GUI

needs Skript-mirror or Skript-reflect:
`
import:
    dev.lone.itemsadder.api.ItemsAdder

open chest with 3 rows named "GUI" to player
wait 1 tick
if name of player's current inventory is "GUI":
    set slot 0 of player's current inventory to ItemsAdder.getCustomItem("itemsadder:item") named "Test"

on inventory click:
    if name of player's current inventory is "GUI":
        cancel event
`

**Comment by MinecollYT** [comment]
NONONONO!!!!
DON'T USE SKQUERY FOR A GUI!!!!!!

And it seems like this issue has been fixed
//closed

**Comment by TPGamesNL** [comment]
We don't close issues until they are fixed in a public release

**Comment by MinecollYT** [comment]
> We don't close issues until they are fixed in a public release

oh sorry
