### ISSUE TITLE
Add /sk list command

### ISSUE THREAD

**Issue by iamthewallrus** [SkriptLang/Skript#3902]
I reckon that an /sk list command would make it easier for developers to list everything skript-related they have in-game.

**/sk list commands**

this lists the commands

**/sk list scripts**

this lists all files in the /plugins/Skript/scripts/ folder

**Comment by TPGamesNL** [comment]
And why would this be useful? It would indeed list commands/scripts, but what for?

**Comment by iamthewallrus** [comment]
> And why would this be useful? It would indeed list commands/scripts, but what for?

Its a quality-of-life feature. T'would make it easier to display them

**Comment by TPGamesNL** [comment]
I know it'd be easier to display them, [but](https://en.wikipedia.org/wiki/Circular_reasoning) *why* would you want to display them?

**Comment by iamthewallrus** [comment]
> I know it'd be easier to display them, [but](https://en.wikipedia.org/wiki/Circular_reasoning) _why_ would you want to display them?

Why did you add /skript version? Exactly, so you don't have to look at the console.
Why add /skript list commands? So you don't have to look through your scripts

**Comment by TPGamesNL** [comment]
`/skript version` was added to make it easier to provide environmental information when reporting bugs, but this isn't the case for your suggestion. Can you provide a use case scenario in which you benefit from seeing all registered commands/scripts?

**Comment by iamthewallrus** [comment]
> `/skript version` was added to make it easier to provide environmental information when reporting bugs, but this isn't the case for your suggestion. Can you provide a use case scenario in which you benefit from seeing all registered commands/scripts?

idk man its 5 am just make a pull
