### ISSUE TITLE
problem with index

### ISSUE THREAD

**Issue by Lakingsun** [SkriptLang/Skript#3903]
### Description

can't save value in list

### Steps to Reproduce

```
command /tt: 
  trigger: 
    set {a::01} to "A" 
    set {a::1} to "B" 
    message "{a::01} = %{a::01}%" 
    message "{a::1} = %{a::1}%" 
    message "{a::*} = %{a::*}%" 
    loop {a::*}: 
      message "loop-value : %loop-value%"
```

**output**
> {a::01} : A
> {a::1} : B
> {a::*} : B
> loop-value : A

### Expected Behavior

{a::01} : A
{a::1} : B
{a::*} : A and B
loop-value : A
loop-value : B

### Server Information
* **Server version/platform:**  1.16.4-R0.1-SNAPSHOT
* **Skript version:**  2.5.3

### Additional Context

[20:02:59] [Server thread/INFO]: {a::01} = A
[20:02:59] [Server thread/INFO]: {a::1} = B
[20:02:59] [Server thread/INFO]: {a::*} = B
[20:02:59] [Server thread/INFO]: loop-value : A

**Comment by TPGamesNL** [comment]
Caused by `VariablesMap.variableNameComparator.compare("01", "1")` returning 0 instead of 1 or -1.
