### ISSUE TITLE
Filter issue with lored items in an inventory

### ISSUE THREAD

**Issue by MovesLikeJaeger** [SkriptLang/Skript#3905]
### Description
Attempted to set a list to all items in an inventory that had a lore, however this list will always return empty when using a filter. Have attempted numerous times with different layouts, none of which have worked apart from looping.

### Steps to Reproduce
With a couple of items with a lore in your inventory, do this:

`on inventory close:`
`  set {_a::*} to all items in player's inventory where [lore of input is set]`
`  broadcast "%{_a::*}%"`

This will always return an empty list, however when attempting the same code with named items

`on inventory close:`
`  set {_a::*} to all items in player's inventory where [name of input is set]`
`  broadcast "%{_a::*}%"`

It functions as it should and returns correctly

You can loop to work around this, but I thought it might be worth reporting incase it has other implications.

### Expected Behavior
Should not be returning an empty list if your inventory has lored items inside it

### Server Information
Skript 2.5.3
Paper 1.16.5

### Extra comments
Funnily enough, this filter works for removing non lored items from the list, which I find quite interesting as it is very similar.

`on inventory close:`
`  set {_a::*} to all items in player's inventory`
`  remove ({_a::*} where [lore of input is not set]) from {_a::*}`
`  broadcast "%{_a::*}%"`

Thanks for reading :)

**Comment by AyhamAl-Ali** [comment]
Even weirder is that this code doesn't work
```
set {_a::*} to all items in player's inventory where [lore of input is set]
broadcast "%{_a::*}%" # <none> while there are 3 items in inventory that has lore
```
but this works
```
set {_a::*} to all items in player's inventory
broadcast "%{_a::*}  where [lore of input is set]%" # broadcasts the 3 items with lore
```

![image](https://user-images.githubusercontent.com/20037329/115862788-38edc900-a43d-11eb-82f4-edf7b05860f7.png)

**Comment by MovesLikeJaeger** [comment]
Apologies for another notification, but should this be closed now?

**Comment by TPGamesNL** [comment]
Nope
We close issues when the fix has been published in a release
