### ISSUE TITLE
Feature: player group change event

### ISSUE THREAD

**Issue by Wafffidooe** [SkriptLang/Skript#3907]
As you can extract from the title, it'd be awesome with a new event for player-group change, like:

"On player group change: #code"

Apologies if the event has already been suggested... couldn't seem to find such any suggestions on this. I still believe it'd be very useful. I just came to think of how this could be used when wanting to easily change tablist nametags/output.

**Comment by FranKusmiruk** [comment]
Groups are part of permission managers, for Skript to do this it would have to hook into specific permission managers such as LuckPerms. That being said, hooks are something better off in an addon, might be better off suggesting it to a relevant addon.
