### ISSUE TITLE
block xp

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3909]
I think a block xp expression would be nice, like skellett's 
```
on block break:
    set block xp to block xp * 2
```
this could be accomplished with BlockBreakEvent#getExpToDrop() and #setExpToDrop()\
I searched up code and apparently the experience expression uses this, but it doesn't seem to work\
if this was fixed the `spawned experience` expression would be fine for manipulating block xp

**Comment by MrScopes** [comment]
player's xp should also be an expression tbh

**Comment by Romitou** [comment]
> I searched up code and apparently the experience expression uses this, but it doesn't seem to work

I have just tested this expression, and everything works on my side, I can also get the XP amount.
```applescript
on block break:
    set the dropped xp to 40
```

https://user-images.githubusercontent.com/35146758/115782711-47e06700-a3bc-11eb-95de-041d7a54f218.mp4
