### ISSUE TITLE
Skript ignore any folder named .DAV

### ISSUE THREAD

**Issue by Ryan12439** [SkriptLang/Skript#3910]
### Description
WebDAV creates a folder called .DAV in any folder accessible by WebDAV. This causes problems as it saves files in that folder with the same file ending (.sk). 

### Steps to Reproduce
Set up WebDAV and use skript normally, else create a folder named .DAV and put a .sk file with seemingly random text in it.

### Expected Behavior
Skript should ignore any folder with this name.

### Errors / Screenshots
Skript throws console errors saying all code must be in triggers for files in that folder, and in some cases causes a stackoverflow.

### Server Information
* **Server version/platform:** Paper-556 1.16.5
* **Skript version:** 2.5.3-nightly-936bbc8   Using this version because it fixes stackoverflow

**Comment by TPGamesNL** [comment]
Related: https://github.com/SkriptLang/Skript/issues/3866
IMO Skript shouldn't try to load directories starting with `.`
