### ISSUE TITLE
[Suggestion] force respawn at spawnpoint

### ISSUE THREAD

**Issue by AggerTV** [SkriptLang/Skript#3912]
My suggestion is:

https://docs.skunity.com/syntax/search/id:4996
`force %players% to respawn` currently respawns the player at the location they died.
My suggestion is to add syntax so that the player respawns at their given spawnpoint, and not at the location where they died.

E.g
`force %players% to respawn at spawnpoint`

And please don't reply with "You can just do this or this" I know, but simple syntax makes for easier to read / cleaner skripts.

**Comment by AyhamAl-Ali** [comment]
AFAIK this can't be done because it requires the respawn location to be changed in `on respawn` event while this effect is called in `on death` event.

So such thing be done manually by the user

**Comment by AggerTV** [comment]
I'm not calling it in a event, but in a function, does that change anything?

**Comment by AyhamAl-Ali** [comment]
The respawn effect only simluate a player click on the respawn button in the death screen.

Also, based on [docs](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.Spigot.html#respawn()) it does not accept any args.

Changing respawn location must be done in `on respawn`.

**Comment by FranKusmiruk** [comment]
just do:
``
on respawn:
  set respawn location to spawn of event-player's world
```
as AyhamAl suggested
