### ISSUE TITLE
console spamed of warnings with... attributes????

### ISSUE THREAD

**Issue by Alidonis** [SkriptLang/Skript#3943]
Basicaly , after a while when my server is running, it says something like this and spams it:

`[WARN] could not find attribute generic.<insert attribute name here>`

idk why it happens , but it was always with skript that the warns showed up.

**Comment by TPGamesNL** [comment]
Please provide your Skript version, server version and scripts

**Comment by ShaneBeee** [comment]
Going to close this, as theres a lack of provided information and no reply in nearly a week.

**Comment by Alidonis** [comment]
Hello. i am back. i am using skript v2.5.3 , my server version is latest spigot for 1.16.5. i don't remember my skripts tho.

**Comment by TPGamesNL** [comment]
Keeping this closed since you can't provide your scripts
