### ISSUE TITLE
Fireballs are bugged when used on Withers and Ender Dragons

### ISSUE THREAD

**Issue by IStoleYourKill** [SkriptLang/Skript#3945]
I am trying to create a skript where a enderdragon shoots fireballs from its mouth (Like hypixel Skyblock). But the fireballs always shoot backwards instead of in the correct direction. I have tried everything and nothing works. I can spawn the fireball with a vanilla command but then i cant manipulate it with Skript because "Loop all fireballs:" Doesn't give a error but it still wont work.

Can someone tell me if i am clearly doing something wrong or if there actually is a issue with skript. Because if i use the same code but make the fireball shoot from the player it works perfectly.

**Comment by TPGamesNL** [comment]
This is not a place for Skript help, this is for bug reports. See https://github.com/SkriptLang/Skript#relevant-links
