### ISSUE TITLE
Coloring potion's doesn't work

### ISSUE THREAD

**Issue by HW2955** [SkriptLang/Skript#3947]
### Description

While trying to color (any) potion the effect won't be applied ex. dye {_i] red, {_i} being a potion (just a potion, without effects)
### Steps to Reproduce

few examples:
```set {_i} to potion named "I''m a potion!"
colour {_i} yellow
give player {_i}
^ doesn't color it

give player potion named "Another potion!"
dye player's tool green
^ doesn't color it, worth mentioning that coloring leather armor works just fine in that case!
^ same goes for rgb colors:
color player's tool (100, 120, 140)
```

### Expected Behavior

Potion/player's tool (potion as well) should've been colored

### Server Information
* **Server version/platform:** 
paper-1618 (1.12.2)
* **Skript version:** 
2.5.3
### Additional Context

Worth mentioning that we have addons for that stuff, like skbee for adding nbt to item's etc.. though it's even said on docs
`https://docs.skunity.com/syntax/search/id:4980`
that on 1.11+ we can also color potions

**Comment by APickledWalrus** [comment]
This is because https://github.com/SkriptLang/Skript/blob/f4ace32321c446938938137da4fba51dfd54e920/src/main/java/ch/njol/skript/effects/EffColorItems.java#L53 does not specify the parameter.
