### ISSUE TITLE
Bug related to target detector with "set {_target} to player's targeted entity"

### ISSUE THREAD

**Issue by Hivane060** [SkriptLang/Skript#3964]
### Description
When I'm aiming to the entity/target which has also a block behind it that can be broken by me, it won't be detected:

(Image 1) Here I am aiming the wither skeleton, that has also a gold block that can be reached (and therefore broken) by me. This is the situation where the target is not detected
![2021-05-09_01 05 41](https://user-images.githubusercontent.com/83833914/117556332-f1378600-b067-11eb-8468-18fdb0f6ac35.png)

Here are shown situations when the issue doesn't occur:
As it can be noticed here the code works fine, due to the message (that tells the type of the target) showing up

(Image 2) In this image I'm aiming the wither skeleton + the crosshair doesn't encounter any block
![2021-05-09_01 26 33](https://user-images.githubusercontent.com/83833914/117556432-40ca8180-b069-11eb-8c36-6108c2a95fbf.png)
(Image 3) In the second image I'm really far from the target (and therefore from the blocks behind it)
![2021-05-09_01 24 59](https://user-images.githubusercontent.com/83833914/117556434-432cdb80-b069-11eb-906b-9ee946f48f13.png)

### Steps to Reproduce
To replicate this issue:
1. make a skript with this code: https://pastebin.com/MLJdKD33
2. Summon a mob and put a block behind it
3. Left click when you are close enough to be able to break that block behind the "target"
4. You will notice that the message that says the type of the target won't show up 

### Expected Behavior
The target should be detected even if it has a block behind it, which is being aimed from the player's crosshair

### Server Information
* **Server version/platform:**  1.16.5
* **Skript version:**  2.5.3

### Additional Context
To resume:
 the main source of the issue, at least for me, is the "set {_target} to player's targeted entity" part

I hope to have explained everything in an understandable way

**Comment by TPGamesNL** [comment]
This is unrelated to the targeted entity expression, it's related to the click event.
`PlayerInteractEvent` (part of the click event) is only called when there's a block in line of sight. If anything, this is a bug with CraftBukkit/Spigot, not Skript, but it's probably expected behaviour, because you shouldn't use `left click` event for detecting entity clicks, use the damage event for that.
