### ISSUE TITLE
[Skript] Severe Error

### ISSUE THREAD

**Issue by STEED01** [SkriptLang/Skript#3965]
### Description
My skript was not loaded.
### Steps to Reproduce
I don't know how it happened ...

### Expected Behavior
it should have happened that my skript fully loads with an end message.

### Errors / Screenshots
https://cdn.discordapp.com/attachments/364108392022933506/840810010509574204/unknown.png

### Server Information
* **Server version/platform:** 1.8.8
* **Skript version:** 2.2-dev25

### Additional Context
nothing

**Comment by APickledWalrus** [comment]
You are running an extremely outdated version of Minecraft and Skript. We do not provide support for 1.8, but there are some forks that you may be able to find 😃  (e.g. https://github.com/Matocolotoe/Skript-1.8)

**Comment by STEED01** [comment]
Thanks to you.
