### ISSUE TITLE
Raw name of an item throwing an error

### ISSUE THREAD

**Issue by WrexBG** [SkriptLang/Skript#3967]
### Description
Using only `raw name of tool` inside a string throws an internal error

### Steps to Reproduce
`send "%raw name of tool%"`

### Expected Behavior
Sends the raw/minecraft name without throwing an error

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/40688355/117567022-b6167080-b0c2-11eb-991e-b6e13c8ac7d2.png)
Console Error: https://pastebin.com/qu5L2cyd

### Server Information
* **Server version/platform:** git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* **Skript version:** 2.5.3

### Additional Context
No Addons. Also the effect works if you add something else in the string, e.g. `send "Raw name is: %raw name of tool%"`

**Comment by TPGamesNL** [comment]
Resolved by https://github.com/SkriptLang/Skript/pull/3693

**Comment by TPGamesNL** [comment]
We don't close issues until they are fixed in a public release
