### ISSUE TITLE
No maximum durability value for netherite tools

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/Skript#4027]
I was trying to make durability warning skript. When max durability of player's tool is 0 a title shows to player. I've tested on gold tools and it works but after that when I'm in creative I accidently break a block with netherite tools and i got warned by skript "your tool was broken". I didn't understand why this happened so I debugged my code and figured out %max durability of player's tool% is returning 0 for netherite tools.

![Screenshot_2](https://user-images.githubusercontent.com/59025999/119442969-7477fd80-bd31-11eb-84f1-d643d330bb3b.png)

git-Purpur-1097 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Skript 2.5.3

**Comment by TPGamesNL** [comment]
I cannot replicate this. Do you have any addons?

**Comment by UsainSrht** [comment]
I have addons but you don't need to have any addons for "maximum durability". https://docs.skunity.com/syntax/search/id:5184

**Comment by TPGamesNL** [comment]
I know, but I suspect this is an addon syntax conflict, so can you send which addons you use?

**Comment by UsainSrht** [comment]
TuSKe 1.8.2 Pikachu Patch v3
Skellet 1.9.11
Skacket 1.0.5
Skbee 1.10.2
skript-placeholders 1.5.1
skript-reflect 2.2.1

**Comment by TPGamesNL** [comment]
It's probably a syntax conflict with TuSKe then. Can you try `max durability of player's tool`? If that works, then it is the syntax conflict

**Comment by UsainSrht** [comment]
I already showed max durability of player's tool it doesn't work but maximum durability of player's tool worked. Thanks.
