### ISSUE TITLE
Suggestion: translated text

### ISSUE THREAD

**Issue by FokaStudio** [SkriptLang/Skript#4036]
It sometimes suck when you want to send a translated message and you have to use third party addons, like ThatPackedAddon to make a packet that sends JSON message...

So this would help people do this!

let's say I have assigned text `translation` to `custom.translated.text` in the .lang file (en_us) and `translethion` in en_gb

For people with American English language, this
```
send "<translate:custom.translated.text> test"
``` would send `"translation test"`, while for British people it would be `translethion test`

**Comment by WeeskyBDW** [comment]
Imo it's better to delegate this to an addon, but why not an addon for easly send translated messages

**Comment by FranKusmiruk** [comment]
> Imo it's better to delegate this to an addon, but why not an addon for easly send translated messages

translation keys are part of Minecraft's component system, and Adventure seems to support them so the feature should be in vanilla. Handling cross-platform support however is going to be tricky.
