### ISSUE TITLE
if victim is rabbit isn't working

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#4040]
### Description

When I define rabbit in "if" - it's not being recognized

### Steps to Reproduce

```
on death:
	if victim is rabbit:
		send "yeah, it is rabbit" to attacker
on death of rabbit:
	send "yeah, it is rabbit 2" to attacker
on death:
	if victim is cow:
		send "yeah, it is cow" to attacker
on death of cow:
	send "yeah, it is cow 2" to attacker
```

### Expected Behavior

"if victim is rabbit" should be working as it works for cow, there's no error but it doesn't work. 
That's weird that "on death of rabbit" works, but checking for victim needs to clarify which rabbit we want.
for now, I need to use "if victim is gold rabbit or salt and pepper rabbit or white rabbit or black and white rabbit or brown rabbit", because "any rabbit" isn't working too.

### Server Information
* **Server version/platform:** paper-742
* **Skript version:**  2.6-alpha1

**Comment by XfedeX** [comment]
Try using "if victim is **a** rabbit".

**Comment by iOshawott** [comment]
it's still not working while I added "a"

**Comment by FranKusmiruk** [comment]
Can someone confirm this?

**Comment by TPGamesNL** [comment]
I can confirm this. Using the specific rabbit, e.g. `brown rabbit`, does work.
