### ISSUE TITLE
Internal Error when giving item

### ISSUE THREAD

**Issue by agentgamer100** [SkriptLang/Skript#4041]
### Description
When a skull item is given and you have that specific item already, it gives out an internal error, and a Severe Error in the console

### Steps to Reproduce
Here is the skript i use. The problem is with /givebee
https://pastebin.com/m6XgGhYx

### Expected Behavior
Should give the pet. I get the pet with no pet in my inventory, but if i have the pet in my inventory before executing the command, it gives internal error.

### Errors / Screenshots
https://pastebin.com/ZbJcn2tN
(Yes i did disabled TuSKe same result)

### Server Information
* **Server version/platform:** Paper version git-Paper-416 (MC: 1.16.4)
* **Skript version:** 2.5.3

### Additional Context
Confusion is head brain hurt

**Comment by ShaneBeee** [comment]
> (Yes i did disabled TuSKe same result)

This error is from Tuske, not Skript:
```
[03:28:27 ERROR]: #!#! Stack trace:
[03:28:27 ERROR]: #!#! java.lang.NullPointerException
[03:28:27 ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
```

Please try without Tuske and send the error if there still is one.

**Comment by agentgamer100** [comment]
> > (Yes i did disabled TuSKe same result)
> 
> This error is from Tuske, not Skript, so I highly doubt disabling Tuske gave the "same result":
> 
> ```
> [03:28:27 ERROR]: #!#! Stack trace:
> [03:28:27 ERROR]: #!#! java.lang.NullPointerException
> [03:28:27 ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
> ```
> 
> Please try without Tuske and send the error if there still is one.

said i disabled TuSKe in errors/screenshots but ok

**Comment by ShaneBeee** [comment]
But the error shows Tuske, Tuske is clearly NOT disabled.

This is why I said, try replicate without Tuske on your server, and if you get an error, send it. 
Based on the error you sent, it's a Tuske issue, and we can't fix issues with Tuske.

**Comment by agentgamer100** [comment]
> But the error shows Tuske, Tuske is clearly NOT disabled.
> 
> This is why I said, try replicate without Tuske on your server, and if you get an error, send it.
> Based on the error you sent, it's a Tuske issue, and we can't fix issues with Tuske.

My mistake, i must have sent the wrong error. Heres the one without TuSKe:
https://pastebin.com/Rq9Anmzb

**Comment by ShaneBeee** [comment]
Thank you.

Based on this error, it seems to be an issue with the server itself.
I see you are using 1.16.4. We only support the latest Minecraft revision per major version, ie: 1.13.2, 1.14.4, 1.15.2 and 1.16.5

Please try this on a 1.16.5 server and see if you can replicate this issue. This may be a bug on the server itself.
I would try replicate this myself, but you are using syntax from an addon I do not recognize:
```
set {_skull} to skull from skin with value {_value} signature ""
```
This also makes me think again this is not a Skript issue

**Comment by agentgamer100** [comment]
> Thank you.
> 
> Based on this error, it seems to be an issue with the server itself.
> I see you are using 1.16.4. We only support the latest Minecraft revision per major version, ie: 1.13.2, 1.14.4, 1.15.2 and 1.16.5
> 
> Please try this on a 1.16.5 server and see if you can replicate this issue. This may be a bug on the server itself.
> I would try replicate this myself, but you are using syntax from an addon I do not recognize:
> 
> ```
> set {_skull} to skull from skin with value {_value} signature ""
> ```
> 
> This also makes me think again this is not a Skript issue

Alright well updating to 1.16.5 didnt do anything, but ill take it up with the creators of MundoSK and see if they can fix it.

**Comment by ShaneBeee** [comment]
Closing as this didn't appear to be a Skript issue
