### ISSUE TITLE
World Guard does not work in Minecraft version 1.12.2, script version 2.6-alpha1.

### ISSUE THREAD

**Issue by startree236** [SkriptLang/Skript#4045]
### Description

When I open the server I get an error and the "region" related events don't work.

### Steps to Reproduce

I uploaded the version of the world guard plugin, but it is not compatible with the script.

### Expected Behavior

A "region" related event must be used in the script.

### Errors / Screenshots

[13:22:07 ERROR]: [Skript] An error occurred while trying to enable support for WorldGuard 6. WorldGuard region support has been disabled!
[13:22:07 ERROR]: [Skript] Could not hook into WorldGuard. This can happen if Skript doesn't support the installed version of WorldGuard

### Server Information
* **Server version/platform:** The server version is 1.12.2 and I am using Paper-1618.
* **Skript version:** The script version is using 2.6-alpha1 .

**Comment by TPGamesNL** [comment]
Which WorldGuard and WorldEdit versions do you use?

**Comment by startree236** [comment]
> 어떤 WorldGuard 및 WorldEdit 버전을 사용하십니까?

World Guard: 6.2.2
World Edit : 6.1.7
I am using it.

**Comment by APickledWalrus** [comment]
From a quick look, it seems as though Skript is not including the WorldGuard 6 module in the jar, so the class doesn't exist.

**Comment by Romitou** [comment]
Indeed, the module package containing WordGuard 6 is not present in the JAR of the last release. I think that the JAR was probably built without first building the WordGuard 6 module.

**Comment by ShaneBeee** [comment]
I screwed up when I built the jar, and didnt run the GitHubrelease command

**Comment by APickledWalrus** [comment]
@startree236 Is this working for you okay now in beta 2?

**Comment by TPGamesNL** [comment]
This should work, the WorldGuard 6 classes are present in the 2.6-beta2 jar:
![image](https://user-images.githubusercontent.com/29547183/126337255-68649a14-7a9e-4bc8-ac02-7641c8f6a110.png)
