### ISSUE TITLE
"contains" is not working properly.

### ISSUE THREAD

**Issue by startree236** [SkriptLang/Skript#4046]
### Description

"contains" is not working properly.
### Steps to Reproduce

Several attempts were made using temporary variables, etc.
### Expected Behavior

```
if mid contain "_" or "기본공격" or "비약" or "기타-도약" or "피버" or "신의$축복":
		stop
```
The above syntax doesn't work.
### Server Information
* **Server version/platform:** The server version is 1.12.2 and I am using Paper-1618.
* **Skript version:** The script version is using 2.6-alpha1 .

**Comment by vjh0107** [comment]
it's removed at skript version 2.6, you may use loop syntax to Implement similarly

**Comment by TPGamesNL** [comment]
> it's removed at skript version 2.6, you may use loop syntax to Implement similarly

The contains condition was not removed, two syntaxes from it where removed:
![image](https://user-images.githubusercontent.com/29547183/120327903-9271cf00-c2ea-11eb-91aa-ff8fa24ab448.png)

**Comment by vjh0107** [comment]
My mistake, that's what I meant.

**Comment by Zzheyd** [comment]
It's same for worlguard's region?
For exemple, -> if "%region at player%" contains "one" or "two" or "three":
?

**Comment by TPGamesNL** [comment]
> It's same for worlguard's region?
> For exemple, -> if "%region at player%" contains "one" or "two" or "three":
> ?

Yep, that's the same issue
