### ISSUE TITLE
skript use mod item

### ISSUE THREAD

**Issue by MRuNanM** [SkriptLang/Skript#4051]
### Description

Skript 2.6alpha how can I use mod item in skript
### Expected Behavior

 aliases:
	plus = 4521
	minus = 4522

### Errors / Screenshots

[23:10:15] [Server thread/ERROR] [Mohist]: Minecraft id 4522 is not valid (은행.sk, line 55: minus: 4522')

### Server Information
* **Server version/platform:** 
* **Skript version:** 
mohist 1.12.2 lastest
skript 2.6 alpha

**Comment by ShaneBeee** [comment]
You need to use a valid namespace.
Skript no longer uses numerical IDs for items

**Comment by MRuNanM** [comment]
I do 4522 --> numbermod minus       but I can't
[01:34:50 ERROR]: [Skript] Minecraft id numbermod minus is not valid (은행.sk, line 55: minus: numbermod minus')

**Comment by MRuNanM** [comment]
> 유효한 네임 스페이스를 사용해야합니다.
> Skript는 더 이상 항목에 숫자 ID를 사용하지 않습니다.

**Comment by MRuNanM** [comment]
> 4522-> numbermod 마이너스를 수행하지만 할 수 없습니다.
> [01:34:50 ERROR] : [Skript] Minecraft id numbermod minus가 유효하지 않습니다 (은행 .sk, 55 행 : 마이너스 : numbermod minus ').

**Comment by MRuNanM** [comment]
> ### 기술
> Skript 2.6alpha skript에서 모드 항목을 어떻게 사용할 수 있습니까?
> 
> ### 재현 단계
> ### 예상되는 동작
> 
> 뭐라고 : 더하기 = 4521
> 빼기 = 4522
> 
> ### 오류 / 스크린 샷
> [23:10:15] [서버 프로그램 / 오류] [Mohist] : Minecraft ID 4522가 유효하지 (은행 .sk, 55 : 빼기 : 4522 ').
> ### 서버 정보
> * **서버 버전 / 플랫폼 :**
> * **Skript 버전 :**   
>   mohist 1.12.2 lastest 
>   skript 2.6 alpha
> 
> ### 추가 신규

**Comment by ShaneBeee** [comment]
I just realized Skript does not support modding.

You would need to use a valid namespace, ie: `modname:namespace` but Skript only supports the Minecraft namespace

Closing due to this not actually being an issue, we just dont offer any support for mods right now.

**Comment by MRuNanM** [comment]
In Skiprt 2.2dev37 We had a mod item available.

**Comment by ShaneBeee** [comment]
Yes, Im very well aware.
But due to the changes in Minecraft 1.13, we dropped supporting numerical IDs

Feel free to continue using Skript 2.2, but I repeat, we do not currently offer support for mods

**Comment by MRuNanM** [comment]
Then, is there any way to support the ID only for mod items?

**Comment by ShaneBeee** [comment]
yeah, by using 2.2
I already said this

**Comment by MRuNanM** [comment]
Then, is there no support for mod items from now on? Many development communities in Korea want it.

**Comment by ShaneBeee** [comment]
Come Skript 2.7, we are dropping 1.12.2 and below support. 
We will not go backwards in time and re-add support for numeric IDs, since the use of numeric IDs was dropped years ago.

As for offering support for mod namespaces, it has been talked about, and may be added in the future.
But due to the way we use namespaces in the internal code, and the work that would have to be done to restructure all of this, this is a very very low priority to the Skript dev team.

As stated, if you need this kind of support, please feel free to use Skript 2.2

**Comment by FranKusmiruk** [comment]
Skript doesn't **officially** support mods, that being said there are Bukkit forks which allow you to use them. There has been a recent PR which added support for dynamic enum values (this was an issue for Mohist/CatServer when registering aliases) so you should be able to use `numbermod:minus` or whatever the minecraft namespace is just fine but whether it works or not is not guaranteed nor supported by us.

If it doesn't work, PRs to solve the issue are welcome as long as they don't impose a maintenance burden on our current codebase.

**Comment by MRuNanM** [comment]
What lastest version support Item ID

**Comment by MRuNanM** [comment]
And I think it will be a mod item through Skript Aliases, is it possible?

**Comment by AyhamAl-Ali** [comment]
> What lastest version support Item ID
You would need Skript 2.2-dev36 _(because dev37c had a memory leak afair)_

> And I think it will be a mod item through Skript Aliases, is it possible?
As the devs stated above, it might be added in the future but no plans for that yet. However, as Frank said, `PRs to solve the issue are welcome as long as they don't impose a maintenance burden on our current codebase.`

**Comment by MRuNanM** [comment]
Did you happen to have any problems other than memory leaks in skript 2.2-dev37c?  compared to dev36
