### ISSUE TITLE
Log handler not stopping properly

### ISSUE THREAD

**Issue by SlickTorpedo** [SkriptLang/Skript#4052]
### Description

Im getting alot of errors in console that say:
> [22:12:06 ERROR]: [Skript] 12 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1606)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
### Steps to Reproduce

Im just using the latest 1.8 download (2.5.3) for Skript https://github.com/Matocolotoe/Skript-1.8/releases/download/2.5.3/Skript.jar and when i restart my server it has that spammed in console.
### Expected Behavior

The server should just start normally without all these errors
### Errors / Screenshots

https://pastebin.com/6rqDq1Nh

https://www.mediafire.com/view/kqa4f8kej3rawer/Capture.PNG/file
### Server Information
* **Server version/platform:** 
* **Skript version:** 
Paper 1.8.8
Skript 2.5.3 (1.8 Skript) https://github.com/Matocolotoe/Skript-1.8/releases/download/2.5.3/Skript.jar
### Additional Context

One thing, the server does start completely and work properly its just i get a crap ton of errors

**Comment by ShaneBeee** [comment]
This issue tracker is for our version of Skript, not other peoples' forks.

**Comment by Matocolotoe** [comment]
@SlickTorpedo try to update skript-mirror, this is likely caused by an old version
