### ISSUE TITLE
Condition "Name" of certain items in player's inventory is broken when item have lore

### ISSUE THREAD

**Issue by tiradorus** [SkriptLang/Skript#4054]
### Description
When you have a script, the all item's name check (or certains items name) into an inventory, the Name condition is considered as false if the item have lore on it.
However, it works if the item does not have any lores.

I'll send you the script that i've done. You can try it yourself, it works, does not send any errors.
But if your named item have a lore, then it's not counted into the condition, even if the name is the same.

```
command /changes:		
    trigger:
        set {_diampur} to amount of diamond named "&f&lDiamant épuré" in player's inventory
        remove all diamond named "&f&lDiamant épuré" from player's inventory
        wait 5 ticks
        make console execute command "/mi give material DIAMANTPLUS %player% %{_diampur}%"
        message "%{_diampur}%" to player
```

On the code above, it count all the diamonds named "&f&lDiamant épuré" into player's inventory and removes them.
Afterwards, it gives to the player, the number of the items removed, to another item type.
It's an echange with NameCondition on items...

BUT! If the diamonds (On the script) have a lore, then, they are not counted into "{_diampur}", even if the name is still "&f&lDiamant épuré"

Without lore on the items, it works.
With lore, it's not working.

Skript version: 2.5.3
Minecraft version: 1.16.5

**Comment by TPGamesNL** [comment]
Please fill in the entire format:
```
### Description
<!--- What happened? --->

### Steps to Reproduce
<!--- What did you do to make it happen? Provide as accurate instructions as possible! --->

### Expected Behavior
<!--- What should have happened? --->

### Errors / Screenshots
<!--- Console errors and screenshots of visual bugs in game, if you have any --->

<!---
If you have console errors, copy them to a paste service which won't delete them.
DON'T use Hastebin!
--->

<!--
Screenshots of bugs visible in-game can also be attached.
--->

### Server Information
* **Server version/platform:** <!-- /version -->
* **Skript version:** <!-- /version Skript ("latest" is not useful, we need the version number) -->

### Additional Context
<!--- Anything you'd like to add? This can be left empty. --->
```

**Comment by tiradorus** [comment]
### Description
When you have a script, the all item's name check (or certains items name) into an inventory, the Name condition is considered as false if the item have lore on it.
However, it works if the item does not have any lores.

I'll send you the script that i've done. You can try it yourself, it works, does not send any errors.
But if your named item have a lore, then it's not counted into the condition, even if the name is the same.

### Steps to Reproduce
Use condition named item into a player's inventory, like that:
`set {_diampur} to amount of diamond named "&f&lDiamant épuré" in player's inventory`
Then try with an item with correct name, without lore, and another with a lore.

### Expected Behavior
All items with the name should have been counted, with or without lores.

### Actual Behavior
Only items without lores are counted

### Errors / Screenshots
None, because there is no errors.

### Server Information
* **Server version/platform:** 1.16.5
* **Skript version:** tryed en 2.5.3 and 2.6.0

### Additional Context
I use this script, you can use it too and see what happens.
```
command /changes:		
    trigger:
        set {_diampur} to amount of diamond named "&f&lDiamant épuré" in player's inventory
        remove all diamond named "&f&lDiamant épuré" from player's inventory
        make console execute command "/mi give material DIAMANTPLUS %player% %{_diampur}%"
        message "%{_diampur}%" to player
```

**Comment by tiradorus** [comment]
However, there is a little change between 2.5.3 and 2.6.0.
On 2.5.3, the `remove all diamond named "&f&lDiamant épuré" from player's inventory` was corrupted by lores.
On 2.6.0 the `remove all diamond named "&f&lDiamant épuré" from player's inventory` isn't corrupted by lores

**Comment by TPGamesNL** [comment]
Okay, so it works as expected on 2.6?

**Comment by tiradorus** [comment]
Nope, only the "Remove all diamonds ..." has been solved on 2.6.0
However the `"set {_diampur} to amount of diamond named "&f&lDiamant épuré"` in player's inventory" is still buged

**Comment by tiradorus** [comment]
Bump?

**Comment by TPGamesNL** [comment]
@APickledWalrus pinging you since this is related to item comparisons

**Comment by APickledWalrus** [comment]
This is because ExprAmountOfItems uses ItemType#isOfType(ItemStack). It should probably use a comparator instead where the ItemStack is the first argument and ItemType is the second argument (ItemStack comes first as we are verifying that it has at least the same qualities at the ItemType, but that it may also have more).

Ideally we could improve the situation of comparing items in ItemType directly (it's not really logical to have the important item comparisons in the comparators class) but because of how tied together these methods are with blocks and everything it becomes very difficult in terms of preventing bugs and making sure everything works the same.

I will add this to #4162 with the comparators fix as that will be the quickest for the time being (it is not a necessarily bad fix either).

**Comment by APickledWalrus** [comment]
Should be resolved in the PR shown above. If anyone reading this tests the nightly build, please leave feedback/problems there :)
