### ISSUE TITLE
stone slab and sandstone slab don't have ids

### ISSUE THREAD

**Issue by Bugin4** [SkriptLang/Skript#4055]
### Description

When you want to give stone slab to player it gives random stone slab to player.
When you want to give sandstone slab to player it gives random sandstone slab to player.

by stone slab I mean minecraft:stone_slab
by sandstone slab I mean minecraft:sandstone_slab

Yes, I debugged the item it said: 
stone slab in case of minecraft:stone_slab
sandstone slab in case of minecraft:sandstone_slab

### Steps to Reproduce

command /test:
   trigger:
      give stone slab to player
      give sandstone slab to player

### Expected Behavior

it should give stone slab not random stone slab
it should give sandstone slab not random sandstone slab

### Server Information
* **Server version/platform:** Paper 1.16
* **Skript version:** The “We’ll Do Better This Time” Update

**Comment by ShaneBeee** [comment]
This issue stems from the stone slab alias being the same as the any stone slab alias (where "any" is optional)
ex:
```
{waterloggable} {slab} stone slab¦s = minecraft:stone_slab
...
[any] stone slab¦s = stone slab, smooth stone slab, granite slab,...
```

This should be a simple fix, we should just make "any" non-optional
