### ISSUE TITLE
rightclick on air

### ISSUE THREAD

**Issue by danielzinh** [SkriptLang/Skript#4056]
`on rightclick` doesn't work if dont click on a block/entity

**Comment by TPGamesNL** [comment]
Please read the documentation of this event: https://skriptlang.github.io/Skript/events.html#click

**Comment by TPGamesNL** [comment]
Which is exactly what the documentation says it does

**Comment by danielzinh** [comment]
is not working on the 2.5.3

**Comment by TPGamesNL** [comment]
You're saying that on 2.5.3, the right click event isn't triggered when you right click the air with nothing in your hand?

**Comment by danielzinh** [comment]
Yea!!!

**Comment by TPGamesNL** [comment]
Awesome, then it works as documented. Please read the docs next time.
