### ISSUE TITLE
"on teleport" trigger broken

### ISSUE THREAD

**Issue by PayMe2Dollars** [SkriptLang/Skript#4057]
### Description

I have a very simple block that says "on teleport: broadcast "test"" and it doesn't broadcast "test" when I teleport.

### Steps to Reproduce

1. Make a new script
2. Type
on teleport:
    broadcast "test"
3. reload the script
4. try teleporting, it doesn't work
### Expected Behavior

It should have broadcasted "test"
### Server Information
* **Server version/platform:** 
* **Skript version:**

**Comment by TPGamesNL** [comment]
I cannot replicate this. Can you fill in the server information (server version/platform and Skript version)?

**Comment by PayMe2Dollars** [comment]
I'm using Paper 1.16.5 (build 348), version 2.6-alpha1.

**Comment by TPGamesNL** [comment]
And how are you teleporting?

**Comment by PayMe2Dollars** [comment]
Using an ender pearl, though I've also tried with a command.

I updated to paper 768 and it seems to resolve the issue.
