### ISSUE TITLE
EVENT On sponge absorb

### ISSUE THREAD

**Issue by adviis** [SkriptLang/Skript#4059]
****
Event "On Sponge Absorb" in version 1.12.2 does not work at all (does not detect such an event) 

****
I wrote a simple script
```
on sponge absorb:
(TAB)cancel event
```
And when typing the command "sk reload sponge" it throws the error given below 

****
The script should not show an error. (I suspect it's the server version's fault) 

****
"can't understand this event: 'on sponge absorb' (sponge.sk, line 1: on sponge absorb:')

* **Server version/platform:** SPIGOT 1.12.2
* **Skript version:** 2.5.3

Have a nice day

**Comment by TPGamesNL** [comment]
The event isn't documented properly, it should say it is only present on 1.13+
