### ISSUE TITLE
"block at location {_loc}" and "block at {_loc}" yield different results

### ISSUE THREAD

**Issue by Adevy** [SkriptLang/Skript#4061]
```
on rightclick on armor stand:
	if player is not sneaking:
		if nbt of target entity contains "Invisible:1":
			set {_loc} to target entity's name
			set {_loc::*} to {_loc} split at " "
			loop 3 times:
				set {_loc::%loop-number * 2%::*} to {_loc::%loop-number * 2%} split at ","
			set {_loc} to location at ({_loc::2::1} parsed as number), ({_loc::4::1} parsed as number), ({_loc::6::1} parsed as number) of world "world"
			send "<gray>%{_loc}% | %block at location {_loc}% | %name of target entity%" to player
			if the block at {_loc} is a crafting table:
				send "asd" to player
```
Check the last 3 lines. While the "%block at location {_loc}%" returns "grass block" (which is the block under the crafting table), I also get the message "asd" with this code. Furthermore, if I change the "%block at location {_loc}%" part to "%block at {_loc}%", it correctly says "workbench" instead of "grass block".

For clarification, the armor stand's name IS the location of the crafting table. This code is a part of a bigger skript.

Also, on an irrelevant note, without the "loop 3 times" part, {_loc} variable is set to the location of workbench but both ways to get the block at {_loc} will result in Skript returning the block UNDER the crafting table. I assume that's so because the parsed numbers aren't proper numbers.

**Comment by ShaneBeee** [comment]
When reporting issues, please fill out the template provided.
It asks questions to help us triage your issue.
