### ISSUE TITLE
Skript Modifies variables when customized in a GUI

### ISSUE THREAD

**Issue by BuggyAl** [SkriptLang/Skript#4067]
### Description

Formatting an item stored as a variable in a GUI with a custom lore and/or name will modify the item variable itself.

### Steps to Reproduce

1. Save an item as a variable
2. Create a GUI to display the item with a different lore (format slot # of player with {var} with lore "this is a bugged item")
3. Open the GUI
4. Give yourself the variable item through some means (give player {var})
5. The item will have the lore "this item is bugged"

### Expected Behavior

The GUI should open and format the slot without modifying the variable. Afterwards, the item variable will not be affected with the custom name or lore.

### Errors / Screenshots

https://www.youtube.com/watch?v=oy3I_C4Yf6g (video demonstration)

### Server Information
* **Server version/platform:** 3111-Spigot-66f9d3c-cbf2f67 (MC: 1.17)
* **Skript version:** 2.5.3-MH

**Comment by AyhamAl-Ali** [comment]
> Fix an issue where lore was incorrectly being changed on items (#3928, closes #3901)

The `with lore` effect has been changed in Skript 2.6-alpha1, it used to update the item itself instead of cloning it.
