### ISSUE TITLE
GUI Error With Spigot 1.17

### ISSUE THREAD

**Issue by LungJameSK** [SkriptLang/Skript#4069]
After i use this Command /gui from Vanilla Gui.sk or other GUI Effect like enderchest ETC. from Skripthub ,My Server has stop working.
[latest.log](https://github.com/SkriptLang/Skript/files/6642610/latest.log)

command /gui:
	trigger:
		set {_gui} to a new chest inventory with 6 row with name "Gui Test"
		set slot 0 of {_gui} to stone
		open {_gui} to player
 
on inventory click:
	if name of event-inventory is "Gui Test":
		if index of event-slot = 0:
			cancel event
			send "You clicked on the slot 0 !"

**Comment by ShaneBeee** [comment]
try rebuilding spigot, I believe this was a bug in spigot that was fixed.

After updating your spigot jar, please report back

**Comment by LungJameSK** [comment]
TY>It Work.

**Comment by ShaneBeee** [comment]
Good to know. 
I remember seeing a few people talk about it on spigot, and I figured it was fixed.

closing now as issue is resolved.
