### ISSUE TITLE
Suggestion : The last color of %string%

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#4077]
Hi I suggest to add this simple expression :
 
```
import:
    org.bukkit.ChatColor as BukkitColor

expression [the] last color of %string%:
    return type: color
    get:
        return BukkitColor.getLastColors(expression-1)
```

It's from Tuske but should be in Skript [](https://skripthub.net/docs/?id=1289)

**Comment by GovindasOM** [comment]
I'd love this, been needing to use skript-reflect for it. A great use-case is splitting a text into multiple lines while still keeping the original color - which is very hard to do without this
