### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FinnLmao** [SkriptLang/Skript#4078]
![image](https://user-images.githubusercontent.com/86077460/122457951-886cf300-cfaf-11eb-8a36-622d566d3d50.png)

**Comment by AyhamAl-Ali** [comment]
More info is needed, follow the bug report format otherwise none will be able to help you

**Comment by ShaneBeee** [comment]
1) when opening a new issue, please fill out the template provided. It helps us get the info we need to triage your issue.

2) 99% of the time this error comes from running an outdated version of Skript-mirror. Consider switching to Skript-reflect (an updated fork of skript-mirror)
