### ISSUE TITLE
Remove items only without enchants

### ISSUE THREAD

**Issue by adviis** [SkriptLang/Skript#4079]
Hello
****
remove {_item} from player - works badly 

****
I wrote a script like this:
```
command /test:
	trigger:
		set {_x} to diamond pickaxe
		if player has {_x}:
			remove {_x} from player
```
And while I have it in my inventory
Slot 1: Diamond Pickaxe of Unbreaking 3
Slot 2: Diamond pickaxe
Takes my pickaxe with unbreaking 3 from slot 1 (when I have 1 pickaxe without enchants in 1 slot, it takes a pickaxe without enchants)

Maybe it's my mistake, but I've been trying to do it for over an hour and nothing gets through. I tried to do something like this among other things, but they show errors when refreshed (Can't understand this expression:)
set {_x} to diamond pickaxe without [enchants/enchantments]
set {_x} to diamond pickaxe without any [enchants/enchantments]
set {_x} to diamond pickaxe isn't [enchants/enchantments]
But it doesn't work at all (throws refresh error)..........

****
Remove the pickaxe without enchants 

* **Server version/platform:**  Spigot 1.12.2
* **Skript version:**  2.6-alpha1

Have a nice day.

**Comment by APickledWalrus** [comment]
In this case, just writing "diamond pickaxe" means the item can be any sort of diamond pickaxe. However, you can reference just plain diamond pickaxes without any name/lore/enchants with the "plain" expression (e.g. `set {_x} to a plain diamond pickaxe`) and that should remove any diamond pickaxe without any extra data. However, if you want to remove every diamond pickaxe that doesn't have enchantments (even if it has a name or has lore) you could probably loop through all of the items in the players inventory. Check it the item is a diamond pickaxe, and if it is, check that the number of enchantments on the item is 0 (ex: `if the size of the enchantments of {_x} is 0:`), and then you can remove the item.

**Comment by AyhamAl-Ali** [comment]
As far as I know, the `%inventory% has %itemtype%` will accept all items if you don't specify the exact item you want to find, therefor your code will match all diamond pickaxes with/without name/lore/enchantments.

If you want to remove all un-enchanted items you can make a filter for that like
```
item is not enchanted
remove item from player

```

**Comment by adviis** [comment]
Thank you both very much, "a plain" works!
