### ISSUE TITLE
On experience spawn event and furnace

### ISSUE THREAD

**Issue by tinesone** [SkriptLang/Skript#4080]
I broke a furnace with the code that previously melted some ores.

with this skript on my server
`on experience spawn:
  cancel event`

and it spawned an experience orb
It doesn't do that when picking up items from within the fornace

I was running spigot 1.16.5 and the "Uh. That's Hot" version of skript

**Comment by ShaneBeee** [comment]
I tried this and could not replicate.

**Comment by ShaneBeee** [comment]
The issue on Spigot has been fixed.

Rebuild your spigot jar, and try again. Issue SHOULD be resolved.
If issue still persists, let us know.

NOTE:
This issue was fixed on 1.17, not 1.16.5. As for 1.16.5, well... thats just a bug with Spigot 1.16.5 that we can't do anything about.
