### ISSUE TITLE
[Suggestion] Multithreading

### ISSUE THREAD

**Issue by XfedeX** [SkriptLang/Skript#4084]
Multithreading in Skript would be very useful, e.g. to loop a lot of blocks without crashing the server.

**Comment by TPGamesNL** [comment]
Duplicate of https://github.com/SkriptLang/Skript/issues/4005 / https://github.com/SkriptLang/Skript/issues/3568

Do note that you won't be able to loop blocks with this, since MC doesn't like multithreading in many places
