### ISSUE TITLE
[BUG] Variable Won't save if variable is set 1 minute+ before server stop/restart

### ISSUE THREAD

**Issue by LowScarlet** [SkriptLang/Skript#4085]
### Description
Variables are not saved to a .csv file. If I set the variable 1 minute before my server restarts

### Steps to Reproduce
Code example:
```hs
on skript start:
  set {variable} to 2021
````
Then the server restarts 1 minute after the server is active, then {variable} remains empty, even I tried to test it with an empty `variables.csv`

### Server Information
* **Server version/platform:** 1.16.5
* **Skript version:** 2.5.3

**Comment by TPGamesNL** [comment]
Can you send your server log?
