### ISSUE TITLE
[Suggestion] Create effect to save skript variable from memory to database

### ISSUE THREAD

**Issue by LowScarlet** [SkriptLang/Skript#4086]
I saw that SKRIPT saves variables every 5 minutes, so I hope you create an effect to save script variables directly like `save variable directly`

**Comment by TPGamesNL** [comment]
I don't think users should need to do this themselves, but I'll leave this open

**Comment by TPGamesNL** [comment]
And that was the wrong button, my bad

**Comment by ShaneBeee** [comment]
I agree with TP, users shouldn't be saving variables themselves. This will end up causing more issues than anything else, ie: loop 100+ variables and saving each and every one.

To add to this, variables save every 5 minutes if theres a change of more than 1000 variables I believe. 
If not enough changes it just waits for the next 5 minutes. Else it waits for the server to stop.

Since the variable save thing is on another thread, they also save in the event of a crash

**Comment by AyhamAl-Ali** [comment]
I had some issues couple times when my server stopped there was some rollback (probably a 5m rollback to my ad-counter), it doesn't happen a lot but it happened few times and also happens sometimes when the server crashes, is this related?

Does Skript save the variables when it stops? I have searched through Skript's `onDisable` event and didn't see anything about saving the variables unless I didn't search enough.

**Comment by LowScarlet** [comment]
> I had some issues couple times when my server stopped there was some rollback (probably a 5m rollback to my ad-counter), it doesn't happen a lot but it happened few times and also happens sometimes when the server crashes, is this related?
> 
> Does Skript save the variables when it stops? I have searched through Skript's `onDisable` event and didn't see anything about saving the variables unless I didn't search enough.

if you have skript-gui, there a problem with that addon because this addon make skript won't save variable if server restart/stop

**Comment by AyhamAl-Ali** [comment]
> > I had some issues couple times when my server stopped there was some rollback (probably a 5m rollback to my ad-counter), it doesn't happen a lot but it happened few times and also happens sometimes when the server crashes, is this related?
> > Does Skript save the variables when it stops? I have searched through Skript's `onDisable` event and didn't see anything about saving the variables unless I didn't search enough.
> 
> if you have skript-gui, there a problem with that addon because this addon make skript won't save variable if server restart/stop

Nice to know that, but I didn't use it yet.

**Comment by TPGamesNL** [comment]
If there are issues where variables are not saved properly when the server is stopped, they should be fixed, we shouldn't require users to do this manually.
> I had some issues couple times when my server stopped there was some rollback (probably a 5m rollback to my ad-counter), it doesn't happen a lot but it happened few times and also happens sometimes when the server crashes, is this related?

If the server shuts down improperly, some variables may not be saved. For the error with skript-gui, this means that any variables modified right before the server stops may be lost.
> Does Skript save the variables when it stops? I have searched through Skript's `onDisable` event and didn't see anything about saving the variables unless I didn't search enough.

See these:
https://github.com/SkriptLang/Skript/blob/04fadb47793015dcb914b87f43dd54f7abe22f84/src/main/java/ch/njol/skript/variables/Variables.java#L126-L131
https://github.com/SkriptLang/Skript/blob/04fadb47793015dcb914b87f43dd54f7abe22f84/src/main/java/ch/njol/skript/Skript.java#L988-L994

**Comment by AyhamAl-Ali** [comment]
> If there are issues where variables are not saved properly when the server is stopped, they should be fixed, we shouldn't require users to do this manually.

100% Correct. Such ability might cause more issues with Skript than fix especially if players misuse it.

> See these:

Great! I didn't read that in detailes when I was checking therefor I missed it :+1:

**Comment by Pikachu920** [comment]
@TPGamesNL if we're all in agreement that this shouldn't be added, maybe we're better off closing it and marking it wont fix? that way nobody wastes time developing a PR that likely won't merge anyway.
