### ISSUE TITLE
Item amount - on craft 

### ISSUE THREAD

**Issue by adviis** [SkriptLang/Skript#4089]
It's probably my stupid mistake as well, but I'd rather report it to be sure 

****
on craft, item amount of event-item not working

****
```
on craft:
(TAB)set {_x} to item amount of event-item
(TAB)set name of event-item to "Test"
(TAB)send "%{_x}%"
```
And when I make, for example, 3 breads (at the same time), {_x} = 1, and out of three breads only one is named "Test" . Only once did I get a message about {_x}. I changed event-item to event-items, but this didn't work

****
In my opinion, {_x} should have a value of 3 because I made 3 breads at once. And the name of the item should apply to everyone, not just one.
 
### Server Information
* **Server version/platform:**  Spigot 1.16.5
* **Skript version:**  2.6-alpha1

### Additional Context
Yea, I found the same situation in a 2016 post. My code is completely the same, however it doesn't work. https://github.com/SkriptLang/Skript/issues/218
Have a nice day.

**Comment by TPGamesNL** [comment]
This is a bug in Spigot, see https://hub.spigotmc.org/jira/browse/SPIGOT-1009
