### ISSUE TITLE
[BUG] Name of %inventories% not work

### ISSUE THREAD

**Issue by LowScarlet** [SkriptLang/Skript#4090]
### Description
Ekspression `name of %inventories%` not work

### Steps to Reproduce
1. create code:
```hs
on load:
  set {_inventory} to chest inventory with 1 row named "AAAAAAA"
  broadcast "%name of {_inventory}%"
```
2. reload it
3. look at broadcast
    
### Expected Behavior
it should output `AAAAAA` but this is `<none>`

### Errors / Screenshots
No error just `<none>` on broadcast

### Server Information
* **Server version/platform:** 1.16.5 paper
* **Skript version:** 2.5.3

**Comment by ShaneBeee** [comment]
Bukkit does not have API to get the name of an inventory.
Inventory names are now linked to InventoryView .... which is the current inventory opened to a player, so thats the only way we can get a name.
