### ISSUE TITLE
ExprPlayerViewDistance not registered

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#4094]
### Description
`ExprPlayerViewDistance` is not registered

### Steps to Reproduce
```
command /test:
	trigger:
		set {_x} to view distance of player
```

### Expected Behavior
Parse without errors

### Errors / Screenshots
`[Skript] Can't understand this expression: 'view distance of player' (script.sk, line 32: set {_x} to view distance of player')`

### Server Information
* **Server version/platform:** 1.16.5
* **Skript version:** f70570c4e339612bd7b36b7b643deb7fa1f43e01

### Additional Context
See 
https://github.com/SkriptLang/Skript/blob/f70570c4e339612bd7b36b7b643deb7fa1f43e01/src/main/java/ch/njol/skript/expressions/ExprPlayerViewDistance.java#L50
(introduced in https://github.com/SkriptLang/Skript/commit/707d124f9a4d5b0ff06f2739565ada971ce85a67)

**Comment by AyhamAl-Ali** [comment]
I can see it is `getClientViewDistance` in the javadocs

**Comment by ShaneBeee** [comment]
Unless its been fixed recently, this has been broken in Paper since 1.14, which is why it won't load

**Comment by TPGamesNL** [comment]
Yea I should've checked the Javadocs, for some reason I thought that comment meant specifically 1.14.x, but Paper Javadocs even mark it as deprecated now. I also did not read the @RequiredPlugins annotation
