### ISSUE TITLE
Cannot check for a 'variable number' of items

### ISSUE THREAD

**Issue by Adevy** [SkriptLang/Skript#4098]
### Description
If I use the line "if the player doesn't have 8 wool:", the line will work just fine. However, if I instead use the line "if the player doesn't have {_number::1} wool:", Skript won't understand that condition. Same if I try to "remove {_number::1} wool from player".

### Steps to Reproduce
`if player doesn't have {_number::1} wool:
	  send "You don't have enough wool!"
	  stop`

### Expected Behavior
Skript should check if the player has {_number::1} wool of any color.
For example, if {_number::1} is set to 8, it should check if the player has 8 wool.

### Errors / Screenshots
can't understand this condition: 'player doesn't have {_number::1} wool'

### Server Information
* **Server version/platform:** git-Paper-584 (MC:1.16.5)
* **Skript version:** 2.5.3

### Additional Context
I know for a fact that {_number::1} is an integer variable, because I can use the line "loop {_number::1} times" and that works perfectly.

**Comment by ShaneBeee** [comment]
this is caused by the literally of an item type
when using vars for numbers you need to have `of` in there
ie: `{_var} of item type`
