### ISSUE TITLE
Cannot check for 'integer variable of' wool

### ISSUE THREAD

**Issue by Adevy** [SkriptLang/Skript#4100]
### Description
```
if {_p} doesn't have {_number::1} of wool:
	send "DEBUG: you don't have %{_number::1}% of wool" to {_p}
```
This line returns "DEBUG: you don't have 8 of wool" no matter how much wool I have (have tested with 8 and 64).
Changing "of wool" to "of any wool" yields the same result.
"if {_p} doesn't have 8 wool:" works as intended, and I want the players to be able to use any colors they want.

### Steps to Reproduce
set {_number::1} to a number variable. Then;
```
if {_p} doesn't have {_number::1} of any wool:
	send "DEBUG: you don't have %{_number::1}% of wool" to {_p}
	send formatted "%{!}% Gereken malzemelere sahip değilsiniz!" to {_p}
	stop
```

### Expected Behavior
It should not have sent those messages because the condition is clearly not met.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/62482302/122962417-14a35f80-d38e-11eb-92b3-712736e20954.png)

### Server Information
* **Server version/platform:** git-Paper-584 (MC:1.16.5)
* **Skript version:** 2.5.3

### Additional Context
I am sure {_number::1} is an integer variable because I can "loop {_number::1} times".

**Comment by AyhamAl-Ali** [comment]
try `"%{_number::1}% of any wool" parsed as itemtype`

**Comment by Adevy** [comment]
> "%{_number::1}% of any wool" parsed as itemtype

Hey, that worked!!! 
Thanks.
