### ISSUE TITLE
Change Skript's string colour code handling

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#4102]
Currently, with the way `VariableString` works, there is no simple way to write the literal string `a&b`, because it automatically converts the `&b` to `§b` because of colour coding. 
Colour coding is done for every script's strings, even tho it's only useful for message effects, so it'd be better to do the colour coding when sending a message, instead of when the script is being parsed.

**Comment by Romitou** [comment]
It would be a great addition!
