### ISSUE TITLE
[SUGGESTION] Get attack cooldown.

### ISSUE THREAD

**Issue by XfedeX** [SkriptLang/Skript#4105]
Add a way to get attack cooldown. E.G.:

on any move:
  set {_a} to player's attack cooldown
  send "§eCooldown: %{_a}%"

0 = not recharged, 1 = fully recharged.
And, if it is possible, allowing numbers greater than 1 would be cool too!
E.G.: 2 = fully charged 2 times.

**Comment by ShaneBeee** [comment]
based on the docs:
`A float between 0.0-1.0 representing the progress of the charge` 

it only returns a value from 0 to 1.0 so we'd have no control over larger
