### ISSUE TITLE
Slimechunk expression wrong in 1.17

### ISSUE THREAD

**Issue by Primorior** [SkriptLang/Skript#4106]
### Description

I used the slimeball expression to make it easier for my players to locate a slimechunk. While rightclicking with a slimeball it shows if there is a slimechunk or not. I attached the code.

### Steps to Reproduce

-> Used this code as sk file:

```
on rightclick with slimeball:
	if chunk at player is a slime chunk:
		send "&aSlimechunk!"
	else:
		send "&cNo Slimechunk" 
```

-> Create world in 1.17 with seed "-8580642221070289223" (probably wrong with all seeds but in this one we used when one of my players found this issue)

-> Teleport to 178 / -2069 

-> Use slime ball to see if it's a slimechunk and it says it is. 
-> To validate if this is true, see here it's wrong, there is no slimechunk: https://www.chunkbase.com/apps/slime-finder#-8580642221070289223

### Server Information
* **Server version/platform: 3158-Spigot-f773da8-470050 
* **Skript version: 2.5.3

**Comment by TPGamesNL** [comment]
`CondIsSlimeChunk` should use `Chunk#isSlimeChunk` if that method exists
