### ISSUE TITLE
start error 1.17 spigot

### ISSUE THREAD

**Issue by Bobbbe** [SkriptLang/Skript#4107]
### Description
i have many error when im start the server.

### Steps to Reproduce
just start the server !

### Errors / Screenshots
2 big pastbin is better https://pastebin.com/KQjNFnjw

no bug in game,

### Server Information
im use spigot 1.17 java 16
* **Skript version:** 
Skript v2.6-alpha1
### Additional Context
errors refer to scripts, decoration.sk grass path, brewing.sk , I haven't installed a script yet! all scripts in the script folder are disabled.

**Comment by Romitou** [comment]
MC 1.17 is not supported yet.
