### ISSUE TITLE
Can't reload skript without make it crash

### ISSUE THREAD

**Issue by Izanaagii** [SkriptLang/Skript#4114]
Hey, when I reload skript with a command like "/sk reload test", that make my server crash, and I don't even  know what is the problem, and in the console it sent me something like "If you are a server admin please make a report on (this issues pages)"
Can I get a answer please ?
Thank you, have a nice day.

**Comment by Romitou** [comment]
Can you send errors you have?

**Comment by Izanaagii** [comment]
Hey, I fixed it, I just removed the skript-mirror addon and a skript which
make a tabcompleter, thanks for the response ^^
