### ISSUE TITLE
enchant type is not working properly

### ISSUE THREAD

**Issue by doCronie** [SkriptLang/Skript#4116]
### Description

I was trying to make a custom command that would enchant the player's currently held item with the first argument the player gave, but noticed that using <enchant type> doesn't work. However using <enchantment type> or <enchanting type> does work
### Steps to Reproduce

```
command /enchant <enchant type>:
    trigger:
        enchant the player's tool with arg-1
```
### Expected Behavior

the skript should have reloaded normally and the player should be able to enchant their item by using the command /enchant
### Errors / Screenshots

https://imgur.com/a/JznvQcu

### Server Information
* **Server version/platform:1.16.5 papermc, java** 
* **Skript version: 2.6-alpha1**

**Comment by ShaneBeee** [comment]
its `enchantment type` ... please read the docs before opening issues

**Comment by doCronie** [comment]
> its `enchantment type` ... please read the docs before opening issues

I did... clearly the original docs and the ones on skripthub aren't correct. Sorry for the misunderstanding
