### ISSUE TITLE
is online/offline not working with variables

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#4125]
### Description

using `is online/offline` condition with variables is not working.

### Steps to Reproduce

set {_p} to player
send "1" if {_p} is online # should send 1 but doesn't send anything
send "0" if {_p} is offline # should send 0 but doesn't send anything

### Expected Behavior

Should send 1 if online and 0 if offline

### Errors / Screenshots

None

### Server Information
* **Server version/platform:**  1.16.5 Paper-771
* **Skript version:**  2.5.3

### Additional Context

![image](https://user-images.githubusercontent.com/20037329/123563328-c1ca0d80-d7bc-11eb-9ed7-db9888292a66.png)

![image](https://user-images.githubusercontent.com/20037329/123563301-aa8b2000-d7bc-11eb-9262-a97ccf369d08.png)

**Comment by TPGamesNL** [comment]
Likely addon conflict, probably DiSky, try without it

**Comment by AyhamAl-Ali** [comment]
> Likely addon conflict, probably DiSky, try without it

Not using that.
My current addons

![image](https://user-images.githubusercontent.com/20037329/123605900-01b4e300-d805-11eb-8c3d-cb84e2052498.png)

**Comment by TPGamesNL** [comment]
One of them has a type named 'onlinestatus', check which

**Comment by AyhamAl-Ali** [comment]
okay I will let you know as soon as I can.

**Comment by OGContent** [comment]
> ### Description
> using `is online/offline` condition with variables is not working.
> 
> ### Steps to Reproduce
> set {_p} to player
> send "1" if {_p} is online # should send 1 but doesn't send anything
> send "0" if {_p} is offline # should send 0 but doesn't send anything
> 
> ### Expected Behavior
> Should send 1 if online and 0 if offline
> 
> ### Errors / Screenshots
> None
> 
> ### Server Information
> * **Server version/platform:**  1.16.5 Paper-771
> * **Skript version:**  2.5.3
> 
> ### Additional Context
> ![image](https://user-images.githubusercontent.com/20037329/123563328-c1ca0d80-d7bc-11eb-9ed7-db9888292a66.png)
> 
> ![image](https://user-images.githubusercontent.com/20037329/123563301-aa8b2000-d7bc-11eb-9262-a97ccf369d08.png)

![image](https://user-images.githubusercontent.com/81373802/123713844-f356dd80-d87d-11eb-8470-4325143204a5.png)
the else didn't work somehow
git-Paper-"e04368045" mc: 1.16.5
skript version 2.5.3

**Comment by AyhamAl-Ali** [comment]
Can confirm that it works as expected without addons only TuSKe. (haven't yet found which addon conflict with this)

> the else didn't work somehow

Can confirm as well. there was a fix for EffDoIf for stopping the whole trigger instead of the line itself in 2.6.0 not sure if this is related.

**Comment by TPGamesNL** [comment]
It's Vixio, see https://github.com/iBlitzkriegi/Vixio/blob/9cca56fa1fa4cb6253000b1175e300e4bf2efe21/src/main/java/me/iblitzkriegi/vixio/registration/Types.java#L224-L241

**Comment by AyhamAl-Ali** [comment]
> It's Vixio, see https://github.com/iBlitzkriegi/Vixio/blob/9cca56fa1fa4cb6253000b1175e300e4bf2efe21/src/main/java/me/iblitzkriegi/vixio/registration/Types.java#L224-L241

I suspected that from the beginning. Is there a way to maybe add a setting in each script to make Skript's vanilla effects, expressions, types etc. have a higher priority than addons? or should I make another suggestion for that?

**Comment by TPGamesNL** [comment]
They are parsed first, but CondCompare comes before CondIsOnline, so that wouldn't matter here. It would be possible to make CondCompare be attempted last, which would also solve https://github.com/SkriptLang/Skript/pull/4123#issuecomment-869215817

**Comment by AyhamAl-Ali** [comment]
> They are parsed first, but CondCompare comes before CondIsOnline, so that wouldn't matter here. It would be possible to make CondCompare be attempted last, which would also solve [#4123 (comment)](https://github.com/SkriptLang/Skript/pull/4123#issuecomment-869215817)

Indeed that would be good I think.
