### ISSUE TITLE
[SUGGESTIONS] Add failure limit to while loops

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#4126]
Since many of programmers forget to add failure limits to `while loops` and new skripters will for sure fall in that too,

It would be a great idea to add something like `while %condition% [(to|and|) (fail[s]|exit [loop]) at %integer%]` which will do the condition but when the loop reaches 30 times and condition is still met it will stop.

Current solution
```v
while true:
  add 1 to {_n}
  if {_n} > 30:
    stop loop
# More code
```
Suggested replacement
```v
while true fails at 30:
  send "1"
# code will print 30 at the end and stop
```

**Comment by FranKusmiruk** [comment]
What about just adding an expression that acts as a counter for loops, such as:
```css
[the] [current] iteration [count]
```
so like:
```python
while true:
  if iteration count is greater than 30:
    exit loop
    
loop {player-attributes::%player%::*}:
  if loop-index is "attack_speed":
    iteration count is less than 30
    send "congratulations, you've been one of the lucky 30 that got a boost on attack speed" to player
    add random number between 1 and 5 to {player-attributes::%player%::%loop-index%}
```

**Comment by AyhamAl-Ali** [comment]
> What about just adding an expression that acts as a counter for loops, such as:


Nice idea as well. could be used in for loops which is useful too.

**Comment by Pikachu920** [comment]
can this:
```
while true:
  if iteration count is greater than 30:
    exit loop
```
be shortened to this:
```
while iteration count is less than 31:
```

**Comment by AyhamAl-Ali** [comment]
> can this:
> 
> ```
> while true:
>   if iteration count is greater than 30:
>     exit loop
> ```
> 
> be shortened to this:
> 
> ```
> while iteration count is less than 31:
> ```

Would be great as well, because the whole idea was to shorten it as much as possible, but how will you get the iteration count outside a loop? unless iteration expression is registered differently it will be doable ofc.
