### ISSUE TITLE
Skript not working on 1.17 properly?

### ISSUE THREAD

**Issue by Laukage** [SkriptLang/Skript#4130]
### Description

Skript not working on 1.17? :/

### Steps to Reproduce

Not sure how exactly to reproduce this as i'm not sure the cause of it.

### Expected Behavior

That it worked? xD

### Errors / Screenshots

https://mclo.gs/5ON1Y0Y

### Server Information
* **Server version/platform:** Purpur1206 
* **Skript version:** Skript-alpha1 (I've also tried latest "Action" builds

**Comment by ShaneBeee** [comment]
that error is from skript-reflect not Skript itself, please report to them
