### ISSUE TITLE
problem with skript

### ISSUE THREAD

**Issue by vspres** [SkriptLang/Skript#4131]
I would be happy to help, the command does not work for me
(gui)

command /gui:  
    premission: command.gui
    permission message: "&4You can't do this!"
    trigger:
        open virtual chest inventory with size 3 named "&2GUI" to player
        format gui slot 11 of player with grass block named "&2Shop" with lore "&6Open shop" to run:
            make player execute command "/shop"
            close player's inventory

![image](https://user-images.githubusercontent.com/62903664/123785331-15ce1280-d8e1-11eb-8503-c61ea694c00f.png)
![image](https://user-images.githubusercontent.com/62903664/123785401-27afb580-d8e1-11eb-9018-103649a30856.png)

**Comment by TPGamesNL** [comment]
This issue tracker is for bugs / suggestions for the Skript project, not for help with Skript. See https://github.com/SkriptLang/Skript/#relevant-links for places to get Skript help
