### ISSUE TITLE
Improve event value registration and handling

### ISSUE THREAD

**Issue by Mwexim** [SkriptLang/Skript#4141]
The current system is great and allows many possibilities, but still limits developers in a certain way. I will list some things I like and all the things I think should be reworked, enhanced, or added to allow an easier registration of event values for addon developers and future contributors.

**The good**
- Event values can be registered per event and subclasses of events can be disabled very easily.
- ~Event values function as default values, so users can omit certain parts to make code look cleaner.~ (Incorrect)

**The bad**
- ~Event values must always be single.~ https://github.com/SkriptLang/Skript/pull/5168
- Event value denominators (in `event-player`, 'player' is the denominator) are determined by the type and cannot be custom.
- Expressions like 'attacker' and 'victim', which are technically event values, need to be registered as separate expressions instead.
- ~'Future' and 'past' states are possible for all expressions, while they're technically only functional for event values (please correct me if I'm wrong).~ (Addressed in another issue https://github.com/SkriptLang/Skript/issues/3150)
- Some expressions like `player` have event value counterparts (`event-player`) and need to be registered separately, while they have the exact same functionality.
- Default values need to be registered separately, while this functionality should be built-in.

**API-related**
- ~The API in general uses outdated code and could really be cleaned up using the lambda API.~ (Pull request https://github.com/SkriptLang/Skript/pull/5405)

I will try to enhance the system to fix the issues I listed. This is issue is purely for discussion and other issues that aren't on the list, but should be fixed as well (all related to event values of course).

**Comment by TheLimeGlass** [comment]
Updated to address current status. Didn't know this issue existed, we've already handled some of these.

> Event value denominators (in `event-player`, 'player' is the denominator) are determined by the type and cannot be custom.

AND

> Some expressions like `player` have event value counterparts (`event-player`) and need to be registered separately, while they have the exact same functionality.

Reflect the same issue

**Comment by Mwexim** [comment]
I made this comment while I was adding event values to skript-parser from Skript and noticing many inconsistencies and unnecessary constraints with the API. That said, I did not understand Skript's way of handling event values that well and ended up doing it a lot differently.

If the issue contains errors it may be closed if you want, unless you'd like to use it as some sort of a progress report.
