### ISSUE TITLE
Current node; error message

### ISSUE THREAD

**Issue by 18126** [SkriptLang/Skript#4149]
https://pastebin.com/QFeS0AGE

This error shows everytime I try to use remove, add, permission $, yaml. Installed plugins: skDragon, Skellett, Sk-Perm, SkQuery, Skript, SkriptAddonPatcher-CT, SkriptAddonPatcher-PR, skript-yaml, skUnity, TuSKe, Vault, WildSkript. Everything is CONVERTED by SkriptAddonPatcher.
Server version: 1.17
Every plugin is last version.

**Comment by TPGamesNL** [comment]
Can you send your entire server log (the latest.log file)?

**Comment by 18126** [comment]
https://pastebin.com/05yYfYvG

**Comment by TPGamesNL** [comment]
This error is caused by an outdated version of SkQuery, I recommend you use https://github.com/SkQuery/SkQuery/releases/tag/4.1.5.

You also shouldn't install both SkriptAddonPatcher-CT and SkriptAddonPatcher-PR, I recommend you only use SkriptAddonPatcher-PR.
