### ISSUE TITLE
prefix of var

### ISSUE THREAD

**Issue by ZConnorZ** [SkriptLang/Skript#4151]
### Description
An empty response when using a variable instead of a player.

### Steps to Reproduce
```
command /test:
	trigger:
		set {_player} to player
		set {_prefix} to prefix of {_player}
		send "%{_prefix}%" to player
```

### Expected Behavior
It should send the player's prefix, but it only works like this:
```
command /test:
	trigger:
		set {_prefix} to prefix of player
		send "%{_prefix}%" to player
```

### Server Information
* **Server version/platform:** This server is running Purpur version git-Purpur-1236 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: c0244ec on HEAD)

* **Skript version:** 2.6-beta1

### Additional Context
Prefix Manager: LuckPerms

**Comment by CrazyWords1** [comment]
On version 2.5.3 all work perfectly, 2.6-beta1, wait for updates i thing

**Comment by TPGamesNL** [comment]
I can not replicate this, MC 1.17, Skript 2.6-beta1 and LuckPerms.
Do you have Vault installed?
Which addons do you have?

**Comment by ZConnorZ** [comment]
Sorry, I checked everything again, the problem is due to the DiSky addon.
