### ISSUE TITLE
the new release

### ISSUE THREAD

**Issue by OGContent** [SkriptLang/Skript#4153]
### Description

Skript is erroring 
### Expected Behavior

skript would load fine
### Errors / Screenshots

https://pastebin.com/nibiyjr9

### Server Information
* **Server version/platform:** 
* **Skript version:** 
Server version: git-Paper-"e04368045" (1.16.5)
Skript version: 2.6-beta2
### Additional Context

java 11

**Comment by APickledWalrus** [comment]
I think this issue has to do with the materials.json file. Could you try deleting it and reporting back here if it fixes your issue?

**Comment by OGContent** [comment]
> I think this issue has to do with the materials.json file. Could you try deleting it and reporting back here if it fixes your issue?

Oh, yea it worked fine thanks
