### ISSUE TITLE
Baby husk

### ISSUE THREAD

**Issue by Eng1ner** [SkriptLang/Skript#4155]
### Description
Baby husk cannot be spawned (while baby zombie and baby drowned works fine)

### Steps to Reproduce
`spawn 1 baby husk at location of player`

### Errors / Screenshots
At reload it returns:
> Can't understand this condition/effect: spawn 1 baby husk at location of player

### Server Information
* **Server version/platform:** git-Paper-318 (MC: 1.16.4)
* **Skript version:** 2.5.3

**Comment by APickledWalrus** [comment]
I believe the pattern here is missing `<age>` https://github.com/SkriptLang/Skript/blob/6b5ad08857df19dc09c4488e8fe4c0aa1fc18729/src/main/resources/lang/english.lang#L1062

**Comment by APickledWalrus** [comment]
@TPGamesNL Could you perhaps tackle this in #3999

**Comment by TPGamesNL** [comment]
> Could you perhaps tackle this in #3999

Done 👍
