### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by OGContent** [SkriptLang/Skript#4156]
Allow things like <link:https://github.com/SkriptLang/Skript> in the Broadcast effect if possible

**Comment by APickledWalrus** [comment]
I believe you can do:
`broadcast formatted "<message with formatting here>"`
Let me know if this works for you.

**Comment by AyhamAl-Ali** [comment]
Can confirm you can't do formatting with `EffBroadcast`.
This issue can be a suggestion and for now you can use `send formatted "<ttp:test>test" to all players`

You can use `all players and console` that will throw an error see #3863

**Comment by OGContent** [comment]
> I believe you can do:
> `broadcast formatted "<message with formatting here>"`
> Let me know if this works for you.

Like Ayham said, you can't

**Comment by APickledWalrus** [comment]
Labeling this as a bug as `broadcast formatted .....` should work

**Comment by Romitou** [comment]
I don't think this is a bug. https://github.com/SkriptLang/Skript/issues/1093#issuecomment-362527135

**Comment by APickledWalrus** [comment]
Technically you can broadcasts components through https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Server.Spigot.html#broadcast(net.md_5.bungee.api.chat.BaseComponent)

Skript also does not even use a broadcast message to format. It just calls sends to every player & the console. This is something that can be fixed/improved though in https://github.com/SkriptLang/Skript/issues/3112 through the usage of something like MiniMessage.

**Comment by APickledWalrus** [comment]
Looking at it more, technically not a bug as documentation states it isn't supported. Not too important though as I have a PR incoming.
