### ISSUE TITLE
Skript alias for corals has a hyphen to much

### ISSUE THREAD

**Issue by AlmightyAnubis** [SkriptLang/Skript#4160]
### Skript/Server Version

2.5.3

### Bug Description

When Displaying the name of corals, the name isn't shown right. Would have put it to skript-aliases, but there was no issue tracker.

### Expected Behavior

Displaying the names right

### Steps to Reproduce

call vanilla name of {_item} for any coral

### Errors or Screenshots

-

### Other

-

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Can confirm for coral plants, not blocks (dead or alive):
![image](https://user-images.githubusercontent.com/29547183/124451727-fb36e600-dd85-11eb-9fcf-78f00f7dd0d5.png)
![image](https://user-images.githubusercontent.com/29547183/124451677-ebb79d00-dd85-11eb-8199-12c0cf34b593.png)
![image](https://user-images.githubusercontent.com/29547183/124451696-f2deab00-dd85-11eb-8489-4a7bb82e8ef3.png)

**Comment by APickledWalrus** [comment]
It is probably not properly connecting for the full alias

see https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprRawName.java
