### ISSUE TITLE
Bug Report for on right click event with named item

### ISSUE THREAD

**Issue by NameIsCam** [SkriptLang/Skript#4163]
### Skript/Server Version

```
2.6-beta2
```

### Bug Description

https://pastebin.com/eWe1CAvs (Sorry if I wasn't supposed to put this here)

Following the PasteBin above, it should output "F" only if the player has an ender chest named "&7Box" but it still works with a regular ender chest (no name: &7Box).

### Expected Behavior

To output "F" and cancel the event, which it does but when the ender chest is named "&7Box" and not a normal ender chest named "&fEnder Chest" (default name).

### Steps to Reproduce

https://pastebin.com/eWe1CAvs (provided again)

I tested it twice, the first time was with other plugins, and SkQuerey, my second test was a new server run with only Skript itself, no other plugins added.

### Errors or Screenshots

```
https://gyazo.com/86a3ee7a4d986192906feae00faca6fc
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by APickledWalrus** [comment]
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/conditions/CondItemInHand.java should just use the Comparators method for this - other comparison methods are somewhat unreliable.

As a workaround, you can use:
```
if player's tool is an ender chest named "&7Box":
```

Let me know if this works for you. Thanks for the report.

**Comment by NameIsCam** [comment]
Thank you for the quick response for a workaround but yes it does seem to work with what you provided, not to distract you too much as it may just be something I have to work around but if the ender chest is in a stack in the player's hand it won't output "F", less you have 1 ender chest in your hand.

Thank you!
