### ISSUE TITLE
Parse Problem

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#4165]
### Skript/Server Version

![image](https://user-images.githubusercontent.com/47111280/124495949-749ffa00-ddc1-11eb-8066-e0799c7df401.png)

### Bug Description

I can't parse the blocks I have looped as items.

### Expected Behavior

In previous non-beta versions I was able to parse blocks that I had looped.

### Steps to Reproduce

```
on explosion:
	fallingExplosion(location of event-location, {yield}, {velocity}, {force})
	cancel event

function fallingExplosion(location: location, radius: number, velocity: number, force: number):
	set {_patlat} to "Parti"
	loop blocks in radius {_radius} around {_location}:
		loop-block is not air:
			add loop-block to {pat.%{_patlat}%::*}
			add location at loop-block to {lok.%{_patlat}%::*}
        regenregion({_patlat})

function regenregion(t: text):
	set {regenaktif.%{_t}%} to true
	while {lok.%{_t}%::*} is set:
		set {_blok} to 1st element of {pat.%{_t}%::*}
		set {_blok} to {_blok} parsed as item # or item type, its same
		set {_lok} to 1st element of {lok.%{_t}%::*}
		set block at {_lok} to {_blok}
		broadcast "%{_blok}%"  # said <none>
                broadcast "%{pat.%{_t}%::*}%"  # showing all looped blocks
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Can you broadcast the string you are trying to parse as an item, and send the result of that?

**Comment by OverBrave** [comment]
Yes, I have already included this in the issue. Please see the last code string.

**Comment by OverBrave** [comment]
Yes, I'd even say parsing doesn't work for sure. Any item I add to the codebase cannot be parsed as an item. There was no this problem before.

**Comment by TPGamesNL** [comment]
Your problem is that you're not parsing a string, you're parsing a block, which is not possible: https://skriptlang.github.io/Skript/expressions.html#ExprParse
This worked on previous versions, because setting a variable to something that returned `<none>`, did not have effect. We changed that to deleting the variable.

**Comment by OverBrave** [comment]
> Your problem is that you're not parsing a string, you're parsing a block, which is not possible: https://skriptlang.github.io/Skript/expressions.html#ExprParse
> This worked on previous versions, because setting a variable to something that returned `<none>`, did not have effect. We changed that to deleting the variable.

I'm trying to understand but I couldn't understand. So how do I parse it here? Can you help me? I couldn't fix it.

**Comment by TPGamesNL** [comment]
> I'm trying to understand but I couldn't understand. So how do I parse it here? Can you help me? I couldn't fix it.

You don't have to parse it at all: removing the line that parses will have the same behaviour as it did on 2.5.3. For further help, see https://github.com/SkriptLang/Skript/#relevant-links

**Comment by OverBrave** [comment]
> > I'm trying to understand but I couldn't understand. So how do I parse it here? Can you help me? I couldn't fix it.
> 
> You don't have to parse it at all: removing the line that parses will have the same behaviour as it did on 2.5.3. For further help, see https://github.com/SkriptLang/Skript/#relevant-links

Unfortunately it doesn't work. I put it in the block part, but it does not place the block. But when I debug, it shows the block. As far as I know the variable only needs to point to the block.

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/124563332-9e503400-de48-11eb-80ba-852b99c32f9a.png)
I still think it's a skript bug. Because it was probably doing the parsing in the previous version. Have to try again.

**Comment by TPGamesNL** [comment]
Try to narrow your code down to a few simple lines, if you think it is a Skript bug. Then, add a lot of debug messages to see exactly what is happening

**Comment by OverBrave** [comment]
I solved the problem. I got the loop block as type and then parceled it and the problem was solved.
