### ISSUE TITLE
walking in the rain condition

### ISSUE THREAD

**Issue by YKDZ** [SkriptLang/Skript#4180]
### Suggestion

Add an Walking in the rain Condition,used to determine whether the player was caught in the rain

### Why?

it can provide some interesting effect,make the weather more funny

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment]
We could add a condition for these methods (Paper, [Entity](https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/Entity.html)):
![image](https://user-images.githubusercontent.com/29547183/125268723-44e47b00-e308-11eb-8aaf-7cf57edbf375.png)

**Comment by AyhamAl-Ali** [comment]
> We could add a condition for these methods (Paper, [Entity](https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/Entity.html)):
> ![image](https://user-images.githubusercontent.com/29547183/125268723-44e47b00-e308-11eb-8aaf-7cf57edbf375.png)

I can make that :+1:
