### ISSUE TITLE
Support Gamerule in Minecraft 1.12.2

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/Skript#4187]
### Suggestion

Allow using GameRule in Minecraft 1.12.2

### Why?

It's useful and Bukkit support it:
_World.setGameRuleValue(String, String)_
return a boolean, if it is true, it succeed

### Other

No

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment]
Duplicate of #3350
