### ISSUE TITLE
All plugins expressions

### ISSUE THREAD

**Issue by OGContent** [SkriptLang/Skript#4189]
### Suggestion

add a way to do like `if plugin list contains "myGoodPlugin":`, but it won't check if the plugin is enabled or disabled

### Why?

If someone wants to check if the plugin exists they don't have to do 
`if plugin "Vault" is enabled:
  send "The plugin Vault exists!"
else:
   send "The plugin Vault exists!"
`
ik this isn't really useful but since the CondIsPluginEnabled is there might awell do that

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment]
What could this be used for? I don't see much use in checking for disabled plugins

**Comment by OGContent** [comment]
> What could this be used for? I don't see much use in checking for disabled plugins

It could be used for people who want to check if a certain plugin exists, not just disabled plugin exists since that already exists

**Comment by OGContent** [comment]
closed it by mistake (,_,)

**Comment by TPGamesNL** [comment]
> It could be used for people who want to check if a certain plugin exists, not just disabled plugin exists since that already exists

So that is what it would do, but why would you need that?

This condition would be true if either `plugin {_p} is enabled` or `plugin {_p} is disabled` is true, so that could be used as an alternative

**Comment by OGContent** [comment]
>This condition would be true if either plugin {_p} is enabled or plugin {_p} is disabled is true, so that could be used as an >alternative

well yea it could be used as an alternative, instead of checking if the plugin is enabled, and then checking if it's disabled to see if the plugin exists, you could just do `plugin {_p} exists`

**Comment by TPGamesNL** [comment]
I'm closing this because I don't think it's useful for anything. 
For the rare occasion you do need this, you can use `CondIsPluginEnabled`.

**Comment by FranKusmiruk** [comment]
Alternatively, I think we can in fact provide a `plugin list` expression since that's useful when users want to replicate the /plugins behavior or something of the sort.
