### ISSUE TITLE
More config options

### ISSUE THREAD

**Issue by OGContent** [SkriptLang/Skript#4190]
### Suggestion

In [here](https://github.com/SkriptLang/Skript/blob/master/src/main/resources/lang/english.lang)
there are some options that need to be put on the config, for example, the `commands:` should be on the config to edit its messages

### Why?

very useful for people who wants the `no permission message:` to be 1 message and they don't have to worry about doing `permission message: My custom permission message`

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by APickledWalrus** [comment]
I'm thinking #3999 will solve this as you *should* be able to edit the english.lang file

**Comment by TPGamesNL** [comment]
Duplicate of #136
