### ISSUE TITLE
Can't compare player's balance with an integer

### ISSUE THREAD

**Issue by Darkweasam** [SkriptLang/Skript#4191]
### Skript/Server Version

```
2.6-beta2
Paper104 1.17.1-r0.1snapshot
```

### Bug Description

if player's balance is higher than 1: returns an error "Can't compare player's balance with an integer"

### Expected Behavior

player's balance should be an integer

### Steps to Reproduce

command /rankup [<text>]:
    trigger:
        if player's balance is higher than 1:
            send "hi"

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Darkweasam** [comment]
player's balance doesn't seem to work at all

add {_moneypool} to balance of player
set {_money} to player's balance
remove {_moneypenalty} from player's balance

all seem to be broken

**Comment by OGContent** [comment]
> player's balance doesn't seem to work at all
> 
> add {_moneypool} to balance of player
> set {_money} to player's balance
> remove {_moneypenalty} from player's balance
> 
> all seem to be broken

Do you have the plugin Vault?

**Comment by Darkweasam** [comment]
> 
> 
> > player's balance doesn't seem to work at all
> > add {_moneypool} to balance of player
> > set {_money} to player's balance
> > remove {_moneypenalty} from player's balance
> > all seem to be broken
> 
> Do you have the plugin Vault?

[15.07 23:43:39] [Server] [INFO] [Vault] Enabling Vault v1.7.3-b131
[15.07 23:43:39] [Server] [INFO] [Vault] [Permission] SuperPermissions loaded as backup permission system.
[15.07 23:43:39] [Server] [INFO] [Vault] Enabled Version 1.7.3-b131

**Comment by wallace4BR** [comment]
pretty sure you need a economy plugin, not only vault

**Comment by Darkweasam** [comment]
> 
> 
> pretty sure you need an economy plugin, not only vault



> 
> 
> > player's balance doesn't seem to work at all
> > add {_moneypool} to balance of player
> > set {_money} to player's balance
> > remove {_moneypenalty} from player's balance
> > all seem to be broken
> 
> Do you have the plugin Vault?

Looks like I just fixed it by downloading a different version of vault
