### ISSUE TITLE
Player in water condition

### ISSUE THREAD

**Issue by YKDZ** [SkriptLang/Skript#4200]
### Suggestion

~~1. A location condition that can let us determine whether the player is in a relative coordinate. For example, check whether the player's Y-axis coordinate is higher than 100.~~
2. Player's "in the water" condition that can help us determine whether the player is "in the water",not just check whether the player is swimming.
~~3. An In combat condition that can check whether the player is PVP or PVE.~~

### Why?

More conditions can create more possibilities, and many people like me need them.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
1- `if player's y-loc > 100`
2- Already done and waiting to be merged #4184 
3- That is probably something must be done with a script code using `on damage` because afair there is no condition in Spigot nor Paper about this

**Comment by Ankoki-Dev** [comment]
number 3 would be hard to deal with as there would be in combat with monsters, players, both and what would the combat timer be? it's better to be handled in a script yourself

**Comment by TPGamesNL** [comment]
1 is possible already (mentioned above), 2 will be implemented in #4184, 3 is outside the scope of Skript
