### ISSUE TITLE
Help [SKRIPT ERROR]

### ISSUE THREAD

**Issue by RORY112345** [SkriptLang/Skript#4201]
### Skript/Server Version

[https://imgur.com/mzoJQsL](url)

### Bug Description

It says Reloading script and it never done and it says something in console.

### Expected Behavior

Atleast an error or succesful. 

### Steps to Reproduce

I Don't know.

### Errors or Screenshots

`19.07 04:56:26 [Server] ERROR #!#! 
19.07 04:56:26 [Server] ERROR #!#! [Skript] Severe Error:
19.07 04:56:26 [Server] ERROR #!#! 
19.07 04:56:26 [Server] ERROR #!#! Something went horribly wrong with Skript.
19.07 04:56:26 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
19.07 04:56:26 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
19.07 04:56:26 [Server] ERROR #!#! Here is full list of them:
19.07 04:56:26 [Server] ERROR #!#! Vixio v2.0.7 (http://vixio.space) skLib v1.1.0 (https://github.com/WheezyGold7931/skLib/) TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe) skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo) GameAPI v2.0.3 SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.5 DiscordSRV v1.23.0 (https://github.com/DiscordSRV/DiscordSRV) 
19.07 04:56:26 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
19.07 04:56:26 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
19.07 04:56:26 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
19.07 04:56:26 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
19.07 04:56:26 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
19.07 04:56:26 [Server] ERROR #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
19.07 04:56:26 [Server] ERROR #!#! 
19.07 04:56:26 [Server] ERROR #!#! Stack trace:
19.07 04:56:26 [Server] ERROR #!#! java.lang.NoSuchFieldError: hasDelayBefore
19.07 04:56:26 [Server] ERROR #!#!     at me.iblitzkriegi.vixio.commands.DiscordCommandRegistry.init(DiscordCommandRegistry.java:127)
19.07 04:56:26 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1097)
19.07 04:56:26 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1060)
19.07 04:56:26 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:751)
19.07 04:56:26 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:533)
19.07 04:56:26 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:420)
19.07 04:56:26 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:436)
19.07 04:56:26 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:532)
19.07 04:56:26 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1066)
19.07 04:56:26 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
19.07 04:56:26 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
19.07 04:56:26 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
19.07 04:56:27 [Multicraft] Skipped 40 lines due to rate limit (30/s)`

### Other

Help!

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
This is probably due to the changes of `Skript 2.6`. Try download this [Addon Patcher](https://github.com/TPGamesNL/RuntimeSkriptAddonPatcher/releases/download/v1.0/SkriptAddonPatcher-PR.jar) and put it in your server plugins, restart the server and see if this fixes your issue.

**Comment by TPGamesNL** [comment]
Caused by Vixio

**Comment by RORY112345** [comment]
Wait

**Comment by RORY112345** [comment]
It didn't work

**Comment by AyhamAl-Ali** [comment]
This issue tracker is only for Skript itself not its addons. The fix I sent should fix your issue however, you can go to [SkUnity's help channel](https://discord.gg/M9gz5vWV) and ask there
