### ISSUE TITLE
[Bug] Skript 2.6-beta2 not working

### ISSUE THREAD

**Issue by lolBoi9696** [SkriptLang/Skript#4202]
### Skript/Server Version

latest beta 2.6-beta2

### Bug Description

skript doesnt work

### Expected Behavior

skript to work

### Steps to Reproduce

download 2.6-beta2

### Errors or Screenshots

https://paste.md-5.net/pufurovazi.cs

### Other

no

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by APickledWalrus** [comment]
Try deleting the materials.json file. Let me know if this fixes your issue.

**Comment by lolBoi9696** [comment]
it stops it from erroring but it still crashes

**Comment by AyhamAl-Ali** [comment]
server version?

**Comment by lolBoi9696** [comment]
1.16.5

**Comment by lolBoi9696** [comment]
Also no skript sddons

**Comment by AyhamAl-Ali** [comment]
Then what and how it crashes? what happens exactly?

**Comment by lolBoi9696** [comment]
Idk it just crashes

**Comment by lolBoi9696** [comment]
I think it's my script I added but it doesn't even do much and I can't send rn cuz I'm on phone

**Comment by AyhamAl-Ali** [comment]
console errors? `just crashes` doesn't help us to know what is causing it at all

**Comment by lolBoi9696** [comment]
No errors

**Comment by AyhamAl-Ali** [comment]
then send the code once you can

**Comment by lolBoi9696** [comment]
I can send tmr

**Comment by lolBoi9696** [comment]
I'm pretty sure it's the script tho cuz once I remove it doesn't crash anymore

**Comment by lolBoi9696** [comment]
And also it crashes on any version of skript

**Comment by lolBoi9696** [comment]
Is it cuz I'm using a while loop in on join? In skript but pretty sure I don't it before and it was fine

**Comment by lolBoi9696** [comment]
Oh wait I forgot to add a wait 1 tock tick after all the code in the while loop oof

**Comment by AyhamAl-Ali** [comment]
Don't send new message in new comment, just edit your last comment, send the code when you can otherwise we can't do anything about it

**Comment by lolBoi9696** [comment]
I think I found the issue
