### ISSUE TITLE
Wood aliases are wrong

### ISSUE THREAD

**Issue by 18126** [SkriptLang/Skript#4206]
### Skript/Server Version

```
Skript Version: 2.6-beta2
Server Version: git-Tuinity-18 (MC: 1.17.1)
```

### Bug Description

When I write:
if player has 3 oak wood: - this gives error(can't understand this condition)
When I write:
if player has 3 stripped oak wood: - this works as expected

### Expected Behavior

It was suppose to not send me this error and let me make a .sk file with "oak wood"

### Steps to Reproduce

I just wrote the code

### Errors or Screenshots

```
https://prnt.sc/1dikvox
there is an if infront but it doens't show in error I don't know why, but there is an if :)
https://prnt.sc/1dil8ul
```

### Other

I want to ask how to check with arg 1 about how many items the player has. Like so:
https://prnt.sc/1dilyr7
The other text is in Bulgarian, don't mind it :)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by 18126** [comment]
It works with oak planks. Oak log works too but there is an item oak wood...

**Comment by TPGamesNL** [comment]
Try `oak bark`

**Comment by APickledWalrus** [comment]
`oak wood` is not a valid alias. You will have to use `oak bark` for now. This can be improved though and the alias can be made `(bark|wood)`.

**Comment by 18126** [comment]
Ok, thank you very much, can you tell me how to do this:
I want to ask how to check with arg 1 about how many items the player has. Like so:
https://prnt.sc/1dilyr7
The other text is in Bulgarian, don't mind it :)

**Comment by TPGamesNL** [comment]
Use `arg-1 of oak bark`

**Comment by APickledWalrus** [comment]
You would want to use `%number% or %item%` e.g `arg-1 of oak bark`

**Comment by 18126** [comment]
Doesn't work:
https://prnt.sc/1diriq0

**Comment by Matocolotoe** [comment]
> Doesn't work:
> https://prnt.sc/1diriq0

You forgot the 'of'...
