### ISSUE TITLE
Conditionals are broken in skript-nightly

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#4212]
### Skript/Server Version

```
[10:58:56] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[10:58:56] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[10:58:56] [Server thread/INFO]: [Skript] Server Version: git-Paper-119 (MC: 1.17.1)
[10:58:56] [Server thread/INFO]: [Skript] Skript Version: 2.6-beta2-nightly-6e7eca0
[10:58:56] [Server thread/INFO]: [Skript] Installed Skript Addons:
```

### Bug Description

In some cases "else" isn't working at all

### Expected Behavior

Else should work like it was in 2.5.3 

### Steps to Reproduce

```
every 1 seconds:
    if {pt} is set:
        if {pt} is greater than 0:
            set {pt} to {pt}-1
            broadcast "%{pt}%"
            wait 1 seconds
        else:
            delete {pt}
            broadcast "The End"
on script load:
    set {pt} to 10
```
In this code {pt} is not deleted then {pt} is 0

```
command /settest [<integer>]:
	trigger:
		set {test} to arg-1
command /whatstest:
	trigger:
		if {test} is 1:
			send "1"
		else if {test} is 2:
			send "2"
		else if {test} is 3:
			send "3"
		else if {test} is 4:
			send "4"
		else if {test} is 5:
			send "5"
		else:
			send "anything"
```

In this code when you reload skript and type /settest 1 and then /whatstest - it's working. Now without reloading skript type /settest 2 and /whatstest. It will not work (sends nothing). But when you reload skript - /whatstest command will work again as intended.

### Errors or Screenshots

First code on 1.16.5 with skript 2.5.3
![image](https://user-images.githubusercontent.com/36040466/126613472-9a310175-c2b6-44d4-8311-2f15b77cfa0c.png)
First code on 1.17 with skript-nightly
![image](https://user-images.githubusercontent.com/36040466/126614268-a988ddcc-fceb-457f-9cbf-f076f0f32b02.png)

Second code video: https://www.youtube.com/watch?v=k6XhLVKmUU8 (It's on a different nightly build but the effect on this one is the same)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Simple code to replicate:
```
command /test:
	trigger:
		loop 2 times:
			broadcast "start %loop-number%"
			if loop-number is 1:
				broadcast "true"
			else:
				broadcast "false"
			broadcast "end %loop-number%"
```
output:
```
```
