### ISSUE TITLE
raw slow

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/Skript#4222]
### Skript/Server Version

![Screenshot_1](https://user-images.githubusercontent.com/59025999/126898879-75b19e01-2783-4392-95d5-75ecf75ad902.png)

### Bug Description

raw slow instead of raw slot

### Expected Behavior

t instead of w

### Steps to Reproduce

use raw slot outside of inventory click event

### Errors or Screenshots

```
[Skript] Cannot use 'raw slow' outside of the inventory click event (ss.sk, line 4: set {_s} to name of slot clicked raw slot of event-inventory')
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
This is Skacket (addon) related see [this](https://github.com/TheLimeGlass/Skacket/blob/master/src/main/java/me/limeglass/skacket/elements/expressions/ExprRawSlot.java#L25)
