### ISSUE TITLE
Powder Snow Support

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/Skript#4227]
### Skript/Server Version

![Screenshot_3](https://user-images.githubusercontent.com/59025999/127124659-19f533a5-df18-41a3-9f09-14220873faec.png)

### Bug Description

Skript doesn't recognize powder snow and not giving its item.

### Expected Behavior

I expect skript will give me powder snow bucket when i write `give targeted block to player`

### Steps to Reproduce

place a powder snow
look at it
and use `!give targeted block to player`

### Errors or Screenshots

There is no error.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Powder snow is not the same as powder snow bucket, they are different items. This works the same for water, `give targeted block to player` with water does not give a water bucket either.
