### ISSUE TITLE
Skript MYSQL

### ISSUE THREAD

**Issue by VemcziN** [SkriptLang/Skript#4229]
### Skript/Server Version

2.2

### Bug Description

Hello, I have a problem with mysql on the server and sometimes the variables are not saved, someone had such a problem and somehow fixed it? Below are my database settings

Console log: [Skript] database error: Deadlock found when trying to get lock; try restarting transaction spigot

Database config:

databases:

database 1:

type: MYSQL
pattern: .*
monitor changes: true
monitor interval: 1 seconds
host: localhost
port: 3306
user: 4444aaaa
password: aaaaaaa
database: aaaaaaa
table: variables211

file: ./plugins/Skript/variables.db

backup interval: 1 hour

### Expected Behavior

--

### Steps to Reproduce

--

### Errors or Screenshots

 [Skript] database error: Deadlock found when trying to get lock; try restarting transaction

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Outdated Skript version
