### ISSUE TITLE
Very Slow load times

### ISSUE THREAD

**Issue by ehetteNandaYo** [SkriptLang/Skript#4230]
### Skript/Server Version

```
[17:03:20 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:03:20 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[17:03:20 INFO]: [Skript] Server Version: git-Purpur-1296 (MC: 1.17.1)
[17:03:20 INFO]: [Skript] Skript Version: 2.6-beta2
[17:03:20 INFO]: [Skript] Installed Skript Addons:
[17:03:20 INFO]: [Skript]  - Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[17:03:20 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[17:03:20 INFO]: [Skript]  - skript-db v1.3.3
[17:03:20 INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[17:03:20 INFO]: [Skript]  - SkQuery v4.1.5
[17:03:20 INFO]: [Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

Scripts take 1359% more time to load than in version 2.5.3

```
Skript version 2.5.3
[Skript] Loaded 32 scripts with a total of 58 triggers and 75 commands in 9.31 seconds
```

```
[Skript] Skript Version: 2.6-beta2
[Skript] Loaded 32 scripts with a total of 58 triggers and 75 commands in 2 minutes and 6.6 seconds
[Skript] Finished loading.
```

### Expected Behavior

Faster load times

### Steps to Reproduce

I have upgraded all my addons, tried to check them using SkriptAddonPatcher and none required upgrade

I tried to remove skript addons but load times were still slow, taking 20 seconds to load all scripts which is still twice more than loading all scripts with all other addons in version 2.5.3

only removing all the scripts the server loads quickly

### Errors or Screenshots

```
none
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by L3v3lup** [comment]
I can confirm this - but it seems to be caused by SkBee. Example code that take about 0.75s to reload:
`add "{Height: y+2}" to nbt of {_item}`

But i think Skript should handle NBT stuff. Its too important to rely on addons.

Ps.
There might be some skript parts, that Skript causes to load for a long time.
My Achievement skript also takes about 2 times as long to load compared to 2.5.3 - and i only use 2 lines with NBT.

**Comment by Moderocky** [comment]
> But i think Skript should handle NBT stuff. Its too important to rely on addons.
Skript will not be handling NBT since it is not a part of the Bukkit API

**Comment by TPGamesNL** [comment]
@ehetteNandaYo do you have a specific code (line, trigger, file, just something smaller than 32 scripts) that takes significantly longer to load?

**Comment by ehetteNandaYo** [comment]
> @ehetteNandaYo do you have a specific code (line, trigger, file, just something smaller than 32 scripts) that takes significantly longer to load?

After  l3v3lup comment, I noticed that SkBee really slowed the startup for 1 minute
lines like this " with custom model data 3505 with nbt "{HideFlags:1}""

removing that reduced the load by half but it wasnt until I completely removed the addon that load time reduced significantly...

**Comment by TheLimeGlass** [comment]
Does this still take a long time? 2.6 had big pattern adjustments and users have been seeing 25% faster loading times. @ehetteNandaYo

**Comment by AyhamAl-Ali** [comment]
Closing due to lack of response.
