### ISSUE TITLE
<condition> AND <condition> ??

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#4232]
### Skript/Server Version

[17:11:52 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:11:52 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[17:11:52 INFO]: [Skript] Server Version: git-Paper-133 (MC: 1.17.1)
[17:11:52 INFO]: [Skript] Skript Version: 2.6-beta2
[17:11:52 INFO]: [Skript] Installed Skript Addons:

### Bug Description

```
on right click:
	if {_value1} is not set:
		{_value3} is set
		send "{_value1} is not set"

	else if {_value2} is not set:
		send "{_value2} is not set"
```

There is a problem that the condition inside the if ~ else statement is also judged.

### Expected Behavior

If it was version 2.5.3, no message would have been printed.

this code prints "{_value2} is not set".
```{_value1} is not set``` and ```{_value3} is set``` operate as AND.

### Steps to Reproduce

```
on right click:
	if {_value1} is not set:
		{_value3} is set
		send "{_value1} is not set"

	else if {_value2} is not set:
		send "{_value2} is not set"
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by nfell2009** [comment]
I assume the inline if statement is causing the issue. Just change it to a normal if statement?

**Comment by vhone** [comment]
```
on right click:
	if {_value1} is not set:
		if {_value3} is set:
			send "{_value1} is not set"

	else if {_value2} is not set:
		send "{_value2} is not set"
```

Changing to "normal if statement" does not cause problems.

```
on right click:
	if {_value1} is not set:
		{_value3} is not set
		send "{_value1} is not set"

	else if {_value2} is not set:
		send "{_value2} is not set"
```

In this case, both messages are printed.

**Comment by iOshawott** [comment]
Did you try nightly build? https://github.com/SkriptLang/Skript/pull/4175 I think this pull request is fixing this problem and it's already merged :)

**Comment by vhone** [comment]
> Did you try nightly build? I think there's already pull request (#4175) that is fixing this problem, because I cannot reproduce it on my version of skript

Uh... I don't know how to build java source. If this issue has already been fixed, I will wait for the next update. thanks.

**Comment by iOshawott** [comment]
> > Did you try nightly build? I think there's already pull request (#4175) that is fixing this problem, because I cannot reproduce it on my version of skript
> 
> Uh... I don't know how to build java source. If this issue has already been fixed, I will wait for the next update. thanks.

You don't need to build it yourself! Go to actions https://github.com/SkriptLang/Skript/actions and download latest master build. (It will be it: https://github.com/SkriptLang/Skript/actions/runs/1062687996) But remember it's not official version so bugs can appear (but for me it's way more stable than beta2 in this moment)

**Comment by vhone** [comment]
> > 
> 
> You don't need to build it yourself! Go to actions https://github.com/SkriptLang/Skript/actions and download latest maste

Thank you for answer. I tested the code with skript-nightly. And no problems were found. It's already been fixed. thank you.
