### ISSUE TITLE
Math can break ceil function

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#4235]
### Skript/Server Version

```
[22:23:42] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:23:42] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[22:23:42] [Server thread/INFO]: [Skript] Server Version: git-Purpur-1053 (MC: 1.16.5)
[22:23:42] [Server thread/INFO]: [Skript] Skript Version: 2.5.3
[22:23:42] [Server thread/INFO]: [Skript] Installed Skript Addons:
[22:23:42] [Server thread/INFO]: [Skript]  - skript-gui v1.2.2 (https://github.com/APickledWalrus/skript-gui)
[22:23:42] [Server thread/INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[22:23:42] [Server thread/INFO]: [Skript]  - SkQuery v4.1.4

Tested it with 2.6 as well
```

### Bug Description

When you do some easy math, ceil function doesn't work as expected

### Expected Behavior

It should work as expected :p

### Steps to Reproduce

```
command /test:
	trigger:
		send "ceil from 7: %ceil(7)%"
		set {_x} to 100*0.07
		send "ceil from {_x} which is 7: %ceil({_x})%"

output:
[22:25:11] [Server thread/INFO]: ceil from 7: 7
[22:25:11] [Server thread/INFO]: ceil from {_x} which is 7: 8
```

### Errors or Screenshots

```
Not needed
```

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
Well that's how floating-point numbers are handled by computers : `System.out.println(100 * 0.07);` yields `7.000000000000001`

**Comment by iOshawott** [comment]
> Well that's how floating-point numbers are handled by computers : `System.out.println(100 * 0.07);` yields `7.000000000000001` therefore it "correctly" rounds it up to 8

So I need -0.01 all numbers before ceiling?

**Comment by Matocolotoe** [comment]
That's not as easily predictable as that, it only depends on how the result is actually represented as bits by the machine, so this "trick" wouldn't work. The only I could recommend you is to try and use actual integers as much as possible.

**Comment by Moderocky** [comment]
> That's not as easily predictable as that, it only depends on how the result is actually represented as bits by the machine, so this "trick" wouldn't work. The only I could recommend you is to try and use actual integers as much as possible.

Strict ought to fix the inconsistency.

**Comment by Aurelien30000** [comment]
```java
System.out.println(Math.ceil(100*0.07));
>>> 8.0
```

Java itself returns this value, how do you want to _fix_ such a thing?!

**Comment by iOshawott** [comment]
Well...

Firstly: I'm not java dev so there's no way I could know it
Secondly: For humans 100*0.07 is 7, not 7.000000000000001 so I see an inconsistency
Thirdly: @Matocolotoe what the hell are you talking about? If I remove 0.001 from the number it will always count what I want so I'll be doing it. I'm not talking that skript devs should use this way of interaction to fix it(!). You misunderstood me. Take a look that I'm doing tax system and I told my player's that from paying 100$ it'll be 7% tax. And now it's taking 8$. Somethings wrong.

`command /test:
	trigger:
		set {_x2} to 100*0.07-0.000000000000001
		send "ceil from {_x2} which is 6.99: %ceil({_x2})%"`

**Comment by Moderocky** [comment]
> ```java
> System.out.println(Math.ceil(100*0.07));
> >>> 8.0
> ```
> 
> Java itself returns this value, how do you want to _fix_ such a thing?!

It's an unintended side-effect of the way Skript handles numbers. Just because Java does it doesn't make it necessarily correct. Skript is significantly more basic and Skript users would expect this to follow traditional logic rather than computer peculiarity. It ought to be corrected for Skript, but the right approach needs to be considered.

**Comment by Matocolotoe** [comment]
> Secondly: For humans 100*0.07 is 7, not 7.000000000000001 so I see an inconsistency

You are not asking a human to perform the calculation.

**Comment by bluelhf** [comment]
Solution: Have someone else do it for you. Does BigDecimal handle floating point precision errors?

**Comment by Aurelien30000** [comment]
> Solution: Have someone else do it for you. Does BigDecimal handle floating point precision errors?

Not likely. This isn't an easy fix tbh.
