### ISSUE TITLE
"contain" code

### ISSUE THREAD

**Issue by YonoSigtuna** [SkriptLang/Skript#4237]
### Skript/Server Version

1.16.5

### Bug Description

on command "/test":
  cancel event
  set {_} to "1 3 4 5 6 7 8 9"
  if {_} contain "1" or "2":
    send "!"

![image](https://user-images.githubusercontent.com/86180648/127739783-907d8e74-da33-4fc2-ad5c-8bf224aef9f3.png)

### Expected Behavior

on command "/test":
  cancel event
  set {_} to "1 3 4 5 6 7 8 9"
  if {_} contain "1" or "2":
    send "!"

![image](https://user-images.githubusercontent.com/86180648/127739783-907d8e74-da33-4fc2-ad5c-8bf224aef9f3.png)

### Steps to Reproduce

on command "/test":
  cancel event
  set {_} to "1 3 4 5 6 7 8 9"
  if {_} contain "1" or "2":
    send "!"

![image](https://user-images.githubusercontent.com/86180648/127739783-907d8e74-da33-4fc2-ad5c-8bf224aef9f3.png)

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/86180648/127739783-907d8e74-da33-4fc2-ad5c-8bf224aef9f3.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by YonoSigtuna** [comment]
It is not 100% effective

**Comment by TPGamesNL** [comment]
Which Skript version do you use?

**Comment by YonoSigtuna** [comment]
> Which Skript version do you use?

2.6-beta1

**Comment by TPGamesNL** [comment]
I cannot replicate this issue, you're probably on the wrong Skript version since this was fixed in #4048:
![image](https://user-images.githubusercontent.com/29547183/127740198-614c40d7-729a-4290-bd98-9ed6cc648c3a.png)

To make sure you're on the right Skript version, use `/skript info`

**Comment by YonoSigtuna** [comment]
> I cannot replicate this issue, you're probably on the wrong Skript version since this was fixed in #4048:
> ![image](https://user-images.githubusercontent.com/29547183/127740198-614c40d7-729a-4290-bd98-9ed6cc648c3a.png)
> 
> To make sure you're on the right Skript version, use `/skript info`

![image](https://user-images.githubusercontent.com/86180648/127740272-706a9382-0bd6-4605-843c-42faa8eb0f9a.png)

**Comment by TPGamesNL** [comment]
That says 2.6-alpha1, which still has the bug. It is fixed in 2.6-beta1 and above

**Comment by YonoSigtuna** [comment]
> That says 2.6-alpha1, which still has the bug. It is fixed in 2.6-beta1 and above

oh...maybe it's right   thanks,bro
