### ISSUE TITLE
Glow Ink Sac

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/Skript#4239]
### Skript/Server Version

![Screenshot_2](https://user-images.githubusercontent.com/59025999/127750243-2e9915a3-7486-4375-8130-794d87299e6b.png)

### Bug Description

Skript drops glow ink sac as ink sac with enchant glow but gives glow ink sac as normal glow squid drop.

### Expected Behavior

I expect drops normal glow squid drop

### Steps to Reproduce

drop glow ink sac at player
give glow ink sac to player

### Errors or Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/59025999/127750260-70316e77-1e88-42e2-9c57-f2b66524681b.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by LowScarlet** [comment]
+ 1

**Comment by LowScarlet** [comment]
I don't know it yet but it seems reasonable

**Comment by LowScarlet** [comment]
you trick it with string parsed it as itemtype

**Comment by TheRealUnderscore** [comment]
Skellett has [glow item](https://skripthub.net/docs/?id=516) syntax, which seems to be conflicting with Skript's aliases.

**Comment by TPGamesNL** [comment]
The glow item expression is not Skript's, so this isn't a Skript issue. The two effects behaving differently is odd, but that will be fixed in #4260, so I'll keep this issue open for that.
