### ISSUE TITLE
Offline player lower case

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/Skript#4240]
### Skript/Server Version

![Screenshot_1](https://user-images.githubusercontent.com/59025999/127767086-63055970-4124-4934-b446-5d532fa148a4.png)

### Bug Description

parsed as offline player doesn't work

### Expected Behavior

I expect parsing a variable as offline player make the variable correct case sensitive.

### Steps to Reproduce

set {_s} to "alperenakoz1" parsed as offline player
send "%{_s}%"

### Errors or Screenshots

no error

### Other

Player's name is AlperenAkoz1 and parsing it as offline player when he is online works fine but parsing it when he is offline doesn't work.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
I can not replicate this:
![image](https://user-images.githubusercontent.com/29547183/127767412-3941a2d2-b465-484a-ba3e-c7d72d50a17a.png)

**Comment by UsainSrht** [comment]
The server I tried that is online-mode=false. Making online-mode=true solves the problem but I need to do that in offline mode.

**Comment by TPGamesNL** [comment]
In that case we won't solve this issue, Skript simply gets the offline player object with `Bukkit#getOfflinePlayer`. If anything, it's up to the server implementation to do something about this, although I doubt they will.
