### ISSUE TITLE
Offline Player Server Lag

### ISSUE THREAD

**Issue by KronosCloud** [SkriptLang/Skript#4254]
### Skript/Server Version

```
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Airplane-10 (MC: 1.16.5)
[Skript] Skript Version: 2.6-beta2
[Skript] Installed Skript Addons:
[Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

I think I found a bug when you have a command that does something with offline players and you enter a name that has never been on the server or has not been on the server for a long time, the server lags briefly and the TPS goes down too

### Expected Behavior

I think I found a bug when you have a command that does something with offline players and you enter a name that has never been on the server or has not been on the server for a long time, the server lags briefly and the TPS goes down too

### Steps to Reproduce

i used this code
```
command /profil [<offlineplayer>]:
	trigger:
		if arg-1 is set:
			set {_uuid} to uuid of arg-1
			if arg-1.hasPlayedBefore() = true:
				send "&7Profil of %arg-1%"
				send "&7Last online: &e%last login of arg-1%"
				if arg-1 is online:
					send "&7Online Status: &aOnline"
				else:
					send "&7Online Status: &cOffline"
			else:
				send "&7This &6player &7is &cnot &7in our &e&ldatabase&8!"
		else:
			send "&7Use&8: &c/profil &8(&ePlayername&8)"
```

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
This is to be expected, as the server will have to do a web request to get the UUID of the offline player, see [Bukkit#getOfflinePlayer(String)](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Bukkit.html#getOfflinePlayer(java.lang.String))
