### ISSUE TITLE
An error occurs when you click anvil inventory's slot

### ISSUE THREAD

**Issue by YonoSigtuna** [SkriptLang/Skript#4263]
### Skript/Server Version

none

### Bug Description

none

### Expected Behavior

none

### Steps to Reproduce

none

### Errors or Screenshots

none

### Other

sk version : 2.6-beta2

An error occurs when you click anvil inventory's slot

![image](https://user-images.githubusercontent.com/86180648/128727190-04900969-648c-4845-a1a0-35277995a951.png)

![bandicam 2021-08-09 22-56-23-007](https://user-images.githubusercontent.com/86180648/128727602-d79dd482-3667-46b5-8fdd-05bb89030e0c.gif)

![image](https://user-images.githubusercontent.com/86180648/128727628-9a35168f-fe8f-4945-a7e7-c4ee22d073f2.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
If anything, this is a server bug

**Comment by YonoSigtuna** [comment]
> If anything, this is a server bug (e.g. Spigot)

I think so... This is not the category of skript..
