### ISSUE TITLE
If the hex color tag is set to a variable, it does not work.

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#4276]
### Skript/Server Version

[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Paper-127 (MC: 1.17.1)
[Skript] Skript Version: 2.6-beta2-nightly-5a6633f
[Skript] Installed Skript Addons:

### Bug Description

If the hex color tag is set to a variable, it does not work.

It worked fine in the previous version. and It doesn't work in latest version.
The latest nightly version doesn't work either. so report it

### Expected Behavior

As well as variables, using the 'colored' expression does not work properly.

### Steps to Reproduce

```
command /chat.color:
    trigger:
        send "<##00ff00>█"
        send colored "<##00ff00>█"
        set {_value} to "<##00ff00>█"
        send {_value}
        send colored {_value}
        send uncolored {_value}
```

### Errors or Screenshots

![2021-08-14_15 55 11](https://user-images.githubusercontent.com/59043053/129438293-779862eb-62d7-4189-9990-5c755e74d97a.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by APickledWalrus** [comment]
Issue is that the color is likely being set to the color corresponding to the last character in that HEX string (&0 aka black as seen in the photo). HEX is very annoying to parse, especially due to it's weird format. This likely occurs within the parsing of `Utils#replaceChatStyles`.
