### ISSUE TITLE
compare itemtype

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#4278]
### Skript/Server Version

Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
Skript's documentation can be found here: https://skriptlang.github.io/Skript
Server Version: git-Paper-127 (MC: 1.17.1)
Skript Version: 2.6-beta2-nightly-bfe39b3

### Bug Description

I know aliases are itemtype.
However, when comparing items, the result was different from what I knew.

### Expected Behavior

If the type of item is paper
'is paper', 'is a paper' both must be true.

### Steps to Reproduce

```
command /compare.type:
    trigger:
        set {_item::1} to 1 of paper
        set {_item::2} to 2 of paper
        set {_item::3} to 3 of paper

        send "compape 'paper'"
        loop {_item::*}:
            if loop-value is paper:
                send "  is 'paper'"
            else:
                send "  not 'paper'"
                
        send "compape 'a paper'"
        loop {_item::*}:
            if loop-value is a paper:
                send "  is 'a paper'"
            else:
                send "  not 'a paper'"

        send "compape one of"
        loop {_item::*}:
            if 1 of loop-value is paper:
                send "  is paper"
            else:
                send "  not paper"
                
        send "compape type of"
        loop {_item::*}:
            if type of loop-value is paper:
                send "  is paper"
            else:
                send "  not paper"
```

### Errors or Screenshots

![2021-08-15_18 07 23](https://user-images.githubusercontent.com/59043053/129473300-5a98483f-f34d-4f71-8636-513646617e4f.png)

It behaves as if it were an item.
Does aliases contain the number of items?
Returns true only when the number of items also matches.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by APickledWalrus** [comment]
This is technically intentional behavior, but it can likely be changed to ignore stack size when comparing with an alias item.
