### ISSUE TITLE
Perfect code is not working: no errors.

### ISSUE THREAD

**Issue by XfedeX** [SkriptLang/Skript#4279]
### Skript/Server Version

```
> skript info
[16:58:01 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[16:58:01 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[16:58:01 INFO]: [Skript] Server Version: git-Paper-186 (MC: 1.17.1)
[16:58:01 INFO]: [Skript] Skript Version: 2.6-beta2
[16:58:01 INFO]: [Skript] Installed Skript Addons:
> _
```

### Bug Description

The following code for some reason "magically" stopped working:
```
every 1 seconds:
    loop all players:
        send "This code works" to loop-player
        if {curImg::%loop-player%} is not set:
            set {curImg::%loop-player%} to 1
            send action bar "Welcome to §6§lServer§f§lName" to loop-player
            teleport loop-player to {fede.hub}
        set {_a} to {curImg::%loop-player%}
        set {_a} to {picPos::%{_a}%}
        distance between loop-player and {_a} > 1:
            send "§aPicture %{curImg::%loop-player%}%" to loop-player
        teleport loop-player to location({_a}'s x position, {_a}'s y position, {_a}'s z position, loop-player's world, 0, 0)
        if {cooldown::%loop-player%} > 0:
            subtract 0.1 from {cooldown::%loop-player%}
            set loop-player's level to {cooldown::%loop-player%}
        #if loop-player's tool is not fermented spider eye:
        set loop-player's held item to fermented spider eye
        set name of loop-player's held item to "§6§lServer§f§lName"
        if {curImg::%loop-player%} is 0:
            stop
```

### Expected Behavior

It is expected to send "This code works" to all players. It doesn't do that and it doesn't run the lines of codes after "loop all players:"

### Steps to Reproduce

Paste the code in a new skript and reload scripts.

### Errors or Screenshots

```
There are no errors in console!
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
I can't replicate this:
![image](https://user-images.githubusercontent.com/29547183/129483393-fb42c684-2a3d-4d4c-b796-43a523032784.png)

Try removing parts of the code that aren't needed to replicate the bug, try changing the send effect to a broadcast, try adding a broadcast before the loop, make sure the script is loaded

**Comment by XfedeX** [comment]
> 
> 
> I can't replicate this:
> ![image](https://user-images.githubusercontent.com/29547183/129484886-407538d0-daa8-434e-9e77-9e336924f7a7.png)
> 
> Try removing parts of the code that aren't needed to replicate the bug, try changing the send effect to a broadcast, try adding a broadcast before the loop, make sure the script is loaded

It is loaded, another loop inside the same skript works fine.
It seems like if after some skript reloads it stops working, and then it randomly fixes.
I used Skript for over 15 months now, and I don't understand what's going on.

**Comment by TPGamesNL** [comment]
You forgot 3/4 of my comment:
Try removing parts of the code that aren't needed to replicate the bug, try changing the send effect to a broadcast, try adding a broadcast before the loop

**Comment by XfedeX** [comment]
> 
> 
> You forgot 3/4 of my comment:
> Try removing parts of the code that aren't needed to replicate the bug, try changing the send effect to a broadcast, try adding a broadcast before the loop

Before the loop the broadcast works fine, after the loop, even with all the code removed, it doesn't work.
But this issue somewhat only occurs when my Mineflayer 1.16.5 bots connect to the 1.17.1 server that has ViaVersion and ViaBackwards. I don't know if this is a ViaVersion/ViaBackwards bug, a Mineflayer protocol bug that makes the Via* bug occur, or a Skript bug. When i close the bots, the issue fixes, when i reopen them, the issue occurs again.

**Comment by TPGamesNL** [comment]
Try adding `broadcast "%all players%"` before the loop, and send here what it returns
