### ISSUE TITLE
bed leave event cannot be cancelled!

### ISSUE THREAD

**Issue by HW2955** [SkriptLang/Skript#4289]
### Skript/Server Version

```
![432434444](https://user-images.githubusercontent.com/67549588/129900568-209402f3-94f8-4554-b8fb-ed1f2da6d4ff.PNG)
```

### Bug Description

Bukkit event https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerBedLeaveEvent.html can be cancelled, thought the one in skript can't, if someone has a free second it would be nice to add

### Expected Behavior

(skript) bed leave event should be cancellable

### Steps to Reproduce

import:
    org.bukkit.event.player.PlayerBedLeaveEvent

#can be cancelled
on PlayerBedLeaveEvent:
    event.setCancelled(true)

#can't be cancelled
on bed leave:
    cancel event

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
PlayerBedLeaveEvent cancelling feature has been added in 1.16

**Comment by HW2955** [comment]
👍 got it
