### ISSUE TITLE
Variable maybe broken

### ISSUE THREAD

**Issue by Zzheyd** [SkriptLang/Skript#4292]
### Skript/Server Version

Skript 2.6-beta2
paper-1.17.1-196

Note: On 1.16 have NOT this issue

I'm using simple command : add player's tool to {MO_shovel::*}  <-- for add block on "list"

and i'm using this:
`on leftclick:
     if {MO_shovel::*} contains clicked block:
          ... run action` 

Example of  "MO_shovel" "dirt, sand and soul soil"

### Bug Description

Have NO error on load/reload skript, but, have no reaction in game on 1.17+, work fine on 1.16.

### Expected Behavior

Player's tool switch automatically when click on block of specified list

### Steps to Reproduce

Simple code to reproduce

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by APickledWalrus** [comment]
This *seems* to be a comparison issue between blocks and itemtypes, at least in the match quality required.
