### ISSUE TITLE
Debug messages display <none> for deleting changer

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4294]
Present for i'm assuming a long long time.

You have to have verbose set to debug.

### Bug Description

When you write code like 
```
delete {test}
```
the debug messages will display this
```
[Skript]   delete/clear <none>
```

### Expected:
```
[Skript]   delete/clear {test}(as java.lang.Object)
```

this is an order of operation issue. The debug message should contain the VariableName and not `<none>`

I'm assuming the debug message is called after it's executed, aka why it's deleted and displays `<none>`

This is for runtime execution debug, not parse time aka when a script is loaded (debug messages are sent both times)
The parse time debug message works fine.

**Comment by TheLimeGlass** [comment]
I have done more testing on this and it seems like it only happens very seldom. I have not figured out a cause, but it displays `<none>` from time to time.

**Comment by TPGamesNL** [comment]
I don't think this is an order of operation issue, the debug message (`TriggerItem#debug(Event, boolean)`) depends on the result of the effect, as the boolean parameter of the method indicates whether or not the next item will be ran (whether the section will be exited). This means that the method can only be called after the effect is executed (although a lot of elements that override the walk method don't seem to follow this behaviour). 

I think this is an issue with Variable's implementation of toString: I think it should give the variable name in all cases, but also include the value if `event` is not null.
