### ISSUE TITLE
Filter expression takes single input

### ISSUE THREAD

**Issue by Darkweasam** [SkriptLang/Skript#4306]
### Skript/Server Version

```
2.6-beta2
Paper version git-Paper-219 (MC: 1.17.1)
```

### Bug Description

This expression doesnt trigger at all anymore in my skript since I updated to 1.17

`loop all blocks in radius 1 around event-location where [location of input is not event-location]`

### Expected Behavior

It supposed to do what it says - loop all block in its radius except the block in the middle

### Steps to Reproduce
Placing a yellow wool on the side of an another yellow wool should broadcast the text "test2"

```
on place of yellow wool:
    loop all blocks in radius 3 around event-location where [location of input is not event-location]:
        broadcast "test"
        if loop-block is yellow wool:
            send "test2"
```

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Use `(all blocks in radius 3 around event-location) where [location of input is not event-location]`. 

Skript parses this as `all blocks in radius 3 around (event-location where [location of input is not event-location])`. We could disallow single expressions in the filter expression.

**Comment by Darkweasam** [comment]
Thank you, it works now! Weird because it worked fine in the previous versions as I needed
