### ISSUE TITLE
Aliases not properly updated with server after changing

### ISSUE THREAD

**Issue by DieHollanderMC** [SkriptLang/Skript#4307]
### Skript/Server Version

```
Replace this text with your output from the command.
```

### Bug Description

I tried using the 'aliases' tag without the use of the 'permission' tag in a command. I figured it wouldn't work when I only put 'aliases' without using another tag.

### Expected Behavior

The 'alias' tag should register a command.

### Steps to Reproduce

`command /test:
    aliases: t
    trigger:
        #action here`

### Errors or Screenshots

No errors.

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Can't replicate
```v
command /abc:
	aliases: a
	trigger:
		broadcast "1"	
```
![image](https://user-images.githubusercontent.com/20037329/131255757-414cc4ad-dc5d-4854-b4f9-cf634fc6037e.png)

Any errors? does that command say anything when executed?

**Comment by DieHollanderMC** [comment]
> Can't replicate
> 
> ```v
> command /abc:
> 	aliases: a
> 	trigger:
> 		broadcast "1"	
> ```
> 
> ![image](https://user-images.githubusercontent.com/20037329/131255757-414cc4ad-dc5d-4854-b4f9-cf634fc6037e.png)
> 
> Any errors? does that command say anything when executed? + Send your `/sk info`

Sorry, let me correct myself.
The command does work, but it doesn't register the way it should.
`command /test:
    aliases: testalias
    trigger:
        broadcast "a"`
https://i.imgur.com/nKxIvTu.png

As you can see, the text color is red, which would mean the command doesn't exist. Though it does execute.

**Comment by APickledWalrus** [comment]
Ah, this has to do with how Skript registers its commands. I don't think this is a bug, but more so something that could be improved :)

**Comment by DieHollanderMC** [comment]
> Ah, this has to do with how Skript registers its commands. I don't think this is a bug, but more so something that could be improved :)

Hm thats a little weird though, because it does show when you just use command /test:

**Comment by AyhamAl-Ali** [comment]
> As you can see, the text color is red, which would mean the command doesn't exist. Though it does execute.

Oh okay, maybe that's in 1.17 only? it doesn't look red in my 1.16 server with skript 2.6 as you can see in the picture I provided

> Ah, this has to do with how Skript registers its commands. I don't think this is a bug, but more so something that could be improved :)

I remember there was a comment on command aliases registering code to make them register as actual commands to fix such cases but I am not finding it in somehow

**Comment by AyhamAl-Ali** [comment]
Another bug found (actually the original bug):

When I changed the aliases from `a` to `h` the command `/skript:a` still exists in tab completion but when executed gives unknown command error but `/skript:h` doesn't exists in tab completion but works when executed

but this only happens when you update an existing command, if you create a new command and add aliases it will work as expected even the main topic if this issue will be fixed, so it is a bug with updating an existing command info

**Comment by APickledWalrus** [comment]
Technically this is a bug, as Skript does not sync commands in many cases where it should. This is one of those cases.
