### ISSUE TITLE
inventory display name always returns "Crafting"

### ISSUE THREAD

**Issue by Robypelle** [SkriptLang/Skript#4321]
### Skript/Server Version

```
Server Version: git-Paper-243 (MC: 1.17.1)
Skript Version: 2.6-beta2
 Installed Skript Addons:
 - skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders)
  - Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
  - skDragon v0.17
  - skRayFall v1.9.26 (https://sk.rayfall.net/)
  - TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe)
```

### Bug Description

i'm trying to perform an action depending on the name of the inventory opened by the player. 
To debug the issue i'm just printing in chat the name of the inventory to see if it is what i think it should be.
no errors after running the skript, i also tried every possible syntax

### Expected Behavior

when opening an inventory i should get in chat the name of the inventory, but i instead get "Crafting", indipendently by the name or type of inventory i open.

```
on inventory open:
    set {_invname} to display name of player's inventory
    send {_invname} to player
```

### Steps to Reproduce

run the code and open any inventory

### Errors or Screenshots

![immagine](https://user-images.githubusercontent.com/5002225/132144759-29d5de40-cd3c-46e1-b0df-b39379d74779.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by APickledWalrus** [comment]
Try `player's current inventory`

**Comment by Robypelle** [comment]
> 
> 
> Try `player's current inventory`

in that case nothing appears in chat, but no errors while running the skript

**Comment by wallace4BR** [comment]
Its probably minecraft side, since the inventory is not completely open maybe
```code
inventory open:
	wait a tick
	send "%name of player's current inventory%"
```
that does the trick

**Comment by Robypelle** [comment]
> 
> 
> Its probably minecraft side, since the inventory is not completely open maybe
> 
> ```
> inventory open:
> 	wait a tick
> 	send name of player's current inventory
> ```
> 
> that does the trick

you are right, it worked

**Comment by TPGamesNL** [comment]
You can probably also use `event-inventory` for this, without having to wait a tick
