### ISSUE TITLE
DB on Skript

### ISSUE THREAD

**Issue by sOxTw-Joel** [SkriptLang/Skript#4322]
### Suggestion

Hello, I'm trying to use Database data bases.
The Plugin that can be used in the configuration is really rare. Causa demaciado retrazo en mi servidor y hasta lo ha logrado romper.
What is the maneja? is there any other way to use data base?

### Why?

We need a data base to connect different servers.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment]
Can you show a crash log and your database config? Also, please make your entire message English.
