### ISSUE TITLE
Can't get last spawned dropped item after drop effect.

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#4325]
### Skript/Server Version

[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Paper-127 (MC: 1.17.1)
[Skript] Skript Version: 2.6-beta2-nightly-bfe39b3
[Skript] Installed Skript Addons:
[Skript]  - skript-reflect v2.2.2-dev (https://github.com/TPGamesNL/skript-reflect)

### Bug Description

Immediately after dropping an item into the world, I use 'last spawned dropped item' but get nothing.

strangely, if the on item spawn event is registered, i can normally receive dropped items.

### Expected Behavior

```
command /drop.item:
    trigger:
        drop stone at player
        send "%last spawned dropped item%"
```
The message is "<none>".
In the normal case it should return dropped item entity.

### Steps to Reproduce

```
on item spawn:
    true is true
command /drop.item:
    trigger:
        drop stone at player
        send "%last spawned dropped item%"
```
When the on item spawn event is registered in the server, the dropped item entity is properly received.

If an event has been registered in the server at least once, the dropped item can be received even if the event is removed through reload.

Only if the server is first loaded and there are no registered events will not receive dropped item.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
The syntax is different for dropped items try this `last dropped item`

**Comment by vhone** [comment]
> The syntax is different for dropped items try this `last dropped item`

oh, thanks.
