### ISSUE TITLE
Allow sorting based on expression with input

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#4327]
### Skript/Server Version

```
[19:25:23] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[19:25:23] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[19:25:23] [Server thread/INFO]: [Skript] Server Version: 3171-Spigot-610a8c0-fb556bf (MC: 1.17.1)
[19:25:23] [Server thread/INFO]: [Skript] Skript Version: 2.5.3
[19:25:23] [Server thread/INFO]: [Skript] Installed Skript Addons:
```
This was also tested on `2.6-Beta3` just wasn't on that server while making this

### Bug Description

When you go over to the docs you search `sorted` you'll see the expression `sorted %objects%` however whenever I run code such has ``send "%sorted (items within player's inventory)%"`` it just replaces with `<none>` while `send "%items within player's inventory%"` will respond correctly with all my items just not sorted

### Expected Behavior

I expected it to sort every item in my inventory
```
on inventory click:
  click type is middle mouse button
  set items within event-inventory to sorted items within event-inventory
```

### Steps to Reproduce

using this code it should replicate the same issue I've been getting
it'll load without any errors however sorting will just set it to `<none>`
```
on inventory:
  player's gamemode is survival
  click type is middle mouse button
  send "%sorted items within event-inventory%"
  # in skript 2.6-beta3 this'll just clear the inventory
  # set items within event-inventory to sorted items within event-inventory
```

### Errors or Screenshots

No errors are shown or sent to console

### Other

Not too sure if I should have put this under suggestion

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Mwexim** [comment]
How do think items should be sorted then? By amount? This doesn't really make sense to me.

**Comment by Fusezion** [comment]
> How do think items should be sorted then? By amount? This doesn't really make sense to me.

By name preferably it's no different than by alphabetically sorting text. well besides being items I don't mind the amount but sorting items to at least do `(stone, dirt, grass)` to `(dirt, grass, stone)` would be something cool to have

**Comment by TPGamesNL** [comment]
This isn't a bug:
![image](https://user-images.githubusercontent.com/29547183/132994074-ea258b96-2454-4285-8ae7-d1474d49b7f7.png)

I also don't think items should be comparable, but it would be a good idea to allow more sorting possibilities, such as `{_items::*} sorted with raw name of input`. For that, I'm marking this as an enhancement

**Comment by Pikachu920** [comment]
alternative syntax suggestion: `%objects% sorted based on %expression%`

**Comment by sluhtie** [comment]
Bump
