### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Fumio-26** [SkriptLang/Skript#4337]
### Skript/Server Version

[13:34:34 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:562)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

### Bug Description

My Skript Configuration:
http://transfer.sh/OKAIYq/archive-2021-09-22T203521+0700.tar.gz

### Expected Behavior

My server is stuck can't restart or stop

### Steps to Reproduce

http://transfer.sh/OKAIYq/archive-2021-09-22T203521+0700.tar.gz

### Errors or Screenshots

![2021-09-22_20h38_56](https://user-images.githubusercontent.com/89429493/134354306-b6a69ed1-3417-4596-b24f-b2b2f9aa8a1f.png)
`

### Other

Please help

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Please provide the information using pastebin or on github directly without downloading anything, the file you provided is considered dangerous in chrome

**Comment by TPGamesNL** [comment]
Most likely caused by an outdated version of skript-mirror, I recommend you update to skript-reflect.
