### ISSUE TITLE
check location in if statement

### ISSUE THREAD

**Issue by Llamasquishy** [SkriptLang/Skript#4338]
### Skript/Server Version

```
[20:18:33 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:18:33 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[20:18:33 INFO]: [Skript] Server Version: git-Paper-236 (MC: 1.17.1)
[20:18:33 INFO]: [Skript] Skript Version: 2.6-beta3
[20:18:33 INFO]: [Skript] Installed Skript Addons:
[20:18:33 INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[20:18:33 INFO]: [Skript]  - SkQuery v4.1.5
[20:18:33 INFO]: [Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
[20:18:33 INFO]: [Skript]  - RediSkript v1.3.3
```

### Bug Description

Using an "if statement" to check a location (of event-block, of a location variable, etc.) no longer works since updating to 2.6-beta3.

### Expected Behavior

`if location of event-block is location at 11.5, 39.5, 24.5 of the world "surv":`
This if statement should return as "true" if the block is at 11, 39, 24. It does not.

If you set a variable to `location of event-block` it sets it correctly as a location variable. However, within the if statement, it doesn't seem to check the location correctly anymore.

### Steps to Reproduce

```
on right-click on sign:
    if location of event-block is location at 11.5, 39.5, 24.5 of the world "surv":
        send "Success!" to player
    else:
        send "Failure." to player
    send location of event-block to player
```

Other test:

```
on right-click on sign:
    set {_signloc} to location of event-block
    if {_signloc} is location at 11.5, 39.5, 24.5:
        send "Success!" to player
    else:
        send "Failure." to player
    send "%{_signloc}%" to player
```

These both return in chat:

```
Failure.
x: 11.5, y: 39.5, z: 24.5
```

The right-clicked sign is at those coordinates.

### Errors or Screenshots

```
No errors in console when reloading or using the script.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Llamasquishy** [comment]
I have done more testing and found that this works with regular blocks like stone, dirt, etc. Even with a standing sign. However, with a sign mounted on a wall, it doesn't work. It shows the location correctly when setting the location of event-block to a variable, however when checking the location in an if statement, it only works on a standing sign, not one one that is on a wall.

**Comment by TheLimeGlass** [comment]
I don't understand how this would have worked in the past.

When checking a location, it's best to use the `distance between %location% and %location%` syntax, as a location has to be exact to 3 decimal points and 5 decimal points (y-coord). Also using `block at %location%` will center the location to the center of the block making the location standardized.

You can try using either of the solutions mentioned to solve the issue.

```
block at  location at 11.5, 39.5, 24.5 in the world "surv"
```

**Comment by TPGamesNL** [comment]
The reason this worked in previous versions, is because the location of a block did not include its direction, this was changed in https://github.com/SkriptLang/Skript/pull/4280.

As LimeGlass said above, you should not compare two locations like that if you don't want to also compare their directions, so use, for example, `distance between {_loc1} and {_loc2} is 0`
