### ISSUE TITLE
on gamemode spectator on inventory click is not work

### ISSUE THREAD

**Issue by CookTurtle** [SkriptLang/Skript#4339]
### Skript/Server Version

[Skript] Server Version: git-Paper-778 (MC: 1.16.5)
[Skript] Skript Version: 2.6-beta2
[Skript] Installed Skript Addons:
[Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[Skript]  - skript-yaml v1.4
[Skript]  - skDragon v0.17
[Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[Skript]  - SkQuery v4.1.5

### Bug Description

I'm design a skript when player died change gamemode to spectator when people move cancel event and open respawn gui to player and click item in inventory can run command for player and when I use "on inventory click:"event, nothing happend,but when I change player to creative or survival the command run correct.

### Expected Behavior

Player's gamemode shouldn't make "on inventory click" event doesn't work

### Steps to Reproduce

on player death cancel event and change player's gamemode to spectator and open GUI create a item and use "on inventory clock to run command and respawn player(change back to gamemode survival)

### Errors or Screenshots

https://youtu.be/7-evTudtZlA

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by DelayedGaming** [comment]
This has nothing to do with Skript.
You generally can't interact with ANY GUIS in spectator mode. This is a Minecraft thing.

**Comment by TPGamesNL** [comment]
Closing as this is not a Skript issue, rather an upstream one (no InventoryClickEvent is called)
