### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by BurnhamR** [SkriptLang/Skript#4343]
### Skript/Server Version

![image](https://user-images.githubusercontent.com/58826382/135416735-1dc31705-d729-4093-a0aa-129e36f6a1e9.png)

### Bug Description

Error on startup, Causing Console Spam/Flood

### Expected Behavior

No/Minimal error on starting

### Steps to Reproduce

Load Spigot 1.17.1 with Skript, Start the server, you'll see the error.

### Errors or Screenshots

```
https://pastebin.com/szUYfQAp
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by HW2955** [comment]
Use skript 2.6

**Comment by TPGamesNL** [comment]
Skript 2.5.3 does not support Minecraft 1.17, update to Skript 2.6-beta3: https://github.com/SkriptLang/Skript/releases
