### ISSUE TITLE
Multilore not working 

### ISSUE THREAD

**Issue by LupeCZ** [SkriptLang/Skript#4345]
### Skript/Server Version

[18:29:37 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[18:29:37 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[18:29:37 INFO]: [Skript] Server Version: git-Paper-281 (MC: 1.17.1)
[18:29:37 INFO]: [Skript] Skript Version: 2.6-beta3
[18:29:37 INFO]: [Skript] Installed Skript Addons:

### Bug Description

Not working multile line in inventory gui items lore with symbols ||

### Expected Behavior

|| should be character that makes text newline. I was working with Skript like 1 year ago and this character was always meant as newline. 

### Steps to Reproduce

I tried to change skript version to older betas, I checked SKUnity forum

### Errors or Screenshots

Code
```
 set {_gui} to a new chest inventory with 1 row with name "      &b&lGenerator upgrades" 
 if {coalpercentage.%player%} is not 0:
  set slot 0 of {_gui} to {coalpercentage.%player%} of coal ore with lore "&aActual percentage: || &c%{coalpercentage.%player%}%"
```
![obrazek](https://user-images.githubusercontent.com/40724446/135656032-6d10e86a-a366-4e93-9ae1-907699857526.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Lore in Skript was never done by the || text, this was a thing from SkQuery. Skript now has its own item with lore expression, with accepts multiple strings, e.g. `stone with lore "first line" and "second line"`
