### ISSUE TITLE
Damage cause was

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4347]
### Suggestion

Damage cause doesn't have a past self

### Why?

Damage cause needs a past tense to make the statement make more sense in English.

damage cause was a projectile

### Other

![qM8cjYd](https://user-images.githubusercontent.com/16087552/135733011-3edc3f2e-b76a-48bf-be04-22dbf3604cd9.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TheRealUnderscore** [comment]
What about [this condition](https://skriptlang.github.io/Skript/conditions.html#CondDamageCause)?

**Comment by TheLimeGlass** [comment]
> What about [this condition](https://skriptlang.github.io/Skript/conditions.html#CondDamageCause)?

It's an alternative, but this still errors.

**Comment by TPGamesNL** [comment]
Why does it make sense in English (also why damage cause but not other event values)?

**Comment by TheLimeGlass** [comment]
> Why does it make sense in English (also why damage cause but not other event values)?

That error is not from me. Someone else caused it, meaning it's more likely to happen. Damage cause is an expression and when referring to it, it's what caused the event to happen making the user write the statement as past tense.

Support for this should be added.

**Comment by TPGamesNL** [comment]
I think it'd be fine to change this, because the damage cause condition linked above also has the past tense in its syntax, so this should also be available to the damage cause expression.
