### ISSUE TITLE
Suggestion: "list" type, can be iterated

### ISSUE THREAD

**Issue by iamthewallrus** [SkriptLang/Skript#4356]
### Suggestion

I am suggesting that a "list" type be added to Skript.

Lists are defined like so:

{variable::*} <- list

{variable.something} <- not a list

The problem, there doesn't seem to be a type that can be used within functions that supports lists.

### Why?

It would make it easier to iterate over arrays (syn. lists) in functions.

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment]
You can use the plural form of the type, e.g. `numbers`, `texts` or `objects`. In the function `function doStuff(nums: numbers):`, `{_nums::*}` will be the input list

**Comment by iamthewallrus** [comment]
You sure?

Code:
`function iterate(arr: texts, p: player):
	loop {_arr}:
		send "%loop-value%" to player
		wait 2 seconds
`

yields:
Can't loop {_arr} because it's only a single value.

**Comment by iamthewallrus** [comment]
Oh wait, just realised what I'm doing wrong.

{_arr} should be {_arr::*}.

Makes sense.
