### ISSUE TITLE
Left and right click at same time not detected in adventure mode

### ISSUE THREAD

**Issue by yeetttt** [SkriptLang/Skript#4361]
### Skript/Server Version

```
Server Version: git-Paper-771 (MC: 1.16.5)

Skript Version: 2.5.3

Installed Skript Addons:
- SkUniversal v2.11.5
- Skellet v1.9.11
- MorkazSk v1.2
- skRayFall v.1.9.25
- Vixio v2.0.7
- SkBee v1.11.2
- TuSKe v1.8.2
- skript-holo v1.0.2
- WolvSK v1.7.2
- Skript-Packet v1.2

```

### Bug Description

While in adventure mode, when you right-click and left-click at the same time on a button or ender chest, it will not broadcast a sentence if you made a right click event in a script.

_Please note this only occurs in adventure mode_

### Expected Behavior

When right clicking and left clicking at the same time in adventure mode, it should have activated the right click event.

### Steps to Reproduce

1. Go into gamemode adventure
2. Make a right-click event in skript and make a broadcast with it
3. Right click and left click at the same time on a button or ender chest
4. Nothing will broadcast

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
I cannot replicate this and you're not on the latest version of Skript.

Are you sure this isn't an issue with addons?
