### ISSUE TITLE
please...

### ISSUE THREAD

**Issue by PrymeOS** [SkriptLang/Skript#4385]
### Suggestion

Not really a suggestion but can you tell me the Best way to update [TuSKe 1.9.1](https://github.com/szumielxd/TuSKe/releases/tag/v1.9.1) (i know most people say use skript-gui but the syntaxes are a pile of sh&t) I tried SkriptAddonPatcher but the classes only changed not Skript support i mean TuSKe 1.9.1 uses Skript 2.5.2 sources.

Please tell a way to fix this.

Thanks!

### Why?

*

### Agreement

- [ ] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by WeeskyBDW** [comment]
- Tuske is outdated, i suggest you to use skript-gui or GUI syntaxes in Skript itself

Anyway, this git repo isn't for addons support, but for skript issue reporting

**Comment by TPGamesNL** [comment]
As said above, if you have issues with an addon, report it to that addon's issue tracker, not here.
