### ISSUE TITLE
Item duplication bug when modifying "player's tool" while using left hand

### ISSUE THREAD

**Issue by oskarkk** [SkriptLang/Skript#4415]
### Skript/Server Version

```
[14:32:20 Server thread/INFO] [Skript] Server Version: git-Paper-373 (MC: 1.17.1)
[14:32:20 Server thread/INFO] [Skript] Skript Version: 2.6
[14:32:20 Server thread/INFO] [Skript] Installed Skript Addons:
```

No script addons, and no plugins other than Skript 2.6 and Essentials on the server.

### Bug Description

Item in player's right hand gets duplicated (appears in both hands) in event triggered by using left hand with script `clear lore of player's tool`.

### Expected Behavior

Clearing the item's lore if it exists.

### Steps to Reproduce

Script:

```
on block break:
  clear lore of player's tool
```

Take a pickaxe in your right hand, and water bucket in your right hand. Place the water somewhere and try to put it back in the bucket. Now you have two pickaxes.

Something like this doesn't clone the item:

```
command /test:
  trigger:
    clear lore of player's tool
```

So it's clearly a bug occurring only when using left hand. Looks like when modifying `player's tool` Skript does something like:
1. Copy the item held in the right hand to memory (regardless of which hand is actually used in the event)
2. Modify the item in memory
3. Save the modified item in the place of the hand that was actually used in the event

Looking at the ["tool" syntax](https://skriptlang.github.io/Skript/expressions.html#ExprTool):

`%living entities%'[s] ((tool|held item|weapon)|(off[ ]hand (tool|item)))`

... I'd say that the bug is in the 3rd point, because it seems like the `player's tool` should always be the right hand tool. and `player's offhand tool` should always be the tool in the left hand, regardless of what happened in the event.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Caused by [ExprTool.java#L84-L107](https://github.com/SkriptLang/Skript/blob/5dc603effff84222c7888c11a8747b4ec50acbde/src/main/java/ch/njol/skript/expressions/ExprTool.java#L84-L107)
