### ISSUE TITLE
Server crash on if condition

### ISSUE THREAD

**Issue by maxcom1** [SkriptLang/Skript#4418]
### Skript/Server Version

![image](https://user-images.githubusercontent.com/46265094/141204169-7ebda4f1-15b1-4223-9f97-68fca0176271.png)

### Bug Description

Hi!
When i add `if player has 32 of fence named "" and 3 of gate named "" and white bed named "" and log named "" and campfire named "":` in `on rightclick on player` event, skript is crashing the server (thread dumps).

### Expected Behavior

I'm trying to check if player has 32 of fence, 3 of gate, white bed, log and campfire without name.

Condition `if player has 32 of fence named "":
            if player has 3 of gate named "":
                if player has 3 of white bed named "":
                    if player has 16 of log named "":
                        if player has campfire named "":
                            send "ma.." to player` works, but I'd rather check it in one line

### Steps to Reproduce

```
on rightclick on player:
    event-entity's name contains "test-name"
    {player.serverstep::%player%} isn't -1

    if player has 32 of fence named "" and 3 of gate named "" and white bed named "" and log named "" and campfire named "":
        send "e" to player
```

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/46265094/141204504-762df370-4054-4dd6-9be2-2e28cff92983.png)
Thread dumps, server is shutting down after ~1 minute

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by TobyMinceraft** [comment]
Have you tried putting each condition on a new line instead of all at once? Skript generally doesn't like single-line conditions with multiple checks

**Comment by AyhamAl-Ali** [comment]
Skript parser can't parse very long lines, try to split them or try to add those items to a list and check if that player has that list

**Comment by Lennord** [comment]
Hello, I have pretty much the same problem with "if command is not...".

The more commands I put the more the error and the loading time takes a long time to load while I am in skript 2.6 Release and it works in skript 2.5.3.

[!] - I tried multiple lines and also tried to list in a variable but still the same problem.

Error: https://pastebin.com/mBs8GNpf

**Comment by AyhamAl-Ali** [comment]
it seems a problem with parsing long lines. @TPGamesNL probably have more info about the parser, could you take a look it this?

**Comment by TPGamesNL** [comment]
Skript has a hard time parsing longer lines. If you use longer lines, use parentheses to make it easier for Skript to parse: `if player has (32 of fence named "") and (3 of gate named "") and (white bed named "") and (log named "") and (campfire named ""):`

It's possible that Skript didn't take as long in 2.5.3, but that was due to a parsing bug that eliminated valid options early (see #4025).
