### ISSUE TITLE
can't use 'cancel event' in 'on command' event with commands that was created with Skript

### ISSUE THREAD

**Issue by noySq** [SkriptLang/Skript#4422]
### Skript/Server Version

```
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Purpur-1421 (MC: 1.17.1)
[Skript] Skript Version: 2.6
[Skript] Installed Skript Addons:
[Skript] - DiSky v2.1 (https://disky.itsthesky.info/)
[Skript] - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[Skript] - skRayFall v1.9.26 (https://sk.rayfall.net/)
[Skript] - SkBee v1.11.4 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

I want to cancel a command that I created using Skript with the 'on command' event, but nothing happens, the command will run, but it works with vanilla commands like '/plugins'. 

### Expected Behavior

It should cancel the command

### Steps to Reproduce

```
command /test2:
	trigger:
		send "test"
		
on command:
	executor is player
	if command isn't "test":
		cancel event
```

Try to run '/test2', and try to run a vanilla command like '/plugins'

### Errors or Screenshots

```
There is no error message or anything
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
I cannot replicate this on Skript 2.6, Paper 1.17. Are you sure this isn't caused by a plugin?

**Comment by TheLimeGlass** [comment]
I also can't replicate on 1.18.1 Skript 2.6. 

@noySq bump for TPGamesNL's comment.
