### ISSUE TITLE
shooting on version 1.12.2

### ISSUE THREAD

**Issue by dolyn0** [SkriptLang/Skript#4426]
### Skript/Server Version

![Zrzut ekranu (34)](https://user-images.githubusercontent.com/94494296/142080517-48d5674f-20bd-47e2-8f00-cb2ba6fc776d.png)

### Bug Description

I have a script for weapons and when I start to shoot the bullet starts to fly sideways, when it meets an obstacle it returns to its path

### Expected Behavior

.

### Steps to Reproduce

`command /bron:
	trigger:
		give 1 glistering melon named "&bSemi-Automatic Rifle" with lore "&4&l=====================" and "&7&lDamage &f40" and "&7&lAccuracy &f4" and "&7&lRecoil &f7" and "&7&lFire rate &f343" and "&7&lRange &f188" and "&4&l=====================" to player

on tool change:
	if player's tool is glistering melon:
		send "1/%{cel::%player%}%" to player
		set the player's level to 16
		set {cel::%player%} to 2
	else:
		set the player's level to 0
		remove slowness from the player
		
on rightclick with glistering melon:
	shoot snowball from player at speed 20
	
on leftclick with glistering melon:
	send "1/%{cel::%player%}%" to player
	if {cel::%player%} is 2:
		apply slowness 9999 to player for 9999 second
		send "3" to player
		set {cel::%player%} to 1
	else:
		remove slowness from the player
		set {cel::%player%} to 2`

### Other

If I have a weapon plugin it works normally and does not have this error 

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by HW2955** [comment]
Please take into consideration that when throwing entites at high speeds a bug occurs where it does in fact change its trajectory, this is an Minecraft issue, and will occur regardless if youre using a plugin or not.

**Comment by dolyn0** [comment]
And is it possible to somehow fix it or do something else about it ?

**Comment by AyhamAl-Ali** [comment]
As mentioned above, this is a known Minecraft visual bug. AFAIR there is no way to fix this and not sure if this was fixed in new MC versions

**Comment by TPGamesNL** [comment]
As said above, this isn't a Skript issue
