### ISSUE TITLE
Documentation slightly inconsistent regarding left clicking on entities

### ISSUE THREAD

**Issue by oskarkk** [SkriptLang/Skript#4429]
### Skript/Server Version

```
[06:43:40 Server thread/INFO] [Skript] Server Version: git-Paper-373 (MC: 1.17.1)
[06:43:40 Server thread/INFO] [Skript] Skript Version: 2.6
[06:43:40 Server thread/INFO] [Skript] Installed Skript Addons:
[06:43:40 Server thread/INFO] [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[06:43:40 Server thread/INFO] [Skript]  - Skellett v2.0.0 (https://forums.skunity.com/resources/skellett.24/)
[06:43:40 Server thread/INFO] [Skript]  - skript-yaml v1.4
[06:43:40 Server thread/INFO] [Skript]  - skDragon v0.17
[06:43:40 Server thread/INFO] [Skript]  - SkQuery v4.1.5
[06:43:40 Server thread/INFO] [Skript]  - SkBee v1.12.3 (https://github.com/ShaneBeee/SkBee)
[06:43:40 Server thread/INFO] [Skript]  - FunkySk v1.0.2
```

### Bug Description

Then I looked at `on click` documentation:
```
[on] [(right|left)[( |-)]][mouse[( |-)]]click[ing] [on %entity type/item type%] [(with|using|holding) %item type%]
[on] [(right|left)[( |-)]][mouse[( |-)]]click[ing] (with|using|holding) %item type% on %entity type/item type%
```
So it looks like I can do `on left click on minecart`, but then:
```
[23:52:56 Server thread/ERROR] A leftclick on an entity is an attack and thus not covered by the 'click' event, but the 'damage' event.
```
So maybe the documentation should be changed to something like:

```
[on] [right[( |-)]][mouse[( |-)]]click[ing] [on %entity type%] [(with|using|holding) %item type%]
[on] [right[( |-)]][mouse[( |-)]]click[ing] (with|using|holding) %item type% on %entity type%
[on] [(right|left)[( |-)]][mouse[( |-)]]click[ing] [on %item type%] [(with|using|holding) %item type%]
[on] [(right|left)[( |-)]][mouse[( |-)]]click[ing] (with|using|holding) %item type% on %item type%
```

That wouldn't suggest that you can detect left-clicking on an entity.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Minecarts are vehicles therefore this can be achieved using [vehicle damage](https://skriptlang.github.io/Skript/events.html#vehicle_damage) event

**Comment by oskarkk** [comment]
Oh, I don't know how I hasn't seen this. I'll leave the issue open because of the documentation thing.

**Comment by TPGamesNL** [comment]
A note could be added to the description, rather than a syntax change

**Comment by oskarkk** [comment]
A note would certainly be nice, but I think that it may be better to have more syntaxes that are shorter and more precise, than few long and sometimes confusing syntaxes.

**Comment by TPGamesNL** [comment]
> A note would certainly be nice, but I think that it may be better to have more syntaxes that are shorter and more precise, than few long and sometimes confusing syntaxes.

On the other hand, someone might look at the syntax and wonder why there isn't a way to detect left clicking on an entity. If the syntax exists for it, they would use it and see why this is and how to fix it.

**Comment by oskarkk** [comment]
I've meant that I think that 4 shorter syntaxes are better than 2 longer, and a note should be added anyway. Making users learn from errors is less preferable. Hmm, now that I think about it, this error:

`A leftclick on an entity is an attack and thus not covered by the 'click' event, but the 'damage' event.`
 
... could be changed to something like:

`A leftclick on an entity is an attack and thus not covered by the 'click' event, but the 'damage' and 'vehicle damage' events.`

Because I think that's why I didn't even try to search for `on vehicle damage`.

**Comment by AyhamAl-Ali** [comment]
@TPGamesNL Can you assign this to me please

**Comment by TPGamesNL** [comment]
> @TPGamesNL Can you assign this to me please

Done 🙃

**Comment by TheLimeGlass** [comment]
@AyhamAl-Ali @Moderocky commit auto closed this.
