### ISSUE TITLE
CI Paper mc api changed: tests fail

### ISSUE THREAD

**Issue by Olyno** [SkriptLang/Skript#4439]
### Skript/Server Version

/

### Bug Description

Because the paper api changed, tests in the ci now fail. Infos: https://github.com/SkriptLang/Skript/runs/4316945484?check_suite_focus=true#step:5:22

### Expected Behavior

Tests of CI should still work.

### Steps to Reproduce

Simply make a pr

### Errors or Screenshots

https://github.com/SkriptLang/Skript/runs/4316945484?check_suite_focus=true#step:5:22

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
New link syntax: https://papermc.io/api/v2/projects/paper/versions/1.12.2/builds/1618/downloads/paper-1.12.2-1618.jar

Useful links:
https://papermc.io/api/v2/projects/paper/versions/1.12.2
https://papermc.io/api/v2/projects/paper/versions/1.12.2/builds/1618
https://papermc.io/api/v2/projects/paper/versions/1.12.2/builds/1618/downloads/paper-1.12.2-1618.jar

Same for other versions
