### ISSUE TITLE
"On jump" event or alternative?

### ISSUE THREAD

**Issue by Weefle** [SkriptLang/Skript#444]
Please add the "on jump" event or please say me an alternative :/
I use the latest spigot-1.11.2 and the latest skript-dev25

**Comment by bensku** [comment]
Please suggest jump event to Spigot team, and if it ever gets added, open new issue.

Sadly there is no alternative; even using a plugin wouldn't really help, since it is mainly Spigot (or Vanilla?) issue.

**Comment by TheLimeGlass** [comment]
Use RandomSk or Skellett Custom events and test for when the player's `JUMP` statistic is increased. Much better event. This is why Spigot doesn't add any Jump event. Use this.

Suggestion to add this though. You would have to add statistic support though if this event was added.

**Comment by Weefle** [comment]
Ok, thank you for your answers! :D

**Comment by TheLimeGlass** [comment]
Less than 24% of Skript users actually use paper. Pika was going to add statistics support after this came out. Which is what should be implemented rather than this.

**Comment by Blueyescat** [comment]
Everyone should use Paper and 1.12.2+, however this is not even an issue, platform dependent features are fine. And also support for Paper 1.12.2- can be added using statistic increment event with a note "can't be cancelled"..

**Comment by Nicofisi** [comment]
Good point @Blueyescat, the ability to cancel the event is a huge pro
