### ISSUE TITLE
Skript doesn't save variables

### ISSUE THREAD

**Issue by crazedorangutan** [SkriptLang/Skript#4442]
### Skript/Server Version

![2021-11-25_08 32 06](https://user-images.githubusercontent.com/95040748/143468869-6e75478e-da3d-44ed-a668-f98e5d2685d5.png)

### Bug Description

Whenever a variable is changed, it sets the variable in RAM, but the variable storage file doesn't change. This makes the variables revert back to their original form on shutdown. I was able to fix this by deleting the skript file and .jar file and reinstalling, but later that day the problem came up again.

### Expected Behavior

Variables save to the variable.csv file. I was monitoring the file when it was working after I reinstalled skript the file would update when I changed a variable. But no longer does that

### Steps to Reproduce

I don't know how this bug even happened, so I can't say anything here

### Errors or Screenshots

Weird thing is I don't get any errors in console. In fact I don't see any thing from Skript during shutdown, and on start up it works fine:
[15:16:36 INFO]: [Skript] Loading variables...
[15:16:36 INFO]: [Skript] Loaded 138 variables in 0.0 seconds

### Other

I don't think this is a problem with any addons I have because I've had them long before these problems occurred, but I'll try testing it out without the addons

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by bluelhf** [comment]
How are you shutting down the server? By default Skript only saves variables to the file occasionally and it can fail to save if you shut the server down without letting it execute its shutdown hooks

**Comment by crazedorangutan** [comment]
I'm using Minehut so whenever the server hibernates even the variables get lost, but also when you press Stop or Restart. And I would let it sit for a while after setting a variable to see if it would show up in the folder after a while but it never did

**Comment by crazedorangutan** [comment]
Tried uninstalling all my addons, but they keep regenerating themselves somehow

**Comment by bluelhf** [comment]
> I'm using Minehut so it just automatically shutsdown whenever the server hibernates but also when you press Stop or Restart. And I would let it sit for a while after setting a variable to see if it would show up in the folder after a while but it never did

Minehut uses [their own fork of Skript](https://github.com/Minehut/Skript/), and considering your addons keep regenerating themselves somehow, this definitely sounds more like an issue with Minehut than Skript... Can you reproduce this on a local server (outside of Minehut) running the version of Skript available [here](https://github.com/SkriptLang/Skript/releases/download/2.6/Skript.jar)?

**Comment by TPGamesNL** [comment]
If you reproduce this on a local server, you can reopen this issue / open another, and include your config.sk and server log (make sure to try without addons on a local server)

**Comment by crazedorangutan** [comment]
> > I'm using Minehut so it just automatically shutsdown whenever the server hibernates but also when you press Stop or Restart. And I would let it sit for a while after setting a variable to see if it would show up in the folder after a while but it never did
> 
> Minehut uses [their own fork of Skript](https://github.com/Minehut/Skript/), and considering your addons keep regenerating themselves somehow, this definitely sounds more like an issue with Minehut than Skript... Can you reproduce this on a local server (outside of Minehut) running the version of Skript available [here](https://github.com/SkriptLang/Skript/releases/download/2.6/Skript.jar)?

I actually redownloaded Skript from Github because with their new addons page Skript isn't on it

**Comment by Daniel361-pixel** [comment]
i have this problem too
