### ISSUE TITLE
Variables.csv file sometimes don't get saved

### ISSUE THREAD

**Issue by itamar1347** [SkriptLang/Skript#4449]
### Skript/Server Version

```
![image](https://user-images.githubusercontent.com/31416473/143765175-5d9ec2a3-235e-46b3-bf87-1a9ff2a275cf.png)[image]

```

### Bug Description

I have an issue in my server, My variables.csv file sometimes get saved and sometimes not, I'm not really sure why this is happening every time before I restart the server I make sure it saves all.

Sometimes I try to modify couple of variables:

Money (I use custom eco script)
Rank
Crystals

And for some reason only half of the times they get saved the other half they get rolled back to the second the server opened (Basically previous restart)

### Expected Behavior

They variables.csv file was supposed to save every time I ran /save-all

### Steps to Reproduce

I have no idea really. I did not do anything unusual.

### Errors or Screenshots

```

[2021-11-28T11_09_43.zip](https://github.com/SkriptLang/Skript/files/7613402/2021-11-28T11_09_43.zip)
this is couple of logs from 3 different restarts
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
We don't support previous versions, only the latest, 2.6
