### ISSUE TITLE
Script parsing if file doesn't exist

### ISSUE THREAD

**Issue by Olyno** [SkriptLang/Skript#4459]
### Skript/Server Version

**Skript:** 2.6
**Spigot:** 1.16.5

### Bug Description

When (re)loading a script which doesn't exist, it throws function errors (this function already exists....)

### Expected Behavior

We should have the "This script doesn't exist"

### Steps to Reproduce

- ``/skript reload myScript``

### Errors or Screenshots

![See error: https://cdn.discordapp.com/attachments/917895984527327262/917895991359832095/unknown.png](https://cdn.discordapp.com/attachments/917895984527327262/917895991359832095/unknown.png)

### Other

I guess the issue comes from [this commit](https://github.com/SkriptLang/Skript/commit/d1b555dbd5f051442c7cbfd46ac01f847debf47f), nothing sure

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

*Reported by @janis4269*

**Comment by AyhamAl-Ali** [comment]
More info can be found [in discord](https://discord.com/channels/135877399391764480/917898634404692028/917911358094336072)
