### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by nTreetHub** [SkriptLang/Skript#4460]
### Skript/Server Version

[ERROR] #!#! Skript: 2.2-dev36

[ERROR] #!#! Bukkit: 1.17.1-R0.1-SNAPSHOT

[ERROR] #!#! Minecraft: 1.17.1

[ERROR] #!#! Java: 16.0.1 (OpenJDK 64-Bit Server VM 16.0.1+9)

[ERROR] #!#! OS: Linux amd64 4.15.0-156-generic 

### Bug Description

When I start a server, plugin isn't being loaded

### Expected Behavior

Plugin should load

### Steps to Reproduce

Go to server.pro hosting
then go to the files
install the plugin in the plugin folder
start the server

### Errors or Screenshots

[ERROR] #!#!

[ERROR] #!#! [Skript] Severe Error:

[ERROR] #!#!

[ERROR] #!#! Something went horribly wrong with Skript.

[ERROR] #!#! This issue is NOT your fault! You probably can't fix it yourself, either.

[ERROR] #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).

[ERROR] #!#! This ensures that your issue is noticed and will be fixed as soon as possible.

[ERROR] #!#!

[ERROR] #!#! Stack trace:

[ERROR] #!#! java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Effect.getName()'

[ERROR] #!#! at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:196)

[ERROR] #!#! at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:63)

[ERROR] #!#! at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:269)

[ERROR] #!#! at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:891)

[ERROR] #!#! at ch.njol.skript.Skript.onEnable(Skript.java:336)

[ERROR] #!#! at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)

[ERROR] #!#! at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)

[ERROR] #!#! at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)

[ERROR] #!#! at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:520)

[ERROR] #!#! at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:434)

[ERROR] #!#! at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619)

[ERROR] #!#! at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266)

[ERROR] #!#! at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010)

[ERROR] #!#! at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)

[ERROR] #!#! at java.base/java.lang.Thread.run(Unknown Source)

[ERROR] #!#!

[ERROR] #!#! Version Information:

[ERROR] #!#! Skript: 2.2-dev36

[ERROR] #!#! Bukkit: 1.17.1-R0.1-SNAPSHOT

[ERROR] #!#! Minecraft: 1.17.1

[ERROR] #!#! Java: 16.0.1 (OpenJDK 64-Bit Server VM 16.0.1+9)

[ERROR] #!#! OS: Linux amd64 4.15.0-156-generic

[ERROR] #!#!

[ERROR] #!#! Server platform: Spigot

[ERROR] #!#!

[ERROR] #!#! Current node: null

[ERROR] #!#! Current item: null

[ERROR] #!#!

[ERROR] #!#! Thread: Server thread

[ERROR] #!#!

[ERROR] #!#! Language: english

[ERROR] #!#! Link parse mode: DISABLED

[ERROR] #!#!

[ERROR] #!#! End of Error.

[ERROR] #!#! 

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
We only support the latest version of Skript, currently 2.6. You are using 2.2-dev36
