### ISSUE TITLE
Can't send message to a player in a variable with Skript 2.6

### ISSUE THREAD

**Issue by HC-Emro** [SkriptLang/Skript#4462]
### Skript/Server Version

```
Paper 399 (1.17.1)
Skript 2.6
```

### Bug Description

With Skript 2.6, we can't send message to a player in a variable with this syntax:

`send "test" to {_player}`

We have to use:

`send "test" to {_player} from {_player}`

### Expected Behavior

Sending a message to the player in the variable but it's not working until we add the "from {_player}"

### Steps to Reproduce

command /test:
 trigger:
  set {_p} to player
  send "test" to {_p} # NOT WORKING

### Errors or Screenshots

```
No errors
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by kossnikita** [comment]
```
command /test:
	trigger:
		set {_p} to the player
		send "It works?" to {_p}
```
![image](https://user-images.githubusercontent.com/39294101/145764369-4a568dba-7774-47c2-b7e9-fc2aaf11e5d7.png)

**Comment by DelayedGaming** [comment]
If you have DiSky v3 ARK installed, you have to change `ParsingSendEffect` in `plugins/DiSky/config.yml` from `false` to `true`, and restart server after.

**Comment by HC-Emro** [comment]
Yeah, thx.
