### ISSUE TITLE
Long Lines Result in Significant Delay and Crashing

### ISSUE THREAD

**Issue by BenguMC** [SkriptLang/Skript#4463]
### Skript/Server Version

```
I've used the latest 2.6 release and the latest nightly build release with the same results. This issue was not present in 1.16.5 Minecraft and associated Skript builds. 
```

### Bug Description

Lines containing enchants, names and long lore cause significant loading delays on the newest Skript builds. Something in the parsing is delaying the load times and even crashing client connections on reloads. 

### Expected Behavior

The skripts load instantly on 1.16.5 with previous builds. I expect them to load instantly. 

### Steps to Reproduce

Use this code:

on load:
	set {Test::Item} to 1 of diamond sword of sharpness 3 and looting 5 named "This is a test sword with a very long name" with lore "This lore is very long" and "and so is this specific line" and "which for whatever reason" and "in Skript 2.6 makes the load times" and "completely unbearable" and "and sometimes even makes the game crash"

### Errors or Screenshots

```
No errors in game or console, just significant delays in load times. 
```

### Other

This is a new issue to 1.17.1 as far as I can tell and is not addon dependent. 

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by nfell2009** [comment]
This has been a problem of Skript for a while now. What's best is to break the single line down into its respective syntax elements.
```
set {test::item} to 1 diamond sword of sharpness 3 and looting 5
set name of {test::item} to "name"
...
```

**Comment by BenguMC** [comment]
You're breaking my heart, Baefell :(

I still love u

any hopes this will be fixed in the future?

**Comment by nfell2009** [comment]
Wait... I know you... Pop up sometime ;)

It'd require a lot of changes to how Skript parses. Iirc there was a branch that someone was looking at reworking parsing but I'm not sure how far it got.

**Comment by TPGamesNL** [comment]
This is a known thing, and probably won't be fixed with how Skript is designed
