### ISSUE TITLE
script[s] [%strings%] (is|are) loaded gives error

### ISSUE THREAD

**Issue by PersonMaster** [SkriptLang/Skript#4467]
### Skript/Server Version

```
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Paper-399 (MC: 1.17.1)
[Skript] Skript Version: 2.6
[Skript] Installed Skript Addons: 
[Skript]  - Skent v3.1.0
[Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[Skript]  - SkQuery v4.1.5
[Skript]  - SkBee v1.14.0 (https://github.com/ShaneBeee/SkBee)
[Skript]  - SkJade v1.3.4 (https://www.github.com/Ankoki-Dev/SkJade)
[Skript]  - Skript-Packet v2.0.1 (www.github.com/Anarchick/skript-packet)
[Skript] Installed dependencies: None
```

### Bug Description

When you are using the script condition `script[s] [%strings%] (is|are) loaded`, you are instead faced with a console error.

### Expected Behavior

Skript should instead check if the specified script is loaded/unloaded.

### Steps to Reproduce

I used the effect `!broadcast "&aTrue" if script "Test.sk" is loaded`, but I have also tested it with scripts.

### Errors or Screenshots

https://www.toptal.com/developers/hastebin/cequmafige.md

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by nfell2009** [comment]
What error log happens when you do it in a script?

**Comment by FalseFusion** [comment]
Interestingly enough, there is no console error.

**Comment by AyhamAl-Ali** [comment]
[Line 61](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/conditions/CondScriptLoaded.java#L61): Shouldn't be hard to fix, just handle it in effect commands since `getParser#getCurrentScript()` is marked as **Nullable**
