### ISSUE TITLE
💡 Add docs link as repo website

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#4471]
### Suggestion

Add the official docs link as the repo's website link
![image](https://user-images.githubusercontent.com/20037329/146897618-9529779c-c0a1-405b-855a-f6faf5bc40cd.png)

### Why?

Will be easier to find for newcomers and a good look ahead of Skript

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by Cerquaas** [comment]
Similar: Put the latest Skript download on the docs.

**Comment by AyhamAl-Ali** [comment]
> Similar: Put the latest Skript download on the docs.

Already in there 
![image](https://user-images.githubusercontent.com/20037329/147359542-86eda5ab-be7e-458d-88ee-bc316ed59e54.png)

**Comment by APickledWalrus** [comment]
Added 👍
