### ISSUE TITLE
Unable to make a "Most Damage Dealt" for boss kill.

### ISSUE THREAD

**Issue by qowq** [SkriptLang/Skript#4481]
### Skript/Server Version

1.18/1.17

### Bug Description

I have a skript that spawns a boss with loads of health and buffs. I am trying to make a skript so that the top 3 people who dealt most damage get rewards for killing the boss, yet i can't seem to get a total damage or damage top, or most damage thing. please help.

### Expected Behavior

What was supposed to happen was for the boss to be defeated and then a broadcast saying 1. (name) >> 304 damage    2. (name) 241 damage    3. (name) >> 194 damage

and then with that rewards would be given to the top 3.

### Steps to Reproduce

Can't seem to make it.

### Errors or Screenshots

https://user-images.githubusercontent.com/96666855/147393805-9129a50c-0f4a-4c9e-b898-d126b71c1e22.png

this above is what i want to happen. it is from another server yet it happens automatically once the boss is killed. please help.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by APickledWalrus** [comment]
This platform isn't intended for help with creating scripts. However, there are a few discords where you will find people able to help you with this specific problem. Check out https://github.com/SkriptLang/Skript#relevant-links
