### ISSUE TITLE
"group of player" and "player's group" returns "<none>"

### ISSUE THREAD

**Issue by erenkarakal** [SkriptLang/Skript#4486]
### Skript/Server Version

![image](https://user-images.githubusercontent.com/67760502/147676753-6bb36f7e-feb4-4929-8f8e-12ba7690c268.png)

Purpur 1.17.1
Luckperms v5.3.89 (latest on luckperms page)
Vault v1.7.3-b131 (latest on spigotmc page)

### Bug Description

"%player's group%" and "%group of player%" returns <none>
![unknown](https://user-images.githubusercontent.com/67760502/147676955-8b20100d-ebe3-43d7-ae23-31e21276c180.png)
>

### Expected Behavior

Return player's groups

### Steps to Reproduce

```
on load:
  loop all players:
    broadcast "%player's group%"
    broadcast "%player's groups%"
    broadcast "%group of player%"
```

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
`group of player` requires valut to work, do you have it?

**Comment by erenkarakal** [comment]
> `group of player` requires valut to work, do you have it? Also if Luckperms doesn't share such info with vault then skript can't retrieve that

yes, I have vault, I mentioned the versions above, it shows that vault hooked into luckperms when I run /vault-info

**Comment by TPGamesNL** [comment]
You used `player`, not `loop-player` in an on load event
