### ISSUE TITLE
Error With Returning Something Inside of a Function that Teleports

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [SkriptLang/Skript#4491]
### Skript/Server Version

```
08.01 18:58:30 [Server] INFO [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
08.01 18:58:30 [Server] INFO [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
08.01 18:58:30 [Server] INFO [Skript] Server Version: git-Paper-"cc43ba7" (MC: 1.17.1)
08.01 18:58:30 [Server] INFO [Skript] Skript Version: 2.6
08.01 18:58:30 [Server] INFO [Skript] Installed Skript Addons:
08.01 18:58:30 [Server] INFO [Skript]  - SkBee v1.14.0 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

If you include `teleport` inside of a function that returns something, it errors.

### Expected Behavior

No errors

### Steps to Reproduce

Use this function (or any function with teleporting and a return statement)
```
function tpTest(p: player) :: boolean:
    teleport {_p} to spawn of {_p}'s world
    send "&aTeleporting..." to {_p}
    return true
```
Then reload the script

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/70504198/148656359-fdbe0968-c348-4dc8-bb31-e48eb3ef5c01.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
The teleport effect is delayed by default (since #3478), therefore you can't do things like cancelling events or return a value in a function after it. You can use the keyword `force` before the effect (e.g. `force teleport {_p} to {_loc}`) to make it not async (delayed) by default
