### ISSUE TITLE
Cant have more loops at the same time

### ISSUE THREAD

**Issue by 0w0Senpai** [SkriptLang/Skript#4495]
### Skript/Server Version

on rightclick with ghast tear:
	cancel event
	add 1 to {count}
	spawn 1 armor stand above player
	set {_ammo::%{count}%::%player%} to last spawned armor stand
	set helmet of {_ammo::%{count}%::%player%} to {bubble}
	add "{NoGravity:1b,Small:1,Invisible:1,NoBasePlate:1}" to nbt of {_ammo::%{count}%::%player%}
	set {_pos} to {_ammo::%{count}%::%player%}'s position
	loop 30 times:
		if block above {_ammo::%{count}%::%player%} is light or air:
			set {_pos} to {_ammo::%{count}%::%player%}'s position
			teleport {_ammo::%{count}%::%player%} forwards {_pos}
			wait 3 tick
		else:
			cancel event
			kill {_ammo::%{count}%::%player%}
			
on right click on armor stand:
	cancel event

command a:
	trigger:
		message "%{count}%"

### Bug Description

when another amorstand spawns the other stop moving

### Expected Behavior

should not stop when another one spawns

### Steps to Reproduce

i just skripted this i taught it would work

### Errors or Screenshots

[LINK TO VIDEO](https://youtu.be/CHljEiD7Sj4)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
This isn't a place for Skript help, this is for bug reports to Skript itself and suggestions, I recommend visiting the skUnity Discord for Skript help: https://discord.gg/0l3WlzBPKX7WNjkf
