### ISSUE TITLE
Add to Do If

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [SkriptLang/Skript#4496]
### Suggestion

My suggestion is to add `else` to the `do if` effect.
Right now, you can do something like `send "you are op!" to player if player is op`, and my suggestion is to make it so you could also do `send "you are op!" if player is op, else send "you are not op!"`

### Why?

This would be useful because it would help people do things more efficiently.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment]
Your example can already be done in a single line using the ternary expression:
`send ("you are op!" if player is op, else "you are not op!")`

I personally don't like this suggestion, it makes reading the code more difficult and adds no extra value besides having some less lines in your code: it's better to have some more lines with improved readability than to have very condensed code that isn't readable.

**Comment by TPGamesNL** [comment]
Closing, if a Skript dev disagrees feel free to reopen
