### ISSUE TITLE
Add Syntax in Variables Failing

### ISSUE THREAD

**Issue by BenguMC** [SkriptLang/Skript#4497]
### Skript/Server Version

```
Skript Version 2.6, - Paper Spigot 1.17.1 git-Paper-353
```

### Bug Description

In all simplicity this bug comes into play when you have a temporary variable set to a number which is then adding itself to a permanent or temporary variable. For instance, if `{_x}` is set to `1`, you cannot `add {_x} to {perm-var}` and result in one... However, you can `set {perm-var} to {perm-var} + {_x}`

### Expected Behavior

When you use the syntax `add {_x} to {perm-var}` when {_x} has been previously set to a number or integer, it should add that value to the variable, assuming the other variable is also a number or integer or unset. At this time, it does nothing at all. 

### Steps to Reproduce

Use this code:

`on break:
set {_x} to 1
add {_x} to {block-counter}
send {block-counter} to player`

### Errors or Screenshots

```
No errors in console or game on reload.
```

### Other

This bug seems rather minor, but I imagine it is something that will frustrate people who enter the community and truthfully does not make any sense as to why it was changed or is broken other than it being a bug. 

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
I cannot replicate this, I presume it is because your `{block-counter]` is set to a string, not a number, as this would give the behaviour you explained

**Comment by BenguMC** [comment]
Oh, you know what... I did not do my due diligence in trying this before I posted. It seems to only be an issue when a returned value is given from a function. Try the following.

`function numberTest(n: number) :: number:
	broadcast "%{_n}%"
	return {_n}

on break:
	set {_n} to numberTest(1)
	add {_n} to {break-counter}
	send "%{break-counter}%" to player`

**Comment by TPGamesNL** [comment]
I also cannot replicate the issue with your new code

**Comment by BenguMC** [comment]
Oof, what a day. This is a DiSky bug with 3.5.0 -- works fine without it enabled. I'll check newer versions and report it as needed to that dev. Thank you for your quick responses.
