### ISSUE TITLE
%block at location of {_loc}% also returns the location

### ISSUE THREAD

**Issue by DoreK333** [SkriptLang/Skript#4503]
### Skript/Server Version

Before update:
![image](https://user-images.githubusercontent.com/11007700/149586136-36033f6b-f3c6-4a20-a290-910bcab8040e.png)

After update Skript Version is 2.6.0

### Bug Description

After update 'block at location of' returns block and... location of block (why? xD)
```
[22:03:28] [Render thread/INFO]: [CHAT] 'blue concrete' at -3.5, 6.5, 18.5 in world 'world'
[22:03:28] [Render thread/INFO]: [CHAT] 'blue concrete' at -3.5, 6.5, 17.5 in world 'world'
[22:03:28] [Render thread/INFO]: [CHAT] 'blue concrete' at -3.5, 6.5, 16.5 in world 'world'
[22:03:28] [Render thread/INFO]: [CHAT] 'blue concrete' at -3.5, 6.5, 15.5 in world 'world'
[22:03:28] [Render thread/INFO]: [CHAT] 'blue concrete' at -3.5, 6.5, 14.5 in world 'world'
[22:03:28] [Render thread/INFO]: [CHAT] 'blue concrete' at -3.5, 6.5, 13.5 in world 'world'
```

### Expected Behavior

Before update %block at location of {_loc}% returns only block (as intended):

![image](https://user-images.githubusercontent.com/11007700/149586207-c64e4baa-dd72-4c49-9203-c541717611f6.png)

### Steps to Reproduce

Install Skript 2.5.3
Use script test.sk:

```
command /test:
	trigger:
		set {_loc} to location of target block
		send "%block at location of {_loc}%"
````

Use command /test and next update to Skript 2.6.0 and re-use this command

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Jjman739** [comment]
To the best of my knowledge, `block at {location}` has always had the location included, even if it wasn't shown in the text form. You can compare distances or the block type freely. `block at {location} is blue concrete` still works, right?

**Comment by AyhamAl-Ali** [comment]
This isn't an issue, the output of toString of blocks have been updated to provide more info about the block

**Comment by TPGamesNL** [comment]
We wanted to make clear that the block type is not just a material / item type, but rather a world block, see https://github.com/SkriptLang/Skript/issues/3315

**Comment by DoreK333** [comment]
Unfortunately, my scripts do not work properly on the newer version of Skript. How do I get ONLY the alias of the block in the given location?

Until now, it was enough to use "block at location of".

**Comment by Jjman739** [comment]
Are you trying to work with strings? e.g., `"%block at {location}%" is "blue concrete"`? If you review the issue TPGamesNL linked (#3315,) alternatives such as `type of {block}` and `block data of {block}` are provided.

You might want to join the official skUnity Discord to ask for help there: https://discord.gg/0l3WlzBPKX7WNjkf
