### ISSUE TITLE
"Selected hotbar slot" is not functioning as intended.

### ISSUE THREAD

**Issue by WilliamPlays0402** [SkriptLang/Skript#4508]
### Skript/Server Version

```
Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
Skript's documentation can be found here: https://skriptlang.github.io/Skript
Server Version: git-Paper-408 (MC: 1.17.1)
Skript Version: 2.6
Installed Skript Addons:
- skDragon v0.17
- skRayFall v1.9.26 (https://sk.rayfall.net/)
- SkBee v1.13.1 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

The expression "Hotbar slot" returns the current item in the player's hand instead of the number of the player's selected slot. 
https://skriptlang.github.io/Skript/expressions.html#ExprHotbarSlot

### Expected Behavior

Expected behaviour: 
send "%player's selected hotbar slot%" to player #Sends the index of player's held item in the hotbar

Actual behaviour:
Sends the player's held item

### Steps to Reproduce

```
command /test:
  trigger:
    send "%player's selected hotbar slot%" ## sends the player's held item
```

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
AFAIR, this is how it should work, there is another expression to get it's index which is [Slot Index](https://skriptlang.github.io/Skript/expressions.html#ExprSlotIndex) - `index of player's selected hotbar slot`

**Comment by WilliamPlays0402** [comment]
Thank you! Someone may have to edit the documentation and skripthub.net!

**Comment by TPGamesNL** [comment]
Just gonna keep this issue open because the description needs modification, because it says that it's anumber while it's a slot

**Comment by AyhamAl-Ali** [comment]
@TPGamesNL assign it to me
