### ISSUE TITLE
Block in player's inventory is not consider as block

### ISSUE THREAD

**Issue by RenaudAvenas** [SkriptLang/Skript#4512]
### Skript/Server Version

Server version: git-Paper-152 (MC: 1.18.1)
Skript version: 2.6 

### Bug Description

I loop on player's inventory and check if the loop-value is a block.
My player has stone block and a hoe in his inventory.
Skript consider that stone block is not a block.

### Expected Behavior

Player should receive message "Is block"

### Steps to Reproduce

Make a skript with this code :
```
command /test:
    trigger:
        loop player's inventory:
            if loop-value is block:
                send "Is block" to payer
```

Load it to minecraft and take some block in your player inventory (stone and andesit by exemple)
Launch the command "/test"

The "Is block" message is not sent

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Please format your codes
Try using `a block`
```
command /test:
    trigger:
        loop player's inventory:
            if loop-value is a block:
                send "Is block" to player
```

**Comment by RenaudAvenas** [comment]
I have formatted the code and relace the text by a block of code

**Comment by AyhamAl-Ali** [comment]
That's part 2 of the answer, part 1 is: have you tried using `is loop-value is a block`

**Comment by RenaudAvenas** [comment]
I thought that the "a" in "is a block" was optional. That is not the case. With your code it is ok! thanks for help.
