### ISSUE TITLE
some itemtypes returns more than one value

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/Skript#4514]
### Skript/Server Version

![image](https://user-images.githubusercontent.com/59025999/149974403-403cf223-1f4d-4ca1-a2ac-f0c1f516530e.png)

### Bug Description

parsing some items as itemtype causes to returning more than one value

### Expected Behavior

return one value

### Steps to Reproduce

!send ("redstone lamp" parsed as itemtype)
or
!send ("hay bale" parsed as itemtype)

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/59025999/149974312-6517822b-964b-4644-b93d-e7d72605dab2.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Aliases should only be doing this when `all` or `any` tag is specified.

**Comment by APickledWalrus** [comment]
The redstone lamp output is the result of a few issues (it should only output `redstone lamp`

The hay bale output is expected (excluding the duplicated item data) as the hay bale alias includes 3 item datas (and the toString method appends all item datas)
