### ISSUE TITLE
Clear All Potion Effects Of Player Bug

### ISSUE THREAD

**Issue by runningute72** [SkriptLang/Skript#4519]
### Skript/Server Version

```
[20:45:37 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:45:37 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[20:45:37 INFO]: [Skript] Server Version: git-Purpur-"08dd6c7" (MC: 1.17.1)
[20:45:37 INFO]: [Skript] Skript Version: 2.6
[20:45:37 INFO]: [Skript] Installed Skript Addons:
[20:45:37 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[20:45:37 INFO]: [Skript]  - MorkazSk v1.2
[20:45:37 INFO]: [Skript]  - skDragon v0.17
[20:45:37 INFO]: [Skript]  - SkQuery v4.1.5
[20:45:37 INFO]: [Skript]  - SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

```
on command "/spawn":
	clear player's inventory
	set {_p::*} to active potion effects of player
	if {_p::*} is not set:
		stop
	else:
		clear all the potion effects of player
		send "&cDue to you going to spawn, your effects have been cleared!" to player
		stop
```
If they have absorption hearts, their hearts still appear on their screen even though the affect isn't there anymore.

### Expected Behavior

It's supposed to clear all effects and golden hearts.

### Steps to Reproduce

Use essentials and the skript I sent above. It should work as multiple people are having this issue.

### Errors or Screenshots

N/A

### Other

N/A

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Can't reproduce on **Skript 2.6, Paper 1.16.5**, I've tried the following
- Eaten a golden apple
- Executed this effect command `!clear potion effects of me`
And all my potions were cleared and yellow hearts were gone as well.

Try without any addons

**Comment by TheLimeGlass** [comment]
I feel like a better test to replicate would be teleporting to spawn and clearing the effects at the same time.

> Can't reproduce on **Skript 2.6, Paper 1.16.5**, I've tried the following
> 
> * Eaten a golden apple
> * Executed this effect command `!clear potion effects of me`
>   And all my potions were cleared and yellow hearts were gone as well.
> 
> Try without any addons

**Comment by TPGamesNL** [comment]
I cannot replicate this (with your code and teleporting to spawn). This could be an addon issue (e.g. an addon has potion syntax).

Because you mention that the effects are cleared while the golden hearts are still there, this is more likely to be a Minecraft client issue (AFAIK the server doesn't control the golden hearts, just the potion effects).

If you can still replicate this without addons on a vanilla Minecraft client please reopen this issue.
