### ISSUE TITLE
Set "on death" event listeners as a condition in other listeners. 

### ISSUE THREAD

**Issue by fr1g** [SkriptLang/Skript#4520]
### Suggestion

I KNOW this is weird, but that's a requirement while I creating a script.
Set "on death" listeners as a condition in other listeners. 
Or, just make other listeners can detect whether a variable is killed.

### Why?

One day I think if I can create a script which can allow my players set each other "wanted" , might be fun (like Leister in GTAOL do.) Then I started everything from the event "on chat". After the wantedScript activated, player first should send the target-player's id, then send the price. (these two events will be cancelled, and the strings will be stored)
But I have to use variable like "{wanted-target-%sender%}".
Then, No "%sender%" can be found in event "on death". Which means, the target, the price, the set-ups, will be pointless.

# Anyway, Adding this is just my request. If it's really impossible to come true, just close this issue. My apologize.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Please read more about skript variables and more about event-values [here](https://skripthub.net/tutorials/31)
and always search in docs or ask in SkUnity discord help channels.

This isn't possible in skript because events are root level, means it can't be inside other scopes

You can achieve something like this using list variables (just a basic concept):
```v
command /bounty [<offlineplayer>] [<number>]:
    executable by: players
    trigger:
        add uuid of arg-1 to {Bounty::list::*}
        set {Bounty::list::%uuid of arg-1%::price} to arg-2
        set {Bounty::list::%uuid of arg-1%::owner} to uuid of player
        
on death of a player:
    {Bounty::list::%uuid of victim%::owner} = uuid of attacker
    add {Bounty::list::%uuid of victim%::price} to attacker's valance
```

**Comment by TheLimeGlass** [comment]
While loops can help you achieve your goal.

**Comment by TPGamesNL** [comment]
I don't think a feature like this would make scripting easier, just more confusing (e.g. what would event-values refer to, would it be ran for each death event called from point of execution or just one, etc). The same effect can already be achieved by using e.g. variables.

About the `%sender%` part, you need to use the right expression for the event, for the death event that is `%victim%`.

**Comment by fr1g** [comment]
> 

I already tried that but not what I prefer, but thanks.

**Comment by fr1g** [comment]
Finally I solved my problem... Kind of...
By adding metadata value for players, which can make the value storaged and parse to a variable.
