### ISSUE TITLE
When i reload my script

### ISSUE THREAD

**Issue by Lubinrns** [SkriptLang/Skript#4522]
### Skript/Server Version

```
Replace this text with your output from the command.
```
Lastest

### Bug Description

When i reload my skript ss.sk

(Code) : 
`#Skript de SS par Thorgal pour Surviria

options:

#Options Générales
	logo: &aSurviria&2-&aMod &8&l»&r
	permission: surviria.ss
	permissionm: &aSurviria &8&l» &cErreur, tu n'as pas la permission d'utiliser cette commande !
	immune_permission: surviria.ss_immune

#Discord
	#bot_token: e
	#bot_name: 
	#bot_channel:

#Définition des sanctions:
#Mettre la commande à éxécuter, selon l'infraction
#ex: méchanceté: /kick %{_malfrat}% Fallait pas dire de méchancetés dans le chat!

#Sanctions de Gameplay:
	construction_incorrecte: /tempban %{_malfrat}% 24h Construction Incorrecte
	cdr: /tempban %{_malfrat}% 24h Contournement du règlement
	pvp: /tempban %{_malfrat}% 24h Freekill 
	grief: /tempban %{_malfrat}% 48h Grief / Vol
	troll: /tempban %{_malfrat}% 48h Troll
	macro: /tempban %{_malfrat}% 72h Macro / Glitch
	cds: /tempban %{_malfrat}% 72h Contournement de sanction
	cheat: /tempban %{_malfrat}% 15d Cheat
	vide_gameplay: /tempban %{_malfrat}% 72h Gameplay Incorrect

#Sanctions de Chat:
	insultes: /mute %{_malfrat}% 48h Insultes
	menaces: /mute %{_malfrat}% 48h Menaces
	spam: /mute %{_malfrat}% 48h Spam
	publicité: /mute %{_malfrat}% 48h Publicité
	propos_sexistes: /mute %{_malfrat}% 72h Propos Incorrect
	vide_chat: /mute %{_malfrat}% 48h Comportement Incorrect
	vide_a_modif: /mute %{_malfrat}% 48h Comportement Incorrect

#on load:
	#login to "{@bot_token}" with the name "{@bot_name}"

#Commande de base
command /ss [<offlineplayer>]:
	permission: {@permission}
	permission message:{@permissionm}
	trigger:
		if arg-1 is set:
			if arg-1 has permission "{@immune_permission}":
				send "{@logo} &aVous ne pouvrez pas punir ce joueur!"
			else:
				ssGUI(player, arg-1)
		else:
			send "{@logo} &aVous devez spécifier un joueur à punir!"

#Menu principal
function ssGUI(p: player, malfrat: offlineplayer):
	set {ss_raison::%{_p}%} to false
	create a new gui with virtual chest inventory named "&6&l»&9&lSS &c&l%{_malfrat}%&r&9&l:" with 4 rows:
		make gui slot 11 with grass named "&a&lRaison: &c&lGameplay" with lore "" and "Cliquez pour choisir cette raison!":
			ssGameplay({_p}, {_malfrat})
		make gui slot 15 with oak sign named "&a&lRaison: &c&lChat" with lore "" and "Cliquez pour choisir cette raison!":
			ssChat({_p}, {_malfrat})
		make gui slot 31 with music disc 11 named "&c&lAnnuler la sanction" with lore "" and "Cliquez pour fermer le menu et annuler":
			close {_p}'s inventory
			send "{@logo} &cSanction annulée"
		open last created gui to {_p}

#Menu Gameplay
function ssGameplay(p: player, malfrat: offlineplayer):
	create a new gui with virtual chest inventory named "&c&l%{_malfrat}%&r&9 | &r&a&lGameplay&9&l:" with 5 rows:
		if {ss_raison::%{_p}%} is "&c&lConstruction Incorrecte":
			make gui slot 3 with glowing dirt named "&c&lConstruction Incorrecte" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssGameplay({_p}, {_malfrat})
		else:
			make gui slot 3 with dirt named "&c&lConstruction Incorrecte" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lConstruction Incorrecte"
				set {ss_cmd::%{_p}%} to "{@construction_incorrecte}"
				ssGameplay({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lCDR":
			make gui slot 4 with glowing book named "&c&lCDR" with lore "&r&f(Contournement de règlement)" and "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssGameplay({_p}, {_malfrat})
		else:
			make gui slot 4 with book named "&c&lCDR" with lore "&r&f(Contournement de règlement)" and "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lCDR"
				set {ss_cmd::%{_p}%} to "{@cdr}"
				ssGameplay({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lPvP / Freekill":
			make gui slot 5 with glowing diamond sword named "&c&lPvP / Freekill" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssGameplay({_p}, {_malfrat})
		else:
			make gui slot 5 with diamond sword named "&c&lPvP / Freekill" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lPvP / Freekill"
				set {ss_cmd::%{_p}%} to "{@pvp}"
				ssGameplay({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lGrief":
			make gui slot 11 with glowing tnt named "&c&lGrief" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssGameplay({_p}, {_malfrat})
		else:
			make gui slot 11 with tnt named "&c&lGrief" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lGrief"
				set {ss_cmd::%{_p}%} to "{@grief}"
				ssGameplay({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lTroll":
			make gui slot 15 with glowing cobweb named "&c&lTroll" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssGameplay({_p}, {_malfrat})
		else:
			make gui slot 15 with cobweb named "&c&lTroll" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lTroll"
				set {ss_cmd::%{_p}%} to "{@troll}"
				ssGameplay({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lMacro":
			make gui slot 20 with glowing carrot on a stick named "&c&lMacro" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssGameplay({_p}, {_malfrat})
		else:
			make gui slot 20 with carrot on a stick named "&c&lMacro" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lMacro"
				set {ss_cmd::%{_p}%} to "{@macro}"
				ssGameplay({_p}, {_malfrat})
		if {ss_raison::%{_p}%} != false:
			make gui slot 22 with glowing structure void named "&a&lConfirmer" with lore "&r&fVous allez punir %{_malfrat}%" and "&r&fpour %{ss_raison::%{_p}%}%" and "" and "Cliquez pour choisir cette raison!":
				close {_p}'s inventory
				send "{@logo} &aVous avez bien puni %{_malfrat}% &r&apour %{ss_raison::%{_p}%}%&r&a!"
				make player execute "%{ss_cmd::%{_p}%}%"
				#ssDiscord({_p}, {_malfrat})
		else:
			make gui slot 22 with structure void named "&a&lConfirmer" with lore "&r&fChoisissez la raison d'abord!" and "" and "Cliquez pour choisir cette raison!"
		if {ss_raison::%{_p}%} is "&c&lCDS":
			make gui slot 24 with glowing barrier named "&c&lCDS" with lore  "&r&f(Contournement de sanction)" and "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssGameplay({_p}, {_malfrat})
		else:
			make gui slot 24 with barrier named "&c&lCDS" with lore  "&r&f(Contournement de sanction)" and "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lCDS"
				set {ss_cmd::%{_p}%} to "{@cds}"
				ssGameplay({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lCheat":
			make gui slot 29 with glowing notch apple named "&c&lCheat" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssGameplay({_p}, {_malfrat})
		else:
			make gui slot 29 with notch apple named "&c&lCheat" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lCheat"
				set {ss_cmd::%{_p}%} to "{@cheat}"
				ssGameplay({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lVide":
			make gui slot 33 with glowing paper named "&c&lVide" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssGameplay({_p}, {_malfrat})
		else:
			make gui slot 33 with paper named "&c&lVide" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lVide"
				set {ss_cmd::%{_p}%} to "{@vide}"
				ssGameplay({_p}, {_malfrat})
		make gui slot 40 with music disc 11 named "&c&lAnnuler la sanction" with lore "" and "Cliquez pour fermer le menu et annuler":
			close {_p}'s inventory
			send "{@logo} &cSanction annulée"
			set {ss_raison::%{_p}%} to false  
		make gui slot 36 with arrow named "&e&lRetour au menu" with lore "" and "Cliquez pour retourner au menu principal":
			ssGUI({_p}, {_malfrat})
	open last created gui to {_p}

#Menu Chat
function ssChat(p: player, malfrat: offlineplayer):
	create a new gui with virtual chest inventory named "&c&l%{_malfrat}%&r&9 | &r&a&lChat&9&l:" with 5 rows:
		if {ss_raison::%{_p}%} is "&c&lInsultes":
			make gui slot 3 with glowing red tulip named "&c&lInsultes" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssChat({_p}, {_malfrat})
		else:
			make gui slot 3 with red tulip named "&c&lInsultes" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lInsultes"
				set {ss_cmd::%{_p}%} to "{@insultes}"
				ssChat({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lCDR":
			make gui slot 4 with glowing snowball named "&c&lSpam" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssChat({_p}, {_malfrat})
		else:
			make gui slot 4 with snowball named "&c&lSpam" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lSpam"
				set {ss_cmd::%{_p}%} to "{@spam}"
				ssChat({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lPublicité":
			make gui slot 5 with glowing emerald named "&c&lPublicité" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssChat({_p}, {_malfrat})
		else:
			make gui slot 5 with emerald named "&c&lPublicité" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lPublicité"
				set {ss_cmd::%{_p}%} to "{@publicité}"
				ssChat({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lMenaces (DDOS, DOX)":
			make gui slot 11 with glowing barrier named "&c&lMenaces (DDOS, DOX)" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssChat({_p}, {_malfrat})
		else:
			make gui slot 11 with barrier named "&c&lMenaces (DDOS, DOX)" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lMenaces (DDOS, DOX)"
				set {ss_cmd::%{_p}%} to "{@menaces}"
				ssChat({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lPropos Sexistes/Racistes":
			make gui slot 15 with glowing red concrete named "&c&lPropos Sexistes/Racistes" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssChat({_p}, {_malfrat})
		else:
			make gui slot 15 with red concrete named "&c&lPropos Sexistes/Racistes" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lPropos Sexistes/Racistes"
				set {ss_cmd::%{_p}%} to "{@propos_sexistes}"
				ssChat({_p}, {_malfrat})
		if {ss_raison::%{_p}%} is "&c&lVide":
			make gui slot 20 with glowing paper named "&c&lVide" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssChat({_p}, {_malfrat})
		else:
			make gui slot 20 with paper named "&c&lVide" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lVide"
				set {ss_cmd::%{_p}%} to "{@vide_chat}"
				ssChat({_p}, {_malfrat})
		if {ss_raison::%{_p}%} != false:
			make gui slot 22 with glowing structure void named "&a&lConfirmer" with lore "&r&fVous allez punir %{_malfrat}%" and "&r&fpour %{ss_raison::%{_p}%}%" and "" and "Cliquez pour choisir cette raison!":
				close {_p}'s inventory
				send "{@logo} &aVous avez bien puni %{_malfrat}% &r&apour %{ss_raison::%{_p}%}%&r&a!"
				make player execute "%{ss_cmd::%{_p}%}%"
				#ssDiscord({_p}, {_malfrat})
		else:
			make gui slot 22 with structure void named "&a&lConfirmer" with lore "&r&fChoisissez la raison d'abord!" and "" and "Cliquez pour choisir cette raison!"
		if {ss_raison::%{_p}%} is "&c&lCDS":
			make gui slot 24 with glowing barrier named "&c&lVide (A modifier)" with lore  "&r&f(Contournement de sanction)" and "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to false
				ssChat({_p}, {_malfrat})
		else:
			make gui slot 24 with paper named "&c&lVide (A modifier)" with lore "" and "Cliquez pour choisir cette raison!":
				set {ss_raison::%{_p}%} to "&c&lVide (A modifier)"
				set {ss_cmd::%{_p}%} to "{@vide_a_modif}"
				ssChat({_p}, {_malfrat})
		make gui slot 40 with music disc 11 named "&c&lAnnuler la sanction" with lore "" and "Cliquez pour fermer le menu et annuler":
			close {_p}'s inventory
			send "{@logo} &cSanction annulée"
			set {ss_raison::%{_p}%} to false
		make gui slot 36 with arrow named "&e&lRetour au menu" with lore "" and "Cliquez pour retourner au menu principal":
			ssGUI({_p}, {_malfrat})  
	open last created gui to {_p}

#Envoyer à Discord
#function ssDiscord(p: player, malfrat: player):
	#add 1 to {ss_number}
	#set {_raison} to uncolored {report_raison::%{_p}%}
	#set {_time} to now formatted human-readable
	#create embed:
		#set the title of embed to title with text "<:warn:809917105994334258> Sanction ##%{ss_number}%| __**%{reported_player::%{_p}%}%**__"
		#add field named "➥ Sanction de:" with value "`%{_malfrat}%`" to embed
		#add field named "➥ Raison" with value "`%{_raison}%`" to embed
		#set the colour of the embed to blue
		#set the thumbnail of embed to "https://cravatar.eu/head/%{_malfrat}%/128.png"	
		#set the footer of embed to footer with text "Sanction par %{_p}% | {_time}" and icon "http://cravatar.eu/avatar/%{_p}%/128.png"
	#send the last created embed to channel with id "{@bot_channel}" with "{@bot_name}"`

My script don't load, and in the console, i have this error 

### Expected Behavior

Load my script

### Steps to Reproduce

Reload my script

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```
CONSOLE ERROR : 

>....=>.... [00:04:36 INFO]: [Skript] Reloading ss.sk...
>.... [00:04:36 ERROR]: A function named 'ssGUI' already exists in script 'Staff/ss.sk' (Staff/ss.sk, line 57: function ssGUI(p: player, malfrat: offlineplayer):')
>.... [00:04:36 ERROR]: A function named 'ssGameplay' already exists in script 'Staff/ss.sk' (Staff/ss.sk, line 70: function ssGameplay(p: player, malfrat: offlineplayer):')
>.... [00:04:36 ERROR]: A function named 'ssChat' already exists in script 'Staff/ss.sk' (Staff/ss.sk, line 170: function ssChat(p: player, malfrat: offlineplayer):')
>.... [00:04:36 WARN]: java.lang.NoSuchFieldException: handlers
>.... [00:04:36 WARN]: at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
>.... [00:04:36 WARN]: at skript-gui 1.2.0.jar//io.github.apickledwalrus.skriptgui.util.ReflectionUtils.getField(ReflectionUtils.java:82)
>.... [00:04:36 WARN]: at skript-gui 1.2.0.jar//io.github.apickledwalrus.skriptgui.util.EffectSection.stopLog(EffectSection.java:87)
>.... [00:04:36 WARN]: at skript-gui 1.2.0.jar//io.github.apickledwalrus.skriptgui.util.EffectSection.loadSection(EffectSection.java:149)
>.... [00:04:36 WARN]: at skript-gui 1.2.0.jar//io.github.apickledwalrus.skriptgui.elements.sections.SecCreateGUI.init(SecCreateGUI.java:64)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:71)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:168)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1134)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:46)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:138)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:733)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:533)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:420)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:436)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:532)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1066)
>.... [00:04:36 WARN]: at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
>.... [00:04:36 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [00:04:36 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [00:04:36 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
>.... [00:04:36 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860)
>.... [00:04:36 WARN]: at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:507)
>.... [00:04:36 WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
>.... [00:04:36 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
>.... [00:04:36 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
>.... [00:04:36 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
>.... [00:04:36 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
>.... [00:04:36 ERROR]: #!#!
>.... [00:04:36 ERROR]: #!#! [Skript] Severe Error:
>.... [00:04:36 ERROR]: #!#!
>.... [00:04:36 ERROR]: #!#! Something went horribly wrong with Skript.
>.... [00:04:36 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
>.... [00:04:36 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
>.... [00:04:36 ERROR]: #!#! Here is full list of them:
>.... [00:04:36 ERROR]: #!#! skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders) skript-gui v1.2.0 (https://github.com/APickledWalrus/skript-gui) SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.3
>.... [00:04:36 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
>.... [00:04:36 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
>.... [00:04:36 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
>.... [00:04:36 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
>.... [00:04:36 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
>.... [00:04:36 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
>.... [00:04:36 ERROR]: #!#!
>.... [00:04:36 ERROR]: #!#! Stack trace:
>.... [00:04:36 ERROR]: #!#! java.lang.NoSuchFieldError: hasDelayBefore
>.... [00:04:36 ERROR]: #!#! at skript-gui 1.2.0.jar//io.github.apickledwalrus.skriptgui.util.EffectSection.loadSection(EffectSection.java:172)
>.... [00:04:36 ERROR]: #!#! at skript-gui 1.2.0.jar//io.github.apickledwalrus.skriptgui.elements.sections.SecMakeGUI.init(SecMakeGUI.java:72)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:71)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:168)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1134)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:51)
>.... [00:04:36 ERROR]: #!#! at skript-gui 1.2.0.jar//io.github.apickledwalrus.skriptgui.util.EffectSection$1.<init>(EffectSection.java:132)
>.... [00:04:36 ERROR]: #!#! at skript-gui 1.2.0.jar//io.github.apickledwalrus.skriptgui.util.EffectSection.loadSection(EffectSection.java:132)
>.... [00:04:36 ERROR]: #!#! at skript-gui 1.2.0.jar//io.github.apickledwalrus.skriptgui.elements.sections.SecCreateGUI.init(SecCreateGUI.java:64)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:71)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:168)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1134)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:46)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:138)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:733)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:533)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:420)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:436)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:532)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1066)
>.... [00:04:36 ERROR]: #!#! at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
>.... [00:04:36 ERROR]: #!#! at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [00:04:36 ERROR]: #!#! at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [00:04:36 ERROR]: #!#! at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
>.... [00:04:36 ERROR]: #!#! at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860)
>.... [00:04:36 ERROR]: #!#! at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:507)
>.... [00:04:36 ERROR]: #!#! at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
>.... [00:04:36 ERROR]: #!#! at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
>.... [00:04:36 ERROR]: #!#! at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
>.... [00:04:36 ERROR]: #!#! at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
>.... [00:04:36 ERROR]: #!#! at java.base/java.lang.Thread.run(Thread.java:833)
>.... [00:04:36 ERROR]: #!#!
>.... [00:04:36 ERROR]: #!#! Version Information:
>.... [00:04:36 ERROR]: #!#! Skript: 2.6 (latest)
>.... [00:04:36 ERROR]: #!#! Flavor: skriptlang-github
>.... [00:04:36 ERROR]: #!#! Date: 17:20:35.482878100
>.... [00:04:36 ERROR]: #!#! Bukkit: 1.18.1-R0.1-SNAPSHOT
>.... [00:04:36 ERROR]: #!#! Minecraft: 1.18.1
>.... [00:04:36 ERROR]: #!#! Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12-39)
>.... [00:04:36 ERROR]: #!#! OS: Linux amd64 4.9.0-13-amd64
>.... [00:04:36 ERROR]: #!#!
>.... [00:04:36 ERROR]: #!#! Server platform: Paper
>.... [00:04:36 ERROR]: #!#!
>.... [00:04:36 ERROR]: #!#! Current node: null
>.... [00:04:36 ERROR]: #!#! Current item: null
>.... [00:04:36 ERROR]: #!#!
>.... [00:04:36 ERROR]: #!#! Thread: Server thread
>.... [00:04:36 ERROR]: #!#!
>.... [00:04:36 ERROR]: #!#! Language: english
>.... [00:04:36 ERROR]: #!#! Link parse mode: DISABLED
>.... [00:04:36 ERROR]: #!#!
>.... [00:04:36 ERROR]: #!#! End of Error.
>.... [00:04:36 ERROR]: #!#!

### Other

ty

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TobyMinceraft** [comment]
I'm not familiar with the Skript version `lastest`. What's that, then?

This might actually be an issue with DiSky, as things like this have happened to me before when using. If you are using a nightly build or other dev build, try using the latest STABLE release, and see if the problem persists. If you are using Skript v2.5.3, update it to 2.6 as the latest version(s) of skript-gui and SkBee require Skript v2.6.

Side-note, use something like PasteBin to share your Skript code, as it spams the issue otherwise

**Comment by bluelhf** [comment]
This issue is none of the above. skript-gui does not support the 2.6 version of Skript by default, due to the changes in #3924. To update, you can try running skript-gui through SkriptAddonPatcher or adding the [RuntimeSkriptAddonPatcher](https://github.com/TPGamesNL/RuntimeSkriptAddonPatcher) plugin to your server.

**Comment by APickledWalrus** [comment]
Since you are using Skript 2.6, you should update to the 1.3 beta version. You can download it at https://github.com/APickledWalrus/skript-gui/releases/tag/1.3-beta1

If you have any questions about updating, please feel free to open an issue at that repository :)
