### ISSUE TITLE
Error While Getting Name of ItemStack directly from a return function

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#4524]
### Skript/Server Version

![image](https://user-images.githubusercontent.com/72163224/151048782-a07b20eb-7e07-401e-995c-0c421019c218.png)

### Bug Description

Getting name of an ItemStack from a return function spits a `is neither a ....` error.

### Expected Behavior

Returns name of an ItemStack from a function, without issues.

### Steps to Reproduce

- Create a function which returns a named item
- Run `send name of FUNCTION()`

My tested code:
```
function getItem() :: item:
    return stone named "&7Innocent Stone"
```

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/72163224/151048731-176762b3-20da-4242-8fc7-c5408b1437be.png)

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
The function parsing process (SkriptParser#parseFunction, FunctionReference, ExprFunctionCall) doesn't support converters
