### ISSUE TITLE
%placeholders% in <name:parameter> tags will make the tag has no effect.

### ISSUE THREAD

**Issue by fr1g** [SkriptLang/Skript#4525]
### Skript/Server Version

```
Replace this text with your output from the command.
```
> sk info
[06:17:09 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[06:17:09 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[06:17:09 INFO]: [Skript] Server Version: git-Paper-794 (MC: 1.16.5)
[06:17:09 INFO]: [Skript] Skript Version: 2.6
[06:17:09 INFO]: [Skript] Installed Skript Addons:
[06:17:09 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[06:17:09 INFO]: [Skript]  - SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee)
[06:17:09 INFO]: [Skript]  - skLib v1.1.0 (https://github.com/WheezyGold7931/skLib/)
>

### Bug Description

While I using skinrestorer Bungee version, one day I got an idea, make a skript to let players switch and clear their skins easily. the command "/skin clear" is normally executed. However, another command actually displayed the command itself, and not clickable---- I used a placeholder %player% in a tag: <cmd:/skin %player%>. the output is just the text which should be executed as command after a click.

### Expected Behavior

It's expected to get the player's ID and then execute as entire <cmd:<command>> on click.
Or this is what you thought it should be?

### Steps to Reproduce

create a .sk like:

```

on command "/sample":
        if sender is a player:
                cancel event
                message "<cmd:/give %player% apple>Give me an Apple"

```

then try how it perform.

### Errors or Screenshots

No obviously error message but 

![image](https://user-images.githubusercontent.com/53085628/151070313-0f630a4b-313b-4186-b086-1527e47ff816.png)

![image](https://user-images.githubusercontent.com/53085628/151070313-0f630a4b-313b-4186-b086-1527e47ff816.png)

### Other

In the end, I won't have any word if you think its not a bug.

But if you have a different way to achieve the effect as I thought, please make this visible on your document.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by fr1g** [comment]
Hey I really don't understand how to use the code block...

**Comment by TPGamesNL** [comment]
When you have an expression in your command, you need to use `message formatted ...` instead of `message ...`

**Comment by fr1g** [comment]
> 

oops thanks
