### ISSUE TITLE
formatted break <#hex>

### ISSUE THREAD

**Issue by ZConnorZ** [SkriptLang/Skript#4527]
### Skript/Server Version

```
1. Server Version: git-Purpur-1529 (MC: 1.18.1)
2. Skript Version: 2.6.1
3. Installed Skript Addons:
   - SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

Since 2.6.1, when using 'formatted' in sending messages, hex stops working.

### Expected Behavior

In the text, you can use one thing, either hex or tooltip. (error)
I mean, with tooltip, hex doesn't work for you :)

### Steps to Reproduce

``send formatted "<#bd583c>Its BROWN WOW!!!"``

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/45974097/151105459-a6479627-8d2f-40e2-ad4a-0b8d5b92935b.png)

### Other

Plugins (3): SkBee, Skript, spark

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by GStudiosX2** [comment]
for me lmao it doesnt even show colors on either
![image](https://user-images.githubusercontent.com/76548041/151128703-ed534b7b-f394-4c8f-8597-d73395290752.png)

**Comment by Shirk** [comment]
This issue is back in 2.6.2 - regression?

**Comment by AyhamAl-Ali** [comment]
> This issue is back in 2.6.2 - regression?

Can't replicate, can you send more info?
![image](https://user-images.githubusercontent.com/20037329/175948594-418fc499-9743-436a-ae5c-10464c39530f.png)

**Comment by Shirk** [comment]
This might be more involved - I can reproduce it with 2.6.1 and 2.6.2 but not with 2.6 using this Skirpt. If I hardcode the hex values it works fine, loading them from a file somehow breaks it. 

**colours.sk**
```skript
function get_colour_string_hex() :: text:
	set {_res} to yaml value "colours.hex" from "coloured.yml"
	return {_res}

function get_colour_string_named() :: text:
	set {_res} to yaml value "colours.named" from "coloured.yml"
	return {_res}

# ensure settings are picked up on load
on script load:
	load yaml "plugins/Skript/scripts/coloured.yml" as "coloured.yml"

command /colour_demo:
	trigger:
		send coloured "named colour: <%get_colour_string_named()%>%get_colour_string_named()%"
		send coloured "  hex colour: <%get_colour_string_hex()%>%get_colour_string_hex()%"

```

**colours.yml**
```yaml
colours:
    hex: '##aa00bb'
    named: purple
```

With Skript 2.6 it works as expected:
<img width="539" alt="Screenshot 2022-06-27 at 20 40 52" src="https://user-images.githubusercontent.com/304352/176014006-0c8c4d95-4053-434a-9d67-55996ed5f42d.png">

Typing `/colour_demo`
<img width="502" alt="Screenshot 2022-06-27 at 20 38 52" src="https://user-images.githubusercontent.com/304352/176014056-cba56b3d-0a3c-4435-9cae-6e7ec594ee5b.png">
 
With Skript 2.6.1 and 2.6.2 I get this:
<img width="537" alt="Screenshot 2022-06-27 at 20 45 36" src="https://user-images.githubusercontent.com/304352/176014281-690429e8-c967-4ca3-a12b-cb4d7f67f139.png">

Typing `/colour_demo`
<img width="502" alt="Screenshot 2022-06-27 at 20 36 46" src="https://user-images.githubusercontent.com/304352/176014314-ce9879dd-bda4-4b4f-887c-544ea055615c.png">

skript-yaml is the latest release from their github <https://github.com/Sashie/skript-yaml/releases/tag/v1.4>

**Comment by ZConnorZ** [comment]
For .yml: <#ffffff> For .sk <##ffffff>
