### ISSUE TITLE
No class info found for type exception during pattern compiling should include pattern itself

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [SkriptLang/Skript#4541]
### Skript/Server Version

> skript info
[06:36:53 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[06:36:53 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[06:36:53 INFO]: [Skript] Server Version: git-Paper-177 (MC: 1.18.1)
[06:36:53 INFO]: [Skript] Skript Version: 2.6.1
[06:36:53 INFO]: [Skript] Installed Skript Addons:
[06:36:53 INFO]: [Skript]  - skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders)
[06:36:53 INFO]: [Skript]  - Skellett v2.0.0 (https://forums.skunity.com/resources/skellett.24/)
[06:36:53 INFO]: [Skript]  - skript-yaml v1.3.2
[06:36:53 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[06:36:53 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[06:36:53 INFO]: [Skript]  - skRayFall v1.9.21 (https://sk.rayfall.net/)
[06:36:53 INFO]: [Skript]  - SkBee v1.14.1 (https://github.com/ShaneBeee/SkBee)
[06:36:53 INFO]: [Skript]  - skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo)
[06:36:53 INFO]: [Skript] Installed dependencies:
[06:36:53 INFO]: [Skript]  - Vault v1.7.3-b131
[06:36:53 INFO]: [Skript]  - WorldGuard v7.0.7-SNAPSHOT+2165-81750e1

### Bug Description

Using 2.6.1 broke two of my scripts, which work fine in 2.6.
Idk much about it, but the error states SkriptApiException: No class info found for basecomponent
one seems to interfer with a particle used in SkBee, the other with loading a file via skript-yaml, but again it sounds like an Skript issue itself, as it mentions SkriptApiException and only occurs in 2.6.1, not in 2.6.

### Expected Behavior

Well, the scripts to load and work.

### Steps to Reproduce

Update to 2.6.1, use the addons and scripts and it breaks. 
Lines which error are stated in the error log so I won't paste them again.

### Errors or Screenshots

Both errors seperated by a line are in the paste.
https://paste.helpch.at/jinaqatixo.cs

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by ILikeOrangeJuice** [comment]
Also using the same skript, addons and 2.6.1 on 1.17.1 does not throw does errors and everything works, just happens on 1.18.1 if that helps.

**Comment by TheLimeGlass** [comment]
Do you have any other errors in console? basecomponent is from SkBee and I don't believe it has a 2.6.1 update yet.

**Comment by ILikeOrangeJuice** [comment]
Hey, no these are the only errors I get, they appear upon loading the scripts on Server start and none of the insides work. I suppose waiting for a SkBee update will be the next step for now, but the first error is from Current node: load "plugins/AllowedCommands/config.yml" as "AC" (chat.sk, line 67) which would be Skript-Yaml, I suppose it needs the same update to match 2.6.1 which SkBee will need as well?

**Comment by TPGamesNL** [comment]
Can you send your startup log?

**Comment by ILikeOrangeJuice** [comment]
Of course! Here it is, I hope it helps, but I went through it as well, it seems like the plugins and addon load fine, unless I missed anything. They are also all green when I run /pl in after the server has fully loaded up. 
https://pastebin.com/9UHzXpCa

**Comment by TPGamesNL** [comment]
I can't find anything in there either, but this is still most likely an addon error. Maybe @ShaneBeee can help if you on SkBee's issue tracker. For Shane: the type `basecomponent` isn't registered while a syntax containing `%basecomponent%` is registered (it shouldn't be: log contains `[SkBee] Text Component Elements disabled via config`).

However, I am keeping this issue open because the error you got should be more descriptive, specifically it should contain the pattern that generated the error

**Comment by ShaneBeee** [comment]
> I can't find anything in there either, but this is still most likely an addon error. Maybe @ShaneBeee can help if you on SkBee's issue tracker. For Shane: the type `basecomponent` isn't registered while a syntax containing `%basecomponent%` is registered (it shouldn't be: log contains `[SkBee] Text Component Elements disabled via config`).
> 
> However, I am keeping this issue open because the error you got should be more descriptive, specifically it should contain the pattern that generated the error

1) Yep, this was SkBee's fault. Im working on a fix for the next update
2) I think the reason the line doesnt show up is due to the fact this errors when SkBee is registering syntaxes, since the base component part was disabled, no classinfo was available, it then errored during registration.

**Comment by ILikeOrangeJuice** [comment]
Glad it got resolved, thanks for the help, I guess I'll wait for the next SkBee update!:)

**Comment by ShaneBeee** [comment]
> Glad it got resolved, thanks for the help, I guess I'll wait for the next SkBee update!:)

For the time being just enable text components in skbee config
