### ISSUE TITLE
"loop all indices of" syntax are not worked

### ISSUE THREAD

**Issue by Ecilpse** [SkriptLang/Skript#4547]
### Skript/Server Version

```
Replace this text with your output from the command.
```

### Bug Description

			else if arg 1 is "등록목록":
				loop all indices of {altar.item::*}:
					loop {altar.item::%loop-value%::*}:
						send "%loop-value-1% 포인트: %loop-value-2%"

"loop all indices of" syntax are not worked (error when reload) after update lastest version of skript. (2.6.1)

### Expected Behavior

			else if arg 1 is "등록목록":
				loop all {altar.item::*}:
					loop {altar.item::%loop-index%::*}:
						send "%loop-value-1% 포인트: %loop-value-2%"

i also tried this syntax. it reloaded without any errors but still not worked.

### Steps to Reproduce

lastest version of spigot (2.6.1) / 1.18.1 purpur

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Sorbon-CH** [comment]
`loop indices of {altar.item::*}:` and it works

**Comment by NCSV** [comment]
> `loop indices of {altar.item::*}:` and it works
![2](https://user-images.githubusercontent.com/25452835/151665271-4cecad92-f60d-4076-9a54-6405dc58e18d.PNG)
can it disable warn notifiy on reload?

**Comment by AyhamAl-Ali** [comment]
You can disable these warnings locally using this [effect](https://skriptlang.github.io/Skript/effects.html#EffSuppressWarnings)

**Comment by NCSV** [comment]
> [](https://skriptlang.github.io/Skript/effects.html#EffSuppressWarnings)

thank you for replies.
