### ISSUE TITLE
SectionSkriptEvent can't be used.

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4557]
### Bug Description

When you use the method `Section#loadCode(SectionNode, String, Class<? extends Event>...)` with the SectionSkriptEvent class, it's not allowed because SectionSkriptEvent is a custom SkriptEvent, and not a Bukkit event, making the whole point of the dummy SectionSkriptEvent class useless.

### Expected Behavior

SectionSkriptEvent should extend the Event class from Bukkit or add a method in Section for loadCode methods should be allowed for SkriptEvents. Probably just changing the dummy event to a Bukkit event is a good fix.

### Steps to Reproduce

Create any Section syntax and attempt to use the loadCode method described with the SectionSkriptEvent and you will get a compile error.

Been present since the Section API, I just forgot to report it or fix it.

**Comment by TheLimeGlass** [comment]
Adding medium priority

**Comment by TheLimeGlass** [comment]
I also propose a class name change. Something like `DummySectionEvent`

**Comment by TPGamesNL** [comment]
This is not what SectionSkriptEvent is for. It is only because a Trigger (the return type of loadCode) requires a SkriptEvent associated.
