### ISSUE TITLE
Custom databases cleared after a restart of the server

### ISSUE THREAD

**Issue by ZeTioZ** [SkriptLang/Skript#457]
Hello, I have an issue with the custom databases, the variables save as well in the file that I set on the config file while the server is running but when I stop the server the variables are erased, the database file in csv become blank and no more variable on the file, could you fix this issue ? I would have a custom database for a skript that make a lot of variable, thank in advance.

EDIT: I tried the SQLite databases and they work well ! But the csv database would be more interresting beacause of the freely modification way.

Config of the custom database:

	Sweetban Database:
		
		type: CSV
		
		pattern: sweetban.*
		
		file: ./plugins/Skript/sweetban.csv
		
		backup interval: 12 hours

**Comment by bensku** [comment]
I would recommend against using SQLite. It potentially has problems related to deleting variables.

I'll take look at this at some point, but Skript's variable system is kinda... complex.

**Comment by TheBentoBox** [comment]
I believe this fixed by #1073. Can anyone confirm; @ZeTioZ ?

**Comment by ZeTioZ** [comment]
Mmh since I use now the yml file to store my data I didn't tried to make a new database. I'll try tomorrow and I'll tell you the result ^^ @TheBentoBox

**Comment by Nicofisi** [comment]
@ZeTioZ any luck yet?

**Comment by ZeTioZ** [comment]
I didn't tested because as I said I'm now using yml, and I totally forgot about that xD

**Comment by TheLimeGlass** [comment]
Still a valid issue.

Test script:
```
on script load:
	broadcast "1: %{sweetban::testing}%"
	broadcast "2: %{sweetban.testing}%"
	broadcast "3: %{sweetbantesting}%"
	set {sweetban::testing} to true
	set {sweetban.test} to "A string test"
	set {sweetbantest} to 1337
	broadcast "End"
```
Results: Only 1. was broadcasting the correct values, where as the others weren't even being set. This is probably due to list variables not accounting like this as the pattern.

The database file was registered and existing.

**Comment by TPGamesNL** [comment]
Cannot confirm this issue anymore, the issue has been fixed, probably in https://github.com/SkriptLang/Skript/pull/1073 as stated before. The code that was tested with in the comment above:
broadcast "2: %{sweetban.**testing**}%"
set {sweetban.**test**} to "A string test"
So obviously, that didn't work
