### ISSUE TITLE
don't send usage message if additional arguments are provided

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#4571]
### Suggestion

make it so if a user provides additional arguments, it won't stop the command, example:
```
command /hello:
    trigger:
        send "Hello, World!"
```
/hello -> works
/hello 123 -> works
/hello 1234 567 89 -> works
and currently only the first one would work, you'd get a pointless usage message saying like `Correct usage: /hello`

### Why?

currently the only way to do this is by adding [\<text>] to the end of the code (as far as I'm aware), I think it shouldn't send the usage message because it prevents the user from using the command when there is no reason to do so.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment]
I don't think this is a good idea, it could make the user think the command arguments they provide will do something while they actually won't. If you want a user to add useless command arguments, you can just add the optional argument yourself.

**Comment by Pikachu920** [comment]
Yeah, I agree with @TPGamesNL on this one. The user used the command wrong, so the usage message is sent. Plus. if a scripter really wanted this behavior they could just declare `command /hello [<string>]:`

**Comment by TPGamesNL** [comment]
In that case I'll close this issue, if a dev disagrees they can reopen it
