### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by DrizzExe** [SkriptLang/Skript#4572]
### Skript/Server Version

command /box:
    trigger:
        send player to world "box1"

### Bug Description

i cant make commands, when i do the code example, it doesnt do anything when i do /box

### Expected Behavior

supposed to make a command

### Steps to Reproduce

the code is simply just:
command /box:
    trigger:
        send player to world "box1"
![image](https://user-images.githubusercontent.com/98975988/152398954-2252978e-ba93-4513-8b4c-f52da5d6113c.png)

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/98975988/152398774-d241964e-4b95-408a-996f-37c2ca2b163a.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
@DrizzExe
