### ISSUE TITLE
On preparing craft

### ISSUE THREAD

**Issue by XenonsEU** [SkriptLang/Skript#4581]
### Skript/Server Version

```
git-Paper-61 for 1.18.1

Tried both Skript 2.6.1 and 2.6
```

### Bug Description

Event works as intended and whole code actually works until I try to send a message to the event player
No message is sent even though player has been used in lines before that

### Expected Behavior

message should be sent

### Steps to Reproduce

```
on preparing craft:
    loop 9 times:
        if "%slot loop-value of player's current inventory%" contains "stick named":
            set {_c} to true
    if {_c} is true:
        close player's inventory
        send formatted "%{c-red}%Custom items cannot be used in crafting recipes"
```
        
   A bit scuffed code but it all works except the send message

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/20037329/154823294-4fc2d764-f8a1-4f21-83e6-b265a82f712f.png)
Do you have disky addon?

**Comment by XenonsEU** [comment]
yeah, that would cause it?
huh interesting

**Comment by AyhamAl-Ali** [comment]
> yeah, that would cause it? huh interesting

Yes, Disky has a conflicting send effect which many have had this issue because of, check this [solution](https://github.com/SkriptLang/Skript/issues/4462#issuecomment-992424020)

**Comment by XenonsEU** [comment]
Thanks a bunch, have a great day
