### ISSUE TITLE
function to get tags, title or contents from a html file from online web server or local file

### ISSUE THREAD

**Issue by fr1g** [SkriptLang/Skript#4585]
### Suggestion

Make a function which allow me to get the title from a website.

### Why?

I'm making a function can make players share video links. it need the page title, not only while showing the video title, but also detecting whether the video exists. I found a addon by Nano(or shane? I'm not very sure) named Skraper which support it but it doesn't work anymore on 1.16.5 server. Due to that author doesn't update this addon anymore, I hope you can let Skript itself able to take this job.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by bluelhf** [comment]
I believe this is outside the scope of Skript. You'd have better luck with skript-reflect or another addon.

**Comment by TPGamesNL** [comment]
This is indeed outside the scope of Skript: it was determined quite a while ago that we would leave network and file IO in the hands of addons, and it won't be added to vanilla Skript

**Comment by Pikachu920** [comment]
not sure if it works anymore, but there was an addon for this in the past https://github.com/NanoDankster/Skraper

**Comment by fr1g** [comment]
> not sure if it works anymore, but there was an addon for this in the past https://github.com/NanoDankster/Skraper

I already tired but didnt work so I seek help here XD
