### ISSUE TITLE
a way to delete variables easily.

### ISSUE THREAD

**Issue by 1iSarah** [SkriptLang/Skript#4589]
### Suggestion

Hello, I'm thinking you could make it easier to do `delete all variables` so some people who want to do a new season or another server, won't have to delete skript folder or .csv file, they can just do `delete all variables` and (Suggesting)ONLY executable in console (effect commands) so maybe some people don't make a mistake of testing it or whatever.

### Why?

Some people (like me) needs to delete all variables without going to the trouble of deleting the file or anything related to variables.csv

This would be a better way to help people make a new season instead of doing `delete {var}` over and over and over.

### Other

Idk, maybe only executed by console so to avoid being hacked(griefed) etc.

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by Pikachu920** [comment]
why would you want to delete all variables often enough that this would be an issue?

**Comment by 1iSarah** [comment]
So there isn't a way to make the `delete all variables` happen?

**Comment by TPGamesNL** [comment]
I agree with Pikachu, I don't think this has a large enough use case to be added. If a dev disagrees, please reopen

**Comment by DelayedGaming** [comment]
> So there isn't a way to make the `delete all variables` happen?

• Stop server
• Delete `plugins/Skript/scripts/variables.csv`
• Start server
• Profit
