### ISSUE TITLE
Entity is in Liquid condition can't tell if player is in snow

### ISSUE THREAD

**Issue by YKDZ** [SkriptLang/Skript#4590]
### Skript/Server Version

Purpur 1551
Skript 2.6.1

### Bug Description

I have a skript like this:
```
on any movement:
    if player is in rain:
        if the gliding state of player is on:
            set gliding state of player to off 
```
But when player is in cold biome, like frozen plain, the rain will become snow, then I found that gliding state of player will not be turned off correctly. 

### Expected Behavior

Have a way to tell if player is in snow.
Maybe add a condition called "in snow"

### Steps to Reproduce

1. Make a skript using "in rain" condition
2. Go to the cold biome
3. Find that the skript will not work correctly.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Based on spigot/paper docs it only checks raining
> Check if entity is in rain

I couldn't find a method to check if entity is in snow, there could be some work around

**Comment by AyhamAl-Ali** [comment]
Closing as neither spigot nor paper have such method, as a work around you can use `if weather is raining` this returns true if it's raining or snowing
