### ISSUE TITLE
function doesn't want send message 

### ISSUE THREAD

**Issue by pawelkuwa** [SkriptLang/Skript#4591]
### Skript/Server Version

[04:15:14 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[04:15:14 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[04:15:14 INFO]: [Skript] Server Version: git-Paper-792 (MC: 1.16.5)
[04:15:14 INFO]: [Skript] Skript Version: 2.6
[04:15:14 INFO]: [Skript] Installed Skript Addons:
[04:15:14 INFO]: [Skript]  - Skellett v2.0.1 (https://forums.skunity.com/resources/skellett.24/)
[04:15:14 INFO]: [Skript]  - skript-ping v0.2
[04:15:14 INFO]: [Skript]  - FunnySkAddon v2.2.19-Beta (funnyskaddon.pl)
[04:15:14 INFO]: [Skript]  - DiSky v3.7.0 (https://disky.itsthesky.info/)
[04:15:14 INFO]: [Skript]  - skript-yaml v1.4
[04:15:14 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[04:15:14 INFO]: [Skript]  - HolographicDisplaysAddon v1.0.0b
[04:15:14 INFO]: [Skript]  - skript-db v1.3.3
[04:15:14 INFO]: [Skript]  - SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee)

### Bug Description

effect in function doesn't want message value to player

### Expected Behavior

send message with value to player

### Steps to Reproduce

execute following code

![image](https://user-images.githubusercontent.com/83598982/153694766-d044686f-3357-47d7-b6ee-21cebe9608b5.png)

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/83598982/153694769-22d18437-a883-4f68-9c1b-08d5b17b27ee.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Can't reproduce this, try to debug both {_p} and {_pi} using `broadcast "%{_p}%"` (inside quotation marks and variables percent signs) to know whether they're `<none>` or not, and check if your console has any errors

**Comment by pawelkuwa** [comment]
broadcast without percent signs with values {_p} and {_pol} returns correct value on chat

**Comment by AyhamAl-Ali** [comment]
Show the results here please, if {_p} isn't correct then it's why this isn't working

**Comment by pawelkuwa** [comment]
console doesn't have any errors 
this is following code 
![image](https://user-images.githubusercontent.com/83598982/153695085-6a8b9a43-58f0-4736-987e-311eace55322.png)

**Comment by pawelkuwa** [comment]
all line with {_p} works perfect but send effect no

**Comment by AyhamAl-Ali** [comment]
What happens if you do `send "%{_pol}%" to {_p}` or `send "test" to {_p}`

**Comment by pawelkuwa** [comment]
test with quotes also doesn't send

**Comment by AyhamAl-Ali** [comment]
Add the following lines to your function and send the results in a screenshot please
```v
send "%{_pol}%" to {_p} 
send "test" to {_p}
```

**Comment by pawelkuwa** [comment]
> Add the following lines to your function and send the results in a screenshot please
> 
> ```v
> send "%{_pol}%" to {_p} 
> send "test" to {_p}
> ```

after execute following lines function doesn't respond message only works this gui
![image](https://user-images.githubusercontent.com/83598982/153695231-fb088211-682f-4da6-b410-cd78229fdcf0.png)

**Comment by AyhamAl-Ali** [comment]
Can you show the code after you put the debug lines

**Comment by pawelkuwa** [comment]
``function setSlotsRynek(p: player):
    set {_pol} to size of {rynek::listItems::*}
    set {_slot} to 0
    set {_page} to 1
    if name of {_p}'s current inventory contains eCol("<neutral700>» <sky700>Rynek - "):
        set {_pa} to uncoloured name of {_p}'s current inventory
        replace all "Rynek - " with "" in {_pa}
        set {_page} to "%{_pa}%" parsed as number
        if {_page} > 1:
            open chest inventory with 6 rows named eCol("<neutral700>» <sky700>Rynek - strona %{_pa}%") to {_p}
    loop {rynek::listItems::*}:
        set {_info::*} to split loop-value at " dodał "
        set slot {_slot} of {_p}'s current inventory to ({_info::2}) parsed as itemtype with lore "" and eCol("<neutral700>» <stone400>Dodał: <green400>%{_info::1}%") and eCol("<neutral700>» <stone400>Cena: <yellow400>%{rynek::list::%{_info::2} parsed as itemtype%::%{_info::1} parsed as player%}% złota<stone400>!") and loop-index
        add 1 to {_slot}
    send "%{_pol}%" to {_p}
    send "test" to {_p}
    if {_li} > 51 * {_page}:
        set slot 53 of {_p}'s current inventory to skull of ("MHF_arrowright" parsed as offlineplayer) named eCol("<green600>Następna strona")
    else:
        set slot 53 of {_p}'s current inventory to skull of ("MHF_arrowright" parsed as offlineplayer) named eCol("<red500>Brak następnej strony")``

**Comment by pawelkuwa** [comment]
![image](https://user-images.githubusercontent.com/83598982/153695362-c0648960-e745-457d-a33c-e54be67e20ac.png)
better

**Comment by AyhamAl-Ali** [comment]
Could be something with your client chat filter OR Addon conflicting syntax like DiSky
To know the issue more try the following:
- Add `broadcast "%{_p}%"` at the beginning of the function code
- Add debug messages using `broadcast` after (outside) the first `if` section block and after (outside) the `loop` section block
- Try using Minecraft official client (without mods/clients) 
- Remove `DiSky` addon

**Comment by pawelkuwa** [comment]
after remove disky addon, disky folder and all files in Skript folder **without scripts** works

**Comment by pawelkuwa** [comment]
thank you

**Comment by DelayedGaming** [comment]
You can fix DiSky which caused your mentioned issue via [this step](https://github.com/SkriptLang/Skript/issues/4462#issuecomment-992424020).
