### ISSUE TITLE
Make Function Better (2)

### ISSUE THREAD

**Issue by LowScarlet** [SkriptLang/Skript#4601]
### Suggestion

Membuat lokal function ini akan sangat berguna (benar-benar berguna)
Example concept:
```vb
local function test():
  send "Nice" to console
local function test() :: text:
  return "Nice"
```

### Why?

Because it's very useful for the future of Skript

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Duplicate of #2188
