### ISSUE TITLE
Add support for filtering in ExprItemsIn

### ISSUE THREAD

**Issue by Pikachu920** [SkriptLang/Skript#4612]
### Suggestion

ExprItemsIn should allow you to filter what type of items you want. For example, instead of doing this:
```
loop all items in player's inventory:
  loop-item is a sword
```
you could just do
```
loop all swords in player's inventory:
```

### Why?

You can currently use the where filter to do this, but this would be prettier

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
https://github.com/SkriptLang/Skript/issues/4856
