### ISSUE TITLE
Add "on any move:" event back

### ISSUE THREAD

**Issue by ItzJulienYT** [SkriptLang/Skript#4621]
### Suggestion

Add the event "on any move:" back.

### Why?

Because i use it alot on my server and its really annoying to not hve it

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by Sorbon-CH** [comment]
https://docs.skriptlang.org/events.html#move

**Comment by AyhamAl-Ali** [comment]
`on any move` is from SkQuery however, Skript does have `on %entity type% move` event since 2.6 see [this](https://docs.skriptlang.org/events.html#move)
