### ISSUE TITLE
Problem with "set score ....'

### ISSUE THREAD

**Issue by ItzJulienYT** [SkriptLang/Skript#4622]
### Skript/Server Version

Sorry, im on my phone so i cant get the full info.

Skript version 2.6.1
Skript addons Tuske, SkRayall and skQuery

Server version 1.17

### Bug Description

When i updated to skript 2
6.1, my scoreboard skript was no longer working. The scoreboard was working before i changed from 2.6.0 to 2.6.1. And it seemed that there was an error that i didnt have before the update.

There was errors on
"set score "text" to sidebar of **loop-player** to 0

"loop-player" was the part that was causing the error. But i did loop all players before the code.
I remember the error being something like "Loop-player isnt an item nor an entity ....."

### Expected Behavior

There was supposed to be no errors and my scoreboard working properly. If you guys changed syntax. Please reply and sending the correct syntax.

### Steps to Reproduce

Before i updated, my scoreboard skript worked fine, there was no errors or anything wrong. Then when i updated, there was errors.

### Errors or Screenshots

Im on phone so i cant send the exact error.

"loop-player isnt an item nor entity ......."

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Skript plugin doesn't have that syntax, that's from SkRayFall. Make sure to update your addons and check your console logs, and if that error persists report to the addon issue tracker.
