### ISSUE TITLE
Loop blocks is broken

### ISSUE THREAD

**Issue by braplony** [SkriptLang/Skript#4623]
### Skript/Server Version

Skript version 2.6.1

### Bug Description

Skript doesn't know how to loop all blocks in a world

### Expected Behavior

It should work

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/96776088/155383253-89a664c9-0b6c-4a74-92e5-a299e798497b.png)

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/96776088/155383283-602f8855-35a3-4c51-a0b2-9c4aac9aaf3f.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
That expression doesn't exist. You can't loop all blocks in a world see [this](https://docs.skriptlang.org/expressions.html#ExprBlocks)
