### ISSUE TITLE
Player's UUID seem to not be saving when the player leaves

### ISSUE THREAD

**Issue by ZyroCube** [SkriptLang/Skript#4637]
### Skript/Server Version

```
[20:19:02 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:19:02 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[20:19:02 INFO]: [Skript] Server Version: git-Pufferfish-46 (MC: 1.18.1)
[20:19:02 INFO]: [Skript] Skript Version: 2.6.1
[20:19:02 INFO]: [Skript] Installed Skript Addons: 
[20:19:02 INFO]: [Skript]  - SkQuery v4.1.4
[20:19:02 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

For some reason on my server, player's uuid doesn't save when the player leaves. I created a skript that would show me a players uuid, and whenever they were online the correct uuid would show, but when the player leaves and I check their uuid its something completely different. Here is the skript:
```
command /test [<offline player>]:
    permission: admin
    trigger:
        send arg-1's uuid
```
Because of this, many skripts using uuid in them arent working properly.

### Expected Behavior

The offline player's uuid should of been shown.

### Steps to Reproduce

Possibly by creating a velocity proxy connecting to another server with skript

### Errors or Screenshots

![Capture](https://user-images.githubusercontent.com/90722430/156243169-786edee6-44cb-4f10-9e44-9807e309420e.PNG)

When the player joined the game i executed the test command and it showed their uuid, when they left and i executed the test command it would show a different uuid.

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Are you running offline mode server? Can you share your plugins list

**Comment by AyhamAl-Ali** [comment]
Try the same script with no plugins, only skript

**Comment by ZyroCube** [comment]
I tried, nothing happened.

**Comment by AyhamAl-Ali** [comment]
As far as I tested I couldn't replicate this using Paper/Pufferfish, with both online and offline mode, the reasonable reason may be is your proxy setup which you can find the same issue easily by searching it up, see [this](https://www.spigotmc.org/threads/getting-real-uuid-string-from-a-proxy-setup.116974/) 

Closing this as it's not Skript's fault unless proven further more.
