### ISSUE TITLE
Error getting the number of items in the player's inventory

### ISSUE THREAD

**Issue by NikeiPr1son** [SkriptLang/Skript#4643]
### Skript/Server Version

```markdown
https://pastenow.ru/4ded59b394014ff7c5b4ea07b3ad4677
```

### Bug Description

Writing the sale of items, I had an error with getting the number of items in the inventory. In version 2.6.1 of the plugin, it returns not quite correctly, which cannot be said about 2.5.3

### Expected Behavior

In plugin version 2.6.1 I think the values ​​should be returned more precise than 64 and 128. In plugin version 2.5.3 everything works fine. Please see my code, and screenshots of the accompanying version results.

My code: https://pastenow.ru/9d54f588ba581c892e4f17f07490364c

2.6.1: https://pastenow.ru/4ded59b394014ff7c5b4ea07b3ad4677
2.5.3: https://pastenow.ru/c163613a59c6f0b2b964bca92df0cd90

### Steps to Reproduce

In plugin version 2.6.1 I think the values ​​should be returned more precise than 64 and 128. In plugin version 2.5.3 everything works fine.

### Other

If this is a bug in version 1.12.2, then I understand everything, but still, please fix it.
If this is possible to implement on version 1.12.2, please update the plugin in releases if possible. Thanks!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Was able to reproduce on 1.12.2 but not on 1.16.5

**1.12.2**
![image](https://user-images.githubusercontent.com/20037329/156896240-b682cd6e-a9bc-4369-b78c-d456fc1c7b2f.png)

**1.16.5**
![image](https://user-images.githubusercontent.com/20037329/156896301-b6383212-dab8-48d1-944e-7b882a961b76.png)

**Comment by APickledWalrus** [comment]
Likely caused by https://github.com/SkriptLang/Skript/pull/4162
