### ISSUE TITLE
[the] bed[s] [location[s]] of %offlineplayers% 

### ISSUE THREAD

**Issue by kossnikita** [SkriptLang/Skript#4659]
### Suggestion

The method currently used to find the bed is Player.getBedSpawnLocation()
This does not allow you to find the beds of players who are not currently online.
Bukkit has a method OfflinePlayer.getBedSpawnLocation()
This method can replace the current one and it will work for both online and offline players.

### Why?

I ran into a problem when I wanted to find out all the players who own a certain bed. And I found that I can't do that with %offlineplayers%'[s] bed[s] [location[s]]. This expression only works with online players.

### Other

In my opinion, this change cannot affect already existing scripts.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
@kossnikita We do not close completed issues until a new release including them is out \:)

**Comment by kossnikita** [comment]
Oh, I'm sorry! It seemed to me that this was already included in the release after the merge.
