### ISSUE TITLE
Skript loading files in sub-directory first

### ISSUE THREAD

**Issue by Remixful** [SkriptLang/Skript#466]
Right now I have a problem.
So I have two scripts: `scripts/objects/bed.sk`  and `scripts/playerneeds.sk`. 
`bed.sk` is loading before `playerneeds.sk`. Why is this such a problem? Because `bed.sk` is relying on `playerneeds.sk` to load first.

Then how am I supposed to fix this problem? 

I did a test:
`scripts/a.sk` prints"a"
`scripts/a/b.sk` prints "b"
`scripts/c.sk` prints "c"

output:
`b
a
c`
This doesn't really make sense. Is it possible for someone to explain to me the order of how things are loaded? 

I would think Skript loads everything in the main directory first then starts going down sub-directories by order but I guess not?

**Comment by bensku** [comment]
Hmm, I guess that would make sense. However, load order has never been guaranteed so I do not see this as a bug.

**Comment by Snow-Pyon** [comment]
It makes sense and is better in this way, such as you can use a sub folder for APIs and put all your APIs there so they are loaded first, which makes a lot of things easier.

**Comment by Syst3ms** [comment]
It's like viewing files on Windows : 
First are loaded folders, and files in it are loaded alphabetically. Then files are loaded alphabetically.

**Comment by TheBentoBox** [comment]
Contrary to what you said, I think this makes particularly good sense, and I don't think this should be changed. Folders load first and are displayed at the top in Windows explorer, and I assume it's similar on other operating systems. And as Pyon said, this lets you force something to load first by putting it in an API folder, which is very nice. This is the way that's the most useful and makes the most sense with how file structures work.

**Comment by Adrihun** [comment]
It should be like this:
New config option, that will say 
**"load first:"**

and then write all of the script names like which one you want to load first, so if you want to load API.Sk first, then do

**load first: API.Sk, Other.sk**

**Comment by Snow-Pyon** [comment]
@Adrihun we can't just create a config option for everything, it isn't as easy as write in on the config.sk, it should be just as it is now, loading sub-directories first then the other scripts.
