### ISSUE TITLE
how to delete skript:<command name> from aliases

### ISSUE THREAD

**Issue by pawelkuwa** [SkriptLang/Skript#4668]
### Skript/Server Version

```markdown
2.6.1
```

### Bug Description

remove skript command aliases like skript:<command name>

### Expected Behavior

in plugin.yml i can't find anything

### Steps to Reproduce

create skript command

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Pikachu920** [comment]
why do you want to do this?

**Comment by pawelkuwa** [comment]
i want to reduce amount of commands and i want delete aliases from skript command, how i can do this?

**Comment by honkling** [comment]
This is a feature built into the vanilla Minecraft server, Skript couldn't remove it.

**Comment by TPGamesNL** [comment]
There's little use case for this, we shouldn't support this natively. There are probably plugins out there that can do this for you, otherwise you can probably script it (though it may need addons)
