### ISSUE TITLE
cant cancel on craft event in stone cutter

### ISSUE THREAD

**Issue by NiewiadomyYYXX** [SkriptLang/Skript#4669]
### Skript/Server Version

```markdown
skript 2.6.1
paper-68 (1.18.1)
```

### Bug Description

event on craft didn't work with stone cutter (its work with crafting table)

code:
on craft of red chiseled sandstone:
	cancel event

### Expected Behavior

it works

### Steps to Reproduce

on craft of red chiseled sandstone:
	cancel event

### Errors or Screenshots

no errors

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
`on craft` event is only for crafting table, stone cutter isn't covered by that however, paper has an [event](https://papermc.io/javadocs/paper/1.18/io/papermc/paper/event/player/PlayerStonecutterRecipeSelectEvent.html) for that
