### ISSUE TITLE
Skript on 1.18.1 does not accept mod items/blocks

### ISSUE THREAD

**Issue by JeonDohyeon** [SkriptLang/Skript#4678]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: arclight-1.18.1-e2655bbd (MC: 1.18.1)
[Skript] Skript Version: 2.6.1
[Skript] Installed Skript Addons: 
[Skript]  - SkChoke v1.1
[Skript]  - InvSK v0
[Skript]  - SkEtcR v3.3
[Skript]  - Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24)
[Skript]  - skript-yaml v1.3.2
[Skript]  - skDragon v0.17
[Skript]  - skUtilities v0.9.2 (https://tim740.github.io)
[Skript]  - skRayFall v1.9.25 (https://sk.rayfall.net)
[Skript]  - SkQuery v4.1.4
[Skript]  - SkBee v1.15.0 (https://github.com/ShaneBeee/SkBee)
[Skript]  - SkJade v1.3.4 (https://www.github.com/Ankoki-Dev/SkJade)
[Skript] Installed Dependencies: 
[Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

When I'm to open the modded server(with Arclight - which is working at this date) with mod items, Skript shows the error that it couldn't import the mod items.

### Expected Behavior

The plugin registers the mod items successfully, and skript scripts accept those items.

### Steps to Reproduce

1. Install Arclight.
2. Install Skript in `/plugins/`, and install known mods with items/blocks in `/mods/`.
3. Boot Arclight, and you'll see some red lines with *failed to register an item*.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Arclight is not supported, it's not a fork of spigot/paper as well

**Comment by JeonDohyeon** [comment]
Status update::
There was dynamic enum fetch on skript 2.5 #3918, to load modded items from mohist or Arclicht (that pr had a typo issue at the beginning- as *Archlight*). If creating an alias for each of the modded is the only way, I'll do it. If there's no way (meaning the plugin will always throw *invalid* even if used alias, changed code, and more to load modded items) there's no choice for me.


> Arclight is not supported, it's not a fork of spigot/paper as well

This is not true. Arclight is not a unsupported platform, since the Arclight fetches the spigot's code as upstream. It's not a direct fork of spigot, but Skript still just fully works on the latest releases and builds as if it were on spigot, including mod item *recognizations*, and excluding mod item *registerations*.

**Comment by TPGamesNL** [comment]
Arclight is not supported, regardless of whether or not it is a fork of Spigot. We support only Spigot and Paper officially, though we recommend Paper.

**Comment by JeonDohyeon** [comment]
> Arclight is not supported, regardless of whether or not it is a fork of Spigot. We support only Spigot and Paper officially, though we recommend Paper.

Got it, won't mentioning that again.

**Comment by 0XPYEX0** [comment]
#7126
