### ISSUE TITLE
Expected 0 tabs, but got 8 spaces

### ISSUE THREAD

**Issue by ErickHatesBMC** [SkriptLang/Skript#4679]
### Skript/Server Version

```markdown
[23:39:40 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[23:39:40 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[23:39:40 INFO]: [Skript] Server Version: git-Paper-408 (MC: 1.17.1)
[23:39:40 INFO]: [Skript] Skript Version: 2.6-alpha1
[23:39:40 INFO]: [Skript] Installed Skript Addons:
[23:39:40 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[23:39:40 INFO]: [Skript]  - skRayFall v1.9.25 (https://sk.rayfall.net/)
```

### Bug Description

When trying to use a script I wrote, it would continuously tell me that I needed to have 0 spaces/tabs on my triggers, when removing them it tells me to put it into triggers, I've updated skript, skutilities, and skrayfall and nothing has worked.

### Expected Behavior

N/A

### Steps to Reproduce

run funny quirky little script and watch the world burn
`command /joindungeon cryptofthefallen 1:
usage: &c/joindungeon [name] [floor]
    trigger:
        make player run command "mvtp crypt" as op
        loop all players:
            if loop-player is in world "crypt":
        add 1 to {_inworld}
            if {_inworld} = 1:
        make player run command "cryptmobspawnscriptf1" as op
        broadcast "&cDungeon starts in 60 seconds!" to "crypt"
        wait 60 seconds
        make player run command "bd open cryptentrance" as op
        make player run command "cryptclearmobsspawn" as op
        make player run command "cryptminibossspawn" as op
        wait 5 seconds
        make player run command "bd close cryptentrance" as op
        loop all items in the inventory of player:
            if loop-value is a tripwire hook named "&cBoss Key":
        make player run command "bd open bossentrance" as op
        make player run command "minecraft:tp @a{range=100} 420 69 666" as op
        wait 2 seconds
        make player run command "bd close bossentrance" as op
        make player run command "mm mobs spawn dungeonprotector 420 69 666" as op
            else:
        make player run command "thiscommanddoesnothingexceptforbeafunnyplaceholderforsomethingcompletelydifferentlaterdowntheline"

`

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/95004726/159151267-23f99318-b2d5-4393-a780-9c008e609e97.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by ErickHatesBMC** [comment]
![image](https://user-images.githubusercontent.com/95004726/159151368-455bb607-158f-41d0-ad78-b341ebf51653.png)
attaching errors from properly indented code

**Comment by AyhamAl-Ali** [comment]
This is not a place to ask for help however, your code has wrong indentation, read this [tutorial](https://skripthub.net/tutorials/33)
