### ISSUE TITLE
probleme with "clicked button is enchantment option..." condition

### ISSUE THREAD

**Issue by AKtomik** [SkriptLang/Skript#4686]
### Skript/Server Version

```markdown
[INFO] [Skript] Server Version: git-Paper-408 (MC: 1.17.1)
[INFO] [Skript] Skript Version: 2.6.1
[INFO] [Skript] Installed Skript Addons:
[INFO] [Skript] - Skellett v2.0.2 (https://forums.skunity.com/resources/skellett.24/)
[INFO] [Skript] - skript-gui v1.3-alpha3 (https://github.com/APickledWalrus/skript-gui)
[INFO] [Skript] - skDragon v0.17
[INFO] [Skript] - skUtilities v0.9.2 (https://tim740.github.io/)
[INFO] [Skript] - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[INFO] [Skript] - skRayFall v1.9.26 (https://sk.rayfall.net/)
[INFO] [Skript] - SkQuery v4.1.5
[INFO] [Skript] - SkriptJSON v1.0.0
[INFO] [Skript] - SkBee v1.14.1 (https://github.com/ShaneBeee/SkBee)
[INFO] [Skript] Installed dependencies:
[INFO] [Skript] - WorldGuard v7.0.6+1cff55f
```

### Bug Description

Hi !
I m tyhing to detecte what button is used in a `on enchant:` event.
I m go to the skriptlang official site and finde that:
```
on enchant:
    if the clicked button is enchantment option 1:
        set the applied enchantments to sharpness 10 and unbreaking 10
```
([https://docs.skriptlang.org/events.html#enchant])
and line 2 does not work (goto error/screeshoot)
i m was going to a forum, pepoles think it's a bug.
        

### Expected Behavior

possibility :

1. **probleme with the syntaxe**, but i finde this syntaxe in a lot of skript site
2. **probleme with an addon**
3. **a skript bug**

### Steps to Reproduce

just past the code in a skript file and reload

### Errors or Screenshots

```
[INFO] [Skript] Reloading Test.sk...
[ERROR] Line 2: (Test.sk)
The expression 'clicked block' may only be used in a click event
Line: if the clicked button is enchantment option 1:
[INFO] [Skript] Encountered 1 error while reloading Test.sk! (4ms)
```

### Other

sorry if my english is not good, im french.
thank for your pluging ! thank you in advance for your help !

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Till the PR gets merged, you can use this work around `clicked enchantment button` and that returns a number so compare like this `if clicked enchantment button = 1` # offer 1

**Comment by AKtomik** [comment]
Okk perfect, this is not a bug, just an error in the site ^^
**thank you for your help !**
