### ISSUE TITLE
send or broadcast doesn't work

### ISSUE THREAD

**Issue by Nether2046** [SkriptLang/Skript#4698]
### Skript/Server Version

```markdown
Server Version: 3383-Spigot-8965a50-b8a25cb (MC: 1.18.1)
Skript Version: 2.6.1
Installed Skript Addons: 
- skRayFall v1.9.27 (https://sk.rayfall.net/)
Installed dependencies: 
- SQLibrary v7.1
- Vault v1.7.3-b131
- WorldGuard v7.0.6+1cff55f
```

### Bug Description

send or broadcast event doesn't work.

### Expected Behavior

work

### Steps to Reproduce

I'm using BungeeCord.
It works fine on the other server under Bungie. I have not operated any plugins, and suddenly send and broadcast are no longer working, so I don't know what the cause is.

### Errors or Screenshots

[Netty Epoll Server IO #1/ERROR]: java.lang.IllegalStateException: zip file closed

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Pikachu920** [comment]
Include the entire error please

**Comment by Nether2046** [comment]
```error
[14:51:04] [Server thread/INFO]: Nether2046 issued server command: /test
[14:51:04] [Server thread/INFO]: test
[14:51:04] [Netty Epoll Server IO #0/ERROR]: java.lang.IllegalStateException: zip file closed
[14:51:04] [Netty Epoll Server IO #0/ERROR]: java.lang.IllegalStateException: zip file closed
[14:51:04] [Netty Epoll Server IO #1/ERROR]: java.lang.IllegalStateException: zip file closed
```

```code
command /test:
    trigger:
        broadcast "test"
        send "test"
```

**Comment by Pikachu920** [comment]
it seems like the code is working. I can see the "test" broadcast in the console output. I'm assuming the send was shown in your Minecraft chat?

**Comment by Nether2046** [comment]
Nothing is displayed in the chat even though it is output to the console
