### ISSUE TITLE
Relative forward 

### ISSUE THREAD

**Issue by Lotzyprod** [SkriptLang/Skript#4708]
### Skript/Server Version

```markdown
pufferfish 1.18.2, git-59
Skript 2.6.1
```

### Bug Description

Block forward of some directional block not correct

### Expected Behavior

Correct position.

### Steps to Reproduce

```markdown
on dispense:
	set block forward event-block to glowstone
```
it's only with upward direction

### Errors or Screenshots

![2022-03-29_22 43 14](https://user-images.githubusercontent.com/35628167/160695981-9dfcc5a0-f02c-4838-ba4a-880b5615ba75.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Pikachu920** [comment]
This is likely because the y coord of a block is actually .5 (e.g. a block at y 65 has a y coord of 65.5) so it's probably being rounded up?

**Comment by Lotzyprod** [comment]
> This is likely because the y coord of a block is actually .5 (e.g. a block at y 65 has a y coord of 65.5) so it's probably being rounded up?

I dont know, but when I use spigot expressions with reflect, it's work normally, I think its bug
