### ISSUE TITLE
Damage cause

### ISSUE THREAD

**Issue by Lotzyprod** [SkriptLang/Skript#4709]
### Skript/Server Version

```markdown
1.18.2 git-Pufferfish-59
Skript 2.6.1
```

### Bug Description

'Projectile' damage cause doesn't compare with 'damage cause' expression

### Expected Behavior

Correct work

### Steps to Reproduce

```
on damage of player:
	broadcast "%damage cause%"
	if damage cause is projectile:
		broadcast "All good."
	else:
		broadcast "bug detected"
```

### Errors or Screenshots

![2022-03-31_01 50 55](https://user-images.githubusercontent.com/35628167/160944596-04b5add1-5c23-46c4-867d-c1831bae3ea1.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
`projectile` here means (for the parser) an entity not a damage cause, try `a projectile` so `if damage cause is a projectile`

**Comment by Lotzyprod** [comment]
> `projectile` here means (for the parser) entity type not a damage cause, try `a projectile` so `if damage cause is a projectile`

Yes, with 'a' article all work

**Comment by AyhamAl-Ali** [comment]
Will keep this opened, `if damage cause is projectile` should work as expected but isn't therefore it is a bug.
