### ISSUE TITLE
I want it so some items cannot be crafted with a specific name

### ISSUE THREAD

**Issue by MinecraftIsCoolz** [SkriptLang/Skript#4714]
### Skript/Server Version

```markdown
I have the recently updated skript
```

### Bug Description

here is my code:

on craft:
    if event-item is blaze rod named "&cWand of the Flame":
        cancel event
        send "&cYou cannot do that!"

### Expected Behavior

There are no errors in the code, but it still doesn't work.

### Steps to Reproduce

on craft:
    if event-item is blaze rod named "&cWand of the Flame":
        cancel event
        send "&cYou cannot do that!"

This isn't working for some reason

### Errors or Screenshots

No errors

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
This is not a place to ask for help, check how to [debug](https://forums.skunity.com/wiki/debug/) here and ask in [skUnity discord help channels](https://discord.gg/0l3WlzBPKX7WNjkf)
