### ISSUE TITLE
BlockLineIterator misses the end block (in a loop of blocks at location between two locations)

### ISSUE THREAD

**Issue by arc-zen** [SkriptLang/Skript#4715]
### Skript/Server Version

```markdown
[03:35:52 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[03:35:52 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[03:35:52 INFO]: [Skript] Server Version: git-Paper-177 (MC: 1.18.1)
[03:35:52 INFO]: [Skript] Skript Version: 2.6.1
[03:35:52 INFO]: [Skript] Installed Skript Addons: 
[03:35:52 INFO]: [Skript]  - MorkazSk v1.2
[03:35:52 INFO]: [Skript]  - skRayFall v1.9.27 (https://sk.rayfall.net/)
[03:35:52 INFO]: [Skript]  - SkQuery v4.1.6
[03:35:52 INFO]: [Skript]  - SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee)
[03:35:52 INFO]: [Skript] Installed dependencies: 
[03:35:52 INFO]: [Skript]  - Vault v1.7.3-b131
[03:35:52 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

This bug relates to this syntax:
`loop blocks between block at (location goes here) and block at (location goes here):`
I discovered this syntax from [this](https://forums.skunity.com/threads/loop-blocks-between-locations.7178/) old forum post, hoping that it'd work. This syntax is useful in some of my future scripts, be it drawing particles in a line from one location to another, or looping enemies in a line.
I am unsure if this is caused by an external plugin. If it is, my apologies.

### Expected Behavior

The loop proceeds, looping the blocks between the two locations. In my skript, particles were supposed to play at the looped block, creating a sort of line effect (of which are supplied by plugins like SkDragon or SkRayFall but I do not want to use them as they are relatively outdated)

### Steps to Reproduce

more testable code:
```
command /test:
  trigger:
    set {_location1} to location 5 blocks in front of the player
    set {_location2} to location 5 blocks behind the player
    loop blocks between block at {_location1} and block at {_location2}:
      set loop-block to stone
```
my code that I was using (not very testable, but it is here if needed):
```
on damage:
	if attacker's tool is {rpg::item::ohmcall}:
		set victim's invulnerability ticks to 5
		if {rpg::item::ohmcall::cooldown::static_scream::%uuid of attacker%} is not set:
			set {rpg::item::ohmcall::cooldown::static_scream::%uuid of attacker%} to 2 seconds
			loop all entities in radius 6 around the victim:
				set {_vl} to location 2 blocks above location of the victim
				set {_el} to location 2 blocks above location of loop-entity
				if {_entities::*} does not contain loop-entity:
					loop-entity is a living entity
					loop-entity is not the victim or the attacker
					damage loop-entity by 0.5 hearts
					set last damage cause of loop-entity to attack
					add loop-entity to {_entities::*}
					draw 50 of dust using dustOption(rgb(245, 188, 66), 2.5) at {_el} with offset vector(0, 0.5, 0)
					wait 2 ticks
					loop blocks between block at {_vl} and block at {_el}:
						draw 50 of dust using dustOption(rgb(245, 188, 66), 2.5) at loop-block with offset vector(0, 0.5, 0)
```

### Errors or Screenshots

https://paste.gg/p/anonymous/02d14bd2ba0f42b4b106a30cabe50274

### Other

The console errors, and Skript does not proceed in running the code that is after the erroring lines.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Does this error always occur when executing the command, or only in certain locations with certain directions? Can you send a screenshot of your location & direction (e.g. from the F3 menu) when the error occurs?

**Comment by AyhamAl-Ali** [comment]
Might be related to #4647 if the player is facing down and Y becomes minus, can you try [this nightly build](https://github.com/SkriptLang/Skript/suites/5580805691/artifacts/180720589) and try to reproduce it

**Comment by TPGamesNL** [comment]
Thanks for the report, and well done on the testing :D

**Comment by AyhamAl-Ali** [comment]
Just adding to that, this is a duplicate of #4645 which is why the PR nightly build worked for the author
and Indeed well done on the testing 👌
