### ISSUE TITLE
[Docs] Title Correction for ExprFormatTime

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#4718]
### Suggestion

A minor correction of title for [this expression](https://docs.skriptlang.org/expressions.html#ExprFormatTime) to **Formatted Date**, followed by a class name correction [ExprFormatTime](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprFormatTime.java) to **ExprFormatDate**.

### Why?

Consumers could get confused from the misleading title `Formatted **Time**`, presumed this expression is to format a _Timespan_ instead of **Date**. The comments in mentioned class above clearly stated is to format a **Date**.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
I think this can be within the scope of #4319, can you make a PR on that branch?
