### ISSUE TITLE
Setting a variable to a direction

### ISSUE THREAD

**Issue by Remixful** [SkriptLang/Skript#472]
How can I set a variable to a direction and then actually _use_ it?
`set {_b} to block 1 meters east of the event-block`
✔️ Does work.

```
set {_facing} to east
set {_b} to block 1 meters {_facing} of the event-block
```
❌ Does not work and throws the error `event-block is not a world`

**Comment by TheBentoBox** [comment]
I guess adding this would be considered an enhancement more than a bugfix?

**Comment by bensku** [comment]
Still happens? I have since fixed several related parser bugs.

**Comment by FranKusmiruk** [comment]
This issue is quite not possible unless we make the direction expression be dynamic, which has its own issues. Closing.
