### ISSUE TITLE
Unreadable Encryption for Skript Files

### ISSUE THREAD

**Issue by SpaceDevz** [SkriptLang/Skript#4721]
### Suggestion

I think there should be encryption system for skripts. I think it would be cool to have a system like 

### Why?

This will be helpful to developers who want to hide their code from users. 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by SpaceDevz** [comment]
My link got removed, how sad.

**Comment by AVeryBadName** [comment]
That wouldnt stop files from getting leaked

**Comment by SpaceDevz** [comment]
> That wouldnt stop files from getting leaked

Yes, but It would allow developers to not have main source code leaked. And have an encrypted version leaked instead

**Comment by TPGamesNL** [comment]
If you haven't noticed the contradiction in the title: if the encryption is unreadable, Skript can't read it (definition of unreadable).

**Comment by bluelhf** [comment]
This would be useless, as it would be trivially easy to use Skript's intermediary in-memory representation of the script to reconstruct a deobfuscated version of it.
