### ISSUE TITLE
In recent versions of Paper, color codes stopped working in the console

### ISSUE THREAD

**Issue by oskarkk** [SkriptLang/Skript#4723]
### Skript/Server Version

```markdown
Skript Version: 2.6.1
Paper 1.18.2 builds since #244
```

### Bug Description

Since Paper build #244 color codes stopped working in the console. This affects some parts of plugin messages (as I've seen, some parts that are translated) and every colored log message, even in the form `log "<red>test"` - it's translated to color codes (section sign), not message components.

### Expected Behavior

Colors working.

### Steps to Reproduce

You can log colored message like that:

```
command /test:
  trigger:
    log "<red>test"
```

![image](https://user-images.githubusercontent.com/16339637/162703526-0777d15a-16a2-477b-a7d4-2f4611805866.png)

Or you can write some invalid script to see an error message in which the colors aren't working:

```
command /test:
  trigger:
    loggggg
```

![image](https://user-images.githubusercontent.com/16339637/162703636-dce60757-b6dd-48f1-84a4-81a34c562814.png)

It's kinda strange, because all parts of that message are translated, but in some of them colors work, and in others they doesn't. Here are the messages from [english.lang](https://github.com/SkriptLang/Skript/blob/master/src/main/resources/lang/english.lang):

```
reload:
	warning line info: <gold><bold>Line %s:<gray> (%s)\n
	error line info: <light red><bold>Line %s:<gray> (%s)\n
	reloading: Reloading <gold>%s<reset>...
	reloaded: <lime>Successfully reloaded <gold>%s<lime>. <gray>(<gold>%2$sms<gray>)
	error: <light red>Encountered <gold>%2$s <light red>error¦¦s¦ while reloading <gold>%1$s<light red>! <gray>(<gold>%3$sms<gray>)
	script disabled: <gold>%s<reset> is currently disabled. Use <gray>/<gold>skript <cyan>enable <red>%s<reset> to enable it.
	warning details: <yellow>    %s\n
	error details: <light red>    %s\n
	other details: <white>    %s\n
	line details: <gold>    Line: <gray>%s\n <reset>
```

### Other

You can find some information about the issue here:

https://github.com/PaperMC/Paper/pull/7560
https://github.com/PaperMC/Paper/issues/7590

Also, it's somewhat related to #3112 - it would be nice if Skript just used Adventure/MiniMessage everywhere, and it would fix problems like this.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Looking at conversations on the GH and Discord of Paper, we won't be able to both specify a log level and have colours for the console messages (they said Logger shouldn't support color parsing, and there is nothing about log levels in the Bukkit API). 
IMO we should keep the colours and ditch the log levels (since the colours should mostly tell the log levels, yellow=warn and red=error).

**Comment by oskarkk** [comment]
I should say that I'm actually using a custom configuration for log4j. By default Paper highlights the whole line in yellow/red in the console if the log level is WARN or ERROR:

```
<TerminalConsole name="TerminalConsole">
    <PatternLayout>
        <LoggerNamePatternSelector defaultPattern="%highlightError{[%d{HH:mm:ss} %level]: [%logger] %paperMinecraftFormatting{%msg}%n%xEx{full}}">
            <!-- Log root, Minecraft, Mojang and Bukkit loggers without prefix -->
            <!-- Disable prefix for various plugins that bypass the plugin logger -->
            <PatternMatch key=",net.minecraft.,Minecraft,com.mojang.,com.sk89q.,ru.tehkode.,Minecraft.AWE"
                          pattern="%highlightError{[%d{HH:mm:ss} %level]: %paperMinecraftFormatting{%msg}%n%xEx{full}}" />
        </LoggerNamePatternSelector>
    </PatternLayout>
</TerminalConsole>
```

In my configuration I've changed the default pattern to:

`[%d{HH:mm:ss} %highlight{%level}]: [%logger] %paperMinecraftFormatting{%msg}%n%xEx{full}`

... so only the word WARN/ERROR is highlighted. With the default configuration, on my second screenshot the whole error 
message would be in red like this:

![image](https://user-images.githubusercontent.com/16339637/162756362-5639c1dc-6c1d-4e58-abfb-6ccf0d83f3f4.png)

I support keeping the colours and ditching the log levels. Error level is better suited to the cases when a plugin breaks (and Skript breaks quite often).

**Comment by TPGamesNL** [comment]
> Error level is better suited to the cases when a plugin breaks (and Skript breaks quite often).

Good point, we should make sure that `Skript.logEx` should keep the log level, since this is what Skript uses to print its exceptions (the 'Something went horribly wrong with Skript.' errors)

**Comment by AyhamAl-Ali** [comment]
Keep in mind that spigot has another issue with this, probably encoding issue (since 1.12 might be earlier can't remember)
