### ISSUE TITLE
Respawn Anchor support.

### ISSUE THREAD

**Issue by Matt-MX** [SkriptLang/Skript#4726]
### Suggestion

Add Respawn anchor event support.

There is currently no way to see if a respawn anchor is **primed / charged** or **exploded**
The Respawn Anchor exploding event also does Not trigger the `on explosion` event, and I cannot find any addons that support this - I feel it should be an integral part of vanilla skript.

### Why?

This is a fairly reasonable addition, and could be seen as quite important.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by kossnikita** [comment]
There is no such event in Bukkit API. You can use `on rightclick on respawn anchor` event.
The only support that can be added is `%block% charges` for anchor charges.

**Comment by kossnikita** [comment]
The reason why the event does not fire is that it is used 'org.bukkit.event.entity.EntityExplodeEvent' and not used `org.bukkit.event.block.BlockExplodeEvent` for it. Maybe it really should be included in support.

**Comment by AyhamAl-Ali** [comment]
- Related Respawn Charges blocks methods can be found [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/data/type/RespawnAnchor.html) which can be added as expressions
- [PlayerRespawnEvent#isAnchorSpawn](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerRespawnEvent.html#isAnchorSpawn())
- [World#isRespawnAnchorWorks](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/World.html#isRespawnAnchorWorks())

as for `on explode` event see this PR
- #3990

**Comment by Pikachu920** [comment]
>[World#isRespawnAnchorWorks](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/World.html#isRespawnAnchorWorks())
what an awful name for that method lol

**Comment by Axecyy** [comment]
i've tried making a skript that disabled end crystal and respawn anchor block damage, but suprisingly enough, end crystals worked but not the respawn anchor part!

because guess what, as this suggests, the on explosion event doesn't support respawn anchors.

That got me pretty confused, but yeah this should be added if possible.

**Comment by kossnikita** [comment]
Ender Crystal is entity, this is not block.

**Comment by Axecyy** [comment]
well yeah but still respawn anchors should quite literally be counted in as a explosion event?
they also explode on ignition?
