### ISSUE TITLE
Trusted Members issue

### ISSUE THREAD

**Issue by Armydusa** [SkriptLang/Skript#4733]
### Skript/Server Version

```markdown
3.2.8
```

### Bug Description

The trusted members back button in island menu does not respon when clicking it

### Expected Behavior

it was supposed to send me back to the main page of the skyblock menu

### Steps to Reproduce

Nothing. Haven't touched config or anything

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
This is Skript plugin issue tracker.
