### ISSUE TITLE
[Suggestion] Stop ALL Sounds

### ISSUE THREAD

**Issue by agentgamer100** [SkriptLang/Skript#4748]
### Suggestion

(Didn't see anything for this in the docs so :/)

With the link given below, you can stop specific sounds from a player.
https://docs.skriptlang.org/effects.html#EffStopSound

Although there's nothing for stopping all sounds.

### Why?

Since Minecraft has /stopsound and can be used for specific sounds (i.e. /stopsound Notch * minecraft:block.bell.use), why not just have /stopsound implemented with no extra arguments (i.e /stopsound Notch)

### Other

idk syntax could be
`stop all sound[s] (to|for) %players%`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Vrganj** [comment]
Player#stopAllSounds only got introduced in 1.17. `SOUND_CATEGORIES_EXIST` can definitely be deleted because they exist since at least 1.12. The sound category should probably be optional, though, since if it isn't passed, it'll stop the specific sound in all categories.
