### ISSUE TITLE
Left click event does not go off when targeting armor stands

### ISSUE THREAD

**Issue by nemxo0709** [SkriptLang/Skript#4750]
### Skript/Server Version

```markdown
Hey, the left click event does not work when targeting an armor stand.

This is an especially big problem when using ModelEngine for custom mobs.

By the way, is there ANY way to register a left click when targeting an armor stand? this would help me out a ton
```

### Bug Description

Left click event not registered by skript when clicking an armor stand

### Expected Behavior

Should go off when left clicking an armor stand

### Steps to Reproduce

on left click:
     broadcast "test"

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by nemxo0709** [comment]
It does not work when specifically targeting the lower half of an armor stand

**Comment by AyhamAl-Ali** [comment]
This is not a place to ask for help however, try `on damage` event and see if that works

**Comment by nemxo0709** [comment]
> This is not a place to ask for help however, try `on damage` event and see if that works

it does work, although I am trying to avoid using on damage since I am trying to shoot a mage spell from far away via left-click which doesn't work when targeting a ModelEngine mob (made of armor stands)

**Comment by DelayedGaming** [comment]
Cannot reproduce bug on Paper 1.19.3 and Skript 2.6.4, although `on right click:` or `on click:` with right click action does not fire the event while holding nothing and looking in the sky.

**Comment by TheLimeGlass** [comment]
Potentially a plugin was blocking the on left click. This does work as intended.
