### ISSUE TITLE
Skript Reload/Load Report

### ISSUE THREAD

**Issue by Zabrid** [SkriptLang/Skript#4759]
### Suggestion

What if when u reloaded a script, and it takes longer than like idk, 3 seconds, it generates like a report (maybe similar to how Spark does it) on what lines took the longest to parse? That way I don't need to manually check each event and each line to try and make my parsing times faster.

### Why?

Would speed up, many fold, the process of figuring out why tf my script is taking 30 seconds to parse

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by APickledWalrus** [comment]
What does your script look like where it's taking that long to parse? Are you using any addons?
