### ISSUE TITLE
place block naturally

### ISSUE THREAD

**Issue by SmellyBurger** [SkriptLang/Skript#4761]
### Suggestion

So i was trying to create a skript that **set a block above the player's clicked block** BUT i ran across an issue, if the player rightclicks a wall, then the block will be in the wall! So i came up with this **BRILLIANT** idea:

An effect that allows the server to place a block naturally! This would be the syntax:
**place %block% naturally at %location%**

This would make it so, for instance, to set a block at a location without getting a block placed in the wall. It would just place next to the wall.

### Why?

It makes it easier to create code that allows the player to set blocks without having to do fancy shmancy stuff to figure out if the block/location is in the wall.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Itzdlg** [comment]
The math required for this is 1) probably not Skript's job to do and 2) requires the location of perspective as well. For example, if it's a wall, then the location is simply a block on the wall. How does Skript know to place it on the side you want, instead of the other one?

**Comment by AyhamAl-Ali** [comment]
There is no such method in paper nor spigot. Once such method is added you can suggest this again.
If anyone from the team thinks otherwise feel free to reopen.
