### ISSUE TITLE
Introduce spectator target expression

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#4768]
### Suggestion

Hey! This issue is to get your opinion on adding a `spectator target of %player%` syntax (and `%player%'s spectator target`) to define for example the entity that is followed by the camera when it is in spectator. [Link to Spigot API docs](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#setSpectatorTarget%28org.bukkit.entity.Entity%29) 

### Why?

This is an expression that would be useful for many Skript users.

### Other

If this suggestion is accepted, I will take care of making the small pull request! :)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Already added in 2.4 
![image](https://user-images.githubusercontent.com/20037329/169697879-1c111124-9ed8-4eb6-8574-ec56122045c0.png)
