### ISSUE TITLE
any supports on 1.16.5 hybrid bukkit servers?

### ISSUE THREAD

**Issue by junyang12** [SkriptLang/Skript#4778]
### Suggestion

any supports on 1.16.5 hybrid bukkit servers? I want to open pixelmon mod on my server with version 1.16.5 but most on hybrid servers are not working. does it only supports catserver 1.12.2? 

### Why?

I really want to use skript on 1.16.5 hybrid bukkit server

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
If they're not Spigot/PaperMC forks then it will most likely not work and so far there are no plans for supporting any other platform than Spigot/PaperMC.
