### ISSUE TITLE
Player trigger's don't work

### ISSUE THREAD

**Issue by TheBest-del** [SkriptLang/Skript#4780]
### Skript/Server Version

```markdown
Server version 1.7 - 1.18 ( ViaVersion )
Engine version: Paper Spigot 1.17.1
```

### Bug Description

```
on join:
    wait 10 seconds
    set player flight mode to true
    send "&aLatanie zostało uruchomione"

```
After entering the server and waiting, nothing happens.

Plugin version "skript"
is the newest one downloaded from this github

**Comment by APickledWalrus** [comment]
Please be sure to fill out (and follow the instructions) of the issue template. We can't help you without that information. If you're still having an issue, feel free to open a new report 🙂
