### ISSUE TITLE
On inventory open 

### ISSUE THREAD

**Issue by xApafaas** [SkriptLang/Skript#4785]
### Skript/Server Version

```markdown
Skript: 2.6.1
```

### Bug Description

L'évenement On inventory Open ne fonctionne pas
Pas d'erreur lors d'un /sk reload 

### Expected Behavior

Exécution de l'évenement

### Steps to Reproduce

Rien

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by bluelhf** [comment]
Nous ne parlons pas français, veuillez utiliser l'anglais à la place. Je ne parviens pas non plus à reproduire le bogue sur Skript 2.6.2.

**Comment by AyhamAl-Ali** [comment]
Please 
- Fill in the blanks correctly
- Provide more useful information so we can identify and understand the issue (check your console as well)
- Use the latest Skript version (currently: 2.6.2) and test if your issue still occur
- Preferably use English language
