### ISSUE TITLE
PlayerPickupArrowEvent

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4788]
### Suggestion

Adding PlayerPickupArrowEvent event `"arrow pickup", "[player] picking up [an] arrow"`
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerPickupArrowEvent.html

### Why?

dew it

### Other

Maybe merge this event with `on pickup` class (not the syntax) similar to EvtItem

**Comment by dkfrede** [comment]
You can use skript-reflect to import classes from Spigot's API.
