### ISSUE TITLE
Skript Folder Not Appearing

### ISSUE THREAD

**Issue by EvMaster-YT** [SkriptLang/Skript#4791]
### Skript/Server Version

```markdown
I'm running Craftbukkit 1.17.1, and Skript 2.6. When I run /skript info, it says /skript help in chat.
```

### Bug Description

I ran and reloaded the server, but the Skript folder wasn't created.
![Skript](https://user-images.githubusercontent.com/73354669/172639985-26fda007-235b-485c-85e4-b7f13730e446.png)

### Expected Behavior

There is supposed to be a folder with the config and scripts folder.

### Steps to Reproduce

I started my server, then dragged Skript into the plugins folder. I did /reload in chat.

### Errors or Screenshots

This is the one error I got:
![l](https://user-images.githubusercontent.com/73354669/172641322-28ffaf0a-a405-4af5-b657-29afed279ee9.PNG)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
> Skript requires Spigot to work. You heard it right, Bukkit does not work. Paper, which is a fork of Spigot, is recommended; it is required for some parts of Skript to be available.
