### ISSUE TITLE
Configurable 'loadbefore' Directory for Scripts

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#4800]
### Suggestion

Introduce a toggleable and configurable `loadbefore` directory in scripts folder for certain scripts to be loaded ahead before any other scripts.

This directory with configurable name in `config.sk` (if toggled on) will be generated in scripts folder and reserved for scripts to load ahead of other scripts (also applies with parallel loading enabled).

### Why?

I'll bring an example. You have to append a character at start of a script file to have it load before any other scripts, as we all know that scripts and subdirectories with scripts are loaded alphanumerically, where some who is sensitive to such may not prefer this option.
_P.S._ This benefits for custom syntaxes created with [skript-reflect](https://github.com/TPGamesNL/skript-reflect).

Another example is now Skript has a `parallel loading` system which distributes scripts across **X** amount of threads to load, which could lead to certain scripts with dependable scripts to fail due to disrupted loading order followed by scripts with different parsing time.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Would be nicer to have this as script option (per script)

**Comment by TPGamesNL** [comment]
Users should not have to think about load order, this should be handled by Skript and addons. This will be easier for addons after the structure API (https://github.com/SkriptLang/Skript/pull/4108)
