### ISSUE TITLE
Unknown Command Issue

### ISSUE THREAD

**Issue by Sovlix** [SkriptLang/Skript#4811]
### Skript/Server Version

```markdown
v2.1.2 | Spigot-1.8.8
```

### Bug Description

```
[09:31:42 INFO]: Wrong usage. Try again with /crgive <player>.
[09:31:42 INFO]: Unknown command. Type "/help" for help.
```
I got unknown command when I type the command in console.

### Expected Behavior

I want to give my players rewards after voting using the cmd

### Steps to Reproduce

```
command /crgive [<player>]:
	trigger:
		if arg 1 is not set:
			send "&cWrong usage. Try again with &e/crgive <player>&7."
			stop
		if arg 1 is set:
			add 1 to {crs::%arg-1%}
			send "&cADDED!"`
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Unsupported server & skript version.
