### ISSUE TITLE
HTTP Requests

### ISSUE THREAD

**Issue by dkfrede** [SkriptLang/Skript#4815]
### Suggestion

Build in HTTP request in Skript.

This will / would help the community have a more understanding about HTTP and requesting, doing this there is no need for third party addons to support this feature.

Its a pretty need function to have in modern Minecraft Servers.

### Why?

Because it would help the community.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
We understand your goal of reducing the use of addons but this is outside scope of Skript as stated [here (comment)](https://github.com/SkriptLang/Skript/issues/4585#issuecomment-1036395568)
