### ISSUE TITLE
on jump event

### ISSUE THREAD

**Issue by OpUlTrA3032** [SkriptLang/Skript#4818]
### Skript/Server Version

```markdown
Skript: 2.6.2
Server: 1.16.5-Spigot
```

### Bug Description

I have a Elevator Skript but i can't use it because the Skript Version do not find the "on jump" event:

Error: Can't understand this event: 'on jump'

### Expected Behavior

No error with the *on jump* event

### Steps to Reproduce

I did nothing 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
`On jump` event is only supported in Paper as stated in the docs 
![image](https://user-images.githubusercontent.com/20037329/174403785-de8b871c-8b89-449b-ba04-9c96a5c12ed9.png)
Spigot have not yet implemented this event.
