### ISSUE TITLE
Issue with getting a player's online status

### ISSUE THREAD

**Issue by PZSleezi** [SkriptLang/Skript#4825]
### Skript/Server Version

```markdown
[20:08:24 INFO]: [Skript] Server Version: git-Paper-794 (MC: 1.16.5)
[20:08:24 INFO]: [Skript] Skript Version: 2.6.1
[20:08:24 INFO]: [Skript] Installed Skript Addons: None
[20:08:24 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

When using the if player is online condition through the use of a variable to check if a player is online the result is always false whether or not a player is online.

### Expected Behavior

A player should be seen as online instead of always offline

### Steps to Reproduce

`command /test <offline player>:
  trigger:
    set {_plr} to arg-1
    if {_plr} is online:
      set {_s} to true
    else:
      set {_s} to false
    broadcast "%{_s}%"`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
I can't replicate this, try to test this with latest Skript version ([2.6.2](https://github.com/SkriptLang/Skript/releases/tag/2.6.2))
This was usually casued by Vixio or Disky but seems like you have no addons


![image](https://user-images.githubusercontent.com/20037329/174587665-a768ed29-a791-4913-b4c5-cd7856105a62.png)
![image](https://user-images.githubusercontent.com/20037329/174587063-f9a262b6-5caf-4b66-b659-cba77350cb36.png)

**Comment by AyhamAl-Ali** [comment]
@PZSleezi Any news on this? 
*The issue wil be closed soon if it stay idle*

**Comment by JohnHeikens** [comment]
![image](https://user-images.githubusercontent.com/50964021/196996757-5b96a794-5acc-47da-afeb-316a64b9001a.png)
this returns 'offline'.
on the same version of skript checking without a variable aka this
![image](https://user-images.githubusercontent.com/50964021/196996939-11c8acac-d10c-48e4-adc3-d7632683823e.png)
returns 'online'.

**Comment by TheLimeGlass** [comment]
> ![image](https://user-images.githubusercontent.com/50964021/196996757-5b96a794-5acc-47da-afeb-316a64b9001a.png) this returns 'offline'. on the same version of skript checking without a variable aka this ![image](https://user-images.githubusercontent.com/50964021/196996939-11c8acac-d10c-48e4-adc3-d7632683823e.png) returns 'online'.

Make a new issue, we need more information.

**Comment by AyhamAl-Ali** [comment]
> ![image](https://user-images.githubusercontent.com/50964021/196996757-5b96a794-5acc-47da-afeb-316a64b9001a.png) this returns 'offline'. on the same version of skript checking without a variable aka this ![image](https://user-images.githubusercontent.com/50964021/196996939-11c8acac-d10c-48e4-adc3-d7632683823e.png) returns 'online'.

See #4125

**Comment by humamlmc** [comment]
I have same error. It caused by disky

**Comment by humamlmc** [comment]
Problem was fixed by setting **fix-skript-online-status** in DiSky config to true
