### ISSUE TITLE
TNT Explosion

### ISSUE THREAD

**Issue by kleymixx** [SkriptLang/Skript#4840]
### Suggestion

```
on place:
    if name of player's tool is "&7TNT &cThanos":
        add location of event-block to {boost::tnt::*}
        send "&8[&e&lANARCHY&8] &7You place &8[&7TNT &cThanos&8] &7on coordinates: &c%location of event-block%"
        remove 1 of player's held item from player

on break:
    if {boost::tnt::*} contains location of event-block:
        cancel event
        set event-block to air
        remove location of event-block from {boost::tnt::*}

on explode:
    if {boost::tnt::*} contains location of event-block:
        cancel event
        remove location of event-block from {boost::tnt::*}
        create an explosion of force 20 at event-block
    else:
        create an explosion of force 2 at event-block
```

### Why?

After place the block, its location is saved, I need it to look at the locations when the TNT explodes, if the TNT location has the saved location, then the TNT explosion increases by 20, if it does not match, then it is set to 2, I have no more ideas how to do this, help please.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Sorry but this is not a place to ask for help, you can join [SkUnity discord help channels](https://discord.gg/xnS3JANY) and ask there \:)
