### ISSUE TITLE
Add support for Where/Filter and their Inputs in addons

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4856]
### Suggestion

Add support for Where/Filter and their Inputs for addons.

Having some sorta implementation so that addons can handle their own predicates in syntaxes

`(where|that match) \\[<.+>\\]`

Mainly the `%*classinfo% input` so that the addon doesn't have to make their own variant.

**Comment by TPGamesNL** [comment]
The predicate part is just a condition, which addons can register. The input also allows for addon types. What part doesn't support addons yet?

**Comment by TheLimeGlass** [comment]
The only allowed class for the where filter ExprInput is ExprFilter.

**Comment by TPGamesNL** [comment]
Can't addon just create their own ExprInput?

**Comment by sovdeeth** [comment]
This should be implemented with #6737
