### ISSUE TITLE
Vanish/Reveal players do not work

### ISSUE THREAD

**Issue by TheSmartKid0079** [SkriptLang/Skript#4869]
### Skript/Server Version

```markdown
Using Skript Version 2.6.2, skRayFall v1.9.27, Vault v1.7.3, WorldGaurd v7.0.7, and skript-gui v1.3-beta1
```

### Bug Description

When vanishing a player, I am not able to reveal the player with the skript. This occurs when I hide the player from a specific player/group then attempt to reveal the player with skript but it doesn't work, all my fail safes occur reassuring that it does the right thing except for the fact the line "reveal player" does not work. The file put into the console is not a text file it is a SK file.
[vanishtest.sk.txt](https://github.com/SkriptLang/Skript/files/9052389/vanishtest.sk.txt)

### Expected Behavior

It is supposed to reveal the player but instead does nothing

### Steps to Reproduce

Hide a player from all players or from a group of players, then once that is called, make a simple if true/false statement to check if they are still hidden then attempt to reveal the player.
![image_2022-07-06_030523895](https://user-images.githubusercontent.com/108788090/177489940-dccef62a-9f56-4861-a0cb-6fdce5a6bb2d.png)

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/108788090/177488773-1c83000c-fbe4-4c84-881c-1650ef2c9a6e.png)
![image](https://user-images.githubusercontent.com/108788090/177488832-43f48aa8-9ccf-484c-8ac7-f3dfb450840e.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Though probably unrelated to this, the `exprs.length` check are nonsensical here:
https://github.com/SkriptLang/Skript/blob/db3214d13f9a57cd4e6904d7f33bf08302b442c4/src/main/java/ch/njol/skript/effects/EffPlayerVisibility.java#L74
https://github.com/SkriptLang/Skript/blob/db3214d13f9a57cd4e6904d7f33bf08302b442c4/src/main/java/ch/njol/skript/effects/EffPlayerVisibility.java#L76
as both patterns contain 2 types

**Comment by TPGamesNL** [comment]
@TheSmartKid0079 I think the issue in your code is that you're hiding `arg-1`, but revealing `player`:
![image](https://user-images.githubusercontent.com/29547183/177741319-36a0fdf5-6395-4cf2-ab28-e68b035e4989.png)

**Comment by TheSmartKid0079** [comment]
Yup I just realized that a few days ago and just forgot to update my post, sorry about that, but I had legit 8 people look at it and they all mistook it!
