### ISSUE TITLE
Goat horn variants don't work

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#4882]
### Skript/Server Version

```markdown
2.6.3
or at least commit from https://github.com/SkriptLang/Skript/pull/4881
```

### Bug Description

Using `sing goat horn` gives the `ponder goat horn` instead, all aliases give the ponder variant. 

This is because the de-duplication mechanism of aliases loading (AliasesProvider#L295) sees the ponder goat horn and the sing goat horn as equal. This is in turn because they're both `minecraft:goat_horn`, and Bukkit doesn't have a goat horn ItemMeta yet (https://hub.spigotmc.org/jira/browse/SPIGOT-7034), which means Skript doesn't have a way to see the difference between the item metas.

When Bukkit adds this, we may have to modify `ItemData#compareItemMetas` to be able to compare goat horn metas, but it'll have to be tested then.

### Expected Behavior

not to do that

### Steps to Reproduce

`!give sing goat horn to me`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
It's actually Mojang that pushed 1.19 with unfinished features, so Spigot/Bukkit is waiting to see what Mojang will do, like how the Shrieker block did have a dedicated packet in the snapshots, but when release came out, Mojang remove it and merged it into generic events for the time being. 1.19 was not properly constructed.

**Comment by APickledWalrus** [comment]
Oh I think this has been fixed but we will need to confirm

**Comment by TheLimeGlass** [comment]
fixed
