### ISSUE TITLE
Split expression case sensitivity from config.sk

### ISSUE THREAD

**Issue by Lotzyprod** [SkriptLang/Skript#4886]
### Skript/Server Version

```markdown
2.6.2
```

### Bug Description

Make expression dependent on sensitivity value in config
add '(?i)' to regular expression if 'case sensitive: false'

### Expected Behavior

split should be non case sensitive

### Steps to Reproduce

```
broadcast  "%"aBcd" split at "b"%"
```
output: 'aBcd'

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
I think you mean ExprSplitJoin is case insensitive?

**Comment by Lotzyprod** [comment]
> I think you mean ExprSplitJoin is case insensitive?

Yes
https://github.com/SkriptLang/Skript/blob/d09320866fa15bd6f2fc77b13f3e0cfd2c46ef36/src/main/java/ch/njol/skript/expressions/ExprJoinSplit.java

**Comment by TPGamesNL** [comment]
If `"aBcd" split at "b"` returns a single element, it is case sensitive (i.e. the casing of input matters), not case insensitive.

**Comment by AyhamAl-Ali** [comment]
As far as I can see the code of that expression doesn't check case sensitivity from config.sk like replace effect for example
