### ISSUE TITLE
On Move event

### ISSUE THREAD

**Issue by thelastguest666667** [SkriptLang/Skript#4888]
### Suggestion

Please add the on move or on player move event

### Why?

it would make it easier to do a freeze command

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Already exists: https://docs.skriptlang.org/events.html#move but you need Skript 2.6 at least

**Comment by thelastguest666667** [comment]
It doesnt for me...

**Comment by AyhamAl-Ali** [comment]
If you need help with something not working you can ask in [SkUnity help channels](https://discord.com/channels/135877399391764480/138027100593455104) if it turns to be a bug/issue you can report it here

**Comment by thelastguest666667** [comment]
![image](https://user-images.githubusercontent.com/79613764/178126155-49228155-1d5b-4110-a433-aa2180f0f10e.png)

**Comment by thelastguest666667** [comment]
> If you need help with something not working you can ask in [SkUnity help channels](https://discord.com/channels/135877399391764480/138027100593455104) if it turns to be a bug/issue you can report it here

invite me to it

**Comment by AyhamAl-Ali** [comment]
I pasted the wrong link.. here is the one https://discord.gg/yhFrXx4g

**Comment by thelastguest666667** [comment]
Thanks.

**Comment by AyhamAl-Ali** [comment]
You probably running spigot, the event requries PaperMC

**Comment by thelastguest666667** [comment]
I have papermc.
