### ISSUE TITLE
Is Op doesn't show up in documentation

### ISSUE THREAD

**Issue by sovdeeth** [SkriptLang/Skript#4910]
### Skript/Server Version

```markdown
2.6.3
```

### Bug Description

`if %player% is op:` doesn't show up in documentation, likely because instead of it being a condition like normal, it's basically hijacking PlayerData and using pattern matching to do comparison. I don't know if there's good reason for this implementation, but it means it doesn't show up in the docs.

### Expected Behavior

The docs should include this "condition".

### Steps to Reproduce

N/A

### Errors or Screenshots

N/A

### Other

Not sure if this should be suggestion or bug, I went with bug to be safe.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment]
In its current impl, I don't think we should add this to the docs, it's not a condition after all. It's the same reason we don't have anything for `if %entity% is a cow:`. 

However, I'm also unsure if we should keep `op` as an EntityData. I don't think there are many advantages to it, it could be better to remove the EntityData and switch to a condition (and whatever other syntax we might want for it). However, this would be a breaking change.

Open to feedback

**Comment by sovdeeth** [comment]
I do agree with switching it to a condition. The `is a cow` thing not being in docs makes sense, but I don't think it's a great analogy here. An op just doesn't seem like a type of player, it seems like a property a player has, which would make more sense as a condition in my opinion.

**Comment by AyhamAl-Ali** [comment]
IMO We should switch `is op` to a condition & add an expression for `getOperators()`
