### ISSUE TITLE
Skript v2.6.1 & Skript v2.6.2 & Skript v2.6.3 do not load on Paper/PaperSpigot 1.8.8

### ISSUE THREAD

**Issue by Juliaxe** [SkriptLang/Skript#4912]
### Skript/Server Version

```markdown
Skript: 2.6.1 through 2.6.3
Minecraft: Paper / PaperSpigot 1.8.8
```

### Bug Description

Skript will not activate, even though it used to before I tried to upgrade to v2.6.3. When v2.6.3 did not work, I tried to downgrade back to v2.6.2.

### Expected Behavior

Skript to load and activate.

### Steps to Reproduce

- Be on Paper / PaperSpigot 1.8.8
- Have any Skript version through v2.6.1 to v2.6.3 installed.
- Upgrade to v2.6.3.
- If v2.6.3 does not activate, downgrade to v2.6.2.

### Errors or Screenshots

- https://gist.github.com/Juliaxe/8208cbd940ae55c94cf7b44ac0e99cb7
- https://gist.github.com/Juliaxe/43a2d06f33645dd72dbc4a4f26e881a6

### Other

1.8.8 / legacy versions are supported in any 2.6.x version, as stated on GitHub.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Skript dropped 1.8 support long time ago, 2.6.X supports 1.9+ but it is the last version to support 1.9-1.12, Skript 2.7 will only support 1.13+

If you want Skript for 1.8 you can use [this fork](https://github.com/Matocolotoe/Skript-1.8/releases)
