### ISSUE TITLE
add 'glass bottle' alias to empty bottle

### ISSUE THREAD

**Issue by J-ak-e** [SkriptLang/Skript#4913]
### Suggestion

![image](https://user-images.githubusercontent.com/102185375/179204208-e2e20737-81a1-4349-af35-d148c7dd7bdc.png)
add the 'glass bottle' alias to 'empty bottle'

### Why?

people will almost never use this alias and will wonder why the line using 'glass bottle' errors

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by ShaneBeee** [comment]
this is already an alias
https://github.com/SkriptLang/skript-aliases/blob/e99be898254965b0207992f66a3289ab6744106e/brewing.sk#L2

I tested to make sure it works:
```
> !send glass bottle
[19:27:27 INFO]: executing 'send glass bottle'
[19:27:27 INFO]: empty bottle
```
it does
