### ISSUE TITLE
Could this plugin interfere with console commands?

### ISSUE THREAD

**Issue by FalZz03** [SkriptLang/Skript#4914]
### Skript/Server Version

```markdown
Server Version: git-Paper-341 (MC: 1.18.2)
Skript Version: 2.6.3
Installed Skript Addons:
 - SkQuery v4.1.6
 - SkBee v1.15.3
```

### Bug Description

I notised when i tried using the console for my MC server the commands i executed did nothing such as op/deop a player (No commands i try to execute works). When that happened i contacted the host i am using (MTXServ) after chatting with a admin from mtxserv they found out that the skript plugin was interfereing with the console commands i am trying to execute, he wanted me to try fixing some of the scipts i made to have no errors when i rebooted the server, after fixing all of them i get the same problem.

So i came here to ask if you know what could of happened to make the console commands not working.

### Expected Behavior

What should happen when i execute a command in the console, such as op is that the player should get operator, and deop is that the player should not have operator.

### Steps to Reproduce

I get no errors trying to execute console commands. all that happens when i execute is nothing.

### Errors or Screenshots

No errors, nothing happens, when i execute console commands.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Skript plugin doesn't do anything by itself, you need a script coded by you/someone to interfere with anything in the server, do you have an script running?

**Comment by AyhamAl-Ali** [comment]
If you needed any help or still need help you can always ask in [SkUnity discord help channels](https://discord.gg/yhFrXx4g)
