### ISSUE TITLE
Skript ignoring most metadata when comparing

### ISSUE THREAD

**Issue by staridiot** [SkriptLang/Skript#4928]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-65 (MC: 1.19)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons: 
[Skript]  - SkBee v1.17.1 (https://github.com/ShaneBeee/SkBee) (also tried without addons)
[Skript] Installed dependencies: None
```

### Bug Description

There seems to be an issue when comparing an item with no metadata to one with metadata. Such that, if I have a Thorns 3 enchanted book and compare it to a Flame 1 enchanted book, it will think they are the same. This also occurs with armor & tools. Skript will confuse a blank diamond axe (as in, no name, no lore, no enchantment, no damage) with one that's been re-named and enchanted.

### Expected Behavior

Skript should be able to tell the difference between items with differing metadata

### Steps to Reproduce

```
on leftclick:
	set {_tool} to player's tool
	set {_nbt1} to nbt compound of player's tool
	set {_nbt2} to nbt compound of player's off hand tool
	if {_tool} is player's off hand tool:
		message "Congratulations! You're holding two of the same item!"
		message "NBT of main hand: %{_nbt1}%"
		message "NBT of off hand: %{_nbt2}%"
		if {_nbt1} is not {_nbt2}:
			message "Skript thinks these are the same item, they are not."
```

Pull out two different enchanted books from the creative inventory, hold one in the main hand, one in the off hand. Left click. Skript will think the differently enchanted books are the same. I've found there's an exception to this; damage values on items will properly identify the item as different.

### Errors or Screenshots

Screenshot of comparing a blank diamond axe to an enchanted and re-named diamond axe: https://imgur.com/a/NrgoOSF

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
Can confirm, but only when using a variable like {_tool}

Skript is not finding a valid comparator for CondCompare (during parsing)

**Comment by TheLimeGlass** [comment]
Cannot replicate with the following code and an enchanted book of flame 1 and sharpness 2

Addon related?
```vb
command /com:
	trigger:
		set {_test} to player's tool
		wait 3 seconds
		if player's tool is {_test}:
			broadcast "True"
```
