### ISSUE TITLE
The syntax "now formatted as (string)" doesn't work anymore

### ISSUE THREAD

**Issue by Shykuzo** [SkriptLang/Skript#4932]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Purpur-1632 (MC: 1.18.2)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons: 
[Skript]  - Skent v3.1.0
[Skript]  - BungeeSK v2.0.0 (https://github.com/ZorgBtw/BungeeSK)
[Skript]  - skript-gui v1.3-beta2 (https://github.com/APickledWalrus/skript-gui)
[Skript]  - skript-yaml v1.4
[Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[Skript]  - SkQuery v4.1.6
[Skript]  - SkBee v1.17.1 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: 
[Skript]  - Vault v1.7.3-b131
```

### Bug Description

Before I upgraded to Minecraft 1.18.2 and Skript 2.6.3, I could use the "now formatted as (string)" syntax, unfortunately, since my version change, I can't use it, I always get an error.

### Expected Behavior

Change the date formatting.
For example, the date is "01/01/2000 - 00:00:00", after formatting in "dd/MM/yyyy", I should get "01/01/2000"

### Steps to Reproduce

Create a Skript.
Add a command, an event, ...
Add in this command, this event, ... the line "send "%now formatted as ""dd/MM/yyyy""%""
See that it doesn't work

### Errors or Screenshots

Line 9: (Punishment\Manager\HistoryManager.sk)
     Can't understand this expression: now formatted as ""dd-MM-yyyy HH-mm-ss""
     Line: load yaml "%getModeratorsHistoryFolder({_Moderator})%[%now formatted as ""dd-MM-yyyy HH-mm-ss""%] (%{_Type}%) %{_Target}%.yml" as "PUNISHMENT-%{_Moderator}%-HISTORY"
  
Line 68: (Punishment\Manager\HistoryManager.sk)
     Can't understand this expression: now formatted as 'dd-MM-yyyy HH-mm-ss'
     Line: load yaml "%getPlayersHistoryFolder({_Target})%[%now formatted as 'dd-MM-yyyy HH-mm-ss'%] (%{_Type}%) %{_Moderator}%.yml" as "PUNISHMENT-%{_Target}%-INFRACTION"  

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Seems like you upgraded from an old version before 2.6

_Skript 2.6 update:_
> Fix quote parsing. This change allows singular double quotes to be used in variables and (expressions within strings), instead of doubled double quotes

Doubled quotes are no longer needed (nor working) with expressions within strings
So you will just need to make `""` -> `"` e.g. `now formatted as "dd-MM-yyyy HH-mm-ss"`
