### ISSUE TITLE
Unable to parse player in some cases

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/Skript#4943]
### Skript/Server Version

```markdown
2.6.3
```

### Bug Description

When name of player is Chinese Chars, Skript cannot get OfflinePlayer correctly

### Expected Behavior

Nothing

### Steps to Reproduce

``` 1. set {P} to "天刹" parsed as offline player  ``` _# parse it by Skript_
``` 2. send "%name of {P}%" ```  _# this return null_

``` 3. set {P} to player.getServer().getOfflinePlayer("天刹") ```  _# parse it by skript-reflect -> Bukkit_
``` 4. send "%name of {P}%"  ```  _# this return <天刹>_

### Errors or Screenshots

![ParseSK1](https://user-images.githubusercontent.com/50171612/180616777-ea51e543-81bd-4199-b51e-41b13919f7b4.png)
![ParseSK2](https://user-images.githubusercontent.com/50171612/180616780-b59b027a-6cd0-4009-8f2b-0f99aa8d5c05.png)
![ParseBK](https://user-images.githubusercontent.com/50171612/180616772-d2500bff-09bb-4a93-bfdb-5cb9f508d7eb.png)

**The player is offline when I was test**

### Other

Nothing

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Can you send your exact server platform and version, and your plugin list?

Usernames with characters except for `a-zA-Z0-9_` aren't allowed in Minecraft, so we need to know how you got them.

**Comment by 0XPYEX0** [comment]
> Can you send your exact server platform and version, and your plugin list?
> 
> Usernames with characters except for `a-zA-Z0-9_` aren't allowed in Minecraft, so we need to know how you got them.

Minecraft allow to use special characters🤔
I know that because I tested it in Paper-1.16.5, 2 years ago.

This is my server info
![Infos](https://user-images.githubusercontent.com/50171612/180617332-45958595-afa2-4c4e-b0b9-66efc72351f3.png)

**Comment by Lotzyprod** [comment]
> Can you send your exact server platform and version, and your plugin list?
> 
> Usernames with characters except for `a-zA-Z0-9_` aren't allowed in Minecraft, so we need to know how you got them.

Non official clients (pirate copies) of minecraft allow you to make nicknames with any characters

But parse nicknames with not allowed characters needen in some other cases, for example:
Geyser (for bedrock support) change players nicknames (if player from bedrock) to ".%player's name%"

**Comment by TPGamesNL** [comment]
According to both NameMC and protocol.vg not:
![image](https://user-images.githubusercontent.com/29547183/180617383-482bb8c5-4f77-4aec-843c-7655459d5ff3.png)
[[1]](https://namemc.com/search?q=%E5%A4%A9%E5%88%B9)
![image](https://user-images.githubusercontent.com/29547183/180617398-d2682930-5474-4c33-99f0-1b2e2c1910e2.png)
[[2]](https://wiki.vg/Mojang_API#Change_Name)

Just saw comment above, that explains it then.

In `config.sk`, there is an entry called `player name regex pattern` (near line 200). If you change this to `.{1,16}`, it should work for you (assuming the length restriction is the same).

**Comment by Lotzyprod** [comment]
> According to both NameMC and protocol.vg not: ![image](https://user-images.githubusercontent.com/29547183/180617383-482bb8c5-4f77-4aec-843c-7655459d5ff3.png) [[1]](https://namemc.com/search?q=%E5%A4%A9%E5%88%B9) ![image](https://user-images.githubusercontent.com/29547183/180617398-d2682930-5474-4c33-99f0-1b2e2c1910e2.png) [[2]](https://wiki.vg/Mojang_API#Change_Name)
> 
> Just saw comment above, that explains it then.
> 
> In `config.sk`, there is an entry called `player name regex pattern` (near line 200). If you change this to `.{1,16}`, it should work for you (assuming the length restriction is the same).

Oh, didn't see this option before, I think this issue closed, waiting author :+1:

**Comment by 0XPYEX0** [comment]
I add Chinese Chars to the regex, and now it is fixed
![Fixed](https://user-images.githubusercontent.com/50171612/180617639-617b4b90-2da0-4118-b9be-9979d34b1d9f.png)

Thanks for your help~~
