### ISSUE TITLE
copy recursives list with its indices

### ISSUE THREAD

**Issue by AKtomik** [SkriptLang/Skript#4947]
### Suggestion

hi ! 
**It would be nice  to copy an entiered list whit his recusive objects**.
but, whit using `set {list2::*} to {list1::*}`, that not work, and just not copy all recursive varibles from the first list to the second...

I propose tow way to do that : 
- you can make the effect `set %objects% to %objects%` can copy recursive list
- or **you can add a parameter to this expression like that `set recursive %objects% to %objects%`, to prevent from lags.**

### Why?

Its possible to clear recursive list with `clear`, that clear recursive objects from the list.
It would be perfect if you can copy it with `set` !!
To move any data, make backup and copy... 
Just, **use recursive list in full potential 👌**

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by DelayedGaming** [comment]
Do you mean to allow support for carrying indices to another list? Like this?
![Screenshot_20220724-233023_Edge](https://user-images.githubusercontent.com/72163224/180654837-2926b552-1b29-4a4a-9488-7cda66a8362b.png)

**Comment by AyhamAl-Ali** [comment]
They probably mean to copy all the children of a list e.g.
List: `{a::*}` have `{a::b::C::D} = "Y"` when executing `set {z::*} to {a::*}` it should also copy C and D level so you can broadcast `{z::b::C::D}` which will be `Y`

Tests
![image](https://user-images.githubusercontent.com/20037329/180655247-1f16143b-6e41-4263-99c0-00c08b9d422b.png)

**Comment by DelayedGaming** [comment]
Ohh okay, then my example is a different thing from this. Will have it in another issue.

**Comment by AyhamAl-Ali** [comment]
> Ohh okay, then my example is a different thing from this. Will have it in another issue.

I believe it's related, if this gets implemented it should already copy the indicies as  well, e.g. see my example above

**Comment by AKtomik** [comment]
**yes, exactly.**
Copy recursive list, which includes copy his indices.
Both are just verry important to use the full potenrial of the variables !
I add it to the title.
