### ISSUE TITLE
x wood pressure plate

### ISSUE THREAD

**Issue by ChaoticPoly** [SkriptLang/Skript#4950]
### Suggestion

Change things like acacia wood pressure plate to just acacia pressure plate

I was trying to do an on step on pressure plate: thing and was stumped for about 10 minutes because 'event-block is acacia pressure plate' doesn't work due to the syntax being 'event-block is acacia wood pressure plate' 

### Why?

Makes it more simple and not need to debug why something such as 'event-block is acacia pressure plate' doesn't work

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment]
I can't replicate this:
```
on step on pressure plate:
	if event-block is acacia pressure plate:
		broadcast "true"
	else:
		broadcast "false"
```
Gives the correct result, true when stepping on an acacia pressure plate and false otherwise. What Skript and server version do you use?
