### ISSUE TITLE
Re-add expressions in the command parameters definition

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4957]
### Suggestion

Njol had an idea to allow expressions in the command so for example:
```
command /setspawn <location = %spawn of player's world%>:
    trigger:
        set {server::spawn} to location-argument
```
as an example assuming location can be parsed from string.

This is currently commented out because I think Njol couldn't figure out how to get them to work as default variables never worked.

I recently added a utility method and fixed some issues with getting values at runtime and comparing to parsing in my default variables fix pull request. This can be worked on after that pull request is merged https://github.com/SkriptLang/Skript/pull/4566

### Why?

I think it was a neat idea. The amount of possibilities is endless, and this just makes another advantage to Skript over using Java command registration, being able to define any default argument is mind boggling.

**Comment by TPGamesNL** [comment]
This already works:
```
command /test [<number = %2 * 4%>] [<offline player = %player%>]:
	trigger:
		message "%arg-1% ; %arg-2%"
```
![image](https://user-images.githubusercontent.com/29547183/181215341-4179c977-9514-4a06-80bb-a0409ebeab0f.png)
