### ISSUE TITLE
Making a scoreboard with a result of an error

### ISSUE THREAD

**Issue by SmudgyKibbles57** [SkriptLang/Skript#4958]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here:
https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here:
https://skriptlang.github.io/Skript
[Skript] Skript's tutorials can be found here:
https://docs.skriptlang.org/tutorials
[Skript] Server Version: 3550-Spigot-14a2382-9a8e080 (MC: 1.19)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons:
[Skript] - skRayFall v1.9.28 (https://sk.rayfall.net/)
[Skript] - skQuery v3.21.4
[Skript] - TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe
[Skript] Installed dependencies:
[Skript] - Vault v1.7.3-b131
```

### Bug Description

I get a massive error in the console making a scoreboard

### Expected Behavior

For it to show a scoreboard when they use the command /helloscoreboards

### Steps to Reproduce

Its having an error at the line of code:
`set name of sidebar of player to "&6Hello Scoreboards!"`

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/68578212/180880166-6678dcd1-8413-4ad5-9fb8-612939af73da.png)
![image](https://user-images.githubusercontent.com/68578212/180880248-7d6ed945-4e5b-455d-8562-4e5b1d334a51.png)
![image](https://user-images.githubusercontent.com/68578212/180880342-64b9d823-8257-4adb-aa02-d515a8f73890.png)
![image](https://user-images.githubusercontent.com/68578212/180880375-4f1be99b-a281-4fe2-80ca-959789c5a921.png)
Sorry if i posted two of the same images

### Other

Code for you to copy and paste:
`command /helloscoreboards:`
`    trigger:`
`        set name of sidebar of player to "&6Hello Scoreboards!"`
`        set score "My Score:" in sidebar of player to 0`
`        wait 10 seconds`
`        wipe player's sidebar`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Skript doesn't have a scoreboard syntax. The error is happening not related to a scoreboard.

The error is happening because Tuske didn't register `customenchant` classinfo, you may want to try an updated version of Tuske if you're not using the forked version of it.
