### ISSUE TITLE
Skript crashes when loading line which sets list to lots of numbers

### ISSUE THREAD

**Issue by cottondell** [SkriptLang/Skript#4977]
### Skript/Server Version

```markdown
[23:45:07] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[23:45:07] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[23:45:07] [Server thread/INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[23:45:07] [Server thread/INFO]: [Skript] Server Version: 3507-Spigot-fa893f0-c3f219e (MC: 1.19)
[23:45:07] [Server thread/INFO]: [Skript] Skript Version: 2.6.3
[23:45:07] [Server thread/INFO]: [Skript] Installed Skript Addons: None
[23:45:07] [Server thread/INFO]: [Skript] Installed dependencies: None
```

### Bug Description

This has been tested on a new 1.19 spigot server with no plugins apart from skript and ViaVersion (because I'm using Minehut) installed.

Line of code:
```
set {_baseblocks.x::*} to -1, 0, 1, -2, -1, 0, 1, 2, -2, -1, 0, 1, 2, -2, -1, 0, 1, 2, -1, 0 and 1
```

Just having this line of code in a script causes the server to freeze when skript loads the script(s). I'm fairly sure that it is skript taking a long time to parse the line and so the server freezes. I have seen other reports of it happening  (#2942 and #2355) but it hasn't been fixed (or at least doesn't work in this skript version).

This is an easy work around which is just to split up the setting of the values into multiple lines, like so:
```
set {_baseblocks.x::*} to -1, 0, 1, -2, -1, 0 and 1
add 2, -2, -1, 0, 1, 2 and -2 to {_baseblocks.x::*}
add -1, 0, 1, 2, -1, 0 and 1 to {_baseblocks.x::*}
```

### Expected Behavior

Set the list variable to the specified values.

### Steps to Reproduce

Place the line of code inside of a skript file, where it would cause no syntax errors (e.g. inside of a function) then reload the skript or start the server. It should freeze and not allow player's to join.

### Errors or Screenshots

Console error from log file:
[latest.log](https://github.com/SkriptLang/Skript/files/9193935/latest.log)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Known issue, due to too many expressions to parsed in a single line. You can also break them up with brackets `()` nothing can be done about this single issue currently as it's a way larger scope. It's like exponentially adding to the parse of the line.

There is currently already a temporary solution for this planned for 2.7 where Skript will stop and print a warning if the time taken to parse a single line has taken longer than the configuration value. More information at https://github.com/SkriptLang/Skript/pull/4784

**Comment by cottondell** [comment]
Ok thanks!
Glad you can just break it up with brackets or else it would look very messy on multiple lines.
