### ISSUE TITLE
Remove Item

### ISSUE THREAD

**Issue by Dominak3** [SkriptLang/Skript#4978]
### Skript/Server Version

![image](https://user-images.githubusercontent.com/29547183/181203244-0ca99e93-dd20-4b75-b9fc-e05240955831.png)

### Bug Description

When I see the "remove compass from arg-1's inventory" section in my script, my server shuts down.    (arg-1 is a player)

### Expected Behavior

I think it could remove the item from the inventory.

### Steps to Reproduce

remove compass from arg-1's inventory (arg-1 is player)

### Errors or Screenshots

No bugs report it to me.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Can you provide your console log, and more of your script?

**Comment by Dominak3** [comment]
> Can you provide your console log, and more of your script?

My skript. And in the console nothing is written about the script
[skript.txt](https://github.com/SkriptLang/Skript/files/9197666/skript.txt)

(Yes I know it should be stored in .sk but I put it in .txt to send it.)

**Comment by TPGamesNL** [comment]
You said your server shut down when running the code, therefore I will need the console log to find out exactly why it shut down.

**Comment by AyhamAl-Ali** [comment]
Your code has a typo `from arg-1's invetory` which gives an error when you reload it, I have tested the skript on Paper-50 1.19 and all worked well.

If you mean something else please provide more info and we can reopen this issue.
