### ISSUE TITLE
Option to sort a list variable from highest to lowest value

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#498]
set {_sortedlist::*} to sorted {_score::*}
This only allows for sorting a list from lowest to highest value it seems.

Could you add an option to sort it the other way (highest to lowest) as well?

**Comment by Snow-Pyon** [comment]
As said before, invert a list is so easy, you just have to do:
```
set {_list::*} to sorted {yourList::*}
loop {_list::*}:
    set {_current} to loop-index parsed as int - 1
    add {_list::%size of {_list::*} - {_current}%} to {_invertedList::*}

**Comment by bensku** [comment]
Having it as part of Skript would improve performance.

**Comment by bloggy** [comment]
Can you make it so that you can sort the values of list entries? 

`		set {_a} to "Marion"
		set {_b} to "Alex"
		set {_c} to "Walburg"
		add {_a} to {_test::*}
		add {_b} to {_test::*}
		add {_c} to {_test::*}
		set {_test::a} to 100
		set {_test::b} to 200
		set {_test::c} to 300
`
And then sort this from highest to lowest and the other way?

**Comment by Matocolotoe** [comment]
@Snow-Pyon The issue should have a higher priority like low or medium because most of the time we (skript devs) have to use horrible methods to sort variables properly that may make the server go boom boom

**Comment by Matocolotoe** [comment]
Why did it unassign you I didn't touch anything wtf

**Comment by Max094Reikeb** [comment]
It doesn't work with me the "set ... to sorted..." how do I do ?

**Comment by bloggy** [comment]
Toplist function, so badly needed :-)

**Comment by TPGamesNL** [comment]
I feel like since [Reversed List](https://skriptlang.github.io/Skript/expressions.html#ExprReversedList) exists now, this is not really needed anymore.

**Comment by bloggy** [comment]
The sorting function of skript is not working well at all. It kinda sorts alphabetically. Also sorting a list deletes the index, which makes it useless for toplists.

**Comment by Wealthyturtle** [comment]
Closing in favor of #371
