### ISSUE TITLE
Add "damage cause" to "on vehicle damage"

### ISSUE THREAD

**Issue by Frithy0** [SkriptLang/Skript#4982]
### Suggestion

Add "damage cause" to "on vehicle damage"

The "on vehicle ..." has very little events variables, it's sad, can you add more events variables ?  

### Why?

Need to know if my vehicle take damage by explosion

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
The on vehicle damage event only has attacker, vehicle and damage. This is how Spigot's API is, which is probably how Mojang has it.

I think what you're looking for is an entity damage event;
```
on damage of minecart:
    damage was caused by explosion
    broadcast "cart took %damage% points of damage"
```
