### ISSUE TITLE
Something with type expression api pattern option parsing

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4984]
### Suggestion

So there are type expression api pattern options like `-` (will null and no default expression) and `*` (force to be a literal) etc

If I define `(entity example [of %-*entitydatas%]|%entitydatas%'[s] entity example)` Skript will error stating that the entity data must be prefixed with `-` because it's an optional, that error.
Well it is prefixed with it where it's optional, but since it's a choice pattern, Skript expects the nullable character on both of the entitydatas, small little bug, maybe it has to do with the literal character being involved, i'm not sure. Skript stop erroring when you add the nullable and literal to the other side too (didn't check without literal).

PropertyExpression doesn't have this error currently, because it doesn't use a choice pattern, it just registers two patterns, avoiding the choice pattern, which is why this minor parse issue never came up.

Also there should be an error check in place if `~` and `*` are used as you should not be able to use both in the same expression, they negate eachother and should error accordingly. Currently it'll just accept the first placed character, and that's not proper handling, Skript needs to error and tell the developer to pick one.

**Comment by TPGamesNL** [comment]
This is correct behaviour, because `exprs` will always have length 2 in this pattern, however it is used. `exprs[1]` will always refer to the second type, so for example in `entity example` or `entity example of {_e}`, `exprs[1]` will not be provided. Therefore, it needs to have the nullable modifier.
