### ISSUE TITLE
Remove Item/Set Item Crash

### ISSUE THREAD

**Issue by SHOOSH12SR** [SkriptLang/Skript#4987]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation be found here: https://skriptlang.github.io/Skript
[Skript] Skript's tutorials can be found here: https://docs.skriptland.org/tutorials
[Skript] Server Version: 3551-Spigot-14a2382-9a8e080 (MC: 1.19)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons:
[Skript] - Skellet v2.0.7 (https://forums.skunity.com/resources/skellet.24)
[Skript] - SkDragon v0.17
[Skript] - SKQuery v4.1.6
[Skript] - SkBee v1.17.3 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: None
```

### Bug Description

when running ``remove (item) from player`` or ``set player's tool to (item)`` the server crashes

Server Log: [2022-07-30-4.log.gz](https://github.com/SkriptLang/Skript/files/9225630/2022-07-30-4.log.gz)
Crash Report:  [crash-2022-07-30_10.19.51-server.txt](https://github.com/SkriptLang/Skript/files/9225633/crash-2022-07-30_10.19.51-server.txt)
Script:  [BattleAxe.txt](https://github.com/SkriptLang/Skript/files/9225645/BattleAxe.txt)

### Expected Behavior

if running ``remove (item) from player`` it should remove the item from the player
if running ``set player's tool to (item)`` it should set the player's tool to the specified item

### Steps to Reproduce

run ``remove (item) from player`` or ``set player's tool to (item)`` in game

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Can you try your script without addons and plugins. Also, you might try PaperMC if the former didn't work

I have tested your script and all worked well (I thrown the axe and the `set to air` didnt crash and the axe came back to me)
![image](https://user-images.githubusercontent.com/20037329/181893574-9d10321f-974d-4a05-8a99-ba06590bdf42.png)

My `/sk info`
```md

[11:18:20 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[11:18:20 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[11:18:20 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[11:18:20 INFO]: [Skript] Server Version: git-Paper-50 (MC: 1.19)
[11:18:20 INFO]: [Skript] Skript Version: 2.6.3
[11:18:20 INFO]: [Skript] Installed Skript Addons: None
[11:18:20 INFO]: [Skript] Installed dependencies:
[11:18:20 INFO]: [Skript]  - Vault v1.7.3-b131
```

**Comment by SHOOSH12SR** [comment]
PaperMC doesn't run on my pc for some reason so i tried it with only skript and i removed the other plugins and sk addons and it still crashed 

Log: [latest.log](https://github.com/SkriptLang/Skript/files/9225770/latest.log)
Crash Report: [crash-2022-07-30_11.36.11-server.txt](https://github.com/SkriptLang/Skript/files/9225772/crash-2022-07-30_11.36.11-server.txt)

**Comment by AyhamAl-Ali** [comment]
I have switched to Spigot 3553 (2 versions newer than yours) and couldn't replicate, can you tell/show how are you causing that error? like the way you throw/are you looking at ground while throwing?

It is for sure about placing an AIR becuase the error says block place packet 
> 	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32)

**Comment by SHOOSH12SR** [comment]
i updated my server to spigot 1.19.1 (latest) and it still crashed (using sk addons)

vid of me replicating it: [2022-07-30 12-01-32_Trim.zip](https://github.com/SkriptLang/Skript/files/9225855/2022-07-30.12-01-32_Trim.zip)
Log:  [latest.log](https://github.com/SkriptLang/Skript/files/9225859/latest.log)
Crash Report:  [crash-2022-07-30_12.02.29-server.txt](https://github.com/SkriptLang/Skript/files/9225861/crash-2022-07-30_12.02.29-server.txt)

**Comment by AyhamAl-Ali** [comment]
Now I am able to replicate it ONLY using creative mode, I have been testing on survival mode the whole time and didn't happen at all

**Comment by SHOOSH12SR** [comment]
thank you for your help

**Comment by AyhamAl-Ali** [comment]
Actually thank you for your reporting this and doing all the steps requested above \:)

**Comment by SHOOSH12SR** [comment]
you're welcome

**Comment by AyhamAl-Ali** [comment]
So far, this seems to be a server issue, when in creative mode it seems to do something related to block place packet with right click event, I have tested few things and here are the results:

**The crashed ONLY happen with Spigot, PaperMC seems to have this fixed**

---

### Test 1
Code:
```py
# Just these 2 lines of code without anything before the set effect
on right click:
    set player's tool to air
``` 
Result: **Will crash** while holding the axe or any other item/block

### Test 2
Code:
```py
on right click:
    wait a tick
    set player's tool to air
``` 
Result: **No crash** while holding the axe or holding air or any other item/block

---

I would suggest reporting this issue to spigot and maybe you can link this issue tests in the new issue on spigot.

**Comment by SHOOSH12SR** [comment]
Thank you again for your help :)

**Comment by AyhamAl-Ali** [comment]
You're welcome, did the `wait 1 tick` solution work for you?

**Comment by SHOOSH12SR** [comment]
i cant try it right now i but will make sure to tell you when i try it

**Comment by SHOOSH12SR** [comment]
yes it worked, thank you for helping :)
