### ISSUE TITLE
Function parameters parser bug

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#4988]
### Skript/Server Version

```markdown
[17:49:28 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:49:28 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[17:49:28 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[17:49:28 INFO]: [Skript] Server Version: git-Purpur-1171 (MC: 1.16.5)
[17:49:28 INFO]: [Skript] Skript Version: 2.6.3
[17:49:28 INFO]: [Skript] Installed Skript Addons:
[17:49:28 INFO]: [Skript]  - Repuska v2.8.9
[17:49:28 INFO]: [Skript] Installed dependencies:
[17:49:28 INFO]: [Skript]  - Vault v1.7.3-b131
[17:49:28 INFO]: [Skript]  - WorldGuard v7.0.5+3827266
```

### Bug Description

```
function ts(uuid: string, s: string) :: boolean:
	if {_uuid} is set:
		if  {_s} is set:
			return true
	return false

command /ts [<string>] [<string>]:
	trigger:
		set {_p} to player
		set {_x} to ts(uuid of {_p}, "1")
		send "%{_x}%"
```
ERRORS:
```
The function 'ts' requires at least 2 arguments, but only 1 is given.
Line: set {_x} to ts(uuid of {_p}, "1")
```

### Expected Behavior

function should be fine and output is true.

### Steps to Reproduce

```
function ts(uuid: string, s: string) :: boolean:
	if {_uuid} is set:
		if  {_s} is set:
			return true
	return false

command /ts [<string>] [<string>]:
	trigger:
		set {_p} to player
		set {_x} to ts(uuid of {_p}, "1")
		send "%{_x}%"
```
Here is my code of producing this bug.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Probably due to `worlds` type in ExprUUID it's reading both parameters as expression 
![image](https://user-images.githubusercontent.com/20037329/181905529-9145076a-6b28-46c6-bd12-a0997d1169b8.png)

**Comment by TheLimeGlass** [comment]
@TPGamesNL Is this related to https://github.com/SkriptLang/Skript/pull/4896

**Comment by TheLimeGlass** [comment]
Problem is that the SkriptParser#parseFunction sends an expression parse request to the SkriptParser, and there is no context sent to the parse expression telling SkriptParser that there should return two separate expressions when having `string, string` Skript will return a single expression that has two values.

Context needs to be provided when parsing the expression otherwise i'll keep returning a single Expression<String> rather than an ExpressionList of strings.

**Comment by TheLimeGlass** [comment]
Debugged, and the problem is the UUID expression accepts multiple types. So in this case Skript is thinking `ts(uuid of {_p}, "1")` is `ts(uuid of {_p} and "1")` for some reason, So it's thinking it's returning a single UUID and erroring.

**Comment by TUCAOEVER** [comment]
This issue was found on Skript 2.6.3+ As version below 2.6.1 works fine.
