### ISSUE TITLE
Getting arguments on "on command" 

### ISSUE THREAD

**Issue by LeckererSandwich** [SkriptLang/Skript#4989]
### Suggestion

being able to Get arguments on an "on command" 

### Why?

I really need that feature for one of my scripts if theres an addon that adds that please tell me

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by JustSkeppYT** [comment]
Use [<>]'s, example:

`command /kill [<player>]:
  trigger:
    kill arg 1`

**Comment by AyhamAl-Ali** [comment]
There is `arguments` expression in `on command` see [this in docs](https://docs.skriptlang.org/expressions.html#ExprCommand)
