### ISSUE TITLE
Can not get the name of used tool in on place event

### ISSUE THREAD

**Issue by Selcuk05** [SkriptLang/Skript#5007]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-794 (MC: 1.16.5)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies:
[Skript]  - GriefPrevention v16.17.1-2b69191
```

### Bug Description

```
on place of player skull or player wall skull:
	broadcast "%event-entity%"
	broadcast name of event-entity
	broadcast "%event-item%"
	broadcast name of event-item
	broadcast "%player's tool%"
	broadcast name of player's tool
	if name of tool of player is "abcd":
		cancel event
```

There is no way to get the name of the used item/tool in the block place event.

These are the broadcasts:
```
[10:23:17 INFO]: SigningFlea90
[10:23:17 INFO]: SigningFlea90
[10:23:17 INFO]: player head item
[10:23:17 INFO]: 0 air
```
Only the name of event-entity gets broadcasted, and it is my name.
The other names are not even broadcasted, and if I put them in a string they are broadcasted as `<none>`.
The item does have a custom name though, so this is interesting.

### Expected Behavior

The code should at least be able to get the name of the used tool or item.

### Steps to Reproduce

Use the code in the description in Skript 2.6.3 and Paper 1.16.5.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Name of unnamed items will return `<none>`, "unnamed" also means the item's default name
Can you send a screenshot of that skull's name

**Comment by Selcuk05** [comment]
![2022-08-04_10 43 53](https://user-images.githubusercontent.com/57503247/182792537-48200d69-5304-4e7e-8905-8eae4d23da4a.png)

**Comment by AyhamAl-Ali** [comment]
The player's tool is `0 air` which it shouldn't be, was that test you did on the code you sent? did you use a wait effect?

I couldn't reproduce (starting from 1:)
![image](https://user-images.githubusercontent.com/20037329/182819520-cb71746a-2562-4e66-828e-00f6c0dbf069.png)


```v

on place of player skull or player wall skull:
	broadcast "1: %event-entity%"
	broadcast "2: %name of event-entity%"
	broadcast "3: %event-item%"
	broadcast "4: %name of event-item%"
	broadcast "5: %player's tool%"
	broadcast "6: %name of player's tool%"
```

**Comment by Selcuk05** [comment]
I tested my code by placing the named head in the screenshot, I tested it again and no chance, the name is still `<none>`.
I didn't add any wait, but I tested it now with wait and it still broadcasts `<none>` unfortunately.

I tested with more than one of the same head in one slot, and that returns the tool and the name successfully. Maybe the event gets the empty slot after I place the block?

**Comment by AyhamAl-Ali** [comment]
Does it only do that with that skull or with all other items? can you try changing the name of a stone and place it

also try to have more that x1 of that item in the same slot like x5 items of stone and place one and let us know what happens

**Comment by Selcuk05** [comment]
Alright, it was apparently because I was removing the item from the user's inventory on right click, and the place event could not catch up to it so it would turn into this situation. I fixed it by removing the place event and doing the checks before the item was removed. Thanks for your help and sorry for taking your time.
