### ISSUE TITLE
plus symbol goes at end when line dividing

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#5008]
### Suggestion

Typically when you have to seperate a string into two or more lines, it's common practice to have the plus symbol at the end of each line.

This way you're signifying that it continues to the next line.

### Why?

This suggestion is to have this added to the code standards for Skript since we've been seperating into multiple lines more and more lately.

### Other

Making this suggestion so I don't forget 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Also it might be better to add to that the space ` `   should go on the top line (at the end) so that when reviewing we can quickly spot them
