### ISSUE TITLE
Condition dont work after restart

### ISSUE THREAD

**Issue by Frithy0** [SkriptLang/Skript#5021]
### Skript/Server Version

```markdown
Serveur : 1.16
Skript : 2.6.3
```

### Bug Description

My condition work before restarting server but don't after

### Expected Behavior

My code test:
![image](https://user-images.githubusercontent.com/56309938/183601591-59093bb3-7485-496a-ad33-49f16eee0fcb.png)

Before restart :
![image](https://user-images.githubusercontent.com/56309938/183601645-51144c37-dd63-4bcc-83cd-ccfd47047878.png)

After restart :
![image](https://user-images.githubusercontent.com/56309938/183601794-813b9ca5-f732-4fe0-b2aa-026354a9cb92.png)

### Steps to Reproduce

All the code :
[town.zip](https://github.com/SkriptLang/Skript/files/9288648/town.zip)

→ /town new [name]
→ /town map 
→ Work 
→ restart server
→ /town map 
→ Don't work 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
It's better to ask in [skUnity discord help channels](https://discord.gg/X8EadNW8) for help as this is an issue tracker.

However, your related code:
> set {_chunkTestLocation} to chunk at location({_xChunkLocation}+(16*(6-loop-value-3)),100,{_zChunkLocation}+(16*(6-loop-value-2)))

When you restart your server that chunk is probably not yet loaded therefore it can't get that chunk unless you load it first then use your code
