### ISSUE TITLE
Problem with Holographic Display (1.19)

### ISSUE THREAD

**Issue by Xgabi86** [SkriptLang/Skript#5036]
### Skript/Server Version

```markdown
Skript Version: 2.6.3
Installed Skript Addons:
skRayFall v1.9.28 (https://sk.rayfall.net/)
SkQuery v4.1.7
SkBee v2.0.0 (https://github.com/ShaneBeee/SkBee)
Installed dependencies:
Vault v1.7.3-b131
WorldGuard v7.0.8-beta-01+cbb2ba7
```

### Bug Description

spam console and dosn't work

### Expected Behavior

create hologram every seconds

### Steps to Reproduce

install Holographic Display (3.0.0-SNAPSHOP) 
create a hologram (create holo object "test" with id "test.test.holo" at location)

### Errors or Screenshots

> [09:02:20] [Server thread/ERROR]: #!#! [Skript] Severe Error:
> [09:02:20] [Server thread/ERROR]: #!#!
> [09:02:20] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
> [09:02:20] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [09:02:20] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
> [09:02:20] [Server thread/ERROR]: #!#! Here is full list of them:
> [09:02:20] [Server thread/ERROR]: #!#! skRayFall v1.9.28 (https://sk.rayfall.net/) SkBee v2.0.0 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.7
> [09:02:20] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
> [09:02:20] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
> [09:02:20] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
> [09:02:20] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
> [09:02:20] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
> [09:02:20] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
> [09:02:20] [Server thread/ERROR]: #!#!
> [09:02:20] [Server thread/ERROR]: #!#! Stack trace:
> [09:02:20] [Server thread/ERROR]: #!#! java.lang.NullPointerException: source cannot be null
> [09:02:20] [Server thread/ERROR]: #!#! at me.filoghost.holographicdisplays.plugin.lib.fcommons.Preconditions.notNull(Preconditions.java:24)
> [09:02:20] [Server thread/ERROR]: #!#! at me.filoghost.holographicdisplays.core.api.v2.V2HologramsAPIProvider.createHologram(V2HologramsAPIProvider.java:39)
> [09:02:20] [Server thread/ERROR]: #!#! at com.gmail.filoghost.holographicdisplays.api.HologramsAPI.createHologram(HologramsAPI.java:26)
> [09:02:20] [Server thread/ERROR]: #!#! at net.rayfall.eyesniper2.skrayfall.holograms.EffCreateStaticHoloObject.execute(EffCreateStaticHoloObject.java:59)
> [09:02:20] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:50)
> [09:02:20] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
> [09:02:20] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
> [09:02:20] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
> [09:02:20] [Server thread/ERROR]: #!#! at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:94)
> [09:02:20] [Server thread/ERROR]: #!#! at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:108)
> [09:02:20] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
> [09:02:20] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
> [09:02:20] [Server thread/ERROR]: #!#! at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245)
> [09:02:20] [Server thread/ERROR]: #!#! at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394)
> [09:02:20] [Server thread/ERROR]: #!#! at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197)
> [09:02:20] [Server thread/ERROR]: #!#! at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1010)
> [09:02:20] [Server thread/ERROR]: #!#! at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
> [09:02:20] [Server thread/ERROR]: #!#! at java.base/java.lang.Thread.run(Thread.java:833)
> [09:02:20] [Server thread/ERROR]: #!#!
> [09:02:20] [Server thread/ERROR]: #!#! Version Information:
> [09:02:20] [Server thread/ERROR]: #!#! Skript: 2.6.3 (latest)
> [09:02:20] [Server thread/ERROR]: #!#! Flavor: skriptlang-github
> [09:02:20] [Server thread/ERROR]: #!#! Date: 00:55:22.847925631
> [09:02:20] [Server thread/ERROR]: #!#! Bukkit: 1.19-R0.1-SNAPSHOT
> [09:02:20] [Server thread/ERROR]: #!#! Minecraft: 1.19
> [09:02:20] [Server thread/ERROR]: #!#! Java: 18.0.2 (OpenJDK 64-Bit Server VM 18.0.2+9)
> [09:02:20] [Server thread/ERROR]: #!#! OS: Linux amd64 5.4.0-107-generic
> [09:02:20] [Server thread/ERROR]: #!#!
> [09:02:20] [Server thread/ERROR]: #!#! Server platform: Spigot
> [09:02:20] [Server thread/ERROR]: #!#!
> [09:02:20] [Server thread/ERROR]: #!#! Current node: null
> [09:02:20] [Server thread/ERROR]: #!#! Current item: null
> [09:02:20] [Server thread/ERROR]: #!#! Current trigger: every seconds (every 1 second) (main.sk, line 1)
> [09:02:20] [Server thread/ERROR]: #!#!
> [09:02:20] [Server thread/ERROR]: #!#! Thread: Server thread
> [09:02:20] [Server thread/ERROR]: #!#!
> [09:02:20] [Server thread/ERROR]: #!#! Language: english
> [09:02:20] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
> [09:02:20] [Server thread/ERROR]: #!#!
> [09:02:20] [Server thread/ERROR]: #!#! End of Error.
> [09:02:20] [Server thread/ERROR]: #!#!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Problem is SkRayFall not Skript. We can't do anything about it. You can report the error at https://github.com/eyesniper2/skRayFall/issues
