### ISSUE TITLE
Function Max does not work with list variables

### ISSUE THREAD

**Issue by WilliamPlays0402** [SkriptLang/Skript#5037]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-131 (MC: 1.19.2)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons:
[Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[Skript]  - SkBee v2.0.0 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: None
```

### Bug Description

The function max() does not work when a list variable is put as an argument.

### Expected Behavior

Max should return the maximum of the list variable.

### Steps to Reproduce

1. Start a server with Skript.
2. Make a file called test.sk and put [this](https://gist.github.com/WilliamPlays0402/d703370afc0fb970badf5d3d0378dda8) inside.
3. Reload and /test
4. Expected outcome:
```
Scores:
1, _..._
Order:
5
Order:
5, 3
Order:
5, 3, 1
Order:
5, 3, 1, 1
_..._
Finale:
test4: 5, test3: 3, test2: 1, test1: 1
```
Actual outcome:
```
Scores:
1
1
3
5
Order:
Order:
Order:
Order:
Finale:
````
This shows that nothing was added to the {_order::*} variable (the max function).

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by bluelhf** [comment]
Perhaps it'd be a good idea to try a more minimal example, like:
```hs
on script load:
    set {_l::*} to 7, 1, 7, 5
    broadcast "%max({_l::*})%"
```
That being said, if it doesn't work for the script you showed I doubt it'll work here, either.

**Comment by sovdeeth** [comment]
```# from the supplied code above:
    set {scores::test1} to "1"
    set {scores::test2} to "1"
    set {scores::test3} to "3"
    set {scores::test4} to "5"
    set {_l::*} to {scores::*}
```

Well you're trying to get the max of a list of strings, william, and max() is specifically for numbers. So it doesn't know how to find the maximum string in a list. Just don't put "" around your numbers when storing them in a list.

**Comment by AyhamAl-Ali** [comment]
As said above, you're using the function incorrectly you should not surround numbers with quotation marks
```diff
- set {scores::test1} to "1"
+ set {scores::test1} to 1
```

**Comment by WilliamPlays0402** [comment]
Oh I'm an idiot.
Sorry guys! (maybe the max() function should return something (false or NaN) if only non-number inputs are put in the function?)
