### ISSUE TITLE
Command Bug

### ISSUE THREAD

**Issue by ergrtgrthgtyh** [SkriptLang/Skript#5046]
### Skript/Server Version

```markdown
Skript Version: 2.6.3
```

### Bug Description

**Command Bug**

when i reload my skript the command doesn't work and it sends Unknown Command, Type "/help" for help.

### Expected Behavior

its supposed to run the command

### Steps to Reproduce

i don't know

### Errors or Screenshots

No Errors

### Other

nop

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by ergrtgrthgtyh** [comment]
btw i can't add any skript plugins but i need them to do what i want

**Comment by TPGamesNL** [comment]
Can you send your full console log?

**Comment by ergrtgrthgtyh** [comment]
[latest.log](https://github.com/SkriptLang/Skript/files/9425687/latest.log)

**Comment by TPGamesNL** [comment]
This is an addon issue, specifically TuSKe. Make sure you use its latest version, and that that version supports your Skript version.

**Comment by ergrtgrthgtyh** [comment]
can you send me the link to download TuSKe for 1.12.2

**Comment by TPGamesNL** [comment]
No I don't have it, but this isn't the right place, if you need help like that I recommend the skUnity Discord, or Google.
