### ISSUE TITLE
Cursor slot

### ISSUE THREAD

**Issue by iPlexy** [SkriptLang/Skript#5050]
### Skript/Server Version

![image](https://user-images.githubusercontent.com/29547183/186919233-4b7cafdb-d47f-42a0-991e-53b679000686.png)

### Bug Description
```
on inventory click:
    send "%cursor slot of player%"
    wait 1 tick
    send "%cursor slot of player%"
```

both returns "0 air"
while 

```
on inventory click:
    send "%event.getCursor()%"
    wait 1 tick
    send "%event.getCursor()%"
```

does return dirt aka the right item

### Expected Behavior

send the right item

### Steps to Reproduce
```
on inventory click:
    send "%cursor slot of player%"
    wait 1 tick
    send "%cursor slot of player%"
```

click on dirt as cursor slot

```
on inventory click:
    send "%event.getCursor()%"
    wait 1 tick
    send "%event.getCursor()%"
```

click on dirt as cursor slot

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by UnderscoreTud** [comment]
Skript's `cursor slot` expression uses the getItemOnCursor method which doesn't work in creative due to how minecraft is coded, event.getCursor() on the other hand uses the cursor slot FROM the event which the expression doesn't
