### ISSUE TITLE
Server could not load skript

### ISSUE THREAD

**Issue by Zynph** [SkriptLang/Skript#5056]
### Skript/Server Version

```markdown
Latest Skript Version on Spigot 1.19.2
```

### Bug Description

Plugin is not loading on my server

### Expected Behavior

Plugin to load and show on /pl

### Steps to Reproduce

I have no idea 

### Errors or Screenshots

erver thread/ERROR Could not load 'plugins/Skript.jar' in folder 'plugins'
27.08 00:56:14 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
27.08 00:56:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
27.08 00:56:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
27.08 00:56:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
27.08 00:56:14 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:414) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
27.08 00:56:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:224) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
27.08 00:56:14 [Server] INFO at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
27.08 00:56:14 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
27.08 00:56:14 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
27.08 00:56:14 [Server] INFO Caused by: java.lang.ExceptionInInitializerError
27.08 00:56:14 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
27.08 00:56:14 [Server] INFO at java.lang.Class.forName(Class.java:466) ~[?:?]
27.08 00:56:14 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
27.08 00:56:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
27.08 00:56:14 [Server] INFO ... 7 more
27.08 00:56:14 [Server] INFO Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.dedicated.DedicatedServer.v()
27.08 00:56:14 [Server] INFO at ch.njol.skript.Skript.<clinit>(Skript.java:1096) ~[?:?]

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Can you send output of `/sk info`

**Comment by TPGamesNL** [comment]
You need to use Skript 2.6.3 if you want to use Minecraft 1.19, Skript 2.6.2 won't work.
