### ISSUE TITLE
MySQL Database not being read properly

### ISSUE THREAD

**Issue by Kiboky** [SkriptLang/Skript#5058]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-131 (MC: 1.19.2)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons: 
[Skript]  - Skungee v2.0.0-BETA-4
[Skript] Installed dependencies: 
[Skript]  - SQLibrary v7.1
```

### Bug Description

I wrote something to a mysql databse with the integraded database support from the config. But after i wanted to read the database from another server with "if {synced.server.iswhitelisted} is true:" the server where i use the code only reads the database once every restart (its for the whole bungeecord) but if i used that line from the server i saved it on it reads it fine. 

### Expected Behavior

I wanted that every time i use this line for example "if {synced.server.iswhitelisted} is true:" skript checks if it modified even though it already has it in chache or whatever is causing this bug. 

### Steps to Reproduce

[Files needed.zip](https://github.com/SkriptLang/Skript/files/9437959/Files.needed.zip)

! Please make sure to use 2 servers that are eigher connected though bungee or seperaded since it works if both skripts are on the same server. And of course a Database (I only used MySQL to test it)

Use the command /bugon on Server-1 and you should still see not whitelisted being spammed on Server-2 until a restart of Server-2 

### Errors or Screenshots

There aren't any..

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
SQL no longer works on newer Paper builds. Duplicate https://github.com/SkriptLang/Skript/issues/3948
