### ISSUE TITLE
Spelling Mistake (Lapis Lazuli = "lapiss")

### ISSUE THREAD

**Issue by iDerpyOfficial** [SkriptLang/Skript#5078]
### Skript/Server Version

```markdown
Skript version 2.6.3
Customize Minecraft's mechanics with simple scripts written in plain English sentences.
Website: https://skriptlang.github.io/Skript
Authors: Njol, Mirreski, SkriptLang Team and Contributors

Server Version: 1.19.2
```

### Bug Description

Lapis Lazuli's name is "lapiss" when you do something like "send "%player's held item%" when you're holding it or something like that

Edit: I meant "send player's held item"

### Expected Behavior

Should be called "lapis"

### Steps to Reproduce

Enable effect commands
Hold a lapis lazuli in your hand
Type "!send player's held item"

### Errors or Screenshots

![javaw_0RnFFLSiRV](https://user-images.githubusercontent.com/95272690/188084358-a6639f22-aabd-4215-9901-b703cc247b56.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
I can replicate, due to this line 
https://github.com/SkriptLang/skript-aliases/blob/e99be898254965b0207992f66a3289ab6744106e/misc.sk#L244

**Comment by bluelhf** [comment]
I assume this would display correctly if the player was holding one lapis lazuli item?
