### ISSUE TITLE
Add 'any potion effect' expression

### ISSUE THREAD

**Issue by J-ak-e** [SkriptLang/Skript#5082]
### Suggestion

add the 'any potion effect' expression that returns all the effects

### Why?

Just like there are expressions like 'any planks' 'any terracotta' and so on, this would be useful in some cases

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Already covered by this PR 
- #5077
