### ISSUE TITLE
offhand bug 

### ISSUE THREAD

**Issue by CatsOnTheMoon** [SkriptLang/Skript#5092]
### Skript/Server Version

```markdown
[Skript] Server Version: git-Paper-411 (MC: 1.17.1)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

So im coding a troll server on minehut, and im trying to get the shield in my offhand to work with an on right click: event

the code im trying is this:
on right click:
	item is shield
	cancel event
	remove item from player's inventory
	broadcast "&f(&2Dream&f):&cOops! &cYour shield broke!"
	
but the shield isn't interacting with the coded event when i right click it in my offhand, any idea how to fix this?

### Expected Behavior

the shield would disappear and this would be the code that ran 
on right click:
	item is shield
	cancel event
	remove item from player's inventory
	broadcast "&f(&2Dream&f):&cOops! &cYour shield broke!"

### Steps to Reproduce

try to make it work in the offhand so it removes it and displays the message, thanks!

### Errors or Screenshots

it should work in my offhand, shouldn't it?

### Other

nope

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by ImNotStable** [comment]
"player's offhand item" is how you get the offhand item of a player

**Comment by TheLimeGlass** [comment]
As ImNotStable stated you have to use player's offhand item
```
on right click:
	message "clicked"
	if player's offhand item is a shield:
		message "shield"
		cancel event
		remove player's offhand item from player's inventory
		broadcast "&f(&2Dream&f):&cOops! &cYour shield broke!"
```
Also a note: The event actually will get cancelled, but the shield continues to block, this is client side. Although when you remove the shield this doesn't happen. The code above I modified to be proper fixes the solution. Also another note, if the player isn't holding an item in their main hand but a shield in their offhand the `item` becomes the offhand, just how Mojang/Spigot works.
