### ISSUE TITLE
Get wrong offhand tool in tool change event.

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#5094]
### Skript/Server Version

```markdown
[18:33:38 INFO]: [Skript] Server Version: git-Paper-794 (MC: 1.16.5)
[18:33:38 INFO]: [Skript] Skript Version: 2.6.3
[18:33:38 INFO]: [Skript] Installed Skript Addons:
[18:33:38 INFO]: [Skript]  - skript-fishing v1.0 (https://github.com/Fusezion/skript-fishing)
[18:33:38 INFO]: [Skript]  - Repuska v2.8.9
[18:33:38 INFO]: [Skript] Installed dependencies:
[18:33:38 INFO]: [Skript]  - Vault v1.7.3-b131
[18:33:38 INFO]: [Skript]  - WorldGuard v7.0.5+3827266
```

### Bug Description

```
on tool change:
	send "%event.getPlayer().getInventory().getItemInOffHand()%" to console
	send "%offhand tool of event-player%" to console
```

the correct output should be same
but actually not same
"%offhand tool of event-player%" is always same as "%tool of event-player%" instead of actual item in player's offhand

### Expected Behavior

offhand tool of event-player should always return player's offhand tool

### Steps to Reproduce

```
on tool change:
	send "%event.getPlayer().getInventory().getItemInOffHand()%" to console
	send "%offhand tool of event-player%" to console
```

code to reproduce with skript-reflect installed.

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/43756134/189479655-701b6d6f-6085-4153-bd77-c3c146bc87c1.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Thank you for the report and pull request.

Reasoning: This is only exclusive to the `on tool change` event. The event-value was grabbing the time specific value of the tool first and returning regardless if the Skript user defined off hand item or main hand.

The solution is to just ignore the event-value time state return if the user defined `offhand item` as the parser mark from the ExprTool expression.
