### ISSUE TITLE
PropertyType.WILL for PropertyCondition

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5120]
### Suggestion

Add another `PropertyType.WILL` enum for `PropertyCondition` class

### Why?

Not implemented yet

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
I suppose this will only be used with time states? do you have some good examples to show this request off
Though not sure if this is something the rest of the dev team would agree on this so opinions are needed

**Comment by TheLimeGlass** [comment]
"Will" is already what defines past tense. Like currently you can do in a teleport event. event-world will be world "world".

You can set this with setTime method in the Expression class.

I'm against adding this because it already exists.

**Comment by Fusezion** [comment]
> "Will" is already what defines future tense. Like currently you can do in a teleport event. event-world will be world "world". Same with event-world was world "world"
> 
> You can set this with setTime method in the Expression class.
> 
> I'm against adding this because it already exists.

I wasn't I wasn't aware of `setTime`, I'll close this as it's already implemented
