### ISSUE TITLE
can't compare inventory to type

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#5130]
### Suggestion

Someone had an issue on SkUnity Discord where they couldn't compare event-inventory with an anvil inventory.

Either something is broken or we need a converter for Inventory to InventoryType.

Chest probably works because it's comparing the actual chest inventory syntax with an actual inventory.

### Why?

Fix

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by DelayedGaming** [comment]
My test with Skript 2.6.4 and Paper 1.19.3 says otherwise:
```v
on inventory click:
    send "click"
    if event-inventory = anvil inventory:
        send "anvil inv"
```
![image](https://user-images.githubusercontent.com/72163224/219870723-bc43a1b5-eded-4c6c-8302-4cb3a80f97d2.png)

**Comment by TheLimeGlass** [comment]
Cannot replicate
