### ISSUE TITLE
how to install this plugin

### ISSUE THREAD

**Issue by krazymann** [SkriptLang/Skript#5142]
### Skript/Server Version

```markdown
2.6.3
```

### Bug Description

idk how to install this plugin, help
this is what i download [https://imgur.com/a/evXVRRu]

### Expected Behavior

???

### Steps to Reproduce

???

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
when you go to the [releases tab](https://github.com/SkriptLang/Skript/releases) you'll find a `Skript.Jar` download
you'd click that
![image](https://user-images.githubusercontent.com/81952476/193745944-16a67768-3aa7-4001-95fd-4e55ddf0b257.png)

**Comment by AyhamAl-Ali** [comment]
This is Skript issue tracker, if you need help you can use [SkUnity discord help channels](https://discord.gg/cezXmzjc).
As said above, download the `Skript.jar` from releases tab to your server plugins folder, restart the server.
