### ISSUE TITLE
right clicking with skeleton spawn egg

### ISSUE THREAD

**Issue by Nesanco** [SkriptLang/Skript#5147]
### Skript/Server Version

```markdown
version is 2.6.3 theres like 40 lines of stuff i cant type it all out
```

### Bug Description

im trying to do stuff when a player spawns a skeleton using an egg but nothing is working,

1st example
```
on right click with skeleton spawn egg:
	broadcast name of player's tool
	if name of player's tool is "&c&lSkeleton Boss &r&7Boss Egg":
		if {skeleton.boss} is not set:
			console command "spawnmob1"
			send "&7Boss spawned!" to player
			cancel event
		else:
			send "&7There is already an active boss!" to player
			cancel event
```

2nd example
```
on spawn of skeleton:    
    if "%spawn reason%" is "spawn egg":
        if name of player's tool is "&c&lSkeleton &r&7Boss Egg":
            if {skeleton.boss} is not set:
                console command "spawnmob1"
                send "&7Boss spawned!" to player
                cancel event
            else:
                send "&7There is already an active boss!" to player
                cancel event
        else:
            broadcast name of player's tool
    else:
        broadcast spawn reason
```

the 1st one spawns a skeleton named whatever the player's tool is so "&c&lSkeleton &r&7Boss Egg" but i never tell it to do that... and the command and everything never get run, nothing is sent to me. the name and everything is correct, and the event is never cancelled

in the 2nd example it spaws a skeleton named whatever the player's tool is so "&c&lSkeleton &r&7Boss Egg" but again i never tell it to do that and nothing is broadcasted from all the else statements and nothing happens after all the if statements

but both events are called just nothing happens which doesnt make sense

### Expected Behavior

well its supose to stop the spawn of the skeleton and send me a message if all the if statements check out which they all do

### Steps to Reproduce

just copy my skript

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment]
The issue is caused by how color code `&r` works.
![image](https://user-images.githubusercontent.com/72163224/197008797-c499dae2-e880-4cab-bde1-fd02d5bd1df8.png)


The workaround is to check names in uncolored state instead:
```v
if uncolored "...." is "....":
```
