### ISSUE TITLE
Any direction expression

### ISSUE THREAD

**Issue by 24GDude** [SkriptLang/Skript#5163]
### Suggestion

Make an `any direction` expression, for example:

```
command /test:
    trigger:
        send any direction
        loop any direction:
            set block loop-value of player to stone
```

output of `any direction`:

`north, east, south, west, above, below` and so on

### Why?

instead of setting a list just do an `any direction` expression, so its easier

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
This can be achieved with this PR #5077 using `all directions`
