### ISSUE TITLE
Outdated Library Breaking Databases 

### ISSUE THREAD

**Issue by Giuca002** [SkriptLang/Skript#5174]
### Skript/Server Version

```markdown
1.18.2
2.6.3
```

### Bug Description

When trying to setup a database for MySQL in the Skript config it does not work because the Sql Library is outdated since 2014. It should have been using the bukkit sql api for this but it appears no one got around to it. https://dev.bukkit.org/projects/sqlibrary
Should be using: 
https://bukkit.fandom.com/wiki/Plugin_Databases

### Expected Behavior

It’s updated and the sql database loads the variables 

### Steps to Reproduce

Try making a sql database and put it in the config and install the library to see it does not work 

### Errors or Screenshots

None 

### Other

None

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Bukkit doesn't provide a SQL database anymore, it got abused by plugins. We're aware that SQLibrary doesn't work anymore, so this is a duplicate https://github.com/SkriptLang/Skript/issues/3948

Discussion here https://github.com/SkriptLang/Skript/discussions/5000

We plan on updating it eventually.

**Comment by Giuca002** [comment]
So what am i supposed to do?

**Comment by AyhamAl-Ali** [comment]
> So what am i supposed to do?

You can try this [skript-db addon](https://forums.skunity.com/resources/skript-db-updated.1261/)
