### ISSUE TITLE
Item amount incorrect cast stack trace error

### ISSUE THREAD

**Issue by kjg25425** [SkriptLang/Skript#5184]
### Skript/Server Version

```markdown
git-Paper-794(MC: 1.16.5)
2.5.3
```

### Bug Description

An error occurred in the part where there should not be any mistakes or errors in the script syntax.

### Expected Behavior

The GUI will open and the quest item rewards should be added to the description

### Steps to Reproduce

	if {MK.QuestReward.items::%{_Quest}%::*} is set:
		set {_lore::*} to {_lore::*} and  "" and "  &e&l&oITEM REWARD&7(아이템 보상) :"
		loop {MK.QuestReward.items::%{_Quest}%::*}:
			add 1 to {_in}
			if loop-value's name is set:
				set {_iname} to loop-value's name
			else:
				set {_iname} to loop-value's type
			set {_amount} to the item amount of loop-value
			set {_lore::*} to {_lore::*} and "  &7- &f%{_iname}% &f%{_amount}%개"
			{_in} is 3
			exit loop

### Errors or Screenshots

![1233](https://user-images.githubusercontent.com/116926687/198752456-40fda170-70de-473f-bacb-2cc72a8071eb.PNG)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
2.5.3 is not the latest Skript version that can run on 1.16

Can you provide us with the Skript code where you're setting the variable `{MK.QuestReward.items::%{_Quest}%::*}`

**Comment by UnderscoreTud** [comment]
Fixed in https://github.com/SkriptLang/Skript/pull/5513
