### ISSUE TITLE
can't send message to discord

### ISSUE THREAD

**Issue by jeff13401769** [SkriptLang/Skript#5192]
### Skript/Server Version

```markdown
Skellett v2.0.7
Disky v4.5.0
skDragon v0.16
MorkazSk v1.3
skUtilities v0.9.2
skript-reflect v2.3
skRayFall v1.9.28
SkQuery v4.1.7
SkBee v2.5.0
Ersatz v1.0
```

### Bug Description

The bot has been started, but the post cannot be used, the reply can be used

### Expected Behavior

Should send a message to Discord

### Steps to Reproduce

here is my code:

command /helpop [<text>]:
    description: 傳送求救訊息給在線管理員.
    usage: /helpop <訊息>
    trigger:
        if arg 1 is not set:
            message "&8[&6&lHelpOP&8] &e請輸入&7/Helpop <欲求助的內容>."
            stop
        message "&8[&6&lHelpOP&8] &e你的求救訊息已傳送給在線管理員並被傳送到Discord管理員頻道."
        if arg 1 is set:
            loop all players:
                loop-player has permission "helpop.receive":
                    message "&8[&6&lHelpOP&8] &e玩家 &6&l&n%player% &e需要幫助&8» &7&n%arg%" to loop-player
        post "**%player%** 需要協助 > **%arg-1%**" to text channel with id "873938295774650370"

### Errors or Screenshots

no error message

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by UnderscoreTud** [comment]
This is not the place for asking help, especially with addons. Check out the [skUnity discord server](https://discord.gg/skript) and ask for help there.

**Comment by AyhamAl-Ali** [comment]
As mentioned above, this is Skript's issue tracker, if you need some scripting help use the [skUnity discord server](https://discord.gg/nHytTVJA)
