### ISSUE TITLE
check player online bug

### ISSUE THREAD

**Issue by jeff13401769** [SkriptLang/Skript#5194]
### Skript/Server Version

```markdown
Skellett v2.0.7
DiSky v4.5.0
skDragon v0.16
MorkazSk v1.3
skUtilities v0.9.2
skript-reflect v2.3
skRayFall v1.9.28
SkQuery v4.1.7
SkBee v2.5.1
Ersatz v1.0
```

### Bug Description

I'm trying to make the command run to detect if the player is online, but it doesn't matter if the detection is online or not
Will not work

### Expected Behavior

Should stop when the player is not online

### Steps to Reproduce

here is my code
                    set {_p} to arg-2 parsed as offline players
                    if {_p} is online:
                        send "1" to player
                    if {_p} is offline:
                        send "2" to player
                    if {_p} isn't set:
                        send "3" to player
                    send "%type of {_p}%" to player
                    if {_p} is online:
                        if {guild.%{_p}%} isn't set:
                            if {guildInvite.%player%::%{_p}%} isn't set:
                                set {guildInvite.%player%::%{_p}%} to true
                                send "{@sysprefix} &a成功發送邀請給 &e%{_p}%." to player
                                send "{@sysprefix} &e%{_p}% &7有 &e{@invitetime} &7秒&e接受&7/&e拒絕" to player
                                send "&6[+]--------------------------[+]" to {_p}
                                send "" to {_p}
                                send "  &e%player% &7邀請你加入公會." to {_p}
                                send "" to {_p}
                                send formatted "  <tooltip:&a點擊接受><run command:/g accept %player%>&2[&a接受&2]<reset>  <tooltip:&c點擊拒絕><run command:/g deny %player%>&4[&c拒絕&4]<reset>" to {_p}
                                send "" to {_p}
                                send "&6[+]--------------------------[+]" to {_p}
                                wait {@invitetime} seconds
                                if {guildInvite.%player%::%{_p}%} is set:
                                    delete {guildInvite.%player%::%{_p}%}
                                    send "{@sysprefix} &c你發送給 &e%{_p}% 的公會邀請已過期!"
                                    stop
                            else:
                                send "{@sysprefix} &c你已邀請過該玩家! 若該玩家未收到邀請, 請等待邀請過期後再重新邀請"
                                stop
                        else:
                            send "{@sysprefix} &c該玩家當前已經擁有公會!"
                            stop
                    else:
                        send "{@sysprefix} &c該玩家不在線上或不存在"
                        stop

### Errors or Screenshots

no error code, 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Try parsing `as offline player` not offline players. Skript is potentially expecting a list.

**Comment by TheLimeGlass** [comment]
What's the arguments of the command? We need to see the command types.

**Comment by TheLimeGlass** [comment]
What version of Skript?

**Comment by sovdeeth** [comment]
Have you tested without disky? In the past disky has interfered with this condition, it's not a surprise if it did so again.

**Comment by jeff13401769** [comment]
> What's the arguments of the command? We need to see the command types.

text

**Comment by jeff13401769** [comment]
> Have you tested without disky? In the past disky has interfered with this condition, it's not a surprise if it did so again.

but i need use discord function qq

**Comment by jeff13401769** [comment]
> What version of Skript?

2.6.3

**Comment by AyhamAl-Ali** [comment]
This is a known disky/vixio issue. It's addon related.
