### ISSUE TITLE
Simple Bug About Minecraft Name Expression

### ISSUE THREAD

**Issue by Blueyescat** [SkriptLang/Skript#520]
`(raw|minecraft|vanilla) name of %item types%`

![image](https://cloud.githubusercontent.com/assets/19474570/25189856/bb0f0372-252a-11e7-9d4e-637779fef4a7.png)

**Comment by bensku** [comment]
Uhh, I need to rework this somehow. Spigot has sooo bad API for that, so will most likely be some kind of lookup table written by me.

**Comment by Blueyescat** [comment]
This is fixed with the rewrite of the aliases system.
