### ISSUE TITLE
%location% is[(n't| not) [with]in radius %number% (around|of) %location

### ISSUE THREAD

**Issue by J-ak-e** [SkriptLang/Skript#5201]
### Suggestion

Add `is within radius` condition.

### Why?

Would be a cool condition to have, would make code cleaner when checking that scenario.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by bluelhf** [comment]
Instead of `radius %number%`, could we use something like `%number% (block|metre|meter)[s]`?
