### ISSUE TITLE
ExprElement | New and Updated Syntax

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5208]
### Suggestion

- [x] Change the annotation name of ExprElement from `Element of` to `Elements`
- [x] Seperate syntax used for `ExprElement` into patterns to increase readability
- [x] Add new syntax for `first x elements of`
- [x] Add new syntax for `elements from x to y`
- [ ] **Debatable** removal of `random element from`

The expression `ExprRandom` | `random %*classinfo% out of %objects%` exist and no reason to make it a usable syntax pattern here. There will be another issue opened referring to this expression soon

### Why?

The `ExprElement` expression has recently received some love in #5183 but after some debating between developers and opinions being thrown with the cat we noticed there's a lot of changes that should be made to this expression/class and not just additions

> Syntax  Changes

Below is the current syntax for this expression. On a scale 1-10 how readable is this?
```AppleScript
([the] first|[the] last|[a] random|%number%(st|nd|rd|th)) element [out] of %objects%
```
Personally I vote a 2 we could split it up to something like what's listed below using proposed syntax as well \*copied from discord
```AppleScript
[the] (first|:last) [%-number%] element[s] [out] of %objects%
random element [out] of %objects%
%number%(st|nd|rd|th) element [out] of %objects%
elements [from] %number% (to|through) %number% of %objects%
```
\*order should be changed to for better understanding of formats
lets break down what the proposed syntax above is

**Pattern 1**
the `first/last element` along with ability to grab `first/last x elements`
`%-number%` is used to allow nullable and combine the original suggestion with the updated syntax

**Pattern 2**
Grab a random element out of a list
\*this really isn't a needed portion as ExprRandom exist more on that in another issue

**Pattern 3**
Grabs the Xth placement in a list
*this should be be used as a better alternative to `first element...` as it's just as conscience but only returns 1 value rather than multiple*

**Pattern 4**
Collects all elements between 2 numbers `x1` and `x2`. The biggest addition to this is the fact it's basically a pagination expression now built into skript no more making your own looping a list *a little too much*.

### Other

I mentioned this in the discord and I want to mention it here *(referring to Pattern 4)* that when this is coded we should check how high the iteration count might end up being when comparing x1 and x2.

I'll be using `page` as a means for easier to understand what I mean. While java is quick at reading large information skript isn't. This leads to a lot of halting at higher loop iterations. For example page 100 (10 elements per page so \*1000 -> 1010)
This isn't super high and is fairly faster but it would be made faster if we simply reversed the order we iterated through so instead if `Start -> .... -> 1000 -> 1010` we'd do `End -> .... -> 1010 -> 1000` and just reverse when we send back the data. depending on the list size we just cut down the time to parse and execute by a lot.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by J-ak-e** [comment]
There was a conversation about this issue in the skriptlang-development channel in the skunity discord, since i'm not sure if i'll ever come here to check i'll leave this here as an additional idea to what font will (at some point) add to this issue.

Addition to the future suggestion of `elements [from] %number% (to|through) %number% of %objects%`:
`if starting index + floor((ending index - starting index) / 2) > floor(size of list / 2):
  start getting the values from the end
else:
  start getting the values from the beginning`
I think this was suggested by Font, posting it because I believe this is the corect condition logic to correctly check if the end is closer to the range than the beginning.
This will make more sense when Font updates the issue, until then, bye.

**Comment by Fusezion** [comment]
I'll update this issue to the new changes and rename it as it isn't limited to only changes to first and last now

**Comment by Fusezion** [comment]
Alright updated the comment and issue title here issue regarding ExprRandom will be made in a hour or so

**Comment by Fusezion** [comment]
An additional note is I don't believe this should be labled a "Good First Issue" anymore. With the changes to this class by this issue being one that requires a full recode of the class basically I believe we're better off preferring people who are more fluent with skript's code base vs. a first time contributor. While I have no issue with a first time contributor taking on this issue I believe it's still something they should consciously decide on vs. something labled a good first issue and do it for that reason only
