### ISSUE TITLE
Skript continues to cancel death event even when all scripts are deleted.

### ISSUE THREAD

**Issue by kaden-tech** [SkriptLang/Skript#5230]
### Skript/Server Version

```markdown
[17:25:35 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:25:35 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[17:25:35 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[17:25:35 INFO]: [Skript] Server Version: git-Paper-290 (MC: 1.19.2)
[17:25:35 INFO]: [Skript] Skript Version: 2.6.4
[17:25:35 INFO]: [Skript] Installed Skript Addons:
[17:25:35 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[17:25:35 INFO]: [Skript]  - SkQuery v4.1.7
[17:25:35 INFO]: [Skript]  - SkBee v2.5.2 (https://github.com/ShaneBeee/SkBee)
[17:25:35 INFO]: [Skript] Installed dependencies:
[17:25:35 INFO]: [Skript]  - Vault v1.7.3-b131
[17:25:35 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

I was messing around with death events and decided to cancel it and try to teleport the player (after waiting a tick (I heard it was a good idea)) and after some testing, I decided against it. I removed the `cancel event` part of the script. I reloaded the script and /kill me. It was canceled again. I was confused. I checked all of the scripts and none had **cancel event** or **command /kill**. So I knew it couldn't be me. I restarted the server and tried again. Still... I though, 

> hmmmmmmmmm maybe this is another plugin's fault

So, I removed skript.   The problem stopped... It was no longer canceling. So that means that the problem is somewhere in script.
I added skript back and deleted the actual scripts. I restarted, and tried to /kill again. It was canceled. I had no scripts and it was still happening??? Well. Yes...

This is a bug and must be treated with highest priority. If players can't die, then that is game breaking... PLEASE HURRY!

### Expected Behavior

Allow the player to die if there is no reason to cancel the event.

### Steps to Reproduce

I said most in the bug description.

cancel death event can remove it... I can't really try to reproduce it as my server is currently broken due to this.

### Errors or Screenshots

No errors. Can't provide screenshots.

When /killing, I still get the _Killed NopeProsOnly_ feedback from the command

### Other

https://discord.com/channels/135877399391764480/1047230699083661422/1047271504104145037

This is the **Ghost Skript Glitch**

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by bluelhf** [comment]
I doubt anyone else will be able to reproduce this... You have a lot of plugins and unrelated scripts, would it be possible for you to make a minimal example that reproduces the issue, without any other plugins or scripts?

**Comment by kaden-tech** [comment]
Perhaps. But I share the same doubts as you. But I do know my other plugins aren't effecting skript. I have already done tests to determine which plugin is at fault. Skript.

**Comment by Pikachu920** [comment]
Can't reproduce on Paper 1.19.2 using Skript 2.6.4. I loaded this script:
```
on death:
  cancel the event
```
and `/kill` was cancelled as expected. I then replaced the script with this:
```
on death:
  broadcast "hi"
```
Upon reloading the script and trying `/kill` again, I was killed and the broadcast was sent.
