### ISSUE TITLE
The phrase all enchantments

### ISSUE THREAD

**Issue by NopeProsOnly** [SkriptLang/Skript#5235]
### Suggestion

`all players` exist
`all worlds` exist 
Why can't `all enchantments`

### Why?

Would make it easier so that we don't have to list every single one...

There are alot of enchantments 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
This will be added by the pull request #5077 as this will add support to get all values under a type

**Comment by kaden-tech** [comment]
Oh great! Is there a snapshot or something I can get of this pull request?

If not, do you know when it is planned to come out?

**Comment by NopeProsOnly** [comment]
> There's a high chance majority of your code will be busted, making you need to revert _which could cause even more issues_

Ah. Then I'm better off waiting...
