### ISSUE TITLE
Request: Get amount of crafted items from "on craft" event

### ISSUE THREAD

**Issue by akaBayest** [SkriptLang/Skript#5247]
### Skript/Server Version

```markdown
Server Version: git-Paper-322 (MC: 1.19.3)
Skript Version: 2.6.4
```

### Bug Description

I've searched in all docs trying to solve this but I couldn't,
so basically when a player shift clicks while crafting to finish faster the amount of crafted items is always one.
the game doesn't understand that there is a difference between slowly clicking and shift clicking.

### Expected Behavior

If you shift-click while crafting it should display the total amount of the crafted items not just one.

### Steps to Reproduce

I've used event-item, amount of event-item, event-itemtype, there is no way to get the amount of crafted items.
There were other reports about this bug but it was never solved/added an expression for it.

### Errors or Screenshots

![2022-12-16_12 01 02](https://user-images.githubusercontent.com/60987048/208074549-1534de12-46cf-4006-b432-ef77a314e876.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
`item amount of event-item`
