### ISSUE TITLE
ViaVersion causing double events to be fired

### ISSUE THREAD

**Issue by AgoMC** [SkriptLang/Skript#5250]
### Skript/Server Version

```markdown
[Skript] Server Version: git-Purpur-1832 (MC: 1.19.2)
[Skript] Skript Version: 2.6.4
[Skript] Installed Skript Addons: 
[Skript]  - BungeeSK v2.0.0 (https://github.com/ZorgBtw/BungeeSK)
[Skript]  - SkBee v2.5.4 (https://github.com/ShaneBeee/SkBee)
[Skript]  - Ersatz v1.0
[Skript] Installed dependencies: None
```

### Bug Description

So I have a network Hub, which has a Server Selector & Profile Viewer. I made it so the Profile Viewer doesn't work, and it will just send you a message saying it's disabled. That works fine, but if I look at someone while doing that, it sends the same message to the selected (looked at) player. I've tried to change the message code, from just `message "text"' to 'message "text" to player', but it still doesn't work. There's no errors coming up in my code...

```
on right click with player head:
 if name of tool is "&aProfile &7&o(Right-Click)":
  message "&cSorry, this item has been disabled"
```

*There's also correct indentation*

I also tried this on one of my friends servers, and it did the same thing.

### Expected Behavior

It should just message the player who actually used the item, not who they're looking at.

### Steps to Reproduce

Add in Skript, give yourself an item, and put in what I have above, just change the name. It should do what I've been talking about.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
use event-player

It's conflicting with clicked player when it's present somehow. I have a pull request fixing event value priority.

**Comment by Agomc** [comment]
Ok thank you!

**Comment by Agomc** [comment]
The only thing is when I do that, it duplicates the message for some reason, but I don't have anything sending it.

**Comment by TheLimeGlass** [comment]
> The only thing is when I do that, it duplicates the message for some reason, but I don't have anything sending it.

Can you send a list of your plugins?

It might be a Skript bug as it's calling two events probably.

**Comment by Agomc** [comment]
![Screenshot 2022-12-17 at 1 21 44 PM](https://user-images.githubusercontent.com/110626852/208255965-206735cd-e06f-4493-9316-b8152b2986c7.png)

This is my backend plugins, cause I'm on a Bungeecord server

**Comment by TheLimeGlass** [comment]
It's caused by ViaVersion. This is a known issue, but it only effects a small amount of users. It calls the event twice or rather previous client version to the server version do or is needed to support backwards client versions.

**Comment by TheLimeGlass** [comment]
I think we can provide a fix if ViaVersion is present.

**Comment by Agomc** [comment]
Alright, would this be a quick fix and just add in a snapshot, or would it be for the next release of Skript?

**Comment by Moderocky** [comment]
> Alright, would this be a quick fix and just add in a snapshot, or would it be for the next release of Skript?

It's not a priority so it might be in a future release.

**Comment by AgoGG** [comment]
Ok sounds good, thank you guys for helping me out 👍
