### ISSUE TITLE
Additional types of variables (restrictions, additional functionality, ...)

### ISSUE THREAD

**Issue by Mwexim** [SkriptLang/Skript#5256]
### Suggestion

While working on a new script, I really noticed the lack of options for variables. I wanted to use variables in different kinds of ways but was always limited by the two currently existing options: global and local variables.

One thing I love about Skript's variable system is that it automatically stores variables for you, so developers do not need to handle cumbersome configuration files and data files. That said, I am suggesting the addition of the following functionalities to the variable system (while repeating the currently existing options as well for comparison):
- global variables (e.g. `{this::is::an::example}`) which will be saved in a file;
- local variables (e.g. `{_this::is::an::example}`) which will be discarded when exiting the current trigger/structure; and
- 'ephemeral' variables (e.g. `{$this::is::an::example}`) which will be discarded once the server restarts.

While I am advocating for the above to be added to Skript, I might just add some other suggestions as well:
- set variables (e.g. `{a::list::*} set`) which will act like Java Sets.

When adding, removing, or setting these variables, all duplicate values will be removed so only unique entries remain.
```skript
set {my::set::*} set to ("Hi", "Hello" and "Hi")
broadcast {my::set::*} # "Hi" and "Hello"
```

I admit that this would probably be such a minor enhancement that it's not worth adding.

### Why?

Variables have been Skript's major selling point for me. Anyone learning Java will admit that configuration files and data files are a hassle to handle and that Skript's variable system is way easier to use. That said, it can still improve and I see no reason not to add these changes. 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
Ephemeral variables already exist. See the bottom of your config file for directions on how to enable them.

**Comment by Mwexim** [comment]
You’re right! I will close this issue.
