### ISSUE TITLE
list variable cant recgonize uuid!?

### ISSUE THREAD

**Issue by shadow123king** [SkriptLang/Skript#5327]
### Skript/Server Version

```markdown
skript version: 2.6.3
server version: 1.17.1
skrayfall installed
```

### Bug Description

for some reason only 1 of these works?!
_______________________
1- works!
_______________________
command /add:
    trigger:
        add player's uuid to {_test::}
        if {_test::} contains player's uuid:
            broadcast "HI"
______________________
2- does not work!
______________________
on damage:
	if attacker is player:
		add attacker's uuid to {attacked.%victim%::*}
		
on death:
	if {attacked.%victim%::*} contains attacker's uuid:
		send "you have killed something special" to attacker

### Expected Behavior

when a player damages a mob, the mob would store that players name in its own nest list variable. And when that mob dies, it detects if the attacker if in the mobs attacked list variable. But it doesnt detect it

### Steps to Reproduce

MY FULL SKRIPT:

on damage:
	if attacker is player:
		add attacker's uuid to {attacked.%victim%::*}
		send "%{attacked.%victim%::*}%" to attacker
		damage victim by {damage.%attacker%}
	if name of attacker's held item is "&c&ltradeoff sword":
		damage attacker by 2 hearts
		
on death:
	send "&c%{attacked.%victim%::*}%" to all players
	if {attacked.%victim%::*} contains attacker's uuid:
		kill attacker
		
command /add:
	trigger:
		add player's uuid to {_test::*}
		if {_test::*} contains player's uuid:
			broadcast "HI"

### Errors or Screenshots

there are no errors

### Other

this is for a rpg game im making, if that helps :D

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Cannot reproduce. Here is my test script. Modified to allow the zombie to kill me. Very similar.
```
on damage:
	victim is a player
	attacker is zombie
	add attacker's uuid to {attacked.%victim%::*}

on death:
	if {attacked.%victim%::*} contains attacker's uuid:
		send "you have died to something special" to victim
```
What exactly isn't working?

Are you running the server in offline mode?
Are you running a bungeecord?

If the last two questions are true, did you have the option `bungeecord` set to true in your spigot.yml? and do you have online mode true in bungeecord's configurations?

**Comment by shadow123king** [comment]
nvm, i actually just deleted the code, then remade it after and it magically worked smh

**Comment by shadow123king** [comment]
on damage:
	if victim is not player:
		add attacker to {attacked.%victim%::*}
		damage victim by {damage.%attacker%}
		
on death:
	clear the drops
	if victim is not player:
		loop all players:
			if {attacked.%victim%::*} contains loop-player:
				set {_random} to random integer between 1 and 3
				add {_random} to {level.points.%loop-player%}
				drop 1 brown dye named "&c&ldead soul" at victim's location
				stop
