### ISSUE TITLE
Expression for skulls

### ISSUE THREAD

**Issue by amatzen** [SkriptLang/Skript#534]
Hi. I have a feature request.

Please add a player skull expression like `on rightclick on skull of "MATZEN"`

If it exists, please tell me how :)

Thanks!
- Alexander

**Comment by Wealthyturtle** [comment]
Skull expression.

**Comment by FranKusmiruk** [comment]
The issue doesn't need to be tested, it's just the fact that you can't use non-literals in event-placeholders.

**Comment by Wealthyturtle** [comment]
My bad lol
