### ISSUE TITLE
Math is done in the wrong order

### ISSUE THREAD

**Issue by skripttpbug2** [SkriptLang/Skript#535]
https://i.imgur.com/eAwNDJb.png

The first is actually doing "5-(2-3)" instead of what is should be doing ("(5-2)-3")

you talk about this in #121

**Comment by Syst3ms** [comment]
Yeah, I don't see a good way to make it atm. For now you can just use () to add priorith

**Comment by bluelhf** [comment]
Bumping this since I just came across it, there's still nothing on this? I think it'd be better to parse arithmetic using a [third-party math parser](https://mathparser.org/) instead of reinventing the wheel
