### ISSUE TITLE
Json in on chat event does not work

### ISSUE THREAD

**Issue by weberlepecheur** [SkriptLang/Skript#536]
`on chat:
replace "(vote)" with "<link:http://my-website.com>link to page just here<reset>" in the message`

Json doesn't work with chat event. I do not know if it is a bug or not but I prefer to post it anyway.

Skript dev26f
Spigot 1.11.2

**Comment by bensku** [comment]
I will see if it is possible to implement this.

**Comment by bensku** [comment]
Confirmed to be impossible with Spigot API currently. But maybe some day...

**Comment by FranKusmiruk** [comment]
It's possible now but we have other issue tracking this (#3112).
