### ISSUE TITLE
Add the possibility to glow the signs

### ISSUE THREAD

**Issue by l-Aeden-l** [SkriptLang/Skript#5361]
### Suggestion

I'd like to be able to glow colored sign through a dedicated syntaxe.

### Why?

We can set lines of text, with color, but there is nothing to glow them.
I'm using Skript as my only plugin. Even if SkBee gives us the ability to easily use NBT tags to use the glowing feature on signs, I'd prefer to have a dedicated syntaxe, directly included inside the default Skript plugin.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
For a quick JavaDocs link https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Sign.html

**Comment by TheLimeGlass** [comment]
Khoryl supports this currently <https://github.com/TheLimeGlass/Khoryl/blob/master/src/main/java/me/limeglass/khoryl/elements/block/sign/SetGlowingText.java> 

<https://forums.skunity.com/resources/khoryl.871/>

Skript currently can't properly support dedicated entities (none literals) and dedicated blocks properly at runtime. Future improvements will fix this like type hints. Skript typically only adds important blocks like signs lines and the newly added respawn anchor support. This is on the fence but it is a sign.

**Comment by l-Aeden-l** [comment]
I understood absolutely nothing about what you tried to explain TheLimeGlass.

**Comment by Fusezion** [comment]
it's fine you don't really need to for it.

THDR; 
Skript can't easily tell what block it is you're attempting to change so if you tried `set line 3 of event-block` and `event-block` is stone skript can't go oh this isn't valid we have to do a bunch of unconventional checks along with ensure aliases are all correct too

Sign lines and a PR of mine have to do this which is annoying

**Comment by Fusezion** [comment]
No I could probably see about starting a PR for it but if I do I'd prefer to add editable state to it as well along with some conditions

**Comment by l-Aeden-l** [comment]
What does "PR" means?
