### ISSUE TITLE
Empty Section Warning Thrown on Non-Existent Conditions

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#5387]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-325 (MC: 1.19.3)
[Skript] Skript Version: 2.6.4
[Skript] Installed Skript Addons:
[Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[Skript]  - SkBee v2.6.3 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: None
```

### Bug Description

If a condition is a section, and the condition is non-existent, both `empty configuration section` and `Can't understand condition` messages are thrown together, instead of the latter alone.

### Expected Behavior

Should not throw `empty configuration section` if the condition is non-existent.

### Steps to Reproduce

Type a non-existent condition as a section, like so:
`if fake condition:`

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/72163224/213883744-7f339a4f-310b-4b0d-a603-8cb1d72f4c72.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
I would argue that I like the current implementation. You can understand that the condition is wrong and that it's empty in one error, rather than fixing the empty section and then finding out it's also incorrect condition.

**Comment by DelayedGaming** [comment]
> I would argue that I like the current implementation. You can understand that the condition is wrong and that it's empty in one error, rather than fixing the empty section and then finding out it's also an incorrect condition after another reload.

On the second thought, I actually find this implementation quite useful! At first I thought it may be a bug so I pointed it out.

**Comment by DelayedGaming** [comment]
Closing as this is intended.
