### ISSUE TITLE
Can't understand this event: on tab complete of /abcd

### ISSUE THREAD

**Issue by mloskot** [SkriptLang/Skript#5394]
### Skript/Server Version

```markdown
2.6.4
```

### Bug Description

My nine year old son is learning how to write plugins for his MC server using Skript. He is following one of tutorials on YouTube
e.g. https://www.youtube.com/watch?v=vKRCYu2Mkl4 in Polish language, but the scripts are displayed there. The video is one year old, but I tried to search the Skript release notes and other resources, and I couldn't find any information about breaking tab completion API before 2.6.4

In the video, author presents how to add tab completion to user's script, for example:

![image](https://user-images.githubusercontent.com/80741/214530649-661f2e80-f7e2-423f-849e-24340a25068f.png)

Unfortunately, none of those techniques from the video work for us.

I also found on the web that some developers use `on tab completer for` and others use `on tab complete of`.

So we tried both variants:

- `on tab complete of "/abcd"`
- `on tab completer for "/abcd"`

but without any luck as both throw `Can't understand this event:`

### Expected Behavior

No loading error and tab completion for `/abcd` command working fine.

### Steps to Reproduce

Try Minecraft load one of these scripts:

### `on tab complete of "/abcd"`

```skript
command /abcd [<text>]:
    trigger:
        if arg 1 is "yes":
            send "YES !"
        else if arg 1 is "no":
            send "NO !"
        else:
            send "UNSET !"

on tab complete of "/abcd":
    if argument at 2 is not set:
        add "yes" to completions
        add "no" to completions
        add "back" to completions
```

### `on tab completer for "/abcd"`

```skript
command /abcd [<text>]:
    trigger:
        if arg 1 is "yes":
            send "YES !"
        else if arg 1 is "no":
            send "NO !"
        else:
            send "UNSET !"

on tab completer for "/abcd":
    if argument at 2 is not set:
        add "yes" to completions
        add "no" to completions
        add "back" to completions
```

### Trying `on tab complete of "/abcd"`

![abcd-2](https://user-images.githubusercontent.com/80741/214531183-4eb70817-a546-4174-bb5c-574587387bd0.png)

### Trying `on tab completer for "/abcd"`

![abcd-1](https://user-images.githubusercontent.com/80741/214531102-21bc3040-5841-4416-b1a3-d88751ec0a9f.png)

### Other

I'd really appreciate any help as I'm running out of ideas what is the problem and how to solve it, and make my son happy :-)

And, ssorry for not running `/skript info` above but I currently have no access to son's computer with Skript installed.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Hello mloskot,

It's very nice to hear that your son is learning Skript and hope they learn more and more about it!

As for the issue, this is hapening because Skript doesn't have that event, that effect is from an Addon [SkBee](https://github.com/ShaneBeee/SkBee) you have to download that addon and then that event should work.

Thank you for reporting that to our issue tracker however, this is made for Skript issues, if you need any help with Skript you can use the discord [help channels](https://discord.gg/skript) of skUnity discord server

And say Hi to your son from the SkriptLang Team 🖐

**Comment by mloskot** [comment]
@AyhamAl-Ali Thank you very much! I will try your suggestions.

> Thank you for reporting that to our issue tracker however, this is made for Skript issues, if you need any help with Skript you can use the discord [help channels](https://discord.gg/skript) of skUnity discord server

Yeah, after the fact I realised I should have opened the Discussion thread instead (I couldn't use Discord at that time).

**Comment by HugoYT123** [comment]
Thank You @AyhamAl-Ali
