### ISSUE TITLE
ExprBlocks | blocks within chunk

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5402]
### Skript/Server Version

```markdown
[21:06:26 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:06:26 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[21:06:26 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[21:06:26 INFO]: [Skript] Server Version: git-Paper-215 (MC: 1.19.2)
[21:06:26 INFO]: [Skript] Skript Version: 2.6.4
[21:06:26 INFO]: [Skript] Installed Skript Addons: 
[21:06:26 INFO]: [Skript]  - Skacket v1.0.13
[21:06:26 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[21:06:26 INFO]: [Skript]  - skript-yaml v1.4.1
[21:06:26 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[21:06:26 INFO]: [Skript]  - SkBee v2.7.2 (https://github.com/ShaneBeee/SkBee)
[21:06:26 INFO]: [Skript]  - SkJade v1.4.2 (https://www.github.com/Ankoki-Dev/SkJade)
[21:06:26 INFO]: [Skript]  - Skript-Advancements v1.5.0
[21:06:26 INFO]: [Skript] Installed dependencies: 
[21:06:26 INFO]: [Skript]  - Vault v1.7.3-b131
[21:06:26 INFO]: [Skript]  - WorldGuard v7.0.6+1cff55f
```

### Bug Description

When you attempt to get the blocks within a chunk and said chunk is saved to a variable it doesn't return any block information and defaults to `<none>`

### Expected Behavior

It would return the same output as a normal usage without the use of a variable

### Steps to Reproduce

```
command example:
    trigger:
        send "%blocks within chunk at player where [type of input is dirt]%"
        set {_chunk} to chunk at player
        send "%blocks within {_chunk} where [type of input is dirt]%"
```

### Image 1 - no variable
![image](https://user-images.githubusercontent.com/81952476/214950674-9c5f8c47-1e48-4fa5-ba3f-2e4a19ae12d6.png)

### Image 2 - variable used
![image](https://user-images.githubusercontent.com/81952476/214950727-7e5e5145-20b4-4505-932b-88bcdfad9cc5.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment]
Have you tried `send "%(blocks within chunk at player) where [type of input is dirt]%"`?

**Comment by Fusezion** [comment]
> Have you tried `send "%(blocks within chunk at player) where [type of input is dirt]%"`?

Not the issue only used target block to decrease block sent amount

**Comment by TheLimeGlass** [comment]
Cannot reproduce on 2.6.4 and 2.7.0-dev using the code you provided under steps to reproduce.
```vb
test "testing":
	set {_chunk} to chunk at spawn of world "world"
	assert {_chunk} is set with "chunk variable was not set"
	set {_blocks::*} to blocks within {_chunk}
	assert {_blocks::*} is set with "blocks list variable was not set"
	set {_blocks::*} to blocks within {_chunk} where [type of input is dirt]
	assert {_blocks::*} is set with "blocks list2 variable was not set"
	set {_blocks::*} to blocks within {_chunk} where [block input is dirt]
	assert {_blocks::*} is set with "blocks list3 variable was not set"
	spawn a pig at spawn of world "world":
		set {_chunk} to chunk at event-entity
		set {_blocks::*} to blocks within {_chunk} where [type of input is dirt]
		assert {_blocks::*} is set with "Entity get chunk blocks variable was not set"
		set {_blocks::*} to blocks within {_chunk} where [input is block below event-entity]
		assert {_blocks::*} is set with "Entity2 get chunk blocks variable was not set"
		clear event-entity
```
Are you sure the provided blocks are actually dirt and not grass?

Also note that I did fix some dirt related blocks not being under `any dirt` at https://github.com/SkriptLang/skript-aliases/pull/81 for `rooted dirt, (grass|dirt) path [block]¦s, coarse dirt [block¦s], coarse dirt and podzol`

**Comment by Fusezion** [comment]
> Are you sure the provided blocks are actually dirt and not grass? Grass is not dirt.

the type of the block never mattered as that worked as intended, it's the fact that doing something like `blocks within {_chunk}` is returning `null/none` despite the fact chunk is a set value. 

but after another test it seems to be a conflict with an addon will be taking the time to figure it out myself sorry for any issues/delays.
I didn't think I had any addons with this syntax

**Comment by Fusezion** [comment]
so glad I kept this open, I'm actually unsure what this is caused by @TheLimeGlass, so I added the plugins to another server of mine 1 at a time and it kept it's save system, what mc version was that being tested on? this new test was 1.17.1 still attempt 1.19.2 shortly the test one uses 1.19.3 no?

**Comment by Fusezion** [comment]
> so glad I kept this open, I'm actually unsure what this is caused by @TheLimeGlass, so I added the plugins to another server of mine 1 at a time and it kept it's save system, what mc version was that being tested on? this new test was 1.17.1 still attempt 1.19.2 shortly the test one uses 1.19.3 no?

yeah even updating doesn't repeat, gonna close this shortly I'm unsure what happened but guess my server is a bit buggy

**Comment by Fusezion** [comment]
Addon issue, not skript related
