### ISSUE TITLE
Skript console error 

### ISSUE THREAD

**Issue by Matti2311** [SkriptLang/Skript#5417]
### Skript/Server Version

```markdown
Skript 2.6.4
Paperspigot 1.19
```

### Bug Description

I’m getting a spam in my console with this error, and after a minute the server crashes.

### Expected Behavior

This is not supposed to happen.

### Steps to Reproduce

I didn’t get this error when all my scripts where disabled.

### Errors or Screenshots

https://paste.gg/p/anonymous/ad14dab6bf204eddb5f70799f710aa16

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Can you provide the full error logs. Usually this error occurs when you have a long line of skript code which causes the parser to fail.
See #4977

**Comment by Matti2311** [comment]
Of course.
Here: https://bpa.st/AQT3M

**Comment by AyhamAl-Ali** [comment]
Full console log would fullfil the equation.

As for the script, it has some long lines with expressions such as lines setting metadata and gui with multiple lines lore, these could possibly cause issues but to be sure it's from this script try to disable it and restart the server or try what you've tried earlier to replciate this error

then let us know if that error still occur

**Comment by AyhamAl-Ali** [comment]
Closing this issue within 2 days due to inactivity.
