### ISSUE TITLE
Java/javascript syntaxe 

### ISSUE THREAD

**Issue by tgbhy** [SkriptLang/Skript#5421]
### Suggestion

Hi,
Here a suggestion:
Add basic javascript syntaxe (like `let {_var} = ""` and `let {_var} to ""`) and java syntaxe too.

### Why?

Because Skript is a simplified langage of Java, and javascript has good syntaxes.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
I think `set` is good enough, `let` doesn't seem very user friendly for new comers

**Comment by TPGamesNL** [comment]
`let x to y` isn't proper English (neither is `let x = y`)

**Comment by tgbhy** [comment]
I know but it's for exemple, and yeah, for comers is not very familiars but it can be usefull to start to learn java or javascript :)

**Comment by AyhamAl-Ali** [comment]
It's more about learning the logic than the syntax of other programming languages
