### ISSUE TITLE
Server crashes and will not restart when Skript is installed

### ISSUE THREAD

**Issue by panterathehacker** [SkriptLang/Skript#5428]
### Skript/Server Version

```markdown
MC 1.19.3
Skript 2.6.4
```

### Bug Description

Sever have had an issue with Skript before -- have had it installed for months, and have not changed anything since 2.6.4 was released. Then, today, the server had a paper crash and when I when I went to restart, it gets stuck when trying to enable Skript, preventing the server from launching. No matter how many times I kill it and restart it, it always gets stuck at [this same spot, enabling Skript](https://pastebin.com/P0XDJQ7D). When I remove Skript from the server files, the server starts regularly, with no problem.

### Expected Behavior

Server enables Skript with no issues, and can start.

### Steps to Reproduce

We're using the most recent versions.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
More info is needed.
- Are you removing the jar file or Skript  folder?
- Try to remove all your scripts and see if it starts
- Try to remove variables.csv
- Try to backup & delete Skript folder
- Send paper crash report
- Send output of /version

**Comment by panterathehacker** [comment]
> More info is needed.
> 
> * Are you removing the jar file or Skript  folder?
> * Try to remove all your scripts and see if it starts
> * Try to remove variables.csv
> * Try to backup & delete Skript folder
> * Send paper crash report
> * Send output of /version

- No, it was running fine yesterday, we haven't touched it, and today it won't enable.
- Removed all Skripts and it still won't start.  
- Where is variables.csv ? Don't see it in any of our files.
- Backing up and deleting Skript folder did not work -- still gets hung when attempting to enable. Reinstalled the plugin from scratch and still gets stuck enabling.
- Server does not crash -- just gets hung when trying to start. I have to kill it. Only paper crashed initially, and Skript hasn't worked since then; I don't have the report.
- Can't get to /version but it's the latest version, I've reinstalled several times using the most recent version.

**Comment by panterathehacker** [comment]
Server hosting company was able to fix by reinstalling paper version.

**Comment by panterathehacker** [comment]
Uh oh my bad -- the issue persists. They also removed Skript when updating paper, which is why the server was able to start without a problem.

So still, with Skript = server hangs on enabling Skript and does not start. Without Skript, server starts and performs fine. I have tried removing all Skripts, and I've reinstalled completely. It gives no errors, just hangs while enabling (pastebin in OP).

**Comment by panterathehacker** [comment]
Also, tried with v2.6.3 and still same issue: [stuck here indefinitely](https://pastebin.com/aHkVMv1s).

**Comment by AyhamAl-Ali** [comment]
Do you have any other plugins? can you send the names here?
also if you could send the exact version of paper that would help us test

**Comment by panterathehacker** [comment]
We're using like 70 plugins. [Here is the list](https://pastebin.com/hjvZ91Xg) -- plugin name is first column (in alphabetical order).

PaperMC v1.19.3

**Comment by panterathehacker** [comment]
> Do you have any other plugins? can you send the names here? also if you could send the exact version of paper that would help us test

We're using like 70 plugins. [Here is the list](https://pastebin.com/hjvZ91Xg) -- plugin name is first column (in alphabetical order). (Skript obviously isn't included, given we can't launch the server with it).

PaperMC v1.19.3

**Comment by panterathehacker** [comment]
Updating Paper fixed this issue.
