### ISSUE TITLE
Falling blocks death

### ISSUE THREAD

**Issue by Symmettry** [SkriptLang/Skript#5429]
### Skript/Server Version

```markdown
[00:29:52 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[00:29:52 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[00:29:52 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[00:29:52 INFO]: [Skript] Server Version: git-Paper-346 (MC: 1.19.3)
[00:29:52 INFO]: [Skript] Skript Version: 2.6.4
[00:29:52 INFO]: [Skript] Installed Skript Addons: 
[00:29:52 INFO]: [Skript]  - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
[00:29:52 INFO]: [Skript]  - SkQuery v4.1.7
[00:29:52 INFO]: [Skript]  - SkJade v1.4.2 (https://www.github.com/Ankoki-Dev/SkJade)
[00:29:52 INFO]: [Skript]  - SkBee v2.7.4 (https://github.com/ShaneBeee/SkBee)
[00:29:52 INFO]: [Skript]  - Khoryl v1.0.6
```

### Bug Description

on death: does not handle falling block entities.

### Expected Behavior

on death:
    broadcast "%entity%"
    
should print the falling block when it hits something such as a torch or slab

### Steps to Reproduce

on death:
    broadcast "%entity%"
    
spawn falling block above a torch
doesn't show the entity

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
Entity? Not victim?

**Comment by AyhamAl-Ali** [comment]
`on death` event requires either `victim` or `attacker` as `entity` can mean either of them which is why it won't work. Try `victim` instead

**Comment by Symmettry** [comment]
"Entity" was just the test code I provided. Entity refers to victim (if i recall correctly that is) and I also tried victim. It does not work, therefore this is still a bug.

You can just edit it to broadcast victim and it won't broadcast, but you decided to not test it even with victim.

**Comment by Symmettry** [comment]
@AyhamAl-Ali please reopen the issue, thanks!

**Comment by AyhamAl-Ali** [comment]
The `death` event only triggers on living entities which means a falling block (non-living entity) will not trigger the event
![image](https://user-images.githubusercontent.com/20037329/219800459-772852fc-19a5-43b1-9b9b-4ece8badb521.png)

Not sure if there is an event for what you mentioned

**Comment by Symmettry** [comment]
Many entities exist that aren’t considered a “living entity”. There still should be an event for those ones (such as end crystal explode if that exists already) or just add them into the death event.

**Comment by AyhamAl-Ali** [comment]
Well, if there are events for those made by Bukkit you can suggest to add support them in their own event not with death's evnet, we don't create events ourselves we just implement them from Bukkit API.

As for Crystal Explode that should be covered by #3990 PR, it should be ready very soon

**Comment by Fusezion** [comment]
> Many entities exist that aren’t considered a “living entity”. There still should be an event for those ones (such as end crystal explode if that exists already) or just add them into the death event.

As far as I'm aware there is zero events explicitly in death for falling block the only even that ever gets called by this is `EntityDamagedByEntityEvent` (skript's `on damage`)

**Comment by Symmettry** [comment]
So it would be checking if the hurt entity nbt is false (else { }) and check if the entity was a falling block, and call an event for something along the lines of "on block death:" or "on falling block death:"
Right?
