### ISSUE TITLE
Skript loads 150k aliases at startup -- server spends so long trying to enable Skript that it crashes, preventing the server from starting.

### ISSUE THREAD

**Issue by panterathehacker** [SkriptLang/Skript#5431]
### Skript/Server Version

```markdown
Skript v2.6.4, but tried with the latest 3 releases.

PaperMC v1.19.3
```

### Bug Description

Skript attempts to load 150k aliases at startup ([image](https://imgur.com/9228Z00)). This times the server out. The server cannot start with Skript installed; it hangs on attempting to enable Skript.

### Expected Behavior

Enable Skript at startup normally, without requiring 2GB of extra RAM.

### Steps to Reproduce

Spent 9 hours on this today, 3 of which were with tech support from my hosting company. Here is the breakdown:

- PaperMC crashes today, due to a corrupted chunk.
- We delete the chunk and restart the server. When we do, the server gets stuck on enabling Skript; it does not start, and times out.
- Note: we did not change anything about any files/plugins. Skript was working, then after the restart it won't load.
- We delete all the custom scripts and restart. Still gets stuck. 
- We delete the Skript folder and restart. Still gets stuck.
- We delete the .jar (uninstall the plugin) and restart. The server starts up fine when Skript isn't installed.
- We reinstall a fresh Skript .jar, and the server once again gets stuck trying to enable it. Does not start. 
- Notably, although it does not finish enabling Skript, a Skript folder is created...but the folder does NOT have the variables.csv file.
- We repeat this process probably 15 times, in different iterations -- trying different releases of Skript, deleting the folder but keeping the jar, deleting different files from the folder, etc. Each time the server does not start because it gets stuck attempting to enable Skript at startup, and no variables.csv file is made.
- We give the server an extra 2GB of RAM (from 8GB to 10GB) and restart -- it is able to enable Skript [after loading over 150,000 aliases](https://imgur.com/9228Z00), and the server starts up fine. Now, in the Skript folder, a variables.csv file is present.

### Other

Question 1: what are "aliases" in Skript, and is 150k a normal amount to load at startup? [Server hosting company support operator thinks not](https://imgur.com/FtnrUWJ), given that it requires that the plugin has 2GB extra of RAM in order to enable the plugin at startup, and will time you out from starting your server otherwise.

Question 2: How might I reduce this number? Note: this is happening with a fresh install of Skript -- no custom scripts or anything.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Moderocky** [comment]
Skript's loading of aliases is not requiring this additional memory by itself.
Below I have attached an image of me loading Skript and all 153613 aliases in under 600mb, which is clearly a lot less than what your server was requiring.
<img width="799" alt="image" src="https://user-images.githubusercontent.com/14147477/216928428-04c0df8c-4173-4386-b003-07833a13a599.png">

"Removing" aliases is not really a solution; aliases are the mappings that allow you to refer to items by an english name rather than their internal ID. They're also relatively small and, while they can take a few seconds to process on a slower machine (as you can see mine took 10 seconds, 4 seconds longer than my typical 6), I have never encountered this stopping the server.

Without knowing more about your server setup I can't really give you any advice other than profiling it on startup to try to determine which task is requiring so much memory.

**Comment by panterathehacker** [comment]
> Skript's loading of aliases is not requiring this additional memory by itself. Below I have attached an image of me loading Skript and all 153613 aliases in under 600mb, which is clearly a lot less than what your server was requiring. <img alt="image" width="799" src="https://user-images.githubusercontent.com/14147477/216928428-04c0df8c-4173-4386-b003-07833a13a599.png">
> 
> "Removing" aliases is not really a solution; aliases are the mappings that allow you to refer to items by an english name rather than their internal ID. They're also relatively small and, while they can take a few seconds to process on a slower machine (as you can see mine took 10 seconds, 4 seconds longer than my typical 6), I have never encountered this stopping the server.
> 
> Without knowing more about your server setup I can't really give you any advice other than profiling it on startup to try to determine which task is requiring so much memory.

Thanks for the detailed response, and for the definitions. 

Without Skript, the server started fine. With Skript, it always got stuck on enabling Skript. Every time; probably 50 times we killed it and restarted it, just for it to hang on enabling Skript. So there’s definitely some part of Skript that’s sucking all the startup memory. Any suggestions on tests I can run to determine which part? 

Seems certain that it’s Skript requiring so much memory, and I’m assuming it’s the aliases just because that’s the part of enabling Skript that was never achieved until the extra 2GB of RAM were added. 

Perhaps there’s some reason my aliases might be larger? Even with a fresh install.

**Comment by Moderocky** [comment]
> Perhaps there’s some reason my aliases might be larger? Even with a fresh install.
Your aliases are the same as everybody else's, they come from our repository [here](https://github.com/SkriptLang/skript-aliases)

> With Skript, it always got stuck on enabling Skript.
Well we can rule out Skript by itself, so now we can check if it's something else interacting with Skript.
The easiest way would be to use some kind of start-up profiler tool or attach a debugger (so we can see what's actually doing what), but barring that:

1. Have you tried removing and re-adding your scripts/variables to see if a particular file is causing the delay? (Skript + file = delay?)
2. Have you tried removing other plugins and adding them one-by-one to see if an interaction between Skript and the other plugin is causing the delay? (Skript + plugin = delay?)
3. Have you tried starting a fresh server like localhost with the same plugins to see if it's Skript interacting with the world causing the delay? (Skript + world = delay?)

Unfortunately without a proper profiling tool we may just have to check things by process of elimination here.

If you could provide your logs and plugin list there may be a clue in there.

**Comment by AyhamAl-Ali** [comment]
Things to note here:
- Your spigot's watchdog configurations might have the timeout set to a low value which causes it to not handle some delay (see Kenzie's loading aliases image, it took ~4.5 seconds)
- Your memory might not be given at full capacity (only max memory set but not minimum memory as well), it might hang when trying to allocate more memory as it's loading which could hang your whole server

Can you try:
- Running Skript on your local
- Running Skript with your plugins on local
- Running Skript alone on your hosted server (no other plugins)

**Comment by panterathehacker** [comment]
> * Your spigot's watchdog configurations might have the timeout set to a low value which causes it to not handle some delay (see Kenzie's loading aliases image, it took ~4.5 seconds)

Will check this out, but usually takes 60-90s to time out. It tries to enable it for a while.

> * Your memory might not be given at full capacity (only max memory set but not minimum memory as well), it might hang when trying to allocate more memory as it's loading which could hang your whole server

Will check this out as well.

> * **Important note** since you had a curropted chunk, this can lead to a possible crash if that chunk was stored in Skript's variables file, can you try to backup and rename your variables.csv (/plugins/Skript/variables.csv) and restart, see if that fixes it.

This is happening with a fresh install of Skript; there are no chunks stored in variables.csv and as I mentioned, the variables.csv folder is actually never created until it fully enables the plugin (requiring the extra 2GB). When it hangs and times out, every file except for variables.csv is created. We tried uploading our own blank variables.csv file when it would hang and that did not work.

**Comment by Moderocky** [comment]
> Is there such a tool we can use? Happy to try this out.

Probably not, since you're doing this on a shared host. There might be some kind of profiler plugin you can find on Spigot, or maybe even Paper's built-in timings might catch something.

**Comment by panterathehacker** [comment]
> 2. Have you tried removing other plugins and adding them one-by-one to see if an interaction between Skript and the other plugin is causing the delay? (Skript + plugin = delay?)
> 3. Have you tried starting a fresh server like localhost with the same plugins to see if it's Skript interacting with the world causing the delay? (Skript + world = delay?)

We haven't been able to reproduce the error on our local server using all the same plugins (have not tried worlds yet).

When Skript is enabled on our server, this is the console message: https://imgur.com/9228Z00 -- of note, it loads 153k aliases in 9 seconds.

When Skript is enabled on our local server, this is the console message: https://imgur.com/a/tgUhHGi -- of note, it loads 0 variables in 0 seconds, and 3 scripts with 5 triggers in 0.25 seconds.

Any reason why these are different? Of note, the entire console message is different on our hosted server than our local server (it confirms the version, shouts out the creator, etc. And on our local server, it does not load any aliases. It is the same version of Skript -- we literally downloaded all our jars from the hosted server and dropped them into a fresh server with the exact same PaperMC version/jar.

Our thought process is that this gap may be why we are unable to reproduce.

**Comment by panterathehacker** [comment]
Hi All,

Closing this out, since we have diagnosed & solved the issue, and wanted to share that it was not at all Skript's fault (kinda).

- On 2/5, our hosting service's Los Angeles server location was under maintenance (this is where our server lives). At that time, all the nodes in that location were under high stress. Because of this node stress, our server crashed several times. As their technical support operator said at the time of our ticket submission: "all the nodes are having this issue."
- When our server crashed because of the crowded node, the chunks.dat file within the data folder of our default world folder became corrupted, and caused a memory leak.
- At 8GB, when the server went to enable Skript during startup, it had already leaked so much memory that the memory required to enable Skript maxed it out, causing a heap error and the server to hang and/or crash.
- This is why adding the extra 2GB of RAM solved the symptom.

We restored a backup non-corrupt version of our chunks.dat file, and with that we were able to load the server fine at the 8GB that previously we could not.

So it wasn't Skript's fault necessarily that our server wasn't able to start. However, Skript does take a lot of memory/time to enable at startup. It takes 15-18 seconds for us to load the plugin at startup. Most plugins take 1 second or less. And of note, this is on 8GB RAM and a solid, hosted, CPU (Intel(R) Xeon(R) CPU E5-2643 v3 @ 3.40GHz). 

Is there anything we can do to reduce this time? I really don't think it's a hardware problem.

**Comment by Moderocky** [comment]
> It takes 15-18 seconds for us to load the plugin at startup. Most plugins take 1 second or less. 

This is an unusually long time, on my laptop it takes around ~5 seconds. \
Some of this will be Skript loading a large number of internals, aliases and other resources.
After this it has to parse all of your script files -- this is not a quick task; there's an entire programming language running here to assemble an executable model of the code you wrote.

> Is there anything we can do to reduce this time? I really don't think it's a hardware problem.

So 15-18 seconds sounds like you either have a large number of (long) scripts or there are inefficiencies in the code you've written (e.g. overly-long lines, ambiguous code).

There are various support Discords you can visit for help in optimising your code, that's really not a task we can handle in a GitHub ticket. :)

**Comment by ShaneBeee** [comment]
>  there exists a Skript build designed to work without them (by @ShaneBeee, if I recall correctly).

Just a note on this:
- It was an experimental build, nothing I actually released. Was done more for testing
- Alias still exist in the form of auto loading. Long story short, the aliases file doesn't exist, it just builds aliases based on material names.
- Due to this, alias load time was DRASTICALLY shortened.

that said I don't have this build anymore.

**Comment by panterathehacker** [comment]
> > It takes 15-18 seconds for us to load the plugin at startup. Most plugins take 1 second or less.
> 
> This is an unusually long time, on my laptop it takes around ~5 seconds. Some of this will be Skript loading a large number of internals, aliases and other resources. After this it has to parse all of your script files -- this is not a quick task; there's an entire programming language running here to assemble an executable model of the code you wrote.
> 
> > Is there anything we can do to reduce this time? I really don't think it's a hardware problem.
> 
> So 15-18 seconds sounds like you either have a large number of (long) scripts or there are inefficiencies in the code you've written (e.g. overly-long lines, ambiguous code).
> 
> There are various support Discords you can visit for help in optimising your code, that's really not a task we can handle in a GitHub ticket. :)

Thanks for the replies here -- just want to say I really appreciate how responsive your team is.

To be fair, we have only 3 scripts. The largest is 120 lines (4.9kb), and half of the lines are actually commented out. All 3 combined are 190 lines (7.5kb total), this is not including any of the disabled default scripts that come with the plugin. So it doesn't seem like too much code to parse through. We can take a look to see how it can be optimized, but they were all 3 written by a Google SWE with lots of minecraft server plugin dev experience so I'd be surprised haha. 

This is to say, are there other factors that may be causing such a long startup time?

**Comment by Pikachu920** [comment]
> > > It takes 15-18 seconds for us to load the plugin at startup. Most plugins take 1 second or less.
> > 
> > This is an unusually long time, on my laptop it takes around ~5 seconds. Some of this will be Skript loading a large number of internals, aliases and other resources. After this it has to parse all of your script files -- this is not a quick task; there's an entire programming language running here to assemble an executable model of the code you wrote.
> > 
> > > Is there anything we can do to reduce this time? I really don't think it's a hardware problem.
> > 
> > So 15-18 seconds sounds like you either have a large number of (long) scripts or there are inefficiencies in the code you've written (e.g. overly-long lines, ambiguous code).
> > 
> > There are various support Discords you can visit for help in optimising your code, that's really not a task we can handle in a GitHub ticket. :)
> 
> Thanks for the replies here -- just want to say I really appreciate how responsive your team is.
> 
> To be fair, we have only 3 scripts. The largest is 120 lines (4.9kb), and half of the lines are actually commented out. All 3 combined are 190 lines (7.5kb total), this is not including any of the disabled default scripts that come with the plugin. So it doesn't seem like too much code to parse through. We can take a look to see how it can be optimized, but they were all 3 written by a Google SWE with lots of minecraft server plugin dev experience so I'd be surprised haha. 
> 
> This is to say, are there other factors that may be causing such a long startup time?

Usually it's not the line count, but rather individual lines that are very long. You can help the parser speed up by adding parentheses around complicated expressions. That's not to say your code isn't optimized, it's really just the parser that is rough. Other than that, there's not a ton to do on your end. It's something we're improving slowly and some recent PRs make great improvements.
