### ISSUE TITLE
Every integer resets

### ISSUE THREAD

**Issue by Crinkl** [SkriptLang/Skript#5434]
### Skript/Server Version

```markdown
https://gyazo.com/4bdf5af784f36abaac7baae3a74f0110
```

### Bug Description

All of my variables, such as kills, deaths, joins inventory, and ender chest all reset.
It happened 3 times, and I don't know what caused it.
Please someone help me. Also, I know it's not a skript causing it because none of my skripts have that in the first place, and yes I've already checked.
Also it couldn't have been a person since my joins were < none > instead of 0.

### Expected Behavior

It was supposed to stay what it was, but it keeps resetting.

### Steps to Reproduce

I didn't do anything, it just keeps randomly resetting everything.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
We would need more info on this to be able to replicate if possible and help.
You should use latest Skript (2.6.4) as we don't support older versions unless it's critical.

Are you running offline mode server? did you switch from offline mode to online mode? Do you remember doing anything before this begun to happen or was it from long time ago?

**Comment by Crinkl** [comment]
> We would need more info on this to be able to replicate if possible and help. You should use latest Skript (2.6.4) as we don't support older versions unless it's critical.
> 
> Are you running offline mode server? did you switch from offline mode to online mode? Do you remember doing anything before this begun to happen or was it from long time ago?

It happened this week, around Sunday, and I'll try to download the 2.6.4 version. And yes my server is running on offline mode. And no I've never switched. Before doing that it was regular stuff, I hadn't coded anything for a while before that because I was trying to focus on my builds.

**Comment by Crinkl** [comment]
My bad I accidentally clicked that lmao

**Comment by AyhamAl-Ali** [comment]
How are you storing the variables e.g. `{playerdata::%uuid of player%::kills}`? if it's using uuids can you send the uuid of the players whose data is being reset

**Comment by Crinkl** [comment]
> How are you storing the variables e.g. `{playerdata::%uuid of player%::kills}`? if it's using uuids can you send the uuid of the players whose data is being reset

I couldn't check the console, as it was spammed. And my variables for kills is `{kills.%player's uuid%}` deaths is `{deaths.%player's uuid%}` joins is `{joins}` and the inventory nor ender chest has a variable

**Comment by AyhamAl-Ali** [comment]
Having their inventory and ender chests being reset is pretty weird, I don't think that's related to Skript. 
Can you share your plugins list and try to remove skript plugin and restart (or try to replicate the reset trigger) see if their ender chests and inventories will reset again.

**Comment by Crinkl** [comment]
Hey so I found out my server's storage had reached its limit, so it was attempting to clear out data to make storage. Sorry about that lmao

**Comment by AyhamAl-Ali** [comment]
Happy to know you figured it out \:) Good luck!
