### ISSUE TITLE
When you remove a potion effect, the Player's cursor slot is removed

### ISSUE THREAD

**Issue by ImNotStable** [SkriptLang/Skript#5463]
### Skript/Server Version

```markdown
Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
Skript's documentation can be found here: https://docs.skriptlang.org/
Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
Server Version: git-Paper-346 (MC: 1.19.3)
Skript Version: 2.6.4
Installed Skript Addons:
 - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
 - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
 - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
 - SkBee v2.7.5 (https://github.com/ShaneBeee/SkBee)
Installed dependencies:
 - SQLibrary v7.1
 - Vault v1.7.3-b131
 - WorldGuard v7.0.8-SNAPSHOT+2221-1729e5e
```

### Bug Description

I'm making it so when a player holds an item they get an effect, but once they aren't anymore it removes that effect. When I pick up the item in my inventory and the effect disappears, the cursor item disappears.

### Expected Behavior

The cursor slot to stay the same.

### Steps to Reproduce

I'm using code similar to this
```
every second:
    loop all players:
        if player's tool is diamond pickaxe:
            apply night vision 1 to loop-player for 1 seconds replacing existing effect
        else:
            remove night vision from loop-player
```
Also, you must be in creative and you must be in the creative inventory.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Make sure to test w/out addons as well, just to ensure it's not an addon issue. Forgot to remind you to do that in discord.

**Comment by sovdeeth** [comment]
I can replicate on a 2.7.0 build:
```
[20:04:10 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:04:10 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[20:04:10 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[20:04:10 INFO]: [Skript] Server Version: git-Paper-404 (MC: 1.19.3)
[20:04:10 INFO]: [Skript] Skript Version: 2.7.0-dev (selfbuilt-unknown)
[20:04:10 INFO]: [Skript] Installed Skript Addons: None
[20:04:10 INFO]: [Skript] Installed dependencies:
[20:04:10 INFO]: [Skript]  - WorldGuard v7.0.8-beta-01+cbb2ba7
```

Also note that #598 and #187 seem to be related

**Comment by DelayedGaming** [comment]
The last time I tried to reproduce this bug failed. @sovdeeth can you share your procedure to reproduce the bug?

**Comment by sovdeeth** [comment]
> The last time I tried to reproduce this bug failed. @sovdeeth can you share your procedure to reproduce the bug?

```
every second:
    loop all players:
        if loop-player's tool is diamond pickaxe:
            apply night vision 1 to loop-player for 1 seconds replacing existing effect
        else:
            remove night vision from loop-player
```
Then I just opened the creative inventory, picked up an item, and waited one second.

**Comment by TheLimeGlass** [comment]
duplicate https://github.com/SkriptLang/Skript/issues/5463

**Comment by sovdeeth** [comment]
> duplicate https://github.com/SkriptLang/Skript/issues/5463

Did you mean to mark it as a duplicate of itself?
