### ISSUE TITLE
On Anvil Damage, Error

### ISSUE THREAD

**Issue by NoxWilding** [SkriptLang/Skript#5472]
### Skript/Server Version

```markdown
Server Version: git-Paper-416 (MC: 1.19.3)
Skript Version: 2.6.4
Installed Skript Addons:
- skript-gui v1.3
- skRayFall v1.9.28
- SkQuery v4.1.8
Installed dependencies:
- Vault v1.7.3-b131
- WorldGuard v7.0.8-beta-01+ccbb2ba7
```

### Bug Description

I was using the following in my Skript, and it gave an error to me.
```
on anvil damage:
    cancel event
``` 

### Expected Behavior

It was supposed to cancel anvil damage, so the anvil stays "full health" always, and never breaks.

### Steps to Reproduce

Using the same Skript and server version as me, just use the following Skript as I did to see.the 

### Errors or Screenshots

https://gist.github.com/NoxWilding/f04fa0e66060ab5ab16eb5234c520eb4

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
This is an SkQuery issue, try reporting to that author :)
