### ISSUE TITLE
Add "command" damage cause

### ISSUE THREAD

**Issue by J-ak-e** [SkriptLang/Skript#5480]
### Suggestion

Command should be a damage cause.

### Why?

When using the /kill command, `damage cause` will return `void` which is just inaccurate, other than that 1.20/1.19.4 will add the /damage command which will probably return `void` as well. Both should return `command`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
Within the minecraft source, the OUT_OF_WORLD damage source is used to kill living entities, so `void` is accurate to what's happening.
![image](https://user-images.githubusercontent.com/10354869/222035340-18a23b15-f003-460e-8071-b911c3fe8571.png)

**Comment by J-ak-e** [comment]
Yeah but you wouldn't be able to distinguish between actual void deaths and command deaths.

**Comment by Pikachu920** [comment]
> Yeah but you wouldn't be able to distinguish between actual void deaths and command deaths.

yeah but neither can Skript, because it's working off the same info. You could check if the player is actually in the void if you wanted to differentiate.

**Comment by J-ak-e** [comment]
Fair point.
