### ISSUE TITLE
Variable Save Effect

### ISSUE THREAD

**Issue by NotSoDelayed** [SkriptLang/Skript#5486]
### Suggestion

A new effect which calls for a variable save task to commence.

### Why?

To allow skripters to call for a variable save into database manually when needed.

Based on my known issues with this effect:
#### The Pros
- Call for variable save without waiting for the periodical task when necessary

#### The Cons
- Cause performance issues when misused

#### My Solutions
- Implement an unavoidable cooldown internally, where the effect will not run when burst-fired
- Effect will not register by default and shall be enabled via config.sk with precautions written above the node
- A pinch of internal stuff modifications to ensure that the save task is called and finished without interruptions caused by this effect

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
Just increase your save interval

**Comment by NotSoDelayed** [comment]
Closing — Opens up performance issues and violates Skript’s code convention
