### ISSUE TITLE
Impossible to shoot a projectile that is in a variable

### ISSUE THREAD

**Issue by Calvineries** [SkriptLang/Skript#5493]
### Skript/Server Version

```markdown
2.6.4
1.19.3
```

### Bug Description

We can't shoot a projectile that is in a variable

### Expected Behavior

Normally, the projectile should have been shooted, but nothing happens.

### Steps to Reproduce
Basic Example:
```
on load:
       set {customsnowball} to snowball
on right click with a netherite hoe:
       shoot {customsnowball} from player at speed 1
```

(you may be wondering why I want to do this, here is a useful example)
```
on load:
       set {customsnowball} to snowball with custom model data 2
on right click with a netherite hoe:
       shoot {customsnowball} from player at speed 1
```
When we do a right click, nothing happens

**Comment by Fusezion** [comment]
Skript just shoots the base projectile so this isn't supported however you can do this in skript-reflect I'm unsure how they'd be able to incorporate into skript

**Comment by Calvineries** [comment]
Same issue with tripped arrow:
```
on right click with a netherite hoe:
       shoot tipped arrow of swiftness from player at speed 5
       
       #last line only to to show that the script works
       give a tipped arrow of swiftness to player
```
-> Can't understand this condition/effect: shoot tipped arrow of swiftness from player at speed 5

**Comment by Fusezion** [comment]
> -> Can't understand this condition/effect: shoot tipped arrow of swiftness from player at speed 5

I'm currently unable to launch minecraft can you test this for me
```applescript
on shoot:
    broadcast event-projectile
```
can you shoot it with both an arrow and 2 different types of tipped arrows

**Comment by Calvineries** [comment]
> > -> Can't understand this condition/effect: shoot tipped arrow of swiftness from player at speed 5
> 
> I'm currently unable to launch minecraft can you test this for me
> 
> ```applescript
> on shoot:
>     broadcast event-projectile
> ```
> 
> can you shoot it with both an arrow and 2 different types of tipped arrows
I shot 1 arrow and 2 tipped arrows
it broadcast "arrow" the 3 times

**Comment by TheLimeGlass** [comment]
Skript is parsing the `snowball` as an itemtype, and saving the variable as an itemtype. Then when Skript goes to parse the variable it uses Variable#getConverteredExpression(EntityData.class) which is just a new variable instance. When it then goes to grab the entity data it returns an empty array because well, an ItemType is not an EntityData and it also cannot be converted as there is no possible converter for these types.

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/3753
