### ISSUE TITLE
Be able to get the id of a effect or potion (item).

### ISSUE THREAD

**Issue by NopeProsOnly** [SkriptLang/Skript#5520]
### Suggestion

The id of Absorption is 22. Which is proven here -
`/give @p potion{display:{Name:'[{"text":"Absorption"}]'},CustomPotionEffects:[{Id:22,Duration:1,Amplifier:1}]} 1`

Here is an example of using it with skript:
```livecodeserver
command /test:
  trigger:
    send id of player's tool
```
Note: this only works below 1.13
If you send it above that, you get:
`Items do not have numeric ids on Minecraft 1.13 or newer.`
If that were not the case, it would still send the 1.13 id of the item.
But, that isn't the case for potion effects!
I see no reason to not add this.

### Why?

Because it is extremely difficult to do custom potions. You can only do `long` or `strong` but you can't do `tier x splash potion of x` for potions (item) Like, how can I give the player a potion that gives the player speed 10 for 100 seconds?

I understand you can use the event for consuming the potion, but come on...

### Other

Uhh. Not really. If anything comes up, I'll let ya know.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Skript 2.7 only support MC 1.13+ therefore you will have to use an older skript version for 1.12- or use the [unofficial Mato's 1.8 fork](https://github.com/Matocolotoe/Skript-1.8/releases/tag/2.6.4-for-1.8)

**Comment by sovdeeth** [comment]
Also, if you want to create a potion of an arbitrary type and duration, do ``add potion effect of speed of tier 10 to potion effects of {_item}``

**Comment by NopeProsOnly** [comment]
> Skript 2.7 only support MC 1.13+ therefore you will have to use an older skript version for 1.12- or use the [unofficial Mato's 1.8 fork](https://github.com/Matocolotoe/Skript-1.8/releases/tag/2.6.4-for-1.8)

I am using skript 2.7 and am on 1.19.2. I am not asking for help with an older version. I just want to have `id of potion effect` added.
What sovdeeth said is super! Although, that doesn't get me the id of a potion effect. Minecraft 1.19.x still uses Numeral ID's for potion effects.

**Comment by Fusezion** [comment]
Minecraft doesn't actively use id's at all if any. Minecraft has taken the route of using words as such you have no use for Id of potion effects

**Comment by NopeProsOnly** [comment]
> Also, if you want to create a potion of an arbitrary type and duration, do `add potion effect of speed of tier 10 for 10 seconds to potion effects of {_item}`

This solves it.

`/give @p potion{display:{Name:'[{"text":"Absorption"}]'},CustomPotionEffects:[{Id:`**22**`,Duration:1,Amplifier:1}]} 1`
As you can see here, they use id's I know skript is for words instead, just thought this would be a good idea.

**Comment by AyhamAl-Ali** [comment]
> I am using skript 2.7 and am on 1.19.2. I am not asking for help with an older version. I just want to have id of potion effect added.

Now that's clear. I wonder if that's available in Spigot's API.. if it's we can reopen this issue

**Comment by Fusezion** [comment]
The best we could do is get the potion of a potion effect type I don't believe there is a method. We might be able to make a enum but would have to update manually

**Comment by AyhamAl-Ali** [comment]
If it's not supported by Spigot/Paper API it has a very low chance of being internally supported by Skript

**Comment by Fusezion** [comment]
> If it's not supported by Spigot/Paper API it has a very low chance of being internally supported by Skript

Just had a little sneak peak, There still exists a `Potion#getNameId` however this has basically been deprecated since 1.9 and replaced with PotionMeta class instead and after rechecking PotionEffect class can confirm it's not within that either meaning there's zero method to get it

![image](https://user-images.githubusercontent.com/81952476/225239062-40cd184d-5274-4a3a-bd5a-6442e654c6ce.png)
