### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Huiqqqqqq** [SkriptLang/Skript#5525]
### Skript/Server Version

```markdown
Last
```

### Bug Description

Is it possible to put the function of a chest or a stove on the blocks? So that when you click on the golden block, the chest opens

### Expected Behavior

.

### Steps to Reproduce

.

### Errors or Screenshots

.

### Other

.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
This is an issue tracker to report issues/bugs or request features. Please use [skUnity discord server help channels](https://discord.gg/skript) for skript help.

A quick answer is yes you can, for more details use the discord server.
