### ISSUE TITLE
ExprEgg works for all events

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5539]
### Suggestion

Add an init method and event check for the ExprEgg class

### Why?

Unlike all the other syntax for this api it was never given an `init` method with a check for if it's a valid event, making the expression usable anywhere

### Other

Class link
https://github.com/SkriptLang/Skript/blob/d2e7ce9084fbc7e1354da424dc66baf0d097121d/src/main/java/ch/njol/skript/expressions/ExprEgg.java

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
It's an event value expression. If the event has an Egg it can be used by the expression. What is this suggesting?

**Comment by Fusezion** [comment]
> It's an event value expression. If the event has an Egg it can be used by the expression. What is this suggesting?

the expression can be used in any event reguardless doesn't send an error like most other stuff ex: attacker/victim in damage/death events. All other classes for this event do so
![image](https://user-images.githubusercontent.com/81952476/226293796-c4863643-84db-42b4-bdf9-1c66e3f48eb0.png)

**Comment by APickledWalrus** [comment]
This seems like a bug because the expectation I had was that this would only work if the event had an event-value registered that specifically returns an egg (not any kind of living entity)
