### ISSUE TITLE
sheared expression instead of effect

### ISSUE THREAD

**Issue by JakeGBLP** [SkriptLang/Skript#5561]
### Suggestion

The effect https://skripthub.net/docs/?id=1111
should be an expression, that's because the effect is changing the sheared status of a sheep which can be simplified with a boolean expression.
Furthermore, this effect should not be removed, instead it should be used with https://jd.papermc.io/paper/1.19/io/papermc/paper/entity/Shearable.html#shear()
and offer the option of shearing without dropping items (which would do what the effect currently does).

### Why?

Would make more sense to have an expression for the current shear effect.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by J-ak-e** [comment]
Using readyToBeSheared() would also make for a pretty decent `force shear %entity%`

**Comment by sovdeeth** [comment]
I would say it'd be better served by just adding a condition ``is shorn/sheared``.
I'm not a fan of expressions in the style of ``shear state of entity``, they feel awkward and weird compared to just ``shear entity`` and ``if entity is shorn/sheared``.

**Comment by DelayedGaming** [comment]
> Furthermore, this effect should not be removed, instead it should be used with https://jd.papermc.io/paper/1.19/io/papermc/paper/entity/Shearable.html#shear() and offer the option of shearing without dropping items (which would do what the effect currently does).

Looks like Shearable interface is added in 1.19. This effect could adapt to it to allow support on these and future entities.
