### ISSUE TITLE
Add "Decrease" to the Change Effect.

### ISSUE THREAD

**Issue by JakeGBLP** [SkriptLang/Skript#5595]
### Suggestion

The 7th pattern of the change effect should include "decrease" along with "reduce"

### Why?

The 7th pattern of the change effect is `reduce %objects% by %objects%`, it would be logical to add "decrease" to it as "decrease" and "reduce" stand for the same thing, as such `(reduce|decrease) %objects% by %objects%` should be the new pattern, no behavior changes.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by APickledWalrus** [comment]
"Good First Issue" Tutorial:

This change is very easy. Simply change the line at https://github.com/SkriptLang/Skript/blob/6724b012792ef7feab2a9645ede2bbfa46941016/src/main/java/ch/njol/skript/effects/EffChange.java#L90 to include a choice pattern for both reduce and decrease. This would appear as `(reduce|decrease)` (the user can then make use of either word).

**Comment by J-ak-e** [comment]
> "Good First Issue" Tutorial:
> 
> This change is very easy. Simply change the line at
> 
> https://github.com/SkriptLang/Skript/blob/6724b012792ef7feab2a9645ede2bbfa46941016/src/main/java/ch/njol/skript/effects/EffChange.java#L90
> 
> to include a choice pattern for both reduce and decrease. This would appear as `(reduce|decrease)` (the user can then make use of either word).

real
