### ISSUE TITLE
Infinite PotionEffect

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#5596]
### Suggestion

Add the infinite potion effect boolean toggle.

Should wait to use the set effects waiting on merge at https://github.com/SkriptLang/Skript/pull/5219

Something like `infinite %potioneffects%` could also make it a WrapperExpression `infinite %~objects%` if we were to add more infinite syntaxes.

### Why?

Discord suggestion

### Other

I think it's a 1.19.4 feature.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Moderocky** [comment]
In versions before 1.19.4 do you think we should use the int-max-value duration or should it not work?

**Comment by TheLimeGlass** [comment]
> In versions before 1.19.4 do you think we should use the int-max-value duration or should it not work?

I don't really know. It wouldn't *really* be infinite.
