### ISSUE TITLE
Left/Right Click recognition not working properly

### ISSUE THREAD

**Issue by HydroCompanys** [SkriptLang/Skript#5598]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-381 (MC: 1.19.3)
[Skript] Skript Version: 2.7.0-beta2 (skriptlang-github)
```

### Bug Description

if i press both only left is debuged

### Expected Behavior

that both clicks are recognized

### Steps to Reproduce

on leftclick:
	send "left"
	
on rightclick:
	send "right"

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by J-ak-e** [comment]
Have you tried the same thing but with broadcast instead? there's a chance, if this isn't already fixed in beta2, that the send effect sends to event-entity instead of the player.

**Comment by TheLimeGlass** [comment]
Left click is only when not on an entity as left clicking on an entity is an attack. Right clicking only works when you have an item in your hand or you right click an entity or block. This is Minecraft behaviour.
