### ISSUE TITLE
Colored banners don't work as an itemtype, only as a blocktype.

### ISSUE THREAD

**Issue by 24GDude** [SkriptLang/Skript#5600]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-448 (MC: 1.19.3)
[Skript] Skript Version: 2.6.4
[Skript] Installed Skript Addons: 
[Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[Skript]  - Diskuise v0.3.4 (https://github.com/UnderscoreTud/diskuise)
[Skript]  - SkBee v2.8.3 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: None
```

### Bug Description

When you're trying giving a player a specific color of a banner, it gives the following error:
```
Error in: give all players orange banner
'orange banner' can't be added to a player because the former is neither an item type, an inventory nor an experience point
```
This only works with setting a block to a colored banner like so: `set block above target block to orange banner` (gives no errors)

### Expected Behavior

You should be able to use a specific color banner as an item, but an error is given.

### Steps to Reproduce

1. In a script or effect command, try giving a player a specific color banner like you would with any other item (such as orange, white, green, etc.)

### Errors or Screenshots

`'orange banner' can't be added to a player because the former is neither an item type, an inventory nor an experience point`
![image](https://user-images.githubusercontent.com/85128892/231578123-3e266d5c-c8f8-44bb-b4d2-192020321d0a.png)

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by hapily04** [comment]
`orange standing banner` is the proper usage

If you're confused as to what alias to use in the future you can see https://github.com/SkriptLang/skript-aliases/tree/fb9c3044e555667b4dc5558467608bd55fa32df0

**Comment by 24GDude** [comment]
Thanks hapily, it finally works. I do think they should allow `orange banner` to still work though.
