### ISSUE TITLE
Skript command bug

### ISSUE THREAD

**Issue by ghostjusr** [SkriptLang/Skript#5613]
### Skript/Server Version

```markdown
1.19 Spigot Server
Installed Addons:
TuSKe
skRayFall
```

### Bug Description

When I was on the server, I reloaded the script. It says that it was successful, but when I try to use a command I created, it says it was an unknown or incomplete command.

### Expected Behavior

I watched a bunch of tutorials about creating custom commands and I'm pretty sure my syntax is correct.

### Steps to Reproduce

I don't know why this happened, and help would be really useful.
Also, the code is here:
[https://pastebin.com/KsrEtfvN](url)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
Please stop using tuske, it isn't made for versions after 1.13 it's basically legacy, please use skript-gui or vanilla guis. unrelated to skript plugin as a whole

**Comment by ghostjusr** [comment]
That worked, thanks.
