### ISSUE TITLE
Gui bug

### ISSUE THREAD

**Issue by ghostjusr** [SkriptLang/Skript#5620]
### Skript/Server Version

```markdown
Spigot 1.19.4
Running Skript version 2.6.4
Installed Addons:
 - SkQuery
```

### Bug Description

When I try to format a gui slot, it gives me the error:
You can't make a GUI slot outside of a GUI creation or editor.

### Expected Behavior

can you please help? 😁

### Steps to Reproduce

This is the code I'm using:
command /minigames:
   trigger:
      open virtual chest inventory with size 6 named "Minigame Selector" to player
      format gui slot 11 with bed named "BedWars" with lore "Click here to play bedwars!"

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
This isn't related to skript, this github is used as a place to suggest featurs, contribute and report bug. The issue you're having is something that should be asked in a help channel such as one in [SkUnity](https://discord.gg/skript)
