### ISSUE TITLE
Bedrockplayer buggs

### ISSUE THREAD

**Issue by RentnerKev** [SkriptLang/Skript#5634]
### Skript/Server Version

```markdown
Server version 1.17.1
skript version 2.6.4
```

### Bug Description

https://paste.gg/p/anonymous/e6c9d890ab864a14a8342993a70cc560/files/7dfdcfe987d1482a90c2e248b47ecb81/raw

this is my skript i use for my server to drop things work fine for the java people but for the bedrock guys it drop like x10 more than for java how can i fix?

for Java/bedrock server i use GeyserMC (i allready been in there support but they said i should come here)

tyall for help

### Expected Behavior

for bedrock it should drop 1 item per 5 sec like the java and not 3-10 items per 5 sec

### Steps to Reproduce

Bedrock (GeyserMC)

### Errors or Screenshots

https://user-images.githubusercontent.com/131619569/234006413-8cee4d94-309d-4f32-b9d8-35764eaa1341.mp4

### Other

ps:
pls ignore the screen recording overlay
and pls awnser fast becouse player beeing angry saddly 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
This is 100% a Geyser issue. Skript has nothing to do with Bedrock, Geyser is not supported by Skript. Skript uses Spigot, so it's the purpose of a protocol mod to handle what it was designed for.

**Comment by RentnerKev** [comment]
perfect becouse they say its your guys fault
