### ISSUE TITLE
EventValueExpression Does Not Error When Used in Incorrect Event

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#5635]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-477 (MC: 1.19.4)
[Skript] Skript Version: 2.7.0-beta2 (selfbuilt-unknown)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

When EventValueExpressions are used in incorrect events such as __teleport cause OR spawn reason in a chat event__, Skript does not error out during script reload.

### Expected Behavior

Skript should error out during script reload.

### Steps to Reproduce

Use any EventValueExpression in an incorrect event.
Using code as shown below for this demonstration:
```py
on chat:
    broadcast teleport cause # Expected to error
    broadcast "%teleport cause% -- Expected to error"

on chat:
    broadcast spawn reason # Expected to error
    broadcast "%spawn reason% -- Expected to error"
```

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/72163224/234041257-339731f8-7b87-4bdf-aa17-8aeb85c53f50.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Cause by the new literal string pull request
