### ISSUE TITLE
Skript Errors

### ISSUE THREAD

**Issue by TBAProgramming** [SkriptLang/Skript#5648]
### Skript/Server Version

```markdown
Skript Verison: 2.6.4
Server Type: Paper
Server Version: 1.19.4
Server Hosting: none, just i made it in my desktop
```

### Bug Description

i trying to reload my skript and its not wont, i checked the console and i see their errors

**Console Logs Errors:**
       **[https://pastebin.com/raw/QPk691Mk](url)**
See all logs

### Expected Behavior

Console errors,
my skript wont work, 
saying to me reloaded without any error in-game but not working

### Steps to Reproduce

checked console
checked logs
checked lastetlog
checked my skript version

### Errors or Screenshots

**
Console Logs Errors:
         [https://pastebin.com/raw/QPk691Mk](url)
**

See all logs

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Addon issue
```log
[21:11:35] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Can't register org.bukkit.boss.KeyedBossBar with the code name bossbar because that name is already used by types.bossbar
[21:11:35] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.registrations.Classes.registerClass(Classes.java:94)
[21:11:35] [Server thread/ERROR]: #!#!     at skript-bossbar.jar//me.tud.skriptbossbar.elements.ClassInfos.<clinit>(ClassInfos.java:25)
```

**Comment by TBAProgramming** [comment]
what is addon that?

**Comment by TBAProgramming** [comment]
and i will delete it

**Comment by APickledWalrus** [comment]
Try removing skript-bossbar and TuSKe

**Comment by TBAProgramming** [comment]
why

**Comment by APickledWalrus** [comment]
Those are the addons causing the error

**Comment by TBAProgramming** [comment]
i will try

**Comment by TBAProgramming** [comment]
wait me

**Comment by TBAProgramming** [comment]
that error or not? 

`[21:40:12 WARN]: Legacy plugin SkStuff v1.6.4.1 does not specify an api-version.
[21:40:12 WARN]: Legacy plugin skript-placeholders v1.5.2 does not specify an api-version.
[21:40:12 WARN]: Legacy plugin Invsee v1.0.0 does not specify an api-version.
[21:40:12 WARN]: Legacy plugin Ersatz v1.0 does not specify an api-version.`

**Comment by AyhamAl-Ali** [comment]
> WARN

That's a warning, not an error no worries

**Comment by TBAProgramming** [comment]
https://pastebin.com/xJFeRD9j see

**Comment by TBAProgramming** [comment]
that error

**Comment by TBAProgramming** [comment]
oops my version skript is: Skript-2.7.0-beta2

**Comment by AyhamAl-Ali** [comment]
> java.lang.RuntimeException: pattern compiling exception, element class: com.gmail.thelimeglass.Npcs.CondNpcIsSpawned (provided by Skellett)

Update Skellett

**Comment by TBAProgramming** [comment]
hm ago 5 minutes i downloaded it

**Comment by TBAProgramming** [comment]
bruh

**Comment by TBAProgramming** [comment]
ayhamai-ali you have fix for that?

**Comment by TBAProgramming** [comment]
oh fixed ty for before downloaded old version not lastest version

**Comment by TBAProgramming** [comment]
here a problem new https://pastebin.com/D20RXsM2

**Comment by TBAProgramming** [comment]
lol

**Comment by AyhamAl-Ali** [comment]
Please use [skUnity discord help channels](https://discord.gg/skript) for further assistance, this is Skript related issue tracker not addons.

**Comment by TBAProgramming** [comment]
ok

**Comment by TBAProgramming** [comment]
i maked post
