### ISSUE TITLE
I need help with it

### ISSUE THREAD

**Issue by TBAProgramming** [SkriptLang/Skript#5651]
### Skript/Server Version

```markdown
server: paper_1.19.4
skript: 2.6.4
```

### Bug Description

[Console logs paste.gg](https://paste.gg/p/anonymous/1483f7bd69544214ad98e782624a527b/files/5a147ed006c44f5dbdd56c12744c4d90/raw)
i need help that error or bug or smth tell me some plugins doesn't work by that

### Expected Behavior

[Console logs paste.gg](https://paste.gg/p/anonymous/1483f7bd69544214ad98e782624a527b/files/5a147ed006c44f5dbdd56c12744c4d90/raw)
some plugins not working

### Steps to Reproduce

1 see logs
2 see if i in correct version of skript
3 checked server

### Errors or Screenshots

[Console logs paste.gg](https://paste.gg/p/anonymous/1483f7bd69544214ad98e782624a527b/files/5a147ed006c44f5dbdd56c12744c4d90/raw)
i need help that error or bug or smth tell me some plugins doesn't work by that

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TBAProgramming** [comment]
someplugins like fawe

**Comment by TBAProgramming** [comment]
![image](https://user-images.githubusercontent.com/121028379/234921749-7e04e323-ce05-4a49-9695-bb45ea302405.png)

**Comment by TBAProgramming** [comment]
home, hosting: minehut

**Comment by TBAProgramming** [comment]
@AyhamAl-Ali

**Comment by BaeFell** [comment]
When you encounter a 403 error, it usually means that the server host is blocked from accessing Github's API. This could be due to a variety of factors, such as exceeding API rate limits or using invalid credentials.

**Comment by AyhamAl-Ali** [comment]
This is not a server issue, I cannot reproduce it, please use skUnity discord help channels before reporting such issues as this issue tracker is for bugs and suggestions.
