### ISSUE TITLE
A player change armor event without triggering whenever the players armor is damaged.

### ISSUE THREAD

**Issue by samthecoderevamp** [SkriptLang/Skript#5652]
### Suggestion

I'm not sure if this is a bug or this is how it is intended to work. I was told it was a server issue and to go on skunity for help but I went on there and I didn't receive help and I was rudely ignored.
Maybe I'm missing something but I'm not sure.

### Why?

Skript should have it's own armor equip and unequip events(or both combined into one event) without having to trigger whenever a player's armor is damaged.
Using SharpSK (the revisited version) has unknown errors with the armor equip and armor unequip events even through it works on my other server perfectly fine with the same plugin and server versions. Fully updated to say.
Sure, you could just make the armor unbreakable but there should be way to have breakable armor that only triggers the event when the armor is equipped or unequipped.
Having unbreakable OP skript armor in PVP can be a severe downside for players who don't have unbreakable skript armor.
It wouldn't be fair either if everyone just had that op skript armor.
Making that armor breakable will help fix those upsides and plus it wouldn't constantly trigger the event which would also trigger the commands in there constantly and cause server resources.

### Other

https://github.com/ShaneBeee/SkBee/issues/319#issuecomment-1378756907 proof

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
Based off what Shane said on there, and basic knowledge. This is an intended thing within paper or something that's caused by Minecraft. As such your only answer would be to check damage of the items, as for skript changing this the most they can do is add a condition check comparing which is most likely unlikely to happen

**Comment by samthecoderevamp** [comment]
I cannot use a periodic event either as it's more resource heavy and it needs to trigger as soon as player takes off and on their armor or else the skript won't be consistent and will have loopholes.

**Comment by samthecoderevamp** [comment]
I already asked how to check if a player's armor is damaged on skunity and I received no solutions from three months ago.

**Comment by samthecoderevamp** [comment]
Okay I fixed somehow using that event but using the condition "if item is armor" in on item damage event it misidentifies as my golden helmet not being counted as armor. I tested it further with a diamond chestplate and same issue occurs. My skript is up to date.

**Comment by samthecoderevamp** [comment]
I also still had to make my own variable to use as a condition for the other event.

**Comment by samthecoderevamp** [comment]
Nope, it doesn't work your skript event(on change player armor) can't check if the player is wearing armor. No idea why the condition doesn't trigger correctly as it works with armor equip and armor unequip from sharpsk but not with normal skript events.

**Comment by samthecoderevamp** [comment]
Nothing happens and there are no errors in console.
