### ISSUE TITLE
do not have permission Issues

### ISSUE THREAD

**Issue by TIM31205** [SkriptLang/Skript#5655]
### Skript/Server Version

```markdown
[18:56:32 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[18:56:32 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[18:56:32 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[18:56:32 INFO]: [Skript] Server Version: git-Paper-511 (MC: 1.19.4)
[18:56:32 INFO]: [Skript] Skript Version: 2.6.4
[18:56:32 INFO]: [Skript] Installed Skript Addons:
[18:56:32 INFO]: [Skript]  - SkBee v2.8.4 (https://github.com/ShaneBeee/SkBee)
[18:56:32 INFO]: [Skript] Installed dependencies:
[18:56:32 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

(Sorry my English is not good)
When I use "do not have permission", the permission point(.↙this) will be invalid when ≧ 3

use luckperms v5.4.71

### Expected Behavior

When the player has permission, it should stop

### Steps to Reproduce

In this skript I have the essentials.sethome.multiple.two permission and it should stop, but it outputs yes!
```
command /test:
	trigger:
		player do not have permission "essentials.sethome.multiple.two"
		send "yes!" to player
```

(i have permission "ss.kk.rr.iipptt")
I also tried this and it passed
Success send "yes!"
```
command /test:
	trigger:
		player do not have permission "ss.kk.rr.iipptt" #←3 point
		send "yes!" to player
```

(i have permission "ss.kk.rr.iipptt")
This one abnormally ignores the condition and outputs "yes!"
(2 point)
```
command /test:
	trigger:
		player do not have permission "ss.kk.rriipptt" #←2 point
		send "yes!" to player
```

### Errors or Screenshots

no error message

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Can't reproduce this
![image](https://user-images.githubusercontent.com/20037329/235306809-f7b191b7-d918-4ca2-97eb-09f5b39989e5.png)
![image](https://user-images.githubusercontent.com/20037329/235307194-4c630b0f-5096-4549-9c87-176a6e3c6258.png)

**Comment by TIM31205** [comment]
Hmm... I just tested it and now the 3-point test is working again, but the essentials.sethome.multiple.four that I wanted to use is still wrong

![image](https://user-images.githubusercontent.com/51401718/235308355-b0d0f10b-8038-4be7-a907-127f13f51e6d.png)

https://user-images.githubusercontent.com/51401718/235308700-82026b48-a33a-4f9d-b527-bcf4327cf083.mp4

**Comment by AyhamAl-Ali** [comment]
This means you actually don't have the permission, it's not a Skript bug pretty sure. It's mostly user error.
Use [skUnity discord server help channels](https://discord.gg/skript) for further assitance, if proven a Skript bug let us know here with proper test cases.
