### ISSUE TITLE
Can't use 'keep inventory' or 'keep experience'

### ISSUE THREAD

**Issue by noySq** [SkriptLang/Skript#5657]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-519 (MC: 1.19.4)
[Skript] Skript Version: 2.7.0-beta2 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

It throws an error even though everything is correct

### Expected Behavior

It's supposed to work

### Steps to Reproduce

```
on death of player:
    keep inventory
    keep experience
```

### Errors or Screenshots

[Skript] Reloading test.sk...
Line 2: (test.sk)
    The keep inventory/experience effect can't be used outside of a death event
    Line: keep inventory

Line 3: (test.sk)
    The keep inventory/experience effect can't be used outside of a death event
    Line: keep experience

[Skript] Encountered 2 errors while reloading test.sk! (13ms)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
After changing how isCurrentEvent works this error started to occur due to the event being EntityDeathEvent
![image](https://user-images.githubusercontent.com/20037329/235361668-f799181f-3b04-43a0-9a0b-5b28861a5c14.png)

**Comment by WilliamPlays0402** [comment]
Any updates on this being pushed into the beta release?

**Comment by TheLimeGlass** [comment]
It won't be in 2.7.

**Comment by not-3than** [comment]
Still experiencing this bug in 2.7, any fixes?

**Comment by AyhamAl-Ali** [comment]
> Still experiencing this bug in 2.7, any fixes?

There is a fix already but not yet merged.
- #5658
