### ISSUE TITLE
EffGive | move give effect

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5670]
### Suggestion

Move the syntax for `give` out of the `EffChange` class and into a `EffGive` class

### Why?

While this is mostly going up for debates, my reasoning for this is clear.
```
(add|give) %objects% to %~objects%
give %~objects% %objects%
```
the syntax given here makes little to no sense in the fact that `give` should really only accept itemtypes.
Additionally changers have nothing in common with the give effect outside of `add` working very close with it

### Other

This change would also increase understanding this more for new users as more often than enough I have people asking "how to give diamond to player" which can easily be guessed, however it can't easily be found on docs for them.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
Recently came to my attention while using skript 2.7 that this would need to be done no matter what as this is technically unintended in my opinion
![image](https://github.com/SkriptLang/Skript/assets/81952476/64703ed2-c6ab-4af9-9ad6-40e8719db3aa)

The `give` effect is adding the input to the list variable due to it most likely taking priority of a variable

**Comment by DelayedGaming** [comment]
The pattern is `(add|give) %objects% to %objects%`, so the behaviour in the screenshot is technically correct.

**Comment by Fusezion** [comment]
> The pattern is `(add|give) %objects% to %objects%`, so the behaviour in the screenshot is technically correct.

yes ik but it's still confusing to a decent margin speaking `give` was only include in common sense just for giving an item to an entity/inventory.
Which inventory only makes sense for `add blank to inventory` not `give blank to inventory`

**Comment by Fusezion** [comment]
> 1. Add-ons may prefer this syntax over the add syntax as it may be more _consistent_ with the syntax for their expressions, thus it would be silly to _restrict_ it to itemtypes or just move it out of changers at all.

Not trying to come off as rude but could you give me a syntax that this would make sense for.


> 2\. This could be a **breaking** change if it's restricted to itemtypes as Skript users may rely on it in their code for other expression modifications.

This would be labled a breaking change

**Comment by hapily04** [comment]
> 
> Not trying to come off as rude but could you give me a syntax that this would make sense for.
> 
If, for example, there's a discord addon, syntax such as `add role from id "1000653428499959848" to member` would make more sense as `give role from id "1000653428499959848" to member`. Realistically either works, but the give syntax is more cohesive with the English language in this scenario. Nonetheless, this is not the only scenario in which an addon developer may prefer this syntax
> 
> This would be labled a breaking change
> 
Correct, however the fact that it is a breaking change at all should still be kept under steep consideration.

**Comment by Fusezion** [comment]
Closing this issue of mine, since thinking over this and the examples given to me this is pretty pointless
