### ISSUE TITLE
Cannot use event-item in on book sign

### ISSUE THREAD

**Issue by WizardWoodland** [SkriptLang/Skript#5671]
### Skript/Server Version

```markdown
2.6.4
```

### Bug Description

If book is in offhand, event-item result will be "air"

### Expected Behavior

get written book or writable book item value

### Steps to Reproduce

different types of writting
it doesn't work

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Can you provide your script code used to replicate the issue?

**Comment by TheLimeGlass** [comment]
`2.7.0-beta2

```
[21:53:36 INFO]: Line 113: (blockhunt.sk)
[21:53:36 INFO]:     There's no item stack in an on book sign event
[21:53:36 INFO]:     Line: broadcast "%event-item%"
```
```
on book sign:
    broadcast "%event-item%"
```
