### ISSUE TITLE
EvtItemDamage - Enhancements

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5677]
### Suggestion

Add support for `damage` within the event to modify the amount done
~~Add support for editing the damaged item, skript doesn't support changers modifying the item directly
but addons like SkBee's nbt is able to~~

### Why?

Isn't currently supported, making it feel sorta pointless

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
>  Add support for editing the damaged item, skript doesn't support changers modifying the item directly
Please open another issue for that
