### ISSUE TITLE
NBT-based ItemTypes are not properly compared on 2.7

### ISSUE THREAD

**Issue by sovdeeth** [SkriptLang/Skript#5693]
### Skript/Server Version

```markdown
[17:09:11 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:09:11 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[17:09:11 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[17:09:11 INFO]: [Skript] Server Version: git-Paper-471 (MC: 1.19.4)
[17:09:11 INFO]: [Skript] Skript Version: 2.7.0-dev-nightly-ef9f3ee7 (skriptlang-nightly)
[17:09:11 INFO]: [Skript] Installed Skript Addons: None
[17:09:11 INFO]: [Skript] Installed dependencies:
[17:09:11 INFO]: [Skript]  - WorldGuard v7.0.8-beta-01+cbb2ba7

(This is a nightly of the current master branch, but I also tested on 2.7-beta2)
```

### Bug Description

ItemTypes that rely on NBT tags (itemmeta?), like potions, tipped arrows, goat horns, and fireworks do not seem to work in comparisons. Any potion is considered to be a `fire resistance potion`, or a `water bottle`, no matter its true effect.

### Expected Behavior

These aliases should behave properly in item comparisons. Fire resistance potions are not strength potions.

### Steps to Reproduce

```
command /test-potions:
    trigger:
        set {_fire-resist} to type of potion of fire resistance
        set {_water-breathing} to type of water breathing potion
        set {_water-bottle} to type of water bottle
        send "%{_fire-resist}% is %{_fire-resist}%: %true if {_fire-resist} is {_fire-resist} else false%"
        send "%{_fire-resist}% is %{_water-breathing}%: %true if {_fire-resist} is {_water-breathing} else false%"
        send "%{_fire-resist}% is %{_water-bottle}%: %true if {_fire-resist} is {_water-bottle} else false%"
        send "%{_water-bottle}% is %{_water-breathing}%: %true if {_water-bottle} is {_water-breathing} else false%"
```

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/10354869/df888953-acf9-4287-a2b5-cc76572d0616)

### Other

Notably, removing `type of` seems to make everything work. However, this impacts things like `if tool is a water bottle`.
### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
what's the nightly? the comparison of 2 literals?

**Comment by sovdeeth** [comment]
> what's the nightly? the comparison of 2 literals?

The current master branch, like I said.

**Comment by Fusezion** [comment]
Seems to be non literals only also
![image](https://github.com/SkriptLang/Skript/assets/81952476/d7dce3ab-c617-41bb-a2dc-767f5181efdf)

**Comment by sovdeeth** [comment]
> Seems to be non literals only also ![image](https://user-images.githubusercontent.com/81952476/238101553-d7dce3ab-c617-41bb-a2dc-767f5181efdf.png)
> 
> Retest using literals ![image](https://user-images.githubusercontent.com/81952476/238101763-f080a454-5a46-4e81-840f-4a10c2a5406d.png)

Yes that's what I was trying to get across in the `Other` section.
