### ISSUE TITLE
Many visual effect issues

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#571]
Hello.

I was testing visual effects to test the issues submitted in #567, and while they do work for the most part, I came across a couple of other issues that are laid out here:

1. It appears the 'extra parameters' of all visual effects -- that being the offset and speed -- don't properly accept floating point values, which are interpreted as zero. I'm not sure if this is the fault of Skript of EffectLib, but it certainly isn't the case in vanilla, as the offset and speed values can certainly accept floating point values for granular control.
2. Sending any item break particle immediately kicks the client with an error (the server does not crash and is unaffected otherwise).
3. A number of visual effect particles don't support the speed or offset arguments at all; when passed in on their own they work fine, but when adding these extra parameters, [a `(No specific information available)` error is returned](https://gyazo.com/fcd4c05c12297ab5513cb307aa555961) and nothing happens.
4. Playing any colored dust ([using the syntax found from the lang file in this gist](https://gist.github.com/bensku/834e7bf666eb995e53d456c21ecc1e0e)) works, but always plays red dust, while playing any potion swirl plays the black one regardless of the color provided.

## Testing

Here's a script I made up to test some of these issues:
```
command /testeffects:
	trigger:
		send "&6Playing oak wood with offset 1, 1, 1 and speed 1"
		play 100 (dust of oak wood with offset of 1, 1, 1 and speed 1) at player
		
		wait 2 seconds

		send "&6Playing oak wood with offset 0, 0, 0 and speed 0"
		play 100 (dust of oak wood with offset of 0, 0, 0 and speed 0) at player
		
		wait 2 seconds
		
		send "&6Playing oak wood with offset 1.5, 1.5, 1.5 and speed 1"
		play 100 (dust of oak wood with offset of 1.5, 1.5, 1.5 and speed 1) at player
		
		wait 2 seconds
		
		send "&6Playing oak wood with offset 1, 1, 1 and speed 1.5"
		play 100 (dust of oak wood with offset of 1, 1, 1 and speed 1.5) at player
		
		wait 2 seconds
		
		send "&6Playing oak wood with offset 1.5, 1.5, 1.5 and speed 1.5"
		play 100 (dust of oak wood with offset of 1.5, 1.5, 1.5 and speed 1.5) at player
		
		wait 2 seconds
		
		send "&6Playing diamond sword item break"
		play 100 diamond sword item break at player
```

And [here's a video of the result](https://gyazo.com/477f36d225f42712c91701b3311ef938). You can see that in none of the instances where the offset is non-integral does it actually use the offset properly (it just uses it as if it's 0, 0, 0), nor do any of the floating point speeds work, instead just having the particles drop to the floor with no speed. [Here's a screenshot](https://gyazo.com/aa3f809dd82640674ffe3f975a6563f9) of the final error upon kicking so you can see it better, and here's what's sent to console:

```
[14:29:18 INFO]: Mr_Simba [6d000b39-6ebd-42c2-a95a-b3923d87d392]: /testeffects
[14:29:23 ERROR]: java.lang.ArrayIndexOutOfBoundsException: 1
[14:29:23 INFO]: Mr_Simba lost connection: Disconnected
```

Some effect commands you can use to test the others as well, for easy copying:

```
play 100 red dust at player
play 100 green dust at player
play 100 blue dust at player
play 100 black dust at player

play 100 red potion swirl at player
play 100 green potion swirl at player
play 100 blue potion swirl at player
play 100 black potion swirl at player
```

## Setup
- Spigot 1.11.2
- Skript dev27
- No addons

**Comment by Snow-Pyon** [comment]
My brother has reported something related in the issue #182 where bnsku said that he may try again (it was 7 months ago so I don't really know if bensku is planning on fix this anytime soon as it doesn't seem something that could be easily fixed).

**Comment by TheBentoBox** [comment]
Yeah, these are related, that one isn't entirely correct on the context in which everything occurs, but it's rooted in the same issues. I hope at the very least the offset and speed issues (where floating point numbers don't work) could probably be fixed even if the other issues are more difficult.

**Comment by bensku** [comment]
I might try to do thia again with Spigot particle API as it currently works with EffectLib or ols Bukkit particles. Last time I tried, Spigot particles were mostly unusable due to bugs, but maybe I'll take a look again.

Colors are bugged, as Bukkit effect API doesn't support them. EffectLib has/had color support, but on the end it still played only red sparks.

**Comment by Sashie** [comment]
hmmm

**Comment by Sashie** [comment]
in my experience there is a way to do it but its a pain regardless

**Comment by bensku** [comment]
I fixed colored dust particles. Apparently I needed to 1) have particle speed exactly 1 2) have RGB in range 0...1 and 3) use count zero (wait what?).

**Comment by TheBentoBox** [comment]
That's obnoxious, but at least you got it working.

**Comment by bensku** [comment]
Oops. Actually, I didn't probably fix everything here...

**Comment by Sashie** [comment]
lel i know exactly how you feel xD maybe some day ill help you with the particle system

**Comment by FranKusmiruk** [comment]
How much of this is still an issue?
