### ISSUE TITLE
Clear entities from variable conflict

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#5716]
### Suggestion

Currently if you store entities in a variable and attempt to clear that list variable. It will clear the variable and lose reference to the entity, when in reality I would be trying to clear the entity from the world.

```
clear {_entities::*}
```

There needs to be a syntax to distinguish between clearing the variable and the entity.
Something like `clear entit(y|ies) %entities%` maybe

You cannot loop the list variable and clear the loop-value. Maybe that should also be a suggestion since it should know it's type.

### Why?

Losing reference of an entity is bad. This is why I always request changes in pull requests to be clearing the entity in the EffSecSpawn section, as it clears the reference to the entity directly, and not just the variable, leaving entities remaining in the world (Which is bad for our test environment)

### Other

Any other ideal solutions can be discussed in this issue.

Placing as LOW priority instead of LOWEST as this is kinda a bigger issue.

A solution currently is to be using metadata but that requires looping all entities and comparing if that entity has metadata when clearing. Very inefficient.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
Wasn't one added for 2.7 values of or smth

**Comment by Fusezion** [comment]
> Wasn't one added for 2.7 values of or smth

https://docs.skriptlang.org/docs.html?search=#ExprValueWithin
Found it, here it is

**Comment by UnderscoreTud** [comment]
That's what #5198 aimed to fix. I am closing this as completed
