### ISSUE TITLE
Abnormal Error for event-chunk

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#5720]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-477 (MC: 1.19.4)
[Skript] Skript Version: 2.7.0-beta2 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

When using `event-chunk` directly in a chunk event, it throws a duplicated and unintended error.
This error does not throw when the chunk is saved into a variable then use that variable.

### Expected Behavior

It should not throw and duplicate error.

### Steps to Reproduce

Use and reload this script used on this issue:
```v
on chunk load:
    set {_c} to event-chunk
    set {_e::*} to entities in {_c}
    set {_e::*} to entities in event-chunk

on chunk unload:
    set {_c} to event-chunk
    set {_e::*} to entities in {_c}
    set {_e::*} to entities in event-chunk
```

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/72163224/ef2e248a-e2de-423c-a559-0705ca4499a9)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
I don't believe entities supports `in` in the syntax.

**Comment by DelayedGaming** [comment]
That doesn’t explain why Line 4 and 9 in the screenshot doesn’t error.

**Comment by sovdeeth** [comment]
Closing in favour of 6005
