### ISSUE TITLE
on click event change

### ISSUE THREAD

**Issue by ScienceKit** [SkriptLang/Skript#5725]
### Suggestion

So currently the on click trigger surprisingly, does not use %click types% instead it uses its own argument in both patterns:
![image](https://github.com/SkriptLang/Skript/assets/127025473/ecdd8bb0-17e1-4147-897e-d95297c8dfe6)

### Why?

If this is added, you could be able to directly detect button presses like the offhand button, spacebar and the whole assortment of buttons 1-9.

### Other

I was asked to leave the link to the Javadoc, so here:
https://docs.skriptlang.org/javadocs/

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
the `on click` event is a PlayerInteractEvent and not an InventoryClickEvent. You use `on inventory click` to use `click type`
