### ISSUE TITLE
Creating timing - this is deprecated behavior Paper issue

### ISSUE THREAD

**Issue by AKtomik** [SkriptLang/Skript#5726]
### Skript/Server Version

```markdown
[INFO] [Skript] Server Version: git-Paper-538 (MC: 1.19.4)
[INFO] [Skript] Skript Version: 2.6.4
[INFO] [Skript] Installed Skript Addons: None
[INFO] [Skript] Installed dependencies:
[INFO] [Skript] - WorldGuard v7.0.7+216b061
```

### Bug Description

An warn from the server when using the `wait` expresssions.
```
Plugin 'Skript' is creating timing '<script>: line <line of the trigger>' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
```
So its spamming the console and make it undreadeble (whit all my scripts on, the console is so spammed that its cant be logged), but that not the most imortant, because if a error is here, its the mening of a deeper problem, and that not a good news.
"this is deprecated behavior, **please report it**"
Why im here now.

### Expected Behavior

No error in the console, and `wait` expression compatible with the server.

### Steps to Reproduce

Using one of the last paper version (538), the last stable version of skript (2.6.4) and use the `wait` expressions to get this warn.

### Errors or Screenshots

So, here a script using the `wait` expressions in two differents sections:
```
on load:
	send "will wait" to the console
	wait 1 ticks
	send "has wait" to the console
every 10 second:
	send "every event" to the console
	wait 1 tick
	send "every event 2" to the console
```
What's happening in the console using this script:
```
[09:45:49] [INFO] [Skript] Reloading Test.sk...
[09:45:49] [INFO] will wait
[09:45:49] [INFO] [Skript] Successfully reloaded Test.sk. (3ms)
[09:45:49] [WARN] Plugin 'Skript' is creating timing 'Test.sk: line 1' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
[09:45:49] [INFO] has wait
[09:45:59] [INFO] every event
[09:45:59] [WARN] Plugin 'Skript' is creating timing 'Test.sk: line 5' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
[09:45:59] [INFO] every event 2
```

### Other

no.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
We're aware of this Paper exclusive issue, it's just a warning and we do plan on addressing it.
