### ISSUE TITLE
Slight visual error with /sk enable

### ISSUE THREAD

**Issue by veeonthewall** [SkriptLang/Skript#5728]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here:
nitips//github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here:
nitps://doos.shripilang.org/
[Skript] Skript's tutorials can be found here:
nttps://doss/skriptlang.org/tutorials
[Skript] Server Version: git-Paper-538 (MC: 1.19.4)
[Skript] Skript Version: 2.6.4
[Skript] Installed Skript Addons:
[Skript] - skript-reflect v2.3 (https://github.com/TPOamesNL/skript-reflect)
[Skript] - SkBee v2.9.0 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies:
[Skript] - Vault v1.73-6131
```

### Bug Description

Wrong color is used for the line "[Skript] Encountered 1 error while reloading (insert skript).sk!", when an error is present in a file about to be enabled with /sk enable.

### Expected Behavior

The color should be &c, not &4.

### Steps to Reproduce

Create an sk file

Type a line that will throw an error

Disable the sk file

Type /sk enable <skript file>

### Errors or Screenshots

<img width="404" alt="Screen Shot 2023-06-02 at 10 47 19 AM" src="https://github.com/SkriptLang/Skript/assets/105337781/0a9a604c-edf8-470e-adb9-0fd3655ecdea">

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Colors were updated only for reloading 😬 
Enabling/Disabling need updating too
https://github.com/SkriptLang/Skript/blob/baf5bdd5671cfa085e5892f1f5b59304caa096f3/src/main/resources/lang/english.lang#L83

**Comment by SlimeDog** [comment]
Paper 1.20.1-21 staunched the bleeding.
https://github.com/PaperMC/Paper/pull/9346
