### ISSUE TITLE
Missing enum error can be displayed twice or thrice 

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#5743]
### Skript/Server Version

```markdown
2.7.0-beta3
1.20 Paper
```

### Bug Description

When missing an enum from the default.lang, an error will be displayed that it is missing, but that error can sometimes be printed up to two or even three times consecutively.

### Expected Behavior

This should not be the case, the error should only print once for each missing enum, no duplicates. There is most likely a for loop that is not being continued or returned when the error happens.

### Steps to Reproduce

Remove an enum value from the default.lang

### Errors or Screenshots

See https://github.com/SkriptLang/Skript/issues/5740 for how it gets printed.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
This is an issue with the EnumUtils validation. I probably broke it during my one PR that added gender support. I'll assign this issue to myself and have a PR fix soon :)
