### ISSUE TITLE
When you do "on inventory click: cancel event" you can duplicate items.

### ISSUE THREAD

**Issue by JeffreyRCGithub** [SkriptLang/Skript#5749]
### Skript/Server Version

```markdown
So, when you want to disable clicking items you obviously try:
on inventory click:
cancel event
But when you click on that item it duplicates the item.
```

### Bug Description

I found a duplication bug.

### Expected Behavior

It is supposed to not duplicate the item and stop it from clicking the item.

### Steps to Reproduce

Add this code to a skript:
on inventory click:
cancel event
Now there is a duplication glitch.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Are you in creative mode? Are the items real or just ghost items? What's your skript and server info?

**Comment by JeffreyRCGithub** [comment]
Oh, this only happens when you’re in creative mode. Thanks for the help!
