### ISSUE TITLE
on Skript start / on script load does not fire when the server turns on.

### ISSUE THREAD

**Issue by WilliamPlays0402** [SkriptLang/Skript#5754]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-540 (MC: 1.19.4)
[Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[Skript] Installed Skript Addons:
[Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net) 
[Skript]  - SkQuery v4.1.9
[Skript]  - SkBee v2.9.0 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: None
```

### Bug Description

This bug appeared, along with the `on death of player: keep items and experience` bug in 2.7.0.
When the server starts, it does not fire any `on script load` or `on Skript start` events (afaik), however `on script load` events continue to work when reloading the file.

This can be frustrating to many people, myself included, as I require some scripts to run only when the server starts (e.g. the below example code is supposed to keep track of the server ontime, whilst it currently requires an admin to reset the server ontime by reloading the script)

### Expected Behavior

The event triggers code.

### Steps to Reproduce

1. Download Skript 2.7.0-beta-3 & make a Paper server v540 (1.19.4)
2. Make a file (index.sk)
3. Paste following code into the file.

```
on script load:
  set {serverOnTime::s} to 0
  set {serverOnTime::m} to 0
  set {serverOnTime::h} to 0

every second:
  add 1 to {serverOnTime::s}
  if {serverOnTime::s} is greater than 59:
    set {serverOnTime::s} to 0
    add 1 to {serverOnTime::m}
  if {serverOnTime::m} is greater than 59:
    set {serverOnTime::m} to 0
    add 1 to {serverOnTime::h}

command /test:
  trigger:
    send "%{serverOnTime::h}%:%{serverOnTime::m}%:%{serverOnTime::s}%"
```

4. Reload the file
5. Wait a minute or two...
6. Run /test.
7. Note the server runtime.
8. Restart the server, quickly join it, and see that the time stayed the same (did not go back down to 0:0:0)
9. Reload the file
10. Note the time dropped back down to 0:0:0

### Errors or Screenshots

There are no errors in chat.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
I use `on script load` frequently for the testing system, they do indeed execute properly.

This may be variable related.

**Comment by WilliamPlays0402** [comment]
Hmm, very odd indeed... I will do some tests later, when I get the chance.

**Comment by sovdeeth** [comment]
Oh just so it's here too, i did a little investigating about it on the discord:
![image](https://github.com/SkriptLang/Skript/assets/10354869/132ab73f-e6b4-41f7-947d-f79306776e68)

**Comment by sovdeeth** [comment]
Related to #5882?

**Comment by AyhamAl-Ali** [comment]
> Related to #5882?

Yes

**Comment by AyhamAl-Ali** [comment]
Closing this issue due to #5882 (better detailed)
