### ISSUE TITLE
Cannot get ANY inventory in Death Event

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/Skript#5755]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-43 (MC: 1.20.1)
[Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[Skript] Installed Skript Addons:
[Skript]  - skript-reflect v2.3.1-for-skript-beta (https://github.com/TPGamesNL/skript-reflect)
[Skript] Installed dependencies: None
```

### Bug Description

Cannot get ANY inventory in Death Event

### Expected Behavior

get Inventory

### Steps to Reproduce

Codes (Within skript-reflect):
```
on death:
	if metadata value "Testing" of victim is set:
		broadcast "%(attacker).getClass()%"
		broadcast "%(victim).getClass()%"
		broadcast "%(inventory of attacker).getClass()%"
		broadcast "%(inventory of victim).getClass()%"
```

Results:
![1YHIWYOG(0%`PI 7~14KQC5](https://github.com/SkriptLang/Skript/assets/50171612/d80e9532-f510-40f2-aa4e-8bd321e8e5d0)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by 0XPYEX0** [comment]
By doing same thing in EFFECT COMMAND, it works well:
![08MERW52K`HJQ10133UUS08](https://github.com/SkriptLang/Skript/assets/50171612/ea83b31f-ab05-4190-bea2-8b5e221f9f0b)

**Comment by 0XPYEX0** [comment]
Some entities does not have its own inventory
But PLAYER must have, and it returns null in Death Event
![1MBX$9%}}2GC9H BXK8C6XV](https://github.com/SkriptLang/Skript/assets/50171612/d1b8fe25-2030-4a47-b280-6b05b3b4ec24)
I think we can get inventories of LivingEntities :)

**Comment by TheLimeGlass** [comment]
The player is dead, they have no inventory unless keep inventory is enabled.

Placing this issue into a suggestion to implement a warning for this exact situation.

**Comment by 0XPYEX0** [comment]
> The player is dead, they have no inventory unless keep inventory is enabled.
> 
> Use the `on damage` event and check if the `final damage` is going to be greater than or equal to the health of the player to then get their inventory, or enable keep inventory.
> 
> Placing this issue into a suggestion to implement a warning for this exact situation.

You may not understand
The ATTACKER is a Player
The player did NOT die

**Comment by 0XPYEX0** [comment]
By the way, in the Death Event
set {_i::*} to items of attacker  →  works well
set {_i::*} to items of inventory of attacker  →  null

**Comment by madebygood** [comment]
Upon death, both victim and attacker lose control of all their items, so why is this the lowest priority?

This is a bug that needs to be resolved with the highest priority.

This is a serious situation where it is impossible to set any items on death.

**Comment by NiaSwift** [comment]
I had the same problem and I found a silly way to make it work:
```
on death of player:
    set {_p} to victim
    broadcast "%{_p}'s inventory%"
```
