### ISSUE TITLE
Use Variable lists in the config over variables with .

### ISSUE THREAD

**Issue by PublicJake** [SkriptLang/Skript#5784]
### Suggestion

Changing line 88 and 89 of the config to use lists over periods.

```
use player UUIDs in variable names: false
# Whether to use a player's UUID instead of their name in variables, e.g. {home.%player%} will look like
# {home.e5240337-a4a2-39dd-8ed9-e5ce729a8522} instead of {home.njol}.
# Please note that if this setting is changed old variables WILL NOT be renamed automatically.
```

```
use player UUIDs in variable names: false
-># Whether to use a player's UUID instead of their name in variables, e.g. {home::%player%} will look like
-># {home::e5240337-a4a2-39dd-8ed9-e5ce729a8522} instead of {home::njol}.
# Please note that if this setting is changed old variables WILL NOT be renamed automatically.
```

### Why?

Using dots in variables is a pretty old practice and should be replaced with lists in all cases, promoting them in the config doesn't sound like the best of ideas.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
This is already done in https://github.com/SkriptLang/Skript/pull/4837
Your config is probably just old.
