### ISSUE TITLE
No event-slot in Tool Change Event

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#5786]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-477 (MC: 1.19.4)
[Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

`event-slot` can't be used in an `on tool change` event.

### Expected Behavior

`event-slot` can be used in an `on tool change` event.

### Steps to Reproduce

Use `event-slot` in an `on tool change` event, like so:
```py
on tool change:
    send past event-slot
    send event-slot
```

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/72163224/4b78ddd2-fda4-4e02-8134-18adbbbf2f63)

### Other
`event-slot` is registered, so I am unsure where did the issue come from.
![image](https://github.com/SkriptLang/Skript/assets/72163224/2ede17cf-541d-45de-9aa6-9cd59dc819e4)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
These values are not yet in a released version, as they were added after beta3 (see https://github.com/SkriptLang/Skript/pull/5271).

**Comment by CirrusPreeminent** [comment]
I still have the same issue on skript version 2.7.3

![image](https://github.com/SkriptLang/Skript/assets/153276550/6c4e70e9-ec64-4e3a-9195-08fa04c8132d)

```on player's tool change:
    send "%past event-slot%"```
    
    have try with all combination "past event-slot", "past event-item", "past player's tool" with all of the event name "on player's tool change" , "on player's held item change", "on tool change". Still no luck..
