### ISSUE TITLE
I fall throguth the world when i load a certain script

### ISSUE THREAD

**Issue by BryanThePotato** [SkriptLang/Skript#5788]
### Skript/Server Version

```markdown
[19:48:09 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[19:48:09 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[19:48:09 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[19:48:09 INFO]: [Skript] Server Version: git-Paper-17 (MC: 1.20)
[19:48:09 INFO]: [Skript] Skript Version: 2.6.4
[19:48:09 INFO]: [Skript] Installed Skript Addons: 
[19:48:09 INFO]: [Skript]  - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
[19:48:09 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[19:48:09 INFO]: [Skript]  - SkBee v2.14.0 (https://github.com/ShaneBeee/SkBee)
[19:48:09 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

I joined my minecraft server and when i logged in, it made me fall forever, and when i turn off the skript it doesent do that anymore

### Expected Behavior

I was expecting to join my server and play minecraft with a mana bar, but instead i got sent to the void realm

### Steps to Reproduce

im using this skript that a guy gave me, it doesent have any problems on his server but does on mine im unsure of why
but it might not be reproduceable
`on load:
	set {manaVisual::0} to "&c||||||||||"
	set {manaVisual::1} to "&b|&c|||||||||"
	set {manaVisual::2} to "&b||&c||||||||"
	set {manaVisual::3} to "&b|||&c|||||||"
	set {manaVisual::4} to "&b||||&c||||||"
	set {manaVisual::5} to "&b|||||&c|||||"
	set {manaVisual::6} to "&b||||||&c||||"
	set {manaVisual::7} to "&b|||||||&c|||"
	set {manaVisual::8} to "&b||||||||&c||"
	set {manaVisual::9} to "&b|||||||||&c|"
	set {manaVisual::10} to "&b||||||||||"

on join:
	while player is online:
		add 1 to {mana::%player's uuid%}
		wait 0.3 seconds

command /manafill <offline player>:
	permission: mana.fill
	trigger:
		set {mana::%arg-1's uuid% } to 10

on join:
	while player is online:
		send action bar "&bMana: %{manaVisual::%{mana::%player's uuid%}%} ? {manaVisual::20}%"  to player`

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/102700299/d6b60da7-1853-4c70-a787-e92eadfeddbb)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
You're likely crashing the server with the following code:
```
on join:
while player is online:
send action bar "&bMana: %{manaVisual::%{mana::%player's uuid%}%} ? {manaVisual::20}%" to player
```
You need to include some sort of delay. However, GitHub is not the place for script support, so I would recommend reaching out somewhere like the SkUnity discord if you require further assistance :)

**Comment by BryanThePotato** [comment]
The sk unity discord had said to come here

**Comment by BryanThePotato** [comment]
![image](https://github.com/SkriptLang/Skript/assets/102700299/29744f2f-734d-4573-957c-ccedf3812b5c)

**Comment by APickledWalrus** [comment]
The issue is because you do not have a delay on your while loop (the code I cited above). It should resolve if you add one :)

**Comment by BryanThePotato** [comment]
> You're likely crashing the server with the following code:
> 
> ```
> on join:
> while player is online:
> send action bar "&bMana: %{manaVisual::%{mana::%player's uuid%}%} ? {manaVisual::20}%" to player
> ```
> 
> You need to include some sort of delay. However, GitHub is not the place for script support, so I would recommend reaching out somewhere like the SkUnity discord if you require further assistance :)

where should i put said delay?

**Comment by BryanThePotato** [comment]
ok thanks!

**Comment by BryanThePotato** [comment]
> 

this has caused a new issue, 

on join:
	while player is online:
		send action bar "&bMana: %{manaVisual::%{mana::%player's uuid%}%} ? {manaVisual::20}%"  to player
		**wait 5 ticks**
		
i added the wait 5 ticks line but now it doesent work. 
![image](https://github.com/SkriptLang/Skript/assets/102700299/416c5b2f-9dcd-4b31-98c9-f29195a37d48)

**Comment by APickledWalrus** [comment]
As I mentioned above, we don't offer script support on the Discord, so you should reach back out on somewhere like the SkUnity discord.
