### ISSUE TITLE
Error with stop sound

### ISSUE THREAD

**Issue by jugandomiguel** [SkriptLang/Skript#5818]
### Skript/Server Version

```markdown
[INFO] ....>.... [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases

[INFO] .... [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/

[INFO] .... [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials

[INFO] .... [Skript] Server Version: git-Paper-69 (MC: 1.20.1)

[INFO] .... [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)

[INFO] .... [Skript] Installed Skript Addons: None

[INFO] .... [Skript] Installed dependencies: None
```

### Bug Description

Console error

### Expected Behavior

Play a random sound, but when it call the function create chair it don't work

### Steps to Reproduce

Here's the code that maked the error
function startGame():
  teleport all players to location(0.5, 4, 0.5, world "flat")
  send title "Bienvenidos al!" with subtitle "Juego de las Sillas" to all players
  createChair(random integer between 1 and 4)

function createChair(song: number):
  if {_song} = 1:
    play sound "chairgames_songs:song.bloody_ass_shoes" at location(0.5, 4, 0.5, world "flat")
    send action bar "&bPlaying: &7Bloody Ass Shoes" to all players
    wait a random number between 10 and 20
    stop all sound for all players
  else if {_song} = 2:
    play sound "chairgames_songs:song.money_on_the_dash" at location(0.5, 4, 0.5, world "flat")
    send action bar "&bPlaying: &7Money on the Dash" to all players
    wait a random number between 10 and 20
    stop all sound for all players    
  else if {_song} = 3:
    play sound "chairgames_songs:song.push_up" at location(0.5, 4, 0.5, world "flat")
    send action bar "&bPlaying: &7Push Up" to all players
    wait a random number between 10 and 20
    stop all sound for all players    
  else if {_song} = 4:
    play sound "chairgames_songs:song.sun_is_dark" at location(0.5, 4, 0.5, world "flat")
    send action bar "&bPlaying: &7Sun is Dark" to all players
    wait a random number between 10 and 20
    stop all sound for all players

### Errors or Screenshots

[INFO] ....>.... [Skript] Reloading chairgame.sk...

[ERROR] .... #!#!

[ERROR] .... #!#! [Skript] Severe Error:

[ERROR] .... #!#! An error occurred while trying to load a Structure.

[ERROR] .... #!#!

[ERROR] .... #!#! Something went horribly wrong with Skript.

[ERROR] .... #!#! This issue is NOT your fault! You probably can't fix it yourself, either.

[ERROR] .... #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).

[ERROR] .... #!#! This ensures that your issue is noticed and will be fixed as soon as possible.

[ERROR] .... #!#!

[ERROR] .... #!#! Stack trace:

[ERROR] .... #!#! ch.njol.skript.SkriptAPIException: The class 'string' does not provide a default expression. Either allow null (with %-string%) or make it mandatory [pattern: stop (all:all sound[s]|sound[s] %strings%) [(in|from) %-soundcategory%] [(from playing to|for) %players%]]

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:923)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:225)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Section.init(Section.java:69)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:179)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:212)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Section.parse(Section.java:178)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:943)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:47)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:124)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.structures.StructFunction.load(StructFunction.java:97)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:555)

[ERROR] .... #!#! at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)

[ERROR] .... #!#! at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:551)

[ERROR] .... #!#! at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)

[ERROR] .... #!#! at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)

[ERROR] .... #!#! at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)

[ERROR] .... #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:190)

[ERROR] .... #!#! at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)

[ERROR] .... #!#! at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)

[ERROR] .... #!#! at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1006)

[ERROR] .... #!#! at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:969)

[ERROR] .... #!#! at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:501)

[ERROR] .... #!#! at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)

[ERROR] .... #!#! at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)

[ERROR] .... #!#! at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)

[ERROR] .... #!#! at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)

[ERROR] .... #!#! at java.base/java.lang.Thread.run(Thread.java:1589)

[ERROR] .... #!#!

[ERROR] .... #!#! Version Information:

[ERROR] .... #!#! Skript: 2.7.0-beta3 (latest)

[ERROR] .... #!#! Flavor: skriptlang-github

[ERROR] .... #!#! Date: 03:18:03.366646700

[ERROR] .... #!#! Bukkit: 1.20.1-R0.1-SNAPSHOT

[ERROR] .... #!#! Minecraft: 1.20.1

[ERROR] .... #!#! Java: 19.0.2 (Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44)

[ERROR] .... #!#! OS: Linux amd64 5.15.0-60-generic

[ERROR] .... #!#!

[ERROR] .... #!#! Server platform: Paper

[ERROR] .... #!#!

[ERROR] .... #!#! Current node: stop all sound for all players (chairgame.sk, line 97)

[ERROR] .... #!#! Current item: null

[ERROR] .... #!#!

[ERROR] .... #!#! Thread: Server thread

[ERROR] .... #!#!

[ERROR] .... #!#! Language: english

[ERROR] .... #!#! Link parse mode: DISABLED

[ERROR] .... #!#!

[ERROR] .... #!#! End of Error.

[ERROR] .... #!#!

[INFO] .... [Skript] Successfully reloaded chairgame.sk. (68ms)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Duplicate completed https://github.com/SkriptLang/Skript/issues/5756
