### ISSUE TITLE
On inventory click does not trigger with all click types.

### ISSUE THREAD

**Issue by GibsonGYIOVdguisdo** [SkriptLang/Skript#5820]
### Skript/Server Version

```markdown
[14:43:45 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:43:45 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:43:45 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:43:45 INFO]: [Skript] Server Version: git-Paper-71 (MC: 1.20.1)
[14:43:45 INFO]: [Skript] Skript Version: 2.6.4
[14:43:45 INFO]: [Skript] Installed Skript Addons: None
[14:43:45 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

When click and dragging the inventory click event does not get triggered.

Video of bug happening:
https://github.com/SkriptLang/Skript/assets/114831858/83c13d98-8019-4b71-9415-01727cd4d024

### Expected Behavior

The inventory click event should be triggered.

### Steps to Reproduce

`on inventory click:`
`    if event-inventory is chest inventory:`
`        cancel event`
`        broadcast "%event-inventory%"`
`        broadcast "%inventory action%"`

### Other

Additionally, the event sometimes does not get triggered when you spam-click an item into the inventory.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment]
Try `a chest inventory`. Just some Skript comparison moment as with that syntax you’re comparing an inventory with a non existent inventory.

**Comment by Fusezion** [comment]
> Try `a chest inventory`. Just some Skript comparison moment as with that syntax you’re comparing an inventory with a non existent inventory.

skript should have a comparator for inventory to inventory type, so honestly shouldn't have this issue I believe.
https://github.com/SkriptLang/Skript/blob/5a44852ebbb6243f9b211d4f7880fd65ba0315b4/src/main/java/ch/njol/skript/classes/data/DefaultComparators.java#L607-L610

**Comment by TheLimeGlass** [comment]
Spigot has the inventory click and inventory drag as separate events.
