### ISSUE TITLE
Add support for EntityTeleportEvent

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#5825]
### Suggestion

Add support for EntityTeleportEvent which is like enderman, shulkers etc

### Why?

There is no support for this yet.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by DelayedGaming** [comment]
EntityTeleportEvent and PlayerTeleportEvent are 2 separate teleport events, and neither of them inherits the other. Looks like we have to handle both events in one syntax.
