### ISSUE TITLE
Dynamic function calls

### ISSUE THREAD

**Issue by ahmadMsaleem** [SkriptLang/Skript#5838]
### Suggestion

``(execute|call) function [named|with name] %string% [(with|using) argument[s] %-objects%]``
``call function named {_myRandomFunction} with arguments {_listArguments::*}``

### Why?

skript need a propar why to call dynmic functions. Using variables, you will be able to call a function from anywhere 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
The only issue that I can see with argument calls is when the function takes in a list so `String, Items, Boolean`
items will most likely only accept 1 unless we do the system `parse as "my %items%"` does where it's `{blah::1::*}`

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/1265
