### ISSUE TITLE
💡Adding `player(name: string)` function

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#5842]
### Suggestion

Adding `player(name: string, online: boolean = false)` function which returns OfflinePlayer by default unless {_online} is true it would return Player instance (online), this is a bit easier than `"SkriptDev" parsed as player`

### Why?

Easier, doesn't exist

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
Great idea, ayham!

**Comment by ahmadMsaleem** [comment]
``isOnline()`` instead of ``player()``

**Comment by sovdeeth** [comment]
> ``isOnline()`` instead of ``player()``

No, it returns a player, not a boolean
