### ISSUE TITLE
the plugin is not working

### ISSUE THREAD

**Issue by larrygaming019** [SkriptLang/Skript#5851]
### Skript/Server Version

```markdown
the plugin version is V2.1.2, the server version is 1.20.1!
```

### Bug Description

so i checked in the console, and it says red about skript. it says plugin disabled! im so sad! i just want it to start! please help to get the plugin to work :((((((

### Expected Behavior

that i was adding autopickup skript to it and it would work.

### Steps to Reproduce

i just installed it and it doesnt work. it may be server version, but idk!!!!!

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/140148151/511c334c-04af-4c15-b91f-a7af5f208795)

### Other

just please try and make it fixed. :((((

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Version 2.1.2 is 8+ years old. We do not support that version. SkriptLang is only MC 1.13+. Please download the latest stable version or beta at https://github.com/SkriptLang/Skript/releases
