### ISSUE TITLE
Bug to subtract with a variable from players's balance not working

### ISSUE THREAD

**Issue by Cebix4k** [SkriptLang/Skript#5858]
### Skript/Server Version

```markdown
My Server is running on paper 1.20.1
with lastet script version 2.7.0 (Beta)
```

### Bug Description

```markdown
command /debugbank [<text>]:
	trigger:
		set {payinok.%player%} to arg-1
		subtract {payinok.%player%} from player's money
		send "&cDEBUG: %{payinok.%player%}% &8| &c%player's money%"`

this method to remove the money from balance is not working
```

Changing the arg-1 to a normal var
is this working again 

```markdown
command /debugbank [<text>]:
	trigger:
		set {payinok.%player%} to 100
		subtract {payinok.%player%} from player's money
		send "&cDEBUG: %{payinok.%player%}% &8| &c%player's money%"
```

Fun fact the same variable with different set function

### Expected Behavior

The variable normal remove the money from balance when is working

### Steps to Reproduce

when you try to set the variable to 100 is this working

set {payinok.%player%} to 100

when you try to set with arg-1 or set chat message to the variable is this not longer working to substract from essentials money

### Errors or Screenshots

on this screenshot you can see i m try to get money from essentials balance but not working...

![Screenshot 2023-07-25 232138](https://github.com/SkriptLang/Skript/assets/49566322/c6450444-8297-41a0-91dc-90f8c4299402)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
You need to take in a number argument, not a text argument. If you need further assistance, I recommend reaching out in one of the community Discord guilds.
