### ISSUE TITLE
Some error causing skript to get disabled.

### ISSUE THREAD

**Issue by rasp-pi-420** [SkriptLang/Skript#5859]
### Skript/Server Version

```markdown
2.2-dev37c
```

### Bug Description

Skript errored and apparently disabled itself and will not work, Im unable to run commands.

### Expected Behavior

No errors, Being able to run /skript

### Steps to Reproduce

Run a minehut server on paper 1.18.2 and join.

### Errors or Screenshots

[lastest.txt](https://github.com/SkriptLang/Skript/files/12167948/lastest.txt)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
We will not provide help for a server using 2.2-dev37c
please try and use latest https://github.com/SkriptLang/Skript/releases/latest
and if the error persists you can respond here again

**Comment by AyhamAl-Ali** [comment]
You're using the wrong and very outdated Skript version. Please use [latest Skript version](https://github.com/SkriptLang/Skript/releases/latest).
