### ISSUE TITLE
💡Add `applyBoneMeal` effect

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#5869]
### Suggestion

Would be nice to add [applyBoneMeal](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Block.html#applyBoneMeal(org.bukkit.block.BlockFace)) effect.

### Why?

Doesn't exist.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by nylhus** [comment]
This looks doable. I'll try and get it done
