### ISSUE TITLE
Spawn egg support

### ISSUE THREAD

**Issue by cwken10** [SkriptLang/Skript#587]
```
aliases:
	llama spawn egg = 383:103
	polar bear spawn egg = 383:102

command /test:
    trigger:
        give player llama spawn egg
```

other spawn egg id can be aliases, except llama & polar bear (so far found this 2), once give to player, item will become white spawn egg named "Spawn" with no function
![screenshot 2017-05-24 01 05 15](https://cloud.githubusercontent.com/assets/20023067/26366290/1abad7c6-401d-11e7-9346-4f45a8b73efd.png)

**Comment by Snow-Pyon** [comment]
1.9+ doesn't use data values for spawn eggs anymore, it would be cool if the type of expression supported spawn eggs.

**Comment by TheBentoBox** [comment]
Yeah, this certainly isn't a bug or Skript's fault, but it would be cool to have support for how spawn eggs work now.

**Comment by xXAndrew28Xx** [comment]
That would be nice:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/SpawnEggMeta.html

**Comment by Pikachu920** [comment]
@Snow-Pyon i'm willing to add this, are we sure that it is going to be in the aliases rework?

**Comment by Snow-Pyon** [comment]
yes, since you can put special nbt tags to the aliases now it should be doable with the new aliases.

**Comment by Pixwok** [comment]
hello, aliases do not work in a condition, because my condition is not respected. Help me :)

**Comment by bensku** [comment]
Aliases rework is not ready yet. Do not use it unless you're helping us to write the aliases.
