### ISSUE TITLE
Vehicle events doesn't work

### ISSUE THREAD

**Issue by Drapika** [SkriptLang/Skript#5870]
### Skript/Server Version

```markdown
Server: paper 1.20.1 #100
Skript: Skript 2.7.0 beta 3
```

### Bug Description

When I use any vehicle event
    - on vehicle enter
    - on vehicle exit
    
It does nothing, any error when I reload my skript or in console. I try to put a message for debugging like "send "test" to player" but nothing

Exept, "player's vehicle" is ok

### Expected Behavior

Initially I make a skript to destroy player's vehicle on exit

### Steps to Reproduce

on vehicle exit:
    send "test" to player
    destroy player's vehicle

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Try `broadcast` instead of `send to player`

**Comment by Fusezion** [comment]
`destroy player's vehicle` what is this from? As it isn't skript

**Comment by Fusezion** [comment]
Wanting to make a mention here too, not everything is labeled a vehicle there's only a handful. If you're riding something you normally can't ride without special commands you should be using the `on dismount` event which is called for the non vehicle entities like arrows and cows

**Comment by Drapika** [comment]
Thanks, I made a mistake, it's not "destroy" but "delete"

And, I try your code Fusezion and it works ! I try with a armor stand for vehicle and it does nothing, but with a boat it work

So I don't understand ._. For more explanation I try to make a /sit with a armor stand vehicle

**Comment by AyhamAl-Ali** [comment]
An armor stand is not a vehicle, you're using `mount` effect to mount player in the armor stand therefor the event will never trigger, for more help you can join the [skUnity discord server](https://discord.gg/skript) to chat with other users about possible solutions.

This issue in invalid towards what it was opened for.
