### ISSUE TITLE
Variables are loaded after Skript is finished loading

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#5882]
### Skript/Server Version

```markdown
> sk info
[11:15:13 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[11:15:13 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[11:15:13 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[11:15:13 INFO]: [Skript] Server Version: git-Paper-101 (MC: 1.20.1)
[11:15:13 INFO]: [Skript] Skript Version: 2.7.0-nightly-755f59c (skriptlang-nightly)
[11:15:13 INFO]: [Skript] Installed Skript Addons: 
[11:15:13 INFO]: [Skript]  - skript-reflect v2.4-dev1 (https://github.com/TPGamesNL/skript-reflect)
[11:15:13 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

Skript is loading variables AFTER Skript has finished loading, therefor variables in a load event are useless.

This is due to LimeGlass adding a delay for variables
https://github.com/SkriptLang/Skript/blob/7632dd8fb367778bf9f28b59e4f147f091d37302/src/main/java/ch/njol/skript/Skript.java#L607
Thus pushing variables to load AFTER everything else

TPGames brought this up during the PR
https://github.com/SkriptLang/Skript/pull/4873#discussion_r1019256633

### Expected Behavior

for variables to load before scripts load

### Steps to Reproduce

test code
```vb
on load:
	send "&aLOADED MY SCRIPT WITH VAR %{var}%"
	wait 1 tick
	send "&bAFTER VARIABLES ARE LOADED VAR: %{var}%"
```

Outcome:
<img width="495" alt="Screenshot 2023-08-05 at 11 19 41 AM" src="https://github.com/SkriptLang/Skript/assets/20008482/8bb031e7-86b5-4a81-bfc8-03eaee5b2e4d">

### Errors or Screenshots

see above

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Use default expressions

**Comment by BaeFell** [comment]
Clean install of Skript 2.7.0-beta3, just Skript, no configurations changed. Still has this problem. You've delayed the loading of ALL variable systems. If there is a race condition, you should look into other ways of handling addon registered variable storage or have it not be an option.

```
on script load:
	broadcast "Value of var is: %{var}%"
	wait 1 tick
	broadcast "Value of var is: %{var}%"
```

![image](https://github.com/SkriptLang/Skript/assets/4953800/853707de-6415-47c5-9417-56ad6fa39e6a)

**Comment by bluelhf** [comment]
> Use default expressions. This is required, otherwise not possible to have add-on registered variable storage, race condition.

Could we delay the load events in Skript to run after variable initialisation? This way you addons could register custom variable storages and the variables would still work in load events.

**Comment by Moderocky** [comment]
As far as I can see we have no choice but to remove the delay or to revert #4873 entirely.

> delay the load events in Skript to run after variable initialisation

I don't think this is a practical option in the short term, changing this would guarantee the load event occurs at a different time and that is likely to cause breaking changes for users expecting the load event to happen when it does (i.e. before something else happens) -- 
it seems like we would be breaking one thing to fix another

**Comment by ShaneBeee** [comment]
I wanted to start off with saying @TheLimeGlass your "fix" for this is to use default expressions?
A Skript user shouldn't have to use default expressions and/or waits just because you broke Skript.
You need to realize this is a group project and not another one of your addons. You can't introduce a breaking change then ignore it, close the issue and tell someone to "fix it yourself"

Next, I wanted to address the issue at hand.
From my understanding, correct me if im wrong, but this is how Skript USED to load:
- server starts up
- magic happens
- Skript STARTS loading
- aliases are loaded
- elements are loaded (structures, effects, expression, etc)
- at this point, Skript is basically done its initial loading, so Skript inits a 0 tick delay, which allows other plugins (addons) to load before Skript finishes
- addons load
- "Running delayed init tasks" (because we caused a delay earlier)
- variables are loaded  (SEE NOTE BELOW)
- scripts are parsed (therefor events are registered)
- server is done loading

NOTE:
Ok, so variables are already loaded after a delay, variables already load AFTER ADDONS LOAD.... why are we delaying it even more???
As seen in Skript 2.6.4:
<img width="920" alt="Screenshot 2023-08-06 at 9 25 29 AM" src="https://github.com/SkriptLang/Skript/assets/20008482/afcb51dd-2967-4327-b7e8-169366039f75">
You can see variables clearly already load after addons are finished loading.... why are we delaying this task even further?

**Comment by Moderocky** [comment]
We came to the same conclusion in the group chat, it shouldn't cause a problem to just remove the extra delay.
