### ISSUE TITLE
[SUGGESTION] Add NamespacedKey support

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5884]
### Suggestion

Add support for bukkit's NamespacedKey systems

- Expression for creating NamespacedKeys (`namespaced[ ]key from %strings%`)
- Expression for getting namespace/key from a NamespacedKey (`namespace [:key] of %namespacedkeys%`)

### Why?

Not currently supported, this is a useful tool for allowing skript developers to prevent conflicts between systems and don't rely only on variables, this is already used for recipes and can destroy/place item meta flags.

### Other

I don't care what chu people say this shouldn't be treated the same as the recipe section pr. This is bukkit's not skript's messed up view of how it should be handled 

`fusezion:*#&D(*JH(*#HDOI#` out

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
I've seen a pull request, I believe by Pikachu not sure. Where there was a Utils#getNamespace method added, to get a namespace using Skript instance, which may provide aid to addons.

I do not agree with this enhancement for the sole reason of it not being needed to be a ClassInfo, you can just accept a string in an expression and parse using internal of that class of Utils class.

**Comment by Pikachu920** [comment]
> Where there was a Utils#getNamespace method added, to get a namespace using Skript instance, which may provide aid to addons for exact match grabbing.

that was me and yeah that's the intention of that method. to provide a way for addons to use a common way of getting keys (and to be compatible with vanilla keys as they have the special encoding).

since it seems there are a good amount of people on the team who prefer not having a classinfo, i'm going to close this for now unless opinions change.
