### ISSUE TITLE
Add NBT and pathfinders support & potion aliases broken

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#589]
Hey people!

## Aliases bug
I found this bug while trying to save items for my backpack script:
```
give a lingering_potion to player
give a splash potion to player
```
None of these aliases work in any expression, with the following error:
`'a lingering_potion'  can't be added to a player because the former is neither an item type...`

Changing the alias from `lingering(_| )potion¦s = 441` to just `lingering = 441` fixes the problem, so it's most likely an alias conflict.

## **Now the suggestion**
I know there's already support for NBT and pathfinders in skStuff, but some parts of it don't work, and I really don't know if TheBukor is going to update it to 1.12.

Also, there's many other useful things to do with it:
- You can store so much data in item's NBT, instead of saving it into variables.
- There's a new tag in 1.9 that allows storing data into mob's NBT, which may replace some variables.
- Full item customization, like custom potions, pick up delay, can place on and unbreakable tags.
- Mob customization, with unlimited amount of passengers on a mob in a single line of code, invulnerability (of mobs), drop chances, effects, gravity, **attributes**, AI, equipment,, and many other things.
- Armor stand management.
- Spawners will be a lot more useful, since you can edit them completely, being able even to create a "StackSpawners" and "SilkSpawners" script.
- Skull customization.
- BlockEntityData, so you can spawn a chest with pre-defined items much easier.
- You'll let the community create their own scripts to make the usage of NBT even easier.

### **If you are pretending to add it, there's skStuff's expressions + some others which may be useful**
- `%itemstack% without nbt`
- `%itemstack% with nbt %text%`
- `nbt [tag|compound]` - can be set, added, etc
- `tag %text% of %nbt%`
- `element %number% of nbt list %nbt list%`

### Examples:
- `enchanted book without nbt`
- `diamond sword with nbt {Saving:['yey','spaced text']}` - it'd be interesting to automatically replace ' with normal ", since it may conflict (you'd need to double it everytime) with " from Skript.
- `nbt of tool`
- `tag "Saving" from nbt of tool`
- `element 1 of nbt list ("[a,b,c,d,e,f]" parsed as nbt list)` - in this case, would be "a"
- `element 2 of nbt list tag "Saving" from nbt of tool` - would be "spaced text" if using the diamond sword case.

NBT is love, NBT is life.

I really hope you add it <3
Thanks!

**Comment by bensku** [comment]
NBT support will not come unless Spigot folks decide to add it or Skript is ported to another platform. The former is extremely unlikely and the latter... well, not anytime soon.

It seems there is a bug with aliases and potions, though. I wonder how easy it will be to fix...

**Comment by melinstagibson** [comment]
Did you have time to look into this? not worth fixing? Im happy with sticking to ID's for now since i cant see any downside from that (besides that ill be screwed when 1.13 but won't we all :D)

**Comment by TheBentoBox** [comment]
@melinstagibson For now you can fix it yourself by renaming the `potion` aliases so that they don't conflict with the potion expression. e.g. I changed my lingering and splash potion aliases from `lingering potion` and `splash potion` to `lingering pot` and `splash pot`.
