### ISSUE TITLE
Error with portal block type

### ISSUE THREAD

**Issue by iRevCodes** [SkriptLang/Skript#5890]
### Skript/Server Version

```markdown
Skript 2.6.4
```

### Bug Description

So When you use  'type of portal block' end portals output as nether portals.

### Expected Behavior

It's meant to output 'end portal block'

### Steps to Reproduce

on player portal:
  send type of portal block
  cancel event

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/112442449/47ae4af9-2343-484b-96aa-32e8660a8dc7)
![image](https://github.com/SkriptLang/Skript/assets/112442449/85632bfe-2396-4fa7-b8ae-7a125d35a285)

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
It's `type of event-block` or `type of block`
`portal block` is an alias to nether portal block, see [this](https://github.com/SkriptLang/skript-aliases/blob/fb9c3044e555667b4dc5558467608bd55fa32df0/other.sk#L15C2-L15C46)

**Comment by iRevCodes** [comment]
![image](https://github.com/SkriptLang/Skript/assets/112442449/70207289-1c0a-4ad4-8f03-44320f49ff6b)

**Comment by iRevCodes** [comment]
W fix

**Comment by AyhamAl-Ali** [comment]
Portal event doesn't have a block event value, only a location/entity therefor you won't get the block in that event
