### ISSUE TITLE
For loops

### ISSUE THREAD

**Issue by dialedd** [SkriptLang/Skript#5893]
### Suggestion

I suggest adding For Loops into skript. Even tho For loops can be made with a combination of while loops and conditionals, I feel that adding For Loops would allow skript to grow and become a more powerful scripting language

### Why?

Adding For loops to Skript will enhance its ability to automate repetitive tasks and iterate over data, making it more versatile and powerful.

### Other

Nope.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
`loop %objects%` for each loop
`loop x times` for loop
I don't get where while loop is from

**Comment by dialedd** [comment]
I lowkey was not thinking when I was writing this sooo yeaa.
