### ISSUE TITLE
Console error, variables

### ISSUE THREAD

**Issue by ImOnFireeeeeeeee** [SkriptLang/Skript#5904]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here:
https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here:
https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here:
https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-115 (MC: 1.20.1)
[Skript] Skript Version: 2.6.4
[Skript] Installed Skript Addons:
[Skript] SkBee v2.14.1 (https://github.com/ShaneBeee/SkBee) -
[Skript] Installed dependencies:
[Skript] Vault v1.7.3-b131
[Skript] WorldGuard v7.0.9-beta1+2249-223b80c
```

### Bug Description

![Screenshot 2023-08-10 125846](https://github.com/SkriptLang/Skript/assets/141966057/6a73f8ad-2512-4354-a1d7-ee85563cb459)
I was told to make an issue here, it says something about my varibales thing but it's only 69 kb if that makes sense. This showed up in console and I don't think i've seen it before

### Expected Behavior

I'm not sure 

### Steps to Reproduce

I don't entirely know what the bug is so I cannot answer this

### Errors or Screenshots

Screenshot posted 

### Other

Nope

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Have you recently updated or downgraded your Skript versions, and or Server versions?

**Comment by ImOnFireeeeeeeee** [comment]
I have 2 list variables which contain 4 items each, all renamed with kinda complex lore if that matters. I have deleted worlds but I don't believe I have used any location variables. Not that recently but we have changed to 1.20.1, skript version has stayed the same since i downloaded it (2.6.4)

databases:
	# Databases to store variables in. These can either be used as a simple one-server-storage
	# where variables are written constantly but only read at server start,
	# or as a connection between multiple servers by monitoring the database(s) for changes.
	#
	# You can define as many databases as you want, just make sure to choose a distinct name for each one, and don't forget to set all options correctly.
	#
	# To be able to use a database you'll need to download the plugin 'SQLibrary' from https://dev.bukkit.org/projects/sqlibrary/files
	# and install it in your server's plugin directory like other plugins.
	#
	# Please note that '/skript reload' will not reload this section, i.e. you'll have to restart Skript for changes to take effect.
	
	# Each database definition must be in a separate section. You can choose any name for the sections, as long as it's not already used.
	database 1:
		# An example database to describe all possible options.
		
		type: disabled
		# The type of this database. Allowed values are 'CSV', 'SQLite', 'MySQL' and 'disabled'.
		# CSV uses a text file to store the variables, while SQLite and MySQL use databases, and 'disabled' makes Skript ignore the database as if it wasn't defined at all.
		
		pattern: .*
		# Defines which variables to save in this database.
		# This pattern uses Regex syntax, e.g. use 'db_.*' (without the quotes) to store all variables prefixed with 'db_' in this database,
		# or use '.*' (the default value) to store all variables here (recommended for the last database in this list, as otherwise some variables might not be saved).
		# Please note that variables are only stored in one database, and databases are checked from top to bottom,
		# e.g. if a variable matches the topmost database's pattern it will be saved there and nowhere else.
		# BTW: Patterns are checked in a separate thread, i.e. your server likely won't run slower when using complicated patterns.
		
		monitor changes: false
		monitor interval: 20 seconds
		# If 'monitor changes' is set to true, variables will repeatedly be checked for updates in the database (in intervals set in 'monitor interval').
		# ! Please note that you should set 'pattern', 'monitor changes' and 'monitor interval' to the same values on all servers that access the same database!
		
		# == MySQL configuration ==
		host: localhost# Where the database server is located at, e.g. 'example.com', 'localhost', or '192.168.1.100'
		port: 3306# 3306 is MySQL's default port, i.e. you likely won't need to change this value
		user: root
		password: pass
		database: skript# The database to use, the table will be created in this database.
		table: variables21# The name of the table to create. 'variables21' is the default name, if this was to be omitted.
		# (If the table exists but is defined differently that how Skript expects it to be you'll get errors and no variables will be saved and/or loaded)
		# == SQLite/CSV configuration ==
		file: ./plugins/Skript/variables.db
		# Where to save the variables to. For a CSV file, the file extension '.csv' is recommended, but not required, but SQLite database files must end in '.db' (SQLibrary forces this).
		# The file path can either be absolute (e.g. 'C:\whatever\...' [Windows] or '/usr/whatever/...' [Unix]), or relative to the server directory (e.g. './plugins/Skript/...').
		
		#table: variables21
		# The name of the table to create. 'variables21' is the default name, if this was to be omitted.
		# (If the table exists but is defined differently that how Skript expects it to be you'll get errors and no variables will be saved and/or loaded)
		# This is generally not required as the the .db file will only be used by Skript, unless you want to split different variables into different tables
		
		backup interval: 2 hours
		# Creates a backup of the file every so often. This can be useful if you ever want to revert variables to an older state.
		# Variables are saved constantly no matter what is set here, thus a server crash will never make you loose any variables.
		# Set this to 0 to disable this feature.
		
		
	MySQL example:
		# A MySQL database example, with options unrelated to MySQL removed.
		
		type: disabled# change to line below to enable this database
		# type: MySQL
		
		pattern: synced_.*# this pattern will save all variables that start with 'synced_' in this MySQL database.
		
		host: localhost
		port: 3306
		user: root
		password: pass
		database: skript
		table: variables21
		
		monitor changes: true
		monitor interval: 20 seconds
		
	SQLite example:
		# An SQLite database example.
		
		type: disabled# change to line below to enable this database
		# type: SQLite
		
		pattern: db_.*# this pattern will save all variables that start with 'db_' in this SQLite database.
		
		file: ./plugins/Skript/variables.db
		# SQLite databases must end in '.db'
		#table: variables21
		# Usually not required, if omitted defaults to variables21 (see above for more details)
		
		backup interval: 0# 0 = don't create backups
		monitor changes: false
		monitor interval: 20 seconds
		
	default:
		# The default "database" is a simple text file, with each variable on a separate line and the variable's name, type, and value separated by commas.
		# This is the last database in this list to catch all variables that have not been saved anywhere else.
		# You can modify this database freely, but make sure to know what you're doing if you don't want to loose any variables.
		
		type: CSV
		
		pattern: .*
		
		file: ./plugins/Skript/variables.csv
		
		backup interval: 2 hours
		
		# PS: If you don't want some variables to be saved in any database (e.g. variables that contain an %entity% which usually despawn when the server is shut down)
		# you can modify the last database's pattern to not match all variables, e.g. use '(?!x_).*' to match all variables that don't start with 'x_'.
		# Be very cautious when doing this however as unsaved variables cannot be recovered after the server has been stopped.
		# I recommend to use a single character to denote unsaved variables (similar to local variables' '_'), e.g. '-', in which case the last database's pattern should be '(?!-).*'.
		
		
		
		# ==== Settings that should not be changed ====
		
version: 2.6.4
# DO NOT CHANGE THIS VALUE MANUALLY!
# This saves for which version of Skript this configuration was written for.
# If it does not match the version of the .jar file then the config will be updated automatically.

That is the database,

**Comment by ImOnFireeeeeeeee** [comment]
I haven't
________________________________

**Comment by TheLimeGlass** [comment]
So what Minecraft version did you upgrade from to 1.20.1.

Restarting your server should fix the error.

**Comment by ImOnFireeeeeeeee** [comment]
Updated from 1.19.4, I did pass through console after restart and I don't believe I saw the error but I'll check again next restart

**Comment by AyhamAl-Ali** [comment]
Any updates?
