### ISSUE TITLE
[SUGGEST] optional 'is' when using symbols for greater/less than

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5910]
### Suggestion

Add an optional `is` into the comparison condition when players are using `>`, `<`, `>=`, `<=`, `=` symbols

### Why?

I don't believe this causes any improper grammar conflicts and is kind of hand holding. When you're reading your own code back and you use those you're reading `player's balance >= {_price}` normally as `player's balance is greater than or equal to {_price}` This can at times cause a mental conflict as you type `player's balance is >= {_price}` this reads correct, but doesn't really look correct for some.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
Type the whole syntax if it bothers your brain. I always fully type `if the balance of the player is greater than or equal to the health of the player`

**Comment by AyhamAl-Ali** [comment]
Discussed with the team about this, the ones who participated didn't like the idea therefore closing the issue.
