### ISSUE TITLE
Disabling events for a specific skript when it's disabled.

### ISSUE THREAD

**Issue by CerialPvP** [SkriptLang/Skript#5911]
### Suggestion

Usually, when you use /sk disable (script), it does disable the script, but commands and events still run even when disabled.
My suggestion is, when you run the disable command, unregister all commands and events in that disabled skript.

### Why?

To be honest, yes, I can make a variable which is set to true when `on unload` runs, and then make all my commands and events in that skript check for that variable, but we need an easier way. If we do this, this just makes more boilerplate code which we don't want.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by DelayedGaming** [comment]
What’s your server software and the version of the MC server and Skript? As these are definitely disabled in disabled skripts.

**Comment by CerialPvP** [comment]
> What’s your server software and the version of the MC server and Skript? As these are definitely disabled in disabled skripts.

I am using Paper 1.19 and Skript 2.7-beta3, but it still happens on older stable Skript versions.

**Comment by sovdeeth** [comment]
Cannot replicate on 1.20.1, Skript 2.7-beta3

**Comment by sovdeeth** [comment]
Closing due to inability to replicate
