### ISSUE TITLE
[SUGGESTION] add delete changer to ExprMessage

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5919]
### Suggestion

add support for using `delete (join|death|quit) message` 

### Why?

Not supported and using `""` or `" "` only make an empty line

### Other

kick message is labeled not null sadly so we can't do it with that.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by UnderscoreTud** [comment]
Setting it to an empty string makes the message not send.

**Comment by Pikachu920** [comment]
I think this would be nice to have but I think we should probably use `clear death message` in the example rather than `delete death message`.

**Comment by TheLimeGlass** [comment]
> I think this would be nice to have but I think we should probably use `clear death message` in the example rather than `delete death message`.

clear is the same as delete under the ChangeMode.DELETE changer.

**Comment by Pikachu920** [comment]
> > I think this would be nice to have but I think we should probably use `clear death message` in the example rather than `delete death message`.
> 
> clear is the same as delete under the ChangeMode.DELETE changer.

yup sorry if I wasn't clear, I mean that in the documentation for the changer I'd prefer if we using `clear` over `delete`.

**Comment by Fusezion** [comment]
Yeah, sorry, delete was just the thing that came to mind when i wrote this. I agree that clear should be the example stuff

**Comment by DelayedGaming** [comment]
> using "" or " " only make an empty line
Assuming you’re using 1.8 (or pre 1.13, iirc) when setting the message to "" displays a newline instead

**Comment by Fusezion** [comment]
If it's only pre 1.13 that would probably explain it, I opened this based off what a discord user experienced while in skript help
still a nice addition non the less to have rather then relying on unintended set method

**Comment by AyhamAl-Ali** [comment]
> > using "" or " " only make an empty line
> 
> Assuming you’re using 1.8 (or pre 1.13, iirc) when setting the message to "" displays a newline instead

Keep in mind, Skript 2.7 only supports 1.13+
