### ISSUE TITLE
Skript Namespaces/Classes

### ISSUE THREAD

**Issue by andriejs** [SkriptLang/Skript#5920]
### Suggestion

Skript currently has no support for namespaces / classes

Classes of course being like how they are in programming languages (I'm more talking about simple classes not like java/javascript's bloated classes with proctected, static, etc).

Classes can hold functions, variables, etc that are LOCAL to instances of that class.
Functions inside of classes can use `this` to refer to the class.
Functions inside of classes can be ran/used by using something like `{_classInstance}.%functionName%(%args)`.
If a class has a function called `constructor` it would be called when the class is instanced.

Namespaces are kind-of like classes BUT they are static, meaning `this` cannot be used inside of an namespace, and they dont need to be instanced before using them, functions would be ran/used by using something like `%namespace%.%functionName%(%args%)`

Classes and Namespaces can have `local` to make them local to that script file.
Anything inside of a class/namespace is local to that class instance or namespace.

### Why?

This can help organizing functions, variables, etc A LOT.

### Other

**Related issues:** #2188 and #5139

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Thank you for your  suggestion. You're thinking of Skript like a new programming language but it isn't. Skript's goal is to simplify Minecraft customization using human and English friendly sentenses and logic. If you're thinking of all this being added to Skript then you better be switching to Java programming, the real programming goes there.

**Skript Definition**
> Skript is a Bukkit plugin which allows server admins to customize their server easily, but without the hassle of programming a plugin or asking/paying someone to program a plugin for them.

Adding to that, Skript does have local functions.. local to scripts

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/5884

**Comment by Fusezion** [comment]
> Duplicate #5884

Seems like he's wanting something completely different
