### ISSUE TITLE
[SUGGESTION] add editItemMeta() to Itemtype class

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5922]
### Suggestion

Add a method to edit item meta of an itemtype. 

### Why?

Itemstacks support this functionality however itemtype only supports the ability to get/set meaning in order to do this for addons we have to `getRandom -> update item meta -> create new itemtype instance -> return itemtype`

this seems unintuitive in my opinion especially with how much skript keeps depending on itemtype for just about everything making things like itemstacks uncommonly used

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by UnderscoreTud** [comment]
No, you don't need to do all of that. You can use `ItemType#getItemMeta` to get the global item meta of the item type, edit it, then update the item meta using `ItemType#setItemMeta`. Sure the method is nice to have but it's more of a niche in my opinion

**Comment by TheLimeGlass** [comment]
An ItemStack will have the applied ItemMeta from the ItemType when you use `ItemType#getRandom` Pickle has a pull request to remove the `ItemType#setItemMeta` i'm pretty sure it's never used because you can modify the getItemMeta directly.

**Comment by Fusezion** [comment]
I guess that's fair
