### ISSUE TITLE
Rename Slot classinfo name to Slot and not Inventory Slot

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5931]
### Suggestion

Change the `.name()` of classinfo Slot to "Slot" instead of "Inventory Slot"
  
https://github.com/SkriptLang/Skript/blob/7b0bfce68c4fb512814005ab76cb55e6a401cbcd/src/main/java/ch/njol/skript/classes/data/SkriptClasses.java#L479-L483

### Why?

A slot classinfo will not always have an inventory reference, and having the classinfo name being "Inventory Slot" doesn't make sense when classes like `DroppedItemSlot`, `ThrowableProjectileSlot` and `ItemFrameSlot` don't have an inventory reference but say they return "Inventory Slot"

### Other

up for debates, but helps with clarity of return types

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by MihirKohli** [comment]
https://github.com/SkriptLang/Skript/pull/6001
