### ISSUE TITLE
Make it possible to mix taps and spaces 

### ISSUE THREAD

**Issue by thebox4** [SkriptLang/Skript#5939]
### Suggestion

Make it possible to mix taps and spaces

### Why?

It very annoying you dose the script has to not work

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
You either use spaces or tabs.

**Comment by thebox4** [comment]
> You either use spaces or tabs.
servers on minehut are one of the biggest users of this plugin and the editor makes it impossible , its so BAD

**Comment by AyhamAl-Ali** [comment]
> servers on minehut are one of the biggest users of this plugin and the editor makes it impossible , its so BAD

We understand howevef,r It's just a very bad practice to support both tabs and spaces mixed together, it's a little complicated but useless feature to fix a simple issue that any code editor can fix with a single click. It's recommended to use a real editor like Visual Studio Code, it will show you tabs/spaces and fix it for you.

**Comment by thebox4** [comment]
> > servers on minehut are one of the biggest users of this plugin and the editor makes it impossible , its so BAD
> 
> We understand howevef,r It's just a very bad practice to support both tabs and spaces mixed together, it's a little complicated but useless feature to fix a simple issue that any code editor can fix with a single click. It's recommended to use a real editor like Visual Studio Code, it will show you tabs/spaces and fix it for you.

Can you please add a option, i use vs code but if i want to change something small i always uses the opposite
