### ISSUE TITLE
[Suggestion] Region location coordinates

### ISSUE THREAD

**Issue by superstorm192** [SkriptLang/Skript#5962]
### Suggestion

[greater|lesser] coords of region
  returns the location of a corner of the region
[greater|lesser] (x|y|z) coord[s] of region
  returns the number of a coordinate of the corner of region
location of region
  returns the location of the lesser corner of the region
size of region
  returns a location with the length, width, and height of the region
all regions
  returns a list of all regions of the server

### Why?

The reason I am posting this is that I can't find a way to get more details about a region so I can perform code relative to a region. I am trying to save and load blocks and I need coordinates to save it to a structure (from SkBee)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
Might be best if this issue is transferred to skript-worldguard repo

**Comment by AyhamAl-Ali** [comment]
https://github.com/SkriptLang/skript-worldguard/issues/15
