### ISSUE TITLE
[Parser] Long load times for complex syntaxes and explicitly defined lists

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#597]
Hi there,

I made many scripts with 1000+ lines of codes. Some of them are loading real quickly and some taking forever to reload. Does anybody know how to fix this? Is there any information available how to optimize loading time?

https://forums.skunity.com/threads/why-are-some-scripts-loading-fast-while-others-loading-slow.3799/#post-11768

**Comment by Snow-Pyon** [comment]
It's for sure an expression/effect with a syntax that makes the parser slower for some reason, it has been reported earlier and is a very known issue. You should look which expressions/effects you're using in your Skript, for example Skellett's sound effect and skRayFall's show particle effect have this behavior.

**Comment by bensku** [comment]
General script loading performance should be a *bit* better in next release, but doesn't help with this. Someone help me :)

**Comment by Adrihun** [comment]
Yeah. It happens to me also (if i add sounds to my script)

**Comment by Matocolotoe** [comment]
Big lores take more time to parse than on dev37-, maybe it's related to the new lore system ?

**Comment by FranKusmiruk** [comment]
Closing issue as parser performance is a well-known issue.
