### ISSUE TITLE
💡 Correct Javadocs name, title

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#5984]
### Suggestion

Skript Javadocs should be named `Skript $VERSION$` e.g. `Skript 2.7.0`
https://docs.skriptlang.org/javadocs/

Name
![image](https://github.com/SkriptLang/Skript/assets/20037329/2a401139-dc41-4242-9cf4-f97d604e5ce0)

Webpage Title
![image](https://github.com/SkriptLang/Skript/assets/20037329/8a427a24-0831-4eee-a320-bc224358b5ac)

### Why?

cuz we cool

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by MihirKohli** [comment]
Can you assign me this issue?

**Comment by Moderocky** [comment]
While we're here, are you aware you can change the styling of the javadocs template so it doesn't look like it arrived here in a time machine from 2003?

If you are interested in making it not look the way it does, let me know and I can show you how to build it with a special stylesheet.

Below is a simple example with the colours changed; you could do the same in Skript's colour scheme
<img width="812" alt="image" src="https://github.com/SkriptLang/Skript/assets/14147477/4aa18d2f-6941-4628-90ae-38f9c90c4e20">

You are, of course, able to make much larger changes to the styling but remember that the layout and the files are procedurally-generated, so you must work with what you are given.

**Comment by MihirKohli** [comment]
Is it Possible to change all instance at once? would like to work on it

**Comment by MihirKohli** [comment]
> While we're here, are you aware you can change the styling of the javadocs template so it doesn't look like it arrived here in a time machine from 2003?
> 
> If you are interested in making it not look the way it does, let me know and I can show you how to build it with a special stylesheet.
> 
> Below is a simple example with the colours changed; you could do the same in Skript's colour scheme <img alt="image" width="812" src="https://user-images.githubusercontent.com/14147477/268241591-4aa18d2f-6941-4628-90ae-38f9c90c4e20.png">
> 
> You are, of course, able to make much larger changes to the styling but remember that the layout and the files are procedurally-generated, so you must work with what you are given.

wa

**Comment by MihirKohli** [comment]
> While we're here, are you aware you can change the styling of the javadocs template so it doesn't look like it arrived here in a time machine from 2003?
> 
> If you are interested in making it not look the way it does, let me know and I can show you how to build it with a special stylesheet.
> 
> Below is a simple example with the colours changed; you could do the same in Skript's colour scheme <img alt="image" width="812" src="https://user-images.githubusercontent.com/14147477/268241591-4aa18d2f-6941-4628-90ae-38f9c90c4e20.png">
> 
> You are, of course, able to make much larger changes to the styling but remember that the layout and the files are procedurally-generated, so you must work with what you are given.

Is it possible to make changes in all the instance at once?

**Comment by Moderocky** [comment]
> Is it possible to make changes in all the instance at once? Making all pages have common header & favicon?

Possibly, Maven comes with a built-in plugin for manipulating javadocs but Skript uses gradle and I don't know what the equivalent is for that. You might have to google it :)

**Comment by MihirKohli** [comment]
Updated Changes required for Homepage 
https://github.com/SkriptLang/skript-docs/pull/50

**Comment by MihirKohli** [comment]
<img width="380" alt="image" src="https://github.com/SkriptLang/Skript/assets/55236890/368167fa-2545-4c86-a9b3-b3124ece6cf6">

**Comment by MihirKohli** [comment]
> > Is it possible to make changes in all the instance at once? Making all pages have common header & favicon?
> 
> Possibly, Maven comes with a built-in plugin for manipulating javadocs but Skript uses gradle and I don't know what the equivalent is for that. You might have to google it :)

Btw i am interested in building as you have mentioned above

**Comment by MihirKohli** [comment]
@Moderocky how to add favicon couldn't find any guide?

**Comment by MihirKohli** [comment]
How to add favicon couldn't find any reference @AyhamAl-Ali ?

**Comment by AyhamAl-Ali** [comment]
> How to add favicon couldn't find any reference @AyhamAl-Ali ?

Based on my quick research (with help of ChatGPT as well), you can do that using gradle
```gradle
// Define a variable to store the path to your favicon image
def faviconPath = 'resources/favicon.ico'

// Configure the Javadoc task
javadoc {
    // Include the favicon in the Javadoc output
    options {
        // Add the following line to include the favicon
        headContent = "<link rel='icon' type='image/x-icon' href='$faviconPath'/>"
    }
}
```

for the title, current gradle properties file already have an option for it only set to the version, it should be `"Skript" + version`

**Comment by MihirKohli** [comment]
```
javadoc {
	source = sourceSets.main.allJava
	classpath = configurations.compileClasspath
	options.encoding = 'UTF-8'
	// currently our javadoc has a lot of errors, so we need to suppress the linter
	options.addStringOption('Xdoclint:none', '-quiet')
}

task releaseJavadoc(type: Javadoc) {
	title = project.name + ' ' + project.property('version')
	source = sourceSets.main.allJava
	classpath = configurations.compileClasspath
	options.encoding = 'UTF-8'
	// currently our javadoc has a lot of errors, so we need to suppress the linter
	options.addStringOption('Xdoclint:none', '-quiet')
}```

i have tried various ways still favicon doesn't show up on viewing html
Thank you if you can help me?

**Comment by AyhamAl-Ali** [comment]
> ```
> javadoc {
> 	source = sourceSets.main.allJava
> 	classpath = configurations.compileClasspath
> 	options.encoding = 'UTF-8'
> 	// currently our javadoc has a lot of errors, so we need to suppress the linter
> 	options.addStringOption('Xdoclint:none', '-quiet')
> }
> 
> task releaseJavadoc(type: Javadoc) {
> 	title = project.name + ' ' + project.property('version')
> 	source = sourceSets.main.allJava
> 	classpath = configurations.compileClasspath
> 	options.encoding = 'UTF-8'
> 	// currently our javadoc has a lot of errors, so we need to suppress the linter
> 	options.addStringOption('Xdoclint:none', '-quiet')
> }
> ```
> 
> i have tried various ways still favicon doesn't show up on viewing html Thank you if you can help me?

Sounds like you will need more help with that which contradicts the idea behind PRs. I would suggest you create a PR for the titles with the correct way (you sent above) and leave the favicon for others or maybe we will push the changes on your PR

**Comment by MihirKohli** [comment]
https://github.com/SkriptLang/Skript/issues/6045
