### ISSUE TITLE
New items from 1.20. don't work.

### ISSUE THREAD

**Issue by ZuRiKanHD** [SkriptLang/Skript#5998]
### Skript/Server Version

```markdown
Skript 2.70
```

### Bug Description

The new items from Minecraft version 1.20. seem to be unknown to the script. The actual Minecraft BlockID is there when you ask for the ItemType. If you try to display the item via an inventory, it will not be displayed. These items cannot be given to the player via give item. This has been the case since the update from 2.7.0-Beta3 to 2.7.0.

### Expected Behavior

The items from version 1.20. seem to be unknown to the script.

### Steps to Reproduce

Create a script that displays the name of the item to hold.

Compare the 1.20. Blocks with the blocks from previous versions.
The spelling is different.

If you try with the function: "Give player an item" to give the item based on the name, it doesn't work.

### Other

  - PoaSK v2.6.5
  - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
  - skript-db v1.3.9
  - SkQuery v4.1.10
  - SkBee v2.18.0 (https://github.com/ShaneBeee/SkBee)
  - SkJade v1.4.3 (https://www.github.com/Ankoki-Dev/SkJade)
  - Ersatz v1.0
 --------------------------------
  - Vault v1.7.3-b131
  - WorldGuard v7.0.9-SNAPSHOT+2250-fffb0c1

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
PR ready for 2.7.1
https://github.com/SkriptLang/skript-aliases/pull/88

**Comment by APickledWalrus** [comment]
By default it should create a temporary alias which is the Minecraft ID as you mention

You can try using that and BlockData for the meantime until a fix is released :)
