### ISSUE TITLE
Allow EffContinue to continue parent loops

### ISSUE THREAD

**Issue by Burbulinis** [SkriptLang/Skript#6012]
### Suggestion

I don't have much to say. The title really says it all.. basically this would look like this:
```applescript
loop all players:
    loop {values::%loop-value%::*}:
        set {_x} to foo(loop-value-2)
        if {_x} < 10:
            continue loop 1
    bar(loop-value)
    broadcast "Player has valid values!"
``` 
*Credits to @sovdeeth  for making beautiful example code*

Would just continue the parent loop instead of continuing the current loop, wondering why this isn't in Skript because in my opinion, this is a nice idea :)

### Why?

This is just a niche addition, I've had some situations where I really needed this...
Would improve the language in situations like mine, no negative side effects

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
To elaborate, the idea was described like Java's labels, being able to continue a loop from wherever. 
This is currently achievable by re-arranging logic or using some local variables as flags, but those methods are a little unwieldy and can be prone to bugs due to oversights.
```
loop all players:
    set {_valid} to true
    loop {values::%loop-value%::*}:
        set {_x} to foo(loop-value-2)
        if {_x} < 10:
            set {_valid} to false
            exit loop
    {_valid} is true
    bar(loop-value)
    broadcast "Player has valid values!"
```
