### ISSUE TITLE
Chat Components in action bar/scoreboard

### ISSUE THREAD

**Issue by Gustias** [SkriptLang/Skript#6043]
### Suggestion

So I will write this quickly and simply.

As you know there is formatting for font in skript.
For example:
"<f:name:padding_nosplit>..."
This changes the font of the following text after the format.

But there's an issue. You can use this formatting in chat messages, action bars. But in scoreboards or tab you can't. It just doesn't get formatted. And that's the issue.

### Why?

Resolving this issue would be great for the new servers that use font with resource packs.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
You can use ChatFormat in action bars currently. Skript doesn't have Scoreboard support, if you wish to use Skript's own ChatFormat in Scoreboards, I suggest an addon like Skore which takes this into consideration https://forums.skunity.com/resources/skore-the-scoreboard-addon.617/

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/3112
