### ISSUE TITLE
Skript-reflect giving errors in console only when I use skript 2.7

### ISSUE THREAD

**Issue by AMJazzarvdv** [SkriptLang/Skript#6046]
### Skript/Server Version

```markdown
1.20
2.7
```

### Bug Description

Files that use any skript-reflect implementation just cannot be reloaded for some reason, I do /reload <file name> and it says "Reloading" but never reloads.

### Expected Behavior

The file was supposed to reload and work

### Steps to Reproduce

I didn't do anything, its an internal error.

### Errors or Screenshots

^^^^

### Other

Please fix this, as well as the potions glitch, thanks.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This is a reflect issue, not a skript issue. Please update your reflect to 2.4-dev1.

**Comment by AMJazzarvdv** [comment]
thanks, sir sovde the 5th.

**Comment by AMJazzarvdv** [comment]
where can I get 2.4-dev1?

**Comment by AMJazzarvdv** [comment]
@sovdeeth

**Comment by sovdeeth** [comment]
On the skript-reflect GitHub.
