### ISSUE TITLE
Aternos

### ISSUE THREAD

**Issue by ae23rn7diu2** [SkriptLang/Skript#6055]
### Skript/Server Version

```markdown
It says there is a problem wit skript I am on the latest version of skript on aternos.
```

### Bug Description

Aternos

### Expected Behavior

IDK

### Steps to Reproduce

Install Aternos skript

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Aternos has a very outdated version of Skript. We do not support that version. Ask Aternos to get a newer version.
