### ISSUE TITLE
raw expression 3 can't be set to anything

### ISSUE THREAD

**Issue by LeCraft2Ouf** [SkriptLang/Skript#6062]
### Skript/Server Version

```markdown
Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
Skript's documentation can be found here: https://docs.skriptlang.org/
Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
Server Version: git-Paper-388 (MC: 1.18.2)
Skript Version: 2.7.0 (skriptlang-github)
Installed Skript Addons: 
  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
  - Skent v3.2.0
  - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
  - BungeeSK v2.0.0 (https://github.com/ZorgBtw/BungeeSK)
  - skript-yaml v1.4
  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
  - skript-db v1.3.9
  - Skungee v2.0.0-BETA-4
  - SkBee v2.15.1 (https://github.com/ShaneBeee/SkBee)
  - RediSkript v1.3.6-SNAPSHOT
  - ItemsAdder v3.5.0c-r2 (devs.beer)
 Installed dependencies: 
  - Vault v1.7.3-b131
  - WorldGuard v7.0.7+216b061
```

### Bug Description

I'd like to write to a variable but it doesn't seem possible since the latest version.

### Expected Behavior

My variable given in argument 3 should be set to variable {_output::result::1}.

### Steps to Reproduce

`import:
    ch.njol.skript.lang.Variable

effect [SQL] get[ |-]data int for %OfflinePlayer% to %text% and put in %object%:
	parse:
		expr-3 is an instance of Variable # to check if the second argument is a variable
		continue
	trigger:
		delay effect
		execute "SELECT result FROM VAR_INT WHERE var=%expr-2% AND uuid=%uuid of expr-1%" in {-sql} and store the result in {_output::*}
		set raw expr-3 to {_output::result::1}
		continue`

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/29964590/d702437a-2c13-421a-8380-5bd69bf0433c)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
1. this is addon related [skript-reflect](https://github.com/TPGamesNL/skript-reflect)
2. that expression can't be set to anything as the error says. `set {_blah} to something`
