### ISSUE TITLE
variables error : location cant be variable

### ISSUE THREAD

**Issue by madebygood** [SkriptLang/Skript#6068]
### Skript/Server Version

```markdown
1.20.1
2.7.0
```

### Bug Description

{TEST::%event-location%} <- this variable doesn't work.

### Expected Behavior

.

### Steps to Reproduce

.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Please give more information, this doesn't meant anything and if you need help you can use skUnity discord help channels
