### ISSUE TITLE
missing new GENERIC_MAX_ABSORPTION attribute

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#6079]
### Skript/Server Version

```markdown
[18:08:26 INFO]: [Skript] Server Version: git-Paper-205 (MC: 1.20.2)
[18:08:26 INFO]: [Skript] Skript Version: 2.7.0 (selfbuilt-unknown)
```

### Bug Description

`Missing lang enum constant for 'attribute types.GENERIC_MAX_ABSORPTION'`

### Expected Behavior

Please add the attribute to the lang file

### Steps to Reproduce

n/a

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Already fixed in #6072, will be in 2.7.1
