### ISSUE TITLE
event-initiator-inventory is not going to work properly

### ISSUE THREAD

**Issue by moraedu** [SkriptLang/Skript#6092]
### Skript/Server Version

```markdown
Irrelevant
```

### Bug Description

In the [PR for the inventory move item event](https://github.com/SkriptLang/Skript/pull/5462), the EventExpression `event-initiator-inventory`, [but due to an artifact when resolving the conflicts for rebase](https://github.com/SkriptLang/Skript/pull/5462/commits/e8d145d30fad871d2bf9a184b7e9f7a121dba60a#diff-dc9420c5561a15cb91397e809cc0c35240d0ef414b3927c7f2a196b5b19ba77bL1656-R1685), the registered event values were removed. This renders the expression useless as EventExpression depends on these event values to be registered to work.

### Expected Behavior

for the expression to have an event-value

### Steps to Reproduce

just using the expression should be enough

### Other

This should not have been made as an EventExpression. When there are multiple getters of the same type within an event, the unwritten convention is to create a separate expression for each one of them, and if applicable, provide one event-value of said type directing to the most sensible default for such an event (which in this case, it might be the initiator inventory). At least such is the example set by the ExprAttacker and ExprAttacked expressions in the damage events, among others.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Unreleased patch/feature 2.8.0-dev feature by the way.

**Comment by DelayedGaming** [comment]
As I introduced the involved PR for this feature, I will take care of this issue at the soonest possible.
