### ISSUE TITLE
Add paper's player isConnected method

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#6100]
### Suggestion

Add `OfflinePlayer#isConnected` into skript. 

### Why?

This method is a better alternative to `isOnline` for while loops and not added yet

### Other

Link to it's documentation: https://jd.papermc.io/paper/1.20/org/bukkit/OfflinePlayer.html#isConnected()
This is a paper 1.20.1 method if I remember properly

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
I don't think this is a good addition to Skript.
Skript stores the instance of the OfflinePlayer, and once that instance has left the server, it will always be false until a new instance is created of the offlineplayer as stated in the JavaDoc.

**Comment by Fusezion** [comment]
I don't understand your message Mr. Lime, this has nothing to do with skript's instance fully and is mostly there for while loops where we're actively using `while {_p} is online` or `while player is online` both of these cases are not gonna be affected by using `is connected`

To add to this, I've already had this within SkBee for awhile now with no reports of issues when using it. Like I said this is mostly for `while` loops where the issue of multiple loops are from `is online`

**Comment by sovdeeth** [comment]
> Skript stores the instance of the OfflinePlayer, and once that instance has left the server, it will always be false until a new instance is created of the offlineplayer as stated in the JavaDoc.

That's kind of the point. Right now you can't tell if a player has left and rejoined between calls to `is online`, so adding this would allow you to tell if the player has relogged in the interim.

**Comment by Moderocky** [comment]
I think I've done what you wanted but I don't fully understand so please check my PR and see if it's what you're looking for :)
