### ISSUE TITLE
Upload Skript to Spigot or Paper website

### ISSUE THREAD

**Issue by ScadeBlock** [SkriptLang/Skript#6111]
### Suggestion

Upload Skript to Spigot(https://spigotmc.org/) or Paper(https://papermc.io/) website

### Why?

Because it's easier to reachs to many people that don't know SkriptLang, also it can be add into Aternos

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Moderocky** [comment]
Duplicate of #3678 and #5627.
