### ISSUE TITLE
Permission Message not showing in Skript 2.7.1

### ISSUE THREAD

**Issue by NemusCraft** [SkriptLang/Skript#6125]
### Skript/Server Version

```markdown
Skript: 2.7.1
Server: git-Paper-119
```

### Bug Description

So i wanted to put a permission message and in skript 2.7 it worked while in skript 2.7.1 it returns "unknown command" 

### Expected Behavior

Send a custom perm message while executing the commannd without permissions.

### Steps to Reproduce

1. Make a command with permission message while your skript version is 2.7.1
2. Test the command without permission
3. and boom you see "unknown message" instead of custom perm message

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by NemusCraft** [comment]
![image](https://github.com/SkriptLang/Skript/assets/95968788/cd78f318-0e31-46af-aebe-1f857c8f7223)
this is what it looks like in previous version of skript (2.7)
![image](https://github.com/SkriptLang/Skript/assets/95968788/25540065-9134-4559-a7a5-f5812f5a7213)
this is what it looks like in latest version of skript

**Comment by AyhamAl-Ali** [comment]
Can you send the code you used

**Comment by NemusCraft** [comment]
`command /gmc [<player>]:
	permission: test.gamemode
	permission message: &chey, you dont have access to that command!
	trigger:
		if arg-1 is set:
			set arg-1's gamemode to creative
			send minimessage from "<gradient:light_purple:dark_purple>[Nemus]</gradient><light_purple>: Successfully gamemoded %arg-1% to creative!"
		else:
			set player's gamemode to creative
			send minimessage from "<gradient:light_purple:dark_purple>[Nemus]</gradient><light_purple>: Successfully gamemoded yourself to creative!"` @AyhamAl-Ali

**Comment by NemusCraft** [comment]
> Can you send the code you used

command /gmc [<player>]:
	permission: test.gamemode
	permission message: &chey, you dont have access to that command!
	trigger:
		if arg-1 is set:
			set arg-1's gamemode to creative
			send minimessage from "<gradient:light_purple:dark_purple>[Nemus]</gradient><light_purple>: Successfully gamemoded %arg-1% to creative!"
		else:
			set player's gamemode to creative
			send minimessage from "<gradient:light_purple:dark_purple>[Nemus]</gradient><light_purple>: Successfully gamemoded yourself to creative!"

**Comment by NemusCraft** [comment]
@AyhamAl-Ali here are the code ^

**Comment by sovdeeth** [comment]
I believe this is due to #5966. It appears that spigot has changed behavior over the years from sending a permission message error to simply telling the user the command does not exist if they do not have permission, which is a better security policy but is a breaking change.

We may need to re-add a PPCE listener to deal with the permission messages, I'm not sure.

**Comment by NemusCraft** [comment]
Skript released new version which contains a bug fix for this bug.
