### ISSUE TITLE
amount of players in player's world returns 1 instead of 2 when 2 online

### ISSUE THREAD

**Issue by TwinkleToes777** [SkriptLang/Skript#6135]
### Skript/Server Version

```markdown
Skript 2.7.1, 1.19.4
```

### Bug Description

amount of players in player's world returns 1
amount of players in world player's world returns 2

syntax bug

### Expected Behavior

expected both to return 2 as 2 are online

### Steps to Reproduce

just !send amount of players in player's world when 2 online

### Other
it worked in Skript 2.6.3 and 1.19.2, that's all that changed I think

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Please provide the FULL output of `/sk info`, like the bug report template asked you to.

**Comment by TwinkleToes777** [comment]
The template didn't ask me for /sk info

Server Version: git-Purpur-1985 (MC: 1.19.4)
Skript Version: 2.7.1 (selfbuilt-unknown)
Installed Skript Addons: 
Skent v3.2.2
skript-yaml v1.5
skDragon v0.17-alex-MC1.18-hack-4
skript-reflect v2.4-dev1 (https://github.com/SkriptLang/skript-reflect)
skript-db v1.4.0
SkriptJSON v1.0.0
SkBee v2.18.3 (https://github.com/ShaneBeee/SkBee)
SkJade v1.4.4 (https://www.github.com/Ankoki-Dev/SkJade)
Skooldown v1.2.1
RediSkript v1.3.6-SNAPSHOT
Installed dependencies: 
Vault v1.7.3-b131
WorldGuard v7.0.8+33cdb4a
GriefPrevention v16.18.1

**Comment by sovdeeth** [comment]
Please test with an official build of Skript and without addons. I cannot replicate on 2.7.1 and 1.20.1.

Also, the template does ask, you may have just missed it :)
![image](https://github.com/SkriptLang/Skript/assets/10354869/ab293865-126b-44be-a94d-3dc60a67a0be)

**Comment by TheLimeGlass** [comment]
Are you using Geyser?

**Comment by TwinkleToes777** [comment]
> Are you using Geyser?

No, but I am using a similar plugin that adds a special character to player usernames, if that is relevant.

**Comment by erenkarakal** [comment]
Even after adding a special character to my name (`.name`) I was unable to replicate this issue with both syntaxes in Skript 2.9.2, Paper 1.21
