### ISSUE TITLE
Server crashes when command executes the same console command

### ISSUE THREAD

**Issue by Tomastore** [SkriptLang/Skript#6144]
### Skript/Server Version

```markdown
[Skript] Server Version: git-Paper-550 (MC: 1.19.4)
[Skript] Skript Version: 2.7.1 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

This simple script instantly crashes the server.

I know this may be a low priority issue, but I find it really funny, and it's still a bug (?) so I report it here.

This is on a paper 1.19.4 local server on my pc. There was only Skript 2.7.1 in the plugins folder, and one script with the code below. 

### Expected Behavior

Execute the command many times

### Steps to Reproduce

```
Command /crash:
	trigger:
		make console execute command "crash"
```

### Errors or Screenshots

[crash-server.txt](https://github.com/SkriptLang/Skript/files/13164700/crash-server.txt)

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by Moderocky** [comment]
Please do not use our issue tracker for jokes.

**Comment by Tomastore** [comment]
I didn't mean to. While not a bug, I do think think it is an unexpected behaviour. If not the case, I apologize for wasting your time.

**Comment by DelayedGaming** [comment]
You’re calling the command to call itself, which ends up a recursive loop of death.
