### ISSUE TITLE
Hex aliases &x

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#6151]
### Suggestion

Add support for hex with aliases &x which defines the hex colour after it. This is how Minecraft uses hexs in books, and also how the placeholder community uses hex.

### Why?

This should be added similarly to how you can do &c the same as `<light red>`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by UnderscoreTud** [comment]
This is already possible.
