### ISSUE TITLE
Condition "Contains" in loop does not work for items

### ISSUE THREAD

**Issue by tiradorus** [SkriptLang/Skript#6153]
### Skript/Server Version

```markdown
Skript 2.7.1 ==> Version Mc 1.20.1 
Skript 2.6-beta2 ==> Version Mc 1.16.5 (Same problem)
```

### Bug Description

When you ask to a variable filled by an item, if the variable contains letters, or numbers, or anything, nothing happens.
HOWEVER if you display the variable, it shows you the values of the item, with his name etc etc.

So it's impossible, to insert all items from a player's inventory into a variable, loop it, and search for some special items with certain name.

### Expected Behavior

The loop-value is supposed to aprove if his value contains or not the condition that you've write.

### Steps to Reproduce

Try this code:
_It's just to see the bug._
```
command /testvar:
    trigger:
        set {_%player%.name} to player's name
        message "%{_%player%.name}%" to the player
        if {_%player%.name} contains "n":
            message "&aVALIDE NAME" to the player
        set {_%player%.item} to player's tool
        message "%{_%player%.item}%" to the player
        if {_%player%.item} contains "n":
            message "&aVALIDE ITEM" to the player
```

If your tool is for exemple an iron ingot, the variable "{_%player%.item}" will be "iron ingot" and so, will display "iron ingot" in the chat with the message that directly display the variable.
HOWEVER the condition <that contains a "n"> won't be validate, even if your item have a "n" in its name.
AND the other variable (with the player's name) WILL validate the condition if the player have a "n" in his name.
The bug seems to occurs only with the items.

More complex..
This code:
```
command /searchiron:
    trigger:
        set {_inv.%player%::*} to items in player's inventory
        loop {_inv.%player%::*}:
            if loop-value contains "iron ingot":
                message "&cIron ingot found" to player
            message loop-value to player
```
The loop-value will never match the iron ingot contains condition, even if you have some iron ingot in your inventory.
And the message "Loop value" will display the iron ingots into the chat if you have some in inventory, without triggering the condition above.

And even more complex!
This code:
```
command /testvar:
    trigger:
        set {_inv.%player%::*} to nbt of items in player's inventory
        loop {_inv.%player%::*}:
            if loop-value contains "insert":
                message "&cValue INSERT found" to player
            message loop-value to player
```
This command will register every NBT of every items into the player's inventory (SkBee dependency).
Same problem, the loop-value will display every NBT of every items, without any problems, however, the condition that contains the word "insert" won't be validate.
Even the direct <if loop-value is "value you are looking for":> does not work.

### Errors or Screenshots

No errors in skript. Juste have to copy and test the code to see the problem.

### Other

Yes!
Another bug that looks coming from the same issue:

Try this code:
```
command /changes:		
    trigger:
        set {_diampur} to amount of diamond named "&f&lDiamond pure" in player's inventory
        remove all diamond named "&f&lDiamond pure" from player's inventory
        message "%{_diampur}%" to player
```

IF you have some Diamonds named "&f&lDiamond pure" in your inventory, then the variable "{_diampur}" will be the number of diamonds well named, no problems.
(And the items are removed)
HOWEVER! If you have some diamonds named "&f&lDiamond pure" BUT that are coming from another plugin (Exemple: MMoItems, MythicMobs, etc etc) the diamonds aren't considered as valide into the condition.
And thoses items are not removed

SAME problem but not with the name, with enchants now
Instead of name you use a code like that:
```
command /changes:		
    trigger:
        set {_diampur} to amount of diamond of fortune 3 in player's inventory
        message "%{_diampur}%" to player
```
Same problem, if you just enchant a diamond with "/enchant fortune 3" then it's okay, the diamond is counted into the variable.
HOWEVER! if it's a simple diamond from another plugin, enchanted with fortune 3, it's not counted into the variable.
EVEN if you generate a diamond from... MythicMobs for exemple, you enchant it with "/enchant fortune 3" ... the command /changes won't consider this diamond enchanted as valide for the condition.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This is just a misunderstanding of how comparisons work.
An item does not contain text. It's an item, not more text. If you want to check if the name contains "n", do exactly that:
```
if name of {_item} contains "n":
```

If you want to check if a list of items contains a specific item type, you still don't compare against a string. Again, an item is not text. You compare against another item:
```
if {_items::*} contains iron ingot:
```
And again with nbt. Nbt is not a string, it does not contain text. You would have to stringify the nbt first or check the tags individually.
```
        set {_inv.%player%::*} to nbt of items in player's inventory
        loop {_inv.%player%::*}:
            if "%loop-value%" contains "insert":
```

Finally, for the "other bug", this is also a misunderstanding of item comparison.
a `diamond named "test"` is not the same as a diamond named "test" with another nbt tag. When comparing items, you can use the literal alias ``if x is a diamond`` and that's pretty lenient. But if you specify any trait about the diamond, well, now you have to specify ALL the traits, otherwise it won't match. This is why it's best to look at traits one at a time, like ``name of x is "test"`` and ``type of x is diamond``, etc.
