### ISSUE TITLE
Sorting Lists Addition

### ISSUE THREAD

**Issue by ElijahJunaid** [SkriptLang/Skript#6161]
### Suggestion

I am suggesting adding the ability to use the sorting lists by values with custom formats, exactly to what MorkazSk.

### Why?

I want this feature added because it's more convenient to have than installing an add-on for one change.

### Other

I suck at describing stuff and asking for stuff

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
Is the sorted indices expression not working or something?

**Comment by TheLimeGlass** [comment]
The sorted expression in MorkazSk and RandomSk returns a list of Strings that contains both the value and index in the String. See https://github.com/TheLimeGlass/RandomSk/blob/master/src/main/java/com/mirre/random/elements/expressions/ExprSortOutput.java

**Comment by Moderocky** [comment]
Do you think you could explain the functionality you're asking for?
