### ISSUE TITLE
Add recipe book syntaxes

### ISSUE THREAD

**Issue by Legoman99573** [SkriptLang/Skript#617]
I know this doesn't count as a bug, but could be of a reference of what will be missing in 1.12 release
- [ ] ~~Custom Advancements (Could make survival more fun and could be triggered like for example ``advancement title %string% with description %string%``)~~ see #3351/#3899
- [x] Parrots
- [x] Beds (just like slime blocks, except there are different color beds)
- [x] Terracotta (could make for good patterns)
- [ ] recipe book
- [x] illusioner

Others I can't think of right now. If you can edit, you can add others if needed. This can make a good milestone for 1.12.

**Comment by nshun1896** [comment]
also, illusioner. : )

**Comment by Legoman99573** [comment]
@nshun1896 Added

**Comment by bensku** [comment]
Not all of these will be complete for next release. Advancements, for example, are not exactly easy to implement properly.

**Comment by Legoman99573** [comment]
How about the crafting recipe book [one.](url) It probably won't be as confusing if it has a proper API to handle it.

**Comment by jaylawl** [comment]
@bensku Advancements are amazing! But Mojang is reworking advancements for 1.13, so you better check if working on this before 1.13 will be worth your time at all :)

**Comment by TheBentoBox** [comment]
Where did they say they're reworking advancements @jaylawl ? I keep up-to-date on upcoming changes pretty religiously and I haven't heard of that nor is it listed on the wiki page for 1.13. They're changing TONS of stuff with commands, block ID's, and data values, but not with advancements as far as I can tell.

**Comment by jaylawl** [comment]
@TheBentoBox https://minecraft.gamepedia.com/1.13 its going to be part of the upcoming data-packs is what i meant

**Comment by TheBentoBox** [comment]
That's not an actual change to advancements at all though, it's just a change to how players can store them to package them with other data-driven game elements. I don't believe it should matter in any way that's relevant to Skript but it's still good that you pointed it out for us to keep in mind.

**Comment by TheLimeGlass** [comment]
Closing in favor of https://github.com/SkriptLang/Skript/issues/5261 as there is only book recipes left.
