### ISSUE TITLE
Skript: "An internal error occurred while attempting to perform this command."

### ISSUE THREAD

**Issue by mynameisjec** [SkriptLang/Skript#6177]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-307 (MC: 1.19.2)
[Skript] Skript Version: 2.7.2 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: 
[Skript]  - WorldGuard v7.0.8+33cdb4a
```

### Bug Description

I have recently made a command called /block [block] [amount] that gives the player their specified block when the command is run. A few hours ago, it worked perfectly! However, when I logged back on a few minutes ago, whenever I run the command, or a second command that I created, it says: "An internal error occurred while attempting to perform this command." However, the command works perfectly, however, instead of sending chat messages like "This is not a block!" or "Success", it says the error. I looked into the console log, and all I can find is something related to the messages being sent? But I'm not really sure. This also is happening to another command I made called /tool [tool], which gives the player the specified tool, which, again, worked fine a few hours ago but suddenly only the function works and not the messages.

### Expected Behavior

In /block: The player is supposed to receive their chosen block and its amount, along with a message, which could be "This is not a block!" or "Successfully obtained this block!" or "You cannot give yourself this many blocks at once!", however, it now gives the block but instead of the correct message, always says the error.
In /tool: The player is supposed to run /tool [tool], e.g. /tool pickaxe, and receive that tool, along with a message, like "You have obtained a pickaxe/axe/shovel/hoe!", however, it only gives the tool, and instead of showing the message, it shows the error/

### Steps to Reproduce

I am not sure how this is reproducible; possibly by installing my plugins and replicating the code? I am not sure. However, I will attach the code, which, note, worked a few hours ago.
[toolscmd.sk.txt](https://github.com/SkriptLang/Skript/files/13290951/toolscmd.sk.txt)
[buildcommand.sk.txt](https://github.com/SkriptLang/Skript/files/13290952/buildcommand.sk.txt)
![image_2023-11-07_202409048](https://github.com/SkriptLang/Skript/assets/140921351/c016e9c6-dc2c-47f6-9c9d-e8a3553f4618)

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/140921351/4f04f2cb-d77b-4e65-a25d-329964e2d818)

Console error for /block:
https://paste.gg/p/anonymous/e0f7641169344aaca72126476e1da062

Console error for /tools:
https://paste.gg/p/anonymous/ac59b3cb886647dd8860166374d4f09d

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This is a pretty common issue due to something messing with Skript.
It could be from doing a /reload or similar, or you could have messed up the jar itself.
Usually a restart will fix this, but if it doesn't, redownload Skript.
If that doesn't fix it, make a comment here and I'll re-open it.
