### ISSUE TITLE
Cannot write variables to the database 'CSV' at sufficient speed

### ISSUE THREAD

**Issue by TomHo41** [SkriptLang/Skript#6178]
### Skript/Server Version

```markdown
[06:12:50 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[06:12:50 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[06:12:50 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[06:12:50 INFO]: [Skript] Server Version: git-Paper-388 (MC: 1.18.2)
[06:12:50 INFO]: [Skript] Skript Version: 2.7.2 (skriptlang-github)
[06:12:50 INFO]: [Skript] Installed Skript Addons: 
[06:12:50 INFO]: [Skript]  - skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders)
[06:12:50 INFO]: [Skript]  - SkBee v2.14.1 (https://github.com/ShaneBeee/SkBee)
[06:12:50 INFO]: [Skript] Installed dependencies: 
[06:12:50 INFO]: [Skript]  - Vault v1.7.3-b131
[06:12:50 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

Every 10 minutes it writes this error: ` [Skript]     Cannot write variables to the database 'CSV' at sufficient speed; server performance may suffer and many variables will be lost if the server crashes. (this warning will be repeated at most once every 10 seconds)` And if there are some player it sometimes lags. But this error is showing even if there are 0 players on server

### Expected Behavior

Dont' write this in console 

### Steps to Reproduce

Use CSV database
config.sk about databases
```
	default:
		# The default "database" is a simple text file, with each variable on a separate line and the variable's name, type, and value separated by commas.
		# This is the last database in this list to catch all variables that have not been saved anywhere else.
		# You can modify this database freely, but make sure to know what you're doing if you don't want to loose any variables.
		
		type: CSV
		
		pattern: (?!_).*
		
		file: ./plugins/Skript/variables.csv
		
		backup interval: 2 hours
```
Also tried at another server with SQL still same error

### Errors or Screenshots

` [Skript]     Cannot write variables to the database 'CSV' at sufficient speed; server performance may suffer and many variables will be lost if the server crashes. (this warning will be repeated at most once every 10 seconds)`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Shroobz** [comment]
don't abuse variables

**Comment by TomHo41** [comment]
And any solution?

**Comment by TheLimeGlass** [comment]
You're writing variables to the database faster than it can keep up. So don't have a while loop infinitely setting global variables. Consider using local variables or more efficient methods of data saving like metadata on entities.

**Comment by AyhamAl-Ali** [comment]
Can ypu provide the code you used that produced this error?

**Comment by TomHo41** [comment]
I can't I have over 10 skripts and can't share codes. My question is how much data can you transfer to CSV without any performance issues? I will write to players metadata.

**Comment by sovdeeth** [comment]
> I can't I have over 10 skripts and can't share codes. My question is how much data can you transfer to CSV without any performance issues? I will write to players metadata.

There's no hard limit, it depends on what machine you're running on and how your code works. We unfortunately cannot help much if you can't share code.

For now I'm going to close this as there's not much we can do with this limited information. Feel free to re-open if you are able to share your code or a reproducible snippet, or if you have new information.
