### ISSUE TITLE
Falling blocks being destroyed does not trigger on damage or on death

### ISSUE THREAD

**Issue by GibsonGYIOVdguisdo** [SkriptLang/Skript#6189]
### Skript/Server Version

```markdown
[19:30:29 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[19:30:29 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[19:30:29 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[19:30:29 INFO]: [Skript] Server Version: git-Paper-263 (MC: 1.20.2)
[19:30:29 INFO]: [Skript] Skript Version: 2.7.2 (skriptlang-github)
[19:30:29 INFO]: [Skript] Installed Skript Addons:
[19:30:29 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[19:30:29 INFO]: [Skript]  - SkBee v2.18.4 (https://github.com/ShaneBeee/SkBee)
[19:30:29 INFO]: [Skript] Installed dependencies:
[19:30:29 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

When a falling block hits the edge of a block and breaks it does not trigger either on damage or on death

### Expected Behavior

It should trigger the events

### Steps to Reproduce

Use the code below and drop a falling block onto an edge
```
on death:
    broadcast "death"

on damage:
    broadcast "damage"
```
None of them will trigger

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment]
Javadocs is being clear that [EntityDeathEvent](https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/EntityDeathEvent.html) is called for living entity. It didn’t mention such for [EntityDamageEvent](https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/EntityDamageEvent.html) but from my understanding it should only be called on living entities as well.
![IMG_2555](https://github.com/SkriptLang/Skript/assets/72163224/5c0b44af-2cd8-4e61-90c1-49fd05b6ff5e)
![IMG_2554](https://github.com/SkriptLang/Skript/assets/72163224/155417d8-d2b6-4601-b5ec-0ba899894ba4)

**Comment by GibsonGYIOVdguisdo** [comment]
Ah alright. Do you know if their is currently any event in skript that gets triggered when a falling block breaks?

**Comment by TheLividX** [comment]
https://docs.skriptlang.org/events.html?search=#endermansheepsilverfishfalling_block

**Comment by GibsonGYIOVdguisdo** [comment]
> https://docs.skriptlang.org/events.html?search=#endermansheepsilverfishfalling_block

Those events only trigger when the falling block lands properly and is placed, not when the falling block breaks and drops an item

**Comment by TheLividX** [comment]
> > https://docs.skriptlang.org/events.html?search=#endermansheepsilverfishfalling_block
> 
> Those events only trigger when the falling block lands properly and is placed, not when the falling block breaks and drops an item

there isn't a specific event for the death of a falling block

try:
https://docs.skriptlang.org/events.html?search=#drop

otherwise:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDropItemEvent.html

**Comment by GibsonGYIOVdguisdo** [comment]
> > > https://docs.skriptlang.org/events.html?search=#endermansheepsilverfishfalling_block
> > 
> > 
> > Those events only trigger when the falling block lands properly and is placed, not when the falling block breaks and drops an item
> 
> there isn't a specific event for the death of a falling block
> 
> try: https://docs.skriptlang.org/events.html?search=#drop
> 
> otherwise: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDropItemEvent.html
> 
> I don't think this is a skript issue

On drop also does not trigger when falling blocks are broken

**Comment by GibsonGYIOVdguisdo** [comment]
Closing since this isn't an issue with Skript

I managed to get code to trigger on falling block break with the following code
```

function triggerOnFallingBlockBreak(location: location):
    broadcast "block broke"

on spawn:
    if "%event-entity%" is "falling dirt block":
        add event-entity to {-FallingBlocks::*}
    else if "%event-entity%" is "dropped dirt block":
        loop {-FallingBlocks::*}:
            if loop-value is dead:
                remove loop-value from {-FallingBlocks::*}
                triggerOnFallingBlockBreak(event-location)

on falling block land:
    if {-FallingBlocks::*} contains event-entity:
        remove event-entity from {-FallingBlocks::*}
```
