### ISSUE TITLE
Decoration Aliases: Error in short grass

### ISSUE THREAD

**Issue by NemusCraft** [SkriptLang/Skript#6235]
### Bug Description

I found a error when trying to reload aliases for just purpose and it says "minecraft:grass is not valid ID"

### Expected Behavior

No errors for aliases

### Steps to Reproduce

1. Do /sk reload aliases
2. Wait
3. And boom you see the error in aliases

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/95968788/364d9c6b-5077-4234-8329-ccb8640cee00)

### Related file:
https://github.com/SkriptLang/skript-aliases/blob/0884ede0fdf69e914b944500d9f24f1c000a90a2/decoration.sk

**Comment by NemusCraft** [comment]
ahhhhhh why does nobody respond

**Comment by TheLimeGlass** [comment]
rip

**Comment by NemusCraft** [comment]
![image](https://github.com/SkriptLang/Skript/assets/95968788/6780e50b-7dc4-433e-b10f-223f4e20fbca)
mistake was found in line 183

**Comment by DelayedGaming** [comment]
Minecraft renamed it so it was erroring when Skript is used in newer versions of Minecraft server.

**Comment by APickledWalrus** [comment]
This was fixed a while ago in https://github.com/SkriptLang/skript-aliases/pull/105
