### ISSUE TITLE
Added support for Folia

### ISSUE THREAD

**Issue by PTPAAA** [SkriptLang/Skript#6247]
### Suggestion

Added support for Folia

### Why?

Folia is currently performing well and is the best tool for large survival servers, and the adaptation of this plugin will make the folia ecosystem even better, allowing server managers to avoid buying expensive high-clock CPU servers

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by DelayedGaming** [comment]
I’m looking for this support more worth doing so when #6246 is merged.

**Comment by TheLimeGlass** [comment]
https://github.com/SkriptLang/Skript/tree/feature/folia

**Comment by AyhamAl-Ali** [comment]
WIP #5645

**Comment by PTPAAA** [comment]
@TheLimeGlass Does this work on folia?

**Comment by TheJoshue** [comment]
Any news?

**Comment by sovdeeth** [comment]
Nothing substantial has changed since this issue.

**Comment by FemBoysAreCute** [comment]
@NotSoDelayed so?

**Comment by jovanstar** [comment]
It will be added soon?

**Comment by Pikachu920** [comment]
> It will be added soon?

my personal belief is that we are unlikely to ever see Skript support folia. even if it did, it would likely be a totally different codebase and existing scripts largely would not be backwards compatible.
