### ISSUE TITLE
Missing lang enum constant

### ISSUE THREAD

**Issue by Lorafen223** [SkriptLang/Skript#6248]
### Skript/Server Version

```markdown
Latest Skript, latest spigot 1.20.4
```

### Bug Description

Missing lang enum constant

### Expected Behavior

[latest.log](https://github.com/SkriptLang/Skript/files/13759981/latest.log)

### Steps to Reproduce

I don't know why this happens

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Fixed in https://github.com/SkriptLang/Skript/pull/6227
