### ISSUE TITLE
[2.8-dev] #5815 broke aliases comparisons

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#6251]
### Skript/Server Version

```markdown
[12:28:04 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[12:28:04 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[12:28:04 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[12:28:04 INFO]: [Skript] Server Version: git-Paper-332 (MC: 1.20.4)
[12:28:04 INFO]: [Skript] Skript Version: 2.8.0-dev (selfbuilt-unknown)
[12:28:04 INFO]: [Skript] Installed Skript Addons:
[12:28:04 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[12:28:04 INFO]: [Skript]  - skript-reflect v2.4-beta1 (https://github.com/SkriptLang/skript-reflect)
[12:28:04 INFO]: [Skript]  - SkBee v3.1.0 (https://github.com/ShaneBeee/SkBee)
[12:28:04 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

When using an itemtype aliases that has more than one item internally the comparator class can no longer tell if it's valid. You get forced to add an additional `or...` to resolve the errors

### Expected Behavior

Skript to only error when using `player's tool is all swords` rather than `player's tool is any sword`

### Steps to Reproduce

Use any comparison of `any...` with an aliases containing more than one item

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/81952476/037461fd-d6c5-4553-9f9d-759d8ab469d1)

### Other

Before anyone ask, this build from the screenshot was tested on both the version prior to the pr and the pr in question.
Before this pr the error didn't exist and worked fine, with this pr added the error appeared.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Use any sword contains player's tool. It's properly erroring now in 2.8. You cannot compare one item to many. Skript cannot do that from ClassInfos.

**Comment by Fusezion** [comment]
Said on discord, but will put here for people, I strongly disagree on your statement. `contains` is meant for exact matching this is the most basic of basic tbh.

you don't do `any sword contains player's tool` you do `player's tool is any sword`, `any sword` is not a list it's a single value 
well is currently should technically be an or list. That's a whole other issue tho. `every sword` and `all swords` are list but are a single value. That's the only reason I see this error even having a reason to exist.

The issue is `player's tool is any sword` is treated like `player's tool is every sword`. If we want this error to stay we should first fix the fact `player's tool is diamond and emerald` doesn't error like above and fix the comparisons for `any...`. Skript couldn't care less for and/or comparisons as there's nothing internally separating them properly.

**Comment by Fusezion** [comment]
ended up accidently learning this is a very weird bug to me now. so it's weird comparisons
```applescript
set {_pants} to leggings of player
{_pants} are any leggings # this will not cause a error
# however
leggings of player are any leggings # this will cause an error
```

this seems related to an issue I had back in september when comparators aren't registered for some types.

expression compared against literal fails
variable compared against literal succeeds

*screenshot from the issue back then*
![image](https://github.com/SkriptLang/Skript/assets/81952476/8e353c9e-f14f-4fa3-8ea1-af37079021f3)
