### ISSUE TITLE
While: ... Then: ...

### ISSUE THREAD

**Issue by JakeGBLP** [SkriptLang/Skript#6258]
### Suggestion

Add any/all to while loop
ex:
```applescript
while all:
    player is online
    player is op
    getGroupID(player) = "OWNER"
then:
    # something
```

### Why?

It's handy and removes the need to use separate functions or do like this:
```applescript
while true is true:
    if any:
        player doesn't have space for {_item}
        {_counter} >= maximum stack size of {_item}
    then:
        stop loop
    # do stuff
```
> By Fusezion

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
I don't love the usage of `then` for conditions it makes sense to me but while loops it just feels wrong.
syntax for this type of thing would need to be
```
[:do] while <.+>:
[:do] while [all|any:(at least one|any)]:
```
much like how it is for conditionals

**Comment by sovdeeth** [comment]
It could be nice to do 
```
while:
    xyz
do:
   abc
```
and
```
do:
   abc
while:
   xyz
```

**Comment by hapily04** [comment]
https://github.com/SkriptLang/Skript/issues/5883 exists

**Comment by sovdeeth** [comment]
Ah thanks I'll mark this as duplicate.
