### ISSUE TITLE
Missing lang enum constant

### ISSUE THREAD

**Issue by LohsMC** [SkriptLang/Skript#6264]
### Skript/Server Version

```markdown
[Skript]: Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript]: Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript]: Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript]: Server Version: 3999-Spigot-5c76b18-2e88514 (MC: 1.20.4)
[Skript]: Skript Version: 2.7.3 (skriptlang-github)
[Skript]: Installed Skript Addons:
[Skript]: - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[Skript]: - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
[Skript]: - MorkazSk v1.3
[Skript]: - SkBee v2.18.4 (https://github.com/ShaneBeee/SkBee)
[Skript]: Installed dependencies: None
```

### Bug Description

Right clicking/opening a chest/barrel now shows an error? I cannot do on right click: if event-inventory is barrel: cancel event anymore, it worked completely fine yesterday but today it breaks as I switched from 1.20.2 to 1.20.4.

### Expected Behavior

I made it cancel event but now it completely disregards that and just opens the barrel

### Steps to Reproduce

Installed 1.20.4, once I open any storage type, it sends that error. Even if it doesn't have code linked to it, it will still say the error.

### Errors or Screenshots

[Skript]: Missing lang enum constant for 'inventory types.CRAFTER'

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
This is high priority by the way team.

**Comment by LohsMC** [comment]
Do I wait for a new release or patch or does it automatically merge with the current one?

**Comment by APickledWalrus** [comment]
You will have to wait for the next release, but the 2.8.0 release is planned for January 15. Pre-relese builds will begin on January 1st. Though the issue you mention should not be caused by this. Try doing something like `if type of event-inventory is barrel inventory`

**Comment by LohsMC** [comment]
By the way, when Skript starts it gives the same error:
![image](https://github.com/SkriptLang/Skript/assets/103527555/b8652d19-337e-434e-bf70-2f900c62037c)
or when another Skript addon starts it also does or when a skript loads like here:
![image](https://github.com/SkriptLang/Skript/assets/103527555/dc47aa98-ef1e-4151-81fe-6e710e898987)

**Comment by APickledWalrus** [comment]
Yeah it's a bit spammy due to how the system works unfortunately. It should not cause any errors with your Skript though (the lines it references may not actually be problematic)

**Comment by LohsMC** [comment]
Oh yeah, sorry about that, it does work. Anyway thank you for your time and I will await for new release.
