### ISSUE TITLE
When you right click under a block with a water bucket, the breaking event is triggered.

### ISSUE THREAD

**Issue by ashtre1** [SkriptLang/Skript#6268]
### Skript/Server Version

```markdown
server version: 1.20.2
skript version: 2.7.3
```

### Bug Description

When you right click under a block with a water bucket, the breaking event is triggered.
(You should spam with bucket to under the block)
![image](https://github.com/SkriptLang/Skript/assets/82036955/c10ae622-1523-41e3-97e0-3e7fef6e3c72)

### Expected Behavior

Will not be triggered

### Steps to Reproduce

`on break of any ore:
	if getGörev(player) is 2:
		if tool of the player is not enchanted with silk touch:
		    send "mined" to event-player`

They complete the breaking event without breaking the blocks and complete the tasks.

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/82036955/2322e770-c97b-4ef8-bc96-287e51c240fb)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Cannot replicate on 1.20.2, 2.7.3
![image](https://github.com/SkriptLang/Skript/assets/10354869/145df91c-3ae0-43cf-a287-6dbae52501ea)

Can you please provide the full output of `/sk info`?

**Comment by ashtre1** [comment]
![image](https://github.com/SkriptLang/Skript/assets/82036955/29dd0fca-d215-4109-bfb1-cfe52dd05f19)

**Comment by sovdeeth** [comment]
Do you mind trying without addons, and if possible, providing a video of it occurring?

**Comment by ashtre1** [comment]
https://youtu.be/SSOPyB7TNZ0

**Comment by ashtre1** [comment]
I used 2.7.2 here, but I have the same problem in 2.7.3.

**Comment by sovdeeth** [comment]
Ah ok I can replicate it. It seems dependent on the angle and position you place the bucket at.

**Comment by sovdeeth** [comment]
Lines 114-119 of EvtBlock seem to be incorrect on both 1.20.2 and 1.19.4 paper. More testing should be done on prior versions, but it seems like this code is both unnecessary and causing incorrect results:
```
else if (e instanceof PlayerBucketFillEvent) {
	PlayerBucketFillEvent playerBucketFillEvent = ((PlayerBucketFillEvent) e);
	Block relative = playerBucketFillEvent.getBlockClicked().getRelative(playerBucketFillEvent.getBlockFace());
	item = new ItemType(relative);
	blockData = relative.getBlockData();
}
```
