### ISSUE TITLE
Visible Command Parameter Types and Identifier Command Argument

### ISSUE THREAD

**Issue by aaaeeeMC** [SkriptLang/Skript#6284]
### Suggestion

Visible Command Parameter Types: while typing a command, you can see the type of the parameter you're at (it can also be modified). Example: you type "/kick (player)", now it shows (look at the text above the next parameter in the image below) above your parameter.
Identifier Command Argument: A new command argument, <(entity|player) identifier>. In those parameters you add @ e, @ p, @ s, etc. with nbt as well. Works just like vanilla minecraft commands!

Visible Command Parameter Types Screenshot Example:
![Screenshot 2024-01-02 015910](https://github.com/SkriptLang/Skript/assets/86488606/b9af6e58-73e4-45d3-ad81-0856f0af88cf)

Identifier Command Argument Screenshot Example:
![Screenshot 2024-01-02 020430](https://github.com/SkriptLang/Skript/assets/86488606/af80a91a-280b-4dd7-86c2-09bb50d7dc11)

### Why?

I'm trying to work with command blocks for a minecraft server, these 2 features would be really helpful. I'll be sure to post more suggestions, I had A LOT of suggestions before but I forgot, I will post them when I remember.

### Other

Good luck with the development.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
Duplicate: #1600 #2155 #3894
