### ISSUE TITLE
Plugin Update For 1.20.4

### ISSUE THREAD

**Issue by Fiber-Official** [SkriptLang/Skript#6295]
### Suggestion

Pls update the plugin to support minecraft version 1.20.4 without any bugs plss fast

### Why?

Because I need it for my server 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by EquipableMC** [comment]
It should already support 1.20.4.

**Comment by TheLimeGlass** [comment]
2.8.0-pre1 works fully on 1.20.4 but doesn't have 1.20.4 features yet.

**Comment by AyhamAl-Ali** [comment]
If you find a specific bug please report it other than that we're working on adding MC 1.20.x features to Skript
