### ISSUE TITLE
Performances issue with offline player

### ISSUE THREAD

**Issue by WarnDa** [SkriptLang/Skript#6301]
### Skript/Server Version

```markdown
[08:55:35 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[08:55:35 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[08:55:35 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[08:55:35 INFO]: [Skript] Server Version: git-PufferfishPlus-"a9f972b" (MC: 1.20.1)
[08:55:35 INFO]: [Skript] Skript Version: 2.7.3 (skriptlang-github)
[08:55:35 INFO]: [Skript] Installed Skript Addons: 
[08:55:35 INFO]: [Skript]  - SkQuery v4.1.9
[08:55:35 INFO]: [Skript]  - SkBee v2.18.4 (https://github.com/ShaneBeee/SkBee)
[08:55:35 INFO]: [Skript]  - ItemsAdder v3.6.3-beta-6 (devs.beer)
[08:55:35 INFO]: [Skript] Installed dependencies: 
[08:55:35 INFO]: [Skript]  - Vault v1.7.3-b131
[08:55:35 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

I'm using a skript when player vote, to give them rewards even if they are offline

### Expected Behavior

It shouldn't cause lag

### Steps to Reproduce

Get a skript that parse command from console using offline players

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/31826333/8a14ac0e-087d-488a-bc89-60bcf0affba0)
No other plugin appear in spark
![image](https://github.com/SkriptLang/Skript/assets/31826333/becfa8c6-7901-4d6e-a562-fde1fe6a2eb2)

### Other

Didn't get issue before on skript 2.6.4 and pufferfish 1.19.3

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by WarnDa** [comment]
Same with latest version : 
![image](https://github.com/SkriptLang/Skript/assets/31826333/9730e0e3-4363-4f68-a840-59a341fee12c)
Very annoying :/

**Comment by AyhamAl-Ali** [comment]
Can you provide the code that causes this.

**Comment by WarnDa** [comment]
`command /joueurvientdevotersite1 [<text>]:
    permission: mine.admin
    permission message: &5Nop &8» &cPas la perm!
    trigger:
        make console execute "lp user %arg 1% permission settemp vote.24h true 24h replace"
        make console execute "lp user %arg 1% permission settemp vote.site1 true 24h replace"
        make console execute "av voteexact %arg 1% site1"
        wait 1 second
        make console execute "joueurvientdevoterpinata %arg 1%"

command /joueurvientdevotersite2 [<text>]:
    permission: mine.admin
    permission message: &5Nop &8» &cPas la perm!
    trigger:
        make console execute "lp user %arg 1% permission settemp vote.24h true 24h replace"
        make console execute "lp user %arg 1% permission settemp vote.site2 true 3h replace"
        make console execute "av voteexact %arg 1% site2"
        wait 1 second
        make console execute "joueurvientdevoterpinata %arg 1%"

command /joueurvientdevotersite3 [<text>]:
    permission: mine.admin
    permission message: &5Nop &8» &cPas la perm!
    trigger:
        make console execute "lp user %arg 1% permission settemp vote.24h true 24h replace"
        make console execute "lp user %arg 1% permission settemp vote.site3 true 3h replace"
        make console execute "av voteexact %arg 1% site3"
        wait 1 second
        make console execute "joueurvientdevoterpinata %arg 1%"
		
command /joueurvientdevotersite4 [<text>]:
    permission: mine.admin
    permission message: &5Nop &8» &cPas la perm!
    trigger:
        make console execute "lp user %arg 1% permission settemp vote.24h true 24h replace"
        make console execute "lp user %arg 1% permission settemp vote.site4 true 90m replace"
        make console execute "av voteexact %arg 1% site4"
        wait 1 second
        make console execute "joueurvientdevoterpinata %arg 1%"

command /joueurvientdevoterpinata [<offline player>]:
    permission: mine.admin
    permission message: &5Nop &8» &cPas la perm!
    trigger:
        make console execute "lp user %arg 1% parent removetemp pinata"
        wait 1 second
        make console execute "lp user %arg 1% parent addtemp pinata 3h"`

**Comment by AyhamAl-Ali** [comment]
There is no such heavy use here of offlineplayer at all, the only heavy thing is the use of many console commands which is probably cuasing all this. The current code is not recommended at all, try to use an  addon that supports LuckPerms functions  directly, it should fix your issue.

**Comment by AyhamAl-Ali** [comment]
> with that you can also double check if the issue is from the offlineplayer arg or the console commands you're executing.

@WarnDa Any updates on this? have the issue been solved?

**Comment by WarnDa** [comment]
> > with that you can also double check if the issue is from the offlineplayer arg or the console commands you're executing.
> 
> @WarnDa Any updates on this? have the issue been solved?

Issue fixed itself, so seems fine !

**Comment by AyhamAl-Ali** [comment]
Good to hear.
