### ISSUE TITLE
Armor Points and Damage Effect

### ISSUE THREAD

**Issue by aaaeeeMC** [SkriptLang/Skript#6303]
### Suggestion

Currently there doesn't seem to be a condition and/or expression in skript about the armor points of an entity. Therefore, I posted this suggestion.

Armor Points: Exactly how you read it, **Armor Points**. If an entity doesn't wear any armor, they have 0 armor points.

Damage Effect Addition: An addition to the syntax of the damage effect that could look like this: | damage entity by 5 hearts ignoring 50% of armor | with the percentage being a number between 0 and 100. If it's 0%, it doesn't ignore the armor at all. If it's 100%, like always in the current damage effect, it ignores all armor and damages the entity as if it wasn't wearing any armor (0 armor points)

### Why?

With these features, players won't struggle trying to control the armor ignorance percentage in damage effects anymore.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
Is this supported by Spigot/Paper using their javadocs?

**Comment by sovdeeth** [comment]
You can already get the armor points with `armor final attribute of player` (which really needs to be swapped to `final armor attribute of player` but that's another discussion).
As far as I'm aware, Spigot/Paper don't support damaging that takes armor into account. There's always the workaround of doing a little damage and setting the real damage in the damage event.
