### ISSUE TITLE
Skript Updating

### ISSUE THREAD

**Issue by EquipableMC** [SkriptLang/Skript#6304]
### Suggestion

Prevent Skript from saying you have to update it when beta/pre-release builds are posted.

### Why?

Most of pre-release/beta builds are not recommended for production use so it would make sense to prevent skript from saying this.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
There is `release channel` in Skript's config which can filter the updates between stable and pre-releases

**Comment by EquipableMC** [comment]
Yeah but by default it's set to stable. Pre-release shouldn't fall under stable since (and even you all say it,) it's not stable and not meant for production.

**Comment by AyhamAl-Ali** [comment]
It's definitely not, unless it's bugged.

**Comment by EquipableMC** [comment]
I reproduced. The only plugins I had installed are just skript. Here is the skript output:
[19:00:28 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[19:00:28 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[19:00:28 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[19:00:28 INFO]: [Skript] Server Version: git-Paper-344 (MC: 1.20.4)
[19:00:28 INFO]: [Skript] Skript Version: 2.7.3 (skriptlang-github)
[19:00:28 INFO]: [Skript] Installed Skript Addons: None
[19:00:28 INFO]: [Skript] Installed dependencies: None 

video: https://streamable.com/f2a9od

**Comment by Fusezion** [comment]
this issue is due to skript following new release channels I mentioned this needed changed in the clockwork release pr and it seems like we just never did. 

In the past there were "beta" and "alpha" but now there's "pre", "candidate", "patch" and "stable/release". The whole system for that needs to be updated to support these changes.

**Comment by AyhamAl-Ali** [comment]
The system seems outdated a little therefore will be updated accordingly. Thank you for reporting this issue ⚡

**Comment by APickledWalrus** [comment]
Updating this to a higher priority as we do not really want to recommend unstable builds to users in the stable channel
