### ISSUE TITLE
Comma after a classinfo gets parsed within the classinfo

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#6308]
### Skript/Server Version

```markdown
2.8.0-pre1
1.20.1
```

### Bug Description

Adding a comma in a pattern after a classinfo gets included in the parsing of the ClassInfo for some reason.

### Expected Behavior

To not include the comma inside the ClassInfo parse and properly grab the classinfo.

### Steps to Reproduce

`[new] example [made [up] of] %number%, [and] %number%`

### Errors or Screenshots

`Caused by: ch.njol.skript.SkriptAPIException: No class info found for number, `

You see how it picked up the comma in the error. This should not be happening.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Can you be more specific about how exactly to reproduce this? I'm not able to do so with either an addon, or with `parsed as`.
![image](https://github.com/SkriptLang/Skript/assets/10354869/18f6cd40-48bb-4179-8c2f-dedc3f892c1b)
![image](https://github.com/SkriptLang/Skript/assets/10354869/6ff13068-6c50-4e7e-8b99-de5fa39da998)

**Comment by TheLimeGlass** [comment]
> Can you be more specific about how exactly to reproduce this? I'm not able to do so with either an addon, or with `parsed as`. ![image](https://private-user-images.githubusercontent.com/10354869/294817602-18f6cd40-48bb-4179-8c2f-dedc3f892c1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjEzOTgsIm5iZiI6MTcwNDcyMTA5OCwicGF0aCI6Ii8xMDM1NDg2OS8yOTQ4MTc2MDItMThmNmNkNDAtNDhiYi00MTc5LThjMmYtZGVkYzNmODkyYzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzMzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OTJjZDIxODZkMGFlZDI2OGY3NTI2OTE1ZjcyODllMzhmOWNmZjFiMjE3MTk3NjI4NWVlMjQ2NGUwZWJmZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7BPc0L2kiZvqt0ejmfxWIvAA3VnFSEjxc2ItmWbHICI) ![image](https://private-user-images.githubusercontent.com/10354869/294817622-6ff13068-6c50-4e7e-8b99-de5fa39da998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjEzOTgsIm5iZiI6MTcwNDcyMTA5OCwicGF0aCI6Ii8xMDM1NDg2OS8yOTQ4MTc2MjItNmZmMTMwNjgtNmM1MC00ZTdlLThiOTktZGU1ZmEzOWRhOTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzMzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MTEzYzExMzc5NDEzZWNlYWQ3YzVkNjM4YjIyODY1N2FmMTYyZjU4M2FmMzgzOTAwODRlMmZhYzM1NzYwMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7GAPZJZbzRB_B_QbtEJ12UwPWNGWlQKyJVkeiuK_QUw)

I don't think it happens in a parsed as, so don't use that to test this. It will throw an exception on addon register.

**Comment by TheLimeGlass** [comment]
I'll probably fix this later.

**Comment by sovdeeth** [comment]
> I don't think it happens in a parsed as, so don't use that to test this. It will throw an exception on addon register.

Well, it didn't error for me in my addon, so I'm not sure how else to replicate this. Can you send the file you were using when the error was generated? The stacktrace and any surrounding info would also be useful.

**Comment by TheLimeGlass** [comment]
Wasn't my coding, but I'm pretty confident I can figure out how to replicate it.

**Comment by TheLimeGlass** [comment]
I'll look at it on the weekend.

**Comment by sovdeeth** [comment]
Closing due to lack of response and inability to replicate.
