### ISSUE TITLE
[Suggestion] Coreprotect log hook

### ISSUE THREAD

**Issue by aescraftbr** [SkriptLang/Skript#631]
The title says it all - Would be nice to give the option to hook into the coreprotect system with skript. Thanks!

**Comment by bensku** [comment]
I'm not particularly interested in doing this, but sure, it would be helpful.

**Comment by xXAndrew28Xx** [comment]
Working on that right now.

**Comment by melinstagibson** [comment]
shouldnt this be in a addon instead of skript itself?
Not complaining, would love to see that added one way or the other

**Comment by xXAndrew28Xx** [comment]
Not sure, I'll just add it into Skript for now.

**Comment by HYPExMon5ter** [comment]
Andrew you should add this too ;) https://github.com/bensku/Skript/issues/652

**Comment by xXAndrew28Xx** [comment]
I'll take a look at it after I finish CoreProtect.

**Comment by HYPExMon5ter** [comment]
Okay thx <3
