### ISSUE TITLE
Cant find the right item id for red sand.

### ISSUE THREAD

**Issue by Ande651j** [SkriptLang/Skript#6320]
### Skript/Server Version

```v
on block break:
	if player's tool is diamond shovel with lore "&cExplosive":
		loop blocks in radius 1.9 of event-block:
			if loop-block is sand or 0012/1 or soul sand or dirt or grass block:
				give loop-block to player			
				set {_drops::*} to drops of block with player's tool
				set loop-block to air
				give player {_drops}
			
on break:
  set {_drops::*} to drops of block with player's tool
  set block to air
  give player {_drops::*}				



Command /enchantts:
	trigger:
		give player diamond shovel with lore "&cExplosive"
```

### Bug Description

Server version: 1.8
- SkUtilities v0.9.2
- SkQuery v4.1.6
- LeafSK v2.3.8
- UnikPay v1.0.13(not really relevant because its a plugin for a specific server!)
- WildSkript v1.8
- SkAction v1.0
- Vault v1.7.3-b131
- Skellett v1.9.8
- skript-reflect v2.3

The skripts loads in just fine but when I mine the problem occurs. It doesn't loop the red sand in my mine.

What is the right id for it? I've tried: minecraft:red_sand, 12:1 and red_sand. The skript only allows red sand but doesn't loop red sand. Just the normal sand..

### Expected Behavior

When anyone with the shovel with lore "&cExplosive" would break a block. Red sand aswell as original sand, soul sand, grass block and dirt would "loop block in radius 1.9 of event-block" when mined. But I cant find the right id for red sand.

### Steps to Reproduce

I copied my explosive pickaxe skript and switched pickaxe with shovel and changed the blocks that would loop when mined.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Ande651j** [comment]
"0012/1" is where "red sand" is supposed to go..

**Comment by Ande651j** [comment]
Skript fork?

**Comment by Ande651j** [comment]
Aight. I've downloaded it now, but now i got alot of red plugins.
![image](https://github.com/SkriptLang/Skript/assets/14166978/4b3fc9d3-79db-46dc-a07c-fde9166f9432)

**Comment by Ande651j** [comment]
Even Skript itself is red. What do I do?

**Comment by DelayedGaming** [comment]
Skript 2.7 onwards only supports Minecraft 1.13 and above, while your issue with your current Skript plugin is not our official plugin. If you wish to seek help from the custom Skript jar you have here which works on 1.8, you should contact the author of this custom Skript jar.

**Comment by Ande651j** [comment]
Aight. Do you know who it is or where I can find out who. I got Skript 2.6.5

**Comment by Ande651j** [comment]
Or if change the version 1.13 or above. Would that break my server in terms of skripts and builds?

**Comment by DelayedGaming** [comment]
https://github.com/Matocolotoe/Skript-1.8/issues
