### ISSUE TITLE
Skript allows you to divide by a date.

### ISSUE THREAD

**Issue by AsleeppMC** [SkriptLang/Skript#6321]
### Skript/Server Version

```markdown
[Skript] Server Version: git-Purpur-2062 (MC: 1.20.1)
[Skript] Skript Version: 2.7.3 (skriptlang-github)
[Skript] Installed Skript Addons: 
[Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[Skript]  - skript-particle v1.2.0 (https://github.com/sovdeeth/skript-particle)
[Skript]  - skript-reflect v2.3.1-for-Skript-2.7 (https://github.com/TPGamesNL/skript-reflect)
[Skript]  - SkBee v3.0.1 (https://github.com/ShaneBeee/SkBee)
[Skript]  - ItemsAdder v3.6.3-beta-5 (devs.beer)
[Skript] Installed dependencies: 
[Skript]  - Vault v1.7.3-b131
[Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

for some reason, skript allows you to divide by a date disguised in a variable (results in infinity)

### Expected Behavior

for skript to error when trying that.

### Steps to Reproduce

```
spawn arrow 1 meter above player
set {_v} to vector from yaw player's yaw and pitch player's pitch
wait 1 tick
push last spawned arrow {_v} at speed 2
set {_n} to now
wait 1 second
set {_temp} to (distance between the player and last spawned arrow)
set {_tlimit} to ({_temp} / {_n} * 0.1)
broadcast {_tlimit}
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by erenkarakal** [comment]
skript doesn't know the type of the variable while parsing the script.

**Comment by AsleeppMC** [comment]
i mean, it really should though...

**Comment by DelayedGaming** [comment]
Currently no, but there’s a PR for it: #5457

**Comment by sovdeeth** [comment]
To give a coherent answer, Skript doesn't actually allow this. What happens is that it sees that the variable is not a number and replaces it with 0. Division by 0 is always infinity.
In 2.8, this will be reworks so any invalid operation will always return <none>.
