### ISSUE TITLE
Equip should give the items to players if not armor

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#6322]
### Suggestion

The equip effect should give the item to players if the item is not armor, otherwise if it is equip, it should apply appropriately. If the user wants to set the helmet, they should set the helmet.

### Why?

This allows for one syntax to do all the handling, it's like a custom give effect, but if it's armor, it'll apply it. Making it easier to give a list of items to a player, so you don't have to separate applying to armor, and giving.

### Other

The equip effect currently sets the helmet if the item is not armor.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Efnilite** [comment]
after some discussion, it seems the team is against this as it may cause confusing behaviour. the currently existing syntaxes to achieve this should be used instead
