### ISSUE TITLE
2.8.0-pre2 - Loop Trouble: Loop-Entities

### ISSUE THREAD

**Issue by aaaeeeMC** [SkriptLang/Skript#6324]
### Skript/Server Version

```markdown
[20:03:35 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:03:35 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[20:03:35 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[20:03:35 INFO]: [Skript] Server Version: git-Paper-382 (MC: 1.20.4)
[20:03:35 INFO]: [Skript] Skript Version: 2.8.0-pre2 (skriptlang-github)
[20:03:35 INFO]: [Skript] Installed Skript Addons:
[20:03:35 INFO]: [Skript]  - SkBee v3.1.0 (https://github.com/ShaneBeee/SkBee)
[20:03:35 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

I was just chilling in my local hosted server, transferring some skript files from another server. When all of a sudden, I encountered an error. Inside of a loop where I looped all zombies in a world with the filter "input's display name is "display name"", there were lots of errors.
![Screenshot 2024-01-12 195825](https://github.com/SkriptLang/Skript/assets/86488606/adfe13a5-707e-4e61-9186-2c3f697d4c7f)
The reason why loop-value is mixed with loop-entity in the loop is because originally it was all loop-entity, not loop-value. I changed it to loop-value trying to fix the error, but it didn't work, so just think of all the loop-values as loop-entity, the errors are the same regardless. The issue is that Skript is confused about "loop-entity" when it shouldn't be, and you'll see why it shouldn't give that error in the code provided in the "Steps to Reproduce" zone.

### Expected Behavior

I was trying to check for all zombies in a world with a specific display name, and teleporting them to a zombie boss I was working on. There weren't any errors on 2.7.x, so this 100% is a 2.8.0-prerelease bug.

### Steps to Reproduce

![image](https://github.com/SkriptLang/Skript/assets/86488606/dd35166c-09fc-4313-a5cc-5d708d4a9179)
To actually test it, you can make a temporary testing command and in the trigger: section you can add this. Make sure you're on the 2.8.0-pre2 version of skript.

Any questions?
1. What is {_z}? It's a variable that identifies the zombie boss. It's the zombie boss himself.
2. Why do you use loop-value and loop-entity for the same thing?! Like I said in the Bug Description zone, I changed some loop-entity instances to loop-value to see if I still get an error on those lines. I'm too lazy to change them back to normal, heh.
3. Why are you looping all those blocks and adding them to a list variable then teleport loop-entity to a random element out of that list variable? It's my way of teleporting those loop-entities around the boss in a nice way that I like.

### Other

This is a quick post.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
My initial guess is that it's somehow parsing like `(all zombies in {_p})'s word`. Can you try either seeing if `loop-world` parses, or if adding () around `{_p}'s world` works?

**Comment by APickledWalrus** [comment]
initial testing indicates sovde's suspicions are correct. these errors do seem to be present in 2.7 as well - there is no simple fix here. i believe using `loop all zombies in world of {_z}` will work too.

**Comment by aaaeeeMC** [comment]
> My initial guess is that it's somehow parsing like `(all zombies in {_p})'s world`. Can you try either seeing if `loop-world` parses, or if adding () around `{_p}'s world` works?

i did not touch the loop line at all, it's the exact same as in the original server that i am transferring files from. the original server has skript 2.7.3 and there were no errors and it was working fine

**Comment by aaaeeeMC** [comment]
> My initial guess is that it's somehow parsing like `(all zombies in {_p})'s world`. Can you try either seeing if `loop-world` parses, or if adding () around `{_p}'s world` works?

yup adding parantheses around {_z}'s world worked. i guess we can close this case now, sorry. in the original server the loop line was "loop all zombies in world("myworld") ..." and now i changed it to {_z}'s world and i just had to add parantheses.
