### ISSUE TITLE
subtraction of index of event-slot

### ISSUE THREAD

**Issue by NiewiadomyYYXX** [SkriptLang/Skript#6326]
### Skript/Server Version

```markdown
Server Version: git-Paper-196 (MC: 1.20.1)
Skript Version: 2.8.0-pre2 (skriptlang-github)
Installed Skript Addons:
- Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
- skript-yaml v1.5
- skUtilities v0.9.2 (https://tim740.github.io/)
- skRayFall v1.9.28 (https://sk.rayfall.net/)
- SkQuery v4.1.10
- SkBee v3.0.1 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies:
[Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

u cannot subtraction number from index of event-slot it use to work in 2.7.x skript

### Expected Behavior

it work

### Steps to Reproduce

`					set {_p} to index of event-slot - 9 # dont work

					set {_p} to index of event-slot  #work
					set {_p} to {_p} - 9 `

### Errors or Screenshots

[15:54:13 INFO]: Line 782: (npctrader.sk)
[15:54:13 INFO]:     subtraction can't be performed on a type and an integer
[15:54:13 INFO]:     Line: set {_p} to index of event-slot - 15

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
You can do `(index of event-slot) - 15`, but I'd think that Skript should be smart enough to do this natively, so keeping this open as a bug.
