### ISSUE TITLE
Player's tool doesn't work

### ISSUE THREAD

**Issue by SweatyBufalo** [SkriptLang/Skript#6337]
### Skript/Server Version

```markdown
2.8.0
```

### Bug Description

Player's tool is not detecting wether the tool is the right tool. The image below shows my skript but it returns false even when the player uses a hoe. 

### Expected Behavior

Should continue with the skript not return false as I am using a hoe

### Steps to Reproduce

	if {_crop} is melon slice or pumpkin:
		if {_p}'s tool is a hoe:
			send "{@prefix} {@color_error}You must be using an axe" to {_p}
			playSound({_p}, "no")
			return false
	else:
		if {_p}'s tool isn't a hoe:
			send "{@prefix} {@color_error}You must be using a hoe" to {_p}
			playSound({_p}, "no")
			return false[](url)

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/145505267/e62d8c60-82d3-44b6-bfe0-0b134e15b164)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Cannot replicate with `message "Yes" if player's tool is a hoe`

I believe you have the same error message for if they are or not holding a hoe.

**Comment by sovdeeth** [comment]
We need a fully valid code snippet that shows the error. For all we know, you simply haven't set `{_p}`. Please provide a full snippet that reproduces the error, and we'll try to investigate.
