### ISSUE TITLE
Remove the requirement to add "to player" at the end of send commands

### ISSUE THREAD

**Issue by Elijahlmao** [SkriptLang/Skript#6338]
### Suggestion

Remove the requirement to add "to player" at the end of send commands

### Why?

Imagine people like me having to sit down and go through several skript files and add "to player" at the end of each "message "x and y" commands. This worked fine previously, why is it necessary now?

### Other

🥺

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by DelayedGaming** [comment]
It is still optional based on the 2.8.0 branch. Can you provide your affected code and `/sk info`?
![IMG_3067](https://github.com/SkriptLang/Skript/assets/72163224/fbd696f6-dbd2-4979-9c26-c25d827f16b4)

**Comment by Elijahlmao** [comment]
`on leftclick holding shears:
    if event-world is "MinerWorld":
        if player's gamemode is survival:
            cancel event
            remove 1 of player's tool from player's tool
            play sound "item.shield.break" to player
            message "&cYou slammed your shears into the ore, but it broke on impact."`
            
            
![image_2024-01-17_012905319](https://github.com/SkriptLang/Skript/assets/137965197/3468ee3c-f57e-474b-8c29-8fa7c78dbf41)



I downgraded my version to 2.7.3, but it happened on Skript 2.8.0 before I downgraded.

**Comment by erenkarakal** [comment]
its a new change in 2.8, if there are multiple entities in an event it makes sure the user is sending it to the right person to avoid confusion, it is technically still optional but depends on the event.

**Comment by sovdeeth** [comment]
> ```applescript
> on leftclick holding shears: 
>     if event-world is "MinerWorld": 
>         if player's gamemode is survival: 
>             cancel event 
>             remove 1 of player's tool from player's tool 
>             play sound "item.shield.break" to player 
>             message "&cYou slammed your shears into the ore, but it broke on impact."```
> ```

This error is intentional, because your code has a bug. If the player clicks on an entity while holding shears, the message will be sent to the clicked entity.
