### ISSUE TITLE
Location offsetting with vectors broke after v2.8.0

### ISSUE THREAD

**Issue by Idani1** [SkriptLang/Skript#6348]
### Skript/Server Version

```markdown
Server Version: git-Paper-381 (MC: 1.20.4)
Skript Version: 2.8.0 (skriptlang-github)
Installed Skript Addons:
- Skent v3.2.2
- skRayFall v1.9.28 (https://sk.rayfall.net/)
- SkQuery v4.1.10
- SkBee v3.1.0 (https://github.com/ShaneBeee/SkBee)
Installed dependencies:
- Vault v1.7.3-b131
- WorldGuard v7.0.9+5934e49
```

### Bug Description

Title explains it.
`[location[s]] %locations% offset by %vectors%` always returns the same location

### Expected Behavior

2.7.3: offsets by the correct coordinates
2.8.0: no offset at all
(Referring to the function below)

### Steps to Reproduce

```
function dungeonGeneratePressurePlate(loc: location, previoustype: text):
	set {_x} to 0
	set {_y} to 0
	set {_z} to 0
	if {_previoustype} is "wood":
		set {_x} to 3
		set {_z} to 13
	else if {_previoustype} is "skeleton_king":
		set {_x} to -3
		set {_z} to 31
	else if {_previoustype} is "village":
		set {_x} to -4
		set {_z} to 14
	else if {_previoustype} is "mineshaft":
		set {_z} to 20
	else if {_previoustype} is "default":
		set {_z} to 5
	set {_loc} to {_loc} offset by vector from {_x}, {_y}, {_z}
	set block at {_loc} to gold pressure plate
```

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Replicated, preliminary testing suggests that the vector from direction expression is conflicting: `vector[s] [from] %directions%`. 
For now, use the vector function `vector({_x}, {_y}, {_z})`, but need to add a fix to prevent the from direction expression from parsing for an expression list of length 3, or make it singular only (honestly I don't like it being plural very much tbh `vector from player's facing, north` is pretty rough.)
