### ISSUE TITLE
Skript on (Ketting) 1.20.1

### ISSUE THREAD

**Issue by C0D3-M4513R** [SkriptLang/Skript#6351]
### Skript/Server Version

```markdown
Running Ketting 1.20.1 (dev version) [I am a dev]
Running Skript 2.8.0
```

### Bug Description

https://github.com/SkriptLang/Skript/blob/b9f89c14c6cd7859b96a0c6a7d791fdb455c09d6/src/main/java/ch/njol/skript/Skript.java#L1160 contains the method handle to `MinecraftServer.isRunning()`.

Instead it points to `MinecraftServer.getLocalIp()`, which results in an error, when calling `Skript.isServerRunning()`, because `IS_RUNNING.invoke(MC_SERVER)` returns a `java.lang.String`, not a `boolean`. 

This is because Minecraft's 1.20.1 mangled name for `MinecraftServer.isRunning` is back to `v`. 

### Expected Behavior

The plugin shuts down cleanly, without needing to provide `boolean isStopping();` in `org.bukkit.Server`.

### Steps to Reproduce

Build ketting and remove the `boolean isStopping();` method in `org.bukkit.Server`.
Put Skript into the plugin folder.
Run and stop the server.
Observe an error whilst shutting the Server down.

### Other

![image](https://github.com/SkriptLang/Skript/assets/28912031/6ead9d5a-023e-4b4a-aaf4-1e7fadf68cde)
(yeah, this shows 2.7.3, but I also validated, that this happens on 2.8.0)
![image](https://github.com/SkriptLang/Skript/assets/28912031/30f192fd-0f5b-4868-bbae-abbe8b5baaf6)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Should be simply adding a case for 1.20. Probably should refactor to a switch instead of a bunch of ternaries.
Feel free to make the pr yourself.

Do note that Skript doesn't support Forge servers so you may encounter other issues while running Skript that we can't or won't fix.

**Comment by C0D3-M4513R** [comment]
Yeah. I am aware of that. e.g. this here. dunno why this happens or whose issue it is...
![image](https://github.com/SkriptLang/Skript/assets/28912031/2cb2752c-cec8-4cce-bd42-6c2b819b429f)

**Comment by BaeFell** [comment]
> Yeah. I am aware of that. e.g. this here. dunno why this happens or whose issue it is... ![image](https://private-user-images.githubusercontent.com/28912031/298309696-2cb2752c-cec8-4cce-bd42-6c2b819b429f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODg0NzksIm5iZiI6MTcwNTc4ODE3OSwicGF0aCI6Ii8yODkxMjAzMS8yOTgzMDk2OTYtMmNiMjc1MmMtY2VjOC00Y2NlLWJkNDItNmMyYjgxOWI0MjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIyMDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZDc4ZmZmZmIxNDQzODhiZDA5ZDFhMjQyZmEzYjkzOTMyMzI2MTc2MDI1YmZlZDFiZDc3ZjY3MDkyZWE5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.17OK3dP6tEr9EvLjmetGGtxO46pmkcycdEoFitFfD7k)

You need to update skript-reflect and Skript to the latest versions.

**Comment by C0D3-M4513R** [comment]
> > Yeah. I am aware of that. e.g. this here. dunno why this happens or whose issue it is... ![image](https://private-user-images.githubusercontent.com/28912031/298309696-2cb2752c-cec8-4cce-bd42-6c2b819b429f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODg0NzksIm5iZiI6MTcwNTc4ODE3OSwicGF0aCI6Ii8yODkxMjAzMS8yOTgzMDk2OTYtMmNiMjc1MmMtY2VjOC00Y2NlLWJkNDItNmMyYjgxOWI0MjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIyMDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZDc4ZmZmZmIxNDQzODhiZDA5ZDFhMjQyZmEzYjkzOTMyMzI2MTc2MDI1YmZlZDFiZDc3ZjY3MDkyZWE5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.17OK3dP6tEr9EvLjmetGGtxO46pmkcycdEoFitFfD7k)
> 
> You need to update skript-reflect and Skript to the latest versions.

let's move this to #6353
