### ISSUE TITLE
Bug With Middle Click

### ISSUE THREAD

**Issue by xLoyals** [SkriptLang/Skript#6362]
### Skript/Server Version

```markdown
1.20.2 Paper
Skript 2.7.2
```

### Bug Description

Just noticing that when in a skript-gui i try to use my middle mouse button in creative, (to clone the stack) it doesnt work unless the actual binded key is middle mouse button, (i typically keep my pick block(middle mouse button) binded to the key C) and it doesnt allow me to clone the items if i use my normal keybind. It forces me to have to change my keybind to middle mouse button and then clone the item.

### Expected Behavior

Clone items normally, (i noticed the click types were apart of skript itself and not an addon)

### Steps to Reproduce

if click type is middle mouse button:
                broadcast "yo"

### Errors or Screenshots

no errors

### Other

i do not.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by EquipableMC** [comment]
Can you try with 2.8?

**Comment by xLoyals** [comment]
i found a work around, if you do if player's click type is unknown: it works as it should, so ill do it like that for now. and i dont think the syntax ever changed in the updates related to click types so i would guess it also wouldnt work in 2.8

**Comment by EquipableMC** [comment]
Still, we would need to know if it's an issue in 2.8. You having 2.7.2 doesn't really help us.

**Comment by sovdeeth** [comment]
Click actions and events are nearly completely unreliable when the player is in creative mode, due to how Minecraft works. I don't think there's anything skript can do about that.

If anyone has other info on this, please feel free to reopen.
