### ISSUE TITLE
... to all players where [] breaks the parser (I think?)

### ISSUE THREAD

**Issue by WhoCutTheCheese** [SkriptLang/Skript#6368]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Purpur-2128 (MC: 1.20.4)
[Skript] Skript Version: 2.8.0 (skriptlang-github)
[Skript] Installed Skript Addons:
[Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[Skript]  - MongoSK v2.3.0 (https://github.com/Romitou/MongoSK)
[Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[Skript]  - SkQuery v4.1.10
[Skript]  - SkBee v3.1.0 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies:
[Skript]  - Vault v1.7.3-b131
[Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

So I was trying to send a message to all players with a certain permission, and that message had some timespan stuff in it that I made a typo in. Well I didn't notice the typo because when I reloaded the script it didn't error, but weirdly the code I was working on just completely stopped.

So because I just added that message, I tried removing the message and it worked! So then I tried just looping all players and sending it to loop player, only then did my error trip the parser.
**I just noticed!** It does error to console.

### Expected Behavior

The expected behavior was for it to throw an error.

### Steps to Reproduce

```
command test:
	trigger:
		send "Testing %diference between (12 hours from now) and now%" to all players where [player input has permission "test.test"]
```
Just try that on the latest version of Skript and it won't throw an error, BUT it DOES error to console!

### Errors or Screenshots

https://hastebin.skyra.pw/rebosusetu.md

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by ShaneBeee** [comment]
that error is from SkQuery, not Skript.

**Comment by WhoCutTheCheese** [comment]
**OH**
