### ISSUE TITLE
Unable to detect biome at player location

### ISSUE THREAD

**Issue by Acult** [SkriptLang/Skript#6370]
### Skript/Server Version

```markdown
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §rServer Version: §31.16.5-1212 (MC: 1.16.5)
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §rSkript Version: §32.8.0 (skriptlang-github)
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §rInstalled Skript Addons: §3
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §r - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §r - SkUniversal v2.13
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §r - SkArclight v1.0.0 (https://github.com/ShaneBeee/SkArclight)
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §r - skRayFall v1.9.28 (https://sk.rayfall.net/)
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §r - SkBee v1.15.3 (https://github.com/ShaneBeee/SkBee)
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §r - SkJade v1.4.3 (https://www.github.com/Ankoki-Dev/SkJade)
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §rInstalled dependencies: §3
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §r - Vault v1.7.3-b131
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §r - WorldGuard v7.0.5+3827266
29.01 11:19:39 [Server] Server thread/[INFO] §7[§6Skript§7] §r - GriefPrevention v16.17.1-2b69191
```

### Bug Description

Internal error throwed when checking biome at location of player, while being in a dimension different than world.
Note that skript recognizes such dimension, as i can teleport to it through skript teleport when i specify world(""world name") on the location function

### Expected Behavior

It should tell me the biome at my current location

### Steps to Reproduce

Latest Skript, latest SkArclight
Mohist 1.16.5
Any mod which adds new biomes

command /checkbiome:
    trigger:
         send biome at player to player

### Errors or Screenshots

https://pastebin.com/eZuD4seF

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
We'll take a look, but it's extremely likely that we won't be doing anything to solve this, as Skript currently doesn't support running on Mohist.

**Comment by sovdeeth** [comment]
This is because Mohist inserts new values into the Biome enum and Skript does not have lang nodes for them. This is not something we can or will completely fix, but we can at least prevent the stacktrace and return the raw enum name instead.

**Comment by Acult** [comment]
thanks a lot
