### ISSUE TITLE
Condition "Event Cancelled" works strangely or not at all

### ISSUE THREAD

**Issue by noySq** [SkriptLang/Skript#6380]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-405 (MC: 1.20.4)
[Skript] Skript Version: 2.8.0 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

When you check if an event is canceled, the "Event Cancelled" condition might not always accurately show that it's canceled, even if it is

### Expected Behavior

The code below isn't supposed to send any message to the chat.

### Steps to Reproduce

```
on break:
    if event isn't cancelled:
        send "Not cancelled" to player

on break:
    cancel event
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Lotzyprod** [comment]
use `on %event% with priority %priority%`

**Comment by sovdeeth** [comment]
This is intended behavior. Skript runs your event in order of loading, so since the first break is loaded before the second, it runs before the second one cancels the event.
