### ISSUE TITLE
Remove message when using %player% in variables

### ISSUE THREAD

**Issue by GGnoobjeL** [SkriptLang/Skript#6406]
### Suggestion

Just remove it.

### Why?

It crashes game when you have big skript.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by DelayedGaming** [comment]
Suggestion denied -- Server is not killed with 1000 lines of these in my $1 server, at max increases load time.
![image](https://github.com/SkriptLang/Skript/assets/72163224/cf9509b3-7ecc-4980-90cc-8e1edba4015e)

Jokes aside, https://github.com/SkriptLang/Skript/discussions/6270 is being clear of the purpose of this change, and it will stay as is.

**Comment by AyhamAl-Ali** [comment]
see #6270
