### ISSUE TITLE
Custom Inventory

### ISSUE THREAD

**Issue by e3e19** [SkriptLang/Skript#6408]
### Suggestion

Add other types of inventories/guis, like:
- Furnace, Crafting Table, etc.

### Why?

Because there's only chest inventories but not others. also it could be useful for those who have custom recipes, so they can show how to craft something. Or how to smelt something, or something else

### Other

this probably wont get added

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
This already exists. You can open many different inventory types, including but not limited to hoppers, furnaces, crafting tables, dispensers, and enchanting tables.
