### ISSUE TITLE
ConcurrentModificationException warning

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#6417]
### Skript/Server Version

```markdown
[Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Server thread/INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Server thread/INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Server thread/INFO]: [Skript] Server Version: git-Purpur-2139 (MC: 1.20.4)
[Server thread/INFO]: [Skript] Skript Version: 2.8.1 (selfbuilt-unknown)
[Server thread/INFO]: [Skript] Installed Skript Addons: 
[Server thread/INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[Server thread/INFO]: [Skript]  - skript-npc v0.1.2 (https://github.com/NanoDankster)
[Server thread/INFO]: [Skript]  - skript-yaml v1.5
[Server thread/INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[Server thread/INFO]: [Skript]  - SkBee v3.2.1 (https://github.com/ShaneBeee/SkBee)
[Server thread/INFO]: [Skript]  - Skript-Packet v2.1.2 (www.github.com/Anarchick/skript-packet)
[Server thread/INFO]: [Skript]  - Skript-Advancements v1.5.9-rudde
[Server thread/INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[Server thread/INFO]: [Skript]  - skDragon v0.18-alex-MC1.20.2-hack-5
[Server thread/INFO]: [Skript]  - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[Server thread/INFO]: [Skript]  - skript-db v1.3.4
[Server thread/INFO]: [Skript]  - SkQuery v4.1.9
[Server thread/INFO]: [Skript]  - TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe)
[Server thread/INFO]: [Skript]  - MundoSK-Async v0.1.0
[Server thread/INFO]: [Skript]  - skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo)
[Server thread/INFO]: [Skript] Installed dependencies: 
[Server thread/INFO]: [Skript]  - Vault v1.7.3-b131
[Server thread/INFO]: [Skript]  - WorldGuard v7.0.10-SNAPSHOT+2260-c7319f1
[Server thread/INFO]: [Skript]  - GriefPrevention v17.0.0-12-gd53199d-dirty
```

### Bug Description

Sometimes, espically tps is low, some players are losing their items which they are stored to chest. They store something to chest and go away (unloads the chunk) and after they come back, items are gone. When I was searching this issue, I saw sometimes Skript throws this warning. Idk is it related with my issue but I wanted to report it.

### Expected Behavior

It shouldn't print this stack.

### Steps to Reproduce

Sorry, I don't know

### Errors or Screenshots

```
[Server thread/WARN]: [Skript] Task #94 for Skript v2.8.1 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
	at ch.njol.skript.bukkitutil.PlayerUtils$1.run(PlayerUtils.java:56) ~[Skript-2.8.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2139]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2139]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2139]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2139]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2139]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2139]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2139]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by EquipableMC** [comment]
Have you tried with just skript? because it could me one of your addons.
As far as I am aware the following addons are broken/outdated:
- skript-packet is broken (unless it was updated recently)
- TuSke (Skript-gui does the same thing related to guis)
- skript-holo
- SkDragon (There is a recoded (updated) version availablke
and probably others

**Comment by rudde0** [comment]
> Have you tried with just skript? because it could be one of your addons. As far as I am aware the following addons are broken/outdated:
> 
> * skript-packet is broken (unless it was updated recently)
> * TuSke (Skript-gui does the same thing related to guis)
> * skript-holo
> * SkDragon (There is a recoded (updated) version availablke
>   and probably others

I'm suspecting of async setItem tasks. But PlayerUtils already seems old and may change as async compatible. That's why I opened this issue.

In some of my codes, I simply do:
```
async # (MundoSK's async effect)
# some heavy tasks..
give {_item} to player
```

**Comment by EquipableMC** [comment]
MundoSK is outdated... so its most likely that

**Comment by rudde0** [comment]
I'm not 100% sure MundoSK is the main issue.

Also if it is the main issue, I'm maintaining MundoSK's async effect for newer versions of Skript, but I'm not sure what should be done from addon side to fix this.

**Comment by sovdeeth** [comment]
I don't think there's an issue per se with Skript here. Anything interacting with bukkit api is usually not safe to happen async, and since Skript is intended to run code on the main thread for those safety reasons, it seems like this is more just a misuse of the bukkit/skript api on an async thread. If I'm mistaken and Skript has a way to fix this, please re-open this issue, anyone.
