### ISSUE TITLE
Skript ... overcomplication

### ISSUE THREAD

**Issue by Vulcano771** [SkriptLang/Skript#6438]
### Skript/Server Version

```markdown
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/command/Commands.java#L107

Why is that done with reflection when there exists: `Bukkit.getCommandMap()`?
```

### Bug Description

NotAbug

### Expected Behavior

NotAbug

### Steps to Reproduce

NotAbug

### Errors or Screenshots

NotAbug

### Other

NotAbug

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Because it's legacy code from when it was necessary. Please make an properly formatted suggestion or PR for this; this isn't a useful issue in its current form.

**Comment by bluelhf** [comment]
Reflection in some capacity is still necessary for Spigot support
