### ISSUE TITLE
(Request) Making a Placeholder plugin for PlaceholderAPI

### ISSUE THREAD

**Issue by cengiz77** [SkriptLang/Skript#644]
Could you devs make a placeholder plugin for PlaceholderAPI? I know Maximvdw's plugins contain it but the PlaceholderAPI doesn't. Could you make it for the variables? I'll be apreciated :)

Suggestion:

%skript_{Var}%

**Comment by Snow-Pyon** [comment]
It should be something that an addon would address. Ask any addon developer in the forums rather than here.

**Comment by bensku** [comment]
I'll think about this. Supporting PlaceholderAPI would actually make sense, considering that scripting it would really add new use cases.

**Comment by Snow-Pyon** [comment]
I just have done this expansion if you want:
https://forums.skunity.com/resources/papi-skript-expansion.250/

**Comment by cengiz77** [comment]
It's deleted. I didn't see anything

**Comment by Snow-Pyon** [comment]
@cengiz77 oh, it's because it hasn't been aproved yet there, here is the spigot's link:
https://www.spigotmc.org/conversations/skript-expansion.224609/

**Comment by cengiz77** [comment]
This is too :D

**Comment by rplcnn** [comment]
@Snow-Pyon hey can you send me a source code of papi skript

**Comment by Nicofisi** [comment]
This is still an issue?

**Comment by Pikachu920** [comment]
no, this already exists so i guess it should be closed @Snow-Pyon

**Comment by Snow-Pyon** [comment]
An expression like `placeholder %strings%` in Skript isn't a bad idea, I'll keep this open till I get time to implement it.

**Comment by Pikachu920** [comment]
should change the title to reflect what this issue really is now, then

**Comment by FranKusmiruk** [comment]
Seeing that I have even less time now than before and the fact that we have enough issues with WG support, I reconsidered adding an expression like this in Skript, Ersatz handles it pretty well so there should be no reason for us to add it.
