### ISSUE TITLE
New Type

### ISSUE THREAD

**Issue by minecraftakcz360** [SkriptLang/Skript#6443]
### Suggestion

can you add something like player & offline player but it will never return none

### Why?

why? because i was making command that have player in arguments and when you type the name wrong it will send you error to chat, i want to make custom message by checking if the player is online and if not then sending something like: you typed the players name wrong try checking the players name again.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by minecraftakcz360** [comment]
![image_2024-02-18_162742597](https://github.com/SkriptLang/Skript/assets/103266461/ce9f04ad-307d-4f4a-a328-8e5b622ddc5b)

**Comment by Pikachu920** [comment]
you can use a string argument and then parse it as a player (for example, `arg-1 parsed as a player`), the parse expression will return none if parsing fails, and the parsed value if successful.

**Comment by minecraftakcz360** [comment]
> you can use a string argument and then parse it as a player (for example, `arg-1 parsed as a player`), the parse expression will return none if parsing fails, and the parsed value if successful.

but then the tab completion will not be there :(

**Comment by minecraftakcz360** [comment]
> you can use a string argument and then parse it as a player (for example, `arg-1 parsed as a player`), the parse expression will return none if parsing fails, and the parsed value if successful.

or add something to the command function that will customize the tab completion

like
command /hi: <string>
    completion: playerlist     _--this will show all players online on the completion_
    trigger:
        send "hi" to arg-1 parsed as a player

command /warp: <string>
    completion: "earth", "moon", "spawn", "land"     _--this will show earth, moon, spawn and land on the completion_
    trigger:
        send "hi" to arg-1 parsed as a player

**Comment by minecraftakcz360** [comment]
> > you can use a string argument and then parse it as a player (for example, `arg-1 parsed as a player`), the parse expression will return none if parsing fails, and the parsed value if successful.
> 
> or add something to the command function that will customize the tab completion
> 
> like command /hi: completion: playerlist _--this will show all players online on the completion_ trigger: send "hi" to arg-1 parsed as a player
> 
> command /warp: completion: "earth", "moon", "spawn", "land" _--this will show earth, moon, spawn and land on the completion_

or maka it more specific like

command /give <string> <string>:
arg-1 completion = playerlist
arg-2 completion = itemlist

**Comment by Pikachu920** [comment]
skript does need tab completion support, but we've already got an issue for that (#3894)
