### ISSUE TITLE
Loops dont continue after reloading skript

### ISSUE THREAD

**Issue by ShadowKlassic** [SkriptLang/Skript#6449]

**Comment by ShadowKlassic** [comment]
I dont like having to kick players and having them rejoin just for the loops to continue working.

**Comment by sovdeeth** [comment]
Can't replicate on 2.8.2 with the following code.
It's likely something to do with your specific code or addons.
```
on command "test":
    while true is true:
        broadcast "test"
        wait 1 tick
```

**Comment by sovdeeth** [comment]
Please provide a minimum reproducible example that we can recreate the issue with, without addons. We can't do much if all we're going off is guesswork and we're unable to replicate it.

**Comment by ShadowKlassic** [comment]
https://paste.gg/p/anonymous/acfd6d92eefd4b2dad0b772696678d8f

**Comment by ShadowKlassic** [comment]
Ok I found how you can recreate it. Heres a part of my code. This is the ONLY part of my code that does this(as in doesn't continue after reloading)

https://paste.gg/p/anonymous/d5ab79e4753e409f999c07522f7aa775

**Comment by sovdeeth** [comment]
> Ok I found how you can recreate it. Heres a part of my code. This is the ONLY part of my code that does this(as in doesn't continue after reloading)
> 
> https://paste.gg/p/anonymous/d5ab79e4753e409f999c07522f7aa775

I think you sent the wrong link. That's the same code with the same reliance on global variables you have set, and function you wrote, that we can't duplicate.

**Comment by ShadowKlassic** [comment]
If you take out the functions and global variables. It still does it

**Comment by sovdeeth** [comment]
> If you take out the functions and global variables. It still does it

As I said above, please take out everything you can that doesn't affect it, and only send us the minimum needed to replicate it. I'll try to replicate with that.
