### ISSUE TITLE
Change inventory move item syntax

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#6451]
### Suggestion

Change the inventory move syntax in skript 2.8 to a more accurate and correct syntax of `on inventory move item`

### Why?

Currently the syntax is `on inventory item move` which is not valid and confusing when the event is `InventoryMoveItemEvent` implying syntax should of been `inventory move item`. This seems more like an under sight during it's initial implementation than an intended design.

### Other

Due to this being a newer 2.8 feature I would label this change valid enough to make it into a patch preferably in the existing pr #6233 for event values as it's a smaller change if possibe.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
Both seem like perfectly valid names to me, adding an alias without removing the existing name seems fine to me.

**Comment by DelayedGaming** [comment]
@sovdeeth Can this change be done in my #6233 as both are on the same page?
