### ISSUE TITLE
command i made doesnt work properly

### ISSUE THREAD

**Issue by Winpez** [SkriptLang/Skript#6499]
### Skript/Server Version

```markdown
> skript info
[21:09:10 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:09:10 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[21:09:10 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[21:09:10 INFO]: [Skript] Server Version: git-Paper-409 (MC: 1.20.4)
[21:09:10 INFO]: [Skript] Skript Version: 2.7.3 (skriptlang-github)
[21:09:10 INFO]: [Skript] Installed Skript Addons: None
[21:09:10 INFO]: [Skript] Installed dependencies: 
[21:09:10 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

when i use one of the command i made it all works properly but it sends "An internal error occured while trying to do this command." and the command does what it supposed to do except for sending the chat its supposed to send

### Expected Behavior

```
set {nickname::%player%} to colored arg 2
send "&6Your nickname is now &l%colored arg 2%" to player
```

does the first part correctly just doesnt do the second part (colored arg 2 is the nickname btw)

### Steps to Reproduce

i am in 1.20.2, my server is 1.20.4, i use viabackwards 4.9.2 and viaversion 4.9.3, to be able to join when i start my server i start the server in minehut dashboard then delete the old viaversion that im forced to have when server starts, /rl confirm then i can get in and then i try to do the command and thats what happens ^ (also i tried to restart the server many times and i also deleted skbee and skrayfall, bug still happens)

### Errors or Screenshots

https://pastebin.com/1BadH71G

### Other

please help me asap so i can work in my server in peace

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by bluelhf** [comment]
This is probably caused by you reloading the server with `/rl confirm`

**Comment by sovdeeth** [comment]
This often appears if you used /reload or reloaded skript/your server with plugman or a similar plugin. 
Additionally, please ensure you're using the latest Skript version (2.8.3) before submitting bug reports.

**Comment by Winpez** [comment]
> This is probably caused by you reloading the server with `/rl confirm`

maybe but i cant restart my server normally because then it would install the bad version of viaversion again and then it will repeat and so on

**Comment by sovdeeth** [comment]
You should figure out how to make it not auto-install viaversion then. This isn't anything we can or will be fixing. Skript is not /reload safe.

**Comment by Winpez** [comment]
> You should figure out how to make it not auto-install viaversion then. This isn't anything we can or will be fixing. Skript is not /reload safe.

i blame it on minehut, they always install the wrong version of viaversion automaticly and they dont let me delete plugins even if im the one who put them

**Comment by Winpez** [comment]
> You should figure out how to make it not auto-install viaversion then. This isn't anything we can or will be fixing. Skript is not /reload safe.

also, skript always work when i reload this is the first time it doesnt work

**Comment by EquipableMC** [comment]
Well its never reload safe anyways.
