### ISSUE TITLE
Global value changing after loop

### ISSUE THREAD

**Issue by KiraKenjiro** [SkriptLang/Skript#6500]
### Skript/Server Version

```markdown
Version: 2.8.3
Plugins: skellet, skquery, skbee
Server: 1.20.4 git-paper-409
```

### Bug Description

Comment 1 will log incrementally correctly from 10 through 43. Where as comment 2 and beyond will only log the first value of 10. This if statement should not be able to manipulate the {_slot} variable.

[snippet.zip](https://github.com/SkriptLang/Skript/files/14628264/snippet.zip)

### Expected Behavior

It should always be the incremented value. As it will loop through and use the value as the GUI slot ID. And again, After the If statement it resets to 10.

### Steps to Reproduce

The bug is within the code itself. Run the code

### Errors or Screenshots

n/a

### Other

This isn't my issue. It is this users issue: 1083392976857858058 (Discord ID)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Pikachu920** [comment]
the provided script uses functions and variables that are not provided. please provide a minimal reproducible example script.

**Comment by KiraKenjiro** [comment]
KKazukii solved the issue on discord. I was asked to close the ticket. DM 1083392976857858058 for more info.
