### ISSUE TITLE
2.8.3 Skript Mod Item Compatability

### ISSUE THREAD

**Issue by TBX3D** [SkriptLang/Skript#6503]
### Suggestion

Could we please make it so that Mod:Item works on 2.8.3? I've tried editing the modpack to make it work but I've been having problems. What do?

### Why?

Me and my friends want to fix something on our modded server using skript (Mohist or?)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Sparky200** [comment]
Skript doesn't support mod loaders. The closest you'll get is [SkArclight](https://github.com/ShaneBeee/SkArclight) which makes Skript compatible with Arclight, but it doesn't work with Mohist.

**Comment by sovdeeth** [comment]
Skript only supports Paper and Spigot at the moment, support for other server software is a long ways off.

**Comment by 0XPYEX0** [comment]
#7126
