### ISSUE TITLE
Add support for variables in the command permission message

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#652]
Hello, I was just wondering if you could add support for variables in the Permission Message, only options and regular text work. :(

Thanks in advance.

**Comment by CormanYT** [comment]
I very much agree with this and I think it should be added. I recommend this is ready next update.

**Comment by Pikachu920** [comment]
Maybe I'll try to add this

**Comment by HYPExMon5ter** [comment]
That’d be 👌
