### ISSUE TITLE
Add middle click event

### ISSUE THREAD

**Issue by AlliSite** [SkriptLang/Skript#6540]
### Suggestion

Add middle click event

### Why?

More Features

Example:

on middleclick on player:
    execute player command "/invsee %clicked player%

### Other

Middle click to inventory

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
I don't believe there's a server event called when a player middle clicks on an entity, only on a block. For that reason I'm unsure if this is possible to implement.

**Comment by AlliSite** [comment]
> I don't believe there's a server event called when a player middle clicks on an entity, only on a block. For that reason I'm unsure if this is possible to implement.
> 
> Edit: actually, I can't even find an event for middle clicking a block (pick block)

What if

(example)
on middleclick:
    if name of player's tool is "Example":
        broadcast "&cExample"

**Comment by sovdeeth** [comment]
> > I don't believe there's a server event called when a player middle clicks on an entity, only on a block. For that reason I'm unsure if this is possible to implement.
> > Edit: actually, I can't even find an event for middle clicking a block (pick block)
> 
> What if
> 
> (example) on middleclick: if name of player's tool is "Example": broadcast "&cExample"

That is the same thing? There no event for middle click we can listen to.

**Comment by EquipableMC** [comment]
> > > I don't believe there's a server event called when a player middle clicks on an entity, only on a block. For that reason I'm unsure if this is possible to implement.
> > > Edit: actually, I can't even find an event for middle clicking a block (pick block)
> > 
> > 
> > What if
> > (example) on middleclick: if name of player's tool is "Example": broadcast "&cExample"
> 
> That is the same thing? There no event for middle click we can listen to.

But skript has types for each click, which includes middle mouse button

**Comment by sovdeeth** [comment]
> > 
> > That is the same thing? There no event for middle click we can listen to.
> 
> But skript has types for each click, which includes middle mouse button

Unfortunately that's completely unrelated. That's for the inventory click event.

**Comment by Moderocky** [comment]
If at some point Minecraft itself supports this we can add it.

**Comment by EquipableMC** [comment]
> > > That is the same thing? There no event for middle click we can listen to.
> > 
> > 
> > But skript has types for each click, which includes middle mouse button
> 
> Unfortunately that's completely unrelated. That's for the inventory click event.

ahh gotcha alright
