### ISSUE TITLE
How do I write Hex code in skript!?

### ISSUE THREAD

**Issue by SkVL4D** [SkriptLang/Skript#6543]
### Skript/Server Version

```markdown
ver. 2.8.3
no addons added
```

### Bug Description

![image_2024-04-08_213651451](https://github.com/SkriptLang/Skript/assets/166437342/78260d6f-fff9-496a-8636-82cef64b91c5)
![image_2024-04-08_213712748](https://github.com/SkriptLang/Skript/assets/166437342/df21b6f2-a9ad-4897-9e45-744a4d2fb3c0)

It doesn't let me write it and gives me this wierd error message.
I tried multiple variations of writing hex and none worked, please I need help ASAP

### Expected Behavior

It should've set the event block to dirt if the shovel was named like that

### Steps to Reproduce

I typed that if i mine a block with a stone shovel named like something, it makes the event-block into another block

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Moderocky** [comment]
Hashtag `#` is a comment start character, you should double it `##` if you want to write it in code rather than begin a comment.
