### ISSUE TITLE
named atribute doesnt work..

### ISSUE THREAD

**Issue by SkVL4D** [SkriptLang/Skript#6546]
### Skript/Server Version

```markdown
2.8.3
```

### Bug Description

The named atribute doesnt work for some reason? if i do /sk reload, it says the code works perfectly and it has no problems. but when i try it, it doesnt work. I did more things and i found out that when i add the: named "&7&lStone &3&lShovel &7[&cTier I&7]" It basically stops it from working.. I did get the name exacly like the item i want and theres 
no incorrect misspelling

![image_2024-04-09_234640859](https://github.com/SkriptLang/Skript/assets/166437342/3ac9e4c7-5e37-4225-a765-6a7e211ed3b5)
![image_2024-04-09_234803575](https://github.com/SkriptLang/Skript/assets/166437342/2db4ff3a-887f-4848-92c5-45d250af1470)

### Expected Behavior

----

### Steps to Reproduce

----

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by SkVL4D** [comment]
btw, when i remove "named "&7&lStone &3&lShovel &7[&cTier I&7]"" The code works fine, but i added the name just so it only applies for this only shovel, and when i add the name thing, the code doesnt work

**Comment by sovdeeth** [comment]
This is due to item comparisons comparing all attributes and finding a difference in the (it looks like) enchantments. Please test the type and the name separately, or make sure you're checking an exact replica (enchants and other data included).
