### ISSUE TITLE
New event "on any event:"

### ISSUE THREAD

**Issue by AlliSite** [SkriptLang/Skript#6565]
### Suggestion

I propose to create an event that is responsible for absolutely all events, as well as additional conditions for it

### Why?

Example:

on any event:
.     if event is not command and event is not chat:
.         cancel event

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
Personally I'm against this, however I'd love to hear a further explanation why you'd like this.

**Comment by AlliSite** [comment]
> Лично я против этого, но хотел бы услышать более подробное объяснение, почему вам это нужно.

For example, for a script for registration and authorization, prohibiting all actions, rather than writing them manually and clogging up the script.
Example:

on any event:
    if {not_authorized.%uuid of player%} is set:
        cancel event
        send "Please log in with the command /l [password]" to player

**Comment by ShaneBeee** [comment]
This would break so many more things than you'd know.
A good example is:
- events that can't be cancelled, how would that be handled
- what about events that fire that are unrelated to a player?
- how exactly would you handle event-player???

There isn't an easy or plausible way to handle this in Skript.
Something like this is just "syntax sugar" and in my opinion, a little lazy... while also causing more issues that you could imagine.

I personally vote no on this

**Comment by Pikachu920** [comment]
For many of the reasons outlined here, this isn't feasible to add to Skript
