### ISSUE TITLE
suggestion: on click Hold

### ISSUE THREAD

**Issue by dialedd** [SkriptLang/Skript#6584]
### Suggestion

Add syntax to check if a player is holding down left or right click.

on hold right click:
or
on right click hold:

for example.

### Why?

Even though it is possible in skript, I feel it is much-needed syntax since it creates simplicity.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
This isn't really possible to do with any guarantee of accuracy, as far as I know. All the information the server gets is a repeating click event every 4 ticks iirc.

**Comment by ShaneBeee** [comment]
I was about to say something similar.
A packet is sent when they either click or start breaking a block.
There wouldn't really be finite way of know thing the player has started "holding"

**Comment by dialedd** [comment]
> This isn't really possible to do with any guarantee of accuracy, as far as I know. All the information the server gets is a repeating click event every 4 ticks iirc.

oh ok, i thought it was just something with skript
good to know thanks

**Comment by Moderocky** [comment]
Sadly, I think we'll have to close this until the server itself provides support.

It's not really something we can make ourselves, and our best attempt will just be an estimation which you can do yourself (e.g. check for regular right-click events without breaks, and no interactions with other things at the same time).
