### ISSUE TITLE
variable local storage improvement 

### ISSUE THREAD

**Issue by corrupteddroid** [SkriptLang/Skript#6599]
### Suggestion

instead of saving the all variable in a single csv file (by default),
what if the variable is saved on a folder where it will stored based on its name?
something like
{a} -> ./plugins/skript/variable/_.csv
{a::#} -> ./plugins/skript/variable/a.csv
{a::b::#} -> ./plugins/skript/variable/a/b.csv

where # is any alphanumeric text

and as a failsafe if for example _.csv is overloaded then it would create a another file which will be named 2.\<name\>.csv

and can be backup as a zip file

### Why?

reason:
- to avoid queueing too much variable to a file which lag the server
- to lessen amount of variables getting corrupt from accidents
- to remove a list without starting a server
- not needed to tamper the database option to separate variables

downside:
- reworking how variable are load
- may slowing down variables
- file conflict will happen if they use "." on the variable name

### Other

i would suggest to add this as a experimental feature and having a original feature running at the same time.

upsides and downsides are not the only ones there maybe more.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Moderocky** [comment]
A user could have thousands of different list::variations::like:this, potentially multiple for every::%player%::who::joined the server.
This could create hundreds of thousands of files, all of which take up extra disk space (headers, metadata, inodes, file tables, etc.) and will slow down the system incredibly.
Not to mention there's no difference in the amount of data you're loading, except that it's having to access hundreds of different places, so it'll be significantly _slower_ than it is currently.

**Comment by corrupteddroid** [comment]
yes but no.

 {player::%player%::scores} can be {player::scores::%player%} but it would be harder to clean up using "clear {player::%player%::*}" if we exclude that idea leaving {player::scores::%player%} as the format then it would be the same as the current one and it may became more efficient if storage file are loaded one by one

**Comment by corrupteddroid** [comment]
yes but no.

 {player::%player%::scores} can be {player::scores::%player%} but it would be harder to clean up using "clear {player::%player%::*}" if we exclude that idea leaving {player::scores::%player%} as the format then it would be the same as the current one and it may became more efficient if storage file are loaded one by one
