### ISSUE TITLE
Vehicle Steer Event

### ISSUE THREAD

**Issue by EquipableMC** [SkriptLang/Skript#6620]
### Suggestion

It would be cool if there was an [on Vehicle Steer Event](https://skripthub.net/docs/?id=3687) to easily better check for steering in vehicles

### Why?

I saw this from an addon Kenzie made awhile back (that's now discontinued) from MiSK. The [Vehicle Steer Event](https://skripthub.net/docs/?id=3687) was where you could check which method of steering you are using (left, right, forward, reverse, shift, and jump). I just thought it would be cool to have in Skript

### Other

It may be easier to implement if Kenzie still has this addon/event saved without having to code it all over again.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Asleeepp** [comment]
Seems to require ProtocolLib though, don't think the team are gonna like that one

**Comment by EquipableMC** [comment]
> Seems to require ProtocolLib though, don't think the team are gonna like that one

ahh yeah, but then again this is up for debate since it's a suggestion

**Comment by cheeezburga** [comment]
This isnt really an up-for-debate kind of thing - its out of Skript's scope (as far as I know). See #6603 for a similar suggestion which was closed as "not planned" for a similar reason.

**Comment by Moderocky** [comment]
The pull request adding support for this to PaperMC was [abandoned](<https://github.com/PaperMC/Paper/pull/7274>), and nobody has followed it up since. Until the server supports this we can't do anything about it.
