### ISSUE TITLE
Add version to Skript JARs

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#6622]
### Suggestion

My suggestion is to modify the build.gradle so that it automatically includes the Skript version in the name of the output JAR, and maybe even other information such as the release flavor.

### Why?

Skript users will no longer be confused when two JARs with the same name have different versions. So this is more of a QoL suggestion, making it easier to handle the many versions of Skript.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by ShaneBeee** [comment]
I agree ... I would love to see this!

**Comment by Asleeepp** [comment]
Agreed! Hate to see Skript (number) everytime i update..

**Comment by Fusezion** [comment]
> Agreed! Hate to see Skript (number).jar saved to my file explorer everytime i update., would much rather there be the version

just rename your file and stop keeping copies...

but yes I agree would love to see version added to jar at least
