### ISSUE TITLE
Update Paper API to 1.20.6

### ISSUE THREAD

**Issue by NotSoDelayed** [SkriptLang/Skript#6629]
### Suggestion

As the title says, update the Paper API to 1.20.6, as I noticed that dependabot has been long disabled due to how the repo sorts out features and patches commits.

### Why?

So contributors can implement features to Skript for 1.20.6.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
This has already been done in #6617 by pickle, just awaiting it's merging.
