### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by AllawiEZ** [SkriptLang/Skript#6634]
### Suggestion

`set {_prefix} to colored prefix of group named "admin"`
`set {_prefix} to colored {_group}`

### Why?

Since you have [this](https://skripthub.net/docs/?id=2485) and [this](https://skripthub.net/docs/?id=2616). It will be a pretty neat edition.

### Other

Maybe suffix? Don't really care about that.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
this? https://docs.skriptlang.org/expressions.html?search=#ExprPrefixSuffix

**Comment by Phill310** [comment]
I think thats what they want except they want to be able to use it on groups as well as players

**Comment by AllawiEZ** [comment]
> this? https://docs.skriptlang.org/expressions.html?search=#ExprPrefixSuffix

No, I meant color of groups

> I think thats what they want except they want to be able to use it on groups as well as players

Correct.

**Comment by Hurming** [comment]
Also add group of offline player that is very needed.

**Comment by Phill310** [comment]
The code looks like it already supports offline players. That error makes me think arg-1 is a string, not an offlineplayer

**Comment by Hurming** [comment]
> The code looks like it already supports offline players

It's showing as <none>.

**Comment by AyhamAl-Ali** [comment]
This is probably not related to Skript. skript only uses Vault's API that permission plugins uses
See if enabling this option helps

https://github.com/LuckPerms/LuckPerms/blob/d74a4dcb7efe61aa366397c5cff7de3aef132aeb/bukkit/src/main/resources/config.yml#L641
