### ISSUE TITLE
Add recently added attributes

### ISSUE THREAD

**Issue by hyeonsu06** [SkriptLang/Skript#6645]
### Suggestion

like "set attack damage attribute of player to 100", make other attributes do so like
"set reach distance attribute of player to 5 (blocks)"

### Why?

its too hard for me to use skript-reflect to do so

### Other

apply change of name-changed attributes like "horse.jump_strength" -> "generic.jump_strength"

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
all 1.20.5/6 attributes were added ahead of time

**Comment by sovdeeth** [comment]
Closing, please re-open if a specific attribute was forgotten.
