### ISSUE TITLE
Add skript-reflect (or at least some features) into Skript

### ISSUE THREAD

**Issue by Palgia** [SkriptLang/Skript#6658]
### Suggestion

I think skript-reflect should merge with Skript, if possible, or Skript should adopt its main functionalities (such as creating custom events, custom conditions, etc.).

This would make it simpler and allow better management of expressions, custom events, etc.

For example, currently, it's very complicated to manage custom events with other scripts using skript-reflect, as you have to be very careful with organizing the scripts. And when there are many of them, it's difficult to keep track, and it quickly becomes chaotic.

I'm someone who shares a lot of resources on SkUnity that work independently but can also work together. These are resources that I share and use myself.

To illustrate this problem, let me explain what's happening to me right now: I'm currently creating a quest script that allows creating custom quests that interact with plugins (like ItemsAdder, etc.) but also with my other scripts. For example, I created a custom event in my SkCollections script that allows knowing when a player levels up. I plan to add custom events in my other scripts.

The problem is that when multiple scripts have their custom events, the organization becomes really chaotic. So adding these skript-reflect features to Skript would be really beneficial because the events/expressions/conditions, etc. could be loaded with the functions.

Or another solution would be to revisit this suggestion I made before: https://github.com/SkriptLang/Skript/issues/6564 Determining dependencies could greatly facilitate script organization as well as sharing.

I'm not sure if this suggestion is feasible, but it would be so beneficial.

### Why?

This would improve the customization and the way custom events and other things are loaded.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
This is not something we're interested in doing. Features in skript-reflect are outside of the scope of Skript and are maintained separately for a reason. We want users to opt into the powerful but confusing things reflect lets you do, rather than being overwhelmed by them when they begin. If you have issues with reflect, or suggestions to make it better, please head over to the skript-reflect repo and suggest them there!
