### ISSUE TITLE
Remove skript: from commands created in skript (config option)

### ISSUE THREAD

**Issue by EquipableMC** [SkriptLang/Skript#6703]
### Suggestion

Remove skript: from commands created in skript (config option). If the config option is set to true to disable it, it will remove it from all current and new commands created with skript.

### Why?

I feel like it's weird having skript: as a tab completion for your custom commands. It would be cool if there was a way to "disable it".

### Other

This config option would be set to "false" by default

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Asleeepp** [comment]
How would disabling it work?

**Comment by Phill310** [comment]
Pretty sure all plugins do that

**Comment by EquipableMC** [comment]
> How would disabling it work?

Most likely would require a server restart and whatever skript does to add the tab completions for `skript:test` for the test command, they can add a check if x is true

**Comment by EquipableMC** [comment]
> Pretty sure all plugins do that

i've seen some that dont

**Comment by Phill310** [comment]
Name one and we can go look at their code

**Comment by Asleeepp** [comment]
pretty sure commands NEED a namespace, like even minecraft commands have minecraft:

**Comment by EquipableMC** [comment]
> pretty sure commands NEED a namespace, like even minecraft commands have minecraft:

oh didnt know that

**Comment by UnderscoreTud** [comment]
Adding onto what's been said: you can use the `prefix:` entry to change a command's prefix
