### ISSUE TITLE
Tadpoles cannot spawn

### ISSUE THREAD

**Issue by Symmettry** [SkriptLang/Skript#6707]
### Skript/Server Version

```markdown
[01:12:29 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[01:12:29 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[01:12:29 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[01:12:29 INFO]: [Skript] Server Version: git-Paper-36 (MC: 1.20.6)
[01:12:29 INFO]: [Skript] Skript Version: 2.8.5 (skriptlang-github)
[01:12:29 INFO]: [Skript] Installed Skript Addons: 
[01:12:29 INFO]: [Skript]  - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[01:12:29 INFO]: [Skript]  - SkBee v3.5.0 (https://github.com/ShaneBeee/SkBee)
[01:12:29 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

Tadpoles cannot be spawned

### Expected Behavior

Tadpoles should spawn

### Steps to Reproduce

`spawn tadpole at <any location>`

### Errors or Screenshots

No error is given

### Other

setting it to something like `spawn husk` works fine but when I try `spawn tadpole` it just doesn't spawn.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Alexanderlo58** [comment]
Which minecraft version are u on

**Comment by EquipableMC** [comment]
> Which minecraft version are u on

It says in the error message, 1.20.6

**Comment by EquipableMC** [comment]
> ### Skript/Server Version
> ```
> [01:12:29 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
> [01:12:29 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
> [01:12:29 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
> [01:12:29 INFO]: [Skript] Server Version: git-Paper-36 (MC: 1.20.6)
> [01:12:29 INFO]: [Skript] Skript Version: 2.8.5 (skriptlang-github)
> [01:12:29 INFO]: [Skript] Installed Skript Addons: 
> [01:12:29 INFO]: [Skript]  - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
> [01:12:29 INFO]: [Skript]  - SkBee v3.5.0 (https://github.com/ShaneBeee/SkBee)
> [01:12:29 INFO]: [Skript] Installed dependencies: None
> ```
> 
> ### Bug Description
> Tadpoles cannot be spawned
> 
> ### Expected Behavior
> Tadpoles should spawn
> 
> ### Steps to Reproduce
> `spawn tadpole at <any location>`
> 
> ### Errors or Screenshots
> No error is given
> 
> ### Other
> setting it to something like `spawn husk` works fine but when I try `spawn tadpole` it just doesn't spawn.
> 
> ### Agreement
> * [x]  I have read the guidelines above and affirm I am following them with this report.

Try using the beta 2.9.0

**Comment by Fusezion** [comment]
It's indeed registered for 1.19+
https://github.com/SkriptLang/Skript/blob/master/src%2Fmain%2Fjava%2Fch%2Fnjol%2Fskript%2Fentity%2FSimpleEntityData.java#L301

**Comment by Symmettry** [comment]
Yes; it doesn't give an error message when it runs, it just doesn't spawn the tadpole.

**Comment by sovdeeth** [comment]
FishData in general seems to be broken. I cannot spawn Fish, Cod, Salmon, Pufferfish, or Tadpole. I can spawn Tropical Fish, though.
