### ISSUE TITLE
 Checking for updates failed. Do you have Internet connection?

### ISSUE THREAD

**Issue by OrsoSgravato34** [SkriptLang/Skript#6717]
### Skript/Server Version

```markdown
I'm in 1.17.1 version

[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-411 (MC: 1.17.1)
[Skript] Skript Version: 2.8.5 (skriptlang-github)
[Skript] Installed Skript Addons:
[Skript] - skript-placeholders v1.6.0 (https://github.com/APickledWalrus/skript-placeholders)
[Skript] - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[Skript] - SkQuery v4.1.9
[Skript] - SkBee v2.11.0 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies:
[Skript] - Vault v1.7.3-b131
[Skript] - WorldGuard v7.0.7+216b061
```

### Bug Description

When i start my server the skript plugin says:

![Screenshot 2024-05-23 200846](https://github.com/SkriptLang/Skript/assets/170664139/c793ae37-95cc-4fbc-962b-74ab5339422e)

the problem is that i have the internet connection so idk why it says that

### Expected Behavior

Not sure but i don't think so since i have the internet connection

### Steps to Reproduce

Just started the server i don't know what i did wrong

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Likely you just cannot connect to GitHub for some reason, or GitHub was down for a bit. Is this still occurring?

**Comment by sovdeeth** [comment]
Closing due to no response.
