### ISSUE TITLE
magma cubes and Slimes aren't not monster or creature?

### ISSUE THREAD

**Issue by ZuRiKanHD** [SkriptLang/Skript#6755]
### Suggestion

Hello,

I have noticed that the trigger "on death of monster or creature" does not respond to Slimes and Magma Cubes. These need to be included separately, so it looks like this: on death of a monster or a creature or a slime or a magma cube:

### Why?

i think slimes and Magma Cubes are monster :)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
Slimes and Magma Cubes are not actually Monsters or Creatures. They are, however, Mobs and Enemies. You may want to use those instead. (this is based on their classifications in minecraft code)
