### ISSUE TITLE
on join seems to crash my skript server

### ISSUE THREAD

**Issue by lakabukki** [SkriptLang/Skript#6771]
### Skript/Server Version

```markdown
https://media.essential.gg/28c956be-9a0b-4440-e078-45da82fd0c00
```

### Bug Description

Whenever I try using on join: it ends up crashing the server on start up or when a player joins. When I remove the on join: it fixes the problem. I only have a broadcast statement and its correct syntax.

### Expected Behavior

Not crash.

### Steps to Reproduce

Make a skript in 1.20.1 with skbee 3.5.3 and skript 2.8.6

Then add an on join:

Start the server and it will crash(should)

### Errors or Screenshots

No errors :(

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
what's the code in your `on join`?

**Comment by sovdeeth** [comment]
Closing due to lack of response. User likely had an unbounded while loop
