### ISSUE TITLE
Skript bug very big problem 

### ISSUE THREAD

**Issue by shounakdeogharia** [SkriptLang/Skript#6776]
### Skript/Server Version

```markdown
command /ranks:
    trigger:
        open virtual chest with size 3 named "&l&8[&eRank Shop&8]" to player
        format gui slot 0 of player with red stained glass pane named " " to do nothing
        format gui slot 1 of player with red stained glass pane named " " to do nothing
        format gui slot 2 of player with red stained glass pane named " " to do nothing
        format gui slot 3 of player with red stained glass pane named " " to do nothing
        format gui slot 4 of player with red stained glass pane named " " to do nothing
        format gui slot 5 of player with red stained glass pane named " " to do nothing
        format gui slot 6 of player with red stained glass pane named " " to do nothing
        format gui slot 7 of player with red stained glass pane named " " to do nothing
        format gui slot 8 of player with red stained glass pane named " " to do nothing
        format gui slot 9 of player with red stained glass pane named " " to do nothing
        format gui slot 17 of player with red stained glass pane named " " to do nothing
        format gui slot 18 of player with red stained glass pane named " " to do nothing
        format gui slot 19 of player with red stained glass pane named " " to do nothing
        format gui slot 20 of player with red stained glass pane named " " to do nothing
        format gui slot 21 of player with red stained glass pane named " " to do nothing
        format gui slot 24 of player with red stained glass pane named " " to do nothing
        format gui slot 25 of player with red stained glass pane named " " to do nothing
        format gui slot 26 of player with red stained glass pane named " " to do nothing
        
        format gui slot 13 of player with diamond named "&eFlame Rank" with lore "&7Price: &62,000,000" to run:
            execute player command "/confirm flame"
            close player's inventory

        format gui slot 14 of player with diamond named "&4Bloody Rank" with lore "&7Price: &65,000,000" to run:
            execute player command "/confirm bloody"
            close player's inventory

        format gui slot 22 of player with diamond named "&8Deadliest Rank" with lore "&7Price: &610,000,000" to run:
            execute player command "/confirm deadliest"
            close player's inventory

        format gui slot 23 of player with diamond named "&6God Rank" with lore "&7Price: &615,000,000" to run:
            execute player command "/confirm god"
            close player's inventory
```

### Bug Description

This is my script when I am loading it it is saying failed to load structure minecraft version 1.20.4 paper
Cannot run and the commandd is not working

### Expected Behavior

It should work correctly but the command was not showing it loaded the skript successfuly.

### Steps to Reproduce

I just got in the skript folder created rankshop.sk and then paste the script into there and reloaded it

### Errors or Screenshots

![Screenshot_2024_0609_204246]
![Screenshot_2024_0609_204217](https://github.com/SkriptLang/Skript/assets/172236431/19bb658f-cc96-427f-a8be-a43cf0ae45dc)
(https://github.com/SkriptLang/Skript/assets/172236431/5c5261bf-b3d7-4a25-91d4-73e2c37adb14)
![Screenshot_2024_0609_204232](https://github.com/SkriptLang/Skript/assets/172236431/0ff029e7-c48d-4737-ac31-ee3b2eadb6ec)

### Other

 Nothing!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by shounakdeogharia** [comment]
Reply as fast as you can

**Comment by Fusezion** [comment]
let's start by removing tuske and actually following the format given by the team

**Comment by shounakdeogharia** [comment]
I removed it
But nothing happened

**Comment by Fusezion** [comment]
> I removed it But nothing happened

yeah I mean the code won't work still, but the issue is tuske, also let's go to skunity help channels instead https://discord.gg/skript

**Comment by shounakdeogharia** [comment]
What will happen if I join the discord server
My server is paper and 1.20.4 and the script version 2.8.6

**Comment by shounakdeogharia** [comment]
Can u please tell me exact what happened

**Comment by shounakdeogharia** [comment]
Can u fix the skript

**Comment by sovdeeth** [comment]
This is invalid Skript code. If you want help on writing Skript code, please join the SkUnity discord or a similar community. This GitHub is not an appropriate place to ask for help with writing code; it's for reporting bugs and suggestions.

**Comment by bluelhf** [comment]
> ### Skript/Server Version
> 
> ```
> command /ranks:
>     trigger:
>         open virtual chest with size 3 named "&l&8[&eRank Shop&8]" to player
>         format gui slot 0 of player with red stained glass pane named " " to do nothing
>         format gui slot 1 of player with red stained glass pane named " " to do nothing
>         format gui slot 2 of player with red stained glass pane named " " to do nothing
>         format gui slot 3 of player with red stained glass pane named " " to do nothing
>         format gui slot 4 of player with red stained glass pane named " " to do nothing
>         format gui slot 5 of player with red stained glass pane named " " to do nothing
>         format gui slot 6 of player with red stained glass pane named " " to do nothing
>         format gui slot 7 of player with red stained glass pane named " " to do nothing
>         format gui slot 8 of player with red stained glass pane named " " to do nothing
>         format gui slot 9 of player with red stained glass pane named " " to do nothing
>         format gui slot 17 of player with red stained glass pane named " " to do nothing
>         format gui slot 18 of player with red stained glass pane named " " to do nothing
>         format gui slot 19 of player with red stained glass pane named " " to do nothing
>         format gui slot 20 of player with red stained glass pane named " " to do nothing
>         format gui slot 21 of player with red stained glass pane named " " to do nothing
>         format gui slot 24 of player with red stained glass pane named " " to do nothing
>         format gui slot 25 of player with red stained glass pane named " " to do nothing
>         format gui slot 26 of player with red stained glass pane named " " to do nothing
>         
>         format gui slot 13 of player with diamond named "&eFlame Rank" with lore "&7Price: &62,000,000" to run:
>             execute player command "/confirm flame"
>             close player's inventory
> 
>         format gui slot 14 of player with diamond named "&4Bloody Rank" with lore "&7Price: &65,000,000" to run:
>             execute player command "/confirm bloody"
>             close player's inventory
> 
>         format gui slot 22 of player with diamond named "&8Deadliest Rank" with lore "&7Price: &610,000,000" to run:
>             execute player command "/confirm deadliest"
>             close player's inventory
> 
>         format gui slot 23 of player with diamond named "&6God Rank" with lore "&7Price: &615,000,000" to run:
>             execute player command "/confirm god"
>             close player's inventory
> ```
> 
> ### Bug Description
> 
> This is my script when I am loading it it is saying failed to load structure minecraft version 1.20.4 paper Cannot run and the commandd is not working
> ### Expected Behavior
> 
> It should work correctly but the command was not showing it loaded the skript successfuly.
> ### Steps to Reproduce
> 
> I just got in the skript folder created rankshop.sk and then paste the script into there and reloaded it
> ### Errors or Screenshots
> 
> ![Screenshot_2024_0609_204246] ![Screenshot_2024_0609_204217](https://private-user-images.githubusercontent.com/172236431/338049466-19bb658f-cc96-427f-a8be-a43cf0ae45dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjM2OTMsIm5iZiI6MTcxODAyMzM5MywicGF0aCI6Ii8xNzIyMzY0MzEvMzM4MDQ5NDY2LTE5YmI2NThmLWNjOTYtNDI3Zi1hOGJlLWE0M2NmMGFlNDVkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMjQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzY2MzY0OGI0NjgwYWRkZjk4MWU5NGYyNmE0MGUyZTU3YWE0NTE1OTA3YjIzOWQ5YzUwMjIxNjhkZmEyMGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XRTSCJLq3OsY1xX85ywK9gUE1YjiK-6fPVB7urdVzE8) (https://github.com/SkriptLang/Skript/assets/172236431/5c5261bf-b3d7-4a25-91d4-73e2c37adb14) ![Screenshot_2024_0609_204232](https://private-user-images.githubusercontent.com/172236431/338049464-0ff029e7-c48d-4737-ac31-ee3b2eadb6ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjM2OTMsIm5iZiI6MTcxODAyMzM5MywicGF0aCI6Ii8xNzIyMzY0MzEvMzM4MDQ5NDY0LTBmZjAyOWU3LWM0OGQtNDczNy1hYzMxLWVlM2IyZWFkYjZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMjQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWY0MGQ3NzZjMzE4ZjkyYzMyYzIxMDU2OWExOTNiMWRhYjE5YTdmMTQ4MjJlZWU3YWY0ODY0MjI1MWQ3MjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZSD1lZj2L8h2mn4E_wO79E-uhBJgzJldp-kOyGZanpk)
> ### Other
> 
> Nothing!
> ### Agreement
> 
>     * [x]  I have read the guidelines above and affirm I am following them with this report.

This issue is caused by TuSKe, the version you have installed does not support your Skript version (and likely no TuSKe version does, it's my understanding that the add-on isn't maintained anymore).

Since it's not a Skript issue, we can't really help here. You should probably try following an skUnity tutorial for making _vanilla guis_, and uninstall TuSKe altogether.
