### ISSUE TITLE
Slime chunk

### ISSUE THREAD

**Issue by WolfezzKyne** [SkriptLang/Skript#678]
It would be a nice function to detect if chunk-events can use slime-chunks since there is a api in bukkit to detect them (commit in api https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/319013857d3eb9a64171d64e453f36dd0641447f )

**Comment by Syst3ms** [comment]
That would be a good idea, but this change was only made in 1.11+ versions, so people using 1.9 or 1.10 wouldn't benefit from it. Also, the code used inside the method is from NMS, which is forbidden in Skript's code

**Comment by Snow-Pyon** [comment]
There is a formula to detect a slime chunk which is:
```
Random rnd = new Random(seed +
                        (long) (xPosition * xPosition * 0x4c1906) +
                        (long) (xPosition * 0x5ac0db) + 
                        (long) (zPosition * zPosition) * 0x4307a7L +
                        (long) (zPosition * 0x5f24f) ^ 0x3ad8025f);
return rnd.nextInt(10) == 0;
```
MundoSK has the following expression, which uses that formula:
```
%chunks% (is|are) slimey
```

**Comment by xXAndrew28Xx** [comment]
@Syst3ms Spigot is built ontop of Bukkit (API). The implementation of Bukkit, CraftBukkit is built on the Vanilla Minecraft Server. Basically every method in Spigot uses NMS, whether directly or indirectly.

**Comment by Syst3ms** [comment]
@xXAndrew28Xx I knew all of that. And yeah I meant that.

**Comment by Wealthyturtle** [comment]
Someone please close this issue, it's been sitting open for a year xD
