### ISSUE TITLE
Skript killing/deleting mobs/entities

### ISSUE THREAD

**Issue by Blizzmond** [SkriptLang/Skript#6782]
### Skript/Server Version

```markdown
git-paper-496 mc 1.20.4 
skript 2.8.5
```

### Bug Description

Skript not receiving mobs in chunks that are far with no players

### Expected Behavior

Receive and delete the entities

### Steps to Reproduce

```
loop all mobs:
	while chunk at loop-entity is not loaded:
		wait 1 tick
		load chunk at loop-entity
	delete loop-entity
```

for some reason it doesn't delete or kill mobs that are around 100-200 (estimate) blocks far from where I stand, without loading the chunk also doesnt work

### Errors or Screenshots

no error

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Blizzmond** [comment]
This might be a paper bug/problem since when I do /kill @e it also doesnt kill entirely all the mobs, only a bunch near where I stand

**Comment by sovdeeth** [comment]
This isn't a bug, skript and /kill only deal with loaded entities. This is intended behavior.
