### ISSUE TITLE
Change the way or storing Variable

### ISSUE THREAD

**Issue by L1shed** [SkriptLang/Skript#6783]
### Suggestion

Change Skript's variable storing system. it currently uses files to store these datas.
It will be more optimized if Skript uses databases such as SQLite instead.

### Why?

Skript variables system is very slow and laggy

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Phill310** [comment]
You can already have skript save files in a database (check the config file). Additionally there is work being done in #5646  to improve this feature. I would check out both of those before continuing this suggestion

**Comment by L1shed** [comment]
Thank you for everything, I close this suggestion
