### ISSUE TITLE
Vector arithmetic enhancement

### ISSUE THREAD

**Issue by MissingReports** [SkriptLang/Skript#6784]
### Suggestion

You can use arithmetic on vectors using another vectors, but it would be nice if you could do ``{_vector} * 10`` instead of ``{_vector} * vector(10, 10, 10)``, this applies to all arithmetic related to vectors

### Why?

Easier to write and to understand what you're trying to do and saves some line space (abit less reload time)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
![image](https://github.com/SkriptLang/Skript/assets/81952476/0a5e1868-7f00-4385-9d3f-68118a8560c0)
but you can?

**Comment by MissingReports** [comment]
i swear you couldn't? i tried that before

**Comment by bluelhf** [comment]
yes, it's a recent addition :)

**Comment by Fusezion** [comment]
You've been able to do this since 2.8 when they deprecated `**` in favor of a proper api
