### ISSUE TITLE
Condition enhancements

### ISSUE THREAD

**Issue by MissingReports** [SkriptLang/Skript#6809]
### Suggestion

First, I feel like making conditions act like expressions would be nice, for example ``set {_isSet} to {variable} is set``
This is most useful is functions where you would want to do something like this
```
function hasDiamond(p: player) :: boolean:
    return {_p} has diamond
```
instead of
```
function hasDiamond(p: player) :: boolean:
    if {_p} has diamond:
        return true
    return false
```

i know this is abit lazy but it also cleans the code abit. and doesn't cause confusion for people that use skript and java

Second, i don't even know why this isn't a thing but you can't do ``if true``, you have to do ``if true is true`` which also causes confusion when using skript and java

### Why?

Cleaning up code and makes skript similar to pretty much all scripting languages

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
See #6748
