### ISSUE TITLE
Checking for amount instead of item amount causes

### ISSUE THREAD

**Issue by eliavhaganav** [SkriptLang/Skript#6819]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-496 (MC: 1.20.4)
[Skript] Skript Version: 2.8.7 (skriptlang-github)
[Skript] Installed Skript Addons: 
[Skript]  - SkBee v3.5.5 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: 
[Skript]  - WorldGuard v7.0.10+d9424b1
```

### Bug Description

Whenever you try to call for an amount of an item (i.e player's tool's amount) instead of item amount (player's tool's item amount), skript gives you a something went horribly wrong error in the server console, reloading a skript with the line in it causes it to not send any message after reloading skript and even after removing it the skript stays broken until a server restart is issued, and if a server is restarted with one of the skripts having it, it breaks all skripts completely causing nothing to work except basic skript commands (/sk reload, /sk info) until you restart the server after removing it.

### Expected Behavior

It should either return the amount of the item as an integer or give a syntax error.

### Steps to Reproduce

Easiest way I found is to run the effect command !send "%player's tool's amount%" and seeing that it doesn't send anything while !send "%player's tool's item amount%" works completely fine, another way is putting it this effect in one of the skripts and trying to reload it, which will cause it to stop working completely with only a server restart without the effect inside of it fixing it.
lastly is a server restart with the effect inside of a skript and seeing all the other skripts stop working until you remove the effect or the entire skript.

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This doesn't seem related to the amount expression. Please add the error itself to your report so we can see the actual issue.

**Comment by Moderocky** [comment]
Closing due to no response. Unable to triage the error without any information.
