### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by Sckaletz** [SkriptLang/Skript#6855]
### Skript/Server Version

```markdown
[16:12:00 INFO]: [Skript] Server Version: 1.21-40-b45d9b6 (MC: 1.21)
[16:12:00 INFO]: [Skript] Skript Version: 2.9.0-pre1 (skriptlang-github)
[16:12:00 INFO]: [Skript] Installed Skript Addons: None
[16:12:00 INFO]: [Skript] Installed dependencies:
[16:12:00 INFO]: [Skript]  - Vault v1.7.3-b131
[16:12:00 INFO]: [Skript]  - WorldGuard v7.0.11-beta1+a801a9d
[16:12:00 INFO]: [Skript]  - GriefPrevention v16.18.4
```

### Bug Description

I'm not really sure, what happened, but suddenly the server just crashed with this error: https://pastebin.com/aERaRa4V

### Expected Behavior

Well, not to crash.

### Steps to Reproduce

I can't really tell you, since I don't know what made it crash.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
Are you using the latest version of Paper or something else? It looks like there may have been an issue with Skript, but the main error in your screenshot comes from the server.

**Comment by EquipableMC** [comment]
> Yea it's the latest version of Paper 1.21. But I think I figured it out. I might have made a skript, that performed an endless loop somehow. Just didn't think that was possible.

check for while loops, and make sure you got a proper wait x seconds/ticks/minutes in there

**Comment by APickledWalrus** [comment]
This does still appear to be a Paper issue. I'll try and see if I can replicate it in any way.

**Comment by ShaneBeee** [comment]
Looking at the error, it goes for miles referencing command dispatch.
You stated you think there's an endless loop.
That is kinda what it looks like, like you've called a command that repeats itself endlessly.

**Comment by APickledWalrus** [comment]
Right, it seems like one of your scripts is causing and error, but Paper is running into an issue when trying to catch/handle it (which is why I recommend a reinstallation of the jar)

**Comment by Sckaletz** [comment]
Yea it seems like the problem is on my hand. Thanks for the help ;-)
