### ISSUE TITLE
"Has Potion" condition producing error

### ISSUE THREAD

**Issue by itsleeoh** [SkriptLang/Skript#6875]
### Skript/Server Version

```markdown
v2.9.0-pre1
```

### Bug Description

"Can't understand this structure..." error message is given when trying to load either example for the "Has Potion" condition.

### Expected Behavior

Detect potion effect of speed, or any other potion effect

### Steps to Reproduce

Load either of the 2 examples from the documentation into a skript file

if player has potion speed:
    send "You are sonic!"

if all players have potion effects speed and haste:
    broadcast "You are ready to MINE!"

### Errors or Screenshots

![errorSkript](https://github.com/SkriptLang/Skript/assets/174900916/63ac9573-4336-49ff-bdab-fd02eb7af974)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by theuwufurry** [comment]
bro this is not a error lol this is a skill issue you dont need %% and you cant use if all players thats not a thing dont report things here untill you asked for help in the discord https://discord.gg/fQNCq82m

**Comment by theuwufurry** [comment]
also all skripts need to start with a event

**Comment by APickledWalrus** [comment]
As mentioned, this is a syntax issue. You can find help at one of these links: https://github.com/SkriptLang/Skript?tab=readme-ov-file#relevant-links

**Comment by itsleeoh** [comment]
My bad, i literally started working with skripts this week and have minimal experience so far
