### ISSUE TITLE
'my' in effect commands

### ISSUE THREAD

**Issue by colton-boi** [SkriptLang/Skript#6877]
### Suggestion

In effect commands you should be able to use "my" instead of "me's" to be grammatically correct and just easier.

### Why?

Currently to do something like enabling your flight, you have to do "set (me|player)'s flight state to true" instead of "set (my|player's) flight state to true"

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
This would be nice but extremely difficult to implement. The 's is part of the properties syntax, so every property syntax would somehow need to support this. I would love to have it, but I genuinely can't think of a way to support it.

**Comment by colton-boi** [comment]
This should be very easy to implement, just replacing src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java's syntax from '[s] to ['][s]

**Comment by sovdeeth** [comment]
> This should be very easy to implement, just replacing src/main/java/ch/njol/skript/expressions/base/PropertyExpression.java's syntax from '[s] to ['][s]

But that would break a ton of stuff and cause parsing times to increase significantly. The required ' is what skript looks for to see if it can parse it as a property expression in the first place.

**Comment by Moderocky** [comment]
This is very unlikely to be added because it would require significant changes to core parts of property syntax.
