### ISSUE TITLE
Cancel Event Bug 

### ISSUE THREAD

**Issue by Mav124004** [SkriptLang/Skript#6878]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-550 (MC: 1.19.4)
[Skript] Skript Version: 2.8.7 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

In the script below, the event should be canceled when the player right-clicks on an NPC named "kowal". However, the event is not being canceled despite the conditions being met.

In both script examples, the event should be canceled

# EXAMPLE 1
on right click:
	if "%target entity of player%" is "kowal":
		cancel event
		kowal(player)
		
		
# EXAMPLE 2
on right click:
	if player is not wearing a helmet:
		cancel event
	if player is not wearing a chestplate:
		cancel event
	if player is not wearing a leggings:
		cancel event
	if player is not wearing a boots:
		cancel event
	if "%target entity of player%" is "kowal":
		kowal(player)

### Expected Behavior

In both script examples, the event should be canceled

### Steps to Reproduce

https://github.com/SkriptLang/Skript/assets/113462926/f304c04e-a566-41fb-91d5-ab4dd5b79f73

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Prorickey** [comment]
I was not able to reproduce your bug, is it still happening on the newest version of Skript?
