### ISSUE TITLE
Timespan#getAs(TimePeriod) truncates to Integer, breaking larger timespans.

### ISSUE THREAD

**Issue by Diclo** [SkriptLang/Skript#6908]
### Skript/Server Version

```markdown
Server: 1.21-75
Skript: Skript-2.9.0
```

### Bug Description

The time subtraction function isn't working.

script:
    set {_pcd} to skutil yaml value "cd.%{_tipo}%" of file "{@file}"
    send "%nl% Tiempo guardado: %{_pcd}% %nl%" to console
    set {_pcd} to "%{_pcd}% seconds" parsed as timespan
    send "%nl% Tiempo convertido: %{_pcd}% %nl%" to console
    set {_pcd-hoy} to convert date now to unix date
    set {_pcd-hoy} to "%{_pcd-hoy}% seconds" parsed as timespan
    send "%nl% Tiempo hoy: %{_pcd-hoy}% %nl%" to console
    subtract {_pcd} from {_pcd-hoy}
    send "%nl% tiempo restado: %{_pcd-hoy}% %nl%" to console
    
   When performing the subtraction of {_pcd} and {_pcd-hoy}, it always results in 0.
   
   
![imagen](https://github.com/user-attachments/assets/79049e04-884c-4ae1-a8ae-3dc7b383cc58)

### Expected Behavior

The result should be the remaining time.

![imagen](https://github.com/user-attachments/assets/7420775d-cf3d-4a85-8d4f-cc466bb6bc8f)

### Steps to Reproduce

command /redem:
  trigger:
    set {_pcd} to skutil yaml value "cd.%{_tipo}%" of file "{@file}"
    send "%nl% Tiempo guardado: %{_pcd}% %nl%" to console
    set {_pcd} to "%{_pcd}% seconds" parsed as timespan
    send "%nl% Tiempo convertido: %{_pcd}% %nl%" to console
    set {_pcd-hoy} to convert date now to unix date
    set {_pcd-hoy} to "%{_pcd-hoy}% seconds" parsed as timespan
    send "%nl% Tiempo hoy: %{_pcd-hoy}% %nl%" to console
    subtract {_pcd} from {_pcd-hoy}
    send "%nl% tiempo restado: %{_pcd-hoy}% %nl%" to console

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by EquipableMC** [comment]
can you send your /sk info?

**Comment by Diclo** [comment]
![imagen](https://github.com/user-attachments/assets/ff3d93ad-9019-4c18-b634-9eb08d13bd0a)

**Comment by sovdeeth** [comment]
Was this working prior to 2.9.0?

**Comment by Diclo** [comment]
> Was this working prior to 2.9.0?

Yes, for example, this is the productivity server:
![imagen](https://github.com/user-attachments/assets/de1e0c2f-4670-4dc1-b0a8-6fc8ebfd87dd)
![imagen](https://github.com/user-attachments/assets/755a9cb7-26e2-4c71-b47d-7f665dcacb53)

**Comment by sovdeeth** [comment]
I wonder if we're running into integer overflow. I'll investigate further.

**Comment by sovdeeth** [comment]
Yes, Math.round() is truncating the value to an integer. 
![image](https://github.com/user-attachments/assets/c66f1106-5ace-4abd-a6a8-9487877e05db)

**Comment by Diclo** [comment]
> Workaround for now is just to do the math before parsing as timespan.

Subtract while both are in Unix date format
oka thanks c:
