### ISSUE TITLE
"On Break" event does not fire while door upper half is broken

### ISSUE THREAD

**Issue by quillincn** [SkriptLang/Skript#6937]
### Skript/Server Version

```markdown
Skript Version: 2.9.0 (skriptlang-github)
Server Version: git-Paper-196 (MC: 1.20.1)
```

### Bug Description

"On Break" event does nothing if the upper half of the door is broken, the lower half works fine. Script used for debug:

```
on break:
    broadcast "Block was broken:"
    broadcast "%event-block%"
```

### Expected Behavior

Expected event will be fired on upper half break and event-block will be sent to chat.

### Steps to Reproduce

1. Use this for debugging:
```
on break:
    broadcast "Block was broken:"
    broadcast "%event-block%"
```
2. Place any door in the world
3. Break it's upper half
4. See no reaction on it

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
![image](https://github.com/user-attachments/assets/8ae21a79-e9f5-4acc-9c33-39ea76b88efc)
![image](https://github.com/user-attachments/assets/985057dd-6280-4108-8dac-27c524854bb1)

Cannot replicate on 2.9.0, 1.21

**Comment by quillincn** [comment]
I apologize. I did a clean install, works fine. Probably one of the plugins creating conflict. Thanks for reply! @sovdeeth
