### ISSUE TITLE
Server Crash when load Skript!

### ISSUE THREAD

**Issue by madebygood** [SkriptLang/Skript#6939]
### Skript/Server Version

```markdown
Skript : 2.8.7
Server : 1.20.1
```

### Bug Description

Often, when the server starts up, Skript loads and then suddenly terminates.
This happens with an EXCEPTION_ACCESS_VIOLATION (0xc0000005) error.

It is suspected that the issue occurs while loading the aliases feature of Skript, according to the logs.

### Expected Behavior

It should operate normally.

### Steps to Reproduce

I don't know

### Errors or Screenshots

[hs_err_pid2444.log](https://github.com/user-attachments/files/16394432/hs_err_pid2444.log)
[hs_err_pid10236.log](https://github.com/user-attachments/files/16394433/hs_err_pid10236.log)
[replay_pid2444.log](https://github.com/user-attachments/files/16394434/replay_pid2444.log)
[hs_err_pid1012.log](https://github.com/user-attachments/files/16394435/hs_err_pid1012.log)

![image](https://github.com/user-attachments/assets/acc1da1b-d434-4082-bacc-d543ba2bd9f0)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by JonanekDev** [comment]
Same error on Paper 1.21

**Comment by APickledWalrus** [comment]
What version of Java are you using? What system/OS are you hosting with? Are you able to try reinstalling Skript?

**Comment by APickledWalrus** [comment]
Does this issue occur with 2.9? I might recommend reinstalling Java

**Comment by Emmett1027** [comment]
The crash might be because of the code. If code repeats too much, it crashes; I suggest you look at any loops you may use in your code. This thing happened with me once, and it was only because of my skript code.

**Comment by Moderocky** [comment]
Closing due to no response.
