### ISSUE TITLE
New Effect - Narrator

### ISSUE THREAD

**Issue by aaaeeeMC** [SkriptLang/Skript#6943]
### Suggestion

I would like to request a new feature (obviously), more specifically **a new effect**. Judging by the title of this suggestion, you might already know. I'll explain how it works. You already know that the narrator is an option in Minecraft in the accessibility settings that can help people with visual problems by talking, telling what actions the users do. I hope this can somehow be used within Skript. The format could be something like "narrate %string% (to|for) %players%". You could also be able to modify the pitch of the narrator's voice and the speed at which it speaks, so the effect format could be "narrate %string% (to|for) %players% [with] [pitch %number%] [and] [volume %number]". If the format is wrong, I apologize, but you get the idea. 2.10 is a big milestone after all, right? Good day :) I hope you'll consider my proposal.

### Why?

The narrator can be useful, it can be used as a vocal version of the send effect, narrating instead of sending a message in chat. If you want to make a script where you turn yourself into a robot, for example, and the scoreboard has a battery percentage, and if it's low then it narrates "Low battery warning!". If you switch to, for example, gun mode, then it narrates "Gun Mode Activated". Pretty cool, right?

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment]
After doing a quick javadocs search I don't believe this suggestion is currently possible, there's nothing for forcing narrator or reading messages

**Comment by Efnilite** [comment]
the narrator is definitely client-sided, there's no reason why it would be on the server

**Comment by sovdeeth** [comment]
As cool as this would be, it's sadly impossible with Minecraft is currently written. Maybe one day if the ability is added to Minecraft's protocol.
