### ISSUE TITLE
A cancellable event for when blocks affected by gravity turn into falling block entities

### ISSUE THREAD

**Issue by furiouswhqle** [SkriptLang/Skript#6953]
### Suggestion

The title is pretty self-explanatory.
I'd imagine it would be something like this:

```
on block fall:
    cancel event
```

### Why?

It would be useful for servers I build on, and i could easily build with sand and other gravity affected blocks without having to use /tick freeze.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Pikachu920** [comment]
isn't this part of the block physics event?

**Comment by furiouswhqle** [comment]
> isn't this part of the block physics event?

I didn't see that when I initially checked documentation, thanks for letting me know
