### ISSUE TITLE
Add spark implementation

### ISSUE THREAD

**Issue by Alyanos22** [SkriptLang/Skript#6971]
### Suggestion

Add a implementation for the [Spark](https://www.spigotmc.org/resources/spark.57242/) plugin.

### Why?

It will help us to identify which of our skripts are "trash"

### Other

Nope

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
Spark has no API for this. See #5918
