### ISSUE TITLE
Colored Issue With latest (2.9.1) version

### ISSUE THREAD

**Issue by JustDavide** [SkriptLang/Skript#7005]
### Skript/Server Version

```markdown
09:15:53 [INFO] [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
09:15:53 [INFO] [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
09:15:53 [INFO] [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
09:15:53 [INFO] [Skript] Server Version: git-Paper-497 (MC: 1.20.4)
09:15:53 [INFO] [Skript] Skript Version: 2.9.1 (skriptlang-github)
09:15:53 [INFO] [Skript] Installed Skript Addons: 
09:15:53 [INFO] [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
09:15:53 [INFO] [Skript]  - skript-reflect v2.5.1 (https://github.com/SkriptLang/skript-reflect)
09:15:53 [INFO] [Skript]  - SkBee v3.5.8 (https://github.com/ShaneBeee/SkBee)
09:15:53 [INFO] [Skript] Installed dependencies: 
09:15:53 [INFO] [Skript]  - Vault v1.7.3-b131
09:15:53 [INFO] [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

When trying to make a skript that created colored tags I encountered this weird bug (discussed with other members of skUnity)

I tried to make 

`on load:
    if {tags::*} is not set:
        set {tags::test1} to "&aTest1"
        set {tags::test2} to "&dTest2"

command /gettag <string>:
    trigger:
        send formatted {tags::%arg%} to player

command /createtag <string> <string>:
    usage: &cUse: &7/createtag <tagName> <tagFormat>
    trigger:
        set {tags::%arg-1%} to arg-2`
        
this skript. If I tried to do /gettag test1 everything works fine and I get a colored text.

if I do /createtag test3 &ctest3 and then /gettag test3 I get an uncolored text

(I tried replacing formatted with colored)

![Screenshot 2024-08-29 150135](https://github.com/user-attachments/assets/1b681e35-1fc9-4f59-8bca-038049a2ada0)

### Expected Behavior

I should get the new tag colored instead of the uncolored one. (Mind that the tags set under "on load:" do work and get colored)

### Steps to Reproduce

I just created that code, nothing more, nothing less.

### Errors or Screenshots

![Screenshot 2024-08-29 150840](https://github.com/user-attachments/assets/1ffc5e95-4676-4faf-9e66-a3ef4ca85243)
![Screenshot 2024-08-29 150135](https://github.com/user-attachments/assets/9d584a9c-1e1f-415e-b760-923331202142)

### Other

Downgrading to the previous version (2.9.0) solves the issue

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by GStudiosX2** [comment]
Wasn't this always the case where command arguments are uncolored

**Comment by JustDavide** [comment]
> Wasn't this always the case where command arguments are uncolored

no, it wasn't. Not changing any code and downgrading works, it's the new version that breaks it

**Comment by Efnilite** [comment]
Cannot reproduce on latest `dev/patch` if I use `/createtag test3 &ctest3` or `/createtag test4 <red>test4` 

Code:
```
on load:
	if {tags::*} is not set:
		set {tags::test1} to "&aTest1"
		set {tags::test2} to "&dTest2"

command /gettag <string>:
	trigger:
		send formatted {tags::%arg%} to player

command /createtag <string> <string>:
	usage: &cUse: &7/createtag
	trigger:
		set {tags::%arg-1%} to arg-2
```

sk info
```
[20:06:30 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:06:30 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[20:06:30 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[20:06:30 INFO]: [Skript] Server Version: 1.21.1-12-1798e94 (MC: 1.21.1)
[20:06:30 INFO]: [Skript] Skript Version: 2.9.2 (selfbuilt-unknown)
[20:06:30 INFO]: [Skript] Installed Skript Addons: None
[20:06:30 INFO]: [Skript] Installed dependencies: None
```

**Comment by JustDavide** [comment]
> Cannot reproduce on latest `dev/patch` if I use `/createtag test3 &ctest3` or `/createtag test4 <red>test4`
> 
> Code:
> 
> ```
> on load:
> 	if {tags::*} is not set:
> 		set {tags::test1} to "&aTest1"
> 		set {tags::test2} to "&dTest2"
> 
> command /gettag <string>:
> 	trigger:
> 		send formatted {tags::%arg%} to player
> 
> command /createtag <string> <string>:
> 	usage: &cUse: &7/createtag
> 	trigger:
> 		set {tags::%arg-1%} to arg-2
> ```
> 
> sk info
> 
> ```
> [20:06:30 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
> [20:06:30 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
> [20:06:30 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
> [20:06:30 INFO]: [Skript] Server Version: 1.21.1-12-1798e94 (MC: 1.21.1)
> [20:06:30 INFO]: [Skript] Skript Version: 2.9.2 (selfbuilt-unknown)
> [20:06:30 INFO]: [Skript] Installed Skript Addons: None
> [20:06:30 INFO]: [Skript] Installed dependencies: None
> ```

Prob. got fixed in newer version ig? Haven't used skript lately

**Comment by erenkarakal** [comment]
Closing this issue since neither Efnilite nor I can reproduce it and it has been inactive for a month.
