### ISSUE TITLE
Full Treesitter Support

### ISSUE THREAD

**Issue by Eveeifyeve** [SkriptLang/Skript#7077]
### Suggestion

Well Treesitter is a generator parser for syntaxes for languages. 
Common languages support Treesitter for syntax support across a lot of IDE's 
An example IDE's that you would be able to support is [neovim](https://github.com/nvim-treesitter/nvim-treesitter), [zed](https://github.com/zed-industries/zed/blob/main/crates/language/src/syntax_map.rs) and more.

link: https://tree-sitter.github.io/tree-sitter/

### Why?

It would be useful as you can support a lot of IDE Grammers for Skript as you originally wanted to Grammer for it.

### Other

If you need I will be able to help you out.
**Just to note you can do it in [java](https://github.com/tree-sitter/java-tree-sitter/tree/master/src/main/java/io/github/treesitter/jtreesitter) btw.**

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
Similar to your post on LSPs, if you want this it's likely you're going to need to do it yourself. You may want to check out skript-grammar for similar regex rules for skript.

**Comment by Eveeifyeve** [comment]
> Similar to your post on LSPs, if you want this it's likely you're going to need to do it yourself. You may want to check out skript-grammar for similar regex rules for skript.

Okay well I guess I will start a skript-treesitter repo on my account.

**Comment by Eveeifyeve** [comment]
I will keep it unofficial, but if you want it official, let me know we can work on transferring it to skript org.
https://github.com/Eveeifyeve/skript-treesitter.git

**Comment by Eveeifyeve** [comment]
Closing this for now, but I have it on my list todo so I will do it unofficial.

**Comment by Eveeifyeve** [comment]
Closing this for now, but I have it on my list todo so I will do it unofficial.

**Comment by Eveeifyeve** [comment]
This might require a lexar to be implemented.
