### ISSUE TITLE
(old and new block on walk) and (single walk event) events.

### ISSUE THREAD

**Issue by FUZIK** [SkriptLang/Skript#716]
## (old and new block on walk) and (single walk event) events.

examples:
```
on step on ores:
	broadcast "%past location%"
	broadcast "%future block%"
```
please add single walk event
```
on step:
	broadcast "top-top-top of %player%" to block
```

spigot api:

- [PlayerMoveEvent](hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerMoveEvent.html)

methods:
```
getFrom(); setFrom(loc);
getTo(); setTo(loc).
```
thanks to all and Bensku. ✌️

**Comment by Nicofisi** [comment]
Wouldn't it hurt performance? If not, I can just add it because it's rather trivial

**Comment by bensku** [comment]
Skript doesn't have generic on move for performance reasons. It is likely that even excessive use of specific walk events might cause lag.

**Comment by Nicofisi** [comment]
Can this be marked as wontfix then, or will we keep it open until someone rewrites skript in bytecode for performance lolol

On the other hand and for real though , while I understand it might lag ~~a lot~~, I see how it might be considered a rather basic feature by some people, hmm. How about implementing this, with a config option to enable the whole thing?
