### ISSUE TITLE
There is an error in Turkish translation!

### ISSUE THREAD

**Issue by yrexly** [SkriptLang/Skript#7160]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Pufferfish-52 (MC: 1.20.4)
[Skript] Skript Version: 2.9.3 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies:
[Skript]  - Vault v1.7.3-b131
```

### Bug Description

When I set the language of the skript plugin to Turkish, it gives the error "skript command.reload.error line infoskript command.reload.error informationskript command.reload.linetails".

### Expected Behavior

It shouldn't give an error

### Steps to Reproduce

I translated it into Turkish

### Errors or Screenshots

![5F2C4BCB-6FD7-47B2-814A-C0BF0323618E](https://github.com/user-attachments/assets/b57e78a9-7922-41ff-9b96-7942e6792c80)

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by erenkarakal** [comment]
Is it only like this during server startup or always?

**Comment by yrexly** [comment]
When the server starts and /sk reload

**Comment by erenkarakal** [comment]
I wasn't able to reproduce this on my Skript 2.9.3 server, can you try deleting the plugins/Skript/lang folder and restart the server?

**Comment by yrexly** [comment]
This still happens when translated into Turkish.

**Comment by erenkarakal** [comment]
can you send your `turkish.lang` file inside `plugins/Skript/lang/` through a paste service or Discord? something might be happening when loading the file

**Comment by yrexly** [comment]
https://dosya.co/3xy35sqv8dr5/turkish.rar.html
