### ISSUE TITLE
unwanted event-block handling changes

### ISSUE THREAD

**Issue by Pilvinen** [SkriptLang/Skript#72]
All of a sudden event-block handling has changed and is being done in a very retarded way which breaks a lot of backwards compatibility.

The code below used to work and now it doesn't. In the past Skript held the value of event-block and you could reliably use it in your code to refer to the block which was the event-block at the moment of the event happening. "if event-block is {@kehikko-tammi}" would be true even after waiting for 1 tick and confirming that the block at the location of event-block has indeed changed to air, ie:

```
on break of {@kehikko-tammi} or {@kehikko-kuusi}:
  wait for 1 ticks
  block at location of event-block is air

  if event-block is {@kehikko-tammi}:
    drop {@kehikko-tammi} at location of event-block
  if event-block is {@kehikko-kuusi}:
    drop {@kehikko-kuusi} at location of event-block

```

Now as a workaround you have to use the code below:

```
on break of {@kehikko-tammi} or {@kehikko-kuusi}:

  if event-block is {@kehikko-tammi}:
    wait for 1 ticks
    block at location of event-block is air
    drop {@kehikko-tammi} at location of event-block
  if event-block is {@kehikko-kuusi}:
    wait for 1 ticks
    block at location of event-block is air
    drop {@kehikko-kuusi} at location of event-block

```

Which proves that Skript has started handling "event-block" in a very different way - it's updating it's value -> making extra checks -> making things run slower as a consequence (the proper way to check the true and current event-block was to check "block at location of event-block" if you wanted to know what it is). 

This change makes the code structure more constrained and longer than necessary which is not good. This needs to be reverted back to the way it was.

**Comment by Pilvinen** [comment]
Or if for some reason you can't fix this then at the very least you would need to fix past states:

```
on break of {@kehikko-tammi} or {@kehikko-kuusi}:
  wait for 1 ticks
  block at location of event-block is air

  if event-block **was** {@kehikko-tammi}:
    drop {@kehikko-tammi} at location of event-block
  if event-block **was** {@kehikko-kuusi}:
    drop {@kehikko-kuusi} at location of event-block

```
--->
[08:51:34 ERROR]: Cannot use time states after the event has already passed (rakentaminen.sk, line 258: if event-block was {@kehikko-tammi}:')

**Comment by bensku** [comment]
Could you tell when it did work? Before my fork, or before @Mirreski's fork?

**Comment by Pilvinen** [comment]
Some of your latest updates broke it.

**Comment by bensku** [comment]
Probably going for past/future states fix, if anyone happens to stumble to this issue. See #671 for some information.
