### ISSUE TITLE
A global function named '<function>' a;readu exists in script '<script name>'

### ISSUE THREAD

**Issue by NobleSkye** [SkriptLang/Skript#7225]
### Skript/Server Version

```markdown
2.9.4
also 2.9.3
havent tested any other versions

with skript gui but breaks without it
```

### Bug Description

create a function it loads properly and then it on reload again says the function already exits in the function that created this

### Expected Behavior

to reload without error and keep the same function name

### Steps to Reproduce

create a function ie
function sayhello(p: player):
    send "hello" to {_p}
    
   command /hellworld:
    trigger:
         sayhello(player)
         
         
         /sk reload helloworld.sk

### Errors or Screenshots

![image](https://github.com/user-attachments/assets/135c35b1-bc92-4c7b-900b-dc41354c92ff)
![image](https://github.com/user-attachments/assets/b4d0bc33-9289-4706-92c2-2a7da2127d70)
--2nd reload--
![image](https://github.com/user-attachments/assets/16a7aea2-3d08-4c9f-bc30-51b423d2969e)
-- same code--
![image](https://github.com/user-attachments/assets/60f683d2-7dab-4d90-b884-3add72587c5a)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by erenkarakal** [comment]
![image](https://github.com/user-attachments/assets/39ce27f0-a46a-446b-90ca-3084000e9d83)
used the code you sent but couldn't reproduce it

**Comment by NobleSkye** [comment]
> ![image](https://github.com/user-attachments/assets/39ce27f0-a46a-446b-90ca-3084000e9d83)
> 
> used the code you sent but couldn't reproduce it
> 
> using Skript 2.9.4

It happens no matter what code I write for some reason, if I don't make a big enough change, I can send the jar file & hash maybe see if it just is a bad file though I redownloaded many times

**Comment by NobleSkye** [comment]
0246a9db68350279550e37587de34eb1
here is the has of the file
`Skript-2.9.4.jar`

**Comment by sovdeeth** [comment]
please send the output of /sk info
The issue format requires it but you did not fill it out

**Comment by NobleSkye** [comment]
![image](https://github.com/user-attachments/assets/b85fbb88-41e3-4f6e-8b0d-8ad80eafafdd)
![image](https://github.com/user-attachments/assets/e6862239-d580-4e9e-a272-8591471fed19)

i didnt know that is what it was asking for - it should say to use /sk info to fill out that section - but thats just me

**Comment by sovdeeth** [comment]
Please check if you can reproduce without addons. Many of those are quite old and may cause issues.

> it should say to use /sk info to fill out that section

![image](https://github.com/user-attachments/assets/4206baf1-6ea6-4ef6-8c28-22cf299e2417)

**Comment by NobleSkye** [comment]
![image](https://github.com/user-attachments/assets/7e706e9f-d31e-4f38-9ef5-80d3ecf6473a)
![image](https://github.com/user-attachments/assets/4a4beffd-907c-4ef4-a72c-a7d522d29f52)
my bad, yeah must of been an addon. ill have to re look a which one does this, it was working before then suddenly stopped, ill look and try
