### ISSUE TITLE
sqrt(n) is unfathomably wrong

### ISSUE THREAD

**Issue by fsdghyiusfdhiusodf** [SkriptLang/Skript#7248]
### Skript/Server Version

```markdown
any
```

### Bug Description

sqrt(n) should return a list of two values which are the inverse of one another, but due to this breaking code, I've come up with a solution:
sqrt(n) = (-x|x)
since median or modal wouldn't do anything, sqrt(n) = (x + -x)/2 = 0/2 = 0

### Expected Behavior

sqrt(n)=0

### Steps to Reproduce

on load:
  broadcast sqrt(25)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Efnilite** [comment]
🗿

**Comment by fsdghyiusfdhiusodf** [comment]
nah wdym invalid
