### ISSUE TITLE
[Need Help] How to get completely command help?

### ISSUE THREAD

**Issue by Mooling0602** [SkriptLang/Skript#7258]
### Skript/Server Version

```markdown
It may not a Skript bug, if need, I'll provide later.
```

### Bug Description

Very sorry but I can't get help from Discord for no response, so I post my issue here. This is not a Skript bug I think.

### Expected Behavior

Console print true command for MCDR to parse and run it's commands and response the executor who is a player.

### Steps to Reproduce

I'm trying to register [MCDReforged](https://mcdreforged.com) commands to a sk plugin, then players can execute then with "/".
But I got into trouble with getting the correct completely command text. Here is my code:
```sk
on command:
    if the command start with "!!":
        send "<%player%> %command% %arguments%" to the console
```

### Errors or Screenshots

When a player try to execute MCDR commands with "/" command system, something unexpected wrong like this happened:
```bash
> sk reload MCDR_Commands.sk
[Server] [21:22:53 INFO]: [Skript] Reloading MCDR_Commands.sk...
[Server] [21:22:53 INFO]: [Skript] Successfully reloaded MCDR_Commands.sk. (8ms)
[Server] [21:22:58 INFO]: CleMooling issued server command: /!!etp back death
[Server] [21:22:58 INFO]: <CleMooling> !!etp back and death
[Server] [21:26:31 INFO]: CleMooling issued server command: /!!info
[Server] [21:26:31 INFO]: <CleMooling> !!info <none>
```
That's terrible, extra words makes the wrong command sent to console.
I hope someone can help me with this, thanks a lot!

### Other

Raw link: https://discord.com/channels/138464183946575874/1316758705596923905
This issue can be delete directly if you're willing to help me by replying in the Discord post. Thanks a lot!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by NagasonicDev** [comment]
Use %full command%, as %arguments% is a list, Skript automatically formats it as one, so that it would be like "back and death". @Mooling0602 This should work, so please close the issue ASAP.

**Comment by Mooling0602** [comment]
> Use %full command%, as %arguments% is a list, Skript automatically formats it as one, so that it would be like "back and death". @Mooling0602 This should work, so please close the issue ASAP.

Thanks a lot

**Comment by sovdeeth** [comment]
@Mooling0602 Please do not post help questions here, this is for bug reports and suggestions only!

**Comment by Mooling0602** [comment]
> @Mooling0602 Please do not post help questions here, this is for bug reports and suggestions only!

Very sorry, I'll not do this any more.
