### ISSUE TITLE
i want a free iphone 12

### ISSUE THREAD

**Issue by Azexxx** [SkriptLang/Skript#7295]
### Suggestion

i want a free iphone 12

### Why?

i want a free iphone 12

### Other

i want a free iphone 12

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by erenkarakal** [comment]
Good for you man.

**Comment by Pikachu920** [comment]
its not an iphone 12 but you could try this sweepstakes:
https://www.macobserver.com/deals/win-an-iphone-16-pro-max-epic-international-christmas-new-year-giveaway/
