### ISSUE TITLE
Proposal: Expression for moon phase

### ISSUE THREAD

**Issue by DatArnoGuy** [SkriptLang/Skript#746]
I would like, if there would be an expression for moon phase. ex. full moon and new moon. Also event "on moon phase change" would be very nice.

**Comment by TheBentoBox** [comment]
`on moon phase change` is basically just `every minecraft day` so I'd say it's completely pointless, but a vanilla expression for the moon phase makes sense.

**Comment by TheLimeGlass** [comment]
SkQuery has this. I see no point in adding it as said above, because Skript has that.

**Comment by TPGamesNL** [comment]
I don't think this should be in vanilla Skript, would prefer to leave this up to addons (e.g. SkQuery), unless this stuff is added to Bukkit.

Closing for reason above since this is an old issue, feel free to reopen if you think this should be added

**Comment by TheBentoBox** [comment]
Not gonna reopen on my own but there is [*Paper* API support for moon phase](https://papermc.io/javadocs/paper/1.18/org/bukkit/World.html#getMoonPhase()) and we already have some Paper-specific feature implementations.

**Comment by TPGamesNL** [comment]
Oh I didn't look at the Paper Javadocs, in that case I'm reopening this :)
