### ISSUE TITLE
Proposal: Ability to get skull owner from player head on the ground

### ISSUE THREAD

**Issue by DatArnoGuy** [SkriptLang/Skript#747]
I would like, if there was way to get player name from player head on the ground. Like expression "skull owner" or something.

**Comment by TheLimeGlass** [comment]
Skellett has this if you need it asap + head rotation.

But as Head's in GUI's are possible with Skript, this should be a feature in Skript.

**Comment by Snow-Pyon** [comment]
@TheLimeGlass would be good if you get time to do a pull request to implement this, it wouldn't change much from the current Skellett's expression so. And head rotation is on vanilla Skript as far I'm aware.

**Comment by Wealthyturtle** [comment]
Closing in favor of #534
