### ISSUE TITLE
Upcoming: 1.13 changes that will need addressing

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#751]
### Aliases

- [x] Numeric Block ID's ["no longer exist"](https://twitter.com/Dinnerbone/status/890549741888712704)
  - Numeric ID's have been deprecated since 1.7, but it seems that they won't be usable externally anymore come 1.13, which means Skript's method for referencing materials (string -> ID mapping) will likely need to be rewritten (likely string -> material name) unless Spigot adds some sort of ID to material mapper.
- [x] Numeric Damage/data values ["no longer exist"](https://twitter.com/Dinnerbone/status/890549741888712704) (same tweet)
  - Mojang has long been moving to a "block state" system, which is essentially a series of named bit masks (e.g. `facing` or `open`) applied to an internal data value to draw out a state as an object.
  - Example: what is currently `log2:2` (an east-west acacia log) would become `acacia_log[axis=x]`. This would break data value checks (e.g. checking a lever's powered state via `if data value of event-block < 8` would need rewriting, perhaps as `if state "powered" of event-block is false`)
  - In case it's not obvious already, these changes include making all block variants into their own separate blocks with their own internal ID (i.e. birch logs won't be stored in the same ID as oak logs anymore, nor will each color of wool be stored together). 
  - For things that actually use damage values to represent damage, such as tools and armor, the damage will now be stored in a `Damage` NBT tag. 
  - How this will need to be addressed by Skript will depend on Spigot's implementation of full block state support. That being the case, I will update this as necessary in the future.
- [For further reading, Dinnerbone's post on upcoming breaking changes](https://www.reddit.com/user/Dinnerbone/comments/6l6e3d/a_completely_incomplete_super_early_preview_of/). He keeps it up-to-date as their work on 1.13 progresses.

---

### Gameplay

- [ ] New Entities
  - [ ] Dolphins: spawn commonly in water, can swim with players to give a new status effect. Play with dropped items. Suffocate on land. Find nearby treasure when fed cod.
  - [ ] Drowned: underwater zombies. Throws tridents to attack (ranged).
  - [ ] Phantom: flying undead hostile mob, spawns around players who haven't slept recently.
  - [ ] Turtle: spawn on/near beaches. Breed by laying eggs, which they return to their "home beach" (spawn location) to do; this location may be API-accessible.
  - [ ] Fish mobs:
    - [ ] Cod: spawn in oceans mid-range temperature. Drop cod items. Swim in schools of up to 9.
    - [ ] Salmon: spawn in colder oceans or rivers. Drop salmon items. Swim in schools of up to 6.
    - [ ] Pufferfish: spawn in warm oceans. Inflate when certain entities approach, dealing damage on contact and inflicting poison.
    - [ ] Tropical fish: spawn in warm oceans. Come in tons of different colors/patterns. Drop clownfish currently (I expect this to change).
- [ ] New Status Effects
  - [ ] Conduit Power: given by Conduits (a new block that can be powered to give an AoE effect like beacons).
  - [ ] Dolphin's Grace: obtained while swimming with dolphins. Increases swimming speed.
  - [ ] Slow Falling: just like it sounds
- [ ] Biomes
  - [ ] Added biomes with different temperatures: `warm_ocean`, `warm_deep_ocean`, `lukewarm_ocean`, `deep_lukewarm_ocean`, `cold_ocean`, `deep_cold_ocean`, `frozen_ocean`, and `deep_frozen_ocean`. Frozen ocean already exists but doesn't generate until 1.13. Warm deep oceans exist but don't generate.
  - [ ] Outer End dimension uses new `sky_island_low`, `sky_island_medium`, `sky_island_high`, and `sky_island barrens` biomes.
  - [ ] Tons of biomes have been renamed, both the internal ID and external name. [Chart here](https://gyazo.com/27e9a6bd2b6220e13897b9ffb54ccd06).
- [ ] Enchantments
  - [ ] Channeling: one level, summons lightning in storms, applicable to tridents.
  - [ ] Impaling: five levels, deals more damage to sea creatures, applicable to tridents.
  - [ ] Loyalty: three levels, causes tridents to return on throw and is only applicable to them.
  - [ ] Riptide: three levels. Makes tridents unable to be thrown unless in rain or water, but when thrown incompatible with Loyalty/Channeling.
- [ ] Particles
  - [ ] Added `bubble_column_up`, `bubble_pop`, `current_down`, and `squid_ink` particles.
  - [ ] Tons of particle IDs have changed, [chart here](https://gyazo.com/6b86cea5f80b464268960752c119d008). Unsure if this will affect the Bukkit API.
- [ ] Gameplay
  - [ ] Swimming: players can now properly swim by sprinting in water. May be a retrievable state like elytra gliding, not sure.

**Comment by bensku** [comment]
It will be certainly... Interesting when numeric ids are gone. Reworking aliases is quite high amount of work.

**Comment by TheBentoBox** [comment]
Who knows, I may be wrong and this may be something similar to 1.8 where vanilla Minecraft "stopped supporting" numeric IDs but they are still entirely accessible and usable by 3rd party software (plugins and mods). But yeah, the wording definitely makes it sounds like they'll be 100% gone except for extremely internal stuff related to data storage, so this will be a difficult update.

**Comment by TheBentoBox** [comment]
Actually, looks like I'm definitely not reading too much into it or something; [here's a comment from Dinnerbone](https://www.reddit.com/user/Dinnerbone/comments/6l6e3d/a_completely_incomplete_super_early_preview_of/dkqyxod/?context=3) from a couple days ago, his words being "All states are serialised to disk and the old "block id" or "block data" numbers literally don't exist anywhere anymore".

**Comment by Nicofisi** [comment]
Some related interesting stuff:


https://www.spigotmc.org/threads/minecraft-1-13-what-to-expect.288714/

https://www.spigotmc.org/threads/minecraft-1-13-api-preview-2.296779/

1.13 Spigot API, second preview of changes: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/compare/diff?targetBranch=refs%2Fheads%2Fmaster&sourceBranch=refs%2Fheads%2Fpreview&targetRepoId=11

**Comment by bensku** [comment]
I have gone through the current planned changes to the API. Should be ok, though Skript will need some additional changes (besides aliases stuff).

**Comment by Syst3ms** [comment]
Reminder : Spigot will provide a ton of legacy interfaces that *should* make 1.12 plugins work on 1.13, even though they'll fail to compile against 1.13.

**Comment by bensku** [comment]
Skript is unlikely to be able to use them. On Spigot 1.9-1.12, material names do not match Vanilla names, but there is an UnsafeValues method to work around the issue. On 1.13. names are identical to Vanilla material ids (according to md_5 on Spigot IRC), but the UnsafeValues method no longer exists.

It is not possible to take only "some" legacy compatibility. It is all byte code transformers applied by Spigot, or none of them. And I think for Skript, none is only option...

**Comment by bensku** [comment]
Tracking aliases stuff at #431. Other changes - gameplay features can be added here @TheBentoBox @Snow-Pyon

**Comment by TheBentoBox** [comment]
I've updated the post with important 1.13 gameplay features @bensku

**Comment by TheBentoBox** [comment]
Closing in favor of #1385.
