### ISSUE TITLE
Lists returned by a function don't keep indices

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#811]
Sorry if this has already been reported, it feels like a report I've seen before but I tried doing a search and didn't find this specific issue reported.

I was trying to write myself a handy function that would let me pass in two lists of objects - one representing list indices and one representing list values - and it would return me one list where the two were mapped together, as a way to allow me to quickly build mapped lists. However, I've come across the problem that my function's returned list loses all of the "custom" (so to speak) indices, instead returning to the default upwards-counting indices we're used to. My test code:

```
function getMappedList(indices: objects, values: objects) :: objects:
	loop {_indices::*}:
		set {_val} to "%loop-value%"
		set {_return::%{_val}%} to {_values::%loop-index%}
	if size of {_values::*} > size of {_indices::*}:
		loop integers from (size of {_indices::*} + 1) to size of {_values::*}:
			add {_values::%loop-value%} to {_return::*}
	return {_return::*}
```

I have confirmed (via a debug in the function prior to its return) that it correctly maps each index to each value as I expect it do (AKA, the code works), and the list is in the state I want it directly prior to being returned, but the returned list never has the same indices; it just "reverts" to indices of 1, 2, 3, and so on ad infinitum. It basically seems like the function thinks of the returned objects as just that (a list of objects) as opposed to a list of key=value pairs like lists actually are.

Given the nature of Skript and how functions handle lists, I'm not sure how fixable this is without a big change. Hopefully, something can be done about this, because otherwise my concept (as well as any other function that returns an index-reliant list) is essentially impossible. The only workaround I think think of is also passing it the name of a global list variable to store it in temporarily, which will work for now but is definitely not ideal.

This is occurring for me on Spigot 1.12.0 with Skript dev25. Apologies if this has already been fixed in a more recent version; I don't think it has since I keep a good eye on the release notes. It's just something I noticed a few moments ago while on my live server, which isn't updated past dev25 due to the parser performance issues on newer versions.

Cheers!

**Comment by Syst3ms** [comment]
Yeah it is hard to fix without Skript 3.0. Although, what can be done is make it so getting values from a list can return an array of Pairs/Entrys and make Skript treat these kind of arrays as lists with indices. Kinda hacky, but I think it would work.

**Comment by sspmrsomebody1** [comment]
I created an list with custom indices in a command and when it's accessed later I had the same problem. It's not returned through a function.
Relevant code:
`
command /createkit <text>:
	permission: skKitpvp.createkit
	trigger:
		loop 40 times:
			set {_slot} to loop-value - 1
			player's inventory's slot {_slot}'s type isn't air
			set {kitpvp.kit::%arg 1%::%{_slot}%} to player's inventory's slot {_slot}
			broadcast "var kitpvp.kit::%arg 1%::%{_slot}% = %{kitpvp.kit::%arg 1%::%{_slot}%}%"
		set {kitpvp.kit::%arg 1%::*} to all items in player's inventory
		set {kitpvp.kit::%arg 1%} to arg 1
		send "&6Successfully created the &e%arg 1%&6 kit."
`
`command /kit <text="">:
	trigger:
		if arg 1 is "":
			set {_msg} to "&6Available kits:&f"
			loop {kitpvp.kit::*}:
				set {_msg} to "%{_msg}% %loop-value%"
			send {_msg}
		else if {kitpvp.kit::%arg 1%} is set:
			{kitpvp.playerKit::%player%} is set:
				send "&cYou have already ordered a kit!"
				stop
			loop {kitpvp.kit::%arg 1%::*}:
				broadcast "var kitpvp.kit::%arg 1%::%loop-index% = %{kitpvp.kit::%arg 1%::%loop-index%}%"
				set player's inventory's slot loop-index parsed as number to loop-value
			set {kitpvp.playerKit::%player%} to arg 1
			send "&6Recieved the &e%arg 1%&6 kit."
		else:
			send "&cThat kit doesn't exist!"`
`command /clearkit:
	trigger:
		kitpvp_clearKit(player)
		clear player's inventory
		send "&6Cleared your kit."`
Console with debug messages:
`[14:58:36 INFO]: mrsomebody1 issued server command: /createkit diamond
[14:58:36 INFO]: mrsomebody1 [ae08e1fc-bfcc-3517-b873-a94841a42f94]: /createkit diamond
[14:58:36 INFO]: var kitpvp.kit::diamond::0 = diamond sword
[14:58:36 INFO]: var kitpvp.kit::diamond::38 = diamond chestpiece
[14:58:41 INFO]: mrsomebody1 issued server command: /minecraft:clear
[14:58:41 INFO]: [mrsomebody1: Cleared the inventory of mrsomebody1, removing 2 items]
[14:58:44 INFO]: mrsomebody1 issued server command: /kit diamond
[14:58:44 INFO]: mrsomebody1 [ae08e1fc-bfcc-3517-b873-a94841a42f94]: /kit diamond
[14:58:44 INFO]: var kitpvp.kit::diamond::1 = diamond sword
[14:58:44 INFO]: var kitpvp.kit::diamond::2 = diamond chestpiece`

**Comment by bensku** [comment]
The issue here is that {variable::*} generally refers to values of a list in natural order. I say generally, because with loops it obviously also allows access to indices.

The new variable system that is currently in works attempts to persist indices at all times. Unfortunately it is a huge change and will take at least a few months to be ready for most people. Also, this is a breaking change; some scripts might not expect indices to be kept.

**Comment by Wealthyturtle** [comment]
Closing in favor of #3127
