### ISSUE TITLE
Enable/Disable Skript File Effects

### ISSUE THREAD

**Issue by Blueyescat** [SkriptLang/Skript#822]
(Suggestion)

## Enable/Disable/Reload Skripts
```vb
(enable|load) s(c|k)ript [file] %string% [[logging] in %objects%]

reload s(c|k)ript [file] %string% [[logging] in %objects%]

(disable|unload) s(c|k)ript [file] %string%
```
These effects completely do the same with **/skript** command expect logging errors/warnings to the sender. If the Skript is already loaded/unloaded or the Skript file doesn't exist it shouldn't do anything.

The `[logging] in %objects%` part supports only a list variable. Errors and/or warnings while parsing a Skript go to this list variable by order.

---
### Examples
```vb
enable script "Test.sk" logging in {_logs::*}

reload skript "Folder/Test.sk" logging in {_output::*}

unload script "Test.sk"
```

**Comment by Louis-D** [comment]
I like the idea 👍

**Comment by WheezyGold7931** [comment]
I could PR this @Blueyescat, just not with logging as I have no idea how that works

**Comment by Blueyescat** [comment]
It would bettter with logging :sparkles:

**Comment by bensku** [comment]
Disabling parse logging is not supported and actually, might be nearly impossible. Might be good idea to just leave it there.

**Comment by Blueyescat** [comment]
I don't understand..

**Comment by Sashie** [comment]
I think he means he wants that syntax to output some logs to a variable

**Comment by tutur1004** [comment]
We need this plzzzz addd :D :D 💃

**Comment by boucki** [comment]
great idea,
















### send me nudes
