### ISSUE TITLE
'blocks' should be usable alias for 'meters'

### ISSUE THREAD

**Issue by whoshenry** [SkriptLang/Skript#828]
On the latest Skript version, on startup, it doesn't recognise this line - [Skript] Can't understand this expression: 'the location 1.5 blocks in front of attacker's head' (axes.sk, line 304: set {_hellmaul-particle-location} to the location 1.5 blocks in front of attacker's head')

In previous versions it did (dev29 and back).

**Comment by whoshenry** [comment]
I fixed this by replacing the word blocks with meters.

**Comment by bensku** [comment]
It would make sense if both worked.

**Comment by Snow-Pyon** [comment]
This was tagged wrongly, it isn't an enhacement, it's an actual bug.

**Comment by TheBentoBox** [comment]
Yeah, blocks definitely used to work. This is a breaking 'change'/bug, not an improvement to be made.

**Comment by TheLimeGlass** [comment]
Parser conflicts with https://github.com/SkriptLang/Skript/blob/6524d69f1e8583f917ea18c9fe526ec6df66dbfc/src/main/java/ch/njol/skript/expressions/ExprBlocks.java#L58 and https://github.com/SkriptLang/Skript/blob/6524d69f1e8583f917ea18c9fe526ec6df66dbfc/src/main/java/ch/njol/skript/expressions/ExprDirection.java

**Comment by TPGamesNL** [comment]
Can't replicate, probably fixed at some point
