### ISSUE TITLE
Offhand item check on enderpearl and firework?

### ISSUE THREAD

**Issue by xion87** [SkriptLang/Skript#848]
Hi i am trying to block these items, it seem to block perfect when they are in main hand... but when they are in offhand it still can be used:
I am using this skript

on rightclick holding a firework rocket:
	cancel the event
	remove 1 of tool from tool

on rightclick holding a eye of ender:
	cancel the event
	remove 64 of tool from tool

**Comment by bensku** [comment]
What Skript version?

**Comment by xion87** [comment]
i am using the latest one on release of this github (dev31b) the server is 1.12.1

**Comment by Weefle** [comment]
Any error logs?

**Comment by xion87** [comment]
nope, basically these two items in offhand are not blocked

**Comment by Weefle** [comment]
There is no error on /sk reload?

**Comment by Weefle** [comment]
Oh, ok I see, bensku will look at it

**Comment by bensku** [comment]
Sounds familiar, there have been numerous issues with click events in past. Also with these items, but they were supposed to be fixed.

**Comment by xion87** [comment]
i got some errors on skript maybe is related
https://hastebin.com/izatifiduv.md

**Comment by xion87** [comment]
any news about it? i am blocking some items with skript and you can use items in offhand....

**Comment by TheBentoBox** [comment]
@xion87 Do you still encounter this issue?

**Comment by TheBentoBox** [comment]
No response and off-hand issues should probably all be taken to #51
