### ISSUE TITLE
Can't set entity's velocity to 0

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#849]
I used this code:
`set {_ball}'s velocity to 0`

{_ball} is an entity. Using this line of code causes the rest of the function or event not to execute.

Using Paper 1.12 and Skript dev31

**Comment by bensku** [comment]
You cannot set velocity (a vector) to scalar number. Does it give parse errors?

**Comment by jaylawl** [comment]
No parse errors at all! :)

Actually i just realized that i was trying to set a vector to a single number and came back here to admit the mistake. ^^

However, while on the topic, a shorthand for that, something like "stop entity" or "kill entity's velocity" (cant come up with a good phrasing rn) would be quite handy.

**Comment by bensku** [comment]
Stop entity... Not bad idea. But anyways, trying to use scalar as vector should give an error.

**Comment by Pikachu920** [comment]
```
stop %living entity%
```
already exists in some form, the velocity expression has a delete changer so you can do
```
delete velocity of player
```
or the way you were trying to do it in the first place:
```
set velocity of player to new Vector 0, 0, 0
```

**Comment by Syst3ms** [comment]
What is this last line of code ? I don't even know what you mixed the vector syntaxes with.
It's either
```
set velocity of player to velocity(0, 0, 0)
```
or either (using Skript-mirror)
```
set {_args::*} to 0, 0 and 0
set velocity of player to new (class "org.bukkit.util.Vector")(...{_args::*})
```
or 
```
import "org.bukkit.util.Vector"
set {_args::*} to 0, 0 and 0
set velocity of player to new {Vector}(...{_args::*})
```

**Comment by Blueyescat** [comment]
This doesn't happen for me on 2.2-dev37c, probably it was a conflict with some addons?

![image](https://user-images.githubusercontent.com/19474570/44749797-4e8b8300-ab1c-11e8-8762-e0c507635bb3.png)

**Comment by Matocolotoe** [comment]
> ```
> stop %living entity%
> ```
> already exists in some form, [the velocity expression has a delete changer](https://github.com/bensku/Skript/blob/10cd79a78b25c0c355353f3448c49c94bff5ddad/src/main/java/ch/njol/skript/expressions/ExprVelocity.java#L92-L94) so you can do
> 
> ```
> delete velocity of player
> ```
> or the way you were trying to do it in the first place:
> 
> ```
> set velocity of player to new Vector 0, 0, 0
> ```

This works

> What is this last line of code ? I don't even know what you mixed the vector syntaxes with.
> It's either
> 
> ```
> set velocity of player to velocity(0, 0, 0)
> ```
> or either (using Skript-mirror)
> 
> ```
> set {_args::*} to 0, 0 and 0
> set velocity of player to new (class "org.bukkit.util.Vector")(...{_args::*})
> ```
> or
> 
> ```
> import "org.bukkit.util.Vector"
> set {_args::*} to 0, 0 and 0
> set velocity of player to new {Vector}(...{_args::*})
> ```
> **EDIT :**
> 
> _looks at docs_
> 
> _facepalms_
> 
> The capitalization made it confusing though.

This does not work

**Comment by TheBentoBox** [comment]
Blue's test shows this hasn't been an issue for a while. A `stop entity` effect could still be nice I guess but it seems unnecessary when setting to a 0,0,0 vector or deleting velocity both work fine and are more accurate to what's actually being done.

If someone feels strongly about the `stop entity` effect feel free to reopen a new enhancement issue request for it.
