### ISSUE TITLE
[Suggestion] on any movement

### ISSUE THREAD

**Issue by jrbq** [SkriptLang/Skript#85]
On Skript 1.8, we had the "on any movement" event, and I would like to have it on your fork. Thanks.

**Comment by bensku** [comment]
What that event actually does? What about on move event?

**Comment by Pilvinen** [comment]
I think the point is being able to see the difference between "playing is moving" and "player is standing still" and possibly (?) to cancel movement.

**Comment by Jonni1** [comment]
^^

**Comment by itismejoey** [comment]
`on any move` was actually an WildSkript syntax that never made its way into Umbaska. I have already asked for it to be added.

**Comment by bensku** [comment]
Need help figuring a way to do this that doesn't kill performance.

**Comment by Nicofisi** [comment]
Making it optional and killing the performance for people who want it dead? Wellllllllllll

**Comment by Snow-Pyon** [comment]
@Nicofisi PaperSpigot actually has an event for this:
https://ci.destroystokyo.com/userContent/apidocs/com/destroystokyo/paper/event/player/PlayerJumpEvent.html
We can't implement it because it'd make Skript totally Paper dependent though.

**Comment by bensku** [comment]
We can, by checking if server is running Paper or not and not enabling it if it isn't.

**Comment by Nicofisi** [comment]
Oh and wait, I don't know how came we changed the topic here, this issue is about `on any movement`, the `on jump` issue is #444 ;)

**Comment by ItzCookies** [comment]
This seems to have been added

**Comment by Wealthyturtle** [comment]
Good catch, closing this since there's already a movement event, and I doubt we'll be adding a custom event that handles that + jumping...

**Comment by TPGamesNL** [comment]
The only event for movement is the [on move on](https://skriptlang.github.io/Skript/events.html#move_on) event, which is different from any movement.

**Comment by idchlife** [comment]
I want to check if player is underwater at any given moment to give it some effect and I suspect it's not quite possible without any movement event.

Well, besides writing ALL types of blocks with on move on which will be a disaster

**Comment by Pikachu920** [comment]
ins't there a swim event?

**Comment by HYPExMon5ter** [comment]
Sort of, https://helpch.at/docs/1.13.2/index.html?org/bukkit/event/entity/EntityToggleSwimEvent.html
