### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by fratik** [SkriptLang/Skript#850]
Hi, I can't get build to work, on both Windows and Linux. Sorry if this is a duplicate.

```
:processTestResources NO-SOURCE
:testClasses
:test

ch.njol.skript.aliases.AliasesTest > testNames FAILED
    org.junit.ComparisonFailure at AliasesTest.java:95

ch.njol.skript.localization.NounTest > testNormalizePluralMarkers FAILED
    org.junit.ComparisonFailure at NounTest.java:65

ch.njol.skript.localization.NounTest > testGetPlural FAILED
    org.junit.ComparisonFailure at NounTest.java:47

10 tests completed, 3 failed, 1 skipped
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///root/Skript/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 58.057 secs
```

**Comment by bensku** [comment]
Known issue with Windows, but with Linux... Hmm, could help to find where it goes wrong. What's your distro? Java version (also, Oracle or OpenJDK)? System locale? Kernel version? Desktop environment? Minecraft version?

Jar should be there anyway, but giving those details would still be helpful to get this fixed.

**Comment by Fratik** [comment]
Distro: Debian 8
Java: 1.8.0_131 (Oracle)
Locale: (locale command returned `LANG=` and `LANGUAGE=`) (but everything is in English)
Kernel: 2.6.32-48-pve
Enviroment: ??? (ssh, this is on VPS)
Minecraft version: no Minecraft in Skript folder

**Comment by bensku** [comment]
Ok, so no X server/client installed, likely...

Is your locale UTF8 or some form of ISO 8859? Aka does the locale state .utf8 somewhere?

And oops, I asked MC version by mistake. It has nothing to do with this.

**Comment by Fratik** [comment]
yep, no X server/client. 

nope, I think that's why I have wrong symbols..

**Comment by bensku** [comment]
Hmm, confirms my theory of what causes this. Not how to fix, but at least I have an idea where to start.

**Comment by Fratik** [comment]
I can suggest a fix, create something like Jenkins, something that will build Skript automatically.. you will specify config, that will work and we will just download the jar file at Jenkins site.. that's only a suggestion 😉

**Comment by bensku** [comment]
I tried having CI to check commits, PRs and so on. It couldn't properly compile with ECJ and Skript failed to build.

I guess I could use my own web server.

**Comment by bensku** [comment]
Build server done. Take a look at https://github.com/bensku/skript-build
