### ISSUE TITLE
Suggestion: "loop-number" expression for all types of loops

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#862]
As far as i can tell so far, the only instance where you're able to use the "loop-number" expression is in a loop like this:
```
loop 1337 times:
    broadcast "%loop-number%"
```
However this expression would also be useful in the other loop-types. It would prevent us all from having to do this all over our scripts:
```
loop {_some_var::*}:
    add 1 to {_n}
    broadcast {_n}
    if {_n} >= 1337:
        exit loop
```
Cheers for reading! :)

**Comment by Pikachu920** [comment]
That appears in any loop where there is a number. %number% times is actually an expression that returns 1 to the number e.g. 1 to 6 for 6 times

**Comment by WheezyGold7931** [comment]
%loop-index% is a number of times it has been looped

**Comment by TheBentoBox** [comment]
No it's not @WheezyGold7931, the `loop-index` is the index of the current item being looped in the list. By default list indices are labelled as numbers in sequential order (1, 2, 3, ...) but if you specify your own index then that's not at all the case (e.g. `set {cooldown::%player's UUID%} to now` would result in the player's UUID for the `loop-index`).

**Comment by JeepSmash** [comment]
@WheezyGold7931 was almost correct with his statement as it only pertains to 
`loop %number% times:`
when using this loop type the loop-value not the loop-index will hold the number of times the loop has run.  If something like this was to be added to other loop types such as looping lists or entities or blocks i would recommend adding in a  loop-count expression that would hold the number of times any loop has cycled so it doesn't get confusing as to what loop-value is really holding
