### ISSUE TITLE
tree types broken?

### ISSUE THREAD

**Issue by Wqrld** [SkriptLang/Skript#865]
`on grow of big regular tree:
  cancel event`
also stops crops from growing? is this a bug or is there a workaround?

**Comment by bensku** [comment]
Hmm, very interesting. Sounds like a bug.

**Comment by aycgit** [comment]
what block would event-block return ? the bottom block where the sapling was?

**Comment by TheBentoBox** [comment]
`ripe wheat` is the name of fully grown wheat with the default aliases.

**Comment by aycgit** [comment]
uhmmm, is it just me or did the event-block workaround just break
