### ISSUE TITLE
About Vectors Syntaxes

### ISSUE THREAD

**Issue by Blueyescat** [SkriptLang/Skript#867]
### 1
Uses ``['s]`` instead of ``'[s]``:
```autohotkey
%location%['s] vector
%vector%['s] (vector|standard|normal) length
%vector%['s] squared length
```
### 2
```autohotkey
vector (yaw|pitch) of %vector%
```
should be
```autohotkey
[the] vector (yaw|pitch) of %vector%
%vector%'[s] vector (yaw|pitch)
```
**Or add vector type support to [Yaw / Pitch](https://bensku.github.io/Skript/expressions.html#ExprYawPitch) syntax?**
### 3
```autohotkey
(x|y|z) of %vector%
```
should be
```autohotkey
[the] (x|y|z) of %vector%
%vector%'[s] (x|y|z)
```
**Or add vector type support to [Coordinate](https://bensku.github.io/Skript/expressions.html#ExprCoordinate) syntax?**
### 4
```autohotkey
[new] vector from yaw %number% and pitch %number%
```
This syntax should be
```autohotkey
[new] vector [(from|with)] [yaw] %number% and [pitch] %number%
```
Same with [Cylindrical Shape](https://bensku.github.io/Skript/expressions.html#ExprVectorCylindrical) syntax.

### 5
```autohotkey
%vector% [to location] [in] %world%
location (from|of) %vector% [(from|in)] %world%
%vector% [to location] [in] %world% with yaw %number% and pitch %number%
location (from|of) %.vector% [(in|from)] %world% with yaw %number% and pitch %number%
```
``{_v} "world"`` :thinking: It should be:
```autohotkey
%vector%('[s]| to) location [(from|in|of) [the] %world%] [(from|with) yaw %number% and pitch %number%]

location (from|of) %vector% [(from|in|of) [the] %world%] [(from|with) yaw %number% and pitch %number%]
```

### 6
```autohotkey
angle between %vector% and %vector%
```
should be
```autohotkey
angle (between|of) [vectors] %vector% and %vector%
```

### 7
```autohotkey
normalize %vector%
%vector% normalized
```
should be
```autohotkey
normalize[d] %vector%
%vector% normalize[d]
```

**Comment by bensku** [comment]
1. Valid point, thought not that big deal.
2. Yeah, merging expressions would be a good idea.
3. Again, merging would be a good idea.
4. I'd rather change cylidrical shape syntax than this...
5. Merging expressions to produce overly complex patterns is usually bad idea. It can add unpredictable slowdowns to parsing.
6. Something like this would be good.
7. Normalized should be made mandatory. "normalize" would imply that it modifies the input data.

**Comment by Sashie** [comment]
`Uses ['s] instead of '[s]` wouldnt moving the `'` out of the optional make it required all the time and mess everything up

**Comment by Blueyescat** [comment]
@Sashie with that you can use `location's vector` or `location' vector`, already other Skript syntaxes uses this way. I think it is better for English...

**Comment by Snow-Pyon** [comment]
It isn't, `location' vector` doesn't make any sense unless it's plural which is when it would make sense to use something such as `locations' vector`.

**Comment by TheBentoBox** [comment]
Blue's improvements are now merged and in the latest release.
