### ISSUE TITLE
variables in block expression

### ISSUE THREAD

**Issue by DevonPalma** [SkriptLang/Skript#910]
Currently you have to specify north, south, etc. when using the block expression, however I would like to see something as follows

> right click on cobble-stone:
>   set {_temp} to north
>   set block 1 {_temp} of event-block to event-block

Granted having it for this script is pointless it would help greatly when picking a random direction, and help reduce the size of some of my current scripts.

**Comment by Pikachu920** [comment]
IIRC you can do random direction via something like `random direction out of north, west, south and east` inline whatever you're trying to use directions in

**Comment by TheBentoBox** [comment]
Yeah, or just something like `random element out of (north, south, east and west)`. I think in your example the second line could become `set {_temp} to north, south, east or west` and it would choose one randomly.

But if that doesn't work for one reason or another then it's probably a bug that should be fixed.

**Comment by Demonkid1112** [comment]
neither of the ladder options have worked, I've tried a few different things but none seem to work except independently going like
if {_direction} is north:
    set block 1 north of event block
if {_direction} is south:
    set block 1 south of event block 
etc....
so most likely it is a bug then

**Comment by TheBentoBox** [comment]
Not sure if this is still an issue and regardless it is very old.
