### ISSUE TITLE
Replace 'is burning' with 'fire ticks of %entity%'

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#923]
Hey!
This is just a small suggestion to make burn expression more useful.

Basically it would change `%entities% (is|are) (burning|ignited|on fire)` to `%entities%'s (burn time|fire ticks)` or `(burn time|fire ticks) of %entities%`. It would return a number, so if it's `0` it means the entity is not burning.

It'd also allow you to set and add more fire ticks, so you can make someone burn for a longer time.

Thanks once again.

**Comment by Pikachu920** [comment]
Why would it be replaced? `%entities% (is|are) (burning|ignited|on fire)` isn't even a expression anyway, it's a condition. If anything, this should be a new expression.

**Comment by TrademarkTM** [comment]
Fire ticks would do the same thing as `is burning`, as you can check if it's `0`, so I don't think both would be needed.

**Comment by Pikachu920** [comment]
Well for one `is burning` would be needed for backwards compatibility, and it increases the englishness of skript. While you can do direct comparisons like that, for example `if damage cause is fire`, skript also lets you do things like `if the damage was caused by fire`

**Comment by TheBentoBox** [comment]
I agree it shouldn't replace the old expression, but still a good idea.
