### ISSUE TITLE
Error with color code(s) turns colored.

### ISSUE THREAD

**Issue by slothiful** [SkriptLang/Skript#928]
**Hello,**

Whenever Skript encounters an error involving text with color codes, the last color code in the text will cause the rest of the error message to be formatted accordingly. Instead, the formatting should stop in the quotation marks but doesn't. 
Example:
![alt text](https://puu.sh/xYmN5/48a6fa53ab.png "Example of Issue")
After the quotation marks, _&7_ is the continued format of the error message.

**Thank you,**
**Slothiful**

**Comment by WheezyGold7931** [comment]
@Slothiful can I get the code you are using for this...

**Comment by xXAndrew28Xx** [comment]
I can only reproduce this if I use `§` in place of ampersands to do color formatting.

**Comment by TPGamesNL** [comment]
Can confirm:
```
command /test:
	trigger:
		this gives error §e test abc
```
![image](https://user-images.githubusercontent.com/29547183/122031552-1b9b0280-cdcf-11eb-872a-2d2f3c6c3d76.png)

**Comment by TPGamesNL** [comment]
Closing, as there is no way to escape colour codes AFAIK (and this doesn't happen for '&', only with '§')
