### ISSUE TITLE
Improve the usefulness of the parsing expression

### ISSUE THREAD

**Issue by Pikachu920** [SkriptLang/Skript#952]
my idea is this:
```
set {_e} to "survival" parsed as an object
set player's gamemode to {_e}
```
parsing as an object would parse as any type possible (excluding string). It would probably make sense for a
```
type[s] of %objects%
%object%'[s] type[s]
```
to exist along with this

**Comment by TheBentoBox** [comment]
I'm not sure if this is very feasible, usually parsing something as a generic 'object' actually treats it as the base object class, and actually figuring out what type it would need to be would probably require looping through available types and attempting a parse until one is successful, which I can't imagine would be very performant.

That being said, I don't really know what I'm talking about realistically speaking, so I'll leave it up to Bensku if this seems realistic.

**Comment by xXAndrew28Xx** [comment]
I agree, this doesn't seem realistic. Even if we did loop through all types, there would a lot of the times be more than one type that returns non-null for the same string and the first one to return might not be what you're looking for.
