### ISSUE TITLE
Code colors in the chat

### ISSUE THREAD

**Issue by Vulc4n** [SkriptLang/Skript#961]
Hello, With Skript, when a player stands out for example "&c" in the chat, the message is transformed with the color code that goes with it. Would it be possible to have an option to deactivate that ? I would like that colors are not available in the chat, for example: when the player wants to write "&cTest" it marks "&cTest" and not "test". (with the red color)
I would not want that the players can have access to colors. :/

My skript version : 2.2-dev28c

**Comment by TheBentoBox** [comment]
If you do `uncolored %text%` it will not use the formatting codes, but they will still be parsed so for example `send uncolored "&cTest"` will still send as just "Test" without the &c, but it will be colored white. Does that work for your needs or do you really need it to still display the code?

**Comment by Vulc4n** [comment]
In fact, I would want that the players cannot utilser colors in the chat, here is my code of chat:

`				# CONSOLE LOG
				message "&7%player% : %message%" to console
				# CHAT
				loop all players:
					if message contains "%loop-player%":
						add loop-player to {_mentions::*}
					else:
						add loop-player to {_autres::*}
				if {_mentions::*} or {_autres::*} are set:
					set {_message} to "%message%"
					loop {_mentions::*}:
						replace all "%loop-value%" with "&5&l%loop-value%&f" in {_message}
						message "&7%player%&r : &f%{_message}%" to loop-value
						show an action bar from "&eVous avez été mentionné par &7%player% &e!" to loop-value
						play sound "BLOCK_NOTE_PLING" to loop-value with volume 1 and pitch 2
						set {_message} to "%message%"
					loop {_autres::*}:
						message "&7%player%&r : &f%message%" to loop-value`

When I use the "uncolored message " that makes for me really discolor all the message, there is no way means to discolor only the message ? (Except the mentions)

**Comment by TheBentoBox** [comment]
You don't have to do it on the whole message, you can do it to any piece of text, so in your case you'd probably update the line where you set `{_message}` to:
```
set {_message} to "%uncolored message%"
```

**Comment by Vulc4n** [comment]
Here we are, I used as said higher " %uncolored message% ", but it does not still work :/

My code: http://prntscr.com/h6dhve

Screen (When i put "&cTest" in the chat) : http://prntscr.com/h6di89

**Comment by Blueyescat** [comment]
dev28 is broken... especially about chat https://github.com/bensku/Skript/releases

**Comment by TheBentoBox** [comment]
Good catch, I missed that this was dev28. You should try updating.

**Comment by Vulc4n** [comment]
I took the last version of skript, and always the same problem  :/

**Comment by Blueyescat** [comment]
@Vulc4n Please send your full ``on chat`` event with https://hastebin.com.

**Comment by Vulc4n** [comment]
/ver : https://prnt.sc/h7gf1d
/ver Skript : https://prnt.sc/h7gffb

Chat event : https://hastebin.com/sixuqipolo.sql

**Comment by Blueyescat** [comment]
Weird... Looks like it should work. Remove the on chat event fully and try this to see what happens:
```vb
on chat:
    cancel event
    loop all players:
        message "&7%player%&r : &f%uncolored message%" to loop-value
```

**Comment by Vulc4n** [comment]
Same, http://prntscr.com/h81lzy :/

**Comment by Snow-Pyon** [comment]
Can someone test this and verify if this is still an issue?

**Comment by TheLimeGlass** [comment]
It still exists but it's not really an issue, it's more of an issue with how it's inputted, because 
```
on chat:
	cancel event
	loop all players:
		set {_message} to "&7%player%&r : &f%uncolored message%"
		message {_message} to loop-player
```
This will provide the exact string that was being looked for in this issue.

For anyone confused on the issue: Skript will parse %uncoloured message% normally like `&a&lStuff` but when it gets inserted into the message effect, it gets re-parsed again and the colours return.

I think this is just a user error and should be closed as there is no clean way to fix this without testing if the uncoloured expression is contained within the given string expression.

**Comment by Wealthyturtle** [comment]
Fixed with the recent chat updates if I'm not wrong...

Using
```
on chat:
	cancel event
	loop all players:
		set {_message} to "&7%player%&r : &f%uncolored message%"
		message {_message} to loop-player
```

And typing in 
![image](https://user-images.githubusercontent.com/19924575/62590314-7e333580-b8fe-11e9-8a80-4503037669a4.png)

Will yield
![image](https://user-images.githubusercontent.com/19924575/62590327-87bc9d80-b8fe-11e9-9cdd-42a0e2da7e7f.png)

Showing that ```%uncolored message%``` is now fixed.
Tested using Skript 2.4-beta5 
@TheBentoBox close?
