### ISSUE TITLE
X of expression trying to convert entity to item type

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#987]
Running latest skript version on paper spigot 1.12.2 (latest dev build). Console error:

https://hastebin.com/tonemulasa.md

**Comment by TheBentoBox** [comment]
Out of curiosity, what's the code that's causing this error to appear?

**Comment by bloggy** [comment]
Mh I don't know. The skript causing it is not mentioned. I have dozens of skripts.

**Comment by TheBentoBox** [comment]
Ah alright fair enough. Seems like an issue with the default converter running when it shouldn't.

**Comment by kimidu1609** [comment]
I have also this problem

**Comment by jaylawl** [comment]
@bloggy it seems to be your script containing this line: "drop {_amount} of loop-value at {_loc}"

**Comment by Nicofisi** [comment]
The link is dead

**Comment by Snow-Pyon** [comment]
Is this still an issue? Also, as said above the link to the stack trace is dead, if you could possibly reupload it (better if you use another paste service since hastebin deletes links older than 30 days).

**Comment by Nicofisi** [comment]
Well now it isn't dead but is still on hastebin lol

**Comment by Snow-Pyon** [comment]
Okay, after digging a bit found out that this is an issue of the X of Item expression trying to convert an Entity to an ItemType when used in loops. The cause of this might be deeper though since it only happens in loops (so, probably issues with the loop-value expression).

**Comment by TheLimeGlass** [comment]
Not just due to loops and not really at all what happened. Yes it was being casted to the wrong object, but it was an issue within the converter.

**Comment by TheBentoBox** [comment]
IIRC this was fixed recently and is a very old issue regardless.
