### ISSUE TITLE
Teleporting ignores yaw + pitch?

### ISSUE THREAD

**Issue by StealWonders** [SkriptLang/Skript#996]
I have locations saved into variables which used to teleport players to the location I set (with north south location respected) Now in dev32b it just teleports player looking at the north with is rather annoying... Having to turn around every time when you spawn (get teleported) is just plain stupid.

**Comment by bensku** [comment]
What version were you using before?

**Comment by Louis-D** [comment]
2.2-dev29

**Comment by bensku** [comment]
Oh. That is weird... Same server version, right?

**Comment by Louis-D** [comment]
I'm not sure - I might have updated to 1.12.2

**Comment by TheBentoBox** [comment]
Can anyone else reproduce this with dev32 on 1.12.2?

**Comment by Pikachu920** [comment]
i can reproduce it, although its on 1.8:
1![](https://cdn.discordapp.com/attachments/135877399391764480/401480862044127262/unknown.png)

**Comment by GrimEpp** [comment]
This is not an error on the latest build of Skript 1.12.2

**Comment by Pikachu920** [comment]
@GrimEpp can you provide a screenshot? i reproduced it on dev32d.

**Comment by jaylawl** [comment]
having this issue also. generally setting the yaw of an entity doesn't work for me, but won't throw any bugs either. for instance:

```set victim's yaw to attacker's yaw```

nothing

**Comment by Snow-Pyon** [comment]
@jaylawl that's a expected behaviour, as you have to teleport the entity to actually change it.

**Comment by TheBentoBox** [comment]
If setting the yaw/pitch of an entity isn't supposed to work then it should be changed so that setters for it don't parse. It should be disallowed & give a warning saying to use teleportation instead. Unless I'm misunderstanding something.

**Comment by Snow-Pyon** [comment]
Or, I could make it so when you set the yaw/pitch of an entity it also teleports the entity, either way works.

**Comment by TheBentoBox** [comment]
That works too!

**Comment by Pikachu920** [comment]
shouldn't this be bug not enhancement? this used to work

**Comment by Blueyescat** [comment]
Weird, but this happens only when the yaw or pitch is 0, 90, 180, 270 or 360. For example 360.01 will work and it will be 360 in the game.

**Comment by Wealthyturtle** [comment]
Adding priority for this issue since it still occurs on Skript 2.4 / Spigot 1.14.4 2 years after the issue was made...

**Comment by bluelhf** [comment]
According to my testing, even using values like 0.00001 will work, but not 0.

**Comment by Wealthyturtle** [comment]
Yes, as Blueyescat pointed out: Related to https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffTeleport.java#L105

**Comment by bluelhf** [comment]
Could maybe make the effect something like `teleport %entities% (to|%direction%) %location% [directionally]`, ignore direction unless `directionally` is present?

**Comment by StealWonders** [comment]
It's 2020 now and still not fixed. :-(

**Comment by APickledWalrus** [comment]
I’ll open a PR soon to fix this issue.

**Comment by PrecedingxD** [comment]
Works for me if you set the pitch and yaw to -0.01 and -0.01.
